[FIX] web_editor: prevent TB when dropping a non-dropable block
odoo/odoo pull request #100054
Opened 2022-09-13 08:33 UTC by Guillaume-gdi

Before this commit when you grabbed a block that couldn't be dropped and dropped it back into the block list, a traceback was displayed. This commit makes it possible to not have this traceback anymore. Steps to reproduce the bug fixed by this commit:
- Install website
- Go to the home page of the website.
- Remove all the blocks of the page (remove also the footer)
- Grab an inner block (which is in red because it cannot be dropped)
- Drop this same block where you grabbed it (in the block list)

=> a traceback is displayed

task-2948895
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-13 08:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100054).

2022-09-20 11:41 UTC, qsm-odoo requested changes
As seen in live demo: playing a bit quickly still seems buggy

2022-09-21 08:27 UTC, Guillaume-gdi commented
@qsm-odoo the bug you showed me is now resolved.

2022-11-17 14:11 UTC, Guillaume-gdi commented
It seems that there is [another PR](https://github.com/odoo/odoo/pull/76900) which will fix the same issue. So I close this one :+1:

2022-11-17 14:11 UTC, closed without merging