[FIX] product_margin: product margin use partial/reversed payment
odoo/odoo pull request #100022
Opened 2022-09-12 12:56 UTC by robinengels

Current behavior:
Partial and reversed payments were not taken into account for the product margin calculation.

Steps to reproduce:
1. Create a product with a common avco setup.
2. Go to purchase 1 unit at 10 dollars.
3. Upon confirming the invoice your cost is updated in the product margin report.
4. Create a partial payment on the bill. This creates issues as the product margin report is looking for paid or open not partially paid so it won't show up in the cost calculation.
5. Once the bill is fully paid then it shows up in the cost section of the product margin report again as its payment status moves to Paid.
6. Create a sales order for the unit at 100 dollars.
7. Invoice for the full amount then cancel it by creating a full credit note to put the original invoice in reversed status. This will have only the credit note show up in the turnover calculation as it is in paid status while the original invoice doesn't have a paid or open status so it isn't taken into account.

Note: I decided to add a new option that uses all the payments because adding partial/reversed payment to any other option seemed like a bad idea.

opw-2887240
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-15 17:00 UTC, tsb-odoo commented on addons/product_margin/models/product_product.py
> +            ('all', 'All')
No need for this. 'all'

2022-12-15 17:01 UTC, tsb-odoo commented
@robinengels 

Add : 
"reversed" payment status among "paid", "open & paid", "draft, open & paid".
"partially paid" payment status among "open & paid" + "draft, open & paid". 

Do not add the "all" selection.

2022-12-22 08:56 UTC, robinengels commented
@epictete can you have a look at this

2022-12-22 10:42 UTC, qdp-odoo commented
I'm ok with reversed but I've a doubt about partial payments: I fear that considerating them would just fuck up the margin since you'd be basically counting partially the income for whole units. I think it's also a behavior change that should be avoided in stable

@tsb-odoo

2022-12-23 10:39 UTC, qdp-odoo requested changes
seeing things like that just makes me wanna hit you hard. Next time, test your code, maybe?
:angry:

2022-12-23 10:39 UTC, qdp-odoo commented on addons/product_margin/models/product_product.py
> +            payment_states = ('not_paid', 'in_payment', 'paid', 'reversed', 'partially_paid')
```suggestion
            payment_states = ('not_paid', 'in_payment', 'paid', 'reversed', 'partial')
```

2022-12-23 10:39 UTC, qdp-odoo commented on addons/product_margin/models/product_product.py
> +            payment_states = ('not_paid', 'in_payment', 'paid', 'reversed', 'partially_paid')
```suggestion
            payment_states = ('not_paid', 'in_payment', 'paid', 'reversed', 'partial')
```

2022-12-28 09:40 UTC, robinengels commented
@epictete @qdp-odoo

2023-01-03 08:48 UTC, qdp-odoo commented
@robodoo r+

2023-01-03 09:56 UTC, closed without merging