[FIX] hr_timesheet: employee is filled taking user's company instead of task's one
odoo/odoo pull request #100194
Opened 2022-09-15 01:40 UTC by deivislaya

Steps :

- Install project, timesheet and employee.
- Create 2 company and an employee for you user in 1 of them.
- Create a new project and task.
- Switch to the one without employee.
- Register a timesheet.

Issue:
The timesheet has no employee or if both companies have employees, the
taken one will be the one from current company instead of task's company

Fix:

Sets the user, according to the company indicated in the task.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-15 01:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100194).

2022-09-15 04:23 UTC, luisg123v requested changes
Hi  @deivislaya,

I'll leave some recommendations:

- Lowercase first letter of PR's short description in title. It could seem nitpick, but it's part of the guidelines, all Odoo commits use it and they've already pointed that out on one of my PRs
- I think example may be simplified a bit using two companies. If both companies have employees, the taken one will be the one from current company instead of task's company
- If the above point is applicable, title could be:
`employee is filled taking user's company instead of task's one`
- Describe steps using a list, i.e. adding `-` at the beginning (like I'm doing on this comment)

Regards,

2022-09-15 14:56 UTC, deivislaya commented
Hi @luisg123v 

Change applied. Thanks

Regards

2022-09-15 20:31 UTC, luisg123v requested changes
I think these steps are inverted:

- Switch to the one without employee.
- Create a new project and task.

Because the project and task will be in the company without employee, and we need task to be on a different company than the user's company.

2022-09-15 20:43 UTC, deivislaya commented
It's true, change applied

Thanks !!!

2022-09-15 21:00 UTC, luisg123v approved these changes
LGTM :+1: 

Hi @IT-Ideas,

Could you review, please?

Regards,

2022-09-15 21:01 UTC, luisg123v commented
CC @hugho-ad

2022-09-16 08:26 UTC, IT-Ideas commented
Hello @auon-odoo,
Can you have a look at this as you already treated similar issues?
I'll review after that.
Thanks

2022-09-16 09:22 UTC, auon-odoo commented
Hello,
Thanks for your work!
Actually, this issue is already taken care of in master : https://github.com/odoo/odoo/pull/93823
And it is going to be back-ported to 14.0 : https://github.com/odoo/odoo/pull/99188
We will use that version because we prefer it to be mananged in the create, plus it is a little more complex.
Have a nice one!

2024-04-16 08:58 UTC, C3POdoo commented
Dear @deivislaya,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 08:58 UTC, closed without merging