[IMP] Payment: remove duplicate chatter message
odoo/odoo pull request #100162
Opened 2022-09-14 13:18 UTC by vava-odoo

The confirmation message for the sale order appeared twice in the chatter: first with the confirmation and second with the posted payment. The second message is now rephrased in order to avoid any confusion for the user (no double payment).

task-2965158

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-14 13:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100162).

2022-09-21 15:08 UTC, chevalierv requested changes
Good works on this but I think we can go little further :rocket:  

Since we don't log anything about the transaction anymore, I think that we should do this in another method. That way, we will be able to remove the second call to `_log_received_message ` in `payment.transaction` (line 846, odoo/addons/payment/models/payment_transaction.py), by adding an override of `_finalize_post_processing` in `account_payment`. Then we'll just need to log the payment information thanks to `_log_message_on_linked_documents`, after calling `super()`.

What do you think about that?

PS: `payment` doesn't takes upper case in your commit message :zany_face:

2022-09-23 15:12 UTC, chevalierv approved these changes
LGTM :+1:

2022-09-23 15:12 UTC, chevalierv commented on addons/account_payment/models/payment_transaction.py
> +    #=== BUSINESS METHODS - FINALIZE ===#
```suggestion
    #=== BUSINESS METHODS - POST-PROCESSING ===#
```

2022-09-26 08:08 UTC, AntoineVDV approved these changes

2022-09-26 08:08 UTC, AntoineVDV commented on addons/account_payment/models/payment_transaction.py
> -        if self.state == 'done' and self.payment_id:
This condition should be re-integrated, should a transaction not have a payment.

2022-09-26 08:37 UTC, AntoineVDV approved these changes

2022-10-03 10:11 UTC, AntoineVDV commented
@robodoo r+

2022-10-03 12:19 UTC, closed without merging