[ADD] website_sale_subscription: Initial commit
odoo/odoo pull request #100210
Opened 2022-09-15 08:41 UTC by fdamhaut

Change test in website_sale to accommodate with website_sale_subscription

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-15 08:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100210).

2022-10-10 07:58 UTC, Williambraecky requested changes
I asked for the exception for the new module in stable.

There is also one function on which I had left a TODO some time ago related to the merge of this module; could you check `def _is_reorder_allowed` on `sale.order.line`?
Thanks

2022-10-10 07:58 UTC, Williambraecky commented on addons/website_sale/tests/test_website_sale_visitor.py
> +            self.assertNotIn(product, res_products)
Why is this change actually necessary? does `_prepare_values` now depend on `request`?

2022-10-10 12:44 UTC, fdamhaut commented
> I asked for the exception for the new module in stable.
> 
> There is also one function on which I had left a TODO some time ago related to the merge of this module; could you check `def _is_reorder_allowed` on `sale.order.line`? Thanks

I just added the condition to both website_sale_subscription and website_sale_rental, do I need to add smth else ?

2022-10-10 12:47 UTC, Williambraecky commented
> > I asked for the exception for the new module in stable.
> > There is also one function on which I had left a TODO some time ago related to the merge of this module; could you check `def _is_reorder_allowed` on `sale.order.line`? Thanks
> 
> I just added the condition to both website_sale_subscription and website_sale_rental, do I need to add smth else ?

No it's exactly what needed to be done, thanks :)

2022-10-10 15:01 UTC, Williambraecky approved these changes
Just need to change the commit message

2022-10-11 12:12 UTC, Williambraecky approved these changes
Thanks for your work!
robodoo r+

2022-10-11 14:12 UTC, closed without merging