[WIP] mail, *: convert all compute method into inline field function
odoo/odoo pull request #100313
Opened 2022-09-15 17:08 UTC by alexkuhn

Task-2985304

2022-09-15 17:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100313).

2022-09-16 13:02 UTC, phenix-factory commented on addons/im_livechat/static/src/models/chatbot.js
> +             * Helper method that checks if the script should be ended or not.
This is not really a helper ? Maybe just call it compute instead of helper ?

2022-09-20 12:28 UTC, oomsveta requested changes

2022-09-20 12:28 UTC, oomsveta commented on addons/sms/static/src/models/message_view.js
> +         compute() {
extra leading space to be deleted

2022-09-20 12:28 UTC, oomsveta commented on addons/snailmail/static/src/models/popover_view.js
> +         compute() {
extra leading space to be deleted

2022-09-21 09:21 UTC, alexkuhn commented
Retarget to 16.0: https://github.com/odoo/odoo/pull/100667

2022-09-21 09:21 UTC, closed without merging