[FIX] hr_skill_slides: log course notifications on correct chatter
odoo/odoo pull request #100649
Opened 2022-09-21 07:54 UTC by robcoekaerts

Since https://github.com/odoo/odoo/pull/94876 every call to _action_add_member (or _remove_membership) in hr_skill_slides is wrongly logged on the chatter of the calling employee. With this commit, it is now logged on the affected employee.

The method is now also supported to be used in batch.

task-2980912

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-21 07:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100649).

2022-09-26 09:54 UTC, phwa-odoo commented on addons/hr_skills_slides/models/slide_channel.py
> +            employee = None
```suggestion
            employee = self.env['hr.employee']
```

2022-09-27 06:18 UTC, kba-odoo requested changes

2022-09-27 06:18 UTC, kba-odoo commented on addons/hr_skills_slides/models/slide_channel.py
> +                        break
You can simplify with a filtered() here, and bonus, you only sudo() the record once this way :-D

```suggestion
                employee = partner.user_ids.sudo().filtered(lambda u: e.employee_id and not p.company_id or u.employee_id.company_id == partner.company_id)
```

2022-09-28 13:05 UTC, kba-odoo commented
robodoo r+

2022-09-28 16:35 UTC, closed without merging