[FIX] base, snailmail: Fix custom paperformat missing on reports
odoo/odoo pull request #100715
Opened 2022-09-21 13:11 UTC by clesgow

Since changes on env mixup on the PDF calls, the PDF are generated with an empty self, which means paperformat set directly in the xml record cannot be accessed anymore.

Part of task-2985735

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-21 13:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100715).

2022-09-22 13:24 UTC, mart-e requested changes
The issue is that `self.paperformat_id` is not working because it's not a record. So the proper fix is to make sure this actually returns a value, not put something before to avoid evaluating this code.

2022-09-22 13:44 UTC, clesgow commented
The problem is that at this point `self` is an empty record. So `self.paperformat_id` returns an empty record too.
Problem is that I don't know much on how all calls up to that function works.
But since every calls to `_render_qweb_pdf()` have been changed from `<report>._render_qweb_pdf()` to `self.env['ir.actions.report']._render_qweb_pdf()`, we don't have non-empty record anymore.

2022-10-05 08:25 UTC, clesgow commented
@mart-e Could you have a look at the changes ?

2022-10-06 07:57 UTC, closed without merging