[FIX] calendar: wrong timezone in sms template
odoo/odoo pull request #100733
Opened 2022-09-21 14:28 UTC by momegahed

Issue :
- `compute_display_time` uses `_get_display_time` which always uses Odoobot (cron user) timezone

Fix:
- use the timezone of the event organizer instead by using `get_display_time_tz`. this also avoids editing the xml templates in stable.

OPW-2991624

2022-09-21 14:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/100733).

2022-09-23 10:07 UTC, nle-odoo reviewed
so checking usage of display_time, we are using it in:

1. view `invitation_page_anonymous` rendered in route `/calendar/meeting/view` where the timezone is set in context to the current attendee (found by using the access_token) => here the change doesn't seem good

2. in `sms.template().sms_template_data_calendar_reminder` sent by an calendar.alarm => here the change seems ok if the even is always sent by OdooBot and we have the same message for all attendees (so it's the best we can do, other that saying "change the timezone of OdooBot)

3. `calendar.event()._do_sms_reminder` => seems similar as previous point (and would be sent by OdooBot) so this seems as good

4. when doing `calendar.alarm_manager().do_notif_reminder` => it seems to me that it's for an internal notification in Odoo (for someone that is logged in) so it was correct for the current user before the change and now is using the timezone of the event organizer.

5. in error message of calendar.event()._ensure_attendees_have_email with microsoft_calendar synchronization => doesn't seem good but not very bad

it seems that this is an improvement, but it is also causing some issue (especially when viewing the event as an attendee and now not having the timezone of the attendee)

2022-10-24 09:05 UTC, nle-odoo approved these changes
looks better to me

as a side note, the alternative done somewhere else is I think to have `object.get_display_time_tz(object.partner_id.tz)` inside the sms.template:

https://github.com/odoo/odoo/blob/35a596dbbc4e2e55461bf7e5e8ae12873249d4af/addons/calendar_sms/data/sms_data.xml#L7

note: this should be rebased and retargetted to 14.0

2022-10-25 09:35 UTC, tde-banana-odoo commented
Seems more for @arj-odoo :)

2022-10-26 07:13 UTC, arj-odoo requested changes
Hello, thank you for your contribution. I am skeptical about this change in an old stable version. Normally we don't accept changes that do not fix big issues in these old stable versions.

The description is the issue seems not correct: 
> compute_display_time uses _get_display_time which always uses Odoobot (cron user) timezone

compute_display_time is called each time the display time is needed. It may be called in overrides. Being called by OdooBot is not requirement. 

I fear this change would have side effects (thanks @nle-odoo for referencing them), especially for other people relying on the display_time current behavior. Moreover, this change do not bring any tests which is an issue for any change in stable. 

If the issue only occurs when do_notif_reminder is called, another solution is to replace the following statement 

```py
message = meeting.display_time
```
by
```py
message = meeting.get_display_time_tz(tz=timezone)
```
But once again, if nothing is really broken (E.G. a traceback occurs), I would not risk introducing regressions in these olds stable branches. You should target 14.0 but a lot of TZ issues had been fixed in 14.0 so it is possible that this change is not relevant anymore.

2022-11-03 10:53 UTC, momegahed commented
> Hello, thank you for your contribution. I am skeptical about this change in an old stable version. Normally we don't accept changes that do not fix big issues in these old stable versions.
> 
> The description is the issue seems not correct:
> 
> > compute_display_time uses _get_display_time which always uses Odoobot (cron user) timezone
> 
> compute_display_time is called each time the display time is needed. It may be called in overrides. Being called by OdooBot is not requirement.
> 
> I fear this change would have side effects (thanks @nle-odoo for referencing them), especially for other people relying on the display_time current behavior. Moreover, this change do not bring any tests which is an issue for any change in stable.
> 
> If the issue only occurs when do_notif_reminder is called, another solution is to replace the following statement
> 
> ```python
> message = meeting.display_time
> ```
> 
> by
> 
> ```python
> message = meeting.get_display_time_tz(tz=timezone)
> ```
> 
> But once again, if nothing is really broken (E.G. a traceback occurs), I would not risk introducing regressions in these olds stable branches. You should target 14.0 but a lot of TZ issues had been fixed in 14.0 so it is possible that this change is not relevant anymore.

the problem actually happens in `_do_sms_reminder` the edits in `do_notif_reminder` is to negate the effects on it listed by nle.

but you are right, I think it is better to leave `compute_display_time` as is and just edit the SMS XML template to account for the time zone

2022-11-03 11:54 UTC, arj-odoo approved these changes

2022-11-07 08:58 UTC, kitan191 commented
@robodoo delegate+

2022-11-07 09:06 UTC, momegahed commented
@robodoo r+

2022-11-07 10:46 UTC, closed without merging