[IMP] website, *: make is_view_active a model method
odoo/odoo pull request #102231
Opened 2022-10-05 10:20 UTC by bso-odoo

*: website_blog, website_membership, website_sale

Since [1] `is_view_active` relies on `viewref` which is a model method that uses the `website` specified in the context.

This commit turns `is_view_active` to a model method too, to avoid that its callers think the `website` on which it is called is the one used.

[1]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b

task-2687506

2022-10-05 10:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102231).

2022-10-11 00:56 UTC, rdeodoo requested changes
> Since [1] `is_view_active` relies on `viewref` which is a model method
that uses the `website` specified in the context.

Not really true, it was also relying indirectly on viewref before, and was already an "api.model" even if not specified?

> This commit turns `is_view_active` to a model method too, to avoid that
its callers think the `website` on which it is called is the one used.

Is that a thing (Python? Odoo?)? I have never paid attention to that and always called api.model method from a record(set) if I had one available instead of going through `self.env['xx']`. I don't think I have ever seen any remark about that on a PR either.

It seems like everywhere in Odoo that's not something you can rely on, there is plenty of api.model method being called on record(set).

I am fine with adding the decorator, but I'd not change every caller, unless I am missing something, let me know :)

2022-10-11 09:03 UTC, bso-odoo commented
@rdeodoo Kept only the `@api.model`.

2022-10-11 16:27 UTC, rdeodoo approved these changes
@robodoo r+
Thank you. I guess we should do a pass one day and clean all that, there is probably other cases like that.

2022-10-11 17:29 UTC, closed without merging