[FIX] website_sale_renting: shop rental datepicker
odoo/odoo pull request #102477
Opened 2022-10-06 14:42 UTC by alpa-odoo

This PR adds a mechanism so that a datepicker can be empty by default. 

taskid: 3000852

2022-10-06 14:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102477).

2022-10-06 14:51 UTC, alpa-odoo commented on addons/web/static/lib/daterangepicker/daterangepicker.js
> +            this.inputEmpty = false;
We know at this point that the input is not empty anymore.

2022-10-24 11:23 UTC, alpa-odoo commented on addons/web/static/lib/daterangepicker/daterangepicker.js
> +        if (typeof options.inputEmpty === 'boolean')
Not 100% sure if that's clean code, maybe we can put it as one object that contains both the information for if the input should be empty and its placeholder 🤔

2022-10-28 12:48 UTC, Williambraecky requested changes
We can not modify daterangepicker as the file comes from a library, I'm sure we can make it work without needing those changes.

2022-10-28 13:17 UTC, closed without merging