[FIX] web_editor, *: remove some inner content dropzones in Carousel
odoo/odoo pull request #102696
Opened 2022-10-07 16:16 UTC by sobo-odoo

*: website

When dragging inner contents, dropzones appear in the Carousel snippet, allowing to drop them directly in the element with the `row` class, where it should not be the case. This is due to the `content` class present on these elements and to the drop-in rule for inner contents that allows them to be dropped in elements having this class.

This commit fixes this issue:
- in stable: as the XML files cannot be modified, the drop-in rule is patched in JS to exclude the elements having both the `content` and `row` classes.

- in 16.0 and higher: it removes the `content` classes from the rows of the Carousel snippet. It also removes this class from the drop-in rule, as only Carousel was concerned by it.

task-3011192

2022-10-07 16:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102696).

2022-10-07 17:19 UTC, sobo-odoo commented
@qsm-odoo it's ready for review :) 
There is also a PR in design-themes that removes the `content` classes from a theme that extends Carousel. I made it start at 14.0 so it is linked to this PR but as for this one, it's only from 16.0 that these class changes have to be applied (so there is only a comment for stable versions).

2022-11-30 16:56 UTC, rdeodoo commented
@robodoo delegate=@bvr-odoo

2022-12-01 13:10 UTC, bvr-odoo requested changes

2022-12-05 12:52 UTC, sobo-odoo commented
@bvr-odoo I made the changes :)

2022-12-22 14:50 UTC, bvr-odoo commented
@robodoo r+

2022-12-22 15:00 UTC, robodoo commented
@sobo-odoo @bvr-odoo linked pull request(s) odoo/design-themes#603 not ready. Linked PRs are not staged until all of them are ready.

2022-12-22 17:40 UTC, closed without merging

2022-12-27 10:59 UTC, qsm-odoo commented
@sobo-odoo @bvr-odoo Something to be done here ? :point_up: If something to adapt in master and nothing to do in the other versions:
- `@fw-bot r+` on the 16.0 version (community + themes) (this will merge 16.0 PR and below)
- Push force the master versions and `robodoo r+`

Thanks :)