[IMP] website, *: use generic code for "edit event menu"
odoo/odoo pull request #102728
Opened 2022-10-07 19:47 UTC by xO-Tx

*: website_event

The `website_event.menu_edit_menu` menuitem was added on 'website_event' module to the 'custom menus'
registry so it can be displayed by the `website_custom_menus` service if the event page has menus to edit.

The goal of this commit is to move this code to 'website' by using a generic `custom_menu_edit_menu`
menuitem that will get a name value depending on the targeted content menu (`dataset.menu_name`).

task-2973149

2022-10-07 19:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102728).

2022-10-10 13:43 UTC, qsm-odoo requested changes
Seems cool, just one small thing to fix then I'll test and merge :+1:

2022-10-10 13:43 UTC, qsm-odoo commented on addons/website/static/src/services/website_custom_menus.js
> +                                name: `Edit ${menu[0]}`,
You should translate this (use sprintf, the translate term should be "Edit %S")

2022-10-10 19:09 UTC, qsm-odoo approved these changes
Nice work :+1: 

I just push-forced to add some precisions in the commit message (especially the fact that this is a fix as it would be a regression to release 16.0 without this).

@robodoo r+

2022-10-10 21:10 UTC, robodoo commented
@xO-Tx @qsm-odoo staging failed: ci/runbot on f94ce0f87082d4cc8ce0dde58be9c20f67d69816 (view more at https://runbot.odoo.com/runbot/build/20158598)

2022-10-10 23:26 UTC, rdeodoo commented
@robodoo retry

2022-10-11 02:44 UTC, robodoo commented
@xO-Tx @qsm-odoo staging failed: timed out (>120 minutes)

2022-10-11 05:54 UTC, d-fence commented
robodoo retry

2022-10-11 07:11 UTC, closed without merging