[DRAFT] [FIX] 16.0 dark mode fixes morm
odoo/odoo pull request #102937
Opened 2022-10-10 15:08 UTC by morm-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-10-10 15:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102937).

2022-10-10 15:15 UTC, stefanorigano requested changes
I know that is still DRAFT, but since you asked for a review:

- PR/Commits description: missing task-id
- Commits tiles: `Webclient` is not a module
- Commits tiles:  `Web` (module name) should be lowercase
- [FIX] commit descriptions: missing general information on the issue you're solving and how
- [IMP] commit descriptions: missing general information on what are you improving and **why**  (improvements were not supposed to be part of this task, but I'd like to understand..)

2022-10-11 15:41 UTC, stefanorigano approved these changes
ok @morm-odoo , thanks.
You can remove the draft state from both PRs (comm/ent).

@adr-odoo , @pparidans , ready for tech. review, thanks !

2022-10-12 09:31 UTC, pparidans approved these changes
LGTM
@robodoo r+ rebase-ff

2022-10-12 09:32 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-10-12 13:02 UTC, closed without merging