[FIX] test_assetsbundle: don't pregenerate assets outside test mode
odoo/odoo pull request #102994
Opened 2022-10-10 23:00 UTC by rdeodoo

Commit [1] and [2] introduced an assets pregeneration to speed up the testing suite on runbot.

It seems like it was chosen to always pregenerate the assets when a module was installed/upgraded. This was done in the `test_assetsbundle` module to only impact the tests flows, but it was not correct as it was not only impacting the tests flows but also regular runbot usage. Indeed, any `all` runbot (the default one) will have that module installed.
It means that any module operation through regular flow in those DB will trigger the assets pregeneration.

One of the problem is then that during a theme switch through the website builder (or configurator), assets would be pregenerated, adding ~40 seconds to the processing time.
Since that theme install was already taking ~30 seconds on `all` runbot, it sometimes now total over 60 seconds, triggering the `CPU Time Limit`. You can find some benchmark and metrics on this commit PR.

Obviously, that's not fine because runbot, despite being our testing tool/platform, is also one of our main demo tool.
That's especially true around the OXP period, where people are recording video on it but will also use it to show demo to the customers.

Finally, there is no reason to not limit this assets pregeneration to the test mode anyway.

Note that sometimes, the theme install is failing and responding with a 502 error after a long time, this is yet unsure if this was the cause but it was during this investigation that this commit fix was found. It is probably the cause though.

[1]: https://github.com/odoo/odoo/commit/c764c38d7caf300dce7509e87d2bd268eee0161d
[2]: https://github.com/odoo/odoo/commit/d47cf37b688117d6b2514b9b620787aa66312c61

2022-10-10 23:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102994).

2022-10-10 23:25 UTC, rdeodoo commented
@Xavier-Do Could this one be reviewed and/or merged in priority tomorrow?
We will really need this fixed for the OXP. Let me know if you think of anything wrong or a better approach.
I added a complete breakdown of what is happening in all 3 flows in the PR description.

cc @qsm-odoo

2022-10-11 07:44 UTC, Xavier-Do commented
The idea of pregenerating it only when test_assetsbundle is installed is a way to check that we are in a test environment. But we need to create them during the install in all cases because runbot installs the template then run the tests. 
I don't know what would be a proper fix we can discuss about that but this one is not the right solution I think. It is adding even more complexity on top of a already complex logic, breaking one of the reason why this is so complex. To make it work we should add a test-tag to generate the templates during the install and in this case the test_assetsbundle part is completely useless since they are also pregenerated before post install.

2022-10-11 07:47 UTC, Xavier-Do requested changes
I think this would work

2022-10-11 07:47 UTC, Xavier-Do commented on odoo/addons/test_assetsbundle/models/ir_qweb.py
> +        if config['test_enable'] and registry.updated_modules and not registry.ready:
```suggestion
        if config['init'] and registry.updated_modules and not registry.ready:
```

2022-10-11 10:53 UTC, Xavier-Do approved these changes
LGTM

2022-10-11 13:18 UTC, rdeodoo commented
@robodoo r+ thanks

2022-10-11 15:30 UTC, closed without merging