[FIX] 16.0 dark mode fixes
odoo/odoo pull request #102948
Opened 2022-10-10 15:41 UTC by anso-odoo

Fix minor visual bug for dark-mode.

task-3012970

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-10-10 15:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/102948).

2022-10-11 13:38 UTC, anso-odoo commented
@stefanorigano can you check this PR and : https://github.com/odoo/enterprise/pull/32675 
ty

2022-10-11 15:10 UTC, stefanorigano requested changes
Commit conventions:
- When using `*` in the title you have to list the affected module in the description. I'd suggest to use it  when you apply changes on a lot of modules, in your case seems not necessary.

- missing `task-id`in several commits

- You the commit description to say "why" you did things not "what" you did (indeed we can clearly see your changes in the commit itself). Someone not familiar with dark-mode may wonder why the class change `bg-white -> bg-view` is needed

2022-10-11 15:37 UTC, stefanorigano requested changes

2023-06-16 15:23 UTC, rdeodoo commented
Cleaning a bit the `rd-website` codeowner review requests.
Since this one is "old" + conflict + task set as deployed, closing it. Feel free to re-open if I missed something.

2023-06-16 15:23 UTC, closed without merging