[IMP] account_edi_ubl_cii: add support for A-NZ Peppol BIS3
odoo/odoo pull request #103056
Opened 2022-10-11 12:13 UTC by JulienVR

Add edi_format "A-NZ BIS3" used in Australia and New-Zealand. This format is derived from OpenPeppol's BIS3 invoice.

task-2994014

2022-10-11 12:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/103056).

2022-12-05 09:22 UTC, vin-odoo reviewed
Pourquoi 1.0.7 et pas 1.0.8?

2022-12-05 09:26 UTC, JulienVR commented
> Pourquoi 1.0.7 et pas 1.0.8?

J'ai pris le plus à jour en me basant sur la liste: https://peppol.helger.com/public, je ne vois pas le 1.0.8 (ni sur ecosio d'ailleurs) :) Tu as trouvé le 1.0.8 où ?

2022-12-05 09:27 UTC, vin-odoo commented
> > Pourquoi 1.0.7 et pas 1.0.8?
> 
> J'ai pris le plus à jour en me basant sur la liste: https://peppol.helger.com/public, je ne vois pas le 1.0.8 (ni sur ecosio d'ailleurs) :) Tu as trouvé le 1.0.8 où ?

https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Specifications

2022-12-05 09:30 UTC, JulienVR commented
> > > Pourquoi 1.0.7 et pas 1.0.8?
> > 
> > 
> > J'ai pris le plus à jour en me basant sur la liste: https://peppol.helger.com/public, je ne vois pas le 1.0.8 (ni sur ecosio d'ailleurs) :) Tu as trouvé le 1.0.8 où ?
> 
> https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Specifications

Le nom de version spécifié est juste utilisé comme identifiant pour utiliser l'API de Philip Helger pour faire des tests, et ne sert à rien d'autre. Si je mets 1.0.8, ça ne fonctionnera pas.

2022-12-13 09:34 UTC, vin-odoo requested changes

2022-12-13 09:34 UTC, vin-odoo commented on addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_au.py
> +            list_line_subtotals=[1782, 1000, -100], currency_id=self.currency_data['currency'].id)
```suggestion
        self._assert_imported_invoice_from_file(
            subfolder='tests/test_files/from_odoo',
            filename='a_nz_out_invoice.xml', 
            amount_total=2950.2, 
            amount_tax=268.2,
            list_line_subtotals=[1782, 1000, -100], 
            currency_id=self.currency_data['currency'].id
        )
```

2022-12-13 09:49 UTC, vin-odoo approved these changes
@robodoo r+

2022-12-13 13:56 UTC, closed without merging