[IMP] website: test that no COW view is created on save without change
odoo/odoo pull request #103057
Opened 2022-10-11 12:18 UTC by bso-odoo

This commit adds a test that verifies that no copy-on-write view is
created if a website page is saved without any change within its
content while there is a change in the footer.

task-2078924

2022-10-11 12:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/103057).

2022-10-19 10:04 UTC, bso-odoo commented
@rdeodoo I forgot to ping you on this one. It is one of the tests of the "Strengthen our testing suite" task.

2022-11-03 13:51 UTC, rdeodoo requested changes
Could you see my review point + be sure that if you locally cherry-pick the [fixing commit](https://github.com/odoo/odoo/commit/6714a327368d6fac608149ce098be3e00e725e7c) and checkout `HEAD~1` so you don't have it, your test will fail, while it won't with the fix?

2022-11-03 13:51 UTC, rdeodoo commented on addons/website/static/tests/tours/website_edit_save.js
> +}]);
It's obviously not that simple.
If you read the [task](https://www.odoo.com/web#id=2567752&action=4043&model=project.task&view_type=form&cids=1&menu_id=4720) I attached to this "test request" + the related [commit](https://github.com/odoo/odoo/commit/6714a327368d6fac608149ce098be3e00e725e7c), it seems to only be about:
- drag & dropping some snippets
- on views containing the "oe_structure_id" "hack"
which would then COW the base view + create an inherit view for the oe_structure_id while it should not have cowed the base view

2024-04-16 09:15 UTC, C3POdoo commented
Dear @bso-odoo,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2026-02-18 13:13 UTC, robodoo commented
@bso-odoo the target branch '15.0' has been disabled, you may want to close this PR.

2026-02-18 15:04 UTC, closed without merging