[IMP] Mandatory checkout - change label
odoo/odoo pull request #103072
Opened 2022-10-11 13:44 UTC by alpa-odoo

This commit changes the label of the checkout button if the user is not signed in and the option is mandatory.

`task: 2991670`

2022-10-24 07:43 UTC, Williambraecky requested changes
Minor detail

2022-10-24 07:43 UTC, Williambraecky commented on addons/website_sale/views/templates.xml
> +                                            <a class="btn btn-primary float-end" t-attf-href="{{redirect_url}}">
Missing `role="button"`

2022-10-24 07:43 UTC, Williambraecky commented on addons/website_sale/views/templates.xml
> +                    <a t-if="website_sale_order and website_sale_order.website_order_line"
Missing `role="button"`

2022-10-26 09:31 UTC, Williambraecky requested changes
Code is OK; the commit title does not follow the guidelines.
It should be something along the lines of: `[IMP] website_sale: change mandatory checkout labels`

2022-10-26 09:53 UTC, alpa-odoo commented
> Code is OK; the commit title does not follow the guidelines. It should be something along the lines of: `[IMP] website_sale: change mandatory checkout labels`

Fixed sorry !

2022-10-27 08:47 UTC, Williambraecky approved these changes
Thanks for your work
robodoo r+

2022-10-27 08:49 UTC, robodoo commented
@Williambraecky you may want to rebuild or fix this PR as it has failed CI.

2022-10-27 10:39 UTC, closed without merging