[FIX] base_vat: keep leading zeros on San Marino tax id
odoo/odoo pull request #103545
Opened 2022-10-19 14:02 UTC by ushyme

### Steps to reproduce
* install the *VAT Number Validation `(base_vat)`* and Contacts module.
* Create a new contact from San Marino and set their Tax Id to SM05426
* Save the contact

You should see that the leading zeros have been removed on the Tax Id (here, SM05426 became SM05426)

opw-3007722

2022-10-19 14:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/103545).

2022-10-19 14:09 UTC, nle-odoo reviewed
this seems a little random to use Switzerland ('ch') vat parsing for san marino ('sm')

side note: in san marino parsing, it seems they are going out of their way to remove leading zero:

> The COE is a tax identification number of up to 5-digits used in San Marino.
Leading zeroes are commonly dropped.
> 
>     """Convert the number to the minimal representation. This strips
    surrounding whitespace and separation dash."""
(from https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/sm/coe.py)

2022-10-19 14:13 UTC, ushyme commented
Yes, you're right, that is a mistake.
Thanks!

2022-10-19 14:24 UTC, nle-odoo approved these changes
looks good to me

reading the ticket, the removing of zero is alright, it's just in italian electronic invoice that this is causing an issue  (it should probably be said in the commit; because removing the zero seems expected otherwise, eg. in this government website they say to remove the zero: https://registroimprese.cc.sm/)

2022-10-19 14:29 UTC, jco-odoo requested changes
I can not agree on this because we checked further and it is only for the e-invoicing itself, so we no need to do the change only when we send it in the XML.  Which is a bit weird, because we should try that setup to send invoices from a San Marino company.

2022-10-20 12:57 UTC, nle-odoo approved these changes

2022-10-21 13:03 UTC, jco-odoo commented
Still doubts as San Marino might require a different TipoDocumento in the file as well.  @lordkrandel

2022-11-11 13:53 UTC, matteoopenf commented
Hi, 
in my opinion this is not the correct way to fix the problem.
The problem is in fase of creation of the partner not in the moment  of export e-invoice.
if you fix in phase of export, when you create the partner the problem persist

2022-11-11 14:02 UTC, jco-odoo commented
@ushyme Talking about it with @TonyMasciI we should keep more what you did first, because the problem is never on export (because it will be the 009999999), but on import.  And then it would be weird to only strip the 0 for San Marino for the import.  

If we add this to base_vat/res_partner.py we will have the possibility to put the zero or not: 
```
    def format_vat_sm(self, vat):
        stdnum_vat_format = getattr(stdnum.util.get_cc_module('sm', 'vat'), 'compact', None)
        return stdnum_vat_format('SM' + vat)[2:]
```

2022-11-15 08:56 UTC, ushyme commented
@jco-odoo thanks for the answer. I made the changes.

2022-11-15 08:57 UTC, jco-odoo commented
@lordkrandel

2022-11-15 11:51 UTC, lordkrandel commented
> @lordkrandel

If from the import it's always like `SM01234` then LGTM.
Otherwise we'll end up with duplicated partners, one with the zero and one without.
(The specs fix the digits number at 5 anyway so we should be ok)

2022-11-15 11:56 UTC, matteoopenf commented
> SM01234

the San Marino Vat have always this format it's not possibile arrive SM1234

2022-11-15 11:56 UTC, matteoopenf approved these changes
LGTM

2022-11-15 11:58 UTC, lordkrandel approved these changes

2022-11-15 16:16 UTC, TonyMasciI approved these changes

2022-11-15 16:18 UTC, TonyMasciI commented
> @TonyMasciI Ok for you as well?

Yes.

2022-11-15 19:06 UTC, jco-odoo commented
@robodoo r+

2022-11-15 19:44 UTC, closed without merging