[FIX] web_editor: wrap user-facing strings in _t()
odoo/odoo pull request #103791
Opened 2022-10-21 13:22 UTC by cammarosano

Description of the issue/feature this PR addresses:
Some of the user-facing strings related to Powerbox commands (name, description and groupName) were not wrapped in a call to _t().

The issue was spotted on PR #103757, by this [comment](https://github.com/odoo/odoo/pull/103757/commits/6d61247957d0c0bdb69ea59277cb21116d105365#r1001691436).

2022-10-21 13:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/103791).

2022-10-21 13:27 UTC, qsm-odoo requested changes
You also have to adapt the .pot file by making a new export via the UI (Settings -> Translations -> Export (po, website)) (and in general I commit only what is relevant to the PR)

2022-10-21 13:51 UTC, dmo-odoo commented
> Note that I was curious to see on the PR (where I made the remark about the missing `_t()`) why was only the website commands missing it, not the web_editor ones.
> 
> So I had a look. For tracking purpose:
> 
> Those commands were introduced with [1](https://github.com/odoo/odoo/commit/4600086e7a2831664cc104a143e1014870874427#diff-6bf09b72528757673aa5f73488708a44ba1af178d51205248e9bb8429d3e6584R1229) in Odoo codebase without the `_t()`. Other commands were added with [2](https://github.com/odoo/odoo/commit/ef145ea7dc249460e1b057493e79795f3006e73f) still without `_t()`. Some of those commands did receive a fix to add the missing `_t()` with [3](https://github.com/odoo/odoo/commit/90f0df32ac7bba0151ea37c440c9136890cea7fb), which did not fix all of the commands (it fixed those in OdooEditor.js but no in wysiwys.js). Note: Those not fixed got moved from `web_editor` to `website` later with [4](https://github.com/odoo/odoo/commit/c1ff3260a8e09ba4af3ad44138d44d4457c7c689).

Great investigation. For the record, the appointment ones in enterprise are also missing a `_t` so it's not just website... :p But yeah in anycase I'm the one who missed all those so, my bad.

2022-10-21 13:58 UTC, rdeodoo commented
> in any case I'm the one who missed all those while reviewing so, my bad.

No worries, I wasn't blaming anyone but was just blaming the git history to figure what happened (as always on every single PR :p). Thought I would share it since I did it.

2022-10-24 08:04 UTC, dmo-odoo commented
@robodoo r+

2022-10-24 11:35 UTC, closed without merging