[FIX] l10n_fi: "brutto" taxes not included in price
odoo/odoo pull request #103725
Opened 2022-10-21 07:39 UTC by peso-odoo

Steps to reproduce:

  - Install finish Finnish Localization(l10n_fi) module,Accounting
  - Verify accounting taxes (brutto: 24%|14%|10%) price_include checkbox is deselected

Issue:

  Price_include field set to False

Cause:

  Field in locale template view not defined, model defaults to False

Solution:

  Field defined in tax template data and set to True for locale

opw-2992952

2022-10-21 07:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/103725).

2022-10-21 07:42 UTC, peso-odoo commented
corrected as per comment: https://github.com/odoo/odoo/pull/103586#pullrequestreview-1149193846
decided to close PR and open a new one

2022-10-27 08:26 UTC, vin-odoo requested changes
Data's seems ok just one small typo to fix

2022-10-27 08:26 UTC, vin-odoo commented on addons/l10n_fi/data/account_tax_template_data.xml
> +        <field name="name">14% EU </field>
```suggestion
        <field name="name">14% EU</field>
```
There is a space too much here :smile:

2022-10-27 08:29 UTC, vin-odoo approved these changes
@robodoo r+

2022-10-27 11:43 UTC, closed without merging