[FIX] account: disable tax deletion
odoo/odoo pull request #104617
Opened 2022-10-31 12:50 UTC by proose

When in a Journal Entry, if we try to delete a generated tax line, an error will be raised, obligating the user to discard current changes, without any other alternative.

Now the tax line cannot manually be deleted (the user should remove the tax on the baseline instead): an error still pops up but the line stays, and previous changes are kept.

2022-10-31 12:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104617).

2022-10-31 12:53 UTC, proose commented on addons/account/models/account_move.py
> +            self.line_ids = self._origin.line_ids
I am unaware of any existing action allowing to delete several lines at the same time in the Journal Entry form view, but, if there is, and if we want to keep the tax lines and go on with the other changes, this line could be replaced by `self.line_ids += (previous_tax_lines - current_tax_lines)`

2022-10-31 12:57 UTC, proose commented
@william-andre is this how you saw it done ? It's not great as the function will constantly be called for every changes, but I don't know if it is custom-widget worthy otherwise...

2022-11-15 13:18 UTC, proose commented
@william-andre Up :grin:

2022-12-01 14:12 UTC, william-andre requested changes
Actually, setting `delete="0"` in the view makes more sense.
You will have exactly the same issue with receivable/payable lines, and the other lines wont update it you remove a product line...

2022-12-06 16:05 UTC, proose commented
> Actually, setting `delete="0"` in the view makes more sense.

Isn't that a bit too drastic ? It means you can't delete any line, right ?

2022-12-06 16:17 UTC, william-andre commented
This should only be the case for invoices-like documents though.
Break down by `display_type`:
* `product`: you can delete them from the invoice line tab
* `cogs`: they are created when posting and deleted when resetting to draft, you can never delete them manually anyways
* `tax`: it looks like you can delete them but you have an error -> the point of this PR
* `rounding`: you can delete without an error them but they will come back
* `payment_term`: it looks like you can delete them but you have an error -> the point of this PR
* `line_section`: you can delete them from the invoice line tab
* `line_note`: you can delete them from the invoice line tab
* `epd`: you can delete without an error them but they will come back

2022-12-16 12:05 UTC, proose commented
@william-andre it is changed :)

2022-12-16 12:38 UTC, william-andre commented on addons/account/views/account_move_views.xml
> +                                    <tree editable="bottom" string="Journal Items" decoration-muted="display_type in ('line_section', 'line_note')" default_order="sequence, id" delete="0">
But with this you can't delete lines from journal entries?
It should be dependent on the `move_type`

2023-02-08 19:44 UTC, qdp-odoo commented
task cancelled internally

2023-02-08 19:44 UTC, closed without merging