[FIX] account: round sale orders' taxlines
odoo/odoo pull request #104748
Opened 2022-11-02 14:23 UTC by ushyme

### Steps to reproduce
* create two 17% sales taxes. We'll call those taxes `17a` and `17b`.
* set rounding method to global
* set product price's decimal accuracy to 5
* create a SO with the following 2 lines:
  * Quantity = `1`, Price = `50.4`, Taxes = `17a`
  * Quantity = `1`, Price = `47.208`, Taxes = `17b`
* note that the total tax amount on the SO is `16.59`
* confirm and invoice the SO.

You should see that the total tax amount on the invoice is `16.60`. The invoice and SO should have the same tax amount.

opw-3014755

2022-11-02 14:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104748).

2022-11-02 19:20 UTC, fmdl commented
linked PR : https://github.com/odoo/odoo/pull/95425

2022-11-03 13:59 UTC, nboulif requested changes
I would say LGTM since it make sense, BUT I don't think it's the right fix, here is why:
I noticed a weird behavior: I was testing your test in previous version and I had also the same error... however, I noticed that the test is running multiple times due to a wrong import and so, by doing a common class to be imported (without the tests), the error disappears... here is a PR for 15.0 of what I meant but still not understanding in why it affects the test : https://github.com/odoo/odoo/pull/104855 .

2022-11-07 12:51 UTC, nboulif approved these changes
@ushyme So, for the inherited test class, it is intended since want to run the tests of `TestTaxTotals` with different configurations (like you explained to me :wink: )
Then, regarding your fix, LGTM :+1: 

Hello @odoo/rd-accounting , may I ask for a confirmation/review? Thanks in advance!

2022-11-07 13:50 UTC, Levizar commented
I don't really understand why it should be 16.60 instead of 16.59

If I do the math:
(50.4 + 47.208) * 0.17 = 16.59336

Shouldn't 16.59336 be rounded to 16.59 instead of 16.60 ?

2022-11-07 14:31 UTC, ushyme commented
Since `17a` and `17b` are two different taxes, they will become two different `move.line` in the invoice, which means they will be rounded individually.

This means the actual calculation is:
`round(50.4 * 0.17) + round(47.208 * 0.17) = round(8.02536) + round(8.568) = 8.03 + 8.57 =16.60`

2022-11-07 14:58 UTC, william-andre approved these changes
@robodoo r+

2022-11-07 16:06 UTC, closed without merging

2022-11-14 10:04 UTC, Levizar commented
> * set rounding method to global

What you say is true with round per line but in the PR description and in the commit message, I read `set rounding method to global`

2022-11-16 11:27 UTC, ushyme commented
Hello @Levizar, sorry for the late reply.

This example is a bit confusing because we have 2 lines with one tax each. Because of this, it looks like the tax is being rounded per line.

But actually, the rounding is applied with a **per tax** grouping. So if we had more SO lines with `17a` and `17b` taxes, all `17a` tax amounts would be summed and then rounded (same with `17b` taxes).

ie. Tatal tax would be:  `round(sum_of_all_17a_tax_amounts) + round(sum_of_all_17b_tax_amounts)`

2022-11-16 11:41 UTC, Levizar commented
@ushyme Ok, thx, it makes sense now