[FIX] account: bank journal not showing as payment option when unvailable
odoo/odoo pull request #104821
Opened 2022-11-03 11:45 UTC by Ephoniz

Steps to reproduce:

- Go to Journals > Bank journal > Remove all Incoming Payments
- Try to pay for an invoice
- The Bank journal will still appear

Issue:

Bank journal should not be an option if it doesn't have Incoming Payments.

Solution:

We need to add the proper filter for journals in the default_domain in order to not get the bank journal when it is not available.

This bug affects all versions from 15.2 until 16.

opw-3027346

2022-11-03 11:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104821).

2022-11-03 12:16 UTC, nboulif requested changes
Hello @Ephoniz , LGTM since the domain is set on the field `"[('id', 'in', available_journal_ids)]"` and it's a non-stored compute field, it seems logic that must also restrict the domain in the compute method.

Just a note: I think the fix should also be applied here: 
https://github.com/odoo/odoo/blob/7ed533de576bfe847b8c0edc3d1fc01de59db731/addons/account/wizard/account_payment_register.py#L329-L332

2022-11-03 20:03 UTC, nboulif approved these changes

2022-11-22 16:12 UTC, Ephoniz commented
@lordkrandel

2022-11-22 16:30 UTC, lordkrandel commented
I'll look into it tomorrow! :D

2022-11-23 15:51 UTC, lordkrandel commented
Hummm... apart from the fact that I tried to wake up the build and it didn't work.
Nvm, I tried it on Enterprise and LGTM. 👍🏻

2022-11-23 15:51 UTC, lordkrandel approved these changes

2022-11-24 14:15 UTC, Ephoniz commented
Hi @lordkrandel thanks for the review :) If its good do you mind to "r+" ? Thankss!

2022-11-24 14:50 UTC, lordkrandel commented
Hi @Ephoniz , I cannot `r+`, I'm just a "pre-reviewer" but I just asked in the channel for someone else to come and help.

2022-11-24 15:07 UTC, william-andre approved these changes
@robodoo r+

2022-11-24 16:17 UTC, closed without merging