[FIX] web: fix modal-open class deleted when not needed
odoo/odoo pull request #104846
Opened 2022-11-03 13:26 UTC by bvr-odoo

Steps to reproduce the bug:

    - In website (edit mode), drag and drop a popup onto the page.
    - Add snippets in the popup to make a vertical scrollbar appears.
    - Click on the background image option of any of these snippets to
    open the media dialog.
    - Close the media dialog.
    - Bug => the vertical scrollbar disapears.

This is due to the 'modal-open' class which is removed from the 'body' when you close the media dialog when it should remain.

task-3047815

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-03 13:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104846).

2022-11-30 14:51 UTC, qsm-odoo commented
@robodoo delegate=@sobo-odoo

2022-12-22 16:07 UTC, sobo-odoo requested changes
I just have a comment, otherwise it is working well :slightly_smiling_face:

2022-12-23 10:43 UTC, bvr-odoo commented on addons/web/static/src/js/core/dialog.js
> +        const modals = $('.modal[role="dialog"]').filter(':visible');
Indeed, your suggestion seems to make sense. The problem is this ">" which prevents targeting modals that are not direct children of the ".body" (like the popup snippet). In this case, the most consistent is to simply remove this ">".

2022-12-23 12:13 UTC, sobo-odoo requested changes
Some changes to make in the commit message:
- the line ending by "remain if there are still" has more than 72 chars
- "But in Website editor modals" -> But in the Website editor, modals
- direct "child" -> direct "children"
- ".body" -> remove the '.' (since body is not a class)
- didn't -> did not

Otherwise it is good :wink:

2022-12-23 12:17 UTC, bvr-odoo commented
> Some changes to make in the commit message:
> 
> * the line ending by "remain if there are still" has more than 72 chars
> * "But in Website editor modals" -> But in the Website editor, modals
> * direct "child" -> direct "children"
> * ".body" -> remove the '.' (since body is not a class)
> * didn't -> did not
> 
> Otherwise it is good wink

ok done :+1:

2022-12-23 12:41 UTC, sobo-odoo approved these changes

2022-12-23 14:46 UTC, sobo-odoo commented
@robodoo r+
@fw-bot up to 14.0

2022-12-23 14:47 UTC, robodoo commented
I'm sorry, @sobo-odoo. I'm afraid I can't do that.

2022-12-23 15:02 UTC, sobo-odoo commented
@fw-bot ignore
@robodoo  r+

2022-12-23 15:03 UTC, robodoo commented
I'm sorry, @sobo-odoo. I'm afraid I can't do that.

2022-12-23 15:03 UTC, qsm-odoo commented
@fw-bot ignore

2022-12-23 15:05 UTC, sobo-odoo commented
@robodoo r+

2022-12-23 15:05 UTC, robodoo commented
I'm sorry, @sobo-odoo. I'm afraid I can't do that.

2022-12-23 15:06 UTC, qsm-odoo commented
@robodoo delegate=@sobo-odoo

2022-12-23 15:07 UTC, sobo-odoo commented
@robodoo r+

2022-12-23 15:49 UTC, closed without merging