[IMP] payment: function to build confirmation dialog allowing overrides
odoo/odoo pull request #104883
Opened 2022-11-03 14:53 UTC by vava-odoo

The confirmation dialog to delete a token from a portal user is the same whatever the linked records. This part of the code is now moved to a separate function `_buildConfirmationDialog` in order to allow overrides of the method in particular cases (e.g. Subscriptions).

task-3048269

2022-11-03 14:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104883).

2022-11-04 09:22 UTC, Demesmaeker reviewed
:duck:

2022-11-04 09:22 UTC, Demesmaeker commented on addons/payment/static/src/js/manage_form.js
> +        _buildConfirmationDialog: function (linkedRecordsInfo, onClick) {
So, apparently, JS methods are in alphabetical order and not logical order =D

2022-11-04 11:07 UTC, chevalierv requested changes

2022-11-04 11:07 UTC, chevalierv commented on addons/payment/static/src/js/manage_form.js
> +            let diag = new Dialog(this, {
No needs to create a new variable for that ^^
```suggestion
            return new Dialog(this, {
```

2022-11-04 13:18 UTC, chevalierv approved these changes

2022-11-04 13:24 UTC, Demesmaeker approved these changes

2022-11-04 16:23 UTC, AntoineVDV approved these changes
@robodoo delegate+

2022-11-06 11:04 UTC, vava-odoo commented
@robodoo r+

2022-11-06 11:52 UTC, closed without merging