[FIX] sale_mrp: avoid failing average price test
odoo/odoo pull request #104959
Opened 2022-11-04 06:51 UTC by tdecaluwe

The `test_kit_cost_calculation` test added in this [commit] will fail if the `sale_margin` module is not installed. This happens because an assertion in the test uses the `purchase_price` field defined in the `sale_margin` module.

As the test is testing the average costing method on kit products, it does not actually need this field. The average cost can simply be checked on the product itself.

opw-3041718

[commit]: https://github.com/odoo/odoo/commit/ea9fdac32111e4747453dee1e336b34e934cbc4d

2022-11-04 06:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104959).

2022-11-04 11:15 UTC, DjamelTouati requested changes
Hello @tdecaluwe ,
The purpose of this test is to make sure that the `purchase_price` is computed correctly before and after the SO confirmation, while with your fix we verify that the `standard_price` of the product does not change, but it will not be impacted by this use case, therefore there is no need to check it.

I think the best solution is to create a new bridge module `sale_mrp_margin` like `sale_stock_margin`

what do you think ?

2022-11-04 12:08 UTC, tdecaluwe commented
@DjamelTouati The cost of the product is calculated based on the `cost_method` (for example, AVCO or FIFO) and stored in the `standard_price`. This is from the `standard_price` help string:
> In Standard Price & AVCO: value of the product (automatically computed in AVCO). In FIFO: value of the next unit that will leave the stock (automatically computed). Used to value the product when the purchase cost is not known (e.g. inventory adjustment). Used to compute margins on sale orders.

The `sale_margin` basically copies the `standard_price` to the sale order line (except for expense lines), so that the margin can be easily computed. This means that your test is testing the computation of average cost prices for kit products, and as a consequence it suffices to assert the condition on the `standard_price` instead of the `purchase_price`.

2022-11-07 14:06 UTC, DjamelTouati commented
Fixed in: https://github.com/odoo/odoo/pull/104891

2022-11-07 14:06 UTC, closed without merging