[FIX] mail: fix emoji icon appearance in message editing mode
odoo/odoo pull request #104965
Opened 2022-11-04 08:55 UTC by maki-odoo

Fix emoji icon appearance in message editing mode

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-04 08:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104965).

2022-11-07 10:42 UTC, alexkuhn requested changes
The style is broken because of following style rule:
https://github.com/odoo/odoo/blob/16.0/addons/mail/static/src/components/message/message.scss#L19
```scss
.o_Message_content {
    *:not(li):not(li div) {
        overflow-x: auto;
    }
}
```
The composer is a child of `MessageView_content`, hence why it's affected by this style.
This is a mistake, because above SCSS rule applies on content of message view. It was not intended to have composer view as child of `MessageView`'s content, which feels wrong.

This is ok as a fix in stable versions, starting from version 15.0.

Eventually in master, should change code so that the `ComposerView` is not a `MessageView_content`.

2022-11-07 10:42 UTC, alexkuhn commented on addons/mail/static/src/components/composer/composer.xml
> +                                <i class="o_ComposerView_EmojiIcon fa fa-smile-o" role="img" aria-label="Emojis"/>
Can just add classname `overflow-visible` here (no css needed)

2022-11-07 12:49 UTC, closed without merging

2022-11-07 12:50 UTC, maki-odoo commented
New branches created to fix in v.15 and v.16