[FIX] mail: fix missing hover style on the buttons in the composer
odoo/odoo pull request #104985
Opened 2022-11-04 11:04 UTC by maki-odoo

Fix missing hover style on the buttons in the composer

task #4720

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-04 11:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/104985).

2022-11-07 11:19 UTC, alexkuhn requested changes
LGTM otherwise

2022-11-07 11:19 UTC, alexkuhn commented on addons/mail/static/src/components/composer/composer.scss
> +
Just removing `bg-view` is good enough.
It's properly contrasty in dark theme. A bit soft in white theme, but actually it's best to keep slight hover style in the end.

2022-11-07 11:20 UTC, alexkuhn commented
Also this is a 16.0 fix, so should have branch that targets this version. Thanks! 😊

2022-11-07 15:47 UTC, closed without merging

2022-11-07 15:48 UTC, maki-odoo commented
A new branch from v.16 is created.