[IMP] analytic: distribution model view tree multi-editable
odoo/odoo pull request #105044
Opened 2022-11-04 15:47 UTC by gawa-odoo

We should allow distribution models to be to be editable top.

t-3029083

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-04 15:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/105044).

2022-11-20 16:04 UTC, tsb-odoo commented on addons/analytic/views/analytic_distribution_model_views.xml
> +            <tree string="Analytic Distribution Model" multi_edit="1">
editable="top"

2023-01-25 15:34 UTC, epictete requested changes
I agree with @tsb-odoo, I believe `editable="top"` will be more suitable in this case :+1:

2023-02-23 13:43 UTC, gawa-odoo commented
So, done in 16.0 with https://github.com/odoo/odoo/pull/111089

2023-02-23 13:43 UTC, closed without merging