[FIX] website: scroll to the next visible element
odoo/odoo pull request #105334
Opened 2022-11-08 13:46 UTC by Guillaume-gdi

Before this commit, the buttons to scroll to the next element might not work if the next element was invisible.
Steps to reproduce the bug fixed by this commit:
- Install two languages on one site
- Drop a cover block (1), with a height of 100% and a scroll down button
- Make the block 1 only visible for language A
- Drop a new block (2) only visible for language B below 1
- Drop a new block (3) visible for everyone below 2
- Save and go to the site in language A
- Click on the scroll down button

=> No scroll at all while the user expects to scroll to the block visible to everyone (3). This commit fixes that by making the user scroll down to see the next visible section.

opw-2967706

2022-11-08 13:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/105334).

2022-11-09 08:48 UTC, Guillaume-gdi commented
@qsm-odoo two details:
- Actually the scroll button do not scroll if the block is the last visible of the #wrap, I replicate the same behavior here, but maybe we could make it scroll to the footer in this case (in master).
- The piece of code I change here also exists in 14.0 but I did not find a way to have a similar issue on 14.0. Let me know if I missed a way to have an invisible section :+1: 

otherwise this PR is ready

2022-11-10 12:14 UTC, qsm-odoo requested changes
> Actually the scroll button do not scroll if the block is the last visible of the #wrap, I replicate the same behavior here, but maybe we could make it scroll to the footer in this case (in master).

Agreed, let's keep the "wrong" behavior for stable (limitation) and do that in the master forward-ported PR.

>  The piece of code I change here also exists in 14.0 but I did not find a way to have a similar issue on 14.0. Let me know if I missed a way to have an invisible section

Indeed, though that mobile-invisible option was already there in 14.0 but apparently not. In any case, I would merge this in 14.0 anyway: custo may lead to invisible DOM after scroll buttons. And once this fix is right, I think the risk is 0.000001 for a 0.1 reward, so the ratio reward/risk is good, for an effort of 0.00001 of targeting another version with the same code :wink: (you can mention in your commit message that the flow you described is in 15.0 but it was decided to merge in 14.0 anyway to be custo-friendly).

2022-11-10 12:14 UTC, qsm-odoo commented on addons/website/static/src/js/content/snippets.animation.js
> +        const nextSectionEls = sectionEls.slice(currentSectionIndex + 1);
Those are two "expensive" operation you do not have to do. In this case, the most readable way to implement this is the most efficient way... just loop through next elements (using `nextElementSibling`) until you find a visible one.

2022-11-10 12:14 UTC, qsm-odoo commented on addons/website/static/src/js/content/snippets.animation.js
> +        const nextEl = nextSectionEls.find((el) => window.getComputedStyle(el).display !== 'none');
For this one, I'd like to use `is(':visible')` of jQuery (when we'll get rid of jQuery in a future master, we'll make an util which use their definition: `!!(elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length)`, that's probably more efficient and more precise (considers 0x0 elements invisible))

2022-11-16 16:28 UTC, Guillaume-gdi commented
@qsm-odoo

2022-11-24 13:21 UTC, qsm-odoo approved these changes
@Guillaume-gdi `$target` is a compatibility stuff in public widgets (don't know why you changed from the working `$el`): 
![image](https://user-images.githubusercontent.com/10338094/203794202-6b81a610-0323-449b-b820-9d8a24a06741.png)

I changed back (to use `el`) :) Looks good otherwise :+1: 

@robodoo r+

2022-11-24 16:17 UTC, closed without merging