[FIX] web: products snippet: fix layout issues
odoo/odoo pull request #105455
Opened 2022-11-09 13:34 UTC by xlu-odoo

Before this commit, some templates for the products snippet in website had some layout issues. 
This commit fixes them.

task-3060991

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-09 13:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/105455).

2022-11-10 11:20 UTC, Brieuc-brd requested changes
Hey @xlu-odoo 👋 
Some minor things, thanks !

2022-11-10 11:20 UTC, Brieuc-brd commented on addons/website_sale/data/product_snippet_template_data.xml
> +                        <div class="mb-1">
Decreasing this margin creates a spacing inconsistency when the rating stars are displayed.
I'm not sure if changing this class is necessary.

<img width="616" alt="Capture d’écran 2022-11-10 à 12 11 02" src="https://user-images.githubusercontent.com/80679690/201076268-b3273043-d4dc-47cf-a1a3-58e0b6f5a98c.png">

2022-11-16 09:05 UTC, Brieuc-brd approved these changes
LGTM 👍 
Hello @qsm-odoo this PR is ready for a technical review, could you take a look at it ? 🙂

2022-11-16 13:09 UTC, Williambraecky reviewed
Hello :)
Have those changes been validated with @pierre-pde ?
Cheers

2022-11-16 14:05 UTC, Williambraecky approved these changes
Thanks :)
robodoo r+

2022-11-16 16:33 UTC, closed without merging