[FIX] website_sale: no possibility to go back on e-commerce
odoo/odoo pull request #105570
Opened 2022-11-10 15:07 UTC by thle-odoo

Steps to reproduce:
    - go to e-commerce app;
    - select a product;
    - try to return to the shop with the browser's back arrow.
    (if the URL contains `\@\`, is not necessary to click on a "action", otherwise we must)

Issue:
    It is not possible to go back.

Cause:
	Modifying the hash modifies the history of the browser.

Solution:
	Change hash without changing browser history.

opw-3061027

2022-11-10 15:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/105570).

2022-11-16 15:13 UTC, younn-o approved these changes

2022-11-16 15:15 UTC, Williambraecky requested changes
Thanks :)
I think we also need to fix `_applyHashFromSearch` (which I think does not work anymore since 16.0 😬 )

2022-11-17 09:24 UTC, Williambraecky commented
@thle-odoo runbot is red

2022-11-17 12:01 UTC, Williambraecky approved these changes
Thanks :)
robodoo r+

2022-11-17 17:14 UTC, closed without merging