[FIX] website, website_sale: convert form-control-file class to BS5
odoo/odoo pull request #105872
Opened 2022-11-16 13:22 UTC by sobo-odoo

From BS4 to BS5, the `form-control-file` class has disappeared and
became `form-control`.

This commit replaces the occurrences of the old class by the new one. It
is necessary because by letting the old class, it is impossible to
place a form label above a `File Upload` field.

Indeed, since the `.form-control-file` CSS rule setting the `display`
property to `block` has been removed, the file input now has `display:
inline-block` by default, which is why the label would end up on the
same line as the input, instead of on top. With `.from-control`, this
rule is back, allowing to place the label on top again.

After this commit, the look of the file input will change. This is
because in BS4, with the `form-control-file` class, the input was the
browser native one. It could be customized using `.custom-file` (and
the associated `custom-file-*` classes). But in BS5, the file input is
directly a custom one, thanks to custom styles added on top of `.form-
control`.

task-3071151

See [1] for the enterprise PR.

[1]:https://github.com/odoo/enterprise/pull/34495

2023-02-27 10:49 UTC, qsm-odoo commented
@robodoo delegate=detrouxdev

2023-03-01 15:54 UTC, detrouxdev requested changes
The code is ok for me but maybe you could mention in the commit message why the look will change before and after this commit:
If I understand correctly, it's because of BS5 dropping form-control-file in favor of form-control. And prior to BS5, .form-control was the native look while .custom-file was the custom Bootstrap look? Reading from [here](https://getbootstrap.com/docs/5.0/migration/#forms).

Can you confirm? And maybe add the explanation to the commit? Thanks 👍🏻

2023-03-01 17:51 UTC, sobo-odoo commented
>  it's because of BS5 dropping form-control-file in favor of form-control.

I think only this point is relevant in the explanation (since `.form-file` and `.custom-file` were not used).
The label on top problem comes from the fact that these rules were removed in BS5 :
```css 
.form-control-file,
.form-control-range {
  display: block;
  width: 100%;
}
```
Therefore, the input `display` property was the default one which is `inline-block`, and so no matter what, the label and the input would end up on the same line. 
The problem is solved with the `.form-control` class because the `dispaly: block` property is back :slightly_smiling_face: 
I will add the explanation in the commit message :+1:

2023-03-02 13:43 UTC, sobo-odoo commented
@detrouxdev I updated the commit message :) (in the enterprise PR too)

2023-03-02 14:01 UTC, detrouxdev commented
Thanks!
@robodoo r+

2023-03-02 17:24 UTC, closed without merging