[FIX] rating: hide internal messages from review tab
odoo/odoo pull request #105854
Opened 2022-11-16 10:10 UTC by pivi-odoo

# Current behaviour
The internal message thread from the backend for reviews (eLearning and eCommerce) is currently publicly visible to public users by default.

# Expected behaviour
Internal message threads on reviews should be "Employees Only" by default. Hiding them by hand in the frontend is done by clicking a button one-by-one, which is tedious.

# Steps to reproduce
- Install eLearning and eCommerce
- Login as the admin, and activate "Discussion and Rating" for the eCom.
- Go to the backend, choose a course and a website product, for each of them "Send Message".
- Logout and go on the review tab of the respective course and product
- Observe you can see the message you've just posted.

# Reason for the problem
Message visibility state is the same as frontend reviews.

# Fix
Add the `is_internal` keyword when posting a message from the backend.
Message from the backend don't have a rating value, and if they are
posted by an internal user, we set it as `is_internal`.

# Affected versions
- 14.0
- 15.0
- saas-15.2
- saas-15.3
- 16.0
- master
---
opw-3033074

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-16 10:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/105854).

2022-11-21 14:30 UTC, agr-odoo requested changes
While `website_slides` depends on `rating`, `product` does not, so it would use a variables of unrelated module, which is not ideal. 
This patch should target `rating` module, which has its own `message_post` https://github.com/odoo/odoo/blob/ac0ca14c349e0d70d9f3a1aeb720f5e31f16d63e/addons/rating/models/mail_thread.py#L11

2022-11-22 12:05 UTC, pivi-odoo commented
Hi @agr-odoo,

I had tried to put the fix in the rating module at first, since it is the common point of interest, but it wasn't passing the tests. Adding a condition on the author checking if it is an internal user made some tests pass, but others broke (basically messages related to portal partners who couldn't see their messages).
We don't really have much to be able to differentiate between a message we want to set to "Employees Only" or a review.
What I came up with is adding a dependency to the rating module and overwrite the `message_post` function on the `'product.template'`. This is the least impactfull of the changes possible, because touching on the `message_post` in rating affects too many flows, since the condition is kinda broad (there are a lot of messages that not a rating comming from an internal user, and when posting a message, we don't really have a way to make it visible to internal + portal, but hidden from public, unless I am not aware of something).
If the changes I pushed are not allowed in stable, I would guess this request is a limitation. 

If you have any suggestions I am all ears.
Thanks in advance :)

2022-11-22 13:14 UTC, agr-odoo commented
@pivi-odoo 
Indeed adding a dependency is not allowed in stable.

We could improve the current fix moving the `product` part of the fix into `website_sale`.
It should be feasible to add a `message_post` override in addons/website_sale/models/product.py

> This is the least impactfull of the changes possible, because touching on the message_post in rating affects too many flows, since the condition is kinda broad (there are a lot of messages that not a rating comming from an internal user, and when posting a message, we don't really have a way to make it visible to internal + portal, but hidden from public, unless I am not aware of something).

I agree. Every change in these methods introduce a noticeable change in behavior, and I'm not sure this is something we want so we will need a functional review

2022-11-22 22:24 UTC, agr-odoo commented
Hello @tde-banana-odoo 
Could you check this please?

The issue was raised internally but we are not sure this could be fixed without messing existing message flows.
The idea is to avoid cluttering the website with internal messages that, currently, can only be hided one by one.

2022-11-28 07:44 UTC, tde-banana-odoo commented
Hello,

Indeed this is not really a bug. This is the standard behavior: comments are available when you can read a document. If you want to have notes, you can use "log a note". If you really want to change this behavior, this should be done through a feedback to POs that will see if and how we could make this change. For stable at least we cannot change that behavior that way: a lot of valid use cases could be broken after your patch.

Cheers !

2022-11-28 13:47 UTC, pivi-odoo commented
Ok, thanks for your feedback, I will close the PR then as a technical limitation.
I will forward your comment to the PO.
Cheers :)

2022-11-28 13:47 UTC, closed without merging