[FIX] pos_coupon: send only the id (int) of program_id to UI
odoo/odoo pull request #106059
Opened 2022-11-18 13:50 UTC by pedrambiria

Before this commit: when you use the pos restaurant, it will send the program_id with its id and name([id(int), name(str)]). But it should only send its id.

Steps to reproduce the issue:
 1. Open a new session in a pos_restaurant
 2. Create a new order and add some products
 3. Click on Orders
 4. Click on New Orde and add some products
 5. Go to the Floor screen
 6. Click the table you created the orders
 7. Click on Orders
 8. Click on any of two orders
 9. Click on the Floors button

You will get this Error in the log:
```
INSERT INTO "pos_order_line" ("id", "coupon_id", "create_date", "create_uid", "discount", "full_product_name", "is_program_reward", "mp_dirty", "mp_skip", "name", "note", "order_id", "price_subtotal", "price_subtotal_incl", "price_unit", "product_id", "program_id", "qty", "write_date", "write_uid") VALUES (nextval('pos_order_line_id_seq'), NULL, '2022-11-10 19:56:49.031959', 2, 0.0, '10.0% discount on total amount', true, false, false, 'Bar/0014', '', 2,  -0.22,  -0.22,  -0.22, 205, ARRAY[5,'Code for 10% on orders (Automatic)'], '1.00', '2022-11-10 19:56:49.031959', 2) RETURNING id
ERROR: invalid input syntax for type integer: "Code for 10% on orders (Automatic)"
LINE 1: ...014', '', 2,  -0.22,  -0.22,  -0.22, 205, ARRAY[5,'Code for ...
```

opw-3064038

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-18 13:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106059).

2022-11-21 15:42 UTC, robodoo commented
@pedrambiria @trj-odoo staging failed: ci/runbot (view more at https://runbot.odoo.com/runbot/build/21227906)

2022-11-21 17:21 UTC, hugho-ad commented on addons/pos_coupon/models/pos_order.py
> +            order_line['program_id'] = order_line['program_id'][0]
missing coupon_id

2022-11-21 17:22 UTC, hugho-ad requested changes
Missing Coupon_id field, I think the error could be reproduce if you set a coupon

2022-11-22 07:41 UTC, trj-odoo commented
@hugho-ad 
> Missing Coupon_id field, I think the error could be reproduce if you set a coupon

coupon_id is still being sent as [id, name] because we need that name during the initialization of the order line in the front end. What the fix is doing is taking the name for whatever purposes then setting the coupon_id as an id instead of a pair
@robodoo retry

2022-11-22 08:39 UTC, closed without merging