[FIX] web_editor: fix the history of the drag and drop in grid mode
odoo/odoo pull request #106190
Opened 2022-11-21 16:57 UTC by sobo-odoo

When drag and dropping a grid item and then undoing the operation, it is not undone correctly, causing the grid items to be broken. This happens because since `observerUnactive` is called at the start of the drag, the style (like the `grid-area`) and the grid classes changes are not recorded and therefore, undoing does not restore them.

This issue was previously fixed in [1] by removing the call to `observerUnactive` but it should not have been done and this call was restored in [2].

This commit solves this issue by activating the observer for the changes that have to be recorded when drag and dropping in grid mode, in order to undo them properly afterwards.

[1]: https://github.com/odoo/odoo/commit/cc406afcea7bf5846233a9f97a4a8ac5f618f3ec 
[2]: https://github.com/odoo/odoo/pull/106029

task-3074139

2022-11-21 16:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106190).

2022-11-30 16:53 UTC, rdeodoo commented
@robodoo delegate=@xO-Tx

2023-01-17 16:08 UTC, xO-Tx requested changes
@sobo-odoo It seems that the observer is active for some unwanted changes.
e.g. preview recorded on the history after drag&drop here:

https://user-images.githubusercontent.com/25032876/212949428-64a29f7a-5f71-4b66-b220-7f6a78153c6c.mp4

"Tested by cherry-picking the commit from the first [PR](https://github.com/odoo/odoo/pull/106029)."

2023-01-25 07:42 UTC, sobo-odoo commented
@xO-Tx (Just writing here what we said about the issue mentioned above to have a record about it :slightly_smiling_face: )
It doesn't happen every time and I managed to reproduce it in 15.0 so I think it is unrelated to my fix. There may be an issue with the previews which makes them being observed sometimes. I'll investigate a bit but it will surely be for another task.

2023-02-22 10:28 UTC, xO-Tx commented
@sobo-odoo thanks for the fix & updates :+1:

@robodoo r+

2023-02-22 11:46 UTC, closed without merging