[FIX] website: prevent to have wrong connectors when an icon change
odoo/odoo pull request #106316
Opened 2022-11-23 11:00 UTC by Guillaume-gdi

Steps to reproduce the bug:
- Drop a block steps on a page
- Change one of the icons
- Change the color of the icon

=> The connectors are not correct anymore.

This is due to this commit changing the tag `<i class="fa...` to a `<span class="fa...` so the option could not find the icon to draw the connector correctly. This commit fixes that error by allowing the option to detect the icon even when it is no longer in an `<i/>` tag.

task-3068834

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-11-23 11:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106316).

2022-12-01 13:40 UTC, Guillaume-gdi commented
Note that this PR is clearly inspired by https://github.com/odoo/odoo/pull/98238

2022-12-27 13:17 UTC, Guillaume-gdi commented
@xO-Tx This is ready for your review :+1:

2023-01-11 17:12 UTC, xO-Tx requested changes
@Guillaume-gdi LGTM :+1: but I think this can be fixed directly on the `IconSelector` component? from what I see in the code (correct me if I'm wrong), you can pass the `props.media` to the static `createElements()` of `IconSelector` to create an element with the same `tagName` (if `props.media` is already an icon)... not sure which implementation is "more correct", I leave the decision to you :+1:

2023-01-17 13:02 UTC, Guillaume-gdi commented on addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
> +                }
Indeed, it just remove the `data-bs-original-title` and the `aria-describedby` which could stay. I will remove this piece of code :+1:

2023-01-17 13:05 UTC, Guillaume-gdi commented
> Fix directy in the IconSelector...

Yes it is debatable but here, as it is a stable fix, I prefer the current implementation which doesn't add a function param :+1:

2023-01-17 14:56 UTC, Guillaume-gdi commented
@xO-Tx I ve adapted the code to your comments :heavy_check_mark:

2023-01-27 17:27 UTC, qsm-odoo requested changes
@Guillaume-gdi This is now linked to a ticket if ARD is right: opw-3123850, can you add that in the commit message ?
@xO-Tx Is everything good here? Maybe we should double-check with the editor team?

2023-01-27 17:57 UTC, Guillaume-gdi commented
@qsm-odoo I confirm that the client issue will be fixed by this PR, I added the opw to the commit message :+1: 

MOU asked me to check why we have to activate the snippet when the element is not in the DOM. Maybe we can prevent to call activate snippet if the element is not in the DOM. I didn't have the time to investigate this but in any case I think that if we make this change it would not be for stable version.

2023-01-27 18:00 UTC, xO-Tx commented
> @Guillaume-gdi This is now linked to a ticket if ARD is right: opw-3123850, can you add that in the commit message ? @xO-Tx Is everything good here? Maybe we should double-check with the editor team?

@qsm-odoo it looks good to me (as a fix on stable) :+1:  since it only sets the attributes from the new generated icon `element` (in the `mediaDialog`) to the target, I couldn't r+ yet since I'm worried about calling [activateSnippet()](https://github.com/odoo/odoo/pull/106316/commits/c915c176cacc21c551d114b31a7442debabc8cfd#diff-aa4686cd9f6a0d50e1040ba3dda0b29e9898e7cc31a47f1f02b46a2c4c047a72R1417) on `$(element)` (which is not in the DOM in this case) so as discussed @Guillaume-gdi can you check if we can avoide this (maybe we can simply skip the call if `changedIcon === true`) but I'm not sure 100% it's safe...

2023-02-06 12:40 UTC, Guillaume-gdi commented
@xO-Tx I checked that one and IMO it is useless to prevent the call of `activateSnippet` as this one already checks if the the element is visible or not.
```
if ($snippet && !$snippet.is(':visible')) {
      return;
}
```
The function does nothing if the element is invisible (which is the case when the element is not in the DOM). I am quite against having this kind of double check :/
```
if (visible) {
    activateSnippet()
}

function activateSnippet() {
    if (!visible) {
        return;
     }
     // Do stuff
}

2023-02-08 16:37 UTC, xO-Tx approved these changes
LGTM, @Guillaume-gdi thanks for checking the `activateSnippet()` :+1:

@robodoo r+

2023-02-08 18:33 UTC, closed without merging