[FIX] web_editor: prevent crash when filtering SVGs elements
odoo/odoo pull request #106671
Opened 2022-11-28 10:38 UTC by detrouxdev

When an SVG element changes and is filtered by the `filterMutationRecords` method, the method tries to split its className (Since [1]). This is not supported by the browser however, because the className property of an SVGElement is not a String. Rather, it is an SVGAnimatedString [2].

This commit fixes that by using the getAttribute method instead. Ensuring that the attribute returned is always a String.

[1]: https://github.com/odoo/odoo/commit/1c25ddb42393b136cac2a0ee0b9b7280fd803e7d [2]: https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString

opw-3077287
opw-3074434

2022-11-28 10:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106671).

2022-11-28 11:11 UTC, qsm-odoo requested changes

2022-11-28 12:05 UTC, dmo-odoo commented
@robodoo r+

2022-11-28 15:08 UTC, closed without merging

2022-11-30 18:27 UTC, rdeodoo commented
@detrouxdev don't forget to inform the customer once a fix has been made and merged for an opw (ask me if you are unsure of how to reply/what to tell, but we already gave a few info about it), or just ping me/QSM if you prefer and we will keep the client informed

2022-12-01 08:51 UTC, detrouxdev commented
@rdeodoo My bad, I forgot to re-read the infos you gave us, and wasn't sure if I had to send one once the fix was deployed or if the support rep would handle it. Thank you for taking care of it 😅