[FIX] l10n_in_purchase: right journal id in bills
odoo/odoo pull request #106793
Opened 2022-11-29 15:43 UTC by guva-odoo

The journal id from a purchase order was not
taken into account when creating the bill

Override _prepare_invoice method and add
the journal_id to the vals.

opw-3080805

2022-11-29 15:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106793).

2022-12-12 08:49 UTC, jco-odoo commented on addons/l10n_in_purchase/models/purchase_order.py
> +        self.l10n_in_journal_id and invoice_vals.update({'journal_id': self.l10n_in_journal_id.id})
@jva-odoo

2022-12-12 11:39 UTC, jva-odoo commented
> will be deprecated anyways...

it's looks okay,
And yes we remove it in master

2022-12-12 11:41 UTC, guva-odoo commented
@fw-bot up to 16.0

2022-12-12 15:32 UTC, Levizar requested changes

2022-12-12 15:32 UTC, Levizar commented on addons/l10n_in_purchase/models/purchase_order.py
> +        self.l10n_in_journal_id and invoice_vals.update({'journal_id': self.l10n_in_journal_id.id})
```suggestion
        if self.l10n_in_journal_id:
            invoice_vals.update({'journal_id': self.l10n_in_journal_id.id})
```

2022-12-12 21:05 UTC, Levizar approved these changes
@robodoo r+

2022-12-12 21:51 UTC, closed without merging