[FIX] web_editor: display grid mode mobile view for higher screen sizes
odoo/odoo pull request #106807
Opened 2022-11-30 08:35 UTC by sobo-odoo

When we are in grid mode, if we decrease the screen size small enough, the display is back to `flex` and the columns are displayed one above another (-> mobile view). However, the columns in normal mode do that for screen sizes higher than the breakpoint set for the ones in grid mode, which is unconsistent. Moreover, as the images have their `object-fit` property set to `cover`, they become really deformed and therefore do not look good.

This commit solves these issues by increasing the breakpoint at which the grid mode switches to the mobile view, that is, from `md` to `lg`.

opw-3069234

2022-11-30 08:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/106807).

2022-11-30 09:48 UTC, sobo-odoo commented
@qsm-odoo @rdeodoo 
FYI: I also had to modify in snippets.options where I check if the mobile view is activated to update the overlay, since it is based on the screen size.

2022-11-30 10:08 UTC, qsm-odoo requested changes
Commit message "unconsistent" -> "inconsistent"

2022-11-30 10:08 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            const isMobileView = this.$target[0].ownerDocument.defaultView.frameElement.clientWidth < 992;
@sobo-odoo Could you do better and use the utils to do this? config.js (legacy) / ui_service.js (new)? :+1: Ideally there are ways to write something like "if screenSize below or equal to MD", without re-hardcoding numbers.

2022-11-30 18:24 UTC, qsm-odoo commented
@sobo-odoo After more testing and thinking with PDE and RDE, we decided to add another option for grid images to be able to switch between cover and contain. I quickly made a commit (added on top of this PR): could you review it, test it and tell me if you think something is not right about this? Thanks :+1:

2022-12-02 15:22 UTC, qsm-odoo approved these changes
Thanks for the review @sobo-odoo (typos + the image shape stuff) :+1: I actually also forgot to add the new translated terms to the .pot.

Both commits are not really stable but we decided that it was worth it compared to the different alternatives, keeping in mind the 16.0 is recent:
- Mobile view is triggered on higher breakpoint than before for grid mode (~= portrait tablet), like for the non-grid mode. This will probably solves more usecases than it breaks (if any).
- Images using shape in grid mode now behave differently (including existing ones). Should be minimal as only concerns images whose area was reduced to a smaller height than the image itself.

@robodoo rebase-ff r+

2022-12-02 15:23 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-12-02 23:35 UTC, closed without merging