[FIX] web_editor: enable the use of the save option only on snippet
odoo/odoo pull request #107012
Opened 2022-12-01 13:43 UTC by loco-odoo

2022-12-01 13:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107012).

2022-12-02 10:00 UTC, Guillaume-gdi requested changes
Here is a small review.
![image](https://user-images.githubusercontent.com/78849981/205266535-b101412e-a9a1-4707-b0a2-ad580d8b90c6.png)

You missed to complete the PR description :see_no_evil: 
Will not you adapt the XML selector of the option in master ? If yes, you should add a little `TODO in master: ....` in your code

2022-12-02 10:00 UTC, Guillaume-gdi commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +    },
- This function should not be in the "Options" area, it should be in the "Private" area.
- The function doc string is not correct.
- Your comment should finish with a dot

You should do:
```
//--------------------------------------------------------------------------
// Private
//--------------------------------------------------------------------------

/**
 * @override
 */
_computeVisibility() {
    // Enable the use of the save option only for snippets.
    return this.$target[0].hasAttribute("data-snippet");
},
```

2022-12-12 09:34 UTC, Guillaume-gdi commented
LGTM :heavy_check_mark:

2022-12-12 09:36 UTC, Guillaume-gdi approved these changes

2022-12-14 12:24 UTC, qsm-odoo approved these changes
@loco-odoo Don't forget to ping when a ticket is ready. Here I see no ping on the task, nor on the PR despite a "LGTM" from GDI 2 days ago :wink: 

I push-forced those changes: https://github.com/odoo/odoo/compare/8ca473b3c404f9be252bf14fac5eadc314b13eb8..c51bb98c1b87a4f663ab12d5b37a4bbbbfe9c7ba

- Commit message: nitpicking but don't mention things like "after discussion with the PO, we decided that ...", it's implicit. At best mention you spoke with PDE about it in the task discussion or even as a comment in the PR.
- Your editor is not set up properly, it should remove whitespaces at the end of line automatically. We cannot see it in review but see the diff I made: there were 8 useless spaces
- In the comment I removed the fact you wanted a `data-exclude=":not(...)"`, we'll just adapt the `data-selector` to only target snippets (the thing is we could not do that before as `data-snippet` was not a thing before 14.0).
- "The goal of this commit" in a code comment does not mean anything. What commit? :wink: I removed that part, the code is explicit enough.

@robodoo r+

2022-12-14 14:11 UTC, closed without merging

2022-12-15 13:22 UTC, rdeodoo commented
> Your editor is not set up properly, it should remove whitespaces at the end of line automatically. We cannot see it in review but see the diff I made: there were 8 useless spaces

Note that if you don't want those auto remove, you can easily at least add style to your IDE to highlight those:
![image](https://user-images.githubusercontent.com/30048408/207869272-43dcd7cb-02d4-48c8-99b2-1113018beb32.png)

On vscode I think its:
```js
"workbench.colorCustomizations": {
        "editorWhitespace.foreground": "#5c4848"
},
```

2022-12-15 13:41 UTC, loco-odoo commented
> 

@rdeodoo, thanks a lot for the advice! I have just add ```"no-trailing-spaces": ["warn"]``` in my linter config file that works quite good as well :smiley:

2022-12-16 14:13 UTC, qsm-odoo commented
> If you don't want those auto remove

Does that mean you don't use that @rdeodoo ? I guarantee that if you don't auto-remove them, you will miss some or at least lose 10 minutes per day removing them by hand ^^

![image](https://user-images.githubusercontent.com/10338094/208116905-9a13db5b-52ae-4a51-8200-19d5c34e9bac.png)

2022-12-16 14:24 UTC, rdeodoo commented
> Does that mean you don't use that ?

I don't and I never did use that. I don't want **anything** at all to be done automatically when I save.
And I will never want that. I get that it fits some people way of working tho :)

> I guarantee that if you don't auto-remove them, you will miss some or at least lose 10 minutes per day removing them by hand

I guarantee that I don't :wink: 
I don't think I've ever commited a trailing whitespace, it's as close as impossible as it could be with the visual hint.
Not sure why you have to remove them for 10 min a day :thinking:

2022-12-19 14:05 UTC, rdeodoo commented
@loco-odoo To clarify my last message(s), you should surely enable the auto remove trailing whitespaces, it will avoid the error plain and simple. It's better for most people, you enable it and you don't care about it ever later :)

I was just suggesting an alternative in case you really don't want/refuse to enable auto feature inside your IDE (as I do), so you have something instead of nothing.

And note that I was referring to this extension actually, not a VS code setting: https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces