Master rescue session moda
odoo/odoo pull request #107000
Opened 2022-12-01 12:30 UTC by davidmonnom

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-01 12:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107000).

2022-12-01 14:02 UTC, rhe-odoo commented on addons/point_of_sale/static/src/js/Popups/AlertPopup.js
> +    }
The super call to setup is not needed. You can just do:
class AlertPopup extends AbstractAwaitablePopup { }
Just like in the confirmPopup?

2022-12-01 14:03 UTC, rhe-odoo commented on addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
> +            }
let is better than var.

2022-12-05 11:57 UTC, trj-odoo requested changes
After reviewing your PR, I saw that it's overlapping with another old feature. You should thus remove the old one regarding the number of opened session.

Also, since you modifying the field(s) of a model (adding and soon removing), a `migration` script will be needed. I'm inviting you to read [this](https://github.com/odoo/upgrade/wiki/How-To) to have a better understanding on how and where to write one

2022-12-05 11:57 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +    def _compute_current_rescue_session(self):
You already have a `@api.depends('session_ids', 'session_ids.state')` method in the `pos_config`. No need to create a new one, simply put your code there  (`_compute_current_session`).

2022-12-05 11:57 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +            'domain': [('state', '!=', 'closed'), ('config_id', '=', self.id), ('rescue', '=', True)]
No need for a domain if you are already specifying which session you want to display in `res_id`

2022-12-05 11:57 UTC, trj-odoo commented on addons/point_of_sale/static/src/js/Popups/AlertPopup.js
> +});
We are slowly but surely trying to adapt the code to how it should be defined without having to use the whole `odoo.define......`, `require`, etc and instead use proper import and export.
Can you take a look to `PromoCodeButton.js` to see how to adapt your file ? Don't hesitate to ask question .
Also, at the beginning of the file, it'll be better to put an alias like this
`/** @odoo-module alias=point_of_sale.AlertPopup**/

2022-12-05 13:01 UTC, davidmonnom commented on addons/point_of_sale/views/point_of_sale_dashboard.xml
> +                                            </a>
This is strange, already modified on my side.

2022-12-06 08:38 UTC, trj-odoo requested changes

2022-12-06 08:38 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +            rescue_sessions = pos_config.session_ids.filtered(lambda s: s.state != 'closed' and s.rescue)
you can directly filter on the `opened_sessions` record set above 
```suggestion
            rescue_sessions = opened_sessions.filtered('rescue')
```

2022-12-06 08:38 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +    def open_opened_rescue_session_from(self):
typo i guess
```suggestion
    def open_opened_rescue_session_form(self):
```

2022-12-06 08:38 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +            'res_id': self.session_ids.filtered(lambda s: not s.state == 'closed' and s.rescue).id,
```suggestion
            'res_id': self.session_ids.filtered(lambda s: s.state != 'closed' and s.rescue).id,
```

2022-12-06 08:38 UTC, trj-odoo commented on addons/point_of_sale/static/src/js/Popups/AlertPopup.js
> +Registries.Component.add(AlertPopup);
Add new line at the end of file

2023-01-05 11:20 UTC, trj-odoo requested changes
You will probably have a small conflict in the `ClosePosPopup` file once Sam PR's will be merged by the mergebot. 
Also, can you change the use single quote to double quotes in the js file ? This is to keep the same convention Sam choose in the refactor.

2023-01-05 11:20 UTC, trj-odoo commented on addons/point_of_sale/models/pos_config.py
> +    number_of_rescue_session = fields.Integer(string="Number of Rescue Session", compute="_compute_current_session")
```suggestion
    number_of_rescue_session = fields.Integer(string="Number of Rescue Session", compute='_compute_current_session')
```
Rule of thumb at Odoo, when developing in Python we're using double quotes `"` for string that should be displayed (message shown to the end-user, logs, etc) and single one `'` for technical string

2023-01-10 10:35 UTC, trj-odoo commented
@robodoo r+

2023-01-10 12:39 UTC, closed without merging