[FIX] sale_coupon: select best promotion program for specific product
odoo/odoo pull request #107103
Opened 2022-12-02 13:49 UTC by thle-odoo

Steps to reproduce:
    - create two promotion programs triggered with different order quantity;
    - select "On Specific Products" for "Discount Apply On";
    - select the same specific product for both promotional programs;
    - create a sale order which triggers the promotion program with the highest quantity;
    - click on the "PROMOTIONS" button.

Issue:
    Both promotion programs are applied instead of only the most advantageous.

Cause:
	When preparing sales order lines for promotion programs, we do not look for the most advantageous offer for a specific product.

Solution:
    Add a method that allows to keep only the most advantageous promotion program for a specific product.

Remark:
    We do not modify `_keep_only_most_interesting_auto_applied_global_discount_program` and `_is_global_discount_program` methods not to change the name of these functions which are very explicit.

opw-3076331

2022-12-02 13:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107103).

2022-12-05 13:59 UTC, agr-odoo requested changes
On the technical side this need an improvement:  `_keep_only_most_interesting_discount_specific_product_program` should be done grouping promo programs by product, otherwise you apply the promotions only to the product having the best discount.
IIRC the performance of coupon/promotions computation (and re-computation) are already not great, this would significantly slow the whole operation 

On the functional side we are doing this for promotions applied on the order so it seems ok to have this for promotions applied on each product, but imho it is not something we should add in stable.

@rdeodoo Hello, could we have your opinion on this? Thanks

2022-12-06 10:37 UTC, rdeodoo commented
> @rdeodoo Hello, could we have your opinion on this? Thanks

Hello, sure, but you should now ping @Williambraecky for coupon related issues:
- He is in charge of this module now, so he knows how it work in 16.0 and master, and any bug in earlier version will be of interest to him as it will need to be ported to master (or the other way around, master might already have a clue/solution for this)
- I am not working on it anymore, so I am kinda forgetting about the business knowledge over time :grimacing: 

But:

> > Cause:
> When preparing sales order lines for promotion programs, we do not look for the most advantageous offer for a specific product.
> 
> > Solution:
> Add a method that allows to keep only the most advantageous promotion program for a specific product.

Without investigating, this seems wrong, it's changing the spec not fixing it. It was designed to work that way, there is no "keep only the most advantageous offer for a specific product". This only exists for global discount as you can only apply one, which is not the case for specific product discount.

2022-12-12 11:37 UTC, Williambraecky commented
I have to agree, this does not look like a bug fix at all...

It's a limitation of the `coupon` module.
Since the loyalty refactoring this could actually be done using the point system however. So no change is needed in master either.

Thanks for your work but I don't think we can really help the client in this case. At least with automatic promotions. They might be able to work around the issue using manual promotions and promotional codes. (assuming those are also manual orders and not eCommerce..)

2022-12-12 12:44 UTC, closed without merging