[FIX] onboarding: modify access rights for onboarding model
odoo/odoo pull request #107201
Opened 2022-12-05 07:55 UTC by thle-odoo

Steps to reproduce:
	- install Calendar and Appointments apps; - give "Access Rights" for administration to a user; - go to calendar app with this user.

Issue:
    The user does not have access to the calendar.

Cause:
	The user has no access rights for the onboarding model.

Solution:
    Use the "group_erp_manager" ("Access Rights") group to give access rights knowing that the "group_system" group includes the "group_erp_manager" group.

opw-3083014

2022-12-05 07:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107201).

2022-12-06 13:36 UTC, arj-odoo requested changes
Hello :-). Thanks for your contribution. As discussed on Discord. I don't think this approach is the best one. I think the onboarding model permissions were chosen carefully even if I did not had the full details. To avoid lowering the permissions for the whole model in stable, I would update the controller code.



I think the issue comes from here: 
https://github.com/odoo/odoo/blob/16.0/addons/onboarding/controllers/onboarding.py#L11

```py

class OnboardingController(http.Controller):
    @http.route('/onboarding/<string:route_name>', auth='user', type='json')
    def get_onboarding_data(self, route_name=None):
        if not request.env.is_admin():
            return {}

        onboarding = request.env['onboarding.onboarding'].search([('route_name', '=', route_name)])
```
 `request.env.is_admin()` is true for the `base.group_erp_manager` but they can't access the `onboarding.onboarding` records. I would replace the check to make sure the user has the base.group_system rights :-). 

```diff
-- if not request.env.is_admin():
++ if not request.env.user.has_group('base.group_system')
```

2022-12-06 13:38 UTC, arj-odoo commented
cc @tde-banana-odoo @flch-odoo I was pinged on this one and commented. I thought you would be interested by the discussion :-).

2022-12-06 14:03 UTC, tde-banana-odoo commented
I think it is effectively more something for sys admins (configuration, ...) than erp managers (setting up users), but we might want to confirm with some PO :)

2022-12-06 15:16 UTC, thle-odoo commented
@tde-banana-odoo
After submitting and explaining to a PO, I have confirmation that it is better to fix as summarized @arj-odoo rather than modifying access

2022-12-06 15:21 UTC, arj-odoo approved these changes

2022-12-08 11:45 UTC, arj-odoo commented
@robodoo r+

2022-12-08 13:34 UTC, closed without merging