Master bills dashboard payment status hupo
odoo/odoo pull request #107329
Opened 2022-12-06 14:35 UTC by hupo-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR: In the Bills Dashboard (Accessible by clicking on the vendor Bill Journal and removing the filter for example), for a lot of different entries the payment status is indicated as "Not paid" even though no payment is expected for those entries. Moreover, this status will not change even though a payment is registered, which is counter intuitive. (Example: a payment is registered -> a payment line PBNK will have the status "Not paid")

Desired behavior after PR is merged:The payment status is visible if the entry is "Posted" AND the entry belongs to one of those type:  [Bill (BILL), Refund (RBILL), Purchase Receipt (BILL), Invoice (INV), Credit notes (RINV), Sale Receipt (INV)]. 
If the entry does not meet those criteria, make the payment status invisible. I also kept the previous visibility criteria which stated that the payment status is not visible if the payment state is set to 'Invoicing App Legacy".

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-09 08:49 UTC, FlorianGilbert requested changes

2022-12-09 08:49 UTC, FlorianGilbert commented on addons/account/views/account_move_views.xml
> +                           attrs="{'invisible': ['|', '|', ('payment_state', 'in', ('invoicing_legacy')), ('state', '!=', 'posted'), ('move_type', 'not in', ('out_invoice','out_refund','in_invoice','
```suggestion
                           attrs="{'invisible': ['|', '|', ('payment_state', 'in', ('invoicing_legacy')), ('state', '!=', 'posted'), ('move_type', '=', 'entry')]}"
```
It's easier to read :)

2022-12-09 09:19 UTC, epictete commented
Could you also please follow the coding guidelines for your PR/commit title :wink:
https://www.odoo.com/documentation/master/contributing/development/coding_guidelines.html#commit-message-structure

2022-12-15 08:12 UTC, FlorianGilbert approved these changes
@robodoo r+

2022-12-15 09:30 UTC, closed without merging