[FIX] pad: pad_generate_url should pass a proper Markup to the setHtmlFallbackText
odoo/odoo pull request #107469
Opened 2022-12-08 08:01 UTC by davidtranhp

This is an additional fix for the PR https://github.com/odoo/odoo/pull/84157

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-08 08:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107469).

2022-12-08 12:58 UTC, xmo-odoo requested changes

2022-12-08 14:48 UTC, davidtranhp commented on addons/pad/models/pad.py
> +                myPad.setHtmlFallbackText(path, Markup(content) if not isinstance(content, Markup) else content)
Tks, I will revise it according to your advice 👍

2022-12-09 02:04 UTC, davidtranhp commented on addons/pad/models/pad.py
> +                myPad.setHtmlFallbackText(path, Markup(content) if not isinstance(content, Markup) else content)
I have revised it. Please review.

2022-12-09 02:06 UTC, davidtranhp commented on addons/pad/models/pad.py
> +                myPad.setHtmlFallbackText(path, Markup(real_field_value))
I have changed it by just applying Markup only if the field is an HTML field and its value is taken from context. Please help review. Tks!

2022-12-12 14:31 UTC, davidtranhp commented
> Heya, after looking at it a bit more, this requires some more rejiggering to be clean, do you mind if I update your branch myself? Or alternatively close the PR and create a new one with the fix, as you prefer.

Yes, please update my branch yourself to get the work done 👍

2022-12-13 11:01 UTC, davidtranhp commented
@xmo-odoo Tks for the fix. But renaming method in a stable release may break someone's extensions. Anyway, the fix works for me :+1:

2022-12-13 13:57 UTC, davidtranhp commented
> > But renaming method in a stable release may break someone's extensions.
> 
> Yeah, seems a bit unlikely as it's an internal method only used once, but I'm wondering if I should either let an empty version of the old name for overrides, or leave the empty method in its entirety and add the other one to overwrite what the old one did.

I think, in addition to the new one, just leave the old one as it was and add a depreciation warning to inform others about that if they did use / override the old one.

2022-12-14 01:59 UTC, davidtranhp commented
> > > But renaming method in a stable release may break someone's extensions.
> > 
> > 
> > Yeah, seems a bit unlikely as it's an internal method only used once, but I'm wondering if I should either let an empty version of the old name for overrides, or leave the empty method in its entirety and add the other one to overwrite what the old one did.
> 
> I think, in addition to the new one, just leave the old one as it was and add an obsolate warning to inform others about that if they did use / override the old one.

@xmo-odoo I've added the commit 29841376ce14a0b64a0007e19e2ca0dcf446add1 to remain the method `_set_field_to_pad` with additional warning inside to avoid breaking other modules that may be using this method.

2026-02-10 14:18 UTC, closed without merging