[ADD] base_vat: VAT check for Venezuela
odoo/odoo pull request #107658
Opened 2022-12-09 15:48 UTC by Shawcker

The current VAT check doesn't pass for valid Venezuelan VAT numbers (RIF). Venezuela has a specific method to validate their RIF, very different from the standard VIES check.

This commit adds an implementation of the VAT number validation in Venezuela. The validation is based on
(1) pattern matching
(2) checksum validation

Task id=3094593

2022-12-09 15:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107658).

2022-12-15 09:02 UTC, FlorianGilbert requested changes

2022-12-15 10:29 UTC, Shawcker commented on addons/base_vat/models/res_partner.py
> +            return False
Seems better indeed, I'll look into that

2022-12-15 10:29 UTC, Shawcker commented on addons/base_vat/models/res_partner.py
> +        return True
Well, that's embarrassing :sweat_smile:

2022-12-15 10:29 UTC, Shawcker commented on addons/base_vat/models/res_partner.py
> +            checksum += int(digit) * multiplier
Thank you for all the suggestions, I think I'll go with the first one - it looks more like something I would do

2022-12-15 15:12 UTC, Shawcker commented on addons/base_vat/models/res_partner.py
> +        kind_digit = kind_digit_map.get(kind)
I don't see why `dict.get` is wrong here. As you said, the kind is already validated by the regex, so we actually do handle the kind being missing.

2023-01-11 10:23 UTC, FlorianGilbert approved these changes

2023-01-18 09:54 UTC, Shawcker commented on addons/base_vat/models/res_partner.py
> +            kind_digit = 5
@xmo-odoo is this better/ok then?

2023-01-18 11:18 UTC, xmo-odoo approved these changes
What a weird format though, is the complexity of the optional v optionally required formatting characters in the VAT number really necessary?

2023-01-18 13:07 UTC, Shawcker commented
> What a weird format though, is the complexity of the optional v optionally required formatting characters in the VAT number really necessary?

Yes it is necessary, since you can't have any dot `.` if there is no dash `-` beforehand. So `V12.345.6781` is wrong for instance.

2023-01-25 08:51 UTC, FlorianGilbert approved these changes
@robodoo r+

2023-01-25 10:01 UTC, closed without merging