[IMP] hr, sale(timesheet): improvement  timesheet portal  and employee
odoo/odoo pull request #107938
Opened 2022-12-14 11:56 UTC by ppr-odoo

1.  hr_timesheet, sale_timesheet: clickable some fields in timesheet portal

     - If user has project and sale order access linked to timesheet then that field
         will be clickable. So user can be redirected easily.

2. hr_timesheet: use name_get to add employee's company

   Currently, if both companies have employees with the same name, it is not known which
company the selected employee belongs to.

    In  this commit, the name of the company will only be appended by the name_get when more than
      one company is present in the database.

   Example
    - Administrator - My Company
    - Administrator - Tiny ERP

task-3101249

2022-12-14 11:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107938).

2023-01-17 17:15 UTC, auon-odoo requested changes
Thank you for this super neat work! :fire: 
Few details and we'll be good to go!

2023-01-17 17:15 UTC, auon-odoo commented on addons/hr_timesheet/models/hr_employee.py
> +        employees_count_per_user = {res['user_id'][0]: res['user_id_count'] for res in employee_read_group}
```suggestion
        employees_count_per_user = {
            res['user_id'][0]: res['user_id_count']
            for res in self.env['hr.employee'].sudo()._read_group(
                [('user_id', 'in', self.user_id.ids)],
                ['user_id'],
                ['user_id'],
            )
        }
```
Small detail number 1 :angel:

2023-01-17 17:15 UTC, auon-odoo commented on addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
> +                                    </td>
```suggestion
                                    <td t-if="not groupby == 'project'">
                                        <a  t-if="timesheet.project_id.id in access_project_ids" t-out="timesheet.project_id.display_name"
                                            t-att-title="timesheet.project_id.display_name" t-attf-href="#{timesheet.project_id.access_url}"/>
                                        <t t-else="" t-out="timesheet.project_id.display_name" t-att-title="timesheet.project_id.display_name"/>
                                    </td>
                                    <td t-if="not groupby == 'task'">
                                        <a t-out="timesheet.task_id.display_name" t-att-title="timesheet.task_id.display_name"
                                            t-attf-href="#{timesheet.task_id.access_url}"/>
                                    </td>
```
Small detail number 2. `t-if` first, and the rest is just keeping consistency in attrs's order. :angel:

2023-01-17 17:15 UTC, auon-odoo commented on addons/sale_timesheet/views/sale_timesheet_portal_templates.xml
> +                <t t-else="" t-out="timesheet.so_line.display_name" t-att-title="timesheet.so_line.display_name"/>
Same here :angel:

2023-01-18 08:31 UTC, auon-odoo approved these changes
Thank you :fire:

2023-04-03 07:15 UTC, xavierbol approved these changes
LGTM, thanks for your work! 🙂 

robodoo r+

2023-04-03 09:45 UTC, closed without merging