[FIX] snailmail: Fix base snailmail layouts (15.0)
odoo/odoo pull request #107969
Opened 2022-12-14 14:41 UTC by delvsola

This PR fixes the basic layouts for snailmail in odoo 15.0 due to changes having been made to the invoices themselves and the service provider changing their validation area in the future.

This PR is not to be forwarded and is exclusive to 15.0, saas-15.2 and saas-15.3 as other versions require different tweaks to their layouts.

2022-12-14 14:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107969).

2022-12-26 13:01 UTC, fda-odoo requested changes

2022-12-26 13:01 UTC, fda-odoo commented on addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
> +        padding-top: 0 !important;
tab issues :)

2022-12-26 13:33 UTC, delvsola commented on addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
> +        padding-top: 0 !important;
Nice catch, fixed !

2022-12-26 16:59 UTC, fda-odoo commented
@robodoo r+

2022-12-26 19:01 UTC, robodoo commented
@delvsola @fda-odoo staging failed: timed out (>120 minutes)

2022-12-26 19:11 UTC, delvsola commented
@robodoo retry

On Mon, Dec 26, 2022, 8:01 PM robodoo ***@***.***> wrote:

> @delvsola <https://github.com/delvsola> @fda-odoo
> <https://github.com/fda-odoo> staging failed: timed out (>120 minutes)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/pull/107969#issuecomment-1365358742>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT5XV355HW674P3CKIEDYSDWPHTPPANCNFSM6AAAAAAS6SD2CM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-26 21:13 UTC, robodoo commented
@delvsola @fda-odoo staging failed: timed out (>120 minutes)

2022-12-26 23:54 UTC, delvsola commented
@robodoo retry

On Mon, Dec 26, 2022, 10:13 PM robodoo ***@***.***> wrote:

> @delvsola <https://github.com/delvsola> @fda-odoo
> <https://github.com/fda-odoo> staging failed: timed out (>120 minutes)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/pull/107969#issuecomment-1365462187>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT5XV33DDMDRRADK45NSYFDWPIDBHANCNFSM6AAAAAAS6SD2CM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-27 01:56 UTC, robodoo commented
@delvsola @fda-odoo staging failed: timed out (>120 minutes)

2022-12-27 07:24 UTC, d-fence commented
robodoo retry

2022-12-27 08:04 UTC, robodoo commented
@delvsola @fda-odoo staging failed: ci/runbot on 403289448d6b995c2508e7b1c538e0cd8abfc0d0 (view more at https://runbot.odoo.com/runbot/build/22227032)

2023-01-11 10:22 UTC, fda-odoo commented
@robodoo r+

2023-01-11 12:56 UTC, closed without merging