[FIX] website_sale: add `t-key` to `t-foreach`
odoo/odoo pull request #107946
Opened 2022-12-14 13:07 UTC by abla001

To reproduce
============
- add a second image to a product and publish it on the website
- on the website make sure to enable image popup when clicking on it click on the product image -> error

Problem
=======
according to documentation of owl, `t-foreach` requires the presence of `t-key` to work properly
https://github.com/odoo/owl/blob/master/doc/reference/templates.md#loops

Solution
========
set `t-key` to the `id` of `product_image`

opw-3090782

2022-12-14 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/107946).

2022-12-14 14:07 UTC, nle-odoo reviewed
this doesn't solve the issue for me

testing your use case, the error to me probably happen because of this line:

https://github.com/odoo/odoo/blob/2008cb69dca14d0fe9fbd4484b52912fd4ea68b4/addons/website_sale/static/src/xml/website_sale_image_viewer.xml#L24

because `image.toString()` will always be `[object Object]` so all the keys are the same

side note: I think an owl error would only happen to an owl template (owl="1" in the definition, and not in the database views)

2022-12-14 14:34 UTC, abla001 commented
> odoo/addons/website_sale/static/src/xml/website_sale_image_viewer.xml

@nle-odoo that's weird for once I tested and it worked, I retested and it doesn't :rofl:, even runbot is not happy with my fix.
you are right the error came from the line you mentioned, I will update the commit

2022-12-14 15:22 UTC, nle-odoo approved these changes
looks good to me

a little odd to have a full URL as key, but it is the only option it seems (that or equivalent image.src or image_key). Since it should be unique that's fine.

2022-12-20 09:25 UTC, abla001 commented
@Williambraecky can you please take a look at this PR ? thank you :pray:

2022-12-21 08:34 UTC, Williambraecky requested changes
It's weird I'm sure it worked before..

Could you add test data for the zoom tour so that it does not break in the future?
Thanks for your work :)

2022-12-21 15:04 UTC, abla001 commented
@Williambraecky thank you for the feedback, the tour was fine we just had to enable developer mode to get the error

2022-12-21 15:40 UTC, Williambraecky commented
> @Williambraecky thank you for the feedback, the tour was fine we just had to enable developer mode to get the error

Makes sense!
robodoo r+
Thanks for the fix :)

2022-12-21 17:01 UTC, closed without merging