[FIX] l10_fr_fec : wrong export
odoo/odoo pull request #108012
Opened 2022-12-15 02:43 UTC by fmdl

**Description of the issue/feature this PR addresses:**

- create a company A
- create a company B with french accounting
- in environment with company A and B, and B is the current company

During export an account of company B can be use.

@oco-odoo @alexis-via 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-15 02:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108012).

2022-12-15 02:44 UTC, fmdl commented
OPW #3101947

2022-12-15 07:49 UTC, alexis-via approved these changes

2022-12-19 16:29 UTC, oco-odoo requested changes
Please make the commit message a little more explicit. I suggest:

[FIX] l10_fr_fec : multicompany error when fetching unaffected earnings account

- create a company A
- create a company B with French accounting
- Select A and B in the company selector, with B being the active company

At export, the A's unaffected earnings account can be used instead of B's.

2022-12-26 10:18 UTC, jco-odoo commented
@robodoo r+

2022-12-26 11:05 UTC, closed without merging