[FIX] web_editor: align m2m widget label with first element
odoo/odoo pull request #108227
Opened 2022-12-16 17:48 UTC by xO-Tx

The m2m widget label is aligned at the middle of the height of the whole option's display.

This commit makes the m2m widget label aligned with the first element (either the first
active value, or the "Choose a record..." dropdown if no value is selected).

task-2811746

2022-12-16 17:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108227).

2022-12-26 14:03 UTC, qsm-odoo requested changes
@xO-Tx We don't take risks improving UI design in stable versions, this should be a master "fix" (I would actually mark it with [IMP] and not [FIX], you are not fixing something here... or I missed something). Could you retarget? Thank you :+1:

2022-12-26 14:37 UTC, xO-Tx commented
> @xO-Tx We don't take risks improving UI design in stable versions, this should be a master "fix" (I would actually mark it with [IMP] and not [FIX], you are not fixing something here... or I missed something). Could you retarget? Thank you +1

Actually, I handled this as a FIX but it's more a CSS IMP indeed, moved to master, thanks :+1:

2022-12-27 12:08 UTC, qsm-odoo approved these changes
@robodoo r+

2022-12-27 13:17 UTC, closed without merging