[FIX] website: check if #wrapwrap selector exists
odoo/odoo pull request #108303
Opened 2022-12-19 14:17 UTC by thle-odoo

Steps to reproduce:
-------------------
- install "website" and "sign" module;
- go to webiste (Safari) on Signatures tab;
- select a document to sign.

Issue:
------
The document is not displayed.

Cause:
------
We try to apply modification on the `#wrapwrap` selector.
However, sometimes it does not exist.

Solution:
---------
Check if the `#wrapwrap` selector exists before applying changes.

Introduced with: ffa34d840a07efbbec3b180839d7cbf64787e4ef

opw-3102435
opw-3101909

2022-12-19 14:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108303).

2022-12-19 15:28 UTC, nle-odoo approved these changes
looks good to me

2022-12-20 10:31 UTC, rdeodoo requested changes
Commit message lines are too long, please line return at 72 char max.
Also missing the blame of the problematic commit which was introduced a few days ago, please write it down in the commit message (ideally with markdown).

2022-12-21 12:16 UTC, rdeodoo approved these changes
@robodoo r+
Thanks. I adapted the commit message to use markdown link

2022-12-21 14:23 UTC, closed without merging