Update available banks list
odoo/odoo pull request #108301
Opened 2022-12-19 14:05 UTC by kerteszgergo

Lots of contact information has been changed and some banks has been sold their bisiness portfolio over the years. In some cases the telephone and email links were in the wrong order.

Description of the issue/feature this PR addresses:
Bank information is out of date.

Current behavior before PR:
Outdated bank information.

Desired behavior after PR is merged:
Have an up to date bank records.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-19 14:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108301).

2022-12-19 14:23 UTC, kerteszgergo commented
Updated the name. Now should be working.

2022-12-20 17:29 UTC, kerteszgergo commented
I can't get rid of this name error even after I have changed the name.

2022-12-22 12:05 UTC, lordkrandel commented
> I can't get rid of this name error even after I have changed the name.

It's the commit name. 👇🏻 
![image](https://user-images.githubusercontent.com/1665365/209129090-a95c19e5-53a6-4cb8-ad1a-ee675b496ca8.png)

Commit name stays in `git log` and `git blame`.
The standard commit message format makes context information leap up to the eye! 😄 

![image](https://user-images.githubusercontent.com/1665365/209129747-153251a4-5ae1-4419-be5e-34866066620b.png)

Do a `git rebase -i 16.0` and then choose `reword`, then put the same as the PR title.

![image](https://user-images.githubusercontent.com/1665365/209130839-f79f3c7a-877a-4b5f-af1d-13f9489ec142.png)

2022-12-22 12:10 UTC, lordkrandel requested changes
Some small cleanup needed

2022-12-22 12:10 UTC, lordkrandel commented on addons/l10n_hu/data/res.bank.csv
> +"INGBHUHB","ING Bank N.V. Magyarországi Fióktelepe","INGBHUHB","base.hu",1068,"Budapest","Dózsa György út 84/b.","communications.hu@ingbank.com","+36 1 235 8700"
I see all the telephone numbers in the old file have no space inside.
Can you remove spaces from the new ones?

2022-12-22 12:10 UTC, lordkrandel commented on addons/l10n_hu/data/res.bank.csv
> +"HBWEHUHB","MagNet Magyar Közösségi Bank Zrt.","HBWEHUHB","base.hu",1062,"Budapest","Andrássy út 98.","info@magnetbank.hu","+36 1 428 8888"
See, here (and below this line too) the number didn't even change. It's just the spaces.

2022-12-22 12:15 UTC, lordkrandel commented on addons/l10n_hu/data/res.bank.csv
> -"MAVOHUHB","Sberbank Magyarország Zrt.","MAVOHUHB","base.hu",1088,"Budapest","Rákóczi  út 7.","info@sberbank.hu","+3614114200"
Wait a minute... where did Sberbank go? 😮 
Not available anymore in Hungary? Sanctions?

2024-09-26 10:01 UTC, lordkrandel commented
Since partner has vanished, a new PR odoo/odoo#181547 has been created in place of this.

2024-09-26 10:01 UTC, closed without merging