[BUGPROV] account_tax_update: Add a way to update taxes from local ta…
odoo/odoo pull request #108348
Opened 2022-12-20 09:34 UTC by clbr-odoo

…x templates

When taxes changed for a country (additions, modifications, ...) we were not applying modifications made on templates to regular tax objects. Thus users were forced to modify everything by hand or ask support to do it. We now try to safely update taxes, when we are sure they are the same we update their tax tags, else we create new ones without modifying existing ones.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-20 09:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108348).

2022-12-20 10:21 UTC, oco-odoo requested changes

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +        module, _, name = xml_id.partition(".")
rather use split()

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +        )
Rather use the ORM

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +        Else -> returns 'True'
```suggestion
        :return: True if ... 
```

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +                        # todo and tags are different else we update everytime things that are already the same
TODO

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +                            # clear all tags TODO need to delete unused fields
todo

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +                            tax_line.sudo().write({"tag_ids": [(4, tag.id) for tag in tags_to_add]})
no need for the sudos here

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +                            tax_line.sudo().write({"tag_ids": [(4, tag.id) for tag in tags_to_add]})
```suggestion
                            tax_line.sudo().write({"tag_ids": [(6, 0, tags_to_add.ids)]})
```

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/tests/test_account_tax_update.py
> +                            "Tax template tags and tax tags should be different.")
Probably too much; you're checking the write works ^^

2022-12-20 10:21 UTC, oco-odoo commented on addons/account_tax_update/tests/test_account_tax_update.py
> +    def test_xmlid_match_template_match(self):
docstring

2022-12-21 12:41 UTC, clbr-odoo commented on addons/account_tax_update/wizard/account_tax_update.py
> +            [r"%s\_%%" % company.id],
The first is the % for the LIKE clause and the second is the format specifier character. So yes both necessary :)

2022-12-21 12:42 UTC, pedrobaeza commented
You may want to check https://github.com/OCA/account-financial-tools/tree/15.0/account_chart_update as inspiration :)

2023-01-03 09:13 UTC, closed without merging