[FIX] base: missing MIME-Version header
odoo/odoo pull request #108499
Opened 2022-12-21 18:20 UTC by Julien00859

This is a second attempt at #64651

The reverted commit fixes the lack of a `MIME-Version` header on the
mail enveloppe by using `set_charset`. More specifically, `set_charset`
does the following, it set three headers:

* `MIME-Version`
* `Content-Type`
* `Transert-Encoding`

of them only `MIME-Version` was required.

The function was called *prior* of setting the mail's content or
alternatives.

Upon adding an alternative, python converts the current mail to a
multipart equivalent. Because of the two extra CT and TE headers, it
considered there was some content that needed to be moved inside of a
part, i.e. it created an *empty* part with the two CT and TE headers
set.

This empty part made our emails incompatible with Google G-Suite in case
an rich html footer was included via the G-Suite interface. Google would
wrongly reorder the email and move any text/plain part to the end of the
email and would show that part to the user instead of any text/html
part.

> Be conservative in what you send

Google shouldn't change the order of our alternatives but he does and
it is easier for me to change our code than to fix google's.

2022-12-21 18:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108499).

2023-01-03 11:17 UTC, Xavier-Do requested changes

2023-01-03 11:17 UTC, Xavier-Do commented on odoo/addons/base/tests/test_mail.py
> +        """[1:]).replace('\n', '\r\n'))
Using the regex here looks more confusing than it should be, an assert Equal should work and give a better error message if the test fails:
```suggestion
        self.assertEqual(msg_on_the_wire.strip(), textwrap.dedent(f"""
            From: =?utf-8?q?Jo=C3=A9?= Doe <joe@example.com>
            To: =?utf-8?q?Jo=C3=A9?= Doe <joe@example.com>
            Message-Id: {msg['Message-Id']}
            References: {msg['References']}
        """).replace('\n', '\r\n').strip())
```
(Feel free to adapt to remove the strips)

2023-01-03 11:21 UTC, Xavier-Do commented
I'm not very familiar with email headers but LGTM
@std-odoo if you have the time just to approve this change, this is quite urgent

2023-01-03 11:41 UTC, Julien00859 commented
![image](https://user-images.githubusercontent.com/8208953/210350563-6ba6b9da-5dee-48a0-a64a-e1249f0fe5d9.png)

2023-01-03 11:42 UTC, Xavier-Do commented
@robodoo r+

2023-01-03 11:42 UTC, std-odoo approved these changes
LGTM :)

2023-01-03 11:42 UTC, Xavier-Do approved these changes

2023-01-03 12:19 UTC, VincentSchippefilt approved these changes

2023-01-03 12:42 UTC, robodoo commented
@Julien00859 @Xavier-Do staging failed: ci/runbot on 237df55373e30586c4f2546b6b2c73498037dabf (view more at https://runbot.odoo.com/runbot/build/22407966)

2023-01-04 09:50 UTC, Julien00859 commented
@robodoo retry

2023-01-04 10:43 UTC, closed without merging