[FIX] web: set loadIrFilters to true
odoo/odoo pull request #108529
Opened 2022-12-22 12:49 UTC by thle-odoo

Steps to reproduce:
- install "sale_management" module;
- create a quotation;
- add a product;
- click on "Search More...";
- create a favorite filter;
- leave and return to the Dialog window.

Issue:
No previously saved filter appears.

Cause:
The `loadIrFilters` parameter has a default value equal to `false`.

Solution:
Set the value of the `loadIrFilters` parameter to `true`.

opw-3105096

2022-12-27 14:42 UTC, thle-odoo commented
Remark:
The favorite filters created on the Dialog window will be applied on the model in all views that allow these filters.
Is it the expected behavior ?

2022-12-28 09:26 UTC, hubvd reviewed
Not sure if that's what we want, but if it is, it works as expected

2022-12-28 15:21 UTC, jpp-odoo requested changes
Thank you for fixing the issue, @thle-odoo 
As a best practice in our team, we usually add tests for each fix and improvement made to web.
Could you please add a test for this fix as well?

2023-01-02 13:54 UTC, jpp-odoo commented
@robodoo r+

2023-01-02 15:08 UTC, closed without merging