[FIX] base: ignore spaces around text content when matching translation
odoo/odoo pull request #108706
Opened 2022-12-27 09:51 UTC by bso-odoo

When the same text appears several times inside a translated field but nested in different HTMLs, the matching for each one is done independently if various spacing appear in the HTML.

This commit strips the spaces around the matched texts so that texts that are synchronized on purpose do not become desynchronized. Doing this leads to collisions on the keys of `text2term`, it therefore also has to replace it with a dictionary of text to list of terms.

2022-12-27 09:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108706).

2022-12-29 13:26 UTC, qsm-odoo requested changes
@bso-odoo Thanks for the investigation and fix :+1: 

Maybe mention when this code was introduced (https://github.com/odoo/odoo/commit/ef00294e7189359c47638c4a71626f1937395edb ?), why the bug was not there before, what OPW it is related to (even if not exact same issue), etc.

But in the end, I'd like the opinion of @HydrionBurst on this, I am not confortable merging translations issues fixes :grimacing:

2022-12-30 08:43 UTC, HydrionBurst commented
Hi @bso-odoo thanks for the investigation and fix, I have 2 questions
1. does this happen in 15.x?
2. From a business perspective I think your new feature is better. But technically, terms in attribute should not have this behavior. For example, terms in `<div help="hello world"/>` and  `<div help=" hello    world "/>` are different. Could you provide a real case by writing  a simple test script?

2023-01-02 13:07 UTC, bso-odoo commented
@qsm-odoo @HydrionBurst The bug happened in 15.*.
I did address it in 16.0 because of a conversation I had with the framework team where I learned that the change from "raw text comparison" to "html's text content" that was done in master (which was 15.1 at the time) could not be a fix, because it was a feature change that impacted the expected result - which could break unknown code that relied on that result.
I am not even sure this PR can be in 16.0, maybe it will have to be in master for the same reason.

Regarding strings in attributes like `<div help="hello world"/>`, I will try to see if I can come up with a version that maybe combines the use of the `fields`'s `get_text_content` and `translate`'s `get_text_content`. Otherwise I guess I will have to add a behavior to be able to request the text content with the text coming from attributes having spaces replaced by something else.

2023-01-03 11:55 UTC, Gorash requested changes

2023-01-03 11:55 UTC, Gorash commented on odoo/fields.py
> +                text2terms.setdefault(re.sub(r'\s+', ' ', self.get_text_content(term)).strip(), []).append(term)
Can you output the expression from the method. Creating regular expressions takes time and having it in the loop is not efficient.

2023-01-03 11:55 UTC, Gorash commented on odoo/fields.py
> +                    old_term_text = re.sub(r'\s+', ' ', self.get_text_content(old_term)).strip()
idem
(use the same expression)

2023-01-03 13:29 UTC, HydrionBurst commented on odoo/fields.py
> +                text2terms.setdefault(SPACES.sub(' ', self.get_text_content(term)).strip(), []).append(term)
Maybe we can move the logic
`SPACES.sub()` and `strip()`
to `get_text_content` which is only used while writing model_terms field

2023-01-03 14:05 UTC, HydrionBurst commented on odoo/fields.py
> +                text2terms.setdefault(self.get_text_content(term), []).append(term)
using `defaultdict(list)` would be simpler

2023-01-11 16:28 UTC, rco-odoo commented on odoo/tools/translate.py
> +    return re_spaces.sub(' ', html.fromstring(term).text_content()).strip()
What about this?  It handles all kinds of spaces, and is probably faster that a regexp replacement.
```suggestion
    content = html.fromstring(term).text_content()
    return " ".join(content.split())
```

2023-01-12 10:13 UTC, rco-odoo commented on odoo/addons/base/tests/test_translate.py
> +</form>'''
May I suggest some simplification of the HTML?  The list of classes and style has no relevance in this test and only introduce a lot of noise.  I struggled to find the `%s` into that stuff
```suggestion
        archf = '''<form class="row">
    %s
    <div class="s_table_of_content_vertical_navbar" data-name="Navbar" contenteditable="false">
        <div class="s_table_of_content_navbar"><a href="#table_of_content_heading_1672668075678_4" class="table_of_content_link">%s</a></div>
    </div>
    <div class="s_table_of_content_main" data-name="Content">
        <section class="pb16">
            <h1 data-anchor="true" class="o_default_snippet_text" id="table_of_content_heading_1672668075678_4">%s</h1>
        </section>
    </div>
</form>'''
```

2023-01-12 10:18 UTC, rco-odoo approved these changes
Besides my last suggestion above, this looks good to me.
You can merge it once you finalize it.
@robodoo delegate+

2023-01-12 13:52 UTC, bso-odoo commented
@robodoo r+

2023-01-12 16:10 UTC, closed without merging