[FIX] website_sale: keep pricelist with code from one step to another
odoo/odoo pull request #108728
Opened 2022-12-27 13:25 UTC by joda-odoo

In the current state of the code, pricelist are always recalculated according to the partner id of the user. In the case of a custom pricelist applying to anyone with a code, Odoo will bring back the default pricelist, forcing us to retype the code once or twice 
during the checkout process.

*note*: I've tried to find a way to check if the code in the pricelist correspond of what was introduced in the sale order, but I wasn't able to find it

opw-3101158

2022-12-27 13:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108728).

2023-01-05 14:51 UTC, nle-odoo approved these changes
Maybe it's correct, but this seems to be a dangerous change.

From my tests, we don't find the pricelist in website().get_current_pricelist() at this step:

https://github.com/odoo/odoo/blob/37f77449ae40998e3fdf2f52261d2d9a7ef05ed6/addons/website_sale/models/website.py#L246-L251

So maybe another way would be to set  `website_sale_current_pl` when the pricelist is set , but it seems that we don't set the variable currently.

2023-01-17 15:22 UTC, nle-odoo approved these changes
I'm not sure. It still seems rather general for a particular case (only the pricelist for a code) but I don't know the code enough to know if there is a cleaner / preferred way.

2023-01-19 09:04 UTC, Williambraecky requested changes

2023-01-19 09:04 UTC, Williambraecky commented on addons/website_sale/controllers/main.py
> +        request.session['website_sale_current_pl'] = values["order"].pricelist_id.id
Why not change that when actually putting in the pricelist? (`def pricelist`)

2023-01-20 10:44 UTC, Williambraecky approved these changes
Thanks
robodoo r+

2023-01-20 12:56 UTC, closed without merging