[FIX] spreadsheet_dashboard: translatable name field
odoo/odoo pull request #108841
Opened 2022-12-30 05:01 UTC by niyasraphy

before this commit the name field in spreadsheet.dashboard.group and spreadsheet.dashboard is not translatable, and it always appears in english in the dashboard.

after this commit, the name will be translatable and values will be shown in users language in the dashboard.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-12-30 05:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/108841).

2023-01-02 08:06 UTC, LucasLefevre requested changes
Hello,

Thanks for the feedback. I agree the names should be translated.

However, this change should target the `master` branch as translated fields does not have the same database schema as regular fields (see https://github.com/odoo/odoo/pull/97692).

Could you re-target the PR to master please?
Thanks

2023-01-02 08:19 UTC, niyasraphy commented
@LucasLefevre thanks for the review and feedback, will create a pr targeting the master.

2023-01-03 05:53 UTC, niyasraphy commented
@LucasLefevre created a new pr targeting the master:  https://github.com/odoo/odoo/pull/108972
thanks

2023-01-03 05:53 UTC, closed without merging