[REF] l10n_mx: DIOT report as tax report
odoo/odoo pull request #109300
Opened 2023-01-06 11:46 UTC by tdetry

1/ The mexican DIOT report is now a tax report.

This in order to enjoy more Reportalypse' features (less menuitems, tax_tags engine). The export functinality will remain in enterprise version.

2/ Add missing tax "RET IVA FLETES 4%" tax.

3/ Add migration script for taxes.

As a new tax (RET 1.25%) has been added and the DIOT refactoring updated many invoice_repartition_line_ids and refund_repartition_line_ids with tags, the migration script will be run on module update.

2023-01-06 11:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/109300).

2023-01-10 16:28 UTC, vbe-odoo commented
@lao-odoo ping
@ren-odoo @fvz-odoo

2023-01-12 15:59 UTC, oco-odoo requested changes

2023-01-13 09:53 UTC, tdetry commented on addons/l10n_mx/migrations/2.1/post-migrate_update_taxes.py
> +    update_taxes_from_templates(cr, 'l10n_mx.mx_coa')
indeed https://github.com/odoo/upgrade/commit/414730bc00a5692586dd780d91cb2fa91405c695

2023-01-13 10:06 UTC, tdetry commented on addons/l10n_mx/data/account.account.tag.csv
> -tag_diot_exento,IDTTP: Exempt,taxes,base.mx,0
Yes, I can update the (post) migration script to migrate them to the newly created one, but I do not know how to remove them from the code ?

2023-01-26 16:33 UTC, oco-odoo requested changes

2023-01-31 14:02 UTC, oco-odoo approved these changes
@robodoo r+

2023-01-31 15:00 UTC, robodoo commented
@tdetry @oco-odoo linked pull request(s) odoo/enterprise#35515, odoo/upgrade#4224 not ready. Linked PRs are not staged until all of them are ready.

2023-02-08 10:00 UTC, robodoo commented
@tdetry @oco-odoo linked pull request(s) odoo/upgrade#4224 not ready. Linked PRs are not staged until all of them are ready.

2023-02-10 15:30 UTC, oco-odoo commented
@robodoo r+

2023-02-10 16:50 UTC, closed without merging