[MOV] website, test_website: move test using data file to test_website
odoo/odoo pull request #109349
Opened 2023-01-06 15:39 UTC by bso-odoo

When the QWeb `<template>` loading test was introduced at [1], the
`test_website` module did not exist yet, see [2].

This commit moves that test and its related data file to `test_website`
to remove the `fake data` noise from the `website` module.
That's one of the two purpose of this `test_website` module:
- Avoid noising the website module with test only data & code
- Encapsulate in a lighter module the module operations tests, but it's
  not really the case anymore as those tests are now standalone tests.

See manifest for more details.

[1]: https://github.com/odoo/odoo/commit/9cd982bcc811cacb42f5c08db139043d2734b891
[2]: https://github.com/odoo/odoo/commit/ef03db9edd9472201cb2c08a32d20ff0f33a5fdf

2023-01-06 15:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/109349).

2023-01-10 07:52 UTC, bso-odoo commented
@rdeodoo This is the PR about moving the template import test to `test_website`.

2023-01-19 16:03 UTC, rdeodoo requested changes
Hi Benoit, thanks for the cleaning PR :+1: 

I just push forced the commit message to include the commit references, I get that it has low value here, but since I already [provided](https://github.com/odoo/odoo/pull/104836#discussion_r1063403108) you those links, it was easy to mention :)

But actually, it seems to be missing the `website.test_bundle`, it should be moved too, right?

2023-01-20 10:12 UTC, bso-odoo commented
@rdeodoo I moved `website.test_bundle` to `test_website`, and also renamed it to `test_website.test_bundle`.

2023-01-20 10:31 UTC, rdeodoo approved these changes
@robodoo r+

2023-01-20 10:31 UTC, rdeodoo commented on addons/test_website/tests/test_qweb.py
> +class TestQweb(TransactionCaseWithUserDemo):
Those should have been `@tagged('-at_install', 'post_install')` in the first place IMO, but let's merge it like this

2023-01-20 20:57 UTC, closed without merging