[FIX] l10n_ve: Translation
odoo/odoo pull request #109494
Opened 2023-01-10 08:23 UTC by malb-odoo

All the localisation should be written in english and then translated to the native language of the country. In this case, the Venezuelian localisation was written is Spanish, this PR translate the module in english and add the corresponding PO file in spanish.

Task-id: 3126154

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-01-10 08:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/109494).

2023-01-10 13:39 UTC, vin-odoo requested changes

2023-01-10 13:39 UTC, vin-odoo commented on addons/l10n_ve/data/account.account.template.csv
> +"account_activa_account_1151002","I.S.L.R.I. WITHHELD","1151002","asset_current","l10n_ve.ve_chart_template_amd","True"
```suggestion
"account_activa_account_1151002","I.S.L.R. WITHHELD","1151002","asset_current","l10n_ve.ve_chart_template_amd","True"
```

2023-01-10 13:39 UTC, vin-odoo commented on addons/l10n_ve/i18n/es.po
> +msgstr "IMPUESTOS DIFERIDOS I.S.L.R"
```suggestion
msgstr "IMPUESTOS DIFERIDOS I.S.L.R."
```

2023-01-10 13:39 UTC, vin-odoo commented on addons/l10n_ve/i18n/es.po
> +msgstr "F.A.O.V APORTE EMPRESA"
```suggestion
msgstr "F.A.O.V. APORTE EMPRESA"
```

2023-01-10 13:39 UTC, vin-odoo commented on addons/l10n_ve/data/account.account.template.csv
> +"account_activa_account_7131023","I.N.C.C.E.S. CONTRIBUTIONS","7131023","asset_current","l10n_ve.ve_chart_template_amd","True"
```suggestion
"account_activa_account_7131023","I.N.C.E.S. CONTRIBUTIONS","7131023","asset_current","l10n_ve.ve_chart_template_amd","True"
```

2023-01-10 14:43 UTC, vin-odoo commented
@robodoo r+

2023-01-10 15:50 UTC, malb-odoo commented
@vin-odoo I forgot the spoken language in the chart template, can you R+ again ?

2023-01-11 06:26 UTC, vin-odoo commented
@robodoo r+

2023-01-11 07:30 UTC, closed without merging