RTL alignment
odoo/odoo pull request #110288
Opened 2023-01-18 15:00 UTC by jpp-odoo

[FIX] web: invert position (start/end) when using rtl

Before this commit, when using a rtl language, the position of the
popper elements using the 'usePosition' hook weren't inverted.

---

[FIX] web: align text to the end in RTL languages

Bootstrap forces some input types ("tel", "url", "email", "number") to
be LTR even if in an RTL languages, before the last update of bootstrap
this was done in [1] and [2].

The issue of forcing some input types to LTR, is that the alignment was
wrong. Now, the for the same types when using an RTL language we force
the align to the end.

[1] : https://github.com/odoo/odoo/commit/90ab752c5fc9b27a6a40006abfe49483e7ca847d
[2] : https://github.com/odoo/odoo/commit/0d650c3b19c847181fa50c88eb945792528f01cc

2023-01-18 15:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/110288).

2023-01-19 09:33 UTC, aab-odoo approved these changes
@brboi maybe?

2023-01-19 13:48 UTC, brboi requested changes

2023-01-19 13:48 UTC, brboi commented on addons/web/static/src/core/position_hook.js
> +    }
Do we really want to switch between right-end and right-start and also between left-start and left-end when we are in RTL ?
I don't think so.

IMHO, we should not make the position hook dependent of the localization.

The strategy used in the Dropdown component is to pass the proper positioning options depending on the l10n direction. I think this is what we should do when we face a similar use case.

2023-01-19 13:48 UTC, brboi commented on addons/web/static/tests/core/position_hook_tests.js
> +});
As this test suite is already exhaustive, I would like to see it evolve in the same way.
Add tests for:
- bottom-{start,middle,end}
- right-{start,middle,end}
- left-{start,middle,end}

2023-01-20 09:45 UTC, brboi reviewed
It already looks nice, thanks ;-)
Please investigate the below comment.
I'll give a try at an instance after.

2023-01-20 09:45 UTC, brboi commented on addons/web/static/src/core/dropdown/dropdown.js
> -                direction = direction === "left" ? "right" : "left";
This line is still needed for the direction caret class, am I right ?
Or maybe the directionCaretClass have to be set on the "onPositioned" callback.

2023-01-20 15:16 UTC, brboi commented
robodoo r+

2023-01-20 16:00 UTC, robodoo commented
@jpp-odoo @brboi because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-01-20 16:03 UTC, jpp-odoo commented
@robodoo rebase-ff

2023-01-20 16:04 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-01-20 17:10 UTC, closed without merging