[FIX] sale_coupon: promotion with tax on SO remains positive
odoo/odoo pull request #110289
Opened 2023-01-18 15:14 UTC by vava-odoo

Steps to reproduce:
- Create a promotion with fixed price discount
- Add a tax on the `discount_line_product_id`
- Create a SO with an amount smaller than the discount
- Activate the promotion on the SO

Current behaviour:
- The SO amout is negative

Behaviour after the PR:
- The discount is limited such that both untaxed amout and taxes remain positive.

opw-3119582

2023-01-18 15:31 UTC, robodoo commented
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

2023-01-18 15:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/110289).

2023-01-19 11:07 UTC, vava-odoo commented on addons/sale_coupon/models/sale_order.py
> +            lines = self._get_paid_order_lines().filtered('price_reduce')
I don't know all the details about `price_reduce`, I just followed the exact same logic as it's done a few lines below for the other case where there are no taxes  on the coupon product.

2023-01-19 12:51 UTC, Williambraecky requested changes
Thanks for the fix, note that I am not 100% knowledgeable on `coupon`

Shouldn't be an issue since `loyalty`
@fw-bot up to saas-15.2

2023-01-19 12:51 UTC, Williambraecky commented on addons/sale_coupon/models/sale_order.py
> +            lines = self._get_paid_order_lines().filtered('price_reduce')
The filtered is useless as the sum right below will just ignore lines with 0 as price_reduce.
```suggestion
            lines = self._get_paid_order_lines().filtered('price_reduce')
```

2023-01-19 12:51 UTC, Williambraecky commented on addons/sale_coupon/models/sale_order.py
> +            lines = self._get_paid_order_lines().filtered('price_reduce')
`_get_paid_order_lines` will allow the order to go below 0 with fixed discounts in a case such as this one, I think we need to use `_get_base_order_lines(program)` but don't quote me on this 😅 :
- Product A; 10$
- 50% discount; -5$
- \>5$ fixed price discount; - \>5$ (possibly + tax)
We need to consider the

2023-01-19 12:51 UTC, Williambraecky commented on addons/sale_coupon/models/sale_order.py
> +            discount_amount_without_tax = min(lines_price, discount_amount)
It's a detail but there is no need for another variable
```suggestion
            discount_amount = min(sum(lines.mapped(lambda l: l.price_reduce * l.product_uom_qty)), discount_amount)
```

2023-01-19 13:45 UTC, vava-odoo commented
Many thanks @Williambraecky for the review. 
Indeed, it doesn't impact versions >= 16.0. 
I made the suggested changes. I confirm that I forgot the case where there a fixed coupon and percentage one. It is ok now. Does it need another test?
Also, I'm still able to end up with a small negative SO total amount, due to rounding errors. Do we keep it as is, or should we add something to prevent it to occur?

2023-01-20 08:39 UTC, Williambraecky approved these changes
Thanks
robodoo r+

2023-01-20 09:34 UTC, closed without merging