16.0 misc fidu fixes vin
odoo/odoo pull request #110397
Opened 2023-01-19 12:13 UTC by vin-odoo

WIP

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-01-24 15:21 UTC, FlorianGilbert requested changes

2023-01-24 15:21 UTC, FlorianGilbert commented on addons/base_vat/models/res_partner.py
> +        vat_has_legit_country_code = self.env['res.country'].search([('code', '=', vat_country_code.upper())])
self.env.ref or limit=1?

2023-01-24 15:21 UTC, FlorianGilbert commented on odoo/addons/base/models/res_partner.py
> +                            previous_field.addnext(current_field)
:see_no_evil:

2023-01-24 15:31 UTC, FlorianGilbert approved these changes
LGTM

2023-01-25 16:35 UTC, qdp-odoo requested changes

2023-01-25 16:35 UTC, qdp-odoo commented on odoo/addons/base/models/res_partner.py
> +
heu..

there must be a nicer way of doing it... using_display_address and adding just a text node, a JS widget or even the above postprocess_and_fields() using address_view_id (why would it still be 2 different things, anyway?).

I'm not willing to allow this in stable: we do it cleanly or we do it cleanly in master only, but we do it clean anyway.

2023-01-26 07:54 UTC, qdp-odoo commented on odoo/addons/base/models/res_partner.py
> +
hackish but it's an FP request :man_shrugging:

2023-01-26 08:28 UTC, chklop commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +                    if abs(tax_total - tax_line_amount) <= 0.05:
@qdp-odoo It is not useful, it is mandatory, we do the same in the OCR. It's a tax rounding problem. As the invoice is generated by another software who maybe does the tax rounding differently from the database in Odoo, we need to "correct" the rounding when you import it in Odoo. We cannot let Odoo change the invoice total.

2023-01-27 15:10 UTC, smetl requested changes

2023-01-27 15:10 UTC, smetl commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +        if not invoice.is_invoice(include_receipts=True):
useless check

2023-01-27 15:10 UTC, smetl commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +            if invoice.is_sale_document() and invoice.quick_edit_mode:
```suggestion
            if invoice.is_sale_document(include_receipts=True) and invoice.quick_edit_mode:
```

2023-01-27 15:10 UTC, smetl commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +            percentage = elem.find('.//{*}TaxCategory/{*}Percent')
You are parsing twice exactly the same data...
At this point, you should already have the total for each account.tax, no need to parse it again.
You should perform the update of tax lines using the same mechanism as the pen on vendor bill

2023-01-27 15:10 UTC, smetl commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +        all_taxes = self.env['account.tax'].search([
wtf is that? `invoice.line_ids.tax_line_id`...

2023-01-30 07:32 UTC, d-fence commented
Upgrade exception [#180](https://runbot.odoo.com/web/#id=180&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
view:base_vat.view_partner_base_vat_form
field:res.users.vies_failed_message
field:res.partner.vies_failed_message
```
cc @KangOl @nseinlet

2023-01-30 08:07 UTC, qdp-odoo commented
@robodoo r+ rebase-ff

2023-01-30 10:05 UTC, closed without merging