[IMP] l10n_no_reports: translation
odoo/odoo pull request #110986
Opened 2023-01-25 14:53 UTC by malb-odoo

Before this PR, all this localisation was written in Norwegian, but all the localisation have to be written in english and then translated back in the native language. This PR correct that.

Task-id: 3149392

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-01-25 14:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/110986).

2023-01-26 10:02 UTC, h4818 reviewed
LGTM

2023-01-30 11:55 UTC, vin-odoo requested changes
annen = other
andre = others

2023-01-30 11:55 UTC, vin-odoo commented on addons/l10n_no/data/account.account.template.csv
> +"chart6440","6440","Rent means of transport","expense","","False","no_chart_template"
Rent/ rental
Align these names to use the same terms

2023-01-31 07:35 UTC, vin-odoo approved these changes
@robodoo r+

2023-01-31 13:04 UTC, closed without merging