[FIX] l10n_id_efaktur: custom settings visibility
odoo/odoo pull request #111070
Opened 2023-01-26 12:42 UTC by moerradi

Description of the issue/feature this PR addresses:
Fixing a small bug where the custom invoicing settings for  l10n Indonesian E-invoicing appears even in companies not located in Indonesia in a multi company environment

Current behavior before PR:

<img width="861" alt="before" src="https://user-images.githubusercontent.com/50016803/214837775-47cc511c-08d0-4e04-aba0-31f8b9d6d0f0.png">

Desired behavior after PR is merged:

<img width="773" alt="after" src="https://user-images.githubusercontent.com/50016803/214837869-e998da55-750d-48eb-b22f-dd2e797b9eca.png">

2023-01-26 12:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111070).

2023-01-26 14:09 UTC, Levizar requested changes
Well done!

You just need to polish the commit message. BTW, there is the possibility to define a commit message template to have the skeleton of the commit message written automatically. You just need to write a `.txt` file containing the template and then `git config --global commit.template ~/.gitcommittemplate.txt`


Here is the blabla:
We should make the commit message follows the [guidelines](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-full-description).
The title is ok but there isn't any body.
The minimal body should include a small explanation about why this is needed and the task-id.
```
[TAG] modules: what is done

small explanation of why

task-id: <id of the task>
```

I usually go for a bigger one because it helps the support or other developpers when they are going through the commit history to find why a particular piece of code is shaped that way.
The more you save their time, the more it saves yours because they don't come to you with question about a piece of code you wrote 1 year ago and forgot.

Here is a the pattern I try to follow:
```
[TAG] modules: What is done

The aim of this commit is [functional aim of the commit]

context:
What is the context of this commit

Previous to this commit: (this is mostly in case of a fix commit)
what happens when the user try to do stuff related to the aim

After this commit: (this is mostly in case of a fix commit)
what happens when the user try to do stuff related to the aim

Community-PR: <links to Community pr>
Enterprise-PR: <links to Enterprise pr>
Upgrade-PR: <links to Upgrade pr>

task-id: <task-id>
```

And here an example of one of my https://github.com/odoo/odoo/commit/a926071fc6944d5cd720a8849b2f31a5dd8ff4dc

Again, rules aren't set in stone.
Sometimes a very short body explanation is enough.
Sometimes there isn't any task, blablabla

2023-01-26 17:34 UTC, moerradi commented
I'll create a new PR for 16.0

2023-01-26 17:34 UTC, closed without merging

2023-01-31 07:29 UTC, Levizar commented
Done in this PR