[ADD] l10n_in: merge l10n_in_upi l10n_in
odoo/odoo pull request #111299
Opened 2023-01-30 05:16 UTC by kir-odoo

merge l10n_in_upi into l10n_in

2023-01-30 05:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111299).

2023-05-09 10:37 UTC, jva-odoo commented
@kir-odoo remove model file

2023-05-15 05:39 UTC, jva-odoo approved these changes

2023-05-15 05:41 UTC, jva-odoo commented on addons/l10n_in/models/res_company.py
alrady there is company.py

2023-05-15 05:44 UTC, jva-odoo requested changes

2023-05-15 05:44 UTC, jva-odoo commented on addons/l10n_in/models/res_company.py
alrady there is company.py

2023-05-19 15:00 UTC, jco-odoo commented
@jva-odoo @kir-odoo Is this still needed and if yes, -could this be updated so we can merge?  (it should have an upgrade script as well normally)

2023-05-22 04:53 UTC, jva-odoo approved these changes
@jco-odoo LGTM and ready for merged

2023-05-22 09:47 UTC, jco-odoo approved these changes

2023-05-22 09:47 UTC, jco-odoo commented on addons/l10n_in/models/account_invoice.py
> +            payment_url = 'upi://pay?pa=%s&pn=%s&am=%s&tr=%s&tn=%s' % (
Unrelated with this, but it is still weird there is no url_encode/quote needed for this, but I think you said it was ok this way.

2023-05-22 09:47 UTC, jco-odoo commented on addons/l10n_in_upi/__manifest__.py
> -This module adds QR code in invoice report for UPI payment allowing to make payment via any UPI app.
We could add something in the l10n_in manifest as well.

2023-05-22 10:00 UTC, robodoo commented
@kir-odoo @jco-odoo linked pull request(s) odoo/upgrade#4272 not ready. Linked PRs are not staged until all of them are ready.

2023-05-22 15:51 UTC, closed without merging