[FIX] account: journal taken into account
odoo/odoo pull request #111328
Opened 2023-01-30 11:51 UTC by tdetry

This commit fix an issue on moves creation from attachments.

Before, when creating moves from attachment, if no method is found the 'self' journal is not taken into account.

After, the journal found or contained in 'self' is used while creating the move

2023-01-30 11:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111328).

2023-02-03 12:47 UTC, epictete requested changes
Hello @tdetry 
I'm OK with the fix, but why not do it in stable?
Is there a task/ticket you could link?
If not, could you at least provide the steps to reproduce the issue?

2023-02-10 10:56 UTC, tdetry commented
@epictete description updated !

2023-02-14 15:14 UTC, william-andre approved these changes
@robodoo r+

2023-02-14 17:11 UTC, closed without merging