[FIX] web, sale_management: translation button of text field disappears
odoo/odoo pull request #111448
Opened 2023-01-31 11:01 UTC by Jinjiu96

Reproduction:
1. On Odoo 16, install Sales
2. Go to Sales -> Configuration -> Quotation template
3. Click the example “4 person desk”
4. In the “Lines” and “Optional Products” tabs, the translation button is not show in the Description field
5. In Odoo 15, it shows the translation button

Reason: 1. In text_field.xml, the translationButton is not in the same div element. This causes the translation button is hidden when in the tree view. This is the case of the Optional Products tab
2. For the case of Lines, another reason causing this issue is the use of widget “section_and_note_text”

Fix: move the translation button to the same div element with the textarea in text_field.xml; remove the widget “section_and_note_text” from the Lines tab

The adding of div:
https://github.com/odoo-dev/odoo/commit/98e94d45fd6176d7afdcf682c10ce8894f86915a

Rewrite of Text Field js:
https://github.com/odoo-dev/odoo/commit/32bc28aa665c479e31a40afffca2f03f6f2cc805

Rewrite of section_and_note:
https://github.com/odoo-dev/odoo/commit/5a21823f4364d6db407d48178435de041b157b44

opw-3078122

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-01-31 11:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111448).

2023-01-31 12:19 UTC, niyasraphy commented
hi @Jinjiu96 ,
there is an existing pr to correct the position of translation button:  https://github.com/odoo/odoo/pull/111291
thanks

2023-01-31 12:38 UTC, Jinjiu96 commented
> hi @Jinjiu96 , there is an existing pr to correct the position of translation button: #111291 thanks

Thanks for the reminder! I will adjust the pr to only change the widget then! :pray:

2023-01-31 15:26 UTC, Jinjiu96 commented
As discussed with @niyasraphy I will re-include the change we both made to have a cleaner code history and faster review procedure.

2023-02-01 10:38 UTC, nle-odoo approved these changes
looks good to me

the widget `section_and_note_text` doesn't seem to be called: I guess  it's implemented in legacy and not owl => but I don't see much difference in 16.0 vs 15.0 where the widget is called. Just that line and section are edited in one line (but still showed as several lines when we are not editing). (edit: if it was really needed, I guess we would need to implement this widget in owl)

for the change of position of translation icon, this seems like a good change in list view (where it was not visible), but it will also have some effect when the icon was shown eg. in form view:

> ![20230201_11h37m42s_grim](https://user-images.githubusercontent.com/9977887/216020192-a2cf73b8-be4b-48b2-9799-1a7181812948.png)
> ![20230201_11h37m18s_grim](https://user-images.githubusercontent.com/9977887/216020196-cc0039f7-9480-437d-889b-bbc1151c0d01.png)

Maybe for text field we had preferred the rendering on the left in form view.

2023-02-01 11:05 UTC, Jinjiu96 commented
@nle-odoo  Thanks for checking!! :pray: Indeed it will also have changes on the Text field of form views. But I think it's will be also a good change. I did a small test on Odoo 15 for a form view, it has the same rendering with Odoo 16 with the fix, so I think we will prefer the fix on the form view too :smile: 

![2023-02-01_12-02](https://user-images.githubusercontent.com/23055668/216025681-aaa77cec-0e92-4b88-878d-875b13a0c733.png)

2023-02-01 12:02 UTC, brboi requested changes
LGTM ;-)

Please add a test or an assert in the test called "text field translatable"

2023-02-01 18:41 UTC, brboi commented on addons/web/static/tests/views/fields/text_field_tests.js
> +            target.querySelector("[name=txt] textarea").parentElement.childNodes[1].textContent,
```suggestion
            target.querySelector("[name=txt] textarea").nextElementSibling.textContent,

2023-02-02 09:21 UTC, Jinjiu96 commented on addons/web/static/tests/views/fields/text_field_tests.js
> +            target.querySelector("[name=txt] textarea").parentElement.childNodes[1].textContent,
thank youuu! XD

2023-02-02 14:41 UTC, brboi approved these changes
good job

robodoo r+

2023-02-02 16:26 UTC, closed without merging