Update website_robots.xml
odoo/odoo pull request #111533
Opened 2023-01-31 17:25 UTC by benzir123

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-01-31 17:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111533).

2023-01-31 17:54 UTC, rdeodoo requested changes
Hello,

Thanks for your contribution but we won't be able to go further with the current state of this PR.

> Update website_robots.xml
> Fix robots. txt file.

Is not enough (and not correctly formatted) for us to understand what is trying to be achieved here.

Could you please elaborate a bit more?
Note that the sitemap doesn't have to be added in the robots.txt (it can but it's not mandatory and doesn't really change anything if you have a sitemap.xml existing AFAIK)

2023-01-31 17:54 UTC, rdeodoo commented on addons/website/wizard/website_robots.xml
> +                                <code t-translation="off" class='ms-4'>Sitemap: https://www.quality-galore.com/sitemap.xml</code>
`https://www.quality-galore.com` ?

2023-01-31 18:17 UTC, benzir123 commented on addons/website/wizard/website_robots.xml
> +                                <code t-translation="off" class='ms-4'>Sitemap: https://www.quality-galore.com/sitemap.xml</code>
yes

2023-02-01 08:34 UTC, rdeodoo commented on addons/website/wizard/website_robots.xml
> +                                <code t-translation="off" class='ms-4'>Sitemap: https://www.quality-galore.com/sitemap.xml</code>
no

2024-05-17 14:14 UTC, closed without merging