[FIX] website: do not suggest generic pages for existing specific ones
odoo/odoo pull request #111603
Opened 2023-02-01 13:07 UTC by bso-odoo

Before this commit, when obtaining link URL suggestions, both the specific and the matching generic page were suggested.

After this commit, only the most specific ones are kept in the suggested list.
This commit also adapts the sitemap in the same way. In stable, a condition on a dedicated context key is used in case those methods were called with the goal of obtaining both generic and specific pages.
In master, this `__no_generic_if_specific` context key and its related condition should be removed.

Steps to reproduce:
- Edit Contact Us page (to create a specific view)
- Edit the Contact Us menu
- Type "/" in the URL => "/contactus" appeared twice.

task-2968292

2023-02-01 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111603).

2023-02-10 08:50 UTC, bso-odoo commented
@rdeodoo This is ready for review, will be a one-liner in master.

2023-02-13 13:06 UTC, rdeodoo requested changes
IMO this should just be a patch in the `_get_website_pages` method which is actually being the endpoint from every caller patched here.
Add filter_duplicate behavior there as we have for views and assets, weird that we don't have already one

2023-02-13 16:14 UTC, bso-odoo commented
> IMO this should just be a patch in the `_get_website_pages` method which is actually being the endpoint from every caller patched here. Add filter_duplicate behavior there as we have for views and assets, weird that we don't have already one

@rdeodoo Indeed. Done, and retested on runbot.

2023-02-13 16:29 UTC, rdeodoo commented
I meant without the context :)
I don't think there is any good reason to return generic which have specific in `_get_website_pages` ever. At least it was not designed to be the case. Even in 14.0 I'd do it, but let me know if you are not confortable with such a change in 14.0

2023-02-13 17:06 UTC, rdeodoo commented
@qsm-odoo Second opinion needed here. Would you also remove the context condition (and use) as I mentioned in previous message, or would you keep it as such in 14.0?

Note that if we do keep the context, name it `filter_duplicate_page`, it will be more in par with our code (we name such behavior like that :+1: )

2023-02-13 17:30 UTC, qsm-odoo commented
@rdeodoo I am fine with whatever you prefer. If I was the reviewer here, I would probably have merged it like this in 14.0 and removed the context key in 16.0 as per my interpretation of latest FP guidelines (as before 16.0 I would focus on fixing the bug without changing any API, and from 16.0 I would allow myself to make some unlikely-to-break-anything changes to clean a bit the API for new development in the most recent version). But whatever is fine, that one is a gray area. If you ask me tomorrow, I may say it's obvious we should fix the method entirely without context hacks, do as you prefer :shrug:  :wink:

2023-02-13 17:46 UTC, rdeodoo approved these changes
Well, that's a good compromise :+1: 

@robodoo r+
Let's not forget to remove the context in 16.0

2023-02-13 18:43 UTC, robodoo commented
@bso-odoo @rdeodoo staging failed: ci/runbot on f968a083311bc9eb2922e6e62c9e50203d3328dc (view more at https://runbot.odoo.com/runbot/build/23884892)

2023-02-14 07:52 UTC, bso-odoo commented
@robodoo retry

2023-02-14 08:46 UTC, closed without merging