[FIX] web_editor: correctly remove the image gallery snippet
odoo/odoo pull request #111719
Opened 2023-02-02 13:49 UTC by loco-odoo

Steps to reproduce the bug:
- Add an Image Gallery (IG) snippet on the page.
- Add 2 new images in the IG.
- Click on the first image of the IG to load its data.
- Click on the trash button to remove the snippet.
- Bug => The snippet is not removed (An image is removed instead).

When a snippet is removed, a SnippetEditor is created for each element of it. Note that a Promise is resolved when the SnippetEditor is completely created. In the case of the IG, a SnippetEditor is created for each image of the the snippet. Those SnippetEditor are then stored in a SnippetsMenu. That being said, there are two mechanisms that particularly interests us is this case: The first one is the updateCurrentSnippetEditorOverlay function. Its goal is to destroy a snippet each time it target is not in the DOM anymore. The second mechanism is specific to the IG snippet: when an image of this snippet is destroyed, the slideshow function goes through the remaining images to update paramers such as  "data-index".

Here is what happens when a user try to remove an IG snippet: First, a SnippetEditor is beeing created for the second image of the carousel. In parallel of this, the first image of the snippet is removed from the DOM. Due to that, the "slideshow" function will update the attribute of the second image directly in the DOM. This leads to a race condition. Indeed, the target of the SnippetEditor created for the second image has still the old attribute of the image. Due to that, the updateCurrentSnippetEditorOverlay will not detect the second image in the DOM anymore (as its attribute are now changed) and will destroy the SnippetEditor associated to it. However, the destroy of the SnippetEditor will appear before the end of the creation of it so the Promise bound to the completion of the creation the SnippetEditor will not be resolved.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-02 13:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111719).

2023-03-13 09:28 UTC, qsm-odoo commented
@robodoo delegate=detrouxdev

2023-03-16 12:58 UTC, detrouxdev requested changes
Good commit message! 👍🏻 A few comments related to the tour! Don't forget to have a quick look at the utils provided by the website tour utils. Some of them are quite useful!

2023-03-16 12:58 UTC, detrouxdev commented on addons/website/static/tests/tours/snippet_image_gallery.js
> +    trigger: ".o_we_customize_panel we-button[title='Remove Block']",
This step should probably make sure that it targets the Image Gallery's Remove block button. If I'm not wrong, this step could also apply to a single image that we selected right? 🤔

2023-03-17 09:07 UTC, loco-odoo commented
@detrouxdev , thanks a lot for your review :pray: I adapted the code accordingly :+1:

2023-03-17 15:42 UTC, detrouxdev commented
@loco-odoo The test that you introduce does not crash on my computer when I'm launching it with `--test-tags=.test_03_snippet_image_gallery` though it does crash when I'm running it directly with Chrome (doing `odoo.startTour`). Do you have the same issue? I assume it's linked to the fact that this is a race condition. Could you confirm that the test does fail with the fix?

Could you also pass the PR as Ready for review? After that I'll merge it 👍🏻 

Note: during my testing, I've realized that this also fix the issue of deleting a Dynamic Snippet while it's rendering. To test that, drop a dynamic snippet and preview a lot of options by hovering the mouse above them, when the loading appears, click on the remove button. It should lock the editor up.

2023-03-17 16:14 UTC, loco-odoo commented
> The test that you introduce does not crash on my computer when I'm launching it with `--test-tags=.test_03_snippet_image_gallery` without your fix. Though it does crash when I'm running it directly with Chrome (doing `odoo.startTour`). Do you have the same issue? I assume it's linked to the fact that this is a race condition. Could you confirm that the test does fail with the fix?
@detrouxdev I confirm, on my laptop, the test fails when I am launching it without the fix and does not fail when I am launching it it with the fix :+1:

2023-03-17 16:20 UTC, detrouxdev approved these changes
@robodoo r+

2023-03-17 17:30 UTC, closed without merging