[FIX] Fix report_original_vendor_bill with refunds
odoo/odoo pull request #111820
Opened 2023-02-03 10:15 UTC by ito-invest-js

Description of the issue/feature this PR addresses:

There is a bug in the filter used to control only external invoices are included in the list to proceed with report_original_vendor_bill report that raises an unexpected UserError.

Current behavior before PR:

Before commit it you want to print original bills with report_original_vendor_bill and that your list contains a refund it ends up with a UserError "You can only print the original document for vendor bills.".

Desired behavior after PR is merged:

Fixing the filter allows to properly print documents, including refunds.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-03 10:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111820).

2023-02-07 09:07 UTC, FlorianGilbert requested changes
Btw, you are using the wrong tag for CLA please follow the guidelines (https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#tag-and-module-name) 

Thank you for your contribution

2023-02-07 09:07 UTC, FlorianGilbert commented on addons/account/models/ir_actions_report.py
> +        if any(x.move_type not in ('in_invoice', 'in_refund') for x in invoices):
Why changing `in_receipt` for `in_refund`?
You can add it so :)
Please use the helper directly (`is_purchase_document(include_receipts=True)`)

2023-02-27 09:27 UTC, closed without merging

2023-02-28 12:15 UTC, ito-invest-js commented
Improved PR in https://github.com/odoo/odoo/pull/113857