[FIX] l10n_*: add missing tax closing acccounts
odoo/odoo pull request #111960
Opened 2023-02-06 09:13 UTC by dylankiss

*: l10n_ae, l10n_ar, l10n_at, l10n_au, l10n_bg, l10n_br, l10n_ch, l10n_cl, l10n_dk, l10n_es, l10n_hu, l10n_in, l10n_mn, l10n_nl, l10n_no, l10n_pt, l10n_sa, l10n_se, l10n_sg, l10n_si, l10n_uk

Some localizations do not have any default account for tax closing. This leads to the opening of a RedirectWarning when trying to do a tax closing.

This change sets the default tax closing accounts for the localizations mentioned above. Also, the `COUNTRIES_WITHOUT_CLOSING_ACCOUNT` is removed from `TestAllReportsGeneration`, such that these localizations get tested again.

task-3082332

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-06 09:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/111960).

2023-06-05 14:54 UTC, oco-odoo requested changes
Details ^^

2023-06-05 15:00 UTC, dylankiss commented on addons/l10n_ar/data/account.account.template.csv
> +l10n_ar.base_dummy_vat,l10n_ar.l10nar_base_chart_template,9.9.9.99.999,liability_current,Dummy VAT Payable/Receivable Account,False
You're right, "default" does sound better 😄

2023-06-05 15:50 UTC, oco-odoo approved these changes
@robodoo r+

2023-06-05 20:21 UTC, closed without merging