[IMP] point_of_sale: add code on ticket to create invoice
odoo/odoo pull request #112285
Opened 2023-02-09 10:55 UTC by JulienVR

Currently, it is possible to add a QR to generate an invoice for a pos order at a later time (see
https://github.com/odoo/odoo/commit/14183883432e9d35c6240e1d7dc8c51d04cb93db). When scanning the QR, the customer can fill various fields (including potential l10n_* specific fields) and then generate an invoice.

This commit makes it possible to add a 5-digits code on the ticket. A customer can go to `pos/ticket` and fills this code, the date and the order reference written on the ticket. He will then be redirected to the same flow as when scanning the QR code.

task-3178954

2023-02-09 10:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112285).

2023-02-13 13:57 UTC, trj-odoo requested changes

2023-02-13 13:57 UTC, trj-odoo commented on addons/point_of_sale/models/pos_order.py
> +    ticket_code = fields.Char(help='5 digits alphanumeric code to be used by portal user to request an invoice')
This should also be sent back to the front end when we want to reprint an older receipt. Check how it is done for `access_token` in `_export_for_ui`.
This also needs to be sent in the pos_restaurant module when fetching draft orders. Add it in `_get_fields_for_draft_order`

2023-02-13 13:57 UTC, trj-odoo commented on addons/point_of_sale/models/res_company.py
> +        help="Add a a 5-digit code on the receipt to allow the user to request the invoice for an order on the portal.")
typo
```suggestion
        help="Add a 5-digit code on the receipt to allow the user to request the invoice for an order on the portal.")
```

2023-02-13 13:57 UTC, trj-odoo commented on addons/point_of_sale/static/src/js/models.js
> +            this.ticket_code = this._generate_ticket_code(); // 5-digits alphanum code shown on the receipt
we're slowly trying to unify all those js convention styles into one. Could you change those into camelCase ?

2023-02-13 13:57 UTC, trj-odoo commented on addons/point_of_sale/static/src/js/models.js
> +        var code = '';
Prefer `let` over `var` or `const` if you don't intend to reassign the variable
```suggestion
        let code = '';
```

2023-02-27 10:15 UTC, JulienVR commented
Hello @trj-odoo, could you have a look again at this PR ? I also modified the enterprise counterpart following the advice of @sdegueldre. Thank you :)

2023-03-03 11:09 UTC, chklop commented
@trj-odoo we would like to merge this for 16.2. Any additional comment or we can go with what we have ?

2023-03-03 13:05 UTC, trj-odoo commented
Hey, for me it's fine. I don't know if you need to change some minor stuff or not 
I'm off and I see that the enterprise is RED so you can ask rhe to r+ once it's good to go or do it yourself

2023-03-06 10:18 UTC, smetl approved these changes

2023-03-06 13:50 UTC, smetl commented
@robodoo r+

2023-03-06 20:56 UTC, closed without merging