[IMP] account: Improve perf of reconciliation
odoo/odoo pull request #112210
Opened 2023-02-08 13:40 UTC by smetl

Benchmark:
A batch of 1000 payments and a move of 1000 lines to reconcile each payment separately.

Current observed time: +-288s

Improvement:
Adds some context keys when creating the account.full.reconcile to avoid the recomputation of dynamic lines (invoices), synchronization of payments/statement lines and check if the move is well balanced. => +-288s => +-34s

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-08 13:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112210).

2023-02-10 15:20 UTC, Levizar requested changes

2023-02-10 15:20 UTC, Levizar commented on addons/account/models/account_move_line.py
> +                    'reconciled_line_ids': [(6, 0, involved_lines.ids)],
use the `Command.set`

2023-02-10 15:20 UTC, Levizar commented on addons/account/models/account_move.py
> +                exchange_move_ids.add(row[0])
Can't you just set a `SELECT DISTINCT exchange_move_id FROM (subquery)` so we don't need to create a set for this.

2023-02-10 15:20 UTC, Levizar commented on addons/account/tests/test_account_move_entry.py
> +        with self.assertRaises(UserError), self.cr.savepoint():
I think we don't need the `savepoint` here

2023-02-10 15:20 UTC, Levizar commented on addons/account/models/account_bank_statement_line.py
> +                ],
I don't understand why it repeats twice

2023-02-10 15:27 UTC, Levizar commented on addons/account/models/account_bank_statement_line.py
> +                ],
The diff is the `ilike`.
Once it's `=ilike` ---> exact matching
then it's `ilike` ---> with %stuff%

2023-02-10 15:48 UTC, smetl commented
@Levizar r+ plz :D

2023-02-10 16:29 UTC, Levizar commented
@robodoo rebase-ff r+

2023-02-10 16:30 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-02-10 16:30 UTC, robodoo commented
@Levizar you may want to rebuild or fix this PR as it has failed CI.

2023-02-10 18:34 UTC, Levizar commented
I just removed the trailing space in the query

2023-02-10 18:34 UTC, Levizar commented
@robodoo rebase-ff r+

2023-02-10 18:35 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-02-10 19:23 UTC, smetl commented
@Levizar Thank you! :D

2023-02-10 20:12 UTC, Levizar commented
@smetl ;)

2023-02-10 21:06 UTC, closed without merging