[FIX] account: enable menu addition through studio
odoo/odoo pull request #112330
Opened 2023-02-09 14:17 UTC by joanna350

1. Install [Accounting], [Studio] on Apps
2. Enter [Accounting]
- Click the Studio icon second to left on the top right corner
- [Edit Menu]
- [NEW MENU]
- Fill in e.g.`Test`, select [Existing Model], Model: Payment Methods
- Click the icon on the right, check it is `account.payment.method`
- [SAVE & CLOSE]
- [CONFIRM]
- [CLOSE]
3. Click on `Test` menu created next to [Configuration]
- [NEW]
- Type in all info, click to Save
- Error

Impacted versions: 15-master

opw-3148453

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-09 14:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112330).

2023-02-09 14:37 UTC, nle-odoo approved these changes
Hi


As far as I can tell, the scenario seems to not be a bug. It is doing something wrong in something very technical thanks to studio, but usually this error would happen when you are developing an adding a payment method and did something wrong, for example by adding:

```py
        <record id="account_payment_method_test" model="account.payment.method">
            <field name="name">This is a test</field>
            <field name="code">Test</field>
            <field name="payment_type">outbound</field>
        </record>
```
that would result in the same error but at the module installation I think.

As far as I can tell there is 3 solutions:

- doing nothing => the user did a very technical thing wrong, it makes sense he has an error

- doing what you did => if we want to allow to have a wrong code, allow it (but I think it would break in other locations, for example in `_get_payment_method_domain` it seems we are also expecting to have a valid code)

- instead of ignoring an invalid code, raising a more readable error

I'm not sure what's the best solution is functionnaly.

2023-02-21 13:38 UTC, tdetry approved these changes

2023-02-27 09:44 UTC, Levizar requested changes
Hello @hale-odoo ,

### Regarding the ticket:
I think it would be a good idea to ask the customer why he is doing that flow.
I have the feeling that he should just create an `account.payment.method.line` with its `account.payment.method` set as `Manual`.

### Regarding the PR itself:
 I don't think we should add this `UserError`. We aren't helping the user with it as it triggers even more questions:
- What does "Cannot add payment methods without valid information" exactly mean?
- What are the invalid informations? 
- What should the user do to make it work?

### What we should do:
`account.payment.method` is something linked to some hardcoded stuff and shouldn't be created manually. That's why we didn't create any menu to access it.

I think the proper fix would be to remove the create right on this model which would prevent users to even be able to create such record and to reach those lines of code.
This should be done as of 14.0.
https://github.com/odoo/odoo/blob/14.0/addons/account/security/ir.model.access.csv#L108

2023-02-27 12:49 UTC, Levizar commented
>  Modifying security rights could be a possibility

Do you plan to do it or should we take care of it?

2023-02-27 16:14 UTC, closed without merging