[IMP] web_editor: show drag & drop tooltip helper faster
odoo/odoo pull request #112408
Opened 2023-02-10 12:23 UTC by rdeodoo

Before this commit, if the user mousedown a snippet, it would start a timer of 1500 ms and a the end of the timer, it would show a tooltip to help the user indicating him that he should drag & drop and not click. The drag & drop code would (sort of) stop that timer if a drag was detected, to not show the tooltip if the user is correctly drag & dropping.

But it feels weird, as when you fail to realize you should drag & drop but click instead, you only have the hint 1.5s later. Some people internally when trying to show this tooltip would actually use triple click on snippet, because it's probably not easy to figure exactly what the trigger is.

The change is then made to show the tooltip directly on mouseup. If the drag & drop code did not indicate that a drag happened, we can safely assume it was a simple click and not a drag.

2023-02-10 12:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112408).

2023-02-10 17:39 UTC, rdeodoo commented
@qsm-odoo Following https://discord.com/channels/678381219515465750/687337739129323543/1073573362267344947
I kinda agree, thought the same but as it's minor anyway never really dig into that.
As we can indentify right away (well, when the click is released) if it's a click or a drag, there is no reason to not show the tooltip right away: we know if the user failed and there is no risk of "false positive" that would noise real drag & drop.

All in all it seems smoother with no downside, and every "corner cases" seems to behaves nicely (listing those as those were problematic during the dev, easy to retrieve and check if something has to be changed):
- triple click
- spam click the same snippet
- spam click between multiple snippets

2023-02-10 17:43 UTC, rdeodoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +     * TODO: remove delay param in master
Maybe one can argue about compatibility/custom code:
- the now ignored delay param (could have kept it in the code and make the caller specify 0 instead)
- the now gone `__showSnippetTooltip`

Seems reasonable as-is for me, given the private internal & niche methods.

2023-02-13 14:00 UTC, qsm-odoo requested changes
Commit message: maybe just me but I bugged on the sentence "Some people internally when trying to show this tooltip would actually use triple click on snippet", I'd use "internal people" instead of "people internally would" and I'd put the "when" part at the end.

Note: I should definitely merge this at some point https://github.com/odoo/odoo/pull/77460 ... but needs rebase/rework/etc, need to find the time... like many others. Meanwhile, this can be merged of course :)

2023-02-13 14:28 UTC, rdeodoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +    _onMouseUp(ev) {
Outch, definitely yeah. Shouldn't have missed that.

2023-02-13 14:31 UTC, rdeodoo commented
Adapted, ty :+1:

2023-02-14 10:46 UTC, qsm-odoo approved these changes
Strange I did not implement it like that in the first place... hopefully there was a reason :grimacing: 

@robodoo r+ :+1:

2023-02-14 12:18 UTC, closed without merging