[FIX] l10n_in: Place of supply provision for Indian companies
odoo/odoo pull request #112616
Opened 2023-02-14 08:51 UTC by joanna350

1. Install [Expenses], [Indian - Accounting], [Accounting] on Apps
2. [Settings] [Users & Companies] [Companies]
- create a company based in India with address there
3. Enter [Expenses], [CREATE]
- create and add an employee w contact info (private address) in India
- set paid by: Company, write an amount, category > [CREATE REPORT]
- [SUBMIT TO MANAGER] [APPROVE] [POST TO JOURNAL ENTRIES]
4. Click on the [Journal Entry] created at the top right corner

Issue: No Place of Supply which hinders the client

Resolve by: providing one by default and enable their further revision

Impacted versions: 16.0 up to master

opw-3168426

2023-02-14 08:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112616).

2023-02-16 15:00 UTC, nle-odoo approved these changes
looks good to me

first version seems also a good solution if we want to keep the required attribute like currently: https://github.com/odoo/odoo/commit/bc36219bcdbf4625ddf4f7e560f2c712496b9629

and maybe we could use move_type instead of adding a new related field journal_type.

note: I think in general it's better to prefix a field with l10n_in_ if it's available only in l10n_in_ module (the alternative would be to add the field in accounting module).

2023-02-17 12:02 UTC, jva-odoo requested changes
No need to create field for this

2023-02-17 12:02 UTC, jva-odoo commented on addons/l10n_in/views/account_invoice_views.xml
> +                    attrs="{'invisible': ['|', ('country_code', '!=', 'IN'), ('move_type', '=', 'entry')], 'required': [('country_code', '=', 'IN'), ('move_type', '!=', 'entry'), ('l10n_in_journal_ty
```suggestion
                    attrs="{'invisible': ['|', ('country_code', '!=', 'IN'), ('move_type', '=', 'entry')], 'required': [('country_code', '=', 'IN'), ('move_type', '!=', 'entry'), ('journal_id.type', 'in', ('sale', 'purchase'))], 'readonly': [('state', '!=', 'draft')]}"/>
```

2023-02-17 12:02 UTC, jva-odoo commented on addons/l10n_in/models/account_invoice.py
> +    l10n_in_journal_type = fields.Selection(related='journal_id.type')
```suggestion
```

2023-02-20 05:04 UTC, jva-odoo commented on addons/l10n_in/views/account_invoice_views.xml
> +                    attrs="{'invisible': ['|', ('country_code', '!=', 'IN'), ('move_type', '=', 'entry')], 'required': [('country_code', '=', 'IN'), ('move_type', '!=', 'entry'), ('l10n_in_journal_ty
@yes, my bad, it only works in the `domain`, not in `attrs`.

2023-02-20 05:05 UTC, jva-odoo approved these changes

2023-02-20 08:57 UTC, rigr-odoo approved these changes

2023-02-20 15:50 UTC, jco-odoo commented
@tsb-odoo @qdp-odoo @jva-odoo I don't think it makes sense to have a place of supply on other account moves than sale or purchase.  We do need it there however and with this fix, the logic of the compute and the view are the same.  (and we do not set a field on moves where it is not needed, taking unnecessary space in the database)

2023-02-20 15:50 UTC, jco-odoo commented
@robodoo r+

2023-02-20 18:23 UTC, pimodoo commented
@robodoo r-

Your PR is breaking the stagings: https://runbot.odoo.com/runbot/build/24166456

2023-02-21 05:16 UTC, jva-odoo commented
@pimodoo @jco-odoo we need to do something about this we create PR for localization then runbot auto active a test for that localization.
what did you say?

CC: @odoo/rd-runbot

2023-02-21 08:52 UTC, jva-odoo commented
@hale-odoo you do one thing that you can remove required and raise error when sending E-invoice, E-waybill, and GST return

2023-02-21 12:22 UTC, jco-odoo commented
@robodoo r+

2023-02-21 14:06 UTC, closed without merging