[FIX] website_sale_digital: let salesman download digital via portal
odoo/odoo pull request #112639
Opened 2023-02-14 12:00 UTC by yelizariev

Portal shows all Sale Orders available for current user. For example, salesman can see his sales. If such a user can download digital files via product form in backend, it makes sense to let user download them via SO page on portal. However, it wasn't the case because /my/download requires product be purchased by current user [1]. Fix it by checking read access first.

STEPS

* in backend create SO with digital product (customer must be different from current user)
* create invoice and register a payment
* navigate to portal  (without using customer's token),
* open SO, click download on digital product

[1]: https://github.com/odoo/odoo/blob/1a24477fab4dd323cf94c010321d8942fb2c1a01/addons/website_sale_digital/models/account_invoice.py#L14-L22

opw-3144600

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-14 12:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112639).

2023-04-21 12:30 UTC, Demesmaeker reviewed
Hello!

We don't exactly like the if... pass. Wouldn't it be better to make the access check in a variable and use that in the condition instead? It'd be clearer IMO

2023-04-24 11:52 UTC, AntoineVDV requested changes

2023-04-24 11:52 UTC, AntoineVDV commented on addons/website_sale_digital/controllers/main.py
> +        if request.env['ir.attachment'].search([('id', '=', int(attachment_id))]):
I, too, find it confusing to skip the redirects with a `if: pass`.

Also, it's important that the security check is obvious to the reader. Here, it's not immediate that `.sudo()` is omitted on purpose from the `search` call while it was necessary with the `search_read` call. Instead, could you please use `check_access_{rights,rules}` to make the check obvious?

2023-04-28 10:36 UTC, yelizariev commented
@Demesmaeker @AntoineVDV 

I made explicit check for reading access.

I got rid of `if: pass`, but it requires a bigger diff. Let me know if you have a better idea

2023-05-03 12:08 UTC, Demesmaeker requested changes
Hello :slightly_smiling_face: 
This might be easier and clearer

2023-05-03 15:12 UTC, Demesmaeker commented on addons/website_sale_digital/controllers/main.py
> +            pass
Another solution would be to put this in the except directly and take off the `has_read_access` variable.
This'd make a bigger diff, but it'd also be coherent. Both are fine IMO.

2023-05-03 16:14 UTC, AntoineVDV commented
@robodoo delegate=Demesmaeker

2023-05-03 16:23 UTC, AntoineVDV approved these changes

2023-05-03 16:24 UTC, Demesmaeker commented
Hello @yelizariev :slightly_smiling_face: 
Since it was easier to force-push than explain what we had in mind, we directly did it. Have a nice day =]

2023-05-03 17:44 UTC, closed without merging