[FIX] website: make wysiwyg fonts independent from iframe fonts
odoo/odoo pull request #112759
Opened 2023-02-15 09:42 UTC by bso-odoo

Since the edited page is within an iframe, the built-in fonts used by the wysiwyg are also loaded inside the page within the iframe, which causes them to replace the one used when viewing the page as a visitor if it happens to be one of the fallback fonts.

This commit avoids that by giving a distinct `font-family` to the fonts used by the wysiwyg.

task-3080104

2023-02-15 09:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112759).

2023-02-16 14:39 UTC, bso-odoo commented
@rdeodoo Ready for review, but I fear this will be perceived as overkill...

2025-06-06 08:44 UTC, qsm-odoo requested changes
@bso-odoo Finally having a look at this one.

> Since the edited page is within an iframe, the built-in fonts used by
the wysiwyg are also loaded inside the page within the iframe

In fact... is not that the issue? :thinking: Why are we loading all the fonts inside the iframe? Don't we need them only outside of it? Once you apply one in your theme, the CSS is reloaded anyway, no?

2025-06-10 12:14 UTC, bso-odoo commented
> In fact... is not that the issue? 🤔 Why are we loading all the fonts inside the iframe? Don't we need them only outside of it? Once you apply one in your theme, the CSS is reloaded anyway, no?

@qsm-odoo The issue is not related to the edition itself and having the fonts refreshed with the updated CSS. It happens by simply accessing website as a connected user (i.e. with the iframe). At the time of writing this fix, there seemed to be an issue when a font had the same name in both the iframe's CSS and the main document's CSS - which is the case for the system font.
Note that the symptom only seems to appear in 16.0 and 17.0 - I could not reproduce it in 18.0 nor later... maybe we should forget about this purely cosmetic fix.

2025-06-10 13:57 UTC, qsm-odoo commented
@bso-odoo 

> maybe we should forget about this purely cosmetic fix.

No, I think this is important... we are supposed to be WYSIWYG :wink: 

> I could not reproduce it in 18.0 nor later

That's because, by default, we are not using system fonts anymore... but the user can still enable them.

> The issue is not related to the edition itself 

I know :)

> At the time of writing this fix, there seemed to be an issue when a font had the same name in both the iframe's CSS and the main document's CSS

I don't think so, I think we just really put the loaded fonts in the iframe for no apparent reason and that is the issue. See:
![image](https://github.com/user-attachments/assets/2428775f-7df1-4b58-8546-4e822e3c7506)
With a red border is an extra iframe I added by hand, loading the same URL as the "normal" one below. See that the titles in my iframe are correct compared to the default iframe. It must really be because we are injecting something we should not in the standard iframe.

2025-06-11 11:52 UTC, bso-odoo commented
@qsm-odoo I adapted the solution so that it relies on distinct bundles instead. The various references to the bundle actually could be updated as needed too.

2025-06-11 14:35 UTC, qsm-odoo approved these changes
Nice, better late than never, sorry for the delay :upside_down_face: 

I push-forced to add a bunch of comments and review the commit message a bit (especially the title, to explain what the fix is about, not how it was fixed :wink:)

@robodoo r+

2025-06-11 17:17 UTC, closed without merging