[FIX] website: restore the use of the speed paramter for the IG snippet
odoo/odoo pull request #112796
Opened 2023-02-15 13:19 UTC by loco-odoo

Steps to reproduce the bug:
- On the website application, add an image gallery (IG) snippet.
- Change the "Speed" parameter.
- Save -> Nothing happens: The displayed image is always the first one and there is no cycle between the images of the snippet.

opw-3165570

2023-02-15 13:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112796).

2023-02-20 07:58 UTC, loco-odoo commented
@qsm-odoo, just in case you missed this one.

2023-02-20 13:48 UTC, qsm-odoo requested changes

2023-02-20 13:48 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_image_gallery/options.js
> +        // TODO in master : replace 'data-interval' by 'data-bs-interval'.
Why doing that part in master, is not it broken when using data-internal? :thinking: Worst case you could do "bsInterval or interval" but here it's option's js combined to the `website.gallery.slideshow` which is static and already using bs-interval anyway, I don't see why you cannot fix it directly :)

2023-02-20 13:48 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_image_gallery/options.js
> +    },
Instead of patching the method behavior, you can patch the received template before it is used (see `_patchForComputeSnippetTemplates`)

2023-02-21 12:30 UTC, qsm-odoo approved these changes
@robodoo r+

2023-02-22 11:46 UTC, closed without merging