[FIX] core: try import geoip2 for iot
odoo/odoo pull request #112915
Opened 2023-02-16 15:41 UTC by qle-odoo

The geoip2 module is not installed in the iot so this one cannot launch Odoo. This module is not used by the iot so it is not necessary to install the module in the iot and therefore to make a new build

From this commit c59750d8244068e191a78631f8e0fd3d09067e3d

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-16 15:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112915).

2023-02-17 10:55 UTC, Julien00859 requested changes
This doesn't seem a good idea to me. Together the two lib are 500Ko of code (including `__pycache__`), you don't need to download the databases (that weight more) but geoip is now a core dependency

2023-04-07 12:44 UTC, qle-odoo commented
> This doesn't seem a good idea to me. Together the two lib are 500Ko of code (including `__pycache__`), you don't need to download the databases (that weight more) but geoip is now a core dependency

Yes I understand, but my concern is that I have to make a new build of iot just because there is this new useless dependency in the use of iot.
So users will have to reflash or upgrade their box just for this dependency.

2023-04-07 18:34 UTC, Julien00859 commented
aller, jvais arrêter de casser les couilles hein... au pire j'aurai des issues à gérer du type "None type has no ..." et je devrai répondre "installez geoip", c'est un peu moins explicite comme erreur mais soit...

@robodoo r+

2023-04-07 18:34 UTC, robodoo commented
@Julien00859 you may want to rebuild or fix this PR as it has failed CI.

2023-04-07 18:52 UTC, Julien00859 commented
@robodoo r- delegate+

2023-04-11 14:32 UTC, closed without merging