[IMP] calendar: Make calendar edit more restricted
odoo/odoo pull request #112964
Opened 2023-02-17 09:31 UTC by fdamhaut

This task change the people who can edit a calendar event. This calendar event currently allow every user to modify every event in the calendar. This cause issue where one user can modify the time-off event for other employees.

This PR change the right to modify an event from the calendar view in the calendar app. With these changes, only the people attending an event will be able to modify it from the calendar view.

task-id : 3185743

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-17 09:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/112964).

2023-04-04 14:30 UTC, leonardopavanrocha requested changes

2023-04-04 14:30 UTC, leonardopavanrocha commented on addons/calendar/views/calendar_views.xml
> +                                    <label for="duration" attrs="{'invisible': [('allday','=',True)], 'readonly': [('user_can_edit', '=', False)]}"/>
same

2023-04-05 14:14 UTC, leonardopavanrocha approved these changes
Thanks for your work! LGTM

2023-04-06 10:01 UTC, brboi approved these changes
OK for changes in `@web/views/calendar`
I also had a look at `@calendar/views/attendee_calendar` and it is fine ;-)

2023-04-11 10:21 UTC, arj-odoo commented
@robodoo r+

2023-04-11 12:12 UTC, robodoo commented
@fdamhaut @arj-odoo staging failed: ci/runbot on ce34b3e6f1d3b1a9e158e17af6a0c34ef17339db (view more at https://runbot.odoo.com/runbot/build/29685986)

2023-04-12 13:57 UTC, arj-odoo commented
@robodoo r+

2023-04-13 08:36 UTC, arj-odoo commented
I will create an enterprise branch. This PR is breaking some enterprise tests.

2023-04-26 14:42 UTC, arj-odoo commented
@robodoo r+

2023-04-27 02:30 UTC, robodoo commented
@fdamhaut @arj-odoo staging failed: ci/runbot on 1fadb0bcc24f9067413a5e90c22475c85a2b8c38 (view more at https://runbot.odoo.com/runbot/build/32359005)

2023-04-28 07:40 UTC, arj-odoo commented on addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.js
> +        }
I had to adapt this piece of code to avoid trigger traceback in the appointment test.

2023-05-03 11:41 UTC, arj-odoo commented
@robodoo r+

2023-05-03 13:04 UTC, closed without merging

2024-08-26 07:49 UTC, tde-banana-odoo commented
Hello,

Related to an improvement in appointment (https://github.com/odoo/enterprise/pull/63046/files whoich is still a WIP) I found this PR which I find a bit curious. Why are we adding a "can edit" field that does not really follow the security rules ? In the end, it should be implemented using check_access_rights/rules (and maybe the ``_filter_access_rules_python`` for the compute). You are speaking about preventing people to change values but I don't see changes in ACLs, which is why I wonder if there is something else :) .

Cheers,