[FIX] account: add a unique constraint on report line expressions
odoo/odoo pull request #113222
Opened 2023-02-21 10:41 UTC by epictete

Currently, when editing a report line, it's possible to create a new expression with a label already used on the same report line.

This is problematic as the columns are using the expression label to select the right expression. Indeed, one expression is going to be selected but there isn't any obvious way to guess which one.

The solution is to add an SQL constraint on the report line expression.

task-3199014

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-21 10:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/113222).

2023-02-21 10:56 UTC, Levizar approved these changes
LGTM

2023-02-21 12:01 UTC, oco-odoo requested changes

2023-02-21 12:01 UTC, oco-odoo commented on addons/account/models/account_report.py
> +            "The expression label must be unique per report line !"
Globally speaking, we tend to avoid using exclamation marks in error messages ; they make them a little to aggressive ^^

2023-02-21 12:01 UTC, oco-odoo commented
For once it's done: 

@robodoo delegate+

2023-02-21 12:18 UTC, epictete commented
@robodoo r+

2023-02-21 14:17 UTC, Feyensv commented
Seems to be failing deterministically on enterprise :thinking: 
https://runbot.odoo.com/runbot/build/24207620
https://runbot.odoo.com/runbot/build/24204880

2023-02-21 14:57 UTC, Feyensv commented
@robodoo r-

2023-02-23 12:30 UTC, epictete commented
Thanks for the heads up @Feyensv 
Problem solved here : https://github.com/odoo/odoo/commit/7e0bfb5efd7df1d9d24dc93d3d477104b0969bac
@robodoo r+

2023-02-23 15:08 UTC, closed without merging