[FIX] mrp: rounding total amounts before splitting
odoo/odoo pull request #113346
Opened 2023-02-22 09:34 UTC by lnkphm

Description of the issue/feature this PR addresses:
This PR fixes issue when sum of values in `amounts` is not necessary equal to production quantity because of float rounding (like `0.1 + 0.2 != 0.3`), so new value is added to `amounts` even if the difference is insignificant. This will lead to unable to create new MOs from that.

Current behavior before PR:

Desired behavior after PR is merged:
- Rounding the sum of `amounts` before comparing with production quantity

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-22 09:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/113346).

2023-03-01 09:03 UTC, davidtranhp requested changes

2023-03-06 05:01 UTC, lnkphm commented
@davidtranhp @tranngocson1996 @amoyaux @nle-odoo sorry for the annoying ping, but what do you think about this PR?

2023-03-06 06:53 UTC, tranngocson1996 approved these changes

2023-03-14 16:28 UTC, Whenrow commented
Hello. We made this [PR](https://github.com/odoo/odoo/pull/114563) from version 15.2 .I guess we could backport it in v14 and v15

2023-03-14 16:56 UTC, lnkphm commented
> Hello. We made this [PR](https://github.com/odoo/odoo/pull/114563) from version 15.2 .I guess we could backport it in v14 and v15

@Whenrow Thank you for your mention, but I think the PR you mention here is missing the case this PR means to, which is the first condition of the `if` statement.

2023-03-15 08:19 UTC, Whenrow commented
@lnkphm You are right. It's better to use the `float_compare()` everywhere. Thanks 
robodoo r+

2023-03-15 09:47 UTC, closed without merging