[IMP] website_forum: missing-space-between-number&text-ravb
odoo/odoo pull request #113480
Opened 2023-02-23 09:36 UTC by ravb-odoo

`website_forum` module has missing space between number and text in forum's heading when any one give answers

fix:
add space manually between text and number in website_forum templates.

2023-02-23 09:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/113480).

2023-02-23 10:46 UTC, rdeodoo requested changes
Saw this one passing by, checked by curiosity.

Same bug for comment..
![image](https://user-images.githubusercontent.com/30048408/220884870-43fe9dc8-3ce6-4006-9e9d-579a6468fb58.png)

Same but for multiple answers..
![image](https://user-images.githubusercontent.com/30048408/220885053-c4a15a4b-67bd-4e54-9ed7-d7dca311b654.png)

2023-02-23 10:46 UTC, rdeodoo commented on addons/website_forum/views/website_forum.xml
>                  <t t-else="">Answers</t>
You fixed the `Answer` line but not the `Answers` line just below

2023-02-28 11:02 UTC, rdeodoo commented
@Gorash Hello, we have the same issue everywhere, eg on blog
![image](https://user-images.githubusercontent.com/30048408/221835211-5b7c2d81-092f-4c19-8aa4-26c8d3fded46.png)
Was working fine before 16.0, eg 14.0:
![image](https://user-images.githubusercontent.com/30048408/221835276-6712d743-eaf2-401e-b67f-f68e6cc6cb96.png)

DOM hasn't changed since: https://github.com/odoo/odoo/blame/d594069767cb0f48c829a25f33abc6da620e7235/addons/website_blog/views/website_blog_posts_loop.xml#L43

Seems like a bug in the qweb rendering behavior?

2023-03-06 11:28 UTC, rdeodoo commented
Definitely a bug in the qweb rendering.
I isolated the cause, it seems to be because of the `t-if/t-else` instruction, see
![image](https://user-images.githubusercontent.com/30048408/223097947-8db432ae-cdea-4d32-b7ed-8f9a414a0ef9.png)
15.0:
![image](https://user-images.githubusercontent.com/30048408/223097979-cd4e08ce-bc4c-4b92-9561-b405b786ec0b.png)
16.0:
![image](https://user-images.githubusercontent.com/30048408/223098029-a2b08711-018f-418a-852c-435ba6e2b3ed.png)

2023-03-06 12:29 UTC, Gorash commented
Thanks for the analysis, it's the qweb. A request to remove all line breaks and indentation. It doesn't seem to have the desired behavior in this case (for t-if dirrective, _compile_directive_if).

2023-03-13 07:05 UTC, kcv-odoo commented
Already Fixed in https://github.com/odoo/odoo/pull/114475 so closing this one. Thank you @rdeodoo for review and Thank you @Gorash for fix :slightly_smiling_face:

2023-03-13 07:05 UTC, closed without merging