[IMP] account: add payment onboarding step
odoo/odoo pull request #114131
Opened 2023-03-02 10:01 UTC by anko-odoo

To improve onboarding experience, configuring Stripe has been added in Invoice onboarding process.
For db with other apps(ecommerce or sales) if onboarding is done in one place it is considered done in other places with exclusion of Sales, unless it was done in Sales.

task-3208045

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-02 10:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114131).

2023-03-20 09:35 UTC, chevalierv approved these changes
LGTM :+1:

2023-04-11 15:04 UTC, epictete reviewed
Looks good to me :ok_hand: 
But I think these changes should be made in `account_payment` instead of `account` :slightly_smiling_face:

2023-04-12 13:12 UTC, anko-odoo commented
@epictete Hm, it could be done, but maybe it is a bit of an overkill for such small changes. @chevalierv I would really appreciate your opinion on that.

2023-04-12 14:51 UTC, epictete commented
@anko-odoo What do you mean, overkill?
The changes are the same, they will just be located in another module :thinking: 
All the fields and methods you are using/referencing are located either in `payment` or `account_payment`, so why put your code in `account`?

2023-04-14 09:40 UTC, AntoineVDV requested changes
Hello, this should indeed be moved to `account_payment`.

2023-05-02 10:16 UTC, AntoineVDV approved these changes
@robodoo r+

(runbot is red because of a failing test in the JS framework, but it'll go through eventually)

2023-05-02 10:16 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2023-05-03 11:55 UTC, closed without merging