[IMP] l10n_au: update fiscal year last day, label display, etc
odoo/odoo pull request #114118
Opened 2023-03-02 03:42 UTC by tong-odoo

task-3187734

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-02 03:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114118).

2023-03-06 11:18 UTC, vin-odoo requested changes
I have a few comments for you :)

2023-03-07 06:18 UTC, tong-odoo commented on addons/l10n_au/views/res_company_views.xml
> +            </field>
Sure I will update it once vat_label is deployed to 16

2023-03-07 06:30 UTC, tong-odoo commented
Hi @vin-odoo. Thanks for the review! I have updated the PR based on the comments. Please take a look :smile:

2023-03-14 08:22 UTC, vin-odoo approved these changes
The tasks about labels aren't moving as fast as I would like, so let's merge this one and I'll update it later if we ever release them :smile: 

Thank you for the nice work :)

@robodoo r+

2023-03-14 09:28 UTC, closed without merging