[IMP] hr_recruitment : Improve the UX of recruitment app
odoo/odoo pull request #114342
Opened 2023-03-03 16:26 UTC by jugj-odoo

task - 3175879

2023-03-03 16:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114342).

2023-03-24 09:59 UTC, sofiagvaladze requested changes
@jugj-odoo good job  :raised_hands: 

As discussed here are some point, as we are targeting the stable, we need to take extra care of some changes. 

Thanks!

2023-03-24 09:59 UTC, sofiagvaladze commented on addons/hr/views/hr_job_views.xml
> -                                        <field name="company_id" options="{'no_create': True}" groups="base.group_multi_company"/>
As we discussed, we can't just remove the field from the view in stable, cause that might break customization. Instead what we could do is add `invisible="1"` to it :bulb: 

Applies to this and all the other places that we remove field from the view

2023-03-24 09:59 UTC, sofiagvaladze commented on addons/hr_recruitment/models/hr_recruitment.py
> +    priority = fields.Selection(AVAILABLE_PRIORITIES, "Evaluation", default='0')
.pot here and at other places as well where we add or change the text :innocent:

2023-03-24 09:59 UTC, sofiagvaladze commented on addons/hr_recruitment/views/hr_recruitment_views.xml
> -            <form string="Create a Job Position" class="o_hr_job_simple_form" >
Unnecessary change, especially in stable :innocent:

2023-03-24 12:28 UTC, sofiagvaladze commented
@jugj-odoo thanks for the changes :raised_hands: 

Didn't notice on the first go, final comment from me - the commit messages (community and enterprise) does not reflect all the modules that are affected by the commit, could you change it? :innocent: 

Thanks!

2023-04-25 08:34 UTC, kba-odoo requested changes

2023-05-08 14:18 UTC, kba-odoo commented
robodoo r+

2023-05-08 21:00 UTC, robodoo commented
@jugj-odoo @kba-odoo linked pull request(s) odoo/enterprise#37775 not ready. Linked PRs are not staged until all of them are ready.

2023-05-09 09:21 UTC, kba-odoo commented
robodoo r+

2023-05-09 12:29 UTC, closed without merging