[REM] account: remove tax_audit field
odoo/odoo pull request #114616
Opened 2023-03-07 17:31 UTC by moerradi

remove tax_audit field from account move line

Task-id: 3196711

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-07 17:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114616).

2023-03-08 07:56 UTC, rugo-odoo requested changes

2023-03-08 07:56 UTC, rugo-odoo commented on addons/account/i18n/account.pot
> -
You don't need to this on any of the `.po` files on master. The way it works on **master** is that each time you have a new version, all the `.po` and `.pot` files are exported again and we create a transiflex project. So all unused fields are automatically removed.

2023-03-08 07:56 UTC, rugo-odoo commented on addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
> -    )
You can not do that. We don't touch at previous upgrades scripts unless there was a mistake on them. What you need to do is create a new update script in which you remove the field `tax_audit`. (It is mentioned on the red runbot.)

2023-03-08 07:56 UTC, rugo-odoo commented on addons/l10n_es/upgrades/15.0.5.0/post-61-tag-split-2021.py
> -        """, [old_tag.name, f"{new_tag.name}:", new_tag.id])
Same.

2023-03-08 07:57 UTC, rugo-odoo requested changes
Also improve you pr message. Why are you removing it ? It doesn't need to be long or detailed but as it is, it's not enough.

2023-03-17 13:40 UTC, moerradi commented
@rugo-odoo  finally XD

2023-03-21 18:54 UTC, closed without merging