[FIX] account: fix fiscal country compute
odoo/odoo pull request #114683
Opened 2023-03-08 12:55 UTC by clbr-odoo

The fiscal country was changed each time the user modified his
company's country. This caused problems (in particular at onboarding)
because it was not done transparently for the user and possibly
overrides his setup.

After this commit, the fiscal country will behave like this:
- When we install Invoicing/Accounting, it is set by default to company's country
- When we install CoA, it is set to the CoA's country, if there is one (override above setting)
- It is **no longer automatically changed** when the company's country changes.

Task: 3221792
Enterprise: https://github.com/odoo/enterprise/pull/37923

2023-03-08 12:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114683).

2023-03-21 10:05 UTC, oco-odoo requested changes
One very small detail ^^

2023-03-21 10:28 UTC, clbr-odoo commented
@oco-odoo Thanks. Fixed also in the related Enterprise PR :)

2023-03-21 11:04 UTC, oco-odoo approved these changes
@robodoo r+

2023-03-21 12:01 UTC, robodoo commented
@clbr-odoo @oco-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-03-21 13:53 UTC, oco-odoo commented
@robodoo r+

2023-03-21 18:04 UTC, closed without merging