[IMP] l10n_ar: taxes
odoo/odoo pull request #114741
Opened 2023-03-09 08:45 UTC by malb-odoo

We want to invigorate a Tax Name Taxonomy so that tax names are as codified as possible. This allow for a better display on Invoice Description, and allowed us to implement a smart name_search.

In this PR, we change the taxes name so that it's more clear for the users

task-id: 3052677

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-09 08:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/114741).

2023-05-10 14:12 UTC, oco-odoo requested changes

2023-05-10 14:12 UTC, oco-odoo commented on addons/l10n_ar/data/template/account.tax-ar_base.csv
> +ri_tax_percepcion_iibb_tf_sufrida,"0% IIBB T F I","Perception IIBB Tierra del Fuego incurred","Perc IIBB Tierra del Fuego S","4","fixed","1.0","purchase","tax_group_percepcion_iibb_tf","base","invoic
Same here, it's not a 0% tax ; it's fixed with an amount of 1.0

2023-05-10 14:14 UTC, malb-odoo commented on addons/l10n_ar/data/template/account.tax-ar_ex.csv
> +ri_tax_percepcion_ganancias_sufrida,"0% E I","Perception Earnings incurred","Perc Profit S","4","","fixed","1.0","purchase","tax_group_percepcion_ganancias","base","invoice","","Percepción Ganancias
Yep you're right it's a mistake, my bad will correct that now :+1:

2023-05-10 15:45 UTC, oco-odoo requested changes
few more things ... Blame bib ! :p

2023-05-10 15:45 UTC, oco-odoo commented on addons/l10n_ar/data/template/account.tax-ar_base.csv
> +ri_tax_percepcion_iibb_ct_sufrida,"1% IIBB C I","Perception IIBB Chubut incurred","Perc IIBB Chubut S","4","fixed","1.0","purchase","tax_group_percepcion_iibb_ct","base","invoice","","Percepción IIBB
Name clash with ri_tax_percepcion_iibb_co_sufrida :/

2023-05-10 15:45 UTC, oco-odoo commented on addons/l10n_ar/data/template/account.tax-ar_base.csv
> +ri_tax_percepcion_iibb_mi_sufrida,"1% IIBB M I","Perception IIBB Misiones incurred","Perc IIBB Misiones S","4","fixed","1.0","purchase","tax_group_percepcion_iibb_mi","base","invoice","","Percepción
Name clash with ri_tax_percepcion_iibb_za_sufrida

2023-05-10 15:45 UTC, oco-odoo commented on addons/l10n_ar/data/template/account.tax-ar_ex.csv
> +ri_tax_percepcion_iibb_ha_aplicada,"0% IIBB C","Perception IIBB Chaco applied","Perc IIBB Chaco A","4","False","fixed","0.0","sale","tax_group_percepcion_iibb_ha","base","invoice","","Percepción IIBB
Name clash with ri_tax_percepcion_iibb_co_aplicada

2023-05-10 15:45 UTC, oco-odoo commented on addons/l10n_ar/data/template/account.tax-ar_ex.csv
> +ri_tax_percepcion_iibb_mi_aplicada,"0% IIBB M","Perception IIBB Misiones applied","Perc IIBB Misiones A","4","False","fixed","0.0","sale","tax_group_percepcion_iibb_mi","base","invoice","","Percepció
Name clash with ri_tax_percepcion_iibb_za_aplicada

2023-05-11 09:01 UTC, oco-odoo commented
@robodoo r+

2023-05-11 11:26 UTC, closed without merging