[FIX] payment_adyen: incorrect parsing of partner's address
odoo/odoo pull request #114805
Opened 2023-03-09 13:24 UTC by hote-odoo

When passing the customer data to adyen to execute a payment an error occurred if the address did not follow a very strict pattern that might be unkown to the user.
After this commit we relax the pattern a little and allow the user to supply her address in different ways.

opw - 3171407

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-10 10:24 UTC, Demesmaeker requested changes
Hello :duck: 

I understand that we can't resolve the problem the same way as in V16 (since that was due to a complete rework on the partner address, from my understanding). The problem here is that some street name could have numbers in it, and some numbers could have letters in it... Maybe looking at how `base_address_extended` manages it could be interesting, especially since the base method used here historically comes from there =]

2023-03-24 17:21 UTC, AntoineVDV requested changes
I find the design of this fix overkill for such a niche feature. After all the partner address field is only required if the Automatic Risk Assessment feature is enabled on Adyen's side.

We should not go through a client-side RPC to check whether the address can be parsed. Instead, we should *at most* handle the error gracefully when the address is actually parsed. IMHO, something like this would already be enough:
```diff
diff --git a/addons/payment_adyen/utils.py b/addons/payment_adyen/utils.py
index 73641fff6e7..4b2c84a33dd 100644
--- a/addons/payment_adyen/utils.py
+++ b/addons/payment_adyen/utils.py
@@ -53,6 +53,8 @@ def format_partner_address(partner):
     """
     STREET_FORMAT = '%(street_number)s/%(street_number2)s %(street_name)s'
     street_data = split_street_with_params(partner.street, STREET_FORMAT)
+    if any(key not in street_data for key in ('street_name', 'street_name')):
+        raise ValidationError(_("wrong address format; received %s but expected %s", partner.street, STREET_FORMAT.replace('%(', '').replace(')s', '')))
     return {
         'city': partner.city,
         'country': partner.country_id.code or 'ZZ',  # 'ZZ' if the country is not known.
```

Now, remember that the customer's problem is not being able to make a payment (which is not clearly explained in the commit message, btw), not that we don't support every address format in Odoo 15. Thus, I think that we can simply omit the address if we fail to parse it:
```diff
diff --git a/addons/payment_adyen/utils.py b/addons/payment_adyen/utils.py
index 73641fff6e7..029266fa11f 100644
--- a/addons/payment_adyen/utils.py
+++ b/addons/payment_adyen/utils.py
@@ -58,8 +58,9 @@ def format_partner_address(partner):
         'country': partner.country_id.code or 'ZZ',  # 'ZZ' if the country is not known.
         'stateOrProvince': partner.state_id.code,
         'postalCode': partner.zip,
-        'street': street_data['street_name'],
-        'houseNumberOrName': street_data['street_number'],
+        # Fill in the address fields if the format is supported, or fallback to the raw address.
+        'street': street_data.get('street_name', partner.street),
+        'houseNumberOrName': street_data.get('street_number'),
     }
```

2023-03-27 14:20 UTC, AntoineVDV requested changes

2023-03-27 14:20 UTC, AntoineVDV commented on addons/payment_adyen/utils.py
> +        ))
You tried to combine both suggestions instead of only the second one, which doesn't need the ValidationError.
```suggestion
```

2023-03-28 15:19 UTC, AntoineVDV approved these changes
@robodoo r+

2023-03-28 17:29 UTC, closed without merging