[IMP] l10n_rs: taxes
odoo/odoo pull request #115321
Opened 2023-03-15 14:01 UTC by malb-odoo

We want to invigorate a Tax Name Taxonomy so that tax names are as codified as possible. This allow for a better display on Invoice Description, and allowed us to implement a smart name_search.

In this PR, we change the taxes name so that it's more clear for the users

task-id: 3052677

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-15 14:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/115321).

2023-05-10 15:09 UTC, oco-odoo requested changes

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_sale_vat_10","20","VAT 10%","VAT 10%","10%","False","10.0","percent","sale","True","tax_group_vat_10","100","base","invoice","+004","","10%"
Again, "VAT" equivalent missing in tranlsation

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_sale_vat_0","30","VAT 0%","VAT 0%","0%","False","0.0","percent","sale","True","tax_group_vat_0","100","base","invoice","","",""
missing translation

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_sale_vat_0_no_deduct_previous_tax","50","VAT 0% without the right to deduct previous tax","VAT 0% without the right to deduct previous tax","0% ND","False","0.0","percent","sale","True","tax_grou
translation seems inconsistent

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_purchase_vat_20","60","VAT 20%","VAT 20%","20%","False","20.0","percent","purchase","True","tax_group_vat_20","100","base","invoice","+008","","20%"
missing "VAT" in translation

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_purchase_vat_10","70","VAT 10%","VAT 10%","10%","False","10.0","percent","purchase","True","tax_group_vat_10","100","base","invoice","+008","","10%"
missing "VAT" in translation

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_purchase_vat_0","80","VAT 0%","VAT 0%","0%","False","0.0","percent","purchase","True","tax_group_vat_0","100","base","invoice","","",""
missing translation

2023-05-10 15:09 UTC, oco-odoo commented on addons/l10n_rs/data/template/account.tax-rs.csv
> +"rs_purchase_import_vat_0","90","VAT 0% - import VAT exempt","VAT 0% - import VAT exempt","0% EX","False","0.0","percent","purchase","True","tax_group_vat_10","100","base","invoice","+006","","0% - u
translation seems inconsistent

(on subsequent lines as well)

2023-05-10 18:40 UTC, malb-odoo commented
Description column was wrong, it should be corrected and match the translation

2023-05-11 09:19 UTC, oco-odoo commented
@robodoo r+

2023-05-11 11:26 UTC, closed without merging