[FIX] google_calendar: keep partner order according to email order
odoo/odoo pull request #115660
Opened 2023-03-17 10:51 UTC by arj-odoo

Before this commit, when an event was synced with internal and external users, the corresponding partners were merged like this:
1) partner corresponding to internal users
2) regular partner

If the list of emails provided by google was in another order: regular partners then internal, there were an issue:

```
emails = [a.get('email') for a in google_attendees] # sorted by google, external then internal for example
partners = self._get_sync_partner(emails) # always internal then external partners
for attendee in zip(emails, partners, google_attendees):
    # we are associating the external email with internal partner
    # the external attendee is skipped because we take the user partner
```

This commit makes sure to return the partner is the order of the mails in _get_sync_partner.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-17 10:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/115660).

2023-04-03 10:08 UTC, fdamhaut requested changes
Small change otherwise lgtm

2023-04-03 10:08 UTC, fdamhaut commented on addons/google_calendar/models/google_sync.py
> +            result.append(unsorted_partners.filtered(lambda p: p.email_normalized == email))
```suggestion
        unsorted_partners = self.env['res.partner'].browse([p.id for p in partners])
        # partners needs to be sorted according to the emails order provided by google
        k = {v: n for n, v in enumerate(emails)}
        results = unsorted_partners.sorted(key=lambda p: k.get(p.email_normalized, -1))
```
So we can avoid loop into loop

2023-04-04 08:58 UTC, fdamhaut approved these changes

2023-04-12 10:58 UTC, kba-odoo commented
robodoo r+

2023-04-12 12:58 UTC, closed without merging