[FIX] l10n_din5008: get background image live
odoo/odoo pull request #115665
Opened 2023-03-17 11:11 UTC by hale-odoo

1. Install [DIN 5008]
2. [Settings]-[Document Layout]-[Configure]
- Choose Layout [DIN 5008]
- Layout Background: Geometric

Issue: No background image when there should be
Resolve: Add the missing handler

opw-3141279
versions: saas-15.2 up to saas-16.1

2023-03-17 11:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/115665).

2023-03-17 12:28 UTC, hubvd approved these changes
The same is done in `<template id="external_layout_standard">`
LGTM :+1:

2023-03-17 12:54 UTC, aliyatastemirova reviewed
thanks :slightly_smiling_face: 
did I understand correctly, it's a partial backport of what was done in odoo/odoo#100723 ?
If so, then we only need to fw-port until 16.1.

Could you please format it the way it was formatted there? Adding this fix on one line makes it unreadable in my opinion.

2023-03-27 14:18 UTC, Levizar requested changes
To me it's ok.

I would just like you to add on the commit message the steps that would be required for a customer to correct its template, as it's not trivial, so it will be obvious for anyone investigating that.

1) update the module `l10n_din5008`
2) activate debug mode assets
3) go to Settings / technical / views 
4) write `external_layout_din5008` in the search bar
5) open the record
6) action > compare/reset
7) select `reset to file version`
8) save

2023-03-27 14:51 UTC, Levizar commented
@robodoo r+

I don't know why this is such an issue to add a message that would probably help your colleagues :/

2023-03-27 15:55 UTC, closed without merging