[FIX] web: add the same image on different records
odoo/odoo pull request #115830
Opened 2023-03-20 10:38 UTC by MerlinGuillaume

Using the same image on new records does not work without refreshing the page

Steps to reproduce:
1. Install Sales
2. Go to Sales > Products > Products and create a new product
3. Set a name and an image on the product
4. Create a new product (with the 'New' button in the top right of the form)
5. Set the image used previously on this product
6. The image does not save

Solution:
Reset the FileUploader files when we open a new form

Problem:
The FileUploader component is not reset when we open a new form (the files previously uploaded are still present on the FileUploader). `onFileChange` is thus not called when we use the same image, as the file hasn't changed.

opw-3151756

2023-03-20 10:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/115830).

2023-03-20 15:28 UTC, hubvd approved these changes
Well done :)

2023-03-22 09:19 UTC, MerlinGuillaume commented
Hello @odoo/rd-framework-js, could you review this please ?

2023-03-22 12:05 UTC, brboi requested changes
Your solution is OK, but what do you think about the following ?
```diff
diff --git a/addons/web/static/src/views/fields/file_handler.js b/addons/web/static/src/views/fields/file_handler.js
index b1dc6d38e1e2..4f8b2c996e7b 100644
--- a/addons/web/static/src/views/fields/file_handler.js
+++ b/addons/web/static/src/views/fields/file_handler.js
@@ -6,17 +6,23 @@ import { getDataURLFromFile } from "@web/core/utils/urls";
 import { session } from "@web/session";
 import { formatFloat } from "./formatters";
 
-import { Component, useRef, useState } from "@odoo/owl";
+import { Component, onWillUpdateProps, useRef, useState } from "@odoo/owl";
 
 const DEFAULT_MAX_FILE_SIZE = 128 * 1024 * 1024;
 
 export class FileUploader extends Component {
     setup() {
         this.notification = useService("notification");
-        this.id = `o_fileupload_${++FileUploader.nextId}`;
         this.fileInputRef = useRef("fileInput");
         this.state = useState({
             isUploading: false,
+            key: this.props.key,
+        });
+        onWillUpdateProps((nextProps) => {
+            if (this.state.key !== nextProps.key) {
+                this.fileInputRef.el.value = "";
+                this.state.key = nextProps.key;
+            }
         });
     }
 
@@ -74,4 +80,3 @@ export class FileUploader extends Component {
 }
 
 FileUploader.template = "web.FileUploader";
-FileUploader.nextId = 0;
diff --git a/addons/web/static/src/views/fields/image/image_field.xml b/addons/web/static/src/views/fields/image/image_field.xml
index bb9d42f71875..5ca160a7b29a 100644
--- a/addons/web/static/src/views/fields/image/image_field.xml
+++ b/addons/web/static/src/views/fields/image/image_field.xml
@@ -7,6 +7,7 @@
                 <t t-if="!props.readonly">
                     <FileUploader
                         acceptedFileExtensions="props.acceptedFileExtensions"
+                        key="rawCacheKey"
                         onUploaded.bind="onFileUploaded"
                         type="'image'"
                     >
```


Also, I am requesting changes as a fix should generally come with a test, in order to avoid breaking this again in the future.

2023-03-22 12:05 UTC, brboi commented on addons/web/static/src/views/fields/file_handler.js
> +        }
seems weird to share a bus through props for this single use case

2023-03-22 12:05 UTC, brboi commented on addons/web/static/src/views/fields/file_handler.js
this.id is dead code, could you remove it as well as the nextId static member ?
Thanks

2023-03-22 12:19 UTC, sdegueldre commented
Hm, I feel like this is a more general problem. Somewhere, somehow, if the record changes the entire view should be created from scratch, we probably want to reset the internal state of all HTML elements in those scenarios. Probably needs a well placed t-key cc @aab-odoo

2023-03-22 12:22 UTC, hubvd commented
> Hm, I feel like this is a more general problem

This one could also be fixed this way I guess https://github.com/odoo/odoo/pull/116179

2023-03-22 13:45 UTC, aab-odoo commented
> Hm, I feel like this is a more general problem. Somewhere, somehow, if the record changes the entire view should be created from scratch, we probably want to reset the internal state of all HTML elements in those scenarios. Probably needs a well placed t-key cc @aab-odoo

Not sure. In this case we have an issue because the FileUploader doesn't set the value of the input right? It's a very specific and unique case, so maybe @brboi solution is fine.

2023-03-27 14:45 UTC, ged-odoo commented on addons/web/static/src/views/fields/file_handler.js
> +        onWillUpdateProps((nextProps) => {
you can remove this and use `t-key` in the image field template

2023-03-27 14:45 UTC, ged-odoo commented on addons/web/static/src/views/fields/image/image_field.xml
> +                        key="props.record.resId"
and here, you can use `t-key`:

```
                        t-key="props.record.resId"

```

2023-03-30 12:08 UTC, brboi approved these changes
robodoo r+

2023-03-30 13:17 UTC, closed without merging