[FIX] 10n_fr_fec : fec can be download by unalowaed user
odoo/odoo pull request #115958
Opened 2023-03-20 19:10 UTC by fmdl

Before this commit a user from an other company can download a fec created by an other user.

@odony 
@oco-odoo 
@alexis-via 
@Yenthe666 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-20 19:12 UTC, fmdl commented
OPW #3240374

2023-04-13 08:52 UTC, fmdl commented
ping @oco-odoo

2023-04-13 09:44 UTC, aliyatastemirova requested changes
Could you please write a clearer commit message as well? Also, I think it would be nicer to avoid typos (should be `can be downloaded by unallowed user` for example)

2023-04-13 09:44 UTC, aliyatastemirova commented on addons/l10n_fr_fec/security/security.xml
> +</odoo>
A small thing: can you please add a newline at the end of this file?

2023-05-11 13:26 UTC, oco-odoo requested changes
Please squash your commits. And while you're at it, also fix the typo in the title. Then, I merge :)

2023-06-16 04:55 UTC, fmdl commented
ping @oco-odoo

2023-06-16 08:25 UTC, oco-odoo approved these changes
@robodoo r+

2023-06-16 10:06 UTC, closed without merging