[FIX] website: make carousel controls unremovable
odoo/odoo pull request #116171
Opened 2023-03-22 10:36 UTC by cammarosano

Before this commit, the following elements could be selected and removed from the carouse:
- the "next" and "previous" arrows on each side of the carousel
- the indicators at the carousel's bottom (1st slide, 2nd etc.)

This commit avoids such undesirable removal by wrapping the related elements in unremovable blocks.

task-3102120
opw-3086220

2023-03-22 10:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116171).

2023-06-16 15:33 UTC, rdeodoo requested changes
Can't change html structure in stable.
What happened to the opw? 2 months old..
You can unassign from it and add `vfyd website` tag if you want

2023-06-20 08:55 UTC, cammarosano commented
> You can unassign from it and add `vfyd website` tag if you want

Done.
https://www.odoo.com/web#id=3102120&cids=1&menu_id=4720&action=333&active_id=1695&model=project.task&view_type=form

2023-06-20 08:56 UTC, closed without merging

2023-06-20 16:23 UTC, rdeodoo commented
This is not an `opw` you linked and unassigned from, this is a `task`.
Actually, you were not even assigned on the bugfix, it's been unassigned for multiple months and opened half a year ago.
I will add the `vfyd website` tag so it goes under our scope and we finally take care of it.