[FIX] website: prevent traceback while deleting menu
odoo/odoo pull request #116153
Opened 2023-03-22 08:58 UTC by smna-odoo

the error will occur because when you first add the menu that's menu can not store in the database without clicking on the save button and that id is temporary store in string format now you delete that menu and click on save they try to browse that menu but it is not available in the database and also it has a string.

see: 
![png](https://user-images.githubusercontent.com/98956874/226828010-6f4e626c-ca51-4f69-a9d5-132c2eb148e5.png)

steps to produce this error:
1) go to the website and click on 'menu editor'
2) click on 'Add Menu Item' button
3) Add name and URL and click on the ok button.
4) now delete the newly added menu and save it.

So here we can check the id type and only browse the integer type ids.

sentry-3931666290

2023-03-22 08:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116153).

2023-03-23 09:26 UTC, yelizariev commented on addons/website/models/website_menu.py
> +        to_delete = list(filter(check_id_type, data.get('to_delete')))
```suggestion
        to_delete = [id for id in data.get('to_delete', []) if not isinstance(ids, str)]
```

2023-03-24 05:53 UTC, smna-odoo commented on addons/website/models/website_menu.py
> +        to_delete = list(filter(check_id_type, data.get('to_delete')))
@yelizariev Done!!

2023-04-03 13:43 UTC, rdeodoo requested changes
I might need a few more details here because I can't reproduce the error described in the commit.
Since the fix is in python, I'd have expected the data (newly created menu) to be sent to the server but it's not the case :shrug: 

Hm.. Investigating a bit further, I guess you are talking about 16.0, which indeed is erroring in this case.
Why fixing it in 14.0 where there is no error?

1. Move the fix to 16.0
2. Make the fix JS wise, it shouldn't be sent to the server (as in 14.0, it's not sent to the server if you create and delete it directly, as expected)

2023-04-06 05:09 UTC, smna-odoo commented
@rdeodoo changes are done can you please check this?

2023-04-06 10:21 UTC, rdeodoo approved these changes
Ty :+1: 
@robodoo r+

2023-04-06 10:21 UTC, rdeodoo commented on addons/website/static/src/components/dialog/edit_menu.js
> +        if (parseInt(id)) {
Could've deserved a comment, it's really not obvious that this is filtering out the menu which were deleted after having being created in the current menu edition (and so never actually existed in the DB).

2023-04-06 11:34 UTC, closed without merging