[FIX] account: change move currency
odoo/odoo pull request #116206
Opened 2023-03-22 13:31 UTC by guva-odoo

Before this commit, we could not change
the currency on invoice if related journal
has a default currency set.

opw-3226228

2023-03-22 13:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116206).

2023-03-22 14:28 UTC, epictete requested changes

2023-03-23 08:16 UTC, guva-odoo commented on addons/account/tests/test_account_move_out_invoice.py
> +        self.assertRecordValues(sorted(move.line_ids, key=lambda l: l.account_type == 'asset_receivable'), [
I wanted to be sure to always have lines in the same order, but I guess it is not necessary if you ask 😆

2023-03-23 08:16 UTC, guva-odoo commented on addons/account/models/account_move.py
>                  invoice.statement_line_id.foreign_currency_id
👍

2023-03-23 08:51 UTC, epictete commented
@robodoo r+

2023-03-23 17:59 UTC, closed without merging