[FIX] project: fix broken layout in activity view
odoo/odoo pull request #116317
Opened 2023-03-23 10:24 UTC by yava-odoo

In this PR, we fixed the broken layout of the task activity view.

task-3231708

2023-03-23 10:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116317).

2023-03-30 16:07 UTC, auon-odoo requested changes
Thank you for the fix :wrench:

2023-04-03 05:20 UTC, yava-odoo commented on addons/project/views/project_task_views.xml
> +                            <div class="col-6">
Changes are applied thanks :slightly_smiling_face:

2023-04-03 07:37 UTC, auon-odoo approved these changes
Lgtm, thank you! :fire:

2023-04-06 15:46 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂 

robodoo r+

2023-04-06 17:17 UTC, closed without merging