[FIX]  account: return default value for amount_currency
odoo/odoo pull request #116474
Opened 2023-03-24 08:55 UTC by kaso-odoo

Previously, the _compute_epd_needed() method was accessing dictionary values using brackets and keys, which could potentially raise a KeyError if the key does not exist in the dictionary.

![image](https://user-images.githubusercontent.com/121805291/227471604-999fe8fd-922b-45bf-86ac-3609499da588.png)

This commit refactors the code to use the .get() method for dictionaries, which is a safer way to access dictionary values since it returns the default  as '0' if the key is not found.

sentry - 4022475962

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-24 08:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116474).

2023-03-24 08:57 UTC, kaso-odoo commented
FYI @odoo/sentry_reviewers

2023-03-27 07:38 UTC, Levizar reviewed
@kaso-odoo as discussed with @abz-odoo , I think this is a data issue and that it shouldn't be corrected that way.
`amount_currency` is supposed to always been set and thus, defaulting to 0.0 could be wrong and, instead of a traceback, produce wrong reports which would be more harmful than a traceback.

2023-04-06 11:11 UTC, Levizar requested changes
Hello,

Something doesn't feel right.

> The computed value of 'AccountMove.needed_terms' is overriden 'hr.expense' module
where it removes the 'amount_currency' key-value pair.
So, it will cause error.

From this commit message, the issue seems to be that `hr.expense` removes `amount_currency` and that it would cause a crash.
If that is so, why do we fix by adding `amount_currency` instead of removing the code that tries to remove `amount_currency`?

2023-04-07 05:11 UTC, kaso-odoo commented
> Hello,
> 
> Something doesn't feel right.
> 
> > The computed value of 'AccountMove.needed_terms' is overriden 'hr.expense' module
> > where it removes the 'amount_currency' key-value pair.
> > So, it will cause error.
> 
> From this commit message, the issue seems to be that `hr.expense` removes `amount_currency` and that it would cause a crash. If that is so, why do we fix by adding `amount_currency` instead of removing the code that tries to remove `amount_currency`?

https://github.com/odoo/odoo/pull/115094/files#diff-f75c55fbc485ca0f0a840f46ea54df8fda019322d9fd6a2f7f5a22eea9eba357L55-L71

The `amount_currency` was removed here. So, we are just adding it back. And I have also updated the commit message.

2023-04-11 09:23 UTC, Levizar commented
Hello @tdetry, could you have a look at it?

2023-04-11 09:45 UTC, closed without merging