[IMP] pos: New FloorScreen kanban view and more
odoo/odoo pull request #116534
Opened 2023-03-24 12:47 UTC by adgu-odoo

Currently, there is only 1 plan view that is unreadable on mobile and sometimes also complicated in some cases.
This commit  adds a new "Kanban" view used by default on mobile and available in desktop too. This commit also changes the edit bar of the FloorScreen: the design is changed and some features are added like the multiple selection of the tables or the adding and removing of floors directly from the frontend. It also changes the navbar of the PoS, moving the buttons in a navigation menu accessible thanks to a button.

Task-id: 321203

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-24 12:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116534).

2023-04-06 14:37 UTC, trj-odoo commented on addons/point_of_sale/static/src/scss/pos.scss
> +}
t'es sérieux eof ?

2023-04-06 14:38 UTC, trj-odoo commented on addons/point_of_sale/static/src/scss/pos.scss
> +	}
Pourquoi cela part-il en cacahuètes ? (indentation)

2023-04-06 14:42 UTC, trj-odoo commented on addons/pos_restaurant/models/pos_restaurant.py
> +            returns the id of the floor.
bullshit (with love), you are just modifying the name

2023-04-07 14:16 UTC, trj-odoo requested changes
This is my last and final review at Odoo, you did a great job. Well done. Keep this up and you'll become the very best ~~pokemon trainer~~ at what you do.

It was nice reviewing this alongside you. 
Enjoy the last work i'm giving you

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/floor_screen/floor_screen.js
> +            this.state.selectedTableIds.splice(0, this.state.selectedTableIds.length);
```suggestion
            this.state.selectedTableIds = [];```

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/floor_screen/floor_screen.js
> +        if (equalsCheck(this.state.selectedTableIds, originalSelectedTableIds)) {
careful if the order is important

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/floor_screen/table.js
> +
random space

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/floor_screen/table.js
> +            let position_v = widthTable * Math.floor(index / nbrHorizontal) + 5 + Math.floor(index / nbrHorizontal) * 10
j'crois vraiment tu peux faire des consts

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/navbar/navbar.js
> +            this.env.pos.floorPlanStyle = "kanban";
```suggestion
        this.env.pos.floorPlanStyle = this.env.pos.floorPlanStyle == "kanban" ?  "default" : "kanban";
```

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/app/navbar/navbar.xml
> +                <span>Switch Floor Plan</span>
C'est Alain qui l'a dit

2023-04-07 14:16 UTC, trj-odoo commented on addons/pos_restaurant/static/src/js/Chrome.js
> +        if (this.env.pos.config.iface_floorplan || this.env.pos.config.is_table_management) {
Don't forget to remove this one because is_table_management will replae iface_floorplan

2023-04-12 11:41 UTC, rhe-odoo commented on addons/pos_restaurant/static/tests/tours/FloorScreen.tour.js
>  // test duplicate table
Can you test duplicate on multiple tables? (=> control click)

2023-04-12 11:55 UTC, rhe-odoo commented on addons/pos_restaurant/static/src/js/models.js
> +        this.floorPlanStyle = "";
Shouldn't be it default?

2023-04-12 15:00 UTC, rhe-odoo commented
@robodoo r+

2023-04-12 15:00 UTC, robodoo commented
@adgu-odoo @rhe-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-04-12 15:06 UTC, robodoo commented
Merge method set to merge directly, using the PR as merge commit message.

2023-04-12 15:06 UTC, robodoo commented
I'm sorry, @rhe-odoo: this PR is already reviewed, reviewing it again is useless.

2023-04-12 19:50 UTC, merged