[IMP] payment(asiapay): add var for view required currences
odoo/odoo pull request #116573
Opened 2023-03-24 16:08 UTC by vchu-odoo

avoid overriding payment views by creating new computed field in the payment provider property and override it if needed in inherited payment models 
task-3120983

2023-03-24 16:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116573).

2023-03-28 17:50 UTC, chevalierv approved these changes
Great work on this diff :smiley: 

I only have a few comments about your commit message:
- Good job on using the parenthesis to factorize `payment` and `payment_asiapay`. The best would be with the little `_` like this: `payment(_asiapay)`
- Try to limit the number of characters per line. I personally go no further than 72 characters. Why 72 ? Because `git log` adds a padding of 4 spaces when displaying the commit message, and bc most terminals are 80-column wide. The four left on the right will give the impression that the text has been centered. You can find plenty of articles about that on the web. 
- Try to concentrate the message more on the 'why' e.g. "Some providers require to select a currency for their configuration. This features will now be supported by the payment engine to ease the creation of providers with such requirements"

2023-03-28 17:50 UTC, chevalierv commented on addons/payment/views/payment_provider_views.xml
> +                                               attrs="{'required': [('require_currency', '=', True), ('state', '!=', 'disabled')]}"/>
FYI you can add the `attrs` before the `options` to gain one line in the diff.

2023-04-11 13:25 UTC, AntoineVDV requested changes

2023-04-11 13:25 UTC, AntoineVDV commented on addons/payment/views/payment_provider_views.xml
> +                <field name='require_currency' invisible='1'/>
Use double quotes in XML files.

2023-04-11 13:25 UTC, AntoineVDV commented on addons/payment_asiapay/models/payment_provider.py
> +        """ Override of payment to make currency field required.
```suggestion
        """ Override of payment to make the currency field required.
```
or
```suggestion
        """ Override of payment to make the `available_currency_ids` field required.
```

2023-04-11 13:45 UTC, AntoineVDV approved these changes
@robodoo r+

2023-05-03 13:04 UTC, closed without merging