[IMP] sale: replace stat button with the action one
odoo/odoo pull request #116557
Opened 2023-03-24 13:55 UTC by vchu-odoo

for consistency reason as the button preview in Odoo is an action button rather than a stat button
task-3074608

2023-03-24 13:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116557).

2023-03-28 16:03 UTC, chevalierv requested changes
Good job on this :+1: 

I'd like a little more information in the commit message though. `for consistency reason` is not enough IMO. For example, you could explain on what we based the consistency (in this case, you could say the button preview in Odoo is usually an action button, and that it does not make sense to have a stat button for this because there is no stat to show on it).

I see the effort to try and explain the why though. Kudos for that :fireworks:

2023-03-29 08:14 UTC, vchu-odoo commented on addons/sale/views/sale_order_views.xml
> +            <button name="action_preview_sale_order" position='before'>
Done the changes, you must have meant that in xml files I should use double quotes.

2023-03-29 08:37 UTC, chevalierv commented on addons/sale/views/sale_order_views.xml
> +            <button name="action_preview_sale_order" position='before'>
Yes indeed. Sorry for the confusion :sweat_smile:

2023-03-29 08:37 UTC, chevalierv approved these changes

2023-03-31 09:14 UTC, Feyensv reviewed
Little nitpicky comments, looks good to me :)

2023-03-31 13:21 UTC, vchu-odoo commented on addons/sale/views/sale_order_views.xml
> +                <button name="action_preview_sale_order" string="preview" type="object" class="btn-secondary"/>
Done

2023-03-31 13:21 UTC, vchu-odoo commented on addons/sale/views/sale_order_views.xml
> +            <t groups="sale.group_auto_done_setting">
done

2023-03-31 13:28 UTC, Feyensv approved these changes
@robodoo r+

2023-03-31 17:10 UTC, closed without merging