[FIX] web: calendar filter not showing selection values
odoo/odoo pull request #116626
Opened 2023-03-25 05:32 UTC by niyasraphy

before this commit, in the calendar view, if there is a field of selection field, instead of showing the filter value, currently it is shown as undefined.

after this commit, the filter will show the selection value instead of undefined.

close: https://github.com/odoo/odoo/issues/112689
close: https://github.com/odoo/odoo/issues/113698

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-25 05:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/116626).

2023-03-28 12:52 UTC, niyasraphy commented
hi @pro-odoo @juliusc2066 ,
if you have time, can you review this.
thanks

2023-04-06 07:21 UTC, niyasraphy commented
hi @brboi ,
if you have time, can you review this.
thanks

2023-04-06 12:07 UTC, brboi requested changes
thanks for your work ;-)

please apply this patch:
```patch
diff --git a/addons/web/static/src/views/calendar/calendar_model.js b/addons/web/static/src/views/calendar/calendar_model.js
index cc5cfd640a21..2e4c171b8623 100644
--- a/addons/web/static/src/views/calendar/calendar_model.js
+++ b/addons/web/static/src/views/calendar/calendar_model.js
@@ -728,7 +728,7 @@ export class CalendarModel extends Model {
             type: "dynamic",
             recordId: null,
             value,
-            label: formatter(rawValue, field) || _t("Undefined"),
+            label: formatter(rawValue, { field }) || _t("Undefined"),
             active: previousFilter ? previousFilter.active : true,
             canRemove: false,
             colorIndex,
diff --git a/addons/web/static/tests/views/calendar/calendar_view_tests.js b/addons/web/static/tests/views/calendar/calendar_view_tests.js
index 98aead5b88ee..f877236af1a6 100644
--- a/addons/web/static/tests/views/calendar/calendar_view_tests.js
+++ b/addons/web/static/tests/views/calendar/calendar_view_tests.js
@@ -2573,6 +2573,41 @@ QUnit.module("Views", ({ beforeEach }) => {
         assert.containsN(target, ".fc-event", 9, "should display 9 events on the week");
     });
 
+    QUnit.test("dynamic filters with selection fields", async (assert) => {
+        serverData.models.event.fields.selection = {
+            name: "selection",
+            string: "Ambiance",
+            type: "selection",
+            selection: [
+                ["desert", "Desert"],
+                ["forest", "Forest"],
+            ],
+        };
+
+        serverData.models.event.records[0].selection = "forest";
+        serverData.models.event.records[1].selection = "desert";
+
+        await makeView({
+            type: "calendar",
+            resModel: "event",
+            serverData,
+            arch: /* xml */ `
+                <calendar date_start="start" date_stop="stop">
+                    <field name="selection" filters="1" />
+                </calendar>
+            `,
+        });
+
+        const section = findFilterPanelSection(target, "selection");
+        assert.deepEqual(section.querySelector(".o_cw_filter_label").textContent, "Ambiance");
+        assert.deepEqual(
+            [...section.querySelectorAll(".o_calendar_filter_item")].map((el) =>
+                el.textContent.trim()
+            ),
+            ["Forest", "Desert", "Undefined"]
+        );
+    });
+
     QUnit.test("Colors: cycling through available colors", async (assert) => {
         serverData.models.filter_partner.records = Array.from({ length: 56 }, (_, i) => ({
             id: i + 1,
```

2023-04-06 13:21 UTC, brboi approved these changes
Thanks ;-)
robodoo r+

2023-04-06 13:23 UTC, niyasraphy commented
thanks @brboi for the review and test case,
i was waiting for the checks to get completed before pinging you

2023-04-06 16:53 UTC, closed without merging