[IMP] web_editor: show/hide background shape on mobile
odoo/odoo pull request #116958
Opened 2023-03-29 09:07 UTC by robinlej

Add a button in BackgroundShape editor to show/hide on mobile, hidden by default.
CSS updated :
- on toggle, show the shape
- ensure that the right button (i.e. the remove button) is displayed with a darker background color, not the showOnMobile one

2023-03-29 10:03 UTC, qsm-odoo requested changes
Seems good, some comments to make it perfect before sending this to testing :+1:

2023-03-29 11:49 UTC, robinlej commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            return {showOnMobile};
Not that I can see in `color()` and `_flipShape()`:
- https://github.com/odoo/odoo/blob/947a7ac915a4614885eec105dd23f75b2149f5ef/addons/web_editor/static/src/js/editor/snippets.options.js#L6862-L6868
- https://github.com/odoo/odoo/blob/947a7ac915a4614885eec105dd23f75b2149f5ef/addons/web_editor/static/src/js/editor/snippets.options.js#L6969-L6977

2023-03-29 11:53 UTC, robinlej commented on addons/web_editor/static/src/scss/web_editor.frontend.scss
> +    .o_we_shape:not(.o_shape_show_mobile) {
I initially did something like that (with `d-none` and variants) but a unique toggle class seemed more in line with the code. I can go back to bootstrap classes if it's better, it's just a few lines inside the showOnMobile method.

2023-03-29 13:07 UTC, robinlej commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            return {showOnMobile};
Maybe I read it wrong, but `_handlePreviewState` passes what its function parameter returns to `_markShape`, which in turn recreates a full object from `_getShapeData()` before modifying it with the parameter. So it seems to be the expected use.
https://github.com/odoo/odoo/blob/947a7ac915a4614885eec105dd23f75b2149f5ef/addons/web_editor/static/src/js/editor/snippets.options.js#L7106

2023-03-31 09:47 UTC, qsm-odoo requested changes
@robinlej There is 3 commits in your PR, I don't think this is what you wanted me to review? :wink: 

![image](https://user-images.githubusercontent.com/10338094/229086805-62ed0f77-7824-4565-995a-dd5fc3340ffe.png)

2023-04-04 11:57 UTC, qsm-odoo requested changes
@robinlej A very small comment. Once adapted set the task in RD Dev - Green so this can go through testing :+1: Don't forget it should already been moved to RD Dev as soon as you re-started working on it, I see it is still in RD Review :wink:

2023-04-04 11:57 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +        }
Make this a one-liner thanks to `classList.toggle`

2023-05-04 18:04 UTC, qsm-odoo requested changes
@pierre-pde @robinlej Better, you can now add a shape on desktop, make it visible in mobile, then select a different shape by previsualizing them in mobile... but when you start in mobile, it does not work:
- Enter edit mode, add a snippet
- Switch to mobile view
- Add a shape: the selection stuff opens but previsualizing does not work. Sure the user can click on "show in mobile" then reopen the dropdown but... strange that dropdown opened then. I think that when you are in mobile and you add a shape, that checkbox to show in mobile should be enabled by default.

Also @robinlej when changing: also rebase this branch + remove the "CSS updated" in the commit message. Explain the what and the why, not the how in commit messages (unless very technical stuff). The how is the diff you made: if the diff is not clear enough, there should be explanation **as comments in the code** :wink: Actually, this CSS rule `&:not(.o_we_so_color_palette) ~ we-button:not(:hover):last-child {` could be commented as it is not obvious what it does (I may myself come back to it in one year and not having a clue of what it is without blaming) :+1:

2023-05-05 07:12 UTC, pierre-pde commented
Hi @qsm-odoo , good point. I forgot to think about editing in mobile view...
@robinlej , 100% worth implementing the suggestion of Quentin.
If a shape is added on mobile view, enable the "show on mobile" automatically :)

2023-06-16 15:25 UTC, qsm-odoo approved these changes
@robodoo r+

2023-06-16 22:10 UTC, closed without merging