[REF] sql.py: Take into account materialized views when dropping them
odoo/odoo pull request #117424
Opened 2023-03-31 21:44 UTC by carralc

**Description of the issue/feature this PR addresses:**
The function `drop_view_if_exists` only works when the view in question is a regular view.
PortgreSQL's [materialized views](https://www.postgresql.org/docs/current/rules-materializedviews.html) need a special syntax to be dropped, differing from regular `DROP VIEW` syntax.

**Current behavior before PR:**
If the caller wanted to drop a materialized view, `drop_view_if_exists` would not work and a special
query would need to be called directly.

**Desired behavior after PR is merged:**
 Allow for materialized views to be dropped without any extra logic added from the caller side.
(And without any burden to already existing code)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-03-31 21:45 UTC, hugho-ad approved these changes

2023-03-31 21:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/117424).

2023-04-10 16:39 UTC, hugho-ad commented
Hello @xmo-odoo 

At v16.0
you consider them already
https://github.com/odoo/odoo/blob/faabaf798c70035b3faebad546d034bab268670a/odoo/tools/sql.py#L156

this PR attempts to make `drop_view_if_exists` friendly with materialized views

We are replacing standard views with materialized views, some of theme become to slow so we needed to transform them into materialized views since they are more faster. the only problem is that the definition of these views includes a `drop_view_if_exists` statement 
which fails when we made -u all with the following error
![image](https://user-images.githubusercontent.com/10233975/230947153-e5f1a5b3-779e-4624-9729-cdf7c6b2f0b0.png)

2023-04-24 14:05 UTC, hugho-ad commented
Hello @xmo-odoo 

>Fair enough. Though in that case I'd request that you perform the drop conditionally, as table_kind provides that information.

Do you mean something like following:

```python
def drop_view_if_exists(cr, viewname):
    kind = table_kind(cr, viewname)
    if kind == 'm':
            cr.execute("DROP MATERIALIZED VIEW IF EXISTS %s CASCADE" % (viewname,))
    else:
        cr.execute("DROP view IF EXISTS %s CASCADE" % (viewname,))
```

I'm curious 
what's wrong with the this way?
https://github.com/odoo/odoo/blob/faabaf798c70035b3faebad546d034bab268670a/odoo/tools/sql.py#L156

2023-04-25 07:18 UTC, hugho-ad commented
@xmo-odoo 

Done, I added the if statement, could you please review?

2023-04-29 22:36 UTC, hugho-ad commented
hello @xmo-odoo 

we made the requested changes, could you review it again please?

regards

2023-05-11 16:24 UTC, luisg123v requested changes
Typo in description:

PortgreSQL -> PostgreSQL

2023-05-11 16:54 UTC, carralc commented
> Hello @xmo-odoo
> 
> > Fair enough. Though in that case I'd request that you perform the drop conditionally, as table_kind provides that information.
> 
> Do you mean something like following:
> 
> ```python
> def drop_view_if_exists(cr, viewname):
>     kind = table_kind(cr, viewname)
>     if kind == 'm':
>             cr.execute("DROP MATERIALIZED VIEW IF EXISTS %s CASCADE" % (viewname,))
>     else:
>         cr.execute("DROP view IF EXISTS %s CASCADE" % (viewname,))
> ```
> 
> I'm curious what's wrong with the this way?
> 
> https://github.com/odoo/odoo/blob/faabaf798c70035b3faebad546d034bab268670a/odoo/tools/sql.py#L156

Actually, I would prefer something like this:

```python
def drop_view_if_exists(cr, viewname):
    kind = table_kind(cr, viewname)
    if kind == 'v':
        cr.execute("DROP view IF EXISTS %s CASCADE" % (viewname,))    
    elif kind == 'm':
        cr.execute("DROP MATERIALIZED VIEW IF EXISTS %s CASCADE" % (viewname,))
    else:
        "warning or something"
```
over this:
```python
if kind in ('v', 'm'):
     cr.execute("DROP {0} VIEW IF EXISTS {1} CASCADE".format("MATERIALIZED" if kind == "m" else "", viewname))
else:
    "warning"
```
Given that in the second flow, we are performing the same comparison twice unnecesarily: first in `kind in ('v','m')` and secondly while formatting `"DROP {0} VIEW IF EXISTS {1} CASCADE".format("MATERIALIZED" if kind == "m" else "", viewname)`

And as @xmo-odoo said, we want to optimize for non-materialized views, which is the case 99% of the time

2023-05-17 07:32 UTC, robodoo commented
Merge method set to squash.

2023-05-17 08:47 UTC, closed without merging