[FIX] account: fix the issue of unsupported operand in payment terms
odoo/odoo pull request #118058
Opened 2023-04-07 13:08 UTC by paso-odoo

If applied, this commit will solve the issue of the payment terms 'Example Date' issue while we keep that blank and try to save the Payment Term.

Steps to produce:
- Open any Payment Term.
- Remove the example date and click on the Save button.

Added a default value while the example date is not getting.

sentry - 4065889321
see - https://tinyurl.com/2caru9dd

2023-04-07 13:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/118058).

2023-04-10 05:12 UTC, paso-odoo commented
@odoo/sentry_reviewers 

Can you please check this PR?

Thanks!

2023-04-13 06:22 UTC, jbw-odoo commented
Hello,
When I open an existing payment term, remove the example date and save it works just fine. I can trig the error if I remove the date, then add a line tho.
So code lgtm, maybe update "steps to reproduce" ?
@smetl

2023-04-14 05:42 UTC, paso-odoo commented
@jbw-odoo The requested change is done.

Thank you!

2023-04-14 06:43 UTC, jbw-odoo commented
> @jbw-odoo The requested change is done.
> 
> Thank you!

Thx, I don't hace r+ rights, that's why I pinged las. If you don't hear from him, reping him or so else :)

2023-04-17 13:05 UTC, paso-odoo commented
@smetl 

Can you please check this?

2023-04-27 06:50 UTC, smetl requested changes

2023-04-27 06:50 UTC, smetl commented on addons/account/models/account_payment_term.py
> +                date = record._get_last_discount_date_formatted(record.example_date or fields.Date.today())
```suggestion
                date = record._get_last_discount_date_formatted(record.example_date or fields.Date.context_today(record))
```

2023-04-27 13:10 UTC, paso-odoo commented
@smetl 

The requested changes are done.

Thank you!

2023-05-02 06:33 UTC, smetl approved these changes
@robodoo r+

2023-05-02 08:38 UTC, closed without merging