[FIX] web_unsplash: accept premium image URL
odoo/odoo pull request #118147
Opened 2023-04-10 07:13 UTC by maan-odoo

"ERROR: Unknown Unsplash URL!" is generated when we try to add premium
Unsplash images. This is because when we add the unsplash image, it accepts
the image whose URL starts with "https://images.unsplash.com/" but the premium
image URL starts with "https://plus.unsplash.com/".

Traceback on sentry:
![image](https://user-images.githubusercontent.com/98319223/230847994-3e6c64b9-796a-49bf-9d09-12d043bec46b.png)

This commit solves the above issue by checking that the premium splash
image link starts with the correct format.

sentry-4075507166

2023-04-10 07:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/118147).

2023-04-10 07:15 UTC, maan-odoo commented
Hello @odoo/sentry_reviewers 
Can you please review this PR.

Thanks!

2023-04-11 04:51 UTC, abz-odoo requested changes

2023-04-11 04:51 UTC, abz-odoo commented on addons/web_unsplash/controllers/main.py
> +                if not url.startswith('https://images.unsplash.com/') and not url.startswith('https://plus.unsplash.com/'):
Maybe this is more concise ?
```suggestion
                if not url.startswith(('https://images.unsplash.com/', 'https://plus.unsplash.com/')):
```

2023-04-11 08:53 UTC, rdeodoo approved these changes
Ty
@robodoo r+

Unsplash licensing has very strict licensing and guidelines (which we negociated our own on top of it). I didn't know about the premium/plus part of Unsplash but the licensing seems to be the same: https://unsplash.com/plus/license

2023-04-11 10:12 UTC, closed without merging