[FIX] product: prevent getting value of domain from other method
odoo/odoo pull request #118339
Opened 2023-04-12 12:50 UTC by prec-odoo

While creating a new product in product category with barcode value in inventory module, `_check_barcode_uniqueness` method is called. In which variable 'domain' is passed, and getting wrong value.

Steps to Produce:-
1) Go to Inventory then configuration
2) Click on 'Product Categories' under products
3) Click/Create Product Category
4) Click stat button 'product'
5) Create a product
6) Then add barcode value
7) Click on Save
8) Trace-back will be generated

Reason:-

While creating new product from product category when user add the barcode value in product form, the '_check_barcode_uniqueness' method is called. In this method the value of 'domain' is getting updated by reference from variable 'domain' from method '_search' present in the same model. This results in a traceback with the message

'Invalid field product.packaging.categ_id'.

Applying these changes will resolve this issue.

See:-
![ValueError-Invalid-field-product-packaging-categ_id-in-leaf-categ_id-child_of-6-online-saas](https://user-images.githubusercontent.com/120083663/231462283-d54d3e99-6eda-4fae-b7a8-f6e586367e5e.png)

sentry - 4073963761

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-04-12 12:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/118339).

2023-04-13 06:22 UTC, prec-odoo commented
Hello @odoo/sentry_reviewers  Can you please look into this PR?

Thank you!

2023-04-13 09:50 UTC, yelizariev requested changes
I propose to make copy in `_search` method instead

2023-04-13 10:44 UTC, prec-odoo commented
> I propose to make copy in `_search` method instead
> 
> https://github.com/odoo/odoo/blob/3e21dad7be482c7dbb9cd50619adf89c4b35cb8a/addons/product/models/product_product.py#L396-L401

Hello @yelizariev , I tried this but it didn't work. Thanks!

2023-04-13 13:46 UTC, yelizariev commented
@prec-odoo can show what you have tried exactly?

2023-04-14 06:26 UTC, prec-odoo commented
> @prec-odoo can you show what you have tried exactly?

@yelizariev , the solution has been updated. Can you please check the latest solution?

2023-04-14 10:56 UTC, yelizariev commented on addons/product/models/product_product.py
> +            args.copy().append((('categ_id', 'child_of', self._context['search_default_categ_id'])))
```suggestion
            args = args.copy()
            args.append((('categ_id', 'child_of', self._context['search_default_categ_id'])))
```

2023-04-14 12:18 UTC, prec-odoo commented on addons/product/models/product_product.py
> +            args.copy().append((('categ_id', 'child_of', self._context['search_default_categ_id'])))
> 

@yelizariev , changes has been done.

2023-04-14 14:09 UTC, yelizariev commented
@nle-odoo ?

2023-05-09 13:13 UTC, nle-odoo approved these changes
looks good to me

this is a small equivalent change, but that is fixing an error:

robodoo r+

2023-05-09 13:18 UTC, adwid commented on addons/product/models/product_product.py
>              args.append((('categ_id', 'child_of', self._context['search_default_categ_id'])))
```suggestion
            args = args + [('categ_id', 'child_of', self._context['search_default_categ_id'])]
```
Better for the perf (I know, it's a detail, but still)
robodoo delegate=yelizariev

2023-05-09 15:30 UTC, closed without merging