[IMP] pos_sale: Possibility to apply fixed amount on downpayment
odoo/odoo pull request #118594
Opened 2023-04-14 11:12 UTC by adgu-odoo

Until now, it was not possible to apply fixed amount on downpayment. Users were forced to compute the percentage to apply on a downpayment on the side when the wanted to apply a fixed downpayment. Now the user can choose to apply a down payment based on fixed amount or percentage from the PoS frontend. This PR also changes the NumberPopup to add a percentage or the currency of the company side to the buffer field.

task-id: 2836904

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-04-14 11:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/118594).

2023-04-14 11:59 UTC, rhe-odoo commented on addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
> +            subtitle: "Je sais pas je mets des trucs.",
It's the way to go!

2023-05-09 08:29 UTC, caburj commented on addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
> +                                    return "";
```suggestion
                                    return false;
```

2023-05-10 09:41 UTC, caburj requested changes
Resolve then we can proceed.

2023-05-10 09:41 UTC, caburj commented on addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
> +                    });
add in the commit message about this fix/imp.

2023-05-10 09:41 UTC, caburj commented on addons/point_of_sale/static/src/js/Popups/NumberPopup.js
> +        totalDue: 0,
this is unused. It can be removed.

2023-05-10 09:41 UTC, caburj commented on addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
> +                        totalDue: popupTotalDue,
This is unused, can be removed.

2023-05-10 11:37 UTC, caburj approved these changes
Top!

@robodoo r+

2023-05-10 14:37 UTC, closed without merging