[IMP] hr_recruitment(_skills/_survey): grant interviewer more rights
odoo/odoo pull request #118897
Opened 2023-04-18 09:35 UTC by sofiagvaladze

Purpose: In order to increase visibility of the interviewer group, it is moved from hidden group, to recruitment group.

Moreover, we grant the interviewer additional rights in order to manage the application process properly and be able to execute following actions • Send an interview
• Check interview results
• Add/delete/modify skills
• Create a meeting

In order to allow above mentioned actions on skills to the interviewer, we grant them all the rights to the hr_applicant_skill.

In order to let the interviewer send the survey we grant them access to the private addresses and now recruitment-interviewer implies survey-officer group as well.

Additionally, for the security purposes, we make a change, so that the survey officer is not able to read recruitment interview results unless they are also an interviewer for a specific applicant.

task - 3179332

2023-04-18 09:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/118897).

2023-05-05 12:08 UTC, Bertrand2 approved these changes
LGTM! Apart from the comments discussed on the task, there's only some nitpicking on the english :ok_hand:

2023-05-05 12:08 UTC, Bertrand2 commented on addons/hr_recruitment_survey/security/hr_recruitment_survey_security.xml
> +            <field name="name">Survey user input: recruitment interview: read survey answers that they are set as an interviewer</field>
```suggestion
            <field name="name">Survey user input: recruitment interview: read survey answers for which they are set as interviewer</field>
```

2023-06-14 12:55 UTC, kba-odoo requested changes

2023-06-14 12:55 UTC, kba-odoo commented on addons/hr_recruitment_skills/security/hr_recruitment_skills_security.xml
> +        <field name="name">Applicant Skill: Interviewer</field>
```suggestion
        <field name="name">Applicant Skill: Officer</field>
```

2023-06-14 12:55 UTC, kba-odoo commented on addons/hr_recruitment_survey/security/hr_recruitment_survey_security.xml
> +            <field name="domain_force">[('applicant_id', '!=', False), ('applicant_id.interviewer_ids', 'in', user.id)]</field>
Shouldn't you add `applicant_id.job_id.interviewer_ids` as well?

2023-06-27 08:32 UTC, kba-odoo commented
robodoo r+

2023-06-27 16:41 UTC, closed without merging

2024-01-30 12:57 UTC, lm4649 reviewed
Hi @tde-banana-odoo, @sofiagvaladze 
Thank you for your reviews! :smile: :prey
I've updated the code according to your suggestions. 
Concerning the fact that the interviewers own the survey users rights, I don't have a third way to propose. Does leaving things as they are pose potential security problems?