[FIX] project: allows to quick create record from My Tasks kanban
odoo/odoo pull request #119055
Opened 2023-04-19 11:34 UTC by huca-odoo

The refactor of the kanban quick create implemented in https://github.com/odoo/odoo/pull/117449 introduced a traceback when creating a task from the My Tasks kanban view due to the presence of 'default_personal_stage_type_ids' key in the context.

This commit fix that by removing this key from the context in the customization of the kanban view for project.task model.

task-3281005

2023-04-24 09:37 UTC, auon-odoo requested changes
Thank you for the fix! :fire: 
Could you please write a commit message with the following structure:
- Steps (how to reproduce the issue)
- Issue (what is happening vs what is expected)
- Cause (technical explanation)
- Fix (in consequence of the cause, why this way to fix it is best)

Of course, sometimes, some of it is obvious. But generally, it provides the reviewer with a much needed context. (And personally, writing this "report" actually made me rethink my fix a few times.)
In this particular case, it is not obvious to me why having a key in the context would result in a traceback, nor why it is not needed and so can be deleted without consequences.

Thanks again :pray:

2023-04-24 09:37 UTC, auon-odoo commented on addons/project/static/src/views/project_task_kanban/project_task_kanban_record_quick_create.js
> +        delete this.quickCreateProps.context.default_personal_stage_type_ids
```suggestion
        const res = await super.getQuickCreateProps(props);
        delete this.quickCreateProps.context.default_personal_stage_type_ids;
        return res;
```
Shouldn't we return something? :thinking:

2023-04-24 15:45 UTC, huca-odoo commented
> Thank you for the fix! fire Could you please write a commit message with the following structure:
> 
> * Steps (how to reproduce the issue)
> * Issue (what is happening vs what is expected)
> * Cause (technical explanation)
> * Fix (in consequence of the cause, why this way to fix it is best)
> 
> Of course, sometimes, some of it is obvious. But generally, it provides the reviewer with a much needed context. (And personally, writing this "report" actually made me rethink my fix a few times.) In this particular case, it is not obvious to me why having a key in the context would result in a traceback, nor why it is not needed and so can be deleted without consequences.
> 
> Thanks again pray

I've updated the commit message and changed the implementation as it wasn't working really well... Thanks for your comment!

2023-04-24 15:58 UTC, auon-odoo approved these changes
Lgtm! Amazing commit message :heart_eyes: :heart_eyes:

2023-05-04 09:54 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂 

robodoo r+

2023-05-04 11:17 UTC, closed without merging