[FIX] hr_holidays: remove employee requests must remove validation type
odoo/odoo pull request #119013
Opened 2023-04-19 05:20 UTC by thle-odoo

Steps to reproduce:
- create a time off type;
- select 'Extra Days Requests Allowed' for 'Employee Requests';
- select 'Approved by Time Off Officer' for Approval;
- choose a Responsible Time Off Officer;
- change the select for 'Employee Requests' and select 'Not Allowed';
- create an allocation for an employee with this type.

Issue:
The allocation is blocked at step 'TO APPROVE'.

Cause:
Even if we choose `no` for `employee_requests`,
the `allocation_validation_type` always contains `officer`.

Solution:
If we choose `no` for `employee_requests`,
we have to reset `allocation_validation_type`.

opw-3264758

2023-04-19 05:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119013).

2023-04-19 15:40 UTC, robodoo commented
@thle-odoo @kba-odoo staging failed: ci/runbot on d8e5fca610cb6f964e31794eb5e57723c5b42972 (view more at https://runbot.odoo.com/runbot/build/30411041)

2023-04-20 05:28 UTC, thle-odoo commented
@robodoo retry

2023-04-20 06:07 UTC, robodoo commented
@thle-odoo @kba-odoo staging failed: ci/runbot on 5981b9672235cc63ac333093ceca8def206cb2b2 (view more at https://runbot.odoo.com/runbot/build/30440482)

2023-04-24 11:08 UTC, kba-odoo requested changes

2023-04-24 11:08 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_allocation.py
> +        employee_requests = {holiday.id: holiday.holiday_status_id.employee_requests for holiday in self.sudo()}
```suggestion
        employee_requests = [holiday.id for holiday in self.sudo() if holiday.holiday_status_id.employee_requests == 'no']
```

2023-04-24 11:08 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_allocation.py
> +        self.filtered(lambda holiday: (employee_requests[holiday.id] == 'no' or holiday.validation_type == 'no') and holiday.state != 'validate').action_validate()
```suggestion
        self.filtered(lambda holiday: (holiday.id in employee_requests or holiday.validation_type == 'no') and holiday.state != 'validate').action_validate()
```

2023-04-24 12:10 UTC, kba-odoo commented
robodoo r+

2023-04-24 13:34 UTC, closed without merging