[FIX] website_payment_authorize: fix external id while Authorize.net deleted
odoo/odoo pull request #119155
Opened 2023-04-20 08:50 UTC by paso-odoo

If applied, this commit solves the issue of External ID not found in the system: payment.payment_provider_authorize.

Steps to produce:
- Open the Payment Providers menu.
- Delete the 'Authorize.net' provider.
- Go to Configuration > Settings.
- Error will be generated.

sentry - 4091797215
see - https://tinyurl.com/228beh6o

2023-04-20 08:53 UTC, paso-odoo commented
@odoo/sentry_reviewers 

Can you please check this PR?

2023-04-24 08:53 UTC, yelizariev requested changes

2023-04-24 08:53 UTC, yelizariev commented on addons/website_payment_authorize/models/res_config_settings.py
> +        authorize = self.env.ref('payment.payment_provider_authorize', False)
Meaning of the second parameter might be confusing if you don't specify its name

```suggestion
        authorize = self.env.ref('payment.payment_provider_authorize', raise_if_not_found=False)
```

2023-04-24 08:53 UTC, yelizariev commented on addons/website_payment_authorize/models/res_config_settings.py
> +        authorize = self.env.ref('payment.payment_provider_authorize', False)
```suggestion
        authorize = self.env.ref('payment.payment_provider_authorize', raise_if_not_found=False)
```

2023-04-24 08:53 UTC, yelizariev commented on addons/website_payment_authorize/models/res_config_settings.py
> +            authorize.sudo().capture_manually = capture_manually
We can keep original code if  `authorize` variable is checked before, i.e.

```py
        authorize = self.env.ref('payment.payment_provider_authorize', raise_if_not_found=False)
        if not authorize:
            return
```

The same is applied for `get_values`

2023-04-27 13:06 UTC, paso-odoo commented
@yelizariev 

The requested changes are done.

Thank you!

2023-05-02 11:45 UTC, AntoineVDV commented
Hello, I am closing the PR because it will become necessary after https://github.com/odoo/odoo/pull/119140 is merged :)

Deleting a payment provider has never been supported, but the `unlink` override to prevent it was missing. Customers who have deleted a payment provider should be handled by Tech Support who should uninstall the corresponding module and update the `payment` module to re-create the missing record and xmlid.

2023-05-02 11:45 UTC, closed without merging