[FIX] website_form: prevent input field type change
odoo/odoo pull request #119293
Opened 2023-04-21 06:04 UTC by divy-odoo

Overwritten the field type.
`_getActiveField` is obtaining the non-custom fields from the database(of type `char`),which was creating an issues of field type changes to `text` during the re-rendering of the field.

task-3247520

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-04-21 06:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119293).

2023-04-26 11:40 UTC, xO-Tx requested changes
Hello @divy-odoo thanks for the fix :+1: just a small remark about the commit message:

In general, it should follow this structure:

```
[IMP|FIX|...] module 1,... module n-2, *: title (max: 72 chars)

*: module n-1, module n (optional: only when title > 72 chars)

Message... (max: 72 chars & mainly explains the purpose of the diff...)
...

task|opw|runbot-xxxxxxx
```

So I suggest something like (feel free to change it as you like :+1:):

```
[FIX] website_form: prevent input field type change

The translation of input "default values" is allowed only when
`type="text"`. However, email field values are translatable on 15.0
because of a strange behaviour:

- Go to website (Edit mode) > Add a form block.
- Select the existing email field > Change the label position > The
input is transformed into a `type="text"`.

Each time a "non-custom" field is re-rendered, The `_getActiveField()`
method is obtaining field related data from the database, including its
type, which changes it back to the original value ("char").

The goal of this commit is to fix this behaviour on 14.0 (which will
prevent translating email values on 15.0) using the `_getFieldType()`
to set the right field type instead of the default one.

task-3247520
```

@qsm-odoo fixing the type consistency here will make the email inputs default
values "non-translatable" on 15.0 (which seems correct following the code
in [translate_attrib_value()](https://github.com/odoo/odoo/blob/07263c78719583e76916911b303fc0df79035f31/odoo/tools/translate.py#L159-L162)) so just to be sure, are we OK with this?

2023-04-27 14:38 UTC, qsm-odoo commented
> fixing the type consistency here will make the email inputs default values "non-translatable" on 15.0, are we OK with this?

@xO-Tx I don't see in which case you would like to translate an email so it seems ok yes? (what you are saying, I did not look at the PR)

2023-04-28 08:47 UTC, divy-odoo commented
Hello @qsm-odoo @xO-Tx,

For more clarity, 
According to conventions, the `default value` of the email field will be an email address that should not be translated.

Having strange behaviour where the type changes from `email` to `text` was causing problems with translating the default value in 15.0 and 16.0 (since the default value was introduced in version 15.0). However, the strange behaviour of type changes continued from version 14.0.

This PR prevent unexpected type changes from `email` to `text` while no direct changes have been made to the field type.

2023-05-17 11:21 UTC, divy-odoo commented
@qsm-odoo @xO-Tx  can you please review this PR and let me know if any changes are required?

2023-05-17 11:33 UTC, xO-Tx commented
@divy-odoo LGTM :+1:
cc @qsm-odoo for maybe a final check and r+ :+1:

2023-05-24 09:29 UTC, qsm-odoo commented
@xO-Tx I'll trust you to make the merge when ready for you :)

@robodoo delegate=xO-Tx

2023-06-05 11:47 UTC, divy-odoo commented
@xO-Tx Can you please review?

2023-06-05 17:12 UTC, xO-Tx commented
@divy-odoo Sorry for the late reply !
I just had to force push to fix the commit message (max: 72 chars...) as mentioned [here...](https://github.com/odoo/odoo/pull/119293#issuecomment-1551239227) Thanks for the fix :+1:

@robodoo r+

2023-06-05 18:30 UTC, closed without merging