[FIX] hr_holidays : Remove automatic notification if no responsible_ids is set
odoo/odoo pull request #119388
Opened 2023-04-21 13:48 UTC by jugj-odoo

Currently in hr_leaves_type, if no responsible_ids are set, all members of group_hr_holidays_user would get notified.
The new behavior changes that to : If no responsible_ids are set, no one is notified.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-04-21 13:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119388).

2023-04-24 08:03 UTC, sofiagvaladze requested changes
@jugj-odoo, thanks for your work ^^

So, this changes (if responsible is not set, notify all time off officers) was part of the https://github.com/odoo/odoo/pull/107804

We would also need to change` ['hr.leave']._get_responsible_for_approval `, as https://github.com/odoo/odoo/pull/107804/files#diff-38469def2f870bb866f971f57797dd7c21b6a95d52a8eae72f832f0eea2434f9R1593-R1602 all those officers will still receive activities otherwise.

The same changes were done for allocations as well. We are reverting this for leave, that makes me wonder whether same should be done for allocations. Maybe we can check it with Geoffrey.
Thanks :raised_hands:

2023-05-11 10:18 UTC, sofiagvaladze commented on addons/hr_holidays/models/hr_leave.py
>              else:
This is not needed, because if there is no responsible_ids, then we should get default `responsible = self.env.user`

2023-05-11 10:18 UTC, sofiagvaladze commented on addons/hr_holidays/models/hr_leave_allocation.py
>              else:
same here as on leaves

2023-05-31 10:53 UTC, kba-odoo requested changes

2023-05-31 10:53 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_allocation.py
> +                    if allocation.holiday_status_id.responsible_ids:
```suggestion
                    if allocation.holiday_status_id.responsible_ids:
                        user_ids = allocation.sudo()._get_responsible_for_approval().ids
```

2023-05-31 10:53 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +                if holiday.holiday_status_id.responsible_ids:
Move the `user_ids =` in the if, as it's not needed if there are no responsibles

2023-05-31 10:53 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +                            'activity_type_id': self.env.ref('hr_holidays.mail_act_leave_approval').id,
Even though it's the existing code, the 2 `ref()` can be moved outside of the for loop to speed things up a little bit

2023-05-31 10:53 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_allocation.py
> +                                'activity_type_id': self.env.ref('hr_holidays.mail_act_leave_allocation_approval').id,
Same here for the ref()

2023-06-05 14:15 UTC, kba-odoo commented
robodoo r+

2023-06-05 17:31 UTC, robodoo commented
@jugj-odoo @kba-odoo staging failed: ci/runbot on ec83438722232525e2a6dca4432f7b9944c479a8 (view more at https://runbot.odoo.com/runbot/build/42439694)

2023-06-12 09:15 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +        model_hr_leave_id = self.env.ref('hr_holidays.model_hr_leave').id
Should be moved before the `user_ids = holiday.sudo()._get_responsible_for_approval().ids or self.env.user.ids` to not fetch the records even they are not needed (that's why the staging failed I think) - same thing below

2023-06-13 08:56 UTC, closed without merging