[FIX] stock_account: prevent stock account update on product change when using manual stock valuation
odoo/odoo pull request #119535
Opened 2023-04-24 14:39 UTC by rigr-odoo

If the category of a product is using manual stock valuation, when changing the product on an invoice line, the account should not be set to the `property_stock_account_input_categ_id`. It should be the case only if we use automatic/real-time stock valuation.

opw-3226536

2023-04-24 14:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119535).

2023-04-25 09:21 UTC, Levizar requested changes

2023-04-25 09:26 UTC, rigr-odoo commented on addons/stock_account/models/account_move.py
> +            if accounts['stock_input'] and self.product_id.categ_id.property_valuation == 'real_time':
Done, thx !

2023-04-25 12:43 UTC, Levizar approved these changes
@robodoo r+

2023-04-25 14:05 UTC, closed without merging