[FIX] web_editor: fix grid mode with inner snippet outside a row
odoo/odoo pull request #119965
Opened 2023-04-27 12:33 UTC by sobo-odoo

Before this commit, there were cases where toggling the grid mode did not work. These cases are:
- when a snippet has None columns (e.g. Cover) and that an inner snippet containing a row (e.g. Form) was dropped in it,
- when a snippet has some content outside its row (e.g. Picture) and that an inner snippet containing a row was dropped in this outside content.

This happens because the row that was taken into account when toggling the grid mode was the first `.row` element found in general, instead of only considering the container children. Therefore, what happened in these buggy cases is that the row found was the inner snippet one, which should not be the case and caused the toggle to fail because it was trying to put the element inside itself.

This commit fixes this by only considering the container children when looking for the row element when toggling the grid mode.

task-3279191

2023-04-27 12:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119965).

2023-05-11 12:53 UTC, qsm-odoo commented
@robodoo delegate=Guillaume-gdi

2023-05-11 14:22 UTC, Guillaume-gdi requested changes

2023-05-11 14:22 UTC, Guillaume-gdi commented on addons/web_editor/static/src/js/common/grid_layout_utils.js
> +            columnEl.prepend(outOfRowEls[i]);
What if we have a structure like this
```html
<div class="container">
        <div class="row">
                <div class="col-lg-4" ></div>
                <div class="col-lg-4" ></div>
                <div class="col-lg-4" ></div>
        </div>
        <div class="row">
                <div class="col-lg-4" ></div>
                <div class="col-lg-4" ></div>
                <div class="col-lg-4" ></div>
        </div>
</div>
```
One container with two `.row`... The second one will be skipped no ?

2023-05-15 07:17 UTC, Guillaume-gdi commented on addons/web_editor/static/src/js/common/grid_layout_utils.js
> +            columnEl.prepend(outOfRowEls[i]);
Ok let's say it is a limitation of the current options.

2023-05-15 07:36 UTC, Guillaume-gdi approved these changes
@robodoo r+

2023-05-15 08:44 UTC, closed without merging