[FIX] loyalty: fix missing loyalty product update issue
odoo/odoo pull request #119926
Opened 2023-04-27 09:39 UTC by paso-odoo

If applied, this commit will solve the issue of missing product issue while installing the following modules: loyalty_delivery, pos_loyalty, sale_loyalty, website_sale_loyalty

Steps to produce:
- Install loyalty module.
- Go to 'Products' or 'Product Variants'.
- Delete the product 'Gift Card'.
- Now install the 'sale_loyalty' module.

This commit will raise an userError while deleting the loyalty products.

sentry - 4112536971
see - https://tinyurl.com/2bm5qw3f

2023-04-27 09:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/119926).

2023-04-28 10:55 UTC, paso-odoo commented
@odoo/sentry_reviewers 

Please check this PR.

Thanks!

2023-04-28 11:06 UTC, yelizariev requested changes
What do you need to extend product.template? `ondelete` method of product.product is not called on deleting product.template?

2023-04-28 11:06 UTC, yelizariev commented on addons/loyalty/models/product_product.py
> +            raise UserError(_("You cannot delete %s as it is used in another module but you can archive it instead.", product.name))
Phrase "another module" doesn't make any sense for user. They just see Odoo UI and they don't know what is current module and what is another module

2023-04-28 11:06 UTC, yelizariev commented on addons/loyalty/models/product_product.py
> +
It should be done in a new file `product_template.py`

2023-04-28 11:17 UTC, paso-odoo commented
> What do you need to extend product.template? `ondelete` method of product.product is not called on deleting product.template?

@yelizariev Yes, I have tried in both objects respectively but it is required to put ondelete method in 'product.product' and 'product.template'. If you have any suggestions please let me know.

2023-05-08 12:52 UTC, vava-odoo reviewed
Thanks @paso-odoo for the fix. 
Please try to follow the guidelines (alphabetical order, max 100 characters per line, ...).

2023-05-11 08:47 UTC, paso-odoo commented
@vava-odoo 

The requested changes are done.
Thank you!

2023-05-11 09:32 UTC, Feyensv commented on addons/loyalty/models/product_product.py
> +                "Please archive it instead.",
```suggestion
                " Please archive it instead.",
```

2023-05-11 09:32 UTC, Feyensv commented on addons/loyalty/models/product_template.py
> +                "Please archive it instead.",
```suggestion
                " Please archive it instead.",
```

2023-05-11 09:32 UTC, Feyensv commented on addons/loyalty/i18n/loyalty.pot
> +"You cannot delete %(name)s as it is used in 'Coupons & Loyalty'.Please "
```suggestion
"You cannot delete %(name)s as it is used in 'Coupons & Loyalty'. Please "
```

2023-05-11 11:01 UTC, Feyensv approved these changes
@robodoo delegate+

2023-05-11 11:25 UTC, abz-odoo commented
Hello @paso-odoo , you chave the rights to make a @robodoo r+

2023-05-11 11:54 UTC, paso-odoo commented
@robodoo r+

2023-05-11 13:26 UTC, closed without merging