[FIX] website: enable animations when a cookie bar is displayed
odoo/odoo pull request #120294
Opened 2023-05-02 12:30 UTC by Guillaume-gdi

Before this commit, when a cookie bar was displayed on a page and
elements of that page were animated (on scroll and on appearance), those
animations did not work while the cookie bar was present. This commit
fixes that and enables animations even if a cookie bar is displayed. The
problem was that we were looking to see if a modal (cookie bar, popup)
was displayed and if it was, all animations were based on the scroll
height of that modal. However, this should only be done for elements
that are in the modal. The other elements should always base their
animation on the scroll height of the page.

task-3151000

2023-05-02 12:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/120294).

2023-05-02 13:16 UTC, Guillaume-gdi commented on addons/website/static/src/js/content/snippets.animation.js
> +            ).is(":visible");
Maybe I could base my selector on the id `website_cookies_bar` but it seems a bit more risky to me

2023-05-02 13:27 UTC, rdeodoo requested changes
Can you mention https://github.com/odoo/odoo/commit/2d080ca835c7668bf317d6632bd0f49916a402d6 pls

2023-05-02 13:41 UTC, Guillaume-gdi commented on addons/website/static/src/js/content/snippets.animation.js
> +            ).is(":visible");
My "fear" is that a user has custom code with a custom cookie bar to which he would have given this ID (which by the way is not prefixed by `o_` :grimacing: ) and that my code changes something for him. In my opinion I'm going too far in my questioning of what could break in stable. I gonna use the ID :+1:

2023-05-03 13:05 UTC, Guillaume-gdi commented
Note that since [1], there is a traceback when there is a cookie bar on a website. Before [1] animations were working fine with cookie bar. The traceback only disappeared with [2]. So the flow of this PR is not easily testable between [1] and [2]. Note that after [2] there is no traceback but the animation problem is there. I cannot say which commit is responsible of the issue this PR solve but I can say it is one commit between [1] and [2].

[1]: https://github.com/odoo/odoo/commit/c48f57ea2538ad51e00ac27d58f8e191781444f3
[2]: https://github.com/odoo/odoo/commit/cb7cf77ed080e86f800af61c9a3dc4ad36ad6cfb

2023-05-03 16:51 UTC, rdeodoo requested changes
Quickly testing, seems like a flow that was working before is not anymore:
- Popup + Cookies bar
Before: https://watch.screencastify.com/v/A2j2qZRWEygCkJZAw7C0
After: https://watch.screencastify.com/v/4Y0KVDK5DqMBAhH9fwpI

I also found this one which was not working before and still not after:
- Cookie bar as popup layout: animation effect on image won't appear https://watch.screencastify.com/v/BYTG4clD0tUkzYsoTlPg
But this one could be considered a limitation, especially since when the backdrop option is enabled it's working (as it's removing the double scroll bar)
Maybe there is something deep down to fix that would align all those cases? Maybe the scrolling element is not the correct one somewhere in the computation.

I didn't check technically, let me know if you want me to have a look, I really don't know much about that part.

2023-05-04 09:25 UTC, Guillaume-gdi commented
> Quickly testing, seems like ... still some issues

Thanks for testing, it is fixed now :+1:

2023-05-09 08:41 UTC, bvr-odoo commented
@Guillaume-gdi Note that this should be fixed by this PR https://www.odoo.com/web#id=3102275&menu_id=4720&cids=1&action=4043&model=project.task&view_type=form

2023-05-12 16:58 UTC, rdeodoo approved these changes
@robodoo r+

Ty, first bug reported in my previous message is correctly fixed, the second is not but it's a weird case, it's fine.
The initial error is correctly fixed too.
Note that is partially reverting https://github.com/odoo/odoo/commit/2d080ca835c7668bf317d6632bd0f49916a402d6 which was fixing the same issue back in the days (related to https://www.odoo.com/web#id=2712755&cids=1&model=project.task&view_type=form) :grimacing: . But it's still fixed too.

I am a bit sad because there is no way this fix will last long and that the scroll/animate won't be broken soon.
It's just an endless story at this point, even when only considering the scroll bar and popup, I don't even want to imagine adding the animations on top of all that..
See https://www.odoo.com/web#id=2983901&cids=1&model=project.task&view_type=form :grimacing: 

This is almost impossible to write some tests for all this :/

2023-05-15 12:41 UTC, rdeodoo commented
@robodoo r+
Seems like my previous message was ignored
![image](https://github.com/odoo/odoo/assets/30048408/c9e373ae-3624-4749-b64a-ea943b1f45a0)

2023-05-15 16:59 UTC, closed without merging