[FIX] point_of_sale: prevent traceback while name of coins/bill is st…
odoo/odoo pull request #120207
Opened 2023-05-01 04:48 UTC by prec-odoo

…ring

When we input some string in many2many field under Coins/Bills in configuration setting of point of sale module . it will give an error with the message -

'could not convert string to float'

Steps to Produce:-

1. Go to Point of Sale then configuration
2. click on 'Settings'
3. Under 'Payment' input some string in Coins/Bills

Trace-back will be generated.

Reason -
The 'name_create' method of the 'pos_bill' model generates an error when a string is provided as input for the 'name' field, since the expression 'float(name)' is unable to convert a string to a float.

Traceback - 
```
ValueError: could not convert string to float: 'chéque cadeau'
  File "odoo/http.py", line 2115, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1922, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 28, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "addons/point_of_sale/models/pos_bill.py", line 15, in name_create
    result = super().create({"name": name, "value": float(name)})
```

Applying these changes will resolve this issue.

Sentry - 4122478677

2023-05-01 04:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/120207).

2023-05-01 04:50 UTC, prec-odoo commented
Hello @odoo/sentry_reviewers  ,

Can you please look into this PR?

Thank you!

2023-05-04 12:02 UTC, kitan191 approved these changes
LGTM

2023-05-23 06:57 UTC, kitan191 commented
Hi @caburj 

Could you review this PR?

Thanks.

2023-05-23 07:02 UTC, caburj commented on addons/point_of_sale/models/pos_bill.py
>          return result.name_get()[0]
```suggestion
        try:
            value = float(name)
        except:
            raise UserError(_("The name of the Coins/Bills must be a float."))
        result = super().create({"name": name, "value": value})
        return result.name_get()[0]
```

2023-05-23 07:03 UTC, caburj requested changes

2023-05-23 07:03 UTC, caburj commented on addons/point_of_sale/models/pos_bill.py
> +            raise UserError(_("The name of the Coins/Bills must be a float."))
```suggestion
            raise UserError(_("The name of the Coins/Bills must be a number."))
```

2023-05-23 07:03 UTC, caburj commented on addons/point_of_sale/i18n/point_of_sale.pot
> +
Update this after the change in the user error message.

2023-05-23 07:34 UTC, prec-odoo commented on addons/point_of_sale/models/pos_bill.py
> +            raise UserError(_("The name of the Coins/Bills must be a float."))
@caburj ,
Changes are done!

2023-05-23 07:50 UTC, caburj approved these changes
Thank you!

@robodoo r+

2023-05-23 09:51 UTC, closed without merging