[IMP] point_of_sale,pos_*: preparation tools for everyone
odoo/odoo pull request #120447
Opened 2023-05-03 13:01 UTC by davidmonnom

2023-05-03 13:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/120447).

2023-05-16 14:25 UTC, caburj commented
Is there no way to write test for this dev?

2023-05-22 08:05 UTC, davidmonnom commented
> Is there no way to write test for this dev?

Done and green :)

2023-05-22 08:15 UTC, caburj commented on addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
> +            if (Object.keys(order.lastOrderPrepaChange)) {
Do you intend to compare the length to zero like so: `Object.keys(order.lastOrderPrepaChange).length !== 0)`?

2023-05-22 08:17 UTC, caburj commented
> > Is there no way to write test for this dev?
> 
> Done and green :) [odoo/enterprise#40673](https://github.com/odoo/enterprise/pull/40673)

On it.

2023-05-22 13:03 UTC, caburj requested changes
If `pos_preparation_display` is uninstalled, the feature the cancels the order from the kitchen printer doesn't work. It thinks that there are no changes to print. Here are the steps to reproduce:

1. Install `pos_restaurant`.
2.  Uninstall `pos_preparation_display`.
3. Setup a preparation printer.
4. Open a bar.
5. Add a product that can be sent to the preparation printer.
6. Order. (Error popup but it's okay, the order is sent.)
7. [ISSUE] When deleting the order, there is no "changes to print" that is sent to the printer.

2023-05-22 14:08 UTC, davidmonnom commented
> If `pos_preparation_display` is uninstalled, the feature that cancels the order from the kitchen printer doesn't work. It thinks that there are no changes to print. Here are the steps to reproduce:
> 
> 1. Install `pos_restaurant`.
> 2. Uninstall `pos_preparation_display`.
> 3. Setup a preparation printer.
> 4. Open a bar.
> 5. Add a product that can be sent to the preparation printer.
> 6. Order. (Error popup but it's okay, the order is sent.)
> 7. [ISSUE] When deleting the order, there is no "changes to print" that is sent to the printer.

Should be good

2023-05-22 14:59 UTC, caburj commented
> Should be good

Yeah, maybe it's already printing. But I there is something wrong in the items being printed.

I tested this workflow for 2 situations - with and without pos_preparation_display.
### Steps
1. Create an order, add 1 item and send for preparation (click Order button).
2. Delete the order and check the result of `changesToOrder` which is used for both the preparation printers and displays.

### Results

*With pos_preparation_display*

<img width="1512" alt="Screenshot 2023-05-22 at 16 46 34" src="https://github.com/odoo/odoo/assets/3245568/19eb332b-dd47-4b43-bae9-7589fb36cc0b">

*Without pos_preparation_display*

<img width="1512" alt="Screenshot 2023-05-22 at 16 44 01" src="https://github.com/odoo/odoo/assets/3245568/b86a72eb-fab1-491d-aff7-367329e97f8c">

### Conclusion

I think regardless of presence of `pos_preparation_display`, the result of `changesToOrder` when deleting the order should be the same. In this case, they differ in sign. Basically, the kitchen printer should print the same thing for the same workflow.

You might be doing something wrong in the calculation of `changesToPrint` when considering the `cancelled` param.

2023-05-23 11:40 UTC, caburj commented on addons/point_of_sale/static/src/js/models.js
> +                lineChange["quantity"] = Math.abs(lineChange["quantity"]); // we need always positive values.
Can you quickly explain me why it's sometimes negative? I feel like we are just masking the problem by taking the absolute value.

2023-05-23 13:42 UTC, caburj approved these changes
@robodoo r+

2023-05-23 17:08 UTC, closed without merging