[FIX] web_editor: restore avoiding updates of link content
odoo/odoo pull request #120577
Opened 2023-05-04 13:52 UTC by bso-odoo

[1] mistakenly removed the variable used by the mechanism that was
introduced in [2] to avoid updating link content.

This commit uses the link's `needLabel` instead to achieve the same
goal.

Steps to reproduce:
- Add a mega menu.
- Set the mega menu template to Cards.
- Click on the text of a card.
- DO NOT click on the edit link icon in the popover.
- Click on the href field in the options panel.
- Change the value.

=> Links content was broken (image was removed and texts were grouped).

[1]: https://github.com/odoo/odoo/commit/75166dbcd4962f30624fe19829757acbf8e76022
[2]: https://github.com/odoo/odoo/commit/7a0e58f8d7237514d23d815cdf3d81fc79edb1ec

task-3300977

2023-05-04 13:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/120577).

2023-05-11 12:51 UTC, qsm-odoo requested changes
@robodoo delegate=bvr-odoo 

Maybe worth a few steps in a (existing?) tour?

2023-05-12 15:09 UTC, bvr-odoo approved these changes

2023-05-12 15:10 UTC, bvr-odoo commented
@robodoo r+

2023-05-12 16:00 UTC, robodoo commented
@bso-odoo @bvr-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-05-15 07:04 UTC, bvr-odoo commented
@robodoo rebase-ff

2023-05-15 07:05 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-05-15 08:10 UTC, closed without merging