[FIX] delivery: prevent trace back while partner has no zip
odoo/odoo pull request #120802
Opened 2023-05-08 12:56 UTC by prye-odoo

In delivery address, `country name` and in shipping method, `country name` will be same and no zip in delivery address.  While creating new sale order along with product and clicking on "Add shipping",  error will be generated.

Steps to Reproduce
-Install `sale_management' and 'delivery' modules
-Go to the settings and enable the 'Customer Address'. -Go to the settings and enable 'Shipping Methods' and configure it. -Select a shipping method and  go to the 'Destination Availability' tab and
 set to the 'Countries' and set to 'Zip Prefixes'.
-Create a new customer and add the delivery address of the customer in
 res.partner.
-The delivery address and shipping method of the 'Countries" or 'Country'
 name should be the same.
-Set the  'Zip Prefixes'
-Set the delivery address of zip code null.
-Create a new quotation and add to the customer and delivery address -Add to the product in the sale order line.
-Click on the 'Add Shipping' or 'Update Shipping Cost' button.

A trace back will be generated.

Applying this commit will resolve this issue.

sentry-4147077852

2023-05-08 12:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/120802).

2023-05-09 06:49 UTC, prye-odoo commented
Hello @odoo/sentry_reviewers 
Can you please review this PR?

Thanks!!

2023-05-09 09:38 UTC, abz-odoo commented
Hello @ticodoo What do you think about this change ?

2023-05-09 10:14 UTC, ticodoo requested changes

2023-05-09 12:37 UTC, prye-odoo commented on addons/delivery/models/delivery_carrier.py
> +            if partner.zip and not re.match(regex, partner.zip.upper()):
@ticodoo Changes Done !

2023-05-09 12:39 UTC, ticodoo approved these changes

2023-05-09 15:30 UTC, closed without merging