[FIX] website: set iframe min-width unit percentage
odoo/odoo pull request #121266
Opened 2023-05-12 11:35 UTC by can-odoo

With this commit, we changed the unit for `min-width` to `%` to show the proper
size of the video in the Masonry block.

PR: 
task-3103775

2023-05-12 11:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121266).

2023-06-06 12:55 UTC, can-odoo commented
@qsm-odoo, Can you please review this?

2023-06-06 14:26 UTC, qsm-odoo requested changes

2023-06-12 13:37 UTC, utag-odoo commented
Hello @qsm-odoo, Changes have been applied.

2023-06-12 15:20 UTC, qsm-odoo requested changes
Just a small detail: your commit message title should start with a verb (must complete the sentence "when applied, this commit will ..."). So here something like "fix video size in grid mode" or "make video cover their sized area in grid mode".

Also the commit mention `.media_iframe_videos`, the "s" should be removed. Also "to ensure" and not "to ensures".

2023-06-12 15:20 UTC, qsm-odoo commented on addons/web_editor/static/src/scss/web_editor.frontend.scss
> +    > img, .media_iframe_video {
Why not `>` just like for the images ? It would make the CSS rules more efficient but it will mainly be more consistent.

2023-06-13 07:29 UTC, utag-odoo commented
Hello @qsm-odoo, Changes applied.

2023-06-14 12:17 UTC, qsm-odoo approved these changes
@robodoo r+

2023-06-14 13:57 UTC, closed without merging