[FIX] web: improve calendar view
odoo/odoo pull request #121359
Opened 2023-05-15 07:52 UTC by edi-odoo

This PR fixes the Calendar's font-size, reported in the milk-testing pad:

- [BRD] Calendar : numbers too big ? https://www.awesomescreenshot.com/image/39615825?key=a8393b618be6cdd6ae8db55644930ab0

Tthe font-size of the days and weeks in the "month" view of the Calendar view were very large.
Also, the circle highlighting "today" was not circular when "today" is a single digit.
This PR reduces the font-size of the days and weeks and fixes the 
roundness of the circle.

task-3326564
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-15 07:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121359).

2023-05-15 10:11 UTC, stefanorigano requested changes
Seems to don't solve the issue (unless I'm misinterpreting the feedback?)
![image](https://github.com/odoo/odoo/assets/8558351/25564cda-2c4d-48cc-99d0-f08f7417c336)
hint: looks like the `min-width` value is not applied because of a wrong display property ;)

note: same remarks as the other PRs about draft status and commit messages. I'll let you check the remaining PRs ;)

2023-05-15 10:45 UTC, edi-odoo commented
@stefanorigano
Nope, that wasn't the fix (that issue was already in master and this was a master-milk branch)
The only fix is the font-size being reduced. Should I fix this other issue too? I had done so but reverted because of "already on master"

2023-05-15 12:34 UTC, stefanorigano commented
I'm not sure that the font-size should be reduced...

the problem I see (current master) is that one-digit numbers are squashed 
![image](https://github.com/odoo/odoo/assets/8558351/0652428e-03af-4e78-a003-d31a5c5abbe8)
Either we fix it here or we hopen another PR, up to you ;)

2023-05-15 14:48 UTC, edi-odoo commented
> I'm not sure that the font-size should be reduced...

It's very big compared to everything else in the page. Looks a bit crowded
![image](https://github.com/odoo/odoo/assets/19491443/fdc00221-cc7a-449f-861f-ea416da87295)


> the problem I see (current master) is that one-digit numbers are squashed ![image](https://user-images.githubusercontent.com/8558351/238350364-0652428e-03af-4e78-a003-d31a5c5abbe8.png) Either we fix it here or we hopen another PR, up to you ;)

I'll do the fix in this PR :)

2023-05-30 11:36 UTC, stefanorigano requested changes
Hello @edi-odoo , thanks.
I do agree on reducing the font-size, but the "today" badge design doesn't look better.. could you iterate more?
<img width="998" alt="image" src="https://github.com/odoo/odoo/assets/8558351/b9360917-8935-4c24-be26-fa9541809b06">

2023-06-30 11:23 UTC, Brieuc-brd commented
@edi-odoo 
The result looks good to me, I'm just puzzled about adding all this custom css.
If there's not other way to get the same result, I'm ok with that.

2023-06-30 11:54 UTC, edi-odoo commented
> @edi-odoo
The result looks good to me, I'm just puzzled about adding all this custom css.
If there's not other way to get the same result, I'm ok with that.

I'm afraid not as the calendar is rendered with a JS library :(

2023-07-13 15:18 UTC, edi-odoo commented
@pparidans Could you do a tech review on this please ? Thx!

2023-07-25 09:15 UTC, pparidans approved these changes
I have to admit, I'm not really trill about adding that custom CSS rules... but I see the point (and the limitation).

@robodoo r+

2023-07-25 11:21 UTC, closed without merging