[IMP] web: fix some `.btn-secondary` border
odoo/odoo pull request #121489
Opened 2023-05-16 07:35 UTC by chgo-odoo

== ISSUE ==

With the new design introduced within Milk, most of the buttons received a visual upgrade (eg. removing borders) 

This change applied on most of the buttons since the same code, but some buttons were using a `.border` class on top of that and so they did not loose this border.

== After this commit ==

We clean up these buttons that were keeping a border, in order to make our secondary buttons more consistent.

Please note that this change does not apply on all secondary buttons since some of them are customized for a specific module and so remain unmodified.

task-3326313
part of task-3326263

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-16 07:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121489).

2023-05-16 07:38 UTC, chgo-odoo commented
Hi @stefanorigano 👋

Here is a PR related to some secondary buttons border issue, could you check please?

Thanks 👍

2023-05-16 12:30 UTC, stefanorigano approved these changes
Thanks, LGTM, you can remove the draft state, enterprise branch too 👍 
https://github.com/odoo/enterprise/pull/41112

@pparidans , could you have a look? Thanks

2023-05-22 13:33 UTC, pparidans requested changes
Your commit message should mention the affected modules in the title (instead of `web`).
Same for enterprise.

For the rest, it's :+1:

2023-05-22 13:39 UTC, chgo-odoo commented
> Your commit message should mention the affected modules in the title (instead of `web`). Same for enterprise.
> 
> For the rest, it's 👍

@pparidans changes done, does that look ok to you? I'm trying to make the title not too long

2023-05-22 13:57 UTC, pparidans approved these changes
@robodoo r+

2023-05-22 17:08 UTC, closed without merging