[FIX] website: fix hide on mobile vs section height
odoo/odoo pull request #121434
Opened 2023-05-15 13:49 UTC by bvr-odoo

Previously, when a snippet section was hidden on mobile devices and its height was set to 50% or 100%, the visibility classes remained as "d-lg-block" instead of "d-lg-flex". This inconsistency resulted in the content not being vertically centered until the "hidden on mobile" toggle was turned off and then back on.

Steps to reproduce the bug:
- Open the home page in Website edit mode.
- Drag and drop a "Text" snippet onto the page.
- Click on the "Mobile visibility" option button to hide the snippet on mobile devices.
- Click on the "50%" button in the "Height" option of the snippet.
- Bug: The content within the "Text" snippet is not vertically centered.

task-3224575

2023-05-15 13:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121434).

2023-05-26 07:56 UTC, qsm-odoo commented
@robodoo delegate=sobo-odoo

2023-05-30 13:40 UTC, sobo-odoo requested changes
Here is my review :wink: It seems to work well :+1:

2023-05-31 09:04 UTC, sobo-odoo approved these changes
@robodoo r+

2023-05-31 10:27 UTC, closed without merging