[FIX] base, web: error handling of invalid leaf
odoo/odoo pull request #121545
Opened 2023-05-16 13:39 UTC by sauc-odoo

Currently, when an invalid domain causes an error it raises an Exception which will be caught by the sentry and generates unnecessary traffic.

So, we stop catching exceptions from invalid domains that are supposed to be generated by User's Mistakes.

Steps to reproduce:
    1. Turn on developer mode.
    2. Install mass_mailing module and open it.
    3. Click on the new button.
    4. Enter subject and set recipients as contact or mailing contact.
    5. In code editor pass the domain as [('', '=', 0)]
    6. error will occur - ValueError: Invalid leaf ('', '=', 0)

Applying this commit will fix this issue.

sentry-3945982195

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-16 13:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121545).

2023-06-08 11:31 UTC, yelizariev approved these changes

2023-06-08 11:31 UTC, yelizariev commented on odoo/models.py
> +            raise
It's interesting idea. 
I'd use another either use another name (`search_count_silent` ?) or keep the name, but return dictionary instead (e.g. `{recordCount: 0, isValid: true/false }`).

2023-06-12 09:18 UTC, Julien00859 requested changes
The only correct way to solve this problem is to *some-how* reraise the ValueError as a UserError as this domains comes from the UI. Adding a new method (in stable!!!) on models.py for the sole purpose of hiding exceptions (!!!) is a bad way to do it. Don't change the ValueError to a UserError in `expression.py`, most of the time it is a programming error thus ValueError is the right way to raise the exception.

In the current (master) information, the user receives an error message when the domain is invalid. The only bad thing is that that error is reported as a "server error" although it is the user who screwed up.

The implementation in your branch entirely hide the problem to the client, he doesn't receive any message whatsoever explaining that his domain is bad and that he should correct it. User don't have access to logs.

2023-06-12 10:05 UTC, rco-odoo requested changes
I totally second @Julien00859 's remark.
One has to distinguish between _user errors_ and _programming errors_.
User errors are not server errors, they are the expected way for the server to handle the request.  Programming errors are the ones you should see on sentry.

2023-06-12 10:10 UTC, Julien00859 commented
The domain should be validated upon saving the form

2023-06-12 11:48 UTC, Julien00859 requested changes
You didn't understand my point. Here you always reraise ValueError as UserError no matter if it is a programming or a user error. Meaning that if I'm a developer and I code a search with a bad domain, I receive a UserError instead of a ValueError.

Can you please stop changing the framework? The framework is not to blame here. The problem is not in the traceback either, it is a symptom of a bad domain saved on a record. Your commit message says that the problem is related to saving a bad domain in mass mailing, why am I still reading changes to `models.py` and not to mass mailing??

2023-06-13 05:17 UTC, sauc-odoo commented
Hello @Julien00859 
The traceback will be generated from each and every place where `widget="domain"` is used (check here - 
 (odoo)https://github.com/search?q=repo%3Aodoo%2Fodoo%20widget%3D%22domain%22&type=code (enterprise)https://github.com/search?q=repo%3Aodoo%2Fenterprise%20widget%3D%22domain%22&type=code) and we will enter the invalid domain(for example: `[('', '=', 0)]`).

2023-06-13 08:04 UTC, Julien00859 commented
Then we must fix each and every field for which that widget is used or find a generic solution for them all. You shouldn't be allowed to save a bad domain.

2023-06-15 06:47 UTC, sauc-odoo commented
I have created a draft PR- https://github.com/odoo/odoo/pull/125139 in master as POC to solve this issue.
I have implied two approaches:
1. I have reduced an RPC call to get recordCount.
2. If the user gives a bad domain a ValidationError will be raised.

I have achieved these results by creating a compute field `record_search_count` to get record count and that compute method will raise a ValidationError if a bad domain is added.

Kindly give your feedback on this approach.

2023-08-01 09:15 UTC, sauc-odoo commented
The issue has been fixed in following PR:
https://github.com/odoo/odoo/pull/112326
https://github.com/odoo/odoo/pull/127699

2023-08-01 09:15 UTC, closed without merging