[FIX] payment: translate post-processing messages
odoo/odoo pull request #121690
Opened 2023-05-17 16:00 UTC by chevalierv

Before this commit, the messages displayed on the payment processing page were not translated.

Now the messages about the transaction will be translated on the payment processing page.

task-3055122

2023-05-17 16:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121690).

2023-05-22 09:26 UTC, Demesmaeker approved these changes

2023-05-22 15:47 UTC, AntoineVDV requested changes

2023-05-22 15:47 UTC, AntoineVDV commented on addons/payment/controllers/post_processing.py
> +                display_message = _(tx.provider_id.pending_msg)
You cannot translate a term stored in a variable; you can only translate string primitives. The message should already be translated at this point.

2023-05-23 14:08 UTC, closed without merging