[FIX] auth_signup: prevent traceback when mail template is not found
odoo/odoo pull request #121632
Opened 2023-05-17 13:31 UTC by sauc-odoo

When user deletes 'Settings: Unregistered User Reminder' record from 'mail.template' model and when 'Users: Notify About Unregistered Users' scheduled action is executed at that time traceback is generated on the user side as well as in the log.

See this Traceback: 
```
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f72969445e0>, 'auth_signup.mail_template_data_unregistered_users')
  File "odoo/tools/cache.py", line 91, in lookup
    r = d[key]
  File "<decorator-gen-3>", line 2, in __getitem__
  File "odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
ValueError: External ID not found in the system: auth_signup.mail_template_data_unregistered_users
  File "odoo/tools/safe_eval.py", line 362, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(139,)", line 1, in <module>
  File "addons/auth_signup/models/res_users.py", line 224, in send_unregistered_user_reminder
    template = self.env.ref('auth_signup.mail_template_data_unregistered_users').with_context(dbname=self._cr.dbname, invited_users=invited_users[user])
  File "odoo/api.py", line 566, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "odoo/addons/base/models/ir_model.py", line 1984, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-40>", line 2, in _xmlid_lookup
  File "odoo/tools/cache.py", line 96, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "odoo/addons/base/models/ir_model.py", line 1977, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: auth_signup.mail_template_data_unregistered_users" while evaluating
'model.send_unregistered_user_reminder()'
  File "odoo/addons/base/models/ir_cron.py", line 373, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "odoo/addons/base/models/ir_actions.py", line 688, in run
    res = runner(run_self, eval_context=eval_context)
  File "addons/website/models/ir_actions_server.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "odoo/addons/base/models/ir_actions.py", line 558, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "odoo/tools/safe_eval.py", line 376, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
```

Applying this commit will fix this issue.

sentry-4174950325

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-17 13:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121632).

2023-05-18 04:49 UTC, sauc-odoo commented
Hello @odoo/sentry_reviewers 
Kindly check this PR.
Thanks.

2023-05-23 12:15 UTC, yelizariev requested changes
You should add some warning at least. We can't just ignore it

2023-05-23 12:15 UTC, yelizariev commented on addons/auth_signup/models/res_users.py
> +            if unregistered_user:
Variable name is quite confusing

2023-05-24 04:58 UTC, sauc-odoo commented
Hello @yelizariev 
Changes have been done, Kindly review them.
Thanks.

2023-05-25 06:24 UTC, abz-odoo requested changes

2023-05-25 06:24 UTC, abz-odoo commented on addons/auth_signup/models/res_users.py
> +                _logger.warning("Invalid template. It seems it has been deleted.")
Maybe add more informations to the warning ?

For example
```suggestion
                _logger.warning('Template "auth_signup.mail_template_data_unregistered_users" was not found. Cannot send reminder notifications.')
```

2023-06-09 06:12 UTC, uso-odoo commented
Hello @xmo-odoo 

Can you please look into this PR?

Thanks!

2023-06-22 08:46 UTC, abz-odoo commented
So @sauc-odoo I think you should remove the else with the logger.warning

2023-06-23 04:51 UTC, sauc-odoo commented
Hello @xmo-odoo 
Changes have been done, kindly review them.
Thanks.

2023-06-28 09:41 UTC, VincentSchippefilt commented on addons/auth_signup/models/res_users.py
> +            if email_template:
I would move getting the `email_template` and the `if` in the beginning of the function before any work is done. Sending emails is the whole point of this cron, shouldn't we log something if the cron can't do its work ?

2023-07-03 11:56 UTC, abz-odoo requested changes

2023-07-03 11:56 UTC, abz-odoo commented on addons/auth_signup/models/res_users.py
> +                template.send_mail(user, email_layout_xmlid='mail.mail_notification_light', force_send=False)
```suggestion
        datetime_min = fields.Datetime.today() - relativedelta(days=after_days)
        datetime_max = datetime_min + relativedelta(hours=23, minutes=59, seconds=59)

        res_users_with_details = self.env['res.users'].search_read([
            ('share', '=', False),
            ('create_uid.email', '!=', False),
            ('create_date', '>=', datetime_min),
            ('create_date', '<=', datetime_max),
            ('log_ids', '=', False)], ['create_uid', 'name', 'login'])

        # group by invited by
        invited_users = defaultdict(list)
        for user in res_users_with_details:
            invited_users[user.get('create_uid')[0]].append("%s (%s)" % (user.get('name'), user.get('login')))

        # For sending mail to all the invitors about their invited users
        for user in invited_users:
            template = email_template.with_context(dbname=self._cr.dbname, invited_users=invited_users[user])
            template.send_mail(user, email_layout_xmlid='mail.mail_notification_light', force_send=False)
```

2023-07-03 11:56 UTC, abz-odoo commented on addons/auth_signup/models/res_users.py
> +        if email_template:
```suggestion
        if not email_template:
            _logger.warning("Template 'auth_signup.mail_template_data_unregistered_users' was not found. Cannot send reminder notifications.")
            return
```

2023-07-04 04:54 UTC, sauc-odoo commented on addons/auth_signup/models/res_users.py
> +        if email_template:
Hello @abz-odoo 
Changes are done, kindly review them.
Thanks.

2023-07-12 13:03 UTC, abz-odoo requested changes
Please avoid useless diff
Thank you

2023-07-18 10:22 UTC, sauc-odoo commented
Hello @VincentSchippefilt 
Changes have been made, Kindly review them.
Thanks.

2023-07-24 11:32 UTC, Xavier-Do approved these changes

2023-07-24 11:39 UTC, kitan191 commented
@robodoo delegate=abz-odoo

2023-07-24 11:46 UTC, abz-odoo commented
finally, let's stop this
@robodoo r+

2023-07-24 13:54 UTC, closed without merging