[IMP] website_blog: show latest post on blog cover
odoo/odoo pull request #121742
Opened 2023-05-18 10:28 UTC by divy-odoo

Before this commit, for only one active blog, visitors see the blog_name inside the cover on the youwebsite.odoo.com/blog/blog_name-X page.

After this commit, for only one active blog, visitors see the latest post as a cover on the .../blog/blog_name-X page. 

task-3278892

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-18 10:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121742).

2023-06-19 14:48 UTC, rdeodoo requested changes
14.0 for an IMP about changing single blog behavior ?
Surely this is meant to land in master.

2023-06-21 11:08 UTC, divy-odoo commented
Hello @rdeodoo, Requested changes have been made.
PR is updated now.

2023-07-17 16:18 UTC, rdeodoo requested changes
I don't like this business logic change (adding conditions or changing logic) in templates.

I feel like the template is:
1. Replicating how it can the business logic in python, trying to have things syncronized
2. Trying to juggle with all those `blog`, `blogs`, `first_post` `blog_post` variable to have something that works as expected, but mainly by chance (to not break something else).

I think I would consider rewriting a bit this part and now that we have another use case where we want a `first_post` in a specific condition.
We should imo make the controller (prepare_values) set a new record `cover_record` that the controller would set to either a blog or a post depending of the business logic.
Then the template(s) would not have to worry about anything (or at least a lot less, as we will still need some checks): it receives a cover_record -> It shows that cover_record.
The template should not be doing magic like "I have x and Y and len(something) < 1 so in this case maybe we don't want this but this".

If you could give it a shot and see what you can do. I'd suggest keeping your actual diff so you can simply do `git revert HEAD` which will nullify this commit change and you add a third commit on your branch starting from scratch.

2024-02-07 10:40 UTC, visp-odoo commented
@rdeodoo Can you please review this PR.

2024-03-19 09:21 UTC, rdeodoo requested changes
@divy-odoo We have updated the spec. Sorry for the late change, but the spec was not convincing anymore

2026-03-04 04:33 UTC, closed without merging