[FIX] website_sale: check terms and conditions
odoo/odoo pull request #121798
Opened 2023-05-19 11:53 UTC by thle-odoo

Issue:
When we activate the terms and conditions,
the button "Pay Now" is not "disabled"
at the first loading of the page.

Cause:
When we update the carriers,
if all conditions are good,
we activate the "Pay Now" button.
We do not take into account
the checkbox terms and conditions.

Solution:
Check the the value of checkbox for terms
and conditions when checking carriers.

2023-05-19 11:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121798).

2023-05-31 08:51 UTC, AntoineVDV reviewed
Hello, is this issue occurring only in >=saas-16.2? If not, the PR should target the lowest branch where the issue occurs.

I checked in 15.0, and the T&C checkbox was correctly handled. Could you please investigate why the behavior broke in between and mention the responsible commit hash, if any, in your commit? That'd help make sure we are not leaving dangling pieces of dead code elsewhere by fixing the issue a second time. :)

2023-06-01 07:53 UTC, thle-odoo commented
Hello @AntoineVDV
According to my tests, yes, the problem only occurs in saas-16.2+.
I updated the commit :)

2023-06-01 14:09 UTC, AntoineVDV requested changes

2023-06-06 16:39 UTC, AntoineVDV approved these changes
@robodoo r+

2023-06-06 18:24 UTC, closed without merging