[FIX] snailmail_account: prevent error on computing warning message
odoo/odoo pull request #121830
Opened 2023-05-19 13:59 UTC by yelizariev

Record `res.partner` may have empty name if it's an address record for a regular partner [1]. This may lead to error `sequence item 0: expected str instance, bool found` on computing `display_messages`.

Fix it by using `res.partner(666),` if the record doesn't have a name

[1]: https://github.com/odoo/odoo/blob/c3209aec9741cda8597525add88b0a932fb7532a/odoo/addons/base/models/res_partner.py#L295

https://online.sentry.io/issues/4183834755

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-23 08:08 UTC, aliyatastemirova requested changes
Hi, `name` might not be there in this case but I think the `display_name` should be available. So I think we should rather replace `name` with `display_name`. As this is a warning message for the user, I don't think `res.partner(123)` would be user-friendly.

2023-05-23 14:22 UTC, yelizariev commented
Good point! Indeed, `res.partner` has `name_get` method that can handle it

https://github.com/odoo/odoo/blob/b2f648fb3e3632e51123336850fd6ea1280925fe/odoo/addons/base/models/res_partner.py#L804-L833

2023-05-25 08:05 UTC, yelizariev commented on addons/snailmail_account/wizard/account_move_send.py
> +                    display_messages.append(", ".join(p.display_name for p in wrong_address_partners))
:grimacing:

2023-05-25 08:43 UTC, aliyatastemirova approved these changes

2023-05-25 11:06 UTC, qdp-odoo commented
@robodoo r+

good suggestion @aliyatastemirova :+1:

2023-05-25 16:20 UTC, closed without merging