[FIX] web: binary_field: space between buttons
odoo/odoo pull request #121931
Opened 2023-05-22 12:24 UTC by Brieuc-brd

Prior to this commit, the buttons in `binary_field` didn't have space between them.

This commit fixes this issue.

👉 https://www.awesomescreenshot.com/image/40055599?key=e9026aa3239b1b576dc92b0e03bff83f
task-3334887
Part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-22 12:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/121931).

2023-05-22 13:18 UTC, Brieuc-brd commented
@stefanorigano 👋 This PR is ready for review.

2023-05-22 13:36 UTC, stefanorigano commented
I think that the container should be a btn-group, it would keep the structure more compact in case the field is inside a column. Could you test?

2023-05-31 08:56 UTC, Brieuc-brd commented
@stefanorigano 
Ok 👍  I used `btn-group` but since there are an intermediate wrapper and a hidden input:

```xml
<div class="btn-group">
	<span style="display: contents">
		<input/>
		<button class="fa fa-pencil"/>
	</span>
	<button class="fa fa-download"/>
	<button class="fa trash"/>
	<input class="o_hidden"/> <!-- hidden input -->
</div>
```

 the rounded corners are a bit broken, so I had to force them using `rounded-*` classes.

2023-05-31 09:47 UTC, stefanorigano commented
> the rounded corners are a bit broken, so I had to force them using rounded-* classes.

mmm... too complicated I'm afraid. Thanks for having tried @Brieuc-brd 👍 
Could you test if `gap-1` is works fine? Otherwise let's go back to the  "margins method"... Thanks agin

2023-05-31 12:40 UTC, Brieuc-brd commented
@stefanorigano To me `gap-1` works well 
![Capture d’écran 2023-05-31 à 14 39 21](https://github.com/odoo/odoo/assets/80679690/3806b73b-6501-4f71-8eb7-4c4d0641d8a0)

2023-06-01 14:54 UTC, Brieuc-brd commented
@stefanorigano Is this change ok for you ?

2023-06-02 07:11 UTC, stefanorigano requested changes
Hello @Brieuc-brd  thanks. 
I just noticed how much this field is misaligned... I tested briefly `btn-sm` classes seems to solve the issue, at least partially. 

<img width="949" alt="image" src="https://github.com/odoo/odoo/assets/8558351/754eb415-4e72-4b4e-a59d-aafa964e13a3">

I suspects that move the icons into inner `<i>` tags with `fa-fw lh-1` classes should improve it even more. Could you test? 

ps: Better to avoid using `py-0`... it would make buttons fit,  but overriding buttons padding it's something we shouldn't do...

2023-06-02 13:00 UTC, Brieuc-brd commented
@stefanorigano LGTM, what do you think ?
![Capture d’écran 2023-06-02 à 14 58 44](https://github.com/odoo/odoo/assets/80679690/aa96163d-9f4b-4170-af78-541cb75e3a6b)

2023-06-15 09:30 UTC, Brieuc-brd commented
> @stefanorigano LGTM, what do you think ? ![Capture d’écran 2023-06-02 à 14 58 44](https://user-images.githubusercontent.com/80679690/242890488-aa96163d-9f4b-4170-af78-541cb75e3a6b.png)

@stefanorigano 👋  little reminder :)

2023-06-15 12:33 UTC, stefanorigano approved these changes
LGTM, thanks @Brieuc-brd 👍 

@pparidans , all yours :)

2023-06-15 12:45 UTC, pparidans approved these changes
:sunglasses: 

@robodoo r+

2023-06-15 15:51 UTC, closed without merging