[FIX] documents: `inspector` layout issue, adapt milk
odoo/odoo pull request #122126
Opened 2023-05-23 13:57 UTC by xlu-odoo

This commit addresses an issue where the close button in the chatter section of the `inspector` component in Documents was positioned too closely to the follow button.

With recent changes in this component, additional spacing was required to ensure proper visual separation between the two buttons.

Furthermore, another problem with the icon buttons in the inspector  related to btn-group was identified, where it had a default margin-left  of 1px. To provide flexibility for adjusting the gap size in specific  modules, a variable has been introduced.

task-3336458
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-23 13:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122126).

2023-05-30 09:52 UTC, stefanorigano requested changes
Hello @xlu-odoo , one remark, thanks.
Could you update your commit/pr description? You're not applying changes to the `documents` module here ;)

2023-05-30 09:52 UTC, stefanorigano commented on addons/web/static/src/scss/bootstrap_review_backend.scss
> +            margin-left: var(--btn-group-gap, 1px);
I prefer if we still refer to `$btn-border-width` rather then using the `1px`arbitrary value

2023-05-31 12:07 UTC, stefanorigano requested changes
> Also, this commit adds a bit of spacing next to the close button when 
the chatter is opened in Documents.

This should be done in a separate commit and, since `documents` is not in community, this change needs a bit more explanations.

Could you reword these PR/commit? Again, `documents` is not in community.

2023-06-08 11:03 UTC, stefanorigano approved these changes
LGTM, thanks @xlu-odoo 👍 

@pparidans , could you have. a look? Thanks!

2023-06-15 11:48 UTC, pparidans approved these changes
LGTM

2023-06-21 14:40 UTC, pparidans approved these changes
LGTM
@robodoo r+

2023-06-22 14:06 UTC, closed without merging