[FIX] project,hr_timesheet: fix groupby and shortby issue in portal view and remove 'No Record' from task_id
odoo/odoo pull request #122485
Opened 2023-05-25 13:04 UTC by yava-odoo

This PR address the following issues:

1. Choose 'sort by' any option other than 'Title' or 'Newest', and then navigate back to the project table using the breadcrumb, it may result in a traceback.
2. Search for a task that does not exist, for example, 'xyz' notice that both 'Create xyz' and 'No records' are displayed

Fix:

- In this PR, keep_query is keeping query in URL so removing it solve the issue. By default, the 'Stage' is used as the groupby for each project.
- This PR, will allow canCreate value to be set as true when the project is selected.

Task-3318851

2023-05-25 13:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122485).

2023-06-21 14:18 UTC, auon-odoo requested changes
Thanks for your work!

2023-06-22 05:10 UTC, yava-odoo commented on addons/hr_timesheet/static/src/components/task_with_hours/task_with_hours.js
> +        return Boolean(this.context.default_project_id || this.props.record.data.project_id);
The 'default_project_id' key is assigned a value once a task is selected. However, if we are in the process of selecting a project without choosing a task, the key will remain undefined during that time.

2023-06-22 05:11 UTC, yava-odoo commented on addons/hr_timesheet/static/tests/task_with_hours_tests.js
> +        testFunction(target, '.o_list_many2one[name=task_id] .dropdown ul li:contains(Create "NonExistingTask")');
Hello @auon-odoo 
Thank you for looking into it. :slightly_smiling_face: 

We need to verify that the "Create 'New Task'" option is not visible when no project is selected. The 'create' option link: [https://i.imgur.com/teaGtVZ.png]. In order to ensure an exact match, the word 'create' should be positioned outside of the quotation marks.

2023-06-22 05:23 UTC, yava-odoo commented on addons/project/controllers/portal.py
> +            groupby = 'stage'
This route is intended for projects and their respective pages. 

Projects will always be present, but it is possible that a project may not have any tasks associated with it.

2023-06-22 11:00 UTC, auon-odoo commented on addons/hr_timesheet/static/tests/task_with_hours_tests.js
> +        testFunction(target, '.o_list_many2one[name=task_id] .dropdown ul li:contains(Create "NonExistingTask")');
Oh ok, my bad!

2023-06-22 11:14 UTC, yava-odoo commented on addons/hr_timesheet/static/src/components/task_with_hours/task_with_hours.js
> +        return Boolean(this.context.default_project_id || this.props.record.data.project_id);
Hello @auon-odoo 
Thank you for looking into it. :slightly_smiling_face:
I have implemented the changes

2023-06-22 11:16 UTC, auon-odoo approved these changes
Lgtm! Thank you for your work :pray:

2023-06-23 08:38 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂 

robodoo rebase-ff r+

2023-06-23 08:39 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-06-23 12:44 UTC, closed without merging