[FIX] payment_paypal: ignore exception in sentry for missing notification data.
odoo/odoo pull request #122481
Opened 2023-05-25 12:45 UTC by omra-odoo

ValidationError: PayPal: Missing value for txn_id (78X739757D473425R) or txn_type (None).

This issue occurs when there is some missing value in the received notification_data while evaluating the '_process_notification_data' function. It raises an Exception which will be caught by the sentry.

see stack trace: 
```
ValidationError: PayPal: Missing value for txn_id (78X739757D473425R) or txn_type (None).
  File "addons/payment_paypal/controllers/main.py", line 174, in paypal_webhook
    tx_sudo._handle_notification_data('paypal', data)
  File "addons/payment/models/payment_transaction.py", line 653, in _handle_notification_data
    tx._process_notification_data(notification_data)
  File "home/odoo/src/enterprise/saas-16.2/payment_sepa_direct_debit/models/payment_transaction.py", line 76, in _process_notification_data
    super()._process_notification_data(notification_data)
  File "addons/payment_paypal/models/payment_transaction.py", line 107, in _process_notification_data
    raise ValidationError(
```
sentry- 3954375754

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-26 09:57 UTC, omra-odoo commented
This type of data we get in the sentry.
![image](https://github.com/odoo/odoo/assets/120459808/4981485e-78be-4d4c-8dd9-eb731a165c1c)

2023-05-26 09:58 UTC, omra-odoo commented
Hello @odoo/sentry_reviewers 

Can you please check this PR.

Thanks!

2023-05-26 10:16 UTC, yelizariev requested changes
I think you should replace `_logger.exception` to `_logger.warning("...", exc_info=True)`.
If I recall correctly, ValidationError is already ignored. The sentry issue is created because of the `_logger

cc @abz-odoo

2023-05-29 06:28 UTC, omra-odoo commented
@yelizariev  Changes have been done.

Thanks!

2023-05-31 15:10 UTC, AntoineVDV approved these changes
@robodoo r+

2023-05-31 17:31 UTC, closed without merging