[FIX] hr_timesheet: fix task_id field records when creating a timesheet
odoo/odoo pull request #122631
Opened 2023-05-26 10:54 UTC by yava-odoo

To reproduce the issue, follow these steps:

1. Install the Timesheet and Project.
2. From the settings menu, create a new company.
3. Create a project using the newly created company(e.g. New Company) and add a task to it.
4. Open the Timesheet application and create a new timesheet.
5. In the timesheet, select the project created in step 3, and observe that the dropdown for tasks does not display any task.

Cause for this issue:

- The timesheet application has a domain set for the task field where the company associated with the task_id should be the same as the company selected in the current environment.
- However, when a new project is created with a 'New Company', the tasks associated with it also have the  'New Company' assigned to them. On the other hand, the current environment has a default company called 'Your Company' associated with it.
- Therefore, due to this domain setting, the task field does not display any tasks since there are no tasks associated with the 'Your Company' in the current environment.

Fix:

- Since the cause of the issue is related to the company domain set in the task field, we can solve it by removing it from the domain.

task-3323027

2023-05-26 10:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122631).

2023-06-13 09:29 UTC, MissingNoShiny reviewed
LGTM, thanks for your work :slightly_smiling_face:

2023-06-30 13:41 UTC, auon-odoo requested changes
But so, is it possible that we end up with the timesheet being in one company and its task in another one?
I would make sure to have consistent vals in `timesheet_preprocess` :slightly_smiling_face:

2023-07-03 09:38 UTC, yava-odoo commented
> But so, is it possible that we end up with the timesheet being in one company and its task in another one? I would make sure to have consistent vals in `timesheet_preprocess` 🙂

Hello @auon-odoo Thank you for looking into it. :slightly_smiling_face: 

I verify that the company of the timesheet is being calculated using the '_timesheet_preprocess' methods, 
and both the task and its timesheet have the same company _id on them and getting consistent vals 
through the _timesheet_preprocess

2023-07-04 13:17 UTC, auon-odoo approved these changes
Thanks for the fix! :fire:

2023-07-20 11:33 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂 

robodoo r+

2023-07-20 12:02 UTC, robodoo commented
@yava-odoo @xavierbol staging failed: ci/runbot on 20462237b71f399ee549f72de1a207f15a0dc054 (view more at https://runbot.odoo.com/runbot/build/48163892)

2023-08-01 13:21 UTC, xavierbol commented
robodoo retry

2023-08-01 14:18 UTC, closed without merging