[IMP] website: add test about website-specific assets
odoo/odoo pull request #122855
Opened 2023-05-30 09:27 UTC by bso-odoo

The build does not break if the `with_context(active_test=False)` is removed from `ir.asset`'s `_get_related_assets`. This access to inactive assets is actually needed to be able to disable assets on a specific website, similarly to what is done for `ir.ui.view`.

This commit adds a test to ensures that this feature is not accidentally lost.

task-3326887

2023-05-30 09:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122855).

2023-05-30 11:46 UTC, Guillaume-gdi approved these changes

2023-05-30 12:37 UTC, rdeodoo reviewed
@robodoo delegate=@Guillaume-gdi 

Just need to be sure as reviewer that the test is correctly testing something -> That if you remove the with_context from the business code (which this test is supposed to test), the test fails :+1:

2023-05-30 12:47 UTC, bso-odoo commented on addons/website/tests/test_ir_asset.py
> +        self.assertTrue('/website/test/base0.css' in files[0][0], "First asset should be the same as the base one.")
Actually they could all be `assertEqual`. Changed accordingly. :man_facepalming:

2023-06-01 12:21 UTC, Guillaume-gdi requested changes
Just a nitpick then I will merge :)

2023-06-01 12:21 UTC, Guillaume-gdi commented on addons/website/tests/test_ir_asset.py
> +        website_2 = Website.create({'name': 'Website 2'})
Test working as expected :+1: 
Juste can you put `Website 1` and `Website 2` in double quotes as they are  human readable strings. ty

2023-06-01 13:45 UTC, Guillaume-gdi approved these changes
@robodoo r+

2023-06-01 19:19 UTC, closed without merging