[FIX] point_of_sale: fix kit total cost when sold in PoS with fifo/avco
odoo/odoo pull request #122841
Opened 2023-05-30 08:33 UTC by robinengels

Current behavior:
When selling a kit in PoS, the total cost of the kit is not computed correctly if the product category was using fifo/avco.

Steps to reproduce:
- Create a product category using fifo
- Create a kit product with 2 products in it (Comp A with a cost of 5 and Comp B with a cost of 10). Total cost of product is 15.
- Create a PoS order with the kit product, and validate it
- Check the total cost of the product in the pos sale order, it is 0 but it should be 15.

opw-3189949
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-30 08:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122841).

2023-06-22 15:53 UTC, robinengels commented
@odoo/rd-runbot I added a new module here, I think I need an exception for the template test

2023-06-30 08:42 UTC, robinengels commented
@odoo/rd-runbot ping

2023-07-03 09:27 UTC, Xavier-Do commented
Upgrade exception [#225](https://runbot.odoo.com/web/#id=225&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
module:pos_mrp
```
cc @KangOl @nseinlet

2023-07-03 09:39 UTC, caburj requested changes
Can't immediately r-plus. You need to call super in the override.

2023-07-03 09:39 UTC, caburj commented on addons/pos_mrp/models/pos_order.py
> +            return stock_moves.filtered(lambda ml: ml.product_id.id == product.id)
```suggestion
            return super()._get_stock_moves_to_consider(stock_moves, product)
```

2023-07-03 09:39 UTC, caburj commented on addons/point_of_sale/models/pos_order.py
> +        return stock_moves.filtered(lambda ml: ml.product_id.id == product)
```suggestion
        return stock_moves.filtered(lambda ml: ml.product_id.id == product.id)
```
Right?

2023-07-03 09:40 UTC, rhe-odoo approved these changes

2023-07-03 11:00 UTC, caburj approved these changes
robodoo r+

2023-07-03 12:06 UTC, closed without merging