[IMP] point_of_sale: Allow products to be part of multiple pos categories
odoo/odoo pull request #122907
Opened 2023-05-30 13:50 UTC by vlst-odoo

[IMP] point_of_sale: Allow products to be part of multiple pos categories

Currently, a product can only be part of one `pos_category`. This PR changes the relationship between the `product` and the `pos_category` from a `One2many` to a `Many2many`.\

Closes: 3138825

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-30 13:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/122907).

2023-06-15 08:27 UTC, caburj requested changes
prelim comments

2023-06-15 08:27 UTC, caburj commented on addons/point_of_sale/models/report_sale_details.py
> +        unique_products = list({tuple(sorted(product.items())): product for category in categories for product in category['products']}.values())
Add a comment above this line:
```
# IMPROVEMENT: It would be better if the `products` are grouped by pos.order.line.id.
```

2023-06-16 09:55 UTC, caburj commented on addons/point_of_sale/security/ir.model.access.csv
> +access_product_category_base_user,access_product_category_base_user,model_pos_category,base.group_user,1,0,0,0
Looks like a bug in many2many_tags widget. It tries to access records where user doesn't have access to.

2023-06-19 07:07 UTC, vlst-odoo commented on addons/point_of_sale/security/ir.model.access.csv
> +access_product_category_base_user,access_product_category_base_user,model_pos_category,base.group_user,1,0,0,0
I removed this security rule and fixed the underlying issue

2023-06-19 15:45 UTC, caburj approved these changes
robodoo r+

2023-06-19 16:00 UTC, robodoo commented
@vlst-odoo @caburj linked pull request(s) odoo/upgrade#4739 not ready. Linked PRs are not staged until all of them are ready.

2023-06-21 07:05 UTC, caburj commented
robodoo r+

2023-06-21 13:03 UTC, closed without merging