[FIX] web: SuperUser background
odoo/odoo pull request #123021
Opened 2023-05-31 09:05 UTC by chgo-odoo

=== ISSUE ===

Before we introduced the Milk new design, the navbar component used to have a background-color based on the $o-brand-odoo SCSS variable. This variable would use the primary color on both Community and Enterprise.

With the introduction of Milk, the UI received a fresh upgrade including (in our case) a white navbar rather than using the primary-color.

=== AFTER ===

Since we cannot rely on the $o-brand-odoo to make the component anatomy consistent across Community/Enterprise and the darkmode, we refactored the component using the `border-image` CSS property and adjust the height of the menu to fit its content.

task-3337789
part of task-332626

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-31 09:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123021).

2023-05-31 09:39 UTC, chgo-odoo commented
Hi @stefanorigano 👋

This PR is related to the SuperUser menu background. Since you suggested to tweak Community directly, I suggest to refactor the whole component, to reduce the number of lines with a similar render. Since we don't target Enterprise with this, I closed the old PR. Here is the discussion we had in case you would like to get more context:

![image](https://github.com/odoo/odoo/assets/128030743/3e750da4-da3e-46ac-afc1-51c2617d0718)


Could you check please?

Thanks 👍

2023-05-31 10:09 UTC, stefanorigano requested changes
Well done, very good @chgo-odoo 👍 

Almost perfect, there are just 2 minor glitches (see screenshoot):
- community: the bottom border is "hidden" 
- enterprise: the borders are too attached to the content

Here a proposal

```scss
/// Community
body.o_is_superuser .o_menu_systray {
    border-image: repeating-linear-gradient(135deg, #d9b904, #d9b904 10px, #373435 10px, #373435 20px) 2;
    border-image-width: map-get($border-widths, 2);
}

/// Enterprise
body.o_is_superuser .o_menu_systray {
    border-image-offset: map-get($border-widths, 5);
}
```

<img width="1549" alt="image" src="https://github.com/odoo/odoo/assets/8558351/730aded4-895f-4c87-98ff-4508914ee2d9">

Thanks 👍

2023-05-31 10:13 UTC, stefanorigano commented
note: use lowercase characters for pr/commit titles, unless it's a technical term or component name.
In the last case always wrap the word between acute accents, so: myComponent -> `myComponent`.

"SuperUser" is not a component name or tech. term ;)

2023-05-31 11:33 UTC, chgo-odoo commented
@stefanorigano That's even better and optimized, thanks 🙌

Here is the Enterprise counterpart, could you have a look at it?

- https://github.com/odoo/enterprise/pull/41707

Thanks

2023-05-31 11:56 UTC, stefanorigano reviewed
Thanks @chgo-odoo , code LGTM 👍 

Why you refer to `background-color` in PR and commit titles? Seems unrelated

2023-05-31 12:03 UTC, chgo-odoo commented
That's right, I've been too fast when pasting the description. It should be fine now @stefanorigano 👍

2023-05-31 14:39 UTC, stefanorigano approved these changes
LGTM @chgo-odoo , thanks!
You can remove the draft state,  enterprise branch as well 👍 

@pparidans , another little master-piece for you  🙂

2023-06-02 17:46 UTC, pparidans approved these changes
@robodoo r+

2023-06-02 18:57 UTC, closed without merging