[FIX] sale: prevent traceback while add new product in sale order line
odoo/odoo pull request #123085
Opened 2023-05-31 12:38 UTC by smna-odoo

An error occurs because to convert the amount in sale order line company is required.

when user remove the company and tries to add a new product in sale order line error occur.

sentry traceback:
```
AssertionError: convert amount from unknown company
  File "odoo/http.py", line 2109, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1692, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1719, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1916, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 709, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 28, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 459, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "odoo/api.py", line 439, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-748>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/base_automation/models/base_automation.py", line 390, in create
    action._process(action._filter_post(records))
  File "addons/base_automation/models/base_automation.py", line 340, in _process
    raise e
  File "addons/base_automation/models/base_automation.py", line 337, in _process
    action_server.sudo().with_context(**ctx).run()
  File "odoo/addons/base/models/ir_actions.py", line 700, in run
    res = runner(run_self, eval_context=eval_context)
  File "odoo/addons/base/models/ir_actions.py", line 587, in _run_action_object_create
    res = self.env[self.crud_model_id.model].create(res)
  File "<decorator-gen-270>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/sale_project/models/sale_order_line.py", line 61, in create
    lines = super().create(vals_list)
  File "<decorator-gen-269>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "home/odoo/src/enterprise/saas-16.2/sale_planning/models/sale_order_line.py", line 59, in create
    lines = super().create(vals_list)
  File "<decorator-gen-259>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "addons/sale/models/sale_order_line.py", line 961, in create
    lines = super().create(vals_list)
  File "<decorator-gen-171>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "addons/analytic/models/analytic_mixin.py", line 49, in create
    return super().create(vals_list)
  File "<decorator-gen-10>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "odoo/models.py", line 3949, in create
    new_vals_list = self._prepare_create_values(vals_list)
  File "odoo/models.py", line 4129, in _prepare_create_values
    self._add_precomputed_values(result_vals_list)
  File "addons/sale/models/sale_order_line.py", line 953, in _add_precomputed_values
    return super()._add_precomputed_values(vals_list)
  File "odoo/models.py", line 4166, in _add_precomputed_values
    vals[fname] = field.convert_to_write(record[fname], self)
  File "odoo/models.py", line 5920, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "odoo/fields.py", line 1368, in compute_value
    records._compute_field_value(self)
  File "odoo/models.py", line 4290, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 99, in determine
    return needle(*args)
  File "home/odoo/src/enterprise/saas-16.2/sale_subscription/models/sale_order_line.py", line 110, in _compute_price_unit
    super(SaleOrderLine, line_to_recompute)._compute_price_unit()
  File "addons/sale_management/models/sale_order_line.py", line 29, in _compute_price_unit
    super(SaleOrderLine, self - optional_product_lines)._compute_price_unit()
  File "addons/sale/models/sale_order_line.py", line 434, in _compute_price_unit
    line.price_unit = line.product_id._get_tax_included_unit_price(
  File "addons/account/models/product.py", line 195, in _get_tax_included_unit_price
    product_price_unit = product_currency._convert(product_price_unit, currency, company, document_date)
  File "odoo/addons/base/models/res_currency.py", line 267, in _convert
    assert company, "convert amount from unknown company"
```

applying these changes will resolve this issue.

sentry-4090085761

2023-05-31 12:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123085).

2023-06-01 10:31 UTC, smna-odoo commented
Hello @odoo/sentry_reviewers 

can you check this pr?

2023-06-01 11:18 UTC, Feyensv requested changes
Nope, we won't magically refill a field whenever a user empties it.

2023-06-02 12:42 UTC, smna-odoo commented
@Feyensv so can we add User error when user removes the company then we can raise the User error?

2023-06-02 14:56 UTC, Feyensv commented
First of all, the traceback provided seems to cover another case than the one you're trying to fix
The traceback provided is from a custom server action (`_run_action_object_create`), I doubt your onchange would even solve the problem.

Second, the use-case you target here is quite dumb, I really doubt we have users emptying the field on purpose (only happens in a multi-company environment, which is already an advanced setup).

Third, if we wanted to fix it, it could be as simple as a fallback on the current company in the call to `_get_tax_included_unit_price`, it would fix most of the cases, without much complexity, without another custom error, ...

2023-06-19 05:58 UTC, smna-odoo commented
Hello @Feyensv 

can you review this?

2023-06-19 08:36 UTC, Feyensv approved these changes
@robodoo r+

2023-06-19 10:16 UTC, closed without merging