[FIX] point_of_sale: apply cogs on delivery picking only
odoo/odoo pull request #123152
Opened 2023-05-31 15:49 UTC by Whenrow

Commit 1e82e2731b03e adds cogs account move lines for 'ship later' config at the picking validation. The issue appears if the delivery flow is in multiple steps. The account move lines will be created for each pickings.

This commit ensure the last one actually create the aml only opw: 3324972

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-31 15:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123152).

2023-06-02 07:08 UTC, Whenrow commented
@caburj If you have some times to check this one. Thanks

2023-06-06 13:47 UTC, caburj requested changes
Aside from comments, I think we can proceed.

2023-06-06 13:47 UTC, caburj commented on addons/point_of_sale/tests/test_anglo_saxon.py
> +        self.assertEqual(aml_output[0:1].move_id.journal_id, self.pos_config.journal_id)
```suggestion
        self.assertEqual(aml_output[0:2].move_id.journal_id, self.pos_config.journal_id)
```
Do you intend to get the first 2 move lines? Then the index should be `0:2` or `:2`.

2023-06-06 13:47 UTC, caburj commented on addons/point_of_sale/tests/test_anglo_saxon.py
> +        # self.assertEqual(aml_output[0].name
We can remove this comment.

2023-06-09 09:45 UTC, Whenrow commented
robodoo r+ rebase-ff

2023-06-09 10:24 UTC, caburj approved these changes

2023-06-09 10:48 UTC, robodoo commented
@Whenrow staging failed: ci/runbot on ecb114468eccef57ac7f47f58cac30bee8d2cd0a (view more at https://runbot.odoo.com/runbot/build/44236263)

2023-06-09 11:09 UTC, Whenrow commented
robodoo retry

2023-06-09 12:56 UTC, closed without merging