[FIX] account:  prevent account_move_line singleton error
odoo/odoo pull request #123405
Opened 2023-06-02 05:02 UTC by sami-odoo

When accunt_id and suspense_account_id is matched twice then we we will face this issue 'Expected singleton: account.move.line(516, 517)'.

```
ValueError: too many values to unpack (expected 1)
  File "odoo/models.py", line 5199, in ensure_one
    _id, = self._ids
ValueError: Expected singleton: account.move.line(516, 517)
  File "odoo/http.py", line 2116, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1923, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 28, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 923, in onchange
    return super(BankRecWidget, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "odoo/models.py", line 6529, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "odoo/models.py", line 6240, in _onchange_eval
    method_res = method(self)
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 659, in _onchange_todo_command
    self._ensure_loaded_lines()
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 1481, in _ensure_loaded_lines
    self.line_ids
  File "odoo/fields.py", line 4287, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 2793, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 1155, in __get__
    self.recompute(record)
  File "odoo/fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "odoo/fields.py", line 1338, in apply_except_missing
    func(records)
  File "odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "odoo/models.py", line 4312, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 99, in determine
    return needle(*args)
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 231, in _compute_line_ids
    wizard._lines_widget_add_auto_balance_line()
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 1021, in _lines_widget_add_auto_balance_line
    auto_balance_line_vals = self._lines_widget_prepare_auto_balance_line()
  File "home/odoo/src/enterprise/saas-16.2/account_accountant/models/bank_rec_widget.py", line 972, in _lines_widget_prepare_auto_balance_line
    = self.st_line_id._get_accounting_amounts_and_currencies()
  File "addons/account/models/account_bank_statement_line.py", line 492, in _get_accounting_amounts_and_currencies
    transaction_amount = -suspense_line.amount_currency
  File "odoo/fields.py", line 1151, in __get__
    record.ensure_one()
  File "odoo/models.py", line 5202, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
```

Applying the changes will resolve the issue.

sentry-4217912848

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-02 05:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123405).

2023-06-02 12:30 UTC, sami-odoo commented
Hello @odoo/sentry_reviewers,
Please review it.

2023-06-07 07:40 UTC, abz-odoo commented
@odoo/rd-accounting

2023-06-07 07:44 UTC, william-andre requested changes
I knew by reading the commit message that you were fixing symptoms instead of fixing bugs

2023-06-09 08:03 UTC, h4818 commented
There should never be more than 1 suspense line,
Could you please provide the steps to replicate?

2023-06-12 13:38 UTC, abz-odoo commented
> There should never be more than 1 suspense line, Could you please provide the steps to replicate?

@sami-odoo

2023-06-13 04:58 UTC, sami-odoo commented
Hello @h4818,
We encountered difficulties in finding a suitable method to reproduce the issue. However, we noticed that the problem consisted of multiple events on Sentry, originating from various databases. Therefore, we gave a solution that we believe can further improve the situation.

2023-06-13 09:22 UTC, sami-odoo commented
Hello @h4818,
I have updated the PR and commit message with steps to reproduce. Please check them.

2023-06-13 09:57 UTC, h4818 approved these changes
it's a weird use case to manually edit and add multiple suspense lines, I hope there isn't something in the code which does this without manual intervention.

Given the comment below, I will approve anyway and let @smetl decide

@smetl why do we try the suspense line first, instead of just using the transaction values directly?

2023-06-16 07:30 UTC, smetl requested changes

2023-06-16 07:30 UTC, smetl commented on addons/account/models/account_bank_statement_line.py
> +        if suspense_line and len(suspense_line) == 1 and not other_lines:
Prevent this case by adding a check on `_synchronize_from_moves` instead

2023-06-21 05:29 UTC, smetl commented on addons/account/models/account_bank_statement_line.py
> +                    ) % st_line.move_id.display_name)
```suggestion
                    ,st_line.move_id.display_name)
```

2023-06-21 05:29 UTC, smetl commented on addons/account/models/account_bank_statement_line.py
> +                        "To be consistent, the journal entry must always have exactly one suspense line."
update the `.pot` file

2023-06-21 07:17 UTC, sami-odoo commented on addons/account/models/account_bank_statement_line.py
> +                        "To be consistent, the journal entry must always have exactly one suspense line."
I have Updated th `.pot` file

2023-06-21 08:26 UTC, william-andre commented on addons/account/models/account_bank_statement_line.py
> +                        "The %s reached an invalid state regarding its related statement line.\n"
The message doesn't seem to be in correct English 
```suggestion
                        "%s reached an invalid state regarding its related statement line.\n"
```

2023-06-23 06:26 UTC, sami-odoo commented
Hello @william-andre , @smetl ,
I have updated the code with test case please review them !

2023-06-23 10:14 UTC, smetl approved these changes
@robodoo r+

2023-06-23 12:25 UTC, closed without merging