[FIX] web_editor: break-link on text-image remove text
odoo/odoo pull request #123907
Opened 2023-06-06 11:52 UTC by divy-odoo

Before this commit, break-link action on a link with text-image (e.g. <a> text <img/> </a>) removing text too.
After this commit, It is removing the link only.

task-3231606

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-06 11:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123907).

2023-08-14 06:16 UTC, divy-odoo commented
Hello @odoo/rd-framework-editor, Can you please review this PR?

2023-08-14 06:51 UTC, dmo-odoo commented
cc @odoo/rd-website

2023-08-17 07:43 UTC, qsm-odoo requested changes
Hello, thanks for the fix.

Your commit message is good, just a small detail: the title should complete the sentence "when applied, this commit will ...". So in this case, instead of "break-link on text-image remove text", I would go with something like "preserve content around unlinked images".

2023-08-17 07:43 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            while(parentEl.firstChild) {
Missing linter

2023-08-17 11:18 UTC, divy-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            }
Thanks, @qsm-odoo changes have been made accordingly and works fine. 

But it's failing the `ci/security` checks.:slightly_smiling_face:

2023-08-17 11:32 UTC, qsm-odoo commented
@odoo/rd-security Could you check for the ci/security please? It fails because of call to `replaceWith` but it is the standard javascript one, not the jQuery one, so it should always be ok, right? :)

2023-08-18 11:29 UTC, qsm-odoo approved these changes
@robodoo r+

2023-08-18 13:36 UTC, closed without merging