[FIX] point_of_sale: apply quantity bracode nomenclature
odoo/odoo pull request #123924
Opened 2023-06-06 13:17 UTC by HANNICHE-Walid

Steps to reproduce:
1) Have Barcode Installed and have Barcode Nomenclature set 2) edit 1st rule(Price Barcodes 2 Decimals) to type Quantity 3) Create a product with barcode 2380201000008
4) Open POS and scan barcode 2380201010007

Bug:
error popup product not found because the callback for this rule is not set

Fix:
apply same callback as weight (set product quantity)

opw-3213595

2023-06-06 13:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/123924).

2023-06-12 09:23 UTC, robinengels commented
LGTM

2023-06-12 09:31 UTC, HANNICHE-Walid commented
hi @caburj can you check this PR please

2023-06-12 10:26 UTC, caburj requested changes
Looking good.

2023-06-12 10:26 UTC, caburj commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            } else if (code.type === 'weight' | code.type === 'quantity') {
```suggestion
            } else if (code.type === 'weight' || code.type === 'quantity') {
```

2023-06-12 11:24 UTC, HANNICHE-Walid commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            } else if (code.type === 'weight' | code.type === 'quantity') {
done :)

2023-06-12 12:00 UTC, caburj commented
You might need to rebase to get rid of the documentation CI error.

2023-06-12 13:51 UTC, caburj approved these changes
robodoo r+

2023-06-12 14:52 UTC, closed without merging