[FIX][WIP] web: avoid reset of grouby when reloading a view
odoo/odoo pull request #124284
Opened 2023-06-08 12:49 UTC by huca-odoo

Steps
=====

- Install module project with demo data
- Go to the kanban view of a given project (e.g. Office design)
- Group by Personal Stage
- Remove a non-empty column

Issue
=====

- After the reload of the view, the groupby is reset to the default one (but the groupby filter is still the same in the control panel)

Cause
=====

The parameters of the view are not correctly passed/used to/by the method load of RelationalModel.

Fix
===

Checking that the groupby field does is not already set in load seems to solve the problem.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-08 12:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124284).

2023-06-29 14:39 UTC, auon-odoo requested changes
Thanks for you work :star2:

2023-06-29 14:39 UTC, auon-odoo commented on addons/web/static/tests/views/kanban/kanban_view_tests.js
> +            assert.ok(true, "a confirm modal should be displayed");
Isn't an assertStep more appropriate? :monocle_face:

2023-06-29 14:39 UTC, auon-odoo commented on addons/web/static/src/views/relational_model.js
>              !(params.groupBy && params.groupBy.length)
As `rootParams` combines both `this.rootParams` and `params`, do we still have to check params? :thinking:

2023-06-30 08:13 UTC, huca-odoo commented
> Thanks for you work star2

Thank you for the review! I've updated the pr :)

2023-06-30 10:37 UTC, auon-odoo approved these changes
:zap: :zap:

2023-08-04 15:16 UTC, xavierbol approved these changes
LGTM, thanks for your work, I will let @odoo/rd-framework-js doing the final review. 🙂

2023-08-10 11:44 UTC, xavierbol commented
robodoo r+

(Francois (FGE) agrees with this changes, thanks for his review 😁)

2023-08-10 13:13 UTC, closed without merging