[IMP] sales: confirm on down payment
odoo/odoo pull request #124297
Opened 2023-06-08 13:42 UTC by hote-odoo

Some businesses requires customers to pay a down payment in order to confirm the order. In the case of odoo today this implies to:
 - sending a payment link
 - waiting & Checking if the payment has been done
 - confirming the order
 - creating the down payment invoice A lot of time consuming manual operations with a high risk of errors.

This commit introduces the functionality for sales orders to be confirmed on down payments and automatizes the flow to minimize the errors due to human manipulation.

Task - 3087716

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-08 13:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124297).

2023-06-20 13:23 UTC, hote-odoo commented on addons/sale/static/src/js/sale_portal_downpayment.js
> +        );
@odoo/rd-security could you please verify these lines?

Thank you :)

2023-06-21 07:26 UTC, xmo-odoo reviewed
@robodoo override=ci/security

2023-06-22 05:21 UTC, hote-odoo commented on addons/sale/static/src/js/sale_portal_downpayment.js
> +        );
@xmo-odoo `reloadAmount` is to notify the js that we need to reopen the modal after changing the amount (which needs a full reload of the page).

2023-07-13 16:05 UTC, Feyensv reviewed
quick comments

2023-07-13 16:05 UTC, Feyensv commented on addons/sale/wizard/res_config_settings_views.xml
> +                                          class="d-inline-block text-info"> DOWN PAYMENT</span>
```suggestion
                                          class="d-inline-block text-info">Downpayment</span>
```

2023-07-13 16:05 UTC, Feyensv commented on addons/sale_management/views/sale_order_template_views.xml
> +                                    class="d-inline-block text-info"> DOWN PAYMENT</span>
```suggestion
                                    class="d-inline-block text-info">Down payment</span>
```

2023-07-13 16:05 UTC, Feyensv commented on addons/sale_management/models/sale_order_template.py
> +        for order in self:
```suggestion
        for template in self:
```

2023-07-13 16:05 UTC, Feyensv commented on addons/sale_management/models/sale_order_template.py
> +                    if template.require_payment else 0)
double indentation again

2023-07-13 16:05 UTC, Feyensv commented on addons/sale/wizard/payment_link_wizard_views.xml
> +                <br attrs="{'invisible': ['|', ('res_model', '!=', 'sale.order'), ('show_confirmation_message', '=', True)]}"/>
is this br really necessary ? :thinking:

2023-09-11 13:36 UTC, Feyensv commented on addons/sale/models/sale_order.py
> +        """ Generate invoices as down payments for sale order.
Generate down payment invoices for the given sale orders paid amounts ?

2023-09-11 13:37 UTC, Feyensv commented on addons/sale/models/sale_order.py
> +        A sale order is considered paid if the sum of all the linked transaction is equals or higher
not all the linked transactions, only the authorized/done ones

2023-09-14 15:06 UTC, vava-odoo reviewed
Thanks @Feyensv for moving on with this! :+1: 
I listed a few (:eyes:) remarks, mostly non-blocking nitpicking ones.
Good job!
Cheers

2023-09-14 16:52 UTC, Feyensv commented on addons/sale/views/sale_order_views.xml
> +                                       string="Prepayment amount"
Blame DALA :D

2023-09-15 15:52 UTC, dalaOdoo requested changes

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/models/sale_order.py
>          help="Request a online signature and/or payment to the customer in order to confirm orders automatically.")
```suggestion
        help="Request a online signature from the customer to confirm the order.")
```

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/models/sale_order.py
>          store=True, readonly=False, precompute=True)
```suggestion
        store=True, readonly=False, precompute=True)
        help="Request a online payment from the customer to confirm the order.")
```

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/views/sale_order_views.xml
> +                                       string="Prepayment amount"
the field should be invisible if require_payment is false.

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale_management/views/sale_order_template_views.xml
> +                                   string="Prepayment amount"
should be invisible if require_payment is false

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/views/sale_order_views.xml
> +                                <field name="require_payment"/>
```suggestion
                                <field name="require_payment
                                readonly="state in ['cancel', 'sale']"/>
```

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/views/sale_order_views.xml
> +                                <field name="require_signature"/>
```suggestion
                                <field name="require_signature
                                           readonly="state in ['cancel', 'sale']"/>
```

2023-09-15 15:52 UTC, dalaOdoo commented on addons/sale/views/sale_order_views.xml
> +                                       readonly="state == 'sale'"
```suggestion
                                       readonly="state in ['cancel', 'sale']"
```

2023-09-21 09:24 UTC, Feyensv commented
@robodoo r+ rebase-ff

2023-09-21 09:25 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-09-21 11:00 UTC, robodoo commented
@hote-odoo @Feyensv linked pull request(s) odoo/upgrade#5133 not ready. Linked PRs are not staged until all of them are ready.

2023-09-21 17:53 UTC, closed without merging