[FIX] website: display TourPointer on configurator screen
odoo/odoo pull request #124226
Opened 2023-06-08 09:15 UTC by robinlej

Since [3a79803][1] where the CSS / classes of the TourPointer was completely
redone, the pointer doesn't show up anymore in the default tip on the
configurator waiting screen.
This commit redisplays it as it appeared before.

task-3358028

[1]: https://github.com/odoo/odoo/commit/3a79803

2023-06-08 09:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124226).

2023-06-08 09:31 UTC, rdeodoo requested changes
You forgot the `:` after `[1]` in your markdown link, so it's actually not a markdown link.

2023-06-08 09:31 UTC, rdeodoo commented on addons/website/static/src/components/website_loader/website_loader.xml
> +                    style="--TourPointer__height: 1em; --TourPointer__width: 1em;">
Move this "weird" style inside the scss file, we already have something targetting its parent `o_website_loader_tip`.
Also, you removed the `o_tooltip` which was attached to some style, you need to remove that style :+1:

2023-06-09 15:58 UTC, Guillaume-gdi reviewed
Code looks good thanks!
I just have two questions:
1. I did a try of the configurator with your changes and during the loading the `tour_pointer` is correctly displayed good :+1: but after the loading I don't see the pointer to guide me to build the perfect page in 7 steps (I try with a new DB, I cleared cache,...) Am I missing something or the pointer do not work after the configurator ?
2. Can't you also remove the scss of `o_tooltip` in `website.theme_install.scss` ?

2023-06-12 07:40 UTC, robinlej commented
@Guillaume-gdi Point (1) is handled in task-3084175.
(2) is a nice catch I hadn't seen. It even looks like the whole file is obsolete, those classes aren't used anywhere else in the codebase.

2023-06-12 08:01 UTC, Guillaume-gdi commented
> the whole file is obsolete

Ok @robinlej if the scss class is not used since 16.3, I propose you remove it in the master forward port of this PR :+1:

2023-06-12 08:43 UTC, Guillaume-gdi approved these changes
@robodoo r+

2023-06-12 10:56 UTC, closed without merging