[FIX] website_hr_recruitment: prevent applying for unpublished job
odoo/odoo pull request #124399
Opened 2023-06-09 06:40 UTC by thle-odoo

Issue:
------
When we have the link to the form to apply for a job, even if the job is not published, we can still apply.

Solution:
---------
Check that the job is published before the creation of the record.

opw-3331717

2023-06-09 06:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124399).

2023-06-09 10:29 UTC, rdeodoo requested changes
Do you know why isn't the model converter of the /apply controller is not going into a 403? That's the purpose of using modelConverter in route and IR.rules with `domain_force` set to `website_published=True`.
I guess you are preventing the creating through another way/route/rpc?

Anyway, the @odoo/rd-vidange team might want to review this one? I am not sure who is handling the `website_hr_recruitment`.

2023-06-09 10:29 UTC, rdeodoo commented on addons/website_hr_recruitment/models/hr_recruitment.py
> +            return
at least raise an error for easier debugging and understanding of the error?

2023-06-13 07:47 UTC, thle-odoo commented
The `/jobs/apply/` controller is called to load the application job form.
The `/website_form/model_name` controller is called when the form is submitted.
This flow inserts the new record in sudo (and therefore bypasses ir.rules).

I think that using the `website_form_input_filter` method can be useful by triggering a UserError so that the message is displayed on the website.

2023-06-13 11:16 UTC, kba-odoo commented
robodoo r+

2023-06-13 11:36 UTC, rdeodoo requested changes
@robodoo r-

Just to be sure.. Are you removing the capability in a > 3 years old version to create job apply not linked to a job position but only to a department on purpose?

According to the commit title and desc, it's not what is trying to be achieved, you want to prevent unpublished job, but the code is actually not doing that, it's preventing unpublished job **and no job**.

Why not adding the raise condition inside the previous `if values.get('job_id')`?

If on purpose, you can r+ again, but doesn't seems very stable friendly, especially since you could fix only the problematic case?

Maybe in master you want to remove the jobless submission capability tho :shrug:

2023-06-13 11:36 UTC, rdeodoo commented on addons/website_hr_recruitment/models/hr_recruitment.py
> +            raise UserError(_("You cannot apply for this job."))
Seems violent for stable, what about people with form to apply for a department only, without a job?

2023-06-13 13:03 UTC, thle-odoo commented
@rdeodoo
The classic flow does not allow to apply to a department without a job.
However, it is indeed possible to realize this flow by using the "Apply for a Job" action with the editor (or some other way that we are not aware of).
Therefore, not having a job can happen.

Thanks for your remark !

2023-06-14 09:38 UTC, kba-odoo commented
Thanks for your input indeed @rdeodoo :-) We didn't think at first that a manually added form could use that flow..

robodoo r+

2023-06-14 10:34 UTC, closed without merging

2023-06-15 10:33 UTC, rdeodoo commented
> Thanks for your input indeed @rdeodoo :-) We didn't think at first that a manually added form could use that flow..

No worries, all hail to the code owner ping :D

But on top of the manual form, there is all the custos / third party apps to consider in stable, especially in 14 :p 

Thanks for the change :+1: