[FIX] google_account: accessing the url without any post data
odoo/odoo pull request #124450
Opened 2023-06-09 11:13 UTC by arva-odoo

When a user tries to access the URL directly, at that time the value of dictionary `kw` is not available. The error will be generated.

Error : KeyError: 'state'

Traceback in sentry :

```
KeyError: 'state'
  File "odoo/http.py", line 2116, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1839, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/google_account/controllers/main.py", line 15, in oauth2callback
    state = json.loads(kw['state'])
```

This commit will prevent the traceback.

sentry-3947033806

2023-06-09 11:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124450).

2023-06-09 11:19 UTC, arva-odoo commented
Hello @odoo/sentry_reviewers 
Can you please look into this PR?

Thank you!

2023-06-13 12:44 UTC, abz-odoo requested changes
I suggest this fix, looks better to me

2023-06-13 12:44 UTC, abz-odoo commented on addons/google_account/controllers/main.py
> +            raise request.not_found()
```suggestion
```

2023-06-13 12:44 UTC, abz-odoo commented on addons/google_account/controllers/main.py
>          state = json.loads(kw['state'])
```suggestion
        state = json.loads(kw.get('state', '{}'))
```

2023-06-14 14:08 UTC, tde-banana-odoo commented on addons/google_account/controllers/main.py
> +        state = json.loads(kw.get('state', '{}'))
Then maybe we should be complete when managing input, and do something like
```
if (not dbname or not service
    or (kw.get('code') and not url_return)):
    raise BadRequest()
```

2023-06-16 05:04 UTC, arva-odoo commented
@tde-banana-odoo 
Changes are done!

2023-06-16 06:41 UTC, tde-banana-odoo approved these changes

2023-06-19 06:24 UTC, bit-odoo commented
@tde-banana-odoo @abz-odoo can we merge this?

2023-06-21 09:29 UTC, nle-odoo commented on addons/google_account/controllers/main.py
> +        if (not dbname or not service or (kw.get('code') and not url_return)):
```suggestion
if not dbname or not service or not url_return:
```
this would seem enough to me, since the 3 code branches are using url_return

2023-06-21 09:31 UTC, nle-odoo approved these changes
current version or my suggestion looks good to me

robodoo delegate+ delegate=abz-odoo

2023-06-26 06:42 UTC, abz-odoo commented
robodoo r+

2023-06-26 07:31 UTC, closed without merging

2023-07-03 05:57 UTC, arva-odoo commented
@abz-odoo