[IMP] sale: sign the quotation when it is in draft stage
odoo/odoo pull request #124486
Opened 2023-06-09 13:27 UTC by gusi-odoo

We have made a commit that allows users/customers to sign a quotation even when it is in the draft stage within the sale module. Previously, there was a restriction preventing this action without a valid reason.

task-3340541

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-09 13:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124486).

2023-07-12 15:21 UTC, Demesmaeker requested changes
Hello, thanks for your work, I think there is a slight misunderstanding though:
Instead of adding everywhere that the method `_has_to_be_paid` should include draft quotation, we want this method to include draft quotation by default. Could you get rid of this parameter, change the method to:
```python
    def _has_to_be_signed(self):
        """A sale order has to be signed when:
        - its state is 'draft' or `sent`
        - it's not expired;
        - it requires a signature;
        - it's not already signed.

        Note: self.ensure_one()

        :return: Whether the sale order has to be signed.
        :rtype: bool
        """
        self.ensure_one()
        return (
            self.state in ['draft', 'sent']
            and not self.is_expired
            and self.require_signature
            and not self.signature
        )
```
and adapt every call to it?

Thanks in advance :pray:

2023-07-13 12:08 UTC, Demesmaeker requested changes
Hello @gusi-odoo 
Thanks for your work on this, small last coment and lgtm =]
Have a nice day

2023-07-13 12:08 UTC, Demesmaeker commented on addons/sale/models/sale_order.py
> +    def _has_to_be_paid(self):
Could you also take off L1528? Thanks ^^

2023-07-13 12:31 UTC, Demesmaeker approved these changes

2023-07-14 09:27 UTC, Feyensv approved these changes
@robodoo r+ squash

2023-07-14 09:27 UTC, robodoo commented
Merge method set to squash.

2023-07-14 15:02 UTC, closed without merging

2023-07-15 07:38 UTC, ploegvde commented
Question, if a customer has access to the portal, can he then sign a quotation that is in draft (not ready to sign)?

2023-07-17 08:53 UTC, Feyensv commented
> Question, if a customer has access to the portal, can he then sign a quotation that is in draft (not ready to sign)?

The customer only sees sent/cancelled quotes in his "Quotations" portal.
https://github.com/odoo/odoo/blob/1b72b93a9ae4c307e1d0aa54b4cf47034b6328bc/addons/sale/controllers/portal.py#L34-L38

Therefore, unless they receive the quote portal link through another mean (if the salesman manually sends the portal url), customers won't be able to sign or pay a draft quotation.

2023-07-17 11:31 UTC, ploegvde commented
Ahhh, thank you!