[IMP] hr_contract: make contract and work permit expiration notice periods configurable
odoo/odoo pull request #124414
Opened 2023-06-09 08:40 UTC by ravb-odoo

Currently the warning messages to warn for contracts and work permits that are about to expire are hardcoded to be triggered 7 and 60 days in advance respectively. With this commit, these notice periods are made to be configurable on a per-company basis.

task-3340931

2023-06-09 08:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124414).

2023-06-23 08:15 UTC, robcoekaerts commented on addons/hr_contract/tests/test_contract.py
> +            self.assertFalse(mail_activity2.exists(), "There should be reminder activity as employee contract going to end soon")
In this case, Shouldn't the error text read something like "There should be no reminder as the contract is not yet about to expire."?

2023-06-23 08:23 UTC, robcoekaerts commented
Alternative suggestion for the commit message:
[IMP] hr_contract: make contract and work permit expiration notices configurable

Currently the warning messages to warn for contracts and work permits that are about to expire are hardcoded to be triggered 7 and 60 days in advance respectively. With this commit, these notice periods are made to be configurable on a per-company basis.

task-3340931

2023-06-23 11:10 UTC, robcoekaerts commented on addons/hr_contract/models/res_config_settings.py
> +    work_permit_expiration_notice_period = fields.Integer(string="Work Permit", related='company_id.work_permit_expiration_notice_period', readonly=False)
Can you also change the string arguments accordingly?

2023-06-23 11:55 UTC, robcoekaerts commented
LGTM

2023-07-26 07:10 UTC, sofiagvaladze requested changes

2023-07-26 07:11 UTC, sofiagvaladze commented
@ravb-odoo thanks for your work :raised_hands: 

Some minor comments :)

2023-07-28 07:20 UTC, sofiagvaladze commented on addons/hr_contract/tests/test_contract.py
> +    def test_check_multi_company_contract_expiration(self):
Oh I think we have a a misunderstanding :sweat_smile: I didn't mean to rewrite existing tests. We can just leave them the way they are. I was talking about the test that you added. 

But seeing the changes, maybe it was more readable prior. Just only the last changes. Sorry for the confusion :innocent:

2023-07-28 13:29 UTC, sofiagvaladze commented
robodoo r+

2023-07-28 13:29 UTC, robodoo commented
I'm sorry, @sofiagvaladze: draft PRs can not be approved.

2023-07-28 13:50 UTC, sofiagvaladze commented
robodoo r+

2023-07-28 14:00 UTC, robodoo commented
@ravb-odoo @sofiagvaladze linked pull request(s) odoo/upgrade#4885 not ready. Linked PRs are not staged until all of them are ready.

2023-08-02 07:21 UTC, Bertrand2 commented on addons/hr_contract/tests/test_auto_status.py
>      def test_contract_pending_visa_expire(self):
If we're testing the work permit, the title should reflect that as well :)
```suggestion
    def test_contract_pending_work_permit_expire(self):
```

2023-09-05 13:53 UTC, closed without merging