[FIX] account: restrict user to give invalid formula in account report
odoo/odoo pull request #124582
Opened 2023-06-12 05:46 UTC by alsh-odoo

When user gives invalid formula in account report expression and tries to reporting that report this traceback raises.

Steps to produce:
- Install account_report
- Open Accounting/configuration/Accounting Reports
- Open any report and add a line and add a line for expression
- In expression select 'Computation Engine' as Odoo Domain.
- In Formula give any invalid domain and Sub-Formula as 'sum'
- Save the expression,  line and current record.
- Open Reporting
- Select the above created report.

Traceback will raise

See Traceback:- https://pastebin.com/apQc52wh

By applying these changes will resolve this issue.

sentry-4223028831,4223016757

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-12 05:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124582).

2023-06-13 05:52 UTC, alsh-odoo commented
Hello @odoo/sentry_reviewers 
Can you please check this PR
Thank You

2023-06-21 12:02 UTC, oco-odoo requested changes
What kind of nonsense is this ?

1) The use case you give to reproduce the bug is wrong. When I do that, I can't save the expression, because the domain widget on the field blocks its validation. So, it's impossible to directly create the domain formula with a wrong value from the UI.

2) To get the actual bug, you need to create an expression with a non-domain engine (let's say "tax_tags"), save it, then re-open the expression and only change its engine to "domain". The formula won't get re-validated, and the framework will allow saving (probably will be called a limitation, but that behavior is really arguable IMO). 

===> Then, if you open the report, you'll get the traceback. 

3) From your diff, I thought you were maybe trying to fix point 2), even though your commit and PR said *entirely different* things ... But it just does not work; I tested it locally. 

4) The fix seems stupid simple to me: just catch the exception on this line and raise a UserError if the domain can't be evaluated: https://github.com/odoo/enterprise/blob/16.0/account_reports/models/account_report.py#L2661 

It's what we do for other engines already, as you can see here: https://github.com/odoo/enterprise/blob/16.0/account_reports/models/account_report.py#L2763

2023-06-22 09:57 UTC, alsh-odoo commented
> What kind of nonsense is this ?
> 
> 1. The use case you give to reproduce the bug is wrong. When I do that, I can't save the expression, because the domain widget on the field blocks its validation. So, it's impossible to directly create the domain formula with a wrong value from the UI.
> 2. To get the actual bug, you need to create an expression with a non-domain engine (let's say "tax_tags"), save it, then re-open the expression and only change its engine to "domain". The formula won't get re-validated, and the framework will allow saving (probably will be called a limitation, but that behavior is really arguable IMO).
> 
> ===> Then, if you open the report, you'll get the traceback.
> 
> 3. From your diff, I thought you were maybe trying to fix point 2), even though your commit and PR said _entirely different_ things ... But it just does not work; I tested it locally.
> 4. The fix seems stupid simple to me: just catch the exception on this line and raise a UserError if the domain can't be evaluated: https://github.com/odoo/enterprise/blob/16.0/account_reports/models/account_report.py#L2661
> 
> It's what we do for other engines already, as you can see here: https://github.com/odoo/enterprise/blob/16.0/account_reports/models/account_report.py#L2763

Hello @oco-odoo 

The changes I did on this pr is for one of the use case in which when user tries to change the engine as 'tax_tags' for existing record(without changing the formula). In this case  no 'Accounting Tags' will be created. Because the formula won't get re-validated and due to that a syntax error will be raised when opening that report.
And also I solved rest of the use cases('Domain', 'Custom') in enterprise PR(https://github.com/odoo/enterprise/pull/42335).

2023-07-13 12:49 UTC, alsh-odoo commented
Hello @oco-odoo

Other usecases like(wrong sub-formula, wrong formula for custom engine ) which I solved in Enterprise PR(https://github.com/odoo/enterprise/pull/42335) are coming in sentry.

Do let me know your suggestion on this.

Thank You!!

2023-07-14 13:50 UTC, yelizariev commented
You should fix conflicts...
![image](https://github.com/odoo/odoo/assets/186131/cc2495c3-75c9-4e66-bb58-6569051b39bf)

2023-07-17 06:19 UTC, alsh-odoo commented
> You should fix conflicts... ![image](https://user-images.githubusercontent.com/186131/253588900-cc2495c3-75c9-4e66-bb58-6569051b39bf.png)


Hello @yelizariev this PR which I creaed for one of the usecase(new tag has to be created when user changes the engine to 'tax_tags' for existing record) is solved in this PR(https://github.com/odoo/odoo/pull/120934)

Do let me know what to  do ?

Thanks!!

2023-07-19 10:12 UTC, closed without merging

2023-07-19 10:13 UTC, alsh-odoo commented
I am closing this PR because the usecase which solved in this PR is already solved in another PR(https://github.com/odoo/odoo/pull/120934).