[14.0][FIX] l10n_ch: a qr report is generated although if the option is disabled
odoo/odoo pull request #124995
Opened 2023-06-14 11:04 UTC by eantones

Supersedes #85283

Description of the issue/feature this PR addresses: QR file is generated although the option is disabled

Current behavior before PR: QR file is generated with a QR option disabled

Desired behavior after PR is merged: If the QR option is disabled, the QR document is not generated

--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

2023-06-14 11:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/124995).

2023-06-14 11:49 UTC, epictete requested changes
Hello @eantones 
Thanks for taking over the fix so we can move forward :slightly_smiling_face: 
Could you please put a small description in the commit message?
You can find more information here : https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-full-description

2023-06-14 11:49 UTC, epictete commented on addons/l10n_ch/models/mail_template.py
> +                        record.display_qr_code:
```suggestion
                if include_qr_report and \
                        record.move_type == 'out_invoice' and \
                        record.partner_bank_id._eligible_for_qr_code('ch_qr', record.partner_id, record.currency_id) and \
                        record.display_qr_code:
```
Small detail, but I would put one test per line then (just to be consistent) :wink:

2023-06-14 12:06 UTC, epictete approved these changes
Thanks for the quick update @eantones 
@robodoo r+

2023-06-14 13:48 UTC, closed without merging

2023-06-16 17:17 UTC, eantones commented
Ok, thank you very much @epictete :-)