[FIX] account: payment wizard amount when payment in comp curr
odoo/odoo pull request #125049
Opened 2023-06-14 14:12 UTC by agr-odoo

Have an invoice in foreign currency
Open "Register Payment" wizard
Have wizard currency as company currency
Change wizard date

Issue: amount will not recompute

opw-3357669

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-14 14:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/125049).

2023-06-15 11:21 UTC, jbw-odoo commented
LGMT

2023-06-16 13:56 UTC, agr-odoo commented
@fw-bot up to saas-15.2

2023-06-17 09:28 UTC, Levizar requested changes
The fix seems fine, we just need to hardcode the test results to avoid code duplication between test and tested code.

2023-06-17 09:28 UTC, Levizar commented on addons/account/tests/test_account_payment_register.py
> +
I think this part with the results we are waiting for should be hard-coded in the datalist.

Currently, the testing code contains part that are the same than the tested code.
If this part fails, then we wouldn't detect it.

2023-06-28 10:00 UTC, Levizar approved these changes
@robodoo r+

2023-06-28 11:16 UTC, closed without merging