[FIX] account:  preview invoice if invoice_date not given
odoo/odoo pull request #125193
Opened 2023-06-15 11:44 UTC by sami-odoo

If user creates a payment term with early discount and use that payment term to create an invoice without invoice_date.  
After doing it, if the user tries to preview the invoice they will face error.

steps to produce:
- Create a payment term with 'early_discount' by 'Invoicing > Configuration > Payment Terms'.
- Now create an invoice with a customer, add a product and instead of due date use the payment term you created, 
  through (Invoicing > Customers > Invoices).
- Save the invoice.
- Preview the invoice.

By following above steps user will be able to produce the error.

This commit will allow to preview the invoice when the invoice date is not provided.

sentry-4250888430

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-15 11:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/125193).

2023-06-16 15:52 UTC, sami-odoo commented
Hello ,
@odoo/sentry_reviewers please review it

2023-06-26 11:16 UTC, FlorianGilbert requested changes
Hello, 
I'm not really fan of your fix. You're not solving the issue itself, you're solving the traceback only.

1. Why the preview needs this date?
2. Maybe we should return True in case of preview without setting a default date?
3. We probably need a test :)

2023-07-04 08:34 UTC, sami-odoo commented
Hello @FlorianGilbert ,
Thank you for the suggestion.
I have updated the code accordingly and i have added the test case also. Please review them.

2023-07-07 09:26 UTC, FlorianGilbert requested changes

2023-07-07 09:26 UTC, FlorianGilbert commented on addons/account/models/account_payment_term.py
> +            return True
I'm not sure, returning True here is the best solution for this function. For me, if you don't receive any date, you should return None

2023-07-07 09:26 UTC, FlorianGilbert commented on addons/account/tests/test_early_payment_discount.py
> +        #invoice with payment term of early discount
```suggestion
        # Invoice with payment term of early discount
```

2023-07-07 09:26 UTC, FlorianGilbert commented on addons/account/tests/test_early_payment_discount.py
> +        self.assertTrue(report)
Could you please add an assert to verify that invoice date is not set and explain in a comment what you're testing here? 

Thank you

2023-07-07 11:06 UTC, sami-odoo commented
Hello @FlorianGilbert ,
Requested Changes are done please review them!

2023-07-07 11:18 UTC, FlorianGilbert approved these changes
@robodoo r+

2023-07-07 11:18 UTC, FlorianGilbert commented on addons/account/tests/test_early_payment_discount.py
> +        self.assertEqual(out_invoice.invoice_date, False)
I won't ask you to change it but for your information, you can use `self.assertFalse()` :wink:

2023-07-07 14:13 UTC, closed without merging