[FIX] account, sale: fix dependency on PortalHomeCounters
odoo/odoo pull request #125798
Opened 2023-06-20 14:31 UTC by detrouxdev

Prior to this commit, the patches done by `account_portal.js` and `sale_portal.js` were done without any import.

This means that the widget it modifies (PortalHomeCounters) might not already be loaded in the registry. This could lead to some issue later.

This commit uses an "import" statement on the module that defines PortalHomeCounters to ensure that it is present in the registry.

task-3249625

2023-06-28 12:55 UTC, qsm-odoo requested changes
@detrouxdev I was very close to r+'ing this without testing it for once (to gain some time as it looks fine and I supposed you tested it)... but tested anyway and this does not seem to work? Probably because in 16.0, the "portal.portal" module is not yet converted to the new odoo module syntax... :grimacing:

2023-06-29 07:40 UTC, detrouxdev commented
@qsm-odoo Interesting that importing a module that does not exist does not trigger a traceback. I did test the branch by installing the affected modules and logging in as portal user but thought that any error it could have cause would have shown as a traceback or on the Runbot... bad assumption on my part as there is not real bug currently. :/ 
I did test with `odoo.__DEBUG__.getMissingJobs()` now that the branch is fixed, and it returns an empty array so I think it's good to go now.

Do we want to adapt the import on the saas-16.3 version?

2023-07-04 15:51 UTC, qsm-odoo approved these changes
@detrouxdev 

> Interesting that importing a module that does not exist does not trigger a traceback.

Old debate indeed, but having a traceback would not help much I think (well it would have helped you here but...): we cannot trigger a traceback instantly, indeed a module could rely on a module which is in another bundle which could not be loaded yet. So we would have a deferred traceback (just like we have a deferred log about a non loaded module now)... which the runbot/tours could simply ignore if going to the next step quick enough (race conditions?).

I don't know if there were significant arguments to not trigger a traceback but this might be one of them. It is also not crazy to think an usecase might exist where a big bundle depends on the module of a smaller bundle if present... and you would not want your big bundle to crash when that smaller bundle is not there :shrug: That's actually the case with our test bundle: it is loaded everywhere (frontend, backend, custom screens) but many tests rely on utils which are in frontend/backend bundles (and so all tests would trigger a traceback unless we create one test bundle per environment (backend/frontend/custom screens). So this is more flexible as it is I think (even if in general, I prefer strict coding structure than flexible ones... but well we work with python and javascript so... ^^").

> Do we want to adapt the import on the saas-16.3 version?

Yes :+1: 

@robodoo r+

2023-07-04 17:28 UTC, closed without merging

2023-07-05 06:59 UTC, detrouxdev commented
@qsm-odoo Thanks for the explanation!
I guess I was thrown off by this message which appears in master (I've seen it a bunch because I always forget to restart the server or to add a module file to a bundle)
![CleanShot 2023-07-05 at 08 35 54](https://github.com/odoo/odoo/assets/77747125/372ecf10-cdbc-40d7-b534-da136a988e2a)

Look like it was added by this: https://github.com/odoo/odoo/commit/c989ff339d1bb8afde3371d12dab8cc227941691
but in 16.1+ and it's ignored in certain conditions (because of what you mentioned with the test tours), which means I wouldn't have been saved in 16.1 either. :(