[FIX] website_sale:  fix product description from sales order portal view
odoo/odoo pull request #125929
Opened 2023-06-21 12:25 UTC by shag-odoo

Before this commit if we go to website and purchase the product , the product description was also getting printed in sales order.

Steps:
Go to website and inside shop option add a product to cart. after checkout showing product description in sales order

Fix:
Added the class d-none for not displaying the product description.

 task-3188336

2023-06-21 12:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/125929).

2023-06-29 09:44 UTC, Feyensv commented
Review will be handled following our project stages, no need for codeowner in this case.
For next tasks, please wait until the task reaches the 'Testing BE' green or the 'Final Review' stages before marking the PR as 'Ready for Review', thanks.

2023-09-08 15:12 UTC, vava-odoo requested changes
Hi @shag-odoo 
Thanks for the work and the retarget. Please have a look at my comments below. Don't hesitate to come back to me if it is unclear.
Cheers.

2023-09-08 15:12 UTC, vava-odoo commented on addons/website_sale/views/templates.xml
> +                <div itemprop="description" t-field="product.website_description" class="oe_structure oe_empty mt16 d-none" id="product_full_description"/>
It can be removed now, since we retarget the PR to master.
```suggestion
```

2023-09-08 15:12 UTC, vava-odoo commented on addons/website_sale/views/templates.xml
> +        <xpath expr="//div[@t-field='product_full_description']" position="after">
```suggestion
        <xpath expr="//div[@id='product_full_description']" position="after">
```

2023-09-11 08:15 UTC, vava-odoo approved these changes
Thanks, have a good one as well.

2025-05-30 09:09 UTC, closed without merging