[FIX] account: allow to change the position of report elements
odoo/odoo pull request #126002
Opened 2023-06-21 18:54 UTC by isaako34

Description of the issue/feature this PR addresses:
The sequence in account_report_line has a default value of null, and the elements are displayed in the following sequence order: negative -> positive -> null. This complicates to change the position of report elements to the bottom due to sequences with null values are set at the bottom.

Current behavior before PR:
When updating the sequence in a report element, the position does not change because the remaining elements have a null sequence.

Desired behavior after PR is merged:
When updating the sequence with a value greater than 0, the report element should appear below elements with a sequence equal to 0.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-21 18:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126002).

2023-06-22 15:56 UTC, isaako34 commented
@luisg123v could you review please.

2023-06-23 18:33 UTC, luisg123v requested changes
Code LGTM, just edit description:

- Use same PR description as commit description
- Uppercase NULL
- Model name is `account.report.line`, i.e. with dots instead of underscores
- Specify when there is no default value, it's stored in database as NULL. It's similar as what you said, but the default value is at Python level and NULL is at database level. I consider making that distinction is a relevant point.

2023-07-06 22:02 UTC, luisg123v approved these changes
LGTM :+1: 

Hi @moylop260,

Could you review, please?

Regards,

CC @randall-vx @desdelinux

2023-07-06 23:10 UTC, moylop260 commented
# Short answer:

LGTM 👍 

# Large answer:

I double confirmed the case storing Null in the database using the following mini-script:

```python
report_line = self.env['account.report.line'].create({
    'name': "test",
    'report_id': self.env['account.report'].search([], limit=1).id,
})
print(report_line.sequence)
# 0

self.env.cr.execute("SELECT sequence FROM account_report_line WHERE id=%s", (report_line.id,))
res = self.env.cr.fetchone()
print(res)
# (None,)
```

The field `sequence` is used by Odoo ORM to order and it is able to add an extra feature in the tree view to order the records

IMHO the Odoo ORM should be a `default` if it is not defined in order to avoid raising same issue for the following current cases:

https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/account/models/account_move_line.py#L73
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/account/models/account_report.py#L250
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/account/models/account_report.py#L699
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/account/models/chart_template.py#L1580
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/account/models/partner.py#L22
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/barcodes/models/barcode_rule.py#L14
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/crm_iap_mine/models/crm_iap_lead_industry.py#L16
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/event/models/event_event.py#L55
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/event/models/event_mail.py#L96
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/fleet/models/fleet_vehicle_model_category.py#L17
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/fleet/models/fleet_vehicle_state.py#L13
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/hr/models/hr_contract_type.py#L13
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/im_livechat/models/chatbot_script_step.py#L21
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/l10n_ar/models/l10n_ar_afip_responsibility_type.py#L13
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/loyalty/models/loyalty_program.py#L19
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/mrp/models/mrp_bom.py#L51
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/mrp/models/mrp_bom.py#L530
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/payment/models/payment_provider.py#L24
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/point_of_sale/models/pos_category.py#L20
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/product/models/product_attribute.py#L108
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/product/models/product_attribute.py#L20
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/spreadsheet_dashboard/models/spreadsheet_dashboard_group.py#L12
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/spreadsheet_dashboard/models/spreadsheet_dashboard.py#L17
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/stock/models/product_strategy.py#L72
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/stock/models/stock_picking.py#L32
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_crm_partner_assign/models/res_partner_activation.py#L12
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_crm_partner_assign/models/res_partner_grade.py#L14
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_event_exhibitor/models/event_sponsor.py#L36
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_event_track_quiz/models/event_quiz.py#L28
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_event_track_quiz/models/event_quiz.py#L59
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_slides/models/slide_question.py#L14
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website_slides/models/slide_question.py#L55
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website/models/theme_models.py#L145
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website/models/website_configurator_feature.py#L17
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/addons/website/models/website_rewrite.py#L75
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/odoo/addons/base/models/ir_actions.py#L338
https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/odoo/addons/base/models/ir_module.py#L108

2023-07-06 23:11 UTC, moylop260 commented
@rco-odoo 

What do you think using a default for the `default` parameter from ORM for sequence fields if it is not defined?

2023-07-06 23:17 UTC, moylop260 commented
Hi @mart-e 

Who could help us to review it this PR?

Thank in advance!

2023-07-07 09:29 UTC, mart-e commented
@moylop260 sorry I prefer to let the @odoo/rd-accounting team decide

2023-07-07 09:38 UTC, william-andre reviewed
I'm not sure that this won't break the order of lines in stable. (new lines would get `0` but old lines will keep `NULL`)

What would be better IMO would be this: https://github.com/odoo/odoo/pull/85750
The sequence would be set automatically to an increasing value, making it follow the declaration in the file, and then you can change it manually without issues afterward. (of course it gets reset if you update the module)

2023-07-21 02:00 UTC, luisg123v commented
@william-andre 

> I'm not sure that this won't break the order of lines in stable. (new lines would get 0 but old lines will keep NULL)

What do you think about targeting master instead?

> What would be better IMO would be this: https://github.com/odoo/odoo/pull/85750

IMHO not mutually exclusive. That improvement will cover XML-loaded data, while this one will ensure it gets a value in any case. If the sequence could get `NULL`, then it looses its purpose.

2023-08-04 12:30 UTC, oco-odoo commented
I agree with @william-andre . @rco-odoo is on holiday for now, and I will be as well for the upcoming 3 weeks. I'll discuss https://github.com/odoo/odoo/pull/85750 with him when we're both back, and make it so we move on with this.

2023-09-25 01:12 UTC, randall-vx commented
Hi @oco-odoo do you have any news about this PR?

Regards,

cc: @luisg123v

2023-10-10 11:12 UTC, oco-odoo commented
https://github.com/odoo/odoo/pull/85750 and https://github.com/odoo/enterprise/pull/24956/files
have been merged in master. They introduce an autosequencing mechanism in data files, which will ensure all the lines get a proper sequence. 

As said in previous comments, we can't just add a default value in stable as it could behave weirdly on existing databases (lines would suddenly have sequence=0 while previously present lines had NULL). So I think the the best we can do is solve that for 17.0+, which autosequencing does. I'm closing this PR.

2023-10-10 11:12 UTC, closed without merging