[FIX] website: navbar expand class
odoo/odoo pull request #126489
Opened 2023-06-27 04:03 UTC by imanie383

Description of the issue/feature this PR addresses:

Current behavior before PR:
When the variable `_navbar_expand_class` was defined, it was not being used

Desired behavior after PR is merged:
When the variable `_navbar_expand_class` was defined, it would be set in `<nav>` element

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-27 04:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126489).

2023-06-27 04:13 UTC, niyasraphy commented
@imanie383 i was about to point the extra t and you updated :+1:

2023-06-29 13:08 UTC, rdeodoo commented
I didn't check but:
- @qsm-odoo Maybe something for your interest? Seems to be related to https://github.com/odoo/odoo/commit/6854ff8026999a2de20d163ff7118a59c33064c8
- @imanie383 Are you fixing a bug in the codebase or trying to improve it so it works with custom/third party code?

2023-06-29 15:31 UTC, imanie383 commented
@rdeodoo improve the code base

2023-06-29 16:16 UTC, rdeodoo reviewed
The code is a bit hard to get at first but I don't think there is anything wrong or to improve.
Did you find a bug and do you have a step to reproduce?

I'll let @qsm-odoo have a final look here but here is a preliminary summary.

From what I see, the `_navbar_expand_class` is basically acting as a kind of boolean (empty string will be considered as if the variable is set since the condition is `_navbar_expand_class is None` and not `not _navbar_expand_class`).

Basically, what the code does by checking quickly the original commit:
- `website.navbar` template can receive a `_navbar_expand_class` "boolean" variable. If that variable is not set (omitted), then it will use the default expand class `'navbar-expand-lg'`. If you set the variable to something, it will not add this class (but won't care what you set `_navbar_expand_class` to, it's just acting as a boolean).
- The `option_header_no_mobile_hamburger` option alter this behavior by simply replacing `navbar-expand-lg` class by `navbar-expand`, but doesn't change anything to the "boolean like" behavior.
- If you want to add your own class there, you should use the `_navbar_classes` which is used alongside it, not try to pass some class in `_navbar_expand_class`.

This would be the output of the possible cases:
```xml
<template id="template_header_hamburger" inherit_id="website.layout" name="Template Header Hamburger" active="False">
    <xpath expr="//header//nav" position="replace">
        <t t-call="website.navbar">
            <t t-set="_expand_navbar" t-value="True"/>
        </t>
        <!-- This will have no expand class added, regardless if the option is enabled or not -->
    </xpath>
</template>

<template id="template_header_hamburger" inherit_id="website.layout" name="Template Header Hamburger" active="False">
    <xpath expr="//header//nav" position="replace">
        <t t-call="website.navbar">
        </t>
        <!-- This will have `'navbar-expand'` of `'navbar-expand-lg'` if the option is enabled -->
    </xpath>
</template>
```

Basically, unless I am wrong or missing something, this would be the same as if it was written like the following code, which might be easier to understand, so you figure what is happening:

```diff
<template id="navbar" name="Navbar">
-   <t t-set="_navbar_expand_class" t-value="_navbar_expand_class is None and 'navbar-expand-lg' or ''"/>
+   <t t-set="_navbar_expand_class" t-value="'navbar-expand-lg'"/>
-   <nav data-name="Navbar" t-attf-class="navbar #{_navbar_expand_class} navbar-light o_colored_level o_cc #{_navbar_classes}">
+   <nav data-name="Navbar" t-attf-class="navbar #{_expand_navbar and _navbar_expand_class} navbar-light o_colored_level o_cc #{_navbar_classes}">
        <t t-out="0"/>
    </nav>
</template>

<template id="option_header_no_mobile_hamburger" inherit_id="website.navbar" active="False">
-   <xpath expr="//t[@t-set='_navbar_expand_class']" position="after">
+   <xpath expr="//t[@t-set='_navbar_expand_class']" position="replace">
-       <t t-set="_navbar_expand_class" t-value="_navbar_expand_class and 'navbar-expand' or ''"/>
+       <t t-set="_navbar_expand_class" t-value="'navbar-expand'"/>
    </xpath>
</template>
```

2023-07-04 13:13 UTC, qsm-odoo requested changes

2023-07-04 13:13 UTC, qsm-odoo commented on addons/website/views/website_templates.xml
> +    <t t-set="_navbar_expand_class" t-value="_navbar_expand_class is None and 'navbar-expand-lg' or _navbar_expand_class"/>
Mmh, indeed, that's an obvious mistake, thank you for noticing it :grimacing: (Un)fortunately, as it does not create any bug (as @rdeodoo explained, it just ends up being a "boolean" variable which is enough for the standard usecase), I think this change has no value in stable, only risks (breaking a custom xpath, reviving a wrong class that will be added on the navbar, etc).

Could you retarget to master and at the same time also fix the other `t-set="_navbar_expand_class"` which has the same issue in the codebase?

Thank you :pray: 

Note: for your custo in stable, you still have to possibility to inherit this template with a xpath and replace that whole t-set with the bug fixed version to solve your issue.

2024-04-26 08:59 UTC, qsm-odoo commented
Merged https://github.com/odoo/odoo/commit/86e5026c550deb292f3c150dedac4294fd0ca1f9

2024-04-26 08:59 UTC, closed without merging