[IMP] hr_skills_survey: add certifications report
odoo/odoo pull request #126438
Opened 2023-06-26 14:54 UTC by dasz-odoo

This report allows an HR manager to quickly see the status of employee's certifications red: expired, yellow: expiring in 3 months or less. There are also 2 filters for those situations.

task 3384857

2023-06-26 14:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126438).

2023-07-26 13:21 UTC, Bertrand2 requested changes
It would be nice to have some demo data as well to already have some example directly while testing :thinking:

2023-07-27 07:28 UTC, Bertrand2 approved these changes

2023-09-19 16:17 UTC, sofiagvaladze requested changes
@jugj-odoo super miner nit⁻picking comments ^^

Beyond that, it's good to me :raised_hands:

2023-09-19 16:17 UTC, sofiagvaladze commented on addons/hr_skills_survey/views/hr_employee_certification_views.xml
> +            >
uh, this is not pretty
```suggestion
                default_group_by="employee_id">
```

2023-09-19 16:17 UTC, sofiagvaladze commented on addons/hr_skills_survey/views/hr_employee_certification_views.xml
> +
one line will do

2023-09-20 11:45 UTC, jugj-odoo commented on addons/hr_skills_survey/views/hr_employee_certification_views.xml
> +
applied

2023-09-21 07:23 UTC, sofiagvaladze commented
robodoo r+

2023-09-21 08:59 UTC, closed without merging