[FIX] web: get empty id while upload background-image
odoo/odoo pull request #126683
Opened 2023-06-28 12:16 UTC by sabr-odoo

This error might occur when the user tries to change the background image of the odoo dashboard and in that scenario, if there will be no attachment_id then the error would be generated.

sentry Traceback: -
```
TypeError: WebStudioController.set_background_image() missing 1 required positional argument: 'attachment_id'
  File "odoo/http.py", line 2115, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1922, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
```

Applying these changes will resolve this issue.

sentry:-3948343333

2023-06-28 12:41 UTC, fdardenne commented on addons/web/static/src/core/file_input/file_input.js
> +        if (parsedFileData.length && parsedFileData[0].error) {
`uploadFiles` could upload many files. If the second file caused an error, it should also throw an error (not only the first one)

2023-06-28 12:43 UTC, fdardenne requested changes
Hello,
thank you for the fix. This is indeed better 👍 

Can you also add a test for this fix in `file_input_test.js` ?

2023-06-28 12:43 UTC, fdardenne commented on addons/web/static/src/core/file_input/file_input.js
> +        if (parsedFileData.length && parsedFileData[0].error) {
uploadFiles could upload many files. If the second file caused an error, it should also throw an error (not only the first one)

2023-08-17 09:00 UTC, abz-odoo commented
Hello @Iucapad what do you think about this ?

2023-08-17 11:26 UTC, Iucapad commented
The fix looks okay but the runbot fails.

-> A test should be added, as dafl said in his last comment

2025-11-21 05:50 UTC, closed without merging