[FIX] website: fix default height on image gallery
odoo/odoo pull request #126766
Opened 2023-06-29 05:54 UTC by xO-Tx

Steps to reproduce:

- Go to website > drop an "Image Gallery" snippet.
- Select an image > change its order in the carousel > The height of the snippet is automatically updated.

Before 15.0 (when the snippet had no default content), the `slideshow()` method (that sets the target height to `window.innerHeight * 0.7`) was executed at least once before showing image gallery content.

The goal of this commit is to maintain height consistency by simply adjusting the height `onBuilt()`.

Spotted while reviewing [1].

[1]: https://github.com/odoo/odoo/pull/117369

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-29 05:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126766).

2023-07-07 13:39 UTC, qsm-odoo commented
@robodoo delegate=loco-odoo

2023-09-07 16:03 UTC, qsm-odoo commented
Well... already delegated that one @loco-odoo :)

2023-09-20 13:02 UTC, loco-odoo requested changes

2023-09-20 13:02 UTC, loco-odoo commented on addons/website/static/src/snippets/s_image_gallery/options.js
> -        this.$target.css('height', '');
@xO-Tx , I think we should be carefull about the remove of this line of code; it seems to break something for the "Images Wall" snippet: when you want to add a lot of images, only few are displayed (see video) :)  
[Screencast from 09-20-2023 02:56:35 PM.webm](https://github.com/odoo/odoo/assets/114914971/08990723-902e-4d70-82c1-49af17b48caf)

2024-04-16 09:16 UTC, C3POdoo commented
Dear @xO-Tx,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2026-01-06 15:44 UTC, loco-odoo commented
@robodoo r+

2026-01-06 18:30 UTC, closed without merging