[IMP] l10n_sk,l10n_cz: invoice layout legal imp
odoo/odoo pull request #126837
Opened 2023-06-29 12:49 UTC by malb-odoo

before this PR, some legal information were missing from our invoice layout, for the l10n_cz and l10n_sk localization.

task: 3374969

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-29 12:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126837).

2023-08-02 13:06 UTC, JulienAlardot requested changes
Nothing much but let's avoid adding depreciated trash :p

2023-08-07 14:16 UTC, JulienAlardot approved these changes
LGTM @jbw-odoo

2023-08-08 07:51 UTC, jbw-odoo reviewed
👋

2023-08-08 21:50 UTC, closed without merging