[IMP] account: clarify error message when the address is missing
odoo/odoo pull request #126855
Opened 2023-06-29 14:24 UTC by SaddemAmine

## Description of the issue/feature this PR addresses 
The error message should be clearer.
## Current behavior before PR
When posting an expense to be reimbursed while the user didn't set up their employee address the error message they receive is too generic and doesn't help point them in the right direction.
## Desired behavior after PR is merged
The error message will be changed to a more suitable alternative resulting in better clarity for the user.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-03 07:08 UTC, rugo-odoo requested changes
We also need to update the `.pot` file and the `.po` files in the folder `i18n`.

2023-07-03 08:51 UTC, JulienAlardot commented
@SaddemAmine @rugo-odoo 
We still need the original error message when creating a normal vendor bill

2023-07-26 06:47 UTC, rugo-odoo commented
LGTM good job !

2023-08-03 09:31 UTC, qdp-odoo commented
commit message is wrong, it should be 

> [IMP] expense: clarify error message when the address is missing


Otherwise, I didn't know you spoke that many languages!! :scream: Joke aside: it would have been ok to adjust the .`pot` and let the translators from the community do the rest: it doesn't look like a practice that would scale should you have more than 1 string to translate ^^

2023-08-03 09:45 UTC, SaddemAmine commented
> commit message is wrong, it should be
> 
> > [IMP] expense: clarify error message when the address is missing
> 
> Otherwise, I didn't know you spoke that many languages!! 😱 Joke aside: it would have been ok to adjust the .`pot` and let the translators from the community do the rest: it doesn't look like a practice that would scale should you have more than 1 string to translate ^^

I'm multilingual 😎
But yeah, I didn't know we only translate localization modules, lesson learned, the hard way.

2023-08-10 11:21 UTC, smetl approved these changes
@robodoo r+

2023-08-10 13:13 UTC, closed without merging