[IMP] global_filter: can select user automatically and improve date f…
odoo/odoo pull request #126935
Opened 2023-06-30 09:22 UTC by jash-odoo

…ilter

If a user does not select any year, the system previously displayed data for the current year due to the granularity being set to the year. To enhance this functionality, we've added a boolean field, allYear. If a user doesn't select any specific year, this field will allow retrieval of records from the year 2000 onwards.

Regarding the relation filter, if the model is res.users, a checkbox should be displayed to automatically select the current user. Subsequently, the global filter will present the records corresponding to that user.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-06-30 09:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/126935).

2023-07-19 06:17 UTC, somu-odoo requested changes
Looks good to me, just couple of changes.

2023-07-19 06:17 UTC, somu-odoo commented on addons/spreadsheet/static/src/global_filters/helpers.js
>      } else {
Not needed to be put in a if / else case anymore when there is only ONE expected `type`.  Crosscheck it's functionality once and update the `param` accordingly.

2023-09-15 06:40 UTC, LucasLefevre reviewed
Hello,
I already pushed a commit addressing the comments and other things. I'll continue working on this. OXP approaches, we have to move fast, it will be easier from here.
Thanks

2023-10-03 14:48 UTC, chapital commented
There's a Way to ADD a TODAY filter, to avoid select a range of date

E.g. 01/01/2023 to 01/01/2023

Also if you have the today filter this gonna show the info of today, and not the range of date saved.

2023-10-04 07:23 UTC, hokolomopo reviewed
Olà :wave:

2023-10-04 08:48 UTC, hokolomopo commented on addons/spreadsheet/static/src/global_filters/components/filter_date_value/filter_date_value.js
> +import { FILTER_DATE_OPTION, monthsOptions } from "@spreadsheet/assets_backend/constants";
We could sort it, we only need it sorted once for the filter_date_value component right ?

2023-10-05 07:44 UTC, LucasLefevre commented on addons/spreadsheet/static/src/global_filters/helpers.js
> +                    return CommandResult.Success;
this is a bit stupid, but I keep the empty string as a valid value for backward compatibility.

2023-10-09 13:00 UTC, robodoo commented
@jash-odoo @rrahir linked pull request(s) odoo/enterprise#43426 not ready. Linked PRs are not staged until all of them are ready.

2023-10-09 22:57 UTC, closed without merging