[IMP] timeoff: reports ux change
odoo/odoo pull request #127034
Opened 2023-07-03 07:24 UTC by rupa-odoo

Before this commit if we go to the Time off and go to reporting in that select the to employee  there are graph , calendar, pivot views and there are two default filter active employee , Employee > Type .

And After that when we go to  to type there are list, pivot view  and by default there are 4 filter to the list view of the to type and in list view there is button.

Improvements :

To Employee :
Add the List view and make it default.
And make Current year by  default.

To Type :
Add the graph view and make it default.
Made changes in the filter add Time off Allocations in that filter. Remove that button and use action method to the record.

task-3389174

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-03 07:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127034).

2023-07-26 14:22 UTC, Bertrand2 requested changes

2023-07-26 14:22 UTC, Bertrand2 commented on addons/hr_holidays/report/hr_leave_reports.xml
> +                <field name="number_of_days" string="Duration(Days)" type="measure"/>
```suggestion
                <field name="number_of_days" string="Duration (Days)" type="measure"/>
```

2023-08-02 08:27 UTC, Bertrand2 approved these changes

2023-08-23 08:00 UTC, robodoo commented
I'm sorry, @sofiagvaladze: draft PRs can not be approved.

2023-08-25 15:24 UTC, sofiagvaladze commented
robodoo r+

2023-10-05 07:02 UTC, sofiagvaladze commented
robodoo r+

2023-10-05 07:32 UTC, robodoo commented
@rupa-odoo @sofiagvaladze staging failed: ci/runbot on 5a6b1856a92f033fc07373b2265b94ca3d23c64d (view more at https://runbot.odoo.com/runbot/build/51930316)

2023-10-05 08:46 UTC, tivisse commented
@robodoo retry

2023-10-05 12:59 UTC, closed without merging