[FIX] website_sale_digital: handle the issue for non-integer type attachment_id
odoo/odoo pull request #127450
Opened 2023-07-05 13:33 UTC by omra-odoo

This issue arises when a user adds no value to the `attachment_id` when entering the manual URL.In this case traceback will generated.

steps to produce :
- Install the website_sale_digital module.
- Go to website > Enter the wrong URL without the value of `attachment_id`.
- For e.g. `my/download?attachment_id` > Press the enter error will generated.

see the traceback: 
```
ValueError: invalid literal for int() with base 10: ''
  File "odoo/http.py", line 2123, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1840, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 190, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/website_sale_digital/controllers/main.py", line 50, in download_attachment
    attachment = request.env['ir.attachment'].sudo().browse(int(attachment_id)).exists()
```

After this commit, the problem of a non-integer type for `attachment_id` will be resolved by redirecting the user to the Sales Orders page.

sentry-4286948781

2023-07-05 13:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127450).

2023-07-07 05:19 UTC, omra-odoo commented
@odoo/sentry_reviewers can you please check this PR?

Thank You!

2023-07-07 12:10 UTC, yelizariev requested changes
I don't think we want this change.

We do need do clean sentry from such king of tracebacks, but we must find another solution: fix it internally on saas level or fix it globally in code base. We can't fix every parameter where user may type random string instead of a number

2023-07-07 12:10 UTC, yelizariev commented on addons/website_sale_digital/controllers/main.py
> +    def download_attachment(self, attachment_id=False):
Changing semantics in stable doesn't look as a good idea

2023-08-04 09:34 UTC, closed without merging