[FIX] point_of_sale: PosOrder.get_tip, now checks the actual tip amount, instead of the unit price
odoo/odoo pull request #127519
Opened 2023-07-05 21:06 UTC by JVegaB

Description of the issue/feature this PR addresses:

If you modify the quantity of a tip order line, the method `get_tip`, does not takes into account the actual quantity of the line. So if you have `qty == 0` or `qty == 99`, the result will be the same if it where `qty == 1`.

Desired behavior after PR is merged:

The result will take into account all the calculations needed, to represent the actual amount in the order line.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-05 21:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127519).

2023-07-05 22:21 UTC, hugho-ad approved these changes

2023-07-06 12:36 UTC, pedrambiria requested changes
Thanks for your work.

Since the tip is typically an optional amount added on top of the base price, it makes sense that the quantity of a tip should remain fixed at one. Allowing the quantity to be modified might lead to ambiguity or unintended consequences. For example, changing the quantity of the tip might inadvertently multiply the tip amount, which may not be an expected behavior.

Instead of modifying the method to take the quantity into account, a potentially more intuitive approach would be to restrict the quantity of the tip order line to one. This ensures that the tip remains consistent as a single addition to the base price.

In light of this, can you implement a mechanism that prevents the quantity of the tip order line from being modified?

2023-07-07 18:50 UTC, JVegaB commented
@pedrambiria Hi! Thanks for the feedback!

1. As you suggested, Ive added a validation for when a tip quantity is being changed from the UI (the deletion of that line is actually posible)

![notipmod](https://github.com/odoo/odoo/assets/34751857/e1f1390e-4eef-44e3-94a1-69327b8096c2)

2. I still think that we need to fix the `get_tip_method`. Here I present a case when that method is causing a wrong value in the backend:



##### Steps to reproduce

1. Configure a pos.config with tips
1. Open a new pos.session with that pos.config
1. Create a non empty order
1. Click "Pay"
1. In the payment screen, click "Tips"
1. Put X amount on the modal just opened, and add the tip to the order
1. Click back, so it takes you to the product screen, with tha same order
1. Select the tip line
1. Check the numpad is in quantity mode
1. Click the delete button on the numpad
1. Click "Pay"
1. Pay the order and click "Finalize"
1. Open the order in the backend

##### Current

1. There is a `pos.order.line` that is a tip, but the charge on that line is $0.
1. The field `(pos.order).tip_amount`, have the incorret amount of $X, that was entered, then deleted.

![backend_order](https://github.com/odoo/odoo/assets/34751857/1f71de5a-9301-4363-9ae1-a8beea4f844f)

##### Expected

The tip `pos.order.line` amount, must be the same as the field `(pos.order).tip_amount`.

2023-07-12 07:03 UTC, pedrambiria commented
@JVegaB To address this problem, we need to ensure that the tip order line isn't reduced to zero. One approach could be to call this._setValue('remove') if event.detail.key equals "Backspace". However, I propose a more effective solution would be to disable the quantity and discount buttons for the tip product. This could be achieved by implementing a new function for each mode button. This function would return whether the button should be disabled or not, and could then be utilized within the view.

2023-07-12 17:14 UTC, JVegaB commented
@pedrambiria I like the idea you are proposing, that way, we avoid modifying the `get_tip`  method, since we already managed the quantity from the UI.

I will tag you here again when the adjustment is made ;)

2023-07-13 23:01 UTC, JVegaB commented
@pedrambiria Hi! Ive made some modifications to the code:

- You cannot modify a tip line (method `_updateSelectedOrderline`)
- When trying to delete a tip line, instead of being set to `0`, the line is removed. (method `_updateSelectedOrderline`)

Now, why I did not add some helper methods to disable the numpad CTA for discount, and quantity? The reason is that widget (`point_of_sale.NumpadWidget`), has no access to the selected order line. Since the actual logic is in the parent component (`point_of_sale.ProductScreen`).

2023-07-14 15:08 UTC, pedrambiria requested changes
It's possible to implement a mechanism to disable the Numpad mode buttons by passing functions, but it's too much for this, and we can proceed with your current solution. Here I put some suggestions for your code.

2023-07-17 18:43 UTC, JVegaB commented
@pedrambiria Comments solved!

2023-07-21 18:38 UTC, hugho-ad commented
@pedrambiria 
 friendly reminder

2023-07-24 09:33 UTC, pedrambiria commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +                } else {
We can allow users to change the price of the tip. So you have to exclude the price numpad Mode.

2023-07-24 16:38 UTC, JVegaB commented
@pedrambiria Done! Could you check it please?

2023-07-25 08:11 UTC, pedrambiria approved these changes
Looks good to me.
@caburj could you please review it?

2023-07-27 18:50 UTC, JVegaB commented
@caburj Hi! Could you help us here, with a review?

Thanks!

2023-07-28 06:51 UTC, caburj requested changes
Thank you for this contribution. May I ask to add in the commit message a summary of the issues resolved by this PR (both the original intent and the discovered). It would probably be one to two sentences.

Also, kindly resolve the suggested changes and we can proceed.

2023-07-28 06:51 UTC, caburj commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +                        body: this.env.pos.env._t("Customer tips, cannot be modified directly"),
```suggestion
                        title: this.env._t("Cannot modify a tip"),
                        body: this.env._t("Customer tips, cannot be modified directly"),
```

2023-07-28 14:19 UTC, JVegaB commented
@caburj All ready! Could you check this again, please?

2023-07-28 14:23 UTC, caburj commented
Remove the `[IMP]` in the commit title. CI doesn't allow multiple tags.

2023-07-28 14:24 UTC, JVegaB commented
@caburj Fixed

2023-07-28 14:28 UTC, JVegaB commented
@caburj For some reason, the commit message in this PR seems to not be updated. But it is actually renamed:

https://github.com/vauxoo-dev/odoo/commit/ba5a8215e61ae49608734291952e382455c859ce

2023-07-28 14:30 UTC, caburj approved these changes
robodoo r+

2023-07-28 17:36 UTC, closed without merging