[IMP] l10n_in_edi: hsn compliance value to be stored at Invoice Level
odoo/odoo pull request #127559
Opened 2023-07-06 10:13 UTC by gman-odoo

Before this commit
==================
HSN Codes are mapped to Product and same Carried to the various reporting level.

After this commit
=================
HSN Codes are stored at invoice level and displayed in invoice lines

task- 3410236

2023-07-06 10:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127559).

2023-12-22 11:02 UTC, jva-odoo requested changes

2023-12-22 11:06 UTC, jva-odoo commented on addons/l10n_in_edi/models/account_move_line.py
> +    l10n_in_hsn_code = fields.Char(string="HSN/SAC Code", help="Harmonized System Nomenclature/Services Accounting Code", compute="_compute_l10n_in_hsn_code", store=True, readonly=False)
```suggestion
    l10n_in_hsn_code = fields.Char(string="HSN/SAC Code", help="Harmonized System Nomenclature/Services Accounting Code", related="product_id.l10n_in_hsn_code", store=True, readonly=False)
```

2023-12-22 11:06 UTC, jva-odoo commented on addons/l10n_in_edi/models/account_move_line.py
> +            record.l10n_in_hsn_code = record.product_id.l10n_in_hsn_code
```suggestion
```

2023-12-28 06:17 UTC, jipr-odoo commented
Moved to: https://github.com/odoo/odoo/pull/147654

2023-12-28 06:17 UTC, closed without merging