[FIX] mail: mobileTopbar buttons spacing
odoo/odoo pull request #127695
Opened 2023-07-07 07:08 UTC by Brieuc-brd

Prior to this commit, there was a spacing issue between `mobileTopbar` buttons.

This PR fixes this issue.

task-3415575
Part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-07 07:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127695).

2023-07-07 07:44 UTC, edi-odoo approved these changes
LGTM! Only checked on Community though, Enterprise isn't built.

2023-07-07 09:45 UTC, Brieuc-brd commented
@edi-odoo Enterprise is built :)

2023-07-11 07:43 UTC, edi-odoo commented
> @edi-odoo Enterprise is built now :)

LGTM ! @pparidans this PR is ready for review :)

2023-07-11 07:43 UTC, edi-odoo approved these changes

2023-07-11 09:28 UTC, alexkuhn requested changes
Hello, the desired visual is to keep the button next to each other, so it's clear they are "tabs".

So it's not about increasing the gap, but instead not rounding them in-between

2023-07-11 09:47 UTC, edi-odoo commented
> Hello, the desired visual is to keep the button next to each other, so it's clear they are "tabs".
> 
> So it's not about increasing the gap, but instead not rounding them in-between

Oh right! But then the bottom border of the active tab should be removed. And no need for the o-active then @Brieuc-brd ?

2023-07-11 14:01 UTC, edi-odoo commented
@Brieuc-brd Looks good to me but I don't think it's what @alexkuhn meant

2023-07-11 14:27 UTC, Brieuc-brd commented
Hey @alexkuhn 👋 What do you think ?
![Capture d’écran 2023-07-11 à 16 19 00](https://github.com/odoo/odoo/assets/80679690/77aced69-f3bc-4dd9-aacf-8b89b7b3c03c)

2023-07-11 16:21 UTC, alexkuhn approved these changes
LGTM. Thanks!
@robodoo r+

2023-07-11 17:36 UTC, closed without merging