[FIX] web: update props of many2one avtar field
odoo/odoo pull request #127753
Opened 2023-07-07 11:54 UTC by kais-odoo

set to produce:
- Create new record of many2one avtar
- Try to remove record without changing focus
- The avatar image will remain when the record is removed while it is in focus.

fix:
- update the props if input value is empty on focusout event.

task-3386018

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-07 11:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127753).

2023-08-28 17:23 UTC, auon-odoo approved these changes

2023-10-20 14:05 UTC, MissingNoShiny approved these changes

2023-11-02 12:36 UTC, xavierbol approved these changes
Thanks for your work, I left one small comment after that you can mark your PR as ready to review. 🙂

2023-11-02 12:36 UTC, xavierbol commented on addons/web/static/src/views/fields/many2one_avatar/many2one_avatar_field.js
> +    onFocusOut(event) {
Nitpicking 
```suggestion
    }

    onFocusOut(event) {
```

2023-11-03 12:54 UTC, xavierbol commented
Hello @odoo/rd-framework-js 

What do you think about that fix? 🙂 

Thanks in advance!

2023-11-07 10:03 UTC, aab-odoo requested changes
Hello. I doubt it's the right fix, because as far as I can see the issue only happens when you create a new record (btw the test probably doesn't reproduce the issue). 

This is a Many2one issue: on a Contact, in the Company field, quick create a record, then empty the field, click out -> the field looks empty. Save and reload: the quick created company is still associated with the contact

2023-11-29 13:08 UTC, closed without merging