[FIX] lunch: handle error of invalid time in lunch suppliers
odoo/odoo pull request #127860
Opened 2023-07-08 19:11 UTC by alsh-odoo

This traceback raises when user gives invalid time (hours) at the time of updating a record in lunch suppliers.

To produce this issue:

- Install `Lunch`
- Open Lunch/Configuration/Vendors
- Open an existing record and click edit button
- In `Orders` click `Send Order By` as `Email`
- Give invalid time in `Order Time` like `-ve` value or greater-than 12
- Save the record

Error: 
```
ValueError: hour must be in 0..23
  File "odoo/http.py", line 2123, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1927, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 190, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "addons/lunch/models/lunch_supplier.py", line 204, in write
    self._sync_cron()
  File "addons/lunch/models/lunch_supplier.py", line 135, in _sync_cron
    float_to_time(supplier.automatic_email_time, supplier.moment)))
  File "addons/lunch/models/lunch_supplier.py", line 27, in float_to_time
    return time(int(integral), int(float_round(60 * fractional, precision_digits=0)), 0)
```

When user update a record `write` method calls first than `_sql_constraints` and in that `write` method `_sync_cron` method is used. Because of user giving invalid time and that time is used in `_sync_cron` method it lead to above traceback.

See:
https://github.com/odoo/odoo/blob/88c1541a1646c419d37a9ca94a27f069844614db/addons/lunch/models/lunch_supplier.py#L186-L199

Sentry-4297889570

2023-07-08 19:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/127860).

2023-07-11 09:05 UTC, alsh-odoo commented
Hello @odoo/sentry_reviewers 
Please check this PR
Thank You!

2023-07-13 11:49 UTC, yelizariev commented on addons/lunch/models/lunch_supplier.py
> +        self.flush()
I guess it should be moved inside if-block.

Also, what about create method? It also uses `_sync_cron`

2023-07-14 14:00 UTC, yelizariev commented on addons/lunch/models/lunch_supplier.py
> +        self.flush()
Are you saying that `_sql_constraints` is used in create method without `flush()`?

2023-08-10 07:59 UTC, yelizariev approved these changes

2023-08-10 08:56 UTC, sofiagvaladze commented
@alsh-odoo will putting `force_save` on the fields on the view won't do a trick? :thinking:

2023-08-10 11:15 UTC, alsh-odoo commented
> @alsh-odoo will putting `force_save` on the fields on the view won't do a trick? 🤔

Hello @sofiagvaladze 

I tested functionally and won't think `force_save` will work on this case.

Do let me know if I am wrong.

Thanks!!

2023-08-10 12:40 UTC, sofiagvaladze requested changes

2023-08-10 12:40 UTC, sofiagvaladze commented on addons/lunch/models/lunch_supplier.py
> +            self.flush()
We don't need to flush everything, instead

`self.flush_model(['automatic_email_time_range'])
`

2023-08-11 06:51 UTC, sofiagvaladze commented on addons/lunch/models/lunch_supplier.py
> +            self.flush()
ah, didn't pay attention to the version :innocent:

2023-08-11 06:51 UTC, sofiagvaladze commented
robodoo r+

2023-08-11 08:20 UTC, closed without merging