[FIX] web: rectify alignment of worksheet template
odoo/odoo pull request #128035
Opened 2023-07-11 06:35 UTC by mash-odoo

**Steps:**
- Open Field Service
- Switch to the calendar view
- Click on any task
- Notice the space in the row of the worksheet template

**Issue:**
- There is a weird space between the title Worksheet Template and the template name

**Cause:**
- Due to the long name of Worksheet Template, it moves to the next line but occupies a certain amount of space around it

**Fix:**
- By setting the max width of the title, we can avoid the extra space

**Task:** 3394985

2023-07-11 06:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/128035).

2023-08-02 12:43 UTC, MissingNoShiny reviewed
LGTM, thanks for the fix :slightly_smiling_face:

2023-12-28 16:01 UTC, xavierbol commented
LGTM, thanks for your work, I will let @odoo/rd-framework-js do the final review. 🙂

2023-12-28 16:08 UTC, xavierbol commented
I have just rebased your branch. 🙂

2024-01-02 08:42 UTC, pparidans requested changes
This change does make sense and even avoid the value being hidden and requiring a horizontal scroll to be unveiled when the label is very long.

May I just ask you to explain (just a few words) in your commit message why the `flex: wrap` actually makes it display properly ?

2024-01-03 05:12 UTC, mash-odoo commented
Done! :slightly_smiling_face:

2024-01-03 10:01 UTC, pparidans commented
@robodoo r+

2024-01-03 12:20 UTC, closed without merging