[FIX] web: CP: long breadcrumb
odoo/odoo pull request #128036
Opened 2023-07-11 06:42 UTC by Brieuc-brd

Prior to this commit, when the Control Panel breadcrumb was not displayed (eg. after reloading the page), the name of the last element was used. In this case, the name was not truncated and could create a layout issue if it was too long.

This commit fixes this issue.

task-3420194
Part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-11 06:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/128036).

2023-07-11 11:33 UTC, Brieuc-brd commented
Hey @pparidans 👋 This PR is ready for tech. review :)

A simple way to check the issue:
- Go to a project task and rename it with a very long name.
- In this task, create a subtask with another very long name.
- Save and go to the subtask.
- Refresh the page.

2023-07-11 13:11 UTC, edi-odoo requested changes
I see an issue on mobile, could you check?

2023-07-11 14:49 UTC, Brieuc-brd commented
Hey @edi-odoo 👋 I've updated the branch with another issue related to the CP. Could you check ? :)

2023-07-12 07:54 UTC, edi-odoo approved these changes

2023-07-12 07:55 UTC, edi-odoo commented
LGTM! Could you just check your commit and PR note again ? I didn't get it right away.

2023-07-13 06:28 UTC, Brieuc-brd commented
Hey @pparidans 👋 the PR is ready for tech. review :)

2023-07-14 12:18 UTC, pparidans approved these changes
@robodoo r+

2023-07-14 13:38 UTC, closed without merging