[FIX] point_of_sale: load partners when scanning barcode
odoo/odoo pull request #128380
Opened 2023-07-13 09:57 UTC by khah-odoo

Before this commit, because limited partner loading is enabled by default, only a limited number of partners were loaded. As a result when scanning the barcode of a customer, it does not appear in PoS.

To fix this, we should load the partner when their barcode is scanned.

opw-3398628

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-13 09:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/128380).

2023-07-13 12:09 UTC, pedrambiria requested changes
Thanks for your work.
There are some small remarks on the code. Also it's better to mention in the code that it's not possible to load all the partners in the PoS, and if you try to load a partner that is not loaded in PoS by barcode, it won't fetch it from the server.

2023-07-13 12:09 UTC, pedrambiria commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            ]);
Use const instead.
```js
const foundPartnerIds = await this.orm.search("res.partner", [
    ["barcode", "=", code.base_code]
]);
```

2023-07-13 12:09 UTC, pedrambiria commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +                ["barcode", "=", code.base_code]
use `code.code`

2023-07-13 12:09 UTC, pedrambiria commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            // find the barcode in the backend
`// find the partner in the backend by the barcode`

2023-07-13 13:36 UTC, pedrambiria approved these changes
Looks good to me.

2023-07-25 07:25 UTC, pedrambiria commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            ]);
@caburj Here it will get the partner ids and with `_loadPartners` it will load it based on the `_loader_params_res_partner`.

2023-07-25 08:03 UTC, caburj commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
> +            ]);
Oh true. I'm sorry to miss that.

2023-07-25 08:04 UTC, caburj approved these changes
Thank you @khah-odoo and @pedrambiria!

robodoo r+

2023-07-25 10:06 UTC, closed without merging