[FIX] website_form: fix translation issue in saas
odoo/odoo pull request #128601
Opened 2023-07-14 15:35 UTC by goffauxs

In a SaaS server, the `_meta_data` variable will be translated when the
HTTP worker is spawned and it will be translated into whichever language
is set on the DB that spawns said worker. This causes issues when other
DBs use this worker as the variable may be translated into a language that is
not present in that DB. To rectify this issue, we use lazy translate so
the translation lookup is executed at rendering.

opw-3385997

2023-07-14 15:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/128601).

2023-07-14 17:05 UTC, rdeodoo requested changes
That doesn't seem to work.
Have you tried? Was it working?
![image](https://github.com/odoo/odoo/assets/30048408/f206467e-2dee-49f3-8bd8-ad7602749411)
It still shows `Metadata` instead of `Métadonnées` as when you actually print `"%s\n________\n\n" % _lt("Metadata")` at runtime inside the `insert_record()` method (which proves that the translation is not missing for french for instance).

2023-08-03 08:25 UTC, goffauxs commented
Because the translated string was being concatenated to a literal, the `_meta_label` variable wasn't considered a lazy translate object. Moving the string concatenation to when we use the variable fixes this issue. The message will now always be translated to the language the user has set on the website.

2023-08-10 20:18 UTC, rdeodoo approved these changes
@robodoo r+

2023-08-10 21:10 UTC, closed without merging