[FIX] base:  postprocess contents with proper mimetype
odoo/odoo pull request #128963
Opened 2023-07-19 04:57 UTC by sami-odoo

This error occurs when the user manually attempts to change the mimetype of the attachment, 
and then the base function `_postprocess_contents` tries to determine the type and subtype 
of the attachment.

Traceback: 
```
ValueError: not enough values to unpack (expected 2, got 1)
  File "odoo/http.py", line 2123, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1927, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 190, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web_editor/controllers/main.py", line 563, in modify_image
    attachment = attachment.copy(fields)
  File "odoo/addons/base/models/ir_attachment.py", line 599, in copy
    return super(IrAttachment, self).copy(default)
  File "odoo/models.py", line 5103, in copy
    record_copy = self.create(vals)
  File "<decorator-gen-204>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/website/models/ir_attachment.py", line 23, in create
    return super().create(vals_list)
  File "<decorator-gen-57>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "odoo/addons/base/models/ir_attachment.py", line 630, in create
    values = self._check_contents(values)
  File "odoo/addons/base/models/ir_attachment.py", line 364, in _check_contents
    values = self._postprocess_contents(values)
  File "odoo/addons/base/models/ir_attachment.py", line 319, in _postprocess_contents
    _type, _subtype = mimetype.split('/')
```

To address this issue, this commit introduces a check for the mimetype of the attachment before 
attempting to determine its type and subtype.

sentry-4283372480

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-19 04:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/128963).

2023-07-20 10:55 UTC, sami-odoo commented
Hello @odoo/sentry_reviewers ,
Please review it!

2023-07-24 12:47 UTC, kitan191 commented on odoo/addons/base/models/ir_attachment.py
> +            raise UserError(_('Unsupported mimetype (%s)', mimetype))
It's probably better to use a `try...except` clause.

2023-07-24 14:32 UTC, abz-odoo requested changes
Hello, thanks for the fix.
However I think it's better to just replace `.split` by `.partition` without even add an error.
```py
>>> _type, _subtype = "undefined".split("/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 1)
```
vs
```py
>>> _type, _, _subtype = "undefined".partition("/")
>>> _type, _, _subtype
('undefined', '', '')
>>> 
```

2023-07-24 14:32 UTC, abz-odoo commented on odoo/addons/base/i18n/base.pot
> +
```suggestion
```

2023-07-24 14:32 UTC, abz-odoo commented on odoo/addons/base/models/ir_attachment.py
> +            raise UserError(_('Unsupported mimetype (%s)', mimetype))
```suggestion
```

2023-07-24 14:32 UTC, abz-odoo commented on odoo/addons/base/models/ir_attachment.py
>          _type, _subtype = mimetype.split('/')
```suggestion
        _type, _, _subtype = mimetype.partition('/')
```

2023-08-07 13:25 UTC, sami-odoo commented
Hello @abz-odoo,
Please review the requested changes!

2023-08-08 14:08 UTC, Julien00859 approved these changes
@robodoo r+

2023-08-08 16:15 UTC, closed without merging