[IMP] sale: add global discount and fixed amount on so
odoo/odoo pull request #129087
Opened 2023-07-20 05:07 UTC by shag-odoo

Before this commit there was no discount button
IMP:
After this commit new discount button is added which have three option: -first two option calculates discount basis on % value 1.On all sale order line - it gives discount to all order based on value given by user
2. Global discount- it give discount globally to the order amount
3. Fixed amount-it give discount on the amount entered by user on total order amount

taskId-3369680

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-20 05:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129087).

2023-07-20 15:07 UTC, chapital commented
Hi

This button also will appear when you making an invoice?

Because I can make a SO an apply the discount only in the invoice

2023-09-15 09:33 UTC, vava-odoo requested changes
Thanks @shag-odoo for the work on this :+1: 
I listed a few comments and suggestions. Please apply or come back to me if there is any misunderstanding.
Also, we'll probably squash all commits at the end of the reviewing phase.
Cheers

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale/wizard/sale_order_discount_wizard.py
> +            } for tax, price_subtotal in total_price_per_tax.items()])
```suggestion
        vals = {
            'order_id': self.sale_order_id.id,
            'product_id': discount_product_id,
            'sequence': 999,
        }
        if self.discount_type == 'fixed_amount':
            vals_list = [{
                **vals,
                'name': _("Discount: %(discount)s", discount=self.discount_amount),
                'price_unit': -self.discount_amount,
                'tax_id': False,
            }]
        else:
            vals_list = [{
                **vals,
                'name': _(
                    "Discount: %(percent)s%% %(tax_str)s",
                    percent=self.discount_amount,
                    tax_str=len(total_price_per_tax) and any(t.name for t in mapped_taxes[tax]) and _(" - On products with the following taxes: %(taxes)s", taxes=", ".join(mapped_taxes[tax].mapped('name'))) or "",
                ),
                'price_unit': - price_subtotal * self.discount_amount / 100,
                'tax_id': [(Command.CLEAR, 0, 0)] + [(Command.LINK, tax.id, False) for tax in mapped_taxes[tax]],
            } for tax, price_subtotal in total_price_per_tax.items()]
        self.env['sale.order.line'].create(vals)
```

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale/wizard/sale_order_discount_wizard_views.xml
> + <record id="sale_order_line_wizard_view_form" model="ir.ui.view">
```suggestion
    <record id="sale_order_line_wizard_view_form" model="ir.ui.view">
```

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +        if reward.discount_mode == 'per_order':
create a preliminary dictionary with common values (reward_id, coupon_id, ...) to avoid duplicates below

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +                ),
```suggestion
                'name': _("Discount: %(discount)s", discount=reward.description),
```

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +                    tax_str=len(discountable_per_tax) and any(t.name for t in mapped_taxes[tax]) and _(' - On product with the following taxes: %(taxes)s', taxes=", ".join(mapped_taxes[tax].mapped('n
same comment as above

2023-09-15 09:33 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +            }for tax, price in discountable_per_tax.items() if price}
```suggestion
            } for tax, price in discountable_per_tax.items() if price}
```

2023-09-18 06:17 UTC, shag-odoo commented on addons/sale/models/sale_order.py
> +        return True
It will prevent wizard to open if there is no product in sale order.

2023-09-18 06:23 UTC, shag-odoo commented on addons/sale/wizard/sale_order_discount_wizard.py
> +        discount_product_id = self.env.ref('product.product_product_consumable').id
we can prevent user from deleting the prdouct and raise userError.

2023-09-18 06:26 UTC, shag-odoo commented on addons/sale/wizard/sale_order_discount_wizard.py
> +            total_price_per_tax[line.tax_id] += line.price_unit * line.product_uom_qty
It is working fine for multiple taxes as "on all order lines" is independent of tax_id.

2023-09-18 09:10 UTC, vava-odoo requested changes
Thanks @shag-odoo for the changes. Just a few points and I think we're good to move on :+1:

2023-09-18 09:10 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +                'price_unit': -max_discount,
```suggestion
                'price_unit': -max_discount,
                'tax_id': False,
```

2023-09-18 09:10 UTC, vava-odoo commented on addons/sale_loyalty/models/sale_order.py
> +                    tax_str=len(discountable_per_tax) and any(t.name for t in mapped_taxes[tax]) and _(' - On product with the following taxes: %(taxes)s', taxes=", ".join(mapped_taxes[tax].mapped('n
Double quotes for translatable strings in Python :pray: 
```suggestion
                    "Discount: %(discount)s%(tax_str)s", discount=reward.description,
                    tax_str=len(discountable_per_tax) and any(t.name for t in mapped_taxes[tax]) and _(" - On product with the following taxes: %(taxes)s", taxes=", ".join(mapped_taxes[tax].mapped('name'))) or "",
```

2023-09-18 09:31 UTC, shag-odoo commented
As you mentioned earlier that at the end we are going to merge the commits 
so I think it will be fine :+1:

2023-09-18 10:09 UTC, vava-odoo approved these changes
One small comment about demo data, otherwise it's fine by me.
> As you mentioned earlier that at the end we are going to merge the commits
> so I think it will be fine 👍

Yes, already forgot about that :facepalm: 

Cheers

2023-09-18 10:09 UTC, vava-odoo commented on addons/point_of_sale/data/point_of_sale_data.xml
> -            <field name="categ_id" ref="point_of_sale.product_category_pos"/>
Well... only `available_in_pos` and `categ_id` are needed here, as they are not defined in `product`

2023-10-05 15:50 UTC, Feyensv commented
@robodoo r+

2023-10-05 21:59 UTC, tde-banana-odoo commented
@robodoo r-

Seems to be breaking enterprise by removing widget sol_discount, see https://runbot.odoo.com/runbot/build/51985798

2023-10-06 09:01 UTC, Feyensv commented
@tde-banana-odoo strange, there is no enterprise use of the widget (but it was indeed forgotten in the community view).
I don't understand why community runbot was green :thinking: 

@robodoo r+

2023-10-06 10:54 UTC, closed without merging

2024-02-17 01:32 UTC, chapital commented
There's a way to add this button (wizard) on the invoices??