[FIX] l10n_in: Fix python compute taxes.
odoo/odoo pull request #129033
Opened 2023-07-19 13:09 UTC by aboo-odoo

Problem
---------

During the conversion from XML to CSV, some python taxes were broken.

Objective
---------

Fix it.

Solution
---------

Seperate the operations using semi-colons and use ternary operator. Doing so allows for a oneliner that executes with error.

task-3319164

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-19 13:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129033).

2023-07-24 08:49 UTC, rugo-odoo requested changes
Code is good. Pr message not so much haha. We should rework it.

2023-08-01 06:49 UTC, rugo-odoo commented
LGTM good work !

2023-08-03 11:13 UTC, qdp-odoo commented
@robodoo r+

2023-08-03 13:43 UTC, closed without merging