[FIX] account: wrongly unlink
odoo/odoo pull request #129253
Opened 2023-07-21 09:17 UTC by fmdl

Description of the issue/feature this PR addresses:
In case of the user have no access to all account.payment, the record can be deleted

@oco-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-21 09:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129253).

2023-07-24 13:56 UTC, oco-odoo requested changes
I'm alright with the fix, but your commit message is too generic. Explain what should happen instead and what the flow is (it's not usual to see an unlink function overridden as it is there). Also, its title should be more specific, something like "[FIX] account: don't allow unlinking payment method lines used on non-accessible payments"

2023-09-13 11:19 UTC, fmdl commented
ping @oco-odoo

2023-09-13 16:40 UTC, oco-odoo approved these changes
Oopsy, missed this one :o 

@robodoo r+

2023-09-13 18:20 UTC, closed without merging