[IMP] sale: add product in sale report tree
odoo/odoo pull request #129303
Opened 2023-07-23 13:00 UTC by niyasraphy

before this commit, in the sale.report tree
view, the product field was not added.

* sales -> reporting -> switch to pivot
* click on any row to open the tree

after this commit, the product field will
be added in the sale.report tree view.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-23 13:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129303).

2023-07-27 09:16 UTC, niyasraphy commented
hi @Feyensv ,
if you have time, can you review this pr.
thanks

2023-08-03 13:19 UTC, dalaOdoo requested changes
I think we should not separate sales person and sales team so i would suggest to put the product before.

2023-08-03 13:19 UTC, dalaOdoo commented on addons/sale/report/sale_report_views.xml
> +                <field name="product_id" string="Product" optional="show"/>
```suggestion
                <field name="partner_id" optional="hide"/>
                <field name="product_id" string="Product" optional="show"/>
                <field name="user_id" optional="show" widget="many2one_avatar_user"/>
```

2023-08-03 14:03 UTC, Feyensv approved these changes
@robodoo r+

2023-08-03 18:39 UTC, closed without merging