[IMP] l10n_dk: Rework COA
odoo/odoo pull request #129789
Opened 2023-07-26 13:44 UTC by LoisRForgeFlow

Backport of https://github.com/odoo/odoo/pull/121186 adapted to the old CoA templates engine.

@malb-odoo @Levizar

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-26 13:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129789).

2023-07-31 08:23 UTC, FlorianGilbert requested changes
Hello! 
Thank you for your contribution.
Some stuffs to say here:
- I think it should be fine to have all accounts in English and translate them in Danish by using .pot/.po file. It means that you have to add the `_post_init_hook` in the manifest and should ask the user to do a `-u`.
- If you don't translate accounts, don't take my remark about the groups and keep it in Danish. 
- Why didn't you use `.csv` file instead of `.xml` file for groups?

2023-07-31 08:23 UTC, FlorianGilbert commented on addons/l10n_dk/data/account_group.xml
Could you please indent properly your file?
Please, translate the name in English and add `.pot` and `.po` file to translate it in Danish.
Why didn't you let the file in `.csv`?

2023-07-31 08:23 UTC, FlorianGilbert commented on addons/l10n_dk/data/account.account.template.csv
Ideally the file should be translated in English, but it seems the COA was already in Danish, then you could keep it like that.

2023-07-31 08:23 UTC, FlorianGilbert commented on addons/l10n_dk/data/l10n_dk_chart_template_post_data.xml
> +<!--        <field name="property_stock_valuation_account_id" ref="a6530"/>-->
?

2023-08-01 07:45 UTC, gawa-odoo commented
@FlorianGilbert l10n_multilang is needed to translate the accounts/groups/etc... 
=> it's not a current dependency, so he can't add it for 16.0

2023-12-01 13:20 UTC, FlorianGilbert reviewed
Hello
As we have made some changes on the CoA in version 17.0 and because we don't receive response from you. I will close this PR.
Thank you again for your contribution!

2023-12-01 13:20 UTC, closed without merging