[FIX] translate: handle error while double hyphen within comment in view's arch
odoo/odoo pull request #129969
Opened 2023-07-28 04:54 UTC by sauc-odoo

Currently, When the user is adding a double hyphen within a comment in a view's architecture and tries to save the view the error occurs.

To reproduce the issue:
1. Install Argentina - Accounting module.
2. Go to Settings > Technical > Views > open l10n_ar.report_invoice_document.
3. In View Architecture comment out `<div id="informations" position="replace">`
5. Add a double hyphen within the comment.
6. Then save manually, the error will occur.

See this error:
```
XMLSyntaxError: Double hyphen within comment: <!-- <div id="informations" position="replace">
      , line 107, column 23 (<string>, line 107)
  File "odoo/tools/translate.py", line 310, in xml_translate
    root = parse_xml(value)
  File "odoo/tools/translate.py", line 288, in parse_xml
    return etree.fromstring(text)
  File "src/lxml/etree.pyx", line 3255, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
TypeError: sequence item 2: expected str instance, cython_function_or_method found
  File "odoo/http.py", line 2123, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1927, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 190, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "odoo/addons/base/models/ir_ui_view.py", line 587, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "odoo/models.py", line 4046, in write
    fields[0].determine_inverse(real_recs)
  File "odoo/fields.py", line 1396, in determine_inverse
    determine(self.inverse, records)
  File "odoo/fields.py", line 99, in determine
    return needle(*args)
  File "odoo/addons/base/models/ir_ui_view.py", line 363, in _inverse_arch_base
    view_wo_lang.arch = view.arch_base
  File "odoo/fields.py", line 1320, in __set__
    records.write({self.name: write_value})
  File "odoo/addons/base/models/ir_ui_view.py", line 587, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "odoo/models.py", line 4046, in write
    fields[0].determine_inverse(real_recs)
  File "odoo/fields.py", line 1396, in determine_inverse
    determine(self.inverse, records)
  File "odoo/fields.py", line 99, in determine
    return needle(*args)
  File "odoo/addons/base/models/ir_ui_view.py", line 345, in _inverse_arch
    view.write(data)
  File "odoo/addons/base/models/ir_ui_view.py", line 587, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "odoo/models.py", line 4014, in write
    field.write(self, value)
  File "odoo/fields.py", line 1804, in write
    cache_value = self.translate(lambda t: None, cache_value)
  File "odoo/tools/translate.py", line 315, in xml_translate
    root = parse_html(u"<div>%s</div>" % value)
  File "odoo/tools/translate.py", line 296, in parse_html
    return html.fragment_fromstring(text, parser=_HTML_PARSER)
  File "lxml/html/__init__.py", line 851, in fragment_fromstring
    % ', '.join([_element_name(e) for e in elements]))
```

To solve this issue the error has been handled using a try-except block in 'parse_html' method.

sentry-4306359331

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-28 04:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/129969).

2023-07-28 06:49 UTC, sauc-odoo commented
Hello @odoo/sentry_reviewers 
Kindly review this PR.
Thanks!!

2023-07-28 06:59 UTC, abz-odoo requested changes
you should change
`[FIX] translate: handle error when editing comment in view's architecture`
by
`[FIX] `base: handle error when editing comment in view's architecture`
in both commit and pr title

2023-07-28 08:36 UTC, sauc-odoo commented
> you should change `[FIX] translate: handle error when editing comment in view's architecture` by `[FIX] `base: handle error when editing comment in view's architecture` in both commit and pr title

Hello @abz-odoo 
Changes are done, Please check it.
Thanks.

2023-07-28 09:14 UTC, VincentSchippefilt requested changes
good but I think the exception would be better with the "from e" because it will not say that there was a second error while handling the first exception.
You should also avoid catching exception, it's too broad

2023-07-28 09:14 UTC, VincentSchippefilt commented on odoo/tools/translate.py
> +    return parse
```suggestion
    except TypeError as e:
        raise UserError(_("Error while parsing view:\n\n%s")) from e
    return parse
```

2023-07-28 11:40 UTC, sauc-odoo commented on odoo/tools/translate.py
> +    return parse
Hello @VincentSchippefilt 
Changes have been made, Kindly review them.
Thanks!!

2023-07-28 15:02 UTC, VincentSchippefilt commented
robodoo r+

2023-07-28 15:03 UTC, robodoo commented
I'm sorry, @VincentSchippefilt: draft PRs can not be approved.

2023-07-31 05:01 UTC, sauc-odoo commented
Hello @abz-odoo 
Can you please open this PR.
Thanks!

2023-08-14 09:03 UTC, nle-odoo reviewed
robodoo r+

2023-08-14 10:14 UTC, closed without merging

2023-08-21 06:25 UTC, sauc-odoo commented
> @sauc-odoo @nle-odoo this pull request has forward-port PRs awaiting action (not merged or closed):
> 
> * [[FW][FIX] base: handle error when editing comment in view's architecture #131888](https://github.com/odoo/odoo/pull/131888)
> * [[FW][FIX] base: handle error when editing comment in view's architecture #131901](https://github.com/odoo/odoo/pull/131901)

Hello @nle-odoo 
The PR has not been merged in 15.0 and saas-15.2 version.
Rest all forward-port upto master has been merged.
Please look into this.
Thanks :smile: