Master facets fix sri
odoo/odoo pull request #130017
Opened 2023-07-28 11:38 UTC by stefanorigano

Current behavior before PR:

https://github.com/odoo/odoo/assets/8558351/2edf4438-35bf-4c2f-b51c-35d11bced152

Desired behavior after PR is merged:

https://github.com/odoo/odoo/assets/8558351/088ac346-5cce-4f89-8d56-948aef12ab47

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-28 11:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130017).

2023-07-31 08:13 UTC, stefanorigano commented
Hello @bouvyd , here the facets' pr.
What do you think?

2023-08-03 13:23 UTC, stefanorigano commented
> LGTM, except the shadow on hover which looks weird to me
 
_Discussed on discord with @bouvyd . TDLR: we agreed on keeping the shadow 'cause it's consistent with the new m2mAvatar design + all other elements that "stand up" (popovers ,dropdowns..)_ 

@pparidans ready for tech. review, thanks 👍

2023-08-04 07:25 UTC, pparidans requested changes
LGTM

Tiny change to do (but not related to your actual code) and :+1:

2023-08-04 07:25 UTC, pparidans commented on addons/web/static/src/search/search_bar/search_bar.scss
>  }
Now that you edit this file, could you add the missing line break at the end ?

2023-08-04 07:57 UTC, bouvyd commented
nitpicking comments are by definition not blocking, if the code is good we should not stop ourselves because a newline is missing. 
![ain't nobody got time for that](https://media0.giphy.com/media/bWM2eWYfN3r20/giphy.gif?cid=ecf05e47kegs7x8104qvzjl51mn4iljxo2pdp5bb9hf6t8ni&ep=v1_gifs_search&rid=giphy.gif&ct=g)

you can call me _Famien_ if you need to curse about me being annoying regarding efficiency/attention to details trade-offs, i take responsibility for that 😬

@robodoo r+

2023-08-04 10:22 UTC, closed without merging