[REF] hr_expense: Technical refactor
odoo/odoo pull request #130244
Opened 2023-07-31 13:46 UTC by JulienAlardot

[REF] hr_expense: Technical refactor
Accumulation of unused fields and naming conventions
incoherence for models of a same file + depreciated code
snippets + an overdose of tests that were either
redundant or not testing real flow made expense
a dull boy

task-3358176

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-31 13:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130244).

2023-08-28 12:39 UTC, xavierbol approved these changes
LGTM for the services part 🙂 

Thanks for your work! 🙂

2023-10-10 14:23 UTC, qdp-odoo requested changes
as discussed, refactor the refactoring commit, please :pray: 

note to myself: didn't went through the whole diff

2023-10-11 09:15 UTC, JulienAlardot commented on addons/hr_expense/views/hr_expense_views.xml
> +                                       readonly="not is_editable or product_has_cost" force_save="1" class="oe_inline"/>
Because I haven't cleaned that part yet and it is useless now. I removed it

2023-10-17 11:39 UTC, JulienAlardot commented on addons/hr_expense/models/hr_expense.py
> +        for _expense in self:
replacing an element in a list you are iterating over is wrong

2023-10-17 11:39 UTC, JulienAlardot commented on addons/hr_expense/models/hr_expense.py
> +        currency = currencies[:1]
It does the same and is more readable imo

2023-10-19 09:59 UTC, qdp-odoo requested changes
as discussed: refactoring of is_custom_rate has to be removed from this PR, given that it probably is a patch on a wooden leg :) We'll search for a better alternative azfter the freeze

2023-10-19 12:30 UTC, qdp-odoo requested changes

2023-10-19 12:30 UTC, qdp-odoo commented on addons/hr_expense/tests/test_expenses.py
> +            - Printing checks
what does that do here?

2023-10-19 12:30 UTC, qdp-odoo commented on addons/hr_expense/tests/test_expenses.py
> +        if self.env['ir.module.module'].search([('name', '=', 'account_check_printing'), ('state', '=', 'installed')], limit=1):
should be tested in bridge module, and if there isn't any bridge module, only values of payments (that would be printed) should be checked.

the whole "if module is installed" should be removed

2023-10-19 12:30 UTC, qdp-odoo commented on addons/hr_expense/tests/test_expenses_access_rights.py
> +        expense_sheet_approuve = self.env['hr.expense.sheet'].with_user(self.expense_user_employee).create({
franglish

2023-10-19 12:30 UTC, qdp-odoo commented on addons/hr_expense/wizard/hr_expense_split_wizard.py
> -                for coplied_expense in copied_expenses:
lol

2023-10-19 12:57 UTC, qdp-odoo requested changes

2023-10-19 12:57 UTC, qdp-odoo commented on addons/hr_expense/tests/test_expenses_multi_company.py
> +            expense_sheet_approuve \
franglish

I'd suggest a find&replace in the whole module ^^

2023-10-20 12:03 UTC, qdp-odoo commented
@robodoo r+ rebase-ff

2023-10-20 12:03 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-20 15:18 UTC, JulienAlardot commented
@qdp-odoo I need you to re r+ :)

2023-10-20 16:00 UTC, robodoo commented
@JulienAlardot @smetl linked pull request(s) odoo/upgrade#5016 not ready. Linked PRs are not staged until all of them are ready.

2023-10-20 21:48 UTC, qdp-odoo commented
@robodoo r+

2023-10-20 22:01 UTC, robodoo commented
@JulienAlardot @qdp-odoo linked pull request(s) odoo/enterprise#45149 not ready. Linked PRs are not staged until all of them are ready.

2023-10-21 01:02 UTC, closed without merging