[FIX] website: systray's navbar color
odoo/odoo pull request #130243
Opened 2023-07-31 13:39 UTC by stefanorigano

This commit fixes an issue causing website's `systrayItems` to don't be styled correctly.
It also solves a minor indentation error in the same file.

![image](https://github.com/odoo/odoo/assets/8558351/5e17f9fb-b402-4ecf-a5d4-ab201cc6adda)

task-3446638
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-31 13:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130243).

2023-07-31 14:45 UTC, stefanorigano commented
Hello @odoo/rd-website 👋
Could you have a look at this? Many thanks!

2023-07-31 16:00 UTC, rdeodoo requested changes
Hello @stefanorigano thanks for the ping :+1: 

This is breaking the backend links, both in community
![image](https://github.com/odoo/odoo/assets/30048408/e4aa829c-4c0b-43e8-a6f3-fc98cc70b03d)
and enterprise
![image](https://github.com/odoo/odoo/assets/30048408/e62438df-5697-438f-b191-2df2c274f7f7)

Side note:
- the Translate vertical alignment in community is broken but even without this PR
![image](https://github.com/odoo/odoo/assets/30048408/5559b85d-1aad-45a4-86f9-8efaa6f258b5)

For tracking purpose, we already had a fix a few weeks ago after milk at https://github.com/odoo/odoo/pull/123262 where I mentioned all the flaws that need to be considered, it might be useless for the reviewer(s) here (and to just link related things together):
> - Regular mode and translate mode
> - Translate and Edit buttons
> - Community and enterprise

2023-08-02 09:02 UTC, stefanorigano commented
Hello @rdeodoo , thanks 👋

> This is breaking the backend links, both in community ...

Well, this was the intended result following fp's feedback... but the more I see it the more I'm convinced that's not a good idea. Moreover the fact that you thought that it was a bug made me think. 
I've stripped away the "gray button" part from the PR, keeping the text-color adjustments only. 👍 

What do you think? If ok you can eventually r+

---

Some notes (not related to this PR):
- > the Translate vertical alignment in community is broken but even without this PR

I can't replicate on chrome/osx. Since we use system-fonts, I think that's a rendering issue due to a different font.
"Fixing" it for a device may break it for another one, IMO there isn't a real solution. In the backend we use "compromise values" for the most critical elements only (eg small text in breadcrumbs), for the rest we don't specifically handle fonts divergences.  

https://github.com/odoo/odoo/assets/8558351/601d7451-67a7-4f35-b907-b49300d26de8

- The default systray's elements spacing is quite tiny 'cause it normally contains icons only. This value is to tiny for website, it should be increased using the CSS variables (`--NavBar-entry-padding-left/right`).

https://github.com/odoo/odoo/assets/8558351/e6590a0e-778c-49df-8c79-27c981e95e9e


Unfortunately there is not class we can use to target the website's systray though... ideally we need something like:

```scss
.o_menu_systray.o_website_systray {
    --NavBar-entry-padding-left: whatever;
    --NavBar-entry-padding-right: whatever;
}
```

Can we inject a class (`o_website_systray` in the example) to handle this scenario?

Thanks

2023-08-07 14:05 UTC, rdeodoo approved these changes
@robodoo r+

> Can we inject a class (o_website_systray in the example) to handle this scenario?

I don't think it's that easy as we are basically only patching the navbar method which gets the systray item to return a new set of items when you are inside the website preview action and that the NavBar component doesn't seems to have built in way to add a class?

But actually, if you replace `btn btn-primary` by `o_nav_entry` for the translate element, everything works fine regarding the vertical indent in community (of course it breaks the enterprise version).
So, I am wondering, shouldn't we instead either do:
- Introduce back the enterprise css to style the bg color and use o_nav_entry? We have a way to target this element already through the existing `o_translate_website_container`
- Condition the `o_nav_entry` vs `btn btn-xx` inside a `t-att-class` depending if we are in community or enterprise, if it's possible to get that info in js?

2023-08-07 14:38 UTC, stefanorigano commented
@rdeodoo , thanks for the r+ 👍 

> Introduce back the enterprise css to style the bg color and use o_nav_entry? We have a way to target this element already through the existing o_translate_website_container

I find this approach quite problematic, in order :
1. No interactions states (:hover, :focus, :active). To define them would add a lot of CSS 
2. Fragile in case of future redesigns.  
3. Potentially inconsistent in case of clients backend customizations (a very remote case to cover, but still)

> Condition the o_nav_entry vs btn btn-xx inside a t-att-class depending if we are in community or enterprise, if it's possible to get that info in js?

This would be just perfect... also, maybe xpath from `website_enterprise`? 

In any case this would not solve the entries "tiny horizontal" padding tho, we need CSS for that...

2023-08-07 15:12 UTC, rdeodoo commented
Follow a discussion with @detrouxdev it should be feasible, I will open a PR for the class so you can add your css and let you know.
I will also open a PR for the enterprise xpath, even better indeed :+1:

2023-08-07 15:51 UTC, closed without merging

2023-08-08 12:15 UTC, rdeodoo commented
Actually, the valign issue was just because of a mismatching `line-height` between the systray items of type `btn` and others.
It was not related to a font family or a font size or anything, just that different line height making the browser glitch 1-2px.

I made a fix for that targeting this exact case and also added a commit to add the class you asked, so you can fix the spacing in css :+1: 
Would you add your own commit for the spacing on the PR?
https://github.com/odoo/odoo/pull/131228