[FIX] base_vat: update log when vies check fails
odoo/odoo pull request #130532
Opened 2023-08-02 12:46 UTC by uso-odoo

When the user will enter an incorrect VAT number in a partner, the logger exception will occur.

See this logger error message:

```
The VAT number FR10814098851 failed VIES check.

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

When the user enters VAT Number it will check through 'check_vies' method in this method, The logger is updated to use the 'warning' level instead of the 'exception' level.

https://github.com/odoo/odoo/blob/475ea457d8bfd61da19f2339950c0fcc21e25bcf/addons/base_vat/models/res_partner.py#L210

This change reflects a less severe logging level for cases where a request to VIES check fails.

sentry - 4346743977

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-02 12:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130532).

2023-08-09 11:24 UTC, uso-odoo commented
Hello @odoo/sentry_reviewers 

Can you please check this PR!

2023-08-09 13:13 UTC, abz-odoo requested changes
logger.exception gives us exception info, so to keep it we have to add exc_info=True

2023-08-09 13:13 UTC, abz-odoo commented on addons/base_vat/models/res_partner.py
> +                _logger.warning("The VAT number %s failed VIES check.", partner.vies_vat_to_check)
```suggestion
                _logger.warning("The VAT number %s failed VIES check.", partner.vies_vat_to_check, exc_info=True)
```

2023-08-28 12:33 UTC, closed without merging

2023-08-28 12:33 UTC, bit-odoo commented
fixed in https://github.com/odoo/odoo/pull/131529