[FIX] account: prevent taxes on aml for receivable/payable accounts in "invoice" moves
odoo/odoo pull request #130677
Opened 2023-08-03 11:44 UTC by kitan191

Steps to reproduce:
- Go to Contacts and open any contact (e.g. Contact X)
- Check its configured Account Receivable (e.g. 121000 Account Receivable)
- Configure that account and set a default Sales tax on it (e.g. Tax 15%)
- Create an invoice with Contact X as customer
- Add an invoice line for any amount (e.g. $100) and any tax
- Swith to "Journal Items" tab and display "Taxes" column A line (with 121000 Account Receivable) has been created automatically to balance the invoice line. This line has a tax (i.e. Tax 15%): the default one configured on the account. There should not be a tax for a receivable account. Another issue is that the tax is set on the aml but not tax line has been created.
- Go back to "Invoice Lines" tab
- Remove the tax on the invoice line
- Save In "Journal Items" tab, the tax line has been created from the aml with the receivable account.
- Go back to "Invoice Lines" tab
- Add a tax on the invoice line again
- Save
- Remove the tax on the invoice line
- Save In "Journal Items" tab, there are now 2 tax lines from the aml with the receivable account. By repeating the previous steps, new tax lines can be created infinitely.

Solution:
To prevent the issue, the default taxes shouldn't be populated on the aml when the account is a receivable (or payable) one and when the move type is an "invoice" type one. As "display_type" field of "account.move.line" is set to "payment_term" when the account is a receivable or a payable one and when "is_invoice" is True on the move, no tax will be set in "_compute_tax_ids" computed method when "display_type" is "payment_term".

opw-3345953

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-03 11:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130677).

2023-08-04 15:00 UTC, dbkosky approved these changes
This looks good to me. I've tested it locally and it works, and the test is a nice addition.
I'll forward this to @Levizar

2023-08-06 17:07 UTC, Levizar commented
It seems legit but I will have to double check

2023-08-07 09:11 UTC, Levizar requested changes
Good job!
Indeed that's something we should prevent.

2023-08-07 09:11 UTC, Levizar commented on addons/account/tests/test_account_move_out_invoice.py
> +        move = move_form.save()
We should do a classic `self.env["account.move"].create(...)` as it doesn't really matter to use a `Form` here

2023-08-07 09:11 UTC, Levizar commented on addons/account/tests/test_account_move_out_invoice.py
> +        self.assertEqual(len(payment_term_line.tax_ids), 0)
Not mandatory but we could use `assertRecordValues` to ass both at the same time

2023-08-07 09:13 UTC, Levizar commented
Also, I forgot to write it but we should rename the commit title to talk about payment_term line and not about receivable/payable

2023-08-07 11:04 UTC, kitan191 reviewed
Thanks for the review. :)

The suggested changes have been applied.

2023-08-07 12:01 UTC, Levizar approved these changes
Thanks :grin: 
@robodoo r+

2023-08-07 13:31 UTC, closed without merging