[FIX] web: form view max-width
odoo/odoo pull request #130634
Opened 2023-08-03 08:35 UTC by Brieuc-brd

Prior to this commit, there was a spacing issue in large screens (eg. 4K screen), the form view wasn't large enough and this created a big gap between the form view and the chatter.

This commit fixes this issue.

task-3453381
Part of task-3326263

BEFORE:
![image](https://github.com/odoo/odoo/assets/80679690/fa7f810c-440b-4dc6-9f55-1da1f26f2bbe)

AFTER:
![localhost_8069_web](https://github.com/odoo/odoo/assets/80679690/f58f778b-5bc0-431b-9f9d-4b7705b93018)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-03 08:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130634).

2023-08-04 06:57 UTC, Brieuc-brd commented
Hey @stefanorigano 👋  this PR is ready for review. Could you take a look at it ?

2023-08-14 12:07 UTC, Brieuc-brd commented
@stefanorigano 👋 Little reminder :)

2023-09-01 07:37 UTC, Brieuc-brd commented
@stefanorigano 👋  I just removed the `max-width: $o-form-view-sheet-max-width;` to fix this issue.
I'd like to have your feedback to make sure it's the best way to achieve this.

2023-09-01 08:09 UTC, stefanorigano requested changes
Hello @Brieuc-brd 👋

Emm... it doesn't work. The current behaviour is definitely unappealing, but at least makes possible to visually scan the content, thus fill a form in a reasonably comfortable way.

With the proposed implementation we'll end-up having text-fields more than 1100px wide when the chatter is active and almost 2000px when it's not🥲

Fp prefers the current behaviour, but I think that he made the decision without thinking of 4k and such.

In these cases I think that the solution would be a centered "container" layout to be triggered on super-hiRes only (let's say >3000).

What do you think?

![50258176-master-all runbot111 odoo com_web](https://github.com/odoo/odoo/assets/8558351/3695310a-0ab4-456f-ab9e-3b4a01002ce0)

cc. @mano-odoo

2023-09-14 06:45 UTC, Brieuc-brd commented
Hey @pparidans 👋 This PR is ready for tech. review, could you take a look at it ? Thanks ?

cc. @stefanorigano

2023-09-22 12:57 UTC, Brieuc-brd commented
@pparidans 👋  little reminder :)

2023-09-25 07:25 UTC, pparidans approved these changes
Technically, I'm OK with this. :ok_hand: 

But knowing how some people can be finicky about this kind of change, I'd like to have a second, more functional validation.
Ping @bouvyd @stefanorigano

2023-09-25 07:37 UTC, stefanorigano approved these changes
Hello @pparidans , thanks for the heads-up 👍 

LGTM too.. in terms of visual result it's a compromise and, somehow, the expected result considering the constraints; fp wants the layout to be always full-width and left aligned, so...

2023-09-25 08:25 UTC, pparidans commented
@robodoo r+

2023-09-25 11:15 UTC, closed without merging