[FIX] mail: fix chatter z-index
odoo/odoo pull request #130703
Opened 2023-08-03 12:47 UTC by morm-odoo

This PR fixes the z-index issue the chatter topbar had with the project dropdown filter.
The dropdown filter and the chatter topbar are in different stacking contexts, so their z-indexes have no influence, and it's the last one displayed that counts. In this case, in the DOM, dropdown is before chatter, so chatter takes precedence (the last is displayed on top). This was causing display issues.

task-3452373

BEFORE 
![41397951-88db5bacbc14c4dbf4d881bafb843775](https://github.com/odoo/odoo/assets/108661430/cddbde2c-27d5-4695-b0e7-96bccb99f7e9)

AFTER
![Screenshot 2023-08-02 at 15 26 39](https://github.com/odoo/odoo/assets/108661430/9246fc29-b1ef-4b4c-9255-8803f4a768fd)

2023-08-04 11:15 UTC, morm-odoo commented
@odoo/rd-design Could someone check this PR please ?

2023-08-11 07:59 UTC, stefanorigano requested changes
Thanks @morm-odoo .

2023-08-11 07:59 UTC, stefanorigano commented on addons/mail/static/src/views/form/form_renderer.scss
> +    z-index: 0;
I'd prefer to use the `z-index-0` utility class indead. Could you check?

2023-10-06 05:40 UTC, stefanorigano reviewed
Hello @morm-odoo ,
thanks for you changes and sorry for the late reply.
I rebased and push --forced your branch.

Seems like the issue has been already fixed in another way though, the listView dropdown is right aligned. Could you check ?
<img width="490" alt="image" src="https://github.com/odoo/odoo/assets/8558351/c4a538e7-3999-404b-a5c0-f79afa865d3f">

2024-06-21 08:43 UTC, robodoo commented
@morm-odoo the target branch 'saas-16.3' has been disabled, you may want to close this PR.

2024-06-21 09:16 UTC, chgo-odoo commented
Closing the PR as suggested as the issue has been fixes since this PR was created.

2024-06-21 09:16 UTC, closed without merging