[FIX] account, kanban_dashboard: fix favorite alignment
odoo/odoo pull request #130702
Opened 2023-08-03 12:43 UTC by chgo-odoo

Commit[1] introduced a change removing the `padding` property of the favorite element inside a kanban view.

Since this property was removed from the `kanban_dashboard.scss` file, which takes care of all kanbans, the alignment of the star became weird in some modules, as we detected in `project`.

=== AFTER ===

We reintroduce the existing changes and also fix the layout issue in the accounting dashboard that the previous commit aimed to fix.

commit[1]: d4ba0c1

task-3453799
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-03 12:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130702).

2023-08-04 06:42 UTC, chgo-odoo commented
Hi @stefanorigano 👋

Could you have a look at this PR, please?

Thanks

2023-08-07 13:29 UTC, stefanorigano requested changes

2023-08-07 13:29 UTC, stefanorigano commented on addons/web/static/src/views/kanban/kanban_dashboard.scss
> -            $left: calc(var(--KanbanRecord-padding-h) - #{$o-horizontal-padding})
I'd prefer to keep the CSS variables approach

2023-08-07 14:36 UTC, chgo-odoo commented
@stefanorigano PR updated. What about this?

This is actually the closest we can get from the old placement because the first render didn't center the star correctly on the title.

I checked other occurrences of the `widget="boolean_favorite"` to make sure nothing breaks and it looks fine. It only slightly increases the spacing of element inside lunch kanban card but nothing terrible

2023-08-09 14:34 UTC, chgo-odoo commented
Just pushing this so that everything is clear, this still need to be improved by using variables for the margin. Will work on this later

2023-08-09 16:53 UTC, chgo-odoo commented
Hi @stefanorigano 👋

As discussed, we revert the changes introduced in the previous commit and we take care of the layout issue. Since the padding is handled by a SCSS variable which always has the same value, I only applied a negative margin on the parent.

Could you have a look at this?

Thanks 👍

2023-08-10 07:29 UTC, stefanorigano approved these changes
Thanks @chgo-odoo , well done 👍 

I've took the liberty to update the PR's description. 
@oco-odoo , we should deploy this fix asap, could you check and eventually r+ ?

Thanks

2023-08-16 16:00 UTC, alexkuhn commented
@robodoo r+

2023-08-16 18:04 UTC, closed without merging