[FIX] l10n_*: set default taxes
odoo/odoo pull request #130733
Opened 2023-08-03 14:39 UTC by dbkosky

The default taxes for most localisations have been left undefined by default. When loading the chart template, the model generally selects the first sales and purchase taxes, based on the order in which the taxes appear in the csv, for the default sales and purchase taxes respectively.

This behaviour can be confusing to those who are not yet familiar with it. It has been decided that it is preferable instead to specify the default tax in _get_*_res_company function on the account chart template model, such that the 
default taxes are defined explicitly for every localisation.

linked enterprise pr https://github.com/odoo/enterprise/pull/45531

task-3453997

2023-08-03 14:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130733).

2023-08-03 14:41 UTC, dbkosky commented
@JulienAlardot Sorry :wink: 
(if everything looks good to you, we can tag oco, since he is aware of this one :slightly_smiling_face: )

2023-08-04 08:11 UTC, JulienAlardot requested changes

2023-08-04 08:11 UTC, JulienAlardot commented on addons/l10n_ca/models/template_ca.py
>              company.id: {
```suggestion
            self.env.company.id: {
```
oops, my bad for that one xD

2023-08-04 10:12 UTC, dbkosky commented on addons/l10n_ca/models/template_ca.py
>              company.id: {
ah thanks :)

2023-08-04 10:19 UTC, JulienAlardot commented
LGTM @jbw-odoo

2023-08-04 14:04 UTC, dbkosky commented
@JulienAlardot I'm tagging @oco-odoo on this one, since we discussed it on Tuesday

2023-08-04 14:09 UTC, JulienAlardot commented
> @JulienAlardot I'm tagging @oco-odoo on this one, since we discussed it on Tuesday

Yeah, right
mentionning JB is a reflex now xD

2023-08-08 07:09 UTC, Levizar commented
l10n standalone is red, probably a test issue

2023-08-10 15:29 UTC, Levizar requested changes
GJ!

just a few unimportant comments.
Also, there is a conflict with l10n_ZA to fix

2023-08-10 15:29 UTC, Levizar commented on addons/l10n_in_edi/tests/test_edi_json.py
> +            'supplier_taxes_id': [(6, 0, sgst_purchase_5.ids)],
```suggestion
            'taxes_id': [Command.set(sgst_sale_5.ids)],
            'supplier_taxes_id': [Command.set(sgst_purchase_5.ids)],
```

2023-08-10 15:29 UTC, Levizar commented on addons/l10n_in_edi/tests/test_edi_json.py
> +            'supplier_taxes_id': [(6, 0, sgst_purchase_5.ids)],
`Command.Set`

2023-08-10 15:29 UTC, Levizar commented on addons/l10n_in_edi/tests/test_edi_json.py
> +            "supplier_taxes_id": [(6, 0, sgst_purchase_5.ids)],
same

2023-08-17 11:35 UTC, Levizar approved these changes
@robodoo r+

2023-08-17 12:00 UTC, robodoo commented
@dbkosky @Levizar linked pull request(s) odoo/enterprise#45531 not ready. Linked PRs are not staged until all of them are ready.

2023-08-17 17:50 UTC, closed without merging