[FIX] account: prevent deletion of hashed and deferred journal items
odoo/odoo pull request #130808
Opened 2023-08-04 07:21 UTC by rigr-odoo

The account tour was failing in case some entries were hashed or were linked to deferral entries because these kind of entries cannot be deleted but only reverted.

Enterprise PR: https://github.com/odoo/enterprise/pull/44982

task-id 3437130

2023-08-04 07:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/130808).

2023-08-17 14:56 UTC, Levizar requested changes
Très très belle PR!

2023-08-17 14:56 UTC, Levizar commented on addons/account/tests/test_tour.py
> +            all_moves.filtered(lambda m: not m.inalterable_hash and not m.deferred_move_ids).button_draft()
We should add a comment explaining why we need to do that.

2023-08-24 11:20 UTC, Levizar commented
@robodoo delegate+

If TSB is ok with the current work, you will be able to self r+

2023-08-25 14:12 UTC, rigr-odoo commented
@robodoo r+

2023-08-25 14:49 UTC, rigr-odoo commented
@robodoo r+ rebase-ff

2023-08-25 14:50 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-08-25 14:50 UTC, robodoo commented
I'm sorry, @rigr-odoo: this PR is already reviewed, reviewing it again is useless.

2023-08-25 16:29 UTC, closed without merging