[FIX] hr_expense: update sheet's state when posting AM again
odoo/odoo pull request #131060
Opened 2023-08-07 13:32 UTC by adwid

When posting again an account move related to an expense, the sheet's
state and the expense's state won't be updated

To reproduce the issue:
1. Create an expense
   - Paid By: Company
2. Create the related report
3. Submit to manager, Approve, Post Journal Entries
4. Open the related journal entry
5. Reset & Post

Error: States of both expense and sheet are incorrect (sheet:
"Posted" instead of "Done", expense: "Approved" instead of "Paid")

The state of the expense depends on the one of the sheet:
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L141-L153

The state of the sheet is manually written, each time the user does
an action. For instance, when posting the journal entries from the
sheet, we update the state of the sheet (which will change the state
of the expense, as shown in the above `compute`)
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L642-L643
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L1164-L1165

Same thing will happen when resetting the AM to draft:
https://github.com/odoo/odoo/blob/f6a13938f904f275b0360507b7ec987ef3bc2ddc/addons/hr_expense/models/account_move.py#L16-L20

But here is the issue: nothing updates the expense/sheet states when
posting again the AM

OPW-3322836

2023-08-07 13:38 UTC, adwid commented
fw-bot up to saas-16.1
From next version, the issue is not reproducible (the sheet's state is a computed field and works better)

2023-08-08 11:42 UTC, nle-odoo approved these changes
looks good to me

2023-08-22 07:52 UTC, jco-odoo commented
@JulienAlardot Does it make sense to you already?

2023-08-22 11:44 UTC, JulienAlardot commented
> @JulienAlardot Does it make sense to you already?

Well, the [fix](9122f4158c7188db656810f01822c063e1da5b76) that introduced that bug doesn't make sense to me in the first place
Will ask the po for a clear direction on this
Also, the original fix wasn't forwarded after saas-16.1 somehow
I do not like how this fix works as a few things are not needed but before properly reviewing I'll wait for a po answer

2023-08-23 15:23 UTC, JulienAlardot commented
Sorry, the right link is https://github.com/odoo/odoo/commit/9122f4158c7188db656810f01822c063e1da5b76

2023-08-24 10:55 UTC, JulienAlardot requested changes
Ok so, the base behaviour is flawed but we'll keep it. But this shouldn't move further than 16.0 (non-included) so 15.2

2023-08-24 10:55 UTC, JulienAlardot commented on addons/hr_expense/models/account_move.py
> +        sheets.paid_expense_sheets()
```suggestion
        company_sheets = self.mapped('line_ids.expense_id.sheet_id').filtered(lambda sheet: sheet.payment_mode == 'company_account')
        company_sheets.paid_expense_sheets()
```

2023-08-24 14:54 UTC, adwid commented
fw-bot up to saas-15.2

2023-08-25 09:12 UTC, JulienAlardot approved these changes
LGTM @jco-odoo

2023-08-30 13:27 UTC, jco-odoo commented
@robodoo r+

2023-08-30 14:43 UTC, closed without merging