[FIX] web_unsplash: avoid traceback when uploading first Unsplash image
odoo/odoo pull request #131112
Opened 2023-08-07 17:09 UTC by sobo-odoo

Before this commit, when uploading an image, a traceback could appear when selecting a first Unsplash image. Note that it did not happen for the next selected ones, as long as no refresh was performed between the uploads.

It happened because some props of the `ProgressBar` component were not set when adding the first Unsplash images, causing the render to fail (the next cases worked because the props were set to their error values when the first image failed).

This commit fixes this issue by correctly setting the `ProgressBar` props when selecting an Unsplash image.

Note: this issue is difficult to reproduce as it happens in a really strange way: either the database has the issue and so the issue happens after each refresh, or it does not happen at all. Therefore, the fix this commit does is hypothetical. It also seems that clearing the browser cache fixes the issue.

opw-3413299

2023-08-07 17:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131112).

2023-08-09 07:38 UTC, sobo-odoo commented
@qsm-odoo @rdeodoo ready for review :)

2023-08-09 08:54 UTC, qsm-odoo requested changes
Could you add clearer steps to reproduce? :) "when we tried to upload an image, a traceback appeared when selecting the first Unsplash image" -> I am not actually sure what this means as I cannot upload an image and choose an unsplash image at the same time. Then when trying I had a traceback when just choosing the first unsplash image... but only once and then I cannot reproduce it anymore :shrug: 

Thank you :)

2023-08-09 08:54 UTC, qsm-odoo commented on addons/web_unsplash/static/src/components/media_dialog/image_selector.js
> +                    errorMessage: "",
Instead of forcing to add those when calling `addFile`, should not those be the default values somehow?

2023-08-09 14:36 UTC, sobo-odoo commented
@qsm-odoo I made the changes :) 
Not sure if you were talking about default values in the `addFile` function or default props, but I went for the props as I found it cleaner. (FYI, the `optional: true` are needed to define default props, and also since these props were not set, I think that they were meant to be optional to begin with)

2023-08-16 12:01 UTC, sobo-odoo commented
@qsm-odoo re-pinging you since it is a bugfix :)

2023-08-17 09:40 UTC, qsm-odoo approved these changes
- Fixed one or two typos in the commit message
- Added a reference to the commit which introduced the bug, found it because I wanted to know why this was needed starting from 16.1 and not 16.0

Thanks for the fix :+1: 

@robodoo r+

2023-08-17 11:20 UTC, closed without merging