[FIX] hr_expense: handle not null violation error
odoo/odoo pull request #131213
Opened 2023-08-08 11:27 UTC by prye-odoo

When the user sends the mail for creating an expense record from his mail account, if the user's email is not found in the hr.employee object, then a "NotNullViolation" traceback error occurs.

Steps to reproduce:
- Install the "hr_expense" module.
- Settings > Technical > Email > Incoming Mail Servers
- Create a new incoming mail server for creating new expense records from incoming mail, along with the required details, and click on the "Test & Confirm" button.
- Go to Expenses > Configuration > Settings, check the "Incoming Emails" checkbox, and set up your domain alias.
- After that, Send the email, which is configured on the incoming email server.
- While the "Mail: Fetchmail Service" schedule action will run after that, a traceback will be generated.

Error:
null value in column "employee_id" of relation "hr_expense" violates not-null constraint DETAIL:  Failing row contains (34, null, null, null, null, 1, 124, 517, null, 6, 6, test, own_account, draft, null, 2023-07-25, null, null, null, 0.00, 1.00, null, null, null, null, null, null, 2023-07-25 13:45:06.395908, 2023-07-25 13:45:06.395908, miscellaneous, no_extract_requested, null, null, null, null, null)

Traceback:
```NotNullViolation: null value in column "employee_id" of relation "hr_expense" violates not-null constraint
DETAIL:  Failing row contains (34, null, null, null, null, 1, 124, 517, null, 6, 6, test, own_account, draft, null, 2023-07-25, null, null, null, 0.00, 1.00, null, null, null, null, null, null, 2023-07-25 13:45:06.395908, 2023-07-25 13:45:06.395908, miscellaneous, no_extract_requested, null, null, null, null, null).

  File "odoo/http.py", line 2125, in __call__
    response = request._serve_nodb()
  File "odoo/http.py", line 1668, in _serve_nodb
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1929, in dispatch
    result = endpoint(**self.request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "home/odoo/src/custom/default/saas_worker/controllers/main.py", line 2218, in smtp
    proxy.message_process(None, message)
  File "addons/mail/models/mail_thread.py", line 1274, in message_process
    thread_id = self._message_route_process(message, msg_dict, routes)
  File "addons/mail/models/mail_thread.py", line 1170, in _message_route_process
    thread = ModelCtx.message_new(message_dict, custom_values)
  File "addons/hr_expense/models/hr_expense.py", line 697, in message_new
    return super().message_new(msg_dict, custom_values=custom_values)
  File "addons/mail/models/mail_thread.py", line 1309, in message_new
    return self.create(data)
  File "<decorator-gen-122>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/mail/models/mail_thread.py", line 254, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-172>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "addons/analytic/models/analytic_mixin.py", line 83, in create
    return super().create(vals_list)
  File "<decorator-gen-10>", line 2, in create
  File "odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "odoo/models.py", line 4212, in create
    records = self._create(data_list)
  File "odoo/models.py", line 4415, in _create
    cr.execute(
  File "odoo/sql_db.py", line 319, in execute
    res = self._obj.execute(query, params)
```

Before creating the expense record from the email, we need to configure the incoming mail server. user needs to match his email, which should be "Work Email" in the hr.employee object. Otherwise, the fetchmail server will not be creating the record in the hr.expense object.

sentry: 4338964732

2023-08-08 11:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131213).

2023-08-09 16:09 UTC, h4818 commented
So now we just ignore the email? is that what we want? @Laura-labe

2023-08-09 17:05 UTC, Laura-labe commented
Hello @h4818 , what do you mean by we ignore the emails? 
Employees can create expenses through emails if their email address are linked to the employee form. It's the existing behavior. Otherwise, expenses couldn't be linked to the employee and anyone could create expense which is not very safe.

2023-08-10 06:56 UTC, JulienAlardot commented
Not tested functionally but imo this fix makes sense as we want to restrict creation to employees only (users or not)
The only question I have @Laura-labe is, would we have a proper log of failed attempts? As it feels like we should
In the case an employee did a typo on their mail address and they complain that it doesn't work

2023-08-10 08:14 UTC, Laura-labe commented
@JulienAlardot  A log of failed attempts is a good idea indeed.

2023-08-10 08:40 UTC, h4818 commented
@prye-odoo to me this should not be fixed in the expenses app, but should rather be handled before `message_new` is called
See `_alias_get_error` https://github.com/odoo/odoo/pull/101019/files#diff-99b88819228d2d090b8033e629a17487a4775d0cb7990973f8b4498b121adfe1R19

2023-08-18 09:47 UTC, prye-odoo commented
> @prye-odoo to me this should not be fixed in the expenses app, but should rather be handled before `message_new` is called See `_alias_get_error` https://github.com/odoo/odoo/pull/101019/files#diff-99b88819228d2d090b8033e629a17487a4775d0cb7990973f8b4498b121adfe1R19

Hello @h4818,
Yes, I checked that this issue is not related to AliasError; if there is no alias configured, i.e., an expense alias and a domain not configured, a non-registered employee will try to create a new expense record from the incoming mail server. In that case, this not-null constraint traceback occurred because the `employee_id` field is required in the `hr.expense` object.

2023-08-24 10:51 UTC, xmo-odoo requested changes

2023-08-25 06:28 UTC, tde-banana-odoo commented
Garbage in, garbage out. Using default fallback model on incoming server is an old fallback, the right way to do it is to configure aliases. Not sure what you are trying to fix here, allowing all emails to create expense reports ? Does not really make sense to me.

2024-06-21 08:43 UTC, robodoo commented
@prye-odoo the target branch 'saas-16.3' has been disabled, you may want to close this PR.

2024-06-24 06:53 UTC, closed without merging