[FIX] sale_product_configurator: fix read properties error of undefined
odoo/odoo pull request #131210
Opened 2023-08-08 11:19 UTC by vchu-odoo

2023-08-08 11:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131210).

2023-08-09 10:02 UTC, chevalierv requested changes
Hello @vchu-odoo :wave: 

Thanks for your work on this bug fix! I've left a comment about your changes, please review it and come back to me :) FYI, if this fix needs to be forward ported, you'll have conflicts in the forward port in 16.3 following the migration of the configurator to OWL, all the files of the legacy configurator were moved in website_sale(_product_configurator). You'll need to adapt the changes to those files.

Also, can you adapt your commit message to be more precise about what was the bug, and how to reproduce it? You can take inspiration from those commits: a7413a8a5e402629fd258ea16abb3b04af509c9c, 3081a98ee392fb07a79e9334b334fdca0f868d33, 54f4ae6b63342f80fcb8b7958cf0d70e5b4936ef and ff6111f1daea1e434d642098f26356dac957c3b0.

Have a nice day :sun_with_face:

2023-09-01 12:12 UTC, chevalierv approved these changes
Hello @vchu-odoo 

Thanks for your work on this! It looks good to me :+1: 

Sorry for the delay :sweat_smile:

2023-09-01 12:18 UTC, Feyensv commented
@robodoo delegate+

2023-09-01 13:01 UTC, vchu-odoo commented
@fw-bot up to saas-15.3

2023-09-01 13:03 UTC, vchu-odoo commented
@fw-bot up to saas-15.2

2023-09-01 13:19 UTC, vchu-odoo commented
@robodoo r+

2023-09-01 16:15 UTC, closed without merging