[IMP] project_hr_expense,_*: improve project update profitability Bill amount.
odoo/odoo pull request #131505
Opened 2023-08-10 07:24 UTC by ravb-odoo

_* = project_sale_expense

In this commit, an enhancement has been made to the project_sale_expense module. When an expense is in the 'Approved' state, the respective amount is now included in the 'To Bill' section of the project profitability update. Subsequently, when the state is changed to 'Posted', the amount is automatically transferred to the 'Billed' section.

task-3451867

2023-08-10 07:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131505).

2023-08-28 16:23 UTC, auon-odoo requested changes
Thanks for your work!

2023-08-28 16:23 UTC, auon-odoo commented on addons/project_hr_expense/models/project_project.py
> +        for res in hr_expense_ids.filtered(lambda rec: rec.sheet_id.state in ['post', 'done']):
```suggestion
        for expense in hr_expense_ids:
            if expense.sheet_id.state in ['post', 'done']):
```
otherwise, you loop twice

2023-08-28 16:23 UTC, auon-odoo commented on addons/project_sale_expense/models/project_project.py
> +        for res in hr_expense_ids.filtered(lambda rec: rec.sheet_id.state in ['post', 'done']):
same

2023-08-29 08:19 UTC, auon-odoo approved these changes
Thank you @ravb-odoo ! (I think it needs a rebase)

2023-11-06 11:35 UTC, auon-odoo requested changes
Last comments :)

2023-11-06 11:35 UTC, auon-odoo commented on addons/project_hr_expense/models/project_project.py
> +            amount_to_billed += self.env['res.currency'].browse(res['currency_id']).with_prefetch(all_currencies)._convert(
```suggestion
            amount_to_bill += self.env['res.currency'].browse(res['currency_id']).with_prefetch(all_currencies)._convert(
```

2023-11-06 11:35 UTC, auon-odoo commented on addons/project_hr_expense/tests/test_project_profitability.py
> +                    'data': [{'id': 'expenses', 'sequence': expense_sequence, 'to_bill':-expense.untaxed_amount_currency, 'billed': 0.0}],
```suggestion
                    'data': [{'id': 'expenses', 'sequence': expense_sequence, 'to_bill': -expense.untaxed_amount_currency, 'billed': 0.0}],
```

2023-11-06 11:35 UTC, auon-odoo commented on addons/project_sale_expense/models/project_project.py
> +        hr_expense_ids = self.env['hr.expense'].browse(expense_ids)
```suggestion
        expenses = self.env['hr.expense'].browse(expense_ids)
```
:slightly_smiling_face:

2023-11-06 11:35 UTC, auon-odoo commented on addons/project_sale_expense/tests/test_project_profitability.py
> +            {'id': 'expenses', 'sequence': expense_sequence, 'billed': 0.0, 'to_bill':  expense.currency_id.round(-expense_foreign.untaxed_amount_currency * 0.2)},
```suggestion
            {'id': 'expenses', 'sequence': expense_sequence, 'billed': 0.0, 'to_bill': expense.currency_id.round(-expense_foreign.untaxed_amount_currency * 0.2)},
```

2023-11-06 11:35 UTC, auon-odoo commented on addons/project_hr_expense/models/project_project.py
> +        hr_expense_ids = self.env['hr.expense'].browse(expense_ids)
```suggestion
        expenses = self.env['hr.expense'].browse(expense_ids)
```

2023-11-06 12:15 UTC, ravb-odoo commented
Hello @auon-odoo 
Necessary changes are done
Thank You:)

2023-11-06 12:28 UTC, auon-odoo commented
@ravb-odoo `ci/style` :eyes:

2023-11-06 16:25 UTC, auon-odoo approved these changes
Thanks for your work!

2023-11-13 09:20 UTC, xavierbol approved these changes
robodoo r+

2023-11-13 20:05 UTC, closed without merging