[FIX] google_calendar: update log when record sync to google fails
odoo/odoo pull request #131695
Opened 2023-08-11 10:54 UTC by sabr-odoo

This error occurs when a user tries to sync the record with Google and the record does not exist or has been deleted.

```
Message: Error while syncing record. It does not exist anymore in the database.
         Google gave the following explanation: Bad Request
```

The logger is updated to use the 'warning' level instead of the 'error' level.

sentry-4367197269

2023-08-11 10:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131695).

2023-08-18 06:34 UTC, sabr-odoo commented
Hello @odoo/sentry_reviewers  ,
can you please check this PR.

Thank you.

2023-08-21 09:54 UTC, yelizariev commented
I'm not sure. For me it really looks as an error and not a warning

2023-08-22 07:49 UTC, arj-odoo requested changes
Thanks you for your contribution. What are you trying to solve? Is it an internal issue ?
Are people complaining that the logs are polluted with these entries ?
When the synchronization was disabled or not possible for some time, these kind of divergence occurs. It's not an issue but as the status code is in the 40X values, it is an error.
Moreover, the sentry-id does not correspond to a task. it is normal?

2023-08-22 12:15 UTC, yelizariev commented
@arj-odoo 
We are trying to clean logs, which means that sentry must have 0 events. For that goal we either update standard code or add a filter to internal code

2023-09-12 09:29 UTC, closed without merging