[FIX] chatWindowService: closing livechat chatters throw traceback
odoo/odoo pull request #131605
Opened 2023-08-10 16:04 UTC by lrizzi1

when closing a livechat window that is closed when you have more chatters than you can fit in your screen, triggers a method that will try to replace the window that is being closed for one of the folded windows. As this method don't check either the window being closed is actually folded, this results in a broken state that will throw tracebacks upon closig any chatter

opw-3460466

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-10 16:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/131605).

2023-08-16 09:01 UTC, tsm-odoo requested changes
Hello, could you please:
- reword your commit message to follow the [guidelines](https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#commit-message-structure)
- add a test that covers this scenario

Otherwise I think this fix makes sense.

2023-08-16 13:20 UTC, alexkuhn commented on addons/mail/static/src/web/chat_window/chat_window_service.js
> +        if (this.maxVisible < this.store.chatWindows.length && !chatWindow.hidden) {
I would put condition at the front, so it's more apparent that this branching is to handle swapping on visible chat windows

2023-08-17 12:46 UTC, alexkuhn reviewed
LGTM otherwise!

2023-08-17 12:46 UTC, alexkuhn commented on addons/mail/static/tests/chat_window/chat_window_tests.js
> +    patchUiSize({ width: 900 });
I would add the following assertions to make sure expected preconditions of tests are met:
```js
assert.ok(
        CHAT_WINDOW_END_GAP_WIDTH * 2 + CHAT_WINDOW_WIDTH * 2 + CHAT_WINDOW_INBETWEEN_WIDTH < 900,
        "should have enough space to open 2 chat windows simultaneously"
    );
    assert.ok(
        CHAT_WINDOW_END_GAP_WIDTH * 2 + CHAT_WINDOW_WIDTH * 3 + CHAT_WINDOW_INBETWEEN_WIDTH * 2 >
            900,
        "should not have enough space to open 3 chat windows simultaneously"
    );
```

If we change the sizing of chat windows, having these assertions makes life easier to adapt them ;)

2023-08-17 12:46 UTC, alexkuhn commented on addons/mail/static/tests/chat_window/chat_window_tests.js
> +    assert.containsOnce($, ".o-mail-ChatWindow-header:contains(Channel_5)");
`-header` is not necessary. Just `.o-mail-ChatWindow` is good

2023-08-17 12:46 UTC, alexkuhn commented on addons/mail/static/tests/chat_window/chat_window_tests.js
> +    await click(".o-mail-ChatWindow-header:contains(Channel_2) .o-mail-ChatWindow-command[title='Close Chat Window']");
`.o-mail-ChatWindow:contains(Channel_2) [title='Close Chat Window']` is good enough

2023-08-17 12:46 UTC, alexkuhn commented on addons/mail/static/tests/chat_window/chat_window_tests.js
> +    await click(".o-mail-ChatWindowHiddenToggler");
I would add a comment that this closes the chat window hidden menu.
I wasn't aware that it was kept open, and it seems like a soft spec so could change in the future.
Assertion below on `.o-mail-ChatWindow` relies on it being closed, therefore it's important to clearly understand the intent of this `click()` action

2023-08-18 11:59 UTC, lrizzi1 commented
hey @alexkuhn @tsm-odoo could you guys do another review for me please? I hope everything is as it should now

2023-08-18 15:05 UTC, alexkuhn approved these changes
@robodoo r+

2023-08-18 17:17 UTC, closed without merging