[FIX] mrp_account: fix WIP Report Printing Error
odoo/odoo pull request #132005
Opened 2023-08-16 08:41 UTC by cariy-odoo

Before this commit:
The Timesheets module encountered errors when attempting to print the Work-in-Progress (WIP) report in List view. In List view, after selecting an entry, the Print function of the WIP report was not functioning.

After this commit:
The WIP report is now generated seamlessly without any errors, ensuring accurate reporting of work in progress. The main issue was with the XML file,
 which was not handling multiple values of the Work in Progress report.
To resolve this error, I modified the code and implemented a for-loop, enabling it to handle multiple report values effectively.

task:3465424

2023-08-16 08:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132005).

2023-11-13 16:25 UTC, auon-odoo requested changes
Thanks for your work! 2 details and we should be good to go

2023-11-13 16:25 UTC, auon-odoo commented on addons/mrp_account/models/ir_actions_report.py
> +        and self.env.context.get('is_timesheet'):
```suggestion
        if self._get_report(report_ref).report_name == 'mrp_account.report_wip' and self.env.context.get('is_timesheet'):
```

2023-11-13 16:25 UTC, auon-odoo commented on addons/mrp_account/report/report_mrp_templates.xml
> +                                    <t t-out="', '.join(docs.mapped('account_id.name'))"/>
```suggestion
                                <span> WIP Report for
                                    <t t-out="', '.join(docs.account_id.mapped('name'))"/>
```

2023-12-01 11:37 UTC, auon-odoo approved these changes
lgtm :)

2023-12-08 13:39 UTC, Whenrow approved these changes

2023-12-08 13:52 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-12-08 16:34 UTC, closed without merging