[REF] point_of_sale: unify numpads
odoo/odoo pull request #132245
Opened 2023-08-17 15:23 UTC by vlst-odoo

At the moment, the point_of_sale module has 3 different implementations of numpads. This is absurd. In this PR we unify them all into a single numpad component.

One of the reasons why there are multiple numpads is because each requires a slightly different set of buttons. The new `Numpad` component provides a simple API which allows the consumer to specify what the buttons should be.

This is done by proving the `buttons` prop, which has the following type:
```js
    buttons: {
        type: Array,
        element: {
            type: Object,
            shape: {
                value: String,
                text: { type: String, optional: true },
                class: { type: String, optional: true },
                disabled: { type: Boolean, optional: true },
            },
        },
    }
```

In this PR we also provide a simple set of helper functions for the tours and adapt all of the existing tests accordingly.

Task: 3470346

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-17 15:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132245).

2023-08-18 11:45 UTC, caburj commented on addons/point_of_sale/static/src/app/store/pos_store.js
get rid of this diff. doesn't seem to be related.

2023-08-18 11:45 UTC, caburj commented on addons/point_of_sale/static/tests/tours/Chrome.tour.js
if not related, get rid of this diff.

2023-08-18 11:46 UTC, caburj commented on addons/point_of_sale/static/tests/tours/FixedPriceNegativeQty.tour.js
this one as well, remove this diff.

2023-08-18 11:47 UTC, caburj commented on addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
If nothing changed here, remove the diff.

2023-08-18 11:48 UTC, caburj commented on addons/point_of_sale/static/tests/tours/ReceiptScreen.tour.js
remove diff if no important change in this file.

2023-08-18 11:49 UTC, caburj commented on addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
remove diff if nothing important

2023-08-18 11:50 UTC, caburj commented on addons/pos_hr/static/tests/tours/PosHrTour.js
get rid of useless diff in this file.

2023-08-18 11:51 UTC, caburj requested changes
if the file is only changed because of formatting, get rid of that diff. It will be helpful for the review.

2023-08-28 11:48 UTC, vlst-odoo commented on addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
>       * @param {String} keys space-separated numpad keys
adapt this docstring

2023-09-07 16:16 UTC, closed without merging