[IMP] sale_project: update task's customer if SO delivery address changes
odoo/odoo pull request #132320
Opened 2023-08-18 11:47 UTC by huca-odoo

Purpose: Avoid workers ending up going to the wrong location because the delivery address changes made on the SO are not propagated to the related field service task

When the delivery address set on the SO linked to the task is updated, it us updated on the fsm task as well.

On top of the changes made in industry_fsm, the partner_id behavior of tasks is also modified. Until now, if the partner_id of a task linked to a so was removed, the link with the so was removed and the task could not be saved until another partner_id was set. This commits unlink the so from the task, only if the partner_id is set on the task and different to the one on the so.

task-3468679

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-18 11:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132320).

2023-09-29 14:07 UTC, pkyriakou reviewed
Thank you @huca-odoo 
Left two comments for you :grin:

2023-10-12 11:29 UTC, huca-odoo commented on addons/sale_project/models/project.py
> +                task.sale_line_id = False
> are we not changing the `sale_order_id` ?

Indeed :+1:  I've updated the PR to take that into account.

2023-10-12 11:29 UTC, huca-odoo commented
> Thank you @huca-odoo Left two comments for you 😁

Thanks! It's updated :pray:

2023-10-12 15:07 UTC, pkyriakou reviewed
Looks good :green_circle: Thank you @huca-odoo :100:

2023-11-03 12:17 UTC, auon-odoo requested changes

2023-11-03 12:17 UTC, auon-odoo commented on addons/sale_project/models/project.py
> +            consistent_partner_id = [task.sale_order_id.partner_id.commercial_partner_id, task.sale_order_id.partner_shipping_id.commercial_partner_id]
```suggestion
            consistent_partners = [task.sale_order_id.partner_id.commercial_partner_id, task.sale_order_id.partner_shipping_id.commercial_partner_id]
```
little detail

2023-11-03 12:17 UTC, auon-odoo commented on addons/sale_project/models/project.py
> +                consistent_partner_id = [sale_order_id.partner_id.commercial_partner_id, sale_order_id.partner_shipping_id.commercial_partner_id]
```suggestion
                consistent_partners = [sale_order_id.partner_id.commercial_partner_id, sale_order_id.partner_shipping_id.commercial_partner_id]
```
little detail

2023-11-03 15:20 UTC, huca-odoo commented
Thank you for the feedback @auon-odoo :+1:  I've updated the PR.

2023-11-03 15:34 UTC, auon-odoo approved these changes
Thanks for your work @huca-odoo

2023-11-13 08:01 UTC, xavierbol commented
robodoo r+

2023-11-13 12:24 UTC, closed without merging