[FIX] mail: show full company logo in avatar of message
odoo/odoo pull request #132325
Opened 2023-08-18 12:04 UTC by alexkuhn

Before this commit, avatar url of author of message always had style `.o_object_fit_cover`, which makes a nice crop when ratio of image does not match ratio of the `img`.

When the author of message is a company, it shows the logo of the company, and it doesn't look nice to crop it.

This commit fixes the issue by using `.o_object_fit_contain` for avatar of company, so that the logo is fully visible. When displaying the avatar of a partner whose `is_company` is undefined, the data is group-fetched, in order for models to eventually know the value of `is_company` and use the correct desirable showing.

Task-3381748

Before / After
<img width="678" alt="before" src="https://github.com/odoo/odoo/assets/6569390/aafa42c3-4057-430b-9335-e8dc39e8a84e">
<img width="662" alt="after" src="https://github.com/odoo/odoo/assets/6569390/21c4b861-1675-4016-80c9-76e13ccf2de9">

2023-08-18 12:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132325).

2023-08-21 09:33 UTC, phenix-factory commented on addons/mail/static/src/core/persona_model.js
> +    is_company;
Could be false by default instead of undefined?

2023-08-21 09:36 UTC, phenix-factory commented on addons/mail/static/src/core/persona_model.js
> +    is_company;
No it can't be false.

2023-08-23 11:17 UTC, seb-odoo requested changes
Ok for the idea to fetch missing data, but extra RPC are not desirable on page load or at every new message from new person (being either received on bus, or when opening or scrolling channels).

This PR should go together with always sending the is_company value at key moments, I would suggest in particular author from message format and channel member.

2023-08-23 11:19 UTC, seb-odoo commented on addons/mail/static/tests/web/follower_tests.js
> +                assert.step("read_form_view");
extra rpc change not desirable, test should be reverted (see other comment)

2023-08-23 11:20 UTC, seb-odoo commented on addons/mail/static/src/core/persona_service.js
> +            this._sQueue.todo.forEach((id) => this._sQueue.ongoing.add(id));
`ongoing` could be a local variable?

2023-08-23 12:52 UTC, seb-odoo approved these changes
@robodoo delegate+

2023-08-23 12:52 UTC, seb-odoo commented on addons/mail/static/tests/web/follower_tests.js
> +        { is_company: false },
This should be default false in definition setup (same as is python) instead.

2023-08-23 17:28 UTC, alexkuhn commented
@robodoo r+

2023-08-23 19:28 UTC, closed without merging