[IMP] product, website_sale: add image option for color attribute
odoo/odoo pull request #132685
Opened 2023-08-22 12:11 UTC by divy-odoo

With this commit, Image options for the color variant have been implemented.
Now, users can use images to represent pattern colors such as "leopard"
instead of solely selecting a solid color.

- User can add, remove or change the color attribute value image from
  the backend. If no image has been uploaded, it will use the corresponding
  HEX color to represent color/patterns.

task-3381738

2023-08-22 12:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132685).

2023-09-13 07:49 UTC, vava-odoo requested changes
Hi @divy-odoo 
Thanks for this. I only have minor comments at this stage (see below).
As mentioned in the task, the color attribute is also used in the backend, in the product configurator. It would be nice to apply the same change there as well.
You will also need to rebase and handle the conflicts in the view.
Cheers

2023-09-13 07:49 UTC, vava-odoo commented on addons/product/models/product_attribute_value.py
> +        help="If an image is set, the color will not be used on eCommerce")
Discussed with PO, better to explicitly mention what the image will be used for
```suggestion
        help="You can upload an image that will be used as the color of the attribute value.")
```

2023-09-13 07:49 UTC, vava-odoo commented on addons/product/models/product_attribute_value.py
> +    image_1920 = fields.Image(
The variable name looks strange to me... `attribute_image`? `attribute_color_image`? Something more explicit.

2023-09-13 07:49 UTC, vava-odoo commented on addons/website_sale/views/templates.xml
> +    <template id="website_sale.o_wsale_offcanvas_color_attribute" name="Color type attribute in filter">
The module name is not needed in the id.
```suggestion
    <template id="o_wsale_offcanvas_color_attribute" name="Color type attribute in filter">
```

2023-09-18 14:07 UTC, vava-odoo requested changes
Hi @divy-odoo 
Thanks for the update and the changes in the backend.
I have 2 remarks and a suggestion to be discussed with @paju-odoo (on the task).
Cheers.

2023-09-18 14:07 UTC, vava-odoo commented on addons/product/views/product_attribute_views.xml
> +                                <field name="image_1920" class="oe_avatar text-start float-none"
Please put it before `default_extra_price` for clarity.

2023-09-18 14:07 UTC, vava-odoo commented on addons/product/views/product_attribute_views.xml
>                                  <field name="html_color" column_invisible="parent.display_type != 'color'" widget="color"/>
Wouldn't it make sense to hide the color if an image is set?
```suggestion
                                <field name="html_color" column_invisible="parent.display_type != 'color' and not image_1920" widget="color"/>
```

2023-09-18 14:07 UTC, vava-odoo commented on addons/product/views/product_attribute_views.xml
>                  <field name="html_color" invisible="display_type != 'color'" widget="color"/>
same comment

2023-09-18 14:07 UTC, vava-odoo commented on addons/product/views/product_attribute_views.xml
>                          <field name="html_color" invisible="display_type != 'color'"/>
same comment

2023-09-26 13:51 UTC, vava-odoo approved these changes
Looks technically ok to me :+1: 
Let's move it forward! :rocket:

2023-10-20 11:50 UTC, AntoineVDV approved these changes

2023-10-23 09:35 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2023-10-23 09:36 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-23 10:08 UTC, AntoineVDV commented
@robodoo r+

2023-10-23 12:23 UTC, AntoineVDV commented
@robodoo r+

2023-10-23 21:05 UTC, closed without merging