[IMP] website_form_project: improve description set from website form data
odoo/odoo pull request #132608
Opened 2023-08-22 04:38 UTC by ravb-odoo

In this commit, the formatting of adding descriptions to tasks created from the website form has been improved.

Task: 3459958

2023-08-22 04:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132608).

2023-09-21 13:56 UTC, pkyriakou reviewed
Thank you @ravb-odoo 
I left a few minor comments for you to look into. They apply also to the enterprise PR.

2023-09-22 12:15 UTC, ravb-odoo commented on addons/website_form_project/controllers/main.py
> +            _custom_label = "<h2>%s</h2>\n\n" % _("Other Information")  # Title for custom fields
Hello @pkyriakou 
I have done with necessary changes.

Thank you:)

2023-09-27 07:54 UTC, pkyriakou reviewed
Thank you @ravb-odoo, I have no more remarks, LGTM

2023-11-09 14:47 UTC, auon-odoo requested changes
Same comments here. Thanks for your work!

2023-11-13 12:55 UTC, auon-odoo approved these changes
Last comment. You can green the task when the changes are done and the runbot is green again :fire:

2023-11-13 12:55 UTC, auon-odoo commented on addons/website_form_project/controllers/main.py
> +        if (custom or meta) and model.model == 'project.task':
```suggestion
        res = super().insert_record(request, model, values, custom, meta=meta)
        if not (custom or meta) or model.model != 'project.task':
            return res
```

2023-11-27 13:25 UTC, xavierbol reviewed
Thanks for your work, I left 2 comments. 🙂

2023-12-12 10:58 UTC, xavierbol approved these changes
LGTM, thanks again for your work. 🙂 

robodoo r+

2023-12-12 11:00 UTC, robodoo commented
@ravb-odoo @xavierbol linked pull request(s) odoo/enterprise#47278 not ready. Linked PRs are not staged until all of them are ready.

2023-12-12 17:49 UTC, closed without merging