[FIX] product: fix crash when ptav excluded
odoo/odoo pull request #132788
Opened 2023-08-23 07:49 UTC by Dj0ulo

__Current behavior before commit:__
`_get_own_attribute_exclusions()` returns the product template attribute
value (ptav) even when `ptav_active` is **false**. This makes the
frontend crash when we add a product that has such ptav to a sale
order. 

__Description of the fix:__
Prevent ptavs with `ptav_active = false` to be in the result of
`_get_own_attribute_exclusions()`.

__To reproduce:__
1. Create new Product template
1. Add 2 attributes with at least 2 values each
1. Click on the Configure button next to the first attribute line
1. Click on the first attribute value
1. Add an exclusion line for the newly created product template and one
of the value from the other attribute
1. Put `ptav_active` of the ptav to `false` (not sure how to do it 
except from the ORM but one customer managed to do it)
1. Try to add the product to a sale order line
1. `TypeError: Cannot set properties of undefined (setting 'excluded')`

opw-3466451

2023-08-23 07:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132788).

2023-08-24 09:14 UTC, Feyensv requested changes
Could you add a test in `sale_product_configurator/tests/test_product_configurator_data` please ?

We're trying to cover all those advanced cases with a dedicated test to make sure we do not break them anymore.

2023-08-24 09:14 UTC, Feyensv commented on addons/product/models/product_template.py
> +                value_id.id
```suggestion
                value.id
```

2023-08-24 09:14 UTC, Feyensv commented on addons/product/models/product_template.py
> +                ) for value_id in filter_line.value_ids if value_id.ptav_active
```suggestion
                ) for value in filter_line.value_ids if value.ptav_active
```
variable doesn't hold an id anymore, so its name should be updated as well ;)

2023-08-29 13:45 UTC, Dj0ulo commented
@Feyensv I made a test and took this opportunity to make some test utils method as the 3 tests methods were doing similar things

2023-08-31 09:39 UTC, Feyensv approved these changes
@robodoo r+

Thanks for the test (& improvements) :+1:

2023-08-31 09:39 UTC, robodoo commented
@Feyensv you may want to rebuild or fix this PR as it has failed CI.

2023-08-31 09:40 UTC, Feyensv commented
Red runbot caused by a fixed error, I guess you should rebase your branch ;)
@robodoo delegate+

2023-08-31 10:51 UTC, Dj0ulo commented
@Feyensv done!

2023-08-31 11:48 UTC, Feyensv commented
@robodoo r+

2023-08-31 13:54 UTC, closed without merging