[FIX] *: remove data for unprotected uoms
odoo/odoo pull request #132786
Opened 2023-08-23 07:26 UTC by smna-odoo

\* : l10n_ar, l10n_in, l10n_cl 

When the user deletes any unprotected uom and tries to install the module(l10n_ar, l10n_in, l10n_cl (any of one)) traceback appears.

Steps to produce:
1) Sale > Configurations > Units of Measure.
2) Search for 'Dozens' or 'Hour' and delete it.
3) Apps > Install the module.

Traceback:
```
Exception: Cannot update missing record 'uom.product_uom_dozen'
  File "odoo/tools/convert.py", line 550, in _tag_root
    f(rec)
  File "odoo/tools/convert.py", line 385, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
ParseError: while parsing /home/odoo/src/enterprise/saas-16.3/product_unspsc/data/product_data.xml:12, somewhere inside
<record id="uom.product_uom_dozen" model="uom.uom">
        <field name="unspsc_code_id" ref="product_unspsc.unspsc_code_DPC"/>
    </record>
  File "odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "odoo/modules/loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
  File "odoo/modules/loading.py", line 245, in load_module_graph
    getattr(py_module, post_init)(env)
  File "home/odoo/src/enterprise/saas-16.3/product_unspsc/hooks.py", line 13, in post_init_hook
    _assign_codes_uom(env)
  File "home/odoo/src/enterprise/saas-16.3/product_unspsc/hooks.py", line 45, in _assign_codes_uom
    tools.convert.convert_file(
  File "odoo/tools/convert.py", line 613, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "odoo/tools/convert.py", line 599, in parse
    self._tag_root(de)
  File "odoo/tools/convert.py", line 563, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
```

Sentry-4268684848

2023-08-23 07:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132786).

2023-08-24 08:48 UTC, yelizariev commented
Excuse me, but what is unprotected uom?

2023-08-25 04:53 UTC, smna-odoo commented
@yelizariev 

uom that which we can delete

2023-08-25 08:46 UTC, yelizariev commented
> @yelizariev
> 
> uom that which we can delete

Do you have a link to the code that protects some uoms from deleting?

2023-08-25 09:42 UTC, smna-odoo commented
> > @yelizariev
> > uom that which we can delete
> 
> Do you have a link to the code that protects some uoms from deleting?

https://github.com/odoo/odoo/blob/5f1ad0c1e4c1e8ed41337ccd4c12e70c9c760c85/addons/uom/models/uom_uom.py#L171-L178

2023-08-29 12:49 UTC, yelizariev commented
This PR is an implementation of FP's suggestion 
https://github.com/odoo/odoo/pull/126344#issuecomment-1687912156

2023-08-29 13:06 UTC, william-andre requested changes
> This PR is an implementation of FP's suggestion [#126344 (comment)](https://github.com/odoo/odoo/pull/126344#issuecomment-1687912156)

Continuing the discussion there then.
I think that this is a bad idea.

2023-09-22 06:50 UTC, smna-odoo commented
@fpodoo

2026-02-18 13:11 UTC, robodoo commented
@smna-odoo the target branch '15.0' has been disabled, you may want to close this PR.

2026-02-18 13:20 UTC, closed without merging