[FIX] account: setup bank wizard validation
odoo/odoo pull request #132743
Opened 2023-08-22 15:32 UTC by guva-odoo

When adding a bank account via the setup wizard,
an User Error is raised ("Incompatible companies on records")
Since 0479b2b59466ae1d6d74165345aa3a7dc5de24ed,
`check_company` is set to `True` on
`SetupBarBankConfigWizard.linked_journal_id`, but
the model has no `company_id` field.
Therefore in `BaseModel._check_company()`, no
company is found and we raise the error.

Steps:

- Go to accounting dashboard
- Make sure the "onboarding" banner is not removed from the view
- Click on "Add a bank account" on the banner
- Try to create a new one (bottom right of the wizard)
- Enter an account number, select a bank and validate
-> Error is raised

opw-3473184

2023-08-22 15:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132743).

2023-08-22 15:33 UTC, guva-odoo commented
Not convinced that the test is useful as it is, but it was written so..

2023-08-25 11:24 UTC, Levizar requested changes
GJ, just a few blabla

2023-08-25 11:24 UTC, Levizar commented on addons/account/wizard/setup_wizards.py
> +            self.company_id = self.env.company
I know it's stupid but we are able to create several wizard at the same time by code and it should work :man_shrugging: 
```suggestion
        for wizard in self:
            if not wizard.company_id:
                wizard.company_id = self.env.company
```

2023-08-25 11:24 UTC, Levizar commented on addons/account/tests/test_setup_wizard.py
> +    def test_setup_bank_account(self):
As it was broken once, it seems we need it so let's keep it.

2023-08-25 11:24 UTC, Levizar commented on addons/account/tests/test_setup_wizard.py
> +                'bank_id': self.env['res.bank'].search([('name', '=', 'BNP Paribas')]).id,
We should create a `res.bank` record to not rely on the demo data for the test

2023-08-25 11:33 UTC, Levizar approved these changes
@robodoo r+

2023-08-25 14:06 UTC, closed without merging