[FIX] website_sale_comparison: fix alignment of product page specific…
odoo/odoo pull request #132780
Opened 2023-08-23 06:21 UTC by nikj-odoo

…ation

before this PR, In product page specification tags label is not vertially align to it's value.

In this PR, fixes the alignment issue by centering the label in website product page.

task-3451377

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-23 06:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132780).

2023-08-29 12:57 UTC, Demesmaeker reviewed
Hello,

This is the only change I can see, did I miss something?
With the fix: 
![image](https://github.com/odoo/odoo/assets/69820391/5834a7ed-9546-45f7-8ea5-d01c3e5ecf3f)

Without:
![image](https://github.com/odoo/odoo/assets/69820391/473380b8-add9-4662-b1d9-98c9ba977a59)

So this looks a bit overkill for me, especially since the tag is still not aligned '^^

2023-08-30 07:52 UTC, Demesmaeker requested changes
Hello, ok, fine by me, little improvement and then it's good to go =]

2023-08-30 07:52 UTC, Demesmaeker commented on addons/website_sale/views/templates.xml
> +        <div class="o_product_tags o_field_tags d-flex flex-wrap align-items-center gap-2 mt-2">
```suggestion
        <div class="o_product_tags o_field_tags d-flex flex-wrap align-items-center gap-2">
```
This can go away too then =]

2023-08-31 05:19 UTC, nikj-odoo commented on addons/website_sale/views/templates.xml
> +        <div class="o_product_tags o_field_tags d-flex flex-wrap align-items-center gap-2 mt-2">
@Demesmaeker Hello, Done the Changes

2023-08-31 07:48 UTC, Demesmaeker approved these changes

2023-08-31 12:00 UTC, AntoineVDV approved these changes
@robodoo r+

2023-08-31 15:12 UTC, closed without merging