[FIX] web_editor: crop button at bottom of the screen
odoo/odoo pull request #132826
Opened 2023-08-23 11:28 UTC by maad-odoo

**Before this commit:**
When user inserts an image and cropper is activated then the crop buttons used 
to appear at the bottom of the screen irrespective with the size of the image.

**After this commit:**
Now, when the image is inserted and the cropper is activated, the crop buttons 
appears at the bottom of the image.

**task-3258587**

2023-08-23 11:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132826).

2024-02-28 16:59 UTC, rdeodoo requested changes
Just passing by, didn't really check anything except checking runbot by curiosity as this is a fix I wanted for quite some time.

What are those "transparent" top/bottom areas added with this branch around the image which glitches when enabling cropping?

Before: 
![image](https://github.com/odoo/odoo/assets/30048408/07360afe-51ee-4a8f-860e-38f7032ae195)

After:
![image](https://github.com/odoo/odoo/assets/30048408/b5ff8fd3-a333-4f76-878a-c69615111e42)

2024-03-15 13:22 UTC, deso-odoo requested changes

2024-03-15 13:22 UTC, deso-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
> +        !this.visibility && await this._scrollToInvisibleImage();
```suggestion
        if (!this.visibility) {
            await this._scrollToInvisibleImage();
        }
```

2024-12-18 06:16 UTC, closed without merging