[FIX] website, *: add missing _lt and missing .pot entries
odoo/odoo pull request #132975
Opened 2023-08-24 10:06 UTC by rdeodoo

There were 2 errors fixed by this commit:
1. The form registry fields added in [1] and [2] in Odoo 13 had a
   `string` attribute translated with `_t()` while now it should be
   translated with `_lt()`. It was surely working in Odoo 13 but not
   anymore. It's not worth investigating to be sure.
2. The IMP done at [3] added a lot of fields but all of those forgot the
   `_t()`/`_lt()` translation.

Note that:
1. A fix to replace `_t` by `_lt` was done at [4] but it was badly done
   as it was not targetting the correct version... and only fixed one of
   many occurences.

[1]: https://github.com/odoo/odoo/pull/32565
[2]: https://github.com/odoo/enterprise/pull/4063
[3]: https://github.com/odoo/odoo/commit/617eba941785aa680edb826e14b0009637d60dee
[4]: https://github.com/odoo/odoo/commit/2be83cae7bcda369ed5bc7806aef845c6c76e687

opw-3471873

2023-08-24 10:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132975).

2023-08-24 10:07 UTC, rdeodoo commented
@mart-e Maybe second commit is for your interest? It seems like the commits related to `.pot` changes did remove the `.pot` file while the translated term was still in the code.

2023-08-29 08:13 UTC, xavierbol approved these changes
LGTM for the services part. 🙂 

Thanks for your work. 🙂

2023-08-29 10:02 UTC, qsm-odoo requested changes
Thanks for the fix :pray: Just a question about a commit message :)

2023-08-30 09:36 UTC, rdeodoo commented on addons/website_form_project/i18n/website_form_project.pot
> +# Translation of Odoo Server.
Oops, indeed, I was a bit too much "tête in the guidon" trying to sort things out :detective: 
Ty ! Changed

2023-08-30 11:58 UTC, qsm-odoo approved these changes
Looks good, thanks :+1: Although I guess we'll need to translate on transifex before telling the customer?

@robodoo rebase-ff r+

2023-08-30 11:59 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-08-30 12:11 UTC, rdeodoo commented
> Looks good, thanks 👍 Although I guess we'll need to translate on transifex before telling the customer?

The ones which were just about replacing `_t` by `_lt` will already be directly translated, as those were exported and translated but just not correctly loaded.
For the other ones, indeed it will require the translators to translate it, which might never happen in some language especially in old versions, so I wouldn't wait.
But at worst they can translate it themselves if that's really annoying for them.
I'll summarize that to the client.

2023-08-30 13:31 UTC, closed without merging