[FIX] web: `o_search_panel` margins
odoo/odoo pull request #132965
Opened 2023-08-24 09:30 UTC by stefanorigano

Slightly increase the component size and adapt its margin/padding in order to accommodate more text.

This commit addresses an issue that made https://github.com/odoo/odoo/commit/223b9e9 necessary.
Indeed `o_cursor_pointer` has been replaced by `cursor-pointer` in commit https://github.com/odoo/odoo/commit/bd2a111, but the change
has not been applied on `o_search_panel`.

part of task-3326263
task-3476147

| saas-16.3 | This PR |
|--------|--------|
| ![image](https://github.com/odoo/odoo/assets/8558351/00550fa2-6ed7-4ccc-bf8b-c4b1c451bb4b) | ![image](https://github.com/odoo/odoo/assets/8558351/e38c14b2-9d6b-4a69-8a94-1483d6e22d39) | 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-24 09:30 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/132965).

2023-08-24 12:05 UTC, Brieuc-brd requested changes
Hey @stefanorigano , thanks for your work 👍

My only concern is a margin issue on mobile, it doesn't look centered:
![Capture d’écran 2023-08-24 à 13 31 23](https://github.com/odoo/odoo/assets/80679690/f77c7c40-2640-44e8-92bf-bac6b8c505f5)

I'm not sure if it's related to this PR, but on Community, list group items have rounded corners depending on their position. But this seems broken.
To me, either the items should have a rounded radius in all corners, or no border radius at all.
![Capture d’écran 2023-08-24 à 13 30 05](https://github.com/odoo/odoo/assets/80679690/903990b4-b402-4dea-a3a1-bb72fc533d34)

Also, still not sure if it's related to this PR but I have the feeling that the items are too compressed, perhaps adding vertical padding would solve this problem.

What do you think?

2023-08-25 08:20 UTC, stefanorigano commented
Hello @Brieuc-brd , thanks.

> My only concern is a margin issue on mobile, it doesn't look centered:

How did you achieved that screenshoot with the two lines?
I've tested adding a `bg: green` to the relevant elements, looks ok on my side.
![image](https://github.com/odoo/odoo/assets/8558351/8f40776c-9025-468b-abe1-e28567d395ed)

> I'm not sure if it's related to this PR, but on Community, list group items have rounded corners depending on their position. But this seems broken.

Yes, I'm aware, it's because of milk's border-radius changes: `o_search_panel` uses  default `list-group-items`.
It should be handled in another task indeed 👍

2023-08-25 09:35 UTC, Brieuc-brd commented
> How did you achieved that screenshoot with the two lines?

I open the filter tab on mobile : https://www.awesomescreenshot.com/video/20227234?key=5a87c0246221a80da436a778d94d358d
Previously I was talking about "margin issue" but it's actually a padding one 😅 

Since you used `pe-1 ps-3` on `o_search_panel`, it works well on widescreen, but it doesn't seem to be properly aligned when the filter column is in full width on mobile.
![Capture d’écran 2023-08-25 à 11 21 17](https://github.com/odoo/odoo/assets/80679690/8c0b81f6-c34e-415a-a0c1-861bdccf8348)


This could fix that :
```
t-att-class="env.isSmall ? 'px-3' : 'pe-1 ps-3'"
```



>Yes, I'm aware, it's because of milk's border-radius changes: o_search_panel uses default list-group-items.
It should be handled in another task indeed 👍

👍

2023-08-25 11:01 UTC, stefanorigano commented
> Previously I was talking about "margin issue" but it's actually a padding one 😅

Ah ok, I got it , thanks @Brieuc-brd ! Nice catch ;)

2023-08-25 12:39 UTC, Brieuc-brd requested changes
A few comments below, otherwise LGTM :)

2023-08-25 12:39 UTC, Brieuc-brd commented on addons/web/static/src/search/search_panel/search_panel.xml
> +        <li class="o_search_panel_category_value list-group-item py-1 cursor-pointer border-0 pe-0"
Maybe put `cursor-pointer` at the end of the list ?

2023-08-28 11:51 UTC, stefanorigano commented
Hello @Brieuc-brd 👋

Thanks for your feedbacks:

> Unnecessary double space before pb-5

Done 👍 

> Maybe put cursor-pointer at the end of the list ? [+ others...]

We normally do re-order classes when refactoring a line entirely (es.  [here ](https://github.com/odoo/odoo/pull/132965/files#diff-06a7b28e5e5b8adcefa79b5be16e026f94919c8e3113b37a45d70ac599218e99R14)); for minor adjustments it's better to keep the "wrong" order to get a neat diff.

--- 

ps: On @bouvyd request I have increased the padding on mobile.

2023-08-29 06:19 UTC, Brieuc-brd requested changes
I have a last comment below, for the rest LGTM 🙂

2023-08-29 06:19 UTC, Brieuc-brd commented on addons/web/static/src/search/search_panel/search_panel.xml
> +    <div class="o_search_panel flex-grow-0 flex-shrink-0 pb-5 h-100 bg-view overflow-auto"
If this line is entirely refactored then `h-100` should be before `pb-5` 🙂

2023-08-30 06:36 UTC, Brieuc-brd approved these changes

2023-09-05 08:48 UTC, pparidans approved these changes
LGTM :+1: 
@robodoo r+

2023-09-08 10:45 UTC, closed without merging