[IMP] sale_product_configurator: redesign of the modal
odoo/odoo pull request #133056
Opened 2023-08-24 15:17 UTC by anso-odoo

This commit 
- Cleans and optimize the SCSS 
- Improves the layout and the spacing of the existing modal
- Improves the input's style (`.o_input`, better pills)
- Sets a fixed height to the modal so it doesn't grow/shrink when
fields are shown/hidden

| Before | After |
|--------|--------|
| <img width="1002" alt="Screenshot 2023-08-25 at 11 24 46" src="https://github.com/odoo/odoo/assets/110090660/f10a8a67-c4bf-4ccc-8172-4e08a5672273"> | <img width="992" alt="Screenshot 2023-10-13 at 09 39 45" src="https://github.com/odoo/odoo/assets/110090660/ca714b18-b152-4002-a6b9-06b392b5986a"> |

task-3289240
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-28 09:29 UTC, anso-odoo commented
@stefanorigano Hello, can you have a look at this PR please ? Thanks !

2023-09-01 14:05 UTC, stefanorigano requested changes
Hello @anso-odoo , thanks 👋
Sore preliminary remarks in the code

2023-09-04 07:13 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/product/product.xml
> +            <div t-if="!this.props.optional" class="input-group justify-content-end flex-nowrap border-0">
those are leftovers, will remove them :)

2023-09-04 07:20 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/badge_extra_price/badge_extra_price.xml
> +        <span class="badge ms-1 ps-1 bg-100 rounded-pill">
I used a text-bg-info instead, I think it makes more sense than success as it's literally an "info" about the price 👍

2023-09-04 09:11 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/product_list/product_list.xml
> +                        <span class="label">Quantity</span>
It's leftovers from initial implementation, will remove that as it's useless 👍

2023-09-13 08:26 UTC, chevalierv commented on addons/sale_product_configurator/static/src/js/badge_extra_price/badge_extra_price.xml
> +            <span t-out="this.props.price > 0 ? '+' : '-'" class="o_product_badge_extra_price me-1"/>
Why do you keep the class if you remove the SCSS associated with it?
```suggestion
            <span t-out="this.props.price > 0 ? '+' : '-'" class="me-1"/>
```

2023-09-13 08:26 UTC, chevalierv commented on addons/sale_product_configurator/static/src/js/product/product.xml
> +            <div class="o_sale_product_configurator_name mb-3 text-break">
same question 
```suggestion
            <div class="mb-3 text-break">
```

2023-10-05 12:52 UTC, anso-odoo commented
@stefanorigano Hello, can you have a second look at this when you have time pls ? Ty !

2023-10-06 08:39 UTC, stefanorigano requested changes
@anso-odoo , almost there, courage 💪

2023-10-06 08:39 UTC, stefanorigano commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.scss
> +.o_sale_product_configurator_ptav_pills.active label{
```suggestion
.o_sale_product_configurator_ptav_pills.active label {
```

2023-10-06 08:39 UTC, stefanorigano commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.scss
> +    $-btn-secondary-design: map-get($o-btns-bs-override, "secondary");
Missing new line after variables definition:
```suggestion
    $-btn-secondary-design: map-get($o-btns-bs-override, "secondary");
    
```

2023-10-06 09:41 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
The input shouldn't disappear but should appear disabled
Not sure how we manage the disabled input states in the backend. It does nothing with only `o_input` and a `disabled` attribute so I tried to use a `form-control` + `disabled` but then it adds a solid background.

2023-10-09 10:20 UTC, stefanorigano commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
Normally we hide fields that are not editable.

2023-10-10 08:28 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
@dalaOdoo Hi, please can you check this comment 
Considering hiding the disabled inputs is the default behaviour in the back-end, i'm resetting to the previous behaviour. Also added a fixed height to the modal if there is at least an optional product so it's doesn't grow/shrink when we show/hide fields. Can you have a look on runbot please ? 
Thanks

2023-10-10 08:34 UTC, dalaOdoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
@anso-odoo I'll test it again when it is built.
@stefanorigano My concern is the flickering when selecting "custom" as we will have to display the input. For me the input is part of "custom" choice and so it is not a problem displaying it even if custom is not selected

2023-10-10 08:39 UTC, dalaOdoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
@anso-odoo still not fan but I'll not block for this

2023-10-12 15:59 UTC, dalaOdoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
Conversely, if it is the only thing that is blocking this PR I thing we should just keep the version that is working (visible and disabled ?) and  move on. 
This should not be considered as blocking, don't waste time now on nitpicking comment.

CC @anso-odoo @stefanorigano

2023-10-13 10:38 UTC, anso-odoo commented on addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
> +                    t-attf-class="o_input #{!isSelectedPTAVCustom() ? 'opacity-50' : ''}"
After discussion with @dalaOdoo, we will continue with the default system of hiding disabled fields
I'm marking this PR as ready for review @chevalierv

2023-10-24 13:32 UTC, Demesmaeker commented
> @stefanorigano The tours are currently broken but @chevalierv is having a look to fix them 👍

Hello, tours should be fixed now ^^
Have a nice day!

cc: @chevalierv

2023-10-24 14:30 UTC, Feyensv commented
Still red :eyes:

@robodoo delegate=chevalierv

2023-10-24 14:31 UTC, Demesmaeker commented
Yes, just noticed it too xD I forgot event with the product configurator, incoming =]

2023-10-25 12:38 UTC, anso-odoo commented
Hey @chevalierv, looks like it's all 🟢 👍

2023-10-26 12:07 UTC, chevalierv commented
@robodoo r+

2023-10-26 12:15 UTC, chevalierv commented
@robodoo r-

2023-10-26 15:12 UTC, chevalierv commented
@robodoo r+

2023-10-27 04:05 UTC, closed without merging

2023-10-27 07:52 UTC, vava-odoo commented
Hello @anso-odoo 
Could you backport the commit to 17.0? This PR was merged after the freeze.
Thanks!

2023-10-27 11:25 UTC, AntoineVDV commented
Backported with https://github.com/odoo/odoo/pull/140096