[FIX] account: remove deleted attachment data from json
odoo/odoo pull request #133012
Opened 2023-08-24 11:56 UTC by aktr-odoo

The traceback arises when a user deletes an attachment that the referenced in the `account.move.send` model's `mail_attachments_widget` field, and subsequently, the cron uses `mail_attachments_widget` to send invoices.

Steps to produce:
- Install account.
- Open Invoicing > open any invoice > click on SEND & PRINT > click on SAVE.
- Add an attachment > refresh the page.
- Go to attachments > delete the attachment which you have uploaded.
- Let the cron `Send invoices automatically ` run automatically.

See traceback
```
Traceback (most recent call last):
  File "/home/odoo/odoo/community/odoo/api.py", line 959, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 413

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/community/odoo/fields.py", line 1158, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/odoo/community/odoo/api.py", line 966, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.attachment(413,).res_model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/community/odoo/addons/base/models/ir_cron.py", line 373, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/odoo/odoo/community/odoo/addons/base/models/ir_actions.py", line 688, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/odoo/community/odoo/addons/base/models/ir_actions.py", line 558, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "/home/odoo/odoo/community/odoo/tools/safe_eval.py", line 362, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(269,)", line 1, in <module>
  File "/home/odoo/odoo/community/addons/account/models/account_move.py", line 4069, in _cron_account_move_send
    wizard.action_send_and_print(from_cron=True)
  File "/home/odoo/odoo/community/addons/account/wizard/account_move_send.py", line 553, in action_send_and_print
    self._hook_if_success(success, from_cron=from_cron, allow_fallback_pdf=allow_fallback_pdf)
  File "/home/odoo/odoo/community/addons/snailmail_account/wizard/account_move_send.py", line 66, in _hook_if_success
    super()._hook_if_success(moves_data, from_cron=from_cron, allow_fallback_pdf=allow_fallback_pdf)
  File "/home/odoo/odoo/community/addons/account/wizard/account_move_send.py", line 404, in _hook_if_success
    self._send_mails(moves_data)
  File "/home/odoo/odoo/community/addons/account/wizard/account_move_send.py", line 469, in _send_mails
    self._send_mail(
  File "/home/odoo/odoo/community/addons/account/wizard/account_move_send.py", line 411, in _send_mail
    move\
  File "/home/odoo/odoo/community/addons/mail/models/mail_thread.py", line 2054, in message_post
    self._process_attachments_for_post(attachments, attachment_ids, msg_values)
  File "/home/odoo/odoo/community/addons/mail/models/mail_thread.py", line 2137, in _process_attachments_for_post
    filtered_attachment_ids = self.env['ir.attachment'].sudo().browse(attachment_ids).filtered(
  File "/home/odoo/odoo/community/odoo/models.py", line 5471, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/odoo/community/odoo/models.py", line 5471, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/odoo/community/addons/mail/models/mail_thread.py", line 2138, in <lambda>
    lambda a: a.res_model == 'mail.compose.message' and a.create_uid.id == self._uid)
  File "/home/odoo/odoo/community/odoo/fields.py", line 1190, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: ir.attachment(413,), User: 1)
```

A `mail_attachments_widget` is a `JSON`storable field of the `account.move.send` model. `mail_attachments_widget` carries data like the attachment's ID, name, and mime type.

This commit removes the JSON which carries the data of deleted the attachment.

Sentry-4315708399

2023-08-24 11:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133012).

2023-08-25 08:24 UTC, yelizariev requested changes
You should filter out the deleted attachments somewhere else. The way it's implemented now is not good.

Also, you have to explain why it's ok to ignore deleted attachments. Maybe we should raise UserError instead?

2023-08-25 08:24 UTC, yelizariev commented on addons/account/wizard/account_move_send.py
> +                self.mail_attachments_widget = attachments_to
The method name is `_get_mail_params`, so it's not supposed to make changes in `self`

2023-08-28 12:39 UTC, aktr-odoo commented
Hello @yelizariev, 

The requested changes have been made.

The reason for not using `UserError` is that this issue originates from Cron. Thus, we cannot raise a `UserError` in this context.

Please let me know if there's anything else I can assist you with

2023-08-29 07:33 UTC, aktr-odoo commented
Hello @yelizariev, 

The requested changes have been made.

2023-08-29 09:09 UTC, william-andre reviewed
What about just adding
```python
# discard attachments that have been deleted before the cron runs
mail_params['attachment_ids'] = self.env['ir.attachment'].browse(mail_params['attachment_ids']).exists().ids
```
after
https://github.com/odoo/odoo/blob/857892a216535320660df4db540b1872e17a7756/addons/account/wizard/account_move_send.py#L463

2023-08-29 13:10 UTC, aktr-odoo commented
Hello @william-andre,

The requested changes have been implemented.

This fix will work perfectly for `saas-16.2`, but it won't work for `saas-16.3`.

The reason is as follows:

We are fixing this issue by updating the `attachment_ids` that are returned by the `_get_mail_params` function.

In `saas-16.2`, the `_get_mail_params` function returns a simple list of IDs.

https://github.com/odoo/odoo/blob/57a32afb534f18022d632b03a39a316bce2817ab/addons/account/wizard/account_move_send.py#L434-L442

However, in `saas-16.3`, the function `_get_mail_params` returns `mail_attachments`, which is a list of tuples containing attachment information, such as name and raw, obtained from `seen_attachment_ids`.

https://github.com/odoo/odoo/blob/5a8f95f8bfe0b9082abd30093502fd9a1513e133/addons/account/wizard/account_move_send.py#L441-L451

The `seen_attachment_ids` set is prepared using `self.mail_attachments_widget`.

https://github.com/odoo/odoo/blob/5a8f95f8bfe0b9082abd30093502fd9a1513e133/addons/account/wizard/account_move_send.py#L432-L439

However, we have not removed deleted attachment `JSON` from `self.mail_attachments_widget`. This oversight will lead to errors when preparing `mail_attachments`.

Our fix involves updating the data returned by the `_get_mail_params` function.

In `saas-16.3`, the `_get_mail_params` function itself will trigger an error.

2023-08-29 13:59 UTC, william-andre approved these changes
@robodoo r+

2023-08-29 16:56 UTC, closed without merging