[IMP] l10n_us,account_avatax: AvaTax option available only on l10n_us and install if checked
odoo/odoo pull request #133353
Opened 2023-08-28 13:52 UTC by yvsg-odoo

Description of the issue/feature this PR addresses:
AvaTax setting is always available for taxes, but this settings only makes sense for US. Also the module needs to be installed when the option is marked.

Current behavior before PR:
AvaTax setting always available in the settings for taxes.
AvaTax module does not install when the setting is checked

Desired behavior after PR is merged:
AvaTax setting should be visible if and only if l10n_us is installed.
AvaTax setting should install account_avatax module if checked

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-28 13:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133353).

2023-09-13 07:33 UTC, rugo-odoo requested changes
Good job, LGTM

2023-09-13 07:34 UTC, rugo-odoo requested changes

2023-09-13 07:34 UTC, rugo-odoo commented on addons/l10n_us/models/res_config_settings.py
> +# -*- coding: utf-8 -*-
Don't need that on master anymore.

2023-09-14 14:57 UTC, qdp-odoo commented
apparently, avatax is also used in Brazil, and could potentially be used everywhere in the world. So instead of adding that field in the setting to install the module, we gonna install it automatically for US and BR.

This has to be done in account/__init__.py

thx

2023-09-15 08:27 UTC, yvsg-odoo commented
@qdp-odoo and for now, should we leave the option to install the module in the settings visible to other countries?

2023-10-09 07:11 UTC, qdp-odoo commented
superseeded by https://github.com/odoo/odoo/pull/136490

2023-10-09 07:11 UTC, closed without merging