[IMP] sale_ebay: currency symbol editing without debug mode
odoo/odoo pull request #133554
Opened 2023-08-30 07:00 UTC by Megaaaaaa

Description of the issue/feature this PR addresses:

Prior to this, when multiple currencies with the same symbol where to appear in a same document or be sent from a country to another with the same currency symbol, the only information the recipient had was the currency symbol leading to lack of clarity.

Desired behavior after PR is merged:

This set of two PR has for objective to give the user the possibility to edit the symbol curency that is displayed everywhere so that if he feels like the documents and views are lacking clarity, he can improve it.

This was already an option before but only when the debug mode was active.

This commit has the purpose of moving the currency symbol option out of the debug mode section and put it in the right column of the currency form view.

Adding this, the "Symbol" option is moved out of the debug mode.

task-3484335

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-30 07:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133554).

2023-09-08 09:58 UTC, malb-odoo requested changes
LGTM :smile:  (oopps wrong button ahah)

2023-09-08 09:59 UTC, malb-odoo approved these changes

2023-09-11 11:46 UTC, qdp-odoo commented
@robodoo r+

2023-09-11 17:35 UTC, closed without merging