[IMP] website: theme configurator, review size/ratio
odoo/odoo pull request #133523
Opened 2023-08-29 15:42 UTC by mano-odoo

The 3 proposed themes were too tall making them display an overwhelming amount of information.

This commit make them use the page view width to scale their height it makes it less likely to get a vertical scroll in the page.

task-2702154

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-29 15:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133523).

2023-10-10 10:50 UTC, Brieuc-brd approved these changes
LGTM 👍

2023-10-22 12:40 UTC, stefanorigano reviewed
Hello @mano-odoo , thanks 👍 

Landscape previews do streamline the design indeed; the screen is cleaner, less crowded.

Hovering a preview to see more, though, took too much time and the amount of elements on screen was always very low.

I rebased your branch and pushed an adaptation on top that resize the preview on hover.
 @pierre-pde , what do you think? I'm not a big fan of previews covering the title, but it's the expected behavior I think 

cc. @Brieuc-brd 


https://github.com/odoo/odoo/assets/8558351/53bc6e52-0e82-4be5-9594-412855b427b5

2023-10-23 09:21 UTC, pierre-pde commented
@stefanorigano , sorry but I don't like the new version...
1. I think the preview before hover don't show enough content. 
We should see at least 3-4 building block per website. not 1-2... https://bit.ly/3Fu6Tnt 
2. I don't like the huge animation on hover.
3. I think the "click to select" is not visible anymore.

I thought the task was just to "wider" the content based on your mockup:
https://www.odoo.com/web/image/31532822?filename=themes_preview.png&unique=7f211692a7a9c89ea04c856e987889781c491d52

cc @qsm-odoo

2023-10-23 10:17 UTC, qsm-odoo commented
You ping me so I'll answer: I like both version (based on the mockup/video here, not tested live), so as you all wish :smile:

2024-01-09 14:48 UTC, stefanorigano requested changes
In-person meeting notes:

-   simpler layout implementation based on flex and percentages
-   in order to handle unpredictable card size (container-fluid), get the actual svg's height `onmouseover`.

Thanks 💪

2024-10-14 14:27 UTC, closed without merging