[14.0][PERF] reconcile invoice match
odoo/odoo pull request #133690
Opened 2023-08-30 20:10 UTC by mt-software-de

Backport from version 16.0 of _get_default_amls_matching_domain

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-30 20:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133690).

2023-09-05 09:46 UTC, clbr-odoo commented on addons/account/models/account_reconcile_model.py
> +            AND (account.internal_type not in ('receivable', 'payable') OR aml.payment_id is null)
-- Special domain for payments.

2023-09-05 11:17 UTC, clbr-odoo approved these changes
Hello, thank you for your PR, we can indeed backport that change !

2023-09-05 11:22 UTC, clbr-odoo commented
@mt-software-de May I just ask you to rename your commit title message with a [FIX] instead of [PERF], as PERF is not a valid tag of our guidelines :)
https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#tag-and-module-name

2023-09-05 11:24 UTC, mt-software-de commented
> @mt-software-de May I just ask you to rename your commit title message with a [FIX] instead of [PERF], as PERF is not a valid tag of our guidelines :) https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#tag-and-module-name

of course, done

2023-09-05 11:37 UTC, clbr-odoo commented
@fw-bot up to saas-15.2

2023-09-06 09:39 UTC, oco-odoo requested changes
Also, your commit message should give the "why", not the "what". Quickly explain that it improves the perf and why.

2023-09-06 09:39 UTC, oco-odoo commented
@fw-bot up to saas-15.2

Non mais

2023-09-06 12:02 UTC, oco-odoo approved these changes
@robodoo r+

Thanks :)

2023-09-06 13:08 UTC, closed without merging