[FIX] web: reintroduce CSS variables for navbar entries
odoo/odoo pull request #133712
Opened 2023-08-31 08:53 UTC by chgo-odoo

This commit aims to reintroduce CSS variables to handle the different states of our navbar entries.

Recently, the way we handle the navbar entries changed. Previously, we used to set CSS variables in Community, which would allow us to control the color of ours nav entries at every state.

On the Enteprise side, this would allow us to use the different colors we use for these buttons and style them differently

This approach was also very helpful because we could override these CSS variables once again to handle the colors of the Studio navbar elements.

Recently, the approach used to control these elements changed :

- On Community, we make use of CSS variables ;
- On Enterprise, we use the Bootstrap `btn-light` class.

Using `btn-light` was a very good approach to ensure that no issues would appears on our buttons and also to reduce the amount of code needed, but unfortunately, using `btn-light` directly affects Studio, causing contrast issues. It was also a bit weird to have CSS variables + Bootstrap classes being set at the same time.

To fix these issues, we reintroduce CSS variables in Enterprise and Studio, to fully control the color of our elements and ensure everything is readable. Most of these variables are defined in Community, inside the `navbar.scss` file, and we simply override them in Enterprise and Studio.

Requires : #[43857](https://github.com/odoo/enterprise/pull/43857)

task-3418936
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-31 08:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133712).

2023-09-14 13:47 UTC, Brieuc-brd requested changes
@chgo-odoo 👋  Some notes :)

2023-09-14 14:41 UTC, chgo-odoo commented
Thanks @Brieuc-brd 👌

Changes done, could you double check?

2023-09-15 09:36 UTC, Brieuc-brd commented on addons/web/static/src/webclient/navbar/navbar.scss
> +            border: $border-width solid transparent;
There's a trailing space before the property.
There are plugins on VS Code that can help you to find and remove these :)

2023-09-20 10:51 UTC, stefanorigano requested changes

2023-09-20 10:51 UTC, stefanorigano commented on addons/web/static/src/webclient/navbar/navbar.scss
> +    --NavBar-entry-color--active: #{$o-white};
I don't understand this :/
We have a `$o-navbar-entry-color--active` **SCSS** variable that could be used as default/fallback.
I think we should remove this line and, wherever is needed, do something like:

```scss
color: var(--NavBar-entry-color--active, #{$o-navbar-entry-color--active}
```

2023-09-20 10:51 UTC, stefanorigano commented on addons/web/static/src/webclient/navbar/navbar.scss
> +    --NavBar-entry-backgroundColor--hover: #{$o-navbar-entry-bg--hover};
The same here (read my prev. message)

2023-09-20 12:35 UTC, stefanorigano approved these changes
LGTM 👍

2023-09-20 14:32 UTC, Brieuc-brd approved these changes

2023-09-26 07:48 UTC, chgo-odoo commented
Hello @aab-odoo 👋

Just rebased and solve the conflicts in [the Enterprise counterpart of this PR](https://github.com/odoo/enterprise/pull/43857), could you have a look at it and eventually r+ ?

Thanks 👌

2023-09-26 07:55 UTC, aab-odoo commented
robodoo delegate=stefanorigano

2023-09-26 09:08 UTC, stefanorigano commented
@robodoo r+

2023-09-26 12:28 UTC, closed without merging