[IMP] account_reports: add date options for tax periods
odoo/odoo pull request #133715
Opened 2023-08-31 09:01 UTC by dylankiss

Currently the tax report always opens the previous month by default. Since tax periods are not always months, it makes much more sense to open the previous "tax period" (whatever length it has) when opening the tax report.

In order to allow that, this commit introduces a "This Tax Period" and "Previous Tax Period" option for reports and sets the default period for the tax report to "Previous Tax Period". The rest of the functionality is done in the related enterprise commit.

[task-3481913](https://www.odoo.com/web#id=3481913&cids=1&menu_id=4720&action=333&active_id=967&model=project.task&view_type=form)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-08-31 09:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/133715).

2023-09-15 11:06 UTC, oco-odoo requested changes
Just a small detail: you commit message should rather be [IMP] account  ; account_reports is enterprise ;)

2023-09-15 11:15 UTC, dylankiss commented
> Just a small detail: you commit message should rather be [IMP] account ; account_reports is enterprise ;)

@oco-odoo Oops, nice catch 😄 I changed the commit message.

2023-09-15 12:39 UTC, oco-odoo approved these changes
@robodoo r+

2023-09-15 14:01 UTC, robodoo commented
@dylankiss @oco-odoo linked pull request(s) odoo/enterprise#46601 not ready. Linked PRs are not staged until all of them are ready.

2023-09-15 17:41 UTC, closed without merging