[IMP] pos_restaurant: build_line_resume & computeChanges resume datasets now are inheritables
odoo/odoo pull request #134031
Opened 2023-09-01 16:26 UTC by hugho-ad

With this commits the data sets about resume of the orderline now are inheritable, we are  introducing new functions that will be the ones that returns the data structure of the lines resume; That info could be easily extended.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-01 16:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134031).

2023-09-04 15:59 UTC, hugho-ad commented
Hello @trj-odoo 

could you please review?

2023-09-07 18:09 UTC, hugho-ad commented
Hello @caburj 
could you please review?

2023-09-08 15:09 UTC, pedrambiria requested changes
Hello,

For naming variables and functions, please follow the camelCase convention. Additionally, prefer using 'let' and 'const' over 'var' for variable declarations.

Thank you!

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +    get_product_resume_key: function(){
```suggestion
    getProductResumeKey: function(){
```

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +    get_line_resume: function(){
```suggestion
    getLineResume: function(){
```

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +    get_resume_info: function(pid, curr, note, qty){
```suggestion
    getResumeInfo: function(pid, curr, note, qty){
```

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +            var p_key = line.get_product_resume_key()
```suggestion
            const p_key = line.get_product_resume_key()
```

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +            var product_resume = p_key in resume ? resume[p_key] : line.get_line_resume();
```suggestion
            let product_resume = p_key in resume ? resume[p_key] : line.get_line_resume();
```

2023-09-08 15:09 UTC, pedrambiria commented on addons/pos_restaurant/static/src/js/multiprint.js
> +                    add.push(add_resume);
```suggestion
                    add.push(this.get_resume_info(pid, curr, note, curr['qties'][note]));
```

2023-09-11 07:49 UTC, pedrambiria approved these changes
LGTM, @caburj could you please review it?

2023-09-14 06:00 UTC, hugho-ad commented
Hello @caburj 

friendly reminder 
could you please review it please?

2023-09-15 13:35 UTC, caburj commented
robodoo delegate=pedrambiria

Hi @pedrambiria. I'll let you handle this.

2023-09-18 13:40 UTC, pedrambiria commented
robodoo r+

2023-09-18 15:51 UTC, closed without merging