[FIX] website: error when saving page without URL
odoo/odoo pull request #134072
Opened 2023-09-03 03:30 UTC by luisg123v

Before this commit, when trying to save a website page without an URL set, the following error was raised:

    AttributeError: 'bool' object has no attribute 'startswith'

The above is because the URL is automatically formatted to add a leading slash when it's missing, but it didn't handled properly empty URLs.

This commit ensures such case is handled properly.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-03 03:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134072).

2023-09-03 03:36 UTC, luisg123v commented
Hi @desdelinux,

Could you review, please?

Regards,

CC @moylop260 @nhomar

2023-09-04 15:06 UTC, rdeodoo requested changes
I don't think we want to introduce this.
What is the use case for a page without an URL? It should have been a `required` field in the first place actually.
We have some safety net in the code here and there for pages without url but.. It's still a door for errors. See https://github.com/odoo/odoo/commit/f75ec6131eff9165b06d42d27a49dd756387f4a0

I created an [internal task](https://www.odoo.com/web#id=3443119&menu_id=4720&cids=1&action=333&active_id=974&model=project.task&view_type=form) weeks ago to make this required in Odoo 17.

In Odoo 16, the error is correctly handled and let you create non url pages tho..
I don't see the point about allowing people to removing URL in the `write()`, it will do no good but potentially cause some problems. I'd rather have it crashing and preventing it.
I'd not touch Odoo 15.0.

Let me know what you think.

2023-09-04 15:27 UTC, luisg123v commented
Hi @rdeodoo,

I though the URL field not being required was intentional. If the page is not publised, an empty URL is harmless AFAIK (it would serve as a draft page).

But I agree, so I'm closing this PR.

Regards,

2023-09-04 15:27 UTC, closed without merging