[FIX] models: groupby date for pivot view
odoo/odoo pull request #134087
Opened 2023-09-04 08:24 UTC by sauc-odoo

When user tries to apply any Group By as date or datetime in the pivot view and the column value of pivot view is also a date or dateime, the traceback will be generated.

To reproduce the issue:
- Install Point of Sale
- Go to 'Reporting' and click on 'Orders'
- Select pivot view
- Go to Group By and select 'Order Date' same as column value
- Issue can be produce in the same way in other modules, such as - 'sale', 'sale_subscription', 'crm', 'planning', 'hr_expense' etc.

Error: 
```
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "odoo/models.py", line 2593, in read_group
    self._read_group_format_result(rows_dict, lazy_groupby)
  File "odoo/models.py", line 2428, in _read_group_format_result
    range_end = value + interval
TypeError: can only concatenate str (not "relativedelta") to str
```

The issue is occurring because we are getting duplicate values in groupby like ['date:month', 'date:month'] while calling orm method over here - https://github.com/odoo/odoo/blob/6cf3b617d8082df5820283d07e6623b7684cefdd/addons/web/static/src/core/orm_service.js#L143

To solve this issue groupby has been passed into a Set so that no duplicate values occurs in groupby.

sentry-4262719543

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-04 08:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134087).

2023-09-12 09:18 UTC, sauc-odoo commented
Hello @odoo/sentry_reviewers 
Kindly review this PR.
Thanks.

2023-09-12 13:34 UTC, abz-odoo requested changes
I'm not sure about the fix I think you have to understand why there are duplicates, and not only remove them.
In any case this fix needs a js test too.
Thanks

2023-09-14 07:00 UTC, sauc-odoo commented
> I'm not sure about the fix I think you have to understand why there are duplicates, and not only remove them. In any case this fix needs a js test too. Thanks

Hello @abz-odoo 
Test case has been added, please check it.
Thanks!

2023-09-25 06:10 UTC, sauc-odoo commented
Hello @Iucapad 
Kindly review this PR.
Thanks!!

2023-10-04 09:08 UTC, abz-odoo commented
@Iucapad @BastienFafchamps

2023-10-04 09:41 UTC, Iucapad approved these changes
Thanks for the fix.
FYI we also have a `unique` function available in `.../core/utils/arrays.js`

2023-10-04 09:41 UTC, Iucapad commented
@robodoo r+

2023-10-04 10:49 UTC, closed without merging