[FIX] website: viewref should return singleton
odoo/odoo pull request #134280
Opened 2023-09-05 09:56 UTC by royleviindoo

Because of f7df35540b8404a14e8d29af80b8e8642a4c1bdb and since the key of an ir.ui.view cannot be unique (multiwebsite), duplicating views made several parts of Odoo crash (at _view_obj method).

https://github.com/odoo/odoo/blob/16.0/addons/website/models/ir_ui_view.py#L290-L292

After this commit, we limit to one the views that are returned from viewref with their key.

Responsibility is given to the user to change the priority and/or the key in order to predict which view will be taken.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-05 09:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134280).

2023-09-06 01:48 UTC, royleviindoo commented
Hi @rdeodoo , can you review this PR, thank

2023-09-07 15:54 UTC, rdeodoo requested changes
Do you have a step to reproduce?
It seems like this is about making the code work if you manually mess around in the backend, duplicating views, no?
Or is there a legit business flow leading to such a situation?
If that's only about manually duplicating views in the backend, it's not something we want to support.

Other than that, if such a patch should exist, it should be part of the `filter_duplicate`, isn't it?

2023-09-07 16:00 UTC, royleviindoo commented
> Do you have a step to reproduce? It seems like this is about making the code work if you manually mess around in the backend, duplicating views, no? Or is there a legit business flow leading to such a situation? If that's only about manually duplicating views in the backend, it's not something we want to support.
> 
> Other than that, if such a patch should exist, it should be part of the `filter_duplicate`, isn't it?

Hi, thanks for your response. You're right, only about manually duplicating views in the backend, but why not support? I see that the method `viewref` always returns a view (`view = views.filter_duplicate()` -- the variable name does not have -s).

2023-09-07 16:31 UTC, rdeodoo commented
I am not fully against supporting it, it's just that it would be a very terrible risk/reward ratio:
- Pro/Reward: Close to zero, just supporting case of manual messing around with views in the backend in debug mode 
- Con/Risk: You never know until it breaks later in a case we didn't think of during review/merge

I don't see a reason to fix `viewref`, that would be fixing the consequence and not the root cause. The root cause is that `filter_duplicate` is not correctly filtering duplicates, if a fix should be done, it's there.
And the fix would have to be be sure to exclude the one with higher ID (the manually cloned one) and not the other one.

All in all, it's not something I will merge myself, I think I would prefer the system to crash following the manual error than having the system working, without knowing if it really worked correctly: what if it kept the wrong view?
Eg, you duplicate one of the frontend qweb view, you then go in edit mode days later, you do some options changes, which add some inherit views under the duplicated view you created, then you notice the duplicate and remove it, you actually killed your changes.

I am just thinking around at this point. But there is many ways to break your DB by playing with views in the backend, we generally don't try to handle those cases.

I will have to pass on this one.

2023-10-05 06:30 UTC, closed without merging