[FIX] Sales: FIxes Unwanted Validation Error in Discount & Loyalty
odoo/odoo pull request #134261
Opened 2023-09-05 08:33 UTC by nikj-odoo

Before this PR, users encountered an issue when attempting to add rules to Discount and Loyalty programs. An undesired validation message would surface, preventing them from saving their changes.

In this PR, the extraneous validation has been eliminated, enabling users to successfully save their rules.

Task ID: 3487478

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-05 08:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134261).

2023-09-15 07:43 UTC, vava-odoo requested changes
Hi @nikj-odoo 
This field is required for a good reason, I don't think we'll drop that because of a validation error somewhere.
Could you please look for an other solution?
Thanks!

2023-10-19 09:58 UTC, Demesmaeker approved these changes
Hello :duck: 

Nice job! lgtm

2023-10-23 14:09 UTC, Feyensv approved these changes
@robodoo r+ squash

2023-10-23 14:09 UTC, robodoo commented
Merge method set to squash.

2023-10-23 21:05 UTC, closed without merging