[IMP] l10n_{ec,ar,pe,cl,mx}
odoo/odoo pull request #134617
Opened 2023-09-07 06:43 UTC by malb-odoo

This commit aims at changing some tooltip, labels and changing the place of some
 fields. Also adding some invisible tags to avoid the fields to be displayed on
 other companies

 task: 3270458

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-07 06:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/134617).

2023-10-10 15:08 UTC, gawa-odoo reviewed
Didn't check the po/pot :smiley:

2023-10-11 07:30 UTC, gawa-odoo commented on addons/l10n_ar/static/src/js/tours/account.js
By the way, this works if you only install l10n_ar because of this https://github.com/odoo/odoo/blob/master/addons/account/tests/test_tour.py#L34
If you try to run the tour test in the interface, with only l10n_ar installed, it will fail. Is the PO aware of this? (I know there were some discussions about making them work in localizations, but I don't know the conclusion)

2023-10-11 07:38 UTC, malb-odoo commented on addons/l10n_ar/static/src/js/tours/account.js
I have talk to Christophe about it, since the field is now hidden for all localisation except AR checking his presence in this tour is non sense so he told me i could remove it. About making tours for the localisation i think it's still an idea that need to be done but it would need time to put it in place

2023-10-11 09:33 UTC, malb-odoo commented on addons/l10n_ar/views/uom_uom_view.xml
> +                <field name="fiscal_country_codes" invisible="1"/>
It was not needed actually so just removed the diff

2023-10-12 09:38 UTC, gawa-odoo approved these changes
LGTM, small remarks in community left, but here, it looks good

2023-10-17 11:12 UTC, FlorianGilbert requested changes

2023-10-17 11:34 UTC, malb-odoo commented on addons/l10n_ar/models/account_journal.py
> +        help="Specify which type of system will be used to create the electronic invoice. This will depend on the type of invoice to be created",
That was what they give me as the tooltip in the document, but i can add it to be consistent

2023-10-18 07:31 UTC, FlorianGilbert requested changes
2 small comments for the indent.

2023-10-18 07:31 UTC, FlorianGilbert commented on addons/l10n_pe/models/account_tax.py
> +    )
The indent isn't totally correct, we have to do something like this:
```python
    l10n_pe_edi_tax_code = fields.Selection(
        [
            ('1000', 'IGV - General Sales Tax'),
            ('1016', 'IVAP - Tax on Sale Paddy Rice'),
            ('2000', 'ISC - Selective Excise Tax'),
            ('7152', 'ICBPER - Plastic bag tax'),
            ('9995', 'EXP - Exportation'),
            ('9996', 'GRA - Free'),
            ('9997', 'EXO - Exonerated'),
            ('9998', 'INA - Unaffected'),
            ('9999', 'OTHERS - Other taxes')
        ],
        string='Code',
        help="Peru: SUNAT tax code",
    )

2023-10-18 07:31 UTC, FlorianGilbert commented on addons/l10n_pe/models/account_tax.py
> +        ],
We have to do the same indent here :)

2023-10-19 11:11 UTC, FlorianGilbert approved these changes
@robodoo r+

2023-10-19 12:01 UTC, robodoo commented
@malb-odoo @FlorianGilbert linked pull request(s) odoo/upgrade#5266 not ready. Linked PRs are not staged until all of them are ready.

2023-10-19 12:01 UTC, robodoo commented
@malb-odoo @FlorianGilbert because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-10-19 12:12 UTC, FlorianGilbert commented
@robodoo rebase-ff

2023-10-19 12:13 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-20 12:40 UTC, closed without merging