[IMP] account: Better UX during account_accoutant_tour
odoo/odoo pull request #135187
Opened 2023-09-12 12:26 UTC by Megaaaaaa

Description of the issue/feature this commit addresses:

The current onboarding account tour is sometimes broken. The purpose of this commit is to fix it and make it run smoothly.

---

Desired behavior after the commit is merged :

This commit modifies the onboarding account tour to clarify the messages that are shown, add messages to certain steps and try to make it impossible for the user to be lost during its entierty.

Adding this improvement, the onboarding account tour better fills its purpose.

---

Enterprise PR : 

task-3375344

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-12 12:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/135187).

2023-09-22 12:23 UTC, malb-odoo requested changes
Small comment, nice work !

2023-09-22 12:23 UTC, malb-odoo commented on addons/account/wizard/account_tour_upload_bill.py
> +
useless difff :smile:

2023-09-22 12:23 UTC, malb-odoo commented on addons/account/wizard/account_tour_upload_bill.py
> +class AccountTourUploadBillEmailNoAlias(models.TransientModel):
i find it weird to add an empty class, can't we just add some logic in the xml template when there is no alias ?

2023-09-22 12:23 UTC, malb-odoo commented on addons/account/wizard/account_tour_upload_bill.xml
> +        </record>
With the previous comment all of that could be merge with the other template (i think)

2023-09-26 06:38 UTC, malb-odoo approved these changes
LGTM thx for the work ! (maybe the two if statement in `account_tour_upload_bill.py`could be onlined but we will lose readability so i think it's good like this)

2023-10-03 14:52 UTC, qdp-odoo commented
needs a rebase

2023-10-19 07:15 UTC, qdp-odoo commented
@robodoo r+

2023-10-19 13:21 UTC, closed without merging