[FIX] project: improve _get_all_subtasks performances
odoo/odoo pull request #135309
Opened 2023-09-13 12:26 UTC by huca-odoo

In the project.task model, the method _get_all_subtasks allows to get all the subtasks linked to a recordset (recursively). This method uses the method _get_subtask_ids_per_task_id that retrieves all subtasks ids for each task record in the recordset using a sql query to optimize performances (see odoo/odoo#117624).

This commit adds an additional WHERE clause in this request to avoid looking for subtasks in records that have no parent_id set. On top of that, a unit test is added for both methods.

task-3504339

2023-09-13 12:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/135309).

2023-09-20 08:01 UTC, MissingNoShiny reviewed
Thanks for your work, I left two small comments :slightly_smiling_face:

2023-10-03 08:11 UTC, auon-odoo requested changes
Thanks for your work!

2023-10-03 08:11 UTC, auon-odoo commented on addons/project/tests/test_project_subtasks.py
> +                self.assertEqual(set(subtask_ids), expected_result[parent_id])
```suggestion
        self.assertEqual(len(all_subtasks_by_task_id), 1, "The result should only contain one item: the common ancestor")
        for parent_id, subtask_ids in all_subtasks_by_task_id.items():
            self.assertEqual(parent_id, task.id, "The key should be the common ancestor")
            self.assertEqual(set(subtask_ids), set(all_subtasks.ids), "The value should be gnagnaproute")
```
? :thinking:

2023-10-03 09:28 UTC, huca-odoo commented on addons/project/tests/test_project_subtasks.py
> +                self.assertEqual(set(subtask_ids), expected_result[parent_id])
> ? 🤔

In this particular case yes

2023-10-03 10:28 UTC, huca-odoo commented
> Thanks for your work!

I've updated the code, thanks :slightly_smiling_face:

2023-10-03 12:39 UTC, auon-odoo approved these changes
Magnifico 👌

2023-10-17 08:27 UTC, xavierbol commented
robodoo r+

2023-10-17 10:27 UTC, closed without merging