[FIX] auth_oauth: raise badrequest on missing state
odoo/odoo pull request #135498
Opened 2023-09-14 13:29 UTC by aktr-odoo

When the user tries to log in with `odoo.com` or any other third-party app this traceback may appear.

See Traceback
```
KeyError: 'state'
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1851, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/auth_oauth/controllers/main.py", line 47, in wrapper
    return func(self, *a, **kw)
  File "addons/auth_oauth/controllers/main.py", line 125, in signin
    state = json.loads(kw['state'])
```

This commit will solve the above issue by raising the `BadRequest` if the `state` is not available in `kw`.

Sentry-4476285288

2023-09-14 13:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/135498).

2023-09-26 06:39 UTC, aktr-odoo commented
Hello @odoo/sentry_reviewers,
Can you review this PR.
Thanks!

2023-09-26 11:42 UTC, xmo-odoo requested changes
This change doesn't make sense: if `state` is missing, then you'll execute `json.loads(None)` which raises a `TypeError`. So this doesn't fix anything, it just trades a KeyError for a TypeError.

It also doesn't fix the latent `TypeError` if a non-json `state` is passed in.

2023-09-27 06:58 UTC, aktr-odoo commented
Hello @xmo-odoo 
I've implemented the requested changes. 
Additionally, here is the alternative approach.
```
try:
    state = json.loads(kw['state'])
except (json.decoder.JSONDecodeError, KeyError, TypeError):
    return BadRequest()
```
However, after careful consideration, I believe the updated code I've pushed offers more accurate error handling by ensuring that 'state' is a well-formed JSON string before parsing it. Please let me know your thoughts.

2023-09-27 08:51 UTC, aktr-odoo commented
Hello @xmo-odoo 
I have implemented the requested changes.

2025-02-10 06:38 UTC, robodoo commented
@aktr-odoo the target branch '14.0' has been disabled, you may want to close this PR.

2025-02-10 06:50 UTC, closed without merging