[IMP] website: enable to use special characters in a form
odoo/odoo pull request #135797
Opened 2023-09-18 13:21 UTC by loco-odoo

Before [1], the usage of some characters as field label inside a form led to a traceback. To solve the problem, [1] encoded the problematic characters. The problem is that the backslash character was not taken into account and still led to a traceback if it was used as a field label. [2] solved the problem by adding this special character in the list of the characters to encode. The goal of this commit is to use the already defined `encodeURIComponent()` function to encode the special characters in a form rather than encoding them "manually". By doing so, we are sure to not miss again a character that would break the form if it is used as a field label.

[1]: https://github.com/odoo/odoo/commit/ccaf4f1e52f10308ef507059316732c02ad6e6e4
[2]: https://github.com/odoo/odoo/commit/03f230a77c0d38b46944d45b4991f48e45b275dd

task-3510450

2023-09-18 13:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/135797).

2023-09-21 10:24 UTC, qsm-odoo requested changes

2023-09-21 10:24 UTC, qsm-odoo commented on addons/website/controllers/form.py
> +        data['custom'] = "\n".join([u"{} : {}".format(werkzeug.urls.url_unquote_plus(v[0]), v[1]) for v in custom_fields])
`encodeURIComponent` on the client side does not use the "plus" encoding, is that really ok decoding with it? Also are you sure you cannot decode on the client side?

2023-09-21 10:24 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_website_form/options.js
> +    _getEncodedName(name) {
You are in 15.0, you cannot delete/rename functions

2023-09-21 10:24 UTC, qsm-odoo commented on addons/website/static/tests/tours/website_form_editor.js
> +            trigger: `input[type="checkbox"][name="${getEncodedName('Checkbox 1')}"]`,
Mmh, annoying. Maybe `encodeURIComponent` is not the way to go :shrug: Space was not issue in the end, and did not need to be encoded... no other way?

2023-09-25 13:08 UTC, loco-odoo commented
@qsm-odoo , I adapted and rebased the PR :+1:

2023-10-02 08:21 UTC, loco-odoo commented
@qsm-odoo here is a rebased version of the PR :)

2023-10-09 07:44 UTC, loco-odoo commented
@qsm-odoo here is a rebased version of the PR :)

2023-11-15 12:06 UTC, loco-odoo commented
@qsm-odoo , here is a rebased version :)

2023-11-20 12:33 UTC, loco-odoo commented
@qsm-odoo , here is a rebased version :+1:

2023-11-27 14:49 UTC, loco-odoo commented
@qsm-odoo, here is a rebased version 👍

2023-12-11 10:23 UTC, loco-odoo commented
@qsm-odoo , here is a rebased version :+1:

2024-01-03 14:41 UTC, loco-odoo commented
@qsm-odoo , here is a rebased version :+1:

2024-04-17 12:30 UTC, qsm-odoo commented
@odoo/rd-security Security bypass needed here. I would not mind your opinion actually: does encoding some text value using `encodeURIComponent` client-side and decoding it server-side with `urllib.parse.unquote` seem right to you? Thanks :pray:

2024-04-18 16:13 UTC, qsm-odoo commented
> where the concerns of URI-encoding and those of CSS escaping don't match.

@loco-odoo Re-investigate with this in mind please :pray: Basically what it means in human terms is that since we don't want to encode URL parts, we should not use `encodeURIComponent` in the first place, even if it does work. Check again: `CSS.escape` should probably be the way client side let's see if it works, then you would not need `urlparse` server-side. Again make sure using that would be fully stable and keep existing forms fully working :pray:

2024-04-25 13:38 UTC, qsm-odoo approved these changes
@loco-odoo Thanks for your work. Good catch for the second commit and nice that you added a test :+1: 

I push-forced to review the comment you added in the first commit, to provide more explanation :+1: 

I also found another bug due to a special character :man_facepalming: I created a task for it: https://www.odoo.com/web#menu_id=4720&cids=1&action=5050&model=project.task&view_type=form&id=3893749
Let's not delay this because of it, let's merge :+1: 

@robodoo rebase-ff r+

2024-04-25 13:39 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-04-25 13:40 UTC, rdeodoo commented
What about creating a sub team in the website team in charge of everything related to website forms :D ?
It really does not seem straightforward, and has many behaviors and possibilities in website.

2024-04-25 15:24 UTC, qsm-odoo approved these changes
@robodoo r+

2024-04-25 19:59 UTC, closed without merging