[16.0][FIX] Check gift card prefix from nomenclature
odoo/odoo pull request #136187
Opened 2023-09-21 16:48 UTC by grindtildeath

The barcode nomenclature allows to define custom prefix for gift cards. e.g. the default nomenclature in demo data allows both 043 or 044 as prefix for rule of type coupon.

Therefore the hardcoded string with 044 doesn't allow to sell a gift card whose barcode does not start with this.

Instead of hardcoding the value, fetch it from the configuration and the nomenclature that is defined in the settings.

Steps to reproduce:
1. Activate Gift cards in the POS config settings
2. Set as Scan existing cards
3. Make sure default nomenclature is selected in the point of sale with 043 as prefix for coupons
4. Start a pos session
5. Select gift card product
6. Scan or enter a barcode beginning with 043

OPW-3499787

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-21 16:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136187).

2023-10-04 12:04 UTC, JuMiSanAr commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                let trimmedCodeValid = _.find(nomenclatureCodePatterns, function(pattern) {
```suggestion
                const trimmedCodeValid = _.find(nomenclatureCodePatterns, function(pattern) {
```
No need to make this a `let` variable if we're not going to reassign it later.

2023-10-23 15:11 UTC, grindtildeath commented
Hello @caburj , can we get this merged please? :pray:

2023-11-22 15:43 UTC, pedrambiria requested changes
Hello,

Thank you for your efforts on this. It's a great idea to leverage the barcode nomenclature for extracting the prefix instead of using a hardcoded one. However, there's no need to make an additional request for this information, as the barcode rules already exist in `this.env.barcode_reader.barcode_parser.nomenclature.rules`.

Please note that you can set the default nomenclature to GS1. In that case, you can find the coupon rule here: `this.env.barcode_reader.fallbackBarcodeParser.nomenclature.rules`.

Additionally, it's a good practice to handle errors gracefully, so please consider adding error handling for cases where fallbackBarcodeParser is missing or if there isn't any rule defined for the coupon.

Best regards,

2023-11-23 12:33 UTC, caburj commented
robodoo delegate=pedrambiria

2023-11-23 19:02 UTC, grindtildeath commented
@pedrambiria Thanks for your comment.

I reworked the PR to use one or the other parser in case it's undefined, and avoid the extra XMLRPC call.

About error handling, the default message "Please enter a valid gift card code" will be displayed in case there isn't any coupon rule found as `trimmedCodeValid` will be evaluated to False.

2023-12-07 13:56 UTC, pedrambiria commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                const barcodeParser = this.env.barcode_reader.barcode_parser || this.env.barcode_reader.fallbackBarcodeParser;
The rules might exist in either `barcode_parser` or `fallbackBarcodeParser`. To ensure comprehensive coverage, you can merge these rules. Keep in mind that `fallbackBarcodeParser` may be undefined.

2023-12-12 17:13 UTC, grindtildeath commented
@pedrambiria updated

2023-12-19 17:02 UTC, pedrambiria requested changes
Could you please merge all of the commits?

2023-12-19 17:02 UTC, pedrambiria commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                if (Object.hasOwn(this.env.barcode_reader, 'fallbackBarcodeParser')) {
```suggestion
                if (this.env.barcode_reader.fallbackBarcodeParser)) {
```

2023-12-19 17:02 UTC, pedrambiria commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                    nomenclatureRules.push(this.env.barcode_reader.fallbackBarcodeParser.nomenclature.rules);
```suggestion
                    nomenclatureRules.push(...this.env.barcode_reader.fallbackBarcodeParser.nomenclature.rules);
```

2023-12-19 17:02 UTC, pedrambiria commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                );
```suggestion
                const couponNomenclatureRules = _.filter(nomenclatureRules, function(rule) {
                    return rule.type == "coupon";
                });
```

2023-12-20 20:03 UTC, grindtildeath commented
@pedrambiria Thanks for the review. Suggestions applied, commits squashed and branch rebased on 16.0.

2023-12-21 14:29 UTC, pedrambiria commented on addons/pos_loyalty/static/src/js/ProductScreen.js
> +                );
Thanks, just one last thing:
```suggestion
                    return rule.type == "coupon";
                });
```

2024-01-22 15:38 UTC, grindtildeath commented
@pedrambiria Hello, can we please merge this now that I attended all the comments? :pray:

2024-01-24 13:24 UTC, pedrambiria approved these changes

2024-01-24 18:01 UTC, closed without merging

2024-03-01 07:45 UTC, Highcooley commented
@pedrambiria Can you please forwardport this fix to 17 and potentially master, since the issue still exists at least in 17. Thank you!

2024-03-07 14:12 UTC, pedrambiria commented
@grindtildeath Hello,
Could you please create the same pr in version 17?

2024-03-07 15:03 UTC, grindtildeath commented
@pedrambiria IMO it's part of our customer's support contract to have bugfixes done by Odoo... We already did invest a lot of time because Odoo support didn't provide any help and I don't have any more time to invest on this subject.

Can you please do the forward port?

2024-03-07 15:15 UTC, pedrambiria commented
@grindtildeath I asked you because you did it in this version. However, I can handle it myself, and in fact, it might even be more efficient for me to do so rather than reviewing. I apologize for any inconvenience you've experienced during the support process. Could you kindly provide me with your ticket number? I will personally take over and ensure your issue is resolved.

2024-03-07 16:50 UTC, grindtildeath commented
@pedrambiria No worries and thank you very much for taking care of it.

Support ticket was mentioned in PR description, but it was @Highcooley who handled it.