[FIX] account: validate sequence number for entries with hash enabled journals
odoo/odoo pull request #136292
Opened 2023-09-22 11:54 UTC by alsh-odoo

This traceback arises when the user gives `alphabets` or `special characters` 
in `prefix` or `suffix` for `Lock Posted Entries with Hash` enabled journal sequences.

To reproduce this issue:

1) Install `Accounting` and make sure developer mode is On 
2) Open `Accounting/Configuration/Journals`
3) Open the `Customer Invoices` record
4) Enable `Lock Posted Entries with Hash` in `Advance Settings 
5) Open `Sequences` from `Settings/Technical`
6) Open the `Customer invoices` sequence record
7) Give any alphabet to prefix or suffix like `INV-2023-` and save. 
8) create a new invoice with the `Customer Invoices` journal.

Error:
```
ValueError: invalid literal for int() with base 10: 'INV-2023-002'
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 34, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "home/odoo/src/enterprise/saas-16.4/account_accountant/models/account_move.py", line 70, in action_post
    res = super().action_post()
  File "addons/account/models/account_move.py", line 4014, in action_post
    other_moves._post(soft=False)
  File "home/odoo/src/enterprise/saas-16.4/account_asset/models/account_move.py", line 113, in _post
    posted = super()._post(soft)
  File "addons/l10n_sa/models/account_move.py", line 50, in _post
    res = super()._post(soft)
  File "home/odoo/src/enterprise/saas-16.4/account_reports/models/account_move.py", line 51, in _post
    return super()._post(soft)
  File "home/odoo/src/enterprise/saas-16.4/account_invoice_extract/models/account_invoice.py", line 248, in _post
    posted = super()._post(soft)
  File "addons/account_edi/models/account_move.py", line 240, in _post
    posted = super()._post(soft=soft)
  File "home/odoo/src/enterprise/saas-16.4/account_accountant/models/account_move.py", line 62, in _post
    posted = super()._post(soft)
  File "addons/account/models/account_move.py", line 3800, in _post
    to_post.write({
  File "home/odoo/src/enterprise/saas-16.4/documents_account/models/account_move.py", line 29, in write
    res = super().write(vals)
  File "addons/account/models/account_move.py", line 2501, in write
    'inalterable_hash': move._get_new_hash(new_number),
  File "addons/account/models/account_move.py", line 2966, in _get_new_hash
    ('secure_sequence_number', '=', int(secure_seq_number) - 1)])

```

[1] On the `_get_new_hash` method in `account.move`, `secure_seq_number` is
    is converted to an integer using the `int()` function.

[2] Here `secure_seq_number` is getting value from
    `journal_id.secure_sequence_id.next_by_id()`.

[3] In that `next_by_id()`, prefix and suffix are used to get sequence number.

When the user enabled `restrict_mode_hash_table` a new sequence is created.

In that sequence, when the user gives any alphabet or special character to a prefix or suffix. 
It leads to the above traceback, as the `int()` function is used to convert that sequence number
while creating invoice.

See:-

[1]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/addons/account/models/account_move.py#L2935-L2943

[2]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/addons/account/models/account_move.py#L2122-L2125

[3]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/odoo/addons/base/models/ir_sequence.py#L237-L238

After applying this commit will resolve the issue by validating prefix and suffix.

sentry-4477040897

2023-09-22 11:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136292).

2023-10-06 15:19 UTC, agr-odoo requested changes

2023-10-06 15:19 UTC, agr-odoo commented on addons/account/models/ir_sequence.py
> +            if any(seq.id == journal.secure_sequence_id.id and (not seq.next_by_id().strip().isdigit()) for journal in journal_ids):
* using `next_by_id` will actually consume the next identifier, we should just check if prefix and suffix are not digits 
* looping on journals is not really necessary. If in the search we add `('secure_sequence_id', 'in', self.ids)` then we could just check the retrieved journal_ids

2023-10-10 08:02 UTC, alsh-odoo commented
Hello @agr-odoo 

Changes are done.

Please review

2023-10-10 09:18 UTC, agr-odoo approved these changes
Looks good to me, thanks for your work

2023-10-30 13:48 UTC, clbr-odoo commented
Hello, 
Sorry for the delay of the review due to the freeze rush.
There is probably a misunderstanding between invoices sequences and the secured sequences. You are not supposed to modify the latter just like that, it's suspicious :slightly_smiling_face: 

CC: @william-andre

2023-11-20 10:27 UTC, closed without merging