[FIX] project: import records of project
odoo/odoo pull request #136374
Opened 2023-09-25 05:36 UTC by reka-odoo

When user import records of project and if it contains tags in the file,
a traceback will appear.

Steps to reproduce the error:
- Go to project > Favorites > Import records > Upload File
- Note: Make sure that file contains tags

Traceback:
```
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'list'
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "addons/base_import/models/base_import.py", line 1332, in execute_import
    import_result = model.load(import_fields, merged_data)
  File "odoo/models.py", line 1279, in load
    for id, xid, record, info in converted:
  File "odoo/models.py", line 1441, in _convert_records
    converted = convert(record, functools.partial(_log, extras, stream.index))
  File "odoo/addons/base/models/ir_fields.py", line 118, in fn
    converted[field], ws = converters[field](value)
  File "odoo/addons/base/models/ir_fields.py", line 637, in _str_to_one2many
    writable = convert(exclude_ref_fields(record), log)
  File "odoo/addons/base/models/ir_fields.py", line 118, in fn
    converted[field], ws = converters[field](value)
  File "odoo/addons/base/models/ir_fields.py", line 581, in _str_to_many2many
    id, _, ws = self.db_id_for(model, field, subfield, reference)
  File "odoo/addons/base/models/ir_fields.py", line 462, in db_id_for
    ids = RelatedModel.name_search(name=value, operator='=')
  File "odoo/models.py", line 1730, in name_search
    ids = self._name_search(name, args, operator, limit=limit, order=self._order)
  File "addons/project/models/project_tags.py", line 66, in _name_search
    domain += [('name', operator, name)]
```

https://github.com/odoo/odoo/blob/0480005e4498d76fe7a3446693f41500122e41d7/addons/project/models/project.py#L2763 When user import records that contains tags, here args will be None.
So it will lead to above traceback.

sentry-4494554048

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-25 05:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136374).

2023-09-26 13:36 UTC, reka-odoo commented
@odoo/sentry_reviewers 
Please check this PR.
Thanks!

2023-09-27 12:29 UTC, auon-odoo requested changes
Thanks for the fix :)

2023-09-27 12:29 UTC, auon-odoo commented on addons/project/models/project.py
> +            if not args:
```suggestion
            if args is None:
```
this way, we don't reassign args if it is equal to [] already.

2023-09-27 15:09 UTC, xavierbol approved these changes
LGTM, thanks for the fix. 🙂 

Thanks @auon-odoo for the review! 😁 💪🏼 

robodoo r+

2023-09-27 19:23 UTC, closed without merging