[IMP] *: remove jQuery.nested_sortable
odoo/odoo pull request #136375
Opened 2023-09-25 06:26 UTC by res-odoo

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-25 06:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136375).

2023-09-27 12:15 UTC, rdeodoo commented
@detrouxdev is working on that too in website :grimacing: 
He will have a look and approve on behalf of website :+1:

2023-09-27 12:17 UTC, rdeodoo commented
Oh, and it's `task-3439226` not `Task ID: 3439226`, otherwise it sometimes creates wrong links pointing to random commits :grimacing: 
Just follow the guidelines :p (random example: `https://github.com/odoo/odoo/pull/90975/commits`)

2023-09-27 12:50 UTC, rfr-odoo approved these changes

2023-09-27 13:58 UTC, detrouxdev requested changes
Nice to see that nestedSortable is complete now 😄 A few remarks that are mostly suggestions. Thanks for the work! 👍🏻

2023-09-27 13:58 UTC, detrouxdev commented on addons/website/static/src/components/dialog/edit_menu.js
> +        const currentIsMegaMenu = current.element.dataset.isMegaMenu === "true"
Missing `;` (Unfortunately, the default eslint config is disabled on website, so this tends to happen)

2023-09-27 13:58 UTC, detrouxdev commented on addons/website/static/src/components/dialog/edit_menu.js
> +        this.state = useState({rootMenu: {}, flatMenus: new Map()});
I'm not sure I understand why this was necessary 😅 It looks like the state isn't used in the template, and every time we touch the map, we also change rootMenu (or one of its children) so a re-render is already triggered right?

2023-09-27 13:58 UTC, detrouxdev commented on addons/website/static/src/components/dialog/edit_menu.js
> +        }
```suggestion
        if (previous) {
            previous = this.map.get(this._getMenuIdForElement(previous));
            const index = parentMenu.children.findIndex((child) => child === previous);
            parentMenu.children.splice(index + 1, 0, menu);
        } else {
            parentMenu.children.unshift(menu);
        }
```
If it doesn't have a previous, it means it's the first right? 😄 Whether it has a next element shouldn't matter I think.

2023-09-28 11:38 UTC, res-odoo commented
> Nice to see that nestedSortable is complete now 😄 A few remarks that are mostly suggestions. Thanks for the work! 👍🏻

Hi @detrouxdev, I made all suggestions changes. There are pertinent 👍🏻

2023-09-29 10:39 UTC, detrouxdev commented
@res-odoo Thanks for applying my suggestions! After a few more tests, I realised that you can drop a menu with child elements into another menu that already has a child element:
<img width="661" alt="Screenshot 2023-09-29 at 12 30 57" src="https://github.com/odoo/odoo/assets/77747125/d5c2afd0-2f42-4ceb-adf3-14f9129f6c0d">

I don't think this is only related to the website code, but if it is then I guess we should just check if a menu has children in the `_isAllowedMove` method?

2023-10-03 08:18 UTC, res-odoo commented
> @res-odoo Thanks for applying my suggestions! After a few more tests, I realised that you can drop a menu with child elements into another menu that already has a child element: <img alt="Screenshot 2023-09-29 at 12 30 57" width="661" src="https://user-images.githubusercontent.com/77747125/271544031-d5c2afd0-2f42-4ceb-adf3-14f9129f6c0d.png">
> 
> I don't think this is only related to the website code, but if it is then I guess we should just check if a menu has children in the `_isAllowedMove` method?

You found a bug. To fix it, I made some changes in the `nestedSortable` hooks. Now the deepest check for the max level and the allowed move are both made inside a common method call when the `onMove` and the `onDrop` are called. In the case of an unallowed drop, it simply adds a `d-none` class to hide the drop zone from the end user.

2023-10-03 08:25 UTC, detrouxdev approved these changes
Thanks for fixing the bug! I actually think it also slightly improves the UX if a user tries to drag a mega menu as a child menu since there is no longer a dropzone 👍🏻

2023-10-03 13:40 UTC, pparidans approved these changes
Nice work :sunglasses: 

@robodoo r+ rebase-ff

2023-10-03 13:41 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-03 20:19 UTC, closed without merging