WIP
odoo/odoo pull request #136381
Opened 2023-09-25 07:12 UTC by ryv-odoo

2023-09-25 07:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136381).

2023-09-25 12:24 UTC, JulienAlardot requested changes
Small consistency changes

2023-09-25 12:24 UTC, JulienAlardot commented on addons/account/models/account_journal_dashboard.py
>          }
```suggestion
                groupby=['journal_id'],
                aggregates=['amount_total_signed:sum', '__count'],
            )
        }
```
Small change to stay consistent with to_checks definitions of amount, count=...

2023-09-25 12:24 UTC, JulienAlardot commented on addons/account/models/account_journal_dashboard.py
> +                aggregates=['__count', 'amount_total_signed:sum'],
```suggestion
                groupby=['journal_id'],
                aggregates=['amount_total_signed:sum', '__count'],
```
Same, or swap to_checks

2023-09-26 12:00 UTC, rco-odoo approved these changes

2023-09-29 12:17 UTC, rco-odoo commented
@robodoo r+

2023-09-29 13:00 UTC, robodoo commented
@ryv-odoo @rco-odoo linked pull request(s) odoo/enterprise#47826 not ready. Linked PRs are not staged until all of them are ready.

2023-09-29 16:08 UTC, closed without merging