[FIX] account: handle unsigned with signed tax tags
odoo/odoo pull request #136460
Opened 2023-09-25 12:19 UTC by proose

When a tax is created using an unsigned tax tags AND a signed tax tag, the mapper in the chart template model was crashing, skipping the needed mapping for the signed tax (the unsigned tax doesn't need to be mapped as it comes from a template).

2023-09-25 12:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136460).

2023-10-02 11:42 UTC, oco-odoo requested changes

2023-10-02 11:42 UTC, oco-odoo commented on addons/account/models/chart_template.py
> +        return lambda *args: [tags[re.sub(r'\s+', ' ', x.strip())] if not re.match(r"^(\w+\.\w+,)*\w+\.\w+$", x) else x for x in args]
```suggestion
        return lambda *args: [tags[re.sub(r'\s+', ' ', x.strip())] if not re.match(r"^\w+\.\w+$", x) else x for x in args]
```
The terms are split here (see line 954), so I don't think keeping the first part of the regex makes sense, does it ? (I didn't test)

2023-10-02 13:29 UTC, proose commented on addons/account/models/chart_template.py
I forgot about saas versions, only checked 16.0 :facepalm:
Opened a new PR with correct target and branch name (and applied your comment): https://github.com/odoo/odoo/pull/137268
I'll close this one.

2023-10-02 13:30 UTC, proose commented
Wrong version target

2023-10-02 13:30 UTC, closed without merging