[FIX] mrp: give default value when precision rounding value is zero
odoo/odoo pull request #136462
Opened 2023-09-25 12:20 UTC by alsh-odoo

The traceback arises when the user removes the `product` from `stock.move`
 and try to add a product in `mrp.production`.

To reproduce this issue:

1) Install `MRP`
2) Create a new record for `Manufacturing Order`
3) First add a line in `Components`
4) Remove the `product_id` from `Component`
5) Now try to add `Product` in `mrp.production`

Error:-
```
AssertionError: precision_rounding must be positive, got 0.0
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "odoo/models.py", line 6756, in onchange
    record.modified(todo)
  File "odoo/models.py", line 6352, in modified
    for field, records, create in tocompute:
  File "odoo/models.py", line 6404, in _modified_triggers
    records = self[invf.name]
  File "odoo/models.py", line 6211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/fields.py", line 4366, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 2852, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 1157, in __get__
    self.recompute(record)
  File "odoo/fields.py", line 1367, in recompute
    apply_except_missing(self.compute_value, recs)
  File "odoo/fields.py", line 1340, in apply_except_missing
    func(records)
  File "odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "addons/mail/models/mail_thread.py", line 395, in _compute_field_value
    return super()._compute_field_value(field)
  File "odoo/models.py", line 4553, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 101, in determine
    return needle(*args)
  File "addons/mrp/models/mrp_production.py", line 531, in _compute_workorder_ids
    if production.state != 'draft':
  File "odoo/fields.py", line 1157, in __get__
    self.recompute(record)
  File "odoo/fields.py", line 1367, in recompute
    apply_except_missing(self.compute_value, recs)
  File "odoo/fields.py", line 1340, in apply_except_missing
    func(records)
  File "odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "addons/mail/models/mail_thread.py", line 395, in _compute_field_value
    return super()._compute_field_value(field)
  File "odoo/models.py", line 4553, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 101, in determine
    return needle(*args)
  File "addons/mrp/models/mrp_production.py", line 525, in _compute_state
    elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding) for move in production.move_raw_ids):
  File "addons/mrp/models/mrp_production.py", line 525, in <genexpr>
    elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding) for move in production.move_raw_ids):
  File "odoo/tools/float_utils.py", line 123, in float_is_zero
    epsilon = _float_check_precision(precision_digits=precision_digits,
  File "odoo/tools/float_utils.py", line 29, in _float_check_precision
    assert precision_rounding is None or precision_rounding > 0,\
```

on the `_compute_state` method when the state is in `draft` and the user added a line in `move_raw_ids`.

In this case, `precision_rounding` is getting value from `product_uom.rounding` or `product_id.uom_id.rounding` through `move_raw_ids`.

See:- https://github.com/odoo/odoo/blob/10e0ac377cc235d81819eaa2a4ec2b6a60fffd70/addons/mrp/models/mrp_production.py#L478-L480

When the user removes `product_id` from `move_raw_ids`, `precision_rounding` will be `0.00`. 
Which leads to the above traceback.

Applying this commit will resolve the issue by giving a default value of `0.01`, 
when the `precision_rounding` value is `0.00`.

sentry-4220927307

2023-09-25 12:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136462).

2023-09-26 09:43 UTC, alsh-odoo commented
Hello @odoo/sentry_reviewers 

kindly check this PR

Thank You!!

2023-09-26 10:02 UTC, abz-odoo commented
to be pre-reviewed by rd-bugfix-stock

2023-09-26 15:15 UTC, DjamelTouati reviewed
Hello @alsh-odoo 
I tried to reproduce the bug on runbot V15, but it seems to work well, could you send me a video with the steps to reproduce please, Thank you

2023-09-27 05:06 UTC, alsh-odoo commented
Hello @DjamelTouati 

Here is the video reference to produce the bug

See:-  https://tinyurl.com/2cl7hvao

Thank You !!

2023-10-05 09:57 UTC, alsh-odoo commented
Hello @DjamelTouati 

Please review this PR

Thanks !!

2023-10-05 12:36 UTC, DjamelTouati requested changes
Hello, Thank you for your fix!

2023-10-05 12:36 UTC, DjamelTouati commented on addons/mrp/models/mrp_production.py
> +            elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding or 0.01) for move in production.move_raw_ids):
```suggestion
            elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding) for move in production.move_raw_ids if move.product_id):
```

2023-10-06 08:37 UTC, DjamelTouati approved these changes
LGTM, Thanks!

2023-10-06 08:40 UTC, Whenrow commented
robodoo delegate=@DjamelTouati

2023-10-06 09:25 UTC, DjamelTouati commented
robodoo r+

2023-10-06 10:48 UTC, closed without merging