[IMP] point_of_sale: multi-attribute support
odoo/odoo pull request #136441
Opened 2023-09-25 11:41 UTC by davidmonnom

Prior to this PR, `product_configurator_popup.js` did not support attribute selection of type `multi`. In addition, the `pos_preparation_display` did not display any attributes.

Now it's possible to select attributes of type `multi` in the Point of Sale, and the preparation display shows all available attributes.

taskid: 3497560

Preparation display before:
![image](https://github.com/odoo/odoo/assets/63289800/66b834d1-a2b1-47c0-9b8d-09192d657b22)

Preparation display after:
![image](https://github.com/odoo/odoo/assets/63289800/05c7d3c8-f4a9-4450-b1dd-8678d64f8351)

Point of Sale multiple attributes support:
![image](https://github.com/odoo/odoo/assets/63289800/f3900435-2397-43ce-ad35-ff725d5c54c4)

2023-09-25 11:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136441).

2023-09-25 12:40 UTC, caburj requested changes

2023-09-25 12:50 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/store/product_configurator_popup/product_configurator_popup.xml
> +                <label class="form-check-label" for="flexCheckDefault" t-esc="value.name" />
oops

2023-09-27 08:27 UTC, adgu-odoo approved these changes

2023-09-27 11:05 UTC, adgu-odoo commented
@robodoo r+

2023-09-27 16:44 UTC, closed without merging