[FIX] web_editor: adjust "add URL" button for documents
odoo/odoo pull request #136512
Opened 2023-09-25 14:55 UTC by bso-odoo

Before this commit the button to add documents from an URL is labeled "Add Document" which is confusing given it is displayed besides an "Upload Document" button.

This commit renames the "Add Document" button into "Add URL" to make its purpose more obvious.

task-3493618

2023-09-25 14:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136512).

2023-10-16 08:44 UTC, rdeodoo requested changes
It's IMO not worth in Odoo 14.. People have lived like that for years.
Let's not improve wording in (that old) stable, especially if it comes with javascript for existing DBs?

But see my review, the JS is useless actually, no?
I'd just keep the XML change, and then it seems OK as it doesn't break any translation since "Add URL" is already translated in the same file.

I would be more confortable with Odoo 16 but it's fine.

2023-10-16 08:44 UTC, rdeodoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/media.js
> +    },
What's this change for? The changed XML file in this PR is a static file, not an `ir.ui.view`, so existing DBs should receive the change already?

2024-01-11 14:45 UTC, bso-odoo commented
@rdeodoo I just noticed this one-liner is sleeping there. :grimacing:

2024-01-11 17:34 UTC, rdeodoo approved these changes
@robodoo r+ Very low risk / Very low value (in stable given the risk), I would not have target 15 initially but now that it's done :+1: 

Term will be translated already as this term is already translated in the same file

Note that in Odoo 16, this is becoming some JS translated terms, will need to be adapted

2024-01-11 19:04 UTC, closed without merging