[FIX] web: prevent unintended closure of dialog attached to a dropdown
odoo/odoo pull request #136600
Opened 2023-09-26 05:54 UTC by ushyme

### Summary
Activating a new dropdown within a dialog, initiated from another dropdown, leads to the unintended closure of the original dropdown and its dialog.

### Steps to reproduce
- Install `account_accountant`
- Navigate to Report > Partner Ledger
- Click 'Partners' button to open a dropdown (referred to as `DD`)
- In that dropdown, click the 'Partners' text field, then 'Search More'
- A dialog opens. In that dialog, toggle the search panel

You should see that the dialog closes.

### Cause
When a new dropdown is activated, the existing implementation closes all other open dropdowns. In this case, toggling the search panel within the 'Search More' dialog opens a new dropdown. This action triggers the closure of `DD`, which also unmounts 'Search More'. Unmounting 'Search More' also leads to the unmounting of the dialog, as they are tied together through `useOwnedDialogs()`.

opw-3464528

2023-09-26 05:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136600).

2023-10-12 07:04 UTC, ushyme commented
Hello @Iucapad, could you take a look at this when you have some time ?

2023-10-12 09:05 UTC, Iucapad commented
I don't know much about `useSelectCreate` in relational utils, but could you add a test for this fix?

2023-11-28 15:03 UTC, jpp-odoo requested changes
This is not the correct way to solve the issue, with this solution, if you chose a partner of the list after opening the filters' dropdown, it will raise a "Component is destroyed" error.

The real issue is that the first dropdown is destroyed when opening the filters' dropdown and it shouldn't.

2023-11-29 08:56 UTC, jpp-odoo commented
I'm closing this PR as it didn't solve the issue.
There is a proposition PR to solve this : https://github.com/odoo/odoo/pull/144119

2023-11-29 08:56 UTC, closed without merging