[FIX] sale_coupon, sale_coupon_delivery: filter delivery line
odoo/odoo pull request #136742
Opened 2023-09-27 05:35 UTC by thle-odoo

Versions:
---------
- (14.0)
- 15.0
- saas-15.2

Steps to reproduce:
-------------------
Create a promotion program which trigger a promotion when there are three products which don't contain "test" in their name. Add two product to the cart and process checkout.

Issue:
------
A promotion line is created even if we don't respect the condition.

Cause:
------
A delivery line is added to the sale order.
THis new line is considered when we check for apply program.

Solution:
---------
Create a method that filters order lines.
Override this method in the sale_coupon_delivery module.

opw-3507286

2023-09-27 05:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/136742).

2023-09-28 09:40 UTC, Demesmaeker requested changes
Hello, thanks for your fix, lgtm =]

Could you also put that new method just after the `_filter_programs_on_products` method where it's called? Thanks ^^

2023-09-28 09:40 UTC, Demesmaeker commented on addons/sale_coupon/models/coupon_program.py
> +    def _get_program_lines(self, order):
```suggestion
    def _get_lines_suitable_for_program(self, order):
```
Or anything that could be better to be clear you don't get reward/program lines, but lines that are adapted to get a reward instead =]

2023-09-28 11:13 UTC, Demesmaeker approved these changes

2023-10-02 08:46 UTC, Feyensv approved these changes
@robodoo delegate+

A test would have been nice, but since it's not reproducible in 16.0+ (and would be annoying to fw-port), let's forget it :ok_hand:

2023-10-03 07:26 UTC, thle-odoo commented
@fw-bot up to saas-15.2

2023-10-03 07:34 UTC, thle-odoo commented
@robodoo r+

2023-10-03 13:17 UTC, closed without merging