[FIX] account: hide payment term placeholder on invoice
odoo/odoo pull request #137420
Opened 2023-10-03 12:40 UTC by lvsz

Versions:
---------
- saas-16.4+

Steps to reproduce:
-------------------
1. create a customer invoice;
2. set customer to be a person (not a company)
3. set a due date instead of payment terms
4. click preview;

Issue:
------
The invoice will say "Payment within 30 calendar days" regardless of due date selected.

Cause:
------
This is a placeholder string for a `t-field` that should be hidden when viewing actual records.

Solution:
---------
Changes need to be made to `ir_qweb.py` in Odoo base as to not force rendering of `t-field` nodes when a default value is present, but because this has been documented behavior thus far, I don't think this can be done on stable.
For now, I propose changing the template by moving the `payment_terms_note_id` node behind the
`<t t-if="o.invoice_payment_term_id.display_on_invoice">` check, but before the `<t t-if="payment_term_details">` check.

opw-3523921

2023-10-03 12:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/137420).

2023-10-03 16:20 UTC, agr-odoo requested changes
The patch works but it also modify the behavior in some cases. When we have a payment term with a note and `display_on_invoice` set to `False` with current patch we would not display the note
A simple and effective fix could be to add a `t-if` inside the `span` to add the element, so that we show the element if we actually have the note

Anyhow updating account (or manually fix the template) will be necessary but it doesn't seem to be another way around

2023-10-04 11:47 UTC, lvsz commented
> When we have a payment term with a note and `display_on_invoice` set to `False` with current patch we would not display the note

Isn't that how it's supposed to work? If `invoice_payment_term_id.display_on_invoice` is set to `False`, why would you expect `invoice_payment_term_id.note` to be displayed on the invoice?

2023-10-04 11:50 UTC, agr-odoo commented
The field `display_on_invoice` is defined as
```python
display_on_invoice = fields.Boolean(string='Show installment dates', default=True)
```
Imho the field name is a bit misleading as the help string only refers to the dates, leaving open the possibility to show only the notes

2023-10-04 11:53 UTC, agr-odoo commented
@casp-odoo 
@smetl 
Could we have your opinion on this? Is `display_on_invoice` supposed to show/hide everything or just the date?

2023-10-05 14:42 UTC, agr-odoo approved these changes

2023-10-10 17:09 UTC, closed without merging