[FIX] point_of_sale: sync orders on pos closing
odoo/odoo pull request #137648
Opened 2023-10-05 06:56 UTC by fja-odoo

**Step to reproduce**:

- Open a pos session
- Turn off the connection between the server and your POS instance
- Create an order offline
- Turn back on the connection between the server and your POS instance
- Close the POS session

**Issue**:

The order created offline is not synced to the server

**Cause**:

The sync of the order has been implemented for the button to go back to the backend without closing but not for the closing session button.

**Solution**:

Make the synch mechanism common to both buttons.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-05 06:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/137648).

2023-11-06 14:18 UTC, caburj requested changes
apologies for the late review. I'd like to request for changes. After that we'll ask the security team for override.

The changes are asked because you introduce the extracted procedure in the PosModel, so `this` is already the instance of PosModel.

Also, is it conscious decision to reject when user selected "Do not close"? From what I understand, that will show an extra error popup.

2023-11-06 14:18 UTC, caburj commented on addons/point_of_sale/static/src/js/models.js
> +            return await this.env.pos.push_orders(order, opts);
```suggestion
            return await this.push_orders(order, opts);
```

2023-11-06 14:18 UTC, caburj commented on addons/point_of_sale/static/src/js/models.js
> +            const reason = this.env.pos.get('failed')
```suggestion
            const reason = this.get('failed')
```

2023-11-13 04:11 UTC, fja-odoo commented
> Also, is it conscious decision to reject when user selected "Do not close"? From what I understand, that will show an extra error popup.

Hello thank you for the review, yes it is a conscious decision since the unhandled falsey rejections are ignored https://github.com/odoo/odoo/blob/15.0/addons/point_of_sale/static/src/js/Chrome.js#L494

2023-11-15 08:54 UTC, caburj commented
@odoo/rd-security Hi team. I'm okay with this PR. However, the ci/security is triggered because of the move of code that sets the current `window.location` to the backend. Can we proceed?

2023-11-15 12:10 UTC, caburj approved these changes
robodoo r+

2023-11-15 13:22 UTC, closed without merging