[FIX] website: prevent traceback because megamenu toggle does not exist
odoo/odoo pull request #137705
Opened 2023-10-05 12:40 UTC by rdeodoo

Commit [1] introduced a method to restore the mega menu state (closed) so it's not saved open when saving the website builder edition. That method is `_restoreMegaMenus()`.

It was called in `destroy` where it was actually making the code crash because once you read `destroy`, the website content (the iframe) has already been reload (and thus removed / recreated). It's done through `reloadIframe()`.

So, depending of your network speed and the server response time, if the page is served before reaching the mega menu restoration, it will crash.

Restoring the mega menu in the (wysiwig) destroy doesn't seems to do anything as the page is already saved when reaching `destroy`.

Step to reproduce:
- Create a mega menu on the website
- Enter edit mode
- Directly save or discard -> Traceback, the jQuery toggle elements (`.o_mega_menu_toggle`) are not
   in the DOM anymore, since the iframe got reloaded. Those elements
   thus don't have a reference to `$` anymore, ultimately making this
   line crash:

```js
const $toggle = toggle.ownerDocument.defaultView.$(toggle);
```

[1]: https://github.com/odoo/odoo/commit/d7245d2abf528d093226c80e40975e63d61e8997

opw-3483837
opw-3478642

2023-10-05 12:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/137705).

2023-10-05 12:41 UTC, rdeodoo commented
@Goaman @dmo-odoo Hello, could anyone of your team have a look?
I am not sure to have fully understand that part of the code but from what I tested, my commit explanation seems right?

2023-10-11 09:12 UTC, Goaman commented
@rdeodoo The code was not analysed adapted in the ([owl conversion](https://github.com/odoo/odoo/commit/d7245d2abf528d093226c80e40975e63d61e8997)) nor in the [OdooEditor creation](https://github.com/odoo/odoo/commit/740168ce8d27da3d6a7156d2d79655a898394923).

I can't see why your changes would break something so lgtm.

2023-10-11 09:25 UTC, rdeodoo commented
> The code was not analysed adapted in the [owl conversion](https://github.com/odoo/odoo/commit/d7245d2abf528d093226c80e40975e63d61e8997) nor in the [OdooEditor creation](https://github.com/odoo/odoo/commit/740168ce8d27da3d6a7156d2d79655a898394923).

I am not sure to understand what does that mean?

2023-10-11 14:15 UTC, Goaman commented
@rdeodoo It means that I don't know either why the code is there in the first place and I don't see why it would break something by removing it.

2023-10-11 14:19 UTC, dmo-odoo commented
@robodoo r+

2023-10-11 15:02 UTC, qsm-odoo requested changes
@robodoo r-

In fact what NBY meant was he did not introduce that line, after investigation it was introduced here: https://github.com/odoo/odoo/commit/1345702258adbfbee0d780dc22e552395e6d1df7 (a very long time ago). Now it probably ended up being moved at the wrong place indeed. And it may have been useless in the first place, who knows :grimacing: Explanation to be adapted.

2023-10-12 11:44 UTC, rdeodoo commented
Adapted, @dmo-odoo Could you please r+ again :) ?

2023-10-12 11:49 UTC, dmo-odoo commented
@rdeodoo Depends if @qsm-odoo is going to r- me again or not... 🤔

2023-10-12 11:50 UTC, rdeodoo commented
What.. :') ?
There was a mistake in the commit message, I would expect anyone to r- any PR when a mistake is in the commit message, even people not related to the PR :grimacing:

2023-10-12 12:09 UTC, dmo-odoo commented
This was a poor attempt at a snarky joke, though I legit did not understand the reason of the r-. I do now, thanks.

@robodoo r+

2023-10-12 14:36 UTC, closed without merging