[IMP] pos_self_order,pos_online_payment_self_order: improve success page
odoo/odoo pull request #138013
Opened 2023-10-09 11:10 UTC by davidmonnom

Previously, when ordering an order in `meal` mode in the mobile selfOrder, no confirmation page was displayed but only a notification indicating that the order had been sent. In `each` mode no page was displayed either.

Now, when ordering in the mobile selfOrder, a confirmation page showing the order lines just ordered is displayed. On this page a message indicating the table number / place to pick up the order is also displayed.

![image](https://github.com/odoo/odoo/assets/63289800/5add7c5a-0fd7-42a4-ab26-4c319a751a43)

2023-10-09 11:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/138013).

2023-10-12 08:32 UTC, Feyensv approved these changes

2023-10-13 11:54 UTC, adgu-odoo requested changes
Nice PR

2023-10-13 11:54 UTC, adgu-odoo commented on addons/pos_self_order/static/src/app/pages/confirmation_page/confirmation_page.js
> +    }
Is this used ?

2023-10-13 11:54 UTC, adgu-odoo commented on addons/pos_self_order/static/src/app/pages/landing_page/landing_page.js
> +    }
You are only using this getter to get the length of the draft orders. Maybe return the length in the getter and not the orders

2023-10-13 11:54 UTC, adgu-odoo commented on addons/pos_self_order/static/src/app/pages/landing_page/landing_page.xml
> +                        t-attf-class="btn btn-lg btn-{{link.style}} {{ hideBtn(link) ? 'd-none' : ''}}">
To hide a button, use a t-if rather that a d-none added to the class

2023-10-13 11:54 UTC, adgu-odoo commented on addons/pos_self_order/static/src/app/pages/landing_page/landing_page.js
> +            routeName === "products" &&
You do not need this part of the condition

2023-10-13 14:33 UTC, davidmonnom commented on addons/pos_online_payment_self_order/static/src/pages/cart_page/cart_page.js
> +        if (mode === "meal" && isOnlinePayment && order.isSavedOnServer) {
In fact, it's the second check that's useless, so I've deleted it.

2023-10-16 08:19 UTC, adgu-odoo approved these changes

2023-10-16 08:21 UTC, adgu-odoo commented
@robodoo r+ rebase-ff

2023-10-16 08:22 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-16 10:39 UTC, closed without merging