[FIX] website_blog: fix latest blog tag color
odoo/odoo pull request #138151
Opened 2023-10-10 08:43 UTC by bvr-odoo

Since commit [1], the color combination system has been introduced, affecting the colors of elements in the snippets. For the "blog" page cover, it wasn't adjusted to work with this color combination system. This resulted in inconsistencies, like the "Latest blog" tag having nearly the same background and text color. This is because some elements are affected by the chosen color combinations, while others have a hardcoded color in the XML template (for example, the "text-white" class on the blog title link).

In this stable version, we address this by ensuring that the text color of the "latest blog" tag matches our original intention before the introduction of the color combinations.

[1]: https://github.com/odoo/odoo/commit/69190959ce8e08481be7ebdfefd314edf0c5dce1

opw-3524351

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-10 08:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/138151).

2023-10-10 08:46 UTC, bvr-odoo commented
In Master, the "Blog" page cover should be adapted to work with the color combination system.

2023-10-15 16:12 UTC, rdeodoo requested changes
Shouldn't we fix the titles too which seems more problematic than a tag?

https://watch.screencastify.com/v/Esf44j8izGKJc3RqnEHa

![image](https://github.com/odoo/odoo/assets/30048408/cb94599c-0d39-4007-9f38-9339a7129bde)

2023-10-16 07:49 UTC, bvr-odoo commented
> Shouldn't we fix the titles too which seems more problematic than a tag?

I believe it's not a bigger issue, the text is hardcoded in white but we have the flexibility to alter the background and the filter.
On the other hand, with the tag, we can't make any changes, and it's initially hidden. I chose not to update the title in the stable version to avoid affecting the title color on functioning online sites.

2023-10-16 14:21 UTC, rdeodoo commented
But hard-coding a color doesn't seems better, see:
![image](https://github.com/odoo/odoo/assets/30048408/1409785f-a93c-411b-a0fc-be114a6b9527)

As the background color of that tag element is not fixed but `bg-o-color-3` class, it's just going to work with some colors but not with others.

Surely there is a way to use the `bg-o-color-3` bg color with a readable text in all cases, no?

2023-10-17 13:15 UTC, bvr-odoo commented
> But hard-coding a color doesn't seems better, see: ![image](https://user-images.githubusercontent.com/30048408/275544486-1409785f-a93c-411b-a0fc-be114a6b9527.png)
> 
> As the background color of that tag element is not fixed but `bg-o-color-3` class, it's just going to work with some colors but not with others.
> 
> Surely there is a way to use the `bg-o-color-3` bg color with a readable text in all cases, no?

I made the change using the correct variable, now the text color becomes lighter if the background color is dark.
Should be adapted in the xml in master

2023-10-17 16:35 UTC, rdeodoo approved these changes
@robodoo r+

2023-10-17 17:54 UTC, closed without merging