[FIX] web: fix color-list in the Dark Mode
odoo/odoo pull request #138391
Opened 2023-10-11 13:15 UTC by ppr-odoo

Step:
----
 - install planning module
 - active the Dark Mode
 - open planning model
 - create shift with material resource
 - check the material resource icon

Issue:
-----
   when dark mode active that time background and color are not proper show

Fix:
-----
   We have fixed according the tag_list.

task-3524295
![2023-10-11_18-44](https://github.com/odoo/odoo/assets/24606113/93d4167c-3dd3-493d-ae7d-05fa19f491a3)

- requires : https://github.com/odoo/enterprise/pull/54510

2023-10-11 13:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/138391).

2023-11-17 14:18 UTC, MissingNoShiny reviewed
LGTM, thanks for your work :slightly_smiling_face:

2024-01-10 15:53 UTC, xavierbol commented
Hello @ppr-odoo 

Thanks for the fix, before pinging the Framework JS team to review your fix, I am wondering if your fix should not be retargeted in stable versions?

Seems the last push in that PR is 3 months ago, I guess yes. 🤷🏼‍♂️ 

Can you check that when you have time? 

Thanks in advance! 🙂

2024-01-11 05:15 UTC, ppr-odoo commented
@xavierbol   I regrate the branch in 17.0 because the problem is still present. thank you

2024-01-11 12:49 UTC, xavierbol commented
Thanks 🙂 

I will let @odoo/rd-framework-js do the final review of that styling issue. 🙂

2024-01-11 13:52 UTC, sdegueldre commented
Probably more for @odoo/rd-design I would think?

2024-01-11 16:11 UTC, chgo-odoo requested changes
Hi @ppr-odoo, thanks for your fix, this behaviour was indeed broken !

In addition to this Community PR, you should also **create an Enterprise one**, to ensure the contrast of `colorlist_item` is perfect in dark mode.

What you did in this PR is saying : "use the adjustments made to the tags in light mode for `colorlist_item`."

This means that if the user switches from light mode to dark mode, he will still have the adjustments from the light mode tags.


Since your PR aims to fix the dark mode, I'd suggest to scope your changes to dark mode by adding this line in the `colorlist.dark.scss` file,
right under the --background-color, one :

`--color: #{mix(nth($o-colors, $size), $o-view-background-color, 15%)};`

This will basically use the background-color of our tags in dark mode as the color of the `<i>` if the user is using dark mode, allowing more flexibility.

By doing this, if the user uses light mode, he will get the color from `colorlist.scss`, while he will get the one from `colorlist.dark.scss` if he uses dark mode.

Once the Enterprise PR is created and the CSS line is added, you can ping me on one of the two PR and I will approve them both !

Thanks !

2024-01-17 11:19 UTC, ppr-odoo commented
If you have free time, please review the enterprise PR I have created. https://github.com/odoo/enterprise/pull/54510

2024-01-17 12:25 UTC, chgo-odoo approved these changes
LGTM !

Thanks again for your fix @ppr-odoo 👍

2024-01-17 16:44 UTC, xavierbol commented
Hello @chgo-odoo ,

Okay, thanks for the review. 🙂

2024-01-17 16:44 UTC, xavierbol commented
Thanks for your work @ppr-odoo 

robodoo r+

2024-01-17 17:01 UTC, robodoo commented
@ppr-odoo @xavierbol linked pull request(s) odoo/enterprise#54510 not ready. Linked PRs are not staged until all of them are ready.

2024-01-18 06:26 UTC, closed without merging