[IMP] hr_expense: usability improvements
odoo/odoo pull request #138387
Opened 2023-10-11 13:02 UTC by alialfie

This commit contains a few small improvements to Expense app.

- Primary button moved to the left.
- Reports are auto saved when created from an expense.
- Expense lines in a report are no longer editable. When a line is clicked, the last attachment uploaded for that expense (if any) is shown in the previewer.

task-3539382

2023-10-11 13:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/138387).

2023-10-13 09:39 UTC, h4818 requested changes
Nicely done.
I think a QUnit test is important, in case of changes to ListRenderer or x2manyField

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/models/hr_expense.py
> +                'res_id': sheet.id,
This function should be simplified, something like this should do it.
```py
sheets = self.env['hr.expense.sheet'].create(self._get_default_expense_sheet_values())
return {
  'name': _('New Expense Reports'),
  ...
  'views': [[False, "list"], [False, "form"]] if len(sheets) > 1 else [[False, "form"]],
  'domain': [('id', 'in', sheets.ids)],
  'res_id': sheets.id if len(sheets) == 1 else False,
}
```

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/static/src/views/expense_list_view.js
> +        super.setup();
call super setup first

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/static/src/views/expense_list_view.js
> +        const lineThread = this.threadService.getThread('hr.expense', record.resId)
if the one is sheetThread, maybe `expenseThread` will be better

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/tests/test_expenses.py
> +            expense_sheet_form._view['fields_spec']['expense_line_ids'].pop('fields')
🤔 not convinced

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/views/hr_expense_views.xml
> +                                    <field name="sheet_id" column_invisible="True"/>
This is not necessary
This is a form view of a sheet that already has an id
in js you can get it with `this.env.model.root.resId`

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/static/src/views/expense_list_view.js
> +    // the getter to maintain the same behavior.
no need to mention what it was... keep it simple and move it inside the function
// this field is used like a many2many list - allowing the selection of existing expenses

2023-10-13 09:39 UTC, h4818 commented on addons/hr_expense/static/src/views/expense_list_view.js
> +import { useService } from "@web/core/utils/hooks";
```suggestion
import { registry } from "@web/core/registry";
import { useService } from "@web/core/utils/hooks";

import { ListRenderer } from "@web/views/list/list_renderer";
import { X2ManyField, x2ManyField } from "@web/views/fields/x2many/x2many_field";
```

2023-10-13 09:47 UTC, h4818 commented on addons/hr_expense/static/src/views/expense_list_view.js
> +export class ExpenseListRenderer extends ListRenderer {
Are you aware there is already an `ExpenseListRenderer` class in list.js?
Maybe we should rename this one to avoid confusion?

2023-10-24 11:24 UTC, JulienAlardot commented
Sorry for the hellish rebase you'll have on that one :p (also, check your missing EOL :) )

2023-10-25 11:03 UTC, alialfie commented
Rebased and ready!

2023-10-26 10:36 UTC, JulienAlardot requested changes
Remind me why you are not using the hr_expense.message_main_attachment_id again?

2023-10-26 10:49 UTC, alialfie commented
> Remind me why you are not using the hr_expense.message_main_attachment_id again?

PO request. When an expense line is clicked in a sheet, the last uploaded attachment in that line is shown, and `message_main_attachment_id` is not necessarily the latest.

2023-10-26 12:15 UTC, JulienAlardot commented
> > Remind me why you are not using the hr_expense.message_main_attachment_id again?
> 
> PO request. When an expense line is clicked in a sheet, the last uploaded attachment in that line is shown, and `message_main_attachment_id` is not necessarily the latest.

After discussions with Laura
- We want to display the main attachment
- If we add a new attachment through the "Attach receipt" it becomes the main attachment
- If we add a new attachment through the "Add attachments" it keeps the previous one

The last 2 changes are handled by `register_as_main_attachment` parameter force=True (need to check but it may already be properly set, else it is an easy fix

The reason behind the "last attachment" was because of simplicity (from what another PO told her), here it's definitely not simpler

Note that you would have to edit the attach_document method and check that its overrides are now extends of it

(Also, note that right now as you are never sorting the ids you only show the oldest one and not the latest)

2023-11-06 11:34 UTC, JulienAlardot commented
Runbot is red :)

2023-11-06 14:30 UTC, h4818 reviewed
Small things, let's merge

2023-11-06 14:30 UTC, h4818 commented on addons/hr_expense/static/tests/views/expense_line_widget_tests.js
> +        pyEnv['hr.expense'].write([expense_lines[1]], {message_main_attachment_id: attachmentIds[3]})
both cases have the last attachment as the main attachment.

2023-11-06 16:08 UTC, JulienAlardot requested changes
After some functional testing on the community build
It seems that as I thought the attachments aren't working properly (due to the main attachment being set in the enterprise code)

Also, the default view of the report is the last attachment of one of the expense line (didn't check if it was the last or the first) but not the main attachment of that expense
That's weird, they should at least be sorted by expense then if they are main attachment or not then ids DESC imo

2023-11-07 11:41 UTC, JulienAlardot commented
Runbot is red

2023-11-15 08:33 UTC, JulienAlardot approved these changes
@h4818 LGTM
Functionally tested too

2023-11-16 15:07 UTC, h4818 commented
Thanks @JulienAlardot @alialfie 
robodoo r+

2023-11-16 15:07 UTC, h4818 commented
@robodoo r+

2023-11-16 15:08 UTC, robodoo commented
I'm sorry, @h4818: this PR is already reviewed, reviewing it again is useless.

2023-11-17 03:54 UTC, closed without merging