[IMP] hr_expense:warn user on expense category price update
odoo/odoo pull request #138889
Opened 2023-10-17 08:17 UTC by Megaaaaaa

Description of the issue/feature this commit addresses:

Currently, if the price of an expense category which has expenses posted is modified, the total amount of those expenses is modified too. This is a wanted behavior but this might surprise the user and so it would be preferable to tell him that those amount will be modified when he is editing the category's price.

---

Desired behavior after the commit is merged:

Adding this commit, when a user modifies the standard_price on a expense category, if this category has posted or draft expenses linked, a warning message will appear to tell the tell the user of what is going to happen.

---

task-3506770

---

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-17 08:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/138889).

2023-10-17 09:36 UTC, malb-odoo requested changes
Good job ! Few small comments :smile:

2023-10-17 09:36 UTC, malb-odoo commented on addons/hr_expense/models/product_product.py
> +                    _("There are unposted expenses linked to this category. Updating the category cost will change expense amounts. Make sure it is what you want to do.")
if the message is too big you could split the string into two, better to split it than having a "\" imo

2023-10-17 11:00 UTC, malb-odoo approved these changes
LGTM thxx !

2023-11-02 13:40 UTC, JulienAlardot commented
Why is the task in deployed when it isn't merged?
Also, can it be merged asap
Else I would have to request changes if my [PR](https://github.com/odoo/odoo/pull/140640) goes first

2023-11-02 13:48 UTC, Laura-labe commented
Hello @JulienAlardot , to be honnest I don't really understand, but it seems I changed the status from review to deployed. As explained on Discord I had some issues with my trackpad which moved the mouse without explanation... Sorry about that

2023-11-02 13:49 UTC, malb-odoo commented
Maybe a mistake from @Laura-labe since she is the one who put it in deployed ? Maybe @JulienAlardot you can give it to JBW for the possible r+

2023-11-07 12:55 UTC, qdp-odoo commented
runbot's red in here. It probably needs a rebase and/or a fix

2023-11-07 13:12 UTC, qdp-odoo commented on addons/hr_expense/models/product_product.py
> +        undone_expenses = self.env['hr.expense'].search([('state', 'in', ['draft', 'reported', 'approved']), ('product_id', 'in', self.ids)])
use read_group

2023-11-07 13:14 UTC, qdp-odoo commented on addons/hr_expense/models/product_product.py
> +                product.standard_price_update_warning = _("""There are unposted expenses linked to this category.
when a translatable string is modified or added in stable, the change must be reflected in the .pot file :point_up:

2023-11-07 13:15 UTC, Xavier-Do commented
Upgrade exception [#270](https://runbot.odoo.com/web/#id=270&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
field:product.product.standard_price_update_warning
```
cc @KangOl @nseinlet

2023-11-07 13:16 UTC, qdp-odoo requested changes
you should also be adding a test for that.

2023-11-07 13:38 UTC, qdp-odoo commented on addons/hr_expense/models/product_product.py
> +    standard_price_update_warning = fields.Char(compute="_compute_standard_price_update_warning")
true, but not the same use and feel. :shrug:

2023-11-22 14:39 UTC, JulienAlardot requested changes

2023-11-24 11:30 UTC, JulienAlardot approved these changes
@Xavier-Do Hello, could we have another exception please? (sorry the last one timed out)
@qdp-odoo or @jbw-odoo LGTM

2023-11-24 11:47 UTC, Xavier-Do commented
The exceptions was removed because it didn't look useful anymore. This is why exception should be requested in last minute when all other reviews are done :) 

I reactivated it, please merge it and forward-port it asap ;)

2023-11-28 10:15 UTC, closed without merging