[FIX] website_sale: fix spacing between elements in header and filters
odoo/odoo pull request #139043
Opened 2023-10-18 11:07 UTC by anso-odoo

Prior to this commit, `products_header` had margin issues between buttons and inputs.

This commit fixes these issues using `gap-3`.

Prior to this commit, the left column filter would hide overflowing elements, creating a layout issue with outlines when buttons were focused.

This commit fixes this issue by using paddings and negative margings to compensate.

task-3097005
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-18 11:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139043).

2023-10-19 06:42 UTC, Brieuc-brd requested changes
Just two little things :) : 

-Filter button still has a margin that increases the spacing too much, could you check ?
![Capture d’écran 2023-10-19 à 08 39 57](https://github.com/odoo/odoo/assets/80679690/3da779bd-ff52-44d6-b61b-b1535cfb480c)

- Also, could you double-check your commit and PR messages ?

2023-10-19 11:24 UTC, anso-odoo commented
@Brieuc-brd Thanks ! Fixed :)

2023-10-19 13:06 UTC, Brieuc-brd approved these changes
LGTM

2023-10-19 13:08 UTC, anso-odoo commented
Hello, @odoo/rd-ecommerce can you have a look at this PR please ? Thanks 👍

2023-10-23 13:43 UTC, AntoineVDV approved these changes
@robodoo r+

2023-10-23 21:06 UTC, closed without merging