[IMP] project: unarchive tasks on quotation confirm
odoo/odoo pull request #139010
Opened 2023-10-18 08:36 UTC by arg-odoo

When a project template have some archived task and a (service) product template duplicate the project, the tasks are copied on quotation confirm but the archived one remain archived.

To reproduce behavior:
- Install `sale_project`
- Create a billable project as template
- Create steps and tasks (archive at least one task)
- Create a service product with create project & task on order then select your project template
- Create a quotation with the product freshly created and confirm it
- Go tho the Project created for SO and see that the (archived) tasks are not unarchived.
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-18 08:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139010).

2023-10-23 09:09 UTC, auon-odoo approved these changes

2023-12-29 15:57 UTC, auon-odoo requested changes
Thanks for your work :slightly_smiling_face:

2023-12-29 15:57 UTC, auon-odoo commented on addons/project/tests/test_project_base.py
> +            "project_id": self.project_pigs.id})
```suggestion
            "project_id": self.project_pigs.id,
        })
```

2023-12-29 15:57 UTC, auon-odoo commented on addons/project/tests/test_project_base.py
> +        duplicated_pigs_tasks = _get_all_tasks(duplicated_pigs_project.id)
But why make it dynamic?
Shouldn't we just create one project with one task and work with that?

2023-12-29 15:57 UTC, auon-odoo commented on addons/sale_project/tests/test_sale_project.py
> +        project_template.write({'active': False,})
This can go in create vals

2023-12-29 15:57 UTC, auon-odoo commented on addons/sale_project/tests/test_sale_project.py
> +        tasks = self.env['project.task'].with_context(active_test=False).search([("project_id", "=", sale_order.project_ids.id)])
Again, is the search necessary?

2023-12-29 15:57 UTC, auon-odoo commented on addons/sale_project/models/sale_order_line.py
> +            tasks.write({'active': True})
```suggestion
            project.with_context(active_test=False).tasks.active = True
```
Doesn't that accomplish the same thing?

2023-12-29 15:57 UTC, auon-odoo commented on addons/project/models/project_project.py
> +            tasks.write({'active': True})
```suggestion
        if not self.active:
            project.with_context(active_test=False).tasks.active = True
```
Doesn't that accomplish the same thing?

2023-12-29 15:57 UTC, auon-odoo commented on addons/project/models/project_project.py
> +        if not default.get('active') and not self.active:
```suggestion
        if not default.get('active'):
```
Is this second condition necessary?

2024-01-26 13:28 UTC, auon-odoo reviewed
Self review

2024-01-26 13:28 UTC, auon-odoo commented on addons/project/tests/test_project_base.py
> +        project.active = False
Task is not active

2024-01-26 13:28 UTC, auon-odoo commented on addons/project/tests/test_project_base.py
> +            'partner_id': self.partner_1.id,
Not relevant

2024-01-26 13:28 UTC, auon-odoo commented on addons/project/tests/test_project_base.py
> +        self.assertEqual(project_dup.with_context(active_test=False).task_count, 1, "Duplicated project should have as many tasks as orginial project")
Is active_test needed?

2024-01-26 13:28 UTC, auon-odoo commented on addons/sale_project/tests/test_sale_project.py
> +
Put that in the test

2024-01-26 13:28 UTC, auon-odoo commented on addons/sale_project/tests/test_sale_project.py
> +        tasks = sale_order.project_ids.tasks.with_context(active_test=False)
Is active_test needed?

2024-01-30 09:41 UTC, pkyriakou reviewed
Thank you for the updates and work. I don't really see anything to comment on. LGTM

2024-04-25 08:36 UTC, xavierbol approved these changes
robodoo r+

2024-04-25 15:38 UTC, robodoo commented
@arg-odoo @xavierbol staging failed: ci/runbot (view more at https://runbot.odoo.com/runbot/build/61829479)

2024-04-29 06:21 UTC, xavierbol commented
robodoo retry

2024-04-29 19:15 UTC, closed without merging