[IMP][FIX] website_forum: fix links and buttons
odoo/odoo pull request #139206
Opened 2023-10-19 13:12 UTC by edi-odoo

f36339236786fe95b9433ac3fd27bc1523839d20
On Safari, `<tr>` elements don't support `position: relative`.
The cleanest solution was to switch the table for a CSS grid.

By doing so the DateTime function on the last activity column broke.
This had been fixed thanks to Florian (flg)'s help.

933f31261474918b9a0db4590136c3bce59f2446
There wasn't enough space for the "New Post" button in the header on
mobile. We moved it to the bottom of the screen.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-19 13:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139206).

2023-10-20 14:21 UTC, Brieuc-brd commented
Hey @edi-odoo, thanks for your work 👍 

Regarding the "New Post" button, I'm not sure moving it to the very bottom is the best idea, because when the floating contact button is displayed, it appears above the "Message" button :
![Capture d’écran 2023-10-20 à 15 19 41](https://github.com/odoo/odoo/assets/80679690/c463fc4a-4f93-4b51-b650-9cc197fde6b4)

Why not use `flex-wrap` for navigation and maybe use `flex-fill` for the main button?
![Capture d’écran 2023-10-20 à 15 26 49](https://github.com/odoo/odoo/assets/80679690/7cecb6ce-55da-4a9e-bda0-4c1d821ac4cf)
![Capture d’écran 2023-10-20 à 15 26 41](https://github.com/odoo/odoo/assets/80679690/36fdc433-fd3a-4e34-9ceb-0378226e7e58)

About the Safari issue, I like the fact that you're using a grid instead of a table, but I'm afraid the amount of change is too huge to be added in Stable. I think this improvement should be made in master, what do you think @stefanorigano ?.

I've done some research* and it seems that using `transform: scale(1);` on `tr` might do the trick :) 
Could you try it ? Don't forget to test also on iOS since is related to Apple software :)

*https://stackoverflow.com/questions/8501727/table-row-wont-contain-elements-with-positionabsolute#:~:text=Use%20this%20hack%20as%20position%3A%20relative%20is%20ignored%20in%20%3Ctr%3E%20(thanks%20to

2023-10-26 11:43 UTC, edi-odoo commented
> Hey @edi-odoo, thanks for your work 👍
> 
> Regarding the "New Post" button, I'm not sure moving it to the very bottom is the best idea, because when the floating contact button is displayed, it appears above the "Message" button : ![Capture d’écran 2023-10-20 à 15 19 41](https://user-images.githubusercontent.com/80679690/276956961-c463fc4a-4f93-4b51-b650-9cc197fde6b4.png)
> 
> Why not use `flex-wrap` for navigation and maybe use `flex-fill` for the main button? ![Capture d’écran 2023-10-20 à 15 26 49](https://user-images.githubusercontent.com/80679690/276957023-7cecb6ce-55da-4a9e-bda0-4c1d821ac4cf.png) ![Capture d’écran 2023-10-20 à 15 26 41](https://user-images.githubusercontent.com/80679690/276957019-36fdc433-fd3a-4e34-9ceb-0378226e7e58.png)
> 
> About the Safari issue, I like the fact that you're using a grid instead of a table, but I'm afraid the amount of change is too huge to be added in Stable. I think this improvement should be made in master, what do you think @stefanorigano ?.
> 
> I've done some research* and it seems that using `transform: scale(1);` on `tr` might do the trick :) Could you try it ? Don't forget to test also on iOS since is related to Apple software :)
> 
> *https://stackoverflow.com/questions/8501727/table-row-wont-contain-elements-with-positionabsolute#:~:text=Use%20this%20hack%20as%20position%3A%20relative%20is%20ignored%20in%20%3Ctr%3E%20(thanks%20to

Thanks a lot @Brieuc-brd , that scale hack seems to work great. I've also moved the button as you suggested.

2023-10-26 12:33 UTC, Brieuc-brd requested changes
Hey @edi-odoo, thanks for the work, much lighter :)
Just a few comments below

2023-10-26 12:33 UTC, Brieuc-brd commented on addons/website_forum/views/forum_forum_templates_layout.xml
> +            <div t-attf-class="d-flex justify-content-lg-end gap-2 flex-grow-1 flex-wrap flex-lg-nowrap w-100 w-lg-auto #{'mw-xl-75' if search else 'mw-xl-50'}">
I'd go with `flex-md-nowrap`, otherwise the "New Post" Button is too big when screen is higher than md.

2023-11-06 09:42 UTC, Brieuc-brd approved these changes
Don't forget to update your commit links in the PR description ;) 
Beside that LGTM.

Make sure that the branch is green too ;)

2023-11-16 11:26 UTC, edi-odoo commented
@flch-odoo could you check this please ? Thanks !

2023-11-20 11:30 UTC, edi-odoo commented
> @flch-odoo could you check this please ? Thanks !

or @tde-banana-odoo ?

2023-12-06 13:54 UTC, flch-odoo commented
Hello @edi-odoo , this looks good to me. 
It could be argued that these could wait for 17.0 if not master, but I'll leave that to my +1 :)

2023-12-12 08:19 UTC, tde-banana-odoo commented
@robodoo r+ rebase-merge

2023-12-12 08:20 UTC, robodoo commented
Merge method set to rebase and merge, using the PR as merge commit message.

2023-12-12 09:50 UTC, closed without merging