[FIX] point_of_sale,l10n_be_pos_sale: invoice settled order
odoo/odoo pull request #139467
Opened 2023-10-23 12:08 UTC by robinengels

Current behavior:
In Belgium when using a EU intracom tax, as we need to report those special sales to the government we need to create an invoice as we need to report the customer name, VAT number and the country where the goods are going to end up

Steps to reproduce:
- Create an order with a product and a tax (0% EU M)
- Settle the order in the PoS and pay it (no invoice)
- Go to the accounting and check the EC Sales List report
- There is an error shown in the report

opw-3514737
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-23 12:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139467).

2023-10-26 11:04 UTC, JulienAlardot requested changes
IMO we should force the creation of the invoice, else it would still break everything I will ask the POs for specifications

Please update the commit message to reflect the real issue
- ?In Belgium? when using a EU intracom tax, as we need to report those special sales to the government we need to create an invoice as we need to report the customer name,  VAT number and the country where the goods are going to end up
Side-note: Another Belgian requirement in most cases is a document proving the goods will cross borders (if the goods aren't delivered but pick up directly)

2023-10-26 15:37 UTC, tsb-odoo commented
To me, this PR is reacting to a symptom (namely highlighting problems with the EC Sales List because contextually, it was the concern that triggered this PR) but there are other aspects to reconsider in depth. 

Wouldn't it be wiser to consider downpayments as invoices in any case ? 
There is an open conversation about this (namely task 2786723) but also legal evolutions one should know. Does it really concern Belgium only ? 
https://entreprendre.service-public.fr/vosdroits/F31412#:~:text=Depuis%20le%201er%20janvier,r%C3%A9ception%20de%20la%20facture%20finale.

2023-10-30 12:20 UTC, JulienAlardot commented
@tsb-odoo So? We want this fix and rework that case on the side or we don't want this fix and rework that case on the side?
@robinengels @caburj Do you know anything about that case that could answer tsb questions?

2023-11-14 10:50 UTC, robinengels commented
@tsb-odoo @JulienAlardot ping

2023-11-28 10:42 UTC, robinengels commented
@tsb-odoo @JulienAlardot @caburj ping

2023-12-01 12:42 UTC, caburj requested changes
I'm okay with this patch unless @tsb-odoo really thinks this is a mistake.

2023-12-01 12:42 UTC, caburj commented on addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
> +        async toggleIsToInvoice() {
```suggestion
        toggleIsToInvoice() {
```

Don't change the "color" of the function, we should keep it synchronous.

2023-12-01 12:42 UTC, caburj commented on addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
> +                await this.showPopup('ErrorPopup', {
```suggestion
                this.showPopup('ErrorPopup', {
```

2023-12-01 12:42 UTC, caburj commented on addons/l10n_be_pos_sale/static/src/js/ProductScreen.js
> +        }
You can remove this since you're not adding anything in the setup logic.

2023-12-07 13:07 UTC, robinengels commented
@tsb-odoo does this look ok to you ?

2023-12-15 12:40 UTC, robinengels commented
@caburj You might need to R+ this one again

2023-12-15 14:38 UTC, robodoo commented
@robinengels @caburj staging failed: ci/runbot on 5699906808539f79c7c9d670b39ab68c63d1dca9 (view more at https://runbot.odoo.com/runbot/build/55176288)

2023-12-20 15:12 UTC, caburj commented
robodoo r+

2023-12-20 17:01 UTC, closed without merging