[FIX] web, hr_homeworking: fix after calendar revamp
odoo/odoo pull request #139736
Opened 2023-10-25 13:12 UTC by leonardopavanrocha

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-25 13:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139736).

2023-11-03 14:17 UTC, d-fence commented
Upgrade exception [#266](https://runbot.odoo.com/web/#id=266&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
view:calendar.res_config_settings_view_form
```
cc @KangOl @nseinlet

2023-11-03 14:52 UTC, KangOl requested changes

2023-11-03 15:20 UTC, tivisse commented
@robodoo r+ rebase-ff

2023-11-03 15:21 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-11-04 02:02 UTC, closed without merging