[IMP] sale,sale_management: improve the sale configration setting
odoo/odoo pull request #139805
Opened 2023-10-26 05:27 UTC by nikj-odoo

**Version**

- master

**Improvement**

In this PR, aims to enhance the Sale Configuration Settings by removing the default value sections. Additionally, it allows for separate modification of online signature and online payment settings at the first level. Several label modifications have been made, and appropriate descriptive messages have been added for the Online Signature and Online Payment options.

Current behavior before PR:

- The default section serves as the primary section, with both online signature and online payment falling under it.
- online signature and online payment not descriptive.

Desired behavior after PR is merged:

- remove default value section.
- online signature and online payment at the first level.
- appropriate messages for online signature and online payment.
- change label prepayment amount to **Payment**. 
- separate section of default quotation validity.

task-3546062

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-26 05:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/139805).

2023-11-06 11:41 UTC, vava-odoo requested changes
Hi @nikj-odoo and @mish-odoo 
Thanks for this work. Please have a look at my comments below.
Also, I think this should be targeting 17.0, not master.
Cheers

2023-11-06 11:41 UTC, vava-odoo commented on addons/sale/wizard/res_config_settings_views.xml
> +                                <field name="prepayment_percent" widget="percentage" style="width: 3rem"/>
```suggestion
                                <field name="prepayment_percent" widget="percentage" class="oe_inline"/>
```

2023-11-06 11:41 UTC, vava-odoo commented on addons/sale/wizard/res_config_settings_views.xml
> +                            <div class="mt16" title="Days between quotation proposal and expiration. 0 days means automatic expiration is disabled">
This class doesn't look useful, is it?
```suggestion
                            <div title="Days between quotation proposal and expiration. 0 days means automatic expiration is disabled">
```

2023-11-06 11:41 UTC, vava-odoo commented on addons/sale/wizard/res_config_settings_views.xml
> +                                <field name="quotation_validity_days" class="text-center" style="width: 5rem;"/>
3 should be more than enough
```suggestion
                                <field name="quotation_validity_days" class="text-center" style="width: 3rem;"/>
```

2023-11-06 13:35 UTC, nikj-odoo commented
Hello @vava-odoo,

I have added the changes you suggested above. Some of the changes were not modified by me, but I still improved the code.

Thanks for the suggestions.

2023-11-06 14:05 UTC, vava-odoo approved these changes

2024-01-09 11:09 UTC, Feyensv commented on addons/sale/wizard/res_config_settings_views.xml
> +                                      groups="base.group_multi_company"/>
The company_dependent label was missing for the quotation validity days, I pushed to add this part ;).

2024-01-09 11:10 UTC, Feyensv commented
@robodoo r+

2024-01-09 20:40 UTC, closed without merging