[FIX] website: increase the timeout of the website_form_editor_tour test
odoo/odoo pull request #140058
Opened 2023-10-27 08:55 UTC by loco-odoo

When running the `website_form_editor_tour` test, it may sometimes fail due to a `Script timeout exceeded` error. As there is a high number of steps in this test, it may happen that the process takes longer than the default attributed 60 seconds to perform one of the steps. To resolve the problem, a longer timeout has been set for this step.

runbot-24988

2023-10-27 08:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140058).

2023-11-29 18:28 UTC, rdeodoo requested changes
Why refactoring the code to use util in Odoo 15?
It's already done in later version.
ANd it seems to be the reason (using the utils) why you need to split the file in commit 1 to avoid error about `Missing dependencies:['website.tour_utils'`

It's also unclear what is being fixed in commit 1, it just mention it's now using the utils but not why. We don't do refactoring in stable version, which is what it looks like without an explanation as why it's really needed (if there is any)

Isn't commit 2 about splitting the tour enough?

Could you please elaborate :) ?

2023-11-29 18:28 UTC, rdeodoo commented on addons/website/static/tests/tours/website_form_editor.js
> +        ...wTourUtils.clickOnEditAndWaitEditMode(),
You can then remove `extra_trigger: 'button[data-action="save"]'` in next step to be correct

2023-11-29 18:28 UTC, rdeodoo commented on addons/website/static/tests/tours/website_form_editor.js
> +        ...wTourUtils.clickOnSave(),
Same here, next step you can remove ` trigger: 'body:not(.editor_enable)',` to be correct

2023-12-04 08:33 UTC, loco-odoo commented
@rdeodoo , as I had to touch this part of the code, I thought it was a good idea to introduce the the utils of the website tour. But indeed, I understand the policy of not refactoring in stable version. I removed the first commit and only let the second one in which I divided the code in three parts :+1:

2023-12-05 12:32 UTC, rdeodoo reviewed
I was about to approve the PR (and consider r+) and actually wrote this: 

> Tour goes from ~50 seconds before this PR to 15/10/25 sec which will save ourselves from adding a 90s explicit timeout

And then went to check other versions to see what happened there as our forms got more and more features and so I thought probably more tests too, so I was wondering if we wouldn't have done anything in those version to help with this timeout and actually saw that: https://github.com/odoo/odoo/commit/701a775ec4c16a1adfab62e15a2d56b3933e0057

Why is this just not a backport of this change at the end?
This reasoning is always something that you should do: check in other versions how it behaves first (in both ways, from older to earlier version or like here from older to earlier).

2023-12-06 11:16 UTC, rdeodoo approved these changes
@robodoo r+

Let's not overthink it in Odoo 15: simple backport with larger timeout

If the 120 timeout in later versions is judge problematic at some point, we will see what can we do

2023-12-06 12:36 UTC, closed without merging

2023-12-06 13:09 UTC, rdeodoo commented
@fw-bot up to saas-15.2 (maybe not too late?)

It's actually already in Odoo 16, there is a small typo about it in the commit message:
> as already done in this commit for the version **17**