[IMP] web: fix dropdown-item checkmark position
odoo/odoo pull request #140269
Opened 2023-10-30 10:17 UTC by xlu-odoo

Prior to this commit, the positioning of the checkmark in the project task state dropdown was slightly off, not optimally aligned.

This commit solves this alignment.

<table>
<tr>
 <td>Before</td>
 <td> After</td>
<tr>
 <td>
 <img width="264" alt="before" src="https://github.com/odoo/odoo/assets/80678921/5fbff066-e32b-4b78-ac8c-b344089ba89e">
</td>
 <td><img width="264" alt="after" src="https://github.com/odoo/odoo/assets/80678921/0a4aae9c-9a25-40b3-89b6-02b637f31725">
 </td>
</table>

task-3575446

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-30 10:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140269).

2023-10-30 13:23 UTC, xlu-odoo commented on addons/web/static/src/webclient/webclient.scss
> +        transform: translate(-1em, 75%);
Good idea imo. Updated 👍 thanks

2023-10-30 13:53 UTC, chgo-odoo approved these changes
Thanks @xlu-odoo LGTM, you can remove the draft state  👍

2023-10-30 14:33 UTC, xlu-odoo commented
@pparidans can you look at this PR and eventually merge? Thanks 🙏

2023-10-30 15:30 UTC, Brieuc-brd commented
Hey @xlu-odoo 👋 

I just quickly checked your PR, and I think it should target `saas-16.3` since this issue appears from this version.

Could you check?

2023-10-30 15:49 UTC, xlu-odoo commented
> Hey @xlu-odoo 👋
> 
> I just quickly checked your PR, and I think it should target `saas-16.3` since this issue appears from this version.
> 
> Could you check?

Thanks @Brieuc-brd , retargeted it

2023-10-31 13:08 UTC, pparidans requested changes
Well actually it breaks the SearchPanel's Filter/Group by selected state :
![image](https://github.com/odoo/odoo/assets/33146/25e2ca7d-e6de-4743-98b1-1784689b52c6)

2023-11-02 07:28 UTC, Brieuc-brd commented
Thanks for the review @pparidans.
@xlu-odoo is off for the moment, I updated the branch to change the margin of the dropdown item instead of the main scss. Could you take a look?

2023-11-07 07:29 UTC, Brieuc-brd commented
@stefanorigano 👋 
Little reminder :)

2023-11-17 08:11 UTC, stefanorigano reviewed
Hello @xlu-odoo , thanks.
Could you rebase your branch, runbot is red,
Thanks again

2023-11-17 13:45 UTC, xlu-odoo commented
> Hello @xlu-odoo , thanks. Could you rebase your branch, runbot is red, Thanks again

Rebased (and green) @stefanorigano  :)

2023-11-17 14:00 UTC, stefanorigano approved these changes
Thanks @xlu-odoo , LGTM 👍 

@pparidans , could you have a look? thanks

2023-11-20 09:42 UTC, pparidans approved these changes
@robodoo r+

2023-11-20 13:32 UTC, closed without merging