[FIX] website: Masonry block z-index
odoo/odoo pull request #140397
Opened 2023-10-30 18:17 UTC by Armin-FalDiS

### Description of the issue/feature this PR addresses:
Steps:
- Install `website_sale`
- Go the website editor
- Add a masonry block
- Add "Add to Cart" button on the upper left tile of the masonary block
- Select a product with variants for the "Add to Cart" button
- Save the page
- Press the "Add to Cart" button on the masonry block

### Current behavior before PR:
The z-index of the other 3 tiles of the masonry block are more than the dialog modal. This makes them cut appear on top of the product selection modal.

### Desired behavior after PR is merged:
This fixes the z-index of the faulty elements within the masonry block template.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-30 18:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140397).

2023-11-13 09:21 UTC, Armin-FalDiS commented
This fix should potentially fix any and all problems arising from misplaced product configurator dialog and conflicting z-indexes for it including but not limited to the masonry block.

2023-11-13 10:01 UTC, qsm-odoo requested changes
Thanks for the fix :+1: Some comments, see below :pray: 

Commit message:
- `masonary` -> `masonry`
- Max 72 characters per line
- No uppercase in the title
- The title should complete the sentence "when applied, this commit will ...", so start with a verb
- Since your PR is related to a ticket, the message should end with `opw-XXX` on its own line where `XXX` is the id of the ticket. So here `opw-3529537` I think?

2023-11-23 14:47 UTC, Feyensv commented on addons/website_sale_product_configurator/static/src/js/product_configurator_modal.js
> +        }
the `OptionalProductsModal` is also instantiated in backend flows (cf `sale_product_configurator` module) ;).
(It's not the case in 17.0 anymore, where the backend now uses a new configurator made in OWL)

2023-12-05 11:23 UTC, Armin-FalDiS commented
@odoo/rd-ecommerce 
Should this be changed or be part of the master refactoring?
I believe the only thing that needs the be changes is the use of jQuery.

2023-12-08 12:59 UTC, Feyensv commented
> @odoo/rd-ecommerce Should this be changed or be part of the master refactoring? I believe the only thing that needs the be changes is the use of jQuery.

Wdym ? what should be changed ?
As you're working in stable, you should solve the problem you're facing with minimal changes.

2023-12-08 13:47 UTC, Armin-FalDiS commented
> > @odoo/rd-ecommerce Should this be changed or be part of the master refactoring? I believe the only thing that needs the be changes is the use of jQuery.
> 
> Wdym ? what should be changed ? As you're working in stable, you should solve the problem you're facing with minimal changes.

I mean I am not sure about the state of this PR. Should I change something more or does the current code fix the problem or should I close the PR, ... ?

2024-02-16 09:37 UTC, Armin-FalDiS commented
As it was discussed with @odoo/rd-fun-sale, since this was reworked in 17 and fixing this in any form would break way too many tests, I am closing this.

2024-02-16 09:37 UTC, closed without merging