[FIX] planning: fix groupBy column width
odoo/odoo pull request #140412
Opened 2023-10-31 05:28 UTC by jala-odoo

Steps:
- Open Planning
- Click on search bar menu dropdown

Issue:
- The groupBy column width is more than expected.

Cause:
- The width shows bigger than expected because of not giving the max-width value and property to the scss and that's why the column width takes the width of longest string in the selection field.

Fix:
- Add the max-width property to the scss and give the appropriate value.

task-

2023-10-31 05:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140412).

2023-11-07 12:54 UTC, rfr-odoo requested changes
Not the right fix IMO as the problem is the `select.o_add_custom_group_menu` that have an `option` elements with big values.
e.g.:
* Modified Since Last Publication
* This Shift Was Copied From Previous Week
* ...

2023-11-07 13:29 UTC, jala-odoo commented
@rfr-odoo
Oops! I forget to do this PR draft, the task is still in progress.

2023-12-21 15:06 UTC, pkyriakou reviewed
Thank you @jala-odoo 
I have nothing to comment on :raised_hands: LGTM :green_circle:

2024-01-11 12:03 UTC, xavierbol reviewed
Thanks for your work, I will let @odoo/rd-framework-js do the final review of that PR. 🙂

2024-01-12 09:31 UTC, aab-odoo commented
@rfr-odoo

2024-01-12 12:29 UTC, aab-odoo commented
Would fix opw 3670063

2024-01-15 10:33 UTC, rfr-odoo commented
Hi, can you add a media breakpoint to avoid applying the rule on small screen and so avoid to break mobile style. Thx.

2024-01-16 08:22 UTC, rfr-odoo commented
@robodoo r+

2024-01-16 09:53 UTC, closed without merging