[FIX] hr_attendance: review mobile layout
odoo/odoo pull request #140454
Opened 2023-10-31 10:46 UTC by chgo-odoo

2023-10-31 10:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140454).

2023-11-04 13:30 UTC, stefanorigano requested changes
Hello @chgo-odoo , very good, thanks 👍 

Some remarks:
- Adapt the PR/commit description since these changes affects desktop as well (not just mobile
- There's a conflict, you should rebase 😉
- [FP] Invert "Since" and "Before" position, it's more logical in chronological order 

| This PR. | Proposal |
|--------|--------|
| ![image](https://github.com/odoo/odoo/assets/8558351/f9edbcf0-095e-478d-a2c9-8552c570ac67) | ![image](https://github.com/odoo/odoo/assets/8558351/0ca83c45-7902-4b0e-b4fc-15fe2d11c2bc) | 

- [FP] **IF** all entries are visible ("Since", "Before" and "total today") , render the button inside the grey box.  

| This PR. | Proposal |
|--------|--------|
| ![image](https://github.com/odoo/odoo/assets/8558351/f9edbcf0-095e-478d-a2c9-8552c570ac67) | ![image](https://github.com/odoo/odoo/assets/8558351/420b9f8a-11f4-4588-bcdf-734fe8511c87) | 

...the rest in the code, thanks!

2023-11-04 13:30 UTC, stefanorigano commented on addons/hr_attendance/static/src/components/attendance_menu/attendance_menu.xml
> +        <Dropdown position="'bottom-end'" beforeOpen.bind="searchReadEmployee" menuClass="`p-2 ${ ui.isSmall ? 'd-flex flex-column' : ''}`">
Adding `d-flex flex-column` on mobile look unnecessary... leftovers from a prev. implementation?

2023-11-04 13:30 UTC, stefanorigano commented on addons/hr_attendance/static/src/components/attendance_menu/attendance_menu.xml
> +        <Dropdown position="'bottom-end'" beforeOpen.bind="searchReadEmployee" menuClass="`p-2 ${ ui.isSmall ? 'd-flex flex-column' : ''}`">
I'd suggest adding a `pb-3` 😉

2023-11-04 13:30 UTC, stefanorigano commented on addons/hr_attendance/static/src/components/attendance_menu/attendance_menu.scss
> +    font-variant-numeric: tabular-nums;
Note for the posterity: one day we should create an utility class for this 🤔

2023-11-04 15:48 UTC, chgo-odoo commented
Hi @stefanorigano, thanks for the detailed review !

I've made the requested changes, if you could have a look at it?

Thanks !

2023-11-05 09:17 UTC, stefanorigano approved these changes
Perfect, thanks @chgo-odoo 👍

2023-11-05 09:36 UTC, stefanorigano commented
@odoo/rd-hr , FYI, design approved by FP.
Could you have a look  and eventually r+ ?
Thanks!

2023-11-06 08:13 UTC, sofiagvaladze commented
@chgo-odoo thanks for your work :raised_hands: 

Can you delete empty enterprise branch and after that rebase and push community branch? 

Once it's green, I will merge it :rocket:

2023-11-06 08:34 UTC, chgo-odoo commented
Hi @sofiagvaladze thanks for taking care of this one 👋

I just deleted the empty enterprise branch and rebased community as requested but runbot keeps building that empty branch 🫣

2023-11-06 08:39 UTC, sofiagvaladze commented
@chgo-odoo it seems good now :crossed_fingers: thanks!

2023-11-06 09:38 UTC, sofiagvaladze commented
@chgo-odoo unrelated error is failing.. the thing is, even if I were to r+ it, it won't be merged unless runbot is green.

Rebase and push again in a bit and tag me once the branch is ready :rocket:

2023-11-06 13:54 UTC, chgo-odoo commented
Thanks @sofiagvaladze !

Runbot is (finally) green, can we move this forward? 🚀

Cheers !

2023-11-06 14:31 UTC, sofiagvaladze commented
robodoo r+

2023-11-06 16:55 UTC, closed without merging