[IMP] point_of_sale: split create payment move entry logic
odoo/odoo pull request #140605
Opened 2023-10-31 19:33 UTC by alejandromellado

Description of the issue/feature this PR addresses:

- Odoo's default behavior is to create a journal entry for the invoice payment ('entry'), splitting the logic used to create this entry into a new function would allow l10n modules to alter this behavior.

Current behavior before PR:

- Currently an 'entry' is generated when triggering invoicing for an order when the POS session has been closed and the function to create said record is not exposed to l10n modules.

Desired behavior after PR is merged:

- Split the logic responsible for creating the journal entry into another function, allowing it to be extended or altered by l10n modules.
- As an example of the use case would be Mexico EDI, where a refund ('out_refund') needs to be generated instead of an entry additional to the customer invoice for correct tax purposes after the POS session has been closed.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-10-31 19:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140605).

2024-04-17 20:15 UTC, jco-odoo commented
@luistorresm I do not see immediately how it brings big benefits in the inheritance in comparison with inheriting immediately from _create_payment_moves.  Maybe with a _prepare_values or something.  But it is up to @caburj

2024-04-24 09:19 UTC, caburj commented
This seems to be a refactoring, can you change the tag of the commit title to "[REF]"? You can actually go further and extract the logic that calculate the vals for credit and debit.

2024-04-29 13:00 UTC, caburj requested changes
you missed passing the 'is_reverse' arg. Let's also take this opportunity to make the 'prepara_vals' util methods to accept the payment move and use it.

2024-04-29 13:00 UTC, caburj commented on addons/point_of_sale/models/pos_payment.py
> +            'partner_id': accounting_partner.id if is_split_transaction and is_reverse else False,
```suggestion
            'partner_id': accounting_partner.id if is_split_transaction and is_reverse else False,
            'move_id': payment_move.id,
```

2024-04-29 15:47 UTC, luistorresm commented on addons/point_of_sale/models/pos_payment.py
> +            'partner_id': accounting_partner.id,
Done

2024-04-29 15:47 UTC, luistorresm commented on addons/point_of_sale/models/pos_payment.py
> +            'partner_id': accounting_partner.id if is_split_transaction and is_reverse else False,
Done

2024-06-25 21:41 UTC, luistorresm commented
Hello @caburj 

Would you happen to have any news about this?

Regards

2024-07-01 09:27 UTC, caburj commented
robodoo r+

2024-07-01 10:50 UTC, closed without merging