[FIX] web, timesheet: fix day selection arrow & responsiveness
odoo/odoo pull request #140750
Opened 2023-11-02 15:24 UTC by mano-odoo

In commit f9222c4976a78c2f02264db897bc9826bbda0944 the class `order-3` is applied on the ViewScaleSelector component but it breaks the view in timesheet. This commit creates a props to contextually use this class on the component.

task-3580643

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-05 11:17 UTC, stefanorigano reviewed
Thanks, I've added a remark in the enterprise branch.
@edi-odoo , could you double-check the visual result on screen?

@mano-odoo , once enterprise is done and EDI confirms you can move to tech. review, thanks!

edit/update: there are conflicts

2023-11-06 07:38 UTC, edi-odoo approved these changes
Looks good ! Thank you for fixing this :D

2023-12-01 08:13 UTC, Iucapad requested changes

2023-12-01 08:13 UTC, Iucapad commented on addons/web/static/src/views/view_components/view_scale_selector.js
> +        dropdownClasses: { type: String, optional: true },
Thanks for the fix. Can you just rename dropdownClasses to `dropdownClass`? To have a similar name with the props of the dropdown togglerClass

Once it’s done I’ll approve it

2023-12-01 09:11 UTC, Iucapad approved these changes
Thank you

2023-12-01 09:12 UTC, Iucapad commented
@robodoo r+

2023-12-04 12:41 UTC, xavierbol commented
robodoo r+

2023-12-04 14:47 UTC, closed without merging