Master reorder product tags loti
odoo/odoo pull request #140965
Opened 2023-11-03 13:39 UTC by ltinel

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-03 13:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140965).

2023-12-01 14:18 UTC, vava-odoo requested changes
Hi @ltinel 
Looks good. Just a question and two small remarks.
Cheers

2023-12-01 14:18 UTC, vava-odoo commented on addons/product/models/product_tag.py
> +    sequence = fields.Integer(string='Sequence')
Shouldn't there be a default? Or it is ok to be the first one after creation?
Also, I know examples around it don't follow this remark but there is no need to define the string if it is the same as the name of the field.
```suggestion
    sequence = fields.Integer()
```

2023-12-01 15:41 UTC, ltinel commented on addons/product/models/product_product.py
> +            product.all_product_tag_ids = (product.product_tag_ids | product.additional_product_tag_ids).sorted(lambda t: t.sequence)
Done :)

2023-12-01 15:50 UTC, vava-odoo approved these changes

2024-02-05 15:09 UTC, AntoineVDV approved these changes
@robodoo r+

2024-02-05 20:04 UTC, closed without merging