17.0 finetune pms anko
odoo/odoo pull request #140907
Opened 2023-11-03 11:17 UTC by anko-odoo

2023-11-03 11:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/140907).

2023-11-06 16:16 UTC, AntoineVDV requested changes

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_aps/models/payment_provider.py
> +
extra line
```suggestion
```

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_buckaroo/models/payment_provider.py
> +from odoo.addons.payment_buckaroo.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Import only `const` and replace usages of `SUPPORTED_CURRENCIES` by `const.SUPPORTED_CURRENCIES`.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_flutterwave/models/payment_provider.py
> +from odoo.addons.payment_flutterwave.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as for Buckaroo.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_mercado_pago/const.py
> +]
Could you check if there isn't a card brand typically added by Mercado Pago? If so, it'd make sense to enable it.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_mercado_pago/models/payment_provider.py
> +from odoo.addons.payment_mercado_pago.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_mercado_pago/models/payment_provider.py
> +
extra line
```suggestion
```

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_mollie/models/payment_provider.py
> +from odoo.addons.payment_mollie.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_paypal/models/payment_provider.py
> +from odoo.addons.payment_paypal.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_payulatam/models/payment_provider.py
> +from odoo.addons.payment_payulatam.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_razorpay/models/payment_provider.py
> +from odoo.addons.payment_razorpay.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 16:16 UTC, AntoineVDV commented on addons/payment_sips/models/payment_provider.py
> +from odoo.addons.payment_sips.const import SUPPORTED_CURRENCIES, DEFAULT_PAYMENT_METHODS_CODES
Same as above.

2023-11-06 17:05 UTC, AntoineVDV approved these changes
@robodoo r+ rebase-ff
@robodoo delegate+

2023-11-06 17:05 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-11-06 17:12 UTC, anko-odoo commented
@robodoo r+

2023-11-06 17:13 UTC, robodoo commented
I'm sorry, @anko-odoo: this PR is already reviewed, reviewing it again is useless.

2023-11-06 17:15 UTC, anko-odoo commented
@robodoo r+

2023-11-06 19:31 UTC, closed without merging