[IMP] web: calendar background color improvements
odoo/odoo pull request #141139
Opened 2023-11-06 09:21 UTC by edi-odoo

[IMP] web: calendar background color improvements

Following some changes in the `appointment` module, the calendar's
background colors can be handled with CSS variables.

task-3570053

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-06 09:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141139).

2023-11-07 09:23 UTC, edi-odoo commented on addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.xml
> +            t-attf-class="o_cw_popover_link o_event d-flex align-items-center gap-1 {{ getRecordClass(record) }} {{record.startHour ? 'o_event_dot' : 'o_event_allday'}} {{record.isHatched ? 'o_event_
No, not in Time Off and Planning for example. In calendar it's `o_attendee_status_tentative` and `o_attendee_status_declined` from the `appointment` module which have the same styles as `o_event_hatched` and `o_event_striked` respectively.

That being said, I just noticed the class is applied but not the styles. 
Looking into that now.

2023-11-16 10:11 UTC, Brieuc-brd requested changes
Thanks for your work @edi-odoo 👍 .

There's a lot of css customization, but I guess we have no choice :).
I've checked the structure of your code, commit by commit, and tested your branch on runbot. Some comments below.

**About your commits :** 
- Double check your commit titles, for some of these, module names are missing.
- 21f57a68559b3eb15b9f51a144d08eed3202a170 : Not very descriptive :/
- a75cff96338a1dc141b794077c864213f599dbfa : I guess it should be [FIX] Instead of [IMP]
- I have the feeling that some commits could be squashed, but I'll let @stefanorigano  verify that :)

About the targeting branch, I guess this is too big to be merged on stable, I think this should target `master`.

**Tablet issues :** 
|  |  |
|--------|--------|
| ![Capture d’écran 2023-11-16 à 10 24 30](https://github.com/odoo/odoo/assets/80679690/dbac6f12-10d7-4435-8242-3054c6387f8a)  | Wow, that’s a huge button ! Could it be sticky starting to a lower breakpoints like `position-md-static` instead of `position-lg-static`? |
| ![Capture d’écran 2023-11-16 à 10 28 11](https://github.com/odoo/odoo/assets/80679690/4d173fd3-4099-432f-a443-82e60b924e04) | Some issues on the screenshot |

**Mobile issue :** 
|  |  |
|--------|--------|
| ![Capture d’écran 2023-11-16 à 10 37 10](https://github.com/odoo/odoo/assets/80679690/78741afb-5604-4d9e-866c-5bc93231f004) | Background issue. Also, I’m wondering if we should set a min width for “week” and “month” views to be able to scroll horizontally and make events easier to read. |

**Dark mode contrast issues:**
|  |  |
|--------|--------|
| ![Capture d’écran 2023-11-16 à 10 41 32](https://github.com/odoo/odoo/assets/80679690/14215e8c-5163-4a16-bb7d-01c764c0bc99) | ![Capture d’écran 2023-11-16 à 10 42 51](https://github.com/odoo/odoo/assets/80679690/c71f819e-c0fb-4108-97cc-be193f56cb20) |

2023-11-20 11:18 UTC, edi-odoo commented
The darkmode issues have been fixed by the darkmode team in a separate PR ;)

2023-11-27 10:40 UTC, Brieuc-brd commented
> I can't replicate the buggy background color on the "week" in mobile view, did you refresh the page?

It appears when the screen width is less than 430px even if you refresh the page.
https://www.awesomescreenshot.com/video/22786225?key=306c3e24fbba7450c8ae38fa545e3aaf

2023-11-27 12:22 UTC, Brieuc-brd requested changes
Some comments below.
Also, I think you should add the task id in each commit description ;)

This PR is still huge in terms of css, I think it would be nice if @stefanorigano could check this PR :)

2023-11-27 12:22 UTC, Brieuc-brd commented on addons/hr_homeworking/static/src/calendar/common/popover/calendar_common_popover.xml
> +                        <div class="card-footer border-top d-flex gap-1" t-att-class="{ 'o_footer_shrink': !hasFooter }">
`border-top` should be after `gap-1`

2023-11-27 13:01 UTC, edi-odoo commented on addons/web/static/src/views/calendar/calendar_renderer.scss
> -            gap: map-get($spacers, 1 );
Not really

2023-11-28 15:49 UTC, stefanorigano requested changes
Temporarily on hold.
More info at task-3575827

2026-01-02 08:36 UTC, closed without merging