[REF] website, web: revert useless fixes after headers redesign
odoo/odoo pull request #141172
Opened 2023-11-06 12:17 UTC by robinlej

Commits [1] and [2] introduced separate fixes that are useless after the headers redesign in [3].
We remove the unneeded code in this commit.

[1]: https://github.com/odoo/odoo/commit/e10913d
[2]: https://github.com/odoo/odoo/commit/ce9b350
[3]: https://github.com/odoo/odoo/pull/119650

2023-11-06 12:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141172).

2023-12-01 16:23 UTC, qsm-odoo commented
@robodoo delegate=bso-odoo
@bso-odoo 

(if not required probably not to merge in 17.0 but in master ?)

2023-12-04 08:40 UTC, Guillaume-gdi reviewed
@robinlej Can you rebase on master please ?

2023-12-05 14:30 UTC, Guillaume-gdi requested changes
Just a nitpick.

I don't think we consider this type of a change a refactoring. It's just about removing dead code. The commit message should be `[REM] ...` or `[REV] ...` no ?

2023-12-06 14:34 UTC, Guillaume-gdi approved these changes
@robodoo r+

2023-12-06 18:55 UTC, closed without merging