[REF] account_bacs: rename account_bacs to l10n_uk_bacs
odoo/odoo pull request #141316
Opened 2023-11-06 17:49 UTC by moerradi

This commit renames the 'account_bacs' module to 'l10n_uk_bacs' to reflect its UK-specific implementation of the BACS payment system.

The renaming aligns with Odoo's convention for localization modules, ensuring it is not automatically installed on runbot environments.

This change prevents unnecessary installations on CI staging environments and improves clarity regarding the module's purpose and scope.

task-3517877

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-06 17:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141316).

2023-11-15 07:20 UTC, gawa-odoo approved these changes
LGTM

2023-11-16 08:11 UTC, gawa-odoo commented
I think you need to rebase, one of the tour fails consistently

2023-11-16 14:23 UTC, moerradi commented
@gawa-odoo fixed

2023-11-17 08:54 UTC, gawa-odoo approved these changes
LGTM

2023-11-21 12:15 UTC, FlorianGilbert requested changes
According to [documentation](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#tag-and-module-name), could you please change your tag name for `[MOV]` instead of `[REF]`. 

Thank you :smile:

2023-11-22 14:01 UTC, moerradi commented
on it !

2023-11-24 07:54 UTC, FlorianGilbert approved these changes
@robodoo r+

2023-11-24 08:00 UTC, robodoo commented
@moerradi @FlorianGilbert linked pull request(s) odoo/upgrade#5346 not ready. Linked PRs are not staged until all of them are ready.

2023-11-24 11:54 UTC, closed without merging