wip
odoo/odoo pull request #141516
Opened 2023-11-07 16:10 UTC by yosuanicolaus

wip

2023-11-07 16:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141516).

2024-03-27 16:25 UTC, qdp-odoo requested changes
after a discussion with Anotny, it has been decided to keep that branch as we want that someone trying to modify a posted invoice through RPC get blocked as well. The use case we wanted to cover with 2 users is just an extension of that peculiar case.

That being said, it's a behavior change we should probably save that for master, not to break other people's module.

Other than that, I don't get all the diff in the test.. can you explain?
thanks

2024-03-27 16:25 UTC, qdp-odoo commented on addons/account/models/account_move.py
> +                raise UserError(_("This move has been posted. The field you're trying to change is now readonly."))
need to add that to the .pot file

edit: actually, we don't care if we target master

2024-03-27 16:25 UTC, qdp-odoo commented on addons/account/models/account_move.py
> +        self.write({'auto_post': 'no'})
mmh that's not very elegant. Your code should be able to deal with that by doing
  `move_state = vals.get('state', move.state)`

2024-03-27 16:25 UTC, qdp-odoo commented on addons/account/tests/test_account_move_entry.py
> -
Why do you remove those asserts? They're still supposed to work after your commit :thinking:

2024-04-02 09:05 UTC, yosuanicolaus commented
Moved to the new master PR with the new changes.
https://github.com/odoo/odoo/pull/160096
@qdp-odoo

2024-04-02 09:05 UTC, closed without merging