[ADD] payment_xendit: new payment provider for Indonesia and Philippines
odoo/odoo pull request #141661
Opened 2023-11-09 09:19 UTC by nni-odoo

See the README.md file for more details.

2946329

task-2946329

See also:
- https://github.com/odoo/documentation/pull/6045

2023-11-09 09:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141661).

2023-11-24 09:17 UTC, nni-odoo commented
Hi @AntoineVDV , thanks for help closing the other PRs, I'm making final modifications on this one and ping you here (and discord) when ready! thanks!

2023-12-06 09:31 UTC, nni-odoo commented
@AntoineVDV oh apologies for that, I wasn't too familiar about the commits. I added some payment methods and payment provider for Philippines per FJA's request. Apologies again, won't happen next time

2023-12-06 09:35 UTC, nni-odoo commented
@AntoineVDV not sure if this helps, but I modified `payment_method_data.xml` and `payment_provider_data.xml` from payment/ module on my latest commit that I force-pushed

2023-12-07 17:12 UTC, AntoineVDV requested changes
Hello, overall the diff looks like you've done a good job and the PR should be ready for merge in no time :)

I pushed some commits with cosmetic or minimal changes and commented about the bigger issues below. Feel free to ask if you have questions about those changes.

There are two main issues to tackle:
- There are remnants of support for tokenization everywhere. They should be removed in this PR as we don't want to have dead code dangling just in case we add it later. If we do, it'll not be complicated to make the necessary adaptations.
- The payment flow implemented with this PR is typically a form-based redirection one, but you don't leverage `payment`'s tooling to achieve it. Except if it's not doable, you should override `payment.transaction`'s `_get_specific_rendering_values` method to prepare whatever must be prepared on Xendit's side and return the rendering context that will be passed to QWeb to render the "redirect form" (see `payment_flutterwave` for example). This should allow you to get rid of the entire JS and one controller.

Also, I saw that there is a [Payments](https://developers.xendit.co/api-reference/#payments-api) API flagged with a "New!" tag. Did you consider it? How does it differ from the Invoice API?

2023-12-08 06:25 UTC, nni-odoo commented on addons/payment/data/payment_method_data.xml
> +        <field name="code">paymaya</field>
ah that's a better idea indeed, thanks!

2023-12-11 03:23 UTC, nni-odoo commented on addons/payment/data/payment_provider_data.xml
> +               eval="[(6, 0, [
nice catch! missed it

2023-12-11 03:32 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +    _return_url = '/payment/status'
No, xendit doesn't return any values when redirecting. Instead, the payment status will be communicated through webhook(in their term a callback) instead

2023-12-11 03:53 UTC, nni-odoo commented on addons/payment_xendit/models/payment_provider.py
> +    xendit_api_key = fields.Char("Xendit API Key", groups="base.group_system")
got it!

2023-12-12 03:15 UTC, nni-odoo commented
Hello @AntoineVDV , based on my search on the documentation of payments API and discussion with Xendit team, the payments API differ from the invoice API (the one we're using) on the flow.
https://docs.xendit.co/payment-api/payment-api-flow
The most significant one is in payment API, customer has to do account linking and we'll have to handle all the payment flow in Odoo (I think it's like Stripe).
For invoice API, we are redirecting it to Xendit's side and so our job is to send the reference and amount to them, so payment flow is handled on their side.
In my opinion, invoice API still is the choice here for now, but let me know what you think or if you have further questions to Xendit and I can help you ask them. Hope it's clear!

2023-12-12 08:59 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +        }
yep that looks cleaner, will use form redirect approach instead!

2024-01-05 16:37 UTC, AntoineVDV commented on addons/payment_xendit/models/payment_provider.py
> +    _inherit = 'payment.provider'
tmp

2024-01-05 16:37 UTC, AntoineVDV commented on addons/payment_xendit/models/payment_provider.py
> +    xendit_api_key = fields.Char("Xendit API Key", groups="base.group_system")
The field name should still be `xendit_secret_key`.

2024-01-08 15:59 UTC, AntoineVDV commented
Hello @odoo/rd-security, could you have a look at this one?

ci/security build: https://runbot.odoo.com/runbot/batch/1278987/build/56106335
- **hmac**: used only to compare the signatures;
- **csrf=False**: to allow receiving webhook notifications from Xendit that are checked against the shared secret webhook token;
- **requests**: request made to a hard-coded URL with reasonable timeout

2024-01-08 16:01 UTC, AntoineVDV approved these changes

2024-01-09 10:32 UTC, d-fence commented
Upgrade exception [#291](https://runbot.odoo.com/web/#id=291&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
module:payment_xendit
```
cc @KangOl @nseinlet

2024-01-15 09:56 UTC, AntoineVDV commented on addons/payment_xendit/controllers/main.py
> +        expected_signature = tx_sudo.provider_id.xendit_webhook_token
> wait the "signature" is constant? how does this verify the transaction? edit: ok it's actually just a shared secret, so please don't call it signature https://docs.xendit.co/webhook/getting-started#validate-that-webhook-requests-are-coming-from-xendit

Indeed; forgot to mention that!

2024-01-15 09:58 UTC, AntoineVDV commented on addons/payment_xendit/controllers/main.py
> +            _logger.warning("Received notification with invalid signature.")
Support relies on these warnings to identify what and when something went wrong with the webhook.

2024-01-15 13:05 UTC, AntoineVDV commented on addons/payment_xendit/controllers/main.py
> +            _logger.warning("Received notification with invalid signature.")
> @AntoineVDV but then put information like `Received notification with invalid token %r`

@nni-odoo Can you do that? Usually, the signature is in the payload so we already have the information, but here the secret is indeed in the headers.

2024-01-16 01:19 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +        expected_signature = tx_sudo.provider_id.xendit_webhook_token
since `expected_signature` is only referred once, I'll just put it directly when doing `constseq`, thanks for the suggestion!

2024-01-16 02:29 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +        return request.make_json_response('')
was following some other payment providers' way to do it, but noted on this

2024-01-16 02:35 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +        :rtype: str
I was following other payment methods' webhook docstring (i.e. stripe, razoprpay, etc.) so it looked consistent

2024-01-16 02:37 UTC, nni-odoo commented on addons/payment_xendit/controllers/main.py
> +            _logger.warning("Received notification with invalid signature.")
@AntoineVDV noted, will log the received signature

2024-01-16 15:00 UTC, KangOl commented
Good news: runbot is green.
I will let @odoo/rd-security do the final security check.

2024-01-16 15:19 UTC, mart-e commented on addons/payment_xendit/controllers/main.py
> +            self._verify_notification_signature(received_signature, tx_sudo)
still not a signature

2024-01-16 16:05 UTC, AntoineVDV commented on addons/payment_xendit/controllers/main.py
> +            self._verify_notification_signature(received_signature, tx_sudo)
@nni-odoo Don't forget the comments too

2024-01-17 09:37 UTC, AntoineVDV approved these changes
@robodoo r+

2024-01-17 09:38 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2024-01-22 16:41 UTC, mart-e reviewed
@robodoo override=ci/security

2024-01-22 20:24 UTC, closed without merging

2024-01-31 13:17 UTC, AntoineVDV commented on addons/payment_xendit/README.md
> +[Invoices API](https://developer.flutterwave.com/docs/collecting-payments/standard/) as it
Should be https://developers.xendit.co/api-reference/#create-invoice

2024-01-31 13:18 UTC, AntoineVDV commented on addons/payment_xendit/README.md
> +[Invoices API](https://developer.flutterwave.com/docs/collecting-payments/standard/) as it
Should be https://developers.xendit.co/api-reference/#create-invoice