[FIX] account: create empty attachment if invoice not posted
odoo/odoo pull request #141640
Opened 2023-11-08 13:17 UTC by thle-odoo

Steps to reproduce:
-------------------
- create an invoice without confirm it;
- don't add account move line;
- go to the preview and download it;

Issue:
------
A traceback appears.

Cause:
------
We try to get `ids` field of a non "record" object (not the root cause). The root cause is that we don't create an attachment if the invoice is not posted. And to post an invoice, we must add line before confirm it.

Solution:
---------
Add the possibility to download an invoice that is not posted.

sentry-4612532780

2023-11-08 13:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141640).

2023-11-17 08:51 UTC, agr-odoo requested changes
This seems to work, but from saas-16.4 when the wizard generate the pdf for an invoice the document it is considered the "legal" one
So this patch has a side effect: if the user then confirm the invoice and try to send&print the system will sent the pdf of the draft invoice generated before

2023-11-17 13:46 UTC, agr-odoo approved these changes
Looks good, thanks

2023-11-17 13:46 UTC, agr-odoo commented
@smetl

2023-11-24 14:29 UTC, smetl commented
@robodoo r+

2023-11-25 02:43 UTC, closed without merging