[FIX] account: test switch of days
odoo/odoo pull request #141799
Opened 2023-11-13 12:12 UTC by gawa-odoo

If we begin to run the test at 23h59m59s, 
the move date could be put at a day 
and the freeze for the cron on the following day, and so, 
make the test fail.
Let's just define the day explicitely.

Linked to runbot error 36224

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-13 12:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141799).

2023-11-13 12:21 UTC, lordkrandel requested changes

2023-11-13 14:38 UTC, lordkrandel commented
Did you manage to somehow manually test it? If so, it LGTM.

2023-11-13 15:32 UTC, gawa-odoo commented
Manually test it? I tested it in local, and it indeed passes. 
I couldn't test it at midnight or close to it, but I don't see how it would break there now.

2023-12-07 09:51 UTC, epictete approved these changes
@robodoo r+

2023-12-07 12:09 UTC, closed without merging