[FIX] web: kanban cards border issues
odoo/odoo pull request #141764
Opened 2023-11-13 09:31 UTC by mano-odoo

In commit d8fcc218bc70caff4f4368309d7aa3be8b8ddaa5 we introduced a fix to the focus state of the kanban card. This fix did not account for the ungrouped Kanbancard which are listed next to eachother < md screens.

This commit also changes the `.oe_kanban_card` selector to the same selector that defines the borders. This avoid unconsistency if the `oe_kanban_card` class is omitted.

task-3580229

Closes: https://github.com/odoo/enterprise/pull/50010

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-13 09:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141764).

2023-11-13 10:14 UTC, Brieuc-brd approved these changes
LGTM

My only concern is the complexity of the selectors that add this PR.
Maybe it would be nice to refactor this view to simplify the css (just a thought).

2023-11-21 12:40 UTC, mano-odoo commented
@stefanorigano could you have a look 🙏

2023-11-22 15:14 UTC, stefanorigano requested changes
Hello @mano-odoo , thanks for fighting against this 💪😅

- You should target the last [supported version](https://www.odoo.com/documentation/master/administration/maintain/supported_versions.html), thus 16.4
- PR description: no need to link un-merged PRs closed in favour of the current one, just add a note there, as you did 
- PR description: **absolutely avoid** the `Closes: odoo/[xyz]` formula 'cause it's the one used by mergebot and it's quite confusing 😅

About the code/implementation used:

```scss 
& + .o_kanban_record:not(.o_dragged) > div:not(.o_dropdown_kanban) {
      border-top: none;
}
```
We're **not** gonna target **_any_** element directly descended from `o_kanban_record` and remove its border.
Let's check previous implementations as discussed 😉

2024-01-09 09:48 UTC, closed without merging

2024-01-09 09:48 UTC, mano-odoo commented
Fixed in https://github.com/odoo/odoo/pull/143345