[FIX] l10n_dk: Update taxes and CoA
odoo/odoo pull request #141989
Opened 2023-11-14 11:32 UTC by kenneth-vkd

# In General
The localization has been redefined as per the standardized chart of accounts from the Danish Government (Erhversstyrelsen): https://erhvervsstyrelsen.dk/sites/default/files/2023-02/2023-01-31-Standardkontoplan.xlsx

This is unfortunately only defined in Danish so in order to keep features of Odoo where the various parts of the localization are defined in English, I have translated the various Danish text into English and provided as the source and then provided the Danish text as a translation in the CSV-files.

Below is an overview of the individual areas with changes as well as some points of consideration in terms of the requirements from the government and how things work in Odoo

This PR is a joint operation between us and Odoo S.A. as agreed with Olivier Maessen in order to be compliant with the new Danish Bookkeeping Act

## Chart of Accounts
In general the CoA only required some minor adjustments
The CoA was reviewed based on the above file using hte sheet named `II) Kontoplan`, where all entries with value in column `B` (`Overskrift`) have been ignored. In most existing Danish Accounting software, the chart of accounts
is also what defines the formula for how to P&L report and balance sheet are rendered. This is different in Odoo, since the reports are defined spearately within `odoo/enterprise`.
Some accounts have been removed, since the `code` conflicted with some of the above

The below shows what accounts are used, but now under different numbers/names

Before:

```
5960 - Accounts receivable
5961 - Accounts receivable (PoS)
```

After:

```
6190 - Trade and other receivables
```

Before:

```
7180 - Creditor
```

After:

```
7440 - Suppliers of goods and services
```

Before:

```
7681 - Reverse chargeable business tax
```

After:

```
7680 - Sales tax
```

The internal transfer account is currently set to the prefix of `683`, so this needs to find a new home. A good suggestion would be to have it be `6479` or `6489`, but since we define a prefix and not a specific account,
it is hard to lock it to a specific number and there is no gap in the numbering sequence within bank + cash.

## Taxes
For taxes there are 69 tax codes that must be possible to handle. While some of the are straight forward, others are more dynamically computed, for which changes in other parts of Odoo might be required first

All taxes are defined in the previously linked file on the sheet named `III) Momskoder Bruttoliste`.

The following rules have been applied to map the sheet to Odoo:

- `Overskrift` -> `description@da_DK` (The english translation is put in )
- `Momskode betegnelse` -> `name`
- `Salg/køb` -> `type_tax_use`
- `Momskode` -> `id` (Prefixed with `tax_` and the lowercase value of this field)
- `Momssats` -> `amount` (The `amount_type` field is set accourding the value here as well as the information from the column `Vejledning`)

The column `price_include` is explicitly set to `False` or `True` so that a fallback/default is not used and causing issues in future versions of Odoo in case the default value of the field changes

The column `active` is explicitly set to `False` or `True` so that a fallback/default is not used and causing issues in future versions of Odoo in case the default value of the field changes. Here the rule is that if the code is marked with `x` in the column `5. Særkoder` of the above Excel sheet, then the value will be `False`, as the code is then there, but should not be usable out of the box. Customers needing these codes can enable them in relevant companies on their Odoo instance. Codes not marked with `x` in the column `5. Særkoder` will have `True` by default, since they are expected to used by most companies.

Upon processing the rules, we found the following tax codes where a challenge is found and that needs handling:
`S-DK-25` handles within Denmark regardless of whether we sell products or services. This is fine in terms of taxes and tax reporting, since there are no rules that state a requirement to split these on the tax reporting for the government.
It does however give a challenge when handling international sales, since `S-DK-25` has to be mapped to `S-EU-V-0` for products and mapped to `S-EU-Y-0` for services.
Odoo has a field called `tax_scope`, which allows us to restrict the usage of taxes based on the product type, but it does not help with the above.
Our suggestion is to implement one of the following changes in Odoo:
1. Implement an extra option for the fiscal position, so that each line with a mapping between taxes can be scoped to either products or services
2. Create a variation of `S-DK-25` for products and servicea and then have mapping rules for these on the reporting and data exchange

We would prefer option 1, since it can give a lot of extra features for other countries as well, where a similar challenge exists. If needed, I can attempt a separate PR for this and put a link here when it is ready.
The above also applies for purchases in relation to `K-DK-Fradrag`, where need to map for `K-EU-V-Fradrag` for products and `K-EU-Y-Fradrag` for services.

`S-DK-Brugtmoms` is a special code, as noted by the column `5. Særkoder`. The computation of the tax amount here is based on the following official explanation (translated to English):

```
This code is used for the sale of goods that can be covered by the rules for calculating VAT on used goods and where VAT must therefore be settled on the difference between the selling price and the purchase price.
```

The above means that if purchase a used Meeting table for DKK 1000 and sell it for DKK 2000 a week later, then the taxes are calculated based on what I have earned on this sale.
Compute the difference between my purchase and my sale:
```
2000 - 1000 = 1000
```
Compute the tax based on the above difference
```
1000 * 0.25 = 250
```

When using Odoo inventory management, the above is quite simple when running manual inventory valuation and with standard price. If we however use automated valuation with FIFO, then we need to track each item and these do not always use lot/serial numbers.
A way is needed to handle this code in Odoo

`S-DK-Marginmoms` is quite similar to `S-DK-Brugtmoms` and has the following official explanation (translated to English):

```
This code is used by travel agencies etc. that have to settle VAT on the profit margin.
```

`S-DK-brugtbil` is also a bit special, as it computes similar to `S-DK-Brugtmoms`. Here is the official explanation (translated to English):

```
This code is used for the sale of used cars, where the seller can make a deduction from the calculated sales tax, on the basis of a calculation based on the purchase price of the used vehicle.
```

`S-Lokalmoms` is quite strange and needs to be handled, but should not go in the tax report. I have set the tax rate to 0, but realistically it must be dynanmic and it is needed to find a way for handling this in Odoo.
Here is the official explanation (translated to English):

```
This code is used for sales made in or to customers in other countries where sales are carried out with local VAT.
```

There is also some challenges around `OSS` or One-Stop-Shop taxes in Europe, since special codes are given. I have not defined these as Odoo already has a method of mapping the various taxes from the localization of each country.
There are however some requirements for the reporting, which might need to be handled by Odoo

On the purchase side there are also a series of quite special codes, which we do not often see used, but the government does not list these as special codes, so we need a way to handle these in Odoo.
`K-DK-SkønsmæssigFradrag` is a special code that needs to reported the same as `K-DK-Fradrag`, but the percentage to be deducted is variable. So the tax rate is still 25 %, but how much of the 25 % can be deducted on our VAT statement is dynamic, based on the following official explanation (translated to English):

```
This code is used for the pu [...]

2023-11-14 11:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/141989).

2023-11-14 16:20 UTC, RicGR98 reviewed
Thanks a lot for the PR ! :D 

I've just made a first small technical review, but someone with better knowledge of Denmark will do a second pass (@FlorianGilbert  ? @Levizar  ?)

Regarding the fiscal positions, I've just checked with Olivier, and currently we do not have any request for such a feature for other localizations so it'd better to use your point 2.

> Create a variation of S-DK-25 for products and service and then have mapping rules for these on the reporting and data exchange

for now.

2023-11-14 16:20 UTC, RicGR98 commented on addons/l10n_dk/data/template/account.tax-dk.csv
I have not really understood your explanation of why the OSS - One stop shop salg (onlinehandel) taxes are not in the csv. Could you please clarify ?

> There is also some challenges around OSS or One-Stop-Shop taxes in Europe, since special codes are given. I have not defined these as Odoo already has a method of mapping the various taxes from the localization of each country.
There are however some requirements for the reporting, which might need to be handled by Odoo

2023-11-15 16:00 UTC, kenneth-vkd commented on addons/l10n_dk/data/template/account.tax-dk.csv
When you enable OSS in Odoo you get the various tax codes from the other countries. So from how I read the description of the OSS code, it sounds like they are not needed in Odoo, but perhaps a special report is required to display all the foreign taxes.

2023-11-15 16:02 UTC, kenneth-vkd commented on addons/l10n_dk/__manifest__.py
> +    'author': 'VK DATA ApS',
I will revert it

2023-11-21 12:57 UTC, kenneth-vkd commented
@RicGR98 @Levizar @FlorianGilbert any progress on the reviews?
I am in the processing of doin the clarification on some of the tax codes with the Danish government, but there are some points to be handled from your side.
We need to get cleared whether or not to add the OSS tax codes and how they should be defined.
There are also open questions for you on how to handle some of the special codes for processing of used products (purchase and sales).

2023-11-21 15:06 UTC, FlorianGilbert requested changes
Hello, thank you for your contribution.

Honestly, @RicGR98  did the job very well! :)
Technically speaking, I have few remarks:
* Could you please squash all your commits into one commit.
* Could you please put a summary of your PR message into this commit to explain why we need this commit.
* Could you please rebase your branch to take into account last changes on [l10n_dk](https://github.com/odoo/odoo/commit/8b3394bcd3082828aff5333abe90eac4ae6a1a34) . 
* Could you please verify that Balance Sheet and PnL are still good to use with your changes (I can do it for you if you rebase your branch)

Again, thank you for your contribution!

2023-11-21 15:13 UTC, kenneth-vkd commented
@FlorianGilbert thank you reporting back.
I have not had much luck with squashing commits in the past. In worst case, I will close this PR, re-apply the complete set of changes and then do a new PR.
Changes will be ready for you to review tomorrow

2023-11-22 08:17 UTC, kenneth-vkd commented
It does not go well with getting the commits squashed.
I can get the the interactive rebase running on smaller parts, but it does not really squash the commits together.
Using the full set, creates an infinite loop when I hit one of the "merge branch 17.0 into..." commits.

Will to force a rebase from odoo/odoo and then reapply the changes to `l10n_dk` as one big commit

2023-11-22 08:30 UTC, RicGR98 commented
> It does not go well with getting the commits squashed. I can get the the interactive rebase running on smaller parts, but it does not really squash the commits together. Using the full set, creates an infinite loop when I hit one of the "merge branch 17.0 into..." commits.
> 
> Will to force a rebase from odoo/odoo and then reapply the changes to `l10n_dk` as one big commit

Alright, in this case don't forget to mention this PR in the one so we have an historic, thanks again for your work :)

2023-11-23 14:31 UTC, closed without merging