[FIX] website: remove writing ability
odoo/odoo pull request #142028
Opened 2023-11-14 14:15 UTC by datonefaridze

Commit fixes the issue that allows people
to write on cards (event card, appointment cards, etc) The class `o_editable` is automatically added to the card styles. In order to fix this I decided to add `o_not_editable` to the card styles, so that it prevents adding `o_editable`.

task-3481761

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-14 14:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/142028).

2023-11-14 14:17 UTC, datonefaridze commented
before:
![image](https://github.com/odoo/odoo/assets/52849166/5703ac94-abaa-4af1-a458-742a1fb7dcb7)

after:
![image](https://github.com/odoo/odoo/assets/52849166/657ca520-974d-487c-9ebd-a2fa1f2b00ea)

2023-11-14 17:17 UTC, rdeodoo requested changes
Note that this is breaking the cover concept: you can't edit a blog post content anymore (title subtitle etc), eg on `/blog/travel-1/sierra-tarahumara-1`

2023-11-15 08:00 UTC, datonefaridze commented
@robodoo people still can edit covers
![image](https://github.com/odoo/odoo/assets/52849166/d8524493-9a84-43c1-8041-c8761692e57f)

2023-11-15 10:44 UTC, rdeodoo commented
See https://drive.google.com/file/d/1Igi24cxD2Pkg50_dpM8eu7Zjmz_zELcA/view?usp=drive_link you can't edit your blog anymore
I am surprised we don't have any tour not failing, but I guess it's hard to test `contenteditable="false"` in a test, jQuery text insertion probably just bypass that.

2023-11-15 12:47 UTC, datonefaridze commented
@rdeodoo thanks, i will take another look

2023-11-16 13:32 UTC, datonefaridze commented
@rdeodoo what do you think now? i made second PR (on ent) i basically added o_not_editable only on covers of event and appointment once they are rendered.

2023-11-16 13:32 UTC, datonefaridze commented
@rdeodoo i couldn't figure out better solution (don't know many stuff about editor)

2023-11-17 14:20 UTC, rdeodoo commented
@datonefaridze I believe this is because of what @qsm-odoo reported here: https://discord.com/channels/678381219515465750/687338152372994236/1174767681837207632

Since the editor adds the `o_editable` class which is now also adding the `contenteditable=true` attribute, one can type anything in a cover.. :grimacing: 

It's also linked to this opw https://www.odoo.com/web#id=3595547&menu_id=4720&cids=1&action=333&active_id=49&model=project.task&view_type=form

2023-11-17 14:45 UTC, rdeodoo commented
> datonefaridze requested a review from rdeodoo 1 minute ago

Reading again my previous message it was not clear enough: if this is the same root cause (and it's 99% sure it is), you have nothing to do, this will be fixed with the editor fix that will be done ASAP.

2023-11-17 15:30 UTC, datonefaridze commented
@rdeodoo Hello, thanks for the reply (i didn't see your comment because my github page wasn't refreshed)

2023-12-29 14:31 UTC, rdeodoo commented
https://github.com/odoo/odoo/commit/7f1021b8484cbc17f922c0e69d160a6ff672e7dc

2023-12-29 14:31 UTC, closed without merging