[IMP] delivery,website_sale: hide unavailable delivery carriers during checkout
odoo/odoo pull request #142136
Opened 2023-11-15 10:37 UTC by ltinel

This change applies to both regular and express checkout. The idea is to hide delivery carriers which can't be selected by customers anyway (yielding a simpler UI for the customer).

task-3284612

2023-11-15 10:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/142136).

2023-11-16 13:39 UTC, ltinel commented
@fw-bot up to master

2023-11-23 13:36 UTC, vava-odoo requested changes
Thanks @ltinel for this fix.
I have a few suggestions for your PR. Could you have a look? Some comments should be applied at several places, but I only mentioned it once.
Also, isn't the bug fixed in saas-16.3? If so, why are you asking the bot to port that until master (which is useless as it is the default behaviour)?
Cheers!

2023-11-23 13:36 UTC, vava-odoo commented on addons/website_sale_delivery/models/sale_order.py
> +            return res['success']
As you're changing that in stable, wouldn't it be safer with a `get`?
```suggestion
            return res.get('success')
```

2023-11-23 13:36 UTC, vava-odoo commented on addons/website_sale_delivery/tests/test_controller.py
> +                'fixed_price': 20.0,
I don't think it's necessary since it is computed from `self.product_id.list_price` (and is not used if `base_on_rule`)
```suggestion
```

2023-11-23 13:36 UTC, vava-odoo commented on addons/website_sale_delivery/tests/test_controller.py
> +                        'list_base_price': 0,
Default value
```suggestion
```

2023-11-23 13:36 UTC, vava-odoo commented on addons/website_sale_delivery/tests/test_controller.py
> +                ]
Best practice (nitpicking)
```suggestion
                    }),
                ],
```

2023-11-23 13:36 UTC, vava-odoo commented on addons/website_sale_delivery/tests/test_controller.py
> +                'delivery_type': 'fixed',
Default value
```suggestion
```

2023-11-23 15:06 UTC, ltinel commented
@vava-odoo Thanks for the review! The reason I ported it up to master is because I added a few tests (which I want to add to versions 16.3 and later as well).

2023-11-23 15:18 UTC, vava-odoo approved these changes

2023-12-12 14:49 UTC, AntoineVDV approved these changes
@robodoo r+

2023-12-12 17:37 UTC, closed without merging