[FIX] mass_mailing: image width beyond container
odoo/odoo pull request #142286
Opened 2023-11-16 09:53 UTC by maad-odoo

Before this commit:
When attempting to increase the width of an image using the 'o_handle' arrows, 
the width keeps on increasing until the mouse arrow leaves the body, resulting 
in an increased image width.

After this commit:
When attempting to increase the width of the image using the 'o_handle' arrows, 
the width increases only up until the closest 'div' tag, resulting in an 
undesired restriction in the image width increase.

task-3593008

2023-11-16 09:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/142286).

2024-01-29 08:46 UTC, Zynton requested changes

2024-01-29 08:46 UTC, Zynton commented on addons/mass_mailing/static/src/js/mass_mailing_snippets.js
> +                if (compass === "image") {
Unnecessary diff.

2024-01-29 08:46 UTC, Zynton commented on addons/mass_mailing/static/src/js/mass_mailing_snippets.js
> +                    let maxWidth = self.$target.closest("div").width();
```suggestion
                    const maxWidth = self.$target.closest("div").width();
```

2024-01-29 08:46 UTC, Zynton commented on addons/mass_mailing/static/src/js/mass_mailing_snippets.js
> +                    self.$target.css("width", Math.min(maxWidth, Math.round(event.pageX - offset)));
I suggest this comment to precede it:
```js
// Equivalent to `self.change_width` but ensuring `maxWidth` is the maximum:
```

2024-01-29 10:19 UTC, maad-odoo commented
@Zynton Changes are done. Please have a look.

2024-01-29 10:29 UTC, Zynton commented
@robodoo r+

2024-01-29 11:56 UTC, closed without merging