[FIX] resource: calculate duration of overlapping work intervals
odoo/odoo pull request #142497
Opened 2023-11-17 11:33 UTC by AH-Yussef

### Steps to reproduce:
1. install **Time Off** module
2. Go to the **Employees** app
3. In the menu above, go to **Configuration > Working** Schedules
4. Click on **Standard 40 hours/week**
5. Delete **Monday Lunch** work interval
6. Change the **work from** property of the **Monday Afternoon** to **12:00** so it overlaps with the **Monday Morning** interval
7. Go to the **Time Off** app
8. An Error is raised!

### Investigation:
- When two work intervals overlap they are being merged together https://github.com/odoo/odoo/blob/1229c13c12eedc71aa49dc14fa51059de01885d0/addons/resource/models/resource_calendar.py#L358 That corrupt the metadata of the newly created interval as each one has a different name, day period and more importantly id.
- These intervals' metadata are then used to calculate the duration of each but as they are corrupted, an error arises https://github.com/odoo/odoo/blob/1229c13c12eedc71aa49dc14fa51059de01885d0/addons/resource/models/resource_calendar.py#L491

### Solution:
Following the same approach in version 16.4 by not extracting the `day_duration` from the metadata of the intervals when calculating the duration but rather interfering them.

opw-3588805

2023-11-17 11:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/142497).

2023-11-27 19:26 UTC, nle-odoo approved these changes
looks good to me

functionally I'm not too familiar with this code

2023-12-06 09:41 UTC, Bertrand2 requested changes
Thanks for the PR! :)
Here are a few comments, though all of them are non-blocking it's good to keep the codebase clear and consistent

2023-12-06 09:41 UTC, Bertrand2 commented on addons/resource/tests/test_resource_calendar.py
> +        cls.resource_calendar.attendance_ids = [monday_morning_attendance.id, monday_afternoon_attendance.id, tuesday_morning_attendance.id]
You can create the attendances records directly while creating the calendar:
```suggestion
        cls.resource_calendar = cls.env['resource.calendar'].create({
            'name': 'resource calendar',
            'tz': 'UTC',
            'attendance_ids': [
                (0, 0, {
                    'name': 'Monday Morning',
                    'dayofweek': '0',
                    'hour_from': 8,
                    'hour_to': 12,
                    'day_period': 'morning',
                }),
                (0, 0, {
                    'name': 'Monday Afternoon',
                    'dayofweek': '0',
                    'hour_from': 12.0,
                    'hour_to': 16.0,
                    'day_period': 'afternoon',
                }),
                (0, 0, {
                    'name': 'Tuesday Morning',
                    'dayofweek': '1',
                    'date_from': date(2023, 1, 3),
                    'date_to': date(2023, 1, 3),
                    'hour_from': 8.0,
                    'hour_to': 16.0,
                    'day_period': 'morning',
                }),
            ],
        })
```

2023-12-06 09:41 UTC, Bertrand2 commented on addons/resource/tests/test_resource_calendar.py
> +# -*- coding: utf-8 -*-
We don't set that anymore
```suggestion
```

2023-12-06 09:41 UTC, Bertrand2 commented on addons/resource/tests/test_resource_calendar.py
> +class TestResourceCalender(common.TransactionCase):
Typo :)
```suggestion
class TestResourceCalendar(common.TransactionCase):
```

2023-12-06 09:41 UTC, Bertrand2 commented on addons/resource/tests/__init__.py
> +from . import test_resource_calendar, test_utils
It's usually written like this, let's keep it consistent :smile: 
```suggestion
from . import test_resource_calendar
from . import test_utils
```

2023-12-06 10:29 UTC, closed without merging