[FIX] mrp: product should be available
odoo/odoo pull request #143022
Opened 2023-11-21 18:17 UTC by ande-odoo

Steps to reproduce:
---
1. Go to Manufacturing
2. Go to Products > Bills of Materials
3. Create a new BoM
4. Product: p1 (and create product p1)
5. Component: p2 (and create product p2)
6. Save the BoM
7. Click on Overview
8. p1 and p2 are not available (Normal behavior)
9. Go to the p2 product page
10. Click on Update Quantity > new quantity > Apply all
11. Go back to the p1 BoM
12. Click on Overview
13. p2 is available but p1 is not available
14. p1 should be available

Fix:
---
Backport of https://github.com/odoo/odoo/commit/f13b4d1ae8c12a1668222e6994dea26a27c6f5d4

opw-3601298

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-11-21 18:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/143022).

2023-11-21 18:20 UTC, nle-odoo approved these changes
it's a backport so looks good

usually we try not to change signature method because it would break custom code that calls it. instead we would pass the additional variable in context for example

2023-11-22 08:42 UTC, adwid requested changes
This is not a bug, the behaviour on Odoo 16.3 is actually incorrect: if the manufactured product does not have any route, and if we don't have this product in the stock, we should display "Not available"

Commit [1] only makes sense with kits (this is even how it is explained in the commit description)

So what you should rather do: fix 16.3+ so [1] only work with kit, and add a test

[1] f13b4d1ae8c12a1668222e6994dea26a27c6f5d4

2023-11-23 18:38 UTC, ande-odoo commented
New PR in saas-16.3: https://github.com/odoo/odoo/pull/143421

2023-11-23 18:38 UTC, closed without merging