[IMP] mail: sort attachments on basis of type in discuss and chatter.
odoo/odoo pull request #143983
Opened 2023-11-28 12:12 UTC by maad-odoo

Before this PR:
The attachements that we displayed in the attachmentPanel were not sorted on the 
basis of type, there were displayed just in the order in which they were inserted.

Desired behaviour after this PR:
1. The attachments in the attachment panel are now sorted in three different tab, 
    namely 'Media', 'Links', 'Files'. Each attachment gets stored in its respective tab.
3. Consider linkPreviews as attachement and store all the linkPreviews in the tab 'Links'

task-3485793

2023-12-07 05:59 UTC, rapr-odoo requested changes
Some remarks here.

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/src/discuss/core/common/attachment_panel.js
> +        });
`this.state` should be defined above with other hook variables.

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/src/core/web/chatter.js
> +import { AttachmentPanel } from "@mail/discuss/core/common/attachment_panel";
Import them in alphabetical order.

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/src/core/web/chatter.js
> +        AttachmentPanel,
Alphabetical order.

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/src/discuss/core/common/action_panel.xml
> +                </div>
Won't this affect everywhere?

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/src/discuss/core/common/attachment_panel.xml
> +                    </div>
This could be optimised further

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/tests/discuss/core/attachment_panel_tests.js
> +        contains: ["p", { text: "This channel doesn't have any file attachments." }],
I don't feel like any need of checking `p` tag inside contains. Checking only text should be OK ?

2023-12-07 05:59 UTC, rapr-odoo commented on addons/mail/static/tests/web/attachment_box_tests.js
> -
Unnecessary Diff.

2023-12-11 10:28 UTC, rapr-odoo requested changes
Small changes here...

2023-12-11 10:28 UTC, rapr-odoo commented on addons/mail/static/src/discuss/core/common/attachment_panel.xml
> +                    <t t-foreach="[['media', 'Media'], ['link', 'Links'], ['file', 'Files']]" t-as="category" t-key="category[0]">
the categories list should be a getter for future improvements or overrides.

2023-12-11 10:28 UTC, rapr-odoo commented on addons/mail/static/src/discuss/core/common/attachment_panel.xml
> +                            </div>
Could use `LinkPreviewList` component instead.

2023-12-12 06:31 UTC, maad-odoo commented on addons/mail/static/src/core/web/chatter.js
> +                ) || 0
message.linkPreviews can contain more than one linkPreviews hence reduce is used.

2023-12-13 09:11 UTC, rapr-odoo approved these changes

2024-12-18 06:16 UTC, closed without merging