[FIX] calendar: send attachment with calendar event invitation mail
odoo/odoo pull request #144002
Opened 2023-11-28 12:52 UTC by Mtaylorr

Issue:
======
Attachment files aren't sent with the event invitation email.

Steps to reproduce the issue:
=============================
- Add any attachment to the email template : `Calendar: Meeting Invitation` and save it.
- Go to website and book an appointment.
- Go to Scheduled Actions  and run manually email queue manager to send the notification.
- The sent email doesn't have the attachement you provided, it has only 1 attachement which is the calendar one.

Origin of the issue:
====================
The notification of the event invitation was taking only the calendar as attachment and ignores the template attachemnt.

Solution:
==========
Now the calendar event invitation email will take into account the attachment of the email_template.

opw-3593140

2023-11-28 12:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/144002).

2023-12-04 09:20 UTC, Mtaylorr commented
@odoo/rd-subscription-sign-calendar can you take a look at this ?

2023-12-04 14:18 UTC, arj-odoo requested changes
I have a simple request otherwise, it should work.

2023-12-04 14:32 UTC, arj-odoo approved these changes

2023-12-07 09:05 UTC, Mtaylorr commented
@robodoo r+

2023-12-07 10:54 UTC, closed without merging