[FIX] website: address test tour issue with links href updating
odoo/odoo pull request #144234
Opened 2023-11-29 15:32 UTC by SergeBayet

This commit resolves an issue in the `link_tools` test, specifically addressing a failure that arises when verifying the synchronization between the link's href and the content of the `<a>` tag. The failure was attributed to the oversight of not clicking outside the popup to close it before interacting with the link.

runbot-24929

2023-11-29 15:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/144234).

2023-11-30 15:02 UTC, qsm-odoo requested changes

2023-11-30 16:10 UTC, SergeBayet commented on addons/website/static/tests/tours/link_tools.js
> +            actions.text("callmemaybe.com/shops");
I don't konw neither for the previous code. The new one is borrowed from this commit in [16.4](https://github.com/odoo-dev/odoo/blob/7d26c7b666033a16acfb430b6bf06235dd7d88ea/addons/website/static/tests/tours/link_tools.js), that I found easier to understand. I'll add some explanations to this step.

2023-11-30 16:13 UTC, SergeBayet commented on addons/website/static/tests/tours/link_tools.js
> +    clickOnImgStep,
I didn't know about `text_blur`. I'm gonna try... thanks

2023-12-07 17:38 UTC, qsm-odoo requested changes
@SergeBayet 

- Your commit removes one call to clickOnImgStep but leaves the other ones, any reason? I'd remove them all and always use text_blur no?
- Your commit explain that the failure was due to a missing text_blur but:
   - The commit which introduced that missing blur was merged in 16.2 -> any reason that this PR argets 16.3?
   - Try mentioning if the failure is systematic or not and possibly why

Thanks :pray:

2023-12-11 10:41 UTC, SergeBayet commented
`text_blur` doesn't trigger the event that closes the popover-tooltip. So I had to leave the 'clickOnImgStep' when required. Do you have an alternative solution?

2024-01-17 13:34 UTC, qsm-odoo approved these changes
- Retargeted to 16.0, despite the race condition being only in >= 16.3. In 16.0, the tour seems robust now but since the code is the same... I figured, better unify the tour definition given how annoying it is (breaking differently in each sub version).
- These changes do not apparently (over ~20 tests) change the amount of race condition... but they can only help. `text_blur` is what should have been used, etc etc.
- Kept the "input" dispatch that was initially removed by this PR: without it we do not go through `_onInput` which was the point of that step apparently.

After this PR (and its forward-port), the tour:
- Succeeds 100% of the time in <= 16.2
- Fails ~50% (difficult to say) of the time in >= 16.3 (still have to understand why and fix later).

@robodoo r+

2024-01-17 16:40 UTC, closed without merging

2024-01-17 23:37 UTC, qsm-odoo commented
Note for tracking: part of this PR was actually a backport of https://github.com/odoo/odoo/commit/7d26c7b666033a16acfb430b6bf06235dd7d88ea and I did not understand it until https://github.com/odoo/odoo/pull/149854#pullrequestreview-1828403500
More PR to follow... damned tour.