[FIX] hr_holidays_attendance: Public leave in _get_overtime_leave_domain
odoo/odoo pull request #144732
Opened 2023-12-04 10:19 UTC by hwangh95

The _get_overtime_leave_domain was added to help check for overtime on
employee leaves, but failed to account for public leaves

Note:
Backport of commit 1407052d3ff0663180ea11342569ace643c0cd00 from
odoo/odoo#141235

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-04 10:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/144732).

2023-12-04 10:24 UTC, hwangh95 commented
@sofiagvaladze Sorry for the ping, but if you could quickly look at this that would be great. At the very least before the Christmas holidays, since there are people who might log hours on the public holiday.

2023-12-19 14:18 UTC, sofiagvaladze requested changes
@hwangh95 sorry for late reply, I was on vacation myself :innocent: 

I have just one question and then we can proceed :smile:

2023-12-19 16:40 UTC, hwangh95 commented on addons/hr_holidays_attendance/models/hr_attendance.py
> +        # resource_id = False => Public holidays
I was pretty sure that the change did nothing in the end. resource_list already is initialized with a `self.env['resource.resource']` inside and an empty model.id is False

You can see it here
[1407052#diff-a39d1344f686aade27285d6860b04689032d63189ee42676318b21556140421fL502](https://github.com/odoo/odoo/commit/1407052d3ff0663180ea11342569ace643c0cd00#diff-a39d1344f686aade27285d6860b04689032d63189ee42676318b21556140421fL502)

Just wanted to reduce unnecessary diffs

2023-12-21 11:32 UTC, sofiagvaladze commented on addons/hr_holidays_attendance/models/hr_attendance.py
> +        # resource_id = False => Public holidays
Indeed, I missed that ^^

2023-12-21 11:32 UTC, sofiagvaladze commented
@robodoo r+
@fw-bot up to saas-15.2

2023-12-21 11:33 UTC, sofiagvaladze commented
@robodoo rebase-ff

2023-12-21 11:34 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-12-21 13:53 UTC, closed without merging