[FIX] account: journal entry balance conversion on import
odoo/odoo pull request #145265
Opened 2023-12-06 15:04 UTC by agr-odoo

Import a new journal entry in foreign currency with amount currency but no credit/debit/balance

Issue:
After importing the entry, debit and credit remain at zero.
The conversion to the main currency is not done according to the rate and the accounting date.
If those entries are posted, the debits/credits in the main currency remain at zero.

opw-3614530

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-06 15:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145265).

2023-12-06 15:06 UTC, agr-odoo commented
@Levizar 
Quite specific, but it makes sense to compute credit/debit from amount currency in this case

2024-02-06 08:49 UTC, Levizar requested changes
You're right, it makes sense!
@robodoo r+

2024-02-06 13:23 UTC, closed without merging

2024-02-06 13:27 UTC, Levizar commented on addons/account/models/account_move.py
> +                if not move.is_invoice(include_receipts=True) and vals.get('debit') is False and vals.get('credit') is False:
@ngochung207-viindoo I think it shouldn't: such lines are created with amounts for debit/credit/balance and thus shouldn't pass the `is False` condition.
I will make a test to be sure.