[IMP] website: support column selection to picture snippet
odoo/odoo pull request #145413
Opened 2023-12-07 12:19 UTC by SergeBayet

This commit introduces column selection options to enhance the layout of the previously named `Picture` snippet, which is now renamed as the `Title - Image` snippet.
This update allows users to conveniently include columns below a title without resorting to workarounds such as utilizing the `Parallax` snippet or manually dragging and dropping columns within the `Image` snippet.

design-theme PR : https://github.com/odoo/design-themes/pull/753
task-3626753

2023-12-07 12:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145413).

2023-12-07 12:43 UTC, Guillaume-gdi reviewed
LGTM :+1: 

Don't forget the design theme PR :wink:

2023-12-07 12:43 UTC, Guillaume-gdi commented on addons/website/views/snippets/snippets.xml
>                          <keywords>image, media, illustration</keywords>
A cool bonus would be to add the "old" name in the keywords so that our historical users can still type "Picture" in the search bar.

2023-12-11 07:34 UTC, SergeBayet commented
@Guillaume-gdi I managed not to have to modify the design-theme

2023-12-11 10:23 UTC, Guillaume-gdi requested changes
> I managed not to have to modify the design-theme

With your changes I have now "Custom" as number of column. I should be "1" no ?
And you have to adapt the code to make it pass the `test_replace_media` tour :+1:

2023-12-11 10:45 UTC, SergeBayet commented
I left the class col-lg-10 and offset-lg-1 as is. In design-theme, it's often overridden by col-lg-8 and offset-lg-2. So it makes no sense to remove the offset. But that means that by default the column will be custom. Is it annoying?
I'll adapt the test.

2023-12-11 11:57 UTC, Guillaume-gdi commented
> I left the class col-lg-10 and offset-lg-1 as is. In design-theme, it's often overridden by col-lg-8 and offset-lg-2. So it makes no sense to remove the offset. But that means that by default the column will be custom. Is it annoying?

IMHO the offset doesn't bring value (without theme at least) and could be removed but indeed this task is not about removing this offset. By reading `_areColsCustomized` it is the expected behavior to have "custom" for this case :+1:

2024-01-05 13:21 UTC, qsm-odoo commented
@robodoo delegate=bso-odoo 
@bso-odoo

2024-02-12 16:44 UTC, qsm-odoo commented
@SergeBayet What @bso-odoo said is definitely not intended indeed: there should only be one container which contains a title and a row.
```xml
<section>
    <div class="container">
        <h1>Title</h1>
        <p>Some text</p>
        ...
        <!-- the main row -->
        <div class="row">
            <div class="col-XXX"></div>
            <div class="col-XXX"></div>
            <div class="col-XXX"></div>
        </div>
    </div>
</section>
```

cc @pierre-pde

2024-02-13 08:03 UTC, SergeBayet commented
@pierre-pde @bso-odoo @qsm-odoo It's fixed. But what am I suppose to do with the theme "Vehicle". It entirely changes the layout with a background image and duplicates the title and description when you add some columns. Is it intended too?

2024-02-13 09:45 UTC, pierre-pde commented
@SergeBayet , I had never noticed that the picture snippet was so different in the vehicle theme.
IMO we should change that in stable and make it more similar than the other themes.
https://drive.google.com/file/d/1nSVO5xBAFLFaNX0fvA20FLWb1vErHr1V/view
@stefanorigano , do you agree?

2024-02-13 13:23 UTC, SergeBayet commented
@stefanorigano could you tell me what I should do in relation to @qsm-odoo 's message, or send me an image of what you would like? Thanks in advance

2024-02-13 13:45 UTC, stefanorigano commented
Hello @SergeBayet , I do agree with @qsm-odoo and @pierre-pde of course.
Themes shouldn't be allowed to perform customizations that the user can't overcome using the editor.

2024-02-14 09:28 UTC, SergeBayet commented
@pierre-pde @stefanorigano, I have modified the s_picture snippet in the "vehicle" theme. Could you please let me know if you are satisfied with the result? I have done my best to adhere to the old version while maintaining the expected layout.

2024-02-14 11:47 UTC, stefanorigano commented
@SergeBayet , LGTM, thanks 👍

2024-02-14 11:58 UTC, pierre-pde commented
@SergeBayet , LGTM , perfect

2024-02-14 13:33 UTC, SergeBayet commented
@bso-odoo I think this is good now for merging if you want.

2024-02-14 15:59 UTC, bso-odoo commented
For vehicle, maybe we want to explore a similar "text over image" layout as before, by using the "Grid" mode of the snippet ?
On the other hand, maybe we don't want this because currently when toggling back to "Cols", the header part becomes a full-width column within the row instead of returning outside the row - which would make the initial state of the default theme's snippet unreachable through the editor.
Or maybe we want the conversion to "Cols" to also handle that case (this could be part of a future task too). @pierre-pde

2024-02-14 16:22 UTC, pierre-pde commented
@bso-odoo , I'm not sure I understand your point...
The idea of the task is to make this building block something like "Title & columns".
So we should keep the col layout.
If not clear, we can have a chat tomorrow about this :)

2024-02-16 14:26 UTC, qsm-odoo commented
@robodoo delegate=bso-odoo 
@bso-odoo

2024-02-19 11:01 UTC, bso-odoo commented
@robodoo r+

2024-02-19 21:01 UTC, closed without merging