[IMP] l10n_in: enable cash rounding
odoo/odoo pull request #145517
Opened 2023-12-08 05:41 UTC by zepa-odoo

Implement default Cash Rounding with Half-Up method for Indian localization. Update Chart of Accounts for Expense & Income with appropriate adjustments.

Task Id: 3631283

2023-12-11 07:28 UTC, jva-odoo commented on addons/l10n_in/__init__.py
> +        config_wizard.unlink()
```suggestion
    group_user = self.env.ref('base.group_user').sudo()
    group_user._apply_group(self.env.ref('account.group_cash_rounding'))
```

2023-12-11 09:35 UTC, zepa-odoo commented on addons/l10n_in/__init__.py
> +        config_wizard.unlink()
Done

2023-12-19 12:28 UTC, rugo-odoo requested changes

2023-12-19 12:28 UTC, rugo-odoo commented
(cc @william-andre)

2023-12-19 12:41 UTC, william-andre commented on addons/l10n_in/models/template_in.py
> +        return super()._post_load_data(template_code, company, template_data)
```suggestion
    @template('in', 'account.cash.rounding')
    def _get_in_account_cash_rounding(self):
        return {
            'l10n_in.cash_rounding_in_half_up': {
                'profit_account_id': 'p213202',
                'loss_account_id': 'p213201',
            }
        }
```

2023-12-19 12:41 UTC, william-andre commented on addons/account/views/json of gstr2a
hum

2023-12-19 12:41 UTC, william-andre commented on addons/l10n_in/__init__.py
> +    # The cash rounding is activated by default only if the company is localized in India.
The comment is confusing. It is not for **only** for Indian companies, but as soon as the module is installed, for **all** the companies.

2023-12-19 13:29 UTC, william-andre approved these changes
@robodoo r+

2023-12-19 15:45 UTC, closed without merging