[FIX] web_editor: reactivate automaticStep before returns
odoo/odoo pull request #145623
Opened 2023-12-08 17:32 UTC by robinlej

[Commit 1] made sure the history worked when resizing elements by calling `odooEditor.automaticStepUnactive()`, but forgot to apply its counterpart `automaticStepActive()` before each return that could break the resizing flow.

Note: `automaticStepActive()` makes sure modifications made on the DOM through the browser's developer tools are tracked and can be reversed with the undo button. Not reactivating it in time means some flows could be broken (until another method reactivates it).

[Commit 1]: https://github.com/odoo/odoo/commit/423f4bd2a6cc47e69699d2437eaa5acda94bb98d

2023-12-08 17:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145623).

2023-12-12 13:00 UTC, qsm-odoo requested changes
Add "Related to opw-XXX" in the commit message, that way we know where that came from even though not directly solving opw-XXX :+1:

2023-12-12 16:55 UTC, robinlej commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +                self.options.wysiwyg.odooEditor.automaticStepActive("resizing");
@qsm-odoo You're right, that's updated.

2023-12-13 08:15 UTC, robinlej commented
@qsm-odoo Good to go :+1:

2023-12-13 13:48 UTC, qsm-odoo approved these changes
@robodoo r+

2023-12-13 14:58 UTC, closed without merging