[FIX] pos_loyalty: prevent using expired eWallets
odoo/odoo pull request #145801
Opened 2023-12-11 14:33 UTC by robinengels

Current behavior:
It was possible to use an expired eWallet to pay for an order. It was also possible to put money on an expired eWallet.

Steps to reproduce:
- Create an eWallet with an expiration date in the past
- Open PoS and add products to the order
- Click on the eWallet button
- You can still use the eWallet to pay for the order

opw-3568270
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-11 14:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145801).

2023-12-20 12:29 UTC, robinengels commented
adapt all instanciation of PosLoyaltyCard

2023-12-21 16:01 UTC, caburj commented on addons/pos_loyalty/static/src/js/ControlButtons/eWalletButton.js
> +        const eWalletRewards = await this._getEWalletRewards(order);
```suggestion
        const eWalletRewards = this._getEWalletRewards(order);
```

2023-12-28 14:05 UTC, caburj requested changes
We should not allow `_getEWalletRewards` to throw an error because it's used in the template. Instead, we make the reward invalid if there is no coupon linked to it.

2023-12-28 14:05 UTC, caburj commented on addons/pos_loyalty/static/src/js/ControlButtons/eWalletButton.js
> +        });
```suggestion
        return claimableRewards.filter((reward_line) => {
            const coupon = this.env.pos.couponCache[reward_line.coupon_id]
            return coupon && reward_line.reward.program_id.program_type == 'ewallet' && !coupon.isExpired();
        });
```

2024-01-02 14:26 UTC, caburj approved these changes
robodoo r+

2024-01-02 16:02 UTC, closed without merging