[ADD] l10n_in: HSN code length selection at setting level
odoo/odoo pull request #145912
Opened 2023-12-12 11:23 UTC by kasp-odoo

Before this commit
==================
There was no functionality to select the length of the HSN code.

After this commit
=================
Added settings to select the length of the HSN code at the setting level. Users can now define the desired length for HSN codes.

task_id: 3527378

2023-12-12 11:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145912).

2023-12-13 05:38 UTC, jva-odoo requested changes

2023-12-13 05:38 UTC, jva-odoo commented on addons/l10n_in/models/product_template.py
> +            company = self.env.company
```suggestion
            company = record.company_id or self.env.company
            
```

2023-12-13 05:38 UTC, jva-odoo commented on addons/l10n_in/models/product_template.py
> +            if record.l10n_in_hsn_code and company.l10n_in_hsn_validation and str(len(record.l10n_in_hsn_code)) < company.l10n_in_hsn_code_digit:
```suggestion
            if company.country_id.code == 'IN' and record.l10n_in_hsn_code and company.l10n_in_hsn_validation and len(record.l10n_in_hsn_code) < int(company.l10n_in_hsn_code_digit or '8'):
```

you are comparing string for length check !!!

2023-12-13 05:38 UTC, jva-odoo commented on addons/l10n_in/models/product_template.py
> +                error_message = _("HSN code validation failed, please enter minimum {} digits HSN code.").format(company.l10n_in_hsn_code_digit)
```suggestion
                error_message = _("HSN/SAC code validation failed, please enter minimum %s digits HSN/SAC code.", company.l10n_in_hsn_code_digit)
```

2023-12-13 05:38 UTC, jva-odoo commented on addons/l10n_in/views/res_config_settings_views.xml
> +                        <field name="l10n_in_hsn_code_digit" widget="radio" invisible="l10n_in_hsn_validation == False"/>
```suggestion
                        <field name="l10n_in_hsn_code_digit" widget="radio" invisible="l10n_in_hsn_validation == False" required="l10n_in_hsn_validation"/>
```

2023-12-13 05:38 UTC, jva-odoo commented on addons/l10n_in/views/res_config_settings_views.xml
> +                <block title="Product" name="product_setting_container" invisible="country_code != 'IN'">
```suggestion
                <block title="Product" name="l10n_in_product_setting_container" invisible="country_code != 'IN'">
```

2023-12-14 09:08 UTC, jva-odoo commented
@kasp-odoo Active this when the Indian COA is load on company

2024-01-02 06:16 UTC, jva-odoo requested changes

2024-01-02 06:16 UTC, jva-odoo commented on addons/l10n_in/models/res_config_settings.py
> +    l10n_in_hsn_code_digit = fields.Selection(related='company_id.l10n_in_hsn_code_digit', readonly=False)
```suggestion
    l10n_in_hsn_code_digit = fields.Selection(related='company_id.l10n_in_hsn_code_digit', readonly=False,
    help="""As per Notification No. 78/2020 dated October 15, 2020, the taxpayers,
    having Aggregate Annual Turnover (AATO) above Rs. 5 Crore, shall use at least 6 digit HSN code and
    other taxpayers shall use at least a 4-digit HSN code
    """)
```

2024-01-05 06:01 UTC, jva-odoo commented on addons/l10n_in/models/product_template.py
> +            if check_hsn and len(record.l10n_in_hsn_code) < int(company.l10n_in_hsn_code_digit or '8'):
```suggestion
            if check_hsn and len(record.l10n_in_hsn_code) < int(company.l10n_in_hsn_code_digit):
```

2024-01-05 08:49 UTC, jva-odoo approved these changes

2024-01-05 15:40 UTC, JulienAlardot requested changes
Please improve the commit message
We don't want to know what you're doing, more about the reason behind the change :)

2024-01-08 07:02 UTC, kasp-odoo commented
Hey, @JulienAlardot I have updated the commit message.

Have a great day 😇

2024-01-11 14:19 UTC, jco-odoo commented
Could we avoid the boolean field as we could just not set the selection?

2024-01-11 14:45 UTC, jco-odoo commented
@robodoo r+

2024-01-11 22:02 UTC, closed without merging