[FIX] account: fix traceback when from or to value is false
odoo/odoo pull request #145933
Opened 2023-12-12 12:32 UTC by alsh-odoo

This traceback arises when the user removes the `from` or `to` values.

To reproduce this traceback:

1) Install `account_accountant` and make sure the debugger mode is on 
2) Open `Accounting/Configuration/Account Groups`
3) Create a new record
4) Give the `from` value  and then remove the `to` value

Error:- 

```
TypeError: '>' not supported between instances of 'str' and 'bool'
  File "odoo/http.py", line 2157, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "addons/web/models/models.py", line 1069, in onchange
    todo = [
  File "addons/web/models/models.py", line 1072, in <listcomp>
    if field_name not in done and snapshot0.has_changed(field_name)
  File "addons/web/models/models.py", line 1185, in has_changed
    return self[field_name] != self.record[field_name]
  File "odoo/models.py", line 6584, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/fields.py", line 1151, in __get__
    self.recompute(record)
  File "odoo/fields.py", line 1366, in recompute
    apply_except_missing(self.compute_value, recs)
  File "odoo/fields.py", line 1339, in apply_except_missing
    func(records)
  File "odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
  File "odoo/models.py", line 4858, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 101, in determine
    return needle(*args)
  File "addons/account/models/account_account.py", line 841, in _compute_code_prefix_start
    if not group.code_prefix_start or group.code_prefix_start > group.code_prefix_end:
```

When removing the `to` value `code_prefix_end` will be False. 
It leads to the above traceback from here.

https://github.com/odoo/odoo/blob/230b680bf92583c9f5e4a3739be1d8602df44331/addons/account/models/account_account.py#L838-L842

sentry-4715927815

2023-12-12 12:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/145933).

2023-12-13 06:13 UTC, alsh-odoo commented
Hello @odoo/sentry_reviewers 

Can I have your review on this?

Thank You :innocent:

2023-12-13 12:35 UTC, lordkrandel commented
Hello, isn't this bug also present in Odoo 15?
https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_account.py#L628

(Also, why are there 2 computes for 2 stored fields depending on each other while there could be one depending on both? 🤔 But it's stable so I don't think we'll change that)

2023-12-13 13:09 UTC, alsh-odoo commented
Hello @lordkrandel 
Thanks for reviewing this PR!!

In the previous versions whenever the user removes the value from the `Char` field it returns an empty string(`''`).
From 17.0 it is returning `False`, Because of that error is occurring.

Give your feedback on this if I am wrong.

Thank You !!

2023-12-13 15:54 UTC, lordkrandel requested changes
Something is different because of the `onchange` -> `depends` switch. From the interface, it's fixed, so LGTM.

From the console though (and therefore possibly from server actions) something's strange. If it's simple, can you fix it here, so we avoid other PRs? (Looks like it finds the same record while finding the parent?)
![image](https://github.com/odoo/odoo/assets/1665365/6b684eda-3863-4276-aba4-ac9e3dd704cf)

2023-12-13 16:11 UTC, agr-odoo commented
It seems we have the same error also in `saas-16.4`, but only when unsetting `From`

2023-12-13 17:14 UTC, lordkrandel commented
Ah, true, I forgot we won't be on `17.0` with `saas` for quite a while. So we gotta move this back to `saas-16.4`.

2023-12-20 06:06 UTC, alsh-odoo commented
https://github.com/odoo/odoo/pull/146920

A new PR has been created for targeting `saas-16.4`

2023-12-20 06:06 UTC, closed without merging