[FIX] l10n_de: tax report input positive
odoo/odoo pull request #146317
Opened 2023-12-14 14:20 UTC by rugo-odoo

In the German tax report, they like to have all their taxes express in positive number. This PR changes the symbol of deductible taxes amount from negative to positive.

task-3100357

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-14 14:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146317).

2024-01-11 10:20 UTC, rugo-odoo commented on addons/l10n_de/data/template/account.tax-de_skr04.csv
@tsb-odoo

2024-08-27 07:30 UTC, rugo-odoo commented
@Levizar can you take another look please ?

2024-09-17 10:42 UTC, Levizar requested changes
Regarding the content of the code: Good job. :100: 

Regarding the commit messages, those are a bit fucked up: :monocle_face:
- first commit message is wrong: it says it is about the sign of the tags but it is just about its name.
- second commit message is correct regarding what it does but has its message displayed twice

2024-09-24 14:36 UTC, Levizar requested changes
https://github.com/odoo/odoo/pull/146317#pullrequestreview-2309372176

2024-09-25 11:38 UTC, Levizar approved these changes
@robodoo r+

2024-09-25 11:50 UTC, robodoo commented
@rugo-odoo @Levizar 'ci/upgrade_enterprise' failed on this reviewed PR.

2024-09-25 13:01 UTC, Levizar commented
@robodoo r-

2024-09-25 13:32 UTC, Levizar commented
@robodoo r+

2024-09-25 13:47 UTC, robodoo commented
@rugo-odoo @Levizar 'ci/template' failed on this reviewed PR.

2024-09-25 14:10 UTC, robodoo commented
@rugo-odoo @Levizar 'ci/runbot' failed on this reviewed PR.

2024-10-07 12:00 UTC, Levizar commented
@robodoo r+

2024-10-07 12:00 UTC, robodoo commented
@Levizar you may want to rebuild or fix this PR as it has failed CI.

2024-10-07 14:42 UTC, closed without merging