[REF] web: model field selector css refactoring
odoo/odoo pull request #146450
Opened 2023-12-15 10:18 UTC by mano-odoo

This PR cleans the SCSS of the model_field_selector_popover
keeping the same functionality with less code using bs utility classes.

Small change was made to the aesthetic of the popover header and footer
removing the background customization. This makes the header and footer
take the default background color of the popover component which 
improves consistency and removes the arrow customization.

The dynamic_placeholder_popover was sharing its styling with the
model_field_popover, therefore it needed to be adapted with utility
classes as well to keep the same styling.

task-3580124

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-15 10:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146450).

2023-12-20 10:44 UTC, chgo-odoo requested changes
Hello @mano-odoo, thanks for your work !

I let some small comments below

2023-12-26 13:07 UTC, mano-odoo commented on addons/web/static/src/core/model_field_selector/model_field_selector_popover.xml
> +                            <button t-attf-class="o_model_field_selector_popover_item_name btn btn-light flex-fill border-0 rounded-0 text-start small fw-normal" t-on-click="() => this.selectField(fi
Worth investigating indeed, I will create a task but it's out of the scope of this PR since as you said it was not introduced by my changes.

2023-12-26 15:03 UTC, chgo-odoo approved these changes
LGTM

2024-01-11 14:45 UTC, Polymorphe57 commented
robodoo rebase-ff r+

2024-01-11 14:45 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-01-11 22:02 UTC, closed without merging