[FIX] website: fix page properties dialog buttons
odoo/odoo pull request #146541
Opened 2023-12-15 17:09 UTC by xO-Tx

Steps to reproduce:

Go to the website's home page > Site > Properties > The control panel buttons in the footer of the "Page Properties" dialog are not aligned correctly.

The "Page Properties" dialog extends the `FormViewDialog` component and updates its template using `xpath` to add extra buttons on the right side of the footer (to "duplicate" & "delete" the current page). But since [1], a `w-100` class has been added to the default button container (`.o_cp_buttons`) on form view dialogs to get the same result as the "More Options" button on `Calendar > Quick Create` dialogs (the difference here is that the extra button was added inside the default buttons wrapper, while on page properties, the buttons are added next to it).

The goal of this commit is to "safely" fix this misalignment issue on stable by simply removing the `w-100` class for the page properties dialog. On master, we will replace the template structure with the following implementation:

- Inherit `web.FormViewDialog.ToOne.buttons` instead of the whole `web.FormViewDialog` template.

- Add the extra buttons inside the `.o_cp_buttons` > `.o_form_buttons_edit` using `xpath`.

- Use this template as `this.viewProps > buttonTemplate`

- Pass the `clonePage` & `deletePage` handlers as props to the form controller, where the `buttonTemplate` template will be called.

This way, the page properties buttons will have the same structure as on the calendar dialog.

[1]: https://github.com/odoo/odoo/commit/7dd6e5d1a55de99a4212abc6f24490e47d9ce5bb

task-3642712

2023-12-15 17:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146541).

2023-12-15 17:26 UTC, qsm-odoo commented
@robodoo delegate=sobo-odoo 
@sobo-odoo

2023-12-19 14:15 UTC, sobo-odoo requested changes
Here is my review :wink: Your fix works well :+1: 
I just have two small comments :slightly_smiling_face:

2023-12-22 09:32 UTC, sobo-odoo approved these changes
It's okay for me :wink: 

@robodoo r+

2023-12-22 12:00 UTC, closed without merging