[FIX] website_sale: check pickUp list
odoo/odoo pull request #146606
Opened 2023-12-18 09:33 UTC by abla001

To reproduce
============
- Website > Shipping methods > Pick-up in store
- Add a description displayed on the eCommerce
- add at least 3 or 4 lines with "enter" in between the lines.
- from the shop select Pick-up in store, the payment button will be locked

Problem
=======
- The method `_disablePayButtonNoPickupPoint` checks if there are pickup points in a shipping method based on the count of children in the selected method
- The description will be counted as child which breaks the checking

Solution
========
check the existence of `.o_list_pickup_locations` instead

opw-3628025
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-18 09:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146606).

2023-12-19 15:04 UTC, abla001 commented
@odoo/rd-ecommerce Hello, what do you think about this fix ?

2023-12-26 11:27 UTC, abla001 commented
@odoo/rd-ecommerce any news about this ?

2024-01-02 13:41 UTC, AntoineVDV commented
Hi @abla001, this PR is still in our review pipe ;)

It might take a little longer because most of the team was or is still on leave, and we have several concurrent fixes ongoing for this file so we'll make sure that they don't cancel each other before merging.

2024-01-09 09:11 UTC, vchu-odoo requested changes
Hello!
Sorry that it took so long to review.
Thank you for your work!
Here are some small suggestions.

2024-01-09 09:14 UTC, vchu-odoo commented on addons/website_sale/static/src/js/website_sale_delivery.js
>          const isPickUp = selectedCarrierEl.lastChild.previousSibling.children;
maybe in master it is better to set `id` or `class` to this container with order location and querySelect it directly instead of checking children

2024-01-10 09:54 UTC, abla001 commented
@vchu-odoo thank you for the feedback, I updated the commit with your suggestions, about removing the check `isPickUp.length > 1` it's no more needed because the element with `.o_list_pickup_locations` must be in the list if it exists, so if `isPickUp.length > 1` is `false` then `hasPickUpLocations` is `false` too

2024-01-10 11:50 UTC, vchu-odoo requested changes
Thank you for your changes!
Just a few remarks to improve the clarity.
Also I noticed that isPayable() also has the same lines that should be adapted accordingly or even can be extracted in a separate function `hasPickupLocations` as you prefer.

https://github.com/odoo/odoo/blob/saas-16.2/addons/website_sale/static/src/js/website_sale_delivery.js#L301-L302

2024-01-10 15:11 UTC, abla001 commented
@vchu-odoo indeed the same logic was repeated, I moved it in a helper method

2024-01-10 16:07 UTC, vchu-odoo requested changes
Hi, thanks you for your work!
In the end, this version is not equivalent to the original one and we went too far for this bugfix.
Sorry for the ping pong, but let us keep it simple and revert to the previous version and repeat the same code in isPayable() function for now. We will perform the cleanup/refactoring in master later.

2024-01-10 17:24 UTC, abla001 commented
@vchu-odoo no problem, I reverted last changes

2024-01-11 09:02 UTC, vchu-odoo approved these changes
Thank you!
LGTM
Could you please resolve the conflicts?

2024-01-11 14:01 UTC, abla001 commented
@vchu-odoo conflict resolved :ok_hand:

2024-01-11 15:41 UTC, AntoineVDV approved these changes
@robodoo r+

2024-01-11 17:31 UTC, closed without merging