[FIX] web: name of the selected example should be in white
odoo/odoo pull request #146815
Opened 2023-12-19 12:56 UTC by labo-odoo

Steps to reproduce the issue:
----------------------------
1. Enable dark mode
2. Go to Project app
3. Create a new project
4. Click on `See examples` in the kanban
5. Select an example.

Actual Behavior:
---------------
The name of the selected example is in black instead of white.

Expected Behavior:
-----------------
The name of the selected example should be in white.

Solution:
--------
Update the font color of the selected example name to white for better
contrast in dark mode.

task-3602610

2023-12-19 12:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146815).

2023-12-22 11:50 UTC, auon-odoo approved these changes
lgtm, thanks!

2024-04-04 10:38 UTC, pparidans requested changes
Could we have steps to reproduce in the commit message ?
Also there is a typo in the created filename :wink:

2024-04-10 08:54 UTC, xavierbol commented
Hello @pparidans 

Done. 😁 

But I think we could retarget the fix in 17. 🤔 

What do you think? 🙂

2024-04-12 12:36 UTC, pparidans commented
> Hello @pparidans
> 
> Done. 😁
> 
> But I think we could retarget the fix in 17. 🤔
> 
> What do you think? 🙂

Well, actually the bug is present since saas-16.3 and the merge of https://github.com/odoo/odoo/pull/112620 .

About the fix in itself now : the actual issue is due to the foreground/background colors used for `.nav-link.active` not being both adapted in dark mode.

To be more precise, the `$white` used for the text is adapted to *black* in dark mode, but the "primary" color used as background isn't. This leads to a contrast issue.

I think that the fix should then target the colors used in `web/static/src/views/kanban/kanban_examples_dialog.scss` instead of adding yet another override.

Something like :
```patch
diff --git a/addons/web/static/src/views/kanban/kanban_examples_dialog.scss b/addons/web/static/src/views/kanban/kanban_examples_dialog.scss
index 0332f978c6f2..a1922e935593 100644
--- a/addons/web/static/src/views/kanban/kanban_examples_dialog.scss
+++ b/addons/web/static/src/views/kanban/kanban_examples_dialog.scss
@@ -12,8 +12,9 @@
 
         // sidebar
         .nav-link.active {
-            background-color: #{$o-brand-primary};
-            color: $white;
+            $o-btn-primary-theme-colors: map-get($o-btns-bs-override, "primary");
+            background-color: map-get($o-btn-primary-theme-colors, "background");
+            color: map-get($o-btn-primary-theme-colors, "color");
             &, &:hover, &:focus, &:active {
                 border-right-color: var(--notebook-link-border-color-active);
             }
```

2024-04-16 16:32 UTC, pparidans approved these changes
@robodoo r+

2024-04-16 17:50 UTC, closed without merging