[FIX] core: change the session format to JSON
odoo/odoo pull request #146923
Opened 2023-12-20 08:12 UTC by thle-odoo

Remove the use of pickle to store the session.
Use JSON to store the session on the filesystem.

2023-12-20 08:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146923).

2024-01-12 09:00 UTC, ryv-odoo commented on odoo/http.py
> -from .tools.misc import pickle
Should we remove (or deprecated at least) our pickle version from the misc.py ? AFAIK, you remove the last usage.

2024-01-12 09:54 UTC, Julien00859 requested changes
Is there a task or anything? Why are we changing this? What's about all the existing sessions actually stored on servers? Is there a migration strategy? What's the benefit of using json when you can already access the content of the sessions using `python3 -m pickle ~/.local/share/Odoo/sessions/<prefix>/<session>`? What's about the non-json-serializable values such as datetimes? Did you reach anyone from internal or the python framework about this change?

2024-01-12 10:06 UTC, beledouxdenis commented
> Is there a task or anything? Why are we changing this? What's about all the existing sessions actually stored on servers? Is there a migration strategy? What's the benefit of using json when you can already access the content of the sessions using `python3 -m pickle ~/.local/share/Odoo/sessions/<prefix>/<session>`? What's about the non-json-serializable values such as datetimes? Did you reach anyone from internal or the python framework about this change?

Yes, this is a part of a taskin RD Security

2024-01-12 10:11 UTC, beledouxdenis commented
> Is there a task or anything? Why are we changing this? What's about all the existing sessions actually stored on servers? Is there a migration strategy? What's the benefit of using json when you can already access the content of the sessions using `python3 -m pickle ~/.local/share/Odoo/sessions/<prefix>/<session>`? What's about the non-json-serializable values such as datetimes? Did you reach anyone from internal or the python framework about this change?

There are multiple concerns regarding the use of pickle. Pickle being considered as not safe in the first place, because exploits allow to execute code during the unpickling.
Hence why we had in the first place to have our own pickle load/dump to restrict it as much as possible:
https://github.com/odoo/odoo/blob/bad1edb6b307a74c97a6921da6f898302e7d8f05/odoo/tools/misc.py#L1468-L1504

The fact we used pickle up to now is for historic reason only. That we used werkzeug's implementation for the HTTP layer, and werzkeug's sessions used pickle.

This is just generally safer to store sessions in JSON. I see you look outraged by the removal of the use of pickle for this. Do you see any good reason to keep them in pickle ?

2024-01-12 10:28 UTC, Julien00859 commented
I see one pretty big reason, that all sessions currently stored on all servers are in pickle and not json.

I can imagine doing a kind of "try json first and if it doesn't work use pickle" but this is going to impact **all** requests and decrease performances. That code is going to stay around for a very long time because of people upgrading from older versions. The other solution I see is a migration script that goes and migrate every single session from pickle to json.

Also what's about backups? Looking at `def dump_db(db_name, stream, backup_format='zip')` we don't backup the sessions so if someone attempt an upgrade (say 17.0 -> 18.0), test it a bit (have its sessions converted to json) and then backtrack to 17.0 then there'll be a mix of json and pickle sessions in the filestore. Happily there is a big `try/except` around `pickle.load` so he would just receive an empty session (he would have to log in again, not a big deal). But still, I'm uneasy with this and would like we think about it a bit more.

What annoyed me most is that is kind of popped in my notifications without any prior head up and that the commit message is empty of any rational and wasn't referring any task. It looked more like a caprice "json is just better" like the usual "xmlrpc is bad because nobody like xml, why don't you have rest json api instead?".

2024-03-06 08:36 UTC, beledouxdenis commented
robodoo override=ci/security r+

2024-03-06 11:38 UTC, closed without merging