[FIX] hr_holidays, resource: use employee time-zone for leave compute
odoo/odoo pull request #146938
Opened 2023-12-20 10:22 UTC by mattismegevand

Steps to reproduce:
- Create Allocation for 20 days for Mitchell Admin and validate (12/01 to 12/31).
- Set Working Schedule "Standard 40 hours/week" to UTC timezone.
- Set Mitchell Admin's timezone to Europe/Zurich.
- Create a time off with type Extra Time Off with dates 12/29 - 12/29 and try to save.
- Receive Validation Error: There is no valid allocation to cover that request.

Issues:
You cannot request that leave due to a timezone mismatch, even though you should be able to.

Solution:
To solve the zone mismatch we use the employee timezone to compute the attendance intervals.

opw-3619178

2023-12-20 10:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/146938).

2023-12-21 17:37 UTC, nle-odoo reviewed
this (mixing of calendar / employee tz) makes me afraid of potential issue 

I don't understand the fix currently (I would have thought that the employee tz should not matter, that we would compute everything in the resource_calendar tz) but I don't have time until Wednesday to check it further

so if you think it's correct you could propose it to r&d (or if you have doubt ask another pre-review before wednesday)

2023-12-22 14:07 UTC, Bertrand2 requested changes
Just one change and we're good to go!

2023-12-22 14:07 UTC, Bertrand2 commented on addons/hr_holidays/models/hr_employee.py
> +                            duration_info = employee.with_context(employee_timezone=employee_timezone)._get_calendar_attendances(interval_start, interval_end)
Since the context is added in `_get_calendar_attendances`, this is no longer useful :)

2023-12-22 17:34 UTC, closed without merging