[REM] l10n_in: remove audit trail feature
odoo/odoo pull request #147258
Opened 2023-12-22 10:01 UTC by kasp-odoo

Before this commit
==================
As the `account_audit_trail` module was separated from the `l10n_in` module, but there were duplicate views and models of the audit trail feature in the `l10n_in` module.

After this commit
=================
Removed duplicate views and models of the audit trail feature from the `l10n_in` module.

task_id: 3326258

2023-12-22 10:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/147258).

2024-01-08 08:27 UTC, rugo-odoo requested changes

2024-01-08 08:27 UTC, rugo-odoo commented on addons/l10n_in/models/company.py
If I'm not mistaken, you are removing this behavior (i.e. not being allowed to deactivate the audit trail) completely. Is it intended ?

2024-01-08 08:41 UTC, kasp-odoo commented on addons/l10n_in/models/company.py
Hello @rugo-odoo, this behaviour has been added to the `account_audit_trail` module at the setting level. So, it isn't required here.

2024-01-08 12:11 UTC, rugo-odoo commented on addons/l10n_in/models/company.py
I think there is a difference tho. Here you can't deactivate it once it's active and the behavior in `account_audit_trail` you can't deactivate it once there are moves. So it is not really the same (if I'm not mistaken).

I don't have a problem with the change in behavior as long as it is intended.

2024-01-08 12:20 UTC, kasp-odoo commented on addons/l10n_in/models/company.py
But now, it is not required at all in `l10n_in`.

2024-01-08 12:21 UTC, rugo-odoo commented
LGTM (cc @william-andre)

2024-01-10 10:53 UTC, william-andre commented
@robodoo r+

2024-01-10 10:53 UTC, william-andre approved these changes

2024-01-10 22:20 UTC, closed without merging