[16.0][FIX] hr_expense: Add missing fields in api.depends
odoo/odoo pull request #147609
Opened 2023-12-27 17:43 UTC by grindtildeath

Description of the issue/feature this PR addresses:

Somehow, some expenses are created with a unit_amount being equal to 0.0, and as this field is used to define the amount on the account move lines being created, it does not look good.

Current behavior before PR:

Some expenses have 0 as unit_amount even if total_amount, total_amount_company and unit_amount_display are set properly.

Desired behavior after PR is merged:

Ensure computation of unit_amount is triggered so that no expense has 0 as unit_amount if total_amount, total_amount_company and unit_amount_display are set properly.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-27 17:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/147609).

2024-01-04 10:51 UTC, aliyatastemirova reviewed
Hi, thank you for the fix!
I think `total_amount_company` should be precomputed for this to work.
Also, could you please explain how to reproduce this issue? :slightly_smiling_face:

2024-01-22 12:43 UTC, aliyatastemirova requested changes
hi, could you please let me know if you have an update on the questions above? thanks :slightly_smiling_face:

2024-01-22 19:00 UTC, grindtildeath commented
Hello @aliyatastemirova 

We're still figuring out how to reproduce this exactly to work on a proper fix. I guess I'll ping you back as soon as we did.

2024-01-23 08:46 UTC, aliyatastemirova commented
@grindtildeath thanks! :slightly_smiling_face:

2024-04-03 13:04 UTC, closed without merging