[FIX] web: fix record saving issue
odoo/odoo pull request #147665
Opened 2023-12-28 10:35 UTC by kcv-odoo

Steps:
- Open the Project module.
- Open any project.
- Add a subtask.
- Without manually saving the subtask beforehand, click on 'View'. Form view of sub-task opens that doesn't have any of the fields it should inherit from its parent task.
- Go back to the parent task using the breadcrumbs.
- Click on 'View' again. Now, the sub-task has all of its fields set as it should.

Issue:

- After clicking on 'View', the form view of the sub-task opens, but it doesn't have any of the fields it should inherit from its parent task.

Cause:

- On clicking 'View', the switchToForm action is called, and this action doesn't save records before switching to the form view. Also, it should load that record into the Parent task after saving. In other modules, when clicking on 'View', the openRecord action is called,  which is also not saving data.

Fix:

- Records should be saved when the action is called on clicking 'View'. For the project module, when the action is called, after saving the record, it should also load records in the parent task.

Task: 3508251

2023-12-28 10:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/147665).

2024-01-02 14:17 UTC, pkyriakou reviewed
Thank you @kcv-odoo for your work :100: 
I don't have any comments to make so LGTM :green_circle: but the website team might have more comments to make as it is their scope.

2024-01-09 16:33 UTC, xavierbol commented
Hello @kcv-odoo 

It seems a test in the runbot failed because of your changes. 🤔 
This one: `web > Views > ListView > Adding new record in list view with open form view button`

2024-01-10 04:41 UTC, kcv-odoo commented
Hello @xavierbol

Should be fine now :innocent:

2024-01-10 12:01 UTC, xavierbol reviewed
Thanks for your work, I will let @odoo/rd-framework-js do the final review. 🙂

2024-01-11 09:20 UTC, pparidans requested changes

2024-01-11 09:20 UTC, pparidans commented on addons/web/static/src/views/fields/x2many/x2many_field.js
> +        if (await this.props.record.isDirty()) {
Why do you target `this.props.record` instead of just `record` ? :thinking:

2024-01-11 12:07 UTC, aab-odoo commented on addons/web/static/tests/views/fields/many2many_tags_field_tests.js
> +        await assert.verifySteps([]);
nope :-)

2024-01-11 12:07 UTC, aab-odoo commented on addons/web/static/tests/views/fields/many2many_tags_field_tests.js
> +        await assert.verifySteps(["selectRecord"]);
nope :-)

2024-01-11 12:07 UTC, aab-odoo commented on addons/web/static/tests/views/fields/many2many_tags_field_tests.js
>          await nextTick();
not necessary anymore then

2024-01-11 12:07 UTC, aab-odoo commented on addons/web/static/tests/views/fields/many2many_tags_field_tests.js
>          await nextTick();
same

2024-01-11 12:07 UTC, aab-odoo commented on addons/web/static/tests/views/list_view_tests.js
> +        a.dispatchEvent(new Event("input", { bubbles: true }));
this looks a bit artificial, can't you use the editInput helper?

```js
await clickAdd();
assert.containsN(...,5);
await editInput(...);
await click("open_form_view");
assert.verifySteps();
```

2024-01-12 10:57 UTC, aab-odoo commented
@kcv-odoo runbot is red, you check there're 5 records before click on add

2024-01-17 07:28 UTC, kcv-odoo commented
Hello @aab-odoo,

Opps, Should be fine now :innocent:

2024-01-17 07:36 UTC, aab-odoo approved these changes
robodoo r+

2024-01-17 08:26 UTC, aab-odoo commented
@kcv-odoo it's red again

2024-01-17 08:45 UTC, kcv-odoo commented
@aab-odoo should be fine now :100: :crossed_fingers:

2024-01-18 13:53 UTC, aab-odoo approved these changes
robodoo r+

2024-01-18 21:49 UTC, closed without merging