[FIX] account: create secure sequence on journal creation.
odoo/odoo pull request #147738
Opened 2023-12-29 10:09 UTC by JordiBForgeFlow

Currently the secure sequence is only created on the write operation. But during the set up of a new company, when the inventory valuation and other journals are created upon setting up the chart of accounts, only the create method is called, not the write, and as a consequence no secure sequence is created.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-12-29 10:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/147738).

2023-12-29 12:20 UTC, JordiBForgeFlow commented
See proposed fix to OCA https://github.com/OCA/account-financial-tools/pull/1799. But makes more sense to have the fix in odoo core.

2024-01-17 10:16 UTC, JulienAlardot approved these changes
LGTM @epictete 
Kinda hidden by other modules (E.G. account_check_printing) that write in create inheritance

2024-01-22 16:06 UTC, epictete requested changes
Hello @JordiBForgeFlow 
Thanks for your contribution :slightly_smiling_face: 
Could you please target the oldest supported version (as described [here](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch))?
Thanks!

2024-01-22 16:06 UTC, epictete commented on addons/account/models/account_journal.py
> +                journal._create_secure_sequence(['secure_sequence_id'])
```suggestion
            if journal.restrict_mode_hash_table and not journal.secure_sequence_id:
                journal._create_secure_sequence(['secure_sequence_id'])
```
Why loop twice on `journals`? :wink:

2024-05-30 08:52 UTC, JordiBForgeFlow commented
Closing, as it has already been considered in https://github.com/odoo/odoo/commit/b48e66ed3a4157ca65bdd4c519b797cc6509b9a3

2024-05-30 08:52 UTC, closed without merging