[ADD] l10n_mt: basic package
odoo/odoo pull request #147902
Opened 2024-01-03 10:31 UTC by malb-odoo

This commit will add the basic package of the malta localisation.
- COA
- Taxes
- Default settings
- Tax report
- Fiscal position

task: 3627705

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-03 10:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/147902).

2024-01-03 10:42 UTC, malb-odoo commented
For the reviewer: I didn't translate in Maltese because 88% of Malta speak English and their legal text are written in English also 
the language Maltese seem to be inexistent in Odoo

2024-02-26 16:26 UTC, RicGR98 reviewed
Thanks for the PR ! :)

Some files were translated but not others, any reason why ?

I'll check the Enterprise PR tomorrow :sun_with_face:

2024-02-27 07:11 UTC, malb-odoo commented on addons/l10n_mt/data/template/account.fiscal.position-mt.csv
> +"id","name","sequence","auto_apply","vat_required","country_id","country_group_id","tax_ids/tax_src_id","tax_ids/tax_dest_id","name@hr"
mistake here should be mt, but since the language of malta is for 88% of the population English i think we can remove the column

2024-03-07 10:28 UTC, RicGR98 approved these changes

2024-03-08 15:57 UTC, oco-odoo requested changes

2024-03-08 15:57 UTC, oco-odoo commented on addons/l10n_mt/data/template/account.tax.group-mt.csv
> +"tax_group_mt_18","VAT 18%","base.mt"
No payable/receivable for tax closing ? :thinking:

2024-03-13 11:47 UTC, oco-odoo approved these changes
@robodoo r+

2024-03-13 18:39 UTC, closed without merging