[IMP] product: Enhance kanban view by hiding empty images
odoo/odoo pull request #148047
Opened 2024-01-04 09:25 UTC by mathysPaul

Improves the visual appeal of the product kanban view by not displaying empty images. This change ensures a cleaner and more professional appearance in cases where a product lacks an image. The layout adjustment also includes moving images to the right side and relocating the 'star' icon to the left of the product title. These modifications contribute to a more organized and visually appealing presentation of products in the kanban view.

task-3638042

2024-01-04 09:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148047).

2024-01-22 08:12 UTC, Demesmaeker requested changes
Hello :duck: 

This seems a bit overkill to me. Why not just check if there is an image directly in the template? Couldn't it be done with an "invisible=..." ?

2024-01-30 12:19 UTC, Demesmaeker requested changes
Hello
This is not working for the product variants nor for the product catalog =]

2024-02-09 09:05 UTC, Demesmaeker approved these changes

2024-03-15 16:00 UTC, Feyensv approved these changes
@robodoo r+
Thanks @chevalierv for the css review :sunglasses:

2024-03-15 16:16 UTC, Feyensv commented
@robodoo r+

2024-03-15 18:30 UTC, closed without merging