[FIX] point_of_sale: sale details report
odoo/odoo pull request #148155
Opened 2024-01-04 15:14 UTC by rhe-odoo

Due to legal considerations, it is necessary to modify the template for certain fields.

We also fix the display of differents values because it was not corretcly displayed. Additionally, rectifications have been made to accurately display various values that were previously incorrect.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-04 15:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148155).

2024-02-16 10:06 UTC, adgu-odoo requested changes

2024-02-16 10:06 UTC, adgu-odoo commented on addons/point_of_sale/views/report_saledetails.xml
> +                                    <span t-out='total_paid'>$</span><span t-out='currency["total_paid"]' t-options="{'widget': 'float', 'precision': currency['precision']}">99.99</span>
```suggestion
                                    <span t-out='currency["symbol"]'>$</span><span t-out='total_paid' t-options="{'widget': 'float', 'precision': currency['precision']}">99.99</span>
```

2024-02-16 10:06 UTC, adgu-odoo commented on addons/point_of_sale/views/report_saledetails.xml
> +                                    <span t-out="currency['total_paid'] - total_paid" >$</span><span t-out='currency["total_paid"]' t-options="{'widget': 'float', 'precision': currency['precision']}"
```suggestion
                                    <span t-out="currency["symbol"]" >$</span><span t-out='currency["total_paid"] - total_paid' t-options="{'widget': 'float', 'precision': currency['precision']}">99.99</span>
```

2024-03-20 13:05 UTC, caburj commented on addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
> +                this.currentOrder.finalized = false;
move this in the override of `push_single_order` after calling `pushToBlackbox`.

2024-06-05 13:30 UTC, tde-banana-odoo commented on addons/test_mail/tests/test_mail_template.py
> +        with self.with_user(self.user_employee.login), self.assertQueryCount(109):  # test_mail: 106
:thinking:

2024-06-10 07:48 UTC, caburj approved these changes
robodoo r+

2024-06-10 10:04 UTC, closed without merging