[FIX] web, *: Update X/Twitter logo
odoo/odoo pull request #148126
Opened 2024-01-04 13:43 UTC by xlu-odoo

*: website, website_twitter

This commit introduces an update to the Font Awesome library, specifically replacing the X/Twitter icon with its new design. It also involves adjustments to a few images and SVG files to incorporate the updated X/Twitter logo.

Technical note: It updates an existing file, originally modified for the addition of the TikTok icon, which was not available in Font Awesome 4.

<details>
<summary>Example Preview</summary>

<table>
<tr>
 <td>Before</td>
 <td> After</td>
<tr>

<tr>
 <td>
 <img alt="before" src="https://github.com/odoo/odoo/assets/80678921/67184a33-d1c7-4dea-b412-e8d0269355cc">
</td>
 <td><img alt="after" src="https://github.com/odoo/odoo/assets/80678921/21604407-5bb9-44f9-86c7-70cae6ac3fb9">
 </td>
 </tr>
 
 <tr>
 <td>
 <img alt="before" src="https://github.com/odoo/odoo/assets/80678921/794fa081-f885-4686-9872-e44f10f6318f">
</td>
 <td><img alt="after" src="https://github.com/odoo/odoo/assets/80678921/82ac24ca-8c3c-4166-b2d1-749e1a53db91">
 </td>
 </tr>

 <tr>
 <td>
 <img alt="before" src="https://github.com/odoo/odoo/assets/80678921/7a95b30a-4a10-49ac-a56b-3c81e44bb312">
</td>
 <td><img alt="after" src="https://github.com/odoo/odoo/assets/80678921/528f96e4-a67c-4a85-bac9-318d9f629d88">
 </td>
 </tr>

 <tr>
 <td>
 <img alt="before" src="https://github.com/odoo/odoo/assets/80678921/5b31ab0e-c1eb-4da3-8606-65774a938031">
</td>
 <td><img alt="after" src="https://github.com/odoo/odoo/assets/80678921/c89d4653-c78b-4190-a1ed-7e17bc7e3f10">
 </td>
 </tr>

 <tr>
 <td>
 <img alt="before" src="https://github.com/odoo/odoo/assets/80678921/1cfdab74-a705-481c-9510-b818e980036d">
</td>
 <td><img alt="after" src="https://github.com/odoo/odoo/assets/80678921/b52aa8f8-b098-4524-8cca-1a56a570fad3">
 </td>
 </tr>
 
</table>

</details>

task-3463530

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-04 13:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148126).

2024-01-09 16:32 UTC, jcs-odoo commented
Hello @xlu-odoo 

In the footer of the Website, the X icon on a white square doesn't work well: the stroke is too thin compared to the other icons. In my opinion, it should rather be a white stroke with no background, like Instagram, as the square shape background is not part of the logo design as it is the case for Facebook and LinkedIn
<img width="176" alt="image" src="https://github.com/odoo/odoo/assets/46810843/d1d352bc-5327-44f6-adb0-e0549c8f8fcd">

For the app icon, is there a reason to choose the white-on-black logo? Considering that the black background is not a shape, but just a color, using the "positive" version may be more appropriate. Also, this icon doesn't follow the existing design (in 15.0) as the current Facebook and LinkedIn icons (but neither does Instagram)

Somehow, for the Social Marketing feeds, the black background seems more appropriate, but again, the stroke is too thin. Not sure if this can be improved, though.

**I wonder if X has a dedicated "small icon" version of their logo, though.** When I look at the favicons of X and Twitter, the stroke difference doesn't look this bad. The padding is smaller than in our assets, though.
<img width="176" alt="image" src="https://github.com/odoo/odoo/assets/46810843/23843475-b049-439d-97ce-76ad37a1c996">

Additionally, it's weird not to update the text as well: reading "Twitter" everywhere doesn't make any sense with this logo, now.

I hope this helps :)

2024-01-11 08:27 UTC, xlu-odoo commented
Hello @jcs-odoo , thanks a lot for the feedbacks.

> In the footer of the Website, the X icon on a white square doesn't work well: the stroke is too thin compared to the other icons. In my opinion, it should rather be a white stroke with no background, like Instagram, as the square shape background is not part of the logo design as it is the case for Facebook and LinkedIn <img alt="image" width="176" src="https://private-user-images.githubusercontent.com/46810843/295268729-d1d352bc-5327-44f6-adb0-e0549c8f8fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjA2NzIsIm5iZiI6MTcwNDk2MDM3MiwicGF0aCI6Ii80NjgxMDg0My8yOTUyNjg3MjktZDFkMzUyYmMtNTMyNy00NGY2LWFkYjAtZTA1NDljOGY4ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA4MDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGY3YjA5ZmQyZjYxM2FmY2M4NWY0OTNhNjgzOTc5NWJmMTA4NGYwZjZkODEyY2YyMWVlN2NlYmY3OTFhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vq4_ovRs9MEx6FyeqNhkBGFJVsjI45MBUFXabcHlioQ">

Replaced with just the stroke version (thicker version).

> For the app icon, is there a reason to choose the white-on-black logo? Considering that the black background is not a shape, but just a color, using the "positive" version may be more appropriate. Also, this icon doesn't follow the existing design (in 15.0) as the current Facebook and LinkedIn icons (but neither does Instagram)

Updated with black-on-white. 


> Somehow, for the Social Marketing feeds, the black background seems more appropriate, but again, the stroke is too thin. Not sure if this can be improved, though. I wonder if X has a dedicated "small icon" version of their logo, though.** When I look at the favicons of X and Twitter, the stroke difference doesn't look this bad. The padding is smaller than in our assets, though. <img alt="image" width="176" src="https://private-user-images.githubusercontent.com/46810843/295271424-23843475-b049-439d-97ce-76ad37a1c996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjA2NzIsIm5iZiI6MTcwNDk2MDM3MiwicGF0aCI6Ii80NjgxMDg0My8yOTUyNzE0MjQtMjM4NDM0NzUtYjA0OS00MzlkLTk3Y2UtNzZhZDM3YTFjOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA4MDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZTRhZmQ1MjEzNmNlZTRmODllMzkxYjIwODE3MjA5ZjU3OTI5YWI3YmZmNGU3MDNkYzExNGY3ODFkZmMzMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9uBu8mkjib_cMCxUZcq5Er3o8zEFVsA1uNYvP2a724">

Has been updated with their thicker version.


> Additionally, it's weird not to update the text as well: reading "Twitter" everywhere doesn't make any sense with this logo, now.

 Separate commit, started to replace twitter/tweet/retweet/RT,... references that should no longer exist.

2024-01-12 08:16 UTC, jcs-odoo commented
@xlu-odoo it looks better indeed :)

2024-01-16 09:02 UTC, anso-odoo reviewed
Hello @xlu-odoo ! Some other Twitter relics I found:

The "x/twitter" scroller still mentions Twitter despite having the correct logo
![Screenshot 2024-01-15 at 17 22 28](https://github.com/odoo/odoo/assets/110090660/f0a06ef6-5ef6-48c6-a881-df217b527838)

Same in the apps/modules list 
![Screenshot 2024-01-16 at 09 55 04](https://github.com/odoo/odoo/assets/110090660/ef2062d3-4e67-4313-a53b-d6579bf21d9d)

In this toast as well (in the backend search for twitter wall > click on first row > go to website).
![Screenshot 2024-01-16 at 09 56 31](https://github.com/odoo/odoo/assets/110090660/aa289ac3-8afe-41cd-bf96-f4990c7bd1dc)

Thanks !

2024-01-24 08:15 UTC, xlu-odoo commented
Updated, thank you @anso-odoo . In addition to your found relics, I've found some more.

2024-01-29 08:50 UTC, xlu-odoo commented
@stefanorigano can you check this one when you have time?

2024-02-16 20:13 UTC, euvm-odoo commented
Hello. Is this being worked on? Have found several tickets from customers regarding this. Also, please let me know if there is anything I can help with :))

2024-02-19 07:52 UTC, xlu-odoo commented
> Hello. Is this being worked on? Have found several tickets from customers regarding this. Also, please let me know if there is anything I can help with :))

Hello! Yes it is, it just needs an additional look from @stefanorigano.

2024-02-19 16:49 UTC, stefanorigano reviewed
Hello @xlu-odoo , well done 👍 

Some comments for you... not a lot to check on my side, a dev should verify if there is something risky here (eg. rename a module 😬).

I'd suggest to move fast across versions, even Twitt(ops..)...  "**X**" its in the process of updating old asses. If, for example,  to replace a string hidden somewhere rises migration concerns, let's just skip it for now 😉

Let's focus on website's snippets **content** and other prominent elements.

Thanks!

2024-02-21 10:54 UTC, xlu-odoo commented on addons/website_twitter/__manifest__.py
> -    'name': 'Twitter Snippet',
Being cautious, I now left some `Twitter` terms/strings in some models and controllers (.py) (error message, module name etc,..)

2024-02-22 12:04 UTC, rdeodoo requested changes
Why is it not targeting master (or 17.0 at worst)?
In stable:
- I'd only keep the font-awesome css change so the fa-twitter get the new icon and new color if you really want (I'd not do that in 15 and 16 tho)
- I'd remove all the wording / title / description change, as:
  - It will break translations
  - It will confuse user, eg changing a module name
  
Whatever happen with the PR, don't forget to update `.pot`

2024-02-22 13:06 UTC, xlu-odoo commented
> Why is it not targeting master (or 17.0 at worst)? In stable:
> 
> * I'd only keep the font-awesome css change so the fa-twitter get the new icon and new color if you really want (I'd not do that in 15 and 16 tho)
> * I'd remove all the wording / title / description change, as:
>   
>   * It will break translations
>   * It will confuse user, eg changing a module name
> 
> Whatever happen with the PR, don't forget to update `.pot`

Thank you for your feedback Romain! 

The original spec aimed to affect supported versions from 15 to the latest. 
Following your suggestions, the last update pushed (com & ent) now limit changes to images (except module icon for 15) / icon (fa) / color (except in website as asked for 15.)

If it seems good for you now, could you eventually merge so we can move forward wit others versions? 

( cc @stefanorigano ; I also added a new fontface for twitter, and revert original tiktok only one)

2024-02-28 18:33 UTC, euvm-odoo commented
Hello @xlu-odoo is the plan for this to target 15.0+??

2024-02-29 09:12 UTC, xlu-odoo commented on addons/website/views/website_templates.xml
> +                                <li class="py-1"><i class="fa fa-1x fa-fw fa-twitter mr-2"/><a href="/website/social/twitter" target="_blank">Twitter</a></li>
It shall be adapted for 17+

2024-02-29 17:58 UTC, rdeodoo approved these changes
@robodoo r+

Thank you for having minimized the PR to the fa change and small preview images :+1: 
In master feel free to change everything :+1:

2024-02-29 17:58 UTC, rdeodoo commented on addons/website/views/website_templates.xml
> +                                <li class="py-1"><i class="fa fa-1x fa-fw fa-twitter mr-2"/><a href="/website/social/twitter" target="_blank">Twitter</a></li>
I'll remove this diff, the value is really low in stable, especially 15 (just a tiny bit more beautiful).
But the risk is not null, seems likely that someone xpath'd this element to add a custom social network after it or to hide it or whatever.

Not worth the risk in stable

2024-02-29 19:00 UTC, robodoo commented
@xlu-odoo @rdeodoo linked pull request(s) odoo/enterprise#53644 not ready. Linked PRs are not staged until all of them are ready.

2024-03-01 10:21 UTC, rdeodoo commented
@robodoo r-
See enterprise PR

2024-03-15 20:00 UTC, rdeodoo approved these changes
@robodoo r+


I was hesitating a lot before merging this PR in stable. Even if the PR got trimmed down to the bare minimum.

But:
- as per SRI message [here](https://github.com/odoo/enterprise/pull/53644#issuecomment-1973164756), twitter name and old logo is no more a thing. Regardless if people like it or not: they rebranded.
- clients are complaining about not being able to easily replace the twitter outdated logo by new one, on the other hand, no one should complain about the logo update since it's.. the correct logo now that they rebranded
- we could tell people to upgrade to receive the full twitter -> x update, but it's obviously not a realistic solution for everyone
- the backend will still have some old logo images, which is not a real problem, the need is for the frontend to show the updated logo, people can live with the old logo in their internal backend

2024-03-15 23:03 UTC, closed without merging