[IMP] account, account_payment: add 'sent' stage to invoice
odoo/odoo pull request #148295
Opened 2024-01-05 11:26 UTC by mairasalazar

New stage 'Sent' for invoices/Credit notes sent with Send & Print. Users can see difference between Posted and Sent more easily.

- Add state 'sent' to account move.
- Add this state to the widget bar, but only visible for invoices and credit notes. For those, only visible if move is sent.
- Change invisibility criteria for buttons, so they still show in sent moves.

Still to do by updating the commit once I have olma's perspective: add decoration to the sent stage, add 'sent' to posted filter.

task-3639958

2024-01-05 11:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148295).

2024-01-05 12:43 UTC, malb-odoo commented on addons/account/wizard/account_move_send.py
> +        for move in moves:
I see that there is a loop just above the one you are adding that go through the moves so lets put the modification of the state there :smile:

2024-01-15 16:17 UTC, RicGR98 reviewed
Thanks for the PR :D 

Just an idea on top of my head, what about a ribbon (with Sent instead of Paid) like this ?
![image](https://github.com/odoo/odoo/assets/32981518/6f2e7fa5-81ac-4c47-9f9a-3c7b096ed50c)

2024-01-15 16:17 UTC, RicGR98 commented on addons/account/models/account_move.py
> +        tracking=True,
We already track `is_move_sent` and `state`, so I feel this is a bit redundant
![image](https://github.com/odoo/odoo/assets/32981518/5db33e25-3203-4620-b009-89ed1b767bba)

2024-01-15 16:17 UTC, RicGR98 commented on addons/account/models/account_move.py
> +        ],
Perhaps we should move the common states in a const ? Like for `PAYMENT_STATE_SELECTION`

2024-01-16 07:32 UTC, malb-odoo requested changes
Thanks for the work ! Small comments about formatting since Ricardo already made all the technical comments :smile:

2024-01-16 07:33 UTC, malb-odoo commented on addons/account/models/account_move.py
> +        compute='_compute_visualization_state'
(we could add a comma at the end so that if one day people want to modify the field we keep the github history)

2024-02-14 09:13 UTC, malb-odoo commented
@mairasalazar If i'm not mistaken the task has been closed so this pr can be closed also :smile:

2024-02-15 08:05 UTC, closed without merging