[FIX] website: Patch layout template to replace @ with -
odoo/odoo pull request #148279
Opened 2024-01-05 10:03 UTC by agajic-modoolar

Description of the issue/feature this PR addresses:
Range widget doesn't work with Serbian language, because language locale subtag contains `@`.
Steps to reproduce:
1. Open Runbot instance on Odoo 16.0 enterprise
2. Activate Serbian Latin language (sr@latin), check both checkboxes for "Websites to translate"
3. Go to website and switch to serbian language
4. Navigate to "Prodavnica" (translated "Shop").

Current behavior before PR:
If default theme is selected, then there will be price range widget which will throw "RangeError: Incorrect locale information provided".
This is the problem:
https://github.com/odoo/odoo/blob/4f8779b684cadc5d63129627e7cfe87d35d0793f/addons/website/static/lib/multirange/multirange_custom.js#L267
Multi range widget uses raw lang attribute value of the html tag, which is not compliant with BCP 47 used by javasctipt Intl.NumberFormat()

Desired behavior after PR is merged:
This PR changes website.layout in a way that it replaces `@` with `-` for lang attribute value. This is only going to affect Serbian latin language since it is only one with `@` in the subtag.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-05 10:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148279).

2024-01-05 10:50 UTC, rdeodoo requested changes
I don't think this is the right fix:
- Existing DBs won't receive the fix without a module update, which DB almost never do
- It will set `sr-latin` instead of `sr@latin`, but is that even correct? Shouldn't it be something like `sr_Latn_RS` instead? I guess it prevents the crash and return the serbian format (something like `20. 12. 2012. 03:00:00`) because `toLocaleString` is very permissive: you can type `sr-whatever` and it will ignore `whatever` and still return Serbian, but then we are still passing `latin` which is not right / ignored?
- We already have some places in the frameworkjs code which is handling this case (I checked in 17):
  - https://github.com/odoo/odoo/blame/4f8779b684cadc5d63129627e7cfe87d35d0793f/addons/web/controllers/webclient.py#L32 / https://github.com/odoo/odoo/commit/e71fe9820acc0d21865f9ee7318b2a5e71f7749f
  - https://github.com/odoo/odoo/blame/4f8779b684cadc5d63129627e7cfe87d35d0793f/addons/web/static/src/core/l10n/localization_service.js#L65 / https://github.com/odoo/odoo/commit/caf40dfe2d65df20b71ae701b6ecb6a97b8fbbd7
  - https://github.com/odoo/odoo/blame/4f8779b684cadc5d63129627e7cfe87d35d0793f/addons/web/static/src/legacy/js/public/public_root.js#L332 / https://github.com/odoo/odoo/commit/ce38e0680145d38d1dbb26b62169c862827147d7
  
  Can't we use those somehow? Getting the locale from the lang was probably not the right way in the multirange. If not, I guess I would patch the multirange instead in the same way?

2024-01-05 22:07 UTC, agajic-modoolar commented
Actually I don't know why Odoo Locale codes doesn't comply with BCP 47 standard. Are there any plans to fix this?

Above mentioned issue is the source of the problems, everything else are workarounds :) I don't think this is perfect solution either.

Since it is already established practice to handle sr@latin as an exception, I will update my PR to do it that way, but it is just a matter of time when new issue like this will emerge.
You are correct about format, number is not problem, but formatting long date with "sr-latin" would use only "sr" part and it will write month in cyrilics.

2024-01-08 18:26 UTC, rdeodoo approved these changes
@robodoo r+ squash (to use the PR details as commit msg)

Thanks a lot. Your contribution is really appreciated.
I just edited the PR title and description so it fit our commit guidelines

2024-01-08 18:26 UTC, robodoo commented
Merge method set to squash.

2024-01-08 19:38 UTC, closed without merging

2024-01-08 19:55 UTC, agajic-modoolar commented
You're welcome. Thank you for quick review. ;)