[FIX] account: Take into account caba origin in tax tag invert compute
odoo/odoo pull request #148448
Opened 2024-01-08 10:52 UTC by ThomasBeckers

Before, the tax tag invert is computed based on the entry type if the entry type is different from "entry" or based on the tax set and the balance of aml for entries with type "entry".

This is fine in most cases but we can reach a wrong tag invert if we use cash basis and down-payment.

Here are the steps to reproduce:
- Create a company with cash basis tax (ex: "TVA 20% (Services)" for l10n_fr)
- Create a product with a cash basis default tax and an income account which is not the default one
- Create an sale order with this product for 100€ + 20% tax
- Create a down payment for 30€ + 20% tax (add the tax to downpayment)
- Create the final invoice with deduction of down payment
- Register a payment on both to create the caba entries => Tax report will show 160€ of base instead of 100€

The deduction aml on the cash basis entry of final invoice have an tag invert at False instead of True. So it's computed as -30€ instead of +30€.

If we reproduce the case with a non cash basis tax, it will work because the move type will be different from "entry" and tag invert will be computed only based on the type.

To solve this issue, we now compute the tag invert based on caba origin move if any to improve the tag invert computation for cash basis entries.

opw-3597141

2024-01-08 10:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148448).

2024-01-08 10:54 UTC, ThomasBeckers commented
Maybe also adapt function `_compute_is_refund` ?

2024-01-08 15:11 UTC, rugo-odoo commented
Can you please add a test for it ?

2024-01-18 08:57 UTC, rugo-odoo requested changes
Nice stuff ! (cc @oco-odoo)

2024-01-18 08:57 UTC, rugo-odoo commented on addons/account/tests/test_account_move_out_invoice.py
> +                (0, 0, {
We can use `Command` for all of those.

2024-01-18 14:13 UTC, ThomasBeckers commented on addons/account/tests/test_account_move_out_invoice.py
> +                (0, 0, {
Should be good now :ok_hand:

2024-01-26 16:08 UTC, oco-odoo requested changes
Alright for me, just a few things :)

2024-01-26 16:12 UTC, oco-odoo commented
Also, would maybe be nice to put a bit more emphasis in the commit on the fact the income account on the base line of the down payment must be different from the other one. It's there, but I missed it and had to ask you ^^ Maybe explicitly saying what it causes: the base lines aren't grouped on the CABA move, so it contains a negative base line.

Finally, I'd also add in the commit no "base received account" should have been configured in the cash basis settings, so that the base accounts of the lines are used.

2024-02-02 11:38 UTC, ThomasBeckers commented
Hey @oco-odoo 
Code and commit message has been changed according to your suggestions :)

2024-02-02 14:12 UTC, oco-odoo approved these changes
@robodoo r+
Thanks :)

2024-02-02 17:09 UTC, closed without merging