[FIX] website_sale,{,delivery}: show payment method on change delivery
odoo/odoo pull request #148431
Opened 2024-01-08 09:41 UTC by Mtaylorr

Issue:
======
Payment methods doesn't show when updating delivery method

Steps to reproduce the issue:
=============================
- Install website_sale
- Activate coupons and promotions in settings
- Create a coupon program with the follwing values : reward: discount, percentage: 100%
- Save the program and generate some coupons
- Activate at least 1 free delivery method and 1 free delivery method
- Activate at least one payment method
- Go to shop add anything to cart
- Apply one of the codes from the generated coupons
- Go to confirm order and change between the delivery methods.
- If the default delivery method is free, the payment methods will never show , otherwise they will always show.

Origin of the issue:
====================
The payment methods were rendered using `t-if` directive which means that we can't toggle it dynamically since they don't exist in the view.

Solution:
=========
Use class `d-none`  to hide/show the payment methods.

opw-3662606

2024-01-08 09:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148431).

2024-01-08 19:41 UTC, nle-odoo approved these changes
looks good to me

2024-01-08 19:41 UTC, nle-odoo commented on addons/website_sale_delivery/static/src/js/website_sale_delivery.js
>          if (result.new_amount_total_raw !== undefined) {
we do this code only if `result.new_amount_total_raw` !== undefined, if undefined is a possibility, shouldn't the new code only be called if the value is not undefined too?

2024-01-08 19:41 UTC, nle-odoo commented on addons/website_sale_delivery/static/src/js/website_sale_delivery.js
> +            document.querySelector('#website_sale_non_free_cart').classList.remove('d-none');
I think this will raise an error if we don't do -u of website_sale, but the fix should work even if the module has not been updated

2024-01-08 19:41 UTC, nle-odoo commented on addons/website_sale_delivery/static/src/js/website_sale_delivery.js
> +        }else {
missing space before `else`

2024-01-11 16:25 UTC, vchu-odoo requested changes
Hello,
Thank you for your work on this bug!
Changing the template can usually cause a lot of problems for the existing users.
The better solution would be to reload the page when the user selects the carrier or when the amount is changed from/to zero (even better). That way the template will be re-rendered with the correct values.
However, for versions < 16.2 when the user reloads the page the choice of carrier is reset to default one. I found the fix in 16.2 version of this issue. Maybe we can do the similar fix for versions 15.0 -16.1. In that case we will avoid changing the template and can just do the page reload in js for all versions. Let me know if you have any concerns.
- https://github.com/odoo/odoo/pull/133151

2024-01-12 09:13 UTC, Mtaylorr commented
@vchu-odoo , thanks for the suggestion , I made the fix as you requested , let me know what you think, thanks

2024-01-12 10:06 UTC, vchu-odoo commented
Hello, @Mtaylorr !
Before any testing, could you please fix the test in runbot and split the changes in 2 commits: one commit would be only used for version <16.2 (changes in controller) and the second one in js file (which is a real bug fix) would be applied for every version?

2024-01-15 09:26 UTC, vchu-odoo approved these changes
Thank you for the changes! Great work!
LGTM
There are small nitpickings that are not blocking.

2024-01-15 09:26 UTC, vchu-odoo commented on addons/website_sale_delivery/static/src/js/website_sale_delivery.js
> +            // reload page only when total switch between zero and not zero
```suggestion
            // reload page only when amount_total switches between zero and not zero
```

2024-01-15 09:26 UTC, vchu-odoo commented on addons/website_sale_delivery/static/src/js/website_sale_delivery.js
> +            const hasPaymentMethod = document.querySelector("div[name='o_website_sale_free_cart']") === null;
We try to limit the code line to be < 100 as it eases the code review.
```suggestion
            const hasPaymentMethod = document.querySelector(
                "div[name='o_website_sale_free_cart']"
            ) === null;
```

2024-01-15 10:27 UTC, AntoineVDV approved these changes
Hi, could you please update your commit messages and PR description to link the odoo/odoo commit hash (the one that was merged, linked by robodoo at the bottom of the original PR) rather than odoo-dev/odoo's? The latter will soon be garbage-collected by GitHub because it has no branch.

I've asked the PO to do a testing round to be sure.

2024-01-15 13:43 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2024-01-15 13:44 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-01-15 17:09 UTC, closed without merging