[FIX] l10n_es_pos: handle missing partner in the ReceiptHeader template
odoo/odoo pull request #148688
Opened 2024-01-09 14:02 UTC by ushyme

Currently, if you have Spanish POS installed and create a Cash In/Out, you are met with an error.

### Steps to reproduce

* install `l10n_es_pos`
* start a POS session
* click on the hamburger button in the top-right corner > Cash In/Out
* add any amount and confirm

You should be met with an error.

opw-3667287

2024-01-09 14:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148688).

2024-01-15 16:31 UTC, epictete requested changes
Hello @ushyme 
I agree with the fix, but please provide some more context as to why the fix is needed.
It's not obvious since the optional chaining operator should be OK at first glance :nerd_face:

2024-01-16 09:04 UTC, ushyme commented
Hello @epictete,
I added an explanation on the commit. 
Thanks for taking the time to look into this.

2024-01-16 14:31 UTC, epictete approved these changes
Thanks for the update :+1: 
I added a few more details in the PR description :nerd_face: 

@robodoo r+

2024-01-16 19:18 UTC, closed without merging