[FIX] website: fix video width in image gallery
odoo/odoo pull request #148637
Opened 2024-01-09 10:25 UTC by bvr-odoo

Steps to reproduce:
- Enter edit mode.
- Drag and drop an "Image Gallery" snippet onto the page.
- Double-click on an image within the snippet.
- In the media dialog, click the "Video" tab.
- Copy-paste a YouTube video URL into the URL input.
- Save the media dialog by clicking on the "Add" button.
- Bug: The video is very small.

Note that the "image gallery" snippet (also the "image wall" snippet) was not initially designed to handle anything other than images. When you click on the "Add" button of the snippet, you can only add images.

However, by following the steps described above, it's possible to work around this limitation and add a video to the snippet. Since this was not part of the original plan, several options do not function correctly with a video.

Instead of preventing the addition of videos, we have chosen to allow it and focus on fixing the main issue (the small size of the video). So, if someone specifically wants to add a video, it's currently possible, though some features may not work as intended.

task-3597156

2024-01-09 10:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148637).

2024-01-12 13:31 UTC, qsm-odoo commented
@robodoo delegate=Guillaume-gdi 
@Guillaume-gdi

2024-01-16 09:18 UTC, Guillaume-gdi requested changes
Good commit message, diff and comment. Thanks :+1:
1. I saw the conversation on the task about the fact that options will not work as expected when a video is present in the carousel and in the image wall. IMO we could at least inform the user that the options are not working in this case (maybe inform them to add the video at the last moment, when all the rest of the design is finished) no ?
2. I think you should do some scss adaptation in `.s_image_gallery[data-vcss="001"] {` so that the video is well placed in the image wall. For now, drop image wall and replace an image by a video, you end up with a wrong margin between elements and the block looks broken. I think a few scss change could solve that.
![image](https://github.com/odoo/odoo/assets/78849981/a6f1c57c-e56c-4c87-aa8b-9f50d53e7085)

2024-01-16 09:25 UTC, bvr-odoo commented
> Good commit message, diff and comment. Thanks 👍
> 
> 1. I saw the conversation on the task about the fact that options will not work as expected when a video is present in the carousel and in the image wall. IMO we could at least inform the user that the options are not working in this case (maybe inform them to add the video at the last moment, when all the rest of the design is finished) no ?
> 2. I think you should do some scss adaptation in `.s_image_gallery[data-vcss="001"] {` so that the video is well placed in the image wall. For now, drop image wall and replace an image by a video, you end up with a wrong margin between elements and the block looks broken. I think a few scss change could solve that.
>    ![image](https://private-user-images.githubusercontent.com/78849981/296993508-a6f1c57c-e56c-4c87-aa8b-9f50d53e7085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTcwMTgsIm5iZiI6MTcwNTM5NjcxOCwicGF0aCI6Ii83ODg0OTk4MS8yOTY5OTM1MDgtYTZmMWM1N2MtZTU2Yy00Yzg3LWFhOGItOWY1MGQ1M2U3MDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA5MTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYmIwNjE0MjAxYmIxZGIzOTcwZTlkNjZhMzhjMTUwOTJmZGJiZmNkM2MzNjFmMmQ0ZjA0NDYwZDllNGRmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hl-ketQ-e_Q1PK3P9O9oObnJl8UBwQevq6Cmrdo67k)


There are a lot of issues with Image Wall/Image Gallery videos, so I don't know what we want to allow or not... 
I think it's is a question for @pde

2024-01-16 09:28 UTC, pierre-pde commented
@bvr-odoo  & @Guillaume-gdi ,
The idea is to make some easy improvement that improve video in image wall & carousel.
Even though we're aware it's gonna be perfect until we make a nice imp in master:)

2024-01-16 14:09 UTC, bvr-odoo commented
@Guillaume-gdi I fixed the "spacing" options for videos in the "Image Wall" snippet.
Thanks for the idea, indeed it was an easy fix

2024-01-16 15:21 UTC, Guillaume-gdi approved these changes
Thanks for the adaptations :+1: @bvr-odoo 

As mentioned in the commit message, videos are not yet fully supported in blocks Image wall and Image gallery but, thanks to this PR, with a little tweaking, it's possible to use a video in blocks Image wall and Image gallery and it looks good.
For example:
- in the Image wall block, position all the elements correctly and then replace the images with videos.
- in the Image gallery block, first upload an image (which will act as a preview in the indicator below the block) and then replace the image with the video.

Globally, the best thing to do is to configure your block as you like, with an image instead of a video, and once the block is finished, replace the image with the desired video.

A task will be made in the future to fully support videos and ensure that all options work properly.

@robodoo r+

2024-01-16 17:34 UTC, closed without merging