[FIX] l10n_ch: fix data migration
odoo/odoo pull request #148724
Opened 2024-01-09 16:03 UTC by clbr-odoo

In a previous commit we fixed Swiss localization's taxes data. We changed two children taxes that had wrong tax_type_use since it depends on their parents.
This could raise the python constraint `_check_children_scope()` which is preventing some databases to correctly update their taxes.

See https://github.com/odoo/odoo/commit/7b07df873535446f97abc1de9176b9332de5cb07

2024-01-09 16:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/148724).

2024-01-12 13:54 UTC, oco-odoo requested changes

2024-01-12 13:54 UTC, oco-odoo commented on addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
Shouldn't we increase the module version in the manifest ? 
Also, isn't it better (for upgrades) to do it as a pre-script ? (so that it is fixed *before* running the actual upgrade script). But then, you can't rely on creating an environment :/ 
But I think it could be done directly in SQL, with a single query :thinking:

2024-01-15 15:07 UTC, clbr-odoo commented on addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
We discussed it and decided it was not problematic enough to deserve a version change.
We only need it to be fixed for this script to run correctly, which is also why I fixed it in existing end- script.
But if you changed your mind totally fine by me to change it in pre- and increase the version number :smirk:

2024-01-19 14:07 UTC, oco-odoo commented on addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
Aaaaaah, alright ; I missed the fact this file already existed and contained the problematic script. So, we're sure it'll run, and the version number actually already has been increased ^^

2024-01-19 14:07 UTC, oco-odoo approved these changes
@robodoo r+

2024-01-19 14:40 UTC, robodoo commented
@clbr-odoo @oco-odoo staging failed: ci/runbot on efc5dd87be944b4b8d1d0300ea5562ffb3e7e885 (view more at https://runbot.odoo.com/runbot/build/56725367)

2024-01-19 14:41 UTC, oco-odoo commented
@robodoo retry

2024-01-19 15:25 UTC, closed without merging