[ADD] product: Add demo data for multi-valued attribute
odoo/odoo pull request #149158
Opened 2024-01-12 08:49 UTC by mathysPaul

Adds demo data in the Product module to showcase the Multi-checkbox attribute. The 'Extra Options' attribute is introduced with the following choices:
- 1 year warranty extension (extra price 50)
- Cleaning kit (extra price 5)
- Protection kit (extra price 10)

This attribute is linked to the product:
- Outdoor dinning table:
  - Storable
  - Price : 589
  - Category: Outdoor furniture

This setup demonstrates the new attribute's capabilities in enhancing product customization without affecting variant generation.

task-3610666

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-12 08:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149158).

2024-01-19 13:57 UTC, vava-odoo requested changes
Thanks @mathysPaul 
Looks overall good, only made a few minor comments.
Could you please squash your commits?
Cheers!

2024-01-19 13:57 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +            <field name="detailed_type">consu</field>
Default value
```suggestion
```

2024-01-19 13:57 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +            <field name="name">Outdoor dinning table</field>
Typo
```suggestion
            <field name="name">Outdoor dining table</field>
```

2024-01-19 13:57 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +        <!-- the product template attribute lines have to be defined before creating the variants -->
I don't think this comment is really useful, as it is already present in the file
```suggestion
```

2024-01-19 13:57 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +            <field name="value_ids" eval="[(6,0,[ref('product.product_attribute_value_7'), ref('product.product_attribute_value_8'), ref('product.product_attribute_value_9')])]"/>
No need to specify the module if it is defined in the same one in a `ref` + spaces after `,`
```suggestion
            <field name="value_ids" eval="[(6, 0, [ref('product_attribute_value_7'), ref('product_attribute_value_8'), ref('product_attribute_value_9')])]"/>
```

2024-01-30 10:43 UTC, vava-odoo approved these changes
Hi @mathysPaul 
Thanks for the update. It looks good to me now. I only have two small remarks, to be discussed with the team.
I already approve so that it can move on.
Cheers!

2024-01-30 10:43 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +            <field name="parent_id" ref="product_category_all"/>
Maybe a sub-category of Saleable?
```suggestion
            <field name="parent_id" ref="product_category_1"/>
```

2024-01-30 10:43 UTC, vava-odoo commented on addons/product/data/product_demo.xml
> +        <record id="product_template_no_variant_attribute_attribute_4_product_template_attribute_line" model="product.template.attribute.line">
I know you followed the structure above, but this id looks too long to me.

2024-02-08 14:19 UTC, Feyensv approved these changes
@robodoo r+

Pushed updated commit to:
* rename xml ids to highlight more clearly what they represent
* update commit tag from ADD to IMP
* simplify template declaration, no need to have an xml id for the attribute line, the template can be created directly with the right configuration.

2024-02-09 03:47 UTC, closed without merging