[REF][ADD] hr_homeworking : split module in two modules
odoo/odoo pull request #149384
Opened 2024-01-15 12:09 UTC by mepe-odoo

With this commit, employee's work location can be visible on employee view without calendar. The module hr_homeworking_calendar is a bridge module and is auto-install when calendar is installed.

task: 3642327

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-15 12:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149384).

2024-02-08 12:06 UTC, Bertrand2 requested changes
There seems to be a lot of functional changes... :thinking: Is that intended? I don't see any information about that on the task.
Also, I notice that some stuff seem "unfinished" as there are still some logs and a copy of a file hanging around :) 
Thanks!

2024-02-08 12:06 UTC, Bertrand2 commented on addons/hr_homeworking/static/src/components/hr_presence_status/hr_presence_status.js
> +            console.log(color)
You forgot to remove some logs it seems :)
```suggestion
            if (this.props.record.data.hr_presence_state !== "to_define" && this.props.record.data.hr_presence_state !== "offline") {
                color = this.props.record.data.hr_presence_state === "present" ?  "text-success" : "text-warning";
            }
```

2024-02-08 12:06 UTC, Bertrand2 commented on addons/hr_homeworking/static/src/components/avatar_card_resource/avatar_card_resource_popover copy.xml
copy? :thinking:

2024-02-08 12:18 UTC, mepe-odoo commented on addons/hr_homeworking_calendar/static/src/calendar/common/popover/calendar_common_popover.xml
> +                        <Field name="'employee_name'" record="slot.record" readonly="1"/>
nope it wasn't :D

2024-02-09 09:44 UTC, Bertrand2 requested changes
Changes related to the status icon should be moved in a separate fix commit :+1: 
Thanks! :muscle:

2024-02-09 09:44 UTC, Bertrand2 commented on addons/hr_homeworking/static/src/components/hr_presence_status/hr_presence_status.js
> +            if (this.props.record.data.hr_presence_state !== "to_define" && this.props.record.data.hr_presence_state !== "offline") {
According to the odoo js linter:
```suggestion
            if (
                this.props.record.data.hr_presence_state !== "to_define" &&
                this.props.record.data.hr_presence_state !== "offline"
            ) {
```

2024-02-13 13:35 UTC, Bertrand2 approved these changes

2024-03-18 17:09 UTC, sofiagvaladze reviewed
@mepe-odoo this PR is grand combination of split and improvement and fixes, which makes it hard to review.

If it's not too much work, I would like to ask you to separate them in different commits 

So I would like to see separate commit for
1) split
2) imps
3) fixes

2024-03-19 08:31 UTC, mepe-odoo commented on addons/hr/models/hr_employee_base.py
> -                if employee.user_id.im_status in ['online', 'leave_online']:
it's to simplify the heritage :) for example in homeworking you can have office_online or other_online or home_online.

2024-03-21 10:27 UTC, mepe-odoo commented on addons/hr_homeworking/static/src/components/hr_presence_status/hr_presence_status.js
> +                this.props.record.data.hr_presence_state !== "offline"
Yes you're right, I corrected it :)

2024-04-08 15:00 UTC, robodoo commented
@mepe-odoo @sofiagvaladze linked pull request(s) odoo/upgrade#5796 not ready. Linked PRs are not staged until all of them are ready.

2024-04-09 12:53 UTC, closed without merging