[15.0][FIX] calendar: Select correct base event when current is archived
odoo/odoo pull request #149349
Opened 2024-01-15 07:44 UTC by CarlosRoca13

When the base event is archived, it continues being the base event of the recurrence, and when trying to change the recurrence of all the events of the recurrence, some inconsistencies occur.

To test the problem, you can follow these steps:

1. Create a recurrence of events.
2. Archive the base event of the recurrence.
3. Edit usig the "All events" option and change the days of the recurrence.

Only 1 event will exist with the default value of the ‘until’ field and the others will have been deleted.

See next gif:
![ERROR](https://github.com/odoo/odoo/assets/35952655/a58ff1d6-a244-4c3b-a06d-40584dfbbb40)

By making these changes, the base event will be updated, as indicated in the `_select_new_base_event` method, so these inconsistencies will not occur when making the changes.

See next gif:
![Correct](https://github.com/odoo/odoo/assets/35952655/fdbad6b6-e3ac-4dc0-8dd2-cb7014b83857)

cc @Tecnativa TT46742

ping @pedrobaeza @chienandalu 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-15 07:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149349).

2024-01-15 10:35 UTC, pedrobaeza commented
Isn't this reproducible when you add the recurrence from a non-included day? Or do you need to manually archive the base event?

2024-01-15 10:41 UTC, CarlosRoca13 commented
Yes sorry, when a recurring calendar event is created from a day that is not included in the recurrence, it is archived and the recurrence data in that event is lost, but it remains the base event of the recurrence. Therefore, when trying to make changes to the recurrence, the following error is thrown:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 469, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/calendar/models/calendar_event.py", line 502, in write
    self._rewrite_recurrence(values, time_values, recurrence_values)
  File "/opt/odoo/auto/addons/calendar/models/calendar_event.py", line 913, in _rewrite_recurrence
    detached_events = base_event._apply_recurrence_values(new_values)
  File "/opt/odoo/auto/addons/sale_planner_calendar/models/calendar.py", line 51, in _apply_recurrence_values
    return super()._apply_recurrence_values(values, future=future)
  File "/opt/odoo/auto/addons/calendar/models/calendar_event.py", line 809, in _apply_recurrence_values
    return to_update._apply_recurrence()
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 225, in _apply_recurrence
    ranges = recurrence._range_calculation(event, duration)
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 421, in _range_calculation
    ranges = set(self._get_ranges(event.start, duration))
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 435, in _get_ranges
    starts = self._get_occurrences(start)
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 450, in _get_occurrences
    return self._get_rrule(dtstart=dtstart)
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 530, in _get_rrule
    freq_to_rrule(freq), **rrule_params
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 85, in freq_to_rrule
    return SELECT_FREQ_TO_RRULE[freq]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: False
```

2024-01-15 10:45 UTC, pedrobaeza reviewed
And please change the steps to reproduce the problem (both in the main PR message and in the commit message) with the real use case.

2024-01-15 11:56 UTC, pedrobaeza commented on addons/calendar/models/calendar_event.py
> +                ('base_event_id.id', 'in', self.ids)
```suggestion
                ('base_event_id', 'in', self.ids)
```

2024-01-15 11:56 UTC, pedrobaeza commented on addons/calendar/models/calendar_event.py
> +        if "active" in values and not values["active"]:
```suggestion
        if values.get("active") is False:
```

2024-01-15 12:02 UTC, CarlosRoca13 commented
Changes done @pedrobaeza

2024-01-15 12:08 UTC, pedrobaeza approved these changes

2024-01-15 13:28 UTC, arj-odoo requested changes
Hello, thanks for these changes. Could you add a small test to make sure the issue is not coming back ? It will improve our codebase. Thanks a lot. :-)

2024-01-15 16:37 UTC, CarlosRoca13 commented
@arj-odoo test added :smile:

2024-01-16 07:50 UTC, arj-odoo commented on addons/calendar/tests/test_event_recurrence.py
> +        # Wednesday datetime(2019, 10, 30, 1, 0)
Why are you adding a new test class ? The setup will be heavy for just one single test. You can do everything in the current class. Your test coould be in the class TestUpdateRecurrentEvents. Thanks :-)

2024-01-18 07:11 UTC, CarlosRoca13 commented on addons/calendar/models/calendar_event.py
> +            recurrences._select_new_base_event()
For this PR I have used the same philosophy that has been used for the unlink method. So I understand that there will be the same doubt for that method… 

https://github.com/odoo/odoo/blob/777864403118e1b3a8fd0d66c66e1517913e43be/addons/calendar/models/calendar_event.py#L591-L600

2024-01-18 07:14 UTC, pedrobaeza commented on addons/calendar/models/calendar_event.py
> +            recurrences._select_new_base_event()
Anyway, the scope is limited to when you archive an event, so the impact is also very limited.

2024-01-18 19:57 UTC, robodoo commented
@CarlosRoca13 @arj-odoo staging failed: ci/runbot on 2cccbdeb2f28e3439cc0669109012d8d471f8b70 (view more at https://runbot.odoo.com/runbot/build/56671293)

2024-05-15 08:33 UTC, CarlosRoca13 commented
Something has failed when trying to set this changes @arj-odoo

2024-05-15 08:38 UTC, arj-odoo commented
> Something has failed when trying to set this changes @arj-odoo

Can you rebase the code? I lost this one in the process, sorry /o\

2024-05-15 08:52 UTC, CarlosRoca13 commented
Done @arj-odoo

2024-05-15 12:48 UTC, arj-odoo commented
@robodoo r+

2024-05-15 14:24 UTC, closed without merging