Destroy existing widgets before instantiating the wysiwyg
odoo/odoo pull request #149385
Opened 2024-01-15 12:14 UTC by loco-odoo

[FIX] website: destroy widgets before instantiating the wysiwyg

Steps to reproduce the problem:
- Add a "Countdown" snippet on the website.
- Save.
- Enter in edit mode again.

-> Problem: the `destroy()` of the `CountdownWidget` public widget comes from a `widgets_start_request` that is triggered when the `WysiwygAdapterComponent` has been mounted and patched (see [useEffect documentation]).

The goal of this commit is to, as before the task that moved the frontend UI to the backend ([1]), destroy the existing widgets before instantiating the `wysiwyg`. In the website module, the `wysiwyg` is instantiated (trough the `WysiwygAdapterComponent`) when `state.showWysiwyg` is set to "true" (it is set to "true" when the public root is ready i.e. the iframe has been loaded and it exists a website root instance). To solve the problem, the
`WebsiteEditorComponent` and `WebsiteTranslator` component trigger a `widgets_stop_request` on the website root instance when they got notified that the public root is ready and before to instantiate the `wysiwyg`.

Related to runbot-28700

[1]: https://github.com/odoo/odoo/pull/89223
[useEffect documentation]: https://github.com/odoo/owl/blob/master/doc/reference/hooks.md#useeffect

2024-01-15 12:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149385).

2024-01-17 08:35 UTC, loco-odoo commented
Note: for the second commit, the first idea was to use a `useEffect()` inside of the `WebsitePreview` component that would have reacted to a change of `context.isPublicRootReady`. The problem of this solution is that there could be a little delay between the moment where `websiteRootInstance` is set and the moment where `useEffect()` would react to this change as the `useEffect()` will take place at the next animation frame.

2024-01-17 09:50 UTC, qsm-odoo requested changes

2024-01-22 10:22 UTC, loco-odoo commented on addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
> +            $target: this.$editable,
@qsm-odoo , I did that to try to be close to what was done in version 15.0;
```js
        this.trigger_up('widgets_stop_request', {
            $target:$('#wrapwrap'),
        });
```
Indeed, in version 16.0, `this.$editable` reffers to the `wrapwrap` (see `get editable()` in `wysiwyg_adapter.js`). Moreover, no `$target` is used when triggering the `widgets_start_request` which means that the public root will use `wrapwrap` instead (see `_startWidgets` in `public_root.js`). What do you think? :)

2024-01-22 12:52 UTC, qsm-odoo commented on addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
> +            $target: this.$editable,
I think what there was in 15.0 was a mistake already, so I'd rather try not to be close to it :wink: If we plan on doing a "start" without target once edit mode enabled, let's do a full stop too before (whether or not the target is actually the same in the end).

2024-01-23 12:06 UTC, loco-odoo commented
@qsm-odoo , this PR has been adapted according to our discussion :+1:

2024-01-23 13:49 UTC, qsm-odoo requested changes

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
Commit message: 

> This commit also adds a test to ensure that the order of the calls to the widgets and wysiwyg lifecycle methods is coherent.

This is enough for your test explanation in the commit message. The rest should be removed IMO: it only is a duplicate of what I can read reading the code. If the code does not speak for itself, then it should code comments, not commit message paragraph :+1: 

Also about your reference of the website-in-backend task: reference the merged commit, not the PR please :pray:

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
> +window.localStorage.WidgetAndWysiwygLifecycle = window.localStorage.WidgetAndWysiwygLifecycle || "[]";
Details but, why starting that variable name by a uppercase letter? :thinking:

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
> +publicWidget.registry["countdown_patch"] = publicWidget.Widget.extend({
Detail as it is in a test but we now should name public widget registry entries as classes: so here: `registry.CountdownPatch`

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
> +    },
Consistency: you named the event "widgetStart" and "widgetStopped". Choose: either ("widgetStarted" and "widgetStopped") or ("widgetStart" and "widgetStop")

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/tests/tour_utils/widget_lifecycle_patch_wysiwyg.js
> +const patchWysiwyg = () => patch(Wysiwyg.prototype, "widget_lifecycle_patch_wysiwyg.wysiwyg", {
What's the point in creating a function for this if this is to call it only once just after its definition? :thinking:

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/static/tests/tour_utils/widget_lifecycle_patch_wysiwyg.js
> +        // order of the lifecycle method call of the wysiwyg and the widget.
Is not that a bug to fix? Surely it can't be good that the destroy method is called twice?

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/tests/test_widgets.py
> +class TestWidgets(HttpCase):
Add it with the other tests, no point in creating a new file for this new test only (either UI or snippets). We'll probably refactor that at some point to make it more consistent.

2024-01-23 13:49 UTC, qsm-odoo commented on addons/website/tests/test_widgets.py
> +        })
I think you can put that one in the test bundle instead no? It's nice as you did but it may slow down the runbot so best avoid it for this one.

2024-01-24 11:58 UTC, loco-odoo commented
@qsm-odoo , this PR has been adapted according to your suggestion :)

2024-01-24 16:21 UTC, qsm-odoo approved these changes
I made [these finals changes](https://github.com/odoo/odoo/compare/62725933da6945109a90242ec4b7bd49703f4925..b006c9dc82bba392f81dfa33b189481637b3dbb6), some important, some nitpicking while I was at it:
- widget patch in assets_test: what I meant here https://github.com/odoo/odoo/pull/149385#discussion_r1463308582 is to get rid of the ir.asset which would cause a CSS regeneration each time this test is performed.
- Did not see it in my previous reviews... you used the localStorage without using getItem/setItem, it's better to use those (see note here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API).
- `this.el` instead of `this.$target[0]` in widgets, the other one is an old compability stuff.
- Log the expected alternative to ease debugging
- Made the code a bit more readable

@robodoo r+

2024-01-24 19:13 UTC, closed without merging