[IMP] hr_expense: editable expense lines
odoo/odoo pull request #149588
Opened 2024-01-16 14:19 UTC by alialfie

In b01cd6f the expense lines in a report were made uneditable as it was too error prone. However, modifying the analytic distribution directly from the report is often used and done by accountants before posting. This commit reverts the lines to being editable again while setting the most error prone fields to readonly.

task-3685651

2024-01-16 14:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149588).

2024-01-26 14:08 UTC, lordkrandel requested changes
Hello Ali, can you please rephrase the commit message and the PR description, being more direct? You know, for Git blame and future purposes.

----

> In https://github.com/odoo/odoo/pull/138387 the expense lines in a report were made uneditable as it was too error prone. However, modifying the analytic distribution directly from the report is often used and done by accountants before posting. This commit reverts the lines to being editable again while setting the most error prone fields to readonly.

In Expense reports, the user can click on the lines to see an attached receipt in the viewer at the side of the webpage.
In [this PR](https://github.com/odoo/odoo/pull/138387) we modified the tree to be readonly - to make it easier to click the lines.
We didn't realize that accountants are used to modify the analytic distribution field before posting.
So we revert the lines tree to be editable, but some more sensible fields will be kept as readonly:

- price_unit
- quantity
- tax_ids
- total_amount
- total_amount_currency

----
Then it LGTM, the fields are correctly readonly, the click still works.

2024-01-26 14:41 UTC, alialfie commented
Hi @lordkrandel, thanks for the quick review!
I'm not too sure about the suggested commit message :thinking: 

> In Expense reports, the user can click on the lines to see an attached receipt in the viewer at the side of the webpage.
> In [this PR](https://github.com/odoo/odoo/pull/138387) we modified the tree to be readonly - to make it easier to click the lines

I feel like this is a bit misleading. The first line was actually done in the same PR mentioned in line 2 and is irrelevant to the current task, and the tree wasn't made uneditable to make it easier to click on the lines, it's because editing them in that view was too error prone.

> * price_unit
> * quantity
> * tax_ids
> * total_amount
> * total_amount_currency

Following the git guidelines, adding the exact fields that were changed is unnecessary since it's easy to get that from reading the diff and the "why" that was changed is written in the commit message.

What do you think? :)

2024-01-26 15:28 UTC, lordkrandel commented
> I feel like this is a bit misleading. The first line was actually done in the same PR mentioned in line 2 and is irrelevant to the current task.

It's context: I never opened `expense` before and new devs will also not know.

- **Before**: In Expense reports, the user can click on the lines [...]
- **What we did before**: In this PR we modified the tree to be readonly [...]
- **It was wrong**: We didn't realize [...]
- **So now we fix**: So we revert [...]

> and the tree wasn't made uneditable to make it easier to click on the lines, it's because editing them in that view was too error prone.

Then... fix the task specs! 😄  There it seems that to "ease the click" comes first and being error prone is secondary. It's confusing.
![image](https://github.com/odoo/odoo/assets/1665365/36f00f72-ad2b-4007-9d78-f21c679b743a)

We can say then:
"In https://github.com/odoo/odoo/pull/138387 we modified the tree to be readonly so that it's harder for the user to change a field by mistake."
"Error prone" is a bit too much.

> Following the git guidelines, adding the exact fields that were changed is unnecessary since it's easy to get that from reading the diff and the "why" that was changed is written in the commit message.

Ok, but somehow please mention the reason why those field are more sensible and need protection.
"We protected fields like quantity and taxes because those can invalidate the expense."

It's not only devs reading PR descriptions, also POs and partners do.
Sometimes you copy-paste those to functional people to make them understand what's in the PR.
Otherwise we could always "just look at the code".

2024-01-30 15:41 UTC, lordkrandel commented
LGTM, pinging @qdp-odoo

2024-02-22 15:10 UTC, qdp-odoo commented
@robodoo r+

thanks guys :)

2024-02-22 17:44 UTC, closed without merging