[IMP] l10n_lv: standardize basic package
odoo/odoo pull request #149940
Opened 2024-01-18 12:52 UTC by mairasalazar

Documentation found on the Latvian chart of accounts allowed to improve language used in the Chart of Accounts, as well as remove/add some accounts.

Additionally:

- Changes were made to the taxes, to differentiate between goods and services.
- Renamed tax report file.
- Added report menu.
- Update translation file.

task-3640443

2024-01-18 12:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/149940).

2024-01-19 08:38 UTC, malb-odoo requested changes
LGTM thanks for the work on the localisation ! Just the missing po file and it will be good to go for me :smile:

2024-01-19 08:38 UTC, malb-odoo commented on addons/l10n_lv/i18n/l10n_lv.pot
> +# Translation of Odoo Server.
For localisation especially, a pot without it's po file is useless. So you will need to do the po in latvia :smile: To do this you can do it from the interface by installing the lang you want to export then going in the settings -> translation -> export translation -> select the language and the app you want to export and hop you can download the po file

2024-02-12 14:48 UTC, malb-odoo requested changes
Thanks for the work on this ! :smile: Small comments and i think it will be good :smile:

2024-02-12 14:48 UTC, malb-odoo commented on addons/l10n_lv/data/template/account.fiscal.position-lv.csv
> +"fiscal_position_lv_eu","EU Companies","1","1","","20","base.europe","VAT_S_G_21_LV","VAT_S_EU_G_0_LV","ES uzņēmumi"
Translation for EU is a bit weird ? i would keep EU and not ES :smile:

2024-02-12 14:48 UTC, malb-odoo commented on addons/l10n_lv/data/template/account.fiscal.position-lv.csv
> +"fiscal_position_lv_eu_private","EU Consumer","1","","","30","base.europe","","","ES patērētājs"
same for here and the others :smile:

2024-02-16 08:16 UTC, malb-odoo approved these changes
Thanks for the changes ! Very nice job on this :smile:

2024-03-13 16:11 UTC, qdp-odoo commented
@robodoo r+

2024-03-14 15:00 UTC, robodoo commented
@mairasalazar @qdp-odoo linked pull request(s) odoo/enterprise#54609 not ready. Linked PRs are not staged until all of them are ready.

2024-03-18 10:21 UTC, qdp-odoo commented
@robodoo r+

2024-03-18 15:37 UTC, closed without merging