[IMP] l10n_in: add hsn summary to invoice report
odoo/odoo pull request #150128
Opened 2024-01-19 12:59 UTC by smetl

task_id: 3196107

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-19 13:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/150128).

2024-01-31 12:48 UTC, smetl commented on addons/l10n_in/tests/test_invoice_hsn_summary.py
> +            'has_igst': False,
As mentioned, the flag is `False` because the IGST 0% doesn't have the IGST tag. Idk if it's a bug or not on the indian coa.

2024-01-31 13:00 UTC, hamo-odoo approved these changes
LGTM
It clears all the test case as expected

cc:@jva-odoo @ajjo-odoo

2024-01-31 13:19 UTC, hamo-odoo requested changes
![image](https://github.com/odoo/odoo/assets/121081873/2df8f78f-b43c-45c5-80b4-c1db92bf537c)
@smetl Idk why but this doesn't seem okay

2024-01-31 13:42 UTC, hamo-odoo approved these changes
![image](https://github.com/odoo/odoo/assets/121081873/8badc235-ddff-4ebb-881e-a28c3fb57946)
Thanks for the quick fix :smile:

2024-05-07 14:55 UTC, closed without merging