[FIX] pos_restaurant: prevent duplicate printing of automated receipts
odoo/odoo pull request #150846
Opened 2024-01-24 11:27 UTC by vrpa-odoo

Before this commit
================
The automated receipt printing functionality was causing receipts to be printed twice when payment was confirmed.

After this commit
================
With this commit, the issue of duplicated receipt printing on payment confirmation is resolved. Now, the automated receipt printing functionality ensures that receipts are printed only once.

task: 3568958

2024-01-24 11:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/150846).

2024-04-24 08:04 UTC, vlst-odoo requested changes

2024-04-24 08:04 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/tip_receipt/tip_receipt.xml
> +            <t t-call="pos_restaurant.TipReceipt"/>
what's the idea here ? You want to have the same content twice?

2024-04-24 08:52 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/tip_receipt/tip_receipt.xml
> +            <t t-call="pos_restaurant.TipReceipt"/>
but then you have to make this work just for pdfs, not for normal receipts too; this implementation will affect normal receipts too

2024-05-03 11:02 UTC, closed without merging

2024-05-03 11:04 UTC, shag-odoo commented
Issue fixed in the following PR -  https://github.com/odoo/odoo/pull/163250