[FIX] website_sale: check settings for price comp.
odoo/odoo pull request #151734
Opened 2024-01-30 10:51 UTC by ethanrobv

**Current behavior:**
Enabling the 'Comparison Price' setting and filling out the field will result in this strikethrough price appearing even after disabling the setting.

**Expected behavior:**
The strikethrough comparison price will only appear when the corresponding setting is enabled in the database settings.

**Steps to reproduce:**
1. Enable the 'Comparison Price' setting in website settings

2. Select a product on the 'Shop' page of the website and edit it so it has a comparison price != to its regular one

3. Save product changes, go back to the db settings and disable the 'Comparison Price' setting

4. Go back to the website 'Shop' page and observe that the strikethrough comparison price is still displayed

**Cause of the issue:**
In the product.template model in website_sale, the price values are modified to those informed by the compare_list_price value independent of the current value of the corresponding database setting. It only checks if there is non-False value in the field.

**Fix:**
Look at the 'Comparison Price' setting before the price modification/calculations take place and skip them if it's False.

opw-3705079

2024-01-30 10:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/151734).

2024-02-01 13:57 UTC, nle-odoo approved these changes
this could be ok

but for the scenario, can't users do:

2.5 -> remove the compare_list_price of the products they have set

before removing the option. But maybe it's less user friendly.

2024-02-05 10:28 UTC, Demesmaeker requested changes
Hello,

After these nitpickings comments are resolved, this lgtm. Could you also change the commit name to put the whole word? Even if we'd then be at 55 characters instead of 50, and we try to avoid being above 50, but know that this is a soft/recommended limit, and as it'd still be far under 72, and add a lot of clarity, I think it's okay to put the full word.

Have a nice day,

2024-02-05 10:28 UTC, Demesmaeker commented on addons/website_sale/models/product_template.py
> +        show_comparison_price = self.env.user.has_group('website_sale.group_product_price_comparison')
Try to stay under the 100 chars length =]

2024-02-05 10:28 UTC, Demesmaeker commented on addons/website_sale/tests/test_website_sale_show_compare_list_price.py
> +            'groups_id': [Command.link(self.env.ref('website_sale.group_product_price_comparison').id)],
same

2024-02-15 15:08 UTC, Feyensv approved these changes
@robodoo r+

2024-02-15 17:50 UTC, closed without merging