[IMP] web: progress bar style
odoo/odoo pull request #151758
Opened 2024-01-30 12:32 UTC by xlu-odoo

Before this commit, the progressbar widget had custom options that duplicated standard Odoo field attributes and used inconsistent styling conventions.

This commit removes redundant options (`editable` (-> readonly), `current_value`, `edit_max_value`..) in favor of standard attributes. Also the `decoration-*` attributes (standard view decorations) replaces `overflow_class` for conditional styling.

The progressbar styling is updated to use Bootstrap progress bar classes with some dark mode fixes/improvement. Input behavior is improved with dynamic auto-sizing and fixed vertical alignment, while removing the focus-width glitch that caused unwanted resizing.

task-3605453

Enterprise PR: https://github.com/odoo/enterprise/pull/55426

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-30 12:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/151758).

2024-01-31 16:36 UTC, chgo-odoo commented
Hi @Iucapad !

Since I saw that you improved the progressbar visual state in https://github.com/odoo/odoo/pull/113002, could you please give us your input on this PR, please?
This PR is basically a design improvement of the progressbar component. 

While improving the design, some custom `width` and `height` properties were removed in https://github.com/odoo/odoo/pull/151758/commits/2b527f3a5e4682d70dd9603dcf0946c1060372c1#diff-c4f34fd09d7f209da9da52ee1e223c9cca99fe02099fa3495ea0b8448a691c3eL3-L4 which causes the test `progress_bar_field_tests.js` to fail. What happens here is that since we defined a `w-100` in the `.XML` meaning that the width of the progressbar is relative to its parent. And since we don't have that information, the test will break.

So to ensure this was the real issue, we tested to add a `width` value in px (it could also be a min-width) in https://github.com/odoo/odoo/pull/151758/commits/1b578c66d4ea8dd30ec8e954f9864328b008cd68#diff-c4f34fd09d7f209da9da52ee1e223c9cca99fe02099fa3495ea0b8448a691c3eR3 and the test works fine.

What we have in mind is to set a `width` in the test directly, by targeting `.progress` before https://github.com/odoo/odoo/pull/151758/commits/2b527f3a5e4682d70dd9603dcf0946c1060372c1#diff-99938fec09ce9fd6bbdb6dde065d26f3660d32ab361a503d0757e375c8ee826aR290, where the test try to click on it. The idea here is to avoid any unnecessary CSS rule by fixing the issue directly in the test.

Of course this is what we thought about, this is why I requested your input on this, you might have other workaround or a better global understanding of what's going on here.

Cheers !

2024-02-05 07:49 UTC, Iucapad commented
Hello, I noticed an issue with the fact that the field with `widget="progressbar"` now has the `width: 1px !important` set on the _.progress_ element: 

<img width="102" alt="image" src="https://github.com/odoo/odoo/assets/35101914/373cd9d1-dd56-4507-bf9c-fdb3690a5959">

This happens in list and form views.

Also, when editing the current value, the '/100' does not stay inline: 
<img width="286" alt="image" src="https://github.com/odoo/odoo/assets/35101914/8399e0ee-b651-4bab-ba82-7d9e409d5510">

Otherwise, I would be okay for the change, but it should be tested visually to avoid breaking the feature.

2024-02-05 08:36 UTC, chgo-odoo commented
Hi @Iucapad, thanks for your feedback !

> I noticed an issue with the fact that the field with widget="progressbar" now has the width: 1px !important set on the .progress element:

As mentioned earlier, we have no choice because the `progress` element needs to have a `width` or `min-width` set to pass the test. What we would like to know is if it would be possible to adapt the test to set a `min-width` directly in the JavaScript. IMO it makes sense to add a `min-width` directly in the test, and this would also allow us to remove this selector from the CSS.

> Also, when editing the current value, the '/100' does not stay inline: -> EDIT: in fact it already happens in master, maybe you could add text-nowrap class?

Thanks for pointing out the issue, I added a commit to add the `text-nowrap` class.

2024-02-06 07:26 UTC, Iucapad commented
Thank you, and sorry for the delay between the comments. I took some time this morning to look and test different things.
I don't think it's a good change to remove the width on .progress, because the field will be displayed differently depending of the container size.

In the test that fails, the field should be displayed in a sheet to be visible (well, we shouldn't use a field outside of a sheet I guess, but it's an example). In kanban, the progressbar is not displayed, etc.

Another issue is that the UX is not improved since the input location can be located far from the rest of the inputs of the form. In the following image, it's really too large:
<img width="728" alt="image" src="https://github.com/odoo/odoo/assets/35101914/1846ae2f-c171-4be2-af9a-38357a14b440">

Finally, it's the fact that the progress bar resizes itself when the input is focused. It does not look great (the input change is animated while the progress change suddenly):
<img width="421" alt="image" src="https://github.com/odoo/odoo/assets/35101914/0a373f12-d745-4c40-9040-a437f5dcdd84">
<img width="417" alt="image" src="https://github.com/odoo/odoo/assets/35101914/44a6f6fb-ab6f-4725-880a-d522b5bbccd2">

I think we should remove 'w-100', and choose a constant width. Maybe summoning a PO could be great on this topic: @bouvyd

2024-02-12 12:45 UTC, bouvyd commented
Something that seems to work well: set a flex-basis on the progress bar (66%) and on the values (33%) - animation looks ok (input takes as much space as it can inside its third of the width) and since for big numbers we switch to human readable, seems to work well on smaller scales/mobile as well. Basically the input will just not force the progressbar to change its width.

Otherwise a fixed max width of 200px works for me. Could still trigger some resizing in some cases though, i think.

Having the input far to the right does not excessively bothers me here, this field is seldom used in an editable manner (4 occurences in the whole codebase AFAICT). If we ever want to solve that we can just set the values on the left and the progressbar on the right when it's editable (for example, but i don't think we need to do anything to be honest, usecase is rare)

2026-02-10 10:21 UTC, Brieuc-brd requested changes
This new progress bar looks great, nice work @xlu-odoo ! 👍 
Since the new implementation is quite technical, I’ll leave that part for the technical review and focus my feedback on the visual result and the SCSS 🙂 .

Also about the transition, I’m wondering if it would be better to disable it in some cases.
For example in Projects: depending on the number of tasks in a given status, the transition can appear partially broken when changing a task’s status.

https://www.awesomescreenshot.com/video/49278807?key=e183df28bcbd629062bf2a6b1f91dbb0

What do you think?

2026-02-10 10:21 UTC, Brieuc-brd commented on addons/hr_skills/views/hr_views.xml
> +
No diff, I think this change should be removed ;)

2026-02-10 10:21 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +        height: map-get($spacers, 2);
Can't we use variable from the original component ?

```suggestion
        --progress-height: #{map-get($spacers, 2)};
```

Also I'm wondering if we could improve the flexibility of the other size values using variables 🤔  What do you think ?

2026-02-10 10:21 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +        margin-top: $input-border-width;
I'm not sure about that, this creates inconsistency when hovering other inputs : https://www.awesomescreenshot.com/video/49278313?key=27140f71456043bc773cb95335a54dc4

2026-02-10 10:21 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +        border-color: var(--o-input-border-color);
In which case is this necessary ? I don't see any difference 🤔 

<img width="356" height="188" alt="Image" src="https://github.com/user-attachments/assets/8b193e31-e69c-448f-a403-7f28ad5d8364" />

2026-02-10 10:21 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +
Is this really necessary ?

2026-02-12 14:28 UTC, Brieuc-brd requested changes
Thanks @xlu-odoo 👍 
I've left a few comments below.

2026-02-12 14:28 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +        min-width: var(--progress-min-width);
It's better but I think we could do even more :).
1. We should clearly distinguish between Bootstrap variables and our own variables (see [our coding guidelines](https://www.odoo.com/documentation/master/contributing/development/coding_guidelines.html?highlight=guidelines#css-variables)).
2. Define clear variables at the root of the field so they can be easily reused and customized.
3. Don’t forget to add the prefix for Bootstrap variables. That way, if we decide to change the prefix in the future, this code won’t break.
 
```suggestion
    --ProgressBarField-width: 150px;
    --ProgressBarField-min-width: 35px;
    --ProgressBarField-height: #{map-get($spacers, 2)};

    color: $body-color;

    .progress {
        --#{$prefix}progress-height: var(--ProgressBarField-height);
        
        flex-basis: var(--ProgressBarField-width);
        min-width: var(--ProgressBarField-min-width);
```

2026-02-12 14:28 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +        .o_progressbar_value {
```suggestion
        }
        
        .o_progressbar_value {
```

2026-02-12 14:28 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +                text-align: start;
```suggestion
            span:not(:last-child) {
                text-align: end;
```
And remove the `text-align` on the span, what do you think ?

2026-02-12 14:28 UTC, Brieuc-brd commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.xml
> +        <div class="o_progressbar d-flex align-items-center" t-ref="numpadDecimal">
When it's "read only", the result feels too crowded IMO 🤔 Can we add a bit of gap ?

| Current | With `gap-2` |
|-----|-----|
| <img width="333" height="50" alt="Image" src="https://github.com/user-attachments/assets/0a1260d5-da9c-4b00-9dcc-374d909d0278" /> | <img width="338" height="46" alt="Image" src="https://github.com/user-attachments/assets/14b4cf0f-a4f3-411a-8bb8-9972ed2c5205" /> |

What do you think ?

2026-02-16 13:03 UTC, xlu-odoo commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
> +                text-align: start;
as discussed, ended up removing all of it since we won't apply the min width anymore.

2026-02-18 07:52 UTC, Brieuc-brd approved these changes
The visual result and the css part look good to me, good job @xlu-odoo 👍

2026-02-23 16:04 UTC, aab-odoo commented on addons/hr_skills/views/hr_views.xml
> +                <field name="level_progress" widget="progressbar" width="250" readonly="0"/>
That's weird to set readonly to a falsy value, because either it's indeed a readonly field and then the orm won't allow you to edit it, or it is not and then specifying it is useless

2026-02-23 16:04 UTC, aab-odoo commented on addons/project/views/project_update_views.xml
> +                            <field name="progress" widget="progressbar" readonly="0"/>
same

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.js
> +        isEditable: fieldInfo.readonly !== null && !dynamicInfo.readonly,
Why not
```js
isEditable: !dynamicInfo.readonly,
```

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.js
> +        if (document.activeElement !== this.currentValueRef.el) {
I don't know why this check is necessary. If we blured the input, it can't be the activeElement right?

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/tests/views/fields/numeric_fields.test.js
> +                <field name="progressbar" widget="progressbar" readonly="0"/>
here as well

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/tests/views/fields/numeric_fields.test.js
> +                <field name="progressbar" widget="progressbar" readonly="0"/>
and here

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/tests/views/fields/progress_bar_field.test.js
> +                <field name="int_field" widget="progressbar" readonly="0"/>
multiple times in this file as well

2026-02-23 16:04 UTC, aab-odoo commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.js
> +        isEditable: fieldInfo.readonly !== null && !dynamicInfo.readonly,
I think that's why you need to add these readonly="0" in archs

2026-02-25 10:12 UTC, xlu-odoo commented on addons/web/static/src/views/fields/progress_bar/progress_bar_field.js
> +        isEditable: fieldInfo.readonly !== null && !dynamicInfo.readonly,
Yep, was also a bit confused... Updated all of these..

2026-02-27 09:14 UTC, aab-odoo approved these changes
Thanks @xlu-odoo 

robodoo r+

2026-02-27 13:05 UTC, robodoo commented
@xlu-odoo @aab-odoo unable to stage: merge conflict

2026-02-27 16:00 UTC, xlu-odoo commented
@aab-odoo rebased and solved conflict

2026-02-27 16:06 UTC, aab-odoo approved these changes
robodoo r+

2026-02-28 01:15 UTC, closed without merging