[FIX] website_crm_partner_assign: require fields
odoo/odoo pull request #151982
Opened 2024-01-31 09:46 UTC by ethanrobv

**Current behavior:**
Trying to create an opportunity as a portal user and leaving any of the fields empty will cause an unnecessary exception dialog to flash on screen.

**Expected behavior:**
Submitting the form with empty required fields will just prompt the user to add values to all fields.

**Steps to reproduce:**
0. Give a portal user on the database some partner status and
     assign them an opportunity so they are able to navigate to
     the relevant menu in the portal view

1. As the portal user, go to the my/opportunities website menu

2. Select 'Create Opportunity' in the top right and leave any/all of the fields empty then select 'Confirm'

**Cause of the issue:**
These fields not being filled in is handled as a client exception, causing a modal error dialog to appear on screen.

**Fix:**
Instead of rejecting the Promise and causing the exception, return an object signaling whether or not the onClick method was successfully executed. This prevents the modal dialog from flashing on the screen.

Additionally, the fields are now marked with asterisks which should better signal that they are required in the first place.

opw-3703238

2024-01-31 09:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/151982).

2024-01-31 16:02 UTC, hubvd requested changes

2024-01-31 16:06 UTC, hubvd commented
Also I would detail this a bit more

> 0. Give a portal user on the database a partner level status
and assign them an opportunity so they are able to
navigate tothe relevant menu in the portal view

2024-02-01 11:32 UTC, hubvd reviewed
> This trivial error results in a rejected Promise which causes a
modal dialog to appear on screen.

It isn't exactly clear what a trivial error is.
What I would say instead is that before the mentioned PR, the catch was a [guardedCatch] that would only call the handler when the rejection reason was not an error.

[guardedCatch]: https://github.com/odoo/odoo/blob/8cec29f86dfc47ccfef22b9d6a47c8980e912725/addons/web/static/src/legacy/js/promise_extension.js

2024-02-01 13:43 UTC, hubvd requested changes

2024-02-01 13:43 UTC, hubvd commented on addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
> +            if (e instanceof RPCError) {
```suggestion
            if (e instanceof Error) {
```

2024-02-02 12:01 UTC, hubvd approved these changes

2024-02-06 07:59 UTC, reth-odoo reviewed
I don't get it, isn't the general logic of the original PR:

"If it's an RPC error, handle it properly, otherwise reject."
Why would we invert/change that? If there's some other error, we probably don't want to catch it.

Can't we just raise an error and catch that instead of rejecting the promise manually in `_createOpportunity`? Seems to be the only place we reject manually in this file.

2024-02-06 12:22 UTC, hubvd commented
Before the removal of the guardedCatch, only non errors would run the callback. Then there was a specific handler `lostConnectionHandler` that handled RPCErrors, which is why they handled that case.

The PR that added the condition with the RPCError assumed that we would only go inside the catch if the cause was an actual error.
In this case, we reject the promise as a control flow mechanism.
So we only want to reject the error if it's an actual error (It will be handled elsewhere).

> Can't we just raise an error and catch that instead of rejecting the promise manually in _createOpportunity? 
Can you show some example of what you mean ?

2024-02-07 06:54 UTC, reth-odoo approved these changes
Ok, I think I get the gist of it thanks. I guess if that was the previous behavior that's ok.

> Can you show some example of what you mean ?

Sure, what if in one of the callbacks that doesn't have its own error handling displaying a warning, I have some code that could raise an error? Like `undefined.someValue`

By catching all errors the user will essentially get no feedback, the button will be clickable again and they might wonder why it's not doing anything. Seems to make more sense to let it raise to the top to me, unless it's likely to be recoverable. But to be fair, that's also true of doing nothing for RPCErrors. So let's keep it as is.

2024-02-07 10:10 UTC, hubvd commented
> By catching all errors the user will essentially get no feedback, the button will be clickable again and they might wonder why it's not doing anything.

When we reject inside the catch, it is essentially the same thing as if we never catched the error.
It can then be handled elsewhere. That is actually what happened in this case, and why an error dialog was displayed.

2024-02-07 10:19 UTC, reth-odoo commented
Oh right :man_facepalming: 
Sorry for wasting your time then, indeed seems completely reasonable

2024-02-12 20:23 UTC, robodoo commented
@ethanrobv @tde-banana-odoo staging failed: ci/runbot on 32c0dafe9bf58a99c078d6d26862450bcc71a889 (view more at https://runbot.odoo.com/runbot/build/58054443)

2024-02-13 06:57 UTC, d-fence commented
robodoo retry

2024-02-13 10:06 UTC, closed without merging