[FIX] payment_mercado_pago: handle mercado pago no body responses
odoo/odoo pull request #152102
Opened 2024-01-31 15:40 UTC by OmarAbosamaha

[FIX] payment_mercado_pago: handle mercado pago no body responses
Issue:
When using a mercado pago invalid access token with extra tabs, we get 403 response from mercado pago without a body which raises and exception while handling this exception we fail to parse the response as it has no body.

line causing the issue: https://github.com/odoo/odoo/blob/9764e6f7fe39a10f3b04e1764110d8c274d0431a/addons/payment_mercado_pago/models/payment_provider.py#L70

Steps to reproduce:
1- Enable mercado pago as a payment provider
2- Set a valid access token for mercado pago with extra tabs 3- Go to website
4- Fill the cart
5- Checkout with the cart using mercado pago
6- You see error message of unhandled json parsing error

Solution:
We should wrap parsing the response in a try statement to handle the responses without body

opw-3654133

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-01-31 15:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/152102).

2024-02-01 12:52 UTC, nle-odoo approved these changes
looks ok if we don't get a json response and don't have any more info

I can't reproduce with the steps (I get on the https://sandbox.mercadopago.com.mx/ website and I don't get any error). I don't know what extra tabs meant in "access token for mercado pago with extra tabs" so maybe that's why.

If we add information about why the call fails, it would be useful to give it in the error_message.

2024-02-01 13:50 UTC, OmarAbosamaha commented
> looks ok if we don't get a json response and don't have any more info
> 
> I can't reproduce with the steps (I get on the https://sandbox.mercadopago.com.mx/ website and I don't get any error). I don't know what extra tabs meant in "access token for mercado pago with extra tabs" so maybe that's why.
> 
> If we add information about why the call fails, it would be useful to give it in the error_message.

Unfortunately we don't get any more information from mercado pago, so that's why.
Also what is meant in "access token for mercado pago with extra tabs" is just add extra spaces at the end of the key

2024-02-02 10:19 UTC, AntoineVDV reviewed
Hi, when trying to reproduce the issue by padding the access token with extra spaces, I got the following error message:

![image](https://github.com/odoo/odoo/assets/15896813/cd0630b5-6233-4c04-91d3-36fcc03f2fa1)

I think it's clear enough, and we should not discard it.

2024-02-02 11:12 UTC, OmarAbosamaha commented
> Hi, when trying to reproduce the issue by padding the access token with extra spaces, I got the following error message:
> 
> ![image](https://private-user-images.githubusercontent.com/15896813/301811144-cd0630b5-6233-4c04-91d3-36fcc03f2fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzIyNDUsIm5iZiI6MTcwNjg3MTk0NSwicGF0aCI6Ii8xNTg5NjgxMy8zMDE4MTExNDQtY2QwNjMwYjUtNjIzMy00YzA0LTkxZDMtMzZmY2MwM2YyZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExMDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YTdjZDQ2OWI0ZmJkOGFkYzhkMzI1MmViNjY2YTZiOTM5NDNhMGM5MDVlZjExYmZmZjhjZGEzM2QzZjlmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tgns-zmX0oL_nbD57f4SCR1N7nw9nIwRUT_WKC7Ig7E)
> 
> I think it's clear enough, and we should not discard it.

Yes we're not discarding it. This will stay as is. In order to reproduce this specific bug you need to pad the access token with tab spaces. In that case mercado pago will not respond with that known error. Instead, it will respond with status code 403 only and now we're handling that 403 response.

2024-02-02 12:33 UTC, AntoineVDV commented
Could you share a runbot that has the problem? It works just fine (clear error) for me.

2024-02-02 17:01 UTC, OmarAbosamaha commented
> Could you share a runbot that has the problem? It works just fine (clear error) for me.

Can you try here: https://57568658-master-all.runbot185.odoo.com/shop/payment

2024-02-05 08:22 UTC, AntoineVDV requested changes
Ok this time I could reproduce. Maybe I didn't pad my token enough :shrug:

2024-02-05 08:22 UTC, AntoineVDV commented on addons/payment_mercado_pago/models/payment_provider.py
> +                        error_message = ''
I think we should not try to force dummy error codes and messages into the existing ValidationError text; "information <empty> (code 403)" is useless to users.

Instead, we should raise a different ValidationError (`"The communication with the API failed. The response is empty. Please verify your access token."`) when a ValueError exception is raised.

2024-02-05 12:13 UTC, AntoineVDV approved these changes
@robodoo delegate+

2024-02-05 14:30 UTC, OmarAbosamaha commented
@robodoo r+

2024-02-05 16:09 UTC, closed without merging