[FIX] web: fix HTML user menu items on mobile client
odoo/odoo pull request #152809
Opened 2024-02-06 07:53 UTC by Heshmatkhah

HTML user menu items were escaped on the mobile client

Fixes #145693

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-06 07:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/152809).

2024-03-09 14:37 UTC, Heshmatkhah commented
Hi @pparidans 
Can you check and see if it is okay or not?
Thank you

2024-10-15 09:14 UTC, aab-odoo commented
@pparidans

2024-10-16 11:38 UTC, pparidans commented
Hi @Heshmatkhah, first of all, sorry for the late reply...

Your fix looks good to me. :+1: 

May I ask you to add a test for it ? (and rebase of course :sweat_smile: )
Also, in the commit message, it would be good to mark that it wasn't useful to escape them on mobile and that on "desktop" it wasn't the case anyway.

2024-10-16 16:17 UTC, Heshmatkhah commented
Hi @pparidans, thank you.
Thank you, rebase to which branch? 17.0, 18.0, master.
what should I do to fix this on other versions too?
I will add the test and change the commit message soon.

2024-10-21 08:51 UTC, pparidans commented
> rebase to which branch? 17.0, 18.0, master. 

17.0 ; just to update your branch :wink: .
The forward-port will take care of the upper versions.

2024-10-23 16:50 UTC, Heshmatkhah commented
Hi @pparidans
Done! check it please.
Thank you.

2024-10-24 08:27 UTC, pparidans requested changes

2024-10-24 08:27 UTC, pparidans commented on addons/web/static/tests/webclient/mobile/burger_user_menu_tests.js
Actually, there is already a QUnit test file for this component in `addons/web/static/tests/mobile/webclient/burger_menu/burger_menu_tests.js` :wink: 
Would you mind adding your test in that file ?
Thank you

2024-10-25 13:28 UTC, pparidans commented on addons/web/static/tests/webclient/mobile/burger_user_menu_tests.js
Hi, actually there are 2 JS unit-tests suites : one for the regular/desktop tests (cf. `/web/tests`) and one for the small-screen/mobile tests (cf. `/web/tests/mobile`).

Every file in `addons/web/static/tests/mobile/...` runs in the "mobile" test suite.

NB: I know, this is not really obvious... and is changed in Odoo 18+ with our new tests' runner... :wink:

2024-10-27 07:53 UTC, Heshmatkhah commented on addons/web/static/tests/webclient/mobile/burger_user_menu_tests.js
Hi, @pparidans
Done!
Thanks for your advices.

2024-10-28 15:01 UTC, pparidans approved these changes
LGTM

Thank you for your fix :+1: 

@robodoo r+

2024-10-28 17:22 UTC, closed without merging