[FIX] website, web_editor: prevent edit mode for drag/drop block
odoo/odoo pull request #153001
Opened 2024-02-07 07:03 UTC by shsa-odoo

Steps to reproduce :
1. Enter the edit mode of the homepage
2. Click on the page -> Bug: Drag building block is editable

Current behavior before PR:
With this commit _makeHint menthod has been made to validate whether the block is contenteditable or not before addinga hint/ placeholder to it. It was found that the code wasnt validating for it, which resluted in adding temporary hint to drag drop block with contenteditable false attribute as well. Resulting the data-editor-message to move up.

Before this PR :

![image](https://github.com/odoo/odoo/assets/103405229/4039d00b-43c3-4865-aa3f-83f3edab22f1)

Desired behavior after PR is merged:

No hint/placeholder is added to contenteditable false block, resulting in data editor message to stay on its place.

task-3443430

2024-02-07 07:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153001).

2024-02-14 08:13 UTC, qsm-odoo requested changes
@shsa-odoo Do you know why this is needed in 16.4 and not before? Even without apparent bug (at least with the flow described in the commit message), this seems like a very generic thing to fix, so it should probably be added in earlier versions? To check with @odoo/rd-framework-editor team anyway :+1:

2024-04-02 11:14 UTC, divy-odoo commented
> @shsa-odoo Do you know why this is needed in 16.4 and not before? Even without apparent bug (at least with the flow described in the commit message), this seems like a very generic thing to fix, so it should probably be added in earlier versions? To check with @odoo/rd-framework-editor team anyway 👍

Hello @qsm-odoo, 
In need this should be apply to the previous version. But with more research I found that, there is already a PR[1] in progress which solves the similar issue.( merged till the 16.3 ) In which we merged the diff removing `content==''` from the condition.( not getting why we removed? ) ...and It's breaking few tests in fw-port saas-16.4. [2]
 
[1] https://github.com/odoo/odoo/pull/140444
[2] https://github.com/odoo/odoo/pull/147087

2024-04-09 11:48 UTC, divy-odoo commented
Note: Revised the solution & update the PR.

2024-06-21 08:39 UTC, robodoo commented
@shsa-odoo the target branch 'saas-16.4' has been disabled, you may want to close this PR.

2024-12-26 15:36 UTC, bvr-odoo requested changes
Hello @shsa-odoo 👋🏼 
> Drag building block is editable and is broken

- What do you mean by "is broken". Could you be clearer in your commit message please.
- "Drag building block" is unclear. Please be more specific (e.g the blue block in the page displaying the "Drag building blocks here" message).
- The title of the PR include the website app. It should be removed form it.
- I tested on a runbot version 17.0 without your changes, and I cannot edit the 'Drag building blocks here' block. Could you please retest and explain how I can test it to make it editable?

2024-12-27 07:17 UTC, divy-odoo commented
@bvr-odoo apologies for the unclear commit message. hope now it's clear to you. :pray: 

> I cannot edit the 'Drag building blocks here' block.

The block is not text-editable, so you won't be able to edit it. As you can see in the image, the `o_editable` class is triggering the PowerBox element. However, since the drop zone is not text-editable, triggering the PowerBox here serves no purpose.

![image](https://github.com/user-attachments/assets/9462c1d0-ae2e-4d7e-8775-877b59a8a090)

2024-12-27 07:42 UTC, bvr-odoo commented
> @bvr-odoo apologies for the unclear commit message. hope now it's clear to you. 🙏

It's clear now, thanks for the explanation 👍🏼

2024-12-27 13:12 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-12-27 14:33 UTC, bvr-odoo approved these changes

2024-12-27 14:33 UTC, bvr-odoo commented
@robodoo r+

2024-12-27 14:36 UTC, bvr-odoo commented
@robodoo r-

2024-12-27 14:44 UTC, bvr-odoo commented
@divy-odoo Before I merge this PR, could you explain why we no longer have the bug starting from version 18.0?
This commit https://github.com/odoo/odoo/commit/302250cdde936a47048b8f3403e024e2e617ace7 added `:not(.o_not_editable)`
but this class is not on the "Drag building blocks here" block.

2024-12-30 06:39 UTC, divy-odoo commented
Nice catch @bvr-odoo ! Thanks! 😊
After this PR (https://github.com/odoo/odoo/pull/162804/files), the `#wrap` element has somehow been blacklisted for hint, which prevents the creation of hints(`Type "/" for commands`) only. While may be this can be fine in some cases, in our scenario, why should we wait for that check and make unnecessary computations for the powerbox? computation is well too small which we can eliminate but purpose fo `isHintBlacklisted()` seems different to handle our case.

In my opinion, we should simply eliminate `non-editable` elements from `getPowerboxElement()` as powerbox element itself to prevent further computations. what's your thought?

2024-12-30 09:37 UTC, bvr-odoo commented
> Nice catch @bvr-odoo ! Thanks! 😊 After this PR (https://github.com/odoo/odoo/pull/162804/files), the `#wrap` element has somehow been blacklisted for hint, which prevents the creation of hints(`Type "/" for commands`) only. While may be this can be fine in some cases, in our scenario, why should we wait for that check and make unnecessary computations for the powerbox? computation is well too small which we can eliminate but purpose of `isHintBlacklisted()` seems different to handle our case.
> 
> In my opinion, we should simply eliminate `non-editable` elements from `getPowerboxElement()` as powerbox element itself to prevent further computations. what's your thought?

@divy-odoo I agree with your conclusion. In any case, an element with `contenteditable="false"` should not have a powerbox. Your commit looks like the best solution.

2024-12-30 09:37 UTC, bvr-odoo commented
@robodoo r+

2024-12-30 10:54 UTC, closed without merging