[FIX] sale_mrp: fix picking creation issue for bom with kit type
odoo/odoo pull request #153173
Opened 2024-02-08 06:36 UTC by gusi-odoo

**Version:**

- saas-16.3

**Step to reproduce:**
- Create a subscription product with the type set to 'product.'
- Create a BOM for that product with the BOM type set to 'kit.'
- In mrp.bom.line, add any product with the type 'product.'
- Create a sale order with the products that are created and generate an invoice.
- Upon creating the next invoice for the subscription product, the picking was not being generated.

**Issue:**
if the product type is set to 'product' and recurring_invoice is true, and the product has a bill of materials (BOM) with the type 'kit,' the picking was not created after the first invoice.

**Solution:**
Not updating the qty for bom for kit if the product has a subscription

task-3681597

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-08 06:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153173).

2024-02-14 13:38 UTC, geflx requested changes
Unfortunately on production branches we can not change the signature of functions.
That's because some of our customers can have function overrides on their side and changing the function header could break the system for them.
Another alternative must be used, and in the last case we can make use of context keys.

Additionally, we must avoid changing content of other modules. If it must be done, we can't put code referred to `sale_subscription` there, because this polutes the code and makes it difficult to maintain.

2024-02-27 10:27 UTC, gusi-odoo commented on addons/sale_mrp/models/sale_order_line.py
> +        if bom and not self.env.context.get('has_subscription', False):
Hello @geflx ,

I've implemented the changes requested. Please have a look to this PR and the master branch.

Branch: master-subs-kit-issue-gusi
Odoo: https://github.com/odoo-dev/odoo/commit/248a68f6ac7289f673cc2bc2ef3e068e88a9365d
Enterprise: https://github.com/odoo-dev/enterprise/commit/64c2ab67870342db14cd74556d598ea77b06bbd

Thanks :innocent:

2024-02-28 09:22 UTC, geflx requested changes
Small changes requested, it is looking good! 😄

2024-02-28 10:04 UTC, gusi-odoo commented on addons/sale_mrp/models/sale_order_line.py
> +    @api.model
Hello @geflx ,
Done the changes 
Thanks for the suggestion :innocent:

2024-03-01 08:50 UTC, geflx approved these changes
Looks good to me now, thanks for you work! 🙂

2024-04-24 09:07 UTC, Whenrow requested changes

2024-04-24 09:07 UTC, Whenrow commented on addons/sale_mrp/models/sale_order_line.py
> +        self.ensure_one()
remove `ensure_one()` and use `@api.model` decorator instead

2024-04-24 11:17 UTC, Whenrow commented
robodoo r+

2024-04-24 17:20 UTC, closed without merging