[FIX] website: search field in header not tabable
odoo/odoo pull request #153197
Opened 2024-02-08 09:37 UTC by SergeBayet

This commit resolves the accessibility issue where the search field located within the header was not navigable via keyboard tabbing, rendering it inaccessible to users relying on keyboard navigation.

This fix ensures that users can seamlessly navigate to the search field in the header using the keyboard, thereby enhancing the overall accessibility and usability of the website.

task: 3607481

2024-02-27 09:12 UTC, robinlej commented
Your fix makes it tabable, but it does not open on enter.

One thing was bugging me though, as the `<a>` should be tabable by default. It turns out that this one doesn't have an `href`, which removes the tab order from the tag. So an easy solution to both the tab issue and the open with enter one is simply to add `href="#"` to it. I just tested, it works just fine.

2024-02-28 16:48 UTC, qsm-odoo commented
@robodoo delegate=Guillaume-gdi 
@Guillaume-gdi

2024-02-28 16:49 UTC, qsm-odoo commented
@SergeBayet Apparently you added this in the sheet and put it in blue ^^ I put it in blue when I delegate so if you add a task later, don't forget to ask me to delegate :wink:

2024-02-28 17:07 UTC, Guillaume-gdi requested changes
Thanks for the PR. It's working as expected.

Could you just mention the commit that introduced the new header templates with the search bar in the commit message. That way, developers will directly know why this targets this specific version.

Also, replace `task: 3607481` by `task-3607481`. Thanks you :)

2024-02-29 08:03 UTC, SergeBayet commented
@Guillaume-gdi It's done. Thanks for the review. I've updated the commit message according to your comment.

2024-02-29 08:47 UTC, Guillaume-gdi approved these changes
Thanks for the changes!
@robodoo r+

2024-02-29 12:13 UTC, closed without merging