[FIX] pos_loyalty: enable free product for Next Order Coupon program
odoo/odoo pull request #153268
Opened 2024-02-08 14:58 UTC by pedrambiria

Before this commit, the free product reward feature in a Next Order Coupon program was not functioning as expected. This commit fixes this issue, ensuring that free product rewards are correctly applied in Next Order Coupon programs.

opw-3703485

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-08 15:35 UTC, caburj requested changes
Apply the suggestions also on the 2nd tour.

2024-02-08 15:35 UTC, caburj commented on addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
> +ProductScreen.do.clickCustomer('AAA Partner');
```suggestion
ProductScreen.do.clickCustomer('AAA Partner');
PosLoyalty.check.customerIs('AAA Partner');
```
wait for the customer to be reflected in the UI before clicking the product.

2024-02-08 15:35 UTC, caburj commented on addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
> +ProductScreen.do.pressNumpad('3')
```suggestion
ProductScreen.exec.addOrderline('Product Test', '3');
```
Use addOrderline. It waits for the orderline to be rendered properly (with correct quantity), before going to the next step.

2024-02-09 10:50 UTC, pedrambiria commented
@caburj Thanks for your comments. I applied them.

2024-02-12 09:45 UTC, caburj commented
robodoo r+

2024-02-12 11:06 UTC, closed without merging