[FIX] account_edi_ubl_cii: fix ubl import with allowance charge
odoo/odoo pull request #153276
Opened 2024-02-08 15:29 UTC by aliyatastemirova

When a UBL xml file is being uploaded and it contains an invoice line with an allowance charge, that charge is not being uploaded correctly. This commit:
- fixes the allowance charge xpath, so the node is found properly
- includes allowance charge amount in the discount calculation, because an allowance is not a discount.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-08 15:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153276).

2024-02-12 13:46 UTC, JulienVR requested changes
Could you provide an example file ? :)

2024-02-12 13:46 UTC, JulienVR commented on addons/account_edi_ubl_cii/models/account_edi_common.py
> +        xpath = './{*}InvoiceLine/{*}AllowanceCharge' if is_ubl else './{*}SupplyChainTradeTransaction/{*}ApplicableHeaderTradeSettlement/{*}SpecifiedTradeAllowanceCharge'
The AllowanceCharges we are retrieving here are the document's one, the AllowanceCharges on the lines are retrieved in `_import_fill_invoice_line_values`. So I think there is a misunderstanding here.

2024-02-12 13:46 UTC, JulienVR commented on addons/account_edi_ubl_cii/models/account_edi_common.py
> +                tax_xpath = '../{*}Item/{*}ClassifiedTaxCategory/{*}Percent' if is_ubl else './{*}CategoryTradeTax/{*}RateApplicablePercent'
same here, Item's are only present on the lines, it doesn't make sense on the document level

2024-04-04 09:26 UTC, closed without merging

2024-04-04 09:26 UTC, smetl commented
replaced by task: 3742296