[FIX] web_editor: Traceback when picking an emoji
odoo/odoo pull request #153365
Opened 2024-02-09 04:51 UTC by adsa-odoo

**Current behaviour before commit:**

After selecting cells in table, moving cursor through arrowkeys doesn't deselect cells.

**Desired behaviour after commit:**

Now cells are getting deselected.

task-3718716

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-09 04:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153365).

2024-03-14 14:28 UTC, Zynton requested changes

2024-03-14 14:28 UTC, Zynton commented on addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
> +            !appliedCustomSelection && this.deselectTable();
```suggestion
            if (!appliedCustomSelection) {
                this.deselectTable();
            }
```

2024-03-18 06:59 UTC, adsa-odoo commented on addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
> +            !appliedCustomSelection && this.deselectTable();
Done!

2024-03-18 08:15 UTC, Zynton commented
@robodoo r+

2024-03-18 10:05 UTC, closed without merging

2024-03-18 13:10 UTC, Zynton commented
@robodoo rebase-ff

2024-03-18 13:10 UTC, robodoo commented
Merge method set to rebase and fast-forward.