[FIX] mrp: Generate MOs for BOM with product repetition
odoo/odoo pull request #153400
Opened 2024-02-09 10:07 UTC by lase-odoo

Steps to reproduce:
-
- Create 4 products: Final product (FP), Product 1,2,3 (P1,P2 and P3)
- Set routes to manifacture on each product
- For P1, P2, P3 add a 0:0 reordering rule.
- Add a BOM for P2 with 1 unit of P1 as components
- Add a BOM for P3 with 1 unit of P2 as components
- Add a BOM for FP with 1 unit of P3 and of P2 as components The MO overview of a FP shoud look like this :

                               FP
                               /\
                              /  \
                             P3  P2
                             |    |
                             P2  P1
                             |
                             P1

- Create and confirm a manufacturing order for a FP

Current behavior:
-
As the quantity on hand is not sufficient to manufacture a FP, manufacturing orders are automatically created for P3, P2 and P1. However, the quantity on each of these MOs is of 1 unit.

Expected behavior:
-
Since 2 units of P2 and of P1 will be required to manufacture the FP the quantity of their respective MOs should be at 2.

Cause of the issue:
-
The MOs are generated one level (of the MO overview) at a time during the recursive calls of the _trigger_scheduler() method.
However, during the process corresponding to the second level (P2, P1) the qty_to_order of the orderpoint corresponding to P2 will be incorrectly computed by the method _compute_qty_to_order. To be more precise, the already incoming stock move of P2 will be counted twice in here:
https://github.com/odoo/odoo/blob/432778725d0ed1777edb2793737d802b5ebd035f/addons/stock/models/stock_orderpoint.py#L282
(Once in the virtual qty available and once in the qty in progress).

FIX:
-
Since this quantity in progress is irrelevant for this flow (and used to not be part of it), we delete its contribution to the forecasted qty for our flow.

opw-3689920
-

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-09 10:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153400).

2024-02-14 16:16 UTC, DjamelTouati requested changes
Hello @lase-odoo 
Thank you for your fix, I tested your fix, but it does not seem to solve the problem, also, I tested the use case in V16, and the bug is also present, I therefore advise you to traget your fix in the version where the bug begins.

I also tested instead of making an orderpoint, use the route "MTO (it is an archived route by default) + manufacture" and it works correctly, 2 MO are created for P2, I therefore advise you to take inspiration from this and see why it works correctly and do the same thing for the orderpoints, ignore MO is not the best solution

Additionally, I didn't understand what you mean in this  "FIX:
Since this quantity in progress is irrelevant for this flow (and used to not be part of it), we delete its contribution to the forecasted qty for our flow."

2024-02-19 14:14 UTC, Whenrow commented on addons/mrp/models/stock_orderpoint.py
> +            ],
To me we could add into `_quantity_in_progress` a search on the raw material stock move that will be confirmed in `post_process_scheduler` as well to update the quantity to order. 
For now there is only a search to update finished products quantities

2024-03-18 10:33 UTC, Whenrow commented
robodoo r+

2024-03-18 12:53 UTC, closed without merging