[FIX] website_sale_loyalty: apply reward if multi_product
odoo/odoo pull request #153889
Opened 2024-02-13 15:29 UTC by vchu-odoo

Steps to reproduce:
1) Create 2 products with product tag (ex. 'discount')
2) Create Buy X Get Y reward. In conditional rules and rewards add created tag to 'Product Tag' field.
3) Go to /shop page and add X products with the tag
4) Try to click in the button 'Free product'
5) The reward is not applied

Reason:
In the claim_reward function reward is not applied for rewards with multi products.

After this commit the reward will be applied.

opw-3587020

2024-02-13 15:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153889).

2024-02-19 10:00 UTC, Demesmaeker commented
Hello, I tried to replicate the problem in V16.0, but did automatically get the free product, as expected.
Could you please test to see if the problem is still there and if yes, rewrite this PR message to make it clearer to know how to replicate it?
Thanks in advance

2024-02-19 10:21 UTC, vchu-odoo commented
Hi, @Demesmaeker!
As I can see you did not configure in `rewards` section product tag. So instead of adding a free product you define a tag domain. 
Leave field `product` empty but add product tag 'test' in `rewards` section like in `conditional rules`.

2024-02-19 13:50 UTC, Demesmaeker requested changes
Hello :duck: 

I did see the problem this time :partying_face: and could then test your branch. A reward was indeed applied, but... it's one of the item with the tag that got applied, where the customer should be able to chose through all the products that have that tag, IMHO. Otherwise, the reward should just be set with the single product to use as a reward.
So while there is, now, a reward applied, a problem still remains: it might not be the correct one. It's just the first of a recordset. For instance, in your test: Which free product was it? The carpet or the sofa? You checked it's one of the 2 that was applied, but never had to select one.

2024-02-29 13:40 UTC, vchu-odoo commented
will be fixed in master with the separate task

2024-02-29 13:40 UTC, closed without merging