[IMP] l10n_es_edi_facturae: add PaymentMeans for Facturae edi export
odoo/odoo pull request #153982
Opened 2024-02-14 01:35 UTC by moerradi

this commit does the following:
- Implement dropdown in "Other Info" tab of Factura-e invoices, enabling users to select their preferred PaymentMeans.
- Set default PaymentMeans value to 04.
- Ensure selected PaymentMeans are accurately reported in the PaymentMeans section of Factura-e.

task-3734370

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-14 01:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/153982).

2024-02-19 09:24 UTC, JulienAlardot requested changes
:+1:

2024-02-19 10:33 UTC, moerradi commented
done 👍🏼

2024-02-20 18:58 UTC, moerradi commented
sure, i'll add it !

2024-02-23 09:20 UTC, JulienAlardot approved these changes
@LGTM epictete

2024-02-23 11:53 UTC, moerradi commented
@epictete

2024-02-26 13:30 UTC, epictete commented on addons/l10n_es_edi_facturae/models/account_move.py
> +                    'PaymentMeans': self.l10n_es_payment_means or '04',
```suggestion
                    'PaymentMeans': self.l10n_es_payment_means,
```
It makes more sense to set a default value on the field directly.
Also, please update the doc string as well, to reflect the fact that it is no longer hardcoded :wink:

2024-02-26 15:37 UTC, moerradi commented
@epictete done !

2024-02-26 15:43 UTC, epictete approved these changes
Thanks for the quick update :+1: 

@robodoo r+

2024-02-26 15:53 UTC, moerradi commented
hey @epictete could you r+ again I rebased the branch and didn't notice you already r+

2024-02-26 15:57 UTC, epictete commented
@robodoo r+ :racehorse: :laughing:

2024-02-27 02:32 UTC, closed without merging