[FIX] hr: correct number of employees
odoo/odoo pull request #154162
Opened 2024-02-15 12:20 UTC by arpi-odoo

This will fix the number of employees in the partner view and redirect to a kanban view of the employees.

The smart button on the partner view for the number of employees related to this partner now gives the correct number depending on the companies selected.

If multiple employees are related, the action shows a kanban view of those employees.

Task: 3693173

2024-02-15 12:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154162).

2024-03-06 12:00 UTC, mepe-odoo requested changes
Good Job :+1: 
Just one little comment.

2024-03-06 12:00 UTC, mepe-odoo commented on addons/hr/tests/test_hr_employee.py
> +        company_B_id = company_B.id
You don't use company_A or company_B you can remove these variables I think :blush: 
```py
company_A_id = self.env['res.company'].create({
            'name': 'company_A',
        }).id
company_B_id = self.env['res.company'].create({
            'name': 'company_B',
        }).id```

2024-03-06 12:37 UTC, mepe-odoo approved these changes

2024-03-12 14:00 UTC, tivisse requested changes
Small comments.

2024-03-12 14:00 UTC, tivisse commented on addons/hr/tests/test_hr_employee.py
> +        partner.with_context(allowed_company_ids=[company_A_id, company_B_id])._compute_employees_count()
```suggestion
        partner.with_company(company_A + company_B)._compute_employees_count()
```

2024-03-13 08:56 UTC, tivisse commented
@robodoo r+

2024-03-13 11:35 UTC, closed without merging