[FIX] website: fix login with RPC on website domain
odoo/odoo pull request #154447
Opened 2024-02-16 16:04 UTC by Dj0ulo

__Current behavior before commit:__
When the field `website_id` of a user is set, this user should only be able to login via this website (cfr. [this method][1]). This means that he can  only login if [`get_current_website`][2] returns the same website as `website_id`.

The issue is that when login with RPC, `dispatch_rpc` is making a [`borrow_request`][3] which hides the `request` object from the RPC layer. This has the consequence that `get_current_website` is not able to retrieve the website based on the url of the request. Thus preventing a user to login via RPC even if the domain used corresponds to the website set in its `website_id` field.

__Description of the fix:__
Add the possibility to retrieve the current website via `threading.current_thread().url` (which is set [here][4]). This way it is possible to know the current website even if `borrow_request` has been used.

opw-3742591

[1]: https://github.com/odoo/odoo/blob/0f7cbf2969b3c4b6c496e5b54814c4a9b3081af4/odoo/addons/base/models/res_users.py#L779
[2]: https://github.com/odoo/odoo/blob/0f7cbf2969b3c4b6c496e5b54814c4a9b3081af4/addons/website/models/website.py#L944
[3]: https://github.com/odoo/odoo/blob/0f7cbf2969b3c4b6c496e5b54814c4a9b3081af4/odoo/http.py#L361
[4]: https://github.com/odoo/odoo/blob/0f7cbf2969b3c4b6c496e5b54814c4a9b3081af4/odoo/http.py#L2037

2024-02-16 16:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154447).

2024-03-01 15:03 UTC, rdeodoo requested changes
Could you please add a test? Seems like the client on the opw provided a script to test it, maybe it will make it faster to write the test.

@Julien00859 Is this something you would like to review? I can investigate it but you probably know better about it

2024-03-02 22:00 UTC, Julien00859 requested changes
this deserves an unittest

2024-03-05 10:25 UTC, Dj0ulo commented
> I just don't understand this use case, shouldn't the login always work?

@Julien00859 Well I think the purpose of the field `website_id` on `res.users` is to prevent user from login outside of a particular domain. A user shouldn't be able to connect through another website if `website_id` is set. (At least the existence of [this method](https://github.com/odoo/odoo/blob/8c1716f48846db275e7a884d4c547cf8eb462533/addons/website/models/res_users.py#L43) suggests it is intended to behave like this).

Now I don't know if this is supposed to be the case with RPC as well. Maybe @rdeodoo knows more about that.

2024-03-05 13:28 UTC, rdeodoo commented
Regarding website behavior:
- Websites have a setting ("Specific user account") to separate user accounts
- This setting will make it so when you create an account on a website which has the setting enabled, your user will receive a `website_id`:
   https://github.com/odoo/odoo/blob/141354ca0590650a537d8ed9391940cd742b4169/addons/website/models/res_users.py#L54-L64
- About the other websites in the DB, they could either also have this setting enabled, meaning they will also have their own separate user accounts, or some could share users (generally it's either all enabled or all disabled but everything is supporte and working fine)
- For instance, website A and B could have enabled `specific_user_account` while website C and D would not (and share user)
  Then, you could create an account on website A, and if you try to login with those credentials on website B, it would not work. You could then create an account on website B (with same email) and it would be linked to a new user.
  If you create an account on website C, it will not receive a `website_id` and the account will be usable on website C and D to login, but not on website A and B.

It's actually most of the time the setting you want, if you have multiple ecommerce, you don't want the users to realized it's the same DB/company behind it, and you want them to have separate accounts.

Regarding the issue you fix, since there is no clear step to reproduce, I am not sure if you fix:
1. The user being able to login on a website they should not be able
2. The user not being able to login where he should be able to

Also on the test, adding a website on the user (`self.user_demo.website_id = website1`) should be done alongside enabling `specific_user_account` on the website since it's the condition for the user to receive a website, if we really want to replicate real use case.

Hopefully this brings some useful info

2024-03-05 13:33 UTC, Julien00859 commented
I think I got it. So a possible situation is a database where all websites are `specific_user_account`, hence the domain matching logic is in action for all accounts, including the admin, hence it is not possible to login in RPC. It is IMO a bug and I think that the current fix is correct. I don't know for the unittest thought.

2024-03-05 15:27 UTC, Dj0ulo commented
> Regarding the issue you fix, since there is no clear step to reproduce, I am not sure if you fix...

Indeed I forgot to include the steps to reproduce:
- Install `website`
- Go to Website > Configuration > Websites
- Set the domain of the first website (e.g. `http://localhost:8069/`)
- Go to Marc Demo" res.partner form view
- In Sales & Purchase tab set **Website** to "My Website"

Then run this script in another terminal (it's similar to the test I wrote):
```python
#!/usr/bin/env python3

import json
import urllib.request

url = "http://localhost:8069/jsonrpc"
dbname = "db-16.0"

def rpc_login_user_demo():
    """
    Login with demo using JSON-RPC
    :return: the user's id or False if login failed
    """
    req = urllib.request.Request(url=url, data=json.dumps({
        "params": {
            "service": "common",
            "method": "login",
            "args": [dbname, 'demo', 'demo']
        },
    }).encode(), headers={"Content-Type": "application/json"})
    response = json.loads(urllib.request.urlopen(req).read().decode('UTF-8'))
    if response.get("error"):
        raise Exception(response["error"])
    return response['result']

uid = rpc_login_user_demo()
if uid:
    print("Login success")
else:
    print("Login failed")
```
The login will fail but it should succeed since we sent the request with the same host than the website domain.

Anyway the whole issue lies into the fact that `get_current_website` will not be able to identify the current website with the help of the domain. So it will either return the first website without a domain or the first website in the list. Therefore:
- A user may not be able to login to its *assigned* website
- But in other cases, a user may login to a website on which it is not *assigned*
(Regardless of whether `specific_user_account` is true or not)

That said, I didn't realize that it was for eCommerce purpose so this problematic may not be very relevant for RPC. (Still what I shown in the steps is an annoying bug when working with RPC).

2024-03-05 15:36 UTC, rdeodoo commented
Ok, then it makes sense, thanks for the precision

2024-03-05 16:13 UTC, Julien00859 approved these changes
Thanks! @robodoo r+

2024-03-11 09:18 UTC, Dj0ulo commented
@rdeodoo I think your change request is blocking the r+

2024-03-11 09:31 UTC, rdeodoo commented
I don't have change request, it's just a pending review request since you re-assign me after the request change here https://github.com/odoo/odoo/pull/154447#event-11999613402

And I never heard of such a thing, could be a new feature (and could make sense) but I don't think so.

Probably juste the r+ from @Julien00859 which didn't reach the mergebot?

2024-03-11 12:13 UTC, Julien00859 commented
@robodoo r+

the r+ needs to be on its own line

2024-03-11 13:58 UTC, closed without merging