[FIX] project: fix alias domain value by setting default value
odoo/odoo pull request #154681
Opened 2024-02-20 04:58 UTC by shag-odoo

Steps:
. Install the project
. Enable use custom enable server from general settings . Set an alias domain
. Create a new project
. Wizard pops up

Issue:
. Default value of alias domain is not set.

Cause:
. related field to alias_id but forgot to insert in the view

Fix:
. Issue is been fixed by adding a field in wizard view as alias domain was getting fetched on that field.
. Additionally the same field is been to added to form view as well.

task-3744319

2024-02-20 04:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154681).

2024-02-20 07:27 UTC, paso-odoo requested changes
@shag-odoo 

Thanks for working on this PR.
Need to improve the commit message.

Cheers!

2024-02-20 07:27 UTC, paso-odoo commented on addons/project/views/project_project_views.xml
> +                                        <field name="alias_id" invisible="1"/>
```suggestion
                                        <field name="alias_id" invisible="1"/>    <!--    Need to add alias_id in view for getting alias_domain_id by default    -->
```

I would add a comment on why we need to add alias_id

2024-02-20 07:27 UTC, paso-odoo commented on addons/project/views/project_project_views.xml
> +                            <field name="alias_id" invisible="1"/>
same

2024-02-21 08:46 UTC, shag-odoo commented
Hello @paso-odoo 
Commit message and comments have been updated

Thanks and have a great day ahead :innocent:

2024-03-21 08:11 UTC, damrOdoo reviewed
Lgtm. thanks for your fix.

2024-06-24 11:22 UTC, xavierbol commented
robodoo r+

LGTM, thanks for your work. 🙂 

I just rebased your branch. 🙂

2024-06-24 15:06 UTC, closed without merging