[IMP] payment: allow generate_access_token to call using cron
odoo/odoo pull request #154881
Opened 2024-02-21 13:20 UTC by pash-odoo

Before this commit, generate_access_token method method can not be called when working with cron because request is not available when using function with cron.

After this commit, add optional argument env in generate_access_token which can pass env in function when working with cron.

task-3640650

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-21 13:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154881).

2024-03-15 08:39 UTC, arj-odoo reviewed
I have a few suggestions. The sale team will probably have his opinion too :-).

2024-03-15 08:39 UTC, arj-odoo commented on addons/payment/utils.py
> +        request_env = env(su=True) if env else request.env(su=True)
I am not sure I would use request_env as a variable name because we know that there is not always a http request.

2024-03-15 08:39 UTC, arj-odoo commented on addons/payment/utils.py
> +        _logger.exception('request is not defined')
```suggestion
        _logger.exception('No suitable environment available to generate payment access token')
```

2024-03-15 10:52 UTC, pash-odoo commented
> I have a few suggestions. The sale team will probably have his opinion too :-).

changes done,
Thank you :+1:

2024-03-21 16:47 UTC, AntoineVDV requested changes
Hello, please find my review comments below :)

2024-03-21 16:47 UTC, AntoineVDV commented on addons/payment/utils.py
> +import logging
```suggestion
import logging
from hashlib import sha1
```

2024-03-21 16:47 UTC, AntoineVDV commented on addons/payment/utils.py
> +def generate_access_token(*values, env=None):
Add the docstring entry

2024-03-21 16:47 UTC, AntoineVDV commented on addons/payment/utils.py
> +        _logger.exception('No suitable environment available to generate payment access token')
I don't think this is super useful; it's going to crash and dump a traceback mentioning the call to `generate_access_token` anyway, so it doesn't add information for debugging.

2024-03-22 12:25 UTC, pash-odoo commented
The code has been revised according to this [comment](https://github.com/odoo/enterprise/pull/57137#pullrequestreview-1952843808)
so there's no need for a community PR. Hence, I am closing it.

2024-03-22 12:25 UTC, closed without merging