save
odoo/odoo pull request #154880
Opened 2024-02-21 13:16 UTC by pipu-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-21 13:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154880).

2024-02-22 11:56 UTC, Arcasias requested changes

2024-02-22 12:27 UTC, pipu-odoo commented on addons/web_tour/static/src/tour_service/tour_compilers.js
> +                if (!keepWatchBrowser && !step.freeze) {
cofee ?

2024-02-22 12:34 UTC, Arcasias approved these changes
@robodoo r+

2024-02-22 14:22 UTC, fja-odoo commented
@pipu-odoo Hello, just checking if you are planning to add some info about that in the documentation ?
https://www.odoo.com/documentation/master/developer/reference/backend/testing.html#debugging-tips

2024-02-22 15:50 UTC, pipu-odoo commented
@fja-odoo Here is the documentation https://github.com/odoo/documentation/pull/7808

2024-02-23 08:43 UTC, pipu-odoo commented
this PR was replaced by https://github.com/odoo/odoo/pull/155082.

2024-02-23 08:44 UTC, closed without merging