[IMP] project: add subtask count to subtask tooltip and change behavi…
odoo/odoo pull request #154872
Opened 2024-02-21 12:25 UTC by chrisduvivier

…or of task created directly in waiting stage.

Current behavior before PR:
---------------------
1. In the subtask list view, only the name of the subtask was displayed in the tooltip of the subtask title.
2. Whenever a task is directly created in the waiting stage, the state of the task was set to `waiting` although the task dependencies were not set.

Steps to reproduce:
-------------------
- Subtask Tooltip 
1. Create a task (task A) with a subtask (task B).
2. In the subtask (task B), create subtasks to it.
3. In the Subtask list view of task A, hover over the subtask title of task B.

- Task created directly in waiting stage
1. Group tasks by state
2. Create task in the waiting stage
3. Task should be in 'waiting' state.

Desired behavior after PR is merged:
------------------
The subtask tooltip will display the name and the count of subtasks in the tooltip of the subtask title. 
The task created directly in the waiting stage will be in the 'in progress' stage by default. However, the task will remain in the 'waiting' stage until the page is refreshed.

Task-3690545

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-21 12:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/154872).

2024-08-07 09:08 UTC, MissingNoShiny requested changes
Thanks for your work :slightly_smiling_face:

2024-08-20 11:26 UTC, MissingNoShiny reviewed
LGTM, thanks! I just have two small comments :slightly_smiling_face:

2024-08-20 12:46 UTC, chrisduvivier commented on addons/project/models/project_task.py
> +        # check if 'state' exists and if it equal to '04_waiting_normal' then we set it to '01_in_progress'
Thanks for the review and advice. I agree with you, this is not really adding anything meaningful information.
For this line I changed it to mention that "we prevent direct creation of new task in the waiting state"

2024-08-21 07:59 UTC, MissingNoShiny approved these changes
LGTM, thanks!
@robodoo r+

2024-08-21 10:42 UTC, closed without merging