[IMP] spreadsheet: add highligts on pivot/lists
odoo/odoo pull request #155050
Opened 2024-02-22 14:15 UTC by hokolomopo

[IMP] spreadsheet: add highligts on pivot/lists

This commit add highlights on pivot and list cells. The cells of
a pivot/list are highlighted when:

- the user hovers the menu item corresponding to a list/pivot
- the side panel of a list/pivot is opened
- the user hovers a list/pivot in datasource list side panel

Task: 3571796

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-02-22 14:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/155050).

2024-02-27 15:33 UTC, pro-odoo requested changes
All this code should be moved to enterprise as it will only be used there.

2024-03-04 14:58 UTC, hokolomopo commented
@pro-odoo What do you mean about moving the code to enterprise ? The plugins are in community :sweat:

2024-03-11 09:10 UTC, pro-odoo commented
> @pro-odoo What do you mean by moving the code to enterprise ? The plugins are in community 😓

Two options:
- create two new plugins in enterprise to handle this (overkill IMHO)
- move these functions to an helper file in enterprise (it only requires `getters`).

Anyway, you can ignore that comment as it will land in o-spreadsheet at the end

2024-03-20 09:17 UTC, closed without merging