[FIX] web: fix padding around the state label
odoo/odoo pull request #155017
Opened 2024-02-22 12:03 UTC by padh-odoo

Versions:
---------
- master

Steps to Reproduce:
---------

- open projects
- open form view of any tasks of the project
- check the state button of the task

Issue:
---------

- There is no padding for state label.

Cause:
---------

- Padding was given as 0 for the button.

Fix:
---------

- We remove the p-0 class in the button.

task-3758377

2024-02-29 09:39 UTC, pkyriakou reviewed
Thank you @padh-odoo :100: LGTM :green_circle: :star:

2024-03-06 16:54 UTC, auon-odoo requested changes
Please update your commit message and talk a little about the shadow :pray:

2024-03-07 09:42 UTC, auon-odoo requested changes
It looks better. However, I'm sorry but I still don't understand where this shadow comes from? Maybe you can explain it in the "cause" section. :wink:

2024-03-08 04:47 UTC, padh-odoo commented
> It looks better. However, I'm sorry but I still don't understand where this shadow comes from? Maybe you can explain it in the "cause" section. 😉

Hello @auon-odoo 
I have made a small change in this commit message.
button tags are introduced in the mentioned commit.
IMO the shadow ring we are seeing is likely because the <button> element receives focus when it's clicked.
Probably a default behavior of buttons.
Please let me know if I am missing something.
Thank You

2024-03-13 14:31 UTC, auon-odoo approved these changes
Thanks for the fix AND the commit message :smile:

2024-03-13 14:33 UTC, xavierbol commented
robodoo r+

I just rebased your branch. 🙂

2024-03-13 18:40 UTC, closed without merging