[IMP] point_of_sales : move notification
odoo/odoo pull request #155381
Opened 2024-02-26 13:30 UTC by SalukiMakingCode

display notifications from bottom right, instead of the top

tasks id : 3763034

2024-02-26 13:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/155381).

2024-02-26 13:55 UTC, vlst-odoo requested changes
it looks like clicking on anything on the right side of the screen no longer works ( for example i tried the `cash in/out` option in the burger menu and it is not clickable

2024-03-04 09:46 UTC, davidmonnom commented
![image](https://github.com/odoo/odoo/assets/63289800/58d21005-e8fd-410e-8557-b530ce2ac769)


Should we have different behavior for mobile ui ?

2024-03-18 10:01 UTC, davidmonnom commented
> Hello @SalukiMakingCode , Do you have any update on this?

As dama said is cancelled, we keep the notification on the top to be aligned with the rest of odoo

2024-03-18 10:01 UTC, closed without merging