[FIX] purchase_stock: dropship in picking type domain
odoo/odoo pull request #155529
Opened 2024-02-27 10:23 UTC by ethanrobv

**Current behavior:**
When making a new RFQ, dropship is not an available selection for the 'Deliver To' option.

**Expected behavior:**
As on previous versions, you should 'dropship' should be selectable here which reveals a sub-selection to select the customer who should receive the shipment.

**Steps to reproduce:**
1. Enable `Dropshipping` in Purchase settings as well as `Storage Locations` in Inventory settings

2. Create a new RFQ, observe that in the 'Deliver To' dropdown there is no way to select a dropship option

**Cause of the issue:**
Dropshipping was made into a discrete `stock.picking.type`.code and the domain that constrains the selection menu options was not updated to accomodate this change.

**Fix:**
Update the domain to show picking types that have the dropship code.

opw-3764617

2024-02-27 10:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/155529).

2024-02-28 12:27 UTC, adwid commented
robodoo delegate=@DjamelTouati

2024-03-01 13:40 UTC, DjamelTouati requested changes
Hello,
Thanks for your fix! However, you must instead apply your fix in the `stock_dropshipping` module because this selection is added in this model:
https://github.com/odoo/odoo/blob/72cd1669af2989c0a033ab297bbea524491d3116/addons/stock_dropshipping/models/stock.py#L46-L47

something like:

```diff
diff --git a/addons/stock_dropshipping/views/purchase_order_views.xml b/addons/stock_dropshipping/views/purchase_order_views.xml
index dd3031eb06af..ac37baef7d50 100644
--- a/addons/stock_dropshipping/views/purchase_order_views.xml
+++ b/addons/stock_dropshipping/views/purchase_order_views.xml
@@ -14,6 +14,11 @@
                     <field name="dropship_picking_count" widget="statinfo" string="Dropship"/>
                 </button>
             </xpath>
+                        <xpath expr="//field[@name='picking_type_id']" position="attributes">
+                <attribute name="domain">
+                    [('code', '=', ('incoming', 'dropship'))
+                </attribute>
+            </xpath>
         </field>
     </record>
 </odoo>

```

2024-03-06 08:52 UTC, DjamelTouati commented
Hello @ethanrobv 
could you do this instead because we lose the 2nd part of the domain
```diff
+<xpath expr="//field[@name='picking_type_id']" position="attributes">
+    <attribute name="domain">
+        [('code', 'in', ('incoming', 'dropship')), '|', ('warehouse_id', '=', False), ('warehouse_id.company_id', '=', company_id)]
+    </attribute>
+</xpath>
```

2024-03-07 08:53 UTC, ethanrobv commented
> could you do this instead because we lose the 2nd part of the domain

Understood, should be to your spec now. Thanks for the feedback :+1:

2024-03-13 09:17 UTC, DjamelTouati commented
robodoo r+

2024-03-13 11:35 UTC, closed without merging