[IMP] account_edi_ubl_cii: various adaptation to welcome l10n_co_edi
odoo/odoo pull request #156094
Opened 2024-03-01 13:57 UTC by JulienVR

2024-03-01 13:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/156094).

2024-03-19 18:22 UTC, Levizar requested changes
Here are some wall of text for you! Merry Xmas! :grin:

2024-03-28 09:24 UTC, JulienVR commented on addons/account/static/src/components/document_state/document_state_field.scss
> +}
Done ! I just kept the fixed width

2024-04-22 11:11 UTC, Levizar commented on addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
> +                'document_currency_code': invoice.currency_id.name,
I would have keep it just in case (in case LOL) a customer smoked some crack and change the currency names but you're probably right.

2024-05-30 15:23 UTC, smetl commented
@robodoo r+ rebase-ff

2024-05-30 15:24 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-05-30 18:19 UTC, closed without merging