[FIX] website: add missing prop to CodeEditorDialog
odoo/odoo pull request #156021
Opened 2024-03-01 08:33 UTC by robinlej

Steps to reproduce:
- Enter debug mode
- Drop a Code snippet on a page
- Click on edit in the options => "Invalid props for component 'CodeEditorDialog': unknown key 'value'"

task-3776391

2024-03-01 08:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/156021).

2024-03-07 16:57 UTC, rdeodoo commented
@robodoo delegate=@Guillaume-gdi

2024-03-07 17:10 UTC, Guillaume-gdi requested changes
Good fix :+1: Could you add in the commit message why this one is targeting master please.

2024-03-08 09:27 UTC, robinlej commented
@Guillaume-gdi I added the commit which introduced the bug in the message.

2024-03-08 12:26 UTC, Guillaume-gdi approved these changes
@robodoo r+

2024-03-08 15:23 UTC, closed without merging