[FIX] google_calendar: fix the sync issue after resuming
odoo/odoo pull request #156037
Opened 2024-03-01 10:38 UTC by gusi-odoo

**Version:**

- 17.0

**Step to reproduce:**
- open the Calendar and navigate to Configuration > Settings
- add Google credentials and sync it
- create an event and then pause the sync.
- again create an event and unpause the sync with Google Calendar
- event fails to update on Google Calendar

**Issue:**
Currently, the event created during the pause period won't synchronize after
resuming synchronization in Google Calendar.

**Solution:**
This PR enables the synchronization to restart automatically when unpausing
the Google Calendar.

task-3731607

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-01 10:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/156037).

2024-04-18 08:05 UTC, geflx requested changes
Hi @gusi-odoo! 👋

I think we could go on the direction of changing the `unpause_google_synchronization` function instead of `res.config.settings`, because this way the code would be more namely close to the behavior to be fixed(in this case 'unpause' behavior). What do you think?

Notes: 
1. The functions `_sync_google_calendar` and `_sync_odoo2google` might also help you a lot in this challenge.
2. Adding a test in this task in fundamental, you can get good test examples in our codebase.

See you!

2024-04-18 09:30 UTC, gusi-odoo commented
> Hi @gusi-odoo! 👋
> 
> I think we could go on the direction of changing the `unpause_google_synchronization` function instead of `res.config.settings`, because this way the code would be more namely close to the behavior to be fixed(in this case 'unpause' behavior). What do you think?
> 
> Notes:
> 
> 1. The functions `_sync_google_calendar` and `_sync_odoo2google` might also help you a lot in this challenge.
> 2. Adding a test in this task in fundamental, you can get good test examples in our codebase.
> 
> See you!

Hello @geflx :wave: ,

Can you please explain me why you want to change the flow of unpause_google_synchronization ? because I don't see anyother references of method except the test cases. Though what we are trying achieve here and the method name is same on the contradictory side and I guess res.config.settings is more efficient way to do this whenever the user saves the settings vals functionally.
I wonder what else can be the use case.

Thanks :slightly_smiling_face:

2024-04-24 10:48 UTC, gusi-odoo commented
Hello @geflx :wave: ,
as per your suggestion, I made changes Please have a look 

Thanks :slightly_smiling_face:

2024-04-24 12:41 UTC, gusi-odoo commented on addons/google_calendar/models/res_users.py
> +        if not results or not results.get('default_reminders'):
> Hello! 👋 I didn't understand this change, why are we changing `events` to `default_reminders`?

Hello @geflx,
When an event is created duriing the sync_pause period , the `_google_insert` function does not create the record. Upon resuming sync and accessing the calendar, the `results = self._sync_request(calendar_service)` call yields an empty Google event object. This object returns  `{  'events': GoogleEvent(), 'default_reminders': [{'method': 'popup', 'minutes': 30}], 'full_sync': False, } `. Consequently, the `_sync_google_calendar` method returns False due to the absence of any events. 

to address this scenario, and call the `_sync_odoo2google` method to insert the record into google I have changes the condition

2024-08-01 14:58 UTC, fdamhaut approved these changes
LGTM overall

2024-08-16 09:58 UTC, arj-odoo commented
@robodoo r+

2024-08-16 12:00 UTC, closed without merging