[FIX] Fixed wrong or duplicate ids in some views
odoo/odoo pull request #156421
Opened 2024-03-04 21:56 UTC by victor-sm

**Description of the issue/feature this PR addresses:**

There are some instances with duplicate or wrong element ids in some view files.

**Desired behavior after PR is merged:**

The element ids have been changed to remove duplicates and fix wrong ones.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-04 21:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/156421).

2024-03-05 09:08 UTC, AntoineVDV approved these changes

2024-03-05 14:41 UTC, rdeodoo requested changes
Same as https://github.com/odoo/odoo/pull/146248#pullrequestreview-1793420665, I would just target master, no need to take risk breaking potential xpath in stable while it doesn't solve anything: 0 value / real risk

Also, please keep working on the same PR so we can keep traceability of previous reviews etc, it's just easier :+1:

2024-03-11 16:51 UTC, rdeodoo requested changes
Thanks for the PR and the change to target master only (ideally try to keep working on the same PR).
A few comments

2024-05-17 14:06 UTC, rdeodoo commented
@victor-sm ?

2026-03-04 04:38 UTC, closed without merging