[FIX] remove surplus encodeURIComponent() in shapes URL return
odoo/odoo pull request #156644
Opened 2024-03-06 01:20 UTC by RemiFr82

Description of the issue/feature this PR addresses:
Remove surplus encodeURIComponent() function in URL generation

Current behavior before PR:
It currently results in `/web_editor/shape/web_editor%2FFloats%2F11.svg?[...]`

Desired behavior after PR is merged:
It should result in `/web_editor/shape/web_editor/Floats/11.svg?[...]`

Issue [#129873](https://github.com/odoo/odoo/issues/129873)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-06 01:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/156644).

2024-03-08 11:12 UTC, rdeodoo requested changes
@robodoo delegate=@bso-odoo
@bso-odoo If this is not wrong, this is probably an oversight of https://github.com/odoo/odoo/commit/b7382925b1ac37ff1e00eaa472ea30cea20f61d0, I'll let you have a look

@RemiFr82 Thank you for the PR.
Could you please follow our commit guidelines (module name in title eg)?
Could you also mention the commit your are fixing inside your commit msg?
https://github.com/odoo/odoo/commit/b7382925b1ac37ff1e00eaa472ea30cea20f61d0
Could you add a step to reproduce the issue?

```
[FIX] remove surplus encodeURIComponent() in URL return

See Issue #129873 : https://github.com/odoo/odoo/issues/129873
```
=>
```
[FIX] web_editor: remove useless encodeURIComponent()

Steps to reproduce:
- Do that
- Do that
- See the error xyz

This `encodeURIComponent()` was introduced with commit [1]

[1]: https://github.com/odoo/odoo/commit/b7382925b1ac37ff1e00eaa472ea30cea20f61d0

Fixes https://github.com/odoo/odoo/issues/129873
```

2024-03-08 15:40 UTC, bso-odoo commented
@rdeodoo Oops indeed. I agree with this PR's implementation: the individual elements are already escaped.
I'll approve once the commit message will be updated.

2024-03-08 16:39 UTC, bso-odoo commented
@RemiFr82 Before I forget: this actually already exists in 15.0 which is still maintained, so this PR should be rebased on 15.0.

After digging a bit, it seems that specific escape had been discussed during development of https://github.com/odoo/odoo/pull/116676 (but not in the github log unfortunately).

As far as I remember, the debate went on between "this escape is useless" and "what if a customization finds a way to inject something malicious inside the `data-shape` attribute ?".
Ultimately, the decision was to keep it because it seemed like it did not hurt: the browsers still interpret the URL properly - but e.g. if a "?" is inside the shape name, by escaping it is then received inside the `filename` parameter of the `shape` method in `web_editor`'s `main.py` controller. Otherwise `data-shape` content could impact the `kwargs` of that method instead.

If the only situation where this is an issue is when that string gets displayed in a 404 page, I guess we'll prefer to keep this safety net.
But if this causes an actual functional problem, we'll have to find a solution - which might be the one you suggest. (Or maybe keep the escape - but restore slashes ?)

It would be great if you could further describe how you reached that 404 error that is mentioned in the linked issue https://github.com/odoo/odoo/issues/129873, so that we can better determine in which scenario we are.

2024-05-07 06:12 UTC, HLFH commented
I go on a wrong URL, let's say `https://odoo.vip-fishing.com/wp-admin/`, I get 400 bad request on https://odoo.vip-fishing.com/web_editor/shape/http_routing/404.svg?c2=o-color-2. If I load this link separately: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3.10/site-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3.10/site-packages/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3.10/site-packages/odoo/http.py", line 1912, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3.10/site-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3.10/site-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3.10/site-packages/odoo/addons/web_editor/controllers/main.py", line 681, in shape
    svg, options = self._update_svg_colors(kwargs, svg)
  File "/usr/lib/python3.10/site-packages/odoo/addons/web_editor/controllers/main.py", line 639, in _update_svg_colors
    raise werkzeug.exceptions.BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```
And I would be able to load correctly separately `https://odoo.vip-fishing.com/web_editor/shape/http_routing/404.svg`.

2025-02-26 10:26 UTC, closed without merging