[FIX] account : Fix little Ui issue on pdf report
odoo/odoo pull request #156863
Opened 2024-03-07 09:32 UTC by igbe-odoo

The 'on' wasn't aligned with the line on the pdf report of invoices.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-13 07:54 UTC, malb-odoo commented on addons/account/views/report_invoice.xml
> +                            <span class="text-nowrap">
For the next reviewer: the use of the span is needed for the class to be applied. For the span inside, it is needed for studio modification i think :smile:

2024-03-13 07:54 UTC, malb-odoo requested changes
Good job on this ! The commit description is missing the task number, you can see here the guideline for that https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html :smile:

2024-03-20 07:32 UTC, malb-odoo approved these changes
LGTM thanks for the PR :smile:

2024-03-20 16:09 UTC, qdp-odoo commented
@robodoo r+

2024-03-20 18:07 UTC, closed without merging