[FIX] website: fix class name in the website test file
odoo/odoo pull request #157291
Opened 2024-03-11 16:43 UTC by dc-oerp

The class name of the favicon test was not set properly

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-11 16:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157291).

2024-03-11 16:55 UTC, rdeodoo requested changes
Is there any issue with the code apart from the badly copy pasted name?
Regardless if there is an issue or not, can you indicate it in the commit message?
And if there is no issue apart from being code cleaning, can you retarget the PR to master?
Don't create a new PR, just push force it and change the PR target (I will do it if you want/cant).

Setting the PR in draft in the meantime

2024-03-11 20:52 UTC, dc-oerp commented
@rdeodoo 

This is simply a correction of the class name, and I have retargeted the PR to master.

Thank you

2024-03-12 16:52 UTC, rdeodoo commented
@dc-oerp You also need to rebase your branch on master and push force, because right now your PR is 3070 commits ;-)

2024-04-02 13:53 UTC, closed without merging