[FIX] account: fix traceback when creating new journal through payments
odoo/odoo pull request #157337
Opened 2024-03-12 07:25 UTC by alsh-odoo

This traceback arises when the user tries to create a new journal from the payment.

To reproduce this issue:

1) Install `accounting`
2) Create a new payment from `Accounting/vendors/payments` 
3) save the record and now try to create a new `journal` from the payment 
4) While creating the new journal click on the `discard` button 
5) A traceback arises.

Error:- 
```
KeyError: ('res.company', <function Company.__accessible_branches at 0x7fabdfc69c60>, (1,), False, 2)
  File "odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-8>", line 2, in __getitem__
  File "odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
ValueError: not enough values to unpack (expected 1, got 0)
  File "odoo/models.py", line 5941, in ensure_one
    _id, = self._ids
ValueError: Expected singleton: res.company()
  File "odoo/http.py", line 2251, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1826, in _serve_db
    return self._transactioning(_serve_ir_http, readonly=ro)
  File "odoo/http.py", line 1847, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1824, in _serve_ir_http
    return self._serve_ir_http(rule, args)
  File "odoo/http.py", line 1832, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 2057, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 740, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 34, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 30, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 458, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "addons/web/models/models.py", line 1074, in onchange
    todo = [
  File "addons/web/models/models.py", line 1077, in <listcomp>
    if field_name not in done and snapshot0.has_changed(field_name)
  File "addons/web/models/models.py", line 1190, in has_changed
    return self[field_name] != self.record[field_name]
  File "odoo/models.py", line 6664, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "odoo/fields.py", line 1138, in __get__
    self.recompute(record)
  File "odoo/fields.py", line 1353, in recompute
    apply_except_missing(self.compute_value, recs)
  File "odoo/fields.py", line 1326, in apply_except_missing
    func(records)
  File "odoo/fields.py", line 1375, in compute_value
    records._compute_field_value(self)
  File "addons/mail/models/mail_thread.py", line 416, in _compute_field_value
    return super()._compute_field_value(field)
  File "odoo/models.py", line 4982, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 102, in determine
    return needle(*args)
  File "addons/account/models/account_payment.py", line 369, in _compute_reconciliation_status
    liquidity_lines, counterpart_lines, writeoff_lines = pay._seek_for_lines()
  File "addons/account/models/account_payment.py", line 192, in _seek_for_lines
    if line.account_id in self._get_valid_liquidity_accounts():
  File "addons/account/models/account_payment.py", line 211, in _get_valid_liquidity_accounts
    accessible_branches = journal_comp.with_company(journal_comp)._accessible_branches()
  File "odoo/addons/base/models/res_company.py", line 420, in _accessible_branches
    return self.browse(self.__accessible_branches())
  File "<decorator-gen-107>", line 2, in __accessible_branches
  File "odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "odoo/addons/base/models/res_company.py", line 402, in __accessible_branches
    self.ensure_one()
  File "odoo/models.py", line 5944, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
```

when the user tries to create a new journal and discard it, there will be no journal record, which leads to the traceback from the below line.

https://github.com/odoo/odoo/blob/53d6d795ddf6cc9e470bfeb48bb31bc728acedbe/addons/account/models/account_payment.py#L207-L208

After applying this commit, resolve this issue by taking the default company, 
when there is no journal.

sentry-5054332731

2024-03-12 07:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157337).

2024-03-14 12:23 UTC, rugo-odoo reviewed
Hellooo, can you add a test please ? Also, we don't need to put the huge traceback here, we can just explain briefly what the problem is.

2024-03-18 05:00 UTC, alsh-odoo commented
Hello @rugo-odoo 
The test case has been added.
Please have a look
Thank You :innocent:

2024-03-18 10:19 UTC, rugo-odoo requested changes
Thank you for the test !

After the review of your solution with a PO, we reach the conclusion that this is not the approach we wanna take.

If we try to create a payment without a journal, we will be prevented to do so. So the solution should not be a new fallback in case we don't have a journal but instead, the user should not be able to remove the journal (the same case as in the creation).

2024-03-18 11:38 UTC, alsh-odoo commented
> Thank you for the test !
> 
> After the review of your solution with a PO, we reach the conclusion that this is not the approach we wanna take.
> 
> If we try to create a payment without a journal, we will be prevented to do so. So the solution should not be a new fallback in case we don't have a journal but instead, the user should not be able to remove the journal (the same case as in the creation).

Hello @rugo-odoo 

If we try to create a payment without a journal, we are prevented from doing so as the journal is a required field.
Here the fallback value is used for calculating the valid liquidity accounts if the journal is empty
Here is the video reference:- https://www.loom.com/share/69c8253ae6494ff79a210c5eec2fb059

Correct me if I am wrong or not understood what you mean to say
Thank You :innocent:

2024-03-18 13:09 UTC, rugo-odoo commented
The thing is that when we remove the journal we shouldn't have a traceback because we shouldn't have an rpc call with an empty journal since the journal is required.

In the fix here, we make sure that we have a journal but that's not the real problem, the real problem is that it shouldn't be submitted in the first place, right ?

So we need to investigate why is it submitting it. Here https://www.awesomescreenshot.com/video/25916540?key=d0e37b4a0008b1b74627be0726487c6a whatever is submitting the payment without the journal, shouldn't.

2024-03-21 06:50 UTC, alsh-odoo commented
> The thing is that when we remove the journal we shouldn't have a traceback because we shouldn't have an rpc call with an empty journal since the journal is required.
> 
> In the fix here, we make sure that we have a journal but that's not the real problem, the real problem is that it shouldn't be submitted in the first place, right ?
> 
> So we need to investigate why is it submitting it. Here https://www.awesomescreenshot.com/video/25916540?key=d0e37b4a0008b1b74627be0726487c6a whatever is submitting the payment without the journal, shouldn't.

Hello @rugo-odoo 

Sorry for the delay as I was busy with another PR,

I investigated why it is submitted  and found that it is because of the new onchange method(introduced from saas-16.3).

From this line :- 
https://github.com/odoo/odoo/blob/fc34baedfa25d754dfee7116f49003f57d60b107/addons/web/models/models.py#L1185-L1186

when the current field(`field_name`) is trying to access the value from `self.record`, if it is a computed field then the compute method is triggering.

Which seems weird and it more looks like an ORM issue.

Thank You :innocent:

2024-04-18 07:38 UTC, rugo-odoo commented
> Which seems weird and it more looks like an ORM issue.

Can we close this pr then ?

2024-05-14 06:34 UTC, rugo-odoo approved these changes

2024-06-11 11:26 UTC, william-andre approved these changes
@robodoo r+

2024-06-11 11:26 UTC, william-andre commented on addons/account/tests/test_account_payment.py
> +from odoo.exceptions import ValidationError
Easier to order alphabetically

2024-06-11 11:26 UTC, william-andre commented on addons/account/tests/test_account_payment.py
> +            }])
```suggestion
        }])
```

2024-06-12 05:00 UTC, alsh-odoo commented
Hello @william-andre 

The requested changes are done.

Could you please give r+ again?

Thank You :slightly_smiling_face:

2024-06-12 05:02 UTC, william-andre commented
Was already approved, but thanks for following up
@robodoo r+

2024-06-12 09:52 UTC, closed without merging