[FIX] osv: set id when value type NewId
odoo/odoo pull request #157318
Opened 2024-03-11 19:23 UTC by kawkb

## Issue:
- for a search domain (left, operator, right), when the operator  is in HIERARCHY_FUNCS (child_of/parent_of) and right type is `NewID` we get this error "TypeError: 'NewId' object is not iterable"

## Steps To Reproduce (in 17.0):
- In a contact form open Studio and add a O2M field Customer (Task)
- Create a new task in the O2M and set the Project to a project related to a SO.
- Notice Traceback Error "TypeError: 'NewId' object is not iterable"

## Explanation for this scenario (in 17.0):
- In [_get_last_sol_of_customer](https://github.com/odoo/odoo/blob/2209021a3b77109824b572bb38c6c5d05554d753/addons/sale_timesheet/models/project.py#L603) search domain we parse `('order_partner_id', 'child_of', self.partner_id.commercial_partner_id.id)`, where the type of `self.partner_id.commercial_partner_id.id` is `NewID`.
- Since the operator is in `HIERARCHY_FUNCS` the [parse](https://github.com/odoo/odoo/blob/2209021a3b77109824b572bb38c6c5d05554d753/odoo/osv/expression.py#L805) method calls the [to_ids](https://github.com/odoo/odoo/blob/2209021a3b77109824b572bb38c6c5d05554d753/odoo/osv/expression.py#L847) method which returns `list(value)` where `value` type is `NewId` thus the Traceback error.

I don't know a similar scenario in v 15.0 to add a test. For example a situation where I have a record being edited (its ID type is NewID), and there's a search operation with a domain where the operator is child_of/parent_of and right is the record ID.

## Solution:
- check if the value is an instance of `NewID` and return `value.origin`

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-11 19:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157318).

2024-03-14 12:17 UTC, hubvd reviewed
The fix looks good for me.

This occurs in 17 because of the new onchange. Especially this line: https://github.com/odoo/odoo/blob/15bfff301c4734efd66c45d83fe7fc8e3d2dc83d/addons/web/models/models.py#L960-L962, so maybe we should only target that version ?

What do you think @rco-odoo ?

2024-03-19 13:09 UTC, rco-odoo requested changes
I disagree with the solution.  The domain evaluator in `expression.py` is **not expected** to deal with new ids.  IMHO what we have here is a **programming error**, and therefore this fix silently "approves" the programming error, instead of fixing it.  This kind of solution is risky, because you don't know the programmer's intention.  It may actually hide a more severe programming error, which could go undetected for years.

As you correctly pointed out, the issue comes from method `_get_last_sol_of_customer()`.  That method is called by a compute method, which has to deal with new records.  In the code, I recommend to use `.ids` instead of `.id` in the domain's value:
```py
('order_partner_id', 'child_of', self.partner_id.commercial_partner_id.ids),
```
The operator `child_of` deals with list of ids, and the property `ids` always the record's origin ids.

2024-03-20 09:59 UTC, rco-odoo commented
Here is some extra explanation about why the expression `self.partner_id.commercial_partner_id` returns a new record:
* `self` is the subject of an onchange, that's why it is a new record;
* because `self` is a line in a one2many field in a form, the main record in the form `self.partner_id` must be a new record with the main form's values;
* the computed field `commercial_partner_id` is computed as being the same partner as `self.partner_id`, which makes it a new record, too.

2024-03-20 10:05 UTC, rco-odoo approved these changes
This looks good to me.  I am aware that such situations may occur again, and we will see in the future whether we need more generic solutions.  But for the time being, I prefer to tackle the programming error, which was quite subtle in this case.

2024-03-22 09:52 UTC, rco-odoo commented
@robodoo r+

2024-03-22 13:00 UTC, closed without merging