[IMP] l10n_mx: Don't allow to uninstall l10n_mx_edi from settings
odoo/odoo pull request #157439
Opened 2024-03-12 15:39 UTC by smetl

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-12 15:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157439).

2024-03-13 11:01 UTC, FlorianGilbert requested changes

2024-03-13 11:01 UTC, FlorianGilbert commented on addons/l10n_mx/models/res_config_settings.py
> +        mx_view = self.env.ref('l10n_mx_edi.res_config_settings_view_form', raise_if_not_found=False).sudo()
After testing I'm still have the view, it shouldn't be this?
```suggestion
        mx_view = self.env.ref('l10n_mx.res_config_settings_view_form', raise_if_not_found=False).sudo()
```
In that case, I won't see the field

2024-03-13 12:12 UTC, smetl commented on addons/l10n_mx/models/res_config_settings.py
> +            mx_view.active = False
@FlorianGilbert We don't want to force people to upgrade the module

2024-03-13 12:16 UTC, smetl commented on addons/l10n_mx/models/res_config_settings.py
> +            mx_view.active = False
It's to prevent an extra write for nothing

2024-03-13 13:42 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-03-13 17:05 UTC, closed without merging