[FIX] account: full reconcile have no display_name
odoo/odoo pull request #157406
Opened 2024-03-12 13:33 UTC by fmdl

On Odoo enterprise, use the menu reconcile in accounting. Reconcile some lines with the wizard. In the tree view group by reconcile_id you show 'account.full.reconcile(67)'.

![image](https://github.com/odoo/odoo/assets/16716992/34a8f2ec-f15d-4005-82b3-ced8eb966c2f)

@qdp-odoo @oco-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-12 13:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157406).

2024-03-17 13:27 UTC, fmdl commented
OPW #3812222

2024-03-26 09:52 UTC, fmdl commented
ping @oco-odoo

2024-04-09 14:51 UTC, oco-odoo requested changes
Do we agree that it only happens when manually grouping the move lines on "matching" field (full_reconcile_id) ? If so, I don't think it's worth doing that ; "matching #" (matching_number) already does the job.

2024-04-10 20:42 UTC, fmdl commented
@oco-odoo you see this group view after reconcille in mass.

2024-05-31 08:47 UTC, oco-odoo requested changes

2024-05-31 08:47 UTC, oco-odoo commented on addons/account/models/account_full_reconcile.py
> +            rec.display_name = ', '.join(rec.reconciled_line_ids.filtered('matching_number').mapped('matching_number'))
Won't they all share the same matching number anyway when linked to an account.full.reconcile ? So, you could do 

```suggestion
            rec.display_name = rec.reconciled_line_ids[0].matching_number
```

2024-05-31 12:42 UTC, oco-odoo approved these changes
@robodoo r+

2024-05-31 12:43 UTC, robodoo commented
@oco-odoo you may want to rebuild or fix this PR as it has failed CI.

2024-05-31 12:43 UTC, oco-odoo commented
@fmdl From runbot's state, I think you need to rebase ^^

2024-06-11 09:10 UTC, oco-odoo commented
Actually ... hasn't this been fixed by https://github.com/odoo/enterprise/pull/58840 already ? :thinking:

2024-06-11 09:10 UTC, closed without merging

2024-06-11 09:11 UTC, fmdl commented
yes it is fixed.