[IMP] account: added bank account on customer invoice
odoo/odoo pull request #157503
Opened 2024-03-13 06:18 UTC by hsal-odoo

Description of the issue/feature this PR addresses: 3794432

Current behavior before PR: customer invoice has the sentence "Please use the following communication for your payment : +++000/0000/10205+++"

Desired behavior after PR is merged: customer invoice should have the sentence "Please use the following communication for your payment : +++000/0000/10205+++ on this account : BE81 3101 2528 8724" 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-13 06:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157503).

2024-03-14 12:24 UTC, malb-odoo reviewed
It's missing the task number in the pr description :smile:

2024-03-20 08:02 UTC, malb-odoo requested changes
Thanks for the PR and good job ! Small things that could be better in the term of html i think :smile:

2024-03-20 08:02 UTC, malb-odoo commented on addons/account/views/report_invoice.xml
> +                        <span t-if="o.partner_bank_id">
i think there is not need for a span here ? a t balise would work well

2024-03-20 08:02 UTC, malb-odoo commented on addons/account/views/report_invoice.xml
> +                            on this account: <b><span t-field="o.partner_bank_id"/></b>
for the b balise, i would prefer to use a boostrap class on this :smile:

2024-03-20 12:36 UTC, malb-odoo requested changes
Almost perfeeect, just need to add the translation i think :smile:

2024-03-20 13:47 UTC, malb-odoo approved these changes
A loooot of translation for a little change ahah, thanks for the PR, it's maybe missing the diff about the date when you changed the pot and po files, don't know if it's really that important ? Maybe Quentin can tell us :smile:

2024-04-26 16:02 UTC, qdp-odoo reviewed
from 15.0? okay... good luck with the fw-port :sweat_smile: 

@robodoo r+

2024-04-26 16:02 UTC, qdp-odoo approved these changes

2024-04-26 17:57 UTC, closed without merging