[FIX] portal,*: display avatar when read access right are fulfilled
odoo/odoo pull request #157652
Opened 2024-03-14 08:18 UTC by loco-odoo

*website_blog

Steps to reproduce the bug:
- Enable the comments on a blog.
- Add a comment.

-> Problem: The avatar of the comment is the default placeholder image.

The problem appears since [1]. This commit was created to bypass the read access of an image if a correct `token` was provided in the dataset of the `.o_portal_chatter` element. The problem is that since [1], if the `.o_portal_chatter` element does not have a `token` (or a `hash` and a `pid` since [2]) in its dataset, the avatar images are displayed as the default placeholder image by default. The goal of this commit is to correct this behavior; if there is no token provided, the previously used `/web/image` route is used to show the avatar. Thanks to this route, the avatar is displayed if the read access is fulfilled. If it is not the case, the default placeholder image is displayed.

[1]: https://github.com/odoo/odoo/commit/d4eb996cd3caea3fbb822437057a6a5a8a722293
[2]: https://github.com/odoo/odoo/commit/7f69708bcce3b3c4b096d89cb0ec354998eac191

opw-3749422

2024-03-14 08:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157652).

2024-03-14 08:46 UTC, loco-odoo commented
Note: This PR has the same content than https://github.com/odoo/odoo/pull/156509 but with a correct branch name

2024-03-14 08:48 UTC, tde-banana-odoo commented on addons/website_blog/tests/test_ui.py
> +        self.start_tour(self.env['website'].get_client_action_url('/blog'), 'blog_avatar_comment', login='admin')
Personnally I don't think we have to add a tour just for that: tour takes a lot of time to launch and run, runbot is already taking ages to build. Can't you just add a unit test accessing the image route directly ?

2024-03-21 09:39 UTC, rdeodoo requested changes
@tde-banana-odoo FYI (following previous comment)
Once the review is applied, the tour will have been trimmed to the bare minimum, most of the initial tour will have been moved in python.

For the remaining part and the fact it's still a js tour, it's the only way to test the behavior, since no route is wrong, it's just the JS code choosing a route which is wrong and tested here.

2024-03-21 09:39 UTC, rdeodoo commented on addons/portal/controllers/mail.py
> +        # "access_token" or without a "_hash" and a "pid".
I'd keep the code as is, one line (already coded) to have it support that case instead of having an unpredictable behavior

2024-03-21 11:26 UTC, tde-banana-odoo commented
@rdeodoo Actually the code has been moved in python somewhere between 16 and master, so the tour would be mostly useless I think (considering we have few chances of regression in stable, and code can be tested using python once it is not done in js anymore). So maybe we could skip the tour here, but as you prefer.

2024-03-21 14:04 UTC, rdeodoo commented
Oh, ok thanks for the info, then indeed it's not worth having a tour for just this version, we will drop it.
We will do a python only test in 17.0 :+1:

2024-03-22 08:44 UTC, loco-odoo commented
@rdeodoo , I adapted the PR consequently :+1:

2024-03-22 16:13 UTC, rdeodoo approved these changes
@robodoo r+

2024-03-22 18:39 UTC, closed without merging