[FIX] sale: display paid badge for reversed invoice in portal
odoo/odoo pull request #157693
Opened 2024-03-14 12:06 UTC by kcv-odoo

Steps:
- Install sales app.
- Create SO and add a product.
- Confirm that SO and create invoice and post it.
- Reverse that invoice via adding credit note.
- Go to portal view of that SO.

Issue:
- `Waiting Payment` badge is displaying instead of `Paid` as invoice is reversed

Cause:
- Only to payment status added to display `Paid` badge.

Fix:
- Add `reversed` payment_state in that condition to display `Paid` badge.

opw-3677622

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-14 12:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157693).

2024-03-15 12:01 UTC, Demesmaeker requested changes
Hello :duck: 

Can't we use the "reversed" badge instead? See in `account_payment`, when checking all the invoices:
![image](https://github.com/odoo/odoo/assets/69820391/d8fc0d16-b152-4f8a-85cb-e627433ee08e)

Have a nice day!

2024-03-18 04:59 UTC, kcv-odoo commented
Hello :eagle: 

Yes, sure!

Have a great day!

2024-03-18 12:18 UTC, Demesmaeker approved these changes
Hello :duck: 

One last change and then ready to go!

@robodoo delegate +

2024-03-18 12:37 UTC, Feyensv commented on addons/sale/views/sale_portal_templates.xml
> +                                    <span t-elif="i.payment_state == 'reversed'" class="small badge badge-success orders_label_text_align"><i class="fa fa-fw fa-check"/> <b>Reverse</b></span>
And a little pot update ? :duck:

2024-03-18 12:39 UTC, Demesmaeker commented on addons/sale/views/sale_portal_templates.xml
> +                                    <span t-elif="i.payment_state == 'reversed'" class="small badge badge-success orders_label_text_align"><i class="fa fa-fw fa-check"/> <b>Reverse</b></span>
woops, indeed :facepalm:

2024-03-18 13:00 UTC, kcv-odoo commented on addons/sale/views/sale_portal_templates.xml
> +                                    <span t-elif="i.payment_state == 'reversed'" class="small badge badge-success orders_label_text_align"><i class="fa fa-fw fa-check"/> <b>Reverse</b></span>
Done! :ok_man:

2024-03-19 04:42 UTC, kcv-odoo commented
Thank you @Demesmaeker and @Feyensv for your reviews :smiley: 
@robodoo r+

2024-03-19 04:42 UTC, robodoo commented
I'm sorry, @kcv-odoo: you can't review+.

2024-03-19 09:17 UTC, Demesmaeker commented
>.< I'm soooo sorry...

@robodoo delegate+

2024-03-19 09:24 UTC, kcv-odoo commented
@Demesmaeker :hugs: 

@robodoo r+

2024-03-19 14:12 UTC, closed without merging