[FIX] web, mail: adapt PWA scope for path-based url
odoo/odoo pull request #157717
Opened 2024-03-14 13:43 UTC by res-odoo

Since odoo/odoo@c63d14a0485a553b74a8457aee158384e9ae6d3f , the scope of the pwa was using the legacy mode and break the webpush notification.

This commit fix the web push notification with using the right pwa scope

2024-03-14 13:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157717).

2024-03-14 13:48 UTC, jpp-odoo requested changes
the '/odoo' route is reserved for the webClient, and the new url

2024-03-14 13:48 UTC, jpp-odoo commented on addons/web/controllers/webmanifest.py
> +    @http.route('/odoo/manifest.webmanifest', type='http', auth='public', methods=['GET'])
the '/odoo' route is reserved for the webClient, and the new url

2024-03-14 13:48 UTC, jpp-odoo commented on addons/web/controllers/webmanifest.py
> +    @http.route('/odoo/service-worker.js', type='http', auth='public', methods=['GET'])
same as before

2024-03-14 13:48 UTC, jpp-odoo commented on addons/web/controllers/webmanifest.py
> +    @http.route('/odoo/offline', type='http', auth='public', methods=['GET'])
same as before

2024-03-21 12:10 UTC, res-odoo commented
close: https://github.com/odoo/odoo/pull/158564

2024-03-21 12:10 UTC, closed without merging