[FIX] account: fixing import of a payment reference from Factur-X
odoo/odoo pull request #157811
Opened 2024-03-14 21:42 UTC by petvoj

When importing an invoice from a Factur-X format a payment reference is now read from correct field. From the same field where the original payment reference is exported.

Description of the issue/feature this PR addresses:

Current behavior before PR:
When importing an invoice from a Factur-X format a payment reference was imported from wrong field related to a buyer order referenced document. But when the invoice is exported to Factur-X the original payment reference is exported to a specific field "PaymentReference" under "SupplyChainTradeTransaction" section.

Desired behavior after PR is merged:
The imported field is the same as exported.

I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

2024-03-14 21:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/157811).

2024-04-10 13:10 UTC, alialfie requested changes
Thanks for the fix! Could you change the commit title so it follows the [git guildlines](https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html)? Just need to change the module name.

2024-04-10 19:45 UTC, jco-odoo commented
@petvoj It should be in the commit msg, not the PR title.  The commit itself needs to be changed.  Otherwise, it looks good to me as well.

2024-04-10 19:56 UTC, petvoj commented
@jco-odoo; done. Sorry for complications, this is my very first pull request into Odoo 😉

2024-04-11 09:01 UTC, jco-odoo commented
@petvoj Thanks a lot!

2024-04-11 09:01 UTC, jco-odoo commented
@robodoo r+

2024-04-11 11:22 UTC, closed without merging