[IMP] website_sale: Split the _get_checkout_steps function to allow other modules to add steps.
odoo/odoo pull request #158026
Opened 2024-03-19 03:37 UTC by daonamutc1

Description of the issue/feature this PR addresses:

Sometimes users need to add necessary checkout steps.
The _get_checkout_steps function currently cannot add steps to it.

Current behavior before PR:
The _get_checkout_steps function currently cannot add steps to it.
Desired behavior after PR is merged:
Allow users to add custom steps.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-19 03:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158026).

2024-03-19 04:24 UTC, daonamutc1 commented
@mathieu-mgm can you review?

2024-03-19 04:27 UTC, daonamutc1 commented
@mano-odoo can you review?

2024-03-19 08:31 UTC, mano-odoo commented
Hello @daonamutc1, I would be happy to review design related changes, but for this PR it would be better to ping @odoo/rd-ecommerce 😄

2024-03-19 08:33 UTC, daonamutc1 commented
> Hello @daonamutc1, I would be happy to review design related changes, but for this PR it would be better to ping @odoo/rd-ecommerce 😄

Thank you, it's really hard to find the exact author of this piece of code. Sorry for the inconvenience.

2024-03-19 09:04 UTC, daonamutc1 commented
@Feyensv Can you review

2024-03-19 10:50 UTC, chevalierv requested changes
Hello @daonamutc1 

As you can see in the PR, C3POdoo has already ping the righteous team to review your PR. There is no need to ping everyone on it.

It is possible to add steps to this method, this method is already overridden in our enterprise repository. You can get all the steps by calling the parent like this:
`parent_steps = super()._get_checkout_steps(current_step=None)`
But I do agree that it is not a perfect solution as you'll need to look for `current_step` in your override too.

I've left some comments about your PR, please apply them so I can merge the PR afterward.

Also, please change your commit title to something a little bit shorter so everything fits on one line. Here is a suggestion: `add hook to _get_checkout_steps for easier override` 

Have a nice day!

2024-03-19 10:50 UTC, chevalierv commented on addons/website_sale/models/website.py
> +    def _get_checkout_steps_list(self):
Please add a complete docstring
```suggestion
    def _get_checkout_step_list(self):
        """ Return an ordered list of steps according to the current template rendered.
      
        :rtype: list
        :return: A list with the following structure:
            [
                [xmlid],
                {
                    'name': str,
                    'current_href': str,
                    'main_button': str,
                    'main_button_href': str,
                    'back_button': str,
                    'back_button_href': str
                }
            ]
        """
```

2024-03-19 10:50 UTC, chevalierv commented on addons/website_sale/models/website.py
> +        """
Don't forget to adapt the docstring
```suggestion
        """ Return an ordered list of steps according to the current template rendered.
        If `current_step` is provided, returns only the corresponding step.
        Note: self.ensure_one()
        :param str current_step: The xmlid of the current step, defaults to None.
        :rtype: list
        :return: A list containing the steps generated by :meth:`_get_checkout_step_list`.
        """
```

2024-03-19 10:50 UTC, chevalierv commented on addons/website_sale/models/website.py
> -
Why remove this blank line?

2024-03-19 11:03 UTC, chevalierv commented on addons/website_sale/models/website.py
> +	    """
:eyes: 
```suggestion
	      If `current_step` is provided, returns only the corresponding step.
	      Note: self.ensure_one()
	      :param str current_step: The xmlid of the current step, defaults to None.
	      :rtype: list
	      :return: A list containing the steps generated by :meth:`_get_checkout_step_list`.
	  """
```

2024-03-19 11:04 UTC, daonamutc1 commented
> Hello @daonamutc1
> 
> As you can see in the PR, C3POdoo has already ping the righteous team to review your PR. There is no need to ping everyone on it.
> 
> It is possible to add steps to this method, this method is already overridden in our enterprise repository. You can get all the steps by calling the parent like this: `parent_steps = super()._get_checkout_steps(current_step=None)` But I do agree that it is not a perfect solution as you'll need to look for `current_step` in your override too.
> 
> I've left some comments about your PR, please apply them so I can merge the PR afterward.
> 
> Also, please change your commit title to something a little bit shorter so everything fits on one line. Here is a suggestion: `add hook to _get_checkout_steps for easier override`
> 
> Have a nice day!

I tried `parent_steps = super()._get_checkout_steps(current_step=None)`. However, after adding a new step, `next(step for step in steps if current_step in step[0])[1]` will raise an error because the new step is not in `steps`.

2024-03-19 14:06 UTC, chevalierv requested changes

2024-03-19 14:06 UTC, chevalierv commented on addons/website_sale/models/website.py
> +        steps = self._get_checkout_steps_list()
```suggestion
        steps = self._get_checkout_step_list()
```

2024-03-20 11:10 UTC, chevalierv commented
@robodoo r+ squash

2024-03-20 11:11 UTC, robodoo commented
Merge method set to squash.

2024-03-20 16:03 UTC, closed without merging