[FIX] calendar: set an active base_event_id for recurrence rule
odoo/odoo pull request #158335
Opened 2024-03-20 11:02 UTC by kawkb

Issue:
    - When you set a recurring meeting to a new future
    date, it doesn't update the existing meetings.
    Instead, it creates a duplicate recurring meeting
    on the new date, resulting in two sets of meetings:
    one for the original date and another for the new date.

Steps To Reproduce:
    - ICreate a new meeting in the calendar.
    - Set it to recur on the first day of each month for 12 months..
    - Go to one of the scheduled meetings and edit it.
    - Select the "all events" option and change the recurrence
     to the second day of each month.
    - Observe that the original meetings remain in the calendar.

Solution:
    - When creating a meeting, the `_apply_recurrence_values`
    method assigns the `base_event_id` of the recurrence
    to the current event. If this event doesn't fall within
    the dates specified in the recurrence, it becomes detached
    `_detach_events`, and its `recurrence_id` is set to False.

    - Editing a meeting triggers `action_mass_archive`, which, if
    the base event lacks a `recurrence_id`, retains the old
    scheduled meeting. To address this, I modified 'apply recurrence'
    to ensure there's always an active base event.

opw-3734702

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-20 11:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158335).

2024-03-21 12:32 UTC, geflx requested changes
Thanks for your work!
It is an interesting update and you described pretty well the flow in the PR description. 😊

Since this flow impacts also `google_calendar` and `microsoft_calendar` modules, it will be necessary adding a test in the three calendar modules.

They are pretty simple, here are some examples with `all_events` recurrence update for each module:

- `calendar`: See `test_shift_all` at file `test_event_recurrence.py`

- `google_calendar`: See `test_all_event_updated` at file `test_sync_odoo2google.py`

- `microsoft_calendar`: See `test_update_name_of_all_events_of_recurrence_from_odoo` at file `test_update_events.py`

2024-06-11 10:40 UTC, geflx approved these changes
Looks good to me, thanks for you work :smile: 
Tested successfully on `calendar` and `google_calendar`modules.
Not needed in `microsoft_calendar`, since this module has recurrence updates deactivated when synchronization is ON.

2024-06-17 13:29 UTC, kawkb commented
I am closing this PR, because the issue was fixed here: https://github.com/odoo/odoo/pull/149349

2024-06-17 13:29 UTC, closed without merging