[IMP] base: Added list of states of pakistan
odoo/odoo pull request #158531
Opened 2024-03-21 09:36 UTC by hsal-odoo

The 7 states of pakistan were added. Each state was added on 2 lines:
1. One line for English language.
2. Another line for Urdu language translation.

The states of pakistan were missing.

task-3777571

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-21 09:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158531).

2024-03-21 10:18 UTC, hsal-odoo commented
> Per task 3644762, unless Pakistan Post recommends or requires using the state name in postal address please put the information in a localisation module instead.
> 
> Also per task 3644762 it might be a better idea to put both latin and urdu names in the same value similar to the autonomous communities of spain rather than duplicate them, but @bouvyd should probably be the judge of that bit.

@xmo-odoo the same approach was followed here https://github.com/odoo/odoo/pull/128243

2024-03-25 15:39 UTC, RicGR98 commented
A unrelated test is failing on runbot, could you rebase ?

2024-03-27 12:44 UTC, malb-odoo requested changes
Good job ! Small thing here and it will be good :smile:

2024-03-27 12:44 UTC, malb-odoo commented on addons/l10n_pk/data/res.country.state.csv
> +state_pk_sd,base.pk,"سندھ","SD"
Missing EOF, set up you IDE to do it for you :smile:

2024-04-03 06:55 UTC, malb-odoo approved these changes
LGTM thanks for that ! keep the nice work :smile: It needs a rebase thought

2024-04-05 13:02 UTC, qdp-odoo commented
@robodoo r+

@hsal-odoo thank you :+1:

2024-04-05 19:14 UTC, closed without merging