[IMP] l10n_in_pos: revamp coins/bills screen
odoo/odoo pull request #158514
Opened 2024-03-21 08:55 UTC by sjai-odoo

Before this commit:
Currency with values below ₹1 were also visible in coin/bill screen which are now discontinued in India.

After this commit: 
Modify coin/bill screen to show currencies with values above ₹1.

task-3726978

2024-03-21 08:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158514).

2024-03-21 10:14 UTC, paso-odoo requested changes
@sjai-odoo 
Thanks for working on this PR.
Here are some improvement points from my side.

Cheers!

2024-03-21 10:14 UTC, paso-odoo commented on addons/l10n_in_pos/static/src/money_details_popup_in.js
> +        const indiaMoneyDetails = Object.entries(this.state.moneyDetails)
```suggestion
        if(this.pos.company.country_id?.code == "IN"){
            const indiaMoneyDetails = Object.entries(this.state.moneyDetails)
```

I would check country code before the logic

2024-03-21 10:14 UTC, paso-odoo commented on addons/l10n_in_pos/static/src/money_details_popup_in.js
> +        });
```suggestion
            this.state = useState({
                moneyDetails: indiaMoneyDetails,
            });
        }    
```

2024-03-21 10:14 UTC, paso-odoo commented on addons/l10n_in_pos/static/src/money_details_popup_in.js
> +                return filteredDetails;
Need to optimize

2024-03-21 12:48 UTC, paso-odoo commented on addons/l10n_in_pos/static/src/money_details_popup_in.js
> +            {}
```suggestion
```
?

2024-03-21 12:49 UTC, paso-odoo commented on addons/l10n_in_pos/static/src/money_details_popup_in.js
> +            },
```suggestion
            const indiaMoneyDetails = Object.entries(this.state.moneyDetails)
                .reduce((filteredDetails, [key, value]) => {
                    if (parseFloat(key) >= 1) {
                        filteredDetails[key] = value;
                    }
                    return filteredDetails;
                },
```

2024-03-29 11:42 UTC, caburj commented
closing this PR in favor of https://github.com/odoo/odoo/pull/159272

2024-03-29 11:42 UTC, closed without merging