[FIX] mrp: compute manufacture workorder duration
odoo/odoo pull request #158789
Opened 2024-03-22 10:12 UTC by sbel-odoo

Currently, when making a manufacture order, the duration for operations is not computed when time was not tracked.

Steps to reproduce:
-------------------
* Go to the **Manufacturing** App
* Under **Products**, select **Bill of Materials**
* Create a new bill of materials
  * Add any product
  * Add any component
  * Add an operation
    * Select any work center
    * For `Duration Computation`, select `Set duration manually`, set any amount
* Save everything
* Under **Operations**, select **Manufacturing Orders**
* Create a new order
* Select the product for which the bill of meterial was created
* Save > Confirm > Mark as done
> Observation: Real duration is showing 0, instead of the manual amount.

Why the fix:
------------
As of now, the duration only depends on the time tracked on each operation. https://github.com/odoo/odoo/blob/7a9b05e5e7ccc54fe673a00167a261c2c6181d0a/addons/mrp/models/mrp_workorder.py#L318-L321

The issue was solved in upper versions with this fix: https://github.com/odoo/odoo/commit/5e2b97b47f3cf14616c24631acf2cd08f0295a43

I'm partially backporting this fix as the issue it was originally for does not exist in 16.0 but it still solves the fact that the duration isn't computed if time was not tracked

opw-3800477

2024-03-22 10:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158789).

2024-03-22 10:14 UTC, sbel-odoo commented
NOTE: The fix will be removed in 16.0 but the test will go up to master.

2024-03-25 11:48 UTC, DjamelTouati requested changes
Hello @sbel-odoo ,

For me, it's better to do a full backport of this commit: https://github.com/odoo/odoo/commit/707769478b9f63319689ff2347d300ce1800d1d0.

I've tested it, and it works well. This allows us to have identical code across all versions.
Thank you!

2024-04-02 09:13 UTC, DjamelTouati commented
LGTM, Thank you for the update ;)

2024-04-02 09:21 UTC, amoyaux commented
robodoo r+

2024-04-02 11:40 UTC, closed without merging