[IMP] point_of_sale: Remove use of pos when selecting line in models
odoo/odoo pull request #158779
Opened 2024-03-22 09:32 UTC by davidmonnom

The pos object is not needed in the models when selecting a line. This commit removes the use of pos in the models and uses the store instead.

2024-03-22 09:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158779).

2024-03-22 13:05 UTC, adgu-odoo requested changes
There are still occurence of select_orderline in the codebase, is it normal or is it a mistake ?

2024-03-22 13:05 UTC, adgu-odoo commented on addons/pos_sale/static/src/overrides/models/pos_store.js
> +            line.product_id.id === line.config.down_payment_product_id.id
```suggestion
            line.product_id.id === this.config.down_payment_product_id.id
```
Be consistent and use the config linked to the line or to the pos in both places

2024-03-22 13:09 UTC, davidmonnom commented
> There are still occurence of select_orderline in the codebase, is it normal or is it a mistake ?

Isn't an error, when select_orderline can be called inside the models, but selectOrderLine is made for components who's have access to pos_store

2024-03-22 13:16 UTC, adgu-odoo approved these changes

2024-03-22 14:47 UTC, adgu-odoo commented
@robodoo r+

2024-03-23 03:00 UTC, robodoo commented
@davidmonnom @adgu-odoo staging failed: ci/runbot (view more at https://runbot.odoo.com/runbot/build/60259638)

2024-03-23 15:58 UTC, d-fence commented
robodoo retry

2024-03-23 18:31 UTC, closed without merging