[IMP] account: add setting for local currency on invoice
odoo/odoo pull request #158820
Opened 2024-03-22 13:07 UTC by hupo-odoo

This commit adds a setting to let the user choose if he wants the VAT to be displayed in local currency on his invoices.

In 16.3 we introduced the VAT computation in company currency for invoices made in foreign currencies with this commit: https://github.com/odoo/odoo/commit/8823e01040f9522947e5d11c7312d09c50867cc4. We activated it by default because it's a legal requirement in many localisations (see original task for more details). In some countries however, the feature is not wished as:
    - Cash basis is often used. The tax computation at the invoice creation doesn't make sense then.
    - The local currency may undergo severe fluctuations and is rarely used.

task-3821226

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-22 13:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/158820).

2024-03-25 09:59 UTC, alialfie approved these changes
LGTM @h4818

2024-03-26 12:23 UTC, h4818 requested changes
Thanks @hupo-odoo 

Just a few small things...
Also, I confirm with @tsb-odoo that the term "VAT" is too restrictive, and we should use "Taxes" instead

2024-03-26 12:23 UTC, h4818 commented on addons/account/models/company.py
> +        string='VAT in company currency',
Taxes in company currency

2024-03-26 12:23 UTC, h4818 commented on addons/account/views/res_config_settings_views.xml
> +                            <setting id="display_total_company_currency" help="The VAT is also displayed in local currency on invoices made in foreign currency">
Taxes are also displayed in local currency on invoices

2024-03-27 13:07 UTC, hupo-odoo commented
Thanks @h4818 for the review. I've made the requested changes :smile:

2024-03-28 11:16 UTC, h4818 reviewed
the last nitpick

2024-03-28 11:16 UTC, h4818 commented on addons/account/views/report_invoice.xml
> +                o.move_type in ['out_invoice', 'out_refund'] and o.company_id.display_invoice_tax_company_currency"/>
I'm not sure if we could short circuit those other conditions if we place `o.company_id.display_invoice_tax_company_currency` first. 
Also, Might as well put each condition on a new line starting with `and`

2024-03-28 11:17 UTC, h4818 commented on addons/account/views/res_config_settings_views.xml
> +                            <setting id="display_invoice_tax_company_currency" help="Taxes are also displayed in local currency on invoices made in foreign currency">
`made in foreign currency` is implicit and can be removed

2024-03-28 14:50 UTC, hupo-odoo commented
Thanks @h4818 for the review! :smile:  I've made the requested changes

2024-03-28 17:09 UTC, h4818 commented on addons/account/models/company.py
> +        default=True
is the comma still missing?

2024-03-29 07:08 UTC, h4818 commented on addons/account/views/report_invoice.xml
> +                    and o.move_type in ['out_invoice', 'out_refund']"/>
```suggestion
               t-value="o.company_id.display_invoice_tax_company_currency
                        and o.company_id.currency_id != o.currency_id
                        and o.amount_tax != 0
                        and o.move_type in ['out_invoice', 'out_refund']"/>
```

2024-03-29 08:49 UTC, h4818 commented
gg @hupo-odoo 
@robodoo r+

2024-03-29 17:06 UTC, closed without merging