[17.0][FIX] account: fix not error when delete the SO on form view
odoo/odoo pull request #159018
Opened 2024-03-23 03:19 UTC by SonCrits

This PR
-

- Fix bug when delete SO

**Step**
- Create SO
- Confirm SO, add delivered If the product is a warehouse product
- Create Invoice
- Delete Invoice
- Cancel SO
- Delete SO

**Output**

- Displays the error totals.subtotals order is not iterable

**Reason**

- When unlink SO, tax value no longer exists, so, return value of totals is false, and when try loop totals.subtotals_order (undefine value) will be display this error

**Solution**

- Check the total input value. If there is no value or the return value is false, return it

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-23 03:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/159018).

2024-03-25 13:58 UTC, casp-odoo requested changes
I can't reproduce the issue on the latest runbot 17.0. Maybe some more specific changes are not mentioned ?

2024-03-26 11:50 UTC, SonCrits commented
https://github.com/odoo/odoo/assets/95740163/3de2082f-061f-4663-a0f4-e0806c5f20d7

@casp-odoo , I did it again on the latest runbot, giving you an attached video as proof

2024-03-26 12:36 UTC, casp-odoo reviewed
OK, my bad : I tested with Enterprise. The bug only occurs in Community though, which might give further clue about what's actually happening. Might be worth investigating a bit ! 

I unfortunately have no further ideas on the how-to ; let's see if @Levizar is more enlightened.

2024-03-27 03:54 UTC, SonCrits commented
@Levizar Do you have any solution for this problem?

2024-03-27 03:54 UTC, SonCrits commented
> OK, my bad : I tested with Enterprise. The bug only occurs in Community though, which might give further clue about what's actually happening. Might be worth investigating a bit !
> 
> I unfortunately have no further ideas on the how-to ; let's see if @Levizar is more enlightened.

thank you @casp-odoo

2024-04-01 08:20 UTC, SonCrits commented
@Levizar It seems you are missing notifications in this PR. Ping

2024-04-01 09:20 UTC, Levizar commented
Hi @SonCrits, no I didn't miss it.

I know it's a bit long to wait, sorry for that. 
I'm a bit drawn under PRs to review, was sick last week and today is an official holiday in Belgium.

I'll have a look to this one tomorrow.
Have a nice day

2024-04-01 11:00 UTC, duong77476-viindoo commented on addons/account/static/src/components/tax_totals/tax_totals.js
> +		}
```suggestion
        if (!totals) {
            return;
        }
```

2024-04-01 11:00 UTC, duong77476-viindoo commented on addons/account/static/src/components/tax_totals/tax_totals.js
> +		}
Need to preserve the format i suppose

2024-04-02 15:09 UTC, Levizar requested changes
First of all, thank you for your PR.
I investigated a lot on this today and needed to ask for several colleagues input/help.

Regarding the PR itself:
1) As @duong77476-viindoo said, could you format it?  
2) could you update your commit message to include the minimal step? (it is shorter than  currently described) and to include the following explanation?

Reproduction steps:
- disable any debugger parameter that would on in the url
- create a new sale order
- add a sale order line with a tax
- save (and don't leave the record!)
- delete the sale order

Regarding the bug, there are several issues happening at the same time:
- Business code issue:
    - Our code wasn't defensive and we were assuming the computed value would always be set to the computed value.
- Framework JS issue: (not OWL itself but its integration into Odoo)
    - When the record is deleted, a re-rendering gets triggered.
    - As we deleted the record in the back, the browsed record in the front-end gets its data reset to the default values a field could have. Because the default value of a binary field is `False`, `tax_totals` gets set to `false` for the reset record.

Now, we have a bunch of race conditions going on.
In the invoicing view, it doesn't happen because the rendering is slower and it gets cancelled before being done. Thus the field `tax_totals` hasn't the chance to re-render itself and thus, to call `TaxTotalsComponent.formatData` through the call of `onWillRender`.
In the case of the sale order view, the field has the time to gets rendered, the method gets called and the traceback happens.

Activating the debug parameter is slowing the rendering enough for the rendering to get canceled.

In short terms (stable and master), the business code should be more defensive and be able to handle the fields default values.
In the long term, the framework JS team will try to prevent the useless rendering to happens and may try to find a solution to prevent accidental rendering to crash.

2024-04-03 02:05 UTC, SonCrits commented
@Levizar Thank you, I have updated the commit and formatted the code. Please help me review again

2024-04-03 08:42 UTC, Levizar requested changes
Sorry to be this nitpicky but it is to keep consistency.

May I suggest you to setup a linter or a formatter?
This way, you could let it take care of it automatically.

2024-04-03 08:42 UTC, Levizar commented on addons/account/static/src/components/tax_totals/tax_totals.js
> +        }
```suggestion
        if (!totals) {
            return;
        }
```

2024-04-03 22:04 UTC, Levizar approved these changes
@robodoo r+

2024-04-03 23:50 UTC, closed without merging