[FIX] website_slides: prevent exception while accessing embed external of slide
odoo/odoo pull request #159238
Opened 2024-03-26 06:18 UTC by maan-odoo

Currently, an exception is generated when the user tries to access embed view of slides by following the steps:
 - Install "eLearning" with a demo data
 - Open external embed view of slide 1 by "/slides/embed_external/1" in url

Stack Trace:
```
AttributeError: 'slide.channel' object has no attribute 'website_share_url'
  File "<1405>", line 313, in template_1405
  File "<1405>", line 151, in template_1405_content
  File "<1405>", line 18, in template_1405_t_call_0
QWebException: Error while render the template
AttributeError: 'slide.channel' object has no attribute 'website_share_url'
Template: ir.ui.view(1405,)
Path: /t/html/body/div/div[2]/t[1]/t/t[4]
Node: <t t-set="include_embed" t-value="True"/>
```

This error is generated because [1] it tries to access the 'website_share_url' field in the 'slide.channel' model but it actually belongs to 'slide.slide' see [2].

This commit resolved the above issue by accessing "website_share_url" with "slide" instead of "slide.channel".

[1]-https://github.com/odoo/odoo/blob/d3b8f05e1eba5ae5b64e0fd9c37e3195818639f1/addons/website_slides/views/website_slides_templates_lesson_embed.xml#L48 [2]-https://github.com/odoo/odoo/blob/b7532d33bf6b17c4b2044509a4d0eb5ff6b549e0/addons/website_slides/models/slide_slide.py#L217

sentry-5095823727

2024-03-26 06:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/159238).

2024-03-26 06:30 UTC, maan-odoo commented
Hello @odoo/sentry_reviewers 
Please review this PR!

Thanks!

2024-03-26 11:05 UTC, abla001 requested changes
LGTM! Just a note on the commit message, I think for [1] you mistakenly referenced the wrong line, shouldn't it be line 45 instead of 48?

2024-03-26 11:51 UTC, abla001 approved these changes

2024-03-26 14:13 UTC, Julien00859 approved these changes
LGTM, tested locally. It would be great to have a unittest but we would have to figure out a way to reproduce the test without using demo data.

2024-03-26 15:11 UTC, flch-odoo approved these changes
Instead of the reference to the particular line (as on GH it looks like it should be 46...) that does not seem to add much as it's the single line being updated here, we could perhaps limit the reference to the introducing commit hash?

Otherwise, this looks good to me too and does not warrant a test. Thanks for the fix!

2024-03-27 04:51 UTC, maan-odoo commented
> Instead of the reference to the particular line (as on GH it looks like it should be 46...) that does not seem to add much as it's the single line being updated here, we could perhaps limit the reference to the introducing commit hash?
> 
> Otherwise, this looks good to me too and does not warrant a test. Thanks for the fix!

Hello @flch-odoo 
I have updated the commit message and PR message.

 Thanks :slightly_smiling_face:

2024-03-27 07:54 UTC, tde-banana-odoo commented
@robodoo r+

2024-03-27 10:35 UTC, closed without merging