[FIX] base_vat: properly display in context
odoo/odoo pull request #159332
Opened 2024-03-26 14:27 UTC by wtaferner

**Description of the issue/feature this PR addresses:**
Having the VAT VIES Check valid field directly next to the VAT number as an inline element becomes unreadable, so we add a line break before

**Current behavior before PR:**
![Screenshot from 2024-03-26 15-26-06](https://github.com/odoo/odoo/assets/362478/a307f9d6-30b0-452f-b5ad-f6efc912e9e2)

**Desired behavior after PR is merged:**
![image](https://github.com/odoo/odoo/assets/362478/64339b68-7f63-4801-b302-b4dc23d19a34)

Info: @wt-io-it

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-26 14:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/159332).

2024-04-03 12:23 UTC, casp-odoo requested changes

2024-04-03 12:23 UTC, casp-odoo commented on addons/base_vat/views/res_partner_views.xml
> +                    <br /><label for="vies_valid" invisible="not perform_vies_validation"/>
I do think there should be a way of doing this without using a hardcoded `<br/>` ; you could have a look at `o_address_format`, where this field replaces `vat`. The fields then seem to suffice and don't mention their respective labels. Alternatively, creating a group might give the structure you're looking for :)

2024-04-03 13:48 UTC, william-andre reviewed
There is something wrong with the current 17.0, but I don't believe that the current fix is the right one.
![image](https://github.com/odoo/odoo/assets/44770049/574560f5-4a20-4579-ab52-3857275bc818)

We shouldn't force a new line, but add some padding instead between the two fields, and it shouldn't be possible to have the checkbox on a different line than its label.
But to avoid wasting space (since the VAT field is never that long), we don't need to always have a new line; only when the screen size asks for it.

What I would suggest is putting the label and the field inside of a `<span class="text-nowrap ps-2"/>` allowing for
* a dynamic display based on the size of the screen
* enforce the label and the field to always be on the same line
* always keep a minimal space between the vat field and the checkbox field

2024-04-03 14:07 UTC, wtaferner commented
@william-andre 
thx, works for me and indeed a good solution to get this fix done...

2024-04-03 14:21 UTC, MiquelRForgeFlow commented on addons/base_vat/views/res_partner_views.xml
> +                    <span class="text-nowrap ps-2"/><label for="vies_valid" invisible="not perform_vies_validation"/>
```suggestion
                    <span class="text-nowrap ps-2"><label for="vies_valid" invisible="not perform_vies_validation"/></span>
```

2024-04-03 14:22 UTC, MiquelRForgeFlow commented on addons/base_vat/views/res_partner_views.xml
>                      <field name="vies_valid" invisible="not perform_vies_validation" class="oe_inline"/>
```suggestion
                    <span class="text-nowrap ps-2"><label for="vies_valid" invisible="not perform_vies_validation"/>
                    <field name="vies_valid" invisible="not perform_vies_validation" class="oe_inline"/></span>
```

2024-04-03 14:33 UTC, william-andre approved these changes
@robodoo r+

2024-04-03 17:48 UTC, closed without merging