[FIX] l10n_latam_invoice_document: create debit note from credit note
odoo/odoo pull request #159760
Opened 2024-03-28 17:58 UTC by zaoral

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-28 17:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/159760).

2024-04-25 14:11 UTC, zaoral commented
superses  https://github.com/odoo/odoo/pull/150796

2025-01-08 15:43 UTC, jco-odoo commented
@zaoral There is no way by not completely changing the methods?  Have not we already solved this in later versions?

2025-01-08 16:15 UTC, jco-odoo commented
@zaoral What is the problem with just overriding the compute of the document type?

2025-01-08 16:42 UTC, jco-odoo commented
There is no way through adapting the onchange/compute?

2025-01-10 23:02 UTC, zaoral commented
@jco-odoo 
Hi Jos, I hope you are doing well
About your last comments here is some feedback

> @zaoral There is no way by not completely changing the methods. Have not we already solved this in later versions?

We have not resolved this in later versions :(. Without changing the method, we could make an internal method that can take the invoice_type and does not depend on the record itself. This way, we will be able to get the value without having the new() and call it inside the _get_l10n_latam_documents_domain() method. However, we will still need to change the methods in all the locs. Do you approve it? Do you have a better suggestion for me?

> @zaoral What is the problem with just overriding the compute of the document type?

We do not have a computed field on the debit note to be overridden. We do not have any field to store the document, You suggesting to change the one in account.move? this will not solve the problem?

> There is no way through adapting the onchange/compute?

We do not have any other method, I think we should not use onchanges. Maybe we can implement a compute not stored field on the debit note, but we will need to duplicate the logic we have in the account.move compute for available document fields and also make the adaptations of other localizations so can work.

Let me know your suggestions to continue
Best Regards

2025-01-14 22:57 UTC, zaoral commented
Hi @jco-odoo 
I hope you are doing well
Please let me know about how we can continue with this PR

Best Regards

2025-01-23 16:08 UTC, jco-odoo commented
@zaoral Each time I look at it, I am missing why the compute would not calculate the correct document type already the way it is working now.

2025-02-10 12:23 UTC, agr-odoo commented
@jco-odoo 

>Each time I look at it, I am missing why the compute would not calculate the correct document type already the way it is working now. (maybe the debit origin is not set you or something)

I gave a look and the reason is that when copying the original record to make the debit note, as the field `l10n_latam_document_type_id` is computed but also stored, we already have the value (from the original record) and it won't be recomputed
The solution is to provide default values to the copy, which we do with the `_prepare_default_values`, as this PR does

2025-02-10 13:48 UTC, jco-odoo reviewed
We indeed have a constraint that is triggered too early in the process when we duplicate the move and this would avoid that.  

It is a bit tricky in stable, but I do not see any of the other modules already where it would cause issues as it basically does the same.  (where _create_debit is inherited)

Happy to finally been able to check at ease.  I wonder even why, in master, we do not do the same as for credit notes and let the user choose the appropriate document type.  (I remember we did not for simplicity)

2025-02-10 13:48 UTC, jco-odoo commented on addons/l10n_latam_invoice_document/wizards/account_debit_note.py
> +            'company_id': move.company_id.id,
If you put "debit_origin_id" here, should not it compute automatically the correct l10n_latam_identification_type_id already?

2025-02-10 13:48 UTC, jco-odoo commented on addons/l10n_latam_invoice_document/wizards/account_debit_note.py
> +            'move_type': default_values.get('move_type'),
are move_type and journal_id sometimes not in the default_values?

2025-02-17 14:47 UTC, yolannsabaux requested changes
Hello,

I'll let @jco-odoo finish the final review.

In the meantime, could you retarget the branch to 17.0 ? We only fix tracebacks and critical issues in 16.0.

For me, we should simply close the pull request and the ticket (as it is _lighthly_ _functionally_ bothering). Let's see if we can find a safe way to do it in 17.0 

Thanks for your work!

2025-02-17 14:47 UTC, yosa-odoo commented on addons/l10n_latam_invoice_document/wizards/account_debit_note.py
> -    def create_debit(self):
Please do not remove methods in stable (even more if it is a public one)

2025-04-09 16:39 UTC, zaoral commented
new PR for version 17.0 https://github.com/odoo/odoo/pull/205430

2025-04-09 16:39 UTC, closed without merging

2025-04-09 16:42 UTC, zaoral commented on addons/l10n_latam_invoice_document/wizards/account_debit_note.py
> -    def create_debit(self):
We are not deleting the method, we were only extending the method.
The proposed change only extend a different method to make it work as we expected

Best Regards

2025-04-09 16:43 UTC, zaoral commented
Hi @yosa-odoo 
I appreciate your patience related to this PR
I have closed this one and created a new one for 17.0
https://github.com/odoo/odoo/pull/205430/

Best Regards  

cc @vbe-odoo