Saas 17.1 hr fix same user creation mepe
odoo/odoo pull request #159860
Opened 2024-03-29 10:33 UTC by mepe-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-02 10:11 UTC, tivisse commented on addons/hr/models/hr_employee.py
> +    user_id = fields.Many2one('res.users', 'User', related='resource_id.user_id', store=True, readonly=False, precompute=True)
Could you add a python test as well ?

2024-04-17 11:51 UTC, sofiagvaladze requested changes
@mepe-odoo looks good :raised_hands: 

I think it will make tests easier to get with the commits that I added, what do you think?

2024-04-17 11:51 UTC, sofiagvaladze commented on addons/hr/tests/test_hr_employee.py
> +        employee_form = Form(self.env['hr.employee'].with_user(self.res_users_hr_officer).with_company(company=test_company.id))
Maybe write comment like:
```suggestion
        # Try to set the user with existing employee in the company, on a new employee form
        employee_form = Form(self.env['hr.employee'].with_user(self.res_users_hr_officer).with_company(company=test_company.id))
```

2024-04-17 11:51 UTC, sofiagvaladze commented on addons/hr/tests/test_hr_employee.py
> +        employee_2_form = Form(employee_2.with_user(self.res_users_hr_officer).with_company(company=test_company.id))
```suggestion
        # Try to set the user with existing employee in the company, on another existing employee
        employee_2_form = Form(employee_2.with_user(self.res_users_hr_officer).with_company(company=test_company.id))
```

2024-04-19 09:36 UTC, sofiagvaladze commented
robodoo r+

2024-04-19 12:01 UTC, closed without merging