[IMP] point_of_sale: allow arbitrary data in related models
odoo/odoo pull request #160169
Opened 2024-04-02 13:47 UTC by davidmonnom

This commit allows to access arbitrary data in related models. This is useful for data that are computed on the server side and that are not recomputed on the client side.

Before this commit, it was only possible to access data that are linked to a field in the model.

2024-04-02 13:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160169).

2024-04-11 13:12 UTC, adgu-odoo requested changes
First batch of comments

2024-04-11 13:12 UTC, adgu-odoo requested changes
second batch of comments

2024-04-11 13:24 UTC, adgu-odoo commented on addons/point_of_sale/models/res_users.py
> +        return ['id', 'name', 'login', 'partner_id', 'groups_id']
Why do you add the login field ?

2024-04-11 13:26 UTC, adgu-odoo commented
I have some questions:

- First, can't you make _load_pos_data an `@api.model` method
- Why don't you use super()._load_pos_data() in more of your call to this method ? Maybe that would lead to less duplication of the code ?
- I think you forgot to add `pos.load.mixin` in the `product.product` model. Can you check if you did not forget it in other places ?

2024-04-11 14:11 UTC, davidmonnom commented on addons/point_of_sale/models/pos_combo.py
> +        return [('id', 'in', list(set().union(*[product.get('combo_ids') for product in data['product.product']['data']])))]
Style error when doing that

2024-04-11 14:20 UTC, davidmonnom commented on addons/point_of_sale/models/pos_session.py
> +                    'error': e.args[0]
We will add a popup or an information in the console later

2024-04-11 14:22 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.js
> +        const isCashierManager = this.pos.get_cashier()._role === "manager";
it will be always false... We will check this later

2024-04-11 14:24 UTC, davidmonnom commented on addons/pos_hr/models/hr_employee.py
> +                '|', ('user_id', '=', self.env.user.id), ('id', 'in', config_id.basic_employee_ids.ids + config_id.advanced_employee_ids.ids)]
The user will be the same but maybe not the employee, so no pb

2024-04-11 14:28 UTC, davidmonnom commented on addons/pos_razorpay/models/pos_session.py
> -        return params
Not needed since we load all fields for this model

2024-04-11 14:28 UTC, davidmonnom commented on addons/pos_restaurant/models/pos_restaurant.py
> +        return [('active', '=', True), ('floor_id', 'in', [floor['id'] for floor in data['restaurant.floor']['data']])]
is needed because when deleting a floor from the frontend it mark it as inactive

2024-04-11 14:31 UTC, davidmonnom commented on addons/l10n_pe_pos/models/l10n_pe_res_city_district.py
> +        return ["name", "city_id", "country_id", "state_id"]
Not needed this models is only loaded if we are in a PE company

2024-04-12 09:04 UTC, davidmonnom commented on addons/pos_hr/models/hr_employee.py
> +        employees = self.search(domain)
Not needed the model will not be loaded if module_pos_hr isn't true

2024-04-12 09:06 UTC, davidmonnom commented on addons/l10n_pe_pos/models/res_city.py
> +        return ["name", "country_id", "state_id"]
Not needed this models is only loaded if we are in a PE company

2024-04-12 14:13 UTC, adgu-odoo requested changes

2024-04-29 11:41 UTC, adgu-odoo commented
@robodoo r+

2024-04-30 00:55 UTC, closed without merging