[IMP] base: display only company name in duplicate Tax ID warning
odoo/odoo pull request #160373
Opened 2024-04-03 16:04 UTC by mairasalazar

When creating a new company from a move, if the tax ID is repeated, a warning is displayed. The warning includes the company name, address and VAT, if those have been added. In this case, address is shown in an extra line, which looks broken.

This commit removes additional partner information by updating the context, displaying only the partner name.

It also slightly rewords the warning, from "are you sure to create a new one?" to "are you sure you want to create a new one?".

To replicate the issue:
1. Create an invoice
2. Click on the empty field next to Customer, type a new name and click "Create and edit..."
3. Add a Tax ID that is already in use (e.g. US12345673)
4. Warning of duplicate Tax ID shows, displaying company name, address and VAT

task-3829641

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-03 16:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160373).

2024-04-05 07:46 UTC, malb-odoo approved these changes
LGTM thanks for that :smile: and nice job on the very detail commit message :rocket:

2024-04-05 07:59 UTC, FlorianGilbert reviewed
@robodoo delegate=@malb-odoo

2024-04-05 08:12 UTC, qdp-odoo requested changes
If you change the text here it will break the existing translations for non-english speakers.

2 solutions: 
* don't change the label here but only in master, and keep only the context fix for the stable version
* add a translation for en_us that change fix the label

2024-04-05 13:05 UTC, qdp-odoo commented
@robodoo r+

2024-04-05 15:47 UTC, closed without merging