[FIX] stock: prevent keyerror when reloading page
odoo/odoo pull request #160440
Opened 2024-04-04 04:48 UTC by reka-odoo

When the customer opens the product from Physical Inventory and tries to reload
the page, a traceback will appear.

Steps to reproduce the error:
- Go to Inventory > Operations > Physical Inventory
- Open any product > reload the page

Traceback:
```
KeyError: 'display_name'
  File "odoo/http.py", line 2251, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1827, in _serve_db
    return self._transactioning(_serve_ir_http, readonly=ro)
  File "odoo/http.py", line 1847, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1825, in _serve_ir_http
    return self._serve_ir_http(rule, args)
  File "odoo/http.py", line 1832, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 2057, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 220, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 739, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/action.py", line 74, in load_breadcrumbs
    name = act['display_name'] if any(view[1] != 'form' and view[1] != 'search' for view in act['views']) else None
```

https://github.com/odoo/odoo/blob/853bd97eda1f4eca5f9f63ef1c5909fddaa98d27/addons/stock/models/stock_quant.py#L388 Here, 'display_name' key is not present.

https://github.com/odoo/odoo/blob/853bd97eda1f4eca5f9f63ef1c5909fddaa98d27/addons/web/controllers/action.py#L74 When Customer reloads the page,
It will try to access 'display_name' here, but it is not present.
So, It will lead to the above traceback.

sentry-5132471164

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-04 04:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160440).

2024-04-04 12:19 UTC, reka-odoo commented
Hello @odoo/sentry_reviewers :wave: 
Please review this PR.
Thanks!

2024-04-08 07:14 UTC, jpp-odoo approved these changes
Thanks for the fix.

@robodoo r+

2024-04-08 07:15 UTC, jpp-odoo commented
@robodoo r-

2024-04-08 07:17 UTC, jpp-odoo requested changes
Sorry,

Maybe you can put your code, below the run of the action server.

Like that, if the action returned from the execution of the action server don't have display name, it will also add the display name in that case.

(after line 61)

2024-04-09 13:26 UTC, reka-odoo commented
Hello @jpp-odoo :wave: 
Can you check this PR.
Thanks!

2024-04-09 14:00 UTC, jpp-odoo approved these changes
Thank you for the fix !
@robodoo r+

2024-04-09 16:15 UTC, closed without merging