[FIX] website: prevent void visibility comparator on form fields
odoo/odoo pull request #160464
Opened 2024-04-04 09:03 UTC by Guillaume-gdi

[This first commit] made it possible to have an error when there was no comparator for a field with conditional visibility. [This second commit] prevented an error from occurring in this case. The purpose of this commit is to prevents the user from getting a conditional visibility configuration for a form field where there is no comparator.

Steps to reproduce the problem:
- Go to /contactus.
- Edit page.
- Click on the "Your Company" field.
- Select "Visible Only If" for the "Visibility" option.
- Click on "Visible Only If" again.

=> The comparator is not defined.

Technical information:
When we change the field's visibility to conditional (`setVisibility`), we add a default visibility dependency (`_setVisibilityDependency`). At this point, the comparator is removed and added in `_renderCustomXML`. `_renderCustomXML` was only called if the visibility dependency had changed.

[This first commit]: https://github.com/odoo/odoo/commit/910897fc97d87b08f01627094ec8c159f5267628
[This second commit]: https://github.com/odoo/odoo/commit/808780c89cfba940957f7410f787de31e31bda27

opw-3806409

2024-04-04 09:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160464).

2024-04-04 12:53 UTC, Guillaume-gdi commented
@qsm-odoo This OPW related PR is ready for your review.

2024-04-05 08:08 UTC, qsm-odoo commented
@Guillaume-gdi @xO-Tx On the task I think there were two bugs that I thought to be solved: the UI but also the fact that currently malformed form should not crash, is this commit fixing that?

@robodoo delegate=xO-Tx

2024-04-05 08:27 UTC, Guillaume-gdi commented
@qsm-odoo the traceback issue has been fixed by [this other commit](https://github.com/odoo/odoo/commit/808780c89cfba940957f7410f787de31e31bda27) last week. I just prevent the miss config here.

2024-04-08 13:50 UTC, xO-Tx requested changes
@Guillaume-gdi Shouldn't we also fix default values when the visibility field type is updated :thinking: ? (e.g., using `customField()` & `existingField()`):

[15.0.rev-visibility-options--gdi.webm](https://github.com/odoo/odoo/assets/25032876/90036d61-5ab3-4f9a-b0d6-ddc7814d5359)

After a quick code check, it seems that the rendering is triggered after the field update, but if the new field type is not supporting the old comparator, the default value won't be set (even with a `rerender === true`). Probably because the current code is only testing if the comparator [is available and not if it's supported…](https://github.com/odoo/odoo/blob/15.0/addons/website/static/src/snippets/s_website_form/options.js#L1372)

Maybe we can simply `_deleteConditionalVisibility()` on all fields whose visibility depends on the replaced one, in the same way we do for labels (see: `setLabelText()`)... What do you think ?

2024-04-10 08:00 UTC, Guillaume-gdi commented
@xO-Tx I adapted the PR to your comment :heavy_check_mark:

2024-04-10 13:20 UTC, xO-Tx requested changes
@Guillaume-gdi Thanks for fixing the visibility when the type was updated :pray: I think this will be perfect if we add a test for it in the tour... I suggest something like this (feel free to change it as you like :+1:)

```diff
+ ...addCustomField("char", "text", "Text", false, {visibility: CONDITIONALVISIBILITY}),
+ ...addCustomField("selection", "radio", "Radio", false),
+ ...selectFieldByLabel("Text"),
+ ...selectButtonByData('data-set-visibility-dependency="Radio"'),
+ ...selectFieldByLabel("Radio"),
+ ...selectButtonByData('data-custom-field="char"'),
+ ...selectFieldByLabel("Text"),
+ {
+     content: "Open the select",
+     trigger: `we-select:has(we-button[data-set-visibility="visible"]) we-toggler`,
+ },
+ {
+     content: "Check that the field no longer has conditional visibility",
+     trigger: "we-select we-button[data-set-visibility='visible'].active",
+     run: () => null,
+ },
```
Could you also fix a massage mini-typo: "The purpose of this commit is to prevent[~~s~~]" on your way? Thanks :+1:

2024-04-10 13:51 UTC, qsm-odoo commented
I'd like you to fix me a massage too @Guillaume-gdi 🤡 cc @xO-Tx

2024-04-10 14:37 UTC, Guillaume-gdi commented
:heavy_check_mark: test added :green_circle: 
:heavy_check_mark: commit message fixed :green_circle: 

... massages not done :red_circle: but it's ready to launch @xO-Tx  :rocket:

2024-04-11 08:34 UTC, xO-Tx approved these changes
LGTM @Guillaume-gdi thanks for the fix and adaptation :+1:

@robodoo r+

2024-04-11 11:05 UTC, closed without merging