[FIX] website, *: remove number of subscribers on website form
odoo/odoo pull request #160509
Opened 2024-04-04 12:28 UTC by SergeBayet

*: website_mass_mailing

Before this commit, when a "Form" snippet was added and the action was
changed to "Subscribe to Newsletter", the mailing lists appeared as
checkbox fields with the number of subscribers in parentheses. This
commit removes the display of this unnecessary information.

Steps to reproduce:

- Install the "Email Marketing" module and Website.
- Navigate to the Website in edit mode.
- Drag & drop the "Form" block (dynamic content section).
- Change the form action by setting the "Action" option to "Subscribe to
  Newsletter".

Bug: The number of subscribers appears next to the mailing list names.

task-3472820

Co-authored-by: Adrien Milis <miad@odoo.com>

2024-04-16 14:34 UTC, sobo-odoo reviewed
Here is my pair-review :slightly_smiling_face:

2024-04-17 08:37 UTC, SergeBayet commented on addons/mass_mailing/models/mailing_list.py
@sobo-odoo Good point. I'll make me a reminder to check the FW port on 16.4 and use the correct method.

2024-04-17 12:40 UTC, qsm-odoo commented
Agreed with TDE @SergeBayet, this fix should only impact the snippet

2024-04-17 13:18 UTC, SergeBayet commented
@tde-banana-odoo @qsm-odoo I've modified the code to avoid that. Thanks for your input.

2024-04-17 13:53 UTC, reth-odoo reviewed
I remember we concluded it wasn't cleanly doable 
https://github.com/odoo/odoo/pull/130876

But maybe you'll have better ideas

2024-04-17 14:36 UTC, SergeBayet commented
@reth-odoo I guess my solution is not perfect regarding https://github.com/odoo/odoo/pull/130876. We'll see.

2024-04-18 10:00 UTC, qsm-odoo requested changes
@SergeBayet Is not that the same diff they made before? What was not working in theirs? In any case, let's try not to mention "mailing.list" in the "website" module :wink:

2024-04-19 14:12 UTC, qsm-odoo commented
@SergeBayet I read the conversation in the task, I don't understand it. For me, if working, what was done in https://github.com/odoo/odoo/pull/130876 by @adrienmilis is exactly what we want (if both commits were squashed).

@awa-odoo @LNAodoo Can you confirm again why you canceled it? It seems it was because you did not like the fact that x2x fields are not dynamic in website forms but that's just the way it is at the moment (that may change in the future). Meanwhile it does seem nice to allow not to display the subscribers count for this specific field? Actually: the fact that it is not dynamic is an argument in favor of hiding that info, no?

2024-04-22 08:18 UTC, awa-odoo commented
Hello @qsm-odoo 

From what I remember, it added complexity in the "form field" keys to support something we only need for a single use case.
It also does not fix existing labels, only the ones created post-fix (from what I understand).

It could be done still if you're ok with it, as it's a feedback that keeps coming back.

Hope that helps, cheers!

2024-04-22 13:42 UTC, LNAodoo commented
Hello there, 

Indeed, from what I remember we canceled it because we considered the fix to be a bit too complicated.
But we're still for it so if there is an elegant solution, feel free to go for it :-)

Cheers!

2024-04-22 15:00 UTC, qsm-odoo commented
@SergeBayet Let's take the work that was done in the other PR, move it here into one single commit, add you and the original dev as co-authors, make sure it works then we'll go with it. Thanks :pray:

2024-04-23 06:54 UTC, SergeBayet commented
@qsm-odoo It's done. Hope that satisfies everyone.

2024-04-23 15:26 UTC, qsm-odoo requested changes
@SergeBayet 

- Drag & drop the "Form" block (dynamic content section).
- Change the form action by setting the "Action" option to "Subscribe to
  Newsletter".
- Remove the mailing list field (note that: should that be authorized? The form cannot be sent without that field so... should not it be model-required?)
- Re-add it (+ Field -> Existing field: Mailing lists)
=> Labels are blank :shrug:

2024-04-24 07:41 UTC, SergeBayet commented
@qsm-odoo I fixed the bug concerning the blank labels and added the `modelRequired` constraint to the 'email' and 'list_ids' fields as in https://github.com/odoo/odoo/blob/16.0/addons/website/static/src/js/form_editor_registry.js#L32

2024-04-24 14:38 UTC, qsm-odoo approved these changes
Let's go with that, it's still not perfect as if I delete the field and re-add it, the numbers are back. But since we made the field required... the bug is technically hidden.

Would be easy enough to fix but I'd rather wait for the master owl refactor of this.

@robodoo r+

2024-04-24 16:27 UTC, closed without merging