[IMP] l10n_mx : Update master data with new Exento tax and fix the XM…
odoo/odoo pull request #160624
Opened 2024-04-05 07:21 UTC by igbe-odoo

Add a new tax, Exento, to the master data of the module l10n_mx, change the fiscal position 'Foreign Customer' and add a new tax group for Exento.

Add the Exento tax recognition for the XML reader for vendor bills.

task id : 3774996

2024-04-05 07:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160624).

2024-04-16 07:24 UTC, malb-odoo requested changes
Just minor change

2024-04-16 07:24 UTC, malb-odoo commented on addons/l10n_mx/data/template/account.tax-mx.csv
> -"tax13","19","0%","","VAT(0%)","0.0","percent","purchase","tax_group_iva_0","on_payment","cuenta119_01","","Tasa","","base","invoice","","+DIOT: 0%","","IVA(0%)"
Maybe we could leave the sequence like they were to keep the github history :smile:

2024-04-24 12:29 UTC, qdp-odoo commented
@robodoo r+

2024-04-26 19:10 UTC, qdp-odoo commented
@robodoo r+

2024-04-26 20:25 UTC, closed without merging