[FIX] survey: sharing right link when public survey
odoo/odoo pull request #160769
Opened 2024-04-05 15:43 UTC by Ephoniz

Issue: when we have our survey set to 'anyone with the link', which is esentially, public survey, when sharing through mail we will always share an invitation link specific for this user, and if we are not logged in we won't be able to try the survey, or if we are not the same user.

Steps to reproduce:

- Install survey and create a new one
- Make sure the settings are set to be accessible by anyone with the link
- Now send the invitation through mail
- Try to click on the button without the right account signed in, we are being redirected.

Solution: The solution to this might be very simple, just share the same link that we got if we just copy it when sending the mail, but only when our survey is set to public, otherwise, we still keep the same behavior.

opw-3792297

2024-04-05 15:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160769).

2024-04-09 08:16 UTC, nle-odoo approved these changes
looks good to me

2024-04-09 08:16 UTC, nle-odoo commented on addons/survey/models/survey_user_input.py
> +        if (self.survey_id.access_mode == 'public'):
```suggestion
        if self.survey_id.access_mode == 'public':
```

2024-04-09 08:16 UTC, nle-odoo commented on addons/survey/models/survey_user_input.py
> +            return self.survey_id.get_start_url();
no ; in python (it works but you should not to use the same style as rest of code)

```suggestion
            return self.survey_id.get_start_url()
```

2024-05-06 10:06 UTC, Julien00859 requested changes
I cannot reproduce the problem with the given steps. Here is a screencast showing my side https://youtu.be/Zp9fHLuJKv8

2024-05-06 10:56 UTC, Ephoniz commented
Hi @Julien00859 , thanks for having a look, I forgot to mention, the issue happens if you try to access the link when you are already logged in (with an account which is not the one we sent the invitation to.) also added a test.

2024-05-06 11:06 UTC, Julien00859 commented
> with an account which is not the one we sent the invitation to

Do we care about that? I mean, apart from us dev/support who are connected on several accounts on a daily basis to run tests. Is it something real people do?

2024-05-06 11:18 UTC, Ephoniz commented
> > with an account which is not the one we sent the invitation to
> 
> Do we care about that? I mean, apart from us dev/support who are connected on several accounts on a daily basis to run tests. Is it something real people do?

hmm maybe not, and actually having a double check on the ticket, seems that what functional support sent as bug, is not what the client was complaining about. The fix here is for what functional has reproduced as the issue. And the client complains are about not sending the actual survey link but a test link? Basically he wants to send '/survey/start/' instead of just '/survey' if that makes any sense.

2024-05-06 11:26 UTC, Ephoniz commented
@Julien00859 Thanks for your time and sorry, I'll check out what is really the problem, is there is one..

2024-05-06 11:35 UTC, Julien00859 commented
@Ephoniz no worry, it is part of the job :)

2024-05-23 11:48 UTC, closed without merging