[FIX] point_of_sale: order number not visible in the receipt
odoo/odoo pull request #160706
Opened 2024-04-05 13:07 UTC by shag-odoo

Before this commit :
Order number was not visible in the receipt as well as in the order history.

After this commit :
Order number is now visible in the receipt as well as in the order history.

task-3853157

2024-04-05 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160706).

2024-04-16 10:23 UTC, caburj requested changes
Can you update the other places that misuses `trackingNumber`? Check ticket screen.

2024-04-16 12:47 UTC, shag-odoo commented
Hello @caburj 
I have updated ```trackingNumber``` for ticket screen as well
Could you please have a look over it

Thank you for the suggestions and have a great day ahead :innocent:

2024-04-17 09:14 UTC, caburj commented
I believe there is another one in ticket_screen.js (point_of_sale module)

2024-04-17 13:46 UTC, caburj commented
robodoo r+

2024-04-17 18:48 UTC, closed without merging