[FIX] web: fix upload and set button in small view
odoo/odoo pull request #160913
Opened 2024-04-08 10:59 UTC by ppr-odoo

Steps to Reproduce:
   In enterprise open project->task
   Click on set cover image
   Open mobile view
Issue:
  Upload and Set button is squished.

Cause:
   Because the upload button is located within two span,
   its size cannot be determined.

Fix:
  Outside of the upload button, we removed two spans.

task-3761269

2024-04-08 11:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/160913).

2024-04-08 11:14 UTC, ppr-odoo commented
@pparidans  Can we replace the span with t in the stable version? [Ref](https://github.com/odoo/enterprise/pull/58407).

Can you review this PR whenever you have time?

2024-04-08 11:22 UTC, xavierbol commented
@ppr-odoo We cannot change the XML structure because a custom code could do a xpath and that xpath could be broken due to your changes.

2024-04-08 11:22 UTC, pparidans commented
> @pparidans Can we replace the span with t in the stable version? [Ref](https://github.com/odoo/enterprise/pull/58407).

`<t class="o_file_input">` :thinking: 

Globally, that sound like a risky move in a stable branch (specially as "old" as 16.0)...

2024-04-08 11:25 UTC, xavierbol commented
@pparidans 😁

2024-04-08 12:02 UTC, ppr-odoo commented
@pparidans any other way to fix it without changing XML structure?

Customization won't break if we hide the span and remove it in the master, but I don't think that's the right approach. If there's a better solution, please suggest it to me.

> @ppr-odoo We cannot change the XML structure because a custom code could do a xpath and that xpath could be broken due to your changes.
`      <t t-name="web.FileInput" owl="1">

        <t class="o_file_input" t-att-class="{ 'd-none': props.hidden }" aria-atomic="true">
            <t t-if="!props.hidden" class="o_file_input_trigger" t-on-click.prevent="onTriggerClicked">
                <t t-slot="default">
                    <button class="btn btn-primary">Choose File</button>
                </t>
            </t>
            <input type="file"
                name="ufile"
                class="o_input_file d-none"
                t-att-multiple="props.multiUpload"
                t-att-accept="props.acceptedFileExtensions"
                t-ref="file-input"
                t-on-change="onFileInputChange"
            />
        </t>
        <span class="o_file_input d-none" t-att-class="{ 'd-none': props.hidden }" aria-atomic="true">
            <span t-if="!props.hidden" class="o_file_input_trigger" t-on-click.prevent="onTriggerClicked">
                <t t-slot="default">
                    <button class="btn btn-primary">Choose File</button>
                </t>
            </span>
            <input type="file"
                name="ufile"
                class="o_input_file d-none"
                t-att-multiple="props.multiUpload"
                t-att-accept="props.acceptedFileExtensions"
                t-ref="file-input"
                t-on-change="onFileInputChange"
            />
        </span>
    </span>

2024-04-12 05:57 UTC, pparidans commented
> @pparidans any other way to fix it without changing XML structure?
> 
> Customization won't break if we hide the span and remove it in the master, but I don't think that's the right approach. 

Like I said above : `<t class="o_file_input">` :thinking: 
How would you put a class (or any other attribute) on a Text Node ?

2024-04-15 13:27 UTC, ppr-odoo commented
> > @pparidans any other way to fix it without changing XML structure?
> > Customization won't break if we hide the span and remove it in the master, but I don't think that's the right approach.
> 
> Like I said above : `<t class="o_file_input">` 🤔 How would you put a class (or any other attribute) on a Text Node ?

Can we modify the Choose File button's width?

Like- `<button class="btn btn-primary w-auto" t-on-click="uploadImage">`

2025-03-11 05:25 UTC, ppr-odoo commented
@pparidans Please check my last suggestion when you have time.

2025-05-06 16:04 UTC, xavierbol reviewed
Hello @ppr-odoo 

we could maybe do something like this: 

```diff
diff --git a/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml b/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
index d3af4926a47b..d7dbf29a44cf 100644
--- a/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
+++ b/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
@@ -27,7 +27,7 @@
                     onUpload.bind="onUpload"
                     resModel="props.record.resModel"
                     resId="props.record.resId">
-                        <button class="btn btn-primary" t-on-click="uploadImage">
+                        <button class="btn btn-primary w-auto" t-on-click="uploadImage">
                             Upload and Set
                         </button>
                 </FileInput>
```

instead of your changes.

What do you think?

2025-05-07 06:19 UTC, ppr-odoo commented
> Hello @ppr-odoo
> 
> we could maybe do something like this:
> 
> ```diff
> diff --git a/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml b/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
> index d3af4926a47b..d7dbf29a44cf 100644
> --- a/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
> +++ b/addons/web/static/src/views/kanban/kanban_cover_image_dialog.xml
> @@ -27,7 +27,7 @@
>                      onUpload.bind="onUpload"
>                      resModel="props.record.resModel"
>                      resId="props.record.resId">
> -                        <button class="btn btn-primary" t-on-click="uploadImage">
> +                        <button class="btn btn-primary w-auto" t-on-click="uploadImage">
>                              Upload and Set
>                          </button>
>                  </FileInput>
> ```
> 
> instead of your changes.
> 
> What do you think?

 here -https://github.com/odoo/odoo/pull/160913#issuecomment-2056857140

2025-05-07 08:48 UTC, xavierbol commented
Coucou @pparidans 

What do you think? 🙂 

Thanks in advance!

2025-05-12 10:42 UTC, pparidans requested changes
The solution is OK to me.

Please don't forget to change your commit message, as the "fix" mentioned doesn't reflect the actual implementation.

2025-05-13 08:34 UTC, pparidans approved these changes
Thanks for your work :+1: 
@robodoo r+

2025-05-13 11:01 UTC, robodoo commented
@ppr-odoo @pparidans staging failed: ci/runbot on e7b6021f5cb1a988b335f0aaec6f7cd07d5f7904 (view more at https://runbot.odoo.com/runbot/build/80252863)

2025-05-13 17:36 UTC, closed without merging