[FIX] payment: allow restricting on amount in /my/payment_method
odoo/odoo pull request #161021
Opened 2024-04-08 23:13 UTC by jorenvo

Setting a payment method currently bypasses the maximum_amount on the payment.provider. This provides methods that can be overwritten and handles a possible passed currency_id that is required by _get_compatible_providers() to restrict on amount.

opw-3858340

2024-04-08 23:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161021).

2024-04-09 07:17 UTC, AntoineVDV requested changes
Hi @jorenvo, I understand what you want to achieve, but I don't think it makes much sense at the payment engine level. The maximum amount field on providers is for *payment* amounts; validation operations' amounts might eventually be non-zero depending on the provider but not on the flow.

It seems to me that one can easily bypass this protection by creating the token on `/my/payment_method` and then paying the subscription. IMHO, we should not restrict the creation of tokens and, instead, make sure that a token cannot be used in a payment context where the amount exceeds that of its provider's maximum amount.

2024-04-09 21:30 UTC, jorenvo commented
I agree, I had mentioned it in the ticket:

> A second, related issue exists where somebody can select an already existing token. If the above approach is accepted I do something similar for that.

It seemed that maximum_amount was only used as a "soft" limit for display purposes. But your approach also works and is more robust. I guess it could be made even more strict by always checking during payment.transaction creation, but for now this is ok. Here's a simpler approach: https://github.com/odoo/enterprise/pull/60382

2024-04-10 09:20 UTC, AntoineVDV commented
It's soft because we don't want (for now) to block all future recurring payments if you remove one zero in your provider's maximum amount or something similar. For subscriptions, I think it makes sense to block the use of a token when the limit is exceeded without blocking the payment, should the token be manually assigned in the backend.

2024-04-17 08:35 UTC, closed without merging