[ADD] pos_loyalty: sell physical giftcard from terminal
odoo/odoo pull request #161234
Opened 2024-04-10 05:09 UTC by taal-odoo

- Add "Sell Physical Gift Card" option below the product name for the Gift Card product in pos store.
- Clicking the option opens a pop-up for entering the gift card number.
- Vendors can manually input the gift card number.
- Completing an order generates gift card with number in the backend.
- Allow adding amount to existing gift cards.

task-3647760

2024-04-10 05:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161234).

2024-05-09 06:29 UTC, paso-odoo requested changes

2024-05-09 06:29 UTC, paso-odoo commented on addons/pos_loyalty/static/src/utils/manage_giftcard_popup/manage_giftcard_popup.js
> +    }
```suggestion
```

2024-05-09 06:29 UTC, paso-odoo commented on addons/pos_loyalty/static/src/overrides/components/product_screen/order_summary/order_summary.js
> +                    { limit: 1 }
```suggestion
```

2024-05-10 06:22 UTC, paso-odoo requested changes

2024-05-10 06:22 UTC, paso-odoo commented on addons/pos_loyalty/static/src/utils/manage_giftcard_popup/manage_giftcard_popup.js
> +        this.state.amountError = "";
```suggestion
```

2024-06-07 06:54 UTC, davidmonnom commented on addons/pos_loyalty/static/src/overrides/components/product_screen/order_summary/order_summary.js
> +                );
Nice check

2024-06-07 06:59 UTC, davidmonnom requested changes
[Screencast from 07-06-24 08:51:14.webm](https://github.com/odoo/odoo/assets/63289800/9cd7deab-45c5-41e6-82b0-dc538b6047c7)

Here a little video, about an error, can you check if the user try to create two gift card with the same code ? And if yes block him.

Also, when refreshing the page, physical gift card informations are lost.

Good work!

2024-06-14 08:04 UTC, davidmonnom commented
Hey it looks good, but can you write some tests about this new feature ?

2024-06-18 11:32 UTC, taal-odoo commented
Hello @davidmonnom 
Thanks for the suggestions, I have pushed the changes.

2024-06-26 15:11 UTC, davidmonnom requested changes

2024-06-27 05:08 UTC, taal-odoo commented on addons/pos_loyalty/static/src/overrides/components/product_screen/order_summary/order_summary.js
> +                this.pos.data.syncDataWithIndexedDB(this.pos.data.records);
Yes, I thought so too, but it seems that changes in `uiState` do not trigger a sync to IndexedDB. 
Even before this commit, changes in `couponPointChanges` didn't call for a sync to IndexedDB. As we know the Gift Card order line gets stored. As a result, when the order line is added back after a refresh, a new `couponPointChanges` was created.

Do let me know if I have misunderstood here. Thanks.

2024-08-12 10:16 UTC, paan-odoo commented
Hello @davidmonnom 
Changes are done.
Thanks

2024-08-13 09:01 UTC, davidmonnom requested changes
Hey lgtm, just a last point, can you verify the giftcard price when changing line price after adding a giftcard ?

2024-08-13 12:40 UTC, davidmonnom approved these changes

2024-08-20 08:40 UTC, caburj commented
robodoo r+

2024-08-21 12:28 UTC, closed without merging