[FIX] base_vat: greek vat number format
odoo/odoo pull request #161278
Opened 2024-04-10 10:32 UTC by guva-odoo

According to https://www.easytax.co/en/countries/greece
the vat number format for Greece is EL123456789
instead of GR12345670

opw-3845662

2024-04-10 10:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161278).

2024-04-15 07:27 UTC, gawa-odoo requested changes
Hello! 
Does not seem to be enough. 
With `base_vat` installed (and account_accountant), I still can't create a Greek partner with a VAT number EL123456789

2024-04-15 08:04 UTC, guva-odoo commented
> Hello! Does not seem to be enough. With `base_vat` installed (and account_accountant), I still can't create a Greek partner with a VAT number EL123456789

Indeed, this doesn't pass the vat check function, I'll look into it

2024-04-15 09:40 UTC, gawa-odoo commented
Can you just adapt the commit message (to remove the mention of the wrong VAT number)?

2024-04-15 12:29 UTC, closed without merging