[FIX] website_payment: fix donation snippet prefilled Options
odoo/odoo pull request #161431
Opened 2024-04-11 08:20 UTC by bvr-odoo

Steps to Reproduce :

- Install e-commerce.
- Drag and drop donation snippet.
- Click inside the snippet.
- Now try to toggle off "Pre-filled" option.
- Traceback Occurs.

This bug is due to the fact that since this commit [1], templates have been added to the OWL app.

With OWL, a "t-foreach" in a template can no longer loop over an empty array. This causes an error. This was the case when the "Pre-filled" option of the donation snippet was set to "off".

[1]: https://github.com/odoo/odoo/commit/4703e4a2efa9213979307e4d3dedeedc61ad0fc3

task-3859207

2024-04-11 08:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161431).

2024-04-11 14:44 UTC, qsm-odoo commented
@robodoo delegate=sobo-odoo 
@sobo-odoo

2024-04-15 15:36 UTC, sobo-odoo requested changes
Here is my review :slightly_smiling_face: Your fix works fine :+1: 

I only have some comments about the commit message :wink:

2024-04-16 07:54 UTC, bvr-odoo commented on addons/website_payment/static/src/snippets/s_donation/options.js
>                  this.$target.find('.s_donation_donate_btn').before(sliderTemplate);
@sobo-odoo thanks, I made the change

2024-04-16 12:06 UTC, sobo-odoo approved these changes
Alright, let's r+ ! :wink: 

@robodoo r+

2024-04-16 14:12 UTC, closed without merging