[FIX] hr_holidays: save already_accrued from allocation form views
odoo/odoo pull request #161508
Opened 2024-04-11 13:51 UTC by goffauxs

### Current Issue:
When we have an accrual plan where the accrued time is allocated at the start of the accrual period and we set the allocation start time in the past, the plan will be processed but `already_accrued` will not be saved.

### Example:
 - We have an accrual plan that allocates 1 day per month at the start of the accrual period. Milestone reached 0 days after allocation start.
 - We set the start date of the allocation to 2024-01-01, the current date is 2024-03-15. The number of days are calculated to 3.00 (jan, feb, mar).
 - We save the record, `already_accrued` is not saved (defaults to false)
 - When the scheduled action runs (2024-04-01), it will allocate 2 days instead of 1

### Solution:
This commit fixes this behavior by adding the `already_accrued` field to the form view so that it is saved when the record is created.

opw-3851320

2024-04-11 13:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161508).

2024-04-22 09:01 UTC, Bertrand2 requested changes
Thanks for the fix, it seems like the best solution :+1:
Could you also add a test so that we ensure it stays fixed in the future as well?

2024-04-23 12:56 UTC, Bertrand2 approved these changes

2024-04-23 12:57 UTC, Bertrand2 commented
robodoo r+

2024-04-25 07:48 UTC, Bertrand2 commented
@goffauxs could you rebase your branch since it has a failed build?
Thanks!

2024-04-25 08:25 UTC, goffauxs commented
Whoops, I did something wrong. 😨

2024-04-29 07:34 UTC, Bertrand2 commented
robodoo r+

2024-04-29 09:51 UTC, closed without merging