[16.0][REF] purchase_stock
odoo/odoo pull request #161916
Opened 2024-04-15 13:41 UTC by AungKoKoLin1997

This PR refactors previously hard-coded logic for extracting grouping keys within the purchase order management process into two separate, reusable methods: `_get_po_line_grouping_key` and `_get_groupby_po_line_key`. The first method, `_get_po_line_grouping_key`, is designed to generate keys for grouping purchase order lines, The second, `_get_groupby_po_line_key`, extracts keys from procurement objects to match with these grouped lines, ensuring consistency across the procurement-to-purchase order workflow.This change improves code readability and maintainability by centralizing key generation, facilitating easier updates and extensions to the grouping logic.

This refactoring will be used by OCA module https://github.com/OCA/account-analytic/pull/637

@qrtl QT4346

2024-04-15 13:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161916).

2024-05-03 11:02 UTC, Sehnde requested changes
Hello,
We are not fundamentally against this PR since it doesn't break/remove anything or change function signatures. However, we'd like an explanation as to why you need to subdivide the PO lines depending on analytic distribution in you `procurement_mto_analytic`.

So please consider the following questions:
- what is the plus-value of this subdivision?
- is it possible to do without the need to create new function to overwrite?
- is it possible for a mismatch to happen between `po_line.analytic_distribution` and `procurement.values.get("analytic_distribution")` to happen? I.e. a po_line has an analytic_distribution but the procurement values don't (or vice-versa) and the line is not used later when it should.

Finally, here are some corrections to add:

2024-05-03 11:02 UTC, Sehnde commented on addons/purchase_stock/models/stock_rule.py
> +    def _get_po_line_grouping_key(self, po_line):
Please use the same signature in your module: `def _get_po_line_grouping_key(self, line):`
`po_line` is the better choice

2024-05-03 11:02 UTC, Sehnde commented on addons/purchase_stock/models/stock_rule.py
> +            grouped_po_lines = groupby(po.order_line.filtered(lambda l: not l.display_type and l.product_uom == l.product_id.uom_po_id), key=self._get_po_line_grouping_key)
You still need to use `lambda` to send only 1 line at a time in the function
```suggestion
            grouped_po_lines = groupby(po.order_line.filtered(lambda l: not l.display_type and l.product_uom == l.product_id.uom_po_id), key=lambda l: self._get_po_line_grouping_key(l))
```

2024-05-09 04:43 UTC, AungKoKoLin1997 commented
> * what is the plus-value of this subdivision?

The benefit is if the user wants to keep the different analytic_distribution under same order, this refactoring must be needed.
We are planning to add the options in `procurment_mto_analytic` to allow the users can choose keeping same analytic_distribution or different analytic_distribution po lines. So, this refactoring will be needed.



> * is it possible to do without the need to create new functions to overwrite?

I think the only possible way is complete override of existing function if we don't create new refactored functions. I don't think this is a good way.



> * is it possible for a mismatch to happen between `po_line.analytic_distribution` and `procurement.values.get("analytic_distribution")` to happen? I.e. a po_line has an analytic_distribution but the procurement values don't (or vice-versa) and the line is not used later when it should.

No. It is not if the user doesn't manually update the `po_line.analytic_distribution`.

2024-05-23 09:37 UTC, Sehnde requested changes
Sorry for the delay, this is freeze period.
Anyway, this looks ok. Please do the corrections indicated here.

2024-05-23 09:37 UTC, Sehnde commented on addons/purchase_stock/models/stock_rule.py
> +    def _get_po_line_grouping_key(self, po_line):
You also need to use `@api.model` since this function does not depend on the recordset of `self`

2024-05-23 09:37 UTC, Sehnde commented on addons/purchase_stock/models/stock_rule.py
> +        This key will be used to group order lines by product.
Please indicate that this method exists to be overridden, otherwise someone could decide to remove it later.

2024-05-23 09:38 UTC, Sehnde commented on addons/purchase_stock/models/stock_rule.py
> +            grouped_po_lines = groupby(po.order_line.filtered(lambda l: not l.display_type and l.product_uom == l.product_id.uom_po_id), key=self._get_po_line_grouping_key)
nevermind, that works

2024-05-23 11:40 UTC, Sehnde commented
another thing: please change the commit title to something like this: `[REF] purchase_stock: refactor _run_buy grouping key`
You can find our guidelines here: https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#commit-message-structure

2024-05-24 04:05 UTC, AungKoKoLin1997 commented
@Sehnde Sorry. I didn't notice `[_find_candidate](https://github.com/odoo/odoo/blob/fe35d40d926b161dfe9b758de96f9a1b1253b2e3/addons/purchase_stock/models/purchase.py#L620)`. We can extend this function to filter self with analytic_distribution.
So, we don't need this refactoring.

2024-05-24 05:24 UTC, closed without merging