[FIX] account: Remove `invoice_pdf_report_id` on reset to draft
odoo/odoo pull request #161991
Opened 2024-04-15 20:10 UTC by iada-odoo

Current Behavior:
`is_move_sent` is not updated if there is an existing `invoice_pdf_report_id`.

Purpose of this PR:
Remove the `invoice_pdf_report_id` when resetting invoice to draft so that when the invoice is sent again (using the Send and Print wizard), `is_move_sent` is updated.

Steps to Reproduce on Runbot:
1) Create and Send and Print invoice. (`is_move_sent` is set to True) 
2) Reset invoice to draft. (`is_move_sent` is set to False) 
3) Confirm and resend invoice using Send and Print wizard. (`is_move_sent` remains False, expected to be changed to True)

Notes:
This PR #116698 added a _compute in Odoo 16, however it was removed in Odoo 17 with this PR #125392. `is_move_sent` is not updated when on the second Send and Print because of the existing `invoice_pdf_report_id` (generated and linked during the first Send and Print).

opw-3849109

2024-04-15 20:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/161991).

2024-04-19 11:49 UTC, JulienAlardot commented
Hello, thanks for this PR but that is not what we want.
The reason is_move_sent isn't reset to False is because we cannot know if it was sent through a download + print or download + mail sent on another channel. That is why it is always considered as sent once the pdf is generated. Even if we re-generate it afterhand
The solution for that ticket customer could be to filter on `invoice_pdf_report_id` and safely delete the ones they know are not sent if needed

2024-04-19 18:50 UTC, iada-odoo commented
> Hello, thanks for this PR but that is not what we want. The reason is_move_sent isn't reset to False is because we cannot know if it was sent through a download + print or download + mail sent on another channel. That is why it is always considered as sent once the pdf is generated. Even if we re-generate it afterhand The solution for that ticket customer could be to filter on `invoice_pdf_report_id` and safely delete the ones they know are not sent if needed

Hello @JulienAlardot thank you for your review and comments. 
Currently, the is_move_sent is set to False when the account move is set to draft (after being posted, with pdf generated). 
If the original pdf is never removed then is_move_sent is not set to True even if regenerating a new pdf. The workflow is outlined below.

First create an invoice, send and print
Reset to draft, change some fields
Resend using send and print. 

If the original pdf is not removed, the new one is not regenerated (and is_move_sent is not updated). 
Would it then be more appropriate to keep is_move_sent = True?

2024-04-25 18:07 UTC, iada-odoo commented
> Hello, thanks for this PR but that is not what we want. The reason is_move_sent isn't reset to False is because we cannot know if it was sent through a download + print or download + mail sent on another channel. That is why it is always considered as sent once the pdf is generated. Even if we re-generate it afterhand The solution for that ticket customer could be to filter on `invoice_pdf_report_id` and safely delete the ones they know are not sent if needed

Hello @JulienAlardot, I have made changes so that `is_move_sent` is not set to False when the move is reset to draft. 
This will then confirm that if a move is sent once, it will be deemed as always sent regardless of the state of the move or regeneration of PDFs.

2024-05-16 07:43 UTC, JulienAlardot commented
After further discussion with PO, the fix is what we want, but we would need it in 16.3 (send&Print rework)
Could you retarget it?

2024-05-16 07:46 UTC, JulienAlardot requested changes

2024-05-16 07:46 UTC, JulienAlardot commented on addons/account/models/account_move.py
> +        self.write({'state': 'draft'})
```suggestion
        self.state = 'draft'
```
Since there's only one field left :p

2024-05-16 07:46 UTC, JulienAlardot commented on addons/account/tests/test_account_move_send.py
> +        self.assertTrue(invoice.is_move_sent)
Updating the test would be nice, something like
- Posting a move
- Testing the state
- Send & Print
- Testing the state
- Reset to draft
- Testing the state

could work

2024-05-17 12:19 UTC, JulienAlardot requested changes
Could you update the commit message `Notes:` section? It still mentions the v17.0. It should be mentioning https://github.com/odoo/odoo/commit/ef9e266c86cbc4abc24e2a6f597a2014e6e3439a 16.3 commit

2024-06-11 12:12 UTC, JulienAlardot approved these changes
LGTM @epictete

2024-06-21 08:42 UTC, robodoo commented
@iada-odoo the target branch 'saas-16.3' has been disabled, you may want to close this PR.

2024-06-25 13:51 UTC, JulienAlardot commented
Specs changed, will be handlend in [#170713](https://github.com/odoo/odoo/pull/170713)
Sorry :c

2024-06-25 13:51 UTC, closed without merging