[IMP] website_hr_recruitment: add website menu jobs
odoo/odoo pull request #162015
Opened 2024-04-16 07:36 UTC by arpi-odoo

This adds a menu to published jobs in the navigation bar of the website.

Task: 3869518

2024-04-16 07:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162015).

2024-04-17 07:45 UTC, Flotchet commented on addons/website_hr_recruitment/data/config_data.xml
> +            <field name="sequence" type="int">59</field>
```suggestion
            <field name="sequence">59</field>
```

The sequence is already an int by default

2024-04-17 07:46 UTC, Flotchet requested changes
Just a little comment otherwhise lgtm

2024-04-26 13:38 UTC, Bertrand2 reviewed
![monokuma-verdict_1](https://github.com/odoo/odoo/assets/71561613/c4f01e59-6e1f-4c03-b9f7-5c65a6677b8c)

2024-04-26 13:39 UTC, robodoo commented
I'm sorry, @Bertrand2: draft PRs can not be approved.

2024-04-26 14:34 UTC, Bertrand2 commented
robodoo r+

2024-04-26 19:09 UTC, closed without merging