[FIX] hr_homeworking_calendar: fix action path (js)
odoo/odoo pull request #162014
Opened 2024-04-16 07:32 UTC by mepe-odoo

In this task-3642327, the split between
hr_homeworking and calendar was introduced.
The action's path in js was forgotten.

task-386625

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-16 07:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162014).

2024-05-15 13:41 UTC, Flotchet requested changes
thx for the js :baguette_bread: 
ze test related to your code doesn't seems to be ok  :monocle_face:

2024-05-15 13:41 UTC, Flotchet commented on addons/hr_homeworking_calendar/wizard/homework_location_wizard.xml
> +                    <field name="user_can_edit" invisible="1"/>
seems not usefull given the last changes of the framework
https://github.com/odoo/odoo/pull/137031

2024-06-04 07:26 UTC, closed without merging

2024-06-04 07:27 UTC, mepe-odoo commented
This PR will re-target to saas-17.3