[IMP] point_of_sale: ui/ux improvement
odoo/odoo pull request #162066
Opened 2024-04-16 12:43 UTC by paan-odoo

Before this commit:
==========
- There was no placeholder in the products list view for POS.
- The email notice message on an email sent was "Email sent" in the Receipt screen.

After this commit:
==========
- There is a placeholder in the products list view for POS.
- The email notice message on an email sent is "Email is successfully sent." in the Receipt screen.

task-3356235

2024-04-18 09:51 UTC, paso-odoo requested changes

2024-04-18 09:51 UTC, paso-odoo commented on addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.js
> +                    message: _t("Email is successfully sent."),
```suggestion
                    message: _t("Email is sent successfully."),
```

Both sentences are grammatically correct, but "Email is sent successfully." is more commonly used in formal contexts.
confirm with PO too.

2024-05-22 05:45 UTC, paan-odoo commented on addons/point_of_sale/views/product_view.xml
> +                Define the product and it's category for POS retail and restaurant
Hello @caburj
Changes are done. Can You please check again?
Thanks.

2024-05-22 07:46 UTC, caburj approved these changes
robodoo r+

2024-05-22 17:56 UTC, closed without merging