[ADD] point_of_sale: simplify List view
odoo/odoo pull request #162010
Opened 2024-04-16 06:55 UTC by sjai-odoo

This PR adds the closing date and balance fields to the list view of the pos_config. These fields were already displayed in the kanban view, but were missing from the list view, causing inconsistency between the two views.

task- 3647820

2024-04-16 06:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162010).

2024-04-24 06:13 UTC, paso-odoo requested changes

2024-04-24 06:13 UTC, paso-odoo commented on addons/point_of_sale/views/pos_config_view.xml
> +                <field name="last_session_closing_cash" string="Balance" widget="monetary"/>
```suggestion
                <field name="currency_id" column_invisible="True"/>
                <field name="last_session_closing_cash" widget="monetary" string="Balance"/>
```

2024-05-21 06:27 UTC, adgu-odoo approved these changes

2024-05-21 06:27 UTC, adgu-odoo commented
@robodoo r+

2024-05-21 08:49 UTC, closed without merging