[FIX] website_sale: use separate contact for pick-up point
odoo/odoo pull request #162399
Opened 2024-04-18 11:26 UTC by khah-odoo

Steps to reproduce:
1. Configure Sendcloud shipping with pick-up locations
2. Go to website and use the shipping method and select a pick-up location
3. Try step 2 again, using the same pick-up point but with a different name
4. Checking the delivery address of the second customer, we see the name of the first customer is used

The problem is that if a pick-up location is already saved, we re-use the same contact for the delivery address. This commit ensures separate contacts are created for different customers.

opw-3853716

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-18 11:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162399).

2024-04-19 06:35 UTC, Dotni approved these changes
Hello @khah-odoo :wave:

The code looks good to me, well done!

@amoyaux can you take a look as well?

2024-04-19 08:10 UTC, vchu-odoo requested changes
Hello,

Thank you for your work!

Here is one suggestion for improvement, wdyt?

2024-04-19 08:33 UTC, Dotni commented on addons/website_sale/models/sale_order.py
> +                                                                ('parent_id', '=', order.partner_id.id)], limit=1)
Good catch!

2024-04-19 09:17 UTC, vchu-odoo approved these changes
LGTM :+1:

2024-04-19 09:23 UTC, Feyensv reviewed
Is the bug only there from 17.0 ? If so, why?

2024-04-23 08:41 UTC, closed without merging

2024-04-23 09:25 UTC, vchu-odoo commented
There is no need to close this PR and create a new one for each version. You could have rebased this one and retargeted to 15.0.  The fw-bot will take care to propagate your changes to all versions up to master.