[IMP] website_sale: Enhance category header & footer
odoo/odoo pull request #162394
Opened 2024-04-18 10:42 UTC by mathysPaul

Allows building blocks to be added directly after the shared website header and into the footer of specific eCommerce category pages.

This update allows each category page to have unique header and footer elements.

This feature ensures category-specific customization:
- Building blocks can be placed in the category-specific footer.
- Blocks can be added to the header right after the website-wide header.
- Visibility of these blocks is restricted to their respective category pages.
- Ensures Headers & footers are not shared between parent and child categories.

task-3747565

2024-04-18 10:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162394).

2024-05-13 12:26 UTC, vchu-odoo requested changes
Hey, thanks for your work!
LGTM :+1: 

I was not sure about the position of the footer and confirmed with @paju-odoo that it should be after the products (same manner as the header) like in the screenshot. 
![image](https://github.com/odoo/odoo/assets/127864697/a230366b-3031-4509-b620-6fb534d61e2d)

2024-05-13 13:05 UTC, paju-odoo commented
> Hey, thanks for your work! LGTM 👍
> 
> I was not sure about the position of the footer and confirmed with @paju-odoo that it should be after the products (same manner as the header) like in the screenshot. ![image](https://private-user-images.githubusercontent.com/127864697/330054543-a230366b-3031-4509-b620-6fb534d61e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDU3NzMsIm5iZiI6MTcxNTYwNTQ3MywicGF0aCI6Ii8xMjc4NjQ2OTcvMzMwMDU0NTQzLWEyMzAzNjZiLTMwMzEtNDUwOS1iNjIwLTZmYjUzNGQ2MWUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMzA0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWZmY2M3YmI2ZTU4ZDU1MjY4ZmNhZmFjYzc3ZDYwYWZmMjhiOGQ3NWZjMDJmMTk1MDFmOGNkODA4NmEyYzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q_0IE2SR7_nkMKTNFi0pO2qhhsq8oA9lozcnK6cqkpg)

Also please note that it should be placed after the pagination if there are several pages for an e-commerce category :)
cc @mathysPaul @vchu-odoo

2024-05-17 13:37 UTC, vchu-odoo approved these changes
Great work!
LGTM :+1: 

Just one small comment.

2024-05-17 13:37 UTC, vchu-odoo commented on addons/website_sale/models/product_public_category.py
> +
```suggestion
```

2024-09-19 16:47 UTC, chevalierv commented
Changes done in https://github.com/odoo/odoo/pull/179479

2024-09-19 16:47 UTC, closed without merging