[FIX] pos_sale: duplicate down paytment lines
odoo/odoo pull request #162772
Opened 2024-04-22 07:05 UTC by jipr-odoo

Before this commit:
===================
Duplicate down payment lines were being generated for each imported quotation order.

After this commit:
===================
Prevent the creation of duplicate down payment lines.

task - 3877380

2024-04-22 07:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/162772).

2024-04-29 09:58 UTC, paso-odoo requested changes

2024-04-29 09:58 UTC, paso-odoo commented on addons/pos_sale/models/pos_order.py
> +                # delete sal_order_lines related to deleted pos_order_lines.
```suggestion
                # delete sale_order_lines related to deleted pos_order_lines.
```

2024-05-27 06:51 UTC, paso-odoo approved these changes

2024-05-29 10:51 UTC, caburj commented
robodoo r+

2024-05-29 13:19 UTC, closed without merging