[FIX] web: prevent error while changing the language
odoo/odoo pull request #163087
Opened 2024-04-24 04:58 UTC by aamo-odoo

An error occurred when attempting to change the language in my profile.

Steps to reproduce:
- Install the ``sale_management`` and ``hr`` module
- Settings / Translations / Languages
- Activate any Language
- Open Sales / Click New / Click the profile icon / click ``My Profile``
- Change the language

Traceback: ValueError
Expected singleton: mrp.production('n', 'e', 'w')

In line[1] we are getting the record ID as ('n', 'e', 'w') while trying to change the language.

This commit resolves the mentioned issue by checking the type of record ID

[1] : https://github.com/odoo/odoo/blob/853bd97eda1f4eca5f9f63ef1c5909fddaa98d27/addons/web/controllers/action.py#L67

sentry - 5135218331

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-24 04:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163087).

2024-04-24 10:56 UTC, Julien00859 requested changes
@ryv-odoo some NewId bug, what's the best course of action here (no pun intended)?

2024-04-24 12:38 UTC, aamo-odoo commented
Hello @Julien00859 
The requested changes have been made.
Please have a look :slightly_smiling_face:

2024-04-25 08:31 UTC, ryv-odoo commented
Hello, IMO, the problem comes from the sender; resId should be an integer or not present (meaning that we want to create a new record). Then, I think it is preferable to change that in the web client side. What do you think, @jpp-odoo ?

2024-04-25 08:50 UTC, jpp-odoo commented
Hello,

You can simply reproduce the issue, installing hr, create a new employee, open profile and refresh the browser.
Here the issue is not that "new" is considered as a resId by the load breadcrumb, the issue is that we allow to quit a form view with a new record without saving it, or without discarding the changes. ("new" should never be found in the middle of the url).

The issue is probably in the action_service.js, we are going to check to fix it.

2024-04-26 10:28 UTC, jpp-odoo commented
It seems that we have many cases in which a "new" could be found in the middle of the URL (For instance, after an explicit doAction in a form view).

As "new" being the only non-numeric possible value for an id in the url the framework will generate, it can also put it by hand on the url.

For those reasons, I think it should be accepted on the `load_breadcrumbs` function. But it shouldn't be ignored, for me, it should return a "New" display name, so I would do something like this :

```diff
diff --git a/addons/web/controllers/action.py b/addons/web/controllers/action.py
index 912052ac12c4..afc01c9babab 100644
--- a/addons/web/controllers/action.py
+++ b/addons/web/controllers/action.py
@@ -49,6 +49,9 @@ class Action(Controller):
         display_names = []
         for idx, action in enumerate(actions):
             record_id = action.get('resId')
+            if record_id == 'new':
+                display_names.append(_("New"))
+                continue
             try:
                 if action.get('action'):
                     act = self.load(action.get('action'))
```

2024-04-26 11:50 UTC, jpp-odoo commented
@aamo-odoo 
Sorry I made a mistake,
We still need to check if the action exists, to avoid having in the breadcrumb/url a non-existing action that will generate an error if we click on it. So the code should be here :

```diff
--- a/addons/web/controllers/action.py
+++ b/addons/web/controllers/action.py
@@ -65,7 +65,9 @@ class Action(Controller):
                         continue
                     if record_id:
                         # some actions may not have a res_model (e.g. a client action)
-                        if act['res_model']:
+                        if record_id == 'new':
+                            display_names.append(_("New"))
+                        elif act['res_model']:
                             display_names.append(request.env[act['res_model']].browse(record_id).display_name)
                         else:
                             display_names.append(act['display_name'])
```

2024-04-26 12:52 UTC, ryv-odoo commented
Thanks @aamo-odoo and @jpp-odoo for your help.
@robodoo r+

2024-04-26 15:32 UTC, closed without merging