Master invoicing improvements thbe
odoo/odoo pull request #163014
Opened 2024-04-23 14:47 UTC by Megaaaaaa

*: account, base_import, l10n_be, sale_expense, test_base_automation, web, web_editor

---

This PR contains multiple commit which all serve a common purpose which is making invoicing clearer and more friendly to the user.

The commits that compose this PR are four. A short explanation for each of them will be provided here but more information can be found in their respective commit messages. (Some commits are IMP which are the actual modifications and some of them are accompanied by a FIX commit which modifies the tests linked to it)

1. Enhancing the UI by adding, moving and removing some fields and displayed text. This is mostly cosmetic.
2. Enhancing the UX by modifying the behavior of already selected records in many-to-many tags fields (like taxes for example)
3. Renaming the search more option for taxes so it is clearer the user can have more information before chosing.
4. Modifying the Search More option in the many2many dropdown for taxes to improve clarity.

---

Enterprise PR:
task-3642419

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-23 14:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163014).

2024-04-24 06:21 UTC, FlorianGilbert requested changes
Hello

There is a typo in your first commit:

> The width of certain columns which were **preivously** using default values have
`preivously` should be `previously`

Another thing in your second commit message:

> A **traduction** test on the tax description has been adapted.
`translation` instead of `traduction`
Btw, concerning this commit, I will squash it with the first one because it's fixing tests that are broken by the first commit so as we don't want to merge a broken commit, let's squash it together.

In the fourth commit, we explain the label change but not the change on the search, could you please explain in few word why we're doing that, thank you

Another typo in the fifth commit:

> The way the tax scope is shown in the tax many2many dropdown **meny** is not clear
and can be improved.

`menu` instead of `meny` ?

Same for the last commit concerning the squash, as you're fixing tests there, please squash this commit with the broken commit, thank you

2024-04-24 06:21 UTC, FlorianGilbert commented on addons/account/static/src/components/tax_autocomplete/tax_autocomplete.scss
> +}
Empty line at the end of the file

2024-04-24 06:21 UTC, FlorianGilbert commented on addons/web/static/src/views/fields/relational_utils.js
> +        const records = await searchPromise.promise;
Why don't we do that:

```suggestion
        this.lastProm = this.abortableSearch(request);
        const records = await this.lastProm.promise;
```

2024-04-24 07:20 UTC, Megaaaaaa commented on addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
> +        ) {
This was more a safety net than something actually required. It is true it makes only very little sense for something like that so I will simply remove it.

2024-04-30 06:42 UTC, aab-odoo commented on addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
> +                this.props.record.data[this.props.name].records.map((record) =>
there should be no duplicate in this.props.record.data[this.props.name].records (the model is the source of truth, it should be correct)

2024-04-30 06:42 UTC, aab-odoo commented on addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
> +        if (tagRecord) {
I'm not sure to understand why/how you could remove a tag that isn't in the relation

2024-04-30 06:42 UTC, aab-odoo commented on addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
> +            recordlist = recordlist.filter((element) => {
besides the removal of the domain (diff in getDomain), this is the only other diff that should be there, I think (i.e. you don't filter out records that are already in the relation, and when the user clicks on them, you make sur we don't add them a second time to the relation). The remaining diff shouldn't exist (or I'm missing something)

2024-04-30 06:42 UTC, aab-odoo commented on addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
> +            recordlist = recordlist.filter((element) => {
Also, the new behavior should be tested (I'm surprised no tests fail, actually)

2024-04-30 14:43 UTC, aab-odoo commented on addons/account/tests/test_tour.py
> +        self.start_tour("/web", 'account_tax_widget_tour', login="admin")
I meant unit tests in web/.

2024-05-02 14:38 UTC, Megaaaaaa commented
Hello @odoo/rd-security :wave: 

Could you review this PR please ?

A previously Char field is changed for an Html field and so the tests which used to look for a simple text string now have to look for a Markup text.

No input is ever used inside the new Markup() methods so i believe it makes them safe.

Thank you in advance :pray:

2024-05-03 06:59 UTC, aab-odoo approved these changes
Besides the remaining comment, I approve the change on many2many tags field

2024-05-03 06:59 UTC, aab-odoo commented on addons/web/static/tests/legacy/views/fields/many2many_tags_avatar_field_tests.js
> +        assert.strictEqual(popover.querySelectorAll(".o_tag").length, 2, "Should have 2 tags");
You change the semantics of this test, I would rather click on the third (?) element (the one that was first before your change), to keep the exact same semantics.

2024-05-06 11:18 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-05-06 11:29 UTC, FlorianGilbert commented
@robodoo rebase-ff

2024-05-06 11:30 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-05-06 15:28 UTC, closed without merging

2024-08-14 13:55 UTC, seb-odoo commented
Hello, what was the reasoning to show already selected tags on m2m autocomplete?

I don't know why it would be useful in accounting, but for me this is a big annoyance, especially in project.

Could it be made as a field specific option instead, only for those that need this strange behavior?

If a tag is already set, I don't want to see it again or set it again (as it has no effect, as stated in the commit), so it doesn't need to suggest it. It's confusing and making search results worse, as we only display few of them, the few available spots are wasted. This forces users to use more specific search term to find relevant results, whereas very few chars could be used when already selected tags were filtered out.

And to avoid confusion and clicks that do nothing, if we _really_ must keep them, it should at least display something next to the value to tell it was already selected, and even possibly "disable" the line.

2024-08-19 07:54 UTC, chklop commented
@seb-odoo This discussion has already sailed, please see the discussion in https://www.odoo.com/odoo/project.task/3919307