[IMP] point_of_sale: adding a custom page on iot box's nginx server to catch 502 errors
odoo/odoo pull request #163137
Opened 2024-04-24 11:35 UTC by n-kmron

[IMP] point_of_sale: adding a custom page on iot box's nginx server to catch 502 errors

Current behavior:
When the IoT box's python version is not compatible with the Odoo's one, Odoo server crash and let nginx generate a 502 error with no information for the user

After this commit:
When the error is triggered, a custom page will be shown to the user

`502.html` is the page who will be displayed to the user

`default` is the config of nginx, which is responsible to link the html page with error triggered

opw-3853501

2024-04-24 11:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163137).

2024-04-26 12:07 UTC, lse-odoo requested changes
Overall very good for a first PR :) 

However, the main text is not enough in my opinion. Error 502 can happened in other scenario than having odoo that didn't start at all. It can happen for example during an update is Odoo is temporarily down the time for the update and restart.

+ the error 502 should be displayed somewhere to inform the user

I think it would be wiser to suggest to wait and refresh before re flashing. Maybe something like:
> IoT Box is down 
> Error 502: Bad Gateway
> 
> The IoT Box received the request but was not able to handle it.
> You can try to refresh the page to see if the request can now be handled
>
> If the error persist for more than 2 minutes:
> 1. Force restart the IoT box by plug off the IoT power supply then on again
> 2. Re-flash the SD card of the IoT box, see: https://www.odoo.com/documentation/17.0/applications/general/iot/config/updating_iot.html#flashing-the-sd-card-on-iot-box

2024-04-26 12:38 UTC, n-kmron commented
Thank you for the review, here you are a preview of the render 
<img width="1468" alt="Screenshot 2024-04-26 at 14 33 53" src="https://github.com/odoo/odoo/assets/124042535/5eb06d31-1c97-4f72-8db2-8ce2bf8f9c1c">

2024-04-30 14:17 UTC, n-kmron commented on addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
> +        root /var/www/html;
After more research, 

`/var/www/html` is the configured location for the default server's document root as configured in /etc/nginx/sites-enabled/default.

Basically nginx uses this by default, and this is what is done in the Odoo config file for nginx on port 80 (`odoo/addons/point_of_sale/tools/posbox/overwrite_after_init/etc /nginx/sites-enabled/default`)

But of course, it is customisable if we wish to use another location.

[source 1](https://serverfault.com/questions/718449/default-directory-for-nginx)
[source 2](https://medium.com/@grpeto/how-to-change-the-index-html-in-nginx-a-beginners-expedition-0d80047cb58a)

2024-05-14 11:37 UTC, qle-odoo approved these changes

2024-05-14 17:58 UTC, lse-odoo approved these changes

2024-05-15 11:31 UTC, qle-odoo approved these changes
Ideally this PR should have been made in V17.0 because the changes are made in override_after_init and therefore only applied as part of a new build.
However this has no consequences, I am just making the observation

@robodoo r+

2024-05-15 12:58 UTC, closed without merging