[REF] convert to hoot
odoo/odoo pull request #163158
Opened 2024-04-24 13:22 UTC by pipu-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-24 13:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163158).

2024-06-04 16:24 UTC, Arcasias requested changes

2024-06-05 11:24 UTC, pipu-odoo commented
@Arcasias Thank you very much for you review and comments ! Bismi

2024-06-05 13:07 UTC, Arcasias reviewed
Sorry, missed one :weary:

2024-06-06 14:52 UTC, pipu-odoo commented on addons/web/static/tests/views/pivot_view.test.js
> +    onRpc(({ method }) => {
thx

2024-06-07 07:29 UTC, pipu-odoo commented on addons/web/static/tests/views/pivot_view.test.js
> +        noContentHelp: markup(`<p class="abc">click to add a foo</p>`),
The string in the function is a constant. What's more, the function is used in a unit test. The risk is zero.

2024-06-07 07:29 UTC, pipu-odoo commented on addons/web/static/tests/views/pivot_view.test.js
> +        noContentHelp: markup('<p class="abc">click to add a foo</p>'),
@odoo/rd-security The string in the function is a constant. What's more, the function is used in a unit test. The risk is zero.

2024-06-07 07:29 UTC, pipu-odoo commented on addons/web/static/tests/views/pivot_view.test.js
> +        noContentHelp: markup('<p class="abc">click to add a foo</p>'),
@odoo/rd-security The string in the function is a constant. What's more, the function is used in a unit test. The risk is zero.

2024-06-07 12:30 UTC, closed without merging