[IMP] website: reload connectors on Y-sizing change
odoo/odoo pull request #163285
Opened 2024-04-25 05:27 UTC by panv-odoo

Specification:

In the Step snippet, the connector failed to properly connect to the next step when users attempted to adjust the positioning along the y-axis.

Changes Introduced:

Previously, the logic only accounted for resizing along the x-axis. To address this issue, we enhanced the logic for generating the connectors by ensuring they receive appropriate start and end positions based on the positions of the steps they connect. This improvement involved refining the existing SVG path and viewBox logic to ensure that the connectors remain consistently connected regardless of adjustments made along the y-axis.

task-2963838

2024-04-25 05:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163285).

2024-06-13 08:34 UTC, SergeBayet requested changes
Hi, good PR :+1: 
A typo in your commit message : "Steps snippet" (with a s)
And here's my review

2024-06-13 08:34 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +            }
Maybe this way improves the readability? What do you think?
```js
const marginType = stepHeightDifference < 0 ? 'marginBottom' : 'marginTop';
connectorEl.style[marginType] = `${30 - stepHeightDifference}px`;
```

2024-06-13 08:34 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +                }
The else block is unnecessary here.

2024-06-13 08:34 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +                const verticalPaddingFactor = Math.abs(stepHeightDifference) / 8;
You can multiply the verticalPaddingFactor by 1.5 here instead of calculate it 4 times below.

2024-06-13 08:34 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +                }
else block not necessary

2024-06-13 08:34 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +                }
same as above

2024-06-18 05:38 UTC, panv-odoo commented
Hello @SergeBayet ,

The else block we have used to handle the case when the next step is lower than the current step and IMO it's needed. Could you please share your perspective on why the else block is not necessary? 
I'd appreciate your input. 
Thanks.

cc: @divy-odoo

2024-06-18 06:36 UTC, SergeBayet commented
> Hello @SergeBayet ,
> 
> The else block we have used to handle the case when the next step is lower than the current step and IMO it's needed. Could you please share your perspective on why the else block is not necessary? I'd appreciate your input. Thanks.
> 
> cc: @divy-odoo
@panv-odoo 
```
    If (..) {
       return something;
    else {
       return something_else;
    }
```
and
```
if (...) {
    return something;
return something_else;
```

That's the same behavior, and it's shorter.

2024-06-18 08:53 UTC, panv-odoo commented
Hello @SergeBayet 

The requested changes have been made.

Thanks.

2024-11-06 09:08 UTC, SergeBayet commented
@panv-odoo You can mark this PR as ready to review, it's still in draft. Thanks. And sorry for the delay :)

2024-11-06 10:36 UTC, qsm-odoo commented
@robodoo delegate=SergeBayet 
@SergeBayet

2024-11-07 06:35 UTC, panv-odoo commented
Hello @SergeBayet ,

Thank you for the update! I’ve marked the PR as ready for review. No worries about the delay 😅.

Thanks again!

2024-11-07 09:42 UTC, SergeBayet commented
> Hello @SergeBayet ,
> 
> Thank you for the update! I’ve marked the PR as ready for review. No worries about the delay 😅.
> 
> Thanks again!

Could you rebase your PR, there is an error with ci/upgrade-enterprise. Maybe it will pass.

2024-11-07 10:04 UTC, SergeBayet requested changes
LGTM :+1:  Great PR. I just added one remark concerning a linting problem.

2024-11-07 10:04 UTC, SergeBayet commented on addons/website/static/src/snippets/s_process_steps/options.js
> +                    }`;
My linter propose this like you did below:
```suggestion
                    return `M 0 ${
                        stepHeightDifference + this.hCurrentStepIconHeight - verticalPaddingFactor
                    } L ${width} ${this.hNextStepIconHeight + verticalPaddingFactor}`;
```

2024-11-08 04:26 UTC, panv-odoo commented
Hello @SergeBayet,

I’ve rebased the branch and made the requested changes. Everything is ready to go.

Thanks!

2024-11-08 06:52 UTC, SergeBayet commented
@robodoo r+

2024-11-08 09:06 UTC, closed without merging