[FIX] stock: complete_name can be name and v-v
odoo/odoo pull request #163298
Opened 2024-04-25 08:24 UTC by ethanrobv

**Current behavior:**
In some instances we will try to create a `stock.location` record from a `complete_name` field  value (one such case is creating from import). When this happens, the creation will fail due to the not-null constraint on the `name` field in the table and display a SQL error in logs.

**Expected behavior:**
It is more intuitive to create the record and use the value for both the `complete_name` and `name` fields.

**Steps to reproduce:**
1. Create an .xlsx document representing a Repair Order to be imported, such that the `Location` cell value does not already exist in the database

2. Install the test-import-export module, go into the Repair app and from the favorites action button select import data

3. Upload the .xlsx file, press 'Test Import', select the 'Create New' option for offending data points

4. Observe that the new Location can not be created, and in the console logs there is the output of the bad SQL query

**Cause of the issue:**
The `_rec_name` field for `stock.location` is `complete_name`, however the `name` field as also a required field. When we create the records in this flow, `_rec_name` is used to infer which fields need to be included in the query. So `name` is never added to the INSERT query and we end up violating the not-null constraint on this column of the table (bad query).

**Fix:**
At the point of creation in `stock_location.py`, copy the value of `complete_name` to `name` in the vals dict if possible.

opw-3796010

2024-04-26 10:18 UTC, HANNICHE-Walid approved these changes
LGTM

2024-04-26 14:10 UTC, Whenrow commented
fw-bot up to saas-16.4 
due to the [`name_get` api change](https://github.com/odoo/odoo/pull/122085)

2024-04-29 08:17 UTC, ethanrobv commented
@Whenrow added your suggestion

2024-04-29 09:35 UTC, adwid requested changes
Can you add a test ?

cc @HANNICHE-Walid :upside_down_face:

2024-04-29 09:36 UTC, adwid commented
@Whenrow With the test, we could keep the fw up to master ?

2024-04-29 09:41 UTC, Whenrow commented
@adwid If it's easier to you, feel free to change the `up to` branch.

2024-04-29 11:30 UTC, adwid commented
@Whenrow Thank you for the answer, it's always great to see such an amazing collaboration
fw-bot up to master

2024-05-02 12:07 UTC, ethanrobv commented
@Whenrow thoughts? I wasn't sure what we expect this kind of test to look like.

2024-05-02 13:50 UTC, Whenrow commented
@ethanrobv 
I would have created a test that simply call `name_create()` with a complete name and one with a already split one. 
Also could make your override returning the same thing than the original `name_create()` in case of empty `name`. 
Thank you

2024-05-06 09:30 UTC, ethanrobv commented
@Whenrow Sorry if this is a duplicate ping- wasn't sure if my previous reply will notify you as I forgot to explicitly tag you in it :ok_hand:

2024-05-08 07:20 UTC, ethanrobv commented
@Whenrow :ping_pong:
(@adwid do you need to approve as well if you are in the 'changes requested' state?)

2024-05-14 12:33 UTC, Whenrow commented
robodoo r+

2024-05-14 14:06 UTC, closed without merging