[IMP] l10n_cg,l10n_syscohada: activate taxes and fix some accounts
odoo/odoo pull request #163380
Opened 2024-04-25 15:06 UTC by MuhamedAbdallaMuhamed

For `l10n_cg`, some taxes are unarchived.

For `l10n_syscohada`, the type of some accounts is changed from Equity
to Current liabilities or Current Asset.
A missing account is also added.

task-3848455

2024-04-25 15:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163380).

2024-10-08 14:47 UTC, aboo-odoo reviewed
The community part seems good, well done :smile: 

But the same comment about commit message and PR description applies :+1:

2024-10-17 08:05 UTC, clbr-odoo commented
I suppose that's for LABE/OCO's scope now :)

2024-11-25 13:46 UTC, oco-odoo requested changes
We should split this PR into two commits IMO

2024-11-25 17:21 UTC, Arnaud-Sibille commented on addons/l10n_cg/data/template/account.tax-cg.csv
> -"","","","","","","","","","","tax","invoice","+purc_tax","pcg_4452","","",""
To be clear, before your comment I only wrote the commit msg, so it's me who just forgot to mention the accounts changes ;)

But anyway, I've seperated into 2 commits and removed the accounts changes, as discussed

2024-12-03 12:48 UTC, oco-odoo commented
@robodoo rebase-ff

2024-12-03 13:33 UTC, oco-odoo approved these changes
@robodoo r+

2024-12-03 13:33 UTC, robodoo commented
@oco-odoo you may want to rebuild or fix this PR as it has failed CI.

2024-12-03 17:43 UTC, closed without merging