[FIX] web: barcode scanner FNC1 not escaped
odoo/odoo pull request #163404
Opened 2024-04-25 16:24 UTC by ande-odoo

Current behavior:
---
On a mobile phone, using Chrome, when scanning a barcode that begins 
with the FNC1 character, ']C1' will be added to the final code.

Expected behavior:
---
']C1' should be removed from the final code

Steps to reproduce:
---
1. On a mobile phone, with chrome
2. Go to the barcode module
3. Scan a barcode starting with FNC1
4. Code will begin with ]C1

Cause of the issue:
---
https://github.com/odoo/odoo/blob/321d16950ee9dcf4d722ecbfe0a49ca8f7d855a6/addons/web/static/lib/zxing-library/zxing-library.js#L6928 
zxing-library is adding ']C1' to barcodes starting with a FNC1 character

opw-3853913

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-25 16:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163404).

2024-04-29 08:33 UTC, nle-odoo approved these changes
if we don't want `]C1` at start seems good to me

2024-05-13 08:50 UTC, ande-odoo commented
Hi @aab-odoo @juliusc2066 Could I get a review ? Thanks !

2024-05-17 14:21 UTC, rfr-odoo requested changes
I'm not an expert in barcode, but as said in the `GS1` spec[1] the `FNC1` symbol (`]C1`) is an identifier.
Also the barcode can contains a sperator `<GS>` [2].
So it must be forwarded up to the end of the process of the barcode as it can indicate de type of barcode and only then when it has been identified remove it.

Don't change `barcode_scanner.js` as it's a simple reader there is no logic and no barcode type detection in it.

Same message as another PR: odoo/enterprise#44290

[1]: https://ref.gs1.org/standards/genspecs/
[2]: https://www.barcodefaq.com/1d/gs1-128/

2024-06-13 16:05 UTC, ande-odoo commented
Hi @rfr-odoo I proposed a modification in barcodes_gs1_nomenclature, as if ]C1 is in a barcode, gs1_decompose_extanded will return None, and not identification will be done. Alternatively, I could make the same fix in the route "/stock_barcode/scan_from_main_menu", right after "is_gs1_nomenclature"
In the library it says that if the FNC1 character is in the barcode it should be replaced by ]C1, but is also says "Every subsequent FNC1 is returned as ASCII 29" but in barcodes_gs1_nomenclature, FNC1_CHAR is ASCII 29, not ]C1. Could it be added as a possible FNC1 identifier instead of removing it from the barcode as I am doing now ? 
Tell me what you think, thanks !

2024-06-14 09:16 UTC, rfr-odoo commented
> Hi @rfr-odoo I proposed a modification in barcodes_gs1_nomenclature, as if ]C1 is in a barcode, gs1_decompose_extanded will return None, and no identification will be done. Alternatively, I could make the same fix in the route "/stock_barcode/scan_from_main_menu", right after "is_gs1_nomenclature" In the library it says that if the FNC1 character is in the barcode it should be replaced by ]C1, but is also says "Every subsequent FNC1 is returned as ASCII 29" but in barcodes_gs1_nomenclature, FNC1_CHAR is ASCII 29, not ]C1. Could it be added as a possible FNC1 identifier instead of removing it from the barcode as I am doing now ? Tell me what you think, thanks !

For me it's better, but i think rd-logistics have more expertise to confirm witch one is the best fix.

2024-06-14 13:48 UTC, ande-odoo commented
Hi @odoo/rd-logistics What are your opinions about this ?

2024-07-16 09:31 UTC, ande-odoo commented
Hi @amoyaux Could I get a review ? Thanks !

2024-07-16 11:33 UTC, amoyaux commented
robodoo r+

2024-07-16 13:16 UTC, closed without merging