[IMP] website: redesign `s_numbers` snippet
odoo/odoo pull request #163583
Opened 2024-04-26 14:44 UTC by anso-odoo

The goal of this commit is to improve the visual design of the default `s_numbers` snippet.

task-3619705

| Before | After |
|--------|--------|
| <img width="1420" alt="Screenshot 2024-04-26 at 16 43 17" src="https://github.com/odoo/odoo/assets/110090660/a5252517-ba8d-47ff-9960-dfe355f63dc4">  | <img width="1439" alt="Screenshot 2024-04-26 at 16 43 04" src="https://github.com/odoo/odoo/assets/110090660/f2c6690e-ea30-4c06-93b1-00799214c531"> | 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-16 13:53 UTC, chgo-odoo commented
@stefanorigano this one is ready, if you could have a look at it please 😃

2024-07-17 07:27 UTC, stefanorigano requested changes
Thanks @chgo-odoo , some remarks for you ;)

2024-07-18 10:34 UTC, stefanorigano requested changes
Hello @chgo-odoo , thanks 👍 
Here some minor remarks. I'd propose to allow `s_numbers` columns to be aligned vertically, could you apply the necessary changes to the `vAlignment` options (see https://github.com/odoo/odoo/blob/master/addons/website/views/snippets/snippets.xml#L591)?

2024-07-18 13:28 UTC, stefanorigano approved these changes
Thanks @chgo-odoo , LGTM 👍

2024-07-26 16:26 UTC, anso-odoo commented
I made a small modification to remove the caps at the start of each word in the `.lead` paragraph 👍 
cc @chgo-odoo

2024-07-26 16:27 UTC, chgo-odoo commented
Thank you sir @anso-odoo

2024-07-30 09:40 UTC, bso-odoo commented
FYI - there is a conflict

2024-07-30 10:59 UTC, bso-odoo requested changes
Should I worry about the readability with the default image in `theme_graphene` ?
![image](https://github.com/user-attachments/assets/89fe0fb8-1716-467a-b42d-d21a5fbf150c)
Or is this not a problem, because when using the configurator it will be random images anyway.

2024-07-30 10:59 UTC, bso-odoo commented on addons/website/views/new_page_template_templates.xml
> +        <attribute name="class" add="o_cc3 o_colored_level" separator=" "/>
If the base template does not have `o_cc` anymore - it should be added in variants that add any `o_ccN` => new page templates, configurator templates (if any), and in the themes customization.

2024-07-30 11:09 UTC, chgo-odoo commented on addons/website/views/snippets/s_numbers.xml
> +                        </div>
It's still that heading tag thing 😅

Honestly I wouldn't mind if this was a new snippets but for the sake of easing customizations, I'd prefer keeping it like that

2024-07-31 07:33 UTC, bso-odoo commented
@robodoo r+

2024-07-31 07:36 UTC, bso-odoo commented
@robodoo r-
Errors in design-themes

2024-08-01 09:21 UTC, bso-odoo commented
@robodoo r+

2024-08-01 12:29 UTC, closed without merging