[FIX] account_peppol: display warning if missing info
odoo/odoo pull request #163724
Opened 2024-04-29 08:26 UTC by taqu-odoo

Issue
-----
When a partner has a valid peppol endpoint set but no bank account or country set, the user may not realize that the automatic generation for an electronic document has failed. For example when creating an invoice automatically for a subscription, there will only be an error note from odoobot, but no warning for the user like when creating an invoice manually.

Fix
-----
Display a warning to the user if some information is missing that would result in failling to generate the expected electronic document.

opw-3720730

2024-04-29 08:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163724).

2024-04-30 13:33 UTC, nle-odoo approved these changes
looks good to me

2024-04-30 13:33 UTC, nle-odoo commented on addons/account_peppol/views/res_partner_views.xml
> +                            To generate electronic invoices, also set a country and a bank account for this partner.
if it's a new term, it should be added to addons/account_peppol/i18n/account_peppol.pot

2024-05-24 06:09 UTC, ushyme commented
Hello @aliyatastemirova, could you take a look at this when have a moment ?

2024-05-24 14:11 UTC, aliyatastemirova requested changes
It doesn't look very nice in my opinion :sweat_smile: 
I think it would be nicer if it was done like the alert on line 11

![image](https://github.com/odoo/odoo/assets/39190883/6b707f45-7266-4dd1-9b6d-63888f42d042)

2024-05-28 12:58 UTC, aliyatastemirova requested changes

2024-06-03 09:30 UTC, aliyatastemirova approved these changes
robodoo r+

2024-06-03 09:38 UTC, aliyatastemirova commented
robodoo delegate=thle-odoo

2024-06-03 09:41 UTC, aliyatastemirova commented
@robodoo r-
letting @thle-odoo r+

2024-06-03 12:44 UTC, closed without merging