[FIX] account: misc operations in journal currency
odoo/odoo pull request #163813
Opened 2024-04-29 13:03 UTC by guva-odoo

Steps:

- Create a Bank journal with foreign currency
- Set the `default_account_id` as `payment_account_id` of the first
  `inbound_payment_method_line_ids`
- Create and confirm a customer payment for this journal
- Go to Accounting Dashboard
-> On the journal card, the misc operations value is displayed
   with the right currency sign but in company currency, it
   should be in journal currency.

opw-3869330

2024-04-29 13:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163813).

2024-04-30 09:56 UTC, h4818 requested changes
Thanks @guva-odoo 
I'm not sure it should be in journal currency, IMO it should be in the currency of those entries
Have you seen https://github.com/odoo/odoo/pull/156655#issuecomment-2039947114

2024-04-30 09:56 UTC, h4818 commented on addons/account/models/account_journal_dashboard.py
> +                aggregates=['balance:sum', 'amount_currency:sum', 'id:count'],
This might be a variety of different currencies, no?

2024-04-30 09:56 UTC, h4818 commented on addons/account/models/account_journal_dashboard.py
> +            misc_operations_balance = misc_amount_curr if currency != company_currency else misc_balance
could we use this new `currency_consistent`?

2024-04-30 10:06 UTC, h4818 commented
Please check the steps to reproduce, Customer Payments should not impact the Misc Operations

2024-04-30 12:09 UTC, h4818 commented
@tsb-odoo suggests excluding payments from the misc operations link

2024-05-06 10:24 UTC, h4818 reviewed
@guva-odoo The fix is good, though the commit message is outdated

2024-05-06 10:27 UTC, guva-odoo commented
> @guva-odoo The fix is good, though the commit message is outdated

🤦‍♂️ 🤦‍♂️ 🤦‍♂️

2024-05-06 10:38 UTC, h4818 reviewed
@robodoo r+

2024-05-06 14:58 UTC, closed without merging