[FIX] stock_picking_batch: update batches with backorder processes
odoo/odoo pull request #163935
Opened 2024-04-30 07:27 UTC by lase-odoo

### Steps to reproduce:

- Enable Batch Transfers in the settings
- Go to Inventory > Config> Warehouse Management > Operation Types
- On  receipts, enable "Automatic Batches" group by contact
- Create and confirm a purchase order for any contact with:
  - 1 X storable product P1
- Create and confirm a purchase order for the same contact with:
  - 1 X storable product P1
  - 1 x storable product P2
- Go to the assocated stock picking > change the quantity of P1 to 0
- Validate and create a backorder

#### > invalid operation: The following transfers cannot be added to batch

### Cause of the issue:

When the backorder is processed, the stock picking that currently belongs to our batch is validated and a backorder is created: https://github.com/odoo/odoo/blob/f168c4ba9d64a05a4a55715c44016a15230fe706/addons/stock/models/stock_move.py#L1891-L1892 The picking associated to this backorder is then added to our batch https://github.com/odoo/odoo/blob/f168c4ba9d64a05a4a55715c44016a15230fe706/addons/stock_picking_batch/models/stock_picking.py#L160-L162 But for this action to be performed, we need to pass the sanity check verifying that the pickings associated to our batch are allowed: https://github.com/odoo/odoo/blob/f168c4ba9d64a05a4a55715c44016a15230fe706/addons/stock_picking_batch/models/stock_picking_batch.py#L282-L286 And here comes the problem, the picking that created the backorder was not yet removed from our batch but is not allowed anymore since it is now in 'done' state:
https://github.com/odoo/odoo/blob/f168c4ba9d64a05a4a55715c44016a15230fe706/addons/stock_picking_batch/models/stock_picking_batch.py#L76-L77

opw-3893543
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-30 07:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163935).

2024-05-08 13:20 UTC, HANNICHE-Walid approved these changes
LGTM

2024-06-05 12:48 UTC, Whenrow commented
Your fix is correct but It's could be a bit more robust. I was wondering why this part did nothing in `button_validate` 
https://github.com/odoo/odoo/blob/b0f2a560927604fa788033fd2980ce438c060f3e/addons/stock_picking_batch/models/stock_picking.py#L127-L129

I just realized the backorder is created, assigned and linked to the batch in the `super()`. So what about moving this chunck of code that remove `done` pickings in an override of `_create_backorder()`. The original picking is already validated at that time so we could remove it before adding the backorder.

2024-06-05 12:48 UTC, Whenrow requested changes
see comment above

2024-06-10 07:48 UTC, lase-odoo commented
Thank you for the great suggestion @Whenrow !

I have updated the fix and both the test and the runbot seems to like this change.
Just tell me if that's what you expected :slightly_smiling_face:

2024-06-11 07:01 UTC, Whenrow commented
@lase-odoo Seems a test is failing due to my suggestion. If it's not possible to adapt the code we will go back to your previous solution

2024-06-11 07:14 UTC, lase-odoo commented
@Whenrow, It did not before I rebased. I am currently looking into it !

2024-06-11 09:15 UTC, adwid commented
I think the runbot is red...

2024-06-12 12:20 UTC, lase-odoo commented
> I think the runbot is red...

I think the redbot is run :sunflower:

2024-06-13 12:30 UTC, Whenrow commented
robodoo r+
thank you

2024-06-13 15:24 UTC, closed without merging