[FIX] point_of_sale: remove taxes on gift card
odoo/odoo pull request #163928
Opened 2024-04-30 06:53 UTC by Axel927

Problem:
There is taxes added to the gift card discount

Steps to reproduce:
- Install "Point of sale" app
- Go to Settings and activate gift cards
- Create a gift card (for ex 100€)
- Copy the code
- Open PoS > Add a product (more than the price of the gift card to understand better) > add the gift card
- The card value is not 100€ but more because it includes taxes

Solution:
Set an empty Array as tax will allow this.tax_ids to be evaluated as true in a if statement and will define an empty Array for the tax of the gift card

https://github.com/odoo/odoo/blob/7df8fc435c6ea199292f47954202d4f3c93b2629/addons/point_of_sale/static/src/app/store/models.js#L745-L749

opw-3862427

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-30 06:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163928).

2024-04-30 11:01 UTC, robinengels requested changes

2024-05-17 14:54 UTC, robinengels commented on addons/pos_loyalty/tests/test_frontend.py
> +        # Run the tour. It will pay the gift card and use it.
This is not accurate anymore, it's just using the gift card

2024-05-17 14:54 UTC, robinengels commented on addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
> +            Dialog.confirm(),
You can add a step to test that the gift card is in the order. Something like ´selectedOrderlineHas´ should do the trick

2024-05-24 11:25 UTC, robinengels approved these changes

2024-05-24 11:25 UTC, robinengels commented on addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
> +            ProductScreen.selectedOrderlineHas("Gift Card"),
You can also check the value of the gift card here. Then the PR will be ok for me .

2024-06-04 10:07 UTC, adgu-odoo approved these changes
Good job

2024-06-04 10:08 UTC, adgu-odoo commented
@robodoo r+

2024-06-05 10:32 UTC, closed without merging