[FIX] base: fix .o_onboarding_btn_close overlapping
odoo/odoo pull request #163966
Opened 2024-04-30 10:29 UTC by xlu-odoo

Before this commit, on smaller screens the onboarding steps illustration sometimes overlapped the close button, making it difficult to dismiss the onboarding steps.

This fix ensures the close button is no longer obscured.

task-3749740

<details>
<summary>Preview (See changes)</summary>

<table>
<tr>
 <td>Before</td>
 <td>After </td>
<tr>
 <td><img src="https://github.com/odoo/odoo/assets/80678921/01cd9478-1e9d-4736-9599-3df8bda380b1" alt="before"></td>
 <td><img src="https://github.com/odoo/odoo/assets/80678921/b8d2ec5a-3bea-48d9-8320-b0872ae04be8" alt="after"</td>
</table>

</details>

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-04-30 10:30 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163966).

2024-04-30 10:54 UTC, chgo-odoo approved these changes
Hello @xlu-odoo, thanks for the fix !

Looks good to me, don't forget that you'll need to adapt the forward-port when it reaches master 🙂

2024-04-30 13:15 UTC, xlu-odoo commented
Hello @pparidans , could you tech review this small PR by any chance? 🙏

2024-05-13 14:12 UTC, pparidans approved these changes
I don't like either the `!important` but it makes sense as a fix...

Don't forget to remove it and the class in the xml once reaching `master`

2024-05-13 14:19 UTC, pparidans requested changes
Wait, actually, there is something funky when scrolling up/down and the ControlPanel appears...

![image](https://github.com/odoo/odoo/assets/33146/3d436c4c-6cdb-4f97-b9fa-8dc7cdb28961)

2024-05-13 14:38 UTC, xlu-odoo commented
> Wait, actually, there is something funky when scrolling up/down and the ControlPanel appears...
> 
> ![image](https://private-user-images.githubusercontent.com/33146/330091769-3d436c4c-6cdb-4f97-b9fa-8dc7cdb28961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTEyNTIsIm5iZiI6MTcxNTYxMDk1MiwicGF0aCI6Ii8zMzE0Ni8zMzAwOTE3NjktM2Q0MzZjNGMtNmNkYi00Zjk3LWI5ZmEtOGRjN2NkYjI4OTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE0MzU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOGQ1OTMxMTViYTE3OWZhNDA2MDM2NmUxMTAyMjliMDVmYjRiNTY4YzEwOWQ4ZGUyYjI1NTg4NjBjZTQ3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1eLP8lGGUENh4vqN1uvsRn2GnkwczUehitrK7rVaps)

Ok I see on mobile. will set the z-index to 2 and push. Thanks @pparidans

2024-05-14 08:12 UTC, pparidans approved these changes
@robodoo r+

2024-05-14 11:56 UTC, closed without merging