[IMP] webiste_cf_turnstile: transition from jQuery to vanilla js
odoo/odoo pull request #163987
Opened 2024-04-30 12:01 UTC by shsa-odoo

Specification:

This commit focuses on transitioning all frontend code from jQuery to Vanilla JavaScript. The changes specifically target files in the web.assets_frontend.

task-3770362

2024-04-30 12:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/163987).

2024-07-26 14:26 UTC, bso-odoo requested changes
Here are a few comments: variable to rename to mach the `*El`, `*Els` naming.

2024-07-26 14:26 UTC, bso-odoo commented on addons/website_cf_turnstile/static/src/js/turnstile.js
> +            const turnstileElement = document.createElement("div");
`turnstileEl` ?

2024-07-26 14:26 UTC, bso-odoo commented on addons/website_cf_turnstile/static/src/js/turnstile.js
> +            const scriptElement1 = document.createElement("script");
`script1El` ?

2024-07-26 14:26 UTC, bso-odoo commented on addons/website_cf_turnstile/static/src/js/turnstile.js
> +            const scriptElement2 = document.createElement("script");
`script2El` ?

2024-07-26 14:26 UTC, bso-odoo commented on addons/website_cf_turnstile/static/src/js/turnstile.js
> +            const formSendElement = this.el.querySelector(".s_website_form_send, .o_website_form_send");
`formSendEl` ?

2024-07-26 14:26 UTC, bso-odoo commented on addons/website_cf_turnstile/static/src/js/turnstile.js
> +        const turnstileElements = this.el.querySelectorAll(".s_turnstile");
`turnstileEls` ?

2024-07-29 10:24 UTC, shsa-odoo commented
@bso-odoo done!

2024-07-30 07:39 UTC, bso-odoo commented
@robodoo r+

2024-07-30 09:13 UTC, closed without merging