[IMP] stock: back2basics lna
odoo/odoo pull request #164130
Opened 2024-05-01 12:49 UTC by jaha-odoo

In this commit:
====================
- Moved some text on top of the checkbox in the info banner on delivery orders operation type form view.
- Renamed 'Type of Operation' to 'Operation Category' in the form and list views of operation types, as well as in the inventory overview filter.
- Changed the 'help' field text of replenishment and transfers tree view.
- Changed the default value of the name field to 'New' in transfers.
- Added a placeholder in 'Receive From' in the transfer form view.
- Removed the tooltip of 'Source Documents' from the transfer form view.
- Removed 'Unreserved' from actions since it's already a button in the transfers view.
- Improved lock/unlock method and added lock icon after transfer name to show transfer is locked/unlocked.
- Removed the expense category from product categories if the expense module is not installed.
- Added a separator before starred products in inventory adjustment filters.
- Changed the 'help' field text of the warning, and annual inventory date, and renamed 'Email Confirmation' to 'Confirmation Email' in inventory settings.
- Added missing helper on the product category.

task-3836703

2024-05-01 12:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164130).

2024-05-31 14:19 UTC, Whenrow commented on addons/stock/models/stock_picking.py
> +            if vals.get('name', '/') == '/' and defaults.get('name', 'New') == _('New') and vals.get('picking_type_id', defaults.get('picking_type_id')):
Do not compare translatable strings with hardcoded ones. You can rather do like this : 

https://github.com/odoo/odoo/blob/efe6dac4a1757da935584536f6acb1f6d14eb915/addons/mrp/models/mrp_production.py#L908

2024-05-31 14:19 UTC, Whenrow commented on addons/stock/models/stock_move.py
> +            move.is_initial_demand_editable = (not move.picking_id.is_locked and move.state != 'done') or move.state == 'draft'
initial demand is readonly in "ready" state. unlocking the picking should allow to edit it in this state

2025-09-22 08:44 UTC, dhha-odoo requested changes

2025-09-22 08:44 UTC, dhha-odoo commented on addons/hr_expense/data/hr_expense_demo.xml
It would be better to add a comment like `<!-- Expensable products -->` before the demo data for clarity.

2025-09-22 08:44 UTC, dhha-odoo commented on addons/hr_expense/data/hr_expense_demo.xml
> +            <field name="categ_id"  eval="ref('hr_expense.product_category_expenses', raise_if_not_found=False)"/>
```suggestion
            <field name="categ_id" eval="ref('hr_expense.product_category_expenses', raise_if_not_found=False)"/>
```

2025-09-22 08:44 UTC, dhha-odoo commented on addons/mrp/views/mrp_production_views.xml
Also, I don’t see any reason for these changes; it’s neither defined in the specs nor mentioned in the commit message.

2025-09-22 08:44 UTC, dhha-odoo commented on addons/mrp/views/mrp_production_views.xml
> +                            <i class="fa fa-lock m-3 fs-3" title="This transfer is locked" invisible="not is_locked or state == 'draft'"/>
Why `transfer`? I’m not sure, maybe `MO` or `Manufacturing Order` would be clearer. Please confirm with the PO.

It’s not `looking good visually`. The icon should be aligned with the name.
<img width="448" height="72" alt="image" src="https://github.com/user-attachments/assets/ad27509f-ba71-41b2-b562-a0f90fbd9ca1" />

2025-09-22 08:44 UTC, dhha-odoo commented on addons/product/views/product_category_views.xml
> +        </field>
```suggestion
        <field name="help" type="html">
            <p class="o_view_nocontent_smiling_face">
                Create a new product category
            </p>
        </field>
```

2025-09-22 11:12 UTC, srap-odoo commented on addons/mrp/views/mrp_production_views.xml
Hello @dhha-odoo,
Thanks for pointing that out!

After discussing with the PO, I am removing the lock icon feature from both Transfers and MOs, as this will be addressed with a better UX in task: https://www.odoo.com/odoo/project/966/tasks/5016551

2025-09-22 11:12 UTC, srap-odoo commented on addons/hr_expense/data/hr_expense_demo.xml
Yes, that would add a value.Implemented!
Thanks for the review😊

2025-09-22 13:19 UTC, dhha-odoo approved these changes

2025-11-20 16:29 UTC, amoyaux commented on addons/hr_expense/data/hr_expense_data.xml
> +        </record>
Why this change? I see nothing related in the task

2025-11-20 16:31 UTC, amoyaux commented on addons/stock/views/stock_picking_views.xml
> -
Either keep it and remove the button in the view list. Or add a button in the view form. I would personally delete the button in list view since this action was created to earn place in the form view

2025-11-21 10:36 UTC, srap-odoo commented on addons/stock/views/stock_picking_views.xml
> -
Hello @amoyaux ,
Yes, I also align with removing the button instead. This will make it easier to use the action in other views without having to define the button in each one.
Thank you :relaxed:

2025-11-21 10:41 UTC, amoyaux commented
robodoo r+

2025-11-21 13:56 UTC, closed without merging