[FIX] point_of_sale: notification message in mobile mode
odoo/odoo pull request #164272
Opened 2024-05-03 06:02 UTC by paan-odoo

Before this commit:
==========
- After scanning the product barcode, the notification of the added product was not showing in mobile mode.

After this commit:
==========
- After scanning the product barcode, the notification of the added product will work fine.

task-3877329

2024-05-03 06:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164272).

2024-05-17 06:37 UTC, davidmonnom requested changes
[Screencast from 17-05-24 08:36:52.webm](https://github.com/odoo/odoo/assets/63289800/8473e0c5-08fa-4055-882e-519180d78fec)

It doesn't work. See video.

2024-05-17 11:47 UTC, paan-odoo commented
Hello @davidmonnom
Changes are done. Can You please check again?
Thanks!

2024-05-27 12:39 UTC, davidmonnom commented
@robodoo r+

2024-05-27 19:11 UTC, closed without merging