[FIX] point_of_sale: prevent opening Product popup without options
odoo/odoo pull request #164384
Opened 2024-05-03 14:56 UTC by pedrambiria

This commit addresses the issue where the Product Configurator Popup was displayed unnecessarily when there was only one value for each attribute of a product. The implementation now includes a check to ensure that the popup is shown only when there are more that one choices available. This enhancement improves the user experience by avoiding the display of a redundant popup without viable options.

opw-3903425

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-03 14:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164384).

2024-06-03 08:29 UTC, pedrambiria commented
@davidmonnom Could you please review this pr?

2024-06-03 08:55 UTC, davidmonnom requested changes
Hello,
What do you think about modify `isConfigurable` on product model instead to check inside `openConfigurator` since `openConfigurator` is only call if `isConfigurable` is true.

2024-06-03 09:43 UTC, pedrambiria commented
@davidmonnom It is not feasible due to the nature of the isConfigurable function. This function is designed to return a boolean value. When adding a product where each attribute has only one value, these values must be selected. This selection process needs to occur within the openConfigurator function.

2024-06-03 10:19 UTC, davidmonnom commented
Ignoring the comments because the logic will be duplicated. We'll see what we do with `isConfigurable` later.

@robodoo r+

2024-06-03 12:44 UTC, closed without merging