[IMP] pos: prevent refresh when offline
odoo/odoo pull request #164496
Opened 2024-05-06 07:54 UTC by nesma-neha

Add warning popup for page reload when POS is offline

Task ID: 3901910

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-06 07:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164496).

2024-05-06 08:44 UTC, davidmonnom requested changes
Hello :) 

When I try to reload the page with `CTRL + R` or via the refresh button, I get this message:

![image](https://github.com/odoo/odoo/assets/63289800/aa0894e2-9ab0-4b58-a4ee-1496523e1795)

I didn't get the sentence written in your PR.

2024-05-06 09:35 UTC, nesma-neha commented
@davidmonnom ,

Yes I did some research about this and it appears that the problem is in chrome neglecting the returnValue 
Also other browsers behave the same way and it seems like a common issue

will try to find a work around this

2024-05-10 08:12 UTC, davidmonnom commented
@robodoo r+

For information, some browsers will not display the custom message. It depends on the browser used.

In all cases, a message will be displayed telling the user that some information may not be saved.

2024-05-10 10:48 UTC, closed without merging