[FIX] http: ensure lang is valid when reloading context from session
odoo/odoo pull request #164675
Opened 2024-05-07 08:21 UTC by xavieralt

Following odoo/odoo#142814 we have to ensure the Environment context `lang` is valid after reloading it from the session context, as the session context might contain a lang value that are not valid anymore, otherwise it can unexpectedly crash.

This happen for example by simply browsing the website when the following conditions are met:

- The browser preferred language (`Accept-Language`) reference a language that is not enabled on the Odoo instance
- The `_get_current_website_id()` cache is cold for the requested domain (server startup, worker recycling, ormcache invalidation)
- The request domain match a website and the website model has a translatable field

[OPW-3911437](https://www.odoo.com/web#id=3911437&model=project.task&view_type=form)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-07 08:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164675).

2024-05-07 11:39 UTC, Julien00859 approved these changes
We should remove the following snippet of code then https://github.com/odoo/odoo/blob/80d50f0e881f913f782965dd8e2279f46d93b5df/odoo/addons/base/models/ir_http.py#L192-L196

2024-05-07 11:39 UTC, Julien00859 commented on odoo/http.py
> +            self.update_context(lang=get_lang(self.env).code)
```suggestion
            self.update_context(lang=get_lang(self.env(user=odoo.SUPERUSER_ID)).code)
```

2024-05-07 13:35 UTC, Julien00859 requested changes
Ok so I remember why I didn't do this change myself, some weeks ago when the problem was reported.

So since chw's changes, we cannot use a lang that doesn't exist. That's fair.

When it comes to the HTTP stack is poses a chicken/egg problem.

1) You need to match a route to determine how to authenticate the user (`auth='user'`, `auth='public'`, `auth='none'`).
2) You need to authenticate the user before using the environment of the request (otherwise you could be using a user that doesn't exist anymore)
3) Website uses the environment to match a route.

We solved this problem by making so `website` uses `sudo()` whenever it wants to use the environment, to bypass the access rights, so that the env.user is not used.

The thing is, when you fetch the website it also fetches some Char fields that are translated and it uses the current user's lang to translate them. Keep in mind that `sudo()` only bypass the access rights, it doesn't actually change the user on the environment. Before chw's changes, when the lang didn't exist it simply falledback on english. Now it crashes. That it crashes is IMO correct.

Now about this change inside http.py. `get_lang` is going to fallback on the current user's company's lang when the context lang is missing/uninstalled. BUT we cannot rely on `env.user` to exist this early in the stack (that is `authenticate`'s job). BUT we cannot remplace it with the SUPERUSER_ID because it would mean it would fallback on the superuser_id's company's lang instead of the user's company's lang (when the lang is missing but the user exists). Sorry my previous suggestion was wrong.

---

IMO there is nothing to fix in base. Making sure that the lang is valid inside `_pre_dispatch()` (that is called just after `_authenticate`) is the right thing to do.

The problem is that website uses an environment that is not ready yet.

2024-05-07 13:40 UTC, Julien00859 commented on odoo/http.py
> +            self.update_context(lang=get_lang(self.env).code)
Bad idea actually, `get_lang` will use the user to fallback on his company's lang. There is a chance that `SUPERUSER_ID` and `session.uid` are not in the same company.

2024-05-07 13:42 UTC, Julien00859 commented
An alternative it to skip the company fallback. To immediately fallback on english (when it is installed) or the first lang installed when the context lang is not. Then we can user `SUPERUSER_ID`.

2024-05-08 13:11 UTC, Julien00859 approved these changes
Thanks! This one really was a burden, very happy to see it sorted!

@robodoo r+

2024-05-08 14:08 UTC, JKE-be commented
Simple way to reproduce:

- start db with --load-language=fr_BE
- install a module with translated field on website model (website_sale)
- set a domain on your website (odoo.local:8069)
- set up your browser to use 'fr' as prefered lang
- go to your website with the domain odoo.local

fr will become fr_FR by babel, and get_current_Website will prefetch translated field with this lang fr_FR because called before the nearest_lang stuff that match an installed lang.

This fix allow to avoid the prefetch (lang=None), and it will be done later when the lang is correctly set in the context after the _match.

2024-05-08 14:28 UTC, rdeodoo commented
Would probably be nice to include it in the commit message, especially since the r+ did not yet really kicked in as it's still waiting for staging :innocent:

2024-05-08 15:24 UTC, Julien00859 commented
@robodoo r-

> Would probably be nice to include it in the commit message, especially since the r+ did not yet really kicked in as it's still waiting for staging 😇

doing it

2024-05-08 15:40 UTC, Julien00859 commented
```diff
diff --git a/tmp/before.txt b/tmp/after.txt
index aee38f19d969..f7261a9b7c7a 100644
--- a/tmp/before.txt
+++ b/tmp/after.txt
@@ -1,12 +1,29 @@
     [FIX] http: ensure lang is valid when reloading context from session
     
+    Steps to reproduce (courtesy of JKE):
+    
+    * start db with --load-language=fr_BE
+    * install a module with translated field on website model (website_sale)
+    * set a domain on your website via the settings (e.g. odoo.local:8069)
+    * restart server (cold)
+    * set up your browser to use 'fr' as prefered lang
+    * go to your website with the domain odoo.local (with no existing
+      cookies/session, e.g. in a private tab)
+    * 400 bad request
+    
+    fr becomes `fr_FR` via babel (`Request.best_lang`) in the request
+    context, and `_get_current_website` (called in `IrHttp._match` prefetches
+    website fields + translate the translatable ones using `fr_FR` because
+    the request context has not yet been sanitized by `IrHttp._pre_dispatch`.
+    
+    Before odoo/odoo#142814 the non-installed lang would be silently be
+    replaced by `en_US`.
     Following odoo/odoo#142814 we have to ensure the Environment context
     `lang` is valid, expecially when creating an Environment from the
     session context as it might contain a lang value that are not valid
     anymore, otherwise it can unexpectedly crash.
     
-    This happen for example by simply browsing the website when the
-    following conditions are met:
+    Precisely, the problem happens when the following conditions are met:
     
     - The browser preferred language (`Accept-Language`) reference a
       language that is not enabled on the Odoo instance
```

2024-05-08 15:41 UTC, Julien00859 commented
@robodoo r+

2024-05-10 10:40 UTC, closed without merging