[FIX] base, *: ensure arch_updated set to false when hard reset a view
odoo/odoo pull request #164929
Opened 2024-05-08 12:32 UTC by SergeBayet

*: test_website

Since [1], the code responsible for resetting broken view failed to
consider that during a "hard" reset, the 'arch_updated' field should be
set to False.

Steps to reproduce (on a local server):

- Activate the developer mode
- Navigate to Website and click on "Go to Website"
- Click on the menu "Pages" > "Manage Pages"
- At the /contactus line, click on the "bug" button to access the view
- Click on "Edit" to be able to change the architecture
- Add something that breaks the view in the template (i.e :
  ```<p t-field="no_field.exists"></p>```)
- Click on "Save" and after "Go to Page Manager"
- Click on the /contactus url link
- An internal server error page appears with the possibility to restore
  the previous version of the view (soft reset) or to reset to initial
  version (hard reset). Click on "Hard Reset"
- With your DB manager, search in the table ir.ui.view, the record with
  the key website.contactus. Observe that the field arch_updated is
  still True while the view is reset and shouldn't be in an updated
  state.

This commit ensures consistent updating of this field. 
A "Hard" reset of a broken view will remove its previous architecture
used for "Soft" reset, since there is no real usage where a "Previous"
reset is needed after a "Hard" one.

[1]: https://github.com/odoo/odoo/commit/479585140caca9fdc758709f043da500297e8046

task-3743850

2024-05-08 12:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/164929).

2024-07-01 08:35 UTC, qsm-odoo requested changes
@robodoo delegate=xO-Tx 
@xO-Tx

2024-07-01 08:35 UTC, qsm-odoo commented on odoo/addons/base/models/ir_ui_view.py
> +                view.with_context(no_save_prev=True, lang=None).write({'arch_db': arch, 'arch_updated': False})
Probably better if you avoid to duplicate the `with_context` code, only the `write` differs

2024-07-04 14:56 UTC, xO-Tx requested changes
@SergeBayet I was checking if after a hard view reset, a soft reset will set the `arc_updated` to `True`, but I noticed a very strange behaviour:
Let's suppose the file version of a view arch = v0. If you:

1- Update the arch of a view (current arch = v1, previous arch = v0, `arc_updated` = `True`)
2- Update again the arch (current arch = v2, previous one = v1, `arc_updated` = `True`)
3- Trigger a "hard" reset (current arch = v0, previous one = v1, `arc_updated` = `False`)
4- Trigger a "soft" reset > The reset won't work > Correct behaviour: The new arch of the view should be v1, and `arc_updated` should be set to `True`.

Can you check this :+1:

Before the diff:
https://github.com/odoo/odoo/assets/25032876/a71e5463-9a06-4cc6-88ac-487ca5770fff

After the diff:
https://github.com/odoo/odoo/assets/25032876/1f8838ca-5442-4139-8d29-ba4dc9779611

2024-07-04 14:56 UTC, xO-Tx commented on odoo/addons/base/models/ir_ui_view.py
> -            if arch:
I don't think it's a good idea to remove the `if arch:` check here. If a view has no previous `arch_db` (`arch_prev`), this allows setting `False` on "soft" reset, no ?

2024-07-08 07:01 UTC, SergeBayet commented
@xO-Tx I've investigated the situation here. When you tested my diff, you were in --dev=xml mode? Because in this case, the behaviour change.
Look at the definition of the computes 'arch' field : 
```python
arch = fields.Text(compute='_compute_arch', inverse='_inverse_arch', string='View Architecture',
                       help="""This field should be used when accessing view arch. It will use translation.
                               Note that it will read `arch_db` or `arch_fs` if in dev-xml mode.""")
 ```

2024-08-22 07:57 UTC, SergeBayet commented
@xO-Tx Hi! Any update on this PR? Thanks

2024-10-14 08:59 UTC, qsm-odoo commented
@xO-Tx You were already delegated on this one :)

2024-10-16 10:59 UTC, SergeBayet commented
@xO-Tx Retargeted to 16.0

2024-10-16 15:24 UTC, xO-Tx approved these changes
LGTM Thanks @SergeBayet for the fix and diff adaptations :+1:

2024-10-16 15:24 UTC, xO-Tx commented
@robodoo r+

2024-10-16 16:47 UTC, closed without merging