[IMP] point_of_sale: marketing through POS
odoo/odoo pull request #165088
Opened 2024-05-10 12:01 UTC by paan-odoo

Before this commit:
==========
- There is no feature for marketing in Point of Sale.

After this commit:
==========
- Now, we can use the customer's email and mobile number for marketing in Point of Sale.

task-3872538

2024-05-10 12:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165088).

2024-05-16 13:41 UTC, paso-odoo requested changes

2024-05-16 13:41 UTC, paso-odoo commented on addons/point_of_sale/data/mail_template_data.xml
> +We have a limited time offer only for you, enjoy flat 20% on your next purchase with us.
```suggestion
We have a limited time offer only for you, enjoy flat 20% off on your next purchase with us.
```

2024-05-16 13:41 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +                        country=related_country)
```suggestion
            related_country = False
            if vals.get('mobile'):
                related_country = self.env['res.partner'].browse(vals['partner_id']).country_id if vals.get('partner_id') else self.env.company.country_id
                vals['mobile'] = self._phone_format(number=vals.get('mobile'), country=related_country)
```

I would do something like this

2024-06-24 12:58 UTC, davidmonnom requested changes

2024-06-24 12:58 UTC, davidmonnom commented on addons/point_of_sale/models/pos_order.py
> +    mobile = fields.Char(string='Mobile')
I'm okay about create email field here but mobile is usefull in the main `point_of_sale` module ? Cannot be created in whatsapp_pos ?

2024-06-24 12:58 UTC, davidmonnom commented on addons/point_of_sale/models/pos_order.py
> +                        country=related_country)
maybe instead of that you can create a compute methods that depends on the partner.

2024-06-24 12:58 UTC, davidmonnom commented on addons/point_of_sale/models/pos_order.py
> +                        country=order.partner_id.country_id or self.env.company.country_id)
maybe instead of that you can create a compute methods that depends on the partner.

2024-06-24 12:58 UTC, davidmonnom commented on addons/point_of_sale/models/pos_order.py
> +                        country=related_country)
btw you don't need it if you set the vals from the frontend

2024-07-10 08:51 UTC, davidmonnom approved these changes

2024-07-10 09:49 UTC, davidmonnom commented
@robodoo r+

2024-07-10 13:20 UTC, closed without merging