[FIX] website: prevent creation of 308 to existing controller
odoo/odoo pull request #165083
Opened 2024-05-10 11:26 UTC by rdeodoo

Creating a 308 which redirects to an existing controller will have unpredictable (and unwanted) behaviors.

Indeed, 308 are there to redirect an existing URL (like `/shop`) to a non-existing URL (like `/my-super-shop`) and to make it so that non existing URL will respond with the content of the existing URL.

The way it's done is that it simply replace the routing map rule for the given URL by two new rules:
- One for the non-existing URL (chosen url_to) which will serve the existing url endpoint
- One for the existing URL, which will be turned into a redirect endpoint

This works fine except if you actually select an existing controller as url_to in the 308 rewrite.

In this case, there will be 2 werkzeug Rules for the same URL, which is bad. Worst than that, depending of the selected controller the order of those 2 Rules will change, leading to different behavior.

Step to reproduce:
- Create a 308 from /blog to / (note that "/" is a controller)
- Go to /blog, it will redirect and show the homepage
- Go to /, it will show the homepage
- Now edit the 308 and redirect /shop to /
- Go to /shop, it redirects to / but won't show the homepage, it will show the shop page
- Go to /, it will show the shop page

Technically, here is the routing map for both cases:
1. 308 shop case ``` <FasterRule '/' -> functools.partial(<bound method WebsiteSale.shop of <odoo.http.CustomerPortal (extended by PortalAccount, PaymentPortal, CustomerPortalExternalTax, SaleStockPortal, CustomerPortal, PaymentPortal, PaymentPortal, WebsiteSaleDelivery, WebsiteSaleExternalTaxCalculation, WebsiteSale, WebsiteSaleStockRenting, WebsiteSaleStockRenting, WebsiteSale, WebsiteSaleRenting, PaymentPortal, CustomerPortalExternalTax, CustomerPortal, WebsiteAccount) object at 0x7f4d9468a6b0>>)>, <FasterRule '/' -> functools.partial(<bound method Website.index of <odoo.http.Home (extended by Home, Home, Routing, AuthSignupHome, Website) object at 0x7f4d94583460>>)>, ```
2. 308 blog case ``` <FasterRule '/' -> functools.partial(<bound method Website.index of <odoo.http.Home (extended by Home, Home, Routing, AuthSignupHome, Website) object at 0x7f7fc9ebd7e0>>)>, <FasterRule '/' -> functools.partial(<bound method WebsiteBlog.blog of <odoo.http.WebsiteBlog object at 0x7f7fc9d69090>>)>, ```

You see that the Rule order is inverted from one case to another.

We could have decided to do another fix and adapt the `_generate_routing_rules()` method to keep only one Route but that seems worst as:
1. 308 are not designed for that in the first place, not even sure what we would want
2. it will technically be far from ideal, having the check routing map to check if exists already and ensure the same behavior all the time

opw-3901713

2024-05-10 11:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165083).

2024-05-10 12:12 UTC, rdeodoo commented
@qsm-odoo Do you want to review this one? Or dispatch it (to the team or JUC/JKE?)

2024-05-10 16:20 UTC, qsm-odoo commented
I'll review it.

2024-05-14 11:11 UTC, qsm-odoo requested changes
@rdeodoo I have a weird bug + a question

1. Install `website_sale`
2. Create a 308 rewrite from `/shop` to `/`, save
3. You get the homepage error, nice.
4. Change `/` to `/contactus` -> you can. Question: should not we prevent that also? :thinking: 
5. Change `/contactus` to `/@` -> you can ! Somehow this does not work if you create the rewrite rule with `/@` but it works if you modify the existing one with it :shrug:

2024-05-17 16:46 UTC, qsm-odoo approved these changes
I push-forced to [adapt the comment](https://github.com/odoo/odoo/compare/41708d390bfee3c1f3c6df2f7d3037b08554392d..adaa80a2216f4667af6213cc43a28bc8768bfd5b) that was now wrong

@robodoo r+

2024-05-17 20:00 UTC, closed without merging