[REF] Convert all jquery related code in vanilla Javascript
odoo/odoo pull request #165019
Opened 2024-05-09 05:36 UTC by msh-odoo

Description of the issue/feature this PR addresses:

This PR aim to convert all jQuery code into Vanilla JS in website_slides, this way we will reduce the dependency of jQuery in Odoo codebase.

task-3770362

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-09 05:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165019).

2024-07-26 14:35 UTC, bso-odoo requested changes

2024-07-26 14:35 UTC, bso-odoo commented on addons/website_slides_survey/static/src/js/slides_course_fullscreen_player.js
> +        const content = this.el.querySelector(".o_wslides_fs_content");
`contentEl` ?

2024-07-29 12:29 UTC, visp-odoo commented
Hello @bso-odoo :wave: 

I have made changes suggested by you.

Thanks

2024-07-31 07:38 UTC, bso-odoo commented
@robodoo r+

2024-07-31 09:11 UTC, closed without merging