[FIX] account: prevent error when opening accrued revenue entry
odoo/odoo pull request #165014
Opened 2024-05-09 04:58 UTC by aamo-odoo

This error occurs when we create a new sales order, then proceed to create an invoice within that sales order, and finally attempt to open the ``Accrued Revenue Entry`` from the action button.

Steps to reproduce:

- Install the ``sale_management`` and ``account_accountant`` modules
- Create new sales orders > ``Confirm`` > ``Create Invoice`` button > Down Payment in % > ``Confirm`` > ``Sale Order`` smart button
- Go to action button > ``Accrued Revenue Entry``

Traceback:
``AssertionError: precision_rounding must be positive, got 0.0``

At [1] within ``o.order_line``, we are encountering an issue where ``product_template_id`` is being retrieved as zero. This is leading to an error.

This commit will fix the above error by implementing a check for the ``product_template_id`` in the sale order line.

[1]: https://github.com/odoo/odoo/blob/364821d72b0c3759e3768416886acd1b7f419b91/addons/account/wizard/accrued_orders.py#L171

sentry-4857910663

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-09 04:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165014).

2024-05-13 09:22 UTC, aamo-odoo commented
Hello @odoo/sentry_reviewers 
Please review this PR 🙂

2024-05-21 09:10 UTC, yosa-odoo commented
@guva-odoo I think you worked on the matter ? Could you have a look at it ?

2024-05-23 11:57 UTC, yosa-odoo requested changes
Hello

Thanks for the fix :) 

Why not checking if `not l.is_downpayment`?

Also, could you add a test ?

2024-05-27 11:46 UTC, aamo-odoo commented
> Hello
> 
> Thanks for the fix :)
> 
> Why not checking if `not l.is_downpayment`?
> 
> Also, could you add a test ?

Hello @yosa-odoo 

Thanks for the suggestion :)

I tried implementing your suggestion of using ``l.is_downpayment`` and ``l.product_template_id``. However, this caused the test case to fail because the ``is_downpayment`` and ``product_template_id`` fields do not exist in the ``purchase.order.line`` model. Since ``account.accrued.orders.wizard`` is a ``TransientModel``, it only considers the model on which the wizard is called. Therefore, it is better to use a fixed value like ``0.1`` instead of a fields.

2024-05-29 07:20 UTC, yosa-odoo commented
Hello @aamo-odoo,

I'm not really a fan of it. I don't find it explicit enough that we are not counting the downpayment because the quantity is 0.

What about ? It is not really elegant but at least it is explicit:
```diff
@@ -167,7 +167,7 @@ class AccruedExpenseRevenue(models.TransientModel):
                     o.order_line.with_context(accrual_entry_date=self.date)._compute_untaxed_amount_invoiced()
                     o.order_line.with_context(accrual_entry_date=self.date)._compute_qty_to_invoice()
                 lines = o.order_line.filtered(
-                    lambda l: l.display_type not in ['line_section', 'line_note'] and
+                    lambda l: l.display_type not in ['line_section', 'line_note'] and (is_purchase or not l.is_downpayment) and
                     fields.Float.compare(
                         l.qty_to_invoice,
```
Your test passes with it. Maybe, you should also add a test for the purchase order flow so make sure it does not break (if not already existing; I did not understand what test you are referring to with "this caused the test case to fail")

2024-05-29 09:19 UTC, aamo-odoo commented
Hello @yosa-odoo 

I did not check for ``is_purchase`` which caused the test for the ``purchase.order.line`` model to fail. It was my mistake.

Also, I have updated the code, Can you have a look? 🙂 

Thanks for the suggestion :)

2024-06-03 13:37 UTC, yosa-odoo commented
@aamo-odoo can you add a test for the purchase order scenario?

2024-06-04 11:10 UTC, aamo-odoo commented
> @aamo-odoo can you add a test for the purchase order scenario?

Hello @yosa-odoo 
I have checked the Purchase Order but I can't find a scenario similar to the Sales Order.

2024-06-04 11:35 UTC, aamo-odoo commented
@yosa-odoo 

There is already a test for ``Accrued Expense Entry`` at line [1]. However, what I want to say is that the scenario for ``Down Payment`` does not exist in the ``Purchase Order``. As a result, the product name in the order lines will not remain empty.

[1]: https://github.com/odoo/odoo/blob/88ae8754356d86e50a3c2e7bc2290f15a91c3d14/addons/purchase/tests/test_accrued_purchase_orders.py#L9

2024-06-04 11:45 UTC, yosa-odoo commented
@aamo-odoo I know that there is no down-payment for purchase order. What I mean, is that we want to make sure the fix does not break the purchase flow. Testing the purchase order one (with the expected values) does not seem far fetched in my opinion. 

But this is a pre-review, I'll let the final reviewer decide

2024-06-04 11:58 UTC, yosa-odoo approved these changes
LGTM for the pre-review

2024-06-10 08:53 UTC, dbkosky approved these changes
Nice, thanks for adding a test too :+1: 
I'm passing this on to a colleague who can merge it.

2024-06-12 12:33 UTC, FlorianGilbert requested changes

2024-06-12 12:33 UTC, FlorianGilbert commented on addons/sale/tests/test_accrued_sale_orders.py
> +    def test_product_name_in_accured_revenue_entry(self):
accured ? :nerd_face:

2024-06-12 12:33 UTC, FlorianGilbert commented on addons/sale/tests/test_accrued_sale_orders.py
> +            'active_ids': [self.sale_order.id],
Another way of doing this
```suggestion
            'active_ids': self.sale_order.ids,
```

2024-06-12 12:33 UTC, FlorianGilbert commented on addons/account/wizard/accrued_orders.py
>                  lines = o.order_line.filtered(
We definitely have to add a comment to explain what we're doing here
Why `is_purchase or not l.is_downpayment` ? Please explain it in a comment

2024-06-13 04:47 UTC, aamo-odoo commented on addons/sale/tests/test_accrued_sale_orders.py
> +    def test_product_name_in_accured_revenue_entry(self):
oops 🙈

2024-06-13 04:51 UTC, aamo-odoo commented
Hey @FlorianGilbert 

Requested changes are done ✅ 
Please have a look 

Thanks 🙂

2024-06-18 06:09 UTC, FlorianGilbert approved these changes
Nice, thank you :)
@robodoo r+

2024-06-18 08:20 UTC, closed without merging