[FIX] l10n_au: Deactivate TPAR Taxes
odoo/odoo pull request #165321
Opened 2024-05-14 02:04 UTC by mhch-odoo

TPAR is not commonly used and makes it difficult to search for taxes in Many2one fields. This commits sets them to inactive by default.

Task# 3782518

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-14 02:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165321).

2024-05-16 01:03 UTC, vin-odoo requested changes
Hi!
I'd prefer if you use True & False like we do in the other localizations :)
It's clearer to me.
Thanks!

2024-05-16 04:46 UTC, vin-odoo requested changes

2024-05-16 04:46 UTC, vin-odoo commented on addons/l10n_au/data/template/account.tax-au.csv
> +"","","","","","","","","","","","","tax","refund","au_21380","l10n_au.tax_withheld_tag","True"
close but the field should only be set on the tax itself and not on the repartition lines :)

2024-05-16 08:42 UTC, vin-odoo approved these changes
Thanks!

@robodoo r+

2024-05-16 18:57 UTC, robodoo commented
@mhch-odoo @vin-odoo staging failed: ci/l10n on 6d76335fe9f7cfe4a68c7d5165a035901139b1b8 (view more at https://runbot.odoo.com/runbot/build/62614702)

2024-05-17 00:17 UTC, vin-odoo commented
@mhch-odoo Hi! Seems like this is breaking some report tests 😅 Could you take a look? thanks

2024-05-17 01:43 UTC, mhch-odoo commented
@robodoo r-

2024-05-17 03:56 UTC, vin-odoo commented
@robodoo r+

2024-05-17 05:28 UTC, closed without merging