[IMP] web, *: review z-index utilities
odoo/odoo pull request #165568
Opened 2024-05-15 09:21 UTC by chgo-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-15 09:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165568).

2024-05-15 12:57 UTC, chgo-odoo commented
Hello @pparidans, follow-up of the z-index utilities discussion, here is a PR that removes the custom utilities in favor of BS default. I replaced the occurrences of `z-index-0` & `z-index-1` I found is our `.xml` and `.js` files (I was actually surprised there are not that many occurrences ^^)

It would be nice to include within the freeze if you find some time to have a look at this PR and its enterprise counterpart.

Huge thanks !

2024-06-17 13:50 UTC, chgo-odoo commented
Hello @pparidans, I think this PR is ready now, could you have a look at it, please?

I created an upgrade PR as discussed but AFAIK there's no `z-index-*` class in our snippets. I guess the upgrade PR can still be helpful in case a user applied some utilities there, let me know if we don't need that PR at all !

Thanks !

2024-06-19 13:11 UTC, pparidans requested changes
It looks good to me! :+1: 

Could you rebase your branches and check for remaining occurrences (I found 2 in `addons/mail/static/src/core/common/discuss.xml` but very recently merged :grimacing: ).

2024-06-19 13:17 UTC, chgo-odoo commented
Thanks @pparidans, branches have been rebase. About the upgrade PR, should I keep it open? AFAIK there is no `z-index-X` applied on our snippet but as mentioned earlier, maybe we want to ensure users didn't apply one?

2024-06-19 13:24 UTC, pparidans commented
> About the upgrade PR, should I keep it open? AFAIK there is no `z-index-X` applied on our snippet but as mentioned earlier, maybe we want to ensure users didn't apply one?

I would still keep it, though.

2024-06-19 13:25 UTC, pparidans approved these changes
LGTM
@robodoo r+

2024-06-19 15:00 UTC, robodoo commented
@chgo-odoo @pparidans linked pull request(s) odoo/upgrade#6078 not ready. Linked PRs are not staged until all of them are ready.

2024-06-20 09:54 UTC, KangOl commented
Can you please rebase your branch(es) and fix the conflicts?

2024-06-20 10:40 UTC, chgo-odoo commented
@KangOl Branches have been rebased and conflicts solved, thanks !

2024-06-20 11:55 UTC, pparidans commented
@robodoo r+

2024-06-21 00:55 UTC, closed without merging