[16.0][REF] sale_stock: Avoid calling sale.order.line.expected_date twice
odoo/odoo pull request #165519
Opened 2024-05-14 18:05 UTC by grindtildeath

Computation of sale.order.expected_date is done in sale module and overridden in sale_stock.
Both function are doing mostly the same, except when it is selecting the min or max date from the sale order lines dates list based on the picking policy.

Use a dedicated function to return the selection function to be used so that the override in sale_stock does not have to repeat the code from the sale module.

Description of the issue/feature this PR addresses:

Duplicated code not easy to extend

Current behavior before PR:

Calling twice sale.order.line._expected_date function

Desired behavior after PR is merged:

Calling once sale.order.line._expected_date function

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-14 18:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165519).

2024-05-14 18:20 UTC, grindtildeath commented
ping @jem-odoo @nim-odoo @Feyensv 

Can you one of you guys please have a look? :pray:

2024-05-17 15:07 UTC, Feyensv requested changes
Change seems legit, but is there a real (performance) issue here ?
If not, I believe this should target `master` instead.

2024-05-17 15:07 UTC, Feyensv commented on addons/sale/models/sale_order.py
> +                order.expected_date = order._expected_date_list_select_func()(dates_list)
I don't really like handling function/methods like that.
Can't you add a method `_select_expected_date(self, expected_dates)` instead, that would be overridden in `sale_stock` to select the `min` or the `max` depending on the `picking_policy` ?

2024-05-17 15:07 UTC, Feyensv commented on addons/sale_stock/models/sale_order.py
> +        super(SaleOrder, self)._expected_date_list_select_func()
```suggestion
        super()._expected_date_list_select_func()
```

2024-05-17 17:42 UTC, grindtildeath commented
@Feyensv  Thank you very much for the review. :hugs: 

I amended the commit according to your suggestions.

There is no real performance issue with the standard implementation. However, we did customize `sale.order.line._expected_date` for a customer based on calendars and the computation is getting quite heavy. That's why a single call to `_expected_date` on this compute already helps a lot.

Anyway, if you want to merge this only in master, I'd prefer to open another PR for master. That allows us to keep targeting 16.0 here, to integrate it as a patch in our project.

Please let me know if I should close this one to open a new one targeting master.

2024-05-17 21:20 UTC, grindtildeath commented
@Feyensv I realized I had to add an extra commit to use `_expected_date` in the preparation of procurement value as having duplicated code there was breaking our customization.

IMO it makes sense to fallback on this function instead of repeating the same logic.

2024-05-21 12:07 UTC, Feyensv commented on addons/sale_stock/models/sale_order.py
> +        return res if self.picking_policy == 'direct' else max(expected_dates)
```suggestion
        if self.picking_policy == 'direct:
            return super()._select_expected_date(expected_dates)
        return max(expected_dates)
```

You forgot to pass the arg to the super call.
Also, let's avoid computing the `min` if we know we will return the `max`.

2024-05-27 13:44 UTC, Feyensv approved these changes
@robodoo r+ squash

2024-05-27 13:44 UTC, robodoo commented
Merge method set to squash.

2024-05-27 15:13 UTC, closed without merging