[FIX] l10n_cl: change account in COA and assignation
odoo/odoo pull request #165775
Opened 2024-05-16 12:56 UTC by Danisan

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

This PR replaces https://github.com/odoo/odoo/pull/164077

(odoo-dev:saas-16.3-16.0-fix-account-f29-bAgH-fw)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-16 12:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165775).

2024-05-30 07:37 UTC, rugo-odoo requested changes
Thanks for your contribution ! Just a couple comments. Also I asked a PO to make a little functional check.

2024-05-30 07:37 UTC, rugo-odoo commented on addons/l10n_cl/data/l10n_cl_chart_data.xml
> +</odoo>
We have to keep the blank line here (after `</odoo>`).

2024-05-30 07:37 UTC, rugo-odoo commented on addons/l10n_cl/data/account_fiscal_template.xml
> +            <field name="name">Compras - destinadas a generar operaciones no gravadas o exentas</field>
Names should be in english and translated in the `.po` file to the localization language. It is easier to us to maintain (we all speak english).

2024-06-04 15:02 UTC, fvz-odoo commented
@Danisan hello! could you please address @rugo-odoo's comments?

Let us know, please!

Fernando

2024-06-05 12:01 UTC, jco-odoo commented on addons/l10n_cl/data/account_fiscal_template.xml
> +    <data>
@Danisan This entire XML has been replaced by csv and templates from saas-16.3.

2024-06-05 12:01 UTC, closed without merging