[IMP] point_of_sale: add button to delete all draft orders
odoo/odoo pull request #165725
Opened 2024-05-16 08:41 UTC by shag-odoo

Before this commit :
===============
- No button to delete to draft orders in restaurant

After this commit :
=============
- Added button to delete draft orders in restaurant.

task-3918886

2024-05-16 08:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165725).

2024-05-16 11:13 UTC, paso-odoo requested changes

2024-05-16 11:13 UTC, paso-odoo commented on addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.xml
> +                </button>
visible it when module_pos_restaurant is enabled

2024-05-16 11:13 UTC, paso-odoo commented on addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
> +        this.dialog.add(dialogType, {
```suggestion
        this.dialog.add(DeleteConfirmationDialog, {
```

2024-05-23 08:42 UTC, vlst-odoo requested changes

2024-05-23 08:42 UTC, vlst-odoo commented on addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
> +}
There is no need to create a new dialog for this. You can simply use the confirmation dialog

2025-05-30 09:10 UTC, closed without merging