[FIX] point_of_sale: missing model comment in PO file
odoo/odoo pull request #165761
Opened 2024-05-16 12:02 UTC by mizosoft

Issue
----

POS payment methods that are already translated don't have their translation show up.

Steps
-----

Go to Point of Sale -> New/Continue Session -> Add something to pay for -> Click on "payment". The listed payment methods are not translated if you chose another language.

Cause
-----

Although the terms were translated, they were not showing up because the model referral comment wasn't there.

opw-3880510

2024-05-16 12:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165761).

2024-06-05 13:37 UTC, nle-odoo requested changes
Hi,


I'm not sure how this could work. I don't understand where "_599bee1f" and "_b02dec91" are coming from but I could be missing something.

As far as I can tell, the language of the name of `pos.payment.method` is determined here:

https://github.com/odoo/odoo/blob/17.0/addons/point_of_sale/models/pos_config.py#L681-L692

and should be set to the language used when the module is being installed. Without any change, if I put myself in french, then install "point of sale" module, I get the name in french. Same for other languages:

![2024-06-05-153126_361x472_scrot](https://github.com/odoo/odoo/assets/9977887/aa5ae814-15f2-4c9e-9e00-93446639c926)

If I installed odoo with only one language (for example on saas) and installed point of sale module from terminal (`-i point_of_sale --load-language="fr_FR" -l "fr_FR"`) I get the same result.

So unless I'm missing something, the current change does nothing and either:

- things work ok actually => maybe it's ok to have it only in one language
- or if we really wanted to have it translated, there could be some code inside "assign_payment_journals" that would also add translation when creating the pos.payment.method records.

2024-06-06 10:50 UTC, mizosoft commented
Hi @nle-odoo.

I've extracted these strings from the exported model translations. So the "_599bee1f" and "_b02dec91" are added automatically by Odoo. I have found them weird too but saw that they actually worked. 

Note that the problem is not that the strings are translated when the app is installed. The problem is that the strings don't change when you change the language after the app is installed. In fact, I think that the fact that the strings get translated with language at installation is actually a bug. For instance, you're using french, the implementation will store the french values as english and will result in the following structure for the translatable field: 

```json
"field: {
  "en_US": "French translation, not English!"
}
```

2024-06-10 10:38 UTC, nle-odoo commented
> I've extracted these strings from the exported model translations. So the "_599bee1f" and "_b02dec91" are added automatically by Odoo. I have found them weird too but saw that they actually worked.

Ok maybe you are correct and I am not understanding something.

There is a export system that will create XML ID for records. But these XML will be for module "__export__" and not "point_of_sale" as you have as far as I could tell. And I thought they would work only for your own instances where you created the XML ID (in ir_model_data table) where you exported. But if it works, seems good to me.

2024-06-17 10:05 UTC, mizosoft commented
@nle-odoo do you think this still requires changes?

2024-07-04 11:48 UTC, mizosoft commented
Hi @nle-odoo, can you give me an update here please.

2024-07-10 11:26 UTC, nle-odoo commented
I still don't understand your fix but you could ask a review.

If I try without your fix to install point of sale in database in french (with new database and command line parameters: `-i point_of_sale --load-language="fr_FR" -l "fr_FR"`), I get everything correctly translated because as I said, the lang used when the payment method are created is used.

> ![2024-07-10-131724_959x1038_scrot](https://github.com/odoo/odoo/assets/9977887/d5940360-88c5-470b-9f83-ed20ca39acae)


Without your fix I have this in the database:

```sql
17e=# select id, name from pos_payment_method;
 id |                   name                   
----+------------------------------------------
  2 | {"en_US": "Banque"}
  3 | {"en_US": "Compte client"}
  1 | {"en_US": "Espèces", "fr_FR": "Espèces"}
```
and with your fix (and modifying the fr.po corresponding file) I get exactly the same résult:

```sql
17e=# select id, name from pos_payment_method;
 id |                   name                   
----+------------------------------------------
  2 | {"en_US": "Banque"}
  3 | {"en_US": "Compte client"}
  1 | {"en_US": "Espèces", "fr_FR": "Espèces"}
```
So as far as I can tell, it seems that your fix does and change nothing. But I could be missing something so if you think it really does you could ask for a review from pos team.

2024-08-26 11:11 UTC, sbel-odoo commented
Closing this PR as the behavior is expected. The payment methods we are talking about are created using the `create` function, thus the records don't have xml ids. Data is translated when adding new language only if it has xml ids. However, if the database is using a different language then English when installing PoS, the record will use the language data. After that, adding new languages won't add translations to the record. Translations have to b eadded manually on the records.
-> Normal behavior

2024-08-26 11:11 UTC, closed without merging