[FIX] web: add missing ARIA attributes to AutoComplete component
odoo/odoo pull request #165903
Opened 2024-05-17 02:53 UTC by luisg123v

When filling a relational field, suggestions are displayed using the AutoComplete component. Problem is, when choosing any suggestion, some ARIA attributes are missing for assistive technologies to know what is the currently-selected suggestion. That because the actual focus is always on the  field's input, while the actually-selected suggestion is highlighted by toggling classes, which makes not possible anymore to know what is the selected suggestion for e.g. screen reader users.

This commit adds such attributes.

This is similar to what was done on 9764e6f7 for the command palette to handle search results on the home screen.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-17 02:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/165903).

2024-05-18 20:03 UTC, luisg123v commented
Hi @BastienFafchamps,

Thanks for the suggestion, I've added a few validations to ensure ARIA attributes are being set properly.

Could you review again, please?

CC @moylop260 @desdelinux @nhomar

2024-05-28 16:56 UTC, luisg123v commented
Hi @BastienFafchamps,

Could you review again, please?

CC @pparidans

2024-06-18 21:52 UTC, desdelinux commented
LGTM This is ready @BastienFafchamps @ged-odoo @pparidans @fdardenne

2024-06-19 10:49 UTC, pparidans requested changes
Thank you for your contribution.
I only have a few little remarks, nothing fancy though :wink:

2024-06-19 10:49 UTC, pparidans commented on addons/web/static/src/core/autocomplete/autocomplete.js
> +        let source = this.sources[sourceIndex];
Those variables are never reassigned ; use `const` instead of `let`.

2024-06-19 10:49 UTC, pparidans commented on addons/web/static/src/core/autocomplete/autocomplete.js
> +            return;
A getter should have an explicit return value. In this case, it implicitly returns `undefined` but still.
cf. https://eslint.org/docs/latest/rules/getter-return

2024-06-19 16:46 UTC, luisg123v commented
Hi @pparidans,

Thanks for the feedback! I've applied all your suggestions.

Could you review again, please?

Regards,

2024-06-20 07:29 UTC, pparidans approved these changes
@robodoo r+

2024-06-20 10:05 UTC, closed without merging