[IMP] core, web: Content-Security-Policy on all Streams
odoo/odoo pull request #166532
Opened 2024-05-23 13:07 UTC by Julien00859

The Content-Security-Policy is a header that help browsers filter the new requests the downloaded document is allowed to perform. For a css file, you could authorize the css file to perform new requests to downloads fonts or background images and restrict the rest. For most documents however all new requests should be prohibited, this is possible with the value `default-src "none"`.

That header was only set by the framework on images. Developers were responsible to add that header on their own controller when those controllers were used to download other kind of documents.

It turns out that most developer nowadays use http.Stream in those documents-driven controllers but forget to manually add CSP where it is actually necessary.

In this work we add the CSP header on all response generated by the Stream API. This help with the common case where that header is welcome. For the less common case where it is not, it is advised to simply remove it from the response. A simple `del response['Content-Security-Policy']` is enough.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-23 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/166532).

2024-05-24 11:01 UTC, tbe-odoo approved these changes

2024-05-24 11:17 UTC, tbe-odoo requested changes
Changing review status after discover it breaks websocket

2024-06-18 14:09 UTC, mart-e approved these changes

2024-07-09 11:09 UTC, tbe-odoo approved these changes

2024-07-09 11:13 UTC, mart-e commented
@robodoo r+ rebase-ff

2024-07-09 11:14 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-07-09 15:31 UTC, closed without merging