[FIX] mrp_subcontracting: Reciept show details
odoo/odoo pull request #166702
Opened 2024-05-24 13:27 UTC by HANNICHE-Walid

Steps to reproduce:
- Create a subcontracted product tracked with unique serial number and untracked components
- Create a purchase order and confirm
- go to the receipt, click on the detailled operations button

Bug:
The record components view opens which prevents the user from generating multiple serials at once

Fix:
only display the record components view if it's mandatory other wise that view can still be accessed by the dedicated 'record components' button

opw-3905188

2024-05-24 13:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/166702).

2024-06-26 13:15 UTC, Sehnde reviewed
I understand the idea behind this change but I think more should be changed:
(FYI: test is subcontracted bom, test 2 is normal bom)
![screenshot-127 0 0 1_8069-2024 06 26-15_04_04](https://github.com/odoo/odoo/assets/43445409/c676c43f-76c1-409b-928a-598fd0bfc8d6)
![screenshot-127 0 0 1_8069-2024 06 26-15_04_57](https://github.com/odoo/odoo/assets/43445409/769350e1-8e27-4dc8-8b2a-26dc13683570)

- the burger behavior changes between draft and ready state
- also, it is visible in draft state (it shouldn't)
- the assign serial button disappears for subcontracted products

and now I'm wondering if it should be done as a bugfix or a PR in master. After all, the users stills have the 'Detailed Operations' button at the top of the view so it's not a blocking issue.

2024-06-26 13:56 UTC, HANNICHE-Walid commented
> the users stills have the 'Detailed Operations' button at the top of the view so it's not a blocking issue.

that button shows all the SMLs but we want to use the view to assign the serial numbers on the moves which is not possible right now

the alignment problem is a separate issue that can be handled in another PR

2024-06-27 13:37 UTC, Sehnde requested changes
> the alignment problem is a separate issue that can be handled in another PR

Ok, then please add the following to this PR:
- make the burger button invisible in 'draft' state
- make the assign serial button visible in 'ready' state

Nice to have:
- if the burger button is forced to be visible in draft -> make it have the same behavior as in ready

2024-07-23 15:50 UTC, HANNICHE-Walid commented
> * make the burger button invisible in 'draft' state
> 
> * make the assign serial button visible in 'ready' state

https://github.com/odoo/odoo/pull/91460
looking at this I believe this was done on purpose

2024-10-18 08:03 UTC, closed without merging