[IMP] hr_skills: convert tests to hoot
odoo/odoo pull request #166816
Opened 2024-05-27 08:46 UTC by ramh-odoo

This commit aims to convert QUnit tests which rely on hr_skills/test_utils to hoot.

Part of Task-3818666

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-27 08:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/166816).

2024-05-27 09:35 UTC, rapr-odoo requested changes
There seems to be quite some linting issues. So, please enable the linter on your system and resolve linting issues.

2024-05-27 09:35 UTC, rapr-odoo commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +            .getAttribute("data-src")
could use `queryAllAttributes`

2024-05-28 06:13 UTC, rapr-odoo reviewed
Small changes

2024-05-28 06:13 UTC, rapr-odoo commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +            </kanban>`,
indentation

2024-05-28 06:13 UTC, rapr-odoo commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    "many2one_avatar_employee widget in kanban view with skills on avatar card", async () => {
linting issue.

2024-06-26 10:07 UTC, rapr-odoo approved these changes

2024-07-19 10:17 UTC, tsm-odoo commented on addons/hr_skills/static/tests/hr_skills_test_helpers.js
> +    HrEmployee,
Some of those models belong to the hr module. They should be imported from hr.

2024-07-19 10:21 UTC, tsm-odoo commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    this.data = {};
Very ugly `this` reference that would not work if it wasn't for this lambda. Better have a let on top of the file.

2024-07-19 10:21 UTC, tsm-odoo commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    await openKanbanView("m2o.avatar.employee", {
Do we really need mail test helpers? If not it would be better not to rely on them.

2024-07-23 16:12 UTC, alexkuhn commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    await contains(".o_avatar_card .o_employee_skills_tags > .o_tag", { count: 2 }); // Skills should be listed in the card
I don't like lots of whitespace. This makes the code longer than it should, usually adds scrolling when we shouldn't. And when there are many tests, it's easier to sport beginning/end of test thanks to whitespaces. With arbitrary whitespaces everywhere, the shape helps no one and it's just makes readability worse.

2024-07-23 16:12 UTC, alexkuhn commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    ).toBe(`/web/image/hr.employee/${data.employeePierreId}/avatar_128`);
Comment is useless, the assertion of `data-src` is obviously doing that. Everyone knows `img [src=url]` will show an image with `url`. And the url has semantics of pierre employee's avatar.

2024-07-23 16:12 UTC, alexkuhn commented on addons/hr_skills/static/tests/many2one_avatar_employee.test.js
> +    await contains(".o_avatar_card .o_employee_skills_tags > .o_tag", { count: 2 }); // Skills should be listed in the card
Everything is obvious without comments. The comments just make reading more complex than it should. Just drop the comments.

Too much comments kill the purpose of few relevant and important comments.

2024-07-24 09:26 UTC, alexkuhn approved these changes
@robodoo r+

2024-07-24 11:27 UTC, tivisse commented
Hello.

Why in version 17.2 ? 

This is not fixing anything right ?

2024-07-24 13:51 UTC, alexkuhn commented
@tivisse This is when HOOT has been introduced and also mail test have been converted.

Some people prefer to cover this version over just master, notably because HOOT bugs are caught sooner (HOOT bug fixes are still ongoing and targeting 17.2), and also people targeting a branch in 17.2 that would like some test coverage are highly encouraged to do with HOOT (and doing by copy is still very popular).

I wouldn't mind this if this was cost-free, but merging code in stable with forward-port slows us down quite drastically, because each foward-port is slow and this is distracting to adapt for conflicts, ensure everything still works as it should, etc. when this happens every hour (up to a day or 2 even sometimes, when mergebot is struggling hard).

Personally I wouldn't do that in 17.2 but I failed to convince people not doing that... And insisting more would result to me wasting time so I just let go for just some HOOT test conversions.

2024-07-24 15:31 UTC, closed without merging