[IMP] l10n_pl: add tag_ids to CoA
odoo/odoo pull request #166875
Opened 2024-05-27 13:32 UTC by Megaaaaaa

Description of the issue/behavior this commit addresses:

Currently, the Polish CoA doesn't use tax_tags which makes it pretty hard to add new accounts.

---

Desired behavior after this commit is merged:

The Polish CoA uses tax_tags for his accounts and the reports (Balance Sheet Micro and Small et Profit & Loss Micro and Small) use those tax_tags to be built.

---

Enterprise PR:
task-3950432

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-27 13:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/166875).

2024-08-08 09:00 UTC, svfu-odoo reviewed
preliminary comments

2024-09-24 11:51 UTC, svfu-odoo requested changes
:+1:  Just a few small suggestions.
I think the commit / PR message should also mention that new accounts were added and why (for the new BS / P&L I think) (if it is not too many / too much effort maybe list them since it is a bit difficult to see from the diff)

2024-10-10 14:21 UTC, svfu-odoo requested changes
Only some nitpicks and translation suggestion

2024-10-21 10:00 UTC, svfu-odoo requested changes
It is basically good. Just the translations of the tags do not work for me. Maybe they have to be added in the csv? Or is it not possible; then Polish names would be better I think?

2024-10-21 15:27 UTC, Megaaaaaa commented
> It is basically good. Just the translations of the tags do not work for me. Maybe they have to be added in the csv? Or is it not possible; then Polish names would be better I think?

Well i don't know what to tell you, it works just fine for me. Are you sure you selected the right language and checked the box to overwrite existing terms ?

![image](https://github.com/user-attachments/assets/ea06c883-bf42-404b-adeb-118983297a07)

2024-10-22 07:10 UTC, svfu-odoo commented
It is working indeed, sorry!

2025-01-16 13:53 UTC, closed without merging