[FIX] account: chart template when no country
odoo/odoo pull request #166896
Opened 2024-05-27 14:43 UTC by malb-odoo

Before this commit, when creating a company and directly installing a chart template without putting a country first, the installation of the chart template was giving a traceback.
By updating the country of the company by the one of the chart template, the issues will not happen again.

task: 3945833

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-31 14:27 UTC, tsb-odoo commented on addons/account/models/chart_template.py
> +        chat_template_mapping = self._get_chart_template_mapping()[template_code]
miaou ?

2024-06-10 09:49 UTC, dbkosky approved these changes

2024-06-11 11:28 UTC, FlorianGilbert requested changes
Small nitpick and should be good :)

2024-06-11 11:28 UTC, FlorianGilbert commented on addons/account/tests/test_chart_template.py
> +        self.assertTrue(not company.country_id)
```suggestion
        self.assertFalse(company.country_id)
```

2024-06-17 11:51 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-06-17 23:18 UTC, robodoo commented
@malb-odoo @FlorianGilbert staging failed: ci/l10n on 82ed3d87c7468b303e687cb6b5a6e9d5d85c6440 (view more at https://runbot.odoo.com/runbot/build/64149995)

2024-06-18 06:16 UTC, malb-odoo commented
@robodoo retry

2024-06-18 11:46 UTC, gawa-odoo commented
@robodoo r-

2024-06-18 11:49 UTC, gawa-odoo commented
Forgot to write a message.
It breaks the l10n staging each time https://runbot.odoo.com/runbot/build/64149995

2024-06-24 09:52 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-06-24 11:46 UTC, closed without merging