[FIX] approve_expense_sheets return value
odoo/odoo pull request #167153
Opened 2024-05-29 08:15 UTC by kdmwangi

Description of the issue/feature this PR addresses:
the approve_expense_sheets method was not rendering the notification object returned by _do_approve method
Current behavior before PR:
the approve_expense_sheets method was not rendering the notification object returned by _do_approve method
Desired behavior after PR is merged:
To display the notification window 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-29 08:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/167153).

2024-05-29 12:24 UTC, malb-odoo requested changes
Hello thanks for this pr ! :smile: Just a small problem with the commit title, you can follow that convention here https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html

Also it appears it's missing the CLA ==>  https://github.com/odoo/odoo/blob/17.0/doc/cla/sign-cla.md

2024-05-30 20:16 UTC, kdmwangi commented
> Hello thanks for this pr ! 😄 Just a small problem with the commit title, you can follow that convention here https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html
> 
> Also it appears it's missing the CLA ==> https://github.com/odoo/odoo/blob/17.0/doc/cla/sign-cla.md

i had opened another PR with CLA I hope it works

2024-05-31 06:54 UTC, malb-odoo commented
> > Hello thanks for this pr ! 😄 Just a small problem with the commit title, you can follow that convention here https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html
> > Also it appears it's missing the CLA ==> https://github.com/odoo/odoo/blob/17.0/doc/cla/sign-cla.md
> 
> i had opened another PR with CLA I hope it works

@kdmwangi Can you link it here :smile:

2024-05-31 08:25 UTC, kdmwangi commented
> > > Hello thanks for this pr ! 😄 Just a small problem with the commit title, you can follow that convention here https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html
> > > Also it appears it's missing the CLA ==> https://github.com/odoo/odoo/blob/17.0/doc/cla/sign-cla.md
> > 
> > 
> > i had opened another PR with CLA I hope it works
> 
> @kdmwangi Can you link it here 😄

#167170

2024-05-31 08:46 UTC, malb-odoo approved these changes
Apart from the CLA that need to be approved it LGTM thanks for this :smile: 
@JulienAlardot Can you check to be sure it's good for you :smile:

2024-06-03 12:35 UTC, mart-e commented
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `44490545+kdmwangi@users.noreply.github.com`
- you are signing _for_ the address `k…@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

2024-06-03 14:24 UTC, malb-odoo commented
Like @JulienAlardot it would be nice to retarget the PR in 15.0, if you want i can create the PR and do the forward port up to 16.0 :smile:

2024-06-03 14:44 UTC, mart-e commented
@malb-odoo yes, please :pray:  You can apply the diff in 15.0 with the CLA file (don’t forget to keep authoring with the gmail address).
If the expense patch is not needed above 16.0, you can still make the pr up to master and keep only the cla file in 17+ versions.
Closing this one then.

2024-06-03 14:44 UTC, closed without merging