[FIX] website_sale: clear session after payment with ewallet
odoo/odoo pull request #167133
Opened 2024-05-28 23:51 UTC by kawkb

## Issue:
- When purchasing consecutive appointments on the website using eWallet, an error occurs: "It is forbidden to modify a sales order which is not in draft status."

## Steps To Reproduce:
- Create an eWallet program and generate a coupon for the test user.
- On the eCommerce site, navigate to the "Appointments" tab.
- Select a paid appointment and pay using eWallet credit.
- After completing the payment, return to the "Appointments" tab.
- Encounter the error: "It is forbidden to modify a sales order which is not in draft status."

## Solution:
- In `shop_payment_validate`, when an order is fully paid using a discount or eWallet, the eCommerce website context are not cleared.
- To fix this, call the `sale_reset` method before redirecting to the SO page.

opw-3885533

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-28 23:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/167133).

2024-06-03 07:56 UTC, abla001 requested changes
LGTM! Just a small note: could you please modify the commit message to clarify that another appointment needs to be purchased and paid for to get the error.

2024-06-10 08:01 UTC, Demesmaeker approved these changes
Hello, 
I don't see anything wrong with it, it seems legit, but then, it mostly needs an eCommerce point of view, so I'll let them manage it ^^
It looks like the problem arise with all products, reading your test, and not just appointment, so might be better to update the description too. =]
Have a nice day

2024-06-10 08:03 UTC, abla001 approved these changes

2024-06-12 16:13 UTC, chevalierv commented on addons/website_sale/controllers/main.py
> +            request.website.sale_reset()
Hello @kawkb 

Could you apply this suggestion?

2024-06-14 12:03 UTC, chevalierv approved these changes
Hello @kawkb 

Thanks for your investigation on this!

@robodoo delegate+

Have a nice day!

2024-06-17 12:10 UTC, kawkb commented
@robodoo r+

2024-06-17 21:49 UTC, closed without merging