[IMP] point_of_sale: email format for sending the receipt
odoo/odoo pull request #167157
Opened 2024-05-29 08:34 UTC by paan-odoo

Before this commit:
==========
- The receipt email content is insufficient and inadequate.

After this commit:
==========
- Receipt emails contain sufficient and satisfactory content.

task-3764070

2024-05-29 08:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/167157).

2024-05-30 06:24 UTC, paso-odoo requested changes

2024-05-30 06:24 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +            _("<p>Dear %(client_name)s,<br/>Here is your Receipt%(isInvoiced)s for \
```suggestion
            _("<p>Dear %(client_name)s,<br/>Here is your Receipt%(is_invoiced)s for \
```

2024-05-30 06:24 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +            'isInvoiced': " and Invoice" if self.mapped('account_move') else "",
```suggestion
            'is_invoiced': " and Invoice" if self.account_move else "",
```

2024-06-04 08:04 UTC, vlst-odoo approved these changes

2024-06-04 11:29 UTC, vlst-odoo commented
robodoo r+

2024-06-04 15:05 UTC, closed without merging