[FIX] sale_stock: Prevent negative delivered qty in multi-step delivery returns
odoo/odoo pull request #167271
Opened 2024-05-29 19:05 UTC by kawkb

Issue:
    - When multi-step delivery is enabled, validating then issuing a partial or full return on the first step (E.G. WH/Stock to WH/Output) results in negative values on the SO delivered quantity field.

Steps To Reproduce:
    - Enable multi-Step routes in settings.
    - Go to warehouses and on the main Warehouse set Outgoing Shipments to "Send goods in output and then deliver (2 steps)"
    - go to a product category and set up the 2 steps route on it.
    - create a SO and select a product with a quantity more than 1 from the category save then validate
    - the first delivery will appear (from WH/Stocl to WH/Output)
    - Validate it and then press return and either fill a partial or full return.
    - go back to the sales order page you will notice the the delivered quantity is negative of what was returned on the previous step which is wrong.

Solution:
    - The strict mode in sale_stock's `_get_outgoing_incoming_moves` method only considers moves strictly delivered to customers. Despite calling this method with strict=True in `_compute_qty_delivered`, the issue persisted.
    - The problem was identified at the end of `_get_outgoing_incoming_moves`, where the method incorrectly accounts for returns. It checks that the return destination's usage is not "customer" but fails to verify if the source is "customer."
    - Added a condition to ensure that the source location's usage is "customer" for return moves.

opw-3933009

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-03 07:00 UTC, adwid requested changes
Could you add a test please ?

2024-06-13 12:03 UTC, HANNICHE-Walid approved these changes
LGTM 
bug introduced by the change in the way multi step works in 17.2

2024-06-13 12:06 UTC, HANNICHE-Walid commented
https://github.com/odoo/odoo/pull/165528/files#diff-9403d95761b7209bf0d2d4e0c9c6a3c48b2ecf3f70394751305ab993b7a9ae95R140
this line should be updated too to account for kits

2024-07-03 07:57 UTC, Whenrow commented
Seems that it's already fixed here https://github.com/odoo/odoo/pull/170787

2024-07-04 10:05 UTC, kawkb commented
Hello @Whenrow thank you for your review, shouldn't I keep the changes that account for kits as Walid suggested?

2024-07-23 23:42 UTC, kawkb commented
closing this PR since the issue is already fixed

2024-07-23 23:42 UTC, closed without merging