Master daterange test pipu
odoo/odoo pull request #167503
Opened 2024-05-31 12:40 UTC by pipu-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-05-31 12:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/167503).

2024-06-04 14:33 UTC, Iucapad approved these changes
Good job @robodoo r+

2024-06-04 16:14 UTC, Arcasias requested changes

2024-06-10 14:07 UTC, Arcasias approved these changes
@robodoo r+

2024-06-10 18:50 UTC, closed without merging