[FIX] website_sale_product_configurator: price are wrongly send to GA
odoo/odoo pull request #167962
Opened 2024-06-04 09:27 UTC by fmdl

Description of the issue/feature this PR addresses:
- Intall website_sale_product_configurator
- Create a product A with price 3 999.00 €
- Add an optional product on product A
- Go to shop page
- Go to product A
- Add to cart
- A modal popup appear
- Finelize cart --> Issue the price send to datalayer is 3.
Because "3 999,00" is send in the json, endead 3999.00.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-04 09:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/167962).

2024-06-04 12:47 UTC, ltinel requested changes
Thanks for the fix, looks good! Could you update the commit/PR title to mention both of the modules you're modifying?

2024-06-04 12:47 UTC, ltinel commented on addons/sale_product_configurator/views/templates.xml
> +                    <input type="hidden" class="product_price" t-att-value="combination_info['price']"/>
Could you do the same for the optional products (below) as well?

2024-06-04 12:47 UTC, ltinel commented on addons/website_sale_product_configurator/static/src/js/website_sale_options.js
> +                'price': el.getElementsByClassName('product_price')[0].value,
I think it's better to keep the `parseFloat` around this:
```suggestion
                'price': parseFloat(el.getElementsByClassName('product_price')[0].value),
```

2024-06-04 14:08 UTC, ltinel commented
Now that I think of it, maybe we should fix this from version 15 onwards.

2024-06-04 20:37 UTC, fmdl commented
I move in 15.0 ?

2024-06-05 09:44 UTC, fmdl commented
@ltinel move in 15.0

2024-06-05 10:51 UTC, ltinel commented
Thanks @fmdl. One last thing: could you update your commit/PR title to include both modified modules? E.g. `[FIX] *sale_product_configurator: ...`

2024-06-05 10:51 UTC, ltinel approved these changes

2024-06-05 10:54 UTC, chevalierv commented
Hello @ltinel @fmdl 

I'll update the PR message directly to fit our guidelines, there is no need to update the commit :)

Thank you both for your work on this PR

@robodoo delegate=ltinel squash

Have a nice day!

2024-06-05 10:55 UTC, ltinel commented
@Feyensv, this LGTM. Could you r+ if you have no remaining comments? Thanks!

2024-06-05 10:55 UTC, robodoo commented
Merge method set to squash.

2024-06-05 11:03 UTC, ltinel commented
@robodoo r+

2024-06-05 11:03 UTC, ltinel commented
@robodoo r-

2024-06-05 12:55 UTC, ltinel requested changes
@fmdl unfortunately, this fix won't work. Sorry for not noticing earlier.

The problem is that you're modifying templates in a stable version. A user who already has those modules installed, and who'd try to upgrade them, would run into issues because they'd only get the new JS of this PR, but not the new template (since templates are stored in the DB).

I suggest that, instead of adding new hidden inputs to the template, you simply use the `js_raw_price` span (which is already there and doesn't require you to update the template).

2024-07-22 06:27 UTC, ltinel requested changes
Almost there :)

2024-07-22 06:27 UTC, ltinel commented on addons/website_sale_product_configurator/static/src/js/website_sale_options.js
> +                'price': parseFloat(el.getElementsByClassName('js_raw_price')[0].value),
The element in not an input so it doesn't have a `value`. Could you use `textContent` instead?
```suggestion
                'price': parseFloat(el.getElementsByClassName('js_raw_price')[0].textContent),
```

2024-07-22 10:17 UTC, ltinel commented
Hi @fmdl the checks on this PR are failing because the description of your second commit doesn't follow Odoo's guidelines. Could you squash it with the first one and take the description of the first one?

2024-08-19 16:37 UTC, ltinel approved these changes
Thanks for the fix :)

2024-08-20 06:49 UTC, ltinel commented
@fmdl Could you undo the template changes? They're not strictly needed and it looks like they make some of our checks fail.

Could you re-request a review from me once that's done? (otherwise I'm not notified and might miss your changes, which is also why I saw your latest changes only yesterday, sorry about that by the way)

2024-08-20 09:24 UTC, ltinel commented
@robodoo r+

2024-08-20 10:54 UTC, chevalierv commented
@robodoo retry

2024-08-20 12:06 UTC, closed without merging

2024-08-21 15:05 UTC, ltinel commented
> After this change, is the price correctly display in screen?

Yes, this change only affects tracking (e.g. Google Analytics). Moreover, the `js_raw_price` span is hidden in the view and should contain the same value as before (even if we read it from a different source).

2024-08-21 19:45 UTC, pedrobaeza commented
Thanks for the confirmation