[IMP] stock: back2basics stock thd
odoo/odoo pull request #168136
Opened 2024-06-05 09:36 UTC by jaha-odoo

In this commit:
====================
- Added new SO delivery status as 'preparation'.
- Added the ability to group by product category in vendor pricelists.
- Made the company field optional hide and the on-hand quantity  optional show in the  Lots/Serials list view.
- Improved the replenishment page to display a toast notification and refresh when clicking on a single replenish action or selecting multiple lines for mass replenishment. The refresh action now retains filters.
- In Inventory Configuration, renamed 'UOM Categories' to 'Unit of Measure' and  'Unit of Measure Categories' to 'Unit of Measure' in UOM views.
- Added a warning in settings when activating the Automatic Invoicing setting while Automatic Accounting is activated, and vice versa.
- Hide the Routes smart button when routes are not active.
- In the Purchase tab, made the variant column optional to show and preselected the current variant when adding a new line.
- When a vendor is created from a product vendor pricelist, it is now created as a company.
- Renamed 'Order Date' to 'Receipt Date' in the PO pivot view and added grouping by 'Confirmation Date'.
- When setting a parent on a product category and no products are linked to the category yet, the valuation method is now the same as the parent's method.
- Log cost changes in the chatter if made manually in the product form.
- Removed the 'New' button when viewing the list of transfers linked to a PO/SO.

task- 3850457

2024-06-05 09:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/168136).

2024-08-21 14:05 UTC, kir-odoo commented on addons/stock_account/models/product.py
> +            self.property_cost_method = self.parent_id.property_cost_method
@mohammadhossam Hy `property_cost_method` field is company-dependent true so we can't make it compute.
The other changes have been made please check

2025-09-24 12:48 UTC, dhha-odoo reviewed
Hello @sako-odoo 

LGTM 👍 Just update the commit title to include all the modules where changes were made. Thanks!

2025-09-25 05:31 UTC, dhha-odoo requested changes

2025-09-25 05:31 UTC, dhha-odoo commented on addons/sale_stock/models/sale_order.py
> +        action['context'] = dict(default_partner_id=self.partner_id.id, default_picking_type_id=picking_id.picking_type_id.id, default_reference_ids=self.stock_reference_ids[:-1].id)
You also need to remove `default_reference_ids`, since if we’re already removing the `default_origin`, that means we are considering that this picking will `no longer be assigned to the current SO`.

Additionally, the current expression won’t work at all: `self.stock_reference_ids[:-1].id` always evaluates to False. It should be: `self.stock_reference_ids[-1].id`

I tested this in `saas-18.4` and confirmed that `default_group_id` is passed correctly there.

Note that it also calls for dropship picking, so you need to confirm with the PO whether we want to create a dropship picking without a SO/PO or not.

2025-09-25 06:14 UTC, sako-odoo commented on addons/sale_stock/models/sale_order.py
> +        action['context'] = dict(default_partner_id=self.partner_id.id, default_picking_type_id=picking_id.picking_type_id.id, default_reference_ids=self.stock_reference_ids[:-1].id)
Yes, you are right. `default_reference_ids` is always false, and we don’t want to link them, so I have removed it as you suggested. I also confirmed with the PO that for all types of transfers, when we click the **New** button from the SO/PO linked transfer view, we don’t need to set the source document.

Thanks for the suggestion and for checking all the cases.

2025-09-25 07:49 UTC, dhha-odoo approved these changes

2025-11-21 09:52 UTC, amoyaux commented on addons/purchase/views/purchase_views.xml
> +                    <filter name="order_date" string="Receipt Date" date="date_order"/>
remove

2025-11-21 09:52 UTC, amoyaux commented on addons/purchase/views/purchase_views.xml
> +                        <filter string="Confirmation Date" name="approve_date" domain="[]" context="{'group_by': 'date_approve'}"/>
remove

2025-11-21 14:18 UTC, amoyaux commented
robodoo r+

2025-11-21 19:07 UTC, closed without merging