[IMP] pos_customer_display: UI Improvements
odoo/odoo pull request #168285
Opened 2024-06-06 09:48 UTC by vlst-odoo

Prior to this commit, following recent changes integrating Bootstrap to the customer display, the layout was lacking refinement and required a layout overhaul. This update addresses and improves the UI.

task-3773289

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-06 09:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/168285).

2024-07-29 10:07 UTC, xlu-odoo requested changes
Thanks for your work, a few comments

2024-07-29 10:07 UTC, xlu-odoo commented on addons/point_of_sale/static/src/customer_display/styles.scss
nit-picking for .o_line_container 
Update to:

```
.o_line_container {
    width: 4rem;
    height: 60px;
    padding: map-get($spacers, 2);

    img {
        max-height: 100%;
        max-width: 100%;
        border-radius: $border-radius-lg !important;
    }
}
```

Will rework the generic component in POS redesign task

2024-07-31 15:11 UTC, vlst-odoo commented
robodoo r+

2024-07-31 15:12 UTC, robodoo commented
@vlst-odoo you can't review+. Skill issue.

2024-08-01 12:08 UTC, caburj commented
robodoo r+

2024-08-01 12:30 UTC, robodoo commented
@vlst-odoo @caburj unable to stage: merge conflict

2024-08-01 12:34 UTC, caburj commented
robodoo r+

2024-08-01 15:38 UTC, closed without merging