[FIX] sale: improvement on down payment SO item description
odoo/odoo pull request #168418
Opened 2024-06-07 04:44 UTC by shrm-odoo

Steps to reproduce:
-create sales order for some product.
-create invoice for down payment.
-create regular invoice.

Issue:
-Description of down payment get modified after creating regular invoice.

Cause:
-the responsible method for down payment description is creating detailed description only when there is one invoice.

Fix:
-removed to condition of creating detailed description only when there is only one invoice.
-added loop to iterate through all invoices and set description accordingly.

opw-3904918

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-07 04:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/168418).

2024-06-10 13:23 UTC, Feyensv requested changes
This doesn't seem right, I believe that we want to filter the invoices to have only the original one (the downpayment one), and reference that specific one instead of looping on the invoices, which seems confusing and non deterministic.

2024-06-11 05:29 UTC, shrm-odoo commented
@Feyensv I agree with your perspective. However, according to the task requirements, when a user creates a regular invoice after generating down payment invoices, a credit note is created by consolidating all the down payment invoices. As we have a condition stating that if there is only one down payment, then only description should be detailed with its reference number. Consequently, if there is more than one down payment invoice included in the regular invoice, the description will not contain the reference number. To address this issue, I have added a loop.

2024-06-14 14:06 UTC, Feyensv commented
@robodoo r+

Filtering on the `outgoing` invoices wasn't filtering out the second invoice, as both invoices are outoing ones, changed it to only consider invoice lines with positive quantities

2024-06-14 17:48 UTC, closed without merging

2024-06-18 06:22 UTC, shrm-odoo commented
> @robodoo r+
> 
> Filtering on the `outgoing` invoices wasn't filtering out the second invoice, as both invoices are outoing ones, changed it to only consider invoice lines with positive quantities

Hello @Feyensv 
I have tested this branch on runbot after you have made changes to code, but the issue is still there. Can you please have a look into it?
I was filtering out the outgoing invoices, so we do not take credit note invoice, and take only down payment invoices for description modification.

2024-06-18 08:28 UTC, Feyensv commented
Oh, ok, I think I misunderstood your explanation, you were fixing the case where there was a credit note, but not fixing the situation where the generic invoice was created (deducting the down payment).
Your reproducing steps and issue were speaking of regular invoices, whereas the cause you were fixing was about credit notes.

I'll bring back your solution, as both solution are needed here indeed :ok_hand: 
Thanks for the notice.