[FIX] hw_driver: synchronous websocket message handling
odoo/odoo pull request #169525
Opened 2024-06-14 16:28 UTC by lse-odoo

Before this commit:
Receiving a report call on "Microsoft Print to PDF" printer prevent the websocket to receive any other message after due to the fact that ghostscript script will pop an input prompt (which we can't even interact with).

Although the case is rare, we should not rely on a synchronous process to handle all incoming websocket request as any longer request would force other incoming request to wait.

After this commit:
Handle the messages asynchronously by spawning threads.

2024-06-14 16:29 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/169525.png)](https://mergebot.odoo.com/odoo/odoo/pull/169525)

2024-06-14 16:31 UTC, lse-odoo commented
TODO:
- need to test out
- check if there is not a better way than spawning 2 threads ?
- if the thread really hang, then it can't be easily killed. Maybe a process would be more appropriate ?

2024-06-17 13:47 UTC, lse-odoo commented
@Ysoroko could you review this PR please ? :) (and @qle-odoo if you have the time)

2024-06-19 14:28 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +WS_REQUEST_POOL = concurrent.futures.ThreadPoolExecutor(8)
Need to check whether 8 is a good amount

2024-06-19 14:30 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +            time_differece = time.time() - ws_thread.starting_time
n

2024-06-19 14:31 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +                check_delay = min(WS_REQUEST_TIME_TIMEOUT // 2, check_delay)  # Check a bit more often if there are no stuck threads
not necessary

2024-06-19 14:35 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +            helpers.odoo_restart(2)
restarting iot is too violent and unneeded.
In PrinterDriver_W create a system that will manage the blocked ghostscript.Ghostscript class instance and kill it after a timeout

2024-06-19 14:40 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +WS_REQUEST_TIME_TIMEOUT = 120  # seconds
5 min?

2024-06-19 14:58 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +    del current_thread.starting_time  # let know the pool checker that the thread is free
replace by None?

2024-06-19 15:00 UTC, Ysoroko requested changes
1) Do not restart Odoo
2) Fix printerDriver_W Ghostcript infinite loop
3) Simplify the code: timeout warnings, del etc.

2024-06-21 10:32 UTC, lse-odoo commented
@Ysoroko could you review the PR with the changes please ?
I added a web socket "counter" as the previously used "hash" of the ws message is a terrible idea as 2 request with the same string will have the same hash (and also very small risk of collision). A counter would make more sense.

Regarding the fact that this PR introduce an issue with printers that print in parallel in the same PDF, I would say that it should be it's dedicated PR as it needs more research: ghostscript parameter ? adding lock on the process ? write in pdf with different name automatically removed (like we do with wkhtmltopdf), is it an issue on IoT box or only windows IoT

2024-06-28 09:54 UTC, lse-odoo commented on addons/hw_drivers/websocket_client.py
> +        return ''
can be replaced by `misc.dumpstacks` ? we can give the thread_idents to it and change the used parameter to match with the intended one (if it applies)

2024-07-04 13:44 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +            time_differece = time.time() - ws_thread.starting_time
time differeeeeeece :pinched_fingers:

2024-07-04 13:53 UTC, Ysoroko commented
If the issue is coming solely from Microsoft Print to PDF virtual printer which is blocking the thread, modify the driver/interface to remove it from the list of the detected devices on IoT.
Anyway it doesn't make any sense to print to PDF on an IoT if you can simply do this from the browser

2024-07-04 13:55 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +WS_REQUEST_POOL = concurrent.futures.ThreadPoolExecutor(8)
![image](https://github.com/odoo/odoo/assets/36443074/fe3e807c-53ba-4252-844d-b0663d256a23)

2024-07-04 14:00 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +            time_differece = time.time() - ws_thread.starting_time
![7FPu](https://github.com/odoo/odoo/assets/36443074/58f03f72-19b0-4320-8fb5-0af4b1ebe630)

2024-07-04 14:01 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +        When a message is receive by the websocket, this function is triggered
d

2024-07-04 14:01 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +        When a message is receive by the websocket, this function is triggered
receiveD

2024-07-04 14:04 UTC, Ysoroko approved these changes
Little things to change, will recheck once it's ready as discussed

2024-07-24 13:04 UTC, Ysoroko commented on addons/hw_drivers/websocket_client.py
> +                timeouting_threads_indent.append(ws_thread.ident)
ident or indent?

2024-07-24 15:15 UTC, Ysoroko commented
Tested, works as expected

2024-07-25 06:55 UTC, qle-odoo commented
@lse-odoo 

> Receiving a report call on "Microsoft Print to PDF" printer prevent the websocket to receive any other message after due to the fact that ghostscript script will pop an input prompt (which we can't even interact with).

You want a PDF ? So download it and does not link a printer.
Or correct the way to register a PDF. You can add a virtual printer "Register PDF on this computer" who does not send resquest to ghostscript but just create a copy in a specific folder ? (there is a pretty little task ;) )
So why not exlcude this virtual printer ? Or all virtual printer generated by Windows ?

Why add code that makes websocket management much more complex? 
It is correct, except the arbitrary number of threads: 30? Why?
you make a benchmark?

cc @Ysoroko

2024-07-25 11:46 UTC, lse-odoo commented
@qle-odoo 

> You want a PDF ? So download it and does not link a printer. Or correct the way to register a PDF. You can add a virtual printer "Register PDF on this computer" who does not send resquest to ghostscript but just create a copy in a specific folder ? (there is a pretty little task ;) ) So why not exlcude this virtual printer ? Or all virtual printer generated by Windows ?

This is just an example. We can also think about the scenario on which you print a PDF of several pages long (or any other long operation). While the operation is happening, we will be incapable of handling any other websocket requests.
This in itself make it different than before when we use HTTP as Odoo can natively support multiple HTTP request in //. So, in theory, drivers code is already wrote to work in concurrence.
(note that the particular case of "Microsoft print to PDF" was solve in another PR, but it still highlighted the issue of the fact that ws is synchronous)

> Why add code that makes websocket management much more complex?

This looks to me the best way to do so if we want asynchronous websocket request handling.
We could also think about creating a thread on the fly for each request but it sounds like a terrible idea in term of performance, ressource and unthrottling.
Using a threadpool allow for the same with the control on the maximum number of threads in // (so best of both world in my opinion). Yes it complexify the code, but websocket is complicated in itself and quite low level, it would be like saying that the drivers/interface class code is complicated :thinking:
If you don't agree with the idea, then I will let you the joy of investigating future tickets on which the websockets looks unresponsive and find the root cause without restarting the IoT ;)

> It is correct, except the arbitrary number of threads: 30? Why?

30 is an arbitrary value that we decided with Yaro, see:
https://github.com/odoo/odoo/pull/169525#discussion_r1665750008

2024-08-02 08:15 UTC, lse-odoo commented
judged "too complicate and not useful enough" by the IoT team. Will only keep the log part into a separated PR and close this one to ease investigation

2024-08-02 08:15 UTC, closed without merging