[IMP] account_peppol: refactor phone number to mobile number
odoo/odoo pull request #169607
Opened 2024-06-17 09:55 UTC by stefan-rvic

According to the documentation, the user receives their registration code through SMS, so phone number label is misleading.
    
Steps to reproduce:
1.Install account_peppol > install an peppol egilible accounting l10n (i.e l10n_be)
2.In settings > technical > system parameter > set account_peppol.edi.mode to test
2.in settings search for peppol
3.notice how the phone number is requested in the registration form
4.click on validate registration
5.notice how the validation button displays "verify phone number" while the verification code is sent by sms

Solution:
refactor labels, buttons, helps and errors message to indicate mobile number. The actual field account_peppol_phone_number is not renamed as per stable version changes condition.
    
opw-3977664

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-17 09:56 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/169607.png)](https://mergebot.odoo.com/odoo/odoo/pull/169607)

2024-06-17 13:52 UTC, yosa-odoo requested changes
Hello, thanks for the fix

Indeed, it can be misleading for the user.

Could you also modify the `.pot` file for the translation?

2024-06-17 15:25 UTC, yosa-odoo approved these changes
LGTM

2024-06-19 11:13 UTC, antoine162 reviewed
@stefan-rvic Looks good! Should we do this in 16.4 (since account_peppol exists since 16.4)?

2024-06-20 12:21 UTC, antoine162 approved these changes
Great, thanks so much!

@robodoo r+

2024-06-20 14:27 UTC, closed without merging