[IMP] sale: reorganize sale order footer on mobile
odoo/odoo pull request #169625
Opened 2024-06-17 12:14 UTC by Brieuc-brd

### Reorder elements
Prior to this PR, the "Terms and conditions" field was between the SO lines and the total, which was confusing for users.

This PR reorganizes these elements to place the "Terms and conditions" field after the total.

### Adapt spacing
Prior to this PR, the spacing between elements in `oe_subtotal_footer` was not consistent between the media breadkpoints (the spacing was larger on mobile).

This PR adapts this spacing to maintain consistency between screen sizes.

task-3983459

Requires:
- 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-17 12:15 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/169625.png)](https://mergebot.odoo.com/odoo/odoo/pull/169625)

2024-06-21 06:51 UTC, chgo-odoo requested changes
Hello @Brieuc-brd, thanks for your work on this !

Actually I'm not sure we need the `d-flex flex-column` utility classes as the element already has a grid display.

Except that it looks fine !

2024-06-25 07:48 UTC, Brieuc-brd commented
Thanks for your feedback @chgo-odoo 👍,

Unfortunately, as `oe_subtotal_footer` uses the default grid defined in the form's view groups, you will have a layout issue at some breakpoint. To solve this, we need to force `oe_subtotal_footer` to use a flex column layout.
<img width="551" alt="Capture d’écran 2024-06-25 à 09 43 59" src="https://github.com/odoo/odoo/assets/80679690/6d1d9926-38df-4895-9145-8b234c6b53d0">

2024-06-25 08:34 UTC, chgo-odoo approved these changes

2024-06-25 10:40 UTC, Brieuc-brd commented
Hey @odoo/rd-sales 👋 
This PR is ready for tech. review, could you take a look at it ?
Thanks in advance !

2024-06-25 11:24 UTC, Feyensv approved these changes
@robodoo r+ delegate+

2024-06-25 12:01 UTC, robodoo commented
@Brieuc-brd @Feyensv linked pull request(s) odoo/enterprise#64789 not ready. Linked PRs are not staged until all of them are ready.

2024-06-25 16:43 UTC, closed without merging