[IMP] l10n_in_pos: kiosk mode payment terminal configuration message
odoo/odoo pull request #169912
Opened 2024-06-19 05:23 UTC by jipr-odoo

Before this commit:
====================
In KIOSK mode, the message for the payment terminal was specific to Stripe and Adyen.

After this commit:
===================
In KIOSK mode, we now support the `Razorpay` terminal for `l10n_in`. The message for the payment terminal in the res config settings has been updated to. "Please note that the kiosk for INR currency only works with Razorpay terminal" for INR currency.

task- 3981002

2024-06-19 05:24 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/169912.png)](https://mergebot.odoo.com/odoo/odoo/pull/169912)

2024-06-20 09:54 UTC, paso-odoo requested changes

2024-06-20 09:54 UTC, paso-odoo commented on addons/l10n_in_pos/views/res_config_settings_views.xml
> +        <field name="name">res.config.settings.view.form.inherit.l10n_in.pos_self_order.view</field>
```suggestion
        <field name="name">res.config.settings.view.form.inherit.l10n_in_pos.view</field>
```

2024-06-20 11:42 UTC, jipr-odoo commented on addons/l10n_in_pos/views/res_config_settings_views.xml
> +        <field name="name">res.config.settings.view.form.inherit.l10n_in.pos_self_order.view</field>
@paso-odoo 
Changes are done

2024-06-20 12:14 UTC, paso-odoo approved these changes

2024-06-24 12:24 UTC, vlst-odoo approved these changes
robodoo r+

2024-06-24 16:22 UTC, closed without merging