[FIX] payment: fix traceback when user tries to install payment in multi company
odoo/odoo pull request #169953
Opened 2024-06-19 10:49 UTC by alsh-odoo

This traceback occurs when the user tries to activate stripe through onboarding without installing `website_payment`.

To reproduce this issue:-

1) Install `sale`
2) In the sales `Onboarding` try to activate the stripe payment 
3) Now switch to a new company by creating a `new company` 
4) With the new company try to `activate the stripe` from the `sales Onboarding` 
5) A traceback occurs

Error:- 
```
ValueError: Invalid field 'website_id' on model 'payment.provider'
```

As you can see `website_id` field is defined in `website_payment` at [1], 
but it is used in the `payment` module [2]. Which leads to the above traceback.

[1]
https://github.com/odoo/odoo/blob/16e8de01b14ddac69cd706f8f64e762406769542/addons/website_payment/models/payment_provider.py#L12-L16

[2]
https://github.com/odoo/odoo/blob/16e8de01b14ddac69cd706f8f64e762406769542/addons/payment/models/res_company.py#L48-L53

sentry-5504774122

2024-06-19 11:48 UTC, alsh-odoo commented
Holaa @odoo/sentry_reviewers 

Can I have your review on this PR?

Thank You :slightly_smiling_face:

2024-06-20 09:51 UTC, AntoineVDV requested changes
Hello, are you awaiting a review from the sentry reviewers team?

You should take care not to bring back the bug that https://github.com/odoo/odoo/pull/154280 was trying to fix.

2024-06-21 15:01 UTC, AntoineVDV reviewed
That is one valid way to achieve it, but could you please try a different approach to see if it's simpler: just override the `copy` method and set `website_id` to `None` if the `stripe_connect_onboarding` context key if set.

2024-06-24 08:34 UTC, alsh-odoo commented
Hola @AntoineVDV 

Can I have your feedback on this?

Merci :slightly_smiling_face:

2024-06-24 09:08 UTC, AntoineVDV approved these changes
Thank for the change :)

It's not exactly the best solution there is, but since modularity is already not respected by Stripe Connect, better pick the simpler fix.

@robodoo r+

2024-06-24 11:51 UTC, closed without merging