[IMP] website_profile: prepare profile edition for redesign
odoo/odoo pull request #169982
Opened 2024-06-19 12:56 UTC by pyduf

Instead of loading a new page for editing the profile, the profile is now edited in a popup.

To simplify the code, the "edit" link next to the "biography" that allowed the user to edit it directly in the profile page, is now also replaced by the edit profile popup (biography field being automatically focused).

Technical notes:
- we have converted the profile edition in OWL instead of using a simple bootstrap modal because the wysiwyg component was not compatible with bootstrap modal (ex.: when opening the chatGPT plugin from the wysiwyg field of the profile bootstrap modal, the prompt field was readonly/not focusable)
- We remove the "edit_button_url_param" and "url_param" that were used to transmit the forum_id/channel_id to the page /profile/edit so that when saving on /profile/user/save, the server could redirect to the page /profile/user with the right parameters. As we have converted the profile edition to OWL and used it in the same page, the page is refreshed with the same parameters after saving the profile through ajax call.
- We keep the save controller end point as operation for the current user are done in sudo so it cannot be replaced by simple orm call from the client.

Task-3975540

2024-06-19 12:57 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/169982.png)](https://mergebot.odoo.com/odoo/odoo/pull/169982)

2024-06-27 12:13 UTC, julien-banken requested changes
Hello @pyduf,
Thank you for your review. I have a few questions and suggestions for you. Note that I didn't review the XML templates nor the style sheets since they will be reworked by someone from the design team (as mentioned in the task description).

2024-10-18 06:32 UTC, pyduf reviewed
Hello @julien-banken , 

Sorry for the very long delay, I have updated the code and answered your comments.

2024-11-08 13:01 UTC, pyduf reviewed
Hello @julien-banken ,

Thanks for the review and sorry for the delay. I have updated the code with the suggested changes.

2024-11-08 14:32 UTC, julien-banken approved these changes

2025-03-24 14:09 UTC, awa-odoo reviewed
Hello @pyduf 

Finally took some time to dust off this one and leave some comments 😄 
The usual package of suggestions / questions / remarks.

Thanks for your work & cheers!

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                            <option t-att-value="country.id" t-att-selected="country.id == user.partner_id.country_id.id"><t t-esc="country.name"/></option>
While we're here, let us replace t-esc by t-out.

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                            <option t-att-value="country.id" t-att-selected="country.id == user.partner_id.country_id.id"><t t-esc="country.name"/></option>
![image](https://github.com/user-attachments/assets/ebfabef2-2b02-4f27-8985-d899cc979582)

Kind of strange that it does out the window but maybe will be addressed by the new design.

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                <textarea name="description" style="min-height: 120px"
Why the inline style?

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                    class="form-control o_wysiwyg_loader" placeholder="Write a few words about yourself..." t-att-content="user.partner_id.website_description"><t t-out="user.partner_id.website_descr
Note that /video and /chatgpt commands do not work as I'm unable to type text into the dialog, maybe some z-index shenanigans?

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                    class="form-control o_wysiwyg_loader" placeholder="Write a few words about yourself..." t-att-content="user.partner_id.website_description"><t t-out="user.partner_id.website_descr
"/image" does not work for portal users as they cannot access attachments.

I think there is a way to disable this command for portal maybe?
Note that current version doesn't support it either so if too complex / too annoying, we could ignore it.

2025-03-24 14:09 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                            <t t-call="website_profile.user_profile_edit_main"/>
Again, we could inline the template if only used once.

2025-04-28 09:13 UTC, pyduf reviewed
Hello @awa-odoo , 

Thanks for the review and sorry for the delay. As discussed on the task, I have removed the cover feature, keeping only the change that turns the profile edition page into a edition popup. I have also improved the existing code following your advice. 

As suggested, I have removed the ”email_required”. It was used when trying to create a new post in “Forum” to redirect to the profile page with a special message indicating that we needed an email in order to notify answers, ... But actually, when you don’t have an email, there is already a permanent warning on the profile page so that special message is probably not useful so I have removed it. While doing that, I have noticed that actually that feature was not working as the redirect page when clicking on “New post” while having the email not set is wrong since the v16. I can create a fix PR for that.

To remove the url_params, the form post the data on the current page instead of another page followed by a redirect so that the params stay in the URL. An added benefice of that is that some parameters that were lost are not lost any more (like forum_origin that is used for the back button).

For the not ediable input of wysiwyg editor (/chartGPT or /Image), I have asked the team editor and a solution may be to use owl for the popup. I will try that.

2025-04-30 09:00 UTC, awa-odoo reviewed
Hello @pyduf 

Looks a lot cleaner and much more simple, thank you for this new version.

Left a few minor comments but after that we should be good to go :rocket: 

Cheers!

2025-04-30 09:00 UTC, awa-odoo commented on addons/website_profile/controllers/main.py
> +    @http.route('/profile/user/<int:user_id>', type='http', auth="user", methods=['POST'], website=True)
Is it necessary to have the same endpoint with GET/POST methods for this?

It's rather unusual I think, a more common option would be "/profile/user/<int:user_id>/save" or something similar.

2025-04-30 09:00 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +            <textarea name="description" id="description2"
id="description2" ?

Doesn't match label "for".

Also seems a bit too common, would namespace IDs if possible to avoid collisions.

2025-04-30 09:00 UTC, awa-odoo commented on addons/website_profile/views/website_profile.xml
> +                    <textarea name="description" id="description"
Does this one even need an ID as it doesn't have a matching label?

2025-05-07 06:26 UTC, pyduf reviewed
Hello @awa-odoo , 

Thanks for the review. To solve the problem you've found in the wysiwyg component when used in the bootstrap popup, I have converted the popup to OWL as suggested by the editor team. Everything is working but I've left 2 questions for the editor team about the assets to import and to prevent portal user to access the image plugin.

Otherwise the OWL conversion solves the last problems you have mentioned.

2025-05-16 09:51 UTC, awa-odoo commented
Hello @pyduf 

Where are we one this one? I think you're still waiting for a reply from the editor team?
Maybe you could try to ping them on Discord?

Would really like to close this old task ^^

Thanks & cheers!

2025-05-16 10:38 UTC, dmo-odoo commented on addons/website_profile/__manifest__.py
> +            ('include', 'html_editor.assets_editor'),
Hello @pyduf! I'm a bit confused because the diff is in `website_profile` but `website` does not use `html_editor` yet. As a result, I think you're kind of in uncharted territory in the sense that there isn't, for the time being, a working instance of `html_editor` in the frontend. This will soon change when https://github.com/odoo/odoo/pull/187419 is merged though, which refactors lots of stuff in `website` to use `html_editor` instead of `web_editor`.

2025-05-16 10:40 UTC, dmo-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            };
Yes, the configuration is named `allowImage` in recent versions.

2025-06-06 11:28 UTC, pyduf commented
Hello @awa-odoo , 
cc @abd-msyukyu-odoo

I have updated the assets (following the merge of the PR odoo/odoo#210398) and configured the wysiwyg to only allows file and image for internal user (as the portal user doesn’t have the rights to as you've pointed out). 
Note that with the default plugins (like before), the chat gpt plugin is no longer available.

Thanks for your help to both of you.

2025-06-06 14:51 UTC, awa-odoo reviewed
Hello @pyduf 

Some comments on this new implementation.

When everything is addressed, I think we should ask for some testing, as code has changed a lot recently.
Would you mind asking the tester from the Testing IN stage to give it another try?

Thanks for your work on this one, taking more time than expected but we're close now :muscle:

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_forum/controllers/website_forum.py
>      def forum_post(self, forum, **post):
Commit message says:

> because the wysiwyg component was not compatible with bootstrap
modal (ex.: when opening the chatGPT plugin from the wysiwyg field of the
profile bootstrap modal, the prompt field was readonly/not focusable)

But as far as I understand chatGPT is no longer available anyway, don't we have a better example?

Also, should we mention plugins that have been removed/disabled following this change?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +        this.getUniqueDomID = (suffix) => `profile-dialog-${componentUUID}-${suffix}`;
Usage of "getUniqueDomID" seems overly complicated for not much reasons.

We could hardcode "user_profile_website_published" in the form for example, it's "unique" enough.
Same for the class, just pick a namespaced name.

Should be overall just as robust and easier to read.
(It's also a bit confusing because "getUniqueDomID" is not very unique, if you pass it twice the same suffix you'll get twice the same ID ^^).

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +        onWillStart(async () => {
Detail: We usually space out things a bit, blank space before "onWillStart", blank space before "onMounted" etc, makes it less "packed".

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            const fields = [
No need for a variable, just hardcode the list in the call?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.descriptionConfig = {
Maybe "descriptionWysiwygConfig" ?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.user.country_id = this.user.country_id && this.user.country_id[0]; // keep only id
Curious: does this trigger "this.validate()" as it's a reactive?

Should maybe alter "users[0]" first before making it a reactive?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                setTimeout(() => {
Shouldn't this be placed inside "onWebsiteDescriptionEditorLoad" ?

Otherwise you're assuming that the editor will load within 50 seconds of mounted.

(Unless onMounted is only called when the editor is loaded somehow).

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                content: this.user.website_description,
@abd-msyukyu-odoo 

Kind of the same question as on Stéphane's PR: do we need to worry about any kind of editor migration here?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +    get websiteDescription() {
Looks only used once, maybe inline code? "websiteDescription" is pretty annoying to grep.

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.profileImgData = result.toString().replace(/^data:.*;base64,/, "");
Is this a reliable way to get the data? ^^

Don't we already have a widget / component to handle images?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +    async _confirm() {
Aren't you supposed to configure a "confirm" prop instead that links to your function?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.modalRef.el.querySelector(".modal-footer button").disabled = this.state.hasError;
Can't you alter the "confirmClass" prop instead ?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.xml
> +                                </a>
![image](https://github.com/user-attachments/assets/785e3c01-1427-43fd-a674-5ca2d7a0958a)

Maybe a bit of spacing?

2025-06-06 14:51 UTC, awa-odoo commented on addons/website_profile/static/src/interactions/profile_editor.js
> +            userId: JSON.parse(this.el.dataset.userId),
JSON.parse?

Aren't those simple boolean / integer? Can't we use `this.el.dataset.focusWebsiteDescription === 'true'` and `parseInt(this.el.dataset.userId)` ?

2025-06-10 08:30 UTC, abd-msyukyu-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                content: this.user.website_description,
I believe I missed the ping on Stephane's PR, and I can't find it, can you send it to me again via DM ? Thanks!

The html_migration in JS only applies on very specific elements through selectors, once it runs once in edit mode, it will register the latest version as an HTML attribute and not run again. So no need for concern, if you don't use it you can just ignore it.

2025-06-10 08:55 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                content: this.user.website_description,
But any embedded component can be updated right?

For example, if we decide to update the /toc embedded components, what happens if the migration is never run? Does it stop working on "older articles" at some point? Not sure what you mean by "if you don't use it you can ignore it".

STD PR here: https://github.com/odoo/odoo/pull/212175#discussion_r2128282772

2025-06-10 09:56 UTC, abd-msyukyu-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                content: this.user.website_description,
@awa-odoo @pyduf
Currently, any html value that was never opened in an editor with the `editor_version_plugin` will go through all JS migration scripts if the `HtmlUpgradeManager`, no matter how old it is.

"if you don't use it you can ignore it" I meant that running the script should not cause issue with existing content no matter how old it is, and one should only have to care about it when they write a JS migration script themselves

--->> /!!\\
However now that I've thought about it a bit more, there is one issue with the current implementation in this PR:

I forgot that since the website team did not want the JS migration feature by default in the editor because they have an alternate way of handling issues like these, the `HtmlUpgradeManager` and the `EditorVersionPlugin` are now options of the `HtmlField`, which is not used at all in this PR. Sorry about that.

If you want to make use of the feature, you have to manually add the `EditorVersionPlugin` in the plugins set that you should then provide in the wysiwyg config, and run `HtmlUpgradeManager:processForUpgrade` on the content that you provide to the editor.

You should probably do it, because I believe the `/banner` command was useable prior to your changes, and it had some changes through a JS migration? And it would be safer to have it if there are changes in the future?

2025-06-10 10:01 UTC, awa-odoo commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                content: this.user.website_description,
Maybe easier to discuss at the office tomorrow but I don't see it as a choice, the upgrade manager should be run everywhere because eventually components will be updated, and those editors will be broken.

2025-06-11 06:38 UTC, pyduf reviewed
Hello @awa-odoo , 

Thanks for the review on the new implementation. I have updated the code following your valuable suggestions and asked for testing this new version.

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            };
Thanks, it works.

2025-06-11 06:38 UTC, pyduf commented on addons/website_forum/controllers/website_forum.py
>      def forum_post(self, forum, **post):
Indeed, I have given the example of the search field of the “/Media” instead which was not working either. I have added a comment about chatGPT which is now integrated with discuss following odoo/enterprise#85028: “Now, the chatGPT has been fully integrated in discuss, so every time a user wants to chat with the AI and generate text - they will chat as if it's another user.”. But as mentioned in the commit, it seems not available like before even with the ai module installed.

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +        this.getUniqueDomID = (suffix) => `profile-dialog-${componentUUID}-${suffix}`;
Yes, good idea. I have used the prefix “website_profile_profile_dialog_” (module name followed by component name).

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.user.country_id = this.user.country_id && this.user.country_id[0]; // keep only id
Yes indeed, you’re right. It will spares one call to validate (validate is called in onMounted for the initial validation).

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +                setTimeout(() => {
Unfortunately, onWebsiteDescriptionEditorLoad is called during the setup of the wysiwyg component so it is not yet possible to focus it and set the cursor at the end of it. And there are no hook called after onmounted in the wysiwyg. The timeout of 50 milliseconds in the onMounted of ProfileDialog was necessary because before the wysiwyg component was not yet mounted at that point but now it works without it so I have removed it.

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.profileImgData = result.toString().replace(/^data:.*;base64,/, "");
Yes you’re right. FileUpload can do that, thanks. I had to add “web/static/src/views/fields/file_handler.*” in the frontend asset for that (but it is done as well in some other modules)

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +    async _confirm() {
The confirm props is optional and in the confirm method, we need to deal with private data of the component so it would be hard to define the confirm handler outside the component. I did that because there are already such usage in the code base but it is not ideal indeed as I’ve missed the “execButton” call that prevents the double click. So I have modified slightly the ConfirmationDialog to allow to redefine the confirm callback.

2025-06-11 06:38 UTC, pyduf commented on addons/website_profile/static/src/components/profile_dialog/profile_dialog.js
> +            this.modalRef.el.querySelector(".modal-footer button").disabled = this.state.hasError;
I have used directly the state “hasError” by adding the attribute disabled using xpath.

```xml
<xpath expr="//t[@t-set-slot='footer']/button[@t-on-click='_confirm']" position="attributes">
    <attribute name="t-att-disabled">this.state.hasError</attribute>
</xpath>
```

2025-06-11 10:13 UTC, awa-odoo commented on addons/web/static/src/core/confirmation_dialog/confirmation_dialog.js
> +    get confirm() {
Seems a little strange to let people override "confirm" and not "cancel" ?

I'm not sold on these changes, are you using a lot of things from the ConfirmationDialog? Your extension is looking a lot more like a form and not really a ConfirmationDialog, maybe we could extend "Dialog" instead and just copy the small part from ConfirmationDialog that you need from the template / code.

What do you think?

2025-06-17 09:54 UTC, pyduf commented on addons/web/static/src/core/confirmation_dialog/confirmation_dialog.js
> +    get confirm() {
Hello @awa-odoo , 

Yes indeed, it is simpler by using the Dialog directly. I have done the changes. Thanks.

2025-06-17 12:49 UTC, awa-odoo commented
@robodoo r+

2025-06-17 13:00 UTC, robodoo commented
@pyduf @awa-odoo linked pull request(s) odoo/upgrade#7619 not ready. Linked PRs are not staged until all of them are ready.

2025-06-18 06:27 UTC, closed without merging