[IMP] mail: add clickable html tag to activity component
odoo/odoo pull request #170000
Opened 2024-06-19 13:52 UTC by phenix-factory

Before this PR, t-on-click was directly on `<i>` and `<span>` elements. This
is not correct since they are not clickable html elements and could be a
challenge for people using accessibility tools.

This PR adds clickable elements to the t-on-clicks

Enterprise PR: https://github.com/odoo/enterprise/pull/65053

2024-06-19 13:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/170000.png)](https://mergebot.odoo.com/odoo/odoo/pull/170000)

2024-06-25 22:45 UTC, alexkuhn requested changes
The change add too much spacing. Make sure to keep the same spacing as before:
![Screenshot 2024-06-26 at 00 35 06](https://github.com/odoo/odoo/assets/6569390/e91637af-71e1-4a4e-baa1-e8c48b458c06)

The problem comes (mostly/exclusively) from the "info" `<i>`, which was the height of a text line at 14px but now becomes a `<button>` with 33px. You'd have to apply `p-0 lh-1 border-0` to ensure the button size matches the intended design.

_(BTW the avatar & name not matching looks like an issue with our crosstab / BroadcastChannel sync of activities, as page loading on a tab removes the avatar on the other tab. A bug to fix)_

2024-06-27 06:08 UTC, phenix-factory commented
@alexkuhn I didn't "fix" that because I think it's easier to click on the button like this, especially on mobile. The clickable area is a lot bigger and the design changes feel minor. This button doesn't need to be "part of" the string.

2024-06-27 12:00 UTC, alexkuhn approved these changes
@robodoo r+

2024-06-27 16:49 UTC, closed without merging