[FIX] web, website: fix the values set to the buttons CSS variables
odoo/odoo pull request #170015
Opened 2024-06-19 15:30 UTC by sobo-odoo

In commit [1], the "Themes Options" have been reorganized to make them easier to find. With this relayout, the buttons style options have also been modified in order to have a third choice "Flat", in addition to "Fill" and "Outline". However, the way it was done causes some issues.

Indeed, it wrongly sets the `btn-(primary|secondary)-(outline|flat)` CSS variables to `'True'` instead of the `true` boolean (and to `null` instead of `false`), which is not correct. This happens because `customizeButtonStyle` now sends boolean values to the `_makeSCSSCusto` function, instead of strings representing these booleans. This results in the backend RPC call setting the variables to the Python boolean `True`, or to `null` in the falsy case because of the `"null"` default value.

While it does not seem to break anything in general, there are issues when the "Enark" theme is installed. Indeed, this theme wrongly defines the `btn-primary-outline` variable to `'true'` instead of the boolean `true`. This, combined with the above issue, made it impossible to set the buttons primary style to "Fill".

This commit fixes these issues by properly giving string values to `_makeSCSSCusto`. For already existing databases, all the variables that have been set to `'True'` will have their value replaced by `true`, thanks to the `o-map-omit` SCSS function.

Note that the "Enark" theme will be fixed independently (see PR [2]).

[1]: https://github.com/odoo/odoo/commit/388e4bb2bfcaebdd4ff30277fb49a034592d7086
[2]: https://github.com/odoo/design-themes/pull/806

opw-3957157

2024-06-19 15:31 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/170015.png)](https://mergebot.odoo.com/odoo/odoo/pull/170015)

2024-06-19 16:46 UTC, sobo-odoo commented
@qsm-odoo ready for review :slightly_smiling_face:

2024-06-20 16:45 UTC, qsm-odoo requested changes
Thanks for the fix, some nitpicking :pray:

2024-06-20 16:45 UTC, qsm-odoo commented on addons/web/static/src/legacy/scss/utils.scss
> +// into a boolean `true`.
I'd say let's be a bit more consistent and handle "False" too (even if it was not part of the bug here). Also add a slight explanation about why this is done in this function. You can also add this to justify it more:
```scss
// TODO in master, this should be moved in website, as the only use case is in website user values files
```

2024-06-20 16:45 UTC, qsm-odoo commented on addons/web/static/src/legacy/scss/utils.scss
>      @return $-with-support-font;
Commit message:
>  This, combined with the above issue, made it impossible to set
the buttons primary style to "Fill".

Nitpicking but I think this is not accurate, choosing a value (e.g. setting to "Fill") is buggy in the same way with or without the bug in the theme enark definition.

2024-06-21 08:38 UTC, robodoo commented
@sobo-odoo the target branch 'saas-16.4' has been disabled, you may want to close this PR.

2024-06-21 16:28 UTC, robodoo commented
This PR targets the disabled branch odoo/odoo:saas-16.4, it needs to be retargeted before it can be merged.

2024-06-24 11:58 UTC, sobo-odoo commented
@qsm-odoo I made the changes :slightly_smiling_face: I added the `'False'` case, added a better explanation in the commit message and rebased on 17.0 :wink:

2024-06-27 09:50 UTC, qsm-odoo approved these changes
As discussed, not entirely stable for potential custo using the `o-map-omit` function but as indicated, it is only currently used in website and I doubt any custo is using it. And even if they do, this change is unlikely to break something. And even if they do, it really should not be critical. Let's not overthink for once :grimacing: 

Thanks for the fix :+1: 

@robodoo r+

2024-06-27 12:54 UTC, closed without merging