[IMP] hr_attendance: Add extra hours validation mecanism
odoo/odoo pull request #170334
Opened 2024-06-21 12:48 UTC by jugj-odoo

task-3999208

2024-06-21 12:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/170334.png)](https://mergebot.odoo.com/odoo/odoo/pull/170334)

2024-08-30 05:10 UTC, mepe-odoo requested changes
Hello; huge work (my brain needs an other coffe :coffee: after this review)

I add some comments; the most are just nickpicking; but one is about your structure choice for a variable :)

2024-08-30 05:10 UTC, mepe-odoo commented on addons/hr_attendance/models/hr_attendance.py
> +                attendance.overtime_status = "to_approve" if attendance.employee_id.company_id.attendance_overtime_validation == 'by_manager' else "approved"
this line seems too long ;)

2024-08-30 09:17 UTC, jugj-odoo commented on addons/hr_attendance/views/res_config_settings_views.xml
> +                                <span>Time Period </span><field name="overtime_company_threshold" class="text-center" style="width: 10%; min-width: 4rem;"/><span> Minutes</span>
it was like that before, but i'll change it

2024-09-04 08:18 UTC, tivisse commented on addons/hr_attendance/models/hr_attendance.py
> +                                self.search([('employee_id', 'in', employees_worked_hours_to_compute)]))
Seems we could get rid on 1 search call over here

2024-09-04 14:12 UTC, tivisse commented
@robodoo r+

2024-09-04 16:29 UTC, closed without merging