[FIX] account_account: install stock after outstanding account removal
odoo/odoo pull request #170580
Opened 2024-06-24 13:39 UTC by lase-odoo

### Steps to reproduce:

- Start with an empty DB
- Install account_accountant
- Open settings - Search "Default Accounts" - Clear Outstanding receipts - Save
- Go to Apps: Install stock

#### > traceback

### Cause of the issue:

The "_setup_utility_bank_accounts" method is called during the installation of the stock module. In this call, data about non-existing fields of the "account.account" model are added to the `account_data` dictionary, namely : `prefix` and `code_digits`:
https://github.com/odoo/odoo/blob/e80ff1c285ce633a75ce0de5a7cb8d3dcecd301f/addons/account/models/chart_template.py#L702-L708 Since the "Outstanding receipts" account was removed from the settings of the company, it is not removed from the `account_data` here: https://github.com/odoo/odoo/blob/e80ff1c285ce633a75ce0de5a7cb8d3dcecd301f/addons/account/models/chart_template.py#L749-L751 and the datas of these records will be loaded:
https://github.com/odoo/odoo/blob/e80ff1c285ce633a75ce0de5a7cb8d3dcecd301f/addons/account/models/chart_template.py#L756-L761 If the records were to be created, it would not be problematic because these datas are popped and used by the override of the `create` method of the `account.account` model:
https://github.com/odoo/odoo/blob/e80ff1c285ce633a75ce0de5a7cb8d3dcecd301f/addons/account/models/account_account.py#L701 However, in our case, the record linked to that xml_id already exists and is added to the list of the records to update. A `write` call will then be launched to update the non-existing `account.account` fields leading to the traceback:
https://github.com/odoo/odoo/blob/96d98792bb34772e7acc228dd093c56f2f18b483/odoo/models.py#L5045-L5046

opw-4007561
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-24 13:40 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/170580.png)](https://mergebot.odoo.com/odoo/odoo/pull/170580)

2024-06-24 15:12 UTC, HANNICHE-Walid requested changes

2024-06-24 15:12 UTC, HANNICHE-Walid commented on addons/account/models/account_account.py
> +            vals = {k: v for k, v in vals.items() if k not in ['code_digits', 'prefix']}
del vals['prefix']
del vals['code_digits']

2024-06-24 15:18 UTC, HANNICHE-Walid commented on addons/account/models/account_account.py
> +            vals = {k: v for k, v in vals.items() if k not in ['code_digits', 'prefix']}
but I think it's better to override _load_records_write for the account model and pop the these values there

also you can add test where you just call :
 self.env['account.account']._load_records([ 
     { 
         'xml_id': f"account.{company.id}_{xml_id}", 
         'values': values, 
         'noupdate': True, 
     }

2024-06-25 14:17 UTC, HANNICHE-Walid approved these changes

2024-07-09 09:22 UTC, JulienAlardot commented
Could you add a test please?
Wouldn't it make more sense to add the filter here for existing xml_ids?
```
 for fname in list(accounts_data): 
     if company[fname]: 
         del accounts_data[fname]
```

2024-07-09 13:23 UTC, lase-odoo commented
> Could you add a test please? Wouldn't it make more sense to add the filter here for existing xml_ids?
> 
> ```
>  for fname in list(accounts_data): 
>      if company[fname]: 
>          del accounts_data[fname]
> ```

To be honest, I don't really see why it would be better to filter out existing xml ids here instead of ignoring the fields that are only used at creation. The check on aready existing xml id is already done and used few lines afterwards in the `_load_records` call:
https://github.com/odoo/odoo/blob/c897c076731eb73cb43f0304c9b12f4c6b3540a3/addons/account/models/chart_template.py#L749-L756
to determine the records that will be created and those that will be updated using the `_load_record_write`:
https://github.com/odoo/odoo/blob/c897c076731eb73cb43f0304c9b12f4c6b3540a3/odoo/models.py#L5002-L5008
https://github.com/odoo/odoo/blob/c897c076731eb73cb43f0304c9b12f4c6b3540a3/odoo/models.py#L5046-L5048

2024-07-19 12:29 UTC, JulienAlardot approved these changes
LGTM @antoine162

2024-07-26 13:50 UTC, antoine162 approved these changes
Thanks so much!

@robodoo r+

2024-07-27 00:41 UTC, closed without merging