[FIX] point_of_sale,pos_restaurant: remove dead code in pos_store.js
odoo/odoo pull request #170524
Opened 2024-06-24 10:42 UTC by davidmonnom

Remove dead code in pos_store.js

2024-06-24 10:43 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/170524.png)](https://mergebot.odoo.com/odoo/odoo/pull/170524)

2024-06-26 13:55 UTC, adgu-odoo requested changes

2024-06-27 12:45 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/store/pos_store.js
> -    _updateOrder(ordersResponseData, orders) {
Its use in loca of DE but these one will be modified soon by this PR:
https://github.com/odoo/enterprise/pull/63891

Btw in the current state it do not works anyway

2024-06-28 07:24 UTC, adgu-odoo commented
@robodoo r+

2024-06-28 09:35 UTC, closed without merging