[IMP] l10n_nl_reports: tax closing rounding
odoo/odoo pull request #171191
Opened 2024-06-28 10:06 UTC by rugo-odoo

Add the tax report integer rounding in the tax closing.

Also, add the support to a `total` key in the `vat_results_summary` of `_vat_closing_entry_results_rounding`.
That key is used when reports have a single line with the payable/reclaimable vat.

task-3691312

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-06-28 10:07 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/171191.png)](https://mergebot.odoo.com/odoo/odoo/pull/171191)

2024-07-16 15:01 UTC, oco-odoo requested changes

2024-07-30 14:45 UTC, rugo-odoo commented on addons/l10n_nl/data/template/account.account-nl.csv
https://github.com/odoo/odoo/pull/175023

2024-08-19 09:56 UTC, oco-odoo approved these changes
@robodoo r+

2024-08-30 10:01 UTC, robodoo commented
@rugo-odoo @oco-odoo linked pull request(s) odoo/upgrade#6345 not ready. Linked PRs are not staged until all of them are ready.

2024-09-13 18:19 UTC, oco-odoo commented
@robodoo r+

2024-09-14 12:32 UTC, closed without merging