Fix reservation issue
odoo/odoo pull request #171241
Opened 2024-06-28 13:34 UTC by kamranpoladov

Task: 3962125

2024-06-28 13:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/171241.png)](https://mergebot.odoo.com/odoo/odoo/pull/171241)

2024-07-04 12:17 UTC, Sehnde requested changes
Code is ok. Now could you:
- change the PR title to conform to our standards: [FIX] mrp: fix reservation on split
- put the commit message in the PR body
- add a test

Thanks

2024-07-16 08:36 UTC, amoyaux commented
robodoo r+

2024-07-16 08:39 UTC, robodoo commented
@kamranpoladov @amoyaux 'ci/style' failed on this reviewed PR.

2024-07-16 09:24 UTC, amoyaux commented
robodoo r+

2024-07-16 12:58 UTC, closed without merging