[FIX] web_editor : set a nested invisible element to show on click
odoo/odoo pull request #171724
Opened 2024-07-03 08:48 UTC by paru-odoo

Steps to reproduce:
1.Drag & drop a popup
2.Click on its inner block
3.Set the visibility hidden on desktop
4.Save & enter edit mode (not really needed)
5. Click "Block" to show, popup remains hidden

Issue:
Nested elements do not toggle visibility correctly. Clicking "Block" fails to show the popup. Clicking the popup first, then the block, will make it visible.

Key changes:
Previously, only parent-child paths were stored, limiting navigation from parent to child. Now, paths from parent to children are connected and stored.

Solution:
Ensure clicking a child element makes itself and its parents visible. Conversely, clicking on a parent element should hide itself and all its children.

This PR aims to resolve the visibility toggle bug by creating proper parent-to-child connectivity. Clicking on an invisible element now toggles all its parents visible. Similarly, clicking on a visible element toggles all its descendants invisible.

task-3806730

2024-07-03 08:48 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/171724.png)](https://mergebot.odoo.com/odoo/odoo/pull/171724)

2024-07-16 10:48 UTC, robodoo commented
@paru-odoo the target branch 'saas-17.3' has been disabled, you may want to close this PR.

2024-09-30 06:11 UTC, msh-odoo reviewed
Please add tour as well, add snippet, hide some child elements and then test hide/unhide invisible elements with tour steps.

2024-09-30 06:11 UTC, msh-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +        await toggleVisibility($(invisibleEntry.snippetEl));
Try to reduce jQuery code as much as possible.

2024-09-30 06:11 UTC, msh-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +                    parentNodes: (isDescendant && parentNode.length) ? parentNode : [],
```parentNodes``` => ```parents```

2024-09-30 06:11 UTC, msh-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +                        invisibleElement.children = await createInvisibleElements(descendantSnippetEls, true, [invisibleElement]);
Do we really need to wrap it in array?

2024-09-30 06:11 UTC, msh-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +            if (invisibleEntry.parentNodes.length && !invisibleEntry.parentNodes[0].isVisible) {
If are not going to wrap parents in array then we will not need indexing here.

2024-10-18 09:38 UTC, msh-odoo commented on addons/website/static/tests/tours/snippet_visibility_option.js
> +        name: 'Popup',
Double quotes everywhere.

2024-11-05 15:13 UTC, SergeBayet requested changes

2024-11-05 15:13 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +        // To Toggle all its descendents to invisible(Hide)
```suggestion
        // Toggle all its descendants to invisible (Hide)
```

2024-11-05 15:13 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +            // To Toggle all its parentNodes to visible(show)
```suggestion
            // Toggle all its parents to visible (show)
```

2024-11-05 15:13 UTC, SergeBayet commented on addons/website/static/tests/tours/snippet_visibility_option.js
> +]);
Could you add a test following the steps I outlined in my initial comment on the PR once you've addressed the issue?

2024-11-05 15:14 UTC, SergeBayet commented
And thank you for the work by the way :+1:

2024-11-13 08:34 UTC, SergeBayet commented
@paru-odoo Could you rebase your PR to prevent the error in ci/enterprise? Thanks.

2024-11-13 10:20 UTC, paru-odoo commented
Hello @SergeBayet,

> Overall, it seems correct, but I found a corner case. Please follow the steps below:
> 
> 1. Drag and drop a Popup snippet.
> 2. Add a Banner snippet inside the popup.
> 3. Make the Banner invisible for desktop.
> 
> The popup is visible (as expected), but it is incorrectly marked as not visible.

I investigated this bug and found that it has been occurring from v16 to the master branch. Should we consider this issue as a separate task and create a new PR For it? For now, we address it within the scope of this task. I made a separate commit for that. Please take a look !!

Let me know your thoughts. 
Apologize for the late reply. 
Thanks :)

2024-11-13 10:35 UTC, SergeBayet commented
@paru-odoo 
> I investigated this bug and found that it has been occurring from v16 to the master branch. Should we consider this issue as a separate task and create a new PR For it? For now, we address it within the scope of this task. I made a separate commit for that. Please take a look !!
> 
> Let me know your thoughts. Apologize for the late reply. Thanks :)

If the bug occurs in 16.0, you should definitely create a new PR targeting 16.0 to address the issue. I let you create the task and the PR. When this PR targeting 17.4 is merged, we'll merge the other one. Are you ok with that? Thanks.

2024-11-13 11:25 UTC, paru-odoo commented
>If the bug occurs in 16.0, you should definitely create a new PR targeting 16.0 to address the issue. I let you create the task and the PR. When this PR targeting 17.4 is merged, we'll merge the other one. Are you ok with that? Thanks.

Sure, I'm ready to proceed with this. I just need to inform @msh-odoo about it, and then I'll carry it forward.

2024-11-15 10:27 UTC, paru-odoo commented
Hello @SergeBayet 
We have created a new task with a new PR targeting version 16.0. Can we proceed with this task now? Here are the details:
- PR: [https://github.com/odoo/odoo/pull/187233/files](https://github.com/odoo/odoo/pull/187233)
- Task ID: [https://www.odoo.com/odoo/project/974/tasks/4337481](https://www.odoo.com/odoo/project/974/tasks/4337481)

I have just rebased on this PR also.
Thanks for your review!

2024-11-20 09:01 UTC, SergeBayet requested changes
Thanks for the changes. Still some remarks below. We're almost there :)

2024-11-20 09:01 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +            if (invisibleEntry.parents && !invisibleEntry.parents.isVisible) {
Maybe `else if {` ? What do you think?

2024-11-20 11:54 UTC, SergeBayet commented
@robodoo r+

2024-11-20 11:54 UTC, robodoo commented
I'm sorry, @SergeBayet. I'm afraid I can't do that.

2024-11-20 12:16 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2024-11-20 15:51 UTC, SergeBayet commented
@paru-odoo Resolve the conflict and I'll r+ :+1:

2024-11-21 07:00 UTC, paru-odoo commented
Hello @SergeBayet , I have resolved the conflict.
Thanks for your time :)

2024-11-21 08:00 UTC, SergeBayet commented
@robodoo r+

2024-11-21 11:29 UTC, closed without merging