[FIX] website: prevent duplicate menu creation on page creation
odoo/odoo pull request #171783
Opened 2024-07-03 13:03 UTC by lucasth-dev

This commit has for main purpose to prevent the menu creation when people leave the option of creating a menu during page creation if a menu already exists pointing to that url for this specific website.

Steps to reproduce :
 - Add a menu item for 'Hello Page' and 'hello-page' URL
 - Create a page 'Hello Page' (leave the option of adding the menu item checked) => There is 2 entries in menu for the same page

task-3634878

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-03 13:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/171783.png)](https://mergebot.odoo.com/odoo/odoo/pull/171783)

2024-10-16 13:20 UTC, robinlej commented
Retargeted the PR to 16.0 and added `limit=1` to the `search_count`.

2024-10-30 15:54 UTC, qsm-odoo requested changes

2024-10-30 15:54 UTC, qsm-odoo commented on addons/website/models/website.py
> +                result['menu_id'] = menu.id
Stability issue: now `'menu_id'` is not part of the result always, potentially breaking custo. In the end, it was already dubious to target stable for this fix, let's change our mind: I'll retarget to master.

2024-10-30 16:24 UTC, qsm-odoo approved these changes
@robodoo r+

2024-10-30 19:42 UTC, closed without merging