[FIX] website: horizontal scroll of company team snippet
odoo/odoo pull request #171886
Opened 2024-07-04 07:15 UTC by lucasth-dev

This commit removes the padding right of the last row of the grid layout of the company team snippet. This is to prevent this snippet from having a width larger than the screen and it prevent the window from having an useless horizontal scrollbar.

Steps to reproduce :
 - Enter edit mode
 - Drag & Drop a company team snippet
 - Check grid mode & content width : full
 - Save it 
 => A horizontal scroll bar appears because the section of the snippet is too wide.

opw-3981579

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-04 07:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/171886.png)](https://mergebot.odoo.com/odoo/odoo/pull/171886)

2024-07-04 15:47 UTC, qsm-odoo requested changes
@lucasth-dev Also, commit message: max 72 chars per line :+1:

2024-07-04 15:47 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_company_team/000.scss
> +                margin-right: 0;
@lucasth-dev That's not the right fix, for multiple reasons:

- First given the nature of the bug, this is really not something that is only present for the company team snippet but a general issue of the grid mode: any row as a direct child of a grid item would have the problem. The fix should thus not be here but in the grid mode general CSS.

- "Any row as a direct child of a grid item has the problem" => Indeed the issue is that we do not enforce that the padding of a grid item (which the user can control) is bigger than the gutter-grid i.e., the space that rows compensate (and sub-columns uses as padding). => I think the fix is indeed changing the negative margin of those rows but not to 0: setting it to compensate the exact size of the grid item padding.

cc @sobo-odoo You might be interested to know :)

2024-07-10 12:21 UTC, qsm-odoo requested changes

2024-07-10 12:21 UTC, qsm-odoo commented on addons/web_editor/static/src/scss/web_editor.frontend.scss
> +    }
Put this just before the `.o_grid_item_image {` rule. It should not be in the scope of `.container-fluid > .o_grid_mode`, the bug is the same for other container than `.container-fluid`, even if there is no overflow/scrollbar in those cases.

2024-07-17 13:22 UTC, loco-odoo commented
Hello @lucasth-dev :wave: I had a look at your PR and I think there is an unexpected behavior. I made a video to make it clearer: 
[Screencast from 07-17-2024 03:19:24 PM.webm](https://github.com/user-attachments/assets/b6ba0074-889c-4b0c-b049-b57f4adf1677)
In fact, when changing the padding of the gird item in your PR, it does not seem to have an impact on the column position while it has in stable ;) Can you have a look? :pray:

2024-08-12 13:48 UTC, sobo-odoo commented
Closing this => it will be fixed in this [other PR](https://github.com/odoo/odoo/pull/176421) (with another bugfix for an OPW) :+1:

2024-08-12 13:48 UTC, closed without merging