[IMP] im_livechat: navigating livechat sessions
odoo/odoo pull request #172042
Opened 2024-07-05 05:13 UTC by jayp-odoo

**Current behavior before PR:**

Since v17, we open all the livechat sessions in Discuss, which is better in terms of UX, but doesn't allow you to switch from one session to another, as we only open the selected one.

**Desired behavior after PR is merged:**

This commit improve this when in livechat a session is opened from the session history, it is now open with pager to navigate back and forth with the use of form renderer.

Task-3764236

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-05 05:14 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172042.png)](https://mergebot.odoo.com/odoo/odoo/pull/172042)

2024-08-16 09:16 UTC, rapr-odoo commented
PR needs a rebase. And could you please split the changes in two commits. Separating the changes for the new component and Livechat Sessions Navigation. 
As the PR contains changes in `mail` aswell, do include it in the PR and commit title.

2024-09-11 06:04 UTC, rapr-odoo requested changes

2024-09-11 06:04 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.js
> +        );
It is not a preferred way.

2024-09-11 06:04 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.js
> +    }
All these methods which you added here which are related to the `DiscussHeader` component should have been removed from `discuss.js` aswell.

2024-10-01 10:56 UTC, rapr-odoo reviewed
Convert all the classNames in the new `DiscussHeader` component according to BEM

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +        <div class="o-mail-Discuss-header px-3 d-flex flex-shrink-0 align-items-center border-bottom z-1 flex-grow-0" t-ref="header">
Please follow BEM convention in Discuss code:

- Template is named moduleName.ComponentName
- Root node is named o-moduleName-ComponentName
- Parts are named o-moduleName-ComponentName-partName

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +                    <div t-if="['channel', 'group', 'chat'].includes(thread.channel_type)" class="o-mail-Discuss-threadAvatar position-relative align-self-center align-items-center mt-2 mb-2 me-2">
Same here.

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +                    <div t-if="['channel', 'group', 'chat'].includes(thread.channel_type)" class="o-mail-Discuss-threadAvatar position-relative align-self-center align-items-center mt-2 mb-2 me-2">
You can write it in multiline to make it more readable.

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +                        <FileUploader t-if="thread.is_editable" acceptedFileExtensions="'.bmp, .jpg, .jpeg, .png, .svg'" showUploadingText="false" multiUpload="false" onUploaded.bind="(data) => this.
Same here.

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +                        <FileUploader t-if="thread.is_editable" acceptedFileExtensions="'.bmp, .jpg, .jpeg, .png, .svg'" showUploadingText="false" multiUpload="false" onUploaded.bind="(data) => this.
Same here.

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.xml
> +                    <CountryFlag t-if="thread.anonymous_country" country="thread.anonymous_country" class="'o-mail-Discuss-headerCountry border'"/>
class name.

2024-10-01 10:56 UTC, rapr-odoo commented on addons/mail/static/src/core/common/discuss_header.js
> +            : false;
`this.store.discuss.thread` -> `this.thread`

2025-02-18 16:29 UTC, seb-odoo commented
Hello, could you rebase the PR please? There are some conflicts and outdated features still present, and we'd like to more forward with it soon!

2025-02-20 11:49 UTC, jayp-odoo commented
@seb-odoo Hey :wave: 
I have improved the code with little different approach. Could you please have a look.
Thanks :)

2025-02-28 11:40 UTC, seb-odoo reviewed
Hello, the code is much cleaner like this!

The only "problem" is that it actually thinks the user is in discuss app, so it hides chat window and opens new thread inside the live chat view. It would be nice to change this behavior.

A related issue to previous point is that it actually changes the active discuss thread, when going back to the discuss app for example, it keeps the last visited livechat thread instead of keeping whatever was the active thread on discuss initially.

2025-02-28 11:40 UTC, seb-odoo commented on addons/im_livechat/static/src/core/common/thread_actions_patch.js
> +patch(threadActionsRegistry.get("notification-settings"), {
Why do we need to patch all of those? I think it would be fine to keep the default behavior.

2025-02-28 11:40 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +        }
Could we easily change the code so that discuss app component can take the thread as props rather than having to change the real discuss thread in models?

2025-02-28 13:11 UTC, jayp-odoo commented
@seb-odoo hello
i have updated the code, also as per AJU review on [task](https://www.odoo.com/odoo/project/1519/tasks/3764236) pad we have to hide the above thread actions when livechat is ended.

2025-02-28 13:16 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +        onMounted(() => (this.store.discuss.isActive = false));
Rather than overriding the other value here, it would be nice the original value was only set when necessary (so in "discuss_client_action" rather than discuss component).

2025-02-28 13:17 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +    async restoreDiscussThread(props) {
I would name this differently, it's not longer related to discuss thread, just "get live chat channel" or something like that.

2025-02-28 13:17 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +        }
This check is not needed here, we want to display the provided thread no matter what.

2025-02-28 13:22 UTC, seb-odoo commented on addons/im_livechat/static/tests/tours/im_livechat_history_back_and_forth.js
> +            trigger: ".text-truncate:contains(Visitor)",
.text-truncate is not a very descriptive/reliable selector.
Can't we have a target a little bit more functionally significant?

2025-02-28 13:26 UTC, seb-odoo commented on addons/im_livechat/static/src/core/common/thread_actions_patch.js
> +            !component.thread?.composerDisabled
Shouldn't these conditions be on `livechat_active` instead? `composerDisabled` looks too specific to another purpose.

Also, it would be nice to call super && ... rather than redefining everything.
+ don't we want to apply the override code only for livechat channel type?

2025-02-28 13:33 UTC, seb-odoo reviewed
See all remaining comments above, but otherwise the code is pretty good now, thank you! After the last cleanup we can look to final test and move forward with the PR.

2025-02-28 13:33 UTC, seb-odoo commented on addons/im_livechat/static/tests/tours/im_livechat_session_history_open.js
> +            trigger: ".o_command:contains(Sessions History)",
We should click on the full name "Live Chat / Report / Sessions History" if possible, to avoid any possible miss-click if other elements are named the same.

2025-02-28 13:33 UTC, seb-odoo commented on addons/im_livechat/static/tests/tours/im_livechat_session_history_open.js
> +            run: "fill Live Chat",
searching for "Sessions History" might be more specific here

2025-02-28 13:33 UTC, seb-odoo commented on addons/im_livechat/static/tests/tours/im_livechat_session_history_open.js
> +        },
Is there a particular reason to switch to list view rather than clicking on a session from the kanban page directly?

2025-03-03 09:42 UTC, jayp-odoo commented
@seb-odoo Hi,  

I've updated the code, and I believe it aligns with your suggestions. Regarding your last comment about changing the view from Kanban to List, I've made that adjustment to maintain the order of Live Chat records, allowing me to test that they are in the correct order.  

Thanks!

2025-03-06 05:43 UTC, jayp-odoo commented
@seb-odoo  Hiii
the PR has been updated few days ago please have look. 
its just reminder
Thanks!

2025-03-13 17:22 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +    async get_channel(props) {
Method name in js are usually camelCase

2025-03-13 17:22 UTC, seb-odoo commented on addons/im_livechat/static/src/views/livechat_form_renderer.js
> +        const activeThread = await this.store.Thread.getOrFetch({
this.thread could be assigned directly here

2025-03-13 17:22 UTC, seb-odoo commented on addons/im_livechat/tests/test_session_history_open.py
> +        ])
(apply formatter/this could be much less lines)

2025-03-13 17:22 UTC, seb-odoo commented on addons/im_livechat/static/src/views/discuss_template.xml
> +        <Discuss hasSidebar="false" thread="thread"/>
We might want to be careful here, if `get_channel` returns no thread, the props will be falsy, and the getter in discuss will display `this.store.discuss.thread` rather than no thread, which is not what we want.

2025-03-13 17:22 UTC, seb-odoo commented on addons/mail/static/src/core/public_web/discuss.js
> +        return this.props.thread || this.store.discuss.thread;
Cf. other comment, this should have a way to determine we are in livechat history but no thread was found.

2025-03-13 17:22 UTC, seb-odoo commented on addons/mail/static/src/core/public_web/discuss.js
>          onWillUnmount(() => (this.store.discuss.isActive = false));
This should be moved  to client action as well.

2025-03-21 05:02 UTC, jayp-odoo commented
@seb-odoo :wave: 
I've pushed the updated code, which should meet all your requirements. Regarding the flickering issue, I haven't been able to find a solution yet. If you can help with that, it would be great. Otherwise, we can address it in a follow-up PR later, as it's not a major issue. It also occasionally occurs in the Chatter within form renderers.

2025-03-24 15:09 UTC, seb-odoo approved these changes
@robodoo r+

2025-03-24 17:09 UTC, closed without merging

2025-04-01 13:22 UTC, seb-odoo commented on addons/im_livechat/views/discuss_channel_views.xml
>                      <sheet>
Hello, I'm wondering shouldn't we have removed the content of this form view as we are using a fully custom renderer?

2025-04-01 13:31 UTC, jayp-odoo commented on addons/im_livechat/views/discuss_channel_views.xml
>                      <sheet>
Hello! :wave:  
maybe it can be removed, but I kept that part because I thought it might be needed if something happens with the JS form rendering. If you suggest removing it, I'll make sure to create a PR for it.

2025-04-01 13:32 UTC, seb-odoo commented on addons/im_livechat/views/discuss_channel_views.xml
>                      <sheet>
Yes please, let's make a PR and see what happens if we remove it completely!