[FIX] l10n_in: Made invoice_label field more concise
odoo/odoo pull request #172469
Opened 2024-07-09 13:21 UTC by hsal-odoo

This commit simplifies the labels on invoices in the Indian accounting localization package.

task-4035245

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-09 13:22 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172469.png)](https://mergebot.odoo.com/odoo/odoo/pull/172469)

2024-07-12 07:27 UTC, jva-odoo commented
minimus we need the Name of the tax, Percentage and section of the tax like this
`TCS 1% 206C(1)`
for tax name also

2024-07-12 08:16 UTC, jva-odoo requested changes
minimum we need the Name of the tax, Percentage and section of the tax like this
`TCS 1% 206C(1)`
for tax name also

2024-09-16 14:40 UTC, JulienVR reviewed
@robodoo r+

2024-09-16 17:05 UTC, closed without merging