[ADD] hr_homeworking_calendar_google: workLocation synchronization
odoo/odoo pull request #172780
Opened 2024-07-11 14:43 UTC by geflx

This module allows synchronizing the work locations from Google Calendar to Odoo Calendar through the synchronization of events with 'eventType' attribute 'workLocation'. When fetching these events, we create the new work locations in Odoo using the labels described there and set the most recent work location positions in the 'Employee' model.

For avoiding duplicating the information (synchronizing workLocation events and also setting the work location in the Employee model), we decided to not synchronize this type of event anymore and only use the information they provide: the work location itself.

A cron job is defined for executing the fetching from Google and work location update in Odoo every sunday for keeping the synchronization up-to-date.

task-3809350

2024-07-11 14:43 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172780.png)](https://mergebot.odoo.com/odoo/odoo/pull/172780)

2025-04-23 15:02 UTC, arj-odoo requested changes
These kind of tasks are tricky. Thanks a lot for looking at it. 
I just looked quickly to the overall code, I did not checked out it yet or tested it deeply.
I am afraid of regressions. Would it be possible to add some tests in the new module to validate the behavior we want ? Thanks.

2025-04-23 15:02 UTC, arj-odoo commented on addons/hr_homeworking_calendar_google/models/res_users.py
> +        self.env.cr.execute("""SELECT id FROM res_users WHERE id = %s FOR NO KEY UPDATE SKIP LOCKED""", [user.id])
some explanation why you need to lock the row here would be welcome :-).

2025-04-25 12:57 UTC, geflx reviewed
Thanks! Next up: adding tests. (didn't add them before because it was just a POC)

2025-05-14 09:02 UTC, arj-odoo commented on addons/hr_homeworking_calendar_google/data/ir_cron_data.xml
> +            <field name="interval_number">7</field>
Maybe 7 days are too much. Could it cause issue if a lot of user are created or if homeworking locations are updated and the odoo code is still using the old one ?

2025-05-21 14:21 UTC, arj-odoo commented on addons/google_calendar/utils/google_calendar.py
> +        }
it will crash if it called without start or end value provided.
I would default to today in that case.

2025-05-21 14:23 UTC, arj-odoo commented on addons/hr_homeworking_calendar_google/data/ir_cron_data.xml
> +            <field name="interval_number">7</field>
It depends on the value we have on start and end. too. I am not sure. we can think about it and decide at review.

2025-05-21 14:24 UTC, arj-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +                existing_location_names += [location_name]
warning, you are creating potentially a lot of records in a loop.

2026-03-16 13:01 UTC, arj-odoo reviewed
@reth-odoo may be interested by this PR. It was started a long time ago and it is mature now but I would like to have his opinion on it as he may have to modify the code later.

2026-03-16 13:01 UTC, arj-odoo commented on addons/google_calendar/models/google_sync.py
> +        self._pre_process_google_events(existing)
existing is a subset of google_events. Why do we need to run _pre_process_google_events twice on these ?

2026-03-17 08:30 UTC, reth-odoo reviewed
👁️ 👁️ I see

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        ignored = [e for e in gevents if e.eventType == 'workingLocation']
You can use `gevents.filter for this`, avoids building an intermediary array.
Same below

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/models/google_sync.py
> +        return GoogleEvent([])
init iterator is optional
```suggestion
        return GoogleEvent()
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/utils/google_event.py
> +        # Fast path for empty sets.
To justify that this is ok to do
```suggestion
        # Fast path for empty sets, as event sets are immutable
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/utils/google_calendar.py
> +            _, data, _ = self.google_service._do_request(url, params, headers, method='GET', timeout=timeout)
Would set a non-zero fallback (or have an assert) to follow the spirit of the security warning on missing timeout
```suggestion
            _, data, _ = self.google_service._do_request(url, params, headers, method='GET', timeout=timeout or 3)
```

Also is there a reason to use 3 instead of TIMEOUT as above?
I suppose there's fewer workingLocation events generally (probably no more than 7?), but it might worth a comment

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/utils/google_event.py
> +        return GoogleEvent({**self._events, **other._events})
We could probably improve `__init__` with
```py
if isinstance(iterable, self.__class__):
    self._events = iterables._events
    return
for item in iterable:
    if isinstance(item, self.__class__):
        _events |= item._events
```
instead of what is there now, since we can assume a `GoogleEvent` is well-formed (+ immutable, which is already assumed with current imp)

And here you would just `GoogleEvent((self, other))`
This would avoid creating a new dict here, just for it to be iterated on to create a new one right after in `__init__`.

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/tests/test_work_location_sync.py
> +        with self.mock_datetime_and_now("2025-04-28"):
Maybe have a `@mock_datetime_and_now`?

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/models/google_sync.py
> +        pending = existing - cancelled - self._get_skipped_google_events(existing)
What happens if you just install google calendar, sync some events, then install hr_homeworking? I guess we'll still try syncing to google, but never again from google? It could be a bit confusing if you've been using calendar normally until now.

2026-03-17 08:30 UTC, reth-odoo commented on addons/google_calendar/utils/google_calendar.py
> +        }
I wonder if we could just update get_events to optionally take `(start: datetime, end: datetime, eventTypes: str, singleEvents: bool)` parameters to avoid having too many bespoke API routes

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            return 'office', props['officeLocation'].get('label', 'Office')
Should these fallback labels be translated?

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            dt_str = e.start.get('date') or e.start.get('dateTime', '')[:10]
🤔 Not a massive fan of this, I guess we're cutting off the value to `yyyy-MM-dd`?
What about timezones if it's from the `dateTime` field?

Can't we just fromisoformat the whole thing and then call `datetime.date()`?

--------------------------

If we only call prepare from the regular sync, we can also take advantage of the fact that _odoo_values gets called anyways, pass the values in here and avoid having to parse it twice

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/res_users.py
> +        return True
If we're going to do update it every single time we sync anyways, do we need really an additional cron? Isn't the one that runs every 12 hours by default sufficient?

It seems like not having this would remove quite a bit of code

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        existing_map = {loc.name: loc for loc in existing}
```suggestion
        work_location_by_location_data = {(loc.location_type, loc.name) : loc for loc in existing}
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +                required_names.add(name)
I think we can avoid some iterating and filtering by just storing everything.
Also to handle the case where you might have two locations with the same name but not the same type.
I guess with the current code it's unlikely to matter but it could ease overrides.

```suggestion
        gevents_by_location_data = {}  # {name: gevent_id[]}
        for e in gevents:
            location_data = self._get_location_data(e)
            if location_data[1]:
                gevents_by_location_data.setdefault(location_data, []).append(e)
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +                to_create.append({'name': name, 'location_type': self._get_location_data(ref_event)[0]})
```suggestion
        for location_data in gevents_by_location_data:
            if location_data not in work_location_by_location_data:
                # Find a sample event to deduce the type.
                location_type, name = location_data
                to_create.append({'name': name, 'location_type': location_type})
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        for e in gevents:
```py
for location_data, gevents in gevents_by_location_data:
    for event in gevents:
        # here have access to location data directly, just get the id from the other dict
```

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            user.employee_id.sudo().write(updates)
Is it really useful to create the work location if nobody is going to be using them?
Would say we should check user.employee_id at the top

Also do we need to check anything for this sudo to be valid? Not sure if there's a flow where you could reach here with another user than yours (and not be root), but if so maybe we should check you can write on the user or something like that?

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/tests/test_work_location_sync.py
> +    def setUp(self):
Can probably be setUpClass, as long as you don't modify `work_location_simple_values` (maybe use frozendict to ensure that)

2026-03-17 08:30 UTC, reth-odoo commented on addons/hr_homeworking_calendar_google/tests/test_work_location_sync.py
> +        with self.mock_datetime_and_now("2025-04-28"):
Can't we test all of these in one test? Since they all behave the same, we can just import all of them at once right?

And this way we can also check that multiple events with the same label map to the same location

2026-03-19 14:52 UTC, geflx reviewed
Thanks for the review @arj-odoo, change applied.
Thank you too for the review @reth-odoo, the calendar app is in good hands.
- **Nearly all** suggestions applied, I just skipped not necessary ones for now (e.g. future IMPs).
- Module renamed to `hr_calendar_google` because recently `hr_homeworking_calendar` got merged at `hr_calendar`. 
Cheers. 🍻

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/models/google_sync.py
> +        self._pre_process_google_events(existing)
Good point, it's been a while so I don't remember why I added this second processing, removed.

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/models/google_sync.py
> +        pending = existing - cancelled - self._get_skipped_google_events(existing)
This was from a discussion that I had with Damien, we thought it was better to introduce this behavior to avoid having double information listed there. Honestly it's harmless keeping them, so I'm removing it. Thanks.

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/models/google_sync.py
> +        return GoogleEvent([])
Function removed as discussed in the comment above.

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/utils/google_calendar.py
> +        }
Certainly, updated!

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/utils/google_calendar.py
> +            _, data, _ = self.google_service._do_request(url, params, headers, method='GET', timeout=timeout)
I dropped the function following our agreement of re-using `get_events`.

2026-03-19 14:52 UTC, geflx commented on addons/google_calendar/utils/google_event.py
> +        return GoogleEvent({**self._events, **other._events})
That's a good idea, I won't apply in this one to keep minimal changes on the utils.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        ignored = [e for e in gevents if e.eventType == 'workingLocation']
Function dropped following the other comment.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            return 'office', props['officeLocation'].get('label', 'Office')
Great catch, updated.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            user.employee_id.sudo().write(updates)
They will be used, on that week, and can be reused again. For the sudo,iit's a common practice around HR of calling it on `employee_id`, it is better to keep it.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +                required_names.add(name)
Applied.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        existing_map = {loc.name: loc for loc in existing}
Applied.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +                to_create.append({'name': name, 'location_type': self._get_location_data(ref_event)[0]})
Applied.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +        for e in gevents:
Applied with an improvement.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/google_sync.py
> +            dt_str = e.start.get('date') or e.start.get('dateTime', '')[:10]
`fromisoformat` applied.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/models/res_users.py
> +        return True
I really recommend this additional one, for keeping work location updated as much as possible. It is lightweight because we do that only for the working location events and for that week.

2026-03-19 14:52 UTC, geflx commented on addons/hr_homeworking_calendar_google/tests/test_work_location_sync.py
> +        with self.mock_datetime_and_now("2025-04-28"):
I'll let that for a future improvement.

2026-04-03 12:44 UTC, arj-odoo commented
@robodoo r+ rebase-ff

2026-04-03 12:44 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2026-04-03 15:17 UTC, closed without merging