[IMP] l10n_cl: Show parent customer on invoice report
odoo/odoo pull request #172793
Opened 2024-07-11 17:00 UTC by euvm-odoo

Description of the issue/feature this PR addresses:

## Current behavior before PR:
For legal reasons, the name that should appear in the invoice report is the contact's parent (aka, their employer company). Currently, the child contact appears. 
![image](https://github.com/euvm-odoo/odoo/assets/141070241/508ed141-bedd-40c2-a65d-76337b678f4d)

Desired behavior after PR is merged:
The parent contact should appear if it exists
![image](https://github.com/euvm-odoo/odoo/assets/141070241/6d5f4447-3d0c-4a07-9656-25d2208a08f8)

TaskL: https://www.odoo.com/odoo/project/49/tasks/4048759?cids=17

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-11 17:01 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172793.png)](https://mergebot.odoo.com/odoo/odoo/pull/172793)

2024-07-26 15:24 UTC, euvm-odoo commented
Hello @chklop @fvz-odoo do we have any updates regarding this?

2024-07-27 17:49 UTC, fvz-odoo commented
Hello @euvm-odoo 

I'm currently away. @masi-odoo could you please check? Also, to change something in the CL localization, we need to follow the normal path, consult the POs team and if this is actually a legal requirement, then create a full spec (doesn't need to be long, but has to have all info necessary) with the legal documentation as well. 

Thanks and cheers!

Fernando

@chklop @ren-odoo

2024-08-18 10:21 UTC, jota2rz commented
@fvz-odoo @chklop @euvm-odoo 

Hi, I'm not part of Odoo or Odoo PO team but I'm an active Odoo 17 Enterprise SaaS user.
I have found myself with this same problem and ended up finding this GitHub issue.

I can confirm the name that has to legally appear in any type of chilean electronic invoice must be the legal business name (aka employer company), the technical reference for XML is "<RznSocRecep> (52)" and must be shown printed at all times.

Additionally, the contact name (aka employeer name) can be referenced in the XML field "<Contacto> (58)" and it's legally optional to be included in the XML or to be shown printed.

This technical and legal compliance can be read at https://www.sii.cl/factura_electronica/formato_dte.pdf for confirmation.

2024-08-19 08:03 UTC, chklop commented
@fvz-odoo @masi-odoo Looks like a one-line fix here, shall we proceed ?

2024-08-19 16:53 UTC, mial-odoo commented on addons/l10n_cl/views/report_invoice.xml
> +                <span t-out="o.partner_id.parent_id.name or o.partner_id.name"/>
EUVM is no longer working at Odoo but I agree with you!

2024-08-19 18:30 UTC, masi-odoo commented on addons/l10n_cl/views/report_invoice.xml
> +                <span t-out="o.partner_id.parent_id.name or o.partner_id.name"/>
Hello again @chklop seems that the developer that created this PR no longer works at Odoo, do you think you can assign someone or should we look for other developer in the MX office?

Thanks!

2024-08-19 18:35 UTC, masi-odoo commented on addons/l10n_cl/views/report_invoice.xml
> +                <span t-out="o.partner_id.parent_id.name or o.partner_id.name"/>
Already assigned to @road-odoo, still thanks!

CC @chklop @mial-odoo

2024-08-20 07:40 UTC, rugo-odoo requested changes
Make sure to give [a valid name to your commit](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html) and squash them :slightly_smiling_face:

2024-08-20 17:28 UTC, masi-odoo commented
Hello @road-odoo I also gave it a FUN test and here are my comments:

- The change is working an indeed, the report is printing the commercial partner name
- Nevertheless, it seems it broke the header of the report, I am not seeing the fiscal elements that are regularly printed:

![image](https://github.com/user-attachments/assets/f9abca1b-b6d9-4c7d-814d-7dfbd8a95a28)

The expected behavior should be to have this header:

![image](https://github.com/user-attachments/assets/9ecfaf70-202f-4ebc-928d-a9f1861d3f1e)

Can you check this? Thanks!

2024-08-21 16:17 UTC, masi-odoo commented
Hello @road-odoo it seems the issue with the header (reported in the PR) was just a problem of my own laptop.

It is working fine and the functionality LGTM!

CC @mial-odoo @ren-odoo @chklop @fvz-odoo

2024-08-21 17:13 UTC, road-odoo commented
Hi @rugo-odoo I've just done the squash of the commits and changed the header.

2024-08-21 20:13 UTC, masi-odoo approved these changes

2024-08-21 20:43 UTC, mial-odoo approved these changes

2024-08-27 16:05 UTC, masi-odoo commented
Hello @rugo-odoo can you re-take a look on this? Thanks!

2024-08-29 07:33 UTC, rugo-odoo commented
@masi-odoo @road-odoo runbot is red :grimacing:

2024-08-29 18:30 UTC, road-odoo commented
Hi @rugo-odoo I was checking here https://runbot.odoo.com/runbot/build/67169441 that the tests that broke seem to already have been fixed in a posterior commit.

2024-08-30 07:38 UTC, rugo-odoo commented
Hey @road-odoo, you can rebase and push again (the error should go away then).

2024-09-04 16:07 UTC, masi-odoo commented
Hello @road-odoo can you take a look at the last comment by @rugo-odoo ?

Thanks!

2024-09-04 16:53 UTC, road-odoo commented
Hi @rugo-odoo they didn't disappear but they still show the message that says that the error was already fixed
![Screenshot 2024-09-04 at 10 52 19 a m](https://github.com/user-attachments/assets/b2bad8bf-8ab3-4f25-8cee-746fa3e1ac0e)

2024-09-05 07:25 UTC, rugo-odoo commented
@road-odoo how did you rebase and push when your runbot don't show activity since the 29 august (the same date as your screen by the way) but I made my comment the 30 august ?

2024-09-09 07:19 UTC, rugo-odoo commented
@robodoo r+

2024-09-09 09:07 UTC, closed without merging