[FIX] point_of_sale, pos_loyalty: add context when loading data params
odoo/odoo pull request #172769
Opened 2024-07-11 12:33 UTC by Axel927

Fix for 17.1 and 17.2 only

Problem:
en_US data is loaded while the user uses another language

Steps to reproduce:
- Install "point_of_sale" app and "pos_loyalty" module
- Change the language (e.g. to french)
- Go to POS -> Products -> Discount & Loyalty
- Create a new Loyalty Card
- In Rewards, set a discount of 20 $ on order and save
- Go to the shop and select a partner and a product (price must be expensive enough for the loyalty card to be applicable)
- Click on "Reward", the earlier created reward is there
- Go back to the form of the loyalty card and change the value and save
- Go back to the shop
- Click on "Reward" and the name of the loyalty card is still the same as before while it should be for the new price

Note:
This error has been already fixed but this commit generalize the solution to all the params. So the previous fix is replaced by this one.
See this PR for the previous fix and the test: https://github.com/odoo/odoo/pull/171049

Solution:
Set the environment context for each data param so that the language is loaded by creating a wrapper. Only apply a context if some has not already been defined for specific cases where a different context is needed. "_load_data_params_with_context" replaces "_load_data_params" only where the context is used to keep a bit of optimization.

opw-4039850

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-11 12:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172769.png)](https://mergebot.odoo.com/odoo/odoo/pull/172769)

2024-07-15 09:28 UTC, robinengels approved these changes

2024-07-17 08:00 UTC, davidmonnom requested changes
Since we're now applying context to each model, why not modify lines 337 and 334 directly?

2024-07-17 08:01 UTC, davidmonnom commented
@robodoo r+

2024-07-17 10:28 UTC, closed without merging