Display the Expiration Date and Number of Allocated Leaves that aren't Carried Over on the Dashboard
odoo/odoo pull request #172892
Opened 2024-07-12 07:33 UTC by abdelrahmankhaledg

Description of the issue/feature this PR addresses: If you create an allocation with an end date, you will see a warning on the dashboard indicating how long the allocated leaves will be valid before they expire. However, if you create an allocation with an accrual plan having carryover `None` or `Carryover with a maximum`, then some allocated leaves may expire by the carryover date. Yet, there is no warning on the dashboard to indicate the validity period of the allocated leaves that aren't carried over.

This commit fixes the issue by computing the number of days that will expire on the carryover date and displays the expiration date and the number of expired leaves on the dashboard.

task-3978653

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-12 07:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/172892.png)](https://mergebot.odoo.com/odoo/odoo/pull/172892)

2024-09-02 11:52 UTC, Bertrand2 requested changes
Thanks for the PR!
I feel like the code you made for the whole logic is a bit overkill; defining  that much small methods that are called only once is a bit confusing, and I'm guessing we could simplify by looping over the allocations and keeping the one with the closest date, be it date_to or next carryover :thinking: What do you think? :)

2024-09-06 12:18 UTC, Bertrand2 requested changes

2024-09-11 08:49 UTC, Bertrand2 commented on addons/hr_holidays/models/hr_leave_type.py
> +            closest_expiration_date = False
Indeed! My bad I misread your method :) LGTM then

2024-09-11 08:49 UTC, Bertrand2 approved these changes

2024-09-11 13:00 UTC, tivisse commented
@robodoo r+

2024-09-11 13:00 UTC, robodoo commented
@tivisse you may want to rebuild or fix this PR as it has failed CI.

2024-09-11 13:53 UTC, tivisse commented
@abdelrahmankhaledg Yeah you can move the test to the other task then ^^

2024-09-11 17:19 UTC, tivisse commented
@robodoo r+

2024-09-12 05:37 UTC, closed without merging