[FIX] website_sale: issue when editing address after selecting a pickup point
odoo/odoo pull request #173471
Opened 2024-07-17 08:53 UTC by LouisGobert

Problem: When a pickup point is selected for delivery and the shipping address is then modified, the pickup point remains selected in the frontend but not in the backend, allowing an order to be validated with an unselected pickup point.

Steps to Reproduce:
1. Configure a pickup point provider (ex: Sendcloud).
2. Add a product to the cart.
3. Proceed to checkout.
4. Select a pickup point for delivery.
5. Enter in the page to edit address.
6. Confirm to return to the payment page -> As you will see, a pickup point address is selected, but pickup point addresses list are also visible.
7. Pay -> The shipping address will be the last selected shipping address instead of the pickup point address.

Solution:
Reset ´access_point_address´ in ´/shop/confirm_order´ endpoint to prevent the pickup point from remaining selected when editing an address.

opw-4040321

2024-07-17 08:54 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173471.png)](https://mergebot.odoo.com/odoo/odoo/pull/173471)

2024-07-17 15:18 UTC, vchu-odoo requested changes
Hello,

Thanks for your fix!
We have already encountered and fixed this problem as a part of the task for saas-17.3.
If address is changed then `_check_carrier_quotation` is called which resets the carrier.
The idea is to reset pickup_location on removing delivery line from the order like this.
https://github.com/odoo/odoo/blob/saas-17.3/addons/website_sale/models/sale_order.py#L643-L645

To keep delivery logic separate from the main flow and keep it consistent with the following versions could you apply the same fix as for saas-17.3?

2024-07-18 07:39 UTC, LouisGobert commented
Hello,

The issue is that the call to “/shop/confirm_order” always triggers a “/shop/update_carrier” (even if the address hasn’t changed) when clicking “Confirm”.

As shown in the logs, the "/shop/update_carrier" is called after “access_point/get”, which invalidates the frontend display because the pickup point is reset after being retrieved:
![image](https://github.com/user-attachments/assets/72202f90-96a5-4e0f-a0bd-f7e100c8d2f2)




This is why I ensure the pickup point is reset as soon as the “/shop/confirm_order” endpoint is called.

Could you please provide some guidance on how to implement the solution you propose on 17.0 ? 
Thanks :)

2024-07-18 09:28 UTC, vchu-odoo commented
The problem that I see is that your solution patches one problem but another one stays. If you choose pickup location and then reload the `/payment` page it would result in the same bug because the flow in `website_sale_delivery.js` is poorly handled. 
For ex. I spotted that 
1)
https://github.com/odoo/odoo/blob/607e454f65c2c60c4ee5169bc53706f24a8bc625/addons/website_sale/static/src/js/website_sale_delivery.js#L39-L42 should be before `.click()`. To show selected location on page reload and prevent loading close locations.
 2) 
https://github.com/odoo/odoo/blob/607e454f65c2c60c4ee5169bc53706f24a8bc625/addons/website_sale/static/src/js/website_sale_delivery.js#L140-L145
This call resets selected pickup location on order when `this.forceClick` is True. Happens when we click selected carrier on `start()`. It should not be the case.

I believe that there is smth more. So I think that we need to fix the flow once and for all to not have new bugs.

What do you think?

2024-07-18 12:54 UTC, LouisGobert commented
Well seen.

I believe that in any case, when coming from the address editing page, we should delete the pickup point, correct?

Regarding the page reload scenario ('/payment'), should we also delete the pickup point or can we leave it selected?

One solution could be to modify the initial call to ._getCurrentLocation(); from the start function to not make an RPC call and set data = {}, which would reset the pickup point each time the page is loaded (if that's the goal).

2024-07-18 14:15 UTC, vchu-odoo commented
On the contrary, it is better to save selected pickup location. It does not make sense to reset it on reload. We do not need to know if we come from editing page or just reloading `/payment` the frontend and backend should be consistent. That is why  I suggested some fixes in `website_sale_delivery.js`.

2024-08-06 18:12 UTC, closed without merging