[FIX] base_import_module: fix author is unknown when installing industry module
odoo/odoo pull request #173583
Opened 2024-07-18 05:59 UTC by dhrs-odoo

**Before this commit** when we try to install any industry then author is shown in industries but when we check it in all apps then there it is shown unknown.

**After this commit** author is correctly shown in industries and all apps also.

Task-3959713

2024-07-18 06:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173583.png)](https://mergebot.odoo.com/odoo/odoo/pull/173583)

2024-07-18 15:16 UTC, vava-odoo requested changes
Hi @dhrs-odoo 
Thanks for this. However, the current fix is not what we want. Could you have a look at the comments below?
Thanks!

2024-07-18 15:16 UTC, vava-odoo commented on addons/base_import_module/models/ir_module.py
>          if not terp:
Your code should be below this check

2024-07-18 15:16 UTC, vava-odoo commented on addons/base_import_module/models/ir_module.py
> +            terp['author'] = "Odoo S.A."
We don't want to apply this to all imported modules where the author is missing, only to industry modules

2024-07-19 09:58 UTC, vava-odoo requested changes

2024-07-19 09:58 UTC, vava-odoo commented on addons/base_import_module/models/base_import_module.py
> +        res = IrModule.with_context(module_type="industries")._import_zipfile(fp, force=self.force, with_demo=self.with_demo)
Good idea about the context, but this is still general to all imported modules

2024-07-19 10:29 UTC, dhrs-odoo commented
Hello @vava-odoo 
Changes has been implemented
Thank You :innocent:

2024-07-19 11:33 UTC, vava-odoo approved these changes
Thanks @dhrs-odoo 
I'm not a big fan of the context key name, 'data_module' is misleading here, but it is already existing, so we probably adapt that in forward port to master.

2024-09-12 13:59 UTC, closed without merging