[FIX] l10n_in: duplicate GSTIN + improvement
odoo/odoo pull request #173655
Opened 2024-07-18 13:07 UTC by yosuanicolaus

Step to reproduce:

- install l10n_in
- create an invoice
- select an Indian customer with GSTIN
- change delivery address to other indian customer without GSTIN
- print report, call it "report 1"
- change delivery address to other indian customer with GSTIN
- print report, call it "report 2"

Current behavior:

For report 1:

- The GSTIN value of the partner_id appear twice on the report

For report 2:

- The GSTIN value of the partner_id appear twice
- The GSTIN value of the delivery partner does not appear

Expected behavior:

- The GSTIN value of partner_id should not appear twice
- If exist, the GSTIN value of delivery partner should be shown

opw-4027540

2024-07-24 09:25 UTC, aboo-odoo reviewed
LGTM! 

Claire will be on holiday next week, as this is not urgent, we'll wait for her return for the final look :+1:

2024-07-30 12:41 UTC, clbr-odoo requested changes
You need to re-export the .pot to get that "GSTIN: " translated :thinking: 
Even if it's arguable that it needs translations :p

2024-08-01 20:06 UTC, clbr-odoo approved these changes

2024-08-01 20:07 UTC, clbr-odoo commented
@robodoo r+

2024-08-01 21:32 UTC, closed without merging