[IMP] point_of_sale: whatsapp and email marketing UI/UX
odoo/odoo pull request #173604
Opened 2024-07-18 09:12 UTC by paan-odoo

Before this commit:
==========
- There is no confirmation notification while using WhatsApp and Email marketing.
- Also, there is no option for standalone marketing from the PoS order form view.

After this commit:
==========
- Confirmation notification appears after successfully triggering WhatsApp and Email marketing.
- Now, we have an option for standalone marketing from the PoS order form view.

task-4037963

2024-07-18 09:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173604.png)](https://mergebot.odoo.com/odoo/odoo/pull/173604)

2024-07-22 10:31 UTC, paso-odoo requested changes

2024-07-22 10:31 UTC, paso-odoo commented on addons/point_of_sale/models/mail_compose_message.py
> +        if self.model == 'pos.order':
```suggestion
        if self.filtered(lambda l: l.model == 'pos.order'):
```

2024-07-22 10:31 UTC, paso-odoo commented on addons/point_of_sale/models/mail_compose_message.py
> +                    'title': _("Email triggered successfully"),
```suggestion
                    'title': _("Email triggered successfully!"),
```

2024-07-22 10:31 UTC, paso-odoo commented on addons/point_of_sale/models/mail_compose_message.py
> +                    'sticky': False,
```suggestion
```

2024-07-30 12:03 UTC, adgu-odoo requested changes
Nice PR. One quick question, why allow whatsapp and not sms through mobile number?

2024-07-31 08:19 UTC, adgu-odoo approved these changes

2024-07-31 08:20 UTC, adgu-odoo commented
@robodoo r+

2024-07-31 10:41 UTC, closed without merging