[FIX] l10n_es_edi_facturae: add name field for individual seller
odoo/odoo pull request #173608
Opened 2024-07-18 09:35 UTC by mairasalazar

To replicate the issue:
- Go to the partner page of the current company (Invoicing > Customers
> Customers > Look for the company)
- Change type from Company to Individual
- Create and post an invoice
- Click on Send & Print. Download the Facturae
- NAME should appear in line 30, before <AddressInSpain>, but it doesn't

Cause of the issue:
The template values do not include a value for self_party_name, only for other_party_name. In the template, when partner_name is set, no value is passed for self_party.

Fix:
Instead of only extracting the partner name for partner (other_party), the code is used in a new function, which can be called for both partner and company (self_party). Then, self_party_name can be used as a value in the template.

opw-4053023

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-18 09:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173608.png)](https://mergebot.odoo.com/odoo/odoo/pull/173608)

2024-07-19 08:11 UTC, svfu-odoo requested changes
Looks good. I just have some suggestions about the variable naming.

2024-07-19 11:30 UTC, svfu-odoo approved these changes
Thanks for the changes.
LGTM :+1:

2024-07-23 13:21 UTC, epictete reviewed
LGTM :ok_hand: 
Just a very tiny detail :innocent:

2024-07-23 13:58 UTC, mairasalazar commented on addons/l10n_es_edi_facturae/models/account_move.py
> +        def _extract_name(partner):
Thanks for the review!

2024-07-23 14:00 UTC, epictete approved these changes
Thanks for the quick update and for the fix :+1: 

@robodoo r+

2024-07-23 17:21 UTC, closed without merging