[IMP] website: redesign s_table_of_content snippet
odoo/odoo pull request #173720
Opened 2024-07-18 18:40 UTC by chgo-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-18 18:41 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173720.png)](https://mergebot.odoo.com/odoo/odoo/pull/173720)

2024-07-18 19:30 UTC, chgo-odoo commented
| heading 4 | heading 5 |
|--------|--------|
| <img alt="image" src="https://github.com/user-attachments/assets/7dc797f8-606f-4b7d-a078-9a52cf9bb31b"> | <img  alt="image" src="https://github.com/user-attachments/assets/c28cfc56-4749-4eaa-972a-f74098900b22"> |

2024-07-18 20:00 UTC, stefanorigano requested changes
Thanks @chgo-odoo  👍 
I do agree with you `h5` are better indeed. 
Thanks!

2024-07-18 20:05 UTC, chgo-odoo commented on addons/website/views/snippets/s_table_of_content.xml
> +                            <div class="s_hr pt24 pb24">
Make sense, indeed ! It's weird to have an even spacing on both sides

2024-07-19 05:38 UTC, stefanorigano approved these changes
Thanks @chgo-odoo 👍

2024-07-19 08:48 UTC, chgo-odoo commented
@stefanorigano had to change some changes here : 

- Restore the second section to showcase the sticky feature
- Slightly increased the padding between the section

2024-07-19 09:09 UTC, stefanorigano commented
Re-approved :)
Thanks for the improvements and the heads-up 👍

2024-07-23 14:35 UTC, xO-Tx requested changes

2024-07-23 14:39 UTC, chgo-odoo commented
Hello @xO-Tx, thanks for having a look at this PR, changes have been applied !

Thanks !

2024-07-25 08:15 UTC, detrouxdev commented
@robodoo delegate=xO-Tx

2024-07-25 08:42 UTC, xO-Tx approved these changes
@robodoo r+

2024-07-25 11:00 UTC, closed without merging