[FIX] point_of_sale: change the way to update the fiscal position
odoo/odoo pull request #173770
Opened 2024-07-19 06:46 UTC by Axel927

Current behavior:
When a combo product is on the order and the user change the fiscal position, the prices of the lines of the combo change to get there original prices rather than the price of the combo

Steps to reproduce:
- Install "Point of Sale" app
- Enable "Flexible Taxes" in the shop settings and allow 2 fiscal positions
- Start a session, select one of the fp click on a combo product
- Change the fp, the prices of the orderlines are now the prices of the products themselves and not the prices of the combo

Cause:
After changing the fp, the quantity of al the orderlines are reset

Solution:
After changing the fp, call the function which update the pricelist which update all the prices correctly

opw-4027186

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-19 06:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173770.png)](https://mergebot.odoo.com/odoo/odoo/pull/173770)

2024-07-22 08:51 UTC, robinengels requested changes

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/tests/tours/PosComboTour.js
use `.flat()` at then end of the steps list instead of all the `...`

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/tests/tours/PosComboTour.js
> +        ...inLeftSide(Order.doesNotHaveLine({productName: "Office Combo", price: "0.0"})),
This is not really related to what you are testing. IMO we can remove it

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/tests/tours/PosComboTour.js
> +        ...inLeftSide(Order.doesNotHaveLine({productName: "Office Combo", price: "0.0"})),
Same

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/tests/tours/PosComboTour.js
> +        // another order but won't be sent to the backend
Forgotten comment ?

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/tests/tours/PosComboTour.js
> +    url: "/pos/ui",
This is not required actually. The full url is already specified when starting the tour from the python test

2024-07-22 08:51 UTC, robinengels commented on addons/point_of_sale/static/src/app/store/models.js
> +        this.set_pricelist(this.pricelist);
It's a bit hacky, but if it works it's good for me

2024-07-22 12:51 UTC, robinengels approved these changes

2024-07-26 08:41 UTC, davidmonnom commented
We should not change the price_type of combo_line to manual ? It should fix the main issue

See `getAddProductOptions` & `addComboLines`

2024-07-26 08:42 UTC, davidmonnom commented
[Screencast from 26-07-24 10:41:52.webm](https://github.com/user-attachments/assets/8566a5f8-0463-4ba5-a045-3de552eebfc9)

2024-07-26 08:42 UTC, davidmonnom requested changes
See previous comment :)

2024-07-29 08:04 UTC, davidmonnom approved these changes
@robodoo r+

2024-07-29 10:53 UTC, closed without merging