[FIX] loyalty: resolve validation error for loyalty description
odoo/odoo pull request #173789
Opened 2024-07-19 08:46 UTC by mash-odoo

**Steps:**
- Create a new Discount and loyalty program.
- Keep the program type as BOGO / any other program
- In the rewards pop-up, leave the 'description on the product' empty and click on 'save & close'.
- Try to save the loyalty program. Validation error appears.

**Cause:**
- This occurs because the description is used to set the name of the discount product, but if it's empty, the write method will not get the proper values hence resulting in error.

**Fix:**
- Making the description field required because it is used for all programs and exclusively used to compute value of discount product.

**Affected Version:** 16.0~master
**opw**-4032798

2024-07-19 08:46 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173789.png)](https://mergebot.odoo.com/odoo/odoo/pull/173789)

2024-07-19 12:29 UTC, Demesmaeker requested changes
Hello @mash-odoo :duck: 

The problem could still arise for people that changed the view with studio for instance, so it might be better to raise an userError where it's needed instead. 
And in master, it would be better to put the field as required and manage the upgrade script then. 

Also, regarding your commit message... What program is BOGO? :thinking: 

Have a nice day,

2024-07-23 10:00 UTC, Demesmaeker requested changes
Hello @mash-odoo :duck: 

Could you also update the POT file? =]

2024-07-23 10:00 UTC, Demesmaeker commented on addons/loyalty/models/loyalty_reward.py
> +        for record in self:
```suggestion
        for reward in self:
```

2024-07-23 10:00 UTC, Demesmaeker commented on addons/loyalty/models/loyalty_reward.py
> +    def _check_description_on_loyalty(self):
```suggestion
    def _ensure_reward_has_description(self):
```

2024-07-23 12:38 UTC, mash-odoo commented
Hey @Demesmaeker :heart: ,
Yeah sure, I have updated the POT file and done the requested changes.

2024-07-23 13:03 UTC, Demesmaeker requested changes
Hello @mash-odoo :duck: 

Last little change before merging: as per our guideline, onchange methods should be before CRUD methods. I know that this file is a ~bit~ lot scrambled, but let's at least try ^^ (Someday, we'll clean it in master)

2024-07-23 14:02 UTC, Demesmaeker approved these changes
@robodoo r+ :partying_face:

2024-07-23 14:03 UTC, robodoo commented
@Demesmaeker unknown command ':partying_face:'.

For your own safety I've ignored *everything in your entire comment*.

Currently available commands:

|command||
|-|-|
|`help`|displays this help|
|`r(eview)+`|approves the PR, if it's a forwardport also approves all non-detached parents|
|`r(eview)=<number>`|only approves the specified parents|
|`fw=no`|does not forward-port this PR|
|`fw=default`|forward-ports this PR normally|
|`fw=skipci`|does not wait for a forward-port's statuses to succeed before creating the next one|
|`up to <branch>`|only ports this PR forward to the specified branch (included)|
|`merge`|integrate the PR with a simple merge commit, using the PR description as message|
|`rebase-merge`|rebases the PR on top of the target branch the integrates with a merge commit, using the PR description as message|
|`rebase-ff`|rebases the PR on top of the target branch, then fast-forwards|
|`squash`|squashes the PR as a single commit on the target branch, using the PR description as message|
|`delegate+`|grants approval rights to the PR author|
|`delegate=<...>`|grants approval rights on this PR to the specified github users|
|`default`|stages the PR normally|
|`priority`|tries to stage this PR first, then adds `default` PRs if the staging has room|
|`alone`|stages this PR only with other PRs of the same priority|
|`cancel=staging`|automatically cancels the current staging when this PR becomes ready|
|`check`|fetches or refreshes PR metadata, resets mergebot state|

Note: this help text is dynamic and will change with the state of the PR.

2024-07-23 14:04 UTC, Demesmaeker commented
No fun allowed, I guess...

@robodoo r+

_with a very serious face_

2024-07-23 17:06 UTC, closed without merging