[FIX] web_editor: page crash on burger menu click in mobile view
odoo/odoo pull request #173785
Opened 2024-07-19 08:26 UTC by shsa-odoo

Version: 16.0 to master
Browser: Firefox only

Steps to Reproduce:
1. Open website in edit mode
2. Open inspect element, switch to mobile view
3. Click burger menu to open
4. Traceback occurs

Specification:
The issue was with ev.changedTouches and ev.targetTouches as it relates to browser-specific touch event handling, especially in touchstart, touchmove, and touchend events.

ev.changedTouches: Lists touches contributing to the event. For touchstart, it shows newly active touches. For touchmove, it shows moved touches. For touchend, it shows removed ones.

ev.targetTouches: Lists touches in contact with the event's target element.

Firefox might interpret touch events differently, affecting changedTouches and targetTouches behavior.

Using ev.targetTouches ensures relevant touches are tracked for compatibility across browsers, including Firefox.

task-3980983

2024-07-19 08:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173785.png)](https://mergebot.odoo.com/odoo/odoo/pull/173785)

2025-02-11 08:18 UTC, SergeBayet requested changes
LGTM but I have some remarks about the commit message:

- Commit message header should make a valid sentence once concatenated with if applied, this commit will `header`. For example **[IMP] base: prevent to archive users linked to active partners** is correct as it makes a valid sentence if applied, this commit will prevent users to archive.... (https://www.odoo.com/documentation/18.0/contributing/development/git_guidelines.html)
- Explain WHY you are modifying code, not HOW. We can see your diff, so it's often unnecessary to explain how you do it.
- Could you specify in the steps to reproduce that we talk about the inspector mobile view, and not the web_editor mobile view. I had to see the video attached in the task to understand.

Thanks.

2025-02-11 09:16 UTC, shsa-odoo commented
@SergeBayet Thanks for the insight let me add a more clearer commit message. I hope the following one makes more sense ?

[FIX] web_editor: prevent page crash on burger menu click in mobile view

Version: 16.0 to master
Browser: Firefox only

Steps to Reproduce:
1. Open website in edit mode (In Desktop)
2. Open inspect element, switch to mobile view (Inspector mobile view)
3. Click burger menu to open
4. Traceback occurs

Reason for Change:
In Firefox, when the inspector's mobile view is used, it simulates
touch events. Clicking the burger menu triggers the `_onTouchEvent`
handler, where `ev.changedTouches[0]` returns undefined, causing an
error. This fix ensures that the page does not crash by handling the
undefined `ev.changedTouches[0]`.

task-3980983

2025-02-11 09:20 UTC, SergeBayet commented
> Reason for Change: In Firefox, when the inspector's mobile view is used, it simulates touch events. _Clicking the burger menu triggers the `_onTouchEvent` handler, where `ev.changedTouches[0]` returns undefined, causing an error. This fix ensures that the page does not crash by handling the undefined `ev.changedTouches[0]`._

You can remove the sentences in italic, we see that in the diff :+1:

2025-02-11 09:48 UTC, SergeBayet commented
@shsa-odoo Don't forget to duplicate the commit message changes in the PR title and description. Thanks.

2025-02-11 09:52 UTC, shsa-odoo commented
@SergeBayet Its done !

2025-02-11 13:36 UTC, SergeBayet commented
runbot failed here. Strange, maybe a rebase could do the trick.

2025-02-11 13:38 UTC, JKE-be commented
@robodoo delegate SergeBayet

2025-02-11 13:38 UTC, robodoo commented
@JKE-be unknown delegation 'SergeBayet'.

For your own safety I've ignored *everything in your entire comment*.

Currently available commands:

|command||
|-|-|
|`help`|displays this help|
|`r(eview)+`|approves the PR, if it's a forwardport also approves all non-detached parents|
|`r(eview)=<number>`|only approves the specified parents|
|`fw=no`|does not forward-port this PR|
|`fw=default`|forward-ports this PR normally|
|`fw=skipci`|does not wait for a forward-port's statuses to succeed before creating the next one|
|`fw=skipmerge`|does not wait for the source to be merged before creating forward ports|
|`up to <branch>`|only ports this PR forward to the specified branch (included)|
|`merge`|integrate the PR with a simple merge commit, using the PR description as message|
|`rebase-merge`|rebases the PR on top of the target branch the integrates with a merge commit, using the PR description as message|
|`rebase-ff`|rebases the PR on top of the target branch, then fast-forwards|
|`squash`|squashes the PR as a single commit on the target branch, using the PR description as message|
|`delegate+`|grants approval rights to the PR author|
|`delegate=<...>`|grants approval rights on this PR to the specified github users|
|`default`|stages the PR normally|
|`priority`|tries to stage this PR first, then adds `default` PRs if the staging has room|
|`alone`|stages this PR only with other PRs of the same priority|
|`cancel=staging`|automatically cancels the current staging when this PR becomes ready|
|`override=<...>`|marks overridable statuses as successful|
|`check`|fetches or refreshes PR metadata, resets mergebot state|

Note: this help text is dynamic and will change with the state of the PR.

2025-02-11 13:44 UTC, sobo-odoo commented
@robodoo delegate=SergeBayet

2025-02-11 16:23 UTC, SergeBayet commented
@robodoo r+

2025-02-11 17:58 UTC, closed without merging