[FIX] website: s_quotes_carousel, remove duplicate background
odoo/odoo pull request #173820
Opened 2024-07-19 11:03 UTC by Brieuc-brd

Prior to this commit, the `s_quotes_carousel` had the Background feature two times in the Web editor.

This commit fixes this issue.

task-3654353

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-19 11:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/173820.png)](https://mergebot.odoo.com/odoo/odoo/pull/173820)

2024-08-16 12:30 UTC, stefanorigano requested changes
Hello @Brieuc-brd , thanks for digging deep 👍 

**Unfortunately**, the option is not duplicated 🥲. These are two, targeting `section.s_quotes_carousel_wrapper` and `div. s_quotes_carousel` respectively.

Se example  using rgba colors ⬇︎
![image](https://github.com/user-attachments/assets/368106e4-682a-4dba-b646-0ed44eedf935)


The overall UX is very confusing  indeed and I do agree that it should be addressed, but on`master`.
If we apply the patch  on `15.0` people may get stuck with settings they cannot remove simply because the option is not there anymore.

This option is so old that people may have dealt with it by now, enforcing this change change could complicate things further IMO.

As said, good for master tho 👍 🙂

2024-08-23 14:55 UTC, stefanorigano approved these changes
LGTM, thanks 👍

2024-08-23 14:58 UTC, Brieuc-brd commented
Hello @odoo/rd-website, this small improvement is ready for tech. review, could you take a look at it ? :)
Thanks in advance ! 🙏

2024-08-27 08:58 UTC, qsm-odoo approved these changes
> If we apply the patch on 15.0 people may get stuck with settings they cannot remove simply because the option is not there anymore.

Good catch, did not notice that the two options do not target the same wrapper at first. Actually, targeting the inner carousel seems dubious (I introduced that apparently). It just makes the "height" option not work (although, the slide do not follow the height either so...). I'll add a note in this task to possibly change/fix that: https://www.odoo.com/odoo/all-tasks/3770405 in the future.

Although, we could still have targeted 15.0: existing users won't receive this fix as it requires an XML update. But I guess they technically could with an app update by themselves... ok let's not overthink on that one, I doubt that this snippet is a very used one anyway and it's not a critical bug anyway :+1: 

@robodoo r+

2024-08-27 11:46 UTC, closed without merging