[FIX] mail: Banner should not hide the chatter actions
odoo/odoo pull request #174173
Opened 2024-07-23 10:07 UTC by jayp-odoo

**Current behavior before PR:**

When scrolling down on the chatter, the 'Jump to present' banner hides the chatter actions.

**Desired behavior after PR is merged:**

the issues was resolved by fixing the potions of banner, now scrolling down on the chatter,the 'Jump to present' banner it displayed below chatter actions

task-3930968

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-23 10:08 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174173.png)](https://mergebot.odoo.com/odoo/odoo/pull/174173)

2024-08-16 05:56 UTC, rapr-odoo requested changes
PR is in conflict. Could you please do a rebase?

2024-08-27 06:33 UTC, rapr-odoo requested changes
Small changes!

2024-09-06 08:46 UTC, jayp-odoo commented
closing this PR as another PR with different UI is being created.

2024-09-06 08:46 UTC, closed without merging