[IMP] website: `s_progress_bar` revamp design
odoo/odoo pull request #174286
Opened 2024-07-23 19:46 UTC by stefanorigano

https://getbootstrap.com/docs/5.3/migration/#progress-bars

overflow-visible

data-no-preview="true"

task-4070098
part of task-3619705

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-23 19:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174286.png)](https://mergebot.odoo.com/odoo/odoo/pull/174286)

2024-07-24 09:24 UTC, stefanorigano commented
**_Note for the reviewer_**
design-themes is currently red 'cause of a "versioning issue"... but the snippet it's neither called or customized by themes. Unfortunately I was not able to address the issue.

I do suspect that the issue is caused by legacy code or by exceptions at the the python test itself.

```
FAIL: TestNewPageTemplates.test_render_applied_templates
Traceback (most recent call last):
  File "/data/build/design-themes/test_themes/tests/test_new_page_templates.py", line 209, in test_render_applied_templates
    self.assertFalse(errors, "No error should have been collected")
AssertionError: ["Using 'no theme', view 'website.snippets' contains conflicting classes: {'s_progress_bar_label_inline', 's_progress_bar'} [...]
```

2024-07-25 14:51 UTC, bso-odoo requested changes
Something is wrong, I reach the following display using the branch - and also after a rebase:
![image](https://github.com/user-attachments/assets/7f3745c6-37ad-4f0c-9b4e-51f855f5b939)
Scenario:
- drop text block
- drop progress bar x3 + set different label position in each

2024-07-25 14:51 UTC, bso-odoo commented on addons/website/static/src/snippets/s_progress_bar/options.js
> +        const progressValue = progress.getAttribute('aria-valuenow');
Let's use double-quotes around all strings.

2024-07-25 15:23 UTC, stefanorigano commented
@bso-odoo , `vcss="000"` -> `data-vcss="000"` .. sorry for the hassle 🤦🏻‍♂️
Hopefully it will solve also the [versioning issues](https://github.com/odoo/odoo/pull/174286#issuecomment-2247347565) I had. 

- used double quotes for JS strings
- BS animation fix moved in `bootstrap_review.scss`(it's needed by both backend and frontend) + and in a separated commit 
-branch rebased

Thanks

2024-07-26 12:54 UTC, bso-odoo commented
Strange the display works for some time, but after editing, adding progress bars and saving a few times, the progress bars end up with `.progress` having no width defined - leading 21px.
I suspect this might be due to the version of the old CSS (in default theme) already being 000... maybe this clashes with the new 000 and cause problem. Let's try naming the new one 001 instead.

2024-07-29 11:16 UTC, Brieuc-brd commented
Hello @bso-odoo 👋 
I've updated the branches 🟢 🙂 
Could you take a look ?

The diffs :
- https://github.com/odoo/odoo/compare/859dd8d304cba46fa85f2b797a9d343732f1cee7..5d854452b78aed3cd287285fbfc7bb7fe8680d1e
- https://github.com/odoo/odoo/compare/ac8605e2d12e442665bc86bf4f4bd8d41b8f4cfe..abc601f5a41f13c361684a67d15dc07f375fa14f
- https://github.com/odoo/design-themes/compare/f88697ce25c8015c183bc258e2f94180646461c7..3e04bbd61e0cccaf31c54fd2411e37ea15104339

2024-07-29 11:30 UTC, bso-odoo commented
@robodoo rebase-ff r+

2024-07-29 11:30 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-07-29 14:35 UTC, closed without merging