[FIX] base: prevent putting filter and defaut out of reach
odoo/odoo pull request #174227
Opened 2024-07-23 14:19 UTC by flvr-odoo

This fix add a verification check to ir.filter and ir.default. This aims at preventing user to put such record out of their own reach

This behaviour is usually valid in Odoo, however in this case, it is not normal that the user cannot delete the filter and default that he created himself.

2024-07-23 14:20 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174227.png)](https://mergebot.odoo.com/odoo/odoo/pull/174227)

2024-07-23 15:33 UTC, kmagusiak requested changes
Build fails because of `write(self, ...)`

2024-07-24 16:12 UTC, kmagusiak commented
@ryv-odoo shouldn't this be generalized to all models and not only these 2?
If a value is written that affects the rule filter, we should recheck that the user still has access.

2024-07-26 10:34 UTC, kmagusiak approved these changes

2024-08-06 20:13 UTC, kmagusiak approved these changes

2024-08-14 08:34 UTC, ryv-odoo commented
LGTM @flvr-odoo 
@robodoo r+

2024-08-14 09:42 UTC, closed without merging