[FIX] purchase_stock: properly set final location in manual PO
odoo/odoo pull request #174372
Opened 2024-07-24 12:42 UTC by naja628

Problem
---
Using the default 2 steps receipt routes (input -> stock), when we manually create and confirm a purchase order for a storable product, the incoming products are not being taken into account for the stock forecast

Steps
---
* install purchase, mrp, sales_management
* In the setting enable multi-step routes, and configure the main warehouse to use the 2 step route.
* create a product P: 
   * storable 
   * has a supplier line 
   * route = buy
* create a corresponding 0,0 auto buy reordering rule.
* create a purchase order for 10 P, confirm it. 
  * => the forecast for the reordering rule is still 0
* create a SO for 10 P and confirm it
  * => a new draft purchase order is wrongly generated

Cause
---
Previously, when using multi step routes, creating a purchase order would create a move for every step of the route, and the destination of the last move of the chain was the main stock.
But as of 11e69870db1c49d9a6af79ffd263e4e162b34b6b, we create moves one step at a time, and use `location_final_id` to keep track of the eventual destination.
However, in purchase when creating the moves for a manual PO, we do not set this location. So the forecast doesn't take the move into account, as its destination is not the stock but the input.

opw-4033857

2024-07-24 12:43 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174372.png)](https://mergebot.odoo.com/odoo/odoo/pull/174372)

2024-08-07 14:22 UTC, DjamelTouati requested changes
Hello @naja628 , Thank you for the fix. LGTM!
Just a small change please:

```diff
-  location_final = self.location_final_id or self.order_id.picking_type_id.warehouse_id.lot_stock_id
+  location_final = self.location_final_id or self.order_id.picking_type_id.default_location_dest_id

2024-09-11 12:32 UTC, Whenrow commented
robodoo r+

2024-09-11 15:03 UTC, closed without merging

2024-09-16 07:30 UTC, adwid commented
robodoo delegate=@DjamelTouati