[FIX] website: configurator attachments shouldn't be updated
odoo/odoo pull request #174423
Opened 2024-07-24 14:59 UTC by diagnoza

Method `configurator_apply()` may create new attachments that will have the same `key` and `website_id` as standard, default images: https://github.com/odoo/odoo/blob/f80094f43bcc464cc99fba6aa59f64659fe659b6/addons/website/models/website.py#L737-L752

Standard images should be updated from the source of the `website` module, but those created by the configurator will have their binary content stored in the filestore and therefore have no need to be updated.

As of right now however, we don't make this distinction when updating `website` data, the following line:
https://github.com/odoo/odoo/blob/f80094f43bcc464cc99fba6aa59f64659fe659b6/addons/website/models/ir_module_module.py#L162

will return both the standard attachment and the one originating from the configurator (due to the same `key` and `website_id`). 
The fix is to tighten the `search` by filtering out records that have `store_fname` set.

This issue was discovered in many databases when upgrading to `saas~17.2` and a few also had this problem when upgrading to  `17.0`. Here is an example traceback from one of the request:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.2/odoo/service/server.py", line 1295, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/registry.py", line 120, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 296, in load_module_graph
    module.write({'state': 'installed', 'latest_version': ver})
  File "/home/odoo/src/odoo/saas-17.2/addons/website/models/ir_module_module.py", line 95, in write
    module._theme_load(website)
  File "/home/odoo/src/odoo/saas-17.2/addons/website/models/ir_module_module.py", line 239, in _theme_load
    module._update_records(model_name, website)
  File "/home/odoo/src/odoo/saas-17.2/addons/website/models/ir_module_module.py", line 165, in _update_records
    imd = self.env['ir.model.data'].search([('model', '=', find._name), ('res_id', '=', find.id)])
  File "/home/odoo/src/odoo/saas-17.2/odoo/fields.py", line 5183, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: ir.attachment(797, 725)
```

2024-07-24 14:59 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174423.png)](https://mergebot.odoo.com/odoo/odoo/pull/174423)

2024-07-24 15:02 UTC, diagnoza commented
Hey @qsm-odoo, could you check it out? I believe It is somewhat related to your PR from the past: https://github.com/odoo/odoo/pull/155015

I'm not sure how the configurator works exactly, so an expert's opinion would be greatly appreciated :)

2024-07-24 15:09 UTC, diagnoza commented
I should add for the record that the proposed solution affects not just attachments originating from the configurator, but all that have `store_fname` set, but I would further argue that no attachment with `store_fname` should have the need to be updated from the source.

2024-08-21 15:58 UTC, qsm-odoo requested changes

2024-08-21 15:58 UTC, qsm-odoo commented on addons/website/models/ir_module_module.py
> +                    find = rec.copy_ids.search([('key', '=', rec.key), ('website_id', '=', website.id), ("original_id", "=", False), ("store_fname", "=", False)])
Hello, sorry for the delay, I was on vacation. The explanation seems good but I am confused by some things:

- Why is it targeting 17.2? i.e. there should be a reference to a commit that changed something in 17.2 that created the issue in the commit message
- Should there be a reference to a ticket or whatever in the commit message ?
- I am not sure to understand that whole `if`. `# if module B override attachment from dependence A, we update it` what case is that ? Why is the line above that filters inside `copy_ids` o2m not enough? Maybe that actually is the root of the issue? That `rec.copy_ids.search` does not search inside the `copy_ids` records?

2025-02-10 06:36 UTC, robodoo commented
@diagnoza the target branch 'saas-17.2' has been disabled, you may want to close this PR.

2026-05-03 00:42 UTC, closed without merging