[FIX] sale: apply discount correctly on unit price with tax included
odoo/odoo pull request #174678
Opened 2024-07-26 13:17 UTC by rupa-odoo

Issue : 17.0

When a global discount is applied on a sale order with tax included in the price, the discount was incorrectly calculated based on the tax-excluded price. This resulted in inaccurate discount amounts and incorrect tax calculations.

steps to reproduce:
- Create a tax with included in price (e.g. 10% incl).
- Create a sale order with the 10% incl tax.
- Now, apply a global discount (e.g. 10%)

Cause :
When applying a global discount, the system incorrectly calculates the discount based on the tax-excluded price rather than the unit price.

Fix :
Ensure the total amount is calculated useing price_unit(price_unit) instead of subtotal.
This corrects the discount application and maintains accurate pricing.

opw-4018841

2024-07-26 13:18 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/174678.png)](https://mergebot.odoo.com/odoo/odoo/pull/174678)

2024-08-13 12:19 UTC, Feyensv requested changes
This fully breaks the existing global discount feature :red_circle:
You're magically deciding to consider only one line of the SO, which makes any global discount wrong when there are multiple lines.
Please reread and test your changes before asking for a review.
![image](https://github.com/user-attachments/assets/bffe0a0e-aed9-4487-a8b2-843830aeaa3c)

2024-09-06 08:55 UTC, dalaOdoo commented
LGTM

2024-09-06 09:14 UTC, Feyensv approved these changes
@robodoo r+

2024-09-06 15:18 UTC, closed without merging