[FIX] sale_management: translate default quotation template
odoo/odoo pull request #175258
Opened 2024-07-31 22:47 UTC by myhy-odoo

Problem: When the user sets a default quotation template in Sales > Settings and creates a quotation with a customer whose language preference is not English, the products' description is not translated accordingly for all sale order lines.

Solution: When the user changes the customer on the quotation, the quotation template should recreate the sale order lines according to the new customer's language.

Steps to Reproduce on Runbot:
1. Install Sales
2. Set a default quotation template in Sales > Settings
3. Create a new quotation
4. Set a customer whose language is not English on the quotation
5. Print the quotation
6. Observe that the products' description on each line is not translated, whilst the entire report is translated

opw-3957417

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-07-31 22:48 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175258.png)](https://mergebot.odoo.com/odoo/odoo/pull/175258)

2024-08-01 09:20 UTC, Feyensv requested changes
:red_circle: No, we don't want to reset the whole SO whenever the customer changes (and there is a template).

Not sure there is a good way to fix this issue TBH, but this one is not acceptable :thinking:

2024-08-01 16:20 UTC, Feyensv commented
Either we say it's a limitation, and the customer should unset and set the template again to make sure the description are correctly translated to the customer language.
Or we provide some kind of button to recompute descriptions on customer change, but I'm not sure it's really worth it.

2024-08-01 17:26 UTC, myhy-odoo commented
Got it! I will tell the client it's a limitation, show them the workaround, and submit an rd feedback for consideration for future versions. Thanks!

2024-08-01 17:26 UTC, closed without merging