[FIX] html_editor: youtube shorts not getting added
odoo/odoo pull request #175288
Opened 2024-08-01 06:54 UTC by ksbh-odoo

Steps to Reproduce: 

1. Go to Website --> Drag and drop an Image snippet(here Image - text).
2. Double click on the image --> Add a youtube shorts link in the video tab.
3. It will say the provided url is invalid.

Issue reason:
This issue is introduced by new implementation of `html_editor` intended to replace the `web_editor`. `player_regexes` for youtube didn't support youtube shorts.

Solution:
Updating the `player_regexes` for youtube to add youtube shorts as well as added part to support youtube live videos.

This commit ensures the youtube shorts are getting added and working.

task-4082384

2024-08-01 06:55 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175288.png)](https://mergebot.odoo.com/odoo/odoo/pull/175288)

2024-08-05 13:15 UTC, bvr-odoo requested changes
LGTM :+1: 
Could you just rewrite the commit message explaining why the following commit is no longer sufficient https://github.com/odoo/odoo/commit/d890f7b106039040fd99e97ac77916d971770324

2024-08-06 06:16 UTC, ksbh-odoo commented
Hello @bvr-odoo ,
Requested changes are made. Please do check them.
Thanks!!

2024-08-06 06:58 UTC, bvr-odoo approved these changes

2024-08-06 07:02 UTC, bvr-odoo commented
@robodoo r+

2024-08-06 09:52 UTC, closed without merging