[IMP] website: introduce a new snippet `s_connections`
odoo/odoo pull request #175321
Opened 2024-08-01 11:22 UTC by chgo-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-01 11:23 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175321.png)](https://mergebot.odoo.com/odoo/odoo/pull/175321)

2024-09-11 08:42 UTC, anso-odoo requested changes
Nice job @chgo-odoo, here are some comments

2024-09-11 08:42 UTC, anso-odoo commented on addons/website/views/snippets/s_split_intro.xml
> +                <div class="o_not_editable o_colored_level o_cc o_cc4 pt80 pb80 oe_img_bg o_bg_img_center col-lg-6 order-lg-0" style="background-image: url('/web/image/website.s_split_intro_default_i
```suggestion
                <div class="oe_img_bg o_bg_img_center pt120 pb120 col-lg-6 offset-lg-1 order-lg-0" style="background-image: url('/web/image/website.s_split_intro_default_image'); order: 0;"/>
```

- IMO this image should be editable
- `o_cc o_cc4` don't really look necessary + there is an visual glitch in the modal if we keep them:

| With o_cc | Without o_cc |
|--------|--------|
| ![Screenshot 2024-09-11 at 10 35 24](https://github.com/user-attachments/assets/c8df7fc3-3206-439a-ac64-ac4fb57c1c74) | ![Screenshot 2024-09-11 at 10 35 32](https://github.com/user-attachments/assets/d8d87dd0-1c1f-4f67-9e83-d29f6a52dfe3) |

2024-09-11 11:11 UTC, chgo-odoo commented on addons/website/views/snippets/s_split_intro.xml
> +            <div class="row s_nb_column_fixed">
it's breaking the layout very quickly but I guess we need to activate it as you say and it's on the user to experiment what works or not.

2024-09-11 15:10 UTC, chgo-odoo commented
ty @anso-odoo can you check?

2024-09-11 15:30 UTC, anso-odoo requested changes
Some nitpicking for you. After that it looks like it will be fine 👍

2024-09-19 15:12 UTC, anso-odoo approved these changes
LGTM

2024-11-08 08:55 UTC, lebl-odoo commented
Hi @chgo-odoo , just wondering why we don't left a blank link for "Discover more" (all intro snippets use this value as default link) instead of using /contactus

Nice snippet 🎉

2025-02-13 13:58 UTC, chrisdt1998 commented
Hello, just confirming this PR is ready to be reviewed? :)

2025-02-13 14:13 UTC, chgo-odoo commented
I confirm @chrisdt1998, thank you 👍

2025-02-13 14:57 UTC, chrisdt1998 requested changes
Initial review :)

2025-02-13 14:57 UTC, chrisdt1998 commented on addons/website/views/snippets/s_split_intro.xml
> +<template id="s_split_intro" name="Splitted Intro">
Splitted isn't actually a word. You should use 'Split' instead.

2025-02-13 14:57 UTC, chrisdt1998 commented on addons/website/views/snippets/snippets.xml
> +                <t t-snippet="website.s_split_intro" string="Splitted Intro" group="intro">
Same thing about 'Splitted'

2025-02-13 14:57 UTC, chrisdt1998 commented on addons/website/views/snippets/s_split_intro.xml
> +                <div class="col-lg-4 offset-lg-1 pt120 pb120 order-lg-0" style="order: 1;">
I don't think this is working as intended. My assumption is that you probably want to revert the order in mobile view? In that case, you should use the class name 'order-1'. 

One of the issues I see at the moment is that I cannot switch the order of the columns using the arrow button. (see picture).
![image](https://github.com/user-attachments/assets/4753e6bf-f955-4a21-bec7-12b978379198)

2025-02-13 14:57 UTC, chrisdt1998 commented on addons/website/views/snippets/s_split_intro.xml
> +                    <a t-att-href="cta_btn_href" class="btn btn-lg btn-primary"><t t-out="cta_btn_text">Discover more</t></a>
I'm pretty sure this anchor element should be in a paragraph element because otherwise you cannot align the anchor element without aligning everything else in the div as the same time.

2025-02-14 08:27 UTC, chgo-odoo commented on addons/website/views/snippets/s_split_intro.xml
> +                <div class="col-lg-4 offset-lg-1 pt120 pb120 order-lg-0" style="order: 1;">
I think this changed with the introduction of Colibri. I'll have a look to understand how the system works now. I see that we still have some old `style=""` in the codebase which work well

2025-02-14 10:15 UTC, chgo-odoo commented on addons/website/views/snippets/s_split_intro.xml
> +                <div class="col-lg-4 offset-lg-1 pt120 pb120 order-lg-0" style="order: 1;">
Looks like it comes from the fact I set `.order-lg-1` on the other el. Both should be `.order-lg-0`

2025-02-14 12:55 UTC, chgo-odoo commented
Hello @chrisdt1998 👋 

I pushed the changes on top, it should be good now !

If it looks okay, let's wait for https://github.com/odoo/odoo/pull/184760 to land so we don't have to r+ this twice 😄

2025-02-14 14:16 UTC, chrisdt1998 approved these changes
LGTM :) Will r+ as soon as the other PR is through

2025-02-14 14:38 UTC, qsm-odoo commented
@robodoo delegate=chrisdt1998
@chrisdt1998

2025-02-17 10:47 UTC, chrisdt1998 commented
r+

2025-02-17 10:47 UTC, chrisdt1998 commented
@robodoo r+

2025-02-17 13:22 UTC, closed without merging