[FIX] mail: wrongly assigned attachment as main attachment
odoo/odoo pull request #175459
Opened 2024-08-02 05:21 UTC by maad-odoo

Before this commit:
Sometimes attachments with extension 'p7m' were incorrectly assigned
as the main attachment. This caused the attachment viewer to treat these
attachments as previews that could be displayed.

After this commit:
Attachments with mimetype 'p7m' will no longer be considered as the
main attachment, preventing them from appearing in the attachment viewer.

task-3669465

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-02 05:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175459.png)](https://mergebot.odoo.com/odoo/odoo/pull/175459)

2024-08-02 07:29 UTC, rapr-odoo requested changes

2024-08-02 07:29 UTC, rapr-odoo commented on addons/l10n_it/models/account_move.py
> +    def _message_set_main_attachment_id(self, attachments, force=True, filter_xml=True):
The params should match the original definition.

2024-08-02 09:24 UTC, rapr-odoo approved these changes

2024-08-26 15:23 UTC, alialfie reviewed
Hi! Thanks for the fix, LGTM except the module name is incorrect in the commit message. Can you fix that please?

2024-08-27 01:16 UTC, maad-odoo commented
@alialfie Updated the module name. Please have a look.

2024-08-27 07:22 UTC, alialfie approved these changes
Thanks!
@FlorianGilbert LGTM

2024-08-27 07:35 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-08-27 09:49 UTC, closed without merging