[FIX] mail: scrollable message content inside message bubble
odoo/odoo pull request #175472
Opened 2024-08-02 08:21 UTC by ramh-odoo

**Current behavior before PR:**

When an email template is posted inside the chatter, the content overflows
in the x-direction, causing a UI issue where the message bubble does not
handle the overflow properly.
![image](https://github.com/user-attachments/assets/c838caa5-5424-41ac-9aff-2c78a8e96f12)

**Desired behavior after PR is merged:**

The issue has been fixed, making the message content scrollable inside the
message bubble, preventing overflow and maintaining proper UI appearance.

**Task**-4083373

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-02 08:22 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175472.png)](https://mergebot.odoo.com/odoo/odoo/pull/175472)

2024-08-26 06:33 UTC, rapr-odoo requested changes
Your fix resolves the issue of Body breaking out of the Bubble. But, because of this whole message including the Message Actions would get the scrollbar. Which is not desirable.

Instead I suggest to add the `overflow-x-auto` class to this LOC https://github.com/odoo/odoo/pull/175472/files#diff-0fc14194d473213159537bf41f421dcbaf940dfd81ac87d263b196e914d40af3L92-R92 

As this is the block which is overflowing and breaking out of the bubble it should be properly handled.

2024-08-28 05:31 UTC, ramh-odoo commented
@rapr-odoo Applying the changes requested by you fixes the bug but causes the entire chatter to scroll horizontally rather than just the template. In my opinion, this is not ideal. ([in chatter](https://www.awesomescreenshot.com/video/30924233?key=3f258336136a47016c65a732122c7b07))  ([in message](https://www.awesomescreenshot.com/video/30924487?key=c3721e783e4dc1ad822311b186dc2915))

2024-09-02 06:23 UTC, rapr-odoo approved these changes

2024-09-02 12:27 UTC, alexkuhn approved these changes
@robodoo r+

2024-09-03 02:46 UTC, closed without merging