[FIX] mail: jump to present hide for unstar-all and mark-all read
odoo/odoo pull request #175523
Opened 2024-08-02 11:27 UTC by jayp-odoo

**Current behavior before PR:**

if we click on `Unstar all` or `Mark all read` button from discuss it shows jump to present banner which it shouldn't.

**Desired behavior after PR is merged:**

now on clicking as above mentioned it does not show jump to present banner anymore.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-02 11:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175523.png)](https://mergebot.odoo.com/odoo/odoo/pull/175523)

2024-08-28 09:19 UTC, rapr-odoo requested changes

2024-08-28 09:19 UTC, rapr-odoo commented on addons/mail/static/src/core/common/thread.xml
> +    <t t-if="!env.inChatter and !props.thread.isEmpty" t-call="mail.Thread.jumpPresent"/>
It should be handled in `JumpToPresent` template with other conditions which are responsible for the display of this banner.

2024-09-19 13:20 UTC, jayp-odoo commented
closing this PR as another PR is merged which solves the same issue.

2024-09-19 13:20 UTC, closed without merging