[ADD] website: add new `s_striped_top` snippet
odoo/odoo pull request #175525
Opened 2024-08-02 11:37 UTC by anso-odoo

This commit introduces the new `s_striped_top` intro snippet.

task-4077621

requires: 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-02 11:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175525.png)](https://mergebot.odoo.com/odoo/odoo/pull/175525)

2024-08-07 13:29 UTC, stefanorigano requested changes
Mostly ok @anso-odoo , just a little note in the code 😉
Thanks!

2024-08-07 14:17 UTC, anso-odoo commented on addons/website/views/snippets/s_striped_top.xml
> +            <div class="row flex-column-reverse flex-lg-row">
@stefanorigano indeed, fixed thanks. Does the rest look okay for you ? I changed the image as well

2024-08-08 16:43 UTC, stefanorigano approved these changes
Just perfect 👍 

Ready to move forward when design-themes is ready ;)

2024-09-03 08:21 UTC, SergeBayet approved these changes
@anso-odoo LGTM. Thanks you for explaining me the "order" stuff :)

2024-09-04 09:25 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2024-09-04 14:39 UTC, SergeBayet commented on addons/website/views/snippets/s_striped_top.xml
> +                    <a t-att-href="cta_btn_href" class="btn btn-primary"><t t-esc="cta_btn_text">Read more</t></a>
@anso-odoo I missed the t-esc here. :(

2024-09-04 14:44 UTC, anso-odoo commented on addons/website/views/snippets/s_striped_top.xml
> +                    <a t-att-href="cta_btn_href" class="btn btn-primary"><t t-esc="cta_btn_text">Read more</t></a>
Fixed ✅

2024-09-05 12:34 UTC, SergeBayet commented
@robodoo r+

2024-09-05 15:21 UTC, closed without merging