[FIX] website_sale: apply custom ribbon color
odoo/odoo pull request #175687
Opened 2024-08-05 12:25 UTC by taqu-odoo

Issue
-----
Changing the color of the product's ribbon to a custome one in eCommerce has no effect outside of the editor (after clicking "Save", the background color of the ribbon returns to the default one).

Change
-----
Since the bg-primary class is now set on the ribbon HTML at creation. https://github.com/odoo/odoo/blob/56fd8440707a0f3f2ba298f8bf016577ca08796b/addons/website_sale/static/src/js/website_sale.editor.js#L180 We add an !important property to the background color style as it should override the default color if it is set.

opw-4069818

2024-08-05 12:25 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175687.png)](https://mergebot.odoo.com/odoo/odoo/pull/175687)

2024-08-08 13:51 UTC, nle-odoo approved these changes
explanation and `!important` makes sense since the `bg-primary` class has `!important` 

but it seems odd to me that we:

- adding "bg-primary" if it will break the badge background edition
- or not removing the bg-primary when changing the background

So in my opinion a cleaner solution would be to not have bg-primary (but then we have no background, so we would need to set a background-color in style attribute) at:

https://github.com/odoo/odoo/blob/0527b4b2ffe7d42222334b06a22739cf4963c617/addons/website_sale/static/src/js/website_sale.editor.js#L180

or remove the bg-primary when setting a background (but there is the preview that makes it more complicated).

If those are not ok, the current fix of this PR seems ok too.

2024-08-20 11:56 UTC, vchu-odoo requested changes
Hello,

Thank you for the fix!
I agree with @nle-odoo that the cleaner way is to remove `bg-primary` at all from here.
https://github.com/odoo/odoo/blob/56fd8440707a0f3f2ba298f8bf016577ca08796b/addons/website_sale/static/src/js/website_sale.editor.js#L180
That will clean the code and I do not see any good reason except for the default color to add this class. We can add instead either text color or background color or leave them blank as it works fine anyway.

2024-08-20 11:56 UTC, vchu-odoo commented on addons/website_sale/static/src/js/website_sale.editor.js
> +        }
```suggestion
        $ribbons.css('background-color', ribbon.bg_color || '');
```

2024-08-20 13:17 UTC, vchu-odoo approved these changes
Thank you for the changes!
Looks much easier :)

LGTM :+1:

2024-08-20 14:54 UTC, chevalierv commented
@robodoo delegate=taqu-odoo,vchu-odoo

2024-08-20 15:04 UTC, taqu-odoo commented
robodoo r+

2024-08-20 15:33 UTC, nle-odoo approved these changes
seems good to me if it works

2024-08-20 18:38 UTC, closed without merging