[ADD] website: introduce `s_empowerment` snippet
odoo/odoo pull request #175626
Opened 2024-08-04 16:16 UTC by chgo-odoo

This commit introduces a new inner snippet named `s_cta_badge`. Inspired by the `s_badge`, the `s_cta_badge` aims to provide an other way to display a call to action on a website.

The `s_cta_badge` comes with a set of scss variables, as the `s_badge` one, in order to ease customizations.

task-3856844

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-04 16:17 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175626.png)](https://mergebot.odoo.com/odoo/odoo/pull/175626)

2024-08-22 11:21 UTC, xlu-odoo requested changes
Good work! 🚀 
A few remarks below

2024-08-22 11:21 UTC, xlu-odoo commented on addons/website/views/snippets/snippets.xml
> +    <div data-js="vAlignment" id="row_valign_snippet_option" data-selector=".s_text_image, .s_image_text, .s_three_columns, .s_showcase, .s_numbers, .s_faq_collapse, .s_references, .s_accordion_image
If you do remove the ability to pass in col-mode, then remove this change please : )

2024-08-27 13:27 UTC, xlu-odoo approved these changes
LGTM 🚀

2024-09-02 15:15 UTC, bso-odoo commented on addons/website/views/snippets/s_empowerment.xml
> +                    <h1 class="display-5">Empowering Your Success<br/>with Every Solution.</h1>
I think display only goes up to 4 on `h1`.

2024-09-20 14:12 UTC, bvr-odoo approved these changes

2024-09-20 14:31 UTC, bvr-odoo commented
Commit(s) moved into

- https://github.com/odoo/odoo/pull/180736

2024-09-20 14:31 UTC, closed without merging