[ADD] website: introduce `s_shape_image` snippet
odoo/odoo pull request #175702
Opened 2024-08-05 13:20 UTC by chgo-odoo

- [ ] Meaningful demo-text
- [ ] Adapts to color combinations -> Readable text
- [ ] Mobile friendly
- [ ] Has no `<h1>` tags (except for "Intro" snippets)
- [ ] Has one `<h1>` tag ("Intro" snippets only)
- [ ] Images are optimized
- [ ] Images can be replaced by the website wizard (with fairly apparent exceptions)
- [ ] No ineffective options. Eg "click -> nothing happens"
- [ ] Edition is limited when not necessary
- [ ] Behaves consistently with the rest of the snippets (images can be replaced, etc..)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-05 13:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175702.png)](https://mergebot.odoo.com/odoo/odoo/pull/175702)

2024-08-26 13:08 UTC, Brieuc-brd requested changes
Thanks @chgo-odoo 💪 
I've just left a small comment below, good job :)

Also, some extra notes :
- About your commit description : 
> This commit introduces a new inner snippet named `s_shape_image`.

Your snippet doesn't seems to be an inner snippet :)

- About the text, since we've decided to add more meaningful content, I think we could improve it in this snippet (as you did in DT 😉 ).

Could you check ?

2024-08-26 13:08 UTC, Brieuc-brd commented on addons/website/views/snippets/s_shape_image.xml
> +                    <h3>About our product line</h3>
```suggestion
                    <h2 class="h3-fs">About our product line</h2>
```

2024-08-26 13:20 UTC, Brieuc-brd commented
@chgo-odoo 
Since the purpose is the same as `s_text_image`, I think it would make sense to move this snippet next to `s_text_image` in the list for the modal, what do you think?

2024-08-28 16:46 UTC, Brieuc-brd approved these changes
LGTM, good job @chgo-odoo 👍 

I just moved the snippet closer than `s_image_text` in the modal list.

2024-09-19 13:09 UTC, sobo-odoo commented
@chgo-odoo I will adapt the PRs since the changes asked are small, don't change anything on it from now :wink:

2024-09-19 16:00 UTC, sobo-odoo commented
Note:
- Rebased + conflicts ([diff](https://github.com/odoo/odoo/compare/630f9290938f7f5989e52d84311fc992b55955a4..109f44f3096d8b2d31b016a061491951821dbce0)) 
- Fixed the jpeg issue (see [diff](https://github.com/odoo/odoo/compare/109f44f3096d8b2d31b016a061491951821dbce0..2e2e922598bdda6eaab9d1f54692dc3e405cd621)) :slightly_smiling_face:

2024-09-19 17:21 UTC, sobo-odoo approved these changes
It's okay with me :slightly_smiling_face:
Will move it to the "super PR" haha

2024-09-19 17:37 UTC, sobo-odoo commented
Commit moved to
- https://github.com/odoo/odoo/pull/180736

2024-09-19 17:37 UTC, closed without merging