[FIX] base: return action content for readable fields
odoo/odoo pull request #175843
Opened 2024-08-06 11:06 UTC by maan-odoo

With the recently added embedded actions with commit https://github.com/odoo/odoo/commit/f983703dfa3c5102fa818523ae419a70cc4b5230, added below line  where it returns non related fields to actions, which may generate an error.
 https://github.com/odoo/odoo/blob/ebf6da8d24c72a391113310e66285ded1f5fc9b5/odoo/addons/base/models/ir_actions.py#L232-L236

In the `account_online_synchronization` module, a below exception was generated when cron `Account: Journal online sync` run.

Stack Trace:
```
TypeError: Object of type datetime is not JSON serializable
  File "odoo/tools/safe_eval.py", line 391, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(323,)", line 1, in <module>
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_journal.py", line 118, in _cron_fetch_online_transactions
    journals.with_context(cron=True)._fetch_online_transactions()
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_journal.py", line 64, in _fetch_online_transactions
    journal.manual_sync()
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_journal.py", line 130, in manual_sync
    return self.account_online_link_id._fetch_transactions(accounts=account)
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_online.py", line 815, in _fetch_transactions
    self._notify_connection_update(
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_online.py", line 452, in _notify_connection_update
    self._set_connection_state_details(
  File "home/odoo/src/enterprise/saas-17.4/account_online_synchronization/models/account_online.py", line 423, in _set_connection_state_details
    self.connection_state_details = {
  File "odoo/fields.py", line 1377, in __set__
    write_value = self.convert_to_write(value, records)
  File "odoo/fields.py", line 1023, in convert_to_write
    cache_value = self.convert_to_cache(value, record, validate=False)
  File "odoo/fields.py", line 3346, in convert_to_cache
    return json.loads(json.dumps(value))
  File "__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
  File "json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
ValueError: <class 'TypeError'>: "Object of type datetime is not JSON serializable" while evaluating
'model._cron_fetch_online_transactions()'
  File "odoo/addons/base/models/ir_cron.py", line 562, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "home/odoo/src/custom/trial/saas_trial/models/sentry.py", line 33, in run
    res = super().run()
  File "odoo/addons/base/models/ir_actions.py", line 984, in run
    res = runner(run_self, eval_context=eval_context)
  File "odoo/addons/base/models/ir_actions.py", line 814, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "odoo/tools/safe_eval.py", line 405, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
```

This exception was generated because   [code](https://github.com/odoo/enterprise/blob/b491d3fa529115229fcce58500f742a992a7f2e5/account_online_synchronization/models/account_online.py#L423 ) tries to store a dictionary of action with a datetime object in the json field `connection_state_details`, but when data is converted to cache at [4]-https://github.com/odoo/odoo/blob/ebf6da8d24c72a391113310e66285ded1f5fc9b5/odoo/fields.py#L3346
, it throws an exception because `json.dumps` does not support datetime objects.

This commit will fix the above issue by returning a dictionary of data for related fields only.

sentry-5655598227

2024-08-06 11:06 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175843.png)](https://mergebot.odoo.com/odoo/odoo/pull/175843)

2024-08-06 13:06 UTC, maan-odoo commented
Hello @odoo/sentry_reviewers 
Please review this PR
Thanks!

2024-08-06 14:27 UTC, MiquelRForgeFlow commented on odoo/addons/base/models/ir_actions.py
> +        return result
```suggestion
        if self.sudo().type == "ir.actions.act_window":
            embedded_actions = self.env["ir.embedded.actions"].browse(result["embedded_action_ids"]).read()
            result.update({"embedded_action_ids": embedded_actions})
        return result
```
useless parenthesis and useless whitespace

2024-08-07 11:09 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂

2024-08-07 11:13 UTC, xmo-odoo requested changes

2024-08-07 11:21 UTC, xavierbol commented on odoo/addons/base/models/ir_actions.py
> +            embedded_actions = self.env["ir.embedded.actions"].browse(result["embedded_action_ids"]).read()
I guess we could indeed just read the `readable_fields`. 🙂 

and indeed we could also just check if the `embedded_action_ids` is in readable_fields. 😅

2024-08-08 07:12 UTC, maan-odoo commented on odoo/addons/base/models/ir_actions.py
> +            embedded_actions = self.env["ir.embedded.actions"].browse(result["embedded_action_ids"]).read()
I have updated the code; could you please look at it?
Thanks! :slightly_smiling_face:

2024-08-08 09:51 UTC, maan-odoo commented on odoo/addons/base/models/ir_actions.py
> +            embedded_actions = self.env["ir.embedded.actions"].browse(result["embedded_action_ids"]).read()
Hello @xmo-odoo 
I have updated code; please look at it?
Thanks!

2024-08-08 11:55 UTC, maan-odoo commented on odoo/addons/base/models/ir_actions.py
> +            embedded_actions = self.env["ir.embedded.actions"].browse(result["embedded_action_ids"]).read()
Sorry, I missed this point

I have updated the code and also updated the commit message according to this. 

Thanks!

2024-08-08 11:59 UTC, maan-odoo commented on odoo/addons/base/models/ir_actions.py
> +        if embedded_action_ids:
Should we use like this :thinking: 
```suggestion
        if embedded_action_ids := result["embedded_action_ids"]:
```

2024-08-08 12:23 UTC, maan-odoo commented on odoo/addons/base/models/ir_actions.py
> +        if embedded_action_ids:
Thanks!
I have updated code :+1:

2024-08-08 13:26 UTC, xmo-odoo approved these changes

2024-08-09 07:45 UTC, xavierbol reviewed
Thanks for your work. 🙂 

robodoo r+

2024-08-09 10:32 UTC, closed without merging