[16.0][IMP] hr_holidays: Add constraint to allocation to avoid incompatible dates
odoo/odoo pull request #175841
Opened 2024-08-06 11:04 UTC by victoralmau

Add constraint to allocation to avoid incompatible dates

@Tecnativa TT50433

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-06 11:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175841.png)](https://mergebot.odoo.com/odoo/odoo/pull/175841)

2024-08-06 11:40 UTC, Bertrand2 reviewed
Hello,
Thanks for your fix!
If possible, could you add a test to ensure that an error is raised when trying to set an invalid date?

2024-08-07 11:12 UTC, Bertrand2 commented
Thanks! One last thing that I forgot, since you're adding text content in stable, you'll need to update the translation `.pot` file as well. If you've never done it:
- run a server of your branch locally
- go in debug mode
- go to the app Settings -> menu Translations -> Export Translation
- export the `Time Off` module
![image](https://github.com/user-attachments/assets/bd4451b9-4936-4973-8c84-06e185032b82)
- replace the content of the `hr_holidays.pot` file by that content, except the changes at the beginning of the file

2024-08-07 11:29 UTC, Bertrand2 commented
Actually, we cannot add SQL constraints in stable to avoid DB crashes if some records don't respect the constraint.
This should be implemented as a python constraint instead with `@api.constrains`. A similar constraint was added in 16.1, so you can reuse that code :)

2024-08-08 08:17 UTC, victoralmau commented
I have replaced the change with the backport of https://github.com/odoo/odoo/commit/bfa7a47c860452a8b27a942cd50dc61eba72f5cb.

2024-08-08 15:22 UTC, Bertrand2 commented
Thanks!
We have a misunderstanding however: I was talking about using the logic of the commit you linked for the constraint, but the pot file update and the test are still needed, sorry :sweat_smile:

2024-08-09 07:09 UTC, victoralmau commented
Test added and pot file updated.

2024-08-09 08:11 UTC, Bertrand2 approved these changes
LGTM! Thanks :)

2024-08-09 08:11 UTC, Bertrand2 commented
robodoo r+

2024-08-09 08:12 UTC, robodoo commented
@Bertrand2 you may want to rebuild or fix this PR as it has failed CI.

2024-08-09 08:18 UTC, Bertrand2 requested changes

2024-08-09 08:18 UTC, Bertrand2 commented on addons/hr_holidays/tests/test_leave_requests.py
> +from odoo.exceptions import ValidationError, UserError
UserError is reimported line 15, you can remove line 15 to pass style checks :)
Detail, but we usually put imports in alphabetical order 
```suggestion
from odoo.exceptions import UserError, ValidationError
```

2024-08-09 10:36 UTC, pedrobaeza commented
@Bertrand2 is it ok now?

2024-08-14 14:35 UTC, Bertrand2 commented
robodoo r+

2024-08-14 14:36 UTC, Bertrand2 commented
Looks like it @pedrobaeza , sorry for the late reply!

2024-08-14 16:53 UTC, closed without merging