[ADD] website: add new `s_faq_list` snippet
odoo/odoo pull request #175916
Opened 2024-08-06 16:12 UTC by anso-odoo

This commit introduces the new `s_faq_list` text snippet.

task-4094399

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-06 16:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/175916.png)](https://mergebot.odoo.com/odoo/odoo/pull/175916)

2024-08-09 08:11 UTC, stefanorigano requested changes
Neat 🙂

Just the demo text it's a bit suboptimal 'cause it doesn't really fit the scenario.
It's not where I'd expect to see terms of service, for example, and the content of the last 3 columns is copied for the previous ones.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/b3513083-19ad-4254-834e-77041672910d">


Some proposals for  your in the comments, fee free to refine if you want to.
All good the rest 👍 

_Note_: I wanted to propose to move it into the "Text" category, but you did it it already , good.  Let's not forget to discuss these kind of changes tho, so we can update Figma and task accordingly 😉

2024-08-09 08:11 UTC, stefanorigano commented on addons/website/views/snippets/s_faq_list.xml
> +                    <p>Website may use cookies to personalize and facilitate maximum navigation of the User by this site.</p>
```suggestion
                    <h6><strong>Who are our partners?</strong></h6>
                    <p>We collaborate with trusted, high-quality partners to bring you reliable and top-notch products and services.</p>
```

2024-08-09 08:11 UTC, stefanorigano commented on addons/website/views/snippets/s_faq_list.xml
> +                    <p>These terms of service ("Terms", "Agreement") are an agreement between the website ("Website operator", "us", "we" or "our") and you ("User", "you" or "your").</p>
```suggestion
                    <h6><strong>What support do we offer?</strong></h6>
                    <p>We provide 24/7 support through various channels, including live chat, email, and phone, to assist with any queries.</p>
```

2024-08-09 08:11 UTC, stefanorigano commented on addons/website/views/snippets/s_faq_list.xml
> +                    <p>Although this Website may be linked to other websites, we are not, directly or indirectly, implying any approval</p>
```suggestion
                    <h6><strong>How is your data secured?</strong></h6>
                    <p>Your data is protected by advanced encryption and security protocols, keeping your personal information safe.</p>
```

2024-08-09 08:25 UTC, anso-odoo commented
@stefanorigano Thanks for the copy! Is it good for TR now?

2024-08-09 08:33 UTC, stefanorigano approved these changes
Neat, LGTM, thanks 👍

2024-09-04 09:10 UTC, SergeBayet approved these changes
@anso-odoo Nothing to say LGTM :) Thanks.
PR queued and will be r+ after https://github.com/odoo/odoo/pull/175852

2024-09-04 09:12 UTC, SergeBayet approved these changes

2024-09-10 07:00 UTC, sobo-odoo commented
@robodoo delegate=SergeBayet

2024-09-12 06:34 UTC, SergeBayet commented
@robodoo r+

2024-09-12 07:51 UTC, closed without merging