[IMP] website: add new `s_cta_mockups` snippet
odoo/odoo pull request #176063
Opened 2024-08-07 14:49 UTC by anso-odoo

This commit introduces the new `s_cta_mockups` text snippet.

task-4094394

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-07 14:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176063.png)](https://mergebot.odoo.com/odoo/odoo/pull/176063)

2024-08-09 11:02 UTC, stefanorigano requested changes
Hello, nice UI 🤓

Code look clean, the only problem I see it's the overall alignment and balance that  looks a bit "off" on `LG` size ( `> LG` it's ok 👌) 

| figma | this PR |
|--------|--------|
| <img width="1012" alt="image" src="https://github.com/user-attachments/assets/e51f291c-8516-4744-92ec-7f2785413d48"> | <img width="1033" alt="image" src="https://github.com/user-attachments/assets/9a76c357-db12-4e54-bdaf-10dd3ee34418"> | 
 
 I propose to:
 - reduce the title length
 - review `o_grid_item_image` size and padding in order to align the devices at the bottom. 

| lg | > lg  |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/9d0f777a-e6c8-4616-81f3-bbb60a59c50c) | ![image](https://github.com/user-attachments/assets/8c5a710c-2c60-4052-8588-faf87fd11f02)|
 
 crappy copy/paste from the browser ⬇︎
 ```html
 <div class="row o_grid_mode" data-row-count="9">
  <div class="o_grid_item o_grid_item_image g-height-9 g-col-lg-6 col-lg-6 o_colored_level" style="grid-area: 1 / 6 / 10 / 13; z-index: 1;">
      <img src="web_editor/image_shape/website.s_cta_mockups_default_image/web_editor/devices/macbook_front.svg" class="img img-fluid" data-shape="web_editor/devices/macbook_front" data-original-mimetype="image/jpeg" data-file-name="s_cta_mockups.jpg" loading="lazy" data-mimetype="image/svg+xml" data-original-id="1677" data-original-src="/website/static/src/img/snippets_demo/s_cta_mockups.jpg" data-mimetype-before-conversion="image/jpeg" style="">
  </div>
  <div class="o_grid_item o_colored_level g-col-lg-4 g-height-6 col-lg-4" style="grid-area: 3 / 1 / 9 / 5; z-index: 2;">
      <h3 class="o_default_snippet_text">50,000+ companies trust Odoo.</h3>
      <p class="lead o_default_snippet_text">Join us and make your company a better place.</p>
      <a class="btn btn-primary btn-lg o_default_snippet_text" href="/contactus">Contact us</a>
  </div>
  <div class="o_grid_item o_grid_item_image o_snippet_mobile_invisible g-height-8 d-none d-lg-block o_colored_level g-col-lg-2 col-lg-2" style="grid-area: 2 / 6 / 10 / 8; z-index: 3; --grid-item-padding-y: 14px;" data-invisible="1">
      <img src="web_editor/image_shape/website.s_cta_mockups_default_image_1/web_editor/devices/iphone_front_portrait.svg" class="img img-fluid me-auto float-start" data-shape="web_editor/devices/iphone_front_portrait" data-original-mimetype="image/jpeg" data-file-name="s_cta_mockups_1.jpg" loading="lazy" data-mimetype="image/svg+xml" data-original-id="1678" data-original-src="/website/static/src/img/snippets_demo/s_cta_mockups_1.jpg" data-mimetype-before-conversion="image/jpeg" style="">
  </div>
  </div>
```
 What do you think? 
 Thanks!

2024-08-16 13:19 UTC, anso-odoo commented
@stefanorigano fixed the alignment 👍 Can this move to TR ?

2024-08-21 18:15 UTC, stefanorigano approved these changes
LGTM, thanks @anso-odoo, ready for tech. 👍 
Don't forget to add a nice screenshot in the PR description. 

Also, little detail, commit description:
_This commit introduces the new 's_cta_mockups' text snippet._
 I think that it it should be
 _This commit introduces the new 's_cta_mockups' **content** snippet._

2024-09-04 08:19 UTC, SergeBayet requested changes
Nice job. :+1:  Some comments here below before approving this PR.

2024-09-04 08:19 UTC, SergeBayet commented on addons/website/views/snippets/s_cta_mockups.xml
> +                <div class="o_grid_item g-height-5 g-col-lg-4 col-lg-4" style="grid-area: 3 / 1 / 9 / 5; z-index: 2;">
@anso-odoo It should be g-height-6 since 9 - 3 = 6. Am I right?

2024-09-04 08:19 UTC, SergeBayet commented on addons/website/views/snippets/s_cta_mockups.xml
> +                    <a t-att-href="cta_btn_href" class="btn btn-primary btn-lg"><t t-esc="cta_btn_text">Contact us</t></a>
Could you use t-out instead of t-esc? We have a task that replace all the t-esc by t-out in qweb that will be merged soon... Thx!

2024-09-04 08:21 UTC, SergeBayet commented
@anso-odoo And a last nipticking, the PR description hasn't been updated with "content snippet" instead of "text snippet". :pray:

2024-09-04 09:01 UTC, SergeBayet approved these changes
LGTM :+1: Thanks
This PR is queued and will be r+ after https://github.com/odoo/odoo/pull/176923

2024-09-09 12:11 UTC, SergeBayet commented
@robodoo r+

2024-09-09 12:11 UTC, robodoo commented
I'm sorry, @SergeBayet. I'm afraid I can't do that.

2024-09-10 06:57 UTC, sobo-odoo commented
@robodoo delegate=SergeBayet

2024-09-10 07:05 UTC, SergeBayet commented
@robodoo r+

2024-09-10 09:57 UTC, closed without merging