[FIX] mail: flicker when expanding direct messages in sidebar
odoo/odoo pull request #176114
Opened 2024-08-08 04:41 UTC by akap-odoo

**Current behavior before PR:**

The title "Direct Messages" in the discuss sidebar used to flicker (move up and down) when expanding or folding the section.

**Desired behavior after PR is merged:**

The flickering issue is fixed, so now the title "Direct Messages" remains in place when the section is expanded or folded.

**task**:4100682

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-08 04:41 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176114.png)](https://mergebot.odoo.com/odoo/odoo/pull/176114)

2024-08-08 09:06 UTC, rapr-odoo requested changes
The Fix works for `Direct Message` but it won't work on other categories where this button isn't used, ex. `Livechat`.

2024-08-08 13:15 UTC, rapr-odoo approved these changes

2024-08-08 13:18 UTC, rapr-odoo commented
To be merged in saas-17.4 only, as it's already been fixed in master.

2024-08-09 10:43 UTC, alexkuhn approved these changes
@robodoo r+ fw=no

2024-08-09 10:44 UTC, robodoo commented
Disabled forward-porting.

2024-08-09 13:53 UTC, closed without merging