[FIX] point_of_sale: ensure optional products display from info popup
odoo/odoo pull request #176168
Opened 2024-08-08 11:40 UTC by pedrambiria

Prior to this commit, clicking on an optional product within the product info popup would fail to locate the optional product due to product template filtering applied to product variants. This commit resolves the issue by applying product template filtering exclusively for variants, ensuring optional products are correctly displayed from the product info popup.

opw-4097824

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-08 11:41 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176168.png)](https://mergebot.odoo.com/odoo/odoo/pull/176168)

2024-08-16 07:48 UTC, adgu-odoo requested changes

2024-08-19 14:50 UTC, pedrambiria commented on addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.js
> +    searchProduct(productName, options = {}) {
@adgu-odoo Thanks for your review. You are right. I modified the code.

2024-09-02 06:33 UTC, pedrambiria commented
@adgu-odoo Could you please review this?

2024-09-10 09:34 UTC, adgu-odoo approved these changes

2024-09-10 09:34 UTC, adgu-odoo commented
robodoo r+

2024-09-10 11:53 UTC, closed without merging