[FIX] l10n_de: fix singleton error on multiple attachments unlink
odoo/odoo pull request #176140
Opened 2024-08-08 09:31 UTC by xavieralt

To reproduce (on runbot w/ demo datas)

- Install l10n_de
- Switch to "DE Company"
- Create an invoice and add 2 or more PDF documents
- Switch to debug mode
- Go to menu: Settings / Technical / Database Structure / Attachments
- Search for the added documents, select them all and try to delete them

=> This raise the following error:

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5961, in ensure_one
    _id, = self._ids
    ^^^^
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ..
  File "/data/build/odoo/odoo/addons/base/models/ir_attachment.py", line 610, in unlink
    res = super(IrAttachment, self).unlink()
  File "/data/build/odoo/odoo/models.py", line 4326, in unlink
    func(self)
  File "/data/build/odoo/addons/l10n_de/models/ir_attachment.py", line 25, in _except_audit_trail
    if move and move.posted_before and move.country_code == 'DE':
                ^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/fields.py", line 1204, in __get__
    record.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5964, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move(347, 347)
```

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-08 09:32 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176140.png)](https://mergebot.odoo.com/odoo/odoo/pull/176140)

2024-08-08 12:07 UTC, alialfie requested changes
Thanks for the fix! Just a few comments:
- Could you please add the ticket id in the commit message or mention if there was no ticket?
- Maybe it's not needed to include the full traceback, as long as you explain why the error was happening. What do you think?
- Is 17.4 the earliest version where this issue occurres?

2024-08-08 12:21 UTC, xavieralt commented
> Thanks for the fix! Just a few comments:
> 
>     * Could you please add the ticket id in the commit message or mention if there was no ticket?

Production log, so no ticket

> 
>     * Maybe it's not needed to include the full traceback, as long as you explain why the error was happening. What do you think?

As requested, I've removed it from the commit message (kept of the PR for ref.)

> 
>     * Is 17.4 the earliest version where this issue occurres?

Issue appeared in the `saas~17.3` forward port https://github.com/odoo/odoo/pull/172266 but as this version is already EOL the older supported version with that issue is `saas~17.4`

2024-08-08 14:52 UTC, alialfie approved these changes
Thanks for the update!
LGTM @FlorianGilbert

2024-08-09 06:32 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-08-09 08:26 UTC, closed without merging