[IMP] pos : Internal note like tags
odoo/odoo pull request #176280
Opened 2024-08-09 09:37 UTC by SalukiMakingCode

create tag in the popup

task id : 3976669

2024-08-09 09:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176280.png)](https://mergebot.odoo.com/odoo/odoo/pull/176280)

2024-08-09 10:08 UTC, vlst-odoo requested changes

2024-08-09 10:08 UTC, vlst-odoo commented on addons/point_of_sale/static/src/app/utils/input_popups/text_input_with_tag_popup.js
> +export class TextInputWithTagPopup extends Component {
you can just add the new things to the existing text input component. No need to create a new one

2024-08-09 10:08 UTC, vlst-odoo commented on addons/point_of_sale/static/src/app/utils/input_popups/text_input_with_tag_popup.xml
> +                 </t>
can you use the `TagsList` component from web instead ? 
https://github.com/odoo/odoo/blob/181ec327d769dc374363686dd00ae006ebddff11/addons/web/static/src/core/tags_list/tags_list.js#L3

2024-09-11 08:51 UTC, mobt-odoo commented
Deleting this one for priorities concern. 

Maybe we will do it in the future

2024-09-11 08:51 UTC, closed without merging