[FIX] l10n_it_edi: hide l10n_it_edi_is_self_invoice from non-accountants
odoo/odoo pull request #176222
Opened 2024-08-08 15:40 UTC by madprog

On the invoice form, the Italian localization adds a button that allows sending the tax EDI to the Italian administration.

This depends on the field l10n_it_edi_is_self_invoice that is a computed field that will need access to the model account.report.line.

An other fix could have been to add a sudo() in the compute method, but in fact displaying this button only makes sense for an accountant. Therefore, this commit add the necessary groups properties in the form view, so that only an accountant manager can see the button, as only them can see account.report.lines.

Task-Id: None

2024-08-08 15:41 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176222.png)](https://mergebot.odoo.com/odoo/odoo/pull/176222)

2024-09-03 15:49 UTC, lordkrandel requested changes
Sorry, accountants with `group_account_invoice` should definately be able to send Tax integration documents to the Italian EDI.

The access to the tax tags is just to detect whether the move involves certain taxes (the reverse-charged ones) so it should be sent to the EDI or not.

A `sudo()` in the `is_self_invoice` is totally proper. 👍🏻

2024-09-18 09:50 UTC, madprog commented
@lordkrandel Thanks for your review. Here is an updated version of the fix, with a `sudo()` instead of patched views, and a test that reproduces the issue.

2024-09-18 13:32 UTC, lordkrandel requested changes
Minors, easily fixed. 👍🏻

2024-09-18 13:32 UTC, lordkrandel commented on addons/l10n_it_edi/models/account_move.py
> +            it_tax_report_vj_lines_sudo = self.env['account.report.line'].sudo().search([
```suggestion
            it_tax_report_vj_lines = self.env['account.report.line'].sudo().search([
```

2024-09-18 15:55 UTC, lordkrandel commented on addons/l10n_it_edi/tests/__init__.py
> +from . import test_access_rights
Okay 👍🏻

2024-09-18 16:13 UTC, lordkrandel approved these changes
LGTM 👍🏻 

@smetl for final review.

2024-10-09 08:10 UTC, smetl approved these changes
@robodoo r+

2024-10-09 11:06 UTC, closed without merging