[FIX] website_sale: save phone on shipping address in express checkt
odoo/odoo pull request #176213
Opened 2024-08-08 14:51 UTC by mattismegevand

Steps to reproduce:
- Install `payment_stripe` and `website_sale`
- Configure express checkout for stripe - Add public/secret keys and - Enable "Apple Pay" in settings (to do this comment out this block) https://github.com/odoo/odoo/blob/0527b4b2ffe7d42222334b06a22739cf4963c617/addons/payment_stripe/models/payment_provider.py#L234-L237 - Enable "Link" in Stripe and add payment domain to ngrok domain
- Go to website in incognito page and open a product
- Add it to cart and click on the express checkout button
- Complete process to pay
- Go to contact linked to sale

Issues:
Phone is missing, this is because during the creation of the shipping address `res_partner` record we don't have the phone.

https://github.com/odoo/odoo/blob/0527b4b2ffe7d42222334b06a22739cf4963c617/addons/payment_stripe/static/src/js/express_checkout_form.js#L171-L181

opw-4055084

2024-08-08 14:51 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176213.png)](https://mergebot.odoo.com/odoo/odoo/pull/176213)

2024-08-08 17:14 UTC, nle-odoo approved these changes
seems that this could be ok

2024-08-19 09:55 UTC, ltinel reviewed
Hi @mattismegevand, thanks for your work! I tried to reproduce the issue on a 17.0 database, but the phone number was correctly populated (without your fix). Would you mind double-checking that the issue still happens? Or maybe something's missing in the repro steps which prevents me from getting the issue?

2024-08-21 09:21 UTC, mattismegevand commented
Hello @ltinel I just tried and got the issue locally, I think you may have mistaken the shipping partner with the billing partner.
The shipping partner doesn't have the mobile phone which is what my fix is solving.

2024-08-22 07:32 UTC, ltinel commented
I checked both the billing and shipping partners and they both had a phone number (none of them had a _mobile_ phone number though). Would you mind showing a screencast? Thanks!

2024-08-23 15:19 UTC, ltinel approved these changes
LGTM :)

2024-08-26 07:57 UTC, nle-odoo commented
robodoo delegate+

2024-08-26 08:51 UTC, chevalierv requested changes

2024-08-26 08:51 UTC, chevalierv commented on addons/website_sale/controllers/main.py
> +
This won't update the phone number of the shipping address if there is already one.

2024-09-02 09:12 UTC, chevalierv approved these changes

2024-09-02 16:34 UTC, AntoineVDV commented
@robodoo r+

2024-09-02 16:35 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2024-09-03 02:46 UTC, closed without merging