[FIX] account: fix list view edit in studio
odoo/odoo pull request #176250
Opened 2024-08-08 20:08 UTC by adda-odoo

Issue -->

Traceback when clicking `Edit List View` under Invoice Lines in the `account.move` form view while using Studio.
The cause of the issue is that the props update and lose the data that we expect in the getter `isProductClickable`.

Solution -->

Use an alternate way to get the parent record (account.move) in the case that the root model is not account.move.

opw-4100711

2024-08-08 20:09 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176250.png)](https://mergebot.odoo.com/odoo/odoo/pull/176250)

2024-08-12 12:37 UTC, rugo-odoo requested changes

2024-08-12 12:37 UTC, rugo-odoo commented on addons/account/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.js
> +        }
```suggestion
        if (this.props.record.model.root.data) {
            return this.props.record.model.root.data.state !== "draft";
        }
            
        return this.props.record._parentRecord.data.state !== "draft";
```
No need for the else, we can just use a guard clause.

2024-08-19 10:21 UTC, Megaaaaaa approved these changes
Thank you for the fix, LGTM !

2024-08-19 15:01 UTC, oco-odoo commented
@odoo/rd-framework-js  Could one of you confirm this is ok ? It functionally fixes the problem, but I'm not too sure about the deep JS framework logic ^^

2024-08-20 06:10 UTC, aab-odoo commented on addons/account/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.js
> +        return this.props.record._parentRecord.data.state !== "draft";
General remark: you're not supposed to access private properties (prefixed by _). I don't know what the issue/fix are though. If it's related to studio, @kebeclibre would know

2024-09-05 14:03 UTC, closed without merging