[IMP] stock: add contact to shipping documents in internal transfers
odoo/odoo pull request #176205
Opened 2024-08-08 14:03 UTC by jagh-odoo

Before this commit
==================
When contact is set on internal transfers, it was not added to respective shipping documents: picking operations and delivery slip

After this commit
=================
This commit ensures that when contact is set on internal transfers, it will be added to respective shipping documents: picking operations and delivery slip

TaskId: 4072882

2024-08-08 14:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176205.png)](https://mergebot.odoo.com/odoo/odoo/pull/176205)

2024-08-22 06:24 UTC, kir-odoo requested changes

2024-08-22 06:24 UTC, kir-odoo commented on addons/stock/report/report_stockpicking_operations.xml
> +                                </div>
Add this at first before state for better User viewing

2025-02-18 12:20 UTC, amoyaux commented
robodoo r+

2025-02-18 16:09 UTC, closed without merging