[IMP] point_of_sale: daily sales report layout improved
odoo/odoo pull request #176441
Opened 2024-08-12 06:44 UTC by ksku-odoo

Before this commit:
===================

task: 4035954

2024-08-12 06:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176441.png)](https://mergebot.odoo.com/odoo/odoo/pull/176441)

2024-08-28 10:24 UTC, paso-odoo requested changes

2024-08-28 10:24 UTC, paso-odoo commented on addons/point_of_sale/views/point_of_sale_report.xml
> +    </record>
@caburj 
Is it okay to create a new paperformat to achieve this?

2024-08-28 10:24 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> +                                <tr style="border-bottom: 0.1px solid #ccc;" t-foreach="category['products']" t-as="line">
```suggestion
                                <tr t-foreach="category['products']" t-as="line" style="border-bottom: 0.1px solid #ccc;">
```

2024-09-03 12:53 UTC, paso-odoo commented
@ksku-odoo 
- Removed newly created paper format
- Header with minimal code
I allowed myself to push the commit in your PR for the above points.
Please have a look at it!

Thanks

2024-09-06 06:15 UTC, paso-odoo requested changes

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
>                  <t t-if="refund_products" id="refunds">
```suggestion
                </div>
                <div t-if="refund_products" id="refunds" style="page-break-inside: avoid;">
```

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> +                                    <td/>
```suggestion
                                    <td><span t-out="internal_reference">7897</span><span t-out="line['product_name']">Laptop</span></td>
                                    <td/>
```
avoid style and use bootstrap

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> +                    <h6 class="custom-header fw-bold w-50 ms-auto">Taxes on refunds</h6>
`refund_taxes` should be in div and avoid it to break the page

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> +                    <h6  class="custom-header fw-bold">Discounts</h6>
```suggestion
                    <h6 class="fw-bold">Discounts</h6>
```

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> +                        <h6 class="custom-header fw-bold w-50 ms-auto">Payments</h6>
`payments` should also be in the div with avoiding the page-break

2024-09-06 06:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_session_sales_details.xml
> -                    <tbody>
Is there any reason for removing this code?

2024-09-18 13:11 UTC, caburj commented
robodoo r+

2024-09-18 15:49 UTC, closed without merging