[IMP] website: improve `s_banner` snippet
odoo/odoo pull request #176595
Opened 2024-08-13 11:36 UTC by anso-odoo

The goal of this PR is to improve the visual design of the default `s_banner` snippet.

task-4109584

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-13 11:37 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176595.png)](https://mergebot.odoo.com/odoo/odoo/pull/176595)

2024-08-13 11:39 UTC, anso-odoo commented
@stefanorigano Adding `s_blockquote` in `s_banner`. Can you have a look ?

2024-08-13 12:53 UTC, stefanorigano requested changes
Thanks @anso-odoo , some remarks for you 👍
Don't forget the mobile adaptations 😉

2024-08-13 12:53 UTC, stefanorigano commented on addons/website/views/snippets/s_banner.xml
> -                    <img class="img img-fluid mx-auto rounded" src="/web/image/website.s_banner_default_image" alt=""/>
Doing this way we'll keep `website .s_banner_default_image` defined, but we'll never use it 😉
Use it for the blockquote (L29 c.a.), eg:

```xml
<img src="/web/image/website.s_banner_default_image" class="s_blockquote_avatar img rounded-circle" alt=""/>
```

... and,  in `image_library.xml`, change the `url` attribute  of `s_banner_default_image` to the desired one -> `/website/static/src/img/snippets_demo/s_team_member_2.jpg`

2024-08-13 13:33 UTC, stefanorigano approved these changes
LGTM, thanks @anso-odoo 👍

2024-08-14 10:00 UTC, sobo-odoo commented
@anso-odoo I pushed [this small diff](https://github.com/odoo/odoo/compare/f076b05f44b7a068f97097baecb95dfaf6f4625c..c3bbcc07b4d8024fcab93032e8a3a91cc7188088) to:
- limit the commit message at 72 chars
- remove the `justify-content-center` class from the text grid item => already there before but it had no effect anyway since the display is not flex, so better remove it :+1: 
- add the `data-name="Blockquote"` attribute, so the blockquote does not just say "block" :wink:

2024-08-14 11:56 UTC, sobo-odoo approved these changes
It's okay with me :wink: 

@robodoo r+

2024-08-14 17:06 UTC, closed without merging