[FIX] sale_product_configurator: quantity not updating correctly
odoo/odoo pull request #176551
Opened 2024-08-13 06:31 UTC by shrm-odoo

Steps to reproduce:
- Create a new quotation.
- Choose a product with variants.
- Change the quantity in the product configurator.
- Click confirm.

Issue:
The quantity input in the product configurator does not update correctly when the 'Confirm' button is clicked. The changes are only applied after clicking outside the input field or pressing the 'Tab' key.

Cause:
The issue is caused by the reliance on the `t-on-change` event, which only triggers when the input loses focus.

Fix:
Replaced t-on-change with t-on-input to ensure immediate quantity updates as the user types, without requiring additional interactions.

opw-4049363

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-13 06:32 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176551.png)](https://mergebot.odoo.com/odoo/odoo/pull/176551)

2024-08-19 10:12 UTC, chevalierv requested changes
Hello @shrm-odoo 

Thanks for your investigation on this bug fix!

I don't consider this a bug but an intended feature. When you update the quantity, an RPC call is made to update the data (price, quantity available...). I decided to rely on a `t-on-change` to avoid spamming requests to the server without needing to debounce the method.

If you believe this gives a bad UX and still want to proceed with your fix, please call a debounced `setQuantity` in the `t-on-input` to avoid sending multiple requests to the server.

Have a nice day!

2024-08-21 07:34 UTC, shrm-odoo commented
@chevalierv I think it is bad UX, so as you suggested I have called debounce on setQuantity.

2024-08-21 11:21 UTC, chevalierv commented on addons/sale_product_configurator/static/src/js/product_configurator_dialog/product_configurator_dialog.js
> +            setQuantity: useDebounced(this._setQuantity.bind(this), 1000, true),
That's not really what I had in my mind. I meant for you to create a new method that would be the one denounced. I don't think debouncing `setQuantity` in every case is good.

Also, I'd use less time like 500ms max. 
```suggestion
            setQuantity: useDebounced(this._setQuantity.bind(this), 300),
```

2024-08-21 15:05 UTC, closed without merging