[FIX] base: do not override es_419
odoo/odoo pull request #176706
Opened 2024-08-14 07:59 UTC by asno-odoo

steps to reproduce.
1) Start a fresh database
2) Add any of the spanish languages except generic spanish 3) Start database again with -u all

Specifically check that we don't change the short_code for es_419 from 'es' to 'es_419' when adding spanish languages other than the generic one(es_419).

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 2248, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 1772, in _serve_db
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/registry.py", line 96, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/registry.py", line 120, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 422, in load_modules
    loaded_modules, processed_modules = load_module_graph(
                                        ^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-17.2/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/convert.py", line 630, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/convert.py", line 696, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/convert.py", line 616, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/convert.py", line 559, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-17.2/odoo/tools/convert.py", line 572, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-17.2/odoo/addons/base/data/res_lang_data.xml:15, somewhere inside
<record id="base.lang_es_419" model="res.lang">
            <field name="url_code">es</field>
        </record>
```

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-14 08:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176706.png)](https://mergebot.odoo.com/odoo/odoo/pull/176706)

2024-08-14 08:42 UTC, rdeodoo requested changes
Hello, I don't think we want to prevent the behavior for es_419, and there is a test covering it which is failing on the build.

Reading the commit, I don't understand what is the bug and why it fails/crashes.
Can you explain exactly what's going on? You told me about missing xmlid, but I don't read anything about it in the commit msg.

You can probably remove the traceback completely from the commit msg, it doesn't help and just add noise IMO:
![image](https://github.com/user-attachments/assets/4452f03f-e74b-43c1-9a20-7f9e5a8b4db1)
Maybe keep it on the PR description if you really want?

2024-08-14 08:53 UTC, asno-odoo commented
will remove traceback,
https://github.com/odoo/odoo/blob/saas-17.2/odoo/addons/base/data/res_lang_data.xml#L15
this will always update es_419 to have url_code 'es'  even if the language is active or not. The problem occurs when we have another spanish active and [this](https://github.com/odoo/odoo/blob/saas-17.2/odoo/addons/base/data/res_lang_data.xml#L15) tries to set the value of es_419 as 'es' and it leads to a clash and we get an error as its url_code should be unique.

2024-08-14 08:59 UTC, asno-odoo commented
its nothing to do with missing xmlid

2024-08-14 15:17 UTC, xO-Tx commented
@asno-odoo I force pushed to update the commit message, this way we have a clear explanation of what happens and the situation that leads to this issue :slightly_smiling_face: (maybe you need to set a task/ticket ID if you have one :+1:).

2024-08-14 15:21 UTC, asno-odoo commented
> @asno-odoo I force pushed to update the commit message, this way we have a clear explanation of what happens and the situation that leads to this issue 🙂 (maybe you need to set a task/ticket ID if you have one 👍).

thanks for that, the description is much clearer now,

2024-08-14 15:33 UTC, xO-Tx commented
@asno-odoo also force-pushed to only use the `noupdate` for the updates causing the issue (it seems riskier to add it for other XML updates) :slightly_smiling_face:

2024-08-14 15:41 UTC, rdeodoo approved these changes
@robodoo delegate=@xO-Tx 

As discussed in DM, seems to be the correct fix.
We could have just extracted those 2 records outside the existing `<data/>` to have only 2 `<data>` tag not 3, but this is the most minimal diff possible like that

2024-08-14 16:17 UTC, xO-Tx commented
@robodoo r+

2024-08-15 11:48 UTC, closed without merging

2024-08-16 15:40 UTC, asno-odoo commented
> @asno-odoo also force-pushed to only use the `noupdate` for the updates causing the issue (it seems riskier to add it for other XML updates) 🙂

yes thats what I had in mind too, thanks