[FIX] account_tax_python : accept JS format code in Python computed taxes
odoo/odoo pull request #176720
Opened 2024-08-14 09:25 UTC by mathcoutant

Only in saas-17.2 the JS style of addressing product fields is not accepted. (`product['standard_price']` is accepted, but not `product.standard_price`)

### Steps to reproduce:
- Create a tax with "Tax Computation" at "Python Code"
- Enter `result = (price_unit - product.standard_price) * 1` as the formula
- In Sales create a SO and add this tax
- An error shows saying product dict has no field standard_price

### Cause:
The code does not consider the formula can be written in JS format.

### Solution:
Change the formula to Python format each time it is used. The way to adapt the formula is the same as in saas-17.4 where the JS format is taken into account.

opw-4110562

2024-08-14 09:26 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176720.png)](https://mergebot.odoo.com/odoo/odoo/pull/176720)

2024-08-14 09:26 UTC, mathcoutant commented
@robodoo up to saas-17.2

2024-08-14 09:26 UTC, robodoo commented
Forward-port disabled (via limit).

2024-08-14 09:58 UTC, nle-odoo approved these changes
I don't understand functionally, but since it seems to have been adapted in 17.4 (in 5363189842674b77d03e031896cef2e5e970fdf7 I guess) it seems to makes sense to possibly adapt it in 17.2 too.

You should probably refer to 5363189842674b77d03e031896cef2e5e970fdf7 in the commit message, since it seems to contain part of the code of it (eg. the regex and formula replacement seem similar)

2024-08-26 08:17 UTC, smetl commented
@mathcoutant I think that's a good idea. However, can you backport part of the tests too and ensure both syntaxes are working: `product['blablabla']` or `product.blablabla`?

2024-08-26 13:50 UTC, mathcoutant commented
@smetl I added a test to ensure both syntaxes are working. I couldn't backport the `invalid_formula` test as in saas-17.2 no ValidationError is raised upon creation of the tax.

2024-08-29 09:39 UTC, smetl approved these changes
@odoo/rd-security The name of one `safe_eval`'s parameter changed, not a big deal

2024-08-29 10:48 UTC, xmo-odoo requested changes
Why does the JS side even allow attribute style access? Dict-style works perfectly fine in JS.

@robodoo override=ci/security

2024-08-29 12:00 UTC, mathcoutant commented on addons/account_tax_python/models/account_tax.py
> +        groups = re.findall(r'((?:product\.)(?P<field>\w+))+', formula) or []
I simply backported the way it was done in saas-17.4 up to master to keep coherence of the code and avoid discrepancies in behavior. 
code in master: https://github.com/odoo/odoo/blob/master/addons/account_tax_python/models/account_tax.py#L67-L73

I can change it if you think this should be changed, but maybe this commit is not the place to do it.

2024-09-02 07:21 UTC, smetl commented
@robodoo r+

2024-09-03 09:35 UTC, robodoo commented
@mathcoutant @smetl staging failed: ci/l10n on 1b7cb57afc0c877e7a24d1f15b04d8ac385ad662 (view more at https://runbot.odoo.com/runbot/build/67658986)

2024-09-03 13:34 UTC, yosa-odoo commented
Hello @smetl, can you delegate me on the PR ? MCOU has left the company and I'll be managing the foward-ports

2024-09-05 08:42 UTC, smetl commented
@robodoo delegate=yosa-odoo
@robodoo retry

2024-09-05 10:08 UTC, closed without merging