[FIX] DeserializeDate Doubling Time Offset
odoo/odoo pull request #176866
Opened 2024-08-15 17:52 UTC by cyro-odoo

Currently, when various timestamps in Odoo are processed through the DeserializeDate function, the offset is being doubled by mistake. The Odoo timestamps are passed as strings which have already been converted to UTC. If a user inputs a DateTime on a pricelist for instance, that time will be converted to its UTC equivalent before being converted to a string. The issue arises when we try to parse that string in the frontend during a PoS session. Odoo will correctly parse the timestamp, however through the DeserializeDate function it calls the FromSQL function with the parameter 
`zone: 'default'` which makes Odoo process this timestamp as being in the SystemZone (which is used by default in Luxon) instead of correctly recognizing that it is already in UTC. Thus, it will offset it again, which causes the functionality to fail

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-15 17:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/176866.png)](https://mergebot.odoo.com/odoo/odoo/pull/176866)

2024-08-19 14:01 UTC, davidmonnom requested changes

2024-08-19 16:50 UTC, cyro-odoo commented on addons/web/static/src/core/l10n/dates.js
> +export function deserializeDate(value, date_zone = "default") {
Updated the commit to reflect your input, let me know if there's anything else you notice! Thanks :)

2024-08-20 07:06 UTC, davidmonnom commented
@robodoo r+

2024-08-20 09:36 UTC, closed without merging

2024-08-27 08:05 UTC, aab-odoo commented
Hello. Sorry to react so late, I missed this PR. There're several things that are wrong with your commit:
 - the commit message is terrible (doesn't follow the conventions `[FIX] module_name: ...`, no description of the issue, no related task) I know information is in the PR, but it must be in the commit message (as well).
 - the code isn't linted (you can enable the tooling via ./addons/web/tooling/enable.sh, it will automatically lint/prettify your code when you commit)
 - the name of the variables you introduced is quite bad
 - I didn't challenge the real part of the fix (in pos), I hope that's correct...
 
To late for 17, but could you improve your commit when the forward port reaches master (i.e. do not r+ master like that, amend your commit before). Thanks

cc @davidmonnom

2024-08-27 08:06 UTC, aab-odoo commented on addons/web/static/src/core/l10n/dates.js
> +    const joinedDict = {...defaultDict, ...options}
suggestion:

```js
options = { numberingSystem: "latn", zone: "default", ...options };
```