[IMP] website: introduce `s_quadrant` snippet
odoo/odoo pull request #177058
Opened 2024-08-19 12:31 UTC by xlu-odoo

This commit adds the new `s_quadrant` snippet.

task-4105045
Part-of: task-4077427

requires: https://github.com/odoo/design-themes/pull/874

![Capture d’écran 2024-08-20 à 15 37 59](https://github.com/user-attachments/assets/e43cb768-f61d-44e6-9f86-f58cfeb0e1f6)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-19 12:32 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177058.png)](https://mergebot.odoo.com/odoo/odoo/pull/177058)

2024-08-19 15:14 UTC, Brieuc-brd requested changes
Good job @xlu-odoo, it's clean 👍 
I've left a few comments below ;)

Also :
- As this snippet centers the content, I wonder if it wouldn't be nice to have an image below this block on mobile. Just a thought, what do you think?
![Capture d’écran 2024-08-19 à 17 07 53](https://github.com/user-attachments/assets/781d06ee-5a59-4c47-b041-d60045498105)

- The snippet is broken when we switch to columns :
![Capture d’écran 2024-08-19 à 17 08 32](https://github.com/user-attachments/assets/9635be6a-9aad-4119-a7be-8aedd72251a3)
I think we should prevent it by hiding the option (check here to see how to do it : https://github.com/odoo/odoo/pull/176232/files#diff-9f41c68ba854940dda3361dc32795e2d7e9fc5b83ef7f8afd35a455b493e9930R649)

2024-08-19 15:14 UTC, Brieuc-brd commented on addons/website/views/snippets/s_quadrant.xml
> +                <div class="o_grid_item o_grid_item_image g-col-lg-6 g-height-6 col-lg-6 d-lg-block d-none o_snippet_mobile_invisible" style="z-index: 1; grid-area: 1 / 1 / 8 / 7; --grid-item-padding
```suggestion
                <div class="o_grid_item o_grid_item_image g-col-lg-6 g-height-7 col-lg-6 d-lg-block d-none o_snippet_mobile_invisible" style="z-index: 1; grid-area: 1 / 1 / 8 / 7; --grid-item-padding-y: 0px; --grid-item-padding-x: 0px;">
```

2024-08-19 15:14 UTC, Brieuc-brd commented on addons/website/views/snippets/s_quadrant.xml
> +                        <a t-att-href="cta_btn_href" class="btn btn-primary btn-lg"><t t-esc="cta_btn_text">Learn more</t></a>
```suggestion
                        <a t-att-href="cta_btn_href" class="btn btn-primary btn-lg"><t t-out="cta_btn_text">Learn more</t></a>
```

2024-08-20 09:24 UTC, xlu-odoo commented
> Good job @xlu-odoo, it's clean 👍 I've left a few comments below ;)
> 
> Also :
> 
> * As this snippet centers the content, I wonder if it wouldn't be nice to have an image below this block on mobile. Just a thought, what do you think?
>   ![Capture d’écran 2024-08-19 à 17 07 53](https://private-user-images.githubusercontent.com/80679690/359152202-781d06ee-5a59-4c47-b041-d60045498105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDU5NDAsIm5iZiI6MTcyNDE0NTY0MCwicGF0aCI6Ii84MDY3OTY5MC8zNTkxNTIyMDItNzgxZDA2ZWUtNWE1OS00YzQ3LWIwNDEtZDYwMDQ1NDk4MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2FlZjE0NmQ2MjQzNmRlMDM1YzYzNTA3Y2RkN2JlMmUxYjQ4NDJkY2VhYTUxYTRkYjg2ZDdhYmQ3MDE5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjMQBxMUpkzqV4raB1ptfl1KqEXrMKKK45SbATIu_7s)
> * The snippet is broken when we switch to columns :
>   ![Capture d’écran 2024-08-19 à 17 08 32](https://private-user-images.githubusercontent.com/80679690/359152335-9635be6a-9aad-4119-a7be-8aedd72251a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDU5NDAsIm5iZiI6MTcyNDE0NTY0MCwicGF0aCI6Ii84MDY3OTY5MC8zNTkxNTIzMzUtOTYzNWJlNmEtOWFhZC00MTE5LWE3YmUtOGFlZGQ3MjI1MWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWU3MDVlOTYwNTdkMDIxOTllNDdkMjczM2E5ZDQ5YmUxYTE1NTUyMTBlNzFiNGQ4YTEzMTlkMTc2MzY4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4rY8FjM8Z8Xsb1GwVQx_bKxjZMx4jXibh8-ttDB3zY)
>   I think we should prevent it by hiding the option (check here to see how to do it : [#176232 (files)](https://github.com/odoo/odoo/pull/176232/files#diff-9f41c68ba854940dda3361dc32795e2d7e9fc5b83ef7f8afd35a455b493e9930R649))

Excellent idea for the mobile. (using order)
Made all the changes, thanks for the review @Brieuc-brd .

2024-08-20 12:35 UTC, Brieuc-brd approved these changes
Thanks @xlu-odoo !
Just a nitpick below 😬 

Beside that LGTM 👍

2024-09-06 08:18 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-09-08 13:57 UTC, bvr-odoo commented
@robodoo r+

2024-09-08 15:04 UTC, closed without merging