[FIX] web_editor: revert backgorund filter in cover template change
odoo/odoo pull request #177174
Opened 2024-08-20 09:21 UTC by Mtaylorr

Commit that introduced the issue https://github.com/odoo/odoo/pull/128108/commits/33a04876cad58f413455bdc406c1ad4c70d73e1b

Steps to reproduce the issue:
=============================
- Create a new mass mailing
- Add cover snippet
- Test the email
- Background image doesn't appear

Origin of the issue:
====================
After the chnage of the mentioned commit, we add a div with a black background filter. It displays correclty in mass_mailing view since it has opacity 0.5 but after the `inline` process of the template we convert rgba colors to hex color with `rgbToHex` because some email engines doesn't support rgba. As a result, we will have a black div that covers the background image in the sent email.

Solution:
=========
Rever the change.

task-4070400

2024-08-20 09:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177174.png)](https://mergebot.odoo.com/odoo/odoo/pull/177174)

2024-09-12 13:12 UTC, dmo-odoo requested changes
The change should only impact mass_mailing, not website.

2024-10-08 15:05 UTC, Mtaylorr commented
@dmo-odoo this is ready for review, let me know what you think about the current fix , thanks

2024-10-09 08:47 UTC, dmo-odoo commented
@robodoo r+

2024-10-09 11:07 UTC, closed without merging