[FIX] base: propagate changes on implied groups update
odoo/odoo pull request #177301
Opened 2024-08-20 19:37 UTC by ivantodorovich

Steps to reproduce:

1. Add a stored computed field on `res.users` that depends on `groups_id`
2. Add a constraint on `res.users` that depends on `groups_id`
3. Give the user a group
4. Modify the given group and add an implied group

Result:

- The computed field is not recomputed
- The constraint is not checked

The reason for this is that the users groups are updated with a raw SQL query, and the ORM is not aware of the changes.

This is a regression since 5f12e244. This issue was partially detected and fixed in 459e6dc1, but only for a single constraint.

This commit makes sure that the ORM properly propagates the changes to computed fields and all constraints, not just the one that was explicitly checked.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-20 19:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177301.png)](https://mergebot.odoo.com/odoo/odoo/pull/177301)

2024-08-21 13:09 UTC, kmagusiak requested changes

2024-08-21 13:56 UTC, ivantodorovich commented on odoo/addons/base/models/res_users.py
> +            updated_user_ids = [row[0] for row in self.env.cr.fetchall()]
Ouch, I must be blind.
Thanks for pointing this out!

2024-08-21 13:57 UTC, ivantodorovich commented on odoo/addons/base/models/res_users.py
> +            updated_users.modified(['groups_id'])
Absolutely. I modified the code to process the updated groups, too.

2024-08-21 13:58 UTC, ivantodorovich commented
Thanks for your review, @kmagusiak ❤️

2024-08-21 15:02 UTC, kmagusiak approved these changes

2024-12-04 17:41 UTC, ivantodorovich commented
Gentle ping.
Any chance we can merge this one? 😄

2024-12-04 19:15 UTC, kmagusiak commented
@ryv-odoo @Gorash can you review?

2024-12-06 09:27 UTC, Gorash requested changes
When changing a group on a user we clear the cache (see `_get_invalidation_fields`). It is not useful to be specific when changing a group. Just use `self.clear_caches()`
The code will be simpler and will have the same behavior as when you modify a user (which is actually the case). In addition, some rights may be cached and must be invalidated.
ping @ryv-odoo

2024-12-06 10:18 UTC, ivantodorovich commented
Hmmm 🤔 I fail to see how `clear_caches` would help to solve this:

> - The computed field is not recomputed
> - The constraint is not checked

Am I missing something?

2024-12-06 11:12 UTC, rco-odoo reviewed
Could you please add some test?

2024-12-06 11:12 UTC, Gorash approved these changes
My bad, I'm confusing it with future devs. All this code will be deleted no longer be needed.

2024-12-10 09:42 UTC, Gorash commented
lgfm
ping @rco-odoo ;)

2024-12-10 10:15 UTC, rco-odoo approved these changes
@robodoo r+

2024-12-10 10:16 UTC, rco-odoo commented
@ivantodorovich good job, and thanks for your contribution.
I am taking care of the unrelated failing test.

2024-12-10 11:02 UTC, ivantodorovich commented
Thanks 🙏🏻!

2024-12-10 14:28 UTC, closed without merging