[FIX] web: prevent out of bound error in ListRenderer
odoo/odoo pull request #177407
Opened 2024-08-21 13:16 UTC by naja628

Steps
---
* install `stock`
* create a delivery for 2 products > *Mark as Todo* > *Validate*
* make a return, a `ListRenderer` for the return moves open
* click the last field (quantity) of the last record in the list
* press <tab> * => Traceback: `Uncaught Promise > futureRecord is undefined`

Cause
---
This specific view is `editable='top' create='0'`, but the return moves have been generated on the fly, so their `isNew` property is true.

But, we check `isNew` to decide if a record has just been created in the list, and what element is the last.

This leads to a false negative where we fail to detect that we're on the last record.

opw-4108845

2024-08-21 13:17 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177407.png)](https://mergebot.odoo.com/odoo/odoo/pull/177407)

2024-08-22 12:45 UTC, naja628 commented
I guess technically we could still run into problems if we both have a `ListRenderer` for records that were just created, and the view is `group by`d by default, or maybe if we have a lot of generated records and we page them and go to the second page.

2024-08-22 12:53 UTC, naja628 commented
Another solution I thought of would to change all `<tree editable='top' create='0'>` views (n=5 according to naïve grep) to `editable='bottom'` but that's duct-tape-y and we still have minor bugs in the `create='1'` case...

2024-08-29 15:18 UTC, abz-odoo requested changes
Need a test !

2024-09-19 06:48 UTC, closed without merging