[IMP] website: introduce `s_key_images` snippet
odoo/odoo pull request #177463
Opened 2024-08-21 16:39 UTC by Brieuc-brd

This commit adds the new `s_key_images` snippet.

task-4105059
Part of task-4077427

Requires:
-

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-21 16:40 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177463.png)](https://mergebot.odoo.com/odoo/odoo/pull/177463)

2024-08-22 08:42 UTC, chgo-odoo approved these changes
LGTM, thanks ! 👍

2024-08-26 10:23 UTC, Brieuc-brd commented
- Added custom texts for themes
- Reviewed images of Loftspace and Threehouse
- Rebased

2024-08-29 14:08 UTC, bvr-odoo requested changes
@Brieuc-brd Here is my review, thanks for the work

2024-08-29 15:00 UTC, Brieuc-brd commented on addons/website/views/snippets/s_key_images.xml
> +                    <h2 class="display-5">What we propose to our customers</h2>
Indeed 🙁 Thanks for creating a PR for that 👍 
I've also started checking all my Open PRs to solve this issue asap :)
Here it's now fixed ✅

2024-08-29 15:01 UTC, Brieuc-brd commented on addons/website/views/snippets/s_key_images.xml
> +                    <img src="/web/image/website.s_key_images_default_image_1" class="img img-fluid rounded" alt="" style="width: 100% !important;"/>
Good catch, thanks 👍 
Fixed, I also adapted the themes as well ✅

2024-08-29 15:07 UTC, Brieuc-brd commented
Hey @bvr-odoo 👋 
Thanks for your review, I've updated the branches and left some comments.
Here's the diff : 
- COM: https://github.com/odoo/odoo/compare/5a480662fffca18f8fe7b524353a3b06fc62cee3..17dd2cf22bb078f497fb6a1090f3f629eb084c63
- DT: https://github.com/odoo/design-themes/compare/77284af81391469daeedeb3bbdf9c1b5eb710fa5..bd6b9149327b7a7a11744b38c07d8c4e63b23411

I'll rebase to solve conflicts once these PRs will be ready to be r+ 🙂

2024-08-30 07:36 UTC, bvr-odoo commented
Hi @Brieuc-brd , LGTM :+1:  could you rebase to have both runbots green and without conflicts. Thanks :pray:

2024-08-30 07:51 UTC, Brieuc-brd commented
Hey @bvr-odoo 👋, done ✅

2024-08-30 08:45 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-08-30 09:56 UTC, bvr-odoo approved these changes
LGTM :+1:

2024-08-30 11:41 UTC, bvr-odoo commented
@Brieuc-brd runbot is red :/

2024-08-30 13:06 UTC, Brieuc-brd commented
@bvr-odoo It's now green 🟢

2024-09-03 16:53 UTC, bvr-odoo commented
@robodoo r+

2024-09-04 01:03 UTC, closed without merging