[FIX] sale: don't leak the company_id in values when creating a new order
odoo/odoo pull request #177669
Opened 2024-08-22 19:27 UTC by ivantodorovich

**Steps to reproduce:**

>>> print(self.env.company)
res.company(1)

>>> company1, company2, company3 = self.env['res.company'].browse([1,2,3])
>>> orders = self.env['sale.order'].create(
    [
        {'partner_id': partner.id, 'company_id': company1.id},
        {'partner_id': partner.id, 'company_id': company2.id},
        {'partner_id': partner.id, 'company_id': company3.id},
    ]
)

>>> print(orders.env.company)
res.company(3)

**Expected result:**

The company in the environment returned should be the same than the company in the environment that created the order.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-22 19:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177669.png)](https://mergebot.odoo.com/odoo/odoo/pull/177669)

2024-08-26 14:29 UTC, Feyensv requested changes
What do you mean leak?  It sounds like a security issue when I don't believe it's one.
I believe this might introduce some issues, because updating the super call environment also ensures that the defaults are taken from the right company, which also matters.

Wouldn't `return super().create(vals_list).with_env(self.env)` be a safer fix ?

2024-08-26 14:58 UTC, ivantodorovich commented
Hello!

Thanks for the review :)

Oh, perhaps "leak" is not the right word. I didn't mean there's a security issue.
It's just something I encountered, that I found misleading when working programatically with the ORM.

This code was added a long time ago, not for the defaults but for some company-dependent properties that were filled in right here on `create` (e.g.: the pricelist)

See: https://github.com/odoo/odoo/commit/0c1fcfb0e1ee7481518403bfe0dfd01200d7c060

The code was later refactored to support the `model_create_multi` decorator, and moved within the for loop: https://github.com/odoo/odoo/commit/f503e69d3bc56bfad1d9405ee0b76dbd975c4872#diff-695321b9df7129604a59fbc9bff34f97ba90b3394aa1166ca24e36b27389ae82

⚠️ Notice that, when doing so and presented with a `vals_list` like the one I provided, `super()` is called with the company present in the last item of these `vals_list`. I don't expect this to be an issue, as I don't think we rely on this for anything else than what I described above.

Later, these values read from properties were moved to their own computed methods
e.g.:
https://github.com/odoo/odoo/blob/28d2df7f0763389126a3d4d7193ae7783f58fa76/addons/sale/models/sale_order.py#L411-L420

That made our company resetting code relevant only for the `ir.sequence.next_by_code` call here.
Which is why I propose to go back to the original state before: https://github.com/odoo/odoo/commit/0c1fcfb0e1ee7481518403bfe0dfd01200d7c060, which is only setting the company for this line of code.

2024-08-26 15:15 UTC, Feyensv approved these changes
I agree that this doesn't work well when different companies are provided in `vals_list`.
Until now, I considered that even if the multi-records case was a bit less reliable, most flows only create one SO at a time so it was ok.

Considering your investigation, we can indeed go back to the previous state, it shouldn't break many things (if it even does break anything), and removes some strange/magic logic.

@robodoo r+ squash

2024-08-26 15:16 UTC, robodoo commented
Merge method set to squash.

2024-08-27 00:44 UTC, closed without merging