[IMP] account: Payment method by partner
odoo/odoo pull request #177772
Opened 2024-08-23 14:01 UTC by malb-odoo

This commit will do 3 things:
- As the filter actually works on the field on Invoices, rename the filter to just Payment Method
- Rename the field on moves "Payment Method"
- Add the group on the Amounts to Settle view as well

task: 4134485

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-23 14:02 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177772.png)](https://mergebot.odoo.com/odoo/odoo/pull/177772)

2024-08-29 08:03 UTC, yosuanicolaus requested changes
LGTM, but where is the change for the 3rd requirement in the spec?
```
Add the group on the Amounts to Settle view as well
```
Or is it already done?

2024-08-29 08:24 UTC, malb-odoo commented
> LGTM, but where is the change for the 3rd requirement in the spec?
> 
> ```
> Add the group on the Amounts to Settle view as well
> ```
> 
> Or is it already done?

we decided not to it because it imply adding a stored related field on the move lines and we decided it was overkill :smile:

2024-08-29 08:26 UTC, yosuanicolaus approved these changes
final review by @gawa-odoo

2024-08-30 15:04 UTC, gawa-odoo reviewed
@robodoo r+

```
This commit will do 3 things:
1
2
...
```
:smile: Won't bother making you change for it
Don't hesitate to put the fact that it was removed in the task/chatter as well (and why)

2024-08-31 22:13 UTC, closed without merging