[FIX] point_of_sale: retrieve role from the correct field
odoo/odoo pull request #177892
Opened 2024-08-26 11:44 UTC by walidsahli

Problem:
The `role` attribute is being retrieved from the `raw` field, but when the page is refreshed, all attributes (including `role`) are set in the `cashier` object, not in `raw`.

Steps to reproduce:

- Set up a PoS session with the "Log in with Employees" setting enabled.
- Use a User/Employee with Administrator PoS access (e.g., Mitchell Admin).
- Start a PoS session.
- Refresh the page.
- Click the "i" icon to see more information about a product.
- A traceback occurs.

opw-4120414

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-26 11:44 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/177892.png)](https://mergebot.odoo.com/odoo/odoo/pull/177892)

2024-08-27 09:03 UTC, robinengels commented
LGTM, could you also add a test ? Thanks !

2024-08-27 15:14 UTC, nle-odoo approved these changes
if not .raw works in both situation, seems good to me

2024-08-28 08:43 UTC, walidsahli commented
> LGTM, could you also add a test ? Thanks !

Tests added.

2024-08-28 09:41 UTC, robinengels requested changes

2024-08-28 09:41 UTC, robinengels commented on addons/pos_hr/static/tests/tours/PosHrTour.js
> +            {
There is an helper for this `ProductScreen.clickInfoProduct(productName)`

2024-08-28 09:41 UTC, robinengels commented on addons/pos_hr/static/tests/tours/PosHrTour.js
> +});
You need to add a newline at the end of the file. Depending on your IDE there should be an option to automatically add it when you save a file

2024-08-28 09:41 UTC, robinengels commented on addons/pos_hr/tests/test_frontend.py
> +        )
same

2024-09-20 08:43 UTC, walidsahli commented
Create another PR because of wrong branch name.
PR > https://github.com/odoo/odoo/pull/180841

2024-09-20 08:43 UTC, closed without merging