[FIX] stock: pick move lines linking to a picked move
odoo/odoo pull request #178017
Opened 2024-08-27 09:06 UTC by lase-odoo

### Steps to reproduce:

- Create and confirm a delivery for 10 units of a product P
- Change the quantity of the move to 5 and mark it as picked
- Click on the "detailed operations" button of the picking
- Change the quantity of the move line to 3
- Create a new line for 2 units (this would make sense if you want to register 2 lots for instance the flow is kepts as simple possible)
- Go back to the delivery, validate and create a back order

#### > A back order is created for 7 units rather than 5 and the original delivery was validated for only 3 units.

### Cause of the issue:

When you create a new move line on the picking from the detailed operation it is linked to the move of the picking via these lines: https://github.com/odoo/odoo/blob/4c79aceb3a6c08453f9ec66131e1bc525eae140c/addons/stock/models/stock_move_line.py#L325-L331 However, while the move is marked as picked, the newly created move line is not. As such during the `_action_done` of the stock move, the new sml will be unlinked from the move:
https://github.com/odoo/odoo/blob/4c79aceb3a6c08453f9ec66131e1bc525eae140c/addons/stock/models/stock_move.py#L1865-L1872

opw-4100293
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-27 09:06 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178017.png)](https://mergebot.odoo.com/odoo/odoo/pull/178017)

2024-08-27 15:23 UTC, nle-odoo approved these changes
seems to makes sense to me

2024-08-28 05:45 UTC, lase-odoo commented on addons/stock/models/stock_move_line.py
> +                        vals['picked'] = True
Indeed ! You should not write False particularly in because of barcode flows !

2024-08-29 11:35 UTC, adwid requested changes
No test ?

2024-08-29 11:50 UTC, lase-odoo commented
@adwid you really want a tour for this ?

2024-08-29 19:11 UTC, closed without merging