[IMP] base_setup, google_recaptcha: update reCAPTCHA toggle behavior
odoo/odoo pull request #178166
Opened 2024-08-28 09:34 UTC by alessandro-caldonazzi

The `recaptcha_enabled` field now controls whether reCAPTCHA is active. Unchecking this box will disable reCAPTCHA without uninstalling the module. For reCAPTCHA to function, the keys must be set and the checkbox must be checked. Disabling the checkbox turns off reCAPTCHA functionality without affecting the stored keys.

task-3380702

2025-01-14 09:17 UTC, SergeBayet requested changes
Looks great :+1: Thanks. Just maybe an improvement. See below:

2025-01-14 09:17 UTC, SergeBayet commented on addons/google_recaptcha/models/ir_http.py
>              session_info['recaptcha_public_key'] = public_key
I would avoid call sudo() twice here.
```suggestion
        """Add the ReCaptcha configuration to the given session_info object"""
        config_params = request.env['ir.config_parameter'].sudo()
        session_info['recaptcha_enabled'] = str2bool(
            config_params.get_param('enable_recaptcha', default=True)
        )
        public_key = config_params.get_param('recaptcha_public_key')
        session_info['recaptcha_public_key'] = public_key or ''
```

2025-01-14 09:23 UTC, SergeBayet commented
@xO-Tx Perhaps consider improving the commit message. I had to read it twice to realize that it’s describing the updated behavior rather than the previous one. :)

2025-01-23 12:36 UTC, qsm-odoo requested changes
@xO-Tx Some comments here. But I'd say the priority would be to create another 16.0 PR first to fix this problem in a stable way, then we'll merge this once that other PR is fully forward-ported. Not sure what is the best way, I let you think about it. At worst, it could be something as easy as "a css rule which hides the uninstallation checkbox".

2025-01-23 12:36 UTC, qsm-odoo commented on addons/google_recaptcha/models/res_config_settings.py
> +    enable_recaptcha = fields.Boolean("Enable reCAPTCHA", config_parameter='enable_recaptcha', groups='base.group_system')
You are adding this field but I don't see you removing the existing field which trigger the uninstallation, is that normal?

2025-01-23 12:36 UTC, qsm-odoo commented on addons/google_recaptcha/models/ir_http.py
> +        public_key = config_params.get_param('recaptcha_public_key')
Is there value to have both data in the session info? Would not this be as good but with less session data to load and less JS code if we were to just not send the existing key in the session if recaptcha is not enabled?

2025-01-23 12:36 UTC, qsm-odoo commented on addons/google_recaptcha/views/res_config_settings_view.xml
> +            </xpath>
Ok, when website is not installed you still allow to enable the recaptcha app... but is there any value in having a setting to do that? Is not it automatically installed for apps who use it? To confirm, they added recaptcha for the sign up page but I don't see it as a dependency of anything other than website

2025-01-24 15:41 UTC, xO-Tx commented on addons/google_recaptcha/models/ir_http.py
> +        public_key = config_params.get_param('recaptcha_public_key')
Yes seems better with one value. Actually, it's the same behaviour when the public key is not available: the script won't be loaded… So why not making this controlled by the setting value in backend and only use the "public key" check :+1:)

2025-01-24 15:41 UTC, xO-Tx commented on addons/google_recaptcha/views/res_config_settings_view.xml
> +            </xpath>
Hmmm... Isn't it better to be able to activate the `form[data-captcha]` public widgets even if the module of a form is not automatically installing reCAPTCHA module as we do for [signup forms](https://github.com/odoo/odoo/commit/37fb21911ef33885a3dae309158a359ed1a604e0)? (Which is the same thing for the `website_cf_turnstile` public widget, I guess.) :thinking:

2025-01-24 15:42 UTC, xO-Tx commented on addons/google_recaptcha/models/res_config_settings.py
> +    enable_recaptcha = fields.Boolean("Enable reCAPTCHA", config_parameter='enable_recaptcha', groups='base.group_system')
See: https://github.com/odoo/odoo/pull/178166#discussion_r1928885511 :+1:

2025-02-07 10:53 UTC, qsm-odoo approved these changes
Looks good to me, I'll trust you tested that plenty :+1: 

@robodoo r+

2025-02-07 13:42 UTC, closed without merging