[IMP] loyalty,sale_loyalty: domain in cheapest reward
odoo/odoo pull request #178153
Opened 2024-08-28 04:44 UTC by dere-odoo

Prior to this commit:
- No way to set domain for products in loyalty reward for reward type discount 
and discount_applicability cheapest product

Post this commit:
- Updated discount_product_ids, discount_product_category_id, 
discount_product_tag_id to be available on discount_applicability cheapest  in 
loyalty reward form.

Task-3976068

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-28 04:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178153.png)](https://mergebot.odoo.com/odoo/odoo/pull/178153)

2024-12-20 16:36 UTC, anko-odoo requested changes
Hello, good job on the task. Very sorry for the delay, somehow this task flew under my radar. Only minor changes in code. But you could elaborate a bit more in commit message so it will be more "human friendly" regarding the changes.

2024-12-20 16:36 UTC, anko-odoo commented on addons/sale_loyalty/models/sale_order.py
> +            if (not cheapest_line or cheapest_line_price_unit > line_price_unit) and line.product_id.filtered_domain(domain):
line over 100

2024-12-20 16:36 UTC, anko-odoo commented on addons/sale_loyalty/models/sale_order.py
> +                cheapest_line = cheapest_line or self._cheapest_line(line_reward)
I feel like this line could use a comment why in discount_specific we check cheapest line.

2025-01-27 09:52 UTC, Demesmaeker requested changes
Hello @dere-odoo :duck: 

Here is a little change that could be applied =]
Have a nice day!

2025-01-27 16:14 UTC, Demesmaeker requested changes
Hello @dere-odoo :duck: 

Small nitpicking changes, I personally think it improves the readability, but your version is fine too, so feel free to ignore these.

Anyway, this part of the code is cruelly lacking tests, can I also ask you to add one for this? :pray: 

Thanks in advance!

2025-01-27 16:14 UTC, Demesmaeker commented on addons/sale_loyalty/models/sale_order.py
> +                or (cheapest_line and cheapest_line_price_unit <= line_price_unit)
```suggestion
```

2025-01-27 16:14 UTC, Demesmaeker commented on addons/sale_loyalty/models/sale_order.py
> +            cheapest_line_price_unit = line_price_unit
and keep this as it was =]

2025-01-28 09:14 UTC, Demesmaeker reviewed
Hello @dere-odoo :duck: 

After these changes, it should be good to go, I'll let a bit of time in case POS want to add something, but should be good

2025-01-28 09:14 UTC, Demesmaeker commented on addons/sale_loyalty/tests/test_loyalty.py
> +        )
```suggestion
        msg = "Discount should be applied only on line with applicable products"
        self.assertEqual(order.amount_total, 95, msg)
```

2025-01-28 09:14 UTC, Demesmaeker commented on addons/sale_loyalty/tests/test_loyalty.py
> +            "Discount should be applied only on line with applicable products"
```suggestion
            "Discount should only be applied to the line with a correctly tagged product."
```

2025-01-29 11:41 UTC, davidmonnom requested changes

2025-01-29 11:41 UTC, davidmonnom commented on addons/pos_loyalty/static/src/app/models/pos_order.js
> +                !line.comboParent &&
```suggestion
                !line.combo_parent_id &&
```

I know it was already there but `comboParent`didn't exist on pos_order_line

2025-01-29 11:41 UTC, davidmonnom commented on addons/pos_loyalty/static/src/app/models/pos_order.js
> +                line.getQuantity &&
```suggestion
                line.getQuantity() &&
```

Same, isn't a getter.

2025-01-31 12:25 UTC, Demesmaeker commented
We changed our mind :partying_face:

2025-01-31 12:26 UTC, Demesmaeker commented
@robodoo r+

2025-01-31 15:13 UTC, closed without merging