[IMP] website: introduce `s_references_grid` snippet
odoo/odoo pull request #178359
Opened 2024-08-29 11:52 UTC by mano-odoo

This commit adds the new s_references_grid snippet.

task-4146798
Part-of: task-4077427

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-08-29 11:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178359.png)](https://mergebot.odoo.com/odoo/odoo/pull/178359)

2024-09-06 15:24 UTC, anso-odoo requested changes
Small comments for you @mano-odoo

2024-09-06 15:24 UTC, anso-odoo commented on addons/website/views/snippets/s_references_grid.xml
> +                    <a t-att-href="cta_btn_href" class="btn btn-primary"><t t-esc="cta_btn_text">See our case studies</t></a>
```suggestion
                    <a href="#" class="btn btn-primary">See our case studies</a>
```

`cta_btn_text` and `cta_btn_href` will make this button dynamic based on what the user selected in the configurator. Here I think we want it to stay always "case studies" related, right ? 

See: https://github.com/odoo/odoo/pull/71162

2024-09-06 15:24 UTC, anso-odoo commented on addons/website/views/snippets/s_references_grid.xml
> +                <div class="o_grid_item o_colored_level g-height-5 g-col-lg-5 col-lg-5" style="grid-area: 1 / 1 / 5 / 6; z-index: 1;">
```suggestion
                <div class="o_grid_item g-height-4 g-col-lg-5 col-lg-5" style="grid-area: 1 / 1 / 5 / 6; z-index: 1;">
```

2024-09-06 15:24 UTC, anso-odoo commented on addons/website/views/snippets/s_references_grid.xml
> +            <div class="row o_grid o_grid_mode" data-row-count="4">
```suggestion
            <div class="row o_grid_mode" data-row-count="4">
```

2024-09-10 09:53 UTC, anso-odoo approved these changes

2024-09-11 11:18 UTC, mano-odoo commented
> Is it possible to change the `s_references` images?

@bvr-odoo 
I think it's up to the users to replace the demo images to fit their design. Setting a background or an opacity on the images to make them look okayish on every background color would restrict the users if they are uploading images that perfectly fit their design. It would add up (unwanted) opacity and background.

2024-09-11 11:31 UTC, bvr-odoo commented
> I think it's up to the users to replace the demo images to fit their design. Setting a background or an opacity on the images to make them look okayish on every background color would restrict the users if they are uploading images that perfectly fit their design. It would add up (unwanted) opacity and background.

I meant an opacity (or whatever) integrated into the images, not added via the options on the images. :wink:

2024-09-11 11:54 UTC, mano-odoo commented
> I meant an opacity (or whatever) integrated into the images, not added via the options on the images. 😉

Sorry I misunderstood 🙇 So I just discussed this with SRI and we are not in favour of changing the demo images because it's  predictable enough. The user changes the background to a color that matches the demo images the images are not visible. 

It's sufficiently expected to not be considered an issue.

2024-09-11 13:06 UTC, bvr-odoo approved these changes
LGMT :+1: Thanks

2024-09-19 14:26 UTC, SergeBayet commented
Commit(s) moved into
- https://github.com/odoo/odoo/pull/180736

2024-09-19 14:26 UTC, closed without merging