[FIX] account: Allow users to edit subview list with studio
odoo/odoo pull request #178771
Opened 2024-09-02 08:26 UTC by abz-odoo

Steps to reproduce:

* Install `web_studio` and `account`
* Open customers/invoices
* Edit view form with studio
* click on subview list
* click edit
* traceback

```
TypeError: Cannot read properties of undefined (reading 'state')
    get isProductClickable()
    /account/static/src/components/product_label_section_and_note_field/
        product_label_section_and_note_field.js:188
```

To get fields from the parent view, we need to use evalContext instead
of `model.root`.

Ticket [link](https://www.odoo.com/odoo/project/967/tasks/4148174)
opw-4148174

2024-09-02 08:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178771.png)](https://mergebot.odoo.com/odoo/odoo/pull/178771)

2024-09-02 14:40 UTC, rugo-odoo commented on addons/account/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.js
> +        return this.props.record.model.root.data?.state !== "draft";
Why don't we have any `data` ? What was the cause of the problem ?

2024-09-03 13:53 UTC, lordkrandel requested changes
Can you please change the commit message to be more concise, remove indentation, and be similar to the edited PR description? Commit messages are also useful in `git blame` and `git log`, or other IDE interfaces, not only in Github where space is abundant.

Thank you in advance ^^

2024-09-05 13:06 UTC, lordkrandel approved these changes
LGTM

2024-09-05 14:12 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-09-05 16:06 UTC, closed without merging