[IMP] core: deprecate odoo.registry()
odoo/odoo pull request #178784
Opened 2024-09-02 10:18 UTC by kmagusiak

You can use directly `odoo.modules.registry.Registry` when needed and cases where you need to do it are rare. At the same time, this allows to remove a function from the `odoo` package.

task-4069446

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-02 10:19 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178784.png)](https://mergebot.odoo.com/odoo/odoo/pull/178784)

2024-09-02 11:02 UTC, lordkrandel requested changes
Some minor

2024-09-02 14:06 UTC, kmagusiak commented on addons/website/models/website.py
> +    return Registry(database_name)
After checking the code, they can be removed as the registry is already reset in `_button_immediate_function`. A similar assert is in there.

2024-09-02 15:26 UTC, lordkrandel requested changes
I wouldn't add `warnings` to the `odoo` namespace, it's a very special one.

2024-09-02 15:26 UTC, lordkrandel commented on odoo/__init__.py
> +    warnings.warn("Use directly odoo.modules.registry.Registry", DeprecationWarning)
```suggestion
    from warnings import warn  # noqa: PLC0415
    warn("Use directly odoo.modules.registry.Registry", DeprecationWarning)
```

2024-09-02 15:26 UTC, lordkrandel commented on odoo/__init__.py
> +
```suggestion
```

2024-09-02 16:08 UTC, lordkrandel commented
As far as the code here, I have no more comments.

For the PR scope, I'm probably not the best person to judge, but since the task is kinda explicit on what to do, I would also assume it's ok. 

Someone would have to verify that all the codepoints have been fixed, and some manual testing that nothing blows up, even though automated testing should already do.

You can add the related PRs also to the commit message, for fast reference.

2024-09-05 14:06 UTC, ryv-odoo approved these changes
@robodoo r+
LGTM

2024-09-05 16:37 UTC, closed without merging