[IMP] website_sale: mega menu for ecommerce categories
odoo/odoo pull request #178832
Opened 2024-09-02 13:46 UTC by mash-odoo

**Prior this commit:**
- There was no mega menu based on ecommerce categories. Hence, if a user wanted
one, he had to create it from scratch by typing in the name of each category
and copy/pasting each URL linked to it.

**Post this commit:**
- The user can now easily get the mega menu of Ecommerce categories for all the
possible templates by clicking on a button corresponding to the template.

**Affected version**-master
**Task**-3718978

2024-09-02 13:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178832.png)](https://mergebot.odoo.com/odoo/odoo/pull/178832)

2024-09-06 06:47 UTC, mash-odoo commented
> Hello @mash-odoo, Thanks for your work on this
> 
> 1. For "Little Icons" template we lose the inline text after populating
>    [35b9293d-0670-46ce-acb1-ff8435ea30cc.webm](https://github.com/user-attachments/assets/d8d6dd83-651f-45e4-b892-9784517b9a54)
> 2. Same thing for "Images Subtitle" and other template with a block on the right
> 3. Error on changing "Content Width" after populating with categories on thumbnail and cards template (didn't test all templates for this error
>    [e585b227-c0de-4789-a63c-a7163cfff5dd.webm](https://github.com/user-attachments/assets/7f39f9bd-f471-43bf-bb63-a03ae15faf0d)

Hey Lina,
First of all, much thanks for the early review! :heart: 
1. For the 1st and 2nd point, I will do some research if we can achieve that.
2. For the 3rd point, the issue is existing in the master and I don't think it's related to my task.(https://nimb.ws/bmxfegH)
So if you want, I can create the Help ticket for the same and get the bug fixed by the team. What do you say. :thinking:

2024-09-06 13:34 UTC, mash-odoo commented
Hey @livaios :smile:,
Done with the first two points mentioned above and I must say, 
the template looks more interesting compared to the previous one :heart_eyes:

2024-09-11 13:03 UTC, livaios requested changes
I'll continue the review once the crash is fixed

2024-09-12 05:32 UTC, mash-odoo commented on addons/website/views/snippets/s_mega_menu_images_subtitles.xml
> +                <div class="company_team col-12 col-lg-4 py-2">
I added it so that it would be easier for reference in future. But I guess I will just revert it as of now.

2024-09-20 14:22 UTC, chevalierv approved these changes
Hello @mash-odoo 

Thanks for your job on this task. Kudos for improving eCommerce categories' demo data!

FYI we've split templates into multiple files for clarity, and I've decided to make the templates independent from website's since they have little in common and could bring issues if the website team updates them. 

Also, we've changed the logic in JS to give customers a better experience by allowing them to toggle the eCommerce Categories Mega menu. That gives the opportunity to hover each of them in the menu to preview the eCommerce categories right away.

@robodoo r+

Have a nice day!

Thanks @livaios for the help with the review and the research in the web editor.

2024-09-20 14:22 UTC, robodoo commented
@mash-odoo @chevalierv because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-09-20 14:24 UTC, chevalierv commented
@robodoo rebase-ff

2024-09-20 14:24 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-09-21 09:37 UTC, closed without merging