[IMP] various: improve user error wording
odoo/odoo pull request #178821
Opened 2024-09-02 13:05 UTC by ppr-odoo

Before this commit error messages in odoo are boring and not much attractive to user. Those were like odoo is preventing them from doing something user want to do.

In this commit, we have modified the message to be a more friendly and humorous tone, making it less tedious and more enjoyable. It aims to enhance the user experience and ensure that interactions with any application are both pleasant and informative. As a result, the messages have been clear, short, easy to understand and informative.

task-3422664

2024-09-02 13:05 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178821.png)](https://mergebot.odoo.com/odoo/odoo/pull/178821)

2025-02-25 08:25 UTC, fpodoo requested changes

2025-02-25 08:25 UTC, fpodoo commented on addons/account/models/account_move.py
> +                    "Unbalanced move alert! The move (%(move)s) is feeling a bit unbalanced,"
Replace "Unbalanced move alert! The move (%(move)s) is feeling a bit unbalanced,"
by "The journal entry is not balanced,"

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_entry.py
> +        with self.assertRaisesRegex(UserError, 'unbalanced'), self.env.cr.savepoint():
revert this; not balanced seems better.

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_entry.py
> +        with self.assertRaisesRegex(UserError, 'unbalanced'), self.env.cr.savepoint():
revert this; not balanced seems better.

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_entry.py
> +        with self.assertRaisesRegex(UserError, 'unbalanced'), self.env.cr.savepoint():
revert this; not balanced seems better.

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_entry.py
> +        with self.assertRaisesRegex(UserError, 'unbalanced'), self.env.cr.savepoint():
revert this; not balanced seems better.

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_out_invoice.py
> +            message.body == "<p>The move could not be posted for the following reason: The 'Customer' field is required to validate the invoice.\n"
Replace "<p>The move could not be posted for the following reason: The 'Customer' field is required to validate the invoice.\n" by:
"Please provide a customer to validate the invoice.\n" (keep the second part)

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_account_move_out_invoice.py
> +            message.body == "<p>The move could not be posted for the following reason: Make sure you add a line before posting the invoice. Invoices can't be created from thin air.\n"
shorten: remove "The move could not be posted for the following reason: ", keep the rest

2025-02-25 08:25 UTC, fpodoo commented on addons/account/tests/test_company_branch.py
> +                with self.assertRaisesRegex(UserError, 'belongs to a totally different company'):
revert this change, does not bring value

2025-02-25 08:25 UTC, fpodoo commented on addons/account/wizard/account_automatic_entry_wizard.py
> +            raise UserError(_("Oops! You can't change the period/account for already reconciled items! Only the unreconciled ones are up for such an adventure!"))
Just remove "already" to shorten sligthly.

2025-02-25 08:25 UTC, fpodoo commented on addons/analytic/models/analytic_account.py
> +                raise UserError(_("No company-switching allowed for your analytic account while there are some linked analytic items around! It's a recipe for an analytical disaster!"))
Replace by "You can't change the company of an analytic account having analytic items around! It's a recipe for an analytical disaster!""

2025-02-25 08:25 UTC, fpodoo commented on addons/crm/models/crm_lead.py
> +                "Data safety alert! To prevent any disappearing act, Leads and Opportunities can only be "
Revert, it's longer but not better.

2025-02-25 08:25 UTC, fpodoo commented on addons/hr_contract/models/hr_contract.py
> +                        'No matter how stellar an employee might be, they\'re limited to just one contract at a time '
Replace both lines by:

No matter how stellar %(employee_name)s might be, you are limited to one contract per company at a time.

2025-02-25 08:25 UTC, fpodoo commented on addons/phone_validation/tools/phone_validation.py
> +                raise UserError(_("The format of the number %s is incorrect unless you're dialing aliens! Let's fix it.", number))
Replace by "The phone number %s is incorrect! Let's fix it - you are not dialing aliens."

2025-02-26 12:39 UTC, JulienAlardot commented on addons/hr_expense/models/hr_expense.py
Expense reports don't exist anymore

2025-02-26 13:05 UTC, Levizar commented on addons/account/models/account_move.py
> +                    msg = _('Please provide a customer to validate the invoice.\n %(error_message)s', error_message=e)
The message here is generic.
Are you sure it will always be because there is a missing customer?

2025-02-26 13:14 UTC, dylankiss commented on addons/account/models/account_move.py
> +                ))
This doesn't only apply to invoices, but to any journal entry. We probably want to update the message accordingly.

2025-02-26 13:14 UTC, dylankiss commented on addons/account/models/account_move.py
> +                    msg = _('Please provide a customer to validate the invoice.\n %(error_message)s', error_message=e)
This doesn't make sense. The error could be anything, not only a missing customer. Also this applies for any kind of journal entry and not only invoices.

2025-02-26 13:14 UTC, dylankiss commented on addons/account/wizard/account_automatic_entry_wizard.py
> +            raise UserError(_("Oops! You can't change the period/account for reconciled items! Only the unreconciled ones are up for such an adventure!"))
This is wrong. This error refers to the `posted` state. The one below is the one for unreconciled items.

2025-02-26 14:27 UTC, william-andre commented on addons/account/models/account_move.py
>                      move=move.display_name,
unused

2025-02-26 14:27 UTC, william-andre commented on addons/account/wizard/account_move_reversal.py
> +                'That would be like asking for a credit note for something not invoiced: it’s fishy :)'
Like for many other places: not necessarily an invoice

2025-02-26 14:30 UTC, oomsveta reviewed
Hello, thank you for your work on improving the clarity of error messages!
Here are a few comments:

2025-02-26 15:39 UTC, sdegueldre commented on addons/web/static/src/views/view_button/view_button_hook.js
> +                                cancelLabel: clickParams["close"],
What is this doing here seems unrelated to the changes? cc @aab-odoo

2025-02-26 15:48 UTC, aab-odoo commented on addons/web/static/src/views/view_button/view_button_hook.js
> +                                cancelLabel: clickParams["close"],
Indeed, good catch @sdegueldre 

@ppr-odoo could you remove this diff ? This should not be necessary for this task...

2025-02-27 07:29 UTC, ppr-odoo commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                    Are you sure you want to update <b><t t-out="props.nbValidRecords"/> records</b>?
> There's the exact same problem the line above

list_confirmation_dialog.xml

    <t t-out="nbValidRecordsText"/><br/>
    <span class="text-muted"><strong><i>Enjoy how well designed Odoo is :)

list_confirmation_dialog.js
  
    get nbValidRecordsText() {
          let message = _t("Are you sure you want to update %s records?", this.props.nbValidRecords);
          if (this.props.nbRecords !== this.props.nbValidRecords) {
              message = markup(_t(
                  "Among the %s selected records, %s are valid for this update.<br/>",
                  this.props.nbRecords,
                  this.props.nbValidRecords
              ) + message);
          }
          return message;
      }

Do you have any suggestions for this?

2025-02-27 07:34 UTC, ppr-odoo commented on odoo/orm/models.py
> +            record_msg = _lt("- {record} belongs to company {company} while {field_description} ({field_name}: {values}) belongs to another company.")
> These are not f-strings, please put back the python format specifiers (`%(thing)s`)

Okay. I restored the python format specifiers.

2025-02-27 09:43 UTC, ticodoo reviewed
Ughh, I'll finish my review when the strings stop changing. Also this new line:

 `"We can't post thin air! Add a line before posting."`

literally makes no sense

2025-02-27 09:43 UTC, ticodoo commented on addons/account/models/account_move.py
> +                        "You probably don't want to explain to your auditor that you invoiced the invisible man :)"
The "the invisible man" reference will probably be lost to people who don't have it in their culture (seems to be an English/French reference, not sure if it exists in other cultures). Also it sounds awkward used this way, maybe

"that you invoiced **an** invisible man"

would work better?

2025-02-27 09:43 UTC, ticodoo commented on addons/account/models/account_payment_term.py
> +            raise UserError(_('Uh-oh! Those payment terms are quite popular and can’t be deleted, as there are still some records referencing them. How about archiving them instead?'))
```suggestion
            raise UserError(_('Uh-oh! Those payment terms are quite popular and can’t be deleted since there are still some records referencing them. How about archiving them instead?'))
```

2025-02-27 09:43 UTC, ticodoo commented on addons/account/tests/test_account_move_in_invoice.py
> +        with self.assertRaisesRegex(UserError, r"There's nothing left to pay on those selected journal items, so no payment registration is necessary. You've got your finances under control like a bo
don't have the full context to definitely write this correctly, but I think it's supposed to be:

```suggestion
        with self.assertRaisesRegex(UserError, r"There's nothing left to pay for the selected journal items, so no payment registration is necessary. You've got your finances under control like a boss!"):
```

2025-02-27 09:43 UTC, ticodoo commented on addons/account/wizard/account_automatic_entry_wizard.py
> +            raise UserError(_("Oops! You can't change the period/account for reconciled items! Only the unreconciled ones are up for such an adventure!"))
Better English
```suggestion
            raise UserError(_("Oops! You can't change the period/account for reconciled items! Only unreconciled ones are up for an adventure like that!"))
```

2025-02-27 09:43 UTC, ticodoo commented on addons/account/wizard/account_move_reversal.py
> +                'That would be like asking for a credit note for something not invoiced: it’s fishy :)'
Better English.. I guess, it's weird to use "it's fishy" in this context + it's another of those very culture specific expressions:

```suggestion
                'That would be like asking for a credit note for something that isn't invoiced: it’s fishy behavior :)'
```

2025-03-02 09:30 UTC, ppr-odoo commented
Hello @ticodoo @william-andre @dylankiss 

I have incorporated the suggestions discussed with Jihane. Kindly let me know if anything is missing or if you have any additional suggestions

cc @xavierbol

2025-03-03 10:51 UTC, william-andre reviewed
Nothing important left for the accounting scope

2025-03-03 18:12 UTC, ticodoo reviewed
Please make sure you correctly apply all of my grammar change suggestions. I don't have time to review all of the strings again.

2025-03-03 18:12 UTC, ticodoo commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                    <span class="text-muted"><strong><i>Enjoy how well designed Odoo is :)</i></strong></span>
Uhh, this line looks _extremely_ awkward in context

![image](https://github.com/user-attachments/assets/c05abe36-24cb-4bf8-863c-7f23075af702)

Is the sentence really needed?

2025-03-03 18:12 UTC, ticodoo commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                Update All
This "Update All" button wording is a bit confusing. You're not updating _all_ the records, only the ones you have selected. So maybe this is better?
```suggestion
                Update
```

2025-03-03 18:12 UTC, ticodoo commented on addons/website/static/src/components/dialog/page_properties.xml
> +            <span class="text-warning">But before deleting it, make sure you update all links referring to it. That way, your customers won't bump into the not-so-famous 404 error page.</span>
```suggestion
        <p t-if="props.resIds.length > 1">Ready to make these web pages disappear into thin air? Are you sure?\n They will be gone forever!\n
            <span class="text-warning">But before deleting, make sure you update all links referring to them. That way, your customers won't bump into the not-so-famous 404 error page.</span>
        </p>
        <p t-else="">Ready to make this web page disappear into thin air? Are you sure?\n It will be gone forever!\n
            <span class="text-warning">But before deleting, make sure you update all links referring to it. That way, your customers won't bump into the not-so-famous 404 error page.</span>
```

2025-03-03 18:12 UTC, ticodoo commented on addons/website_slides_survey/models/survey_survey.py
> +                'The courses that need it are:\n%s',
```suggestion
                'Uh-oh! You can’t delete surveys used as a Course Certification! Otherwise, students might think diplomas just grow on trees.\n'
                'The courses that need them are:\n%s',
```

2025-03-03 18:12 UTC, ticodoo commented on odoo/orm/models.py
> +                "How about archiving the record instead?",
```suggestion
                "The troublemaker is: %(model_display)s\n"
                "Thanks to the following constraint: %(field_display)s\n"
                "How about archiving the record instead?",
```

2025-03-03 18:12 UTC, ticodoo commented on odoo/orm/models.py
> +            lines.append(_("To avoid a mess, no company crossover allowed!"))
```suggestion
            lines.append(_("To avoid a mess, no company crossover is allowed!"))
```

2025-03-03 18:14 UTC, william-andre commented
> Please make sure you correctly apply all of my grammar change suggestions. I don't have time to review all of the strings again.

Shouldn't this kind of tasks be done by native (probably from the US) speakers...?

2025-03-03 22:11 UTC, dylankiss requested changes
Some suggestions, but also some important functional issues. Please check them carefully 🙏

2025-03-03 22:11 UTC, dylankiss commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                    <span class="text-muted"><strong><i>Enjoy how well designed Odoo is :)</i></strong></span>
> Uhh, this line looks _extremely_ awkward in context

Totally agree. I don't really understand the purpose in this context 🤔

2025-03-04 09:47 UTC, ticodoo commented on addons/account/models/account_move.py
> +                    "with %(debit_total)s on the debit side and %(credit_total)s on the credit side. We need some equilibrium here!\n\n"
"we've disrupted the equilibrium" sounds a bit weird here. The comma/period change is fine. Doesn't really make a difference

2025-03-04 09:47 UTC, ticodoo commented on addons/hr_holidays/models/hr_leave.py
> +                    raise UserError(_("You can't delete a time off which is in the past"))
You're correct, it should be `that`

2025-03-04 09:47 UTC, ticodoo commented on addons/lunch/models/lunch_order.py
> +                raise ValidationError(_('Oh no! You don’t have enough money in your wallet to order that food! Contact your lunch manager to add some money in your wallet.'))
It is also for drinks. If we want to keep it generic, we can make it `your selected items`, in case someone is using the lunch app...for other non-lunch meals/things.

2025-03-10 05:40 UTC, ppr-odoo commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                    <span class="text-muted"><strong><i>Enjoy how well designed Odoo is :)</i></strong></span>
@jija2  If you have any suggestions, please do share.

2025-03-10 15:40 UTC, fpodoo commented
@robodoo r+

2025-03-10 15:40 UTC, fpodoo commented
@robodoo r+

2025-03-10 15:40 UTC, robodoo commented
This PR is already reviewed, reviewing it again is useless.

2025-04-23 14:22 UTC, ppr-odoo commented on addons/web/static/src/views/list/list_confirmation_dialog.xml
> +                    <span class="text-muted"><strong><i>Enjoy how well designed Odoo is :)</i></strong></span>
> @ppr-odoo can you remove that line?
> 
> cc @aju-odoo

:heavy_check_mark:

2025-05-05 10:10 UTC, xavierbol commented
Hello @ppr-odoo 

Can you rebase your branch? 

We will surely merge that this week.

2025-05-05 10:12 UTC, xavierbol commented on addons/web/static/src/views/list/list_confirmation_dialog.js
> +    }
Cannot we directly write those messages in the template as before? 🤔

2025-05-05 14:03 UTC, xavierbol commented on addons/web/static/src/views/list/list_confirmation_dialog.js
> +    }
Ah okay. 🙂 

Thanks for the explanation! 🙂

2025-05-09 07:06 UTC, xavierbol reviewed
robodoo r+

2025-05-11 02:35 UTC, closed without merging