[FIX] analytic: Remove account dependencies from analytic tests
odoo/odoo pull request #178930
Opened 2024-09-03 08:37 UTC by abz-odoo

Before this fix `TestAnalyticMixin` used `product.product`, `account.move`
and `account.move.line`, but `analytic` does not have these models in its
dependencies.

So this test causes `Single App` tests (when tests are run with just
concerned modules and its dependencies) to fail.

This commit adapts the tests so that they only use
`account.analytic.*` models.

original fix: https://github.com/odoo/odoo/commit/9d51fa9daee09e5467d38c5a890be7c0392d93f4

runbot error logs: https://runbot.odoo.com/web#id=74493&menu_id=405&cids=1&model=runbot.build.error&view_type=form

2024-09-03 08:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/178930.png)](https://mergebot.odoo.com/odoo/odoo/pull/178930)

2024-09-03 11:44 UTC, william-andre reviewed
I have no idea where/what the fix is, and the code style was way more readable before this autolint ~~crap~~ thing

2024-09-04 08:46 UTC, casp-odoo requested changes
Agreeing with @william-andre on this one
Could you please make the commit message explicit (it should be understandable by itself without the use of hyperlinks IMO) , and fixing the ' --> " in a separate commit ?

2024-09-05 12:40 UTC, william-andre approved these changes
@robodoo r+

2024-09-12 06:53 UTC, angv-odoo commented
Hi :) any news on this pr?

2024-09-12 07:26 UTC, adwid commented
robodoo delegate+

2024-09-12 08:49 UTC, closed without merging