[IMP] website: introduce `s_company_team_detail` snippet
odoo/odoo pull request #179007
Opened 2024-09-03 15:51 UTC by mano-odoo

wip

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-03 15:52 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179007.png)](https://mergebot.odoo.com/odoo/odoo/pull/179007)

2024-09-06 14:10 UTC, anso-odoo requested changes
Nice @mano-odoo some small comments

2024-09-06 14:23 UTC, anso-odoo commented on addons/website/views/snippets/s_company_team_detail.xml
> +                    <p class="text-muted">Chief Technical Officer (CTO)</p>
Also, nitpicking but I think it's weird to have only one role with something inside parenthesis `(CTO)`

2024-09-06 15:27 UTC, mano-odoo commented on addons/website/views/snippets/s_company_team_detail.xml
> +                        <h4 class="s_social_media_title d-none o_default_snippet_text">Social Media</h4>
I will replace with `<h5>` and leave it unresolved for tech review as I'm unsure it's risk free to remove the title (and the option). 

Maybe we should even keep the `<h4>` which come with the s_social snippet and apply a `h5-fs` class to be even more safe 🤷

2024-09-09 11:14 UTC, anso-odoo approved these changes
Neat, good job!

Just one small comment, otherwise LGTM

Let's keep an eye on the task to add keywords to the PR when we have them.

2024-09-09 11:14 UTC, anso-odoo commented on addons/website/views/snippets/s_company_team_detail.xml
> +            <p class="lead">Dedicated professionals driving our success</p>
This is usually what we do with heading + lead. It's better structured, easier to resize, you can play with paddings...
```suggestion
        <div class="col-lg-12">
            <h3>Meet our team</h3>
            <p class="lead">Dedicated professionals driving our success</p>
        </div>
```

2024-09-10 13:23 UTC, bvr-odoo requested changes
Nice snippet :+1: 
Here is my review

2024-09-10 14:51 UTC, mano-odoo commented on addons/website/views/snippets/s_company_team_detail.xml
> +                    <div class="s_social_media o_not_editable text-start" data-snippet="s_social_media" data-name="Social Media">
Indeed, let's use the `no_icon_color` by default

2024-09-11 11:17 UTC, bvr-odoo approved these changes
LGTM :+1:

2024-09-19 14:25 UTC, closed without merging