Master fixbasevat jco
odoo/odoo pull request #179078
Opened 2024-09-04 09:20 UTC by jco-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-04 09:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179078.png)](https://mergebot.odoo.com/odoo/odoo/pull/179078)

2025-01-21 17:59 UTC, jco-odoo commented
@rugo-odoo Still quite some work to do, but your ideas could be helpful already.

2025-01-23 10:05 UTC, rugo-odoo reviewed
I took a little look :eyes:

2025-01-29 14:39 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +    def _run_vat_test(self, vat_number, country_code):
I think we can remove the method entirely.  (I removed it bit by bit)

2025-01-29 14:43 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        if validation == 'none':
I thought it as a special option but indeed, you could say that if validation is Falsy you do not do validation...

2025-01-29 14:46 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +    def _simple_vat_check(self, country_code, vat_number):
Because it is the only thing it is doing (just calling the methods. Then it should be _do_vat_check maybe.  The problem is that _check_vat does more checks now...

2025-01-29 14:47 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        check_func = getattr(self, check_func_name, None) or getattr(stdnum.util.get_cc_module(country_code, 'vat'), 'is_valid', None)
Because if we implement it ourselves it is that something in the library was not to our wishes.

2025-01-29 14:48 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        if country and country in self._get_eu_prefixed_countries():
why?  Even the country and is unnecessary.  (as False will not be in there)

2025-01-29 15:13 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +    def fix_eu_vat_number(self, country_id, vat):
That is not what it is doing.  I think we can do _compact_vat_number

2025-01-30 08:54 UTC, rugo-odoo commented on addons/base_vat/models/res_partner.py
> +        if country and country in self._get_eu_prefixed_countries():
Because we are doing that just after the `browse`. `country` will always be `True`. Also it will break when we try to access the value of records that do not exist later.

2025-02-12 13:54 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        stdnum_vat_fix_func = getattr(stdnum.util.get_cc_module('hu', 'vat'), 'compact', None)
This is just formatting (compact is formatting)

2025-02-12 13:58 UTC, jco-odoo commented on odoo/addons/base/models/res_partner.py
> +                        vats.append(new_code + partner.vat)
The logic for validation or adding the prefix still seems different from the logic of checking if partners have the same VAT number...

2025-02-13 00:11 UTC, jco-odoo commented on addons/l10n_vn_edi_viettel/tests/test_edi.py
> +            'vat': '0100109106506', # TODO: check in base_vat, ...
@vin-odoo Any idea if everyone wants this - or not?  (stdnum seems to compact without)

2025-02-13 01:12 UTC, vin-odoo commented on addons/l10n_vn_edi_viettel/tests/test_edi.py
> +            'vat': '0100109106506', # TODO: check in base_vat, ...
I checked with our Vietnamese expert and got the reply:

> Hi Nicolas, the VAT in Vietnam actually doesn't have -
It is only numbers

So this change is correct :ok_hand: I could see resources online displaying the - but I guess it's not common practice so removing it should never be an issue.

2025-02-13 09:29 UTC, jco-odoo commented on addons/l10n_vn_edi_viettel/tests/test_edi.py
> +            'vat': '0100109106506', # TODO: check in base_vat, ...
Mostly if it is in format, it is optional and more of a beautification and we prefer the short form, but sometimes the - is really in handy.  We can override it to use the format...

2025-02-13 12:58 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
yes, chkl

2025-02-13 12:59 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +    'co': _lt('2131234321'),
changed to cl and co -

2025-02-13 13:00 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +                return '', code_to_check
I am not comfortable with adding an error because it will block people from extending the method if they want.

2025-02-13 13:01 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +    def _run_vat_test(self, vat_number, country_code):
removed it

2025-02-13 13:23 UTC, jco-odoo commented
@odoo/rd-security @ThomasBeckers The getattr use is the same as before where we check if we have a method in stdnum or defined one ourselves.  I did not make those methods private, but maybe we should, even if they are not immediately doing something harmful.

2025-02-13 13:24 UTC, jco-odoo commented
@rugo-odoo Ready for review

2025-02-13 13:24 UTC, jco-odoo commented on addons/l10n_vn_edi_viettel/tests/test_edi.py
> +            'vat': '0100109106506', # TODO: check in base_vat, ...
adapted like you suggested

2025-02-14 10:44 UTC, rugo-odoo requested changes

2025-02-14 12:59 UTC, jco-odoo commented on addons/l10n_eg_edi_eta/tests/test_edi_json.py
> +            self.assertEqual(serialized_string, '"ISSUER""ADDRESS""COUNTRY""EG""GOVERNATE""Cairo""REGIONCITY""Iswan""STREET""12th dec. street""BUILDINGNUMBER""10""POSTALCODE""""BRANCHID""0""NAME""bra
You know the serialized_string is a weird thing anyways

2025-02-14 13:18 UTC, jco-odoo commented on addons/account/tests/test_fiscal_position.py
> +                                           vat="ZUÑ920208KL4",
Because BE something is not a valid vat in MX.  (so it needs to fail)

2025-02-14 13:21 UTC, jco-odoo commented on addons/l10n_eg_edi_eta/tests/test_edi_json.py
> +            self.assertEqual(serialized_string, '"ISSUER""ADDRESS""COUNTRY""EG""GOVERNATE""Cairo""REGIONCITY""Iswan""STREET""12th dec. street""BUILDINGNUMBER""10""POSTALCODE""""BRANCHID""0""NAME""bra
I also checked with in the gov doc and they actually suggest to have the VAT without -

2025-02-14 13:23 UTC, jco-odoo commented on odoo/addons/base/models/res_partner.py
> +            vat, _country_code = self._run_vat_checks(partner.commercial_partner_id.country_id, partner.vat,
Not anymore because otherwise the ORM will trigger more queries.

2025-02-14 13:27 UTC, jco-odoo commented
@rugo-odoo Let me know if I can squash or if there is still something else.  (I am keeping an eye on runbot as well)

2025-02-14 14:55 UTC, william-andre commented on addons/l10n_ar/models/res_partner.py
> +            partner.vat = partner._get_id_number_sanitize()
If the number is not valid, won't it be `0`? Do we want that?

2025-02-14 14:55 UTC, william-andre commented on addons/l10n_uy/models/res_partner.py
> +                          and p.l10n_latam_identification_type_id.country_id.code == "UY" and p.vat)
```suggestion
            ci_nie_types = self.filtered(lambda p: 
                p.l10n_latam_identification_type_id.l10n_uy_dgi_code in ("1", "3")
                and p.l10n_latam_identification_type_id.country_id.code == "UY" 
                and p.vat
            )
```

2025-02-14 14:55 UTC, william-andre commented on addons/l10n_ec/models/res_partner.py
> +            it_dni = self.env.ref("l10n_ec.ec_dni", False)
We don't check RUC anymore?

2025-02-14 14:59 UTC, jco-odoo commented on addons/base_vat/__manifest__.py
> +    'version': '2.0',
Because it changed and I wanted to indicate it.

2025-02-14 15:00 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        vat_prefix, vat_number = vat[:2].upper(), vat[2:].replace(' ', '')
Before there was sometimes 'be' and sometimes "BE" and @rugo-odoo already asked to make "BE" the standard.  The reason for the upper is that is you put be0477472701 it would convert as well to BE0477472701

2025-02-14 15:14 UTC, jco-odoo commented on odoo/addons/base/models/res_partner.py
> +        return ""
So, I will try removing it simply.

2025-02-14 15:39 UTC, jco-odoo commented on addons/account/views/partner_view.xml
> +                                required="foreign_vat"
Yes, but I removed it on purpose (maybe I should mention in the commit msg)  The country group was used to detect the country_id, but this system only applies for Europe and we just already do those checks that if the country if France, you can put a Belgian VAT number.

2025-02-14 15:40 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
@chklop All devs are againt your one letter permissiveness.

2025-02-14 15:50 UTC, jco-odoo commented on addons/l10n_eg_edi_eta/tests/common.py
> +            'vat': '123456789',
to allow it to work with and without base_vat: https://sdk.invoicing.eta.gov.eg/documents/invoice-v1-0/#issuer (without - anyways)

2025-02-14 15:51 UTC, jco-odoo commented on addons/l10n_ec/models/res_partner.py
> +            it_dni = self.env.ref("l10n_ec.ec_dni", False)
Because RUC is a vat and then it will fallback on the regular base_vat check.

2025-02-14 15:53 UTC, jco-odoo commented on addons/account/models/partner.py
> -    def _inverse_foreign_vat(self):
maybe we can just keep the inverse name with foreign_vat anyways

2025-02-14 16:53 UTC, william-andre commented on addons/l10n_eg_edi_eta/tests/common.py
> +            'vat': '123456789',
why doesn't this module depend on `base_vat` then?

2025-02-14 16:54 UTC, william-andre commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
I'm not?

2025-02-14 16:55 UTC, william-andre commented on addons/account/views/partner_view.xml
> +                                required="foreign_vat"
Add tests to make sure that we don't have a regression then

2025-02-14 18:39 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
Your suggestion only allows for /

2025-02-14 21:03 UTC, jco-odoo commented
@william-andre @rugo-odoo @odoo/rd-security Ready.

2025-02-15 09:52 UTC, rugo-odoo requested changes
~~A few comments. I won't block for it as it can be discussed after the freeze if needed.~~

~~I'll let @william-andre take a last look and do the final r+.~~

~~(I'll r+ it tomorrow afternoon to be sure we get this for the freeze.)~~

Postponed.

2025-02-15 09:52 UTC, rugo-odoo commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
I don't mind one or the other but if you keep the one letter permissiveness, you should keep the comment.

2025-02-15 09:52 UTC, rugo-odoo commented on addons/account/models/partner.py
> +                              help="The tax ID of your company in the region mapped by this fiscal position.")
```suggestion
    foreign_vat = fields.Char(string="Foreign Tax ID", inverse="_inverse_foreign_vat", help="The tax ID of your company in the region mapped by this fiscal position.")
```

2025-02-15 09:52 UTC, rugo-odoo commented on addons/account/models/partner.py
> +                              help="The tax ID of your company in the region mapped by this fiscal position.")
```suggestion
    foreign_vat = fields.Char(string="Foreign Tax ID", inverse="_inverse_foreign_vat", help="The tax ID of your company in the region mapped by this fiscal position.")
```
[detail]

2025-02-15 09:52 UTC, rugo-odoo commented on addons/account/tests/test_fiscal_position.py
> +    def test_fiscal_position_different_vat_country(self):
No assert ? What behavior/error/exception/etc are we expecting ? (at least comment)

2025-02-15 09:52 UTC, rugo-odoo commented on addons/base_vat/models/res_partner.py
> +                while split_vat: # For the case where the user would accidently repeat the prefix e.g. BEBEBE0477472701
I'm not gonna block for that but I'm not sure about this. The user can also do `EBEBE` and then it won't work. Kind of weird that we try to "fix" that case but not others cases.

(We can discuss this after the freeze if needed.)

2025-02-17 07:51 UTC, xmo-odoo requested changes
@robodoo override=ci/security

2025-02-17 07:59 UTC, vin-odoo commented on addons/base_vat/models/res_partner.py
> +        return stdnum_vat_format(vat)
You mean `_format_vat_number`.
`_format_vat_number` calls the `compact` method of stdnum and not `format`; in most cases this is what we want.
For VN, `compact` removes a `-` that we may not want to see removed by default because it is in the format given by the government and has a practical use (separate the company's general VAT from the branch code).

I explained why I think we should not compact Vietnamese VAT [here](https://github.com/odoo/odoo/pull/179078#discussion_r1953626491)

2025-02-17 10:09 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +                while split_vat: # For the case where the user would accidently repeat the prefix e.g. BEBEBE0477472701
EB would not be a European country in the first place, so it would (should) fail.

2025-02-17 17:27 UTC, william-andre commented on addons/base_vat/models/res_partner.py
> +        if not vat or len(vat) == 1:
> Your suggestion only allows for /

That's the only char that is documented everywhere, including in the placeholder etc

2025-02-25 12:56 UTC, jco-odoo commented
@william-andre @rugo-odoo 

- After a discussion with @chklop , only the "/" is seen as the valid single char vat and if you put something else e.g. "-", the system will let you know to use the / to explicitly say there is no VAT. 
- We also do not want to do anything when country_id is not set. 
- Rebasing with master, the portal code changed (to not need so many l10n_website_sale modules) and testing it, I removed the fix_eu_vat_number.  (as there is no reason the e-commerce should work differently in vat validation than the backend).  Also l10n_latam_base needs to depend on portal with those changes. I tested the e-commerce validation is done correctly.

2025-02-25 12:57 UTC, jco-odoo commented
Please let me know if any doubts, because normally, this is ready to go.

2025-03-06 10:19 UTC, jco-odoo commented
@william-andre

2025-03-10 12:40 UTC, rugo-odoo requested changes

2025-03-10 12:40 UTC, rugo-odoo commented on addons/account/models/partner.py
> +        ])
```suggestion
        fp_exists = self.search_count([
            *self._check_company_domain(self.env.company),
            ('foreign_vat', '!=', False),
            ('country_id', '=', partner.country_id.id),
        ], limit=1)
```

2025-03-10 12:40 UTC, rugo-odoo commented on addons/base_vat/models/res_partner.py
> +            return vat, False
Same return ?

```suggestion
        if not vat or not country:
            return vat, False
```

2025-03-10 12:40 UTC, rugo-odoo commented on addons/base_vat/models/res_partner.py
> +                 expected_format=expected_format)
```suggestion
            expected_note = _(
                 ' \nNote: the expected format is %(expected_format)s',
                 expected_format=expected_format
            )
```
Or inline.

2025-03-10 12:40 UTC, rugo-odoo commented on addons/l10n_latam_base/models/res_partner.py
> +                                               or p.l10n_latam_identification_type_id.is_vat)
```suggestion
        partners_vat = self.filtered(lambda p:
            not p.l10n_latam_identification_type_id
            or p.l10n_latam_identification_type_id.is_vat
        )
```

2025-03-10 12:51 UTC, rugo-odoo requested changes

2025-03-10 12:51 UTC, rugo-odoo commented on addons/account/models/partner.py
> +                if not record.country_id:
We can clean up `if record.country_group_id and record.country_id:`.

2025-03-18 15:21 UTC, jco-odoo commented on addons/account/models/partner.py
> +                if not record.country_id:
I don't think so, because you can have country_id without country_group_id now.  (the country_group_id is not strictly needed for the logic)

2025-03-19 07:21 UTC, rugo-odoo commented on addons/account/models/partner.py
> +                if not record.country_id:
But we will always have a `record.country_id` because we just check it here right ? I think we can simplify some of the code here.

2025-03-19 14:23 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        stdnum_vat_fix_func = getattr(stdnum.util.get_cc_module(country_code, 'vat'), 'compact', None)
Actually, because it has been that way forever.  (so I supposed it was carefully thought about...)

From experience, this formatting is often done for reporting and it might be aesthetically pleasing to have BE 0477.47.27.01, but the dots will just annoy the user if he needs to adapt it + he is ok with seeing BE0477472701. 
Plus, if he wants it more beautifully in the report, we could have a format method there that converts the compacted one in the formatted one.  (it is done like that in certain localizations)

2025-03-19 14:23 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +        """ It is better to always have the -"""
Because the dots are annoying

2025-03-19 14:25 UTC, jco-odoo commented on addons/l10n_latam_base/__manifest__.py
> +        'portal',
There is the controllers/portal.py code which is  a recent refactor to have more code in common that is otherwise in the l10n_..._website_sale modules.  As base_vat does not depend on account anymore, we need to add the portal dependency here.

2025-03-19 14:37 UTC, jco-odoo commented on addons/base_vat/tests/test_vat_numbers.py
> -            test_partner.write({'vat': 'BE42', 'country_id': None})
Because that is exactly the point: if we do not have the country we can not validate it, because BE could be the start of a VAT number in MX e.g.

2025-03-19 15:08 UTC, william-andre commented on addons/base_vat/models/res_partner.py
> +        stdnum_vat_fix_func = getattr(stdnum.util.get_cc_module(country_code, 'vat'), 'compact', None)
Then we should always compact everywhere, and format only when needed (i.e. CL, CO, VN)

2025-03-19 15:10 UTC, william-andre commented on addons/base_vat/tests/test_vat_numbers.py
> -            test_partner.write({'vat': 'BE42', 'country_id': None})
But BE42 is not a valid VAT for France

2025-03-19 15:17 UTC, jco-odoo commented on addons/base_vat/tests/test_vat_numbers.py
> -            test_partner.write({'vat': 'BE42', 'country_id': None})
Ok, I will add a BE something that is valid for France to make the test more useful.

2025-03-20 16:08 UTC, william-andre reviewed
There is still a bunch of comments that are relevant and unresolved I think

2025-03-20 16:08 UTC, william-andre commented on addons/l10n_ro/models/res_partner.py
> +            if vat_country in ('RO', ''):
Shouldn't you also check that the format is valid?

2025-03-20 16:17 UTC, jco-odoo commented on addons/l10n_ro/models/res_partner.py
> +            if vat_country in ('RO', ''):
If it is not valid, it is not going to save, but of course, it could be saved later with another country's one.

2025-04-10 15:55 UTC, jco-odoo commented
@william-andre It looks green

2025-04-11 16:58 UTC, william-andre commented on addons/account/models/partner.py
> +    @api.onchange('country_id', 'country_group_id', 'foreign_vat')
Why the onchange on the country group?

2025-04-11 16:58 UTC, william-andre commented on addons/l10n_latam_base/models/res_partner.py
> +    @api.onchange('l10n_latam_identification_type_id')
For `onchange`, you need to repeat all the previous fields again (unlike for `depends`)

2025-04-11 16:58 UTC, william-andre commented on addons/account/models/partner.py
> +        fp_exists = self.search([
This is called in a loop, you can easily replace it with the following code in order to cache the value and search only once per company

```python
class ResCountry(models.Model):
    has_foreign_fiscal_position = fields.Boolean(compute='_compute_has_foreign_fiscal_position')

    @api.depends_context('company')
    def _compute_has_foreign_fiscal_position(self):
        for country in self:
            country.has_foreign_fiscal_position = self.env['account.fiscal.position'].search_count([
                *self._check_company_domain(self.env.company),
                ('foreign_vat', '!=', False),
                ('country_id', '=', country.id),
            ], limit=1)
```

Then you can get the value by doing `country.with_company(...).has_foreign_fiscal_position`. The `with_company` is most likely already done anyway

2025-04-11 16:58 UTC, william-andre commented on odoo/addons/base/models/res_partner.py
> +        """ Hook used for the _get_required_valid implementation (as base_vat does not depend on account anymore)"""
How do you feel about reading that "anymore" in 2 years? Wouldn't it look silly?

2025-04-15 11:44 UTC, william-andre commented on addons/base_vat/models/res_partner.py
> +            and (company.country_id in eu_countries or self.with_company(company)._eu_fiscalpos_exists())
Avoid using `ref()` for country groups
```suggestion
            and (
                'EU' in company.country_id.country_group_codes
                or self.with_company(company)._eu_fiscalpos_exists()
            )
```

2025-04-15 11:44 UTC, william-andre commented on addons/base_vat/models/res_partner.py
> +        # OVERRIDE
Not an override, it's an extension. But it's obvious anyway since we call `super()`
```suggestion
```

2025-04-15 11:44 UTC, william-andre commented on addons/account/models/partner.py
> +        return self.country_id and self.country_id.has_foreign_fiscal_position
```suggestion
        return super()._eu_fiscalpos_exists() and self.country_id.has_foreign_fiscal_position
```

2025-04-15 11:44 UTC, william-andre commented on odoo/addons/base/models/res_partner.py
> +        return False
In order to avoid this hook, you can:
* In `base_vat`:
```python
    def _get_vat_required_valid(self, company=None):
        vat_required_valid = super()._get_vat_required_valid(company=company)
        if (
            company 
            and self.with_company(company).perform_vies_validation
            and 'EU' in company.country_id.country_group_codes
        ):
            vat_required_valid = vat_required_valid and self.vies_valid
        return vat_required_valid
```
* In `account`:
```python
    def _get_vat_required_valid(self, company=None):
        vat_required_valid = super()._get_vat_required_valid(company=company)
        if (
            company 
            and self.with_company(company).perform_vies_validation
            and self.with_company(company).country_id.has_foreign_fiscal_position
        ):
            vat_required_valid = vat_required_valid and self.vies_valid
        return vat_required_valid
```

2025-04-15 11:44 UTC, william-andre commented on odoo/addons/base/models/res_partner.py
> +        )
Should this not be a country group? (then using `country_id.country_group_codes`)
It would avoid many calls to `ref`, as well as avoid relying on xmlids

2025-04-15 12:05 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +                while split_vat:  # For the case where the user would accidently repeat the prefix e.g. BEBEBE0477472701
@rugo-odoo Please check https://github.com/odoo/odoo/pull/179078/commits/3de95670b4eec2e276517ab80d51394cc5769b3a

2025-04-15 12:43 UTC, rugo-odoo commented
> @rugo-odoo Not sure what you mean by [#179078 (comment)](https://github.com/odoo/odoo/pull/179078#discussion_r2044117499) The country is required when there is a foreign_vat but in the onchanges/computes/... it can still not be filled in.

Probably for @william-andre :smile:

2025-04-15 13:16 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +                while split_vat:  # For the case where the user would accidently repeat the prefix e.g. BEBEBE0477472701
Basically because the stdnum library accepts both BE0477472701 and 0477472701.

2025-04-16 07:44 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +          validation: if vat is not valid, then it raises when validation is error and returns '' when validation is setnull
if the one in base is better, I can just delete this one.

2025-04-16 07:47 UTC, jco-odoo commented on addons/base_vat/models/res_partner.py
> +                return '', code_to_check
This is the setnull case.  And we have already asserted that setnull can be one of the values, so I am not sure what you want to assert further.  (a lots of things were changed since the original comment as well)

2025-04-16 08:14 UTC, jco-odoo commented
@william-andre I could not remove that _eu_fiscalpos_exists yet because in the vat_required method we are also checking with vies_valid and we do not have that in account, so I kind of need an extra method somewhere.  The thing is that in account we want to check an extra case where we also want to check vies_valid.  

@rugo-odoo Not sure what you meant by the assert.  But I think I was able to remove the BEBE while loop stuff.

2025-04-22 16:38 UTC, william-andre commented on odoo/addons/base/models/res_partner.py
> +        return False
Shouldn't we make account depend on `base_vat` then?

Or at least hide this in `base_setup` or something? This is really ugly to have in the minimal code...

2025-04-23 08:24 UTC, jco-odoo commented
@william-andre I made base_vat depend on account again to avoid the trouble.

2025-04-23 08:49 UTC, william-andre commented
@jco-odoo ok for the diff but the commit message needs to be updated regarding the dependency changes

2025-04-23 09:02 UTC, jco-odoo commented
@william-andre done

2025-04-23 09:46 UTC, william-andre approved these changes
@robodoo r+

2025-04-24 07:06 UTC, william-andre commented
@robodoo r+

2025-04-24 10:22 UTC, william-andre commented
@robodoo priority

2025-04-24 17:08 UTC, william-andre commented
@robodoo r+ priority

2025-04-24 19:44 UTC, robodoo commented
@jco-odoo @william-andre unable to stage: merge conflict

2025-04-24 20:32 UTC, william-andre commented
@robodoo r+ priority

2025-04-25 09:06 UTC, closed without merging