[FIX] l10n_ar: Add available document type 82
odoo/odoo pull request #179172
Opened 2024-09-04 15:37 UTC by mem-adhoc

Description of the issue/feature this PR addresses: It is necessary to be able to select document types TIQUE - FACTURA B in an invoice if the journal of the invoice has "Online Invoice" set on field "AFIP POS System".

Current behavior before PR:
User is not able to select document types TIQUE - FACTURA B in an invoice if the journal of the invoice has "Online Invoice" set on the field "AFIP POS System".

Desired behavior after PR is merged:
User is able to select document types TIQUE - FACTURA B in an invoice if the journal of the invoice has "Online Invoice" set on the field "AFIP POS System".

Task Adhoc side: 42561
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-04 15:37 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179172.png)](https://mergebot.odoo.com/odoo/odoo/pull/179172)

2024-09-04 16:34 UTC, mem-adhoc commented
@vbe-odoo Vale Hi!
I created this PR for a client request, should I make a latam task?

2024-09-04 16:38 UTC, vbe-odoo commented
> @vbe-odoo Vale Hi! I created this PR for a client request, should I make a latam task?

@mem-adhoc hello Maxi, yes, please create a latam task, and if you can please add the legal reference of the case and the use case, when and why that Doc Type is needed
Thanks!

2024-09-05 13:48 UTC, vbe-odoo commented
Hello @alialfie can you help me with the review or ping someone who can do the review of this PR?
Thanks!
cc' @mem-adhoc

2024-09-09 12:53 UTC, mem-adhoc commented
Hi @alialfie!
Could you see this PR?

2024-09-11 14:58 UTC, alialfie requested changes
Thanks for the PR! Could we maybe shorten the commit message description a bit? Seems very repetitive. Thanks!

2024-09-16 13:03 UTC, mem-adhoc commented
We close this PR for other aproach.

2024-09-16 13:03 UTC, closed without merging