[FIX] l10n_ec{_stock}: coa configuration
odoo/odoo pull request #179361
Opened 2024-09-05 12:58 UTC by guva-odoo

We were misconfiguring some accounts in ec localization:

- Sale and purchase journals default accounts
- Missing default valuation accounts on Adjustement and Production locations

opw-4127252

2024-09-05 12:59 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179361.png)](https://mergebot.odoo.com/odoo/odoo/pull/179361)

2024-09-06 10:40 UTC, guva-odoo commented on addons/l10n_ec/models/account_chart_template.py
> +
Had to do this because we don't have access to `acc_template_ref` like in `_prepare_all_journal`, there will be a proper way in 17.0

2024-09-12 07:14 UTC, guva-odoo commented
Hello @alialfie when you have time, could you review this one and the related enterprise pr? thanks🙏

2024-09-25 06:53 UTC, guva-odoo commented
Hello @alialfie little reminder for this one 🙂

2024-09-26 08:06 UTC, alialfie requested changes
Thanks for the PR and very sorry for the late review! Left some questions and nitpicks down below :)

2024-09-26 08:06 UTC, alialfie commented on addons/l10n_ec_stock/models/account_chart_template.py
> +            loss_loc = parent_location.child_ids.filtered(lambda l: l.usage == 'inventory' and l.company_id == company and l.scrap_location is False)
`raise_if_not_found=False` will return `None` if not found or an empty recordset? If the first then shouldn't this case be handled?

2024-09-26 13:53 UTC, guva-odoo commented on addons/l10n_ec/models/account_chart_template.py
> +                            'default_account_id': acc_template_ref.get(self.env.ref('l10n_ec.ec410101')).id,
Will do it for the fw port in 17 ;-)

2024-09-30 08:50 UTC, alialfie approved these changes
Thanks for the update and good catch about the walrus operator not being available in 16.0, I missed that :)

LGTM @FlorianGilbert

2024-10-07 14:00 UTC, FlorianGilbert requested changes

2024-10-16 07:57 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-10-16 08:59 UTC, closed without merging