[FIX] pos_restaurant: load floor plan for bar scenario
odoo/odoo pull request #179340
Opened 2024-09-05 12:03 UTC by vava-odoo

Before this commit, the floor plan and the tables were only loaded if the restaurant scenario was selected. Since this plan is also useful in the bar scenario, this commit split restaurant_session_floor.xml so that the floor plan is loaded in both scenarios.

Task-4155648

2024-09-05 12:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179340.png)](https://mergebot.odoo.com/odoo/odoo/pull/179340)

2024-12-20 09:02 UTC, adgu-odoo reviewed
I'm not sure changing xml files and adding xml files that are used in python in stable is a good idea. Why don't you put this in master ?

2025-01-21 15:17 UTC, vava-odoo commented on addons/pos_restaurant/models/pos_config.py
> +        new_floor = floor.copy()
Done, and rebased to master

2025-02-20 15:05 UTC, adgu-odoo commented
Sorry I didn't see that you mentioned me (don't hesitate to contact me on discord when i don't see the messages). Can you rebase once again. Since last time, a PR that separates the floor from the orders in demo was deployed so that should reduce the diff

2025-02-21 11:30 UTC, vava-odoo commented
> Sorry I didn't see that you mentioned me (don't hesitate to contact me on discord when i don't see the messages). Can you rebase once again. Since last time, a PR that separates the floor from the orders in demo was deployed so that should reduce the diff

No problem. Indeed it is more straightforward now that the floors definition is in another file. It seems to work fine like this, could you confirm? Is it ok that, in demo, the floors are shared between both pos configs? Thanks

2025-02-25 09:05 UTC, adgu-odoo requested changes

2025-02-25 09:05 UTC, adgu-odoo commented on addons/pos_restaurant/models/pos_config.py
> +                self.env.ref('pos_restaurant.floor_patio').id,
This can lead to an error if the floor_patio has been deleted but not the floor_main (it could be used or archived). We should check if both exists before using them

2025-02-25 09:05 UTC, adgu-odoo commented on addons/pos_restaurant/models/pos_config.py
> +                self.env.ref('pos_restaurant.floor_main').id,
Same

2025-02-25 09:55 UTC, adgu-odoo approved these changes

2025-02-25 09:58 UTC, vava-odoo commented
@odoo/rd-security Can I get an override here? I'm duplicating a `convert_file`  to load demo data in another PoS scenario

2025-02-25 10:41 UTC, xmo-odoo reviewed
@robodoo override=ci/security

2025-02-25 10:44 UTC, adgu-odoo commented
robodoo r+

2025-02-25 15:09 UTC, closed without merging