[FIX] mail: reload_on_attachment should not close attachment box
odoo/odoo pull request #179345
Opened 2024-09-05 12:08 UTC by jayp-odoo

**Current behavior before PR:**

prior to this PR after posting an attachment, if the attachment box was opened it closes after the reload.

**Desired behavior after PR is merged:**

this PR addresses this issue by updating the behavior to ensure that the attachment box remains open even after the reload.

task-4161477

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-05 12:08 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179345.png)](https://mergebot.odoo.com/odoo/odoo/pull/179345)

2024-09-18 08:39 UTC, maad-odoo requested changes

2024-09-18 08:39 UTC, maad-odoo commented on addons/mail/static/src/core/web/chatter.js
> +                        this.state.wasAttachmentBoxOpened;
Why do we need another state variable to check whether the attachment box is open when you already have one? Instead, you can do this:

```suggestion
                        this.state.isAttachmentBoxOpened ||
                        (this.props.isAttachmentBoxVisibleInitially &&
                            this.attachments.length > 0)
```

 what do you think ?

2024-11-19 11:18 UTC, seb-odoo commented
Hello, at first glance the fix look ok, but could you write a small test to cover it?

Thanks!

2024-12-04 08:53 UTC, jayp-odoo commented
@seb-odoo apologies for late push i have added the test please have look, thanks :bow: .

2024-12-18 09:03 UTC, jayp-odoo commented
@seb-odoo gentle reminder :bow: .

2025-01-07 17:14 UTC, seb-odoo commented on addons/mail/static/tests/web/attachment_box_tests.js
> +        const recordId = pyEnv["mail.test.simple.main.attachment"].create({});
This model is only available in `test_mail` module, either move the test or just use an available thread model (like partner form view).

2025-01-07 17:14 UTC, seb-odoo commented on addons/mail/static/tests/web/attachment_box_tests.js
> +        await contains(".o_form_sheet_bg + .o_attachment_preview");
Checking the whole DOM structure is irrelevant, just get to the point: what is visible before, what is visible after.

2025-01-07 17:14 UTC, seb-odoo commented on addons/mail/static/tests/web/attachment_box_tests.js
> +        await contains(".o-mail-AttachmentBox");
It's better if the test is asserting a change. How about the number of attachments inside the box?

2025-01-08 13:10 UTC, jayp-odoo commented on addons/test_mail/static/tests/chatter_tests.js
> +        await new Promise((resolve) => setTimeout(resolve, 100));
Hello @seb-odoo im little confused about comment 1 and 2,
> if we put `await contains(".o-mail-AttachmentBox .o-mail-AttachmentImage");` before even clicking the attachment button then it would fail because it does not exists in DOM yet.

2025-01-08 13:24 UTC, jayp-odoo commented on addons/test_mail/static/tests/chatter_tests.js
> +        await contains(".o-mail-AttachmentImage", { count: 2 });
is this doable ! to avoid artificial delay
```javascript
        ...
        await openFormView("mail.test.simple.main.attachment", recordId);
        await contains(".o_attachment_preview");
        await click("button", { text: "Send message" });
        await inputFiles(".o-mail-Composer-coreMain .o_input_file", [
            await createFile({ name: "testing.jpeg", contentType: "image/jpeg" }),
        ]);
        await click(".o-mail-Chatter-attachFiles");
        await contains(".o-mail-AttachmentBox");
        await click(".o-mail-Composer-send:enabled");
        await nextTick();
        await click("button", { text: "Send message" });
        await insertText(".o-mail-Composer-input", "test");
        await click(".o-mail-Composer-send:enabled");
        contains(".o-mail-AttachmentBox .o-mail-AttachmentImage", { count: 2 });
```

2025-01-25 17:30 UTC, jayp-odoo commented on addons/test_mail/static/tests/chatter_tests.js
> +        await contains(".o-mail-AttachmentImage", { count: 2 });
@seb-odoo Hii can you please have look thanks.

2025-02-11 15:22 UTC, seb-odoo commented on addons/test_mail/static/tests/chatter_tests.js
> +        await contains(".o-mail-AttachmentImage", { count: 2 });
It's harder to review/see if it works with a comment, could you update the code instead?
I still see a `nextTick` which hopefully we can remove.

2025-02-26 10:14 UTC, jayp-odoo commented
@seb-odoo Hi :wave: 
i have updated the code please have a look. Thanks

2025-03-14 10:00 UTC, seb-odoo approved these changes
@robodoo r+

2025-03-14 17:27 UTC, closed without merging