[FIX] pos*: improve handling of split orders in kitchen display
odoo/odoo pull request #179481
Opened 2024-09-06 11:32 UTC by parp-odoo

pos*: point_of_sale, pos_restaurant, pos_preparation_display

before this commit:
==============
- splitted order lines were not sent to the kitchen display upon splitting order
- there was no widget to distinguish split order lines.

after this commit:
==============
- ensure that split orders are sent to the preparation display if any of the original order lines are sent there.
- standardize the splitting process to ensure consistency between the order widget and the kitchen display.

task - 4114041

2024-09-06 11:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179481.png)](https://mergebot.odoo.com/odoo/odoo/pull/179481)

2024-10-14 07:19 UTC, paso-odoo requested changes

2024-12-24 14:00 UTC, adgu-odoo requested changes
Maybe this
`// for the kitchen printer we assume that everything
        // has already been sent to the kitchen before splitting
        // the bill. So we save all changes both for the old
        // order and for the new one. This is not entirely correct
        // but avoids flooding the kitchen with unnecessary orders.
        // Not sure what to do in this case.
        if (this.pos.orderPreparationCategories.size) {
            originalOrder.updateLastOrderChange();
            newOrder.updateLastOrderChange();
        }`
should be removed as we do not assume anymore the order have been sent to the kitchen prior to the split. This would allow the lines that are not selected in the split to not be considered as sent after the split if they were not.

Other than that, good job

2024-12-26 10:37 UTC, parp-odoo commented
As no new field is added, this PR is retargeted to `saas-17.4`.

2024-12-27 07:54 UTC, adgu-odoo approved these changes

2024-12-27 07:54 UTC, adgu-odoo commented
robodoo r+

2024-12-27 10:01 UTC, closed without merging