[FIX] website: fix double escaping in meta default_title
odoo/odoo pull request #179739
Opened 2024-09-10 09:06 UTC by SergeBayet

Since [1] the meta tag 'default_title' was double-escaped due to improper handling of dynamic content within the template, leading to HTML entities being escaping twice. For example, &#34; was incorrectly transformed into &amp34;

Steps to reproduce:

- Open a product and modify its name by adding a special character, such as a single quote.
- Open the "Optimize SEO" dialog.

Issue: The default title displays &#39; instead of the single quote.

This commit resolves this issue.

[1] https://github.com/odoo/odoo/commit/7c54acaebe38e47cad25d8a1bbdb430e5bad265d

task-3974334

2024-09-10 09:07 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179739.png)](https://mergebot.odoo.com/odoo/odoo/pull/179739)

2024-10-14 11:44 UTC, bvr-odoo requested changes
Thanks for the fix.
Here is some remarks/questions.
+ could you avoid creating links to PRs in the commit message =>
![image](https://github.com/user-attachments/assets/88e6eda2-9f71-4d3a-80c0-404a55858e16)

2024-10-14 11:44 UTC, bvr-odoo commented on addons/website/views/website_templates.xml
> +            <t t-set="default_title" t-translation="off" t-value="' ' + (additional_title + ' | ' if additional_title else '') + (website or res_company).name + ' '"/>
What's the point of the empty spaces at the beginning and end of `default_title`?

2024-10-14 12:29 UTC, SergeBayet commented on addons/website/views/website_templates.xml
> +            <t t-set="default_title" t-translation="off" t-value="' ' + (additional_title + ' | ' if additional_title else '') + (website or res_company).name + ' '"/>
The empty spaces are removed. And as we discuss, for the additional_title condition, it's the same behaviour than before and it makes sense.

2024-10-15 10:41 UTC, bvr-odoo approved these changes
LGTM :+1:

2024-10-15 10:44 UTC, bvr-odoo commented
@robodoo r+

2024-10-15 13:47 UTC, closed without merging