[IMP] sale: replace  `Quotation Date` in proforma invoices
odoo/odoo pull request #179839
Opened 2024-09-11 04:56 UTC by jeep-odoo

This commit replaces the  `Quotation Date` with `Issued Date` in the pro-forma invoice report to provide a more accurate label for pro-forma invoices. Conditions for displaying dates were changed accordingly.

task-4169923

2024-09-11 04:57 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179839.png)](https://mergebot.odoo.com/odoo/odoo/pull/179839)

2024-09-16 08:54 UTC, kcv-odoo requested changes

2024-09-16 08:54 UTC, kcv-odoo commented on addons/sale/report/ir_actions_report_templates.xml
> +                    <t t-set="is_proforma" t-value="env.context.get('proforma', False) or is_pro_forma"/>
You can create variable above to be able to use them at both place

2024-09-16 08:54 UTC, kcv-odoo commented on addons/sale/report/ir_actions_report_templates.xml
> +                    <strong t-elif="is_proforma">Issued Date</strong>
Do conditions like it did for layout_document_title this way you don't have to check `not is_proforma` :thinking:

2024-09-16 11:27 UTC, kcv-odoo approved these changes

2024-09-19 15:23 UTC, Feyensv approved these changes
@robodoo r+

2024-09-19 17:46 UTC, closed without merging