[IMP] website: introduce `s_company_team_card` snippet
odoo/odoo pull request #179843
Opened 2024-09-11 06:54 UTC by xlu-odoo

This commit adds the new `s_company_team_card` snippet.

task-4149441
Part-of: task-4077427

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-11 06:54 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179843.png)](https://mergebot.odoo.com/odoo/odoo/pull/179843)

2024-10-09 13:13 UTC, chgo-odoo approved these changes
LGTM @xlu-odoo 

As discussed, I pushed the changes directly on top of the branches : 

- Template name was not matching the one in `snippets.xml`
- There was an issue about a missing `o_colored_level` on the section

2024-11-05 14:09 UTC, lebl-odoo commented
Hi @xlu-odoo , not sure why I'm not able to change the number of columns on this snippet. Is it something we forgot and was it intented?

2025-02-11 10:39 UTC, chrisdt1998 commented
Hello @xlu-odoo . Is this PR ready to be reviewed? If so, please could you rebase and fix conflicts :) Thanks.

2025-02-11 10:43 UTC, chgo-odoo commented
Hello @chrisdt1998 👋 

This one is ready for review, confirmed 👍

2025-02-11 16:40 UTC, chrisdt1998 requested changes
PR already looks mostly good, just some changes to make :)

2025-02-11 16:40 UTC, chrisdt1998 commented on addons/website/views/snippets/s_company_team_card.xml
> +                            <h5 class="card-title" style="text-align: center;">Tony Fred</h5>
Based on our conversation in this [PR](https://github.com/odoo/odoo/pull/179791#pullrequestreview-2609314254), shouldn't this be an h3 with h5-fs classname?

2025-02-11 19:22 UTC, chgo-odoo commented on addons/website/views/snippets/s_company_team_card.xml
> +            <div class="row s_nb_column_fixed">
Ah damn you're right, totally missed that

2025-02-12 11:41 UTC, chgo-odoo commented
@chrisdt1998 rebased to solve the conflits since another PR was merge meanwhile.

I adapted the PR with your suggestion in the previous push, could you check again, please?

2025-02-13 08:43 UTC, chrisdt1998 commented
@chgo-odoo please could you fix the conflicts again. Reviewing it right now and aiming to get it merged by today.

2025-02-13 09:26 UTC, chrisdt1998 approved these changes
With conflicts fixed, it LGTM :+1:

2025-02-13 09:48 UTC, chgo-odoo commented on addons/website/views/snippets/s_company_team_card.xml
> +                            <h3 class="card-title h5" style="text-align: center;">Tony Fred</h3>
It should be `h5-fs` indeed, good catch

2025-02-13 11:09 UTC, qsm-odoo commented
@robodoo delegate=chrisdt1998 
@chrisdt1998

2025-02-13 16:25 UTC, closed without merging