[FIX] {sale_purchase_,}stock: decrease the SOL qty for MTO product
odoo/odoo pull request #179833
Opened 2024-09-10 20:23 UTC by prri-odoo

Problem: If there are multiple products with the MTO and Buy routes on a sale order, but the first one has enough quantity on hand for the sale order. This sets the procure_method on the associated stock move to “make_to_stock”. However, the procure_method for the second product’s stock move is set to “make_to_order”. When lowering the sale order line quantity for the second product, the negative move’s procure_method gets set to “make_to_stock” from the first product’s positive stock move. Since the procure_methods do not match, a return picking is created, instead of merging the negative move with its positive counterpart.

Purpose: To filter out the stock moves not for the procurement’s product in order for the negative move to follow the same behavior as the initial positive move.

Steps to Reproduce on Runbot:

1. In settings enable “Multi-Step Routes”
2. In Routes, unarchive the “Replenish on Order (MTO)” route
3. Create a storable product A, with the MTO and Buy routes enabled
4. Add a vendor under the Purchase tab on product A
5. Set the On Hand quantity to 10 units for product A
6. Create a storable product B, with the MTO and Buy routes enabled
7. Add a vendor under the Purchase tab on product B
8. Create and confirm a Sales Order for 1 unit of product A and 3 units of product B
9. Lower the quantity on the sale order line for product B to 1 unit
10. Observe a return picking gets created

opw-4138774

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-10 20:23 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/179833.png)](https://mergebot.odoo.com/odoo/odoo/pull/179833)

2024-09-10 20:53 UTC, prri-odoo commented
@robodoo up to saas-17.4

2024-09-10 20:53 UTC, robodoo commented
Forward-porting to 'saas-17.4'.

2024-10-07 22:09 UTC, Sehnde requested changes

2024-10-07 22:09 UTC, Sehnde commented on addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
> +            ]
You can import `Command` and do this instead:
```suggestion
            'order_line': [
                Command.create({
                    'name': product1.name,
                    'product_id': product1.id,
                    'product_uom_qty': 1,
                }),
                Command.create({
                    'name': product2.name,
                    'product_id': product2.id,
                    'product_uom_qty': 3,
                })
            ]
```
it's longer but so much easier to read.

2024-10-08 20:26 UTC, prri-odoo commented
Hi @Sehnde , thanks for the review! I've made changes based on your feedback. Can you review it again? Thanks!

2024-10-09 07:53 UTC, Sehnde requested changes

2024-10-09 07:53 UTC, Sehnde commented on addons/stock/models/stock_rule.py
> +                           procurement.values.get('sale_line_id') is None and move.product_id == procurement.product_id):
Better but still too complicated to read:
- if you place all the conditions inside one big parenthesis, you can go to next line without needing a backslash
- your `or` statement is not clear. What are its possibilities? Try to isolate it inside its own parenthesis if possible.

```py
if (condition_1
        and condition_2
        and (condition_3 or condition_4)
        and condition_5):
    do_stuff()
```

2024-10-09 12:18 UTC, Sehnde commented on addons/stock/models/stock_rule.py
> +                           procurement.values.get('sale_line_id') is None and move.product_id == procurement.product_id):
also please update your commit message with why you use those specific conditions

2024-10-09 21:02 UTC, prri-odoo commented
Hello @Sehnde, thank you for reviewing it again! I have made changes based your comments. Can you take another look and let me know what you think? Thanks!

2024-10-10 13:45 UTC, prri-odoo commented
Hi @clesgow , you are correct that both these PRs are addressing the same issue. However, #182802 does not take into account if there are multiple sale order lines for the same product and will still create the extra return in that scenario. This is why I included a check for sale_line_id as well. For example, if we have product1 and it has 5 units in stock. If we have one sale order line with 5 units and a second sale order with an additional 5 units, then lowering the quantity on the second sale order line will still generate the return. Let me know your thoughts and how you would like to proceed!

2024-10-10 14:57 UTC, Sehnde commented
Hello @prri-odoo 
There's a big issue in your PR though: you can't call `sale_line_id` in the stock module because it is not dependent on sale so `sale_line_id` may not even exist.
Even if you check first with your `if procurement.values.get('sale_line_id')`  and avoid a traceback, that's still bad practice to reference a non-existent field.
My bad for not seeing it earlier, and thanks @clesgow for pointing it out to me.

2024-10-10 15:16 UTC, prri-odoo commented
Hello @Sehnde , that makes sense. Since #182802 addresses this issue I will close this PR. Thank you for your time and insights!

2024-10-10 15:16 UTC, closed without merging