[FIX] website: Add link to Plausible report in settings
odoo/odoo pull request #180021
Opened 2024-09-12 10:58 UTC by aans-odoo

Added a "See Analytics Report" link in the Plausible settings that redirects users to the Website > Reporting > Analytics page. This enhancement provides a direct path to the analytics report, making it easier for users to access and enable the feature.

Also, improved the styling of the sibling button for consistent look.

task-3597041

2024-09-12 10:58 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180021.png)](https://mergebot.odoo.com/odoo/odoo/pull/180021)

2024-10-01 13:59 UTC, msh-odoo commented on addons/website/views/res_config_settings_views.xml
> +                                    icon="oi-arrow-right d-inline"
```suggestion
                                    icon="oi-arrow-right"
```

After doing this change you will get slight space at left side so to fix this you have to fix below widget.

2025-03-12 14:10 UTC, bvr-odoo commented
@aans-odoo could you rebase please

2025-03-12 15:29 UTC, bvr-odoo requested changes

2025-03-13 09:05 UTC, aans-odoo commented on addons/website/views/res_config_settings_views.xml
> +                            </div>
This issue occurs only in the local environment and only when running 'dev --xml'.
Otherwise, the spacing works correctly on both local and runbot.
Could you confirm which environment the above screenshot was taken from?

2025-03-13 15:26 UTC, bvr-odoo commented on addons/website/views/res_config_settings_views.xml
> +                            </div>
> This issue occurs only in the local environment and only when running 'dev --xml'. Otherwise, the spacing works correctly on both local and runbot. Could you confirm which environment the above screenshot was taken from?

Indeed,  Itested with `dev --xml`. It works without it 👍🏼

2025-03-13 15:35 UTC, bvr-odoo requested changes
LGTM but before we merge. Replace [FIX] by [IMP] in the commit title and in the PR title.

2025-03-20 10:08 UTC, aans-odoo commented
Hello @bvr-odoo, updated the PR and commit title to [IMP] 🚀

2025-03-20 10:17 UTC, bvr-odoo approved these changes
LGTM 👍🏼

2025-03-20 10:20 UTC, sobo-odoo commented
@robodoo delegate=bvr-odoo

2025-03-20 10:33 UTC, bvr-odoo commented
@robodoo r+

2025-03-20 12:55 UTC, closed without merging