[IMP] Cash_moves : clean pop-up and allow it at closing
odoo/odoo pull request #180065
Opened 2024-09-12 14:07 UTC by mobt-odoo

Description of the issue/feature this PR addresses: 

Improve UI and UX

Current behavior before PR:

Desired behavior after PR is merged:

- make 'reason' required
- remove amount on confirm button
- bring method at closing

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-12 14:07 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180065.png)](https://mergebot.odoo.com/odoo/odoo/pull/180065)

2024-09-12 14:10 UTC, vlst-odoo requested changes
don't forget to add a commit message

2024-09-17 09:33 UTC, caburj commented on addons/point_of_sale/static/tests/tours/chrome_tour.js
> +            Chrome.fillTextArea(".cash-reason", "MOBT"),
you even have a test. XD

2024-09-17 10:22 UTC, caburj approved these changes
needs rebase before it can be merged.

2024-09-18 12:10 UTC, caburj commented
robodoo r+

2024-09-18 15:48 UTC, closed without merging