[FIX] pos_{self_order, restaurant}: create missing data for
odoo/odoo pull request #180005
Opened 2024-09-12 09:38 UTC by yoba-odoo

This commit for fixing the failure of  in No demo build and Multi-build in community. Tour was introduce in https://github.com/odoo/odoo/pull/162119/commits/832fae8dc2c879cfd1dfb57cfdeb5a5c0c3eebef

2024-09-12 09:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180005.png)](https://mergebot.odoo.com/odoo/odoo/pull/180005)

2024-09-12 09:41 UTC, yoba-odoo commented
@robodoo up to saas-17.2

2024-09-12 09:41 UTC, robodoo commented
Forward-porting to 'saas-17.2'.

2024-10-10 12:09 UTC, adgu-odoo requested changes

2024-10-10 12:09 UTC, adgu-odoo commented on addons/point_of_sale/static/tests/tours/helpers/TicketScreenTourMethods.js
> +            trigger: `.ticket-screen .order-row:nth-last-child(${nRow}) > .col:nth-child(${nCol}):contains("${string}")`,
I think you do not have to change this. It does not make much sense to start counting from the end and now that only test orders are shown, you can start counting from the start without problems

2024-10-10 12:09 UTC, adgu-odoo commented on addons/pos_restaurant/static/tests/tours/TicketScreen.tour.js
> +            TicketScreen.nthColumnContains(1, 3, "1")
you thus will have to change this to something like 
```suggestion
            TicketScreen.nthColumnContains(2, 2, "Order"),
            TicketScreen.nthColumnContains(2, 3, "1"),
            TicketScreen.nthColumnContains(3, 2, "Self-Order"),
            TicketScreen.nthColumnContains(3, 3, "S"),
            TicketScreen.nthColumnContains(3, 3, "1")
```

2024-11-14 13:19 UTC, Williambraecky commented
Hi 👋 

@yoba-odoo @adgu-odoo can we please move forward with this fix? :)

Thanks

2024-11-14 13:21 UTC, yoba-odoo commented
Hey @Williambraecky 

Oups my bad. I am on it.

2024-11-14 14:05 UTC, Williambraecky commented
FYI, I started a manual no demo build to make ensure the fix is valid :)

2024-11-18 08:02 UTC, Williambraecky commented
Hello 👋 
Where are we on this? It's the last fix to make no demo green in 17.0 (see: https://runbot.odoo.com/runbot/build/70687436)

@yoba-odoo @adgu-odoo

2024-11-18 15:09 UTC, yoba-odoo commented
Hello @Williambraecky 

Of course I don't mind you can do this. I am only waiting for @adgu-odoo review if he has any other comments.

2024-11-18 18:16 UTC, Williambraecky commented
I was merged today 😇

2024-11-18 18:16 UTC, closed without merging