[FIX] point_of_sale: block sale of archived product variants
odoo/odoo pull request #180089
Opened 2024-09-12 16:03 UTC by pedrambiria

Before this commit, users could inadvertently sell an archived product variant by selecting its attribute combination in the product configurator popup.

opw-4171604

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-12 16:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180089.png)](https://mergebot.odoo.com/odoo/odoo/pull/180089)

2024-09-17 08:39 UTC, davidmonnom requested changes
Hello, isn't easier to put something like this in `_load_pos_data` of `product.product`:

```
loaded_product_tmpl_ids = list({p['product_tmpl_id'] for p in products})
products += self.env['product.product'].with_context(active_test=False).search_read([('product_tmpl_id', 'in', loaded_product_tmpl_ids), ('active', '=', False)], fields, load=False)

```

And load these archived products in the normal way ?
With this in the frontend you just need to check if `active` is set to true.

I think its ok to load archived products that are linked to a `product.template` that is still in use.

That needs less code.

2024-09-17 10:14 UTC, pedrambiria commented
@davidmonnom Hello,
Yes, it's possible to load the archived products, but it would increase the loaded data.
If you add an attribute to a product, and then remove it, the product variants for that attribute will remain as archived product variants, and could cause other issues.
Also, it needs more code to search for the product with the correct attributes.

2024-09-24 08:36 UTC, caburj approved these changes
I'm okay with this change.

robodoo r+

2024-09-24 11:13 UTC, closed without merging