[FIX] auth_password_policy_signup: error on reset page
odoo/odoo pull request #180139
Opened 2024-09-13 06:36 UTC by fmdl

Description of the issue/feature this PR addresses:
On safari mobile go to https://68150873-16-0-all.runbot224.odoo.com/web/reset_password A javascript error appear.
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/511048e6-c6f9-41fa-ba38-7ebbebf8260c">

@Whenrow 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-13 06:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180139.png)](https://mergebot.odoo.com/odoo/odoo/pull/180139)

2024-09-13 06:37 UTC, fmdl commented
OPW #4184038

2024-09-13 13:44 UTC, Whenrow commented
cc @odoo/rd-framework-js

2024-09-16 08:01 UTC, pparidans requested changes
Thanks for the report and the PR.
Please check the comment below for the fix.

Can I also ask you to rephrase a bit your commit description : adding the full steps to reproduce, a small description of the error (which is not specific to Safari Mobile, btw), the corresponding ticket's ID (with the form `opw-{ID}`).

2024-09-20 20:19 UTC, fmdl commented
@pparidans updated

2024-10-01 05:05 UTC, fmdl commented
ping @pparidans

2024-10-09 09:47 UTC, pparidans approved these changes
@robodoo r+ squash

2024-10-09 09:47 UTC, robodoo commented
Merge method set to squash.

2024-10-09 13:09 UTC, closed without merging