[IMP] website: reintroduce double events in `s_timeline`
odoo/odoo pull request #180351
Opened 2024-09-16 15:09 UTC by Brieuc-brd

Since commit 48545a60ddc4a50bc792318ed6cd20cfb20b5c55, we can no longer have two events in the same line.

This commit reintroduces double events in a row to increase layout possibilities for the user.

This commit also removes primary buttons to simplify the layout.

task-4189342
Part of task-3619705

| Header | Header |
|--------|--------|
| ![Capture d’écran 2024-09-16 à 17 08 54](https://github.com/user-attachments/assets/014c8ff3-8d88-4793-af1b-8d61ecf4c886) | ![Capture d’écran 2024-09-16 à 17 30 37](https://github.com/user-attachments/assets/831e0d86-03c1-452c-9214-f8b931fc350d) |

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-16 15:09 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180351.png)](https://mergebot.odoo.com/odoo/odoo/pull/180351)

2024-09-16 15:18 UTC, Brieuc-brd commented
Hey @sobo-odoo 👋 
We need to reintroduce the "double events" in `s_timeline` snippet. Could you have a look at it ?
Thanks in advance ! 

cc. @stefanorigano

2024-09-16 15:25 UTC, stefanorigano commented
@Brieuc-brd , note: waiting confirmation for the eventual removal the of buttons.
I'll keep you posted.

2024-09-16 15:26 UTC, stefanorigano commented
@Brieuc-brd , confirmed, we have to remove the buttons. Sorry for the hassle.

2024-09-16 15:31 UTC, Brieuc-brd commented
@stefanorigano Done ✅ 
Is it ok for you ?

2024-09-16 15:49 UTC, stefanorigano commented
Hei @Brieuc-brd , thanks. Let me say that I don't really agree with these changes... having 2 elements in the same row really overcomplicate the edition... moreover now we have new snippets covering the scenario described...

Still, it has been asked specifically eand multiple times, I may miss something here 🤷🏻‍♂️
Thanks for your work, "LGTM" 👍 🙂

2024-09-17 12:30 UTC, sobo-odoo requested changes
Here is my review :slightly_smiling_face: Some issues (the same ones as last time which made us drop the "two event per line" in the end) but most of them can be ignored, except one (see review comments) :slightly_smiling_face:

2024-09-17 12:30 UTC, sobo-odoo commented on addons/website/static/src/snippets/s_timeline/options.js
> +        const timelineCardsEls = timelineRowEl.querySelectorAll('.s_timeline_card');
Nitpick: rename it as `timelineCardEls` (without the "s" at the end of "Cards") :slightly_smiling_face:

2024-09-17 14:18 UTC, Brieuc-brd commented on addons/website/views/snippets/s_timeline.xml
> +                <div class="s_timeline_row position-relative d-flex gap-md-5 flex-column flex-md-row pb-4" data-name="Milestone">
As discussed I've updated the code 👍  : 
- https://github.com/odoo/odoo/compare/901312ebeb778430946b88ce540a9c641d6751e5..b139645fe5a543f6f0c900eaf7c697a021429df9
- https://github.com/odoo/odoo/compare/b139645fe5a543f6f0c900eaf7c697a021429df9..a6feed46616cc2aa0fefb3b853fa27e9586f03fa

Thanks again for your help !

2024-09-18 06:41 UTC, Brieuc-brd commented
Thanks for your review @sobo-odoo :)
I've updated the branch, could you take a look at it ? :)

2024-09-18 11:23 UTC, sobo-odoo approved these changes
It's okay with me :wink: 

@robodoo r+

2024-09-18 14:27 UTC, closed without merging