[IMP] hr_holidays: Update "by type" report to separate between `Time Off Requests` and `Allocations`.
odoo/odoo pull request #180331
Opened 2024-09-16 13:15 UTC by abdelrahmankhaledg

The "by type" report in the time off app is not clear. There are positive values representing allocated days and negative values representing time off. These values are summed together in reporting which causes inability to compare between time off types.

These changes:
1. Split allocations from time off requests by using stacked bar chart. Allocations will have their own stack and time 
off requests will have a seperate stack.

  2. Adjusts the values representing time off to be positive.

This will enable users to use the reporting features and to compare between time off types in terms of number of allocated days and number of hours taken as leaves.

task-4014251

2024-09-16 13:15 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180331.png)](https://mergebot.odoo.com/odoo/odoo/pull/180331)

2024-10-29 13:21 UTC, mepe-odoo requested changes
Nice job :+1: 
Implement new behavior with an external library is not easy :D

2024-10-30 12:29 UTC, mepe-odoo commented on addons/hr_holidays/static/src/views/graph/hr_holidays_graph_renderer.js
> +        // Balance represents the leave balance = Allocation - Time Off.
but the word balance is enough to understand i think :)

2024-10-30 12:32 UTC, mepe-odoo commented on addons/hr_holidays/report/hr_leave_report.py
> +                    request.id as leave_id,
oh good to know thanks :+1:

2024-10-30 12:32 UTC, mepe-odoo commented on addons/hr_holidays/static/src/views/graph/hr_holidays_graph_controller.xml
don't forget the empty line at the end of your file :)

2024-10-30 12:36 UTC, mepe-odoo commented on addons/hr_holidays/static/src/views/graph/hr_holidays_graph_renderer.js
> +            'stack': "Balance",
```suggestion
        let balanceDataset = {
            'trueLabels': dataset.trueLabels,
            'stack': "Balance",
```

2024-10-31 11:55 UTC, mepe-odoo commented on addons/hr_holidays/static/src/views/graph/hr_holidays_graph_renderer.js
> +            dataset.data = dataset.data.map(datapoint => -datapoint);
I don't know :/ I don't know what we want; but you're right if we change it it will be a huge change.

2024-10-31 11:56 UTC, mepe-odoo approved these changes

2024-11-19 14:21 UTC, mepe-odoo approved these changes
Nice work :+1: 
You have one file without an empty line at the end; don't forget to change it ;)

2024-12-02 09:36 UTC, tivisse commented on addons/hr_holidays/static/src/views/graph/hr_holidays_graph_renderer.js
> +                dataset.stack = "Time Off";
I don't think this will work on a non English database.

2024-12-04 08:48 UTC, tivisse commented
@robodoo r+

2024-12-04 08:48 UTC, robodoo commented
@abdelrahmankhaledg @tivisse because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-12-04 08:48 UTC, tivisse commented
@robodoo rebase-ff

2024-12-04 08:48 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-12-05 17:44 UTC, closed without merging