[FIX] website_sale_loyalty: factor shipping reward into amount_delivery
odoo/odoo pull request #180347
Opened 2024-09-16 14:56 UTC by lvsz

Versions
--------
- 17.0+

Steps
-----
1. Create a coupon with free shipping reward;
2. in eCommerce, add product to cart & apply coupon.

Issue
-----
In the overview on the right, the "Delivery" line displays the full delivery cost, though the "Total" is displayed correctly.

Cause
-----
The delivery cost displayed is from `website_sale`'s `amount_delivery` field. Currently, it does not factor in any rewards of the `shipping` type.

Commit 9c401632bd9a had the controller handle this in `website_sale_loyalty_delivery`, but this somehow got lost when forward porting it to versions where this module got merged with `website_sale_loyalty`.

Solution
--------
Add a `new_amount_delivery_discounted` handler to the controller, which subtracts shipping discount from the `amount_delivery` value displayed on checkout.

Also removes an `else` that prevented `eWallet` from updating as intended by e08449e42a01 if a shipping reward is applied.

opw-4150258

2024-09-16 14:56 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180347.png)](https://mergebot.odoo.com/odoo/odoo/pull/180347)

2024-09-24 09:01 UTC, Demesmaeker requested changes
Hello @lvsz :duck: 

Thanks for the test, can I ask you to check again both the delivery price and the shipping price reward for the second delivery method? Should be good to go after that ^^

2024-09-24 09:15 UTC, lvsz commented
> can I ask you to check again both the delivery price and the shipping price reward for the second delivery method?

Sure, done :+1:

2024-09-24 09:33 UTC, Demesmaeker approved these changes
Thanks a lot @lvsz :duck: 

@robodoo r+

2024-09-24 15:19 UTC, closed without merging