[FIX] account: Tax report lines grouping
odoo/odoo pull request #180460
Opened 2024-09-17 12:50 UTC by agr-odoo

Open POS Session
Add a product with tax
Checkout and Pay order
Close POS Session

Now create an invoice, with same product and tax
Confirm

Open Tax Reports
Two entries will be present, with correct amounts
Activate 'Group by: Account>Tax' option

Issue: Base line amount is not correct
This occurs because in the tax details query we group by display_type of
the lines. This was done in https://github.com/odoo/enterprise/commit/d302b2091231bc5314cc42463b6294fc5a07d37d
to know when we are dealing with a rounding line but in the FW port to
Odoo 16 the code was changed to group by display_type.
When POS creates closing session move, lines will not have the proper
display_type assigned, so for example, tax lines will have display_type
'product'.

The invoice tax line will have the correct display_type 'tax', so the
tax report engine does not merge correctly the results of the query

A solution is to restore the original behavior by separating only rounding
lines.

opw-4125791

2024-09-17 12:52 UTC, agr-odoo commented
@oco-odoo 
I guess we could patch the POS too in order to have the correct display_type, but that won't fix all the lines already created

2024-09-18 12:46 UTC, agr-odoo commented
Enterprise PR https://github.com/odoo/enterprise/pull/70169

2024-09-20 09:24 UTC, oco-odoo requested changes
I fear such a fix could have crazy side effects :/ 

As you said, the problem rather seems to be in what POS creates ; let's fix that. Existing databases will need tech support, indeed, but only few people use the grouped reports ; I guess the time it took for this bug to be reported is a good hint of that.

2024-09-20 10:10 UTC, agr-odoo commented
Closing in favor of https://github.com/odoo/odoo/pull/180864
(Not re-using this one in order to keep it as reference)

2024-09-20 10:10 UTC, closed without merging