[FIX] base: 17.0 lang lao fix date
odoo/odoo pull request #180481
Opened 2024-09-17 14:06 UTC by baptiste-n42

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-17 14:06 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180481.png)](https://mergebot.odoo.com/odoo/odoo/pull/180481)

2024-09-17 14:14 UTC, RicGR98 requested changes
Thanks for the PR :)

It looks like a big diff (probably your editor ?) just to modify the `y` to `Y`. Could you limit your diff to just the Lao language line ?

Thanks ;)

2024-09-17 14:16 UTC, baptiste-n42 commented
Oups. Thanks for noticing, I just updated it with the right editor. :facepalm:

2024-09-18 05:47 UTC, robodoo commented
@baptiste-n42 @xmo-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-09-18 05:49 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-09-18 06:25 UTC, robodoo commented
@baptiste-n42 @xmo-odoo staging failed: ci/runbot on 31d66b420f758d67aa24609cef4b6ca7e423aed6 (view more at https://runbot.odoo.com/runbot/build/68366290)

2024-09-18 06:39 UTC, robodoo commented
This PR is already reviewed, it's in error, you might want to `retry` it instead (if you have already confirmed the error is not legitimate).

2024-09-18 07:52 UTC, closed without merging