[FIX] base: fix traceback when user removes all devices in preferences
odoo/odoo pull request #180612
Opened 2024-09-18 12:06 UTC by alsh-odoo

Currently, a traceback occurs when the user tries to `log out from all devices`.

To reproduce this issue:

1) Open the `Preferences` from the profile
2) Click `Log out from all devices` from the Account Security page 
3) Give the current password and click `Log out from all devices`

Error:- "AttributeError: 'bool' object has no attribute 'strip'"

When the user clicks on the `Log out from all devices`, the `revoke_all_devices` method triggers in which the `_check_identity` method is triggered.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L2000-L2002

But here in the `_check_identity()` current password is set to False. This leads to a traceback from the `_change_password` method.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L1982-L1988

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L977-L978

Note:-
I don't know the scope of setting the password as False, 
So instead of removing that line, I passed the current password as a variable.

sentry-5867375557

2024-09-19 09:40 UTC, maan-odoo commented
The current solution is good, but IMO it is not an actual problem.

Recently added code with https://github.com/odoo/odoo/pull/179866 in 15.0 is always set `self.password = False` in the `run_check` method.

In 17.0 changes with https://github.com/odoo/odoo/commit/82985296e19ae4bb80c0ede1edce1b192e8c1b86 is divide `run_check` into two part first method `_check_identity` which is just check the credential is correct or not and secong `run_check` which call first `_check_identity` to check identity and set 'self.password = False` and another code.

But Forword Port of https://github.com/odoo/odoo/pull/179866 in 17.0 (https://github.com/odoo/odoo/pull/179960) was added code that set `self.password = False` insignt `_check_identity` method.  IMO, this behaviour is wrong because it is just checking if the credentials are correct or not.

@kmagusiak, @beledouxdenis 
What do you think about it?

2024-09-19 09:44 UTC, maan-odoo commented
Should we use `with contextlib.suppress(UserError)` if we want to always set `self.password = False` in the `run_check` method?

2024-09-19 11:33 UTC, kmagusiak commented
If the issue is about calling strip on False, just add a check in that place since a char field can return either a str or False.

2024-09-19 11:44 UTC, maan-odoo commented
But is it ok to set password as False when we just check credentials?

2024-09-19 11:49 UTC, alsh-odoo commented
Also the issue is not only about calling strip method with password as False .

It leads to a user error if there is no password. After surpassing that it set the password as False of there is no psswd

REF:- https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L979-L988

2024-09-19 16:32 UTC, beledouxdenis approved these changes
It's ok.

Though add a unit test to cover this `revoke_all_devices` feature. It is completely not covered in the unit tests currently and it would have caught this bug.

cc @flvr-odoo

2024-09-20 11:43 UTC, beledouxdenis requested changes

2024-09-20 11:43 UTC, beledouxdenis commented on odoo/addons/base/tests/test_res_users.py
> +        self.assertFalse(user_identity_check.exists())
You test that you fix the bug but you do not really test the feature itself, which is invalidationg all the sessions of the user.

As there is no test testing the feature, it's a good opportunity to do it.

In the end, applying the above comment + testing the feature, here is what I did:

```diff
diff --git a/odoo/addons/base/tests/test_res_users.py b/odoo/addons/base/tests/test_res_users.py
index fe936e071e90..89d67ec83765 100644
--- a/odoo/addons/base/tests/test_res_users.py
+++ b/odoo/addons/base/tests/test_res_users.py
@@ -7,6 +7,7 @@ from unittest.mock import patch
 from odoo import SUPERUSER_ID
 from odoo.addons.base.models.res_users import is_selection_groups, get_selection_groups, name_selection_groups
 from odoo.exceptions import UserError
+from odoo.service import security
 from odoo.tests.common import Form, TransactionCase, new_test_user, tagged, HttpCase, users
 from odoo.tools import mute_logger

@@ -536,25 +537,35 @@ class TestUsersTweaks(TransactionCase):
             user.write({'active': True})


+@tagged('post_install', '-at_install')
 class TestUsersIdentitycheck(HttpCase):

-    @classmethod
-    def setUpClass(self):
-        super().setUpClass()
-        self.user_internal = self.env['res.users'].create({
-            'name': 'Internal',
-            'login': 'user_internal',
-            'password': 'admin',
-            'groups_id': [self.env.ref('base.group_user').id],
-        })
-
-    @users('user_internal')
+    @users('admin')
     def test_revoke_all_devices(self):
         """
         Test to check the revoke all devices by changing the current password as a new password
         """
-        user_identity_check = self.env['res.users.identitycheck'].create({'request': True, 'password': 'admin'})
-        self.assertEqual(user_identity_check.password, 'admin')
+        # Create a session
+        session = self.authenticate('admin', 'admin')
+        # Test the session is valid
+        self.assertTrue(security.check_session(session, self.env))
+        # Valid session -> not redirected from /web to /web/login
+        self.assertTrue(self.url_open('/web').url.endswith('/web'))
+
+        # The user clicks the button logout from all devices from his profile
+        action = self.env.user.action_revoke_all_devices()
+        # The form of the wizard opens with a new record
+        form = Form(self.env[action['res_model']].create({}), action['view_id'])
+        # The user fills his password
+        form.password = 'admin'
+        # The user clicks the button "Log out from all devices", which triggers a save then a call to the button method
+        user_identity_check = form.save()
         user_identity_check.revoke_all_devices()
-        # After revoking all the devices user_identity_check data will be unlinked
+
+        # Test the session is no longer valid
+        self.assertFalse(security.check_session(session, self.env))
+        # Invalid session -> redirected from /web to /web/login
+        self.assertTrue(self.url_open('/web').url.endswith('/web/login'))
+
+        # In addition, the wizard must have been deleted
         self.assertFalse(user_identity_check.exists())
```

2024-09-20 13:12 UTC, alsh-odoo commented
Ola @beledouxdenis 

Thanks for reviewing the PR and the testcase

Added one more line in test case of changing the password to 8 characters for bypass the exception

`Passwords must have at least 8 characters, got 5.`

Please review

2024-09-20 18:11 UTC, beledouxdenis commented
robodoo r+

Thank you for your work 👌

2024-09-20 20:26 UTC, closed without merging