[FIX] base_import: clear _dirty from cache on dryrun
odoo/odoo pull request #180708
Opened 2024-09-19 08:55 UTC by ethanrobv

**Current behavior:**
Attempting to test the import of a new CoA on a fresh DB will result in a query actually getting executed and an error propagated up to the UI, however if you were to instead actually do the import, it would work and everything would be correct.

**Expected behavior:**
If the actual import would work, the 'Test' button should indicate the same.

**Steps to reproduce:**
*From a fresh DB with account_accountant*
1. Go to the Chart of Accounts view

2. Import a new CoA

3. Download the template offerred, upload it

4. Click 'Test' -> see the FKEY error

**Cause of the issue:**
Though we normally clear caches on a dryrun (when 'Test' is clicked) in this instance, the modified values are still marked as dirty in the registry cache, so later when the request is getting resolved and a flush() happens to be called, the changes are written and a query actually executed to write the account move which *would* be created by the import to a field in the current company record -> the account move doesn't exist, so we get the FKEY psql error.

**Fix:**
Clear the `_dirty` values from the cache in the same block where the caches themselves are cleared.

opw-4103686

2024-09-19 08:55 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180708.png)](https://mergebot.odoo.com/odoo/odoo/pull/180708)

2024-09-19 14:01 UTC, nle-odoo approved these changes
could be okay, a little odd that it's necessary just for chart of account

checking in detail, what is in self.env.cache._dirty is:

```py
defaultdict(<class 'odoo.tools.misc.OrderedSet'>, {
    'res.company.account_opening_move_id': OrderedSet([1]), 
    'res.company.write_uid': OrderedSet([1]), 
    'res.company.write_date': OrderedSet([1])
})
```

and it seems that `account_opening_move_id` is written in the method `account.account()._load_precommit_update_opening_move` (a method run before committing the transaction) after the current transaction is flushed, and is adding itself things to be flushed.

Testing by adding:

```py
self._cr.flush()
```
it seems to also work (and maybe could catch an issue in the precommit hook), but this or the current commit might be ok. I don't know how to do this the cleanest, someone from ORM team will probably know.

2024-09-20 10:03 UTC, kmagusiak commented on addons/base_import/models/base_import.py
> +                self.env.cache._dirty.clear()
I think you should clear everything, not just dirty records.
```suggestion
                self.env.clear()
```

2024-09-23 09:57 UTC, kmagusiak approved these changes

2024-09-24 09:44 UTC, rco-odoo approved these changes
@robodoo r+

2024-09-24 09:46 UTC, rco-odoo commented
@robodoo r-

2024-09-24 09:48 UTC, rco-odoo commented
I am wondering about those remaining dirty fields.
Not flushing them may actually hide some potential error, like the violation of a unique constraint.

2024-09-24 10:00 UTC, rco-odoo commented
~~I don't get the explanation with the precommit.~~
The method `load()` actually uses a `Savepoint` object, and when that object is closed, the precommit hooks are executed.
That's where the dirty fields come from.

2024-09-24 10:02 UTC, rco-odoo commented
Note that the precommit hook is expected to flush its changes!
Otherwise, such a hook would never actually complete in a regular request.
I strongly recommend to fix the precommit instead.

2024-09-24 10:03 UTC, rco-odoo requested changes
This only fixes a symptom.
Please fix the root cause (precommit hook) instead.

2024-09-24 11:35 UTC, rco-odoo commented on addons/account/models/account_account.py
> +        self._cr.flush()
You shouldn't flush the cursor, since it will recursively run the precommits.
```suggestion
        self.env.flush_all()
```

2024-09-24 12:14 UTC, rco-odoo approved these changes
Thanks for the quick response.
This looks like the right fix to me.

2024-09-24 15:19 UTC, closed without merging