[IMP] point_of_sale, pos_restaurant: improve split order name
odoo/odoo pull request #180729
Opened 2024-09-19 11:15 UTC by AH-Yussef

when an order is split from:
- a table, the new order name is (table number + char starting from b and increasing with more splits)
- a floating order, the new order name is (floating order name + char starting from b and increasing with more splits)

2024-09-19 11:15 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/180729.png)](https://mergebot.odoo.com/odoo/odoo/pull/180729)

2024-09-19 11:42 UTC, vlst-odoo requested changes

2024-09-19 11:42 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
> +        };
```suggestion
const sort_by_last_char = (a, b) => a.slice(-1).localeCompare(b.slice(-1));
```

2024-09-19 11:42 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
> +        };
```suggestion
        const filter_orders = (order) => order.getOrderName().slice(0, -1) === name
        };
```

2024-09-19 11:42 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
> +    }
```js
_getLatestOrderNameStartingWith(name) {
  return this.pos.get_open_orders()
    .map((order) => order.getOrderName())
    .filter((orderName) => orderName.slice(0, -1) === name)
    .sort((a, b) => a.slice(-1).localeCompare(b.slice(-1)))
    .at(-1) || name
}
```

2024-09-19 11:42 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
> +    _getNewOrderName(originalOrderName) {
shouldn't we have upper case letters in this case ? `6A`, `6B`, instead of `6a`, `6b`

2024-09-19 11:43 UTC, vlst-odoo commented on addons/pos_restaurant/static/src/overrides/models/pos_order.js
> +    },
inline this code in `split_bill_screen.js`. It looks like it's only needed there.

2024-09-19 16:13 UTC, vlst-odoo commented on addons/pos_restaurant/static/tests/tours/utils/chrome.js
> +export function activeTableOrOrderrIs(label) {
typo

2024-09-20 10:24 UTC, caburj commented
Hi @vlst-odoo @AH-Yussef. Can I trust you to merge this PR only after the following PR is merged?

https://github.com/odoo/odoo/pull/175535/files

2024-09-24 20:41 UTC, closed without merging