Master allow animated snippets within snippets modal chgo
odoo/odoo pull request #181087
Opened 2024-09-23 17:03 UTC by chgo-odoo

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-23 17:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181087.png)](https://mergebot.odoo.com/odoo/odoo/pull/181087)

2024-09-30 06:52 UTC, chgo-odoo commented
Hello @bvr-odoo, could you eventually have a look at this one, please, as you worked on the snippets modal, please?

Huge thanks 🙏

2024-09-30 07:51 UTC, bvr-odoo requested changes
Hello @chgo-odoo , thanks for the fix :+1:  Here is some remarks :wink: 

- > This is due to the fact that the `o_animate` class sets
a `visibility: collapse` by default

I see `visibility: hidden` in the `o_animate` rules but not `visibility: collapse` :thinking:

- Souldn't we handle the case for page preview ? cc @bso-odoo

2024-09-30 07:51 UTC, bvr-odoo commented on addons/web_editor/static/src/scss/wysiwyg_snippets.scss
> +                visibility: visible;
I would also add `animation-name: none;` here. Indeed, the animation could apply an opacity or a transform that would make the animated element not visible as well.

2024-10-01 07:25 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-10-01 07:28 UTC, chgo-odoo commented
@bvr-odoo I added your suggestion, for the second point, I guess you were referring to the new page templates?

As we did not add animated snippet there yet, maybe this can be done later? But if a user can add some animated snippet there, I can handle it as well, it's only about a selector. Tell me what you think 🙂

2024-10-01 07:45 UTC, bvr-odoo commented
> @bvr-odoo I added your suggestion, for the second point, I guess you were referring to the new page templates?
> 
> As we did not add animated snippet there yet, maybe this can be done later? But if a user can add some animated snippet there, I can handle it as well, it's only about a selector. Tell me what you think 🙂

@bso-odoo what do you think ?

2024-10-01 08:16 UTC, bso-odoo commented
> > @bvr-odoo I added your suggestion, for the second point, I guess you were referring to the new page templates?
> > As we did not add animated snippet there yet, maybe this can be done later? But if a user can add some animated snippet there, I can handle it as well, it's only about a selector. Tell me what you think 🙂
> 
> @bso-odoo what do you think ?

Well, you could have animated snippets in your page, make it usable as custom template in the page properties... and then you'll have the issue.

2024-10-01 08:19 UTC, bso-odoo commented
Note that I guess the CSS could be added inside the hard-coded string that addresses other new page preview issues. <https://github.com/odoo/odoo/blob/master/addons/website/static/src/components/dialog/add_page_dialog.js#L159>

2024-10-01 14:01 UTC, chgo-odoo commented
Thanks @bso-odoo, is this what you were refering to ?

2024-10-01 14:04 UTC, bso-odoo commented
> Thanks @bso-odoo, is this what you were refering to ?

Yes, and it seems to work. Thanks !

2024-10-07 07:04 UTC, chgo-odoo commented
Hello @bvr-odoo 👋 

This can still target `18.0` if I'm right as we only play with CSS and JavaScript. If yes, could we move this forward?

Thanks !

2024-10-07 07:45 UTC, bvr-odoo requested changes
Hello @chgo-odoo ..
The code is good for me :+1:  but about the commit message:
- Missing website in the module list
- IMO, it is a [FIX] and not an [IMP]

2024-10-07 08:24 UTC, chgo-odoo commented
Thanks @bvr-odoo, I adapted the commit title as suggested !

2024-10-07 11:07 UTC, bvr-odoo approved these changes
LGTM :+1: Thanks @chgo-odoo

2024-10-07 11:07 UTC, bvr-odoo commented
@robodoo r+

2024-10-07 12:28 UTC, closed without merging