[FIX] website: fix `s_opening_hours` background image
odoo/odoo pull request #181170
Opened 2024-09-24 10:49 UTC by xlu-odoo

This commit addresses a usability issue in the s_opening_hours snippet.

Previously, the background image was applied through a grid item, which made it difficult to edit the image, adjust the snippet's height or padding, and even delete the snippet itself.

With this fix, the background image is now applied directly to the section as a background image, and adjustments have been made to grid items. These changes improve the ease of editing and enhance the overall user experience.

task-4207030
Part-of: task-4077427

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-24 10:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181170.png)](https://mergebot.odoo.com/odoo/odoo/pull/181170)

2024-09-24 10:53 UTC, anso-odoo approved these changes
LGTM

2024-10-10 10:37 UTC, xlu-odoo commented
@odoo/rd-website can you please check this PR and eventually merge?

2024-10-29 13:26 UTC, xlu-odoo commented
@odoo/rd-website reminder

2024-10-29 17:30 UTC, qsm-odoo requested changes
Using a background-image instead seems nice but I think you may want to review the mobile mode with the default image, it's not perfect. Maybe it's just about using a new image? Don't know.

2024-11-05 09:40 UTC, xlu-odoo commented
> Using a background-image instead seems nice but I think you may want to review the mobile mode with the default image, it's not perfect. Maybe it's just about using a new image? Don't know.

Hello Quentin 👋 , thanks for reviewing this one.

You're right—it didn’t look great on mobile. I’ve updated it with a different image (popup snippet image fits well imo - default and others themes). I also had to adjust one of the themes (artists) that had a customization. Removed an XPath. (new related PR here: https://github.com/odoo/design-themes/pull/1004 )

2024-11-05 10:53 UTC, qsm-odoo requested changes
I tested the branch again, IMO there is a problem. The snippet use grid mode... but now that there is a huge padding at the top by default, it's an area where you cannot move items into. 

![image](https://github.com/user-attachments/assets/616f9cb6-3ea7-42a6-bae1-148c91707c42)

The user can of course change that, remove the padding, increase the grid etc. But having that by default is weird to me. @lebl-odoo That would not seem strange to you?

Not sure what the solution is though. Increasing the grid instead of using padding would work, but then in mobile... you won't see the background image. You could an extra image only visible in mobile... but then the UX is becoming weird (having one desktop image and a mobile image to configure by default without the user knowing).

There is this solution, which I think is more understandable for the user by default:
- Increase the grid height instead of using padding
- Add an empty grid element covering the whole empty top area
- Add some line breaks in that empty grid element, to act as padding in mobile

You then get this kind of result (visually the same):
![image](https://github.com/user-attachments/assets/ef092c6a-4bbe-408e-b3af-14d52ac842e8)
![image](https://github.com/user-attachments/assets/1bf154fe-f8ef-466c-b02c-cd31263557af)
... but it's kinda ugly to:
- have an empty element (although, by default this allows the user to quickly type text over there)
- have some ugly line breaks by default that the user could have to remove

Note: the same thing (in all versions of this) can be achieved with columns instead of grid too, so is this really needed to use grid? But why not.

What do you think @lebl-odoo @xlu-odoo ?

Also, I am not really convinced by using the popup default image. First, it's something that we will fix/change in the future (snippets using other snippets images like that), but that's another topic. But here it conceptually and technically does not work IMO:
- There is no relation whatsoever between this new block and a popup block. Saying that they use the same image conceptually does not make sense to me
- Technically, the popup image is a 1200x800 image. It works thus well for a popup. But on a normal snippet like this new one, it is blurry, as it is stretched more than 50% to reach 1920 width of my screen.

2024-11-05 15:02 UTC, lebl-odoo commented
Not sure how you get the first screeshot, but I agree the mobile version is quite tricky. I'm expecting a result like the following: 
![image](https://github.com/user-attachments/assets/c57cb2e2-f0e4-4ec0-ac5e-37f50d195ca3)

2024-11-06 09:23 UTC, lebl-odoo commented
Hi @qsm-odoo , @xlu-odoo :wave: 

Except @xlu-odoo has another solution to propose, I would pick the one that suits the most the user which is the current solution (from the PR). I think basic users will use the snippet as is. For more advanced users, if the snippet doesn't meet their expectations, they are able to rebuild it from scratch.

It's not the first snippet with limitations we have and I prefer simplicity (with constraints) to complexity.

2024-11-06 12:57 UTC, qsm-odoo commented
Alright, then let's go with your solution for now @xlu-odoo 

Still the

> Also, I am not really convinced by using the popup default image [...]

part to handle IMO :pray:

2025-01-07 13:56 UTC, xlu-odoo commented
> Alright, then let's go with your solution for now @xlu-odoo
> 
> Still the
> 
> > Also, I am not really convinced by using the popup default image [...]
> 
> part to handle IMO 🙏

Hello Quentin ( @qsm-odoo ),
Reviving this one. Rebased + created new image record for `s_opening_hours` (instead of using popup_default_image)

![image](https://github.com/user-attachments/assets/f407f9d0-8e22-4162-83a0-94baf6d0e2ad)

2025-01-30 13:10 UTC, qsm-odoo approved these changes
That's probably nice :crossed_fingers: 

@robodoo r+

2025-01-30 13:47 UTC, robodoo commented
@xlu-odoo @qsm-odoo linked pull request(s) odoo/design-themes#1004 not ready. Linked PRs are not staged until all of them are ready.

2025-01-31 04:27 UTC, robodoo commented
@xlu-odoo @qsm-odoo unable to stage: merge conflict

2025-01-31 08:27 UTC, qsm-odoo approved these changes
@robodoo r+

2025-01-31 12:12 UTC, closed without merging