[FIX] sale: hide invoicing policy when product type is combo
odoo/odoo pull request #181331
Opened 2024-09-25 06:26 UTC by shrm-odoo

Issue:
- The invoicing policy field is displayed for all product types, including combo products.

Fix:
- Hide invoicing policy field for products of type 'combo'.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-25 06:26 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181331.png)](https://mergebot.odoo.com/odoo/odoo/pull/181331)

2024-09-25 08:05 UTC, ltinel requested changes
Looks good, thanks for taking care of this :) Just a small cleanup comment.

2024-09-25 08:05 UTC, ltinel commented on addons/sale/views/product_views.xml
> +                />
There's an override in `pos_sale` that does the same [1]. Could you remove that override?

[1] https://github.com/odoo/odoo/blob/d0c9ceeb684ac19ff38463ed4abef82420076aac/addons/pos_sale/views/product_views.xml#L9-L11

2024-09-26 07:33 UTC, ltinel approved these changes
LGTM :)

2024-09-26 07:55 UTC, ltinel commented
BTW, could you retarget this PR to 18? :) Thanks!

2024-09-26 12:15 UTC, ltinel commented on addons/pos_sale/views/product_views.xml
> +    //TODO: remove this view in master
Could you use XML syntax for this comment? I'm not sure what will happen if you leave this as is :sweat_smile:

2024-09-26 12:42 UTC, Feyensv approved these changes
@robodoo r+

2024-09-26 12:42 UTC, robodoo commented
@Feyensv draft PRs can not be approved.

2024-09-26 12:53 UTC, robodoo commented
@shrm-odoo @Feyensv 'ci/template' failed on this reviewed PR.

2024-09-26 12:56 UTC, robodoo commented
@shrm-odoo @Feyensv 'ci/runbot' failed on this reviewed PR.

2024-09-26 12:57 UTC, robodoo commented
@shrm-odoo @Feyensv 'ci/upgrade_enterprise' failed on this reviewed PR.

2024-09-26 13:00 UTC, Feyensv commented
Ooops, seems like having an empty view does not work anymore.  Keep the view content, we'll only have the `or type == 'combo'` twice in the resulting view, it's not a big issue.
We'll remove it later in master (with an upgrade script)

2024-09-26 13:24 UTC, Feyensv approved these changes
@robodoo r+

2024-09-26 13:48 UTC, robodoo commented
@shrm-odoo @Feyensv 'ci/runbot' failed on this reviewed PR.

2024-09-27 00:03 UTC, robodoo commented
@shrm-odoo @Feyensv staging failed: ci/runbot on 30a3890f7e360fff29a093a546fa4b3bc43b4854 (view more at https://runbot.odoo.com/runbot/build/68777540)

2024-09-27 18:11 UTC, closed without merging