[FIX] website_sale_mondialrelay: adapt to new checkout
odoo/odoo pull request #181393
Opened 2024-09-25 11:45 UTC by vchu-odoo

It was possible to use delivery as billing address even if delivery address was a modialrelay one. That caused a traceback as it is not allowed to change modialrelay address. This commit will prevent these cases.

2024-09-25 11:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181393.png)](https://mergebot.odoo.com/odoo/odoo/pull/181393)

2024-09-27 09:43 UTC, AntoineVDV requested changes

2024-09-27 09:43 UTC, AntoineVDV commented on addons/website_sale_mondialrelay/static/src/js/checkout.js
> +            this.billingContainer.classList.remove('d-none');
Why not call the toggle method?

2024-09-27 09:43 UTC, AntoineVDV commented on addons/website_sale_mondialrelay/static/src/js/checkout.js
> +        this._super(...arguments);
```suggestion
        await this._super(...arguments);
```

2024-09-27 09:43 UTC, AntoineVDV commented on addons/website_sale_mondialrelay/static/src/js/checkout.js
> +            this.billingContainer.classList.remove('d-none');
Call the toggle method here also?

2024-09-30 10:32 UTC, AntoineVDV approved these changes

2024-09-30 11:49 UTC, d-fence commented
Upgrade exception [#385](https://runbot.odoo.com/web/#id=385&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

PRs adding fields/models should be merged at the beginning of the week and all the forward ports should be merged in the same week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
view:website_sale_mondialrelay.website_sale_mondialrelay_billing_address_row
view:website_sale_mondialrelay.mondialrelay_delivery_method
```
cc @KangOl @nseinlet @aj-fuentes

2024-09-30 14:15 UTC, AntoineVDV commented
@robodoo r+ delegate+

2024-09-30 19:27 UTC, closed without merging