[IMP] mail: new channel chat area decoration
odoo/odoo pull request #181392
Opened 2024-09-25 11:35 UTC by akap-odoo

**Current behavior before PR:**

Only a log of new channel creation was there.

**Desired behavior after PR is merged:**

Introduced a new welcome message for newly created channels

**task-id:**4203450

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-14 13:04 UTC, rapr-odoo requested changes

2024-10-15 06:43 UTC, rapr-odoo approved these changes
LGTM otherwise.

2024-12-11 12:44 UTC, rapr-odoo requested changes
PR needs a rebase.

2024-12-11 12:44 UTC, rapr-odoo commented on addons/mail/static/src/core/common/thread.scss
> +    }
You can put this LOC above the `img` rule.

2024-12-20 13:31 UTC, rapr-odoo approved these changes

2025-01-31 18:16 UTC, alexkuhn commented
Hello, I rebased the PR and also took opportunity to make some tweaks:
![Screenshot 2025-01-31 at 19 10 40](https://github.com/user-attachments/assets/a9096676-c0a4-473c-b1b1-466db84c05be)
![Screenshot 2025-01-31 at 19 10 21](https://github.com/user-attachments/assets/9ef430e2-2d26-4031-834d-1f207ea4498b)
![Screenshot 2025-01-31 at 19 12 00](https://github.com/user-attachments/assets/7f89bb1c-f1f1-4ea8-9d59-c99acc673d48)

- Avatar next to title wastes less space, especially in chat windows
- I've adapted size and spacing to look better
- Texts are properly translated
- Welcome message properly shown only when at the beginning of conversation (had flicker on 1st load and while loading more messages).

2025-03-31 10:30 UTC, alexkuhn commented
I added group chat and direct chat to the decorate:
<img width="1949" alt="Screenshot 2025-03-31 at 12 28 16" src="https://github.com/user-attachments/assets/a4b41f6b-4a67-4e8a-a639-322c65384f6d" />
Not livechat or whatsapp, as agents can be annoyed to see hundreds of them everyday, and visitors have welcome message / template anyway.

2025-03-31 12:05 UTC, alexkuhn approved these changes
@robodoo r+

2025-03-31 17:04 UTC, robodoo commented
@akap-odoo @alexkuhn unable to stage: merge conflict

2025-03-31 17:35 UTC, alexkuhn commented
@robodoo r+

2025-04-01 00:52 UTC, closed without merging