[FIX] account: ensure correct argument passing in _post_add_create method
odoo/odoo pull request #181326
Opened 2024-09-24 23:32 UTC by yordannuez

- Corrected the `_post_add_create` method to ensure arguments are passed correctly when calling the parent method.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-24 23:32 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181326.png)](https://mergebot.odoo.com/odoo/odoo/pull/181326)

2024-09-26 12:42 UTC, Megaaaaaa approved these changes
Hello :wave:

Looks good to me, thank you for the fix :+1: 

Sending it for r+ :rocket:

2024-09-27 16:06 UTC, oco-odoo requested changes
Thank you for contributing ! Just one small detail :)

2024-09-27 16:06 UTC, oco-odoo commented on doc/cla/individual/yordannuez.md
The diff in this file should be in a distinct [CLA] commit. This way, we don't mix it with the actual fix in the history :)

2024-09-27 17:48 UTC, closed without merging