[FIX] account_peppol: Fix pylint undefined-variable / E0602
odoo/odoo pull request #181328
Opened 2024-09-25 04:51 UTC by ngochung207

AssertionError: pylint test failed: `Undefined variable 'res' (E0602) at odoo/addons/account_peppol/models/res_company.py:22`

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-25 04:51 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181328.png)](https://mergebot.odoo.com/odoo/odoo/pull/181328)

2024-09-25 04:54 UTC, ngochung207 commented
Hello @daniel-stenlov can you take a look please ? Thank you

2024-09-26 08:57 UTC, yosuanicolaus requested changes
Was this not working previously? I don't think we need this change.

2024-09-27 13:58 UTC, ngochung207 commented
If you rate this unnecessary, you can close this pr, thanks

2024-09-27 15:14 UTC, closed without merging

2024-09-27 16:41 UTC, daniel-stenlov commented
I’m afraid I don’t see this as a fix. I might be missing something here.

Both the pull request and the original code function the same way logically. The original code uses a classic if-else statement, which is easier to read and understand, while the pull request implements an and-or logic.

Both approaches work similarly in terms of behavior and efficiency. They should also handle undefined variables in the same way. As I see it, this is more a matter of personal preference or coding style.