[IMP] l10n_in_withholding: List of Transections on which TDS/TCS can be applied
odoo/odoo pull request #181372
Opened 2024-09-25 10:31 UTC by bhra-odoo

with this PR:
The banner will be added to the top of TDS and TCS reports. The list of previous
transactions on which TDS needs to be applied will be shown, enabling the
user to apply TDS/TCS when the threshold is reached.

task - 3934821

2024-09-25 10:31 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181372.png)](https://mergebot.odoo.com/odoo/odoo/pull/181372)

2024-10-09 12:16 UTC, hamo-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +    l10n_in_apllicable_section_ids = fields.Many2many('l10n_in.section.alert', string="TDS/TCS Applicable Sections", compute="_compute_l10n_in_tcs_tds_warning")
```suggestion
    l10n_in_applicable_section_ids = fields.Many2many('l10n_in.section.alert', string="TDS/TCS Applicable Sections", compute="_compute_l10n_in_tcs_tds_warning")
```

2024-10-09 12:16 UTC, hamo-odoo commented on addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.xml
> +                    <button string="Discard" special="cancel" class="btn-secondary" data-hotkey="d"/>
```suggestion
                    <button string="Discard" special="cancel" class="btn-secondary" data-hotkey="x"/>
```
Shouldn't it should be `x` as other wizards?

2024-10-09 12:16 UTC, hamo-odoo commented on addons/l10n_in_withholding/models/account_move_line.py
> +    section_id = fields.Many2one(related="account_id.l10n_in_tds_tcs_section_id")
```suggestion
    l10n_in_tds_tcs_section_id = fields.Many2one(related="account_id.l10n_in_tds_tcs_section_id")
```

2024-10-23 12:16 UTC, jva-odoo requested changes

2024-10-23 12:16 UTC, jva-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +        ]
you can add new field like `only_on_over_limit` in `L10nInSectionAlert`

2024-10-23 12:16 UTC, jva-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +    l10n_in_applicable_section_ids = fields.Many2many('l10n_in.section.alert', string="TDS/TCS Applicable Sections", compute="_compute_l10n_in_tcs_tds_warning")
Don't add fields just for view purposes.
find an alternative like showing `account.move.line` with the group by `l10n_in_tds_tcs_section_id` and `move_id`

2024-11-15 08:51 UTC, hamo-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +                group_key = line.account_id.l10n_in_tds_tcs_section_id.id
```suggestion
                group_key = line.l10n_in_tds_tcs_section_id.id
```
Can we do it with `_read_group()` ? just a thought and suggestion if yes then this method would not be needed anymore 🤔

2024-11-15 08:55 UTC, hamo-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +            aplicable_sections = _is_section_applicable(aggregate_total, self.invoice_currency_rate, group_by_section)
```suggestion
            applicable_sections = _is_section_applicable(aggregate_total, self.invoice_currency_rate, group_by_section)
```

2024-11-15 08:56 UTC, hamo-odoo commented on addons/l10n_in_withholding/models/account_move.py
> +            for section_alert in aplicable_sections:
```suggestion
            for section_alert_id in aplicable_sections:
```

2024-11-26 10:20 UTC, hamo-odoo requested changes
We still need to try to improve time-complexity

2026-03-31 11:23 UTC, jva-odoo commented
task is cancelled

2026-03-31 11:23 UTC, closed without merging