[FIX] point_of_sale: unable to settle demo orders in restaturent
odoo/odoo pull request #181585
Opened 2024-09-26 11:52 UTC by ksku-odoo

Steps to reproduce :
---------------------------
- Install the pos_restaurant module.
- Open any demo orders, let's say table 1
- Make the payment, then go to the receipt screen then the floor plan
- [ISSUE] Order is still there.
- In Table 6, can't even place the order

Cause :
---------
1. Demo orders case was not handled in the "sync_from_ui" method leading to this issue
2. Uuid was not given for the Table 6 order line, causing this misbehavior.

Fix :
------
1. Handled the case for demo orders in the "sync_from_ui" method
2. Provide uuid for table 6 order line at the time of creation

Task: 4212901

2024-09-26 11:52 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181585.png)](https://mergebot.odoo.com/odoo/odoo/pull/181585)

2024-09-27 12:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +                    order_ids.append(self._process_order(order, False))
```suggestion
            if not existing_draft_order:
                existing_orders = self.env['pos.order'].search([('uuid', '=', order['uuid'])])
            order_ids.append(self._process_order(order, existing_draft_order or False))
```

2024-09-27 12:59 UTC, paso-odoo requested changes

2024-09-27 12:59 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +                ['&', ('id', '=', order.get('id', False)), ('state', '=', 'draft')], limit=1) if isinstance(order.get('id'), int) else False
```suggestion
            existing_draft_order = self.env["pos.order"].search(
                [('id', '=', order.get('id', False)), ('state', '=', 'draft')]) if isinstance(order.get('id'), int) else False
```

2024-09-27 14:10 UTC, caburj commented
Closing since it's also fixed here: https://github.com/odoo/odoo/pull/181858

2024-09-27 14:10 UTC, closed without merging