[FIX] point_of_sale: ensure unsynced paid orders sync after restart
odoo/odoo pull request #181539
Opened 2024-09-26 09:41 UTC by pedrambiria

Before this commit, orders created in offline mode would not sync upon restarting the session once back online.

opw-4213314

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-26 09:41 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181539.png)](https://mergebot.odoo.com/odoo/odoo/pull/181539)

2024-09-26 09:50 UTC, davidmonnom requested changes

2024-09-26 09:50 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/models/pos_order.js
> +    isUnsyncedPaidOrder() {
Maybe do a getter `isUnsyncedPaid` don't need to put `order` in the name since it will be call from an order object.

2024-09-26 09:50 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/store/pos_store.js
> +        const paidUnsyncedOrderIds = this.data.models["pos.order"]
```suggestion
        const paidUnsyncedOrderIds = this.models["pos.order"]
```

In the pos_store you can directly access models.

2024-09-26 13:43 UTC, davidmonnom commented
@robodoo r+

2024-09-26 14:38 UTC, robodoo commented
@pedrambiria @davidmonnom 'ci/runbot' failed on this reviewed PR.

2024-09-27 09:32 UTC, pedrambiria commented
robodoo r+

2024-09-27 09:32 UTC, robodoo commented
@pedrambiria you can't review+.

2024-09-27 13:01 UTC, davidmonnom approved these changes
@robodoo r+

2024-09-27 13:01 UTC, robodoo commented
This PR is already reviewed, reviewing it again is useless.

2024-09-27 17:00 UTC, closed without merging