[FIX] website: deleting search doesn't refresh
odoo/odoo pull request #181506
Opened 2024-09-26 06:53 UTC by romo-odoo

...

task-3570756

2024-09-26 06:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181506.png)](https://mergebot.odoo.com/odoo/odoo/pull/181506)

2025-10-13 11:56 UTC, SergeBayet commented
Reminder up to 18.0

2025-10-13 12:23 UTC, SergeBayet requested changes
Nice. A remark though. See the comment inside the code.

Commit message header should make a valid sentence once concatenated with `if applied, this commit will <header>`. For example `[IMP] base: prevent to archive users linked to active partners` is correct as it makes a valid sentence `if applied, this commit will prevent users to archive...` (https://www.odoo.com/documentation/19.0/contributing/development/git_guidelines.html)

For the commit message:
"immediatly" -> "immediately"
"The page refresh" -> "The page refreshes"

2025-10-13 12:23 UTC, SergeBayet commented on addons/website/static/src/snippets/s_searchbar/000.js
> -                this.limit = 0; // prevent autocomplete
You should probably keep the `limit` safeguard to prevent the autocomplete kicking in immediately after a clear.

2025-10-13 12:34 UTC, sobo-odoo commented
@robodoo delegate=SergeBayet

2025-10-13 12:50 UTC, romo-odoo commented on addons/website/static/src/snippets/s_searchbar/000.js
> -                this.limit = 0; // prevent autocomplete
Keeping `this.limit = 0` prevent autocomplete at any point after a clear, 
I don't think it should be kept

2025-10-13 13:13 UTC, SergeBayet commented
@robodoo r+

2025-10-13 14:18 UTC, SergeBayet commented
@robodoo up to 18.0

2025-10-13 14:18 UTC, robodoo commented
Forward-porting to '18.0'.

2025-10-13 17:23 UTC, closed without merging