[FIX] l10n_es_edi_facturae: disable facturae if B2C ecommerce
odoo/odoo pull request #181653
Opened 2024-09-26 14:38 UTC by adwid

To reproduce the issue:
(Need website_sale)
1. Set up a website shop for ES company
   - With demo payment method
2. In Settings:
   - Website > Automatic Invoice: enabled
3. With a portal user, add a product to the cart
4. Open the cart
5. Pay with Demo

Error: The client is redirected to a page "Internal server error:
The partner needs a set tax identification number or VAT number"

When post-processing the payment, and because of step 2, it leads to
https://github.com/odoo/odoo/blob/20365bcab548c4a2d93194c8c2b8b2577d14d3ce/addons/l10n_es_edi_facturae/wizard/account_move_send.py#L86-L88
Where we will generate the data for the Facturae XML. There, we
check few things, like the vat number of the partner:
https://github.com/odoo/odoo/blob/e157cb2d8640fac1365beb135763cb25cff554f5/addons/l10n_es_edi_facturae/models/account_move.py#L312-L313
And since the portal user does not have any vat number, the error is
raised.

In such situation, we should not try to generate the Facturae data.

Also, the creation of a bridge just for an one-line patch would be a
bit too much and would not impact existing databases, hence the sad
diff.

OPW-4121724

2024-09-26 14:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181653.png)](https://mergebot.odoo.com/odoo/odoo/pull/181653)

2024-10-07 13:15 UTC, aboo-odoo reviewed
LGTM @clbr-odoo, maybe you can think of another way but it, indeed, seems to be the lesser bad compared to a bridge between ES edi and website

2024-10-08 14:57 UTC, clbr-odoo requested changes

2024-10-09 08:48 UTC, clbr-odoo commented on addons/l10n_es_edi_facturae/models/account_move.py
> +            and not ('website_id' in self and self.website_id and not self.partner_id.vat) \
Very good suggestion :ok_hand:

2024-10-09 13:24 UTC, clbr-odoo approved these changes
Thank you :+1: 
@robodoo r+

2024-10-10 07:20 UTC, robodoo commented
@adwid @clbr-odoo staging failed: ci/l10n on 85a0665c4421b71cbd5ee6ed8150475cdf97c79e (view more at https://runbot.odoo.com/runbot/build/69228581)

2024-10-10 07:23 UTC, clbr-odoo commented
@robodoo r-

2024-10-10 07:24 UTC, clbr-odoo commented
@adwid Welp, sorry I forgot about the tests, they'll probably need you to set is_company correctly in the setup

2024-10-10 12:45 UTC, clbr-odoo commented
@robodoo r+

2024-10-10 19:32 UTC, closed without merging