[FIX] website: check cookies consent before YouTube mobile autoplay
odoo/odoo pull request #181764
Opened 2024-09-27 08:37 UTC by robinlej

Commit [958b41c4] added support to block third-party cookies, but some flows on mobile did not work properly.

Steps to reproduce:
- Enable the Cookies Bar in the settings and check "Block tracking 3rd-party services"
- Add a Cover block (or another block)
- Set a YouTube video as background of the block
- Open an incognito window
- Resize it so that it displays the page in the mobile version
- Refresh the page => AssetsLoadingError: The loading of https://www.youtube.com/iframe_api failed

[958b41c4]: https://github.com/odoo/odoo/commit/958b41c4acec7e1700ca4d6e0b25ee0ad2aac9f1

opw-4202306

2024-09-27 08:37 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/181764.png)](https://mergebot.odoo.com/odoo/odoo/pull/181764)

2024-09-27 10:14 UTC, robinlej commented
@qsm-odoo when you have time. :)

2024-09-29 20:36 UTC, qsm-odoo requested changes
@robinlej I tested in 17.4 using your steps to reproduce, without your PR, I don't get any error :shrug:

2024-09-30 07:13 UTC, robinlej commented
@qsm-odoo It seems to bug only on Chrome (possibly because of Firefox's default settings that block trackers.)
I added it in the commit message.

2024-10-09 13:22 UTC, qsm-odoo approved these changes
@robodoo r+

2024-10-09 15:18 UTC, closed without merging