[MOV] calendar: move unavailable_partner_ids to calendar
odoo/odoo pull request #182082
Opened 2024-09-30 10:11 UTC by mrsr-odoo

The intervals are the generalized concept that can be applied to any model with
start and stop date.

The PR moves the `Interval` class and a few utils methods from resource and
appointment to improve flexibility and reusability across different models without
any additional dependencies.

We also relocates unavailable_partner_ids to the calendar module
for easier access from other modules like appointment.
By default, it computes partners with conflicting events.

Task-3997545

2024-09-30 10:11 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182082.png)](https://mergebot.odoo.com/odoo/odoo/pull/182082)

2025-01-13 15:06 UTC, awa-odoo reviewed
Hello @mrsr-odoo 

Finally had a look at this one, sorry for the delay.
Left some comments and questions.

Thanks & cheers!

2025-01-23 09:52 UTC, mrsr-odoo reviewed
Hello @awa-odoo :slightly_smiling_face: 

Thanks for the review
Updated the code and answered few questions

Thanks :sparkles:

2025-01-23 09:52 UTC, mrsr-odoo commented on addons/calendar/models/res_partner.py
> +        return dict(events.partner_ids.mapped(lambda x: (x.id, (events & x.meeting_ids))))
Not sure how to use `grouped` with many2many
I tried to group on partner_ids but couldn't find desired one
![image](https://github.com/user-attachments/assets/2d0e38cd-c673-4c1b-a726-6977ab7bf64f)
so going with mapped

2025-01-23 09:52 UTC, mrsr-odoo commented on addons/hr_calendar/models/calendar_event.py
>      def _compute_unavailable_partner_ids(self):
moved `test_partner_on_leave_with_calendar_leave` from `appointment_hr`

2025-02-05 09:40 UTC, awa-odoo reviewed
Hello @mrsr-odoo 

Looking better already, left some additional comments / questions.

Thanks & cheers!

2025-02-05 09:40 UTC, awa-odoo commented on addons/calendar/__manifest__.py
> +    'depends': ['base', 'mail', 'resource'],
I don't think we should depend on a whole additional module to just use some utils.

Maybe we could try to move all Intervals related utils and method into the "base" module utils?
(Should be done in a separate MOV commit).

As "Intervals" is a concept abstract from any specific model and can work with anything that has a start and a stop date, it could make sense to have it in base.

cc @reth-odoo

2025-02-05 09:40 UTC, awa-odoo commented on addons/calendar/models/res_partner.py
> +        return dict(events.partner_ids.mapped(lambda x: (x.id, (events & x.meeting_ids))))
You're correct, didn't remember it was a m2m.

I actually preferred the previous version then, easier to read, sorry :grimacing:

2025-02-05 09:40 UTC, awa-odoo commented on addons/calendar/views/calendar_views.xml
> +                            many2many_attendees widget -->
You can put everything on one line.

If it's really too long (but it doesn't appear to be), put the whole comment above the field.

2025-02-05 09:40 UTC, awa-odoo commented on addons/calendar/views/calendar_views.xml
> +                    many2many_attendees widget -->
Same thing here.

2025-02-05 09:40 UTC, awa-odoo commented on addons/hr_calendar/models/calendar_event.py
> +                event.unavailable_partner_ids |= event.partner_ids
Isn't that part already covered by the base calendar logic?

Normally the only addition of the hr override is to take the working calendar of the employees into account.

2025-02-07 09:40 UTC, mrsr-odoo commented on addons/calendar/__manifest__.py
> +    'depends': ['base', 'mail', 'resource'],
Hello @awa-odoo ,

Can we move the whole[ utils.py ](https://github.com/odoo/odoo/blob/master/addons/resource/models/utils.py) as other things related to date and time?

Thanks

2025-02-07 09:45 UTC, awa-odoo commented on addons/calendar/__manifest__.py
> +    'depends': ['base', 'mail', 'resource'],
Hello :wave: 

I think it's fair to move everything yes, it's not resource-module dependent, it's all date manipulation tools.

cc @tivisse

2025-02-13 10:46 UTC, mrsr-odoo commented
Hello @awa-odoo :wave: ,
Moved interval utils to base and update all occurrence
Please have a look
Thanks

2025-02-19 10:35 UTC, awa-odoo approved these changes
Hello @mrsr-odoo 

Looking good, thank you for the update.
Added a few polishing comments but globally LGTM.

As we have done a significant amount of changes, can you ask for another testing round? To make sure everything still works properly.

The branch also needs a proper rebase.

After that we should be good to go :rocket: 

Thanks & cheers!

2025-02-19 10:35 UTC, awa-odoo commented on addons/calendar/static/src/views/fields/many2many_attendee.js
> +        : [];
Indent issue here.

2025-02-19 10:35 UTC, awa-odoo commented on addons/calendar/static/src/views/fields/many2many_attendee.js
> +            if (unavailablePartnerIds.find((partner) => (tag.resId == partner.resId))) {
"partner" is colliding with the "partner" variable here above.

Sugg:
`if (unavailablePartnerIds.find((unavailablePartner) => (partner.id === unavailablePartner.resId))) {`

2025-02-19 10:35 UTC, awa-odoo commented on addons/calendar/static/src/views/fields/many2many_attendee.js
> +                tag.unavailableIcon = true;
Can we rename to '"isUnavailable" while we're at it?

The fact that it toggles an icon in the interface is a bit too specific.

2025-02-19 14:37 UTC, kmagusiak requested changes

2025-02-19 14:37 UTC, kmagusiak commented on odoo/addons/base/models/utils.py
> +    :return bool: True if the two intervals share some time interval, or if interval_a is 0-width
```suggestion
    :return bool: True if two non-zero intervals overlap
```

2025-02-19 14:37 UTC, kmagusiak commented on odoo/addons/base/models/utils.py
> +    return start_a != stop_a and start_a < stop_b and stop_a > start_b
```suggestion
    return start_a < stop_b and stop_a > start_b
```

2025-02-20 07:26 UTC, mrsr-odoo commented on odoo/addons/base/models/__init__.py
> +from . import utils
Hello @awa-odoo ,
I couldn't determine where to put test case for our utils
Should I keep the test case in `base`?
Thanks

2025-02-20 07:49 UTC, kmagusiak commented on odoo/addons/base/models/__init__.py
> +from . import utils
odoo/tools/... (date_intervals.py?)
Check also whether all utils should go into tools and split accordingly. Probably `filter_domain_leaf` should stay where it is.

2025-02-20 08:44 UTC, awa-odoo commented on odoo/addons/base/models/__init__.py
> +from . import utils
Hello @mrsr-odoo 

Looks like the tools tests are located in base/tests (such as "test_date_utils.py", "test_image.py", ...).

I think we could create "date_intervals.py" (in odoo/tools) and "test_date_intervals.py" (in base/tests), as suggested by @kmagusiak 

Indeed, we could leave the "filter_domain_leaf" method where it is currently (in the resource module) as it seems to not be directly related to manipulating dates and intervals like the other methods.

2025-02-20 13:00 UTC, kmagusiak reviewed
I added only some comments on these, but they should be reviewed more in depth. Maybe in a separate PR so that we don't mix that mave with other changes (like the move of the field).

2025-02-20 13:20 UTC, awa-odoo commented
This PR is indeed not about reviewing the whole Interval util lib, we are "only" moving it.

I understand it's a good opportunity to take a good look at it, but it could be done in a separate task/PR so we don't delay this one much longer.
For all intents and purposes, it's working as we want it to and has some decent test coverage already.

(Can always be better as the odoo/utils has higher standards than the functional modules of course, such as typing etc).

2025-02-20 13:59 UTC, kmagusiak commented
> This PR is indeed not about reviewing the whole Interval util lib, we are "only" moving it.
> 
> I understand it's a good opportunity to take a good look at it, but it could be done in a separate task/PR so we don't delay this one much longer. For all intents and purposes, it's working as we want it to and has some decent test coverage already.
> 
> (Can always be better as the odoo/utils has higher standards than the functional modules of course, such as typing etc).
> 
> EDIT: unless you see some significant issues with it of course :)

I won't block as long as someone says they will clean it up just after merging this PR.
You can still move the test files for other methods too and don't re-export inside `odoo.tools` yet; you can import directly `from odoo.tools.date_intervals import ...`.
@rco-odoo your point of view?

2025-02-27 13:04 UTC, robodoo commented
Merge method set to rebase and merge, using the PR as merge commit message.

2025-02-27 18:00 UTC, closed without merging