[FIX] website: fix `s_tabs` underline contrast issue
odoo/odoo pull request #182083
Opened 2024-09-30 10:11 UTC by xlu-odoo

Before this commit, when using the "Tabs" snippet with the underline layout and adding one of the darker color presets, there was a contrast issue, particularly with the active state.

This commit fixes the contrast issue by ensuring that the active text color dynamically inherits the appropriate color based on the background

task-4215783

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-09-30 10:11 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182083.png)](https://mergebot.odoo.com/odoo/odoo/pull/182083)

2024-09-30 11:37 UTC, anso-odoo approved these changes
Just one small comment, otherwise LGTM

2024-09-30 11:37 UTC, anso-odoo commented on addons/website/static/src/snippets/s_tabs/002.scss
> +                }
Missing an empty line

2024-09-30 21:29 UTC, qsm-odoo requested changes

2024-09-30 21:29 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_tabs/002.scss
> +                    color: inherit;
- color inherit if active + color inherit if not active, why not color inherit always then?
- also, is this a very specific issue to s_tabs? Sure it's not a generic problem of o_cc classes?

2024-10-08 12:22 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_tabs/002.scss
> +                    color: inherit;
@xlu-odoo If it is finished and ready for review, can you answer my second question here? Thanks :pray:

2025-01-30 14:13 UTC, qsm-odoo approved these changes
Maybe :shrug: At worst, it's only CSS

@robodoo r+

2025-01-30 18:15 UTC, closed without merging