[FIX] website_sale: ensure delivery page is displayed in checkout
odoo/odoo pull request #182269
Opened 2024-10-01 06:49 UTC by rupa-odoo

Version: saas-17.3

Issue:
When only one delivery method is available, the checkout process skips the delivery page and redirects directly to payment, which confuses users.

Fix:
Adjusted the condition to show the delivery page if at least one delivery method exists (len(delivery_methods) > 0). This ensures users can review and confirm their delivery options even when only one method is available.

The delivery page will now be displayed regardless of the number of delivery methods, improving user experience by allowing them to review their delivery details before payment.

2024-10-01 06:49 UTC, robodoo commented
This PR targets the disabled branch odoo/odoo:saas-17.3, it needs to be retargeted before it can be merged.

2024-10-01 06:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182269.png)](https://mergebot.odoo.com/odoo/odoo/pull/182269)

2024-10-01 07:23 UTC, robodoo commented
This PR targets the disabled branch odoo/odoo:saas-17.3, it needs to be retargeted before it can be merged.

2024-10-07 05:31 UTC, vchu-odoo approved these changes
Thank you for the changes!

LGTM :+1:

2024-10-07 08:14 UTC, AntoineVDV requested changes
Hi @rupa-odoo, could you add a quick unit test to ensure this doesn't get inadvertently reverted to `> 1`, as it's not super clear in the code why `> 0` was chosen?

FYI @dalaOdoo this should fix the behavior you were complaining about.

2024-10-07 08:23 UTC, vchu-odoo requested changes
Hello,

Just noticed that we do not need `can_skip_delivery_step` at all since we want always go through the checkout `if order_sudo._has_deliverable_products()`. Could you please remove it then and adapt `shop_checkout` accordingly?

2024-10-08 05:30 UTC, rupa-odoo commented
> Hi @rupa-odoo, could you add a quick unit test to ensure this doesn't get inadvertently reverted to `> 1`, as it's not super clear in the code why `> 0` was chosen?
> 
> FYI @dalaOdoo this should fix the behavior you were complaining about.

Hello,
Removing can_skip_delivery_step because there is no need to skip the delivery step now we always go through the checkout.

2024-10-08 05:31 UTC, rupa-odoo commented
> Hello,
> 
> Just noticed that we do not need `can_skip_delivery_step` at all since we want always go through the checkout `if order_sudo._has_deliverable_products()`. Could you please remove it then and adapt `shop_checkout` accordingly?

Hello 
Done the changes :+1:

2024-10-08 08:31 UTC, vchu-odoo requested changes
Thank you for the changes!

Just one small comment.
Could you please keep the variable  `can_skip_delivery` with all the comments and set it to `False` in the `if order_sudo._has_deliverable_products():` ?
It would be much clearer that way.

2024-10-08 10:48 UTC, rupa-odoo commented
> Thank you for the changes!
> 
> Just one small comment. Could you please keep the variable `can_skip_delivery` with all the comments and set it to `False` in the `if order_sudo._has_deliverable_products():` ? It would be much clearer that way.

Done the changes 
But we are not using that variable 'can_skip_delivery' due to the check style failing.

2024-10-08 11:32 UTC, vchu-odoo requested changes
The style is failing because you never use the variable that you declared.
It may not be clear what I suggested before, so feel free to check my comments and let me know if you have any questions.

2024-10-08 13:25 UTC, vchu-odoo commented on addons/website_sale/controllers/main.py
> +                    can_skip_delivery = False
could you move it after L982? It should be set `False` when we enter the `if`.

2024-10-08 14:04 UTC, vchu-odoo approved these changes
Thank you for the changes!
LGTM :+1: 

The only strange thing is that L992 is considered modified by git. Could you check if your code editor changed the style (e.g spaces to tab or smth else) and fix it to avoid polluting commit with an unrelated change?
Check the ci/style.

2024-10-09 11:05 UTC, AntoineVDV approved these changes
@robodoo r+

2024-10-09 12:36 UTC, closed without merging