[FIX] resource, hr_work_entry_contract: split work intervals by type
odoo/odoo pull request #182574
Opened 2024-10-07 09:11 UTC by Yoann-bary

Steps to reproduce:
- Payroll > Configuration > Working Schedules
- Edit Monday morning to have shifts as follows -- 8:00-10:00, Overtime Hours type, 0.25 days
-- 10:00-12:00, Attendance type, 0.25 days
- Employees > Any with that schedule > Time Off
- Take a day off on a Monday (Full day)
- Time Off app > Management > Time Off
- Try to validate this time off

An error occurs when trying to read the morning's work entry type because both shifts have been merged (and thus the resulting shift has 2 entry types). This happens because of the use of Intervals in resource_calendar's '_attendance_intervals_batch' method.

When dealing with attendances we prefer using WorkIntervals which, unlike Intervals, keeps adjacent shifts separate. This is necessary to properly handle the entry type of leaves and attendances over contiguous periods.

This also removes the need for fdd9247cb86a01cc8c0903e69b85aae311e7c1ad, as the attendances have already been separated (Shifts cannot overlap any more than at their bounds) according to their type.

opw-4193334

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-07 09:11 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182574.png)](https://mergebot.odoo.com/odoo/odoo/pull/182574)

2024-10-07 15:21 UTC, nle-odoo approved these changes
seems good to me

2024-10-10 08:10 UTC, Bertrand2 requested changes
Just missing the update of the `.pot` file and a test, otherwise LGTM! :) Thanks

2024-10-10 08:15 UTC, Yoann-bary commented
I haven't touched any front-end text so I'm not sure what `.pot` you are referring to. I also reworked the test that was previously meant for _postprocess_attendance_intervals (Which I removed). If that's not enough I can add more but I think that might be somewhat redundant.

2024-10-10 08:51 UTC, Bertrand2 commented
> I haven't touched any front-end text so I'm not sure what `.pot` you are referring to. I also reworked the test that was previously meant for _postprocess_attendance_intervals (Which I removed). If that's not enough I can add more but I think that might be somewhat redundant.

Indeed, my bad! I somehow confused the test change as a code change, and the text inside it as a user text change :sweat_smile: Not enough coffee yet today it seems! LGTM

2024-10-10 08:51 UTC, Bertrand2 commented
robodoo r+

2024-10-10 12:01 UTC, closed without merging

2025-04-08 14:35 UTC, nle-odoo commented on addons/resource/models/resource_calendar.py
> +from odoo.addons.hr_work_entry_contract.models.hr_work_intervals import WorkIntervals
hello


is this causing you an issue?

the cycle should not matter as far as I can tell (the python module should be cached, and gotten back from the cache, without importing the file a second time to follow the cycle)

as for hidden dependency to hr_work_entry_contract, do you mean that the python files will be loaded? then yes and it's not very clean but does it cause an issue to you?

2025-07-04 13:30 UTC, hparfr commented on addons/resource/models/resource_calendar.py
> +from odoo.addons.hr_work_entry_contract.models.hr_work_intervals import WorkIntervals
Hello @nle-odoo.
I'm a bit late on this one.

>is this causing you an issue?

It doesn't prevent me from sleeping. I also don't see any performance implications.

IMO, it is a bad practice. It breaks the contract of the `depends` key in the `__manifest__`.
Because it's Odoo core, and Odoo core lines of codes are golden reference for many developers. The signal it sends is: "don't bother to put dependencies in the manifest, it's not needed".

Newbie developers will also figure out that sometimes (sometimes !) it works. Consequently the volume of bad quality code will increase, instances will bug, customers will be unhappy and they will place the blame on Odoo.

https://github.com/odoo/odoo/blob/18.0/addons/hr_work_entry_contract/models/hr_work_intervals.py#L15C1-L19C35

```py
class WorkIntervals(object):
    """
        This class is a modified copy of the ``Intervals`` class in the resource module.
        A generic solution to handle intervals should probably be developped the day a similar
        class is needed elsewhere.
```

This day has come, is it time move this chunk of code into `resource` ?

2025-07-10 14:45 UTC, nle-odoo commented on addons/resource/models/resource_calendar.py
> +from odoo.addons.hr_work_entry_contract.models.hr_work_intervals import WorkIntervals
Hi

I agree that it is ugly and the good style would be to have the code in resource if it makes sense.

But if there is no issue happening, I don't think bug fixers will do a syntactic fix in a stable version: we try to change the code as little as possible since any fix has some risk of breaking customization, and we would also need to still add the reverse reference anyway to not break custom code using/overriding the class at the current location.

For new versions, this should be solved by this change since saas-18.4 that moves the intervals to "odoo.tools.date_intervals" (outside of an odoo module): https://github.com/odoo/odoo/commit/0f93ec75ae7e94d8ac666195da75a347daeec61a

2025-07-10 15:03 UTC, hparfr commented on addons/resource/models/resource_calendar.py
> +from odoo.addons.hr_work_entry_contract.models.hr_work_intervals import WorkIntervals
Thanks @nle-odoo for your answer.
Glad to see I has been fixed for the upcoming versions.