[FIX] pos_{, restaurant}: traceback when printing bill and validating payment
odoo/odoo pull request #182576
Opened 2024-10-07 09:23 UTC by parp-odoo

Steps:

- Open the restaurant interface.
- Add items to any table order.
- Print the bill using the action button.
- Attempt to validate a payment.
- An error message appears.

Issue:
- A traceback occurs when printing the bill from the action button.
- After printing the bill via the action button, adding a payment line to the order becomes restricted.

Cause:
- An error occurs due to an increment in the bill print count.

Fix:
- Prevent incrementing the bill print count when using the action button.

task-4231943

2024-10-07 09:23 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182576.png)](https://mergebot.odoo.com/odoo/odoo/pull/182576)

2024-11-12 10:16 UTC, adgu-odoo requested changes
Let me know if I'm wrong and I didn't thought about something. Also, did you test with skip preview screen activated (automatic receipt printing) ? I guess it should work as it does not call printReceipt but could you still check ? Thank you for your time

2024-11-12 10:16 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
> +            printBillActionTriggered: this.props.printBillActionTriggered,
Why do you need a props here when you know you are in the BillScreen ?

2024-11-12 10:16 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
> +        printBillActionTriggered: { type: Boolean, optional: true },
I think you could remove this

2024-11-12 10:16 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/app/control_buttons/control_buttons.js
> +            this.dialog.add(BillScreen, {
And also this

2024-11-12 10:16 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
> +            printBillActionTriggered: this.props.printBillActionTriggered,
```suggestion
            printBillActionTriggered: true,
```

2024-11-14 13:11 UTC, parp-odoo commented
Hello @adgu-odoo  ,
Changes Are done.
Could please check?

2024-11-19 10:09 UTC, adgu-odoo approved these changes

2024-11-19 10:10 UTC, adgu-odoo commented
robodoo r+

2024-11-19 13:51 UTC, closed without merging