[FIX] account: prevent error when clicking on Send payment status to SInvoice
odoo/odoo pull request #182621
Opened 2024-10-07 13:17 UTC by reka-odoo

When User Clicks on Send payment status to SInvoice action,
a traceback will appear.

Steps to reproduce the error:
- Install ``l10n_vn_edi_viettel`` module
- Switch to VN Company
- Go to Invoicing > Customers > Invoices > Select any invoice > Actions >
  Send payment status to SInvoice

Traceback:
```
SyntaxError: syntax error at or near ")"
LINE 1: SELECT * FROM account_move WHERE id IN () FOR UPDATE SKIP LO...
                                                ^

  File "odoo/tools/safe_eval.py", line 391, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(2134,)", line 3, in <module>
  File "addons/l10n_vn_edi_viettel/models/account_move.py", line 299, in action_l10n_vn_edi_update_payment_status
    self.env['res.company']._with_locked_records(self)
  File "addons/account/models/company.py", line 785, in _with_locked_records
    self._cr.execute(f'SELECT * FROM {records._table} WHERE id IN %s FOR UPDATE SKIP LOCKED', [tuple(records.ids)])
  File "odoo/sql_db.py", line 347, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'psycopg2.errors.SyntaxError'>: "syntax error at or near ")"
LINE 1: SELECT * FROM account_move WHERE id IN () FOR UPDATE SKIP LO...
                                                ^
```

https://github.com/odoo/odoo/blob/072da22e72e66e6332d073502b987682f1b6e88b/addons/account/models/company.py#L745
Here, when there are no records for sending their payment status to SInvoice,
records.ids will be empty,
It will lead to the above traceback.

This commit will fix the above issue by preventing the execution of the query
when ``records.ids`` is empty.

sentry-5954926261

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-07 13:17 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182621.png)](https://mergebot.odoo.com/odoo/odoo/pull/182621)

2024-10-10 09:53 UTC, kitan191 approved these changes
LGTM

The issue is coming from a filter made on the records in the server action:
https://github.com/odoo/odoo/blob/25264c45d5c0a931df375adccce5d8079df2d273/addons/l10n_vn_edi_viettel/views/account_move_views.xml#L80-L82

Another way to fix it would be to check the filtered records in the action directly, but it would be less generic.

2024-10-17 08:19 UTC, clbr-odoo requested changes
Hello, 
I think the fix is ok but I'd like to clean a bit more further the code.
1. Remove the filter from the XML action that PTA pointed out (it's already in the action):
https://github.com/odoo/odoo/blob/25264c45d5c0a931df375adccce5d8079df2d273/addons/l10n_vn_edi_viettel/views/account_move_views.xml#L80-L82
2. Handle correctly the thing in the action itself:  
https://github.com/odoo/odoo/blob/6172c9af65dbeb730e2ed39485fb169445defb9f/addons/l10n_vn_edi_viettel/models/account_move.py#L298-L301
    a. Filter the moves and assign them to a variable.
    b. If there are valid moves, lock them
    c. Loop

2024-10-17 10:17 UTC, reka-odoo commented
Hello @clbr-odoo :wave: 
Please have a look.
Thanks!

2024-10-17 10:57 UTC, clbr-odoo commented
All good thanks, but your fix of the `_with_locked_records` was also relevant, we can keep it too for me :slightly_smiling_face:

2024-10-17 11:51 UTC, reka-odoo commented
Hello @clbr-odoo :wave: 
I have added that code back.
Thanks for the review :slightly_smiling_face:

2024-10-17 11:55 UTC, clbr-odoo approved these changes
Thank you !
@robodoo r+

2024-10-17 15:40 UTC, closed without merging