[IMP] website: update wrapper for mobile preview
odoo/odoo pull request #182889
Opened 2024-10-09 08:33 UTC by xlu-odoo

Before this commit, the mobile preview in website editor displayed a phone wrapper resembling an outdated device, and the image quality was not sharp.

This commit fixes this issue by updating the phone mockup and adapting the code.

task-4224631

#### Preview
| Before | After |
|--------|--------|
| ![Capture d’écran 2024-10-09 à 10 26 06](https://github.com/user-attachments/assets/1a40e2d9-6b6f-4f33-860e-47929b68c8f7) | ![Capture d’écran 2024-10-09 à 10 26 51](https://github.com/user-attachments/assets/a103d4aa-974d-4ca0-a26a-0e3c380f0678) | 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-09 08:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182889.png)](https://mergebot.odoo.com/odoo/odoo/pull/182889)

2024-11-18 20:42 UTC, stefanorigano approved these changes
LGTM, thanks 👍 

@odoo/rd-website , all yours ;)

2024-11-19 08:13 UTC, xlu-odoo commented
^ (rebased)

2024-12-17 16:10 UTC, qsm-odoo requested changes
@xlu-odoo @stefanorigano I think you can do better:
![image](https://github.com/user-attachments/assets/27f59674-fb04-4358-a0f6-a2febd873735)

We all agree that the current version has to be improved to be more modern but this new version is worse IMO:
- There is no obvious boundary between the phone and the website.
  - At first glance, I though "why is there a white space at the bottom of my website?"
  - Maybe I am too old but the boundaries on the left and right are so tiny, they just feel like a 1px white line bug to me
- I am not entirely convinced by the white color. I was already not for the website backend (again, very nice IMO for the backend of other apps, but for website... not perfect IMO), but now a website backend white bar followed by a white space followed by a white phone followed by a default white website... this lacks contrast IMO, and this particular shadow you added does not work IMO, it made me feel this was not even a phone picture but fully achieved through CSS :shrug: 

Now I am no designer, I cannot do better but I am sure you can :pray:

2024-12-18 10:04 UTC, qsm-odoo commented
@stefanorigano (cc @xlu-odoo)

> > I think you can do better:
> 
> wau @qsm-odoo , thanks for your encouraging words 😅💪 Let's talk about the taks.

Well, I did mean that as encouraging words :thinking: Otherwise I would just have said "what is this crap?", which you know I would have no problem saying (especially hearing it about my own code for months :joy:). It's not the case at all here: I don't think the result is awful, I think it is worse than what we currently have.

> Competitors are moving in a similar direction and we aim to modernize the interface while maintaining clarity and usability.
> As always, "_Just because others do it wrong doesn’t mean we have to follow_", but I think that's not the case here.

It is IMO. I do think all competitors are worse than us on this subject, and probably your iteration here would still be better than what they have :shrug: 

> > There is no obvious boundary between the phone and the website
> 
> It's not accurate. The contrast between a white snippet's bg and the wrapper shadow is very light but adequate. For reference, that's on the same range of the backend kanban cards.

Kanban cards does not have a website preview inside of them. And they are not alone. And their border are not representing a mobile phone :thinking: I honestly don't understand the comparison. What I am saying here is: at first glance, I don't know what part is the phone and what part is the website (same with competitors). It's not that subjective: if anybody answers that he immediately better sees what part is the phone in this new iteration compared to the current one we have in master, he is **objectively** lying.

Again, not saying anything is awfully bad. Just not better, or worse, than before.

> In any case, dark mode is just one click away, so if you happen to be an unpaired user working on a completely white website, we’ve got you covered. 😉

First, I am not an unpaired user. I don't immediately differentiate the phone from the website, I am not alone with that feeling, it does not make me an unpaired user who should use dark mode :shrug:
I do feel that if you are to represent a phone... assume doing it. Otherwise let's just put a plain rectangle without border: there would not be any "where is the phone issue", but I do think it would also be worse than the "it's obviously a phone" we currently have.

Second, unrelated, but I am not a fan of Odoo dark mode (while being a fan of dark mode everywhere else). At least I was not when it came out, maybe it changed since then and I should give it a deeper try. But it's also that I do like our white design :shrug: As I said over and over :shrug: Which makes it even more strange you would take my previous message badly, it's not like I am always complaining about design choices :shrug: I was probably one of the very few that immediately liked the new white design (with a few reserves for the website screen but :shrug:).

> > At first glance, I though "why is there a white space at the bottom of my website?"
> 
> To ensure that the entire website is visible and not cropped by the device "inner roundness". We didn't want to emulate a fake browser's UI (eg following screenshot), each browser has its own and choosing one would have been arbitrary... competitors use [...]

Again: I think that if you are to preview a phone... you should commit to it. The previous one may feel "old" (3 years old) but there is no denying it is a phone. This one is not that clear: a "big" white area with no button at the bottom, no border on the left/right, ...

> I agree. Initially it was intended as a "security measure" , but it appears unnecessary and potentially misleading... we could test without it (@xlu-odoo )

It would sure fix the "white line bug" but I do think it would make the result further from being a "phone" preview as already explained above.

> I sense some "resistance to change" here... I could be wrong tho 🤷🏻‍♂️

Another team is re-coding the whole website codebase, we changed that preview 3 years ago and I keep saying we should change it again, we changed the whole website functionality from frontend to backend... I don't think I am resistant to change ^^ I am just being honest and stating facts: the new phone preview is not liked at first glance by the website team (agreed, this does not mean much, but still better than my opinion alone), I do think you can do better if you spend more time on it (meaning that in a good way), ...

> Please don’t think your subjective feedback isn’t being taken into consideration

I made my subjective opinion as much of an objective feedback as it can be:
- I checked if others felt the same way. I asked the question without stating anything else than "which do you prefer?" (again: yes, maybe if we ask the whole word in 3 years, we'll have 99% for this iteration, we'll never know)
- I explained what I think is not working

From this point, I think *you* are being subjective (just like I can be when someone points out things they don't like in my work). But if you do feel nothing has to be changed and we should merge it the way it is, then let's go. @lebl-odoo can confirm if I am to go ahead (and I am not calling someone which will agree with me: he does prefer this new design than the old one).

2024-12-18 13:41 UTC, stefanorigano commented
Hello @lebl-odoo 👋

>  The content should be the only concern here.

Yes, we agree. From my perspective, the ideal outcome is that the user doesn’t even notice the wrapper; it’s there simply to subtly confirm they clicked the preview button. Since not all devices have the same shape in reality, it must be clear that it’s a "fake" phone, a metaphor for a real one. That’s why we moved in this direction.

> Maybe we should work to ensure the phone stands out from the background. A first solution could be to add a bolder border on the mobile preview wrapper. Another one is to change the background color to something darker, like #efefef

I tested using the "next color in our grayscale" for consistency and to ensure dark mode is supported out of the box (👇🏼).
If we go with this solution, we’ll need to override the dark-mode version of this screen with a custom color; otherwise, the viewport background will match the top-bar background. It’s not a major issue but something to consider.

That said, the "next gray" looks less polished to me, and I feel like it’s one of those compromises that ends up not satisfying anyone. We may try "something in the middle". I can't explore other solutions tho (I’ll be off for the holidays in a couple of hours), but if you decide to move in a different direction let's keep FP in the loop since he previusly approved the version in this PR ... he may love "next gray" version even more tho, who knows 🤷🏻‍♂️

cc. @xlu-odoo

---

> Otherwise I would just have said "what is this crap?", which you know I would have no problem saying (especially hearing it about my own code for months 😂)

@qmo-odoo , **I know you weren’t referring to me here**, but since this is public, I’d like to clarify that I’ve never said or thought anything like that 😊

---

| #F9FAFB (this PR) | #e7e9ed ("next gray") | #efefef (custom)  | 
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/e6f29b33-005f-4141-a165-ff13d901837c) | ![image](https://github.com/user-attachments/assets/d3bfe177-7b59-4711-8d3c-ed6cfed9c6d7) |  ![image](https://github.com/user-attachments/assets/e92b434e-7d98-4983-9591-250c522b9434) | 
| ![image](https://github.com/user-attachments/assets/7638b646-1a11-4d4f-8b2f-791322059277) |  ![image](https://github.com/user-attachments/assets/57c88e2c-7748-4926-8134-ea71ef335c1d) | //  |

2025-02-13 15:55 UTC, lebl-odoo commented
Someone told me we never finish the discussion here.

The proposal of Stefano suits me and I believe it's a step for a better UX. Except if someone has something to add, I propose to move forward with the custom value (for light mode) and the next gray value (for dark mode). 

I'll ping FP once we merged.

cc @qsm-odoo , @stefanorigano

2025-02-17 10:21 UTC, qsm-odoo commented
@robodoo delegate=bvr-odoo 
@bvr-odoo

2025-02-17 15:07 UTC, xlu-odoo commented
> Hello @xlu-odoo Could you please rebase this PR? I'll review it 😉

Done, thanks :) ( @lebl-odoo ; added sri's "custom value" for LM, and "next gray" for DM )

2025-02-18 16:27 UTC, bvr-odoo requested changes
Here is my review, nice improvement 🤩

Could you also fix this issue -> When the page is displayed at 150% zoom (for example), the mobile image extends beyond the top and bottom of the screen. This issue was already present before, but using an SVG might make it easier to fix. The top and bottom of the phone should always stay within the browser limits and not extend beyond them.
See screenshot:

![image](https://github.com/user-attachments/assets/31c59103-0838-4faf-887a-a469c389acfc)

2025-02-18 16:27 UTC, bvr-odoo commented on addons/website/static/src/img/phone.svg
> Why is there big spacing on the right of that new phone.svg?

same question 😉

2025-02-19 15:06 UTC, xlu-odoo commented
Thanks for the review @bvr-odoo !

> Here is my review, nice improvement 🤩
> 
> Could you also fix this issue -> When the page is displayed at 150% zoom (for example), the mobile image extends beyond the top and bottom of the screen. This issue was already present before, but using an SVG might make it easier to fix. The top and bottom of the phone should always stay within the browser limits and not extend beyond them. See screenshot:
> 

I reworked it to ensure the phone always stays within the browser limits with proper spacing around it, along with some scaling adjustments based on screen size.

> Why is there big spacing on the right of that new phone.svg?

Before the last commit, the SVG intentionally had a long shadow, creating that "big spacing". In this latest update, the shadow is now applied to the div instead of the SVG, making it more maintainable and eliminating any weird positioning for it.

> There is an issue probably caused by this change:
> 
> * Go to edit mode.
> * Enable the mobile preview.
> * Change the header template.
> * The iframe reloads.
> * Bug: the mobile preview is mispositioned. (the same bug occurs for all options that reload the iframe)

Doesn't happen anymore with the new changes.

--

What do you think of the changes?

And I hope it was okay to update/move/remove a few things from inside [website.backend.scss](https://github.com/odoo/odoo/pull/182889/commits/781133db2565937f1f92fdd632d92d3b26e0aa29#diff-0a805a9fc69b270d7ad7dbff324b75124e4fd54131944706aea5b0dd97ca3f7d)
Also, I don't think the theme preview's mobile/desktop feature "exist" anymore. Previously, you could switch between desktop and mobile views before selecting a theme. Now, when you're on the theme preview page and click on it, it directly launches the new 'loading screen' instead. Or maybe i'm missing something.

2025-02-21 13:38 UTC, bvr-odoo requested changes
Thanks for the changes, still a few remarks 😉

2025-02-21 13:38 UTC, bvr-odoo commented on addons/website/static/src/scss/website.backend.scss
> +        transform: translate(-50%, -50%) scale(0.85);
This make the phone device too small on my screen (Philips 243B) compared to how it was before.

![image](https://github.com/user-attachments/assets/b7f9fe17-f04d-4e7e-a3b6-8b6ffcbdae85)

I think that using media queries to define the best height for the mobile device is not the right way to handle this. It should be possible to adapt the height of the device responsively by anchoring it to the top and bottom of the page (with margins, of course). This way, it will adjust dynamically to the window height, pixel by pixel, instead of changing at specific breakpoints. What do you think? Could you check if this is possible, please? 😊

2025-03-31 13:24 UTC, xlu-odoo commented
Hello @bvr-odoo, sorry for this long delay. I've just pushed the requested changes.

Could you take a look again when you have a moment?

( Regarding the height/media queries: right after your review, I did try the approach you suggested, but I couldn’t quite get it to work as expected. I remember trying it from a few different angles, but it just never behaved correctly.. 
I've fine-tuned the values a bit tho. )

2025-04-03 09:02 UTC, bvr-odoo requested changes
Hi @xlu-odoo 
It's still too small on my screen compared to before:
| BEFORE  | AFTER |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/af39b836-0e78-471b-83ef-af69d97c5c46)  | ![image](https://github.com/user-attachments/assets/b1652d64-49c7-4bee-a32d-798890dad817)  |

2025-04-08 11:48 UTC, bvr-odoo approved these changes
LGTM, Nice IMP 👍🏼 Thanks for the work

2025-04-08 11:48 UTC, bvr-odoo commented
@robodoo r+

2025-04-08 15:38 UTC, closed without merging