[FIX] web_editor: make columns added with powerbox have the same size
odoo/odoo pull request #182951
Opened 2024-10-09 12:58 UTC by sobo-odoo

Steps to reproduce:
- In edit mode, drop a "Text-Image" snippet.
- In the text column, add 4 columns with the powerbox (type "/" then "columns").
- In each column, add an image.
 => The two outer columns image have the same size, which is bigger than the inner ones.

This happens because in commit [1], in order for the columns to be well aligned with the rest of the content, the left padding of the first column and the right padding of the last one have been forced to 0px. This resulted in the columns content having different sizes depending on their position.

Moreover, this was not a good solution because if we added more columns (by duplicating them) such that they go on multiple lines, the last one of the first line would not be correctly aligned to the content, because it is not the last column so it would keep its right padding. This would also result in the columns being shifted compared to the first line.

This commit fixes that by removing the rules added by commit [1], as the columns were already aligned without them. The row margins are then set so they compensate the grid item padding, for the case when we are in grid mode, to avoid overflow. Note that if the padding is under 15px, the columns are not aligned anymore, but this is the compromise to have identical columns.

[1]: https://github.com/odoo/odoo/commit/fb55f688f6be2211ebeea4ba431a06230c40fb6b

opw-4172256

2024-10-09 12:58 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/182951.png)](https://mergebot.odoo.com/odoo/odoo/pull/182951)

2024-10-28 08:38 UTC, dmo-odoo commented on addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
> -}
Hello, did you make sure that removing this code did not introduce a regression towards the original issue that it was intended to fix? That is https://www.odoo.com/odoo/1695/tasks/3001988.

2024-10-28 12:21 UTC, dmo-odoo commented on addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
> -}
@sobo-odoo Thank you! 👍

2024-10-31 16:12 UTC, qsm-odoo requested changes
That's the right solution, unfortunately this works for website and knowledge but this breaks the html fields in form views (e.g. tasks) adding an horizontal scrollbar.

The only real fix would be to remove the `overflow: auto;` that is added on the `.note-editable` class for unknown reasons... but that's a far more risky change, especially since I already see some code relying on it being the scrollable element (probably wrongly but...).

I'll resume investigation next week. Maybe in stable we can just apply the patch for website/knowledge only or maybe apply the old system when both `container` and `o_text_column` are on the same element (because that's a thing in backend fields for some reason), then in master make the right solution... I don't know... annoying...

2024-10-31 17:14 UTC, sobo-odoo commented
@qsm-odoo Strange because I tested in a task (this is my first screenshot in the review comment) and I did not have any scrollbar :open_mouth: Maybe I did not test correctly, can you tell me how you have it ? :slightly_smiling_face:

2024-11-02 11:17 UTC, qsm-odoo commented
@sobo-odoo Nothing special... go to your runbot branch, open a project task, add columns, you have a scrollbar.
![image](https://github.com/user-attachments/assets/087a6780-d382-4173-bd73-6832de2117c9)

2024-11-06 18:07 UTC, qsm-odoo approved these changes
As discussed previously, I had to adapt the solution: I am choosing to leave the bug in the backend and fix it for the website. I'll re-assess what I can do without refactoring the whole backend in master.

@robodoo r+

2024-11-06 19:13 UTC, robodoo commented
@sobo-odoo @qsm-odoo staging failed: ci/runbot on 26ade518c4da942401929fb7ed6d4d5bc46184d1 (view more at https://runbot.odoo.com/runbot/build/70287035)

2024-11-07 09:50 UTC, qsm-odoo commented
@robodoo retry

2024-11-07 13:37 UTC, closed without merging