[FIX] website_sale_delivery: update carrier_id of SO on shop/payment
odoo/odoo pull request #183178
Opened 2024-10-10 13:30 UTC by vchu-odoo

Steps to reproduce:
1) Configure 2 carriers with different price and different available countries.
2) Go to /shop and add deliverable product to the cart and checkout
3) Observe that the carrier is chosen for you.
4) Go to /checkout and edit a shipping address changing its country to the available country of the other carrier.
5) Go back to /payment and observe that the carrier is not updated accordingly

Problem: When partner_shipping_id is changed or edited carrier_id is not updated accordingly.

Solution: Check that the carrier set on SO is available and recalculate its rate on shop/payment load.

opw-4202126

2024-10-10 13:31 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183178.png)](https://mergebot.odoo.com/odoo/odoo/pull/183178)

2024-10-10 14:28 UTC, AntoineVDV requested changes

2024-10-10 15:14 UTC, AntoineVDV approved these changes
@robodoo delegate+

2024-10-11 08:54 UTC, vchu-odoo commented
@robodoo fw=no

2024-10-11 08:54 UTC, robodoo commented
Disabled forward-porting.

2024-10-11 14:43 UTC, vchu-odoo commented
@robodoo r+

2024-10-11 17:14 UTC, closed without merging