[IMP] website_blog: some ui improvements
odoo/odoo pull request #183130
Opened 2024-10-10 10:52 UTC by visp-odoo

With this commit, we are changing binocular icon with eye icon and removing `--` from websiteblog sidebar.

task-4246651

2024-10-10 10:52 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183130.png)](https://mergebot.odoo.com/odoo/odoo/pull/183130)

2024-11-05 13:44 UTC, SergeBayet commented
@visp-odoo If this PR is ready to review as it seems to be in the task, please mark it as "Ready for review". Thanks :)

2024-11-05 13:53 UTC, visp-odoo commented
@SergeBayet I have marked this PR "Ready for review".

2024-11-05 13:56 UTC, qsm-odoo commented
@robodoo delegate=SergeBayet 
@SergeBayet

2024-11-05 14:01 UTC, SergeBayet requested changes
LGTM :+1: Can you just add some precision in the commit message such as :
- the "comments/views stat" must be enabled to see the "feature"
- the sidebar in the blog options must be enabled as well
And if you could replace websiteblog by `website_blog` as it is the name of the module.
Don't forget to replicate these changes in the PR description.
Thanks.

2024-11-06 07:55 UTC, SergeBayet commented
@robodoo r+

2024-11-06 10:06 UTC, closed without merging