[IMP] project: calendar view improvements
odoo/odoo pull request #183482
Opened 2024-10-14 03:51 UTC by mjvi-odoo

- Add a 'View Tasks' primary button to open tasks associated with the project.
- Rename 'Edit' button to 'Edit Project' and change it to secondary.

task-4244705

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-14 03:51 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183482.png)](https://mergebot.odoo.com/odoo/odoo/pull/183482)

2024-10-21 12:15 UTC, ppr-odoo commented on addons/project/static/tests/project_project_calendar.test.js
> +    ]);
We should verify the view task action.

2024-10-21 12:19 UTC, ppr-odoo commented on addons/project/static/tests/project_models.js
> +    date = fields.Date();
```suggestion
    date = fields.Date(string="Expiration Date");
```
To avoid confusion, we should give the string.

2024-10-21 12:31 UTC, ppr-odoo commented
Thanks for the work, @mjvi-odoo. I left some comments. please take a look at them when you have time.

2024-12-11 16:48 UTC, RaoufGhrissi requested changes
Thanks for your work, i added some comments.

Make sure to write a significant commit body that describes what you have done. 
don't forget to change the pr status to ready for review.

Have a nice evening

2024-12-11 16:48 UTC, RaoufGhrissi commented on addons/project/static/tests/project_project_calendar.test.js
> +    mockDate("2024-01-03 12:00:00", +0);
```suggestion
    mockDate("2024-01-03 12:00:00", 0);
```

2024-12-11 16:48 UTC, RaoufGhrissi commented on addons/project/static/tests/project_project_calendar.test.js
> +test("check 'Edit' and 'View Tasks' buttons is in Project Calendar Popover", async () => {
```suggestion
test("check 'Edit' and 'View Tasks' buttons are in Project Calendar Popover", async () => {
```

2024-12-11 16:48 UTC, RaoufGhrissi commented on addons/project/static/tests/project_project_calendar.test.js
> +    });
```suggestion
    onRpc(({ method, model, args }) => {
        if (method === "get_formview_id") {
            expect(model).toBe("project.project");
            expect(args[0]).toEqual([1]);
            return false;
        } else if (model === "project.project" && method == "action_view_tasks") {
            expect.step("view tasks");
            return false;
        }
    });
```

2025-02-05 11:24 UTC, RaoufGhrissi approved these changes

2025-02-13 08:16 UTC, xavierbol approved these changes
LGTM, thanks for your work. 🙂

2025-02-20 15:55 UTC, xavierbol commented on addons/project/static/tests/project_project_calendar.test.js
> +        } else if (model === "project.project" && method == "action_view_tasks") {
```suggestion
        } else if (model === "project.project" && method === "action_view_tasks") {
```

2025-02-24 08:24 UTC, xavierbol commented
robodoo r+

2025-02-24 09:47 UTC, closed without merging