[FIX] hr_recruitment: prevent error when refusing duplicate application
odoo/odoo pull request #183517
Opened 2024-10-14 08:55 UTC by reka-odoo

When the user refuses the application with its duplicate application,
a traceback will appear.

Steps to reproduce the error:
- Go to Recruitment > All Applications >
  Create 2 applications with the same candidate
- Open that application > Refuse > Select refuse reason >
  Select other Duplicate application > Refuse

Traceback:
```
AttributeError: 'hr.applicant' object has no attribute '_get_similar_applicants_domain'
  File "odoo/http.py", line 2364, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1891, in _serve_db
    return self._transactioning(
  File "odoo/http.py", line 1954, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "odoo/service/model.py", line 137, in retrying
    result = func()
  File "odoo/http.py", line 1921, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 2168, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 330, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 728, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 40, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 517, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "addons/hr_recruitment/wizard/applicant_refuse_reason.py", line 75, in action_refuse_reason_apply
    duplicate_domain = self.applicant_ids._get_similar_applicants_domain()
```

https://github.com/odoo/odoo/blob/e4a4806e5c58c599815204a73c78a228ee230613/addons/hr_recruitment/wizard/applicant_refuse_reason.py#L75
``_get_similar_applicants_domain`` method is removed in this commit 9359d08d331beac389fde0e6c82c895341f7dbc5 but still used here.
So, it will lead to the above traceback.

sentry-5986653915

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-14 08:55 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183517.png)](https://mergebot.odoo.com/odoo/odoo/pull/183517)

2024-10-16 08:16 UTC, adwid commented
robodoo delegate=@nboulif

2024-10-23 05:01 UTC, reka-odoo commented
Hello @nboulif :wave: 
Can you please review this PR?
Thanks!

2024-10-24 12:08 UTC, nboulif requested changes

2024-10-24 12:42 UTC, reka-odoo commented on addons/hr_recruitment/wizard/applicant_refuse_reason.py
>              duplicate_domain = expression.AND([duplicate_domain, [('application_status', '!=', 'refused')]])
Hello @nboulif :wave: 
Requested changes are done.
Thanks for the review! :slightly_smiling_face:

2024-10-24 13:23 UTC, jugj-odoo commented
Hello @reka-odoo, thanks for your work, as a note, the method has actually been replaced by _get_similar_candidates_domain, so we should fix it around that

2024-10-24 13:33 UTC, jugj-odoo commented
Hello, there's an R&D task to fix this already :( https://www.odoo.com/odoo/project/1251/tasks/4269955

2025-08-04 08:25 UTC, closed without merging