[IMP] point_of_sale: hide dismiss button for review order dialog
odoo/odoo pull request #183689
Opened 2024-10-15 07:34 UTC by paso-odoo

Before this commit:
- The dismiss button on the review order popup is no longer required.

After this commit:
- Made a generic component for a confirmation dialog and use it in the review order dialog to achieve the functionality of hiding the dismiss button.

task-4246554

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-15 07:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183689.png)](https://mergebot.odoo.com/odoo/odoo/pull/183689)

2024-11-14 10:59 UTC, davidmonnom requested changes
By pressing `esc` button, it will confirm the dialog, wierd behavior. Ask in the spec if you should do something about that

2024-11-14 10:59 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/generic_components/pos_dialog/pos_dialog.xml
We don't use `generic_components` folder anymore, just put it in `components`

2024-11-19 04:59 UTC, paso-odoo commented on addons/point_of_sale/static/src/app/generic_components/pos_dialog/pos_dialog.xml
Updated!

2024-11-19 05:01 UTC, paso-odoo commented
> By pressing `esc` button, it will confirm the dialog, wierd behavior. Ask in the spec if you should do something about that

@davidmonnom 
I have handled this case now.
Thanks for pointing it out!

2025-06-06 06:40 UTC, closed without merging