[IMP] sale_loyalty: wallet topup on portal
odoo/odoo pull request #183678
Opened 2024-10-15 05:57 UTC by dere-odoo

Prior this commit:
- Portal users could not topup their wallet directly from portal page

Post this commit:
- Added Topup option for wallet on portal card dialog
- Added Payment flow for the same

task-4243458

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-15 05:57 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183678.png)](https://mergebot.odoo.com/odoo/odoo/pull/183678)

2025-02-17 14:34 UTC, anko-odoo requested changes
Hello, good job on the task. Mostly nitpick and some clarification.

2025-02-17 14:34 UTC, anko-odoo commented on addons/website_sale_loyalty/views/loyalty_program_views.xml
> +                <div invisible="program_type!='ewallet'" class="alert alert-warning mt-1" role="alert">To be able to top up eWallet from the portal, eWallet products must be published</div>
>100
```suggestion
                <div 
                    invisible="program_type!='ewallet'" 
                    class="alert alert-warning mt-1" 
                    role="alert"
                >
                    To be able to top up eWallet from the portal, eWallet products must be published
                </div>
```

2025-02-18 05:55 UTC, dere-odoo commented on addons/loyalty/static/src/js/portal/loyalty_card_dialog/loyalty_card_dialog.xml
> +                            <div class="col-7 text-truncate">
It's for the description on the card dialog
before this change
![image](https://github.com/user-attachments/assets/fab997fd-2ed9-4bc0-be52-43966e87eb68)

after this change
![image](https://github.com/user-attachments/assets/faabd3cd-0ed0-47ca-8484-e9d804cf4139)

2025-02-18 12:58 UTC, anko-odoo requested changes
Small comments. Almost there!

2025-02-18 12:58 UTC, anko-odoo commented on addons/loyalty/controllers/portal.py
> +        :return(dict): A dictionary with card history values and trigger products.
When website_sale is not installed, this function is stil called but no trigger products are returned since they are retirned on an override.
```suggestion
        :return(dict): A dictionary with card history values.
```

2025-02-18 12:58 UTC, anko-odoo commented on addons/website_sale_loyalty/controllers/portal.py
> +        program.
Now here it's the other way around, this function is responsible for adding trigger products but the ovveride does not retrieve the card history values.
```suggestion
        Add published trigger products for the loyalty
        program.
```

2025-02-19 09:27 UTC, anko-odoo approved these changes
Hello, LGTM :) Good work on the task.

2025-04-01 09:58 UTC, Demesmaeker requested changes
Hello @dere-odoo :duck: 

Well done! Some small comments, mostly nitpicking, and then it'll be ready to go!

Have a nice day!

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/static/src/js/portal_loyalty_card.xml
> +
```suggestion
```

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/views/loyalty_program_views.xml
> +                     published
```suggestion
                     published.
```

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/views/loyalty_program_views.xml
> +            </div>
This warning would be better if dynamic.
Like: no product set or products set with at least one that's non published ==> show warning.
But if all the products set are published, then why showing the warning?

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +        """
```suggestion
        """ Add published trigger products for the loyalty program. """
```

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +                ),
```suggestion
                'total_price': format_amount(
                    self.env, product.lst_price, request.env.company.currency_id
                ),
```

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +            })
```suggestion
        trigger_products = program_sudo.trigger_product_ids.filtered(lambda p: p.website_published)
        currency = request.env.company.currency_id
        res['program']['trigger_products'] = [{
            'id': product.id, 'total_price': format_amount(self.env, product.lst_price, currency)
        } for product in trigger_products]
```

2025-04-01 09:58 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +class CustomerPortalLoyalty(CustomerPortal):
```suggestion
class CustomerPortalLoyalty(loyalty_portal.CustomerPortalLoyalty):
```

2025-04-01 10:16 UTC, dere-odoo commented on addons/website_sale_loyalty/controllers/portal.py
> +            })
If we consider the worst case scenario where every trigger product is website_published then this approach will run `for loop` twice on same records

2025-04-01 11:12 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +            })
You can add a `if product.website_published` in the list comprehension if you prefer

2025-04-03 12:25 UTC, Demesmaeker requested changes
Hello @dere-odoo :duck: 

Small changes ^^

Have a nice day!

2025-04-03 12:25 UTC, Demesmaeker commented on addons/website_sale_loyalty/models/loyalty_program.py
> +    hide_trigger_product_warning = fields.Boolean(compute="_compute_hide_trigger_product_warning")
```suggestion
    hide_trigger_product_warning = fields.Boolean(compute='_compute_hide_trigger_product_warning')
```

2025-04-03 12:25 UTC, Demesmaeker commented on addons/website_sale_loyalty/models/loyalty_program.py
> +    hide_trigger_product_warning = fields.Boolean(compute="_compute_hide_trigger_product_warning")
```suggestion
    show_trigger_product_warning = fields.Boolean(compute="_compute_hide_trigger_product_warning")
```
Or even, for clarity:
```suggestion
    show_non_published_product_warning = fields.Boolean(compute="_compute_hide_trigger_product_warning")
```
My reasoning is that the default value is False, "showing" is the action. Additionally, we try to keep var names positive, but that's more a personal taste.

2025-04-03 12:25 UTC, Demesmaeker commented on addons/website_sale_loyalty/controllers/portal.py
> +class WebsiteSaleCustomerPortalLoyalty(CustomerPortalLoyalty):
```suggestion
from odoo.addons.loyalty.controllers import portal as loyalty_portal


class CustomerPortalLoyalty(loyalty_portal.CustomerPortalLoyalty):
```

2025-04-03 15:07 UTC, Demesmaeker approved these changes
Hello @dere-odoo :duck: 

Thank you very much for your changes!

@robodoo r+

2025-04-03 19:02 UTC, closed without merging