[FIX] sale_stock,stock: fix traceback  if user click return picking for exchange
odoo/odoo pull request #183865
Opened 2024-10-16 06:28 UTC by alsh-odoo

Currently, a traceback occurs when the user tries to click return for exchange button.

To reproduce this issue:

1) Install `stock`
2) Create a new receipt picking with stock moves and quantity 
3) Click on the `validate` button and then the `return` button
4) Update the return quantity and click `return for exchange`

Error:- 
```
AttributeError: 'stock.move' object has no attribute 'sale_line_id'
```

The `sale_line_id` is defined in `stock.move` from  `sale_stock` module. 
https://github.com/odoo/odoo/blob/2be7f413493a6ad43980eb031b8383deb3a706c0/addons/sale_stock/models/stock.py#L16-L17
If the sales module is not installed, then the move does not contain any sale_line_id.
which leads to the traceback mentioned above.

https://github.com/odoo/odoo/blob/2be7f413493a6ad43980eb031b8383deb3a706c0/addons/stock/wizard/stock_picking_return.py#L197

sentry-5993887458

2024-10-16 06:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/183865.png)](https://mergebot.odoo.com/odoo/odoo/pull/183865)

2024-10-22 12:38 UTC, DjamelTouati requested changes
LGTM, thank you for the fix! Could you just add a small test, please ? Thank you ;)

2024-10-22 12:53 UTC, alsh-odoo commented
I attempted to write a test case before you requested one. 
However, when I ran some existing test cases in the stock, I encountered unexpected tracebacks.
I'm unsure of the exact reason for this. :man_shrugging: 

Could you please assist me in understanding what might be going wrong? 

Thank You :slightly_smiling_face:

2024-11-06 04:59 UTC, maan-odoo commented
Hey @DjamelTouati 
Could you please look at this PR?
Thanks!

2024-11-06 10:34 UTC, Whenrow approved these changes

2024-11-06 10:34 UTC, Whenrow commented on addons/stock/wizard/stock_picking_return.py
> +        return {
```suggestion
        self.ensure_one()
        return {
```

2024-11-06 10:34 UTC, Whenrow commented on addons/stock/wizard/stock_picking_return.py
> +        return {
little change before merging

2024-11-06 11:48 UTC, Whenrow commented
robodoo r+

2024-11-06 14:26 UTC, closed without merging