[FIX] website_sale: ensure delivery method is set during checkout
odoo/odoo pull request #184098
Opened 2024-10-17 11:34 UTC by ushyme

In Mexican (or Colombian) e-commerce websites, a customer may face an issue where they are unable to confirm an order because no delivery method is selected.

### Steps to reproduce

- Install `l10n_mx_edi_website_sale`
- Ensure the website is configured with a Mexican company
- Enable 'Automatic Invoice' in website settings
- As a public user, proceed through checkout and try to confirm the order

The issue occurs if the user is prompted to fill in delivery information and hasn't previously provided an address. This can be consistently reproduced using a new incognito session.

Upon attempting to confirm the order, the following error is shown: "No shipping method is selected."

### Cause

The delivery information form (`/shop/address/submit`) normally redirects to `/shop/checkout`, where the user selects a delivery method. However, the `_get_extra_billing_info_route` hook can alter the redirect, bypassing the checkout step and causing the delivery method to remain unset.

opw-4205135
opw-4222398

2024-10-17 11:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184098.png)](https://mergebot.odoo.com/odoo/odoo/pull/184098)

2024-10-28 08:54 UTC, vchu-odoo requested changes
Hello,

Thank you for the fix!

However, I believe that we should fix the flow rather than redirecting the user when the info is missing. As I can see, the flow breaks only for the public user. The issue can be in the `shop_address_submit`   function, as it assigns the wrong callback. We need to redirect to checkout first (according to `_get_checkout_steps`  ): https://github.com/odoo/odo/blob/sas-17.4/addons/website_sale/controllers/main.py#L1233.
I believe that `_get_extra_billing_info_route`   should set the callback only if `if not is_anonymous_cart:`   WDYT?

2024-10-28 19:16 UTC, masi-odoo commented
Hello @ushyme could you take a look at the last comments?

This fix is pretty urgent since clients on these localizations are not able to sell through their eCommerce environments. 

Let me know if you need anything else on our side. Best!

2024-10-30 12:45 UTC, vchu-odoo approved these changes
As it is risky to change the flow in stable, we will proceed with this fix and improve it in master.
Thank you for your investigation!

2024-10-30 12:48 UTC, chevalierv commented
@robodoo r+

2024-10-30 16:12 UTC, closed without merging

2024-10-30 17:09 UTC, masi-odoo commented
Hello @ushyme @vchu-odoo I was doing more tests and I see that the "Invoicing Info" step is still duplicated.

This could be a pain for the final customer, since he will have to do a double entry of their fiscal information to purchase. See the next video with the example:

https://github.com/user-attachments/assets/101a0392-8c44-4594-8ac8-6baf25e7f709

Could you take a look? Should we fix in this PR or a new one?

CC @ren-odoo

2024-10-31 07:57 UTC, vchu-odoo commented
Hello, @masi-odoo!

I do not see it as a big problem for a customer since the data entered the first time would be prefilled the next time. Here we had to choose between fixing the flow and caring about customization. Since it is a stable version we chose the later. @ushyme will fix the flow in master.

Sorry for the inconvenience!

cc @chevalierv

2024-10-31 16:07 UTC, masi-odoo commented
@vchu-odoo thanks for the clarification, it does still worry me since in the video I attached on my last comment I did have to re-enter the data the second time the "Invoicing Info" step appeared, but it is true that for a next sale the information will already be pre-filled.

@ushyme can you tag me in the PR for the fix in Master when you work on it? Thanks!