[IMP] point_of_sale: display combo line amount on Receipt
odoo/odoo pull request #184034
Opened 2024-10-17 05:28 UTC by parp-odoo

In this commit:
===============
- The receipt will display shows the amounts for the combo line based on the selected product prices.
- Hides individual order line amounts associated with the combo.

task- 4229373

2024-10-17 05:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184034.png)](https://mergebot.odoo.com/odoo/odoo/pull/184034)

2024-11-27 14:56 UTC, adgu-odoo requested changes
After discussion with MOBT, could you also remove the price on the combo lines on the customer screen and the order widget. So I guess the best solution would maybe to change the `getPriceString` method ?

2024-11-28 10:21 UTC, parp-odoo commented
@adgu-odoo ,
Changes are done!
Could you please check?

2024-12-10 15:30 UTC, caburj commented
rebase please

2024-12-11 08:30 UTC, parp-odoo commented
@caburj ,
Done

2024-12-16 09:11 UTC, adgu-odoo commented on addons/point_of_sale/static/src/app/models/pos_order_line.js
> +                          };
```suggestion
                          return {
                              priceWithTax: acc.priceWithTax + clPrices.allUnitPrices.priceWithTax,
                              priceWithoutTax: acc.priceWithoutTax + clPrices.allUnitPrices.priceWithoutTax,
                          };
```

2024-12-16 09:11 UTC, adgu-odoo commented on addons/point_of_sale/static/src/app/models/pos_order_line.js
> +                : this.getAllPrices(1);
```suggestion
                : this.allUnitPrices;
```

2024-12-16 09:11 UTC, adgu-odoo commented on addons/point_of_sale/static/src/app/models/pos_order_line.js
> +                : this.getAllPrices(1);
`allUnitPrices` is cached when called, so calling it is better than calling `getAllPrices(1)` as if the value did not changed, we should not recompute it

2024-12-16 10:03 UTC, adgu-odoo approved these changes

2024-12-16 13:04 UTC, adgu-odoo commented
robodoo r+

2024-12-16 23:37 UTC, closed without merging