Master products snippets template visp
odoo/odoo pull request #184062
Opened 2024-10-17 08:49 UTC by visp-odoo

Work In Progress !

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-17 08:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184062.png)](https://mergebot.odoo.com/odoo/odoo/pull/184062)

2024-12-03 15:14 UTC, msh-odoo reviewed
Improve commit message with details, commit is not as per guidelines.

2024-12-03 15:14 UTC, msh-odoo commented on addons/website_sale/views/snippets/snippets.xml
> +        <t t-snippet="website_sale.s_dynamic_filter_template_product_product_borderless_2" string="Products" group="products"/>
```s_dynamic_filter_template_product_product_borderless_2``` -> ```s_dynamic_filter_template_product_product_borderless```

2024-12-04 09:07 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +                                <input type="hidden" name="product-id" data-product-id="52"/>
No, we don't really need hidden input element.

2024-12-10 06:39 UTC, visp-odoo commented on addons/website_sale/static/tests/tours/website_sale_snippet_products.js
> +        content: 'Click on dropped snippet to open options',
In this tour they have used single quotes every were. So, I used single quoets to be aligned with.

2024-12-10 06:40 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +                                        <button type="button" role="button" class="btn btn-primary js_add_cart w-100" title="Add to Cart" data-product-id="52" data-product-template-id="39" data-produ
No, we don't need this in any template because its just preview templates. I will make sure to remove it.

2024-12-10 06:40 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +                                                <i class="fa fa-fw fa-shopping-cart" contenteditable="false">​</i>
No

2024-12-10 06:44 UTC, visp-odoo commented on addons/website_sale/static/tests/tours/website_sale_snippet_products.js
> +        content: 'Click on dropped snippet to open options',
In this tour they have used single quotes every were. So, I used single quoets to be aligned with.

2024-12-10 06:57 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +            </div>
They have added this next/previous buttons in `s_dynamic_snippet_produtc_preview_data`. So I added this next/previous buttons in every data preview.

2024-12-10 07:16 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +                                <div class="o_carousel_product_card card w-100 rounded-0 border-top-0 border-start-0" data-url="/shop/rent001-projector-160">
No, we don't need `data-url`. I will remove it.

2024-12-10 07:25 UTC, msh-odoo commented on addons/website_sale/static/tests/tours/website_sale_snippet_products.js
> +        content: 'Click on dropped snippet to open options',
Let's follow the guidelines in new code we add.

2024-12-10 07:26 UTC, msh-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +            </div>
In Preview template we don't need it

2024-12-10 07:27 UTC, visp-odoo commented on addons/website_sale/static/tests/tours/website_sale_snippet_products.js
> +        content: 'Click on dropped snippet to open options',
ok :+1:

2024-12-10 07:27 UTC, visp-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +            </div>
ok :+1:

2024-12-10 07:50 UTC, msh-odoo reviewed
I was thinking if we can adapt product_snippet_template_data.xml in such a way that we don't need to copy/paste these templates, it is possible to do.

2025-02-18 09:17 UTC, SergeBayet requested changes
Hi @visp-odoo great PR. Thanks. For a first pass, I have a comment (see below). Could you mark this PR as ready for review and I'll recheck. You can clean up the commits (maybe squash them) :+1:

2025-02-18 09:17 UTC, SergeBayet commented on addons/website_sale/static/tests/tours/website_sale_snippet_products.js
> +const productsSnippet = {id: "s_dynamic_filter_template_product_product_borderless_1", name: "Products", groupName: "Products"};
```suggestion
const productsSnippet = {
    id: "s_dynamic_filter_template_product_product_borderless_1",
    name: "Products",
    groupName: "Products",
};
```

2025-02-18 15:13 UTC, chevalierv reviewed
Hello @visp-odoo @SergeBayet,

Could you provide more details on your changes? I’m surprised by such a large diff just to move a simple dropdown choice to a modal.

I noticed that it's no longer possible to change the template from the editor, was this intentional? Should customers add a new block to change the template?

Also, are we planning to remove the "blocks" column? I'm confused by how it works, I need to drag blocks where I want but It's also fine if I just click on them. At this point, I think clicking directly where I want to add a snippet to open the modal would be more intuitive.

Looking forward to your insights. 

Have a nice day!

2025-02-18 15:34 UTC, SergeBayet commented
> Hello @visp-odoo @SergeBayet,
> 
> Could you provide more details on your changes? I’m surprised by such a large diff just to move a simple dropdown choice to a modal.
> 
> I noticed that it's no longer possible to change the template from the editor, was this intentional? Should customers add a new block to change the template?
> 
> Also, are we planning to remove the "blocks" column? I'm confused by how it works, I need to drag blocks where I want but It's also fine if I just click on them. At this point, I think clicking directly where I want to add a snippet to open the modal would be more intuitive.
> 
> Looking forward to your insights.
> 
> Have a nice day!

That's a question for @lebl-odoo regarding the task... :)

2025-02-18 16:03 UTC, lebl-odoo commented
Hello @chevalierv 

> I noticed that it's no longer possible to change the template from the editor, was this intentional? Should customers add a new block to change the template?

Indeed, we want to remove templates options of our snippets for the benefit of our new snippets dialog. We already did the job for a lot of snippets, now we focus on snippets related to records (blog, product, and so on). 

How to replace an existing snippet with another one? We have a "replace" (center of the screen) button when you click on your snippet

![image](https://github.com/user-attachments/assets/e911f9c5-51f7-4bc3-8f78-344576542669)

Here an example of the expected result (with s_masonry):
![image](https://github.com/user-attachments/assets/1ee674a5-b71a-4dfb-9bea-4b3eeebbbe52)

> Also, are we planning to remove the "blocks" column? I'm confused by how it works, I need to drag blocks where I want but It's also fine if I just click on them. At this point, I think clicking directly where I want to add a snippet to open the modal would be more intuitive.

Your feedback is one more feedback about this flow. For now, we don't agree with FP, but I hope it will change one day :) We would like to review a bit how it's working now by what you described.

Hope it clarifies the vision of the website builder.

2025-02-18 16:13 UTC, chevalierv commented
Hello @lebl-odoo 

Thanks for the detailed answer! I don't find this button very intuitive but indeed, it works! My bad 😅 

I still stand by my previous technical point:
> Could you provide more details on your changes? I’m surprised by such a large diff just to move a simple dropdown choice to a modal.

There is 500 lines that shouldn't be there IMO, perhaps to be replaced by images or a better way to generate preview using existing templates? 

Let me know what's your opinion on the matter!

cc @SergeBayet @visp-odoo

2025-02-18 17:30 UTC, msh-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
> +    </template>
@chevalierv Image will obviously work but as you know for other snippet preview we did not added image so same way here we did not added image.

2025-02-18 17:38 UTC, msh-odoo commented
> Hello @visp-odoo @SergeBayet,
> 
> Could you provide more details on your changes? I’m surprised by such a large diff just to move a simple dropdown choice to a modal.
> 
> I noticed that it's no longer possible to change the template from the editor, was this intentional? Should customers add a new block to change the template?
> 
> Also, are we planning to remove the "blocks" column? I'm confused by how it works, I need to drag blocks where I want but It's also fine if I just click on them. At this point, I think clicking directly where I want to add a snippet to open the modal would be more intuitive.
> 
> Looking forward to your insights.
> 
> Have a nice day!

The code actually adds design for all layout which were previously there in sidebar, something like we did for Masonry snippet in master https://github.com/odoo/odoo/pull/183755.

2025-02-19 06:35 UTC, msh-odoo commented on addons/website_sale/views/snippets/s_dynamic_snippet_products_preview_data.xml
@chevalierv I do agree, maintaining two template adds complexity, will check alternatives, Thanks.

2025-02-21 06:56 UTC, SergeBayet commented
@visp-odoo You can switch this one to "draft" since it's a work in progress. Thanks.

2025-03-21 10:27 UTC, msh-odoo reviewed
Make sure other dynamic snippets used in Blog, Events etc. are working as expected.

2025-11-13 14:16 UTC, msh-odoo commented
Closing this PR, as this is not needed and task is also cancelled.

2025-11-13 14:16 UTC, closed without merging