[FIX] point_of_sale: edit product dialog empty
odoo/odoo pull request #184063
Opened 2024-10-17 08:55 UTC by meji-odoo

Before this commit:
===
- The product edition dialog was empty.

After this commit:
===
- The product edition dialog is no longer empty.

task-4264198

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-17 08:55 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184063.png)](https://mergebot.odoo.com/odoo/odoo/pull/184063)

2024-10-17 09:17 UTC, paso-odoo commented on addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.js
> +        this.pos.editProduct(this.props.productTemplate.product_variant_ids[0]);
I'm okay with the fix as I can see the same behavior on the product info popup.

https://github.com/odoo/odoo/blob/master/addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js#L456

2024-10-23 13:27 UTC, davidmonnom requested changes
Thats not the good way to do. You need to change the product backend view to use the one of product.template.

So this method should be updated:
```js
    async editProduct(product) {
        this.action.doAction(
            product
                ? "point_of_sale.product_product_action_edit_pos"
                : "point_of_sale.product_product_action_add_pos",
            {
                props: {
                    resId: product?.id,
                    onSave: (record) => {
                        this.data.read("product.product", [record.evalContext.id]);
                        this.action.doAction({
                            type: "ir.actions.act_window_close",
                        });
                    },
                },
            }
        );
    }
```

PS: We'll not allow the editing of specific variant.

2024-10-24 06:48 UTC, meji-odoo commented
@davidmonnom 
Changes are done :)

2024-10-24 08:24 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/store/pos_store.js
> +                ? "point_of_sale.product_template_action_edit_pos"
The add action should be also for template.

2024-10-28 04:41 UTC, meji-odoo commented
@davidmonnom
Changes are done :)

2024-12-09 09:17 UTC, davidmonnom approved these changes
@robodoo r+

2024-12-09 10:00 UTC, robodoo commented
@meji-odoo @davidmonnom linked pull request(s) odoo/upgrade#6653 not ready. Linked PRs are not staged until all of them are ready.

2024-12-09 16:53 UTC, closed without merging