[FIX] website: restore "Layout" and "Content Width" options in carousels
odoo/odoo pull request #184111
Opened 2024-10-17 12:04 UTC by sobo-odoo

In commit [1], the carousels have been redesigned. However, with it, the "Layout" and the "ContentWidth" options have been removed from some of them. They can therefore not be toggled to grid mode anymore, and their container width cannot be changed, which could have been useful now that the arrows can be hidden.

This commit restores these options for the `s_carousel` snippet. Note that the `s_carousel_intro` one redefined these options, which is why it has them. The other ones (i.e. `s_image_gallery`, `s_quotes_carousel` and `s_quotes_carousel_minimal`) do not need them.

[1]: https://github.com/odoo/odoo/commit/3deb8050831c69ca1e32039622b322ffa38cc497#diff-934f432382bbc5c89d776f677d71ef50392d8652b2e9fa7bba3ff39475b842ae

task-4263725

2024-10-17 12:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184111.png)](https://mergebot.odoo.com/odoo/odoo/pull/184111)

2024-10-25 08:12 UTC, sobo-odoo commented
Note for the reviewer: some additional changes need to be done on master, in order to remove the duplicated Layout and ContainerWidth options from the carousel_intro snippet => we could have just added the selector in the existing ones, instead of duplicating

2024-10-25 08:37 UTC, qsm-odoo commented
@robodoo delegate=SergeBayet 
@SergeBayet

2024-10-27 11:10 UTC, SergeBayet requested changes
LGTM. :+1: Just a little remark, see below.

2024-10-27 11:10 UTC, SergeBayet commented on addons/website/static/src/snippets/s_carousel/001.scss
> +        }
```suggestion
        &.s_carousel_arrows_hidden .carousel-item {
            @include media-breakpoint-up(md) {
                padding: 0; // Full-width container when arrows are hidden
            }
        }
```

2024-10-29 12:49 UTC, sobo-odoo commented
@SergeBayet I made the changes :slightly_smiling_face:

2024-11-05 08:50 UTC, SergeBayet approved these changes
LGTM! :+1:

2024-11-05 08:50 UTC, SergeBayet commented
@robodoo r+

2024-11-05 11:38 UTC, closed without merging