[FIX] payment_authorize: fix validation currency
odoo/odoo pull request #184226
Opened 2024-10-17 23:25 UTC by adda-odoo

Issue -->

The field `available_currency_ids` is an empty recordset since `authorize` supports all currencies.
We're assuming that `authorize` supports all currencies because it uses the base `_get_supported_currencies` 
method which returns all currencies.

Solution --> Return the company currency as validation currency.

opw-4252974

2024-10-17 23:25 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184226.png)](https://mergebot.odoo.com/odoo/odoo/pull/184226)

2024-10-18 08:32 UTC, AntoineVDV reviewed
Hi @adda-odoo, the `available_currency_ids` field should always hold exactly one currency. The "onboarding" could probably be improved to ensure it's set, but I don't think it's correct to always use the company's currency for validation transactions.
See https://github.com/odoo/odoo/blob/17.0/addons/payment_authorize/models/payment_provider.py#L35-L43

2024-10-18 19:25 UTC, adda-odoo commented
> field should always hold exactly one currency

I see. The compute method for the field sets it to None to signify support for all currencies. https://github.com/odoo/odoo/blob/d07a6969903705f5676cc3052c3fba78bdf76f45/addons/payment/models/payment_provider.py#L202-L207 and so the constraint never complains. 

I added a compute override to set the `require_currency` to true so that the constraint is put to use in case a user tries to add multiple currencies.

2024-10-21 14:57 UTC, AntoineVDV requested changes
Making the currency required doesn't work because it breaks the Authorize-specific actions to set the client key and currency: you have to click "set currency" to set the currency automatically, but before that, you need to set the currency manually...

I think that in 17.0, we could maybe (to check and test) simply remove the `_get_validation_currency` override in `payment_authorize`.

2024-10-22 07:41 UTC, AntoineVDV approved these changes
@robodoo r+

2024-10-22 10:11 UTC, closed without merging