[IMP] website: introduce `s_comparisons_horizontal` snippet
odoo/odoo pull request #184281
Opened 2024-10-18 10:45 UTC by mano-odoo

This commit introduces the `s_comparisons_horizontal` snippet.

task-4105264

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-18 10:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184281.png)](https://mergebot.odoo.com/odoo/odoo/pull/184281)

2024-10-22 08:27 UTC, chgo-odoo requested changes
Thanks @mano-odoo 👍 

I left some comments, some of them are coming from the default `s_comparisons` snippet as you duplicated some part of that code 😅 We should probably open a PR to fix it there as well.

2024-10-22 08:27 UTC, chgo-odoo commented on addons/website/views/snippets/s_comparisons_horizontal.xml
> +                                    <h5 class="card-title">Professional</h5>
Going from `h3` (Our Pricing) to `h5` (card-title) does not seem optimal as you're skipping headings levels. I'd suggest this instead : 

`<h2 class="h3-fs">Our Pricing</h2>`

and 

`<h3 class="card-title h5-fs">Professional</h3>`

Could you adapt the other occurrences as well?

2024-10-22 08:27 UTC, chgo-odoo commented on addons/website/views/snippets/s_comparisons_horizontal.xml
> +                        </div>
Adapt the other card as well 😉 
```suggestion
                        <div class="card-footer" style="text-align: center;">
                            <small>Instant setup, satisfied or reimbursed.</small>
                        </div>
```

2024-10-25 09:05 UTC, chgo-odoo approved these changes
LGTM

2024-11-05 13:11 UTC, lebl-odoo commented
@mano-odoo 

In mobile, shouldn't we be able to get this result (from "old" comparison snippet)?

![image](https://github.com/user-attachments/assets/33b8e806-2306-41ae-8614-3799d004f67e)

I know we are able to do it ourselves by switching device preview and adjusting the mobile view, but I'm wondering if it shouldn't be the default behavior. What do you think?

When I change position order from "price" and "benefits" columns, I got this: a border-right linked to the "price" column
![image](https://github.com/user-attachments/assets/9d188dbd-ad4b-4712-a15f-f10eb5687e78)

(here, by default: )
![image](https://github.com/user-attachments/assets/0a436571-7a65-46e8-91ef-3d33d694da01)

2024-11-08 12:53 UTC, mano-odoo commented
Hello @lebl-odoo you're absolutely right, I was stubborn with the shadow to split the two columns, but it's better without since the users doesn't have much control on it. Plus it allows to use the `col-12` on mobile to provide the result you suggested.

This is what we get now:
| Desktop | Mobile |
|--------| ---- |
| ![image](https://github.com/user-attachments/assets/9c1cab3d-5170-4662-a993-976058c0be66) | ![image](https://github.com/user-attachments/assets/6a2e94cc-9fef-4203-a97d-6875380ebd53) |

2024-11-08 14:03 UTC, lebl-odoo commented
Nice, that's fine for me @mano-odoo :)

2025-02-10 14:25 UTC, mano-odoo commented
@qsm-odoo could you have a look? Thanks 🙏

2025-02-11 14:19 UTC, bvr-odoo requested changes
Hello @mano-odoo thanks for the work 👍🏼 
Here is some remarks

2025-02-11 16:22 UTC, mano-odoo commented
Req changes https://github.com/odoo/odoo/compare/4e4da0f0297d27192bd9b5bb6bb8f5a232f2e040..23d14d823a4790700adf78ef5fce54072c1a447c

2025-02-12 09:47 UTC, bvr-odoo approved these changes
LGTM 👍🏼

2025-02-12 09:49 UTC, bvr-odoo commented
@robodoo r+

2025-02-12 11:37 UTC, closed without merging