[IMP] website_sale: improve product configurator
odoo/odoo pull request #184320
Opened 2024-10-18 13:11 UTC by rupa-odoo

This commit enhances the user interface of the product configurator by improving the footer layout and updating the dialog title.

Before this commit :
The footer buttons for "Proceed to Checkout" and "Continue Shopping" were not properly structured and lacked spacing.

After this commit :
Buttons are spaced and aligned, especially in the product configurator's front end.
Improved title: Item(s) added to your cart
Added the arrows to the button.

task-3425340

2025-03-27 09:20 UTC, vchu-odoo requested changes
Thank you for your work on this task!

Here are some nits/suggestions.

2025-03-27 09:20 UTC, vchu-odoo commented on addons/website_sale/controllers/cart.py
>                      'quantity': line._get_displayed_quantity(),
is it still needed?

2025-03-27 09:20 UTC, vchu-odoo commented on addons/website_sale/static/src/js/notification/add_to_cart_notification/add_to_cart_notification.js
>                      quantity: Number,
should we change it?
```suggestion
                    added_qty: Number,
```

2025-03-27 09:20 UTC, vchu-odoo commented on addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
>                      quantity: Number,
same

2025-03-27 09:20 UTC, vchu-odoo commented on addons/website_sale/controllers/cart.py
> +    def _get_cart_notification_information(self, order, line_ids, added_qty_per_line):
Please adapt the docstring params accordingly

2025-03-27 09:20 UTC, vchu-odoo commented on addons/website_sale/controllers/cart.py
> +                    'added_qty_price_total': line.price_unit *  added_qty_per_line[line.id],
```suggestion
                    'added_qty_price_total': line.price_unit * added_qty_per_line[line.id],
```

2025-04-04 12:34 UTC, vchu-odoo approved these changes
Thank you for the changes!

LGTM :+1:

2025-07-16 11:44 UTC, chevalierv requested changes
Hello @kcv-odoo 

I don't believe this is the right change to make. This doesn't take into account overrides like `website_sale_stock`'s, but not only that, which can affect the quantity of added products. I tested adding a product that had not enough stock, and even though the quantity in my cart was right, the one in the notification was wrong.

IMO, it would be best to update `_cart_add` directly to return the added quantity. I would also construct the dict in the controller - instead of blindly returning `values` - to make it clearer, but that's up to you.

Have a nice day!

2025-07-17 17:39 UTC, chevalierv requested changes
🦆

2025-07-17 17:39 UTC, chevalierv commented on addons/website_sale/models/sale_order.py
> +                'added_qty': values['quantity'] - existing_sol.product_uom_qty,  # new_qty - old_qty
The SOL has been updated, so `added_qty` is 0. I think adapting `_cart_update_line_quantity` would be easier.

2025-07-17 17:39 UTC, chevalierv commented on addons/website_sale/controllers/cart.py
> +                    'added_qty': added_qty_per_line[line.id],
I'd not change this variable as it's still the quantity that would display so no need to clarify here
```suggestion
                    'quantity': added_qty_per_line[line.id],
```

2025-07-17 17:39 UTC, chevalierv commented on addons/website_sale/controllers/cart.py
> +                    'added_qty_price_total': line.price_unit * added_qty_per_line[line.id],
nitpicking: I'd keep it simple. `price_total` is enough IMO
```suggestion
                    'price_total': line.price_unit * added_qty_per_line[line.id],
```

2025-07-18 09:32 UTC, chevalierv commented
Hello 👋 

Please also update or add a new test to ensure that the notification show the numbers of items effectively added :)

2025-07-29 10:36 UTC, chevalierv approved these changes
Hello 

LGTM 👍 

robodoo r+

Have a nice day!

2025-07-29 14:14 UTC, closed without merging