[FIX] base: distinguish between Congo-Brazzaville and Congo-Kinshasa.
odoo/odoo pull request #184763
Opened 2024-10-22 14:40 UTC by MohammedBasioni

Rebublic of the Congo (Congo-Brazzaville) and Democratic Republic of the Congo (Congo-Kinshasa) are two different countries. Using "Congo" alone is ambigous. So, this commits fixes this issue and distinguishes between them to avoid confusing.

Task-4266235

2024-10-22 14:40 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184763.png)](https://mergebot.odoo.com/odoo/odoo/pull/184763)

2024-11-08 13:23 UTC, kmagusiak requested changes

2024-11-08 13:23 UTC, kmagusiak commented on odoo/addons/base/data/res_country_data.xml
> +            <field name="name">Congo-Brazzaville</field>
I have checked the iso standard (and also on google maps), can you use official names?
Also in the task comments, there is no concensus to use what you suggest.

https://www.iso.org/obp/ui/#iso:code:3166:CD - Democratic Republic of the Congo
https://www.iso.org/obp/ui/#iso:code:3166:CG - Republic of the Congo

2024-11-15 09:46 UTC, malb-odoo reviewed
Thanks for the PR, i see that there is still discussion on the task for the name it self. I would say that from what i read, both convention could be used but i find the Congo (RDC) and Congo (Republic) a bit more clear IMO :smile:

2024-11-20 17:03 UTC, kmagusiak approved these changes
Looks ok, although I would find it simpler to have "Congo (Democratic Republic)" instead of "RCD".

2024-11-21 10:03 UTC, oomsveta approved these changes
robodoo r+

2024-11-21 14:04 UTC, oomsveta commented
commit message needs to be updated
@robodoo   r-

2024-11-21 15:03 UTC, oomsveta approved these changes
robodoo r+

2024-11-22 00:28 UTC, closed without merging