[FIX] point_of_sale: prevent error when loading order
odoo/odoo pull request #184754
Opened 2024-10-22 14:25 UTC by pedrambiria

Before this commit, selecting an order from the order list and attempting to load it would result in an error.

opw-4251717

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-22 14:25 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184754.png)](https://mergebot.odoo.com/odoo/odoo/pull/184754)

2024-10-23 13:50 UTC, davidmonnom requested changes
I saw that `selectedOrder` was still in use. Can you make it so that there is only one state for the selected order.

You could make a getter.

```js
get selectedOrder() {
     return this.pos.models['pos.order'].getBy(“uuid”, this.state.selectedOrtderUuid)
}
```

2024-10-23 13:50 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
> +            selectedOrder: this.pos.get_order()?.uuid || null,
Should not be `selectedOrderUuid` ?

2024-10-28 14:57 UTC, davidmonnom requested changes
Line 144 `selectedOrder` is still used.

2024-10-28 15:23 UTC, pedrambiria commented
@davidmonnom I modified the code.

2024-12-12 14:47 UTC, pedrambiria commented
@davidmonnom Could you please review this?

2025-01-13 12:35 UTC, davidmonnom approved these changes
@robodoo r+

2025-01-13 15:09 UTC, closed without merging