[FIX] sale_project: show new created task through the sale order
odoo/odoo pull request #184879
Opened 2024-10-23 11:37 UTC by ppr-odoo

Issue:
  In the task action view of the sale order, the task ID is passed in the action domain, which results in showing only
  old tasks. Newly created tasks are not visible because their   IDs are not included in the domain.

Solution:
  Instead of passing task ids, we now check for project_id, sale_order_id, or sale_line_id  to ensure the new tasks are properly displayed.

Steps to Reproduce:
   - Install the sale_project module.
   - Create a Sale Order (SO).
   - Add a product configured to create a project with tasks.
   - Click on the "Tasks" smart button from the SO.
   - Go to the Kanban view.
   - Create a new task and give a name.
   - Reload the page.
   - Check if the task is visible (the issue was that new tasks were not visible).

Affected PR:
  https://github.com/odoo/odoo/pull/135771/files

task-4224564

2024-10-23 11:37 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/184879.png)](https://mergebot.odoo.com/odoo/odoo/pull/184879)

2024-11-14 16:10 UTC, auon-odoo requested changes
Thanks for your work :fire: :muscle:

2024-11-15 04:59 UTC, ppr-odoo commented on addons/sale_project/models/sale_order.py
>          return action
I am going ahead with the minimum diff in the stable version and applying it to the master version. Is that okay for you?

2024-11-15 09:00 UTC, auon-odoo commented on addons/sale_project/models/sale_order.py
>          return action
Functionally, the diff is the same. Your dev is literally shortest, but I think my suggestion is cleanest and safest, which imo is more important. I am sorry to insist :pray:

2024-11-20 17:26 UTC, auon-odoo approved these changes
LGTM! Thanks for your work @ppr-odoo :fire:

2024-12-18 12:55 UTC, xavierbol reviewed
thanks for your work, I left one comment

2024-12-18 12:55 UTC, xavierbol commented on addons/sale_project/models/sale_order.py
> +        return ['&', ('project_id', '!=', False), '|', ('sale_line_id', 'in', self.order_line.ids), ('sale_order_id', 'in', self.ids)]
```suggestion
        return ['&', ('display_project_id', '!=', False), '|', ('sale_line_id', 'in', self.order_line.ids), ('sale_order_id', 'in', self.ids)]
```
? 🧐

2024-12-24 08:08 UTC, xavierbol commented
robodoo r+

2024-12-24 09:08 UTC, closed without merging