[FIX] website_sale: fix discount display
odoo/odoo pull request #185053
Opened 2024-10-24 09:27 UTC by kcv-odoo

Steps:
- Install Ecom.
- Add a product in pricelist with fomula type.
- Go to Ecom.
- Product old and new price displaying with old in strike out.
- Go to check out.

Issue:
- Only new product price is displaying as formula and fixed type rule directly change value of product on SOL and discount type add discount on SOL.

Cause:
- Only checked discount on SOL to display old price.

Fix:
- Check price before discount and after discount to display old price if both are not same.

opw-4277128

2024-10-24 09:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185053.png)](https://mergebot.odoo.com/odoo/odoo/pull/185053)

2024-11-12 15:00 UTC, chevalierv requested changes
Hello @kcv-odoo 

Just a minor comment otherwise LGTM 👍

2024-11-13 05:04 UTC, kcv-odoo commented on addons/website_sale/models/sale_order_line.py
> +        pass
opps, Fixed :see_no_evil:

2024-11-13 10:14 UTC, chevalierv approved these changes
robodoo r+

2024-11-13 10:14 UTC, robodoo commented
@chevalierv you may want to rebuild or fix this PR as it has failed CI.

2024-11-13 10:59 UTC, chevalierv commented
@robodoo r-

Sorry but I forgot to check to behavior for customer that will have the old template with the new python code

2024-11-13 13:22 UTC, chevalierv commented
Hello @kcv-odoo

It seems that this PR goes against this one: https://github.com/odoo/odoo/pull/181014.

We won't show the strikethrough price if the computation is a formula anymore.

Therefore, I believe this fix shouldn't be merged.

2024-11-13 13:28 UTC, closed without merging