[IMP] website: update website info settings layout
odoo/odoo pull request #185048
Opened 2024-10-24 09:22 UTC by divy-odoo

This commit update the settings in the `Website Info` section of the website settings.

- Update the setting layout.
- Made the help text visible again.
- Added documentation links.

Before:
![image](https://github.com/user-attachments/assets/d7b8529a-8af4-4d49-95d6-e7e8e6eaeb96)

After: 
![image](https://github.com/user-attachments/assets/aa0da361-c3bf-46d9-9f2c-1490779395c6)

task-3933550

2024-10-24 09:22 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185048.png)](https://mergebot.odoo.com/odoo/odoo/pull/185048)

2025-02-18 15:06 UTC, SergeBayet commented
@divy-odoo Is this intended? 
![image](https://github.com/user-attachments/assets/942b23b6-9da5-4677-8e26-7a9af5c2c2c9)
It didn't turn out very well... @lebl-odoo ?

2025-02-18 15:21 UTC, lebl-odoo commented
Indeed, we should have the same size than before, I didn't pay attention during the test phase. Thx for noticing it

2025-02-18 15:29 UTC, SergeBayet commented
> Indeed, we should have the same size than before, I didn't pay attention during the test phase. Thx for noticing it

I'm afraid that was already the case in master: 
![image](https://github.com/user-attachments/assets/17932ae1-14af-4f29-b814-ba779b332c75)

2025-02-18 15:33 UTC, lebl-odoo commented
Oh, well, maybe it's not linked to this PR in that case

2025-02-18 15:36 UTC, SergeBayet commented
> Oh, well, maybe it's not linked to this PR in that case

From 16.0 after investigation.

2025-02-18 15:38 UTC, SergeBayet requested changes
Hi @divy-odoo, seems good, just a typo in your commit and maybe check if you can deal with the size of the favicon. I saw a `.o_we_preview_favicon` somewhere. Maybe a solution, I don't know. Cheers!

2025-02-19 08:13 UTC, SergeBayet approved these changes
LGTM :+1:

2025-02-19 08:49 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2025-02-19 17:51 UTC, closed without merging