[FIX] website_sale: fix Discount Price Color on Product Page
odoo/odoo pull request #185038
Opened 2024-10-24 09:04 UTC by nikj-odoo

Version:
- saas 17.4

Steps to reproduce:
- Install the website_sale module.
- Open the pricelist and apply a discount to a product.

Issue:
- The discount price on the product page appears in a red "danger" color.

Solution:
- Changed the text class from "text-danger" to "text-muted" to fix the issue.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-24 09:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185038.png)](https://mergebot.odoo.com/odoo/odoo/pull/185038)

2024-10-25 08:43 UTC, kcv-odoo commented
Hello @chevalierv @Jean-boje
May I have your opinion? as customer want to display strike through price in product black like it display in shop page and probably in checkout page also

Have a nice day!!

2024-10-31 15:28 UTC, ltinel commented
If we want to go through with this, we should probably change it in all places (product configurator, search bar, cart, comparison page, etc.)

2024-10-31 15:31 UTC, ltinel commented
And we should also do it for the `compare_list_price` I guess

2024-11-06 06:55 UTC, nikj-odoo commented
Hello @ltinel :wave: ,

I've made the changes and updated all places, including on the website search bar. I'm not sure if this will affect other places, so we should check with the website PO to confirm.

Thank You :slightly_smiling_face:

2024-11-12 10:03 UTC, ltinel commented on addons/website_sale/static/src/js/product/product.xml
> +            class="text-muted fw-bold"
Could you also make this italic instead of bold?

2024-11-12 10:07 UTC, ltinel requested changes
Thanks! Looks like there's still one fix remaining for the cart page, probably here: https://github.com/odoo/odoo/blob/f9942d30ab567fbbd28474010894037e04da8e7f/addons/website_sale/views/templates.xml#L1610

2024-11-12 10:23 UTC, nikj-odoo commented
> Thanks! Looks like there's still one fix remaining for the cart page, probably here:
> 
> https://github.com/odoo/odoo/blob/f9942d30ab567fbbd28474010894037e04da8e7f/addons/website_sale/views/templates.xml#L1610

Hello @ltinel :wave: ,
Changes are done.

Thank for noticing :slightly_smiling_face:

2024-11-12 12:31 UTC, ltinel approved these changes
Thanks, LGTM :) Just one last comment: the comparison price doesn't seem to be show in the cart, is that expected? (this was already the case before your fix so not blocking)

2024-11-12 15:06 UTC, chevalierv reviewed
@robodoo delegate=ltinel

2024-11-13 17:03 UTC, closed without merging