[FIX] website: fix product ribbon shadow overlap on shop page
odoo/odoo pull request #185017
Opened 2024-10-24 05:14 UTC by rupa-odoo

Version: V17.4

Issue:
On the shop page, the default product ribbon with a drop shadow was causing the top right corner of the product image to appear cropped.

Cause:
The ribbon's shadow extended over the product image.

Fix:
Added 'display: none' to hide the empty ribbon, which prevents the shadow from displaying.

opw-4190631

2024-10-24 05:14 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185017.png)](https://mergebot.odoo.com/odoo/odoo/pull/185017)

2024-10-28 05:28 UTC, kcv-odoo commented
Hello @rupa-odoo 

Why in website?
I don't think this issue is coming from website as it mention in Task by QSM. can you do more research and find proper solution or give more details why this is best fix for given problem

Have a nice day!

2024-10-28 08:53 UTC, qsm-odoo requested changes
@rupa-odoo Thanks for the fix but it needs more to be possible to merge.

There is no information in the commit message that justifies why this new CSS rule should be added in this particular version.
When you encounter a bug in a specific version in 17.4, the first question should be "why is not the bug present in the previous version" ? You will find that the @odoo/rd-ecommerce team broke this by always adding a `o_ribbon_right` class on all ribbons by default. That is the kind of info that should appear in the commit message, otherwise I cannot know if this is the right fix or not.

Now... maybe that this can't be fixed because what they did is on the XML side and we can't change the XML in stable, I don't know. In that case, this may be the only solution indeed... and I could merge.
But as you explained to me on Discord, this actually is done already in 18.0 so this should not have to be thought through much more than that: just mention that https://github.com/odoo/odoo/commit/b5b8a133eb67f01cabec01a1dc874e8a27a3bb46#diff-f338780f594d6b1f46eda5d3fb9fed86f3c3c8f65522fb93e639534e9d92cdb2R1832 already did this in 18.0 and we can quickly merge.

So:
- Add the info about why this was not needed before 17.4
- Add the info that this fix was already done in 18.0 so we'll match the solution until we come up with something better in master

Thank you :pray: 

@stefanorigano It would be nice to find another solution that adding that rule in master... if the ribbon is empty, just make sure it comes with the d-none class or, better, just don't add it in the DOM. If we were to add a `&:empty { display: none; }` rules on all component in case they are added in the DOM but empty... that would be quite ugly :grimacing:

2024-10-28 12:46 UTC, rupa-odoo commented
> @rupa-odoo Thanks for the fix but it needs more to be possible to merge.
> 
> There is no information in the commit message that justifies why this new CSS rule should be added in this particular version. When you encounter a bug in a specific version in 17.4, the first question should be "why is not the bug present in the previous version" ? You will find that the @odoo/rd-ecommerce team broke this by always adding a `o_ribbon_right` class on all ribbons by default. That is the kind of info that should appear in the commit message, otherwise I cannot know if this is the right fix or not.
> 
> Now... maybe that this can't be fixed because what they did is on the XML side and we can't change the XML in stable, I don't know. In that case, this may be the only solution indeed... and I could merge. But as you explained to me on Discord, this actually is done already in 18.0 so this should not have to be thought through much more than that: just mention that [b5b8a13#diff-f338780f594d6b1f46eda5d3fb9fed86f3c3c8f65522fb93e639534e9d92cdb2R1832](https://github.com/odoo/odoo/commit/b5b8a133eb67f01cabec01a1dc874e8a27a3bb46#diff-f338780f594d6b1f46eda5d3fb9fed86f3c3c8f65522fb93e639534e9d92cdb2R1832) already did this in 18.0 and we can quickly merge.
> 
> So:
> 
> * Add the info about why this was not needed before 17.4
> * Add the info that this fix was already done in 18.0 so we'll match the solution until we come up with something better in master
> 
> Thank you 🙏
> 
> @stefanorigano It would be nice to find another solution that adding that rule in master... if the ribbon is empty, just make sure it comes with the d-none class or, better, just don't add it in the DOM. If we were to add a `&:empty { display: none; }` rules on all component in case they are added in the DOM but empty... that would be quite ugly 😬

Hello @qsm-odoo 
Got the point.
Update the commit message.

Thank you

2024-10-28 13:42 UTC, qsm-odoo requested changes
I know I am annoying but precisions about what I wanted:

![image](https://github.com/user-attachments/assets/5a8feafc-170e-41ab-bdee-1ff420630523)

2024-10-30 13:25 UTC, qsm-odoo approved these changes
@robodoo r+ up to saas-17.4

2024-10-30 13:25 UTC, robodoo commented
Forward-port disabled (via limit).

2024-10-30 16:13 UTC, closed without merging