[FIX] pos_self_order: fix product variant selection
odoo/odoo pull request #185224
Opened 2024-10-25 06:53 UTC by parp-odoo

before this commit:
==============
- Products with attributes in instant mode appeared duplicated in the
  product list for each combination.

after this commit:
==============
- The product list now shows only the main product for variants, similar to POS.
  Clicking on the product opens the configuration page.

Task-4269189

2024-10-25 06:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185224.png)](https://mergebot.odoo.com/odoo/odoo/pull/185224)

2024-11-22 06:36 UTC, paso-odoo requested changes

2024-11-22 06:36 UTC, paso-odoo commented on addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
> +                <h1 class="mb-0 text-nowrap"><strong t-esc="props.product.name"/> options</h1>
```suggestion
                <h1 class="mb-0 text-nowrap"><strong t-esc="product.name"/> options</h1>
```

2024-11-22 06:36 UTC, paso-odoo commented on addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
> +                        <h2 t-esc="props.product.name"/>
```suggestion
                        <h2 t-esc="product.name"/>
```

2024-11-22 06:36 UTC, paso-odoo commented on addons/pos_self_order/static/src/app/self_order_service.js
> +                                }
```suggestion
```

2024-11-22 06:53 UTC, paso-odoo requested changes

2024-11-22 06:53 UTC, paso-odoo commented on addons/pos_self_order/models/product_product.py
> +        self._process_pos_self_ui_product_product(products, config_id)
```suggestion
        self._compute_product_price_with_pricelist(products, config_id)
```

2024-11-22 06:53 UTC, paso-odoo commented on addons/pos_self_order/models/product_product.py
> +    def _process_pos_self_ui_product_product(self, products, config_id):
```suggestion
    def _compute_product_price_with_pricelist(self, products, config_id):
```

2024-11-22 06:53 UTC, paso-odoo commented on addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
> +                        <span>This combination does not exist.</span>
need to update pot

2024-11-27 09:16 UTC, vlst-odoo requested changes

2024-11-27 13:25 UTC, vlst-odoo requested changes

2024-11-27 13:25 UTC, vlst-odoo commented on addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
> +                </div>
```suggestion
                    <div t-if="isArchivedCombination() and !this.isEveryValueSelected()" class="alert alert-warning m-0">
                        This combination does not exist
                    </div>
```
the idea here is to not have any unnecessary tags

2024-11-27 13:25 UTC, vlst-odoo commented on addons/pos_self_order/static/src/app/self_order_service.js
> +                    })
```suggestion
                    prd.product_template_variant_value_ids.every((ptav) => 
                        Object.values(selectedValues).some((value) => ptav.id == value);
                    )
```

2024-11-28 08:40 UTC, parp-odoo commented on addons/pos_self_order/static/src/app/self_order_service.js
> +                    })
@vlst-odoo ,
Changes are done!

2024-11-28 09:40 UTC, vlst-odoo approved these changes
robodoo r+

2024-11-28 09:40 UTC, robodoo commented
@parp-odoo @vlst-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-11-28 09:53 UTC, vlst-odoo commented
robodoo rebase-ff

2024-11-28 09:53 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-11-28 12:04 UTC, closed without merging