[IMP] api: Add warning about api.norecompute() deprecation
odoo/odoo pull request #185258
Opened 2024-10-25 10:09 UTC by rousseldenis

@rco-odoo What do you think of this ? Thanks

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-25 11:26 UTC, kmagusiak commented on odoo/api.py
> +            "norecompute() is deprecated. You should use protecting() instead.",
Just add a version.
```suggestion
            "norecompute() is deprecated since 19.0. You should use protecting() instead.",
```

2024-10-25 12:53 UTC, rousseldenis commented on odoo/api.py
> +            "norecompute() is deprecated. You should use protecting() instead.",
@kmagusiak

2024-10-25 13:04 UTC, rousseldenis commented
IMHO, this can be removed: https://github.com/odoo/odoo/blob/16.0/odoo/fields.py#L2381

2024-10-25 13:12 UTC, kmagusiak requested changes
The PR is about a deprecation. It should not reformat everything.

2024-10-25 13:19 UTC, rousseldenis commented
> The PR is about a deprecation. It should not reformat everything.

What do you mean ?

2024-10-25 13:27 UTC, kmagusiak commented
> > The PR is about a deprecation. It should not reformat everything.
> 
> What do you mean ?

The diff reformats now all the file.

2024-10-25 16:09 UTC, rousseldenis commented
@kmagusiak Done. What do you think about removing the norecompute call in `Binary` field class ? It does nothing.

2024-10-25 17:58 UTC, kmagusiak commented
You will have to fix the runbot, so I'm not sure this should target v16. @ryv-odoo what do you think?

2024-10-25 18:04 UTC, rousseldenis commented
> You will have to fix the runbot, so I'm not sure this should target v16. @ryv-odoo what do you think?

In fact, removing the call to `norecompute()` won't harm anything (that is done in further versions) as it does nothing:

https://github.com/odoo/odoo/blob/9bb45ec35ae34f0c9de320072650bbb63f23d543/odoo/fields.py#L2381

2024-10-28 05:57 UTC, ryv-odoo commented
Hello @rousseldenis , 

What is the purpose of this change (why do you want to backport https://github.com/odoo/odoo/pull/99550) ? We always deprecated and cleaned the master version only, never the stable ones. You can check our stable policy [here](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean). In this case, you may potentially create new warning logs on stable servers that may trigger some stressful situations for the server managers (for no reason).

I hope you understand. 
Sincerely.

2024-10-28 05:57 UTC, closed without merging