[FIX] point_of_sale: prevent 0 amount payment lines
odoo/odoo pull request #185448
Opened 2024-10-28 08:39 UTC by sjai-odoo

Steps to reproduce :
-------------------------
- Install the point_of_sale module.
- Order something and go to payment page.
- Apply multiple payment lines even with 0 amount.

Issue :
-------
The payment lines with 0 amount is also shown on receipt as well.

Cause :
----------
We never checked for the amount of paymentline.

Fix :
----
Updated the condition to remove 0 amount paymentline from the view.

task - 4285705

2024-10-28 08:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185448.png)](https://mergebot.odoo.com/odoo/odoo/pull/185448)

2024-10-28 10:10 UTC, davidmonnom requested changes
![image](https://github.com/user-attachments/assets/e8527c0c-432e-4dfc-8e31-94556a2f76ea)


What you actually do, is just hidding payment line, but they are still saved on the server.

2024-11-04 09:05 UTC, davidmonnom requested changes
@sjai-odoo I put comment on the spec.

2024-11-04 13:27 UTC, davidmonnom requested changes
```js
async validateOrder(isForceValidate) {
    this.numberBuffer.capture();
    if (this.pos.config.cash_rounding) {
        if (!this.currentOrder.check_paymentlines_rounding()) {
            this._display_popup_error_paymentlines_rounding();
            return;
        }
    }
    if (await this._isOrderValid(isForceValidate)) {
        // remove pending payments before finalizing the validation
        const toRemove = [];
        for (const line of this.paymentLines) {
            if (!line.is_done() || line.amount === 0) {
                toRemove.push(line);
            }
        }

        for (const line of toRemove) {
            this.currentOrder.remove_paymentline(line);
        }

        if (this.paymentLines.length === 0) {
            this.currentOrder.add_paymentline(this.payment_methods_from_config[0], 0);
        }

        await this._finalizeValidation();
    }
}
```

2024-11-05 04:54 UTC, sjai-odoo commented
> ```js
> async validateOrder(isForceValidate) {
>     .........
>         if (this.paymentLines.length === 0) {
>             this.currentOrder.add_paymentline(this.payment_methods_from_config[0], 0);
>         }
>    ........
>     }
> }
> ```
Here we can't do payment_methods_from_config[0] directly, supoose we have enabled rounding only on cash payments but the first method we get in payment_methods can be anything if it won't be the cash line than the rounding line won't be created 
![image](https://github.com/user-attachments/assets/09b3db68-9cc6-4692-989a-1758884df4c6)
Rounding Line: 
![image](https://github.com/user-attachments/assets/1b960550-e378-4661-9133-3c86e7228d50)
So instead if we slice 1st one 0 amount paymentline means user's first selected paymentline so we don't have to think about rounding cases if user selected cash and because of rounding it became 0 it will be still there as we are slicing first .
For the case of more than one 0 lines the first one may have rounding purpose rest will be always 0 because of no remaining amount that have no issues to be removed.

```js
        if (this.paymentLines.length === 0) {
             this.currentOrder.add_paymentline(this.payment_methods_from_config[0], 0);
        }
```
In this the 0 amount paymentline will only be added if after deleting all 0 amount lines there is no paymentline but there can be a line with half payment from card and rest by cash which is rounded to 0 idf we do this it won't work.

What do you think?

2024-11-05 13:09 UTC, sjai-odoo commented
Hello @davidmonnom ,
Changes are done according to the suggestions please check it.

2024-12-31 14:30 UTC, davidmonnom approved these changes
@robodoo r+

2024-12-31 16:51 UTC, closed without merging