[FIX] point_of_sale,pos_sale: fix product info popup
odoo/odoo pull request #185549
Opened 2024-10-28 15:24 UTC by davidmonnom

Following changes of product card that are now product.template, adapt the product info popup to display the correct information.

Now it display information about the product template instead of the first product variant.

2024-10-28 15:24 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185549.png)](https://mergebot.odoo.com/odoo/odoo/pull/185549)

2024-10-31 13:56 UTC, adgu-odoo requested changes

2024-10-31 13:56 UTC, adgu-odoo commented on addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.js
> +        console.log(this.state.product);
remove the console.log

2024-10-31 13:56 UTC, adgu-odoo commented on addons/pos_sale/models/product_template.py
> +    def get_product_info_pos(self, price, quantity, pos_config_id):
```suggestion
    def get_product_info_pos(self, price, quantity, pos_config_id, product_variant_id=False):
```

2024-10-31 13:56 UTC, adgu-odoo commented on addons/pos_sale/models/product_template.py
> +        res = super().get_product_info_pos(price, quantity, pos_config_id)
```suggestion
        res = super().get_product_info_pos(price, quantity, pos_config_id, product_variant_id=False)
```

2024-10-31 13:56 UTC, adgu-odoo commented on addons/pos_sale/models/product_template.py
> +            for p in self.optional_product_ids.filtered_domain(self._optional_product_pos_domain())
`_optional_product_pos_domain` is defined in `product.product` and use in `product.template`, shouldn't you adapt that ?

2024-10-31 14:14 UTC, davidmonnom commented on addons/pos_sale/models/product_template.py
> +    def get_product_info_pos(self, price, quantity, pos_config_id):
bien vu le sang

2024-10-31 14:43 UTC, adgu-odoo approved these changes

2024-11-04 08:48 UTC, adgu-odoo commented
robodoo r+

2024-11-04 15:09 UTC, closed without merging