Master fixcanarias jco
odoo/odoo pull request #185571
Opened 2024-10-28 16:54 UTC by jco-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-28 16:54 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185571.png)](https://mergebot.odoo.com/odoo/odoo/pull/185571)

2024-11-14 15:21 UTC, rugo-odoo requested changes

2024-11-14 15:21 UTC, rugo-odoo commented on addons/account/data/res_country_group.xml
Indentation is not 4 spaces and missing empty line at end of file.

2024-11-14 15:21 UTC, rugo-odoo commented on addons/account/views/res_country_group_view.xml
> +    <record id="inherits_website_sale_country_group_form" model="ir.ui.view">
Why `website_sale` ???

2024-11-14 15:21 UTC, rugo-odoo commented on addons/l10n_es/data/res_country_group.xml
Indentation is not 4 spaces and missing empty line at end of file.

2024-11-14 15:21 UTC, rugo-odoo commented on addons/l10n_es/data/template/account.fiscal.position-es_common.csv
> +"id","sequence","name","name@es","name@ca","auto_apply","vat_required","country_id","country_group_id","tax_ids/tax_src_id","tax_ids/tax_dest_id","account_ids/account_src_id","account_ids/account_des
If I'm not mistake, we don't do anything with `state_ids` here. Why are we adding it ?

2024-11-14 15:21 UTC, rugo-odoo commented on addons/l10n_nl/data/res_country_group.xml
Indentation is not 4 spaces and missing empty line at end of file.

2024-11-14 15:21 UTC, rugo-odoo commented on addons/l10n_es/data/res_country_group.xml
> +	<record id="mainland_spain" model="res.country.group">
We do `mainland_nl` for the Netherlands, let's do `mainlaind_es` here to be consistent (?)

2024-11-15 16:53 UTC, jco-odoo commented
@rugo-odoo Should be ready

2024-11-18 12:41 UTC, jco-odoo commented
@rugo-odoo rebased

2024-11-18 14:21 UTC, rugo-odoo commented
@robodoo r+

2024-11-19 05:43 UTC, closed without merging