[IMP] point_of_sale: fixed box width
odoo/odoo pull request #185623
Opened 2024-10-29 04:35 UTC by paan-odoo

Before this commit:
==========
- The width of the input field changes when text is added during the session's opening and cash in/cash out processes.
- The company logo affects the width of the PoS receipt preview.

After this commit:
==========
- The input field's width stays fixed while adding text during the session's opening and cash in/cash out processes.
- The width of the PoS receipt preview remains fixed as well.

task-4285446

2024-10-29 04:35 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185623.png)](https://mergebot.odoo.com/odoo/odoo/pull/185623)

2024-11-06 13:20 UTC, davidmonnom requested changes
Changes requested on Odoo Task

2024-11-07 09:11 UTC, paan-odoo commented
Hello @davidmonnom 

Suggested changes are done.

Thanks!

2024-11-14 13:14 UTC, davidmonnom approved these changes
@robodoo r+

2024-11-14 16:23 UTC, closed without merging