[IMP] website: add desktop alignment option for sidebar header
odoo/odoo pull request #185660
Opened 2024-10-29 10:05 UTC by divy-odoo

With this commit [[1]](https://github.com/odoo/odoo/commit/f87cee6d589694b56caef84beb90259db6cf96b0), we lost the functionality to change the sidebar header position, making it impossible to align the sidebar header to the right. Previously, we managed the sidebar position and text alignment using the common option, "Format > Alignment."

In this commit, we introduce a new option, "Desktop Alignment," for setting the sidebar header position, while keeping "Format > Alignment" for text alignment to simplify the user interaction with these options.

![image](https://github.com/user-attachments/assets/d612d6ad-d4da-4475-ba96-bc6c3e8f0ff6)

task-4204213

2024-10-29 10:05 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185660.png)](https://mergebot.odoo.com/odoo/odoo/pull/185660)

2025-04-02 08:05 UTC, SergeBayet requested changes
Hello @divy-odoo, here's my review. Thanks for the work. Some remarks though. See below. :+1:

2025-04-02 08:05 UTC, SergeBayet commented on addons/website/views/website_templates.xml
> +                <ul class="o_header_mobile_buttons_wrap navbar-nav d-flex flex-row align-items-center gap-2 mb-0 ms-auto"/>
I'm a little bit concern here. If `website_sale` module is not installed, there will be no `<li>` elements in this `<ul>` which is invalid HTML. We should find a solution to that.

2025-04-02 08:59 UTC, divy-odoo commented on addons/website/views/website_templates.xml
> +<template id="template_header_mobile_position_left" inherit_id="website.template_header_mobile" active="False">
@SergeBayet that was my first thought, but to avoid confusion, I didn't choose that.

`template_header_mobile_align_right` and `template_header_mobile_align_center` are used to **align the text content**, not the sidebar position. By default, the text is left-aligned, so you won't find a template with that name. Here, we need something that controls the position of the sidebar.

2025-04-02 09:38 UTC, SergeBayet commented on addons/website/views/website_templates.xml
> +<template id="template_header_mobile_position_left" inherit_id="website.template_header_mobile" active="False">
Makes sense. Thanks!

2025-04-03 06:55 UTC, divy-odoo commented on addons/website/views/website_templates.xml
> +                <ul class="o_header_mobile_buttons_wrap navbar-nav d-flex flex-row align-items-center gap-2 mb-0 ms-auto"/>
Great point, @SergeBayet. 

To avoid invalid HTML, we can replace the `<ul>` tag with a `<div>` and populate the `<ul>` where the `<li>` elements are being prepared. As I see it, we are extending the `<ul>` specifically for the `website_sale`. However, the only downside is that it won't be as flexible as it is now for extending to more modules in the future.

What do you think?

2025-04-03 09:24 UTC, SergeBayet commented on addons/website/views/website_templates.xml
> +                <ul class="o_header_mobile_buttons_wrap navbar-nav d-flex flex-row align-items-center gap-2 mb-0 ms-auto"/>
After investigation, none of the HTML validators I tried consider it an error to have an empty <ul> tag. So let's forget about it.

2025-04-04 06:44 UTC, SergeBayet approved these changes
LGTM! Thanks

2025-04-04 06:45 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2025-04-04 07:23 UTC, SergeBayet requested changes
A few more remarks and we're good to go. Thanks!

2025-04-04 07:23 UTC, SergeBayet commented on addons/website/views/snippets/snippets.xml
> +         <we-select data-variable="hamburger-position" data-reload="/" string="Desktop Alignment" data-dependencies="header_sidebar_opt, header_hamburger_opt">
Indentation issue here...
```suggestion
        <we-select data-variable="hamburger-position" data-reload="/" string="Desktop Alignment" data-dependencies="header_sidebar_opt, header_hamburger_opt">
```

2025-04-04 07:23 UTC, SergeBayet commented on addons/website/views/snippets/snippets.xml
> +            <we-button data-customize-website-variable="'right'"
You don't mention this change (mobile alignment) in your PR / commit description.

2025-04-07 10:21 UTC, divy-odoo commented
Thanks @SergeBayet, PR is ready to launch. :rocket:

2025-04-07 16:19 UTC, closed without merging