[FIX] Account: update is move sent after resending
odoo/odoo pull request #185830
Opened 2024-10-30 10:51 UTC by LouisGobert

Currently, the status `is_move_sent` is only set to `True` upon the first sending of an invoice. If the invoice is reverted to draft and then confirmed and sent again, the `is_move_sent` status is not updated.

Steps to Reproduce:
1. Create an invoice
2. Confirm the invoice
3. Send the invoice
4. Set the invoice back to draft
5. Confirm the invoice again
6. Send the invoice again

Expected behavior: The `is_move_sent` status should be updated to `True` after resending.

opw-4245126

2024-10-30 10:51 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185830.png)](https://mergebot.odoo.com/odoo/odoo/pull/185830)

2024-10-31 15:49 UTC, alialfie reviewed
Hi Louis! So I checked a bit, and I can see that the field is not set to `True` anymore in `_link_invoice_documents` as the PDF is not regenerated in your scenario. Your fix just sets the field to True in another place but I think the issue here is `is_move_sent` shouldn't be set to False when you reset a move to draft. This doesn't happen on 18.0 because of this [task](https://www.odoo.com/odoo/project/967/tasks/3997538). I will check with the POs next week and confirm that this should be backported in 17.0 and this would solve your ticket. I'll keep you updated :)

2024-11-12 14:00 UTC, alialfie commented
Hi Louise! I checked with OLMA and he agreed that we should backport that task to 17.0 as well. Could you do this in this PR please? Would fix your ticket and avoid discrepancies between versions

2024-11-13 10:50 UTC, alialfie requested changes
Thanks Louis! My last nitpick: in the commit message, please limit the line char length to 72 (similar to the original commit message) and add numbers to the steps

2024-11-13 11:24 UTC, LouisGobert commented
You are right, it's done (I thought I had already done it 😅)

2024-11-14 09:13 UTC, alialfie approved these changes
Perfect, thanks! Someone will do a final review and r+ soon :)

2024-11-14 09:39 UTC, gawa-odoo commented
@robodoo up to saas-17.2

2024-11-14 09:39 UTC, robodoo commented
Forward-porting to 'saas-17.2'.

2024-11-14 10:33 UTC, gawa-odoo reviewed
@robodoo r+

2024-11-14 13:01 UTC, closed without merging