wip poll
odoo/odoo pull request #185979
Opened 2024-10-31 11:46 UTC by tsm-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-31 11:46 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185979.png)](https://mergebot.odoo.com/odoo/odoo/pull/185979)

2025-09-29 06:59 UTC, phenix-factory commented on addons/mail/static/src/core/common/create_poll_option_dialog.js
> +                await new Promise(setTimeout);
Is this a mistake? Or do you need to wait a tick for some reason?

2025-09-29 07:02 UTC, tsm-odoo commented on addons/mail/static/src/core/common/create_poll_dialog_answer.js
> +                await new Promise(setTimeout);
Same as for the composer selection, we need to wait for other handlers to potentially handle the event before checking whether it has been handled elsewhere.

2025-09-29 10:01 UTC, alexkuhn commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        </label>
- looks best for `Add another answer` to be a `btn-link`
- could have "allow multiple answers" and "Duration" inline, so less space is wasted

This would look like this:
<img width="652" height="450" alt="Image" src="https://github.com/user-attachments/assets/a53241dd-dafb-4378-9b3a-03542f8224d1" />

2025-09-29 10:05 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/public_web/composer_actions_patch.js
> +    },
`owner.thread` => `composer.targetThread`

The `getter` is solely relying on deduced info on `composer`. The name `targetThread` is poor but was done in a rush before OXP, I don't know the exact semantics hence the quite generic naming. `get thread` on composer is basically deprecated.

2025-09-29 11:55 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/public_web/poll.xml
> +            'border-primary': state.selectedAnswerIds.has(answer.id),
`border-primary` with the green checkbox doesn't work visually:
<img width="507" height="223" alt="Image" src="https://github.com/user-attachments/assets/52e74d0a-2399-48af-9a4f-6cd55d097105" />

Green item with purple wrapper (or vice-versa in composer focused + send button we have) looks off.

I think it's good to use `.primary` to highlight action, but we should not overuse it. In this case, I would keep green color as a soft version of primary, with less transparency for making it more visible:
<img width="508" height="222" alt="Image" src="https://github.com/user-attachments/assets/30358170-f818-4179-b067-697241687a86" />

2025-09-29 12:08 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/public_web/poll.xml
> +            </span>
This doesn't work: no `fa-check` visually on self selected answers, it looks like `is_selected_by_self` is unset in code.

2025-09-29 12:11 UTC, tsm-odoo commented on addons/mail/static/src/discuss/core/public_web/poll.xml
> +            </span>
field has been renamed to `selected_by_self` :see_no_evil: Fixed.

2025-09-29 12:13 UTC, alexkuhn commented on addons/mail/controllers/discuss/poll.py
> +        )
I don't think the notification is worth it: there's already an actual poll in message list and that's more than enough.

The notification for pinned message is useful because we could pin an old message and we must see in recent activities through the notification. This is not the case here, the poll is immediately recent activity by itself.

2025-09-29 12:15 UTC, tsm-odoo commented on addons/mail/controllers/discuss/poll.py
> +        )
It's only used to map the poll to a message, thus allowing to be fetched in the message list.

2025-09-29 12:20 UTC, alexkuhn commented on addons/mail/demo/discuss/discuss_poll_demo.xml
> +            <field name="start_message_id" ref="mail.favorite_food_poll_message_demo"/>
Thank god multiple answers are allowed!

2025-09-30 06:32 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll.py
> +                % {"author_name": poll.start_message_id.author_id.name, "poll_link": poll_link}
Using `'` inside HTML is always weird to me. Why not make an exception and use `'`  for this string?

```suggestion
            poll_link = Markup(
                '<a href="#" class="o_hide_author" data-oe-type="highlight" data-oe-id="%(message_id)s">%(question)s</a>'
            ) % {"message_id": poll.start_message_id.id, "question": poll.question}
            notification_text = (
                Markup('<div class="o_mail_notification o-discuss-Poll-ended">%s</div>')
                % self.env._("%(author_name)s's poll %(poll_link)s has closed")
                % {"author_name": poll.start_message_id.author_id.name, "poll_link": poll_link}
```

2025-09-30 06:42 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    voter_user_ids = fields.Many2many("res.users")
This could just be a 3-column table with an answer_id | partner_id | guest_id.
This will simplify all the SQL in this PR.

2025-09-30 13:33 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll_vote.py
> +    guest_id = fields.Many2one("mail.guest", index=True)
We might want to add 2 uniques index:

answer_id and user_id
answer_id and guest_id

To avoid multiple votes on the same answer.

2025-09-30 13:37 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll_vote.py
> +    guest_id = fields.Many2one("mail.guest", index=True)
If we do it, I'm not sure we still need the `index=True` param.

2025-09-30 13:50 UTC, phenix-factory commented on addons/mail/controllers/discuss/poll.py
> +            raise NotFound()
Isn't this the same? I don't get the check on `answer_ids`, what are you trying to do?
```suggestion
        poll = self.env["discuss.poll"].search_fetch(["id", "=", poll_id])
        if not poll or len(poll.answer_ids) != len(answer_ids):
            raise NotFound()
```

2025-10-01 10:29 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll_vote.py
> +    )
This should use `modes.UniqueIndex`

2025-10-01 11:24 UTC, seb-odoo commented on addons/mail/security/mail_security.xml
> +                            ("channel_id.channel_type", "!=", "channel"),
These rules will miss livechat override, among other things.

Having ACL depending on a relation field (that can be edited, most likely) is never a good idea either.

Can't we make the model fully technical and use sudo?

2025-10-01 11:24 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
Before reading "vote" I thought "answer" was "vote".

Shouldn't answer be called "option" or "choice"?

2025-10-01 11:24 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_option.py
> +    poll_id = fields.Many2one("discuss.poll", ondelete="cascade", required=True, index=True)
we might want a constraint to prevent changing the value

2025-10-01 11:24 UTC, seb-odoo commented on addons/mail/security/mail_security.xml
> +                            ("channel_id.channel_type", "!=", "channel"),
Also if we use sudo, we could have polls non-specifically linked to a channel, in particular working in all threads, or having the same poll posted in multiple places?

2025-10-01 11:28 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +            Store(bus_channel=message).add(
it's strange with current implementation to sometimes send on self (which maps to channel) and sometimes send on message.

Especially in channel, message bus should redirect to channel bus.

2025-10-01 11:28 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_answer.py
> +            domain &= Domain("guest_id", "=", guest.id)
This domain is only correct if there is actually a guest

2025-10-01 11:32 UTC, seb-odoo reviewed
I'm afraid results would be completely irrelevant if we allow guests to vote, as anybody can create an infinite amount of them in most cases.

2025-10-01 11:34 UTC, seb-odoo commented on addons/mail/static/src/core/common/message_actions.js
> +    name: _t("End Poll Now"),
What's the point to specify "now"? All actions are done "now".

2025-10-01 11:38 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/discuss_poll_option_model.js
> +    selected_by_self;
alphabetical

2025-10-01 11:38 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/public_web/poll.js
> +        onWillStart(() => {
onWillStart is a bad hook. Maybe just put that in start.
Note the inverse of onwillunmount is mounted.
And the inverse of start would be destroy.

2025-10-01 11:38 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/public_web/@types/models.d.ts
> +    import { DiscussPollAnswerModel as DiscussPollAnswerModelClass } from "@mail/discuss/core/public_web/discuss_poll_answer_model";
code should just be in common unless we have a strong reason to do it differently (dependencies on things that are only present in public_web in particular).

2025-10-01 11:40 UTC, tsm-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +            Store(bus_channel=message).add(
Here it's just easier to use message. We want to send a store update to messages linked to the unlinked poll. It makes sense to send the message update, on the message channel IMO.

2025-10-01 11:41 UTC, alexkuhn commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
"choice" is another good alternative for "answer".

Usually the ambiguity with vote is not there thanks to using "vote" for individual answers / choices, whereas "answer" and "choice" is for picking one or multiple choices of the poll.

"options" is poor, because lack lots of color and very ambiguous: people could mistakenly think this refers to options to cutomize the poll. We don't have feature, but "options" is overused for customization so that's the 1st think people will wrongly guess just by the name.

2025-10-01 11:44 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
"option" is the best and most appropriate English word generally speaking though "one thing that can be chosen from a set of possibilities"

"choice" is more the act of choosing rather than the option itself

2025-10-01 11:51 UTC, phenix-factory commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
We have 141040 occurrences of the word "option" in the code base. It's very generic and carries very little meaning.
But what we could do is display "option" to the user and use "choice" internally.

2025-10-01 11:57 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
We have 0 occurrence of poll.option or poll_option or any such variation.

2025-10-01 12:02 UTC, alexkuhn commented on addons/mail/models/discuss/discuss_poll_answer.py
> +    _description = "Poll answer"
> "option" is the best and most appropriate English word generally speaking though "one thing that can be chosen from a set of possibilities"

This is far too generic in the context of a big software like Odoo. `options` used in a specific function is alright as we understand this is to tweak behavior of call with `options` param, which are optional.

Here options are not optional, and also "option" is ambiguous as I said: this can refer to option to customize the poll. You can say we don't have that so it should be obvious, but for people that just look at this code they will think "option" is meant for customization as this is the most used application of that word, only to waste time and realize this is "choice" / "answer" that is the most popular wording for these items in poll / survey that lots of applications use.

2025-10-01 12:08 UTC, alexkuhn commented
> I'm afraid results would be completely irrelevant if we allow guests to vote, as anybody can create an infinite amount of them in most cases.

I get this is a problem, but disabling the feature to vote for guests would prevent lots of application in which polls is a relevant use-case, i.e. teacher asking students (guests) to vote.

I think we should allow guests to vote, or have option to decide if guests can vote or not. This problem shows more a problem with not enough control on who can be invited to the conversation and also lack of easy way to authenticate with few friction. We are aware of these issues and we should remedy at some point, but I think we should not block huge features like poll to only authenticated users.

2025-10-01 12:20 UTC, seb-odoo commented
> teacher asking students (guests) to vote.

We already have the survey module for these cases, with all due respect having poll in channels is a fun gimmick and not a "huge" feature.

We're basically just making a heavily reduced version of what already exists in that module (single question, limited answer possibilities), maybe we should work on integration of survey into channels instead?

2025-10-01 12:30 UTC, tsm-odoo commented
> > teacher asking students (guests) to vote.
> 
> We already have the survey module for these cases, with all due respect having poll in channels is a fun gimmick and not a "huge" feature.
> 
> We're basically just making a heavily reduced version of what already exists in that module (single question, limited answer possibilities), maybe we should work on integration of survey into channels instead?

I updated this implementation I had from the last oxp. If we want to integrate survey into discuss, we’d need to introduce a bridge, adapt the entire model structure to match discuss and probably recreate all the views, since survey is built as a standalone external page. All in all, it’s not worth the effort, especially since no one will install the survey module only to vote on a chat on random, non-important subjects.

2025-10-01 12:33 UTC, alexkuhn commented
> We already have the survey module for these cases, with all due respect having poll in channels is a fun gimmick and not a "huge" feature.
> 
> We're basically just making a heavily reduced version of what already exists in that module (single question, limited answer possibilities), maybe we should work on integration of survey into channels instead?

We could probably integrate with survey, but that's a lot of work and as of now survey is definitely not compatible with Discuss needs, so this will postpone the possibility of having the feature way later.

At the same time, I think that's not ok to say we should use Survey for the basic use-case of polls with the example of teacher / students I provide. This case happens a lot and not just for teaching, this is very obvious that disabling the poll feature for guests adds a huge limitation for lots of application. Asking to use surveys with guests goes completely against the value of guests feature: frictionless communication between people.

I totally get the problem of voting more than once with guests, but that shouldn't punish everyone. We can have small option to disable guests if we really care for that problem, but we shouldn't just give up and make the feature almost unusable with guests.

2025-10-06 12:21 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/composer_actions.js
> +        store.self_partner && composer.targetThread?.channel_type?.includes("channel", "group"),
`X.includes("channel", "group")` => `["channel", "group"].includes(X)`

2025-10-06 12:27 UTC, alexkuhn commented on addons/mail/static/src/core/common/message_model.js
> +    async removeFromServer() {
Would add prefix `_` to better get this is an implementation details, `.remove()` is the one true way to remove the message.

2025-10-06 12:31 UTC, alexkuhn commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        <div class="d-flex justify-content-between">
Should add `gap-3` on the `div.justify-content-between` so the checkbox of "Allow multiple options" is not glued to "Duration" label:

<img width="351" height="447" alt="Image" src="https://github.com/user-attachments/assets/99534ac4-0b5e-4849-b4ed-99a93ddb6126" />
<img width="358" height="449" alt="Image" src="https://github.com/user-attachments/assets/9e563611-e8bb-48b1-8522-6ce71dbd8d7c" />

2025-10-06 12:37 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/poll.js
> +            );
The `X minutes / hours left` should be full sentence for translation.

Also would be nice to have seconds granularity below 1 minute, this makes the last seconds of poll thrilling :D

2025-10-06 12:38 UTC, phenix-factory commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        <div class="d-flex justify-content-between">
The checkbox should be on the left, not on the right, because it looks like you enable duration, not multiple options.

2025-10-06 12:39 UTC, phenix-factory commented on addons/mail/static/src/discuss/core/common/poll.js
> +            );
But not accurate since the poll cron doesn't run every minute :(

2025-10-06 12:41 UTC, alexkuhn commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        <div class="d-flex justify-content-between">
> The checkbox should be on the left, not on the right, because it looks like you enable duration, not multiple options.

You mean: `checkbox | checkbox-label | duration-label | duration-input`?
No, checkbox must be on right of checkbox-label.

We could swap order so the checkbox is on the very right of the dialog.

2025-10-06 12:47 UTC, tsm-odoo commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        <div class="d-flex justify-content-between">
Good point, I didn't have time to improve small/mobile views :)

2025-10-06 12:51 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/composer_actions.js
> +    onSelected: ({ owner }) => owner.dialogService.add(CreatePollDialog, { thread: owner.thread }),
`owner.thread` => `composer.targetThread`

2025-10-06 12:56 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/poll.js
> +            return _t("%(count)s vote", { count: option.number_of_votes });
No need for `count`: this is necessarily "1".

2025-10-06 12:57 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/poll.js
> +            return _t("%(count)s vote", { count: this.props.poll.numberOfVotes });
Same

2025-10-06 13:12 UTC, tsm-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +            );
It's not a big deal to have a few minutes of delay. Once the poll duration reaches 0, the display is "Poll will end soon" which is good enough.

2025-10-06 13:13 UTC, alexkuhn approved these changes
LGTM otherwise

2025-10-06 13:14 UTC, phenix-factory commented on addons/mail/static/src/core/common/create_poll_dialog.xml
> +        <div class="d-flex justify-content-between">
> You mean: checkbox | checkbox-label | duration-label | duration-input?

That would be ideal, yes.

> No, checkbox must be on right of checkbox-label.

The inverse of what everyone else does since the beginning of internet time?
We never miss a chance to be original.

2025-10-06 13:17 UTC, tsm-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +            return _t("%(count)s vote", { count: option.number_of_votes });
:face_with_peeking_eye:

2025-10-06 13:28 UTC, phenix-factory commented on addons/mail/static/src/discuss/core/common/poll.js
> +            );
I agree that it's not a big deal, but UI that lies bothers me…

2025-10-07 17:11 UTC, seb-odoo requested changes
Quick check (it was already pretty long), I didn't test and I didn't review JS and templates in details.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/security/ir.model.access.csv
> +access_mail_discuss_poll_erp_manager,access.mail.discuss.poll.user,model_discuss_poll,base.group_erp_manager,1,1,1,1
"user" naming in 2nd part is not correct

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/security/ir.model.access.csv
> +access_mail_discuss_poll_option_erp_manager,access.mail.discuss.poll.option.user,model_discuss_poll_option,base.group_erp_manager,1,1,1,1
"user" naming in 2nd part is not correct

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/security/ir.model.access.csv
> +acess_mail_discuss_poll_vote_erp_manager,access.mail.discuss.poll.vote.public,model_discuss_poll_vote,base.group_erp_manager,1,1,1,1
"public" naming in 2nd part is not correct

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_option.py
> +    text = fields.Char(required=True)
This field name is too generic, it will be a pain to find it back in codebase. The other 2 I'm ok to keep if we don't find better but this one really needs to change.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +        return self.channel_id
Checks in store target (is_internal in particular) are expecting the store target to be the channel directly (or user, or guest), not intermediate records whenever we can avoid them.

Using `bus.listener.mixin` on other kinds of records should be avoided whenever possible.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/mail_message.py
> +            Store.Many("ended_poll_ids", predicate=lambda m: m.ended_poll_ids, sudo=True),
predicate should never be on existence of the value itself as it would fail to un-set the value on future load after deleting the value

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/mail_message.py
> +            Store.Many("ended_poll_ids", predicate=lambda m: m.ended_poll_ids, sudo=True),
We might want a specific message (sub)type for flagging these or just always returning the fields inside channels.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +    question = fields.Char(required=True)
Not the easiest word to find back in the code base either

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +    duration = fields.Integer(help="Duration of the poll, in minutes", required=True)
Not the easiest word to find back in the code base either

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +    winning_option_ids = fields.One2many(
Why is this field a many? The compute only assigns value if there is only one winner, and code always accesses [0]

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +            Store.One("end_message_id", []),
Isn't it equivalent to just "end_message_id" effectively only returning the id?
Same for others that have empty [].

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +            Store(bus_channel=message).add(
channel (user and guest) should always be preferred for better working of target feature

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_option.py
> +            self.env["discuss.poll.vote"].search_fetch(domain, ["option_id"]).option_id
Better leave search_fetch field param empty to use standard prefetch (all columns). Other fields might be accessed in other parts of the code, there is no reason to not immediately get them (more I/O but the table has few columns anyway).

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/mail_poll_option.py
> +            option.vote_percentage = percentage_by_option[option]
Do we really need complex code to force integer?
Can't we just have a decimal percentage?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_vote.py
> +            vote.is_self_vote = False
this can be written outside of the loop

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_vote.py
> +            if not self.env.user.is_public
I would not use `is_public`, it's a compute on partner that checks all users. Better call `_is_public()` on user when we have it.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll_vote.py
> +            if not self.env.user.is_public
Same in all diff

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_dialog.xml
if poll are a channel feature, everything should be in discuss folder

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/discuss_poll_model.js
> +        return user.isInternalUser && this.create_uid === user.userId;
Why check internal user? Comparing id should always be self sufficient.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +        );
use effect should never be used to sync state, create a reactive instead, or better yet use the actual condition directly in the code if possible

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +    }
might need to debounce click?

or at least not do if voting is already true?

disabling through template is probably not sufficient as it will always be one render late?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +    }
Are those also possible with 0 or not? If so they should have their own case too.

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.scss
> +);
Those are very generic names, we might want to be a little more specific?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.xml
> +                        </span>
code be be clearer with one top level t-if and a few repetition rather than many conditions inside, including for the tag itself?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll_result.xml
> +        <div class="o-discuss-PollResult card border border-secondary rounded shadow-sm my-2" style="max-width: 500px;">
Aren't we supposed to have style in css?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll_result.xml
> +                            <p class="card-subtitle mb-0 text-muted smaller">Winning option<span class="mx-1">&#8729;</span><t t-esc="props.poll.winning_option_ids[0].vote_percentage"/>%</p>
This looks like a phrase that should be built for translation?

Do all languages use the % sign?

2025-10-07 17:11 UTC, seb-odoo commented on addons/mail/static/tests/tours/discuss_poll_tour.js
> +        { trigger: "[title='More Actions']", run: "click" },
selector a bit too generic, I'd expect at least one main component name to be present

2025-10-07 17:11 UTC, seb-odoo commented on addons/test_discuss_full/tests/test_performance.py
> +    #       - search ended_poll_ids
It can be done later, but it would be nice to have 2 messages in different channels with polls in the result so we can see also the fetch query and making sure they are properly batched.

2025-10-07 17:11 UTC, seb-odoo commented on addons/test_mail/tests/test_performance.py
> +        with self.assertQueryCount(employee=26):  # tm 23
Non-channels tests should not be impacted by a channel feature. (same for other similar tests)

2025-10-07 21:33 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/poll_result.xml
> +                            <p class="card-subtitle mb-0 text-muted smaller">Winning option<span class="mx-1">&#8729;</span><t t-esc="props.poll.winning_option_ids[0].vote_percentage"/>%</p>
> Do all languages use the % sign?

AFAIK all use it, but Turkish language has number after %. Because of that all "x%" should be a single translatable block.

2025-10-07 21:38 UTC, alexkuhn commented on addons/mail/static/src/discuss/core/common/poll.js
> +        );
Idea is to have manual toggle + default value.

Agree it's not good to `state` sync with `useEffect` here.

I'd suggest to not save `poll` value in `state.showResults` at all by doing this: when `state.showResults` is undefined it uses `poll` data, and manual change sets boolean on `state.showResults`.

2025-10-08 08:23 UTC, tsm-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +    duration = fields.Integer(help="Duration of the poll, in minutes", required=True)
When restricting to the mail module it's not that hard. However, we can perfix all those generic fields by "poll" if you feel like the redundancy is worthing it.

2025-10-08 08:39 UTC, tsm-odoo commented on addons/mail/models/mail_poll_option.py
> +            option.vote_percentage = percentage_by_option[option]
And what do we should in the UI? Rounding issues are a pain to handle, even more JS side. I'd rather keeping an  integer.

e.g.

33.6 => 34 ----- 33.6 => 34 ----- 32.8 => 33 => total 101

2025-10-08 08:42 UTC, tsm-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +    }
In english, zero is plural. So it will actually by correct (e.g. 0 votes)

2025-10-08 08:43 UTC, seb-odoo commented on addons/mail/models/mail_poll_option.py
> +            option.vote_percentage = percentage_by_option[option]
I don't understand why we would want to round percentages rather than displaying their actual value.

They should be only informative anyway, if there is a doubt users can always look at the number of votes.

2025-10-08 08:45 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll.js
> +    }
Only in English yes, but not in French and probably not in many other languages.

2025-10-08 08:45 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_poll.py
> +    duration = fields.Integer(help="Duration of the poll, in minutes", required=True)
Yes, even more so when the prefix is so short.

2025-10-08 08:52 UTC, tsm-odoo commented on addons/mail/static/src/discuss/core/common/poll_result.xml
> +        <div class="o-discuss-PollResult card border border-secondary rounded shadow-sm my-2" style="max-width: 500px;">
We often put style inline if its small/scss file is not created.  I can create the scss file if you want.

2025-10-08 08:55 UTC, seb-odoo commented on addons/mail/static/src/discuss/core/common/poll_result.xml
> +        <div class="o-discuss-PollResult card border border-secondary rounded shadow-sm my-2" style="max-width: 500px;">
It's always better to have less duplication and most likely faster for the browser for rendering them.

2025-10-08 10:01 UTC, tde-banana-odoo commented
Why limiting to discuss ? Would probably be useful on other models also. I know I would use it in some tasks, and won't create channels just for that.

2025-10-08 12:31 UTC, alexkuhn commented
> Why limiting to discuss ? Would probably be useful on other models also. I know I would use it in some tasks, and won't create channels just for that.

I'm definitely not against it, actually I argue quite a lot by saying almost all features should technically be available in both channels and chatter, and differences should be soft-specs rather than caused by technical limitations.

Here I'd say it's easier to make it work just for channels for now.

2025-10-10 14:40 UTC, seb-odoo requested changes

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_message.py
> +            and not self.ended_poll_ids
more simply message_type != "mail_poll"?

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/data/ir_cron_data.xml
> +            <field name="interval_number">5</field>
Don't we want to manually trigger the cron instead based on the expiration of the poll when setting it up?
As this will run for no reason.

See `ir_cron_discuss_channel_member_unmute`.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +               AND create_date + (poll_duration * INTERVAL '1 minute') < NOW() AT TIME ZONE 'UTC';
Shouldn't we store "end date" rather than poll_duration and requiring math with create date?
This would allow for better indexing too, and probably allowing to use search(_fetch)

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            if self.env.user._is_internal()
Quick return for that would be more clear.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            self.env[thread_model]._get_thread_with_access(thread_id, mode="read")
Should use `_get_thread_with_access_for_post` instead

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            body="", message_type="mail_poll", subtype_xmlid="mail.mt_comment"
Using "mt_comment" means all users following threads will receive notifications.
(like send message, not like log note).

Shouldn't we have a dedicated subtype for poll too instead, so let users control their subscription?

How will the poll be displayed when being sent as email? Just an empty body?

How's the native notification (or the internal odoo one) displayed for inbox users?

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +                    ("create_uid", "=", self.env.user.id),
We should probably let admin handle ending them too;

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            .search_fetch([("id", "=", poll_id), ("create_uid", "=", self.env.user.id)])
We should probably let admin handle deleting them too;

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        thread = self.env[options_sudo.poll_id.start_message_id.model]._get_thread_with_access(
_get_thread_with_access_for_post

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +            poll.winning_option_id = winners[0] if len(winners) == 1 else None
This depends on many more things.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +            "end_message_id",
alphabetical?

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +    def _poll_on_delete(self):
What's the point to use this hook with `at_uninstall=True`? Then just override `unlink` instead?

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +            Store(bus_channel=record_by_message[message]).add(
This is not ok for partner, as the bus target would be the partner itself and not its chatter.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        Store(bus_channel=thread).add(
Same in all places basically, this is only acceptable for channel not for other threads.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/message.scss
> +}
Would be best to rely on actual state in JS/template rather that presence of classes in DOM through css.
As body can be pretty much any user input, it's very weak to check like this.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/models/mail_message.py
> +    started_poll_ids = fields.One2many('mail.poll', 'start_message_id')
many is noise due to lack of one2one, we might want to create a non-stored many2one version of these 2 fields to simplify the rest of the code

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_option_dialog.js
> +        onMounted(() => this.props.registerRef?.(this.ref));
props not documented

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_option_dialog.js
> +        onMounted(() => this.props.registerRef?.(this.ref));
This should not be onMounted, it should be in setup as it doesn't depend on rendering.
And it should theoretically be called again on props change.

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_option_dialog.js
> +        onMounted(() => this.props.registerRef?.(this.ref));
Isn't it dead code?

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/message_model.js
> +        if (this.started_poll_ids.length || this.ended_poll_ids.length) {
always prefer message type rather than checking these fields

2025-10-10 14:40 UTC, seb-odoo commented on addons/mail/static/src/core/common/poll.js
> +    }
strong dislike for toggle methods as they are non deterministic by nature

Can't each case be inlined in the template anyway?

2025-10-10 14:57 UTC, alexkuhn commented on addons/mail/data/ir_cron_data.xml
> +            <field name="interval_number">5</field>
That would be nice! That means we can have exact moment when poll ends, and have seconds shown when under 1 minute from https://github.com/odoo/odoo/pull/185979#discussion_r2406039144

2025-10-10 14:58 UTC, alexkuhn commented on addons/mail/controllers/poll.py
> +            body="", message_type="mail_poll", subtype_xmlid="mail.mt_comment"
Chatter is not considered yet (this lacks real-time UI, which we plan to work on it soon after).
But yes, when we enable polls in chatter, we'd probably want to have polls in log notes too, and see how to display by email statically the poll with the options + send the poll results in the email.

2025-10-10 15:07 UTC, tde-banana-odoo commented on addons/mail/models/mail_message.py
> +        ('mail_poll', 'Poll')
I believe 'notification' is ok, don't see why we need a message type, which denotates the source. If you want to filter on "'poll" message, it is simply those with poll_id(s) being set.

2025-10-10 15:09 UTC, tde-banana-odoo commented on addons/mail/tests/test_mail_poll.py
> +    def test_09_poll_ui(self):
We have received word to reduce tests, as it becomes a nightmare for runbot. I believe we can reduce tests here, as models and flows are simple.

Also don't use numbers (makes no sense), use real namespacing.

Reduce boiler plate, reduce code size by removing useless UI / controllers usage when possible.

2025-10-10 15:10 UTC, tde-banana-odoo commented on addons/mail/models/mail_poll.py
> +    end_message_id = fields.Many2one("mail.message", ondelete="cascade", index=True)
Why do you have several links to message ? Isn't a poll inside a message anyway ? Model would be simpler.

2025-10-10 15:11 UTC, tde-banana-odoo commented on addons/mail/controllers/poll.py
> +            self.env["mail.poll"]
You screen is bigger than 10 characters, use them.

2025-10-10 15:12 UTC, tde-banana-odoo commented on addons/mail/models/mail_poll.py
> +            poll.end_message_id = record.message_post(
Don't do that, it is noise in DB. Simply close the poll and keep a single message.

2025-10-13 07:47 UTC, tsm-odoo commented on addons/mail/models/mail_poll.py
> +            poll.end_message_id = record.message_post(
Polls can close after 24 hours, and by that time, it's very unlikely that the original poll message is still visible. Especially in channels where lots of messages are sent. We need a way to notify users when a poll has ended and share the results. I don’t really see the issue here: polls consist of two messages: “poll has started + poll UI” and “poll has ended + poll results.”

2025-10-13 08:16 UTC, tsm-odoo commented on addons/mail/models/mail_poll.py
> +    def _poll_on_delete(self):
Warning on runbot: unlink-override: Avoid using `unlink()`, use `@api.ondelete` instead: `unlink()` overrides can easily break module uninstall (see `ondelete` docstring for the rundown).

2025-10-13 08:40 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +    def _poll_on_delete(self):
But if at_uninstall is True we are back to square one. I don't even know why this param exists on this decorator honestly.

If you read the docstring of `ondelete` we are not on the case that it tries to cover and we don't fit its guideline about either naming or raising exceptions.

2025-10-13 09:05 UTC, tsm-odoo commented on addons/mail/models/mail_message.py
> +        ('mail_poll', 'Poll')
Having a dedicated message type allows you to quickly identify poll messages without having to fetch the poll relation. It also makes the intent clearer. Conceptually, a "poll has started" message is not a notification.

2025-10-13 09:07 UTC, tsm-odoo commented on addons/mail/models/mail_poll.py
> +    end_message_id = fields.Many2one("mail.message", ondelete="cascade", index=True)
A poll comes with a start and an end message, as mentioned here: https://github.com/odoo/odoo/pull/185979#discussion_r2425467179.

2025-10-13 09:33 UTC, tsm-odoo commented on addons/mail/models/mail_message.py
> +            and not self.ended_poll_ids
Message can have the "mail_poll" message type, but what matters is whether the poll has been deleted or not. So the type alone is not enough.

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        self.env.ref("mail.ir_cron_mail_end_polls")._trigger(end_dt)
Just a question we were wondering: if multiple polls are running at the same time, will it correctly trigger the 2nd one?
Or do we need to check inside the cron method if we need to re schedule it?

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/models/mail_poll.py
> +        self.env["mail.poll"].search([("poll_end_dt", "<=", "now")])._end_and_notify()
`_end_and_notify` uses fields so better use `search_fetch`

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/tests/test_mail_poll.py
> +        poll = self.env["mail.poll"].search([("start_message_id.res_id", "=", channel.id)])
Just for consistency, if we work by model/res_id we should also provide the model here.

Also the current code makes the test kind of weak to what is in the database, it would be better if we received the actual poll or message id from either the rpc or the bus.

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/tests/test_mail_poll.py
> +        poll = self.env["mail.poll"].search([("start_message_id.res_id", "=", channel.id)])
same in all tests

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/poll.js
> +            this.state.remainingTimeText = this.props.poll.remainingTimeText;
Just to be sure: do we have render or not if the value is written again but unchanged?

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/mail_poll_model.js
> +        return _t("%(seconds)s seconds left", { seconds });
it makes no difference but it's strange to break the pattern and not use seconds > 1 first

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/mail_poll_model.js
> +        return this.create_uid === user.userId;
`create_uid` should be a relation towards res.users and compare accordingly

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/mail_poll_model.js
> +    /** @type {number[undefined]} */
wrong syntax?
also id shouldn't be undefined

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/message.scss
> +    flex-grow: 1;
usually done with classes

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_dialog.js
> +        this.props.close();
No await? Close is done even if save fails?

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_option_dialog.js
> +                    !ev.isTrusted ||
Why check `isTrusted`?

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/demo/mail_poll_demo.xml
> +            ]"/>
I think demo data are translated, and this would make these options probably non-translatable.

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        Store(bus_channel=thread, bus_subchannel="thread").add(poll).bus_send()
We have quite a lot of repetition already, we might want to introduce a method on thread that returns this channel/subchannel combination that we could spread here to be consistent in all places. `**thread._get_thread_store_target()` (store or bus target) or something like that.

2025-10-14 09:17 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        thread = self._get_thread_with_access_for_post(start_message.model, start_message.res_id)
Note: voting in portal will require passing the access kwargs to validate thread access.

2025-10-20 08:26 UTC, tsm-odoo commented on addons/mail/controllers/poll.py
> +        self.env.ref("mail.ir_cron_mail_end_polls")._trigger(end_dt)
Yes. `_trigger` creates a `ir.cron.trigger` records each time it's called with the appropriate `call_at` dt.

2025-10-20 08:29 UTC, tsm-odoo commented on addons/mail/static/src/core/common/poll.js
> +            this.state.remainingTimeText = this.props.poll.remainingTimeText;
Just tried it: writting the same value doesn't trigger another render.

2025-10-22 15:37 UTC, seb-odoo reviewed
I was in the middle of the review earlier and then we had meetings, so I'm not really sure where I left. I'll send this already and restart from the start when those are taken care of.

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            poll_sudo._end_and_notify()
Do we actually need to check existence before calling `_end_and_notify`?
We don't check existence in the delete method before unlink.

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        # sudo - mail.poll: internal user can create poll on an accessible thread.
better move the comment just above the sudo line when possible

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        # sudo - mail.poll: creator of the poll or admins can end a poll prematurely.
better move the comment just above the sudo line when possible

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        # sudo - mail.poll: creator of the poll or admins can delete a poll.
better move the comment just above the sudo line when possible

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            .sudo()
missing sudo comment

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        guest = self.env["mail.guest"]._get_guest_from_context()
We usually use `_get_current_persona` when we want one or the other (it now returns the user)

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        ).bus_send()
I guess it doesn't matter at all but technically we only need to send `number_of_votes` for the `options_sudo` and not the others.

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +            return
We sometimes re-send the current value to the current user bus when they call a method that does nothing, attempting to fix their UI if they clicked because it was outdated.

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        guest = self.env["mail.guest"]._get_guest_from_context()
also _get_current_persona

2025-10-22 15:37 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        Store(**thread._get_store_target()).add(
It can be another PR but It feels like we would want to generalize `_bus_channel` of bus listener mixin (or another method) to have both channel and possibly a default subchannel.

And message channel should redirect to its thread.

channel should override the `_get_store_target` to be the standard bus channel of discuss channel?
Or actually be replaced by the new "thread" one?

Also this will currently fail on other threads than channel because they don't define `bus.listener.mixin` so `bus_send` -> `_bus_send` can't work.

2025-10-23 06:00 UTC, ThanhDodeurOdoo commented on addons/mail/static/src/core/common/mail_poll_option_model.js
> +    number_of_vote;
```suggestion
    number_of_votes;
```

2025-10-23 06:57 UTC, tsm-odoo commented on addons/mail/controllers/poll.py
> +            poll_sudo._end_and_notify()
No, `_end_and_notify` does nothing on empty recordsets and doesn't issue any query.

2025-10-23 07:18 UTC, tsm-odoo commented on addons/mail/controllers/poll.py
> +        ).bus_send()
Agreed, but I don't think it's worth calling `bus_send` twice. Especially since `vote_percentage` will already fetch `number_of_votes`.

2025-10-23 07:58 UTC, tsm-odoo commented on addons/mail/controllers/poll.py
> +        Store(**thread._get_store_target()).add(
I think we can refine bus channel/sub channel later. For now, I added the `bus.listener.mixin` to thread and overriden the `_store_target` of discuss channel to keep it simple.

2025-10-23 15:14 UTC, seb-odoo approved these changes
@robodoo delegate+

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/controllers/poll.py
> +        self_bus_channel = guest if self.env.user._is_public() else self.env.user
user is only returned if non-public, so this can just be `user or guest` (or `guest or user` works too, as we always only return one of them)

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/data/ir_cron_data.xml
> +            <field name="interval_type">days</field>
As they are triggered, is there a way to avoid it automatically running at all?

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/models/mail_poll_option.py
> +            "option_label",
alphabetical

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/models/res_partner.py
> +    _inherit = ['mail.thread.blacklist', 'res.partner', 'mail.activity.mixin']
Why re-order them?

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/static/src/core/common/composer_actions.js
> +        return ["channel", "group"].includes(composer.targetThread?.channel_type);
read channel fields from channel model in new code

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/static/src/core/common/create_poll_dialog.js
> +        this.orm = useService("orm");
maybe I missed it but I don't see it being used in this component

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/static/src/core/common/mail_poll_model.js
> +    }
do we sometimes need to await vote but never removeVote?

2025-10-23 15:14 UTC, seb-odoo commented on addons/mail/static/src/core/common/message_actions.js
> +        message.poll && !message.poll.end_message_id && message.poll.createdBySelf,
Technically admin should also be allowed to use these actions.

2025-10-24 07:20 UTC, tsm-odoo commented on addons/mail/data/ir_cron_data.xml
> +            <field name="interval_type">days</field>
No, but other parts of the code use month as the `interval_type` with `9999` as the `interval_number`. I did the same.

2025-10-24 07:21 UTC, tsm-odoo commented on addons/mail/models/res_partner.py
> +    _inherit = ['mail.thread.blacklist', 'res.partner', 'mail.activity.mixin']
MRO issue with after adding the `bus.listener.mixin` to the thread model. Kevin did the same in the chatter PR. That's odd though as I would expect MRO resolution to be able to find the correct order without any help.

2025-10-24 07:28 UTC, tsm-odoo commented
@robodoo r+

2025-10-24 10:03 UTC, closed without merging