[FIX] payment,sale: remove amount_to_invoice from the views
odoo/odoo pull request #185977
Opened 2024-10-31 10:49 UTC by epictete

When it was originally introduced on 'sale.order', the 'amount_to_invoice' field was only intended to be used to trigger the credit limit warnings on sale orders and invoices.

With time, it came to be used for other unintended purposes, which created confusion regarding the computation method and ensuing fixes that did more harm than good.

This is why it was decided to remove all unintended usages of the field in the views, and rename it to further clarify its meaning.

task-4213628

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-10-31 10:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/185977.png)](https://mergebot.odoo.com/odoo/odoo/pull/185977)

2024-10-31 12:08 UTC, AntoineVDV requested changes
Hello, I don't see why `amount` is removed from the transaction route params in the `payment` module? This parameter is not related to the `amount_to_invoice` field of `account*` modules.

2024-10-31 12:18 UTC, epictete commented
> Hello, I don't see why `amount` is removed from the transaction route params in the `payment` module? This parameter is not related to the `amount_to_invoice` field of `account*` modules.

Indeed, my bad, I was checking why all the tests were failing on runbot when you pointed it out :laughing:

2024-10-31 17:02 UTC, william-andre approved these changes

2024-11-04 09:17 UTC, Feyensv approved these changes

2024-11-04 10:36 UTC, william-andre commented
@robodoo r+

2024-11-04 11:00 UTC, robodoo commented
@epictete @william-andre linked pull request(s) odoo/upgrade#6700 not ready. Linked PRs are not staged until all of them are ready.

2024-11-05 12:21 UTC, closed without merging