[FIX] account: migrate demo data from default content to demo attribute
odoo/odoo pull request #186391
Opened 2024-11-06 07:09 UTC by masm-odoo

This commit has been generated to move only the demo data(default content) inside the new attribute `data-oe-demo`.

2024-11-07 04:49 UTC, hamo-odoo requested changes
Same as reviewed on Enterprise PR. Add the task in the commit and commit causing the issue

2024-11-07 09:45 UTC, hubvd approved these changes

2024-11-08 06:22 UTC, hamo-odoo requested changes
@masm-odoo @hubvd 

As discussed with @jco-odoo we might not want any demo data on `account`  reports (unless required because as of now it sets a bad example in the code base) since the fields are already sanitized and validated. Most of them are with `t-if`. In that case the demo data is unlikely to be visible on the reports (most of them are not reproducible).

 and to fix the only necessary issue (i.e. Marc Demo visible on payment receipt) might go with different PR. Better to re-target this PR in master since we are cleaning up

2024-11-08 06:22 UTC, hamo-odoo commented on addons/account/views/report_invoice.xml
> +                            <span t-if="o.name != '/'" t-field="o.name" data-oe-demo="INV/2023/0001"/>
```suggestion
                            <span t-if="o.name != '/'" t-field="o.name"/>
```

2024-11-08 06:22 UTC, hamo-odoo commented on addons/account/views/report_invoice.xml
> +                                <span t-field="o.invoice_date" data-oe-demo="2023-09-12"/>
```suggestion
                                <span t-field="o.invoice_date"/>
```

2024-11-08 06:22 UTC, hamo-odoo commented on addons/account/views/report_invoice.xml
> +                                <span t-field="o.invoice_date_due" data-oe-demo="2023-10-31"/>
```suggestion
                                <span t-field="o.invoice_date_due"/>
```

2024-11-08 06:22 UTC, hamo-odoo commented on addons/account/views/report_invoice.xml
> +                                <span t-field="o.delivery_date" data-oe-demo="2023-09-25"/>
```suggestion
                                <span t-field="o.delivery_date"/>
```

2024-11-08 06:22 UTC, hamo-odoo commented on addons/account/views/report_invoice.xml
> +                                <span t-field="o.invoice_origin" data-oe-demo="SO123"/>
```suggestion
                                <span t-field="o.invoice_origin"/>
```

2024-11-08 10:10 UTC, hamo-odoo commented
Ignore my code suggestions It's better to keep `data-oe-demo` because of Studio

Thanks @hubvd

2024-11-11 12:05 UTC, hamo-odoo approved these changes
lgtm

2024-11-22 09:46 UTC, hamo-odoo commented
@jco-odoo Did you check on this PR?

2024-12-24 10:09 UTC, masm-odoo commented
Closing the PR as the task has been canceled :face_with_diagonal_mouth:

2024-12-24 10:09 UTC, closed without merging