[IMP] point_of_sale, **: move fields for category timing
odoo/odoo pull request #186558
Opened 2024-11-07 10:03 UTC by meji-odoo

**: pos_self_order

In this commit:
===
- Moved the fields hour_after and hour_until from the pos_self_order module to the point_of_sale module in the pos.category model.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-07 10:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186558.png)](https://mergebot.odoo.com/odoo/odoo/pull/186558)

2024-11-19 06:25 UTC, paso-odoo requested changes

2024-11-19 06:25 UTC, paso-odoo commented on addons/point_of_sale/models/pos_category.py
> +    hour_after = fields.Float(string='Availability After', default=0.0, help="The product will be available after this hour for online and self order.")
```suggestion
    hour_until = fields.Float(string='Availability Until', default=24.0, help="The product will be available until this hour for online order and self order.")
    hour_after = fields.Float(string='Availability After', default=0.0, help="The product will be available after this hour for online order and self order.")
```

2025-01-15 14:39 UTC, davidmonnom approved these changes

2025-01-17 13:29 UTC, davidmonnom commented
@robodoo r+

2025-01-18 02:58 UTC, closed without merging