[IMP] point_of_sale: implement global invoice like in sales
odoo/odoo pull request #186723
Opened 2024-11-08 06:36 UTC by sjai-odoo

In this commit:
-------------------
- A new wizard is created to facilitate making multiple invoices at the same time
- If consolidated billing is checked, the common invoice will be grouped by partner and config_id; if not, an individual invoice will be created per order.
- Now, the invoice form view has a smart button to navigate connected pos orders Also, navigate orders from the chatter.

Task: 4256209

2024-11-08 06:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186723.png)](https://mergebot.odoo.com/odoo/odoo/pull/186723)

2024-11-25 07:32 UTC, paso-odoo requested changes

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +                    invoices += new_move
```suggestion
                    invoices |= new_move
```

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +                            line_vals.append((0, 0, {
Use Command.create

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/models/account_move.py
> +        return result
```suggestion
        action = self.env['ir.actions.act_window']._for_xml_id('point_of_sale.action_pos_pos_form')

        if len(self.pos_order_ids) > 1:
            action['domain'] = [('id', 'in', self.pos_order_ids.ids)]
        elif len(self.pos_order_ids) == 1:
            action['views'] = [(self.env.ref('point_of_sale.view_pos_pos_form', False).id, 'form')]
            action['res_id'] = self.pos_order_ids.id
        else:
            action = {'type': 'ir.actions.act_window_close'}
        return action
```

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +        action['context'] = context
```suggestion
        action['context'] = {'default_move_type': 'out_invoice'}
```

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +from odoo.exceptions import UserError
```suggestion
import pytz

from odoo import api, models, fields, _
from odoo.exceptions import UserError
from odoo.tools import float_round
```

2024-11-25 07:32 UTC, paso-odoo commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +            float_round(order_id.amount_paid - order_id.amount_total, precision_rounding=self.pos_order_ids.currency_id.rounding) != 0
```suggestion
            float_round(order_id.amount_paid - order_id.amount_total, precision_rounding=order_id.currency_id.rounding) != 0
```

2024-11-28 11:03 UTC, paso-odoo requested changes

2024-11-28 11:03 UTC, paso-odoo commented on addons/point_of_sale/models/pos_order.py
> +            action = {'type': 'ir.actions.act_window_close'}
```suggestion
        if len(invoices) == 1:
            form_view = [(self.env.ref('account.view_move_form').id, 'form')]
            if 'views' in action:
                action['views'] = form_view + [(state, view) for state, view in action['views'] if view != 'form']
            else:
                action['views'] = form_view
            action['res_id'] = invoices.id
        else:
            action['domain'] = [('id', 'in', invoices.ids)]
```

2025-02-11 08:17 UTC, sjai-odoo commented
Yes, i have rebased the branch, can you please check it.

2025-02-11 10:29 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if any(order_id for order_id in self.env['pos.order'].browse(self.env.context.get('active_ids')) if not order_id.partner_id):
should also check that there is a single partner. Occurrence of conflicting partners is not allowed.

2025-02-11 10:35 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if any(order_id for order_id in self.env['pos.order'].browse(self.env.context.get('active_ids')) if not order_id.partner_id):
Also, all the orders should have the same fiscal position.

2025-02-11 10:36 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if any(order_id for order_id in self.env['pos.order'].browse(self.env.context.get('active_ids')) if not order_id.partner_id):
The sessions should also come from the same config.

2025-02-12 04:45 UTC, sjai-odoo commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if any(order_id for order_id in self.env['pos.order'].browse(self.env.context.get('active_ids')) if not order_id.partner_id):
We have filtered all this [inside the function](https://github.com/odoo/odoo/pull/186723/files#diff-823d8a700674063aa28fc3b1c802acc41d144b538a949f36ecd382de851bd346R49-R54)

So it will create a global invoice of same config>partner>fiscal_position 
If we have 2 partner orders it will create 2 invoices one for one parner orders another for another partner orders and likewise for all config and fiscal positions as well.

2025-02-13 11:37 UTC, caburj commented on addons/point_of_sale/models/account_move.py
> +    reversed_pos_order_id = fields.Many2many('pos.order', string="Reversed POS Order",
restore many2one

2025-02-13 11:38 UTC, caburj commented on addons/point_of_sale/views/account_move_views.xml
> +                <field name="reversed_pos_order_id" widget="many2many_tags" readonly="True" invisible="not reversed_pos_order_id"/>
restore this line

2025-02-13 11:42 UTC, caburj commented on addons/point_of_sale/views/account_move_views.xml
> +                        invisible="pos_order_count == 0 or move_type not in ('out_invoice', 'out_refund', 'in_invoice', 'in_refund', 'out_receipt', 'in_receipt')">
```suggestion
                        invisible="pos_order_count == 0 or move_type not in ('out_invoice', 'out_refund')">
```

2025-02-13 11:44 UTC, caburj commented on addons/point_of_sale/wizard/pos_confirmation_wizard.py
> +        selected_orders.write({'partner_id': selected_orders.filtered(lambda o: o.partner_id).partner_id.id})
```suggestion
        selected_orders.write({'partner_id': selected_orders.partner_id.id})
```

2025-02-13 11:46 UTC, caburj commented on addons/point_of_sale/wizard/pos_confirmation_wizard.xml
> +    <record id="view_confirm_action_wizard" model="ir.ui.view">
```suggestion
    <record id="point_of_sale.view_confirm_action_wizard" model="ir.ui.view">
```

prefix even if it's implicitly in pos. It's easier to find this view with the prefix.

2025-02-13 11:46 UTC, caburj commented on addons/point_of_sale/wizard/pos_confirmation_wizard.xml
> +                    <button name="action_cancel" string="Cancel" type="object" class="btn-secondary" special="cancel"/>
```suggestion
                    <button string="Cancel" type="object" class="btn-secondary" special="cancel"/>
```

2025-02-13 11:48 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +    @api.depends('consolidated_billing')
```suggestion
```

doesn't depend on the consolidated_billing

2025-02-13 11:50 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +                raise UserError(_("You should select at least one order with a partner."))
also take into account the situation where the selected orders points to multiple partners.

2025-02-13 11:52 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if not any(order_id for order_id in selected_orders if order_id.invoice_status == 'to_invoice'):
```suggestion
        if not any(order_id.invoice_status == 'to_invoice' for order_id in selected_orders):
```

2025-02-13 11:55 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        if not any(order_id for order_id in selected_orders if order_id.invoice_status == 'to_invoice'):
```suggestion
        if any(order_id.invoice_status == 'invoiced' for order_id in selected_orders):
```

2025-02-13 11:56 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +                "Cannot create an invoice. No items are available to invoice.\n"
```suggestion
                "Cannot create an invoice. One of the selected orders are already invoiced.\n"
```

2025-02-13 11:58 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +                "To resolve this issue, please ensure that selected POS orders contains some POS orders that are neither invoiced nor draft."
```suggestion
                "Cannot create an invoice. To resolve this issue, please ensure that the selection contains orders that are neither invoiced nor draft."
```

2025-02-13 12:00 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        pos_orders = selected_orders.filtered(lambda o: not o.account_move)
```suggestion
        uninvoiced_orders = selected_orders.filtered(lambda o: not o.account_move)
```

2025-02-13 12:02 UTC, caburj commented on addons/point_of_sale/wizard/pos_make_invoice.py
> +        pos_orders = selected_orders.filtered(lambda o: not o.account_move)
```suggestion
```

no need for this. all the selected orders are not yet invoiced.

2025-02-14 11:38 UTC, caburj commented on addons/point_of_sale/tests/test_pos_basic_config.py
> +        self.config = config2
no. the 2nd session should come from the original config.

there should just be 1 generated invoice from the orders coming from different sessions.

2025-02-14 16:52 UTC, caburj commented
robodoo r+

2025-02-14 23:39 UTC, closed without merging