[IMP] website: add the `s_newsletter_benefits` snippet
odoo/odoo pull request #186820
Opened 2024-11-08 15:46 UTC by chgo-odoo

task-4306880
Part of task-4077427

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-08 15:46 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186820.png)](https://mergebot.odoo.com/odoo/odoo/pull/186820)

2024-11-13 08:15 UTC, Brieuc-brd requested changes
Nice work @chgo-odoo 👍 
I've left a few comments, minor things :)

2024-11-14 08:04 UTC, Brieuc-brd commented on addons/website_mass_mailing/views/snippets_templates.xml
> +    <div class="s_popup o_newsletter_popup o_snippet_invisible" Zdata-vcss="001" data-invisible="1">
```suggestion
    <div class="s_popup o_newsletter_popup o_snippet_invisible" data-vcss="001" data-invisible="1">
```

2025-01-20 13:45 UTC, lebl-odoo commented
Hi there :wave: 

I had a quick look, here are some remarks:

1/ Cross icon is too small
![image](https://github.com/user-attachments/assets/bf39daa3-2be4-4bfc-aaa0-fbaf73fb8a0a)

2/ The font size is not right, but I suppose it's because it's not based on the last fix (https://www.odoo.com/odoo/project/1695/tasks/4420329)
![image](https://github.com/user-attachments/assets/85a9c669-d2d0-4070-bc62-55f2eccfed70)

3/ Hide/show elements will hide all dialog
![image](https://github.com/user-attachments/assets/deb29d56-b628-442c-90e5-40741c5af233)

Except this, I love it!

2025-01-20 13:54 UTC, chgo-odoo commented
Hello @lebl-odoo 👋 

> 1/ Cross icon is too small
Yeah, I think this is optical since we don't have the background the default `s_popup` has being the icon. I'll see to scale it a bit.

> 2/ The font size is not right, but I suppose it's because it's not based on the last fix
I rebased recently but I'll give it one more try, this should be related to this PR indeed


3/ Hide/show elements will hide all dialog
Quite unlucky, the `s_popup` can indeed receive inner snippet... That being said, I think it's an expected behaviour so I'd keep it as is. It should be quite uncommon to drop a popup within another one.

2025-03-12 13:40 UTC, chgo-odoo commented
Hello @lebl-odoo 👋 

I fixed everything  you mentioned except the close icon size which should be addressed globally and not only for this snippet IMO.

I'm not exactly sure why we use this trick of using a character instead of the close icon, beside the fact that the close icon uses an opacity, which I'm not sure is the limiting factor.

2025-03-13 08:24 UTC, lebl-odoo commented
Hello @chgo-odoo ,

Thx, it looks nice!

I still have some remarks:

On mobile, some padding is missing
![image](https://github.com/user-attachments/assets/df049e13-7c3a-49c0-9432-6b7ac865b662)

When we select "full", we lost the bg-color value
![image](https://github.com/user-attachments/assets/3f78b0ad-9aa9-47cd-96a6-76faaf6eda3a)

Should we allow the small value for the size option?
![image](https://github.com/user-attachments/assets/c723f512-0c4f-4d61-b8a3-76de8cff1a16)

> I fixed everything you mentioned except the close icon size which should be addressed globally and not only for this snippet IMO.
I'll create a ticket to address the issue

Moreover, shouldn't we display modal like this in mobile? It's a "pavé dans la mare" and shouldn't be address in this PR (cc @stefanorigano)
![image](https://github.com/user-attachments/assets/b8a701cf-dd91-47c2-9da1-ecdb54fb4c24)

2025-03-13 08:39 UTC, chgo-odoo commented
Thanks @lebl-odoo 👍 

I added some padding so the mobile version looks nicer. For the rest, these are related to the overall `s_popup` snippet so it should probably be handled globally. For the missing background in full, it looks like something intended tho since we clearly define this in CSS. Perhaps there is a use-case for it... Probably need some investigation as well as other points.

If the new version with the spacing looks okay to you, I suggest we move it forward

2025-03-13 14:35 UTC, lebl-odoo commented
I had a final look, thx @chgo-odoo

2025-07-08 09:58 UTC, chgo-odoo commented
Hello @odoo/rd-website 👋 

This snippet is ready for tech. review, could you have a look at it ?

I adapted the JS part to match the new builder options. Regarding the `preview.png` I guess we can keep it as a PNG and don't need to convert it to WEBP, could you confirm?

Thanks !

2025-07-31 12:52 UTC, qsm-odoo requested changes

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website/static/src/img/snippets_previews/s_newsletter_benefits_preview.png
- Commit message: remove the useless description
- This image could stay a png, it's not critical but if we can optimize "Odoo's weight", but it's still good to change it to a webp: it's that much less to download when users want to download Odoo :wink: (it's not something we have to think about that much, but when there is no downside, why not?)

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website/static/tests/tours/snippets_all_drag_and_drop.js
> +    const isModal = ['s_popup', 's_newsletter_subscribe_popup', 's_newsletter_benefits'].includes(snippet.name);
- Maybe your snippet technical name should also be suffixed with `_popup` to be consistent?
- Rebase your branch, it's conflicting on that line ;)

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website_mass_mailing/static/src/website_builder/newsletter_benefits_option.xml
> +        <BuilderRange action="'setClassRange'" actionParam="['p-lg-0','p-lg-1','p-lg-2','p-lg-3','p-lg-4','p-lg-5']" max="5"/>
- Do you have to put the "max 5"? It's not automatic?
- Add spacing after each `,` in your actionParam

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website_mass_mailing/static/src/website_builder/newsletter_benefits_option_plugin.js
> +                applyTo: ".row",
This looks very fishy:
- Why a specific feature for this specific snippet for something as basic as this? If we really do want that (do we really @lebl-odoo ? The "edge spacing" for this new snippet), should not it be a "popup" option, not this snippet only?
- Can't you replace the text_image by something else? Should not the user keep your feature in most case?
- You don't want to target all rows (you could type /columns in the snippet, you would have then multiple rows), it should only target the main one.

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website_mass_mailing/views/snippets_templates.xml
> +    <div class="s_popup o_newsletter_popup o_snippet_invisible s_newsletter_benefits" data-vcss="001" data-invisible="1">
I think it's a good time to do like in website: create a snippet folder and add this new one in its own file inside. You can leave the rest as it is for now.

2025-07-31 12:52 UTC, qsm-odoo commented on addons/website_mass_mailing/views/snippets_templates.xml
> +                                    <img src="/web_editor/shape/website_mass_mailing/s_newsletter_benefits.svg" class="img img-fluid mx-auto" alt=""/>
I don't think it should still be `/web_editor/`

2025-08-01 09:44 UTC, chgo-odoo commented on addons/website_mass_mailing/static/src/website_builder/newsletter_benefits_option_plugin.js
> +                applyTo: ".row",
We already have this option for the `s_blockquote`. I'm not against having a global controller honestly, we tend to having a global controller when we only have a few occurrences but IMO as soon as we have two snippets using it, it's better to have it global. I'll let you decide whether this should be global or not.

2025-08-01 16:22 UTC, qsm-odoo commented on addons/website_mass_mailing/static/src/website_builder/newsletter_benefits_option_plugin.js
> +                applyTo: ".row",
We should, yes :+1:

2025-08-05 07:01 UTC, chgo-odoo commented on addons/website_mass_mailing/views/snippets_templates.xml
> +                                    <img src="/web_editor/shape/website_mass_mailing/s_newsletter_benefits.svg" class="img img-fluid mx-auto" alt=""/>
Which folder would you suggest moving it to ? It doesn't seem really clear to me, I aligned the `src` on this other snippet : https://github.com/odoo/odoo/commit/8b5247249fbf7ec51207bcf32fea6bbe5c4d6297#diff-27472e6fa62b441bfa469bba947b25265a504266e582d17e3b384b8b8126bb98R40

2025-08-05 07:03 UTC, chgo-odoo commented
Thanks for the review @qsm-odoo 👍 

In the end, I dropped the Edge spacing option, the more I think about it the more it's looking like something I introduced only to please this specific layout. On top of that, applying this to this specific snippet only doesn't make any sense.

I've put the changes within a !fixup as I pushed the branch multiple times
https://github.com/odoo/odoo/pull/186820/commits/654721e60dc5c557ae9fdde7a346ffa00cea705b

Thanks

2025-08-14 15:05 UTC, qsm-odoo commented on addons/website_mass_mailing/views/snippets_templates.xml
> +                                    <img src="/web_editor/shape/website_mass_mailing/s_newsletter_benefits.svg" class="img img-fluid mx-auto" alt=""/>
Missed this commit sorry: I did not suggest moving anything, just using the new `/html_editor/shape` instead of `/web_editor/shape` as they decided to duplicate the controllers.

2025-08-14 15:07 UTC, chgo-odoo commented on addons/website_mass_mailing/views/snippets_templates.xml
> +                                    <img src="/web_editor/shape/website_mass_mailing/s_newsletter_benefits.svg" class="img img-fluid mx-auto" alt=""/>
Oh okay 😄 Will adapt

2025-08-14 15:08 UTC, qsm-odoo commented
While fixing https://github.com/odoo/odoo/pull/186820#discussion_r2276903851 you can squash @chgo-odoo, I'll review/merge everything again afterwards.

2025-08-14 15:16 UTC, chgo-odoo commented
Thanks @qsm-odoo, should be good now

2025-08-14 15:41 UTC, qsm-odoo approved these changes
I push-forced to mention the right apps and the right snippet name in the commit message.

@robodoo r+

2025-08-14 20:23 UTC, robodoo commented
@chgo-odoo @qsm-odoo unable to stage: merge conflict

2025-08-14 20:28 UTC, chgo-odoo commented
@qsm-odoo Fixed the conflict

the diff was with https://github.com/odoo/odoo/commit/d217d08cb54fc9968603ddc281deba4087c3cac3#diff-ec4b77839f67e12ca2058f5bd1084f903d9bf9cf7fadbdebfc7dfa2a6b8a8f14R45

2025-08-18 09:15 UTC, qsm-odoo approved these changes
@robodoo r+

2025-08-18 11:33 UTC, xmo-odoo commented
@robodoo r- 

https://runbot.odoo.com/runbot/batch/2086884/build/87069815

2025-08-18 16:59 UTC, qsm-odoo approved these changes
@chgo-odoo In fact when you push-forced [here](https://github.com/odoo/odoo/pull/186820#issuecomment-3189787488), you lost my fix of the commit message... :grimacing: 

Anyways, should be good now.

@robodoo r+

2025-08-18 20:11 UTC, closed without merging