[ADD] website_sale: Google Merchant Center xml data feed
odoo/odoo pull request #186976
Opened 2024-11-12 17:06 UTC by lipiraux

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2025-01-06 12:22 UTC, Feyensv reviewed
Quick little comments after looking to the PR out of curiosity.
Great work :sparkles:

2025-01-06 12:22 UTC, Feyensv commented on addons/website_sale/tests/test_website_sale_gmc.py
> +class TestWebsiteSaleGMCCommon(HttpCase):
Can't you rely on existing commons to simplify your setup ?
Maybe the `ProductAttributesCommon` ?

2025-01-06 12:22 UTC, Feyensv commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        super().setUpClass()
No need for the empty override ;)

2025-01-06 12:22 UTC, Feyensv commented on addons/website_sale/tests/test_website_sale_gmc.py
> +class TestWebsiteSaleGMCItems(TestWebsiteSaleGMCCommon):
Since there is no setup difference between this class and `TestWebsiteSaleGMCController`, I don't think it's necessary to use two separate classes :thinking:

2025-01-06 12:22 UTC, Feyensv commented on addons/website_sale/views/website_sale_templates.xml
> +            <title><t t-out="title"/></title>
```suggestion
            <title t t-out="title"/>
```
`t-out` doesn't have to be in its own xml node, unless you believe it's clearer like this.

2025-01-06 12:22 UTC, Feyensv commented on addons/product/models/product_product.py
> +    def _get_gmc_items(self):
why is the method defined in `product` and not `website_sale` ?
It's only used by `website_sale(_stock)` anyway

2025-01-07 09:30 UTC, lipiraux commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        super().setUpClass()
oops, forgot about this one :smile:

2025-01-07 09:32 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +            <title><t t-out="title"/></title>
I just didn't know you could do this :smile:

2025-01-29 12:52 UTC, vchu-odoo requested changes
Great work, thank you!

Here are some small nitpickings mostly and suggestions.

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale/models/website.py
> +    )
```suggestion
    enabled_gmc_src = fields.Boolean(string="Google Merchant Center Data Feed", default=False)
```

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale/models/website.py
> +        string="Google Merchant Center Data Feed",
Why `string` is different from the one in `res_config_settings`  ?

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale/views/res_config_settings_views.xml
> +                    string="Google Merchant Center Data Source"
You already put the string on the field, no need for repetition.

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
warehouse can be empty on website, meaning that a product can be sold if it is in stock in any warehouse

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale_stock/models/product_product.py
> +                    or self.warehouse_id.lot_stock_id.id
out of curiosity: do you know how we can change the value of the product's warehouse field?

2025-01-29 12:52 UTC, vchu-odoo commented on addons/website_sale/views/website_sale_templates.xml
> +                    <t id="more_values"/>
what is it for? :)

2025-01-29 17:22 UTC, lipiraux commented on addons/product/models/product_product.py
> +    def _get_gmc_items(self):
Well, I don't fully remember why :sweat_smile:. 
I think I got issues with the order of override when I started this feature, and a solution was to
define the method at the root of the model and add the dependent datas there so that the overrides are
sure to have the proper datas. But, the code evolved, and there is no dependencies anymore. 
This just sticked for some reason...
I'll put this in `website_sale`

2025-01-30 08:55 UTC, lipiraux commented on addons/website_sale/__manifest__.py
> +        'views/website_sale_templates.xml',
I'll move it to `templates.xml`

2025-01-30 09:23 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +        website = request.website
Im not familiar with the auth process in odoo yet, but is it possible to allow http request with
basic auth? Otherwise, the google crawler will not be able to access the generated file. If its not
possible, I could add a constraint in the settings that does not allow someone to use gmc if the
product are not accessible by a public user.

2025-01-30 09:32 UTC, vchu-odoo commented on addons/website_sale/controllers/main.py
> +        website = request.website
I think we should discuss it with @chevalierv and @Feyensv :)

2025-01-30 09:52 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +            'description': seo.get('og:description', ""),
Its true that calling this function does a lot of computation for not so much. What I was worried
about is that the SEO in Odoo changes, and those changes are not reflected here. But I see now from
the blames that its not moving much, and will probably not change drastically in the future.

I'll use your sugestion, I just have one question: for the title fallback, `get_website_meta`
constructs something like `Home | My Website` should I do the same?

2025-01-30 09:52 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +            'title': seo.get('og:title', website.name),
see sugestion below

2025-01-30 09:55 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +    def _get_image_link(self, website_id=None):
Changed it to `_get_image_1920_link` and did the same for `_get_extra_image_links` -> `_get_extra_image_1920_links`

2025-01-30 09:57 UTC, lipiraux commented on addons/website_sale/models/website.py
> +        string="Google Merchant Center Data Feed",
Good notice, I changed it to "Google Merchant Center Data Source" since thats how google call it

2025-01-30 09:58 UTC, lipiraux commented on addons/website_sale/models/website.py
> +    )
It fits :sparkles:

2025-01-30 09:59 UTC, lipiraux commented on addons/website_sale/static/tests/tours/website_sale_gmc_advertised_prices.js
> +});
I don't know why, the setting to automatically add a new line at the end of a file was not enabled :sweat_smile:

2025-01-30 10:03 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +                        <g:additionnal_image_link t-out="link"/>
Nice catch thanks :+1:

2025-01-30 10:12 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +<template id="gmc_xml"><t t-translation="off">&lt;?xml version="1.0" encoding="UTF-8"?&gt;</t>
The xml tag must be at the top of the file, if I ident here there will be a new line in between unfortunately

2025-01-30 10:14 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +<template id="gmc_xml"><t t-translation="off">&lt;?xml version="1.0" encoding="UTF-8"?&gt;</t>
In the beginning, the xml code was pretty long, and this was just to try and save a bit of
horizontal space. But, VFE sugested some syntax changes and now everything fits

2025-01-30 10:22 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +            <t t-translation="off">&lt;link&gt;<t t-out="link"/>&lt;/link&gt;</t>
For some reason I don't understand, qweb will render this as 
```xml
<link/>
https://e9e4-94-140-169-33.ngrok-free.app/fr
```
So I had to force it to put the link inside the `<link>` tag.
Even:
```
<link><t t-out="link"><link/>
```
doesn't work 😭

2025-01-30 10:25 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +                    <t id="more_values"/>
I use it to extend the gmc file with the `availability_date`. See
`odoo/addons/website_sale_stock/views/website_sale_templates.xml` (or `gmc_templates.xml` denpending
on the version :smile:)

2025-01-30 10:44 UTC, vchu-odoo commented on addons/website_sale/views/website_sale_templates.xml
> +            <t t-translation="off">&lt;link&gt;<t t-out="link"/>&lt;/link&gt;</t>
Okay, maybe because of the translation tag :thinking: . Good to know :)

2025-01-30 10:46 UTC, vchu-odoo commented on addons/website_sale/views/website_sale_templates.xml
> +                    <t id="more_values"/>
but you can add a name to L63 `t`  tag and XPath that, no?

2025-01-30 10:51 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +            <t t-translation="off">&lt;link&gt;<t t-out="link"/>&lt;/link&gt;</t>
with or without translation it still tries to reduce it and puts the link outside the tag... I
thinks its because, qweb is thought as an html template engine, and its not common to put text
inside the link tag

2025-01-30 10:52 UTC, lipiraux commented on addons/website_sale/views/website_sale_templates.xml
> +                    <t id="more_values"/>
true

2025-01-30 15:01 UTC, lipiraux commented on addons/website_sale_stock/models/product_product.py
> +                    or self.warehouse_id.lot_stock_id.id
in the inventory tab of the product template I beleive 🤔

2025-01-30 15:05 UTC, lipiraux commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
For this I changed a "bit" the computation of the availability date. I also check the outgoing moves
now. Do you think its necessary or I should just take the `max(incoming_moves.date)`?

2025-02-05 08:21 UTC, vchu-odoo commented on addons/website_sale/controllers/main.py
> +                Domain.AND([
is it working? :eyes: 
Never seen that, we usually use `expression`   from  odoo.osv

2025-02-05 12:01 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +                Domain.AND([
I saw this in commit odoo/odoo@5ef007a2116e528b796ebe80fb291ba5f1a94c8f some time ago and thought it was released, or was going to be released soon. I guess its not... 😅

2025-02-10 10:30 UTC, vchu-odoo reviewed
Thank you for your changes!

My comments are mostly suggestions and nitpicking :smile:

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale/tests/test_website_sale_gmc.py
> +    def test_gmc_xml_accessible_iff_gmc_src_enabled(self):
split into two tests `test_gmc_xml_accessible_if_gmc_setting_enabled`    and `test_gmc_xml_not_found_if_gmc_setting_disabled`  , better to test one thing at a time :)

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        )
this can be extracted into another test to check if the format is correct.

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        gmc_xml = etree.XML(response.content)
you already tested the request, maybe we can simply call the product's method `_get_gmc_items`  , same for methods below  (just a suggestion)

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        return base64.encodebytes(response.content).replace(b'\n', b'')
should be moved to common class

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        response_image_blue_sofa_1 = self.url_open_image(self.blue_sofa_item['additional_image_link'][1])
do you believe it checks gmc logic? It seems to me that it checks product_product logic more...

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale_stock/views/gmc_templates.xml
> +        <xpath expr="//t[@name='shippings']" position="after">
should work
```suggestion
        <t name="shippings" position="after">
```

2025-02-10 10:30 UTC, vchu-odoo commented on addons/website_sale_stock/views/gmc_templates.xml
> +                                 t-out="item['availability_date']"/>
```suggestion
            <g:availability_date
                t-if="'availability_date' in item"
                t-out="item['availability_date']"
                />
```

2025-02-10 10:32 UTC, vchu-odoo commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
for me it is better to keep it simple, wdyt @Feyensv ?

2025-02-10 10:51 UTC, Feyensv commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
Mhm, feels like this availability dates feature is going way too far indeed (and will probably timeout the gmc request in big databases).
Is it really necessary to provide that information or to provide it precisely ?

2025-02-10 14:34 UTC, vchu-odoo commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
I believe it is optional and can be what we want :)

2025-02-11 15:36 UTC, lipiraux commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
I'll revert to something simple. I just send a msg to boje to know if he prefers the max(incoming_moves.date) or min(incoming_moves.date). I have a doute now, cause as you pointed out there is no requirements from google for this field to tell the truth or not. max would be safe but pessimist, min would be optimist but more chance to be false.

2025-02-11 15:47 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +            'title': website_homepage.website_meta_title or  website.name,
took me a couple of seconds to find the diff from vscode 😂. Nice catch!

2025-02-11 16:10 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +        vals = {
what do you think of `gmc_data`, or `gmc_source_data`, or `source_data`, or just `data` 😅?

2025-02-11 16:13 UTC, lipiraux commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        response_image_blue_sofa_1 = self.url_open_image(self.blue_sofa_item['additional_image_link'][1])
yeah your right, I'll just keep the limit tests and remove those

2025-02-11 16:25 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +        delivery_carriers = (
good to know, thanks!

2025-02-11 16:30 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +                'identifier_exists': "no",
I thought, double quote was meant for strings visible to the user. But know that you talk about it,
it seems I missunderstood, and its more the strings that are meant to be displayed. So here I should
use single quote as it is not intended that way.

2025-02-11 16:44 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +                and product.base_unit_count is not False
no, your right. I meant to check if its zero or not. If its zero, we don't want to show this in google

2025-02-11 17:55 UTC, lipiraux commented on addons/website_sale_stock/models/product_product.py
> +                    (request and request.website.warehouse_id.lot_stock_id.id)
update: we'll drop the field 😅. Taking the minimal approach does not give a precise enough date,
and finding the right one is too heavy to compute.

2025-02-12 10:08 UTC, vchu-odoo approved these changes
Thank you for the changes, nice work!
Approving as nothing is blocking :)

Only small nitpickings left..
Just small comment about tests. We normally want to test the logic that is crucial and if changed by mistake will break the flow. The trivial things (if they are changed they can be changed only on purpose) do not require tests. We try to keep tests as simple as possible, testing one thing at a time. So I would encourage you to check all the tests again and see if anything can be improved as you better know the flow.

2025-02-12 10:43 UTC, lipiraux commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        # Electronics / Electronics Accessories / Computer Accessories
oops 👀

2025-02-12 10:49 UTC, lipiraux commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        self.assertGreaterEqual(set(consu_combo), self.items.keys())  # subseteq
I guess I wanted to test that it ignores services and only includes consu/combo, but what this line
really tests here is: does it contain consu/combo products? And this is already tested pretty much
everywhere, so no need.

2025-02-12 14:45 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +                # TODO: redo :)
After much more thought, I realized yesterday that I was computing this wrong. So I fixed it this morning

2025-02-12 15:25 UTC, lipiraux commented
Hello @vchu-odoo, 

Sorry for all the changes, each time I read my code I find something wrong, or missing and feel the need to update. 

Big thanks for all the reviews, I really appreciate it 😊

2025-02-14 11:13 UTC, vchu-odoo commented on addons/website_sale/tests/common.py
> +class WebsiteSaleGMCCommon(ProductVariantsCommon, WebsiteSaleCommon):
Could you please create a new file for this class? It should be one file per class :)

2025-03-06 15:20 UTC, AntoineVDV requested changes

2025-03-06 15:20 UTC, AntoineVDV commented on addons/website_sale/models/product_product.py
> +        """
Could use a complete docstring.

2025-03-07 10:03 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +        order_line = dummy_order.order_line[0]
yeah..., in order to compute each delivery method price, I need to call
`delivery.carrier.rate_shipment()` which expects a sale.order. So what I tried to do is create a
temporary order and reuse it over and over, changing the product and country destination each time.

Maybe there is another way that I haven't found?

2025-03-07 10:44 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            if product.type not in ('consu', 'combo'):
might already remove this filtering in the product model, and only keep it in the controller

2025-03-07 14:22 UTC, lipiraux commented on addons/website_sale_stock/models/product_product.py
> +from odoo.http import request
nope

2025-03-07 14:27 UTC, lipiraux commented on addons/website_sale/__manifest__.py
> +        'views/gmc_templates.xml',
did you mean? (alphabetical order)
```suggestion
        'views/delivery_form_templates.xml',
        'views/gmc_templates.xml',
        'views/templates.xml',
```
or was is intended to put it at the top?

2025-03-25 15:25 UTC, AntoineVDV requested changes
Almost there! The method restructuration makes it much easier to read, override, and maintain :+1:

2025-03-25 15:36 UTC, Feyensv commented on addons/website_sale/controllers/main.py
> +            return redirection
Unless I'm missing something, it feels like you'll always recompute the pricelist and cart prices because most of the time `pricelist` won't be set :thinking:

2025-03-25 16:15 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            )
Had to before, but with all the rewrite, I forgot to reformat

2025-03-25 16:16 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            [('is_published', '=', True), ('website_id', 'in', (request.website.id, False))],
nice

2025-03-25 16:29 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            ),
god damnit, I need to check formatting anytime I change things (frustrated against myself)

2025-03-25 16:32 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +        IrHttp = self.env['ir.http']
I don't know the perf impact of creating a ir.http class, but to be sure, I keep a ref to one, and
then reuse it every time the format_product_link is called (i.e. for every product in self)

2025-03-25 16:42 UTC, AntoineVDV commented on addons/website_sale/models/product_product.py
> +        IrHttp = self.env['ir.http']
You just access it from the env's dict so it's atomic ;)

2025-03-25 16:43 UTC, lipiraux commented on addons/website_sale/models/delivery_carrier.py
> +                        price=shipment_rate['price'], delivery_method=dm,
yep to both :+1: :smile:

2025-03-25 18:13 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +            return redirection
:thinking:

2025-03-28 08:55 UTC, lipiraux commented on addons/website_sale/controllers/main.py
> +            return redirection
edit: We decided to drop the idea of having a predictable product and shop page by forcing the default pricelist when nothing is specified. This will ensure the current behavior remains. However, it is still possible to specify the pricelist, which is used by Google Merchant Center.

2025-03-28 11:00 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            [('is_published', '=', True), ('website_id', 'in', (request.website.id, False))],
edit: `=?` doesn't work here, `field =? value` is similar to `where value in (null,false) or field = value`.

2025-03-31 14:51 UTC, AntoineVDV approved these changes

2025-03-31 14:51 UTC, AntoineVDV commented on addons/website_sale/tests/test_website_sale_gmc.py
> +        )
Loop over the two products in a single test.

2025-03-31 14:51 UTC, AntoineVDV commented on addons/website_sale/tests/test_website_sale_gmc.py
> +    def test_gmc_items_bundle_iff_combo(self):
Not a big deal but I don't know how popular "iff" is among non-graduate developers :thinking:

2025-04-01 08:23 UTC, lipiraux commented on addons/website_sale/models/product_product.py
> +            ][:100], # Apply the limit after looping to include as many results as possible.
🫣

2025-04-01 09:28 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2025-04-01 09:28 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-04-01 10:00 UTC, robodoo commented
@lipiraux @AntoineVDV linked pull request(s) odoo/documentation#12261 not ready. Linked PRs are not staged until all of them are ready.

2025-04-01 15:57 UTC, closed without merging