[IMP] core: tools.config.is_testing
odoo/odoo pull request #186924
Opened 2024-11-12 12:28 UTC by kmagusiak

A flag on the configuration that indicates whether Odoo was started in a test mode.
However, sometimes it is enough to check that we are in the test mode.

task-4270485

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-12 12:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186924.png)](https://mergebot.odoo.com/odoo/odoo/pull/186924)

2024-11-25 13:25 UTC, Julien00859 commented
A property on the config object looks good to me. Not too sure about the name, but I have nothing better that comes to mind.

2024-12-20 09:42 UTC, kmagusiak commented
@Xavier-Do rebased and removed the config entry that is no longer needed since #190080 is merged.
Could you review/r+?

2024-12-20 11:16 UTC, Xavier-Do commented
Can you rephrase de pr message to indicate the updated changes? :)

2025-01-08 13:28 UTC, kmagusiak commented on addons/account/models/account_move.py
> +        return not (tools.config['test_enable'] or modules.module.current_test)
I removed this and reviewed the other ones.

2025-01-30 08:49 UTC, Xavier-Do requested changes
Except this last comment LGTM

2025-01-30 08:49 UTC, Xavier-Do commented on addons/base_geolocalize/models/res_partner.py
> +        ):
```suggestion
        if not self._context.get('force_geo_localize') and (
            self._context.get('import_file')
            or modules.module.current_test
            or not self.env.registry.ready
        ):
```

maybe something like that  (not sure, to check and test)

2025-01-31 09:31 UTC, Xavier-Do commented
@robodoo r+

2025-01-31 09:31 UTC, robodoo commented
@Xavier-Do you may want to rebuild or fix this PR as it has failed CI.

2025-01-31 10:35 UTC, kmagusiak commented
Security: all gettting the testing flag from the current thread (as before)
- addons/sms/models/sms_sms.py:113
- addons/sms/models/sms_sms.py:163
- addons/stock/models/res_company.py:196

2025-01-31 10:53 UTC, rco-odoo commented
@robodoo override=ci/security

`getattr(threading.current_thread(), 'testing', False)` is used on a non-forgeable object (it does not depend on local variables) and a static attribute name.  Hence it is safe.

2025-01-31 13:42 UTC, closed without merging