[REF] website(_*)_sale(_*): cart access
odoo/odoo pull request #186923
Opened 2024-11-12 12:21 UTC by Feyensv

In all ecommerce flows, the cart was found, and created through the `sale_get_order` util, which not only found the cart, but also updated it according to the current request configuration.

This led recently to a big issue where all the ecommerce orders became assigned to the superuser (aka OdooBot) because the method was called with a modified environment, with the superuser.

This big issue highlighted once again this method, which doesn't work as you'd expect it to and was one of the cornerstones of the ecommerce flows that needed to be adapted to avoid such issues, clarify its uses, ...

The first idea was to follow the existing approach done for the pricelist and the fiscal_position, through computed fields on the website, as a form of 'request cache', but as the field result cannot be sudoed by default like the result of `sale_get_order` was, this means all code would have to be aware of it to avoid forgetting to sudo the field result.

> request.website.sale_order_id.sudo()

After more thoughts, inspiration came from the existing `website` attribute on the request, since the order (and pricelist) are cached in the request session, and are not expected to change during most requests (except specific ones).

> request.cart (sudo)
> request.pricelist
> request.fiscal_position (sudo)

All three records can be empty, if a cart is needed, it must be created clearly through the `_create_cart` method, replacing the previous `force_create` argument of `sale_get_order`.

This new approach:
* provides a clear single access to the existing cart (if any)
* ensures that the cart checks and automatic updates (update the address after login, removing archived products, ...) are only done once by request, with the request environment. Local updates to the environment in routes won't trigger unexpected changes to the cart.
Routes and method overrides won't trigger the check again when fetching the cart, like it was the case previously with calls to `sale_get_order`
* improves performance
* drops the 'confusing' fields on the `website`, which were dependent on the request (and session)

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-12 12:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186923.png)](https://mergebot.odoo.com/odoo/odoo/pull/186923)

2025-01-21 16:00 UTC, chevalierv requested changes
Hello @Feyensv 

LGTM 👍 I've pushed some nitpicking changes in a separate commit and made a few minor comments. Let me know what you think :)

Have a nice day!

2025-01-23 11:26 UTC, Feyensv commented on addons/website_sale/models/ir_http.py
> +        request.fiscal_position = lazy(request.website._get_and_cache_current_fiscal_position)
Wdym the context ?

2025-01-23 11:27 UTC, Feyensv commented on addons/website_sale/models/website.py
> +                pricelist = cart_sudo.pricelist_id
Indeed, good catch :eyes:

2025-01-23 11:28 UTC, Feyensv commented on addons/website_sale/models/sale_order.py
> +
Mhm, I dunno, I find it more logical to only update the cart quantity in the method(s) where the quantity is updated, instead of having that in some controllers unexpectedly.

2025-01-23 11:30 UTC, Feyensv commented on addons/website_sale/controllers/cart.py
> -
Mhm, probably forgot to remove it in update_cart.
The problem of `sale_reset` is that it does way more than you'd think, including removing the SO from the session (leading to an abandoned cart that nobody has access to, when there is no reason to stop using it for the current customer).

2025-01-23 13:04 UTC, chevalierv commented on addons/website_sale/models/ir_http.py
> +        request.fiscal_position = lazy(request.website._get_and_cache_current_fiscal_position)
In `website`, they also update `request.context` sometimes. I guess we won't need this kind of hack but I wanted to double check

2025-01-23 16:00 UTC, Feyensv commented on addons/website_sale/models/website.py
> +            if 'website_sale_cart_quantity' not in request.session:
to avoid computing the cart qty if not needed.

2025-01-23 16:02 UTC, Feyensv commented on addons/website_sale/models/website.py
> +            if request and request.geoip.country_code and self.partner_id.id == partner_sudo.id:
mhm, prefer not changing that rn

2025-01-28 11:28 UTC, Feyensv commented on addons/website_sale/models/website.py
> +            order_sudo._recompute_prices()
Moved to the controller :ok_hand: (and moved the empty pricelist logic to the only place where it was used).

2025-01-31 10:31 UTC, reth-odoo approved these changes

2025-01-31 12:24 UTC, Julien00859 approved these changes

2025-01-31 12:26 UTC, Julien00859 commented on addons/website_sale/models/ir_http.py
> +        request.pricelist = lazy(request.website._get_and_cache_current_pricelist)
Also I have no recollection of any bug related to the extra request attributes inside `website_sales`. So I guess you guys are already doing a good job at using them safely. :+1:

2025-01-31 13:13 UTC, Feyensv commented
@robodoo r+

2025-01-31 15:13 UTC, closed without merging

2025-03-29 13:02 UTC, kig-odoo commented
Cool 👍