[IMP] base,l10n_us: Replace aba_routing with generalized clearing_number field in res.partner.bank
odoo/odoo pull request #186972
Opened 2024-11-12 16:26 UTC by seifgneedy

The ABA number is the clearing number of banks in the US, while some countries in EU still use clearing number for international purposes. So we can generalize the Clearing Number by adding it to res.partner.bank in base and removing the aba_routing from l10n_us.

The Clearing Number label is dependent on the country: for the US, it's ABA/Routing.

task-4307862

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-12 16:26 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/186972.png)](https://mergebot.odoo.com/odoo/odoo/pull/186972)

2024-11-12 16:49 UTC, HydrionBurst commented on addons/l10n_us/models/res_partner_bank.py
> +            if self.env.company.country_code == 'US' and bank.clearing_number and not re.match(r'^\d{1,9}$', bank.clearing_number):
Shouldn't we use `bank.country_code == 'US'` instead of `self.env.company.country_code == 'US'`?

and maybe add `country_code` to `api.constrains`

2024-11-12 16:49 UTC, HydrionBurst commented on odoo/addons/base/data/res_country_data.xml
> +            <field name="clearing_number_label">ABA/Routing</field>
Curious, are most countries have their own different `clearing_number_label`? If it is only for `ABA/Routing` used by US. Maybe leave the field in l10n_us, or hard code it in `_get_view`

2024-11-12 16:49 UTC, HydrionBurst commented on odoo/addons/base/models/res_bank.py
> +        if clearing_number_label := self.env.company.country_id.clearing_number_label:
should we see `ABA/Routing` label when we are in an US company but checking EU res.bank records?

2025-02-12 12:56 UTC, oco-odoo requested changes
Also, don't forget to rebase ; you have a conflict on the enterprise branch ;)

2025-02-12 12:56 UTC, oco-odoo commented on addons/l10n_us/models/res_partner_bank.py
>                  raise ValidationError(_('ABA/Routing should only contains numbers (maximum 9 digits).'))
```suggestion
                raise ValidationError(_('ABA/Routing should only contain numbers (maximum 9 digits).'))
```

No need to fix this in stable, but while we're at it ...

2025-02-13 15:43 UTC, oco-odoo approved these changes
@robodoo r+

2025-02-14 21:58 UTC, closed without merging