[IMP] project: covert tests to hoot
odoo/odoo pull request #187029
Opened 2024-11-13 09:21 UTC by maad-odoo

Purpose for this commit:
To convert the qunit test cases that depends on the 'mail/../tests/helpers/test_utils'

Part of task-3818666

2024-11-13 09:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187029.png)](https://mergebot.odoo.com/odoo/odoo/pull/187029)

2024-11-14 13:43 UTC, rapr-odoo requested changes

2024-11-14 13:43 UTC, rapr-odoo commented on addons/project/static/tests/view/project_task_kanban.test.js
> +    await openView({
Same here.

2024-11-14 13:43 UTC, rapr-odoo commented on addons/project/static/tests/view/project_task_kanban.test.js
> +    const [stageId] = pyEnv["project.task.type"].create([{ name: "New" }]);
You can pass single value instead of List.

2024-11-14 13:43 UTC, rapr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    const pyEnv = await startServer();
Same here.

2024-11-15 12:49 UTC, rapr-odoo requested changes

2024-11-15 12:49 UTC, rapr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    const [projectId] = env["project.project"].create([{ name: "Project One" }]);
You can pass a single value object, so it will return a single value only.

2024-11-15 12:49 UTC, rapr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    const userId = env["res.users"].create([{ name: "User one", login: "one", password: "one" }]);
Same here.

2024-11-15 12:49 UTC, rapr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    await click(target.querySelector("button.o_state_button"));
No need to use querySelector here. You can pass the selector directly.

2024-11-15 12:49 UTC, rapr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +        )
You can use `:contains` selector to find the element with text you needed.

2024-11-18 12:34 UTC, rapr-odoo approved these changes

2024-11-18 13:32 UTC, xavierbol reviewed
Thanks for your work! 🙂 

Why did you not remove all legacy test files? Did we forget to convert some tests in hoot? 🤔

2024-11-19 04:32 UTC, maad-odoo commented
Hello @xavierbol, the purspose of this PR is to convert only those testcases to hoot that depends on the `mail/../tests/helpers/test_utils`

2024-11-19 05:36 UTC, ppr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    ]);
also are these needed? under HOOT we can create those records like [Project](https://github.com/odoo/odoo/blob/master/addons/project/static/tests/project_models.js#L10) .

cc @xavierbol

2024-11-19 06:09 UTC, ppr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +import { defineProjectModels, ProjectTask } from "./project_models";
```suggestion
import { expect, test, describe } from "@odoo/hoot";
import { click, queryAllTexts } from "@odoo/hoot-dom";
import { animationFrame } from "@odoo/hoot-mock";

import { mountView } from "@web/../tests/web_test_helpers";

import { defineProjectModels, ProjectTask } from "./project_models";
```
I think grouping the imports make them more readable 🤓

2024-11-19 06:14 UTC, ppr-odoo commented on addons/project/static/tests/view/project_task_kanban.test.js
> +    env["project.task"].create([{ name: "task one", project_id: projectId, stage_id: stageId }]);
same as `project_task_state_selection.test.js`

2024-11-19 06:15 UTC, ppr-odoo commented on addons/project/static/tests/view/project_task_kanban.test.js
> +import { animationFrame } from "@odoo/hoot-dom";
```suggestion
import { beforeEach, expect, test, describe } from "@odoo/hoot";
import { animationFrame } from "@odoo/hoot-dom";

import { onRpc, mountView, makeMockServer } from "@web/../tests/web_test_helpers";

import { defineProjectModels } from "../project_models";

```

2024-11-19 11:37 UTC, seb-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    await click("button.o_state_button");
Are you sure? click or other inputs are supposed to wait until all events have been triggered, and also adding an async point allows pending micro tasks to execute before doing the following asserts.

2024-11-19 11:43 UTC, seb-odoo approved these changes
There is an issue with manifest and also few suggestions from ppr above but otherwise it's looking ok.

Good that most of those tests have been already converted! They don't always have the same name so it's a bit hard to track but those I checked looked indeed already done, so I'm assuming it's all good.

2024-11-19 16:43 UTC, seb-odoo commented
There is still a runbot issue, it looks like the test suite cannot start, probably a dependency issue?

2024-11-20 05:40 UTC, ppr-odoo commented on addons/project/static/tests/project_task_state_selection.test.js
> +    await click("button.o_state_button");
> Are you sure? click or other inputs are supposed to wait until all events have been triggered, and also adding an async point allows pending micro tasks to execute before doing the following asserts.

In the commit below, the click function has been converted to asynchronous, so we now need to add await . [commit](https://github.com/odoo/odoo/commit/713247e2f1e1161eac1ea501e38ed16b6ad46782#diff-79c44c0f17da5883ebf041d28c8749658b80cd695457b804f9e3bc00769e081bR1652)

2024-11-20 06:05 UTC, mjvi-odoo commented on addons/project/static/tests/view/project_task_kanban.test.js
> +test("quick create button is visible when the user has access rights.", async () => {
@maad-odoo  is there any specific reason to create a new file
you can move these tests to [this file](https://github.com/odoo/odoo/blob/18.0/addons/project/static/tests/project_task_kanban_view.test.js) to reduce the reusability of code.

2024-11-20 09:40 UTC, maad-odoo commented
@seb-odoo 
Dependency issues are solved now and the runbot is green now

2024-11-20 14:25 UTC, seb-odoo approved these changes
@robodoo r+

2024-11-20 14:25 UTC, robodoo commented
@maad-odoo @seb-odoo linked pull request(s) odoo/enterprise#73789 not ready. Linked PRs are not staged until all of them are ready.

2024-11-20 14:25 UTC, robodoo commented
@maad-odoo @seb-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-11-20 14:25 UTC, seb-odoo commented
@robodoo rebase-ff

2024-11-20 14:25 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-11-20 17:28 UTC, closed without merging