[FIX] l10n_fr_account: add ids to bank records in csv
odoo/odoo pull request #187204
Opened 2024-11-14 10:21 UTC by jjmaksoud

Records in csv files also need an id column
to create a data entry, and to be able to load
the file in a mode other than init.

An error is seen on ci during upgrade failing to load the module.
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-14 10:21 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187204.png)](https://mergebot.odoo.com/odoo/odoo/pull/187204)

2024-11-14 16:12 UTC, alialfie requested changes
Thanks for the fix! The changes LGTM but since this is targeting stable, I think we'll need a local migration script, as upgrading after adding IDs on an existing DB will end up duplicating the data.
Also, maybe it would be helpful to add more details in the description as this PR doesn't have a task? A summary of what you explained to me privately would be very helpful to anyone reading this commit message in the future :)

2024-11-18 12:55 UTC, alialfie approved these changes
Perfect thanks! A final review will come soon :)

2024-11-21 16:03 UTC, FlorianGilbert approved these changes
Sorryyy

@robodoo r+

2024-11-22 07:47 UTC, closed without merging