[IMP] wip
odoo/odoo pull request #187357
Opened 2024-11-15 08:50 UTC by malb-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-15 08:50 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187357.png)](https://mergebot.odoo.com/odoo/odoo/pull/187357)

2024-12-04 09:17 UTC, SaddemAmine commented on addons/account/static/src/components/many2many_tags_banks/many2many_tags_banks.js
> +export class FieldMany2ManyTagsBanksTagsList extends TagsList {
I'm not sure but if this class necessary ? Can't we use `TagList` directly ?

2024-12-04 10:46 UTC, malb-odoo commented on addons/im_livechat/tests/test_js.py
> +            watch=True,
forgot to remove that, i will wait for the review to be done to remove it

2024-12-05 10:29 UTC, SaddemAmine approved these changes
LGTM except for a tiny typo in your commit message (cart) and a failing JS test 👀

2024-12-09 09:30 UTC, FlorianGilbert requested changes
In your commit message, you refer to the product form view, isn't it the partner one?

Could you please confirm me that localization changes are not in the spec? I can't find anything about it.
I didn't see the change for the industry field and for the add button in kanban view, is that normal?

2024-12-09 09:30 UTC, FlorianGilbert commented on addons/account/models/res_partner_bank.py
> +    color = fields.Integer(string="Color", compute='_compute_color')
```suggestion
    color = fields.Integer(compute='_compute_color')
```
Not necessary

2024-12-09 10:10 UTC, malb-odoo commented on odoo/addons/base/i18n/base.pot
>  msgstr ""
I will export the pot and po again, i did the change because we had a test that was failing since we check that translation exactly

2024-12-09 10:17 UTC, malb-odoo commented on odoo/addons/base/i18n/base.pot
If i'm not mistaken in master no need to export pot and po, but in this case, a test was checking if the term other address was well translated and so i had to change that

2024-12-09 10:17 UTC, malb-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                    <field name="partner_properties" columns="2"/>
If i remember correctly, if we put the properties field in a group it wasn't displayed but i will check again

2024-12-09 10:19 UTC, malb-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                                                <field name="email"/>
![image](https://github.com/user-attachments/assets/b2aa48bf-51d7-42fd-9854-3784f3f4f6af)
PS: the two last point will be done by the JS team

2024-12-09 12:39 UTC, malb-odoo commented on addons/purchase/views/res_partner_views.xml
>                              <span> day(s) before</span>
The rest seems to be working fine, but the maxLength doesn't work tough

2024-12-09 13:26 UTC, tde-banana-odoo reviewed
SM part review. Thanks for the cleaning and title removal, it simplifies things :) 

Have to say however the properties is probably something that should be extracted and thought again as it feels quite wrong to me.

Cheers !

2024-12-16 09:32 UTC, FlorianGilbert commented on odoo/addons/base/views/res_partner_views.xml
> +                                    <field name="company_id" groups="base.group_multi_company" options="{'no_create': True}" readonly="parent_id" force_save="1" invisible="not is_company"/>
@Olivier-olma

2024-12-16 09:59 UTC, FlorianGilbert approved these changes
Except the case for the `company_regitry` instead of the `company_id`
LGTM

2024-12-16 12:04 UTC, tde-banana-odoo commented on addons/web/static/tests/_framework/mock_server/mock_model.js
> +                    if (container && container[field.definition_record_field]) {
Is it still relevant ? What does it fix ?

2024-12-16 15:05 UTC, malb-odoo commented
@tde-banana-odoo Thanks for the reviews and help ! Could you take a last look before we merge this :smile:

2024-12-19 15:29 UTC, FlorianGilbert commented
@robodoo r+

2024-12-20 11:19 UTC, closed without merging

2025-01-24 04:43 UTC, QaidjoharBarbhaya commented
Keeping title field might have helped in identifying gender of contact.

2025-01-24 04:43 UTC, QaidjoharBarbhaya commented
@malb-odoo

2025-12-02 13:56 UTC, adminswot commented
Could anyone from the odoo team please explain the rationale behind this change? As a customer, I find it quite hard to justify this change, it breaks so many custom apps, views, computed fields, etc.

In many countries, a title is not some nice to have optional field, but an essential piece of information. Its like removing the res.partner.name. 

That I couldn't find any information on how to migrate if you need to keep the title model and field on res.partner makes it even more frustrating.

2025-12-03 15:36 UTC, FlorianGilbert commented
> Could anyone from the odoo team please explain the rationale behind this change? As a customer, I find it quite hard to justify this change, it breaks so many custom apps, views, computed fields, etc.
> 
> In many countries, a title is not some nice to have optional field, but an essential piece of information. Its like removing the res.partner.name.
> 
> That I couldn't find any information on how to migrate if you need to keep the title model and field on res.partner makes it even more frustrating.

About the rationale behind the change, it's a functional decision made by our product owners and by Fabien himself. cc @Olivier-olma 
About "how to migrate", I can't advise you how to migrate custom apps but it's now possible on partner to add a property field if you really need the title field. 

<img width="484" height="301" alt="image" src="https://github.com/user-attachments/assets/a39f0beb-07c2-48dd-8f67-9ced9f91cb76" />
<img width="674" height="531" alt="image" src="https://github.com/user-attachments/assets/f8d991fd-c31d-4b74-acd0-f0122658e9fa" />

Feel free to send an email to feedback@mail.odoo.com to give us a feedback about the feature if needed!

Have a great day