[WIP][ADD] payment_dpo
odoo/odoo pull request #187404
Opened 2024-11-15 13:53 UTC by odoo-pda

2025-02-07 09:38 UTC, anko-odoo requested changes
Good work on the task. Mostly nitpicking and minor stuff.

2025-02-07 09:38 UTC, anko-odoo commented on addons/payment_dpo/models/payment_transaction.py
> +from odoo.exceptions import ValidationError
```suggestion
from odoo import _, models
from odoo.exceptions import ValidationError

from odoo.addons.payment_dpo import const
from odoo.addons.payment_dpo.controllers.main import DPOController
```

2025-02-18 09:24 UTC, odoo-pda commented on addons/payment_dpo/README.md
> +## Not implemented features
You wanna remove the line 13 too? Or it's just for the line 15?

2025-02-18 09:28 UTC, odoo-pda commented on addons/payment_dpo/__manifest__.py
> +# TODO-PDA: add .pot
Forgot to remove :smile: Apparently, on new module, we don't have to handle the translation.

2025-02-18 09:36 UTC, odoo-pda commented on addons/payment/data/payment_method_data.xml
> +        <field name="name">Card / Mobile</field>
We reverted to consider one unique payment method "dpo" as we don't have the information of how paid the customer in the end. 
The payment page of dpo displaying the different methods is subject to change. I had the case while developing the module. Some methods were added or removed. It's also something the customer can customize by calling dpo directly. For consistency, we considered we don't know what's gonna be shown on the payment page so we stay "generic". Moreover, they did not recommended to use the bank wire (don't ask me why).

2025-02-18 09:54 UTC, anko-odoo commented on addons/payment_dpo/README.md
> +## Not implemented features
Just the 15 indeed, I selected wrong,

2025-02-18 09:55 UTC, anko-odoo commented on addons/payment/data/payment_method_data.xml
> +        <field name="name">Card / Mobile</field>
Makes sense in this case.

2025-02-18 10:28 UTC, odoo-pda commented on addons/payment_dpo/controllers/main.py
> +    def _dpo_verify_transaction_token(self, transaction_token, tx_sudo):
I based myself on the name dpo uses for this request: https://docs.dpopay.com/api/index.html#tag/Basic-Transaction-Operations/operation/verifyToken
![image](https://github.com/user-attachments/assets/8c7cf471-0b06-4925-b7ff-d040b9f867e5)
It's a verification that the transaction succeeded 
![image](https://github.com/user-attachments/assets/9a87a5d6-60c1-434c-82f9-a0b6a7a72858)

2025-02-18 10:31 UTC, odoo-pda commented on addons/payment_dpo/models/payment_provider.py
> +    )
That happens when you add more lines then remove some :zany_face: of course you don't think to put everything back :see_no_evil:

2025-02-18 10:50 UTC, anko-odoo commented on addons/payment_dpo/models/payment_provider.py
> +    )
Hahaha, I know it way too well.

2025-02-18 11:04 UTC, odoo-pda commented on addons/payment_dpo/models/payment_transaction.py
> +        last_name = ' '.join(self.partner_name.split()[1:])
Great!

2025-02-18 11:13 UTC, odoo-pda commented
@anko-odoo Changes done.

2025-02-18 12:29 UTC, anko-odoo approved these changes
LGTM :) Great work on the task.

2025-04-03 08:51 UTC, AntoineVDV commented on addons/payment_dpo/README.md
> +## Not implemented features
Not needed if there is nothing, but there should be a listing of the features that DPO offers but we choose not to support, if any.

2025-04-03 08:52 UTC, AntoineVDV commented on addons/payment_dpo/README.md
> +## Module history
It should mention the version it is added in, and with which PR.

2025-04-03 08:54 UTC, AntoineVDV commented on addons/payment_dpo/__manifest__.py
> +# TODO-PDA: add .pot
At the time of your comment, new modules also needed a POT export, but only in stable (same when it's not a new module). It was never necessary to export POT files in master because it's always done a few days after the freeze.

Today, it is still never necessary in master, but now also not necessary in stable *if* it's not a new module. Otherwise, a POT export and edition of `/.tx/config` is necessary.

2025-04-03 08:59 UTC, AntoineVDV commented on addons/payment_dpo/models/payment_provider.py
> +            response = requests.request(method, api_url, data=payload, headers=headers, timeout=10)
It's not about clarity but correctness: `requests.request` accepts various arguments that look alike but serve different purposes. `params` is dedicated to query string params (typical GET payload) while `data` or `json` is dedicated to the request's body params (typical POST payload).

2025-04-03 16:59 UTC, AntoineVDV requested changes

2025-04-07 11:44 UTC, odoo-pda commented on addons/payment_dpo/models/payment_provider.py
> +            response = requests.request(method, api_url, data=payload, headers=headers, timeout=10)
Ok. We do cover the case of GET while we don't call the method with a get method? I've looked at the other payment providers but there was always only one line for setting the response considering the post method only.

2025-04-08 05:56 UTC, odoo-pda commented on addons/payment_dpo/models/payment_transaction.py
> +            # No redirection to /shop/confirmation as no available webhook
Staying on payment/status forever. 
![image](https://github.com/user-attachments/assets/a827e8b7-a283-4bba-aef6-f7b918d8dad4)

2025-04-08 07:42 UTC, odoo-pda commented on addons/payment_dpo/controllers/main.py
> +        data.update(transaction_result)
https://docs.dpopay.com/api/index.html#tag/Basic-Transaction-Operations/operation/verifyToken
This is a mandatory step that gives us the status of the payment. That "Result" is saved in the data to be retrieved in _process_notification_data.

2025-04-08 10:28 UTC, AntoineVDV requested changes

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/models/payment_transaction.py
> +        payload = (
Clean solution to remove the spaces while keeping the code clear :+1:

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/models/payment_transaction.py
> +                _("DPO: No transaction found matching reference %s.", reference)
split

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/models/payment_transaction.py
> +            self._set_error(_("DPO: Unknown status code: %s", status_code))
split

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/controllers/main.py
> +        data.update(transaction_result)
Yes, ok, it makes sense :+1: 

It's correct as-is, but let's just align with how it will soon be done in other providers with similar requirements: https://github.com/odoo/odoo/pull/163860/files#diff-c2a6d10c28ef6b4cdc74d92b3fd4fffdfb5cefd675475db102ece2c40490451d

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/tests/test_payment_transaction.py
> +
```suggestion
```

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/tests/test_payment_transaction.py
> +
```suggestion
```

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/tests/test_payment_transaction.py
> +class TestPaymentTransaction(DPOCommon, PaymentHttpCommon):
You probably don't need the methods of `PaymentHttpCommon`.

2025-04-08 10:28 UTC, AntoineVDV commented on addons/payment_dpo/tests/test_processing_flows.py
> +from odoo.addons.payment.tests.http_common import PaymentHttpCommon
```suggestion
from odoo.addons.payment.tests.http_common import PaymentHttpCommon
from odoo.addons.payment_dpo.controllers.main import DPOController
from odoo.addons.payment_dpo.tests.common import DPOCommon
```

2025-04-09 14:45 UTC, AntoineVDV approved these changes
@robodoo r+ override=ci/security
Reason: `requests.post` -> request to a hard-coded URL with a 10 seconds timeout
Link to ci/security build (master): https://runbot.odoo.com/runbot/build/78043295

![pda-working-on-providers](https://github.com/user-attachments/assets/9af8ff92-8fc4-4721-b402-ac3f40cdce31)

2025-04-09 14:45 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2025-04-09 18:09 UTC, closed without merging