[FIX] website_sale: fix select quantity
odoo/odoo pull request #187556
Opened 2024-11-18 11:35 UTC by rupa-odoo

WIP

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-18 11:35 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187556.png)](https://mergebot.odoo.com/odoo/odoo/pull/187556)

2024-12-12 10:53 UTC, ltinel requested changes
Thanks for your fix :) It still requires a bit of work, but I think the basic idea is good.

BTW, I think there's another use of `showQuantityAndPrice` in `ComboConfiguratorDialog` in the `sale` module. Could you update it as well?

2024-12-12 10:53 UTC, ltinel commented on addons/sale/static/src/js/product_configurator_dialog/product_configurator_dialog.xml
> +            <ProductList t-if="this.state.products.length" products="this.state.products" options="this.props.options"/>
As mentioned above, no need for these options here or below, you can directly get `showQuantity` and `showPrice` from the env.

2024-12-12 10:53 UTC, ltinel commented on addons/sale/static/src/js/product_list/product_list.xml
>                      <th class="px-0 text-end border-bottom-0">Price</th>
Could you also hide the `Price` header when needed?

2024-12-12 10:53 UTC, ltinel commented on addons/sale/static/src/js/product_list/product_list.xml
> +                    <Product t-props="product" optional="this.props.areProductsOptional" options="this.props.options"/>
No need for the options :)

2024-12-12 10:53 UTC, ltinel commented on addons/sale/static/src/js/product_list/product_list.xml
> +                <tr t-if="!this.props.areProductsOptional">
We should hide this when `showPrice` is false.

2024-12-12 10:53 UTC, ltinel commented on addons/website_sale/static/src/js/product_configurator_dialog/product_configurator_dialog.js
> +                showPrice: { type: Boolean, optional: true },
Those are already declared in `sale`, so no need to declare them again in eCommerce :)

2024-12-12 10:53 UTC, ltinel commented on addons/website_sale/static/src/js/product_configurator_dialog/product_configurator_dialog.js
> +            showPrice: this.props.options?.showPrice ?? true,
Nor here.

2024-12-12 10:53 UTC, ltinel commented on addons/website_sale/static/src/js/website_sale_configurators.js
> +                showQuantity: Boolean(this.$form[0].querySelector('.show_quantity')),
I wonder whether we can simply rely on `css_quantity` instead of adding a new class. Not sure though, maybe we need a more specific selector.

2024-12-12 15:07 UTC, ltinel reviewed
Thanks for the changes! :) Just a few more comments

2024-12-12 15:07 UTC, ltinel commented on addons/sale/static/src/js/product_configurator_dialog/product_configurator_dialog.xml
> +                options="this.props.options"/>
```suggestion
            />
```

2024-12-16 06:16 UTC, rupa-odoo commented on addons/sale/static/src/js/product/product.xml
> +                <t t-if="env.showQuantity">
I added the **env.showPrice** part because the **price** appears twice on the product configurator page. To avoid this, I made that change.

2024-12-16 06:17 UTC, rupa-odoo commented on addons/sale/static/src/js/product/product.xml
> +            t-if="env.showPrice"
Done the changes :+1:

2024-12-20 14:12 UTC, ltinel requested changes
Nearly done :)

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +                <t t-if="env.showQuantity">
I believe this should be done a bit differently. I added comments elsewhere in this file to explain what I mean :)

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            <t t-if="!this.props.optional and env.showPrice">
This should be removed:
```suggestion
```

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +                <t t-if="env.showQuantity">
This should be changed to:
```suggestion
                <t t-if="!this.props.optional &amp;&amp; env.showQuantity">
```

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            <t t-elif="env.showPrice">
This should be changed to:
```suggestion
            <t t-elif="this.props.optional &amp;&amp; env.showPrice">
```

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            t-if="env.showPrice"
This should be removed:
```suggestion
```

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            <t t-if="!this.props.optional and env.showPrice">
```suggestion
            <t t-if="!this.props.optional &amp;&amp; env.showPrice">
```

2024-12-20 14:12 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            <t t-elif="env.showQuantity">
This should be changed to:
```suggestion
            <t t-elif="this.props.optional &amp;&amp; env.showQuantity">
```

2025-01-02 10:11 UTC, ltinel commented on addons/sale/static/src/js/product/product.xml
> +            <t t-elif="this.props.optional &amp;&amp; env.showQuantity">
After a bit more thought, I don't think we should rely on `showQuantity` to decide whether to show the `Add` button:
```suggestion
            <t t-elif="this.props.optional">
```

2025-01-02 10:54 UTC, ltinel commented on addons/sale/static/src/js/product_list/product_list.xml
> +                    <th class="px-0 text-end border-bottom-0" t-if="env.showPrice">Price</th>
I noticed that the `Price` header isn't displayed nicely if `showQuantity` is false. You could fix this by increasing the colspan:
```suggestion
                    <th
                        class="px-0 text-end border-bottom-0"
                        t-if="env.showPrice"
                        t-att-colspan="env.showQuantity ? 1 : 2"
                    >
                        Price
                    </th>
```

2025-01-02 17:30 UTC, rupa-odoo commented on addons/sale/static/src/js/product_list/product_list.xml
> +                    <th class="px-0 text-end border-bottom-0" t-if="env.showPrice">Price</th>
Sorry, I have missed that point :cry: !
Made the Changes.

2025-01-03 07:56 UTC, ltinel approved these changes
LGTM, thanks! :) Don't forget to rebase and resolve the conflict (I think there's just a comment that changed so should be easy)

2025-01-03 09:15 UTC, ltinel commented on addons/sale/static/src/js/combo_configurator_dialog/combo_configurator_dialog.js
> +                edit: true, // TODO(loti): this "disables" optional products. Rename variable for clarity?
Could you keep the comment?
```suggestion
                edit: true, // Hide the optional products, if any.
```

2025-01-03 10:04 UTC, rupa-odoo commented on addons/sale/static/src/js/combo_configurator_dialog/combo_configurator_dialog.js
> +                edit: true, // TODO(loti): this "disables" optional products. Rename variable for clarity?
I accidentally removed that. 😢
Added

2025-01-15 15:04 UTC, chevalierv commented
Hello @rupa-odoo 

The quantity selector is still displayed in the combo configurator, is this the expected behaviour?

2025-01-15 15:08 UTC, chevalierv commented
@robodoo delegate=ltinel

2025-01-16 08:44 UTC, ltinel commented
> Hello @rupa-odoo
> 
> The quantity selector is still displayed in the combo configurator, is this the expected behaviour?

Ah, true, we may want to hide the combo configurator's quantity buttons as well in eCommerce if the `Select Quantity` setting is disabled

2025-01-24 09:58 UTC, ltinel requested changes
Thanks for the fix :) Just 2 minor comments

2025-01-24 09:58 UTC, ltinel commented on addons/sale/static/src/js/combo_configurator_dialog/combo_configurator_dialog.js
> +        showQuantity : { type: Boolean, optional: true },
It's probably a good idea to put this in an `options` prop, similarly to the product configurator.

2025-01-24 09:58 UTC, ltinel commented on addons/sale/static/src/js/sale_product_field.js
> +            showQuantity: true,
Instead of explicitly specifying this option, I'd give it a default value. See https://github.com/odoo/owl/blob/master/doc/reference/props.md#default-props

2025-01-24 10:03 UTC, ltinel commented
@kcv-odoo Could you also squash the commits? Thanks! :)

2025-01-29 08:26 UTC, ltinel approved these changes
LGTM, thanks!

2025-01-29 08:34 UTC, ltinel commented
@robodoo r+

2025-01-29 13:43 UTC, closed without merging

2025-02-05 08:47 UTC, ltinel commented
FYI, this needs to be fixed in 17.4 as well for the product configurator. I'll create a PR.