[FIX] web_editor: replace $0 with direct inherited view content
odoo/odoo pull request #187760
Opened 2024-11-19 15:02 UTC by SergeBayet

The $0 placeholder in templates is highly useful, but it is not considered when saving a view. For instance, the search icon in the shop search bar has an incorrect xpath:
`/data/xpath[3]/form/t[1]/div[1]/button[1]/i[1]`, where the inner `t[1]` actually points to another view through a `<t>$0</t>` containing the inherited view.

The method responsible for handling this replacement fails when the element is editable, causing a crash.

This commit replaces any $0 placeholders with their respective inherited views, ensuring the xpath is correctly resolved and targeted.

task-3609835

2024-11-19 15:02 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187760.png)](https://mergebot.odoo.com/odoo/odoo/pull/187760)

2024-11-26 16:46 UTC, qsm-odoo requested changes

2024-11-26 16:46 UTC, qsm-odoo commented on addons/web_editor/models/ir_ui_view.py
> +                    loc.append(copy.deepcopy(inherited_arch[0]))
@SergeBayet We can speak about your PR IRL if you prefer but I don't think this is the right solution. We should not fix the consequence but the cause of the error: the fact that the generated DOM has `/data/xpath[3]/form/t[1]/div[1]/button[1]/i[1]` is wrong in the first place IMO as it indicates that there is a editable `i` at the end of that path, in the view mentioned via `data-oe-model`, `data-oe-id`, which I think is not the case as it "jumps" views through `$0`? But let's talk about it IRL, maybe I don't remember this right.

2025-01-04 16:22 UTC, SergeBayet commented
@qsm-odoo If you have some time to look at this one?

2025-01-14 15:46 UTC, SergeBayet commented
@qsm-odoo Changes have been made. Here the diff: 
https://github.com/odoo/odoo/compare/eccc9197314700021ea75e32a41c6247f7a28d6d..d66b7c89791783a7d39bac2d15c2aec751027220

2025-01-14 16:09 UTC, qsm-odoo requested changes
Should not this target 16.0? Or did we decide 17.0 and I don't remember? :+1: 

Also, not sure about the title: ` replace $0 with direct inherited view content ` does not mean much to me. Should it be something like "disallow branding on wrapped node by xpath (<t>$0</t>)"? Something like that?

2025-01-14 16:09 UTC, qsm-odoo commented on odoo/addons/base/models/ir_ui_view.py
> +                return
Since you used a generic name like "data-oe-no-branding", it does not need explanation. But your comment here would be a better fit at the location where you used that data-oe-no-branding.

2025-01-14 16:09 UTC, qsm-odoo commented on odoo/tools/template_inheritance.py
> +                        if oe_id:
When is that `if` false? :thinking: (again, if we can minimize the notion of "branding" in this function, that would be best).

2025-01-15 07:59 UTC, SergeBayet commented
> Should not this target 16.0? Or did we decide 17.0 and I don't remember? 👍

I targeted 17.0 because the old fix for the *same* problem was [https://github.com/odoo/odoo/pull/164129](https://github.com/odoo/odoo/pull/164129/files). But indeed, the bug is in 16.0 as well. I'll retarget.

> Also, not sure about the title: `replace $0 with direct inherited view content` does not mean much to me. Should it be something like "disallow branding on wrapped node by xpath ($0)"? Something like that?

Yep, that was my first attempt to address this task. I'll correct that.

2025-01-15 08:37 UTC, SergeBayet commented on odoo/tools/template_inheritance.py
> +                        if oe_id:
It's false when the `env.context` includes `inherit_branding: True`. So in edition mode or translate mode I guess. Here the part of the code in ir_ui_view in the `_combine` method:
- https://github.com/odoo-dev/odoo/blob/9aca84895f5c9b0b068a888b102d9b85240b5a5f/odoo/addons/base/models/ir_ui_view.py#L806-L812

So I suppose that I can do
`if inherit_branding` instead of `if oe_id`...

2025-01-15 09:39 UTC, SergeBayet commented
@qsm-odoo Retargeted to 16.0

2025-01-30 12:30 UTC, qsm-odoo approved these changes
Looks right :+1: 

@robodoo r+

2025-01-30 13:46 UTC, closed without merging