[FIX] account_reports: report builder line sequences
odoo/odoo pull request #187907
Opened 2024-11-20 12:57 UTC by hupo-odoo

Issue:
 - Create a report with 2 lines, line 2 being a child of line 1
 - Drag line 2 above line 1

 -> Validation error

Cause of the issue:
 - The backend constraint receives line not ordered by sequence

task-4328098

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-20 12:57 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/187907.png)](https://mergebot.odoo.com/odoo/odoo/pull/187907)

2025-01-29 16:40 UTC, oco-odoo requested changes

2025-01-29 16:40 UTC, oco-odoo commented on addons/account/models/account_report.py
You copy-pasted your commit message from the enterprise branch, but you're touching account here, not account_reports ;)

2025-01-30 09:06 UTC, hupo-odoo commented on addons/account/models/account_report.py
Indeed, I've adapted the commit message, but still refer to the enterprise PR as the fix can't be explained without enterprise feature

2025-01-30 13:39 UTC, oco-odoo approved these changes
@robodoo r+

2025-01-30 15:48 UTC, closed without merging