[FIX] hr_holidays: fix form view actions wizard
odoo/odoo pull request #188182
Opened 2024-11-22 08:27 UTC by jaeschwa

Steps to reproduce:

 - Go in the Time Off app
 - Click on an allocation or a leave
 - Click on the action gear

Issue:

The gear action shows 2 times the "Multiple Requests", this comes from the fact that the wizard is in the xml and defined in the action_generate_allocations. So it is displayed twice in the form.

Fix:

Remove the reference to the wizard in the xml.

opw-4351233

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-22 08:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188182.png)](https://mergebot.odoo.com/odoo/odoo/pull/188182)

2025-01-03 15:54 UTC, yoba-odoo requested changes
I don't think this is the right way to fix the issue. Those actions are being used for the dropdown item that will be left here https://github.com/odoo/odoo/blob/e07f5e99d575bc4ad1211c34101a593ff3cb8931/addons/hr_holidays/static/src/components/multi_time_off_generation_menu/multiple_time_off_generation_menu.js#L23-L31
So if we went with your fix when clicking on 'Multiple Requests' it will raise an error that the action doesn't exist and we don't want to do this :slightly_smiling_face: 

I am not sure but I think it would be better to remove the dropdown item component and keep the actions. What do you think?

2025-01-07 07:57 UTC, jaeschwa commented
> I don't think this is the right way to fix the issue. Those actions are being used for the dropdown item that will be left here
> 
> https://github.com/odoo/odoo/blob/e07f5e99d575bc4ad1211c34101a593ff3cb8931/addons/hr_holidays/static/src/components/multi_time_off_generation_menu/multiple_time_off_generation_menu.js#L23-L31
> 
> 
> So if we went with your fix when clicking on 'Multiple Requests' it will raise an error that the action doesn't exist and we don't want to do this 🙂
> I am not sure but I think it would be better to remove the dropdown item component and keep the actions. What do you think?

Thank you for your feedback you're right, I adjusted the code accordingly :)

2025-01-07 13:46 UTC, yoba-odoo approved these changes
Thank you for your work!!
I guess since the fix is in JS we can re-target the PR back to 17.4 since the issue starts in this version. Other than this LGTM!!

Also if you can update the commit message with the new fix :slightly_smiling_face:

2025-01-21 08:20 UTC, tivisse commented
@robodoo r+

2025-01-21 12:55 UTC, closed without merging