[IMP] html_editor: toggle lists over block segments instead of blocks
odoo/odoo pull request #188213
Opened 2024-11-22 11:19 UTC by Zynton

This adds a new method to the split plugin, which splits the selection in order to isolate any block segment in it. A block segment forms a deliberate line in the content, separated using line breaks. A line break in a list item cannot create block segments as the list item visually marks its own segment (with a bullet point).

For instance,

```html
<p>a<br>b<br>[c<br>d<br>e]<br>f<br>g</p>
```

marks seven line segments
(one per letter). The selection contains 3 line segments, which will be isolated like this:

```html
<p>a<br>b</p>
<p>[c</p>
<p>d</p>
<p>e]</p>
<p>f<br>g</p>
```

We then use the new method before toggling a list, so that multiple block segments will create multiple list items:

```html
<p>a<br>b<br>[c<br>d<br>e]<br>f<br>g</p>
```

-> toggle unordered list

->

```html
<p>a<br>b</p>
<ul>
    <li>[c</li>
    <li>d</li>
    <li>e]</li>
</ul>
<p>f<br>g</p>
```

task-4009005

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-22 11:19 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188213.png)](https://mergebot.odoo.com/odoo/odoo/pull/188213)

2025-11-25 11:28 UTC, sebgeelen requested changes
Props for the Unit Tests coverage 🙏 
Has to be said that I didn't read every single one of them tho.

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/core/shortcut_plugin.js
> +                    blockEl = closestBlock(selection.anchorNode);
I think this re-assignation of `closestBlock` is unnecessary
It's the exact same call as the initial assignation, and the selection Object is the same.

Even if the DOM changed, I don't think the selection objects is updated here, since it's a `EditorSelection` that was created when you called `getEditableSelection()` and not a reference to the actual editor selection.

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/core/dom_plugin.js
> +        this.dependencies.split.splitBlockSegments();
This is probably legit, but your comment did not helped me understand the use case.
So it probably would be nice to rewrite the comment or provide better context in some way...

🤷‍♂️

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/core/split_plugin.js
> +        const { setSelection, getEditableSelection } = this.dependencies.selection;
IMO : This seems a bit unnecessary since you only call `setSelection()` once and `getEditableSelection()` twice.

If you want to keep it anyway, I wont loose sleep tho.

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/core/split_plugin.js
> +                const remapPos = (i) => (i <= brIndex ? [before, 0] : [after, i - brIndex - 1]);
What is `remapPos` mean to stand for ? Remap piece of shit ? 👀 

In any case it's not clear to me. Probably need a better name.

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/main/list/list_plugin.js
> +        this.dependencies.split.splitBlockSegments();
I'm not a huge fan of the fact that all those random plugins now need to know that they have to call `split.splitBlockSegments()` before doing their stuff ... 

I don't realy have a better solution, from the top of my head ...
I don't know, It just seems wrong...

Maybe we can discuss it bit with the rest of the team to be sure there's no better way to achieve this.

WYT?

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/main/list/list_plugin.js
> +        this.dependencies.split.splitBlockSegments();
see: https://github.com/odoo/odoo/pull/188213/files#r2559589666

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/src/main/tabulation_plugin.js
> +            this.dependencies.split.splitBlockSegments();
see: https://github.com/odoo/odoo/pull/188213/files#r2559589666

2025-11-25 11:28 UTC, sebgeelen commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +    test("should isolate all lines in an unbreakable block", async () => {
I didn't see a test case where the selection started in an unbreakable but ended outside of it.
I would like to be sure your new 'splitBlockSegments' will not break the unbreakable in those case.

If I missed it (I didn't read every single Unit tests), ignore this comment

2025-11-25 11:40 UTC, Zynton commented on addons/html_editor/static/src/core/shortcut_plugin.js
> +                    blockEl = closestBlock(selection.anchorNode);
The selection object is the same but since we split the parent, `closestBlock` returns something else. The tree above the element has changed. I have a test that breaks when I remove that line.

2025-11-25 12:05 UTC, Zynton reviewed
Thanks for the review @sebgeelen ! I answered and applied requested changes.

2025-11-25 12:05 UTC, Zynton commented on addons/html_editor/static/src/core/split_plugin.js
> +        const { setSelection, getEditableSelection } = this.dependencies.selection;
Yeah it's really unnecessary but it prevents some lines from being very long and therefore split into several, which I found impeded on the readability of the function which is already quite long. Let's say I indulged here, and same thing, I won't object if you want me to change it.

2025-11-25 12:05 UTC, Zynton commented on addons/html_editor/static/src/core/split_plugin.js
> +                const remapPos = (i) => (i <= brIndex ? [before, 0] : [after, i - brIndex - 1]);
Haha! I meant "pos" to stand for "position". I find this whole section harder to read when it's split into several lines so I tried to keep it short...

2025-11-25 12:05 UTC, Zynton commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +    test("should isolate all lines in an unbreakable block", async () => {
Good idea! I added three, called `should isolate lines in and out of an unbreakable block` then `(at start)`, `(at end)` and `(at start and end)`.

2025-11-25 12:05 UTC, Zynton commented on addons/html_editor/static/src/main/list/list_plugin.js
> +        this.dependencies.split.splitBlockSegments();
I don't know, it doesn't seem too crazy to me. These plugins are basically just saying "my thing should apply to line segments, not to whole blocks".

cc @dmo-odoo @Jinjiu96

2025-11-25 12:05 UTC, Zynton commented on addons/html_editor/static/src/core/dom_plugin.js
> +        this.dependencies.split.splitBlockSegments();
Good catch, actually with the recent change to handle unsplittable blocks (inserting splittable blocks in them instead of doing nothing), this was not needed anymore.

2025-11-25 14:53 UTC, sebgeelen commented on addons/html_editor/static/src/core/shortcut_plugin.js
> +                    blockEl = closestBlock(selection.anchorNode);
hum yes, make sense.

2025-11-25 14:55 UTC, sebgeelen commented on addons/html_editor/static/src/core/split_plugin.js
> +        const { setSelection, getEditableSelection } = this.dependencies.selection;
nah it's ok

2025-11-25 14:57 UTC, sebgeelen commented on addons/html_editor/static/src/core/split_plugin.js
> +                const remapPos = (i) => (i <= brIndex ? [before, 0] : [after, i - brIndex - 1]);
Not a fan, but it's not terrible enough to spent time arguing it

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/src/main/list/list_plugin.js
> +        this.dependencies.split.splitBlockSegments();
You don't _have_ to call it. It's on a case by case basis for now. If we end up putting it everywhere then we will need to reconsider indeed.

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +                    <p>d<br>e</p>
This test is wrong because `splitBlockSegments` added margins around C where there weren't any before. Actually, I just noticed that's the case for almost all the tests. I think it should use DIV, not P.

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +            ),
No test with reversed selection?

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
I'm surprised that the `DIV` is not unbreakable in that case? I thought divs that were not eligible for base container were implicitly unbreakable since they were assumed to be part of the layout like snippets and such.

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: "<div><h1>[a</h1></div><div><h1>b]</h1></div>",
I feel like we broke the div here as well, and probably other places too.

2025-11-27 12:37 UTC, dmo-odoo commented on addons/html_editor/static/tests/tabs.test.js
> +                `<p>${oeTab(TAB_WIDTH, false)}x]c</p>` +
This suddenly adds margin a as well.

2025-11-28 14:07 UTC, Zynton commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +                    <p>d<br>e</p>
Are you sure? We use `baseContainer` right now, not specifically `P` so it depends on the context. I thought that was the point of `baseContainer` to not choose on a case by case basis.

2025-11-28 14:07 UTC, Zynton commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +            ),
Ah that's a good point. I'll add them. That makes me think we probably should have something that automates that so all our tests are automatically run in both directions.

2025-11-28 14:07 UTC, Zynton commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
I just ran the test and checked the status of the div:
<img width="211" height="167" alt="image" src="https://github.com/user-attachments/assets/91374256-a655-4947-9201-9c6b76e47d78" />

I'm guessing you're referring to this condition:
<img width="510" height="103" alt="image" src="https://github.com/user-attachments/assets/db937d26-7613-4efc-a907-5d3d4c68d242" />

I think it's again a case of confusion due to multiple negatives:
<img width="645" height="275" alt="image" src="https://github.com/user-attachments/assets/81b1658d-659a-44b7-ba20-4f061c2f1fa9" />

- A DIV is _not_ splittable if it's _not_ "candidate-for-base-container-allow-unsplittable" (CFBCAU).
- A DIV is CFBCAU if it's _not_ valid for base container.

Therefore, a DIV is _not_ splittable if it's valid for base container.

Here we set the DIV to _not_ be valid for base container, therefore it could still be splittable.

I'm glad this mess of multiple negatives will be sorted out with my predicates refactor.

---

What doesn't help with the confusion here is that `setBlock` inserts the `P` in the `DIV` instead replacing the `DIV`, which looks like what `splitBlockSegments` does when the block is unsplittable, but in fact here `splitBlockSegments` is breaking the block - it's `setBlock` that inserts the `P` and it's by design: 
<img width="395" height="56" alt="image" src="https://github.com/user-attachments/assets/59850640-171d-4b66-a08a-bb00ad593bbd" />

2025-11-28 14:07 UTC, Zynton commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: "<div><h1>[a</h1></div><div><h1>b]</h1></div>",
See answer above.

2025-11-28 14:07 UTC, Zynton commented on addons/html_editor/static/tests/tabs.test.js
> +                `<p>${oeTab(TAB_WIDTH, false)}x]c</p>` +
Refer to my other answer.

2025-11-28 14:29 UTC, dmo-odoo commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +            ),
Created a task about reverse selection tests: https://www.odoo.com/odoo/project/1695/tasks/5367913

2025-11-28 14:30 UTC, dmo-odoo commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +                    <p>d<br>e</p>
I think you're right in theory, but it's going to be weird to call `splitBlockSegments` in a context where `P` is the default, like Knowledge. As long as it is used by a command that is going to change the tag anyway, like `toggleList`, it's fine.

2025-11-28 14:36 UTC, dmo-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
I don't know what I was thinking, this DIV should indeed be splittable because it acts like a paragraph. If there was a `contentBeforeEdit`, I think the div would have the `o-paragraph` class. That being said, it conflicts with your logic. You say " a DIV is not splittable if it's valid for base container", I think it's the opposite. It is splittable if it's a valid base container (will act like a P), otherwise it's not (will act like layout).

Either way, I was mistaken. However, you are right that `setBlock` is wrong here. Can I ask you to look into it and see if it can be fixed easily please? Otherwise we're going to merge a test with a result that we know is just plain wrong due to another bug... ^^'

2025-12-01 08:35 UTC, Zynton commented on addons/html_editor/static/tests/split/split_block_segments.test.js
> +                    <p>d<br>e</p>
And so in practice, what do we do? You want me to force a `div` anyway? A base container div ?

2025-12-01 08:35 UTC, Zynton commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
TLDR:
- I think it's supposed to be unbreakable in this case
- The mistake is unrelated to my PR
- We have a bunch of tests that are wrong because of that mistake
- We need to check with @abd-msyukyu-odoo if what I'm saying is correct

---

> You say " a DIV is not splittable if it's valid for base container", I think it's the opposite.

Indeed in all this multiple negatives mess, I misspoke.

To simplify:
```js
isUnsplittable = node => ... !isCfbcau(node);
isCfbcau = (node) => !isInvalidForBaseContainer(node);
```

So `isInvalidForBaseContainer => !isCfbcau => isUnsplittable`.
And indeed `!isInvalidForBaseContainer => isCfbcau => !isUnsplittable`.

> I don't know what I was thinking, this DIV should indeed be splittable because it acts like a paragraph. If there was a contentBeforeEdit, I think the div would have the o-paragraph class.

In the test we explicitly set `baseContainers: ["P"]` so that _"div isn't eligible for a baseContainer"_ (see title of the test). So according to the logics above, `isInvalidForBaseContainer => !isCfbcau => isUnsplittable`. I would therefore expect it to be unsplittable and my test to be wrong.

BUT! It turns out that this config doesn't affect `isInvalidForBaseContainer`!

<img width="560" height="212" alt="image" src="https://github.com/user-attachments/assets/e55449da-404c-4467-8098-50cc0f203ce0" />
<img width="304" height="256" alt="image" src="https://github.com/user-attachments/assets/51a5b15b-271c-4eb1-b329-877c7577194d" />

That seems to be a mistake because we have all these tests changing this config and saying in their title "div isn't eligible for a baseContainer", and `editor.js` even has this code:

<img width="550" height="103" alt="image" src="https://github.com/user-attachments/assets/affe84e2-23bd-40a3-bb67-9a5c0844a5e2" />

So I think `base_container_plugin`'s `invalid_for_base_container_predicates` should be changed to take the config into account, and the tests should be corrected accordingly. Should I do that in this PR to avoid introducing wrong tests?

---

> However, you are right that `setBlock` is wrong here.

I'm saying it's by design. Its behavior just contributed to our confusion but I'm not saying its behavior is incorrect (hehe double negative again).

The condition for wrapping the contents instead of changing the tag is the `else` of:
```js
if (
    isParagraphRelatedElement(block) ||
    isListItemElement(block) ||
    isPhrasingContent(block) ||
    block.nodeName === "BLOCKQUOTE"
) {
```

`isParagraphRelatedElement` matches against `baseContainer` so here it's false because it isn't a base container. Now we know the div should be unsplittable of course in this case it's doing what it should be doing. It's surprising that this doesn't check unsplittable directly but other than that this seems to be there to handle very specific cases where we don't want to change the tag.

2025-12-03 14:25 UTC, dmo-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
Haha, yes indeed, when I read the code I had seen the `config: { baseContainers: ["P"] },`, but when I re-read my comment afterwards, I did not see it because it was _below_ the comment thread. It should be unsplittable indeed, since the config implies all DIVs are for layouting purposes. Therefore the result of the test is wrong because it splits the DIV. It can't replace the DIV because it's not a valid base container (since it's a layout div), and it can't split it either because it's a layout div. Only thing it can do is best effort inside of the DIV itself, that is:
```html
<div><p>[a</p><p>b]</p></div>
```

2025-12-03 15:07 UTC, abd-msyukyu-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
@dmo-odoo @Zynton Heya, I think it'd be best if we have a live conversation for this, can I come to your office tomorrow?

I just wanted to mention that I did not implement the config option `baseContainers: ["P"]`, and in my work I never supported the feature that we could opt out of using `div` as a baseContainer, so there may indeed be contradictions between the current logic and that config option.

I'll try to understand your discussion thread, but I'll probably come tomorrow anyway :)

2025-12-03 15:20 UTC, dmo-odoo commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
@abd-msyukyu-odoo You're always welcome!

2025-12-04 10:22 UTC, Zynton commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
@abd-msyukyu-odoo @dmo-odoo Here it is: https://github.com/odoo/odoo/pull/238653

2025-12-04 10:33 UTC, Zynton commented on addons/html_editor/static/tests/tags.test.js
> +            contentAfter: `<div><p>[a</p></div><div><p>b]</p></div>`,
I added the commit at the beginning of this branch too, and adapted the tests.

2025-12-05 13:49 UTC, dmo-odoo commented
@Zynton Thank you for this big work!
@robodoo rebase-merge r+

2025-12-05 13:49 UTC, robodoo commented
Merge method set to rebase and merge, using the PR as merge commit message.

2025-12-05 21:01 UTC, closed without merging