[FIX] account: prevent home menu redirection on outstanding click
odoo/odoo pull request #188479
Opened 2024-11-25 14:57 UTC by hubvd

Steps to reproduce
==================

- Click on an invoice
- Register a payment where the amount exceeds the invoice amount
- Switch to another invoice with the same customer
- Switch the active notebook to "Journal Items"
- Click on "Outstanding credits"

=> You are redirected to the homepage

Cause of the issue
==================

Before 16.0, it used to be possible to click on a link where the target is inside another notebook.
In that case, the notebook was switched before scrolling to the anchor. With owl, it is no longer possible to query where the target is as the DOM inside other notebooks is not yet rendered before switching to them.

Solution
========

If the anchor is visible, the link will work as intended, otherwise, the redirection to the homepage will be prevented

opw-4344125

2024-11-25 14:58 UTC, hubvd commented
@robodoo up to saas-17.2

2024-11-28 13:33 UTC, aboo-odoo commented
robodoo fw=no

2024-12-02 09:29 UTC, aboo-odoo reviewed
Hey, thanks for the PR. Since, functionally speaking, it's a bit weird to click on a link and nothing happen (it's weirder to be brought back to the menu I know but still). I mean, I understand that:
1 - The scroller service searches for the anchor
2 - Trigger the onclick
3 - Scroll to void since it couldn't find the element in step 1

But do you have an idea of why OWL does not allow for it anymore ?
If you don't, we should ask the JS R&D team for more info

2024-12-03 12:53 UTC, hubvd commented
Before Owl, every page was present in the DOM, and only their visibility would be toggled. This means we could simply do a getElementById(anchor), switch to the appropriate page and scroll to it.

I checked with the JS team before opening this PR.
It is no longer technically feasible as we don't really know which page to target (we can't deduce it from the arch of the view as the id can be inside a widget itself).

Plus it is already a weird feature to have an anchor targeting an element not present in the page.

cc @cth-odoo

2024-12-03 13:07 UTC, aboo-odoo commented
Thanks for your answer! @rugo-odoo

2024-12-03 15:47 UTC, rugo-odoo requested changes
Nice one !

@robodoo r+

2024-12-03 15:48 UTC, rugo-odoo approved these changes
Ooops, it's an `Approve` haha

@robodoo r+

2024-12-03 15:48 UTC, robodoo commented
This PR is already reviewed, reviewing it again is useless.

2024-12-03 17:22 UTC, closed without merging