[IMP] point_of_sale, pos_*: improve payment method setup
odoo/odoo pull request #188505
Opened 2024-11-25 16:34 UTC by davidmonnom

*: pos_online_payment, pos_paytm, pos_viva_wallet

Improve payment method setup in POS by adding a new widget to display the available payment methods in a card view. This will make it easier for the user to select the payment methods and configure them.

taskId: 4335308

2024-11-25 16:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188505.png)](https://mergebot.odoo.com/odoo/odoo/pull/188505)

2024-12-03 12:28 UTC, vlst-odoo requested changes

2024-12-04 07:08 UTC, davidmonnom commented on addons/point_of_sale/static/src/backend/pos_payment_provider_cards/pos_payment_provider_cards.js
> +export class PosPaymentProviderCards extends Component {
I already tried, we don't really have records for providers. So it would be more quibbling

2024-12-04 09:20 UTC, vlst-odoo approved these changes
robodoo r+

2024-12-05 19:39 UTC, closed without merging