[IMP] pos_urban_piper: prevent cancel of scheduled orders during close session
odoo/odoo pull request #188563
Opened 2024-11-26 07:18 UTC by meji-odoo

In this commit:
===
- Added the `get_session_orders` method to handle session orders.
- Updated session closure logic to exclude scheduled orders from being canceled, ensuring better management of such orders.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-26 07:18 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188563.png)](https://mergebot.odoo.com/odoo/odoo/pull/188563)

2024-12-09 05:58 UTC, paso-odoo requested changes

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +        if self.get_session_orders(self).filtered(lambda o: o.state != 'cancel') or self.sudo().statement_line_ids:
```suggestion
        if self.get_session_orders().filtered(lambda o: o.state != 'cancel') or self.sudo().statement_line_ids:
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +            edited_orders = self.get_session_orders(self).filtered(lambda o: o.is_edited)
```suggestion
            edited_orders = self.get_session_orders().filtered(lambda o: o.is_edited)
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +        open_order_ids = self.get_session_orders(self).filtered(lambda o: o.state == 'draft').ids
```suggestion
        open_order_ids = self.get_session_orders().filtered(lambda o: o.state == 'draft').ids
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +            open_order_ids = self.get_session_orders(self).filtered(lambda o: o.state == 'draft').ids
```suggestion
            open_order_ids = self.get_session_orders().filtered(lambda o: o.state == 'draft').ids
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +        if any(order.state == 'draft' for order in self.get_session_orders(self)):
```suggestion
        if any(order.state == 'draft' for order in self.get_session_orders()):
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +        draft_orders = self.get_session_orders(self).filtered(lambda order: order.state == 'draft')
```suggestion
        draft_orders = self.get_session_orders().filtered(lambda order: order.state == 'draft')
```

2024-12-09 05:58 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +            if any(order.state == 'draft' for order in self.get_session_orders(session)):
```suggestion
            if any(order.state == 'draft' for order in session.get_session_orders()):
```

2024-12-09 06:01 UTC, paso-odoo commented on addons/point_of_sale/models/pos_session.py
> +        return session.order_ids
```suggestion
    def get_session_orders(self):
        self.ensure_one()
        return self.order_ids
```

2024-12-09 10:34 UTC, meji-odoo commented
@paso-odoo 
Changes are done.
Thanks and have great day ahead :)

2025-01-03 07:51 UTC, caburj commented
robodoo r+

2025-01-03 11:18 UTC, closed without merging