[IMP] pos_restaurant: enhance split order screen with additional actions
odoo/odoo pull request #188614
Opened 2024-11-26 11:59 UTC by parp-odoo

In this commit:
==========

Two new actions are added to the Split Bill screen:

- **Pay**: Redirects to the payment screen for the selected split order.
- **Transfer**: Navigate to the Floor screen in transfer/merge mode, allowing the user to transfer the split order to a selected table.

Task-4358352

2024-11-26 11:59 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188614.png)](https://mergebot.odoo.com/odoo/odoo/pull/188614)

2024-12-09 13:36 UTC, paso-odoo requested changes

2024-12-09 13:36 UTC, paso-odoo commented on addons/pos_restaurant/static/src/app/screens/split_bill_screen/split_bill_screen.xml
> +                                t-att-class="(this.ui.isSmall ? 'w-50' : 'w-100')"
```suggestion
                            <button class="button btn btn-lg btn-primary py-3 py-lg-5"
                                t-att-class="(this.ui.isSmall ? 'w-50' : 'w-100')"
                                t-att-disabled="!this.getNumberOfProducts()"
```

2024-12-16 09:57 UTC, adgu-odoo approved these changes

2024-12-19 09:43 UTC, adgu-odoo commented
robodoo r+

2024-12-19 15:28 UTC, Xavier-Do commented
@robodoo r-

Broke here
https://runbot.odoo.com/runbot/build/72210428

2024-12-20 09:22 UTC, parp-odoo commented
Hi @adgu-odoo,

I’ve made the necessary changes to fix the tour.
Could you please review them?

Also, if time permits, could we work on merging this [PR](https://github.com/odoo/odoo/pull/179481) as well?

Thanks!

2024-12-24 13:47 UTC, adgu-odoo approved these changes

2024-12-24 13:47 UTC, adgu-odoo commented
Can you rebase ? Ping me on discord when it's done

2024-12-27 10:08 UTC, adgu-odoo approved these changes

2024-12-27 10:09 UTC, adgu-odoo commented
robodoo r+

2024-12-27 12:16 UTC, closed without merging