[IMP] payment_razorpay: combine payment_razorpay_oauth with payment_razorpay
odoo/odoo pull request #188774
Opened 2024-11-27 10:03 UTC by nikj-odoo

this commit merges the Razorpay OAuth flow into the main payment_razorpay module, integrating both flows into a single and removing the Razorpay OAuth module.

2024-11-27 10:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188774.png)](https://mergebot.odoo.com/odoo/odoo/pull/188774)

2024-12-03 12:38 UTC, kcv-odoo requested changes
Commit title should be CLN not IMP and added some minor comments!

Thank you for you work!

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/const.py
> +# URL for OAUTH flow
No need for this comment as variable name is self explanatory

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
>      )
```suggestion
    )

```

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
> +    def _razorpay_make_request(self, endpoint, payload=None, method='POST', **kwargs):
```suggestion
    def _razorpay_make_request(self, endpoint, payload=None, method='POST', api_version='v1'):
```

It should be like this as there is not point of variable kwargs

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
> +        api_version = kwargs.get('razorpay_api_version', 'v1')
adept according to above comment

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/views/payment_provider_views.xml
> +                            groups="base.group_no_one"/>
```suggestion
                        <field
                            name="razorpay_account_id"
                            groups="base.group_no_one"
                        />
```

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/views/payment_provider_views.xml
>                      <field name="razorpay_key_id"
Can adept this also same as above

2024-12-03 12:38 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
> +        required_if_provider=False,
Do we need this? you can just remove required_if_provider param. No? :thinking:

2024-12-17 13:03 UTC, kcv-odoo approved these changes
Look good to me (just a minor comment)

2024-12-17 13:03 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
>  import requests
Swap this

2024-12-17 13:03 UTC, kcv-odoo commented on addons/payment_razorpay/models/payment_provider.py
> +from datetime import timedelta
same

2025-01-07 12:45 UTC, AntoineVDV approved these changes
Hi @nikj-odoo, thanks for this PR :)

I pushed an additional commit with further cleanup (some leftovers that weren't properly moved from `payment_razorpay_oauth` and some other stuff). Could you have a look and squash the commits?

Also, please move forward with the upgrade PR so we can r+ both. Note that I didn't rebase this branch so you shouldn't need to either.

2025-01-08 05:04 UTC, nikj-odoo commented
Hello @AntoineVDV  :wave: : 
I squashed the commit and updated the upgrade [PR](https://github.com/odoo/upgrade/pull/6858), please have a look.

Thanks! & Have a nice day :slightly_smiling_face:

2025-01-21 16:25 UTC, AntoineVDV commented
@robodoo r+ override=ci/security
(moved with no change (and still okay))

2025-01-21 16:25 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2025-01-21 22:03 UTC, closed without merging