[FIX] website_sale_stock: fix max combo quantity
odoo/odoo pull request #188860
Opened 2024-11-27 16:40 UTC by ltinel

Before this fix, it was possible to add more combo products than available to the cart. Indeed, the available quantity was only checked in the combo configurator, but not in other places where the quantity could be updated (such as the product page or the cart).

This fix introduces a `max_combo_quantity` concept which is based on the available quantities of its items.

2024-11-27 16:40 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/188860.png)](https://mergebot.odoo.com/odoo/odoo/pull/188860)

2024-12-19 16:48 UTC, chevalierv commented on addons/website_sale_stock/static/src/js/variant_mixin.js
> +        // TODO(loti): show "out of stock" message?
👀

2025-01-02 09:45 UTC, ltinel commented on addons/website_sale_stock/static/src/js/variant_mixin.js
> +        // TODO(loti): show "out of stock" message?
I'll have a chat with Jean to discuss what we should do here :)

2025-01-20 15:41 UTC, ltinel commented on addons/website_sale_stock/models/product_product.py
> -            # so we check for it
For the reviewer: the cron in question (`ir_cron_send_availability_email`) doesn't rely on this method anymore, so no need for the check.

2025-01-21 08:31 UTC, ltinel commented on addons/website_sale_stock/models/product_product.py
> -        if not self.allow_out_of_stock_order:
@reviewers: I had a look at the code and we don't actually need this condition. In fact, this condition makes the code a bit inconsistent, so I removed it

2025-03-12 17:20 UTC, chevalierv requested changes
Hello @ltinel 

Thanks for addressing the issues about max quantity with combos. I feel like this is a huge change for stable version. Please double check if it's really needed with PO.

See my comments for other issues.

Have a nice day!

2025-03-18 14:50 UTC, ltinel commented
Note: the latest force-push was just a rebase (commit unchanged).

2025-03-18 15:16 UTC, ltinel commented on addons/website_sale_stock/static/src/xml/website_sale_stock_product_availability.xml
> +    </t>
This change is not essential IMO (it just shows a `Not available` message if a combo product isn't available), so I'll keep it for master :)

2025-03-18 15:50 UTC, ltinel commented
> Hello @ltinel
> 
> Thanks for addressing the issues about max quantity with combos. I feel like this is a huge change for stable version. Please double check if it's really needed with PO.
> 
> See my comments for other issues.
> 
> Have a nice day!

@chevalierv in the meantime, a customer reported this issue (https://www.odoo.com/odoo/project.task/4614309), so I guess we should fix it in stable? The inventory team created a fix PR (https://github.com/odoo/odoo/pull/202316) which is way smaller than mine, but it's insufficient IMO.

@Jean-boje WDYT?

2025-03-25 12:13 UTC, chevalierv approved these changes
Ok to fix this in stable since you removed the cosmetics changes and there is a ticket for that! 

robodoo delegate+

2025-03-25 14:34 UTC, ltinel commented on addons/website_sale/controllers/main.py
> +
This one serves as separation between the main line update and the linked line updates (to which I've added quite a few lines) so I'd like to keep it if you don't mind :)

2025-03-25 14:35 UTC, ltinel commented
@robodoo r+

2025-03-25 14:38 UTC, ltinel commented
@robodoo r+
@robodoo rebase-ff

2025-03-25 14:38 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-03-25 15:56 UTC, robodoo commented
@ltinel 'ci/l10n' failed on this reviewed PR.

2025-03-26 08:40 UTC, robodoo commented
@ltinel 'ci/runbot' failed on this reviewed PR.

2025-03-26 12:52 UTC, ltinel commented
@robodoo r+

2025-03-26 17:18 UTC, closed without merging