[FIX] account: notify rank increases
odoo/odoo pull request #189127
Opened 2024-11-29 10:42 UTC by yajo

Any computed fields that depend on `customer_rank` or `supplier_rank` were not being recomputed when the ranks changed.

This isn't noticeable on standard Odoo code, but downstream modules that use such feature wouldn't work.

@moduon MT-8208

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-11-29 10:42 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189127.png)](https://mergebot.odoo.com/odoo/odoo/pull/189127)

2024-12-03 10:02 UTC, alialfie requested changes
Hello, thanks for your contribution!
I see that runbot is red though. Could you take a look?

2024-12-03 10:47 UTC, yajo commented
Thanks! Fixed.

2024-12-05 10:58 UTC, alialfie reviewed
Thanks @yajo!
@odoo/rd-framework-py This look good to me but could you also take a look please? Thanks :)

2024-12-05 12:14 UTC, kmagusiak reviewed
LGTM

2024-12-06 10:03 UTC, alialfie approved these changes
One final review will soon follow. Thanks @yajo!

2024-12-09 12:25 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-12-09 14:15 UTC, closed without merging