[IMP] website_sale: convert microdata to json-ld
odoo/odoo pull request #189289
Opened 2024-12-02 10:27 UTC by vchu-odoo

task-3866937

2024-12-02 10:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189289.png)](https://mergebot.odoo.com/odoo/odoo/pull/189289)

2024-12-12 15:56 UTC, livaios requested changes

2024-12-13 08:08 UTC, vchu-odoo commented on addons/website_sale/controllers/main.py
> +                        'name': category.name,
I have not found how can you have multiple categories on the product page, can you show me that?

2024-12-13 08:12 UTC, vchu-odoo commented on addons/website_sale/views/templates.xml
> +            <script t-if="res_company and website" type="application/ld+json" >
but that way this data will be available not only on product page

2024-12-13 08:15 UTC, vchu-odoo commented on addons/website_sale/models/website.py
> +        }
I find this way clearer to see the schema structures, nesting functions can be confusing, wdyt?

2024-12-13 08:47 UTC, vchu-odoo commented on addons/website_sale/models/website.py
> +            seo_data['description'] = product_template.description_ecommerce
I have not found that html is not allowed but checked that other e-commerces use text, so will apply it, thanks!

2024-12-13 09:28 UTC, vchu-odoo commented on addons/website_sale/models/website.py
> +            seo_data['description'] = product_template.description_ecommerce
found odoo function for that :)

2024-12-16 12:00 UTC, livaios approved these changes
LGTM

2025-01-20 15:58 UTC, AntoineVDV requested changes
Looking nice so far; don't forget to rebase :wink:

2025-01-20 15:58 UTC, AntoineVDV commented on addons/website_sale/models/website.py
> +    def get_product_seo_data(self, product_template):
Move product-related methods to product files.

2025-01-20 15:58 UTC, AntoineVDV commented on addons/website_sale/models/website.py
> +        If product has more than two variants return product group SEO data
blank line

2025-01-22 09:52 UTC, AntoineVDV approved these changes
@robodoo r+

2025-01-24 10:56 UTC, AntoineVDV approved these changes
@robodoo r+

2025-01-24 11:25 UTC, robodoo commented
@vchu-odoo @AntoineVDV 'ci/upgrade_enterprise' failed on this reviewed PR.

2025-01-28 09:22 UTC, AntoineVDV commented
@robodoo r+

2025-01-28 11:00 UTC, robodoo commented
@vchu-odoo @AntoineVDV linked pull request(s) odoo/enterprise#74980 not ready. Linked PRs are not staged until all of them are ready.

2025-01-28 15:33 UTC, vchu-odoo commented on addons/website_sale_stock/models/product_product.py
> +            if free_qty or self.allow_out_of_stock_order:
Great point, will make the follow-up PR.

2025-01-28 15:58 UTC, closed without merging

2025-03-29 13:13 UTC, kig-odoo commented
@vchu-odoo Good improvement.

Just a small feedback [here](https://github.com/odoo/odoo/commit/5d2fecfd71a818f3f732d9f545b9d81866efdeb5#diff-bcce8086c8655fe6671ccbb5b4739a891993e92380f67930ea24423e80941607R180). instead of checking the `rating_count` you need to add other condition view `website_sale.product_comment` is active for current website. which means rating feature should be enabled.

cc: @Feyensv

2025-04-02 07:46 UTC, vchu-odoo commented
Hello @kig-odoo,

Thank you for your suggestion!
It is applied in https://github.com/odoo/odoo/pull/204147.

2025-04-02 09:27 UTC, kig-odoo commented
Thanks for a quick fix.

Always happy to make odoo bug free 👍

2025-12-04 13:11 UTC, vmac-odoo commented on addons/website_sale/models/product_template.py
> +            'hasVariant': [product._to_markup_data(website) for product in self.product_variant_ids]
💀