[IMP] website: redesign `s_countdown` snippet
odoo/odoo pull request #189265
Opened 2024-12-02 07:13 UTC by chgo-odoo

This commit reviews the different `s_countdown` layouts, as part of the snippets redesign.

With this commit, no new template is added to the current selection, we only review them and remove the ability to drop `s_countdown` as an inner snippet as we plan to introduce a new snippet for that inline use.

task-4370295

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-02 07:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189265.png)](https://mergebot.odoo.com/odoo/odoo/pull/189265)

2024-12-04 10:54 UTC, chgo-odoo commented
Hello @stefanorigano 👋 

If you could have a first look at this PR when you have some time 🙂 

Thanks !

2024-12-05 13:09 UTC, stefanorigano requested changes
Thanks so much @chgo-odoo , very good 👍 
Some preliminary remarks for you, thanks!

2024-12-05 16:33 UTC, chgo-odoo commented
Thanks for the review and the suggestion as well @stefanorigano, looks way better with a `background-image`, indeed !

I've apply the changes in a fixup! on top, if you could have a look 🙂 

Thanks !

2024-12-06 15:37 UTC, chgo-odoo commented
Thanks @lebl-odoo 🙂 

> Shouldn't we prefer to use paddings here?
We could use margin, indeed, but this wouldn't be editable by the user, we use a paragraph with a `<br/>` tag inside to handle the spacing so that the user has a full control on it.

> Moreover, gap between the counter and the CTA is not the same than the gap between counter and social network links.
We can do that, not a big deal IMO as the socials are kind of the last information so I don't mind having them at the very bottom of the snippet, again, not a big deal whatever we decide

2024-12-06 15:42 UTC, lebl-odoo commented
1. Ok, let's keep it like this :)

2. I would like to add more space because currently I find it unbalanced

2025-02-17 14:10 UTC, stefanorigano commented
Hello @chgo-odoo . The inline version is advancing,  but it's not merged yet.
I don't see the point on allowing to drop this as an inline snippet when its new design doesn't suit the inline scenario anymore, I there a reason why you would like to proceed anyway?
Detail, you shave some conflicts ;)

2025-02-17 14:14 UTC, chgo-odoo commented
No specific reason but I didn't see any "blocking task" for this one so I was hoping we could move forward 😅

2025-10-06 09:01 UTC, closed without merging