[FIX] payment_worldline: merchantReference is limited to 30 characters
odoo/odoo pull request #189298
Opened 2024-12-02 11:29 UTC by xavieralt

The hostedcheckout param  `order.references.merchantReference` is limited to 30 characters [^1], so we must not exceed that size for wordline's payment.transaction reference.

[^1]: https://apireference.connect.worldline-solutions.com/s2sapi/v1/en_US/go/hostedcheckouts/create.html?paymentPlatform=ALL

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-02 12:17 UTC, Demesmaeker requested changes
Hello @xavieralt 
Thanks for your fix, this'd ensure the prefix is not longer than 30 chars, but not that the merchantReference is also limited to 30 chars, if that reference already exists, it'll be completed like here: https://github.com/odoo/odoo/blob/18.0/addons/payment/models/payment_transaction.py#L381
Have a nice day,

2024-12-02 12:17 UTC, Demesmaeker commented on addons/payment_worldline/models/payment_transaction.py
> +            return super()._compute_reference(provider_code, prefix=prefix, separator=separator, **kwargs)
```suggestion
            return super()._compute_reference(
                provider_code, prefix=prefix, separator=separator, **kwargs
            )
```
Nitpicking: we try to stay < 100 chars per line =]

2024-12-02 16:41 UTC, xavieralt commented
@Demesmaeker
- fixed lines exceeding 100+ chars
- for the reference: we try computing it the normal way (which will works most of the time), if not we compute a generic reference with `WL` prefix (which will generate a 17-chars reference when singularized, so we have enough space left for the sequence counter)

2024-12-03 10:59 UTC, Demesmaeker approved these changes
Thanks for your changes ^^

2024-12-03 13:49 UTC, Demesmaeker commented
@robodoo r+

2024-12-03 15:33 UTC, robodoo commented
@xavieralt @Demesmaeker 'ci/runbot' failed on this reviewed PR.

2024-12-03 23:32 UTC, closed without merging