[IMP] website_sale: add video from frontend
odoo/odoo pull request #189396
Opened 2024-12-03 05:48 UTC by mash-odoo

**Prior to this commit:**

- Previously, users could only add images as extra media for products in the front-end editor. This update introduces a "Videos" tab, enabling video uploads.

**Post this commit:**

- Added a "Videos" tab to the front-end editor, allowing users to upload videos alongside images for extra product media.

**Affected version**: master
**Task**-3733878

2024-12-19 16:45 UTC, chevalierv reviewed
Hello @mash-odoo 

I can't edit the video with the web editor, when I click on it, it launches the video but I can't reorder it or change the video like I can with images. Could you take a look at this?

Also, as per the spec, Image should be renamed media in the website editor (See the last section on this screenshot)

![web editor](https://github.com/user-attachments/assets/f09fe78b-3299-495c-b7ef-e2e2a6f30040)

2024-12-19 16:45 UTC, chevalierv commented on addons/website_sale/controllers/main.py
>          :raises NotFound : If the user is not allowed to access Attachment model
Please take time to write a better docstring as you are changing it 
```suggestion
        :param type: [...] can be either image or video
        :raises NotFound : If the user is not allowed to access Attachment model
```

2024-12-27 09:16 UTC, mash-odoo commented
Hey @chevalierv :smile: ,
Thanks for bringing this up!

- Good news: you can now replace and reorder videos just like images- no more restrictions.
- Regarding renaming "Image" to "Media" in the website editor, we've made it smart, the implementation will be dynamic. When you replace an image, you'll see the image dialog, and for videos, it'll pull up the video dialog. So, it’ll work exactly as needed for each type of media.

2025-01-06 17:21 UTC, chevalierv commented
Hello @mash-odoo 

Could you rebase your PR, I'll have a look ASAP! 

Thanks and Have a nice day!

2025-01-07 10:21 UTC, mash-odoo commented
Hey @chevalierv Done!

2025-01-14 15:05 UTC, chevalierv requested changes
Hello @mash-odoo 

Sorry for the late review. Please find my comments below.

Also, I've found a traceback while testing your PR:
https://github.com/user-attachments/assets/7cb711bc-5444-4feb-b531-fcac057e8ec1




Have a nice day!

2025-01-17 05:09 UTC, mash-odoo commented on addons/website_sale/views/templates.xml
> +                <div class="media_iframe_video_size" contenteditable="false"/>
We need to have some specific classes for making the video editable just like the website, so we need classes like `media_iframe_video`, `css_editable_mode_display`, `media_iframe_video_size` and everyone plays a vital role for the same

2025-01-17 05:47 UTC, mash-odoo commented on addons/web_editor/tools.py
> +    }
The issue before was that the video customizations like autoplay, loop etc. weren't supporting. By parsing query parameters from the URL and mapping them to embed options (e.g., autoplay, loop, hiding controls), it allows users to specify video configurations directly in the URL. And this will work for all the required video types like vimeo, youtube, dailymotion etc. (for eg: hide_dm_logo is the parameter of dailymotion). In this function even previously, we were getting the values, but it wasn't passed further hence it needed a mapping.

2025-01-17 13:23 UTC, mash-odoo commented on addons/website_sale/views/templates.xml
> +                    allowfullscreen="true">
I checked our codebase, but I didn't find this anywhere.
I saw that mostly for video, this is used instead: `allowfullscreen="allowfullscreen"`
So I modifying it to this instead. Let me know what you think about this! :smile:

2025-01-17 17:04 UTC, chevalierv requested changes

2025-01-17 17:04 UTC, chevalierv commented on addons/web_editor/tools.py
> +    }
Okay, I get why you did that now but IMO, this should be in `get_video_source_data`. That way the parameters would be loaded correctly everywhere, you would just have to adapt a bit `get_video_url_data` to use params from source

2025-01-20 10:35 UTC, chevalierv commented on addons/web_editor/tools.py
Hello @odoo/rd-framework-editor 

What do you think of this implementation? I wonder if it's better to parse the params in `get_video_embed_code` or in `get_video_source_data `.

2025-01-20 13:50 UTC, mash-odoo commented on addons/web_editor/tools.py
For Ref: [get_video_embed_code](https://github.com/odoo/odoo/pull/189396/commits/11eb64ecc6487b459387cfd6ea3d346eafb7e14c) vs [get_video_source_data](https://github.com/odoo/odoo/pull/189396/commits/8ee69daa2f69ff98b9def5f427209a1eb427d270)

2025-01-21 07:31 UTC, dmo-odoo commented on addons/web_editor/tools.py
Hello @chevalierv @mash-odoo! To be honest, my team did not write any of those two functions, so I don't know for sure. That being said, I had a quick look and for me the right place to parse data from a video url would be `get_video_url_data`.

2025-01-21 09:30 UTC, chevalierv approved these changes
Hello @mash-odoo 

Thanks for your work on this PR!

@robodoo r+

Have a nice day 🌞

2025-01-21 09:59 UTC, robodoo commented
@mash-odoo @chevalierv 'ci/runbot' failed on this reviewed PR.

2025-01-21 17:40 UTC, closed without merging