[MOV] hr_*: move l10n time off types and work entry types to community
odoo/odoo pull request #189353
Opened 2024-12-02 15:58 UTC by Bertrand2

*:
- hr_holidays
- hr_work_entry
- hr_work_entry_contract
- hr_work_entry_holidays

To make l10n time off types and work entry types available, the data records were moved in community. As those models allow a restriction on the country those record were defined in standard to avoid multiplying bridge modules.

2024-12-20 15:48 UTC, arpi-odoo requested changes
Just 1 or 2 comments :melting_face:

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="holiday_status_sl" model="hr.leave.type">
```suggestion
    <record id="leave_type_paid_time_off" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="holiday_status_comp" model="hr.leave.type">
```suggestion
    <record id="leave_type_compensatory_days" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="holiday_status_unpaid" model="hr.leave.type">
```suggestion
    <record id="leave_type_unpaid" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    </record>
```suggestion
    <record id="l10n_ae_leave_type_sick_leave_50" model="hr.leave.type">
        <field name="name">Sick Leave 50%</field>
        <field name="requires_allocation">no</field>
        <field name="leave_validation_type">hr</field>
        <field name="support_document">True</field>
        <field name="icon_id" ref="hr_holidays.icon_22"/>
        <field name="company_id" eval="False"/>
        <field name="country_id" ref="base.ae"/>
    </record>

    <record id="l10n_ae_leave_type_sick_leave_0_leave_type" model="hr.leave.type">
        <field name="name">Sick Leave 0%</field>
        <field name="requires_allocation">no</field>
        <field name="leave_validation_type">hr</field>
        <field name="support_document">True</field>
        <field name="icon_id" ref="hr_holidays.icon_22"/>
        <field name="company_id" eval="False"/>
        <field name="country_id" ref="base.ae"/>
    </record>
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="l10n_be_holiday_type_small_unemployment" model="hr.leave.type">
Same for all belgium leave types
```suggestion
    <record id="l10n_be_leave_type_small_unemployment" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="holiday_type_hk_annual_leave" model="hr.leave.type">
Same for all hong kong leave types
```suggestion
    <record id="l10n_hk_leave_type_annual_leave" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="holiday_type_id_annual_leave" model="hr.leave.type">
same for all indonesian leave types
```suggestion
    <record id="l10n_id_leave_type_annual_leave" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="l10n_lu_holiday_status_situational_unemployment" model="hr.leave.type">
```suggestion
    <record id="l10n_lu_leave_type_situational_unemployment" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_holidays/data/hr_leave_type_data.xml
> +    <record id="l10n_sk_hr_leave_type_maternity" model="hr.leave.type">
```suggestion
    <record id="l10n_sk_leave_type_maternity" model="hr.leave.type">
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_work_entry_holidays/data/hr_leave_type_data.xml
> +<odoo><data noupdate="0">
remove data tag
```suggestion
<?xml version="1.0"?>
<odoo>
```

2024-12-20 15:48 UTC, arpi-odoo commented on addons/hr_work_entry_holidays/data/hr_leave_type_data.xml
> +    <record id="hr_holidays.holiday_status_comp" model="hr.leave.type">
Same naming as in `addons/hr_holidays/data/hr_leave_type_data.xml`

2024-12-23 16:52 UTC, Bertrand2 commented on addons/hr_work_entry/data/hr_work_entry_type_data.xml
> +    </record>
I'm guessing it's %, but I'll avoid making changes other than moving the records

2024-12-23 16:59 UTC, Bertrand2 commented on addons/hr_work_entry_contract/data/hr_work_entry_type_data.xml
> +</data>
Because it was before, not sure why tbh :shrug: but this isn't the purpose of the PR to change this

2024-12-23 16:59 UTC, Bertrand2 commented on addons/hr_work_entry_contract/data/hr_work_entry_type_data.xml
> +</data>
Some that should have `is_leave` set to `False`?

2024-12-24 10:00 UTC, arpi-odoo commented on addons/hr_work_entry_contract/data/hr_work_entry_type_data.xml
> +</data>
I thought I removed my comment because I saw the same thing, all good then

2024-12-24 10:13 UTC, arpi-odoo approved these changes
LGTM :+1: Nice work !

2025-02-27 16:21 UTC, closed without merging