[IMP] hr_holidays(_attendance): extra hours as allocation option
odoo/odoo pull request #189578
Opened 2024-12-04 13:16 UTC by khah-odoo

task-4317343

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-04 13:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189578.png)](https://mergebot.odoo.com/odoo/odoo/pull/189578)

2025-02-12 15:16 UTC, mepe-odoo requested changes
Thanks for your work :raised_hands:

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/models/hr_leave_type.py
> +                ])
you need to do your search outside of the loop. And you can just do one search and after you split your result in two to have the confirmed leave on one side and the validated leaves on the other.

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/models/hr_leave_type.py
> +                }, 'extra_hours', leave_type.id))
why do change all these values ? Before it was only two values

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/tests/test_holidays_overtime.py
Can you replace the removed tests by news tests based on your feature please ? :)

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/views/hr_leave_views.xml
> +                                            ('allows_negative', '=', False),
```suggestion
                            '&amp;',
                                ('has_valid_allocation', '=', True),
                                '|',
                                    ('allows_negative', '=', True),
                                    ('virtual_remaining_leaves', '&gt;', 0),
```

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/views/hr_leave_views.xml
> +                                        ('allows_negative', '=', False),
```suggestion
                                    ('allows_negative', '=', True),
                                    ('virtual_remaining_leaves', '&gt;', 0),
```
I think it's the same because allows_negative can just have 2 values so :woman_shrugging:

2025-02-12 15:16 UTC, mepe-odoo commented on addons/hr_holidays_attendance/views/hr_leave_views.xml
> +                                ('requires_allocation', '=', 'no'),
```suggestion
                            ('requires_allocation', 'in', ('extra_hours', 'no')),
```

2025-02-27 15:26 UTC, khah-odoo commented
Closing the PR is the task is cancelled.

2025-02-27 15:26 UTC, closed without merging