[IMP] payment_xendit: add TH, MY, VN coverage
odoo/odoo pull request #189527
Opened 2024-12-04 07:45 UTC by nni-odoo

Xendit has expanded to TH, MY and VN supporting the local payment channels. This commit is to add the supported pamyent channels according to what they have added.

4334511

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-04 07:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189527.png)](https://mergebot.odoo.com/odoo/odoo/pull/189527)

2025-03-21 15:33 UTC, livaios requested changes
Hello @nni-odoo,

Thank you for your work on this!
Keep in mind that this wont be available for existing users only for new users

Please check my comments below 
Have a nice day :slightly_smiling_face:

2025-03-24 01:22 UTC, nni-odoo commented on addons/payment/data/payment_method_data.xml
> +                         ref('base.MYR'),
this one's referring to `payment_method_wechat_pay`, I think Github cuts the whole section starting from line 3652

2025-03-24 01:22 UTC, nni-odoo commented on addons/payment_xendit/const.py
> +    'MYR': 0,
I originally added this variable if Xendit only allow decimal place that is different from the standard rounding of the currency.
Xendit allows only 0 d.p. and since VND is by standard 0 d.p. (https://github.com/odoo-dev/odoo/blob/18.0-xendit_add_regions-nni/odoo/addons/base/data/res_currency_data.xml#L258) I think we don't need it. But let me know if you think it's still good to add it!

2025-03-24 01:22 UTC, nni-odoo commented on addons/payment/data/payment_method_data.xml
> +        <field name="image" type="base64" file="payment/static/img/wallet.png"/>
Indeed. I tried asking the Xendit team previously if they have the image assets for the payment methods they allow but they seem to not want to share it :sweat_smile: , do you think it's ok for us to take from google image instead?

2025-05-06 01:14 UTC, nni-odoo commented
@livaios apologies for the late reply, quite some tasks came by.
I've made some changes per your feedback, thank you for the help!

2025-06-11 09:00 UTC, nni-odoo commented
Hi @livaios apologies for the inconvenience,

I've fixed the commit structure now and have also added the un-edited logos to the PR. Who can I ask for the logo editting part? 
I've also made changes per your feedback on code. Thanks!

2025-06-11 09:01 UTC, livaios commented
Hello @nni-odoo you can ask the design team

2025-06-12 03:23 UTC, nni-odoo commented
Hello @odoo/rd-design team! This is NNI from the HK office, I'm currently pushing this PR to add coverage of region supported by the payment provider Xendit.

I've added some new logos corresponding to new payment methods supported, but I got these from the internet. You can refer to the `.png` files under `payment/static/img`. Could you help re-format these logo so it follows standard? Thank you and let me know if there's anything I can do from my side!

2025-06-12 06:24 UTC, stefanorigano commented
@Brieuc-brd , could you handle this and add the new icons in our library for further use? Thanks!

2025-07-01 14:06 UTC, fja-odoo commented
Hello @Brieuc-brd, friendly reminder for this task :)

2025-07-01 14:46 UTC, Brieuc-brd commented
Hello @fja-odoo 👋 
Sorry, I had a fixup ready to be pushed 3 weeks ago, I was waiting for the green light from @nni-odoo to push it. I didn't get a response and forgot to ping him again, sorry 😅 .

I pushed the fixup, feel free to squash it with the rest 👍 .

2025-07-02 00:20 UTC, nni-odoo commented
@Brieuc-brd appreciate the help thanks!

2025-07-03 11:22 UTC, livaios requested changes
Hello @nni-odoo,

Just a few nitpicking formatting comments 

Thanks!

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +                     ])]"
```suggestion
        <field 
               name="supported_country_ids"
               eval="[Command.set([ref('base.my')])]"
```

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +        />
```suggestion
        <field 
               name="supported_currency_ids"
               eval="[Command.set([ref('base.MYR')])]"
        />
```

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +        />
Make them a one liner like `KFH` example

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +                     ])]"
Same

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +        />
Same

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +                     ])]"
Same

2025-07-03 11:22 UTC, livaios commented on addons/payment/data/payment_method_data.xml
> +    </record>
Same

2025-07-03 11:22 UTC, livaios commented on addons/payment_xendit/models/payment_transaction.py
> +        # specific condition for FPX payment method
```suggestion
        # If it's one of FPX methods, assign the payment method as FPX automatically
```

2025-07-03 11:22 UTC, livaios commented on addons/payment_xendit/models/payment_transaction.py
> +
```suggestion
```

2025-07-04 03:45 UTC, nni-odoo commented
@Brieuc-brd thank you!
@livaios I've revised the code and re-tested all 3 new regions functionally and it still works well. Thanks!

2025-07-07 12:01 UTC, livaios approved these changes
Thanks for checking out the comments :slightly_smiling_face: 
The changes LGTM :+1:

2025-12-17 17:04 UTC, AntoineVDV requested changes

2025-12-17 17:04 UTC, AntoineVDV commented on addons/payment/data/payment_method_data.xml
> +        <field name="code">vnptwallet</field>
VNPT vs VNPT Money vs VNPT Wallet... How is it usually called functionally and referenced technically?

2025-12-17 17:04 UTC, AntoineVDV commented on addons/payment_xendit/const.py
> +    'VND',
alphanum order

2025-12-17 17:04 UTC, AntoineVDV commented on addons/payment_xendit/const.py
> +    'THB': 0,
same

2025-12-17 17:04 UTC, AntoineVDV commented on addons/payment_xendit/const.py
```suggestion
# Comment to explain what are these codes
```

2025-12-18 02:52 UTC, nni-odoo commented on addons/payment/data/payment_method_data.xml
> +        <field name="code">vnptwallet</field>
I believe functionally they call it VNPT Money (the logo and the application is called VNPT Money). The technical part is called vnptwallet

2025-12-18 03:05 UTC, nni-odoo commented on addons/payment/data/payment_method_data.xml
> +        <field name="code">vnptwallet</field>
I'm changing the xmlid to `payment_method_vnpt_money` to follow the functional name for now

2025-12-18 14:24 UTC, AntoineVDV commented on addons/payment/data/payment_method_data.xml
> +        <field name="code">vnptwallet</field>
I'd rather match the XMLID with the code :sweat_smile: 

Functional terms come and go, but we should try to unify the technical codes/ids that identify that record.

2025-12-18 14:26 UTC, AntoineVDV requested changes

2025-12-18 14:26 UTC, AntoineVDV commented on addons/payment/data/payment_method_data.xml
> +    <record id="payment_method_vnpt_money" model="payment.method">
See https://github.com/odoo/odoo/pull/189527#discussion_r2631298718
```suggestion
    <record id="payment_method_vnptwallet" model="payment.method">
```

2026-01-09 12:58 UTC, AntoineVDV approved these changes
@robodoo r+

2026-01-09 12:58 UTC, robodoo commented
@AntoineVDV you may want to rebuild or fix this PR as it has failed CI.

2026-01-09 13:00 UTC, AntoineVDV requested changes, later dismissed

2026-01-09 13:00 UTC, AntoineVDV commented on addons/payment/data/payment_provider_data.xml
> +                   ref('payment.payment_method_vnpt_money'),
```suggestion
                   ref('payment.payment_method_vnptwallet'),
```

2026-01-12 15:36 UTC, AntoineVDV commented
@robodoo r+

2026-01-12 15:38 UTC, AntoineVDV approved these changes

2026-01-12 18:15 UTC, closed without merging