[FIX] website_google_map: world map zooming out when trying to render partners without location
odoo/odoo pull request #189518
Opened 2024-12-03 22:58 UTC by bikh-odoo

The World Map view when you are on the "/partners" page doesn't zoom. This happens when any of the partners that are getting rendered doesn't have location.

So, we can filtered out those partners that don't have the location, and only render the ones that have.

Steps to Reproduce on Runbot:
1. Integrate the Google Place Map key via settings->Geolocation->Google Place Map
2. Go to "/partners"
3. Make sure to have a world map view toggled on for the page via editor.
4. Make sure one of the partner on the page doesn't have location.
5. Go to the "map" view, and we'll see that the map is not zoomed in.

opw-4319619

2024-12-03 22:58 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189518.png)](https://mergebot.odoo.com/odoo/odoo/pull/189518)

2024-12-31 22:54 UTC, bikh-odoo commented
@qsm-odoo @bso-odoo Hi guys, I was wondering if you guys have a chance to review this PR? :slightly_smiling_face:

2025-01-06 15:26 UTC, qsm-odoo commented
@bikh-odoo No, did you ask us before? :thinking: I'll add it to my pipeline :+1:

2025-01-06 23:37 UTC, bikh-odoo commented
@qsm-odoo thank you! and not before, that was the first time asking :slightly_smiling_face:

2025-01-07 15:26 UTC, qsm-odoo requested changes
- Commit message: max 72 characters per line please
- Your PR targets 17.4, so the issue does not exists before? If that is so, your message should include a mention of the commit that created the bug. If that is not the case, then your PR should target the right version

2025-01-25 08:42 UTC, bikh-odoo commented
Hi @qsm-odoo, 

thank you for taking a look. So, after your comments, I tried investigating deeper, and found that the solution wasn't the filtering. The issue is with the Promise, which when rejected, we are not catching it so, it remains pending, and stuck on the line await Promise. So, catching the error when we call set_marker will solve the issue. 
        for (var i = 0; i < odoo_partner_data.counter; i++) {
                markerPromises.push(set_marker(odoo_partner_data.partners[i]).catch((error)=>
                    console.log(error)));
            }
            await Promise.all(markerPromises);
            new MarkerClusterer(map, markers, options);

      
      
Also, the first time version the issue occurs is on 17.2 as that's where the Promise gets introduced.

2025-01-27 14:35 UTC, qsm-odoo requested changes

2025-01-27 14:35 UTC, qsm-odoo commented on addons/website_google_map/static/src/js/website_google_map.js
> +                markerPromises.push(set_marker(odoo_partner_data.partners[i]).catch((error)=>
> Commit message: max 72 characters per line please

:point_up: 

> Missing spaces

You can probably write the line that way:
```javascript
const prom = set_marker(odoo_partner_data.partners[i])
    .catch(error => console.log(error));
markerPromises.push(prom);
```

Also, using `console.error` seems better? Or at least `warn`?

2025-01-28 00:01 UTC, bikh-odoo commented
hello @qsm-odoo, thank you for the suggestions. I made the changes according to the suggestions. :slightly_smiling_face: 

i also changed the commmit messages and the header.

2025-01-30 11:27 UTC, qsm-odoo approved these changes
Probably good enough :+1: 

@robodoo r+

2025-01-30 13:08 UTC, closed without merging

2025-01-31 00:11 UTC, bikh-odoo commented
@qsm-odoo thank you! :slightly_smiling_face: