[IMP] mail, im_livechat: update message params as a dict
odoo/odoo pull request #189686
Opened 2024-12-05 08:28 UTC by maki-odoo

`/mail/message/update_content` will be used in additional use cases in the portal. To do this, we need to pass more update params to the route, such as `rating_value`. This is a preparation PR to make passing update params simpler. This way, the updated data that should be handled in `_message_update_content` is sent as `update_data` dict so it's possible to manipulate it when it's needed. Non-update params such as security params are sent in `kwargs` as before.

2024-12-05 08:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189686.png)](https://mergebot.odoo.com/odoo/odoo/pull/189686)

2024-12-09 14:59 UTC, tde-banana-odoo requested changes
This kind of PR tends to make the code harder to read, understand and follow. I let you do what you want with discuss controllers, but in any case keep calling models using real parameters. We need to know what are the input and outputs.

2024-12-09 14:59 UTC, tde-banana-odoo commented on addons/mail/controllers/thread.py
> +            message, **update_data
Dont' do that, it makes the code impossible to follow (cannot grep arguments, how they are propagated, ...) As a general idea, it is a really bad move to hide everything in dicts. So keep calls to models using real parameters.

2024-12-09 14:59 UTC, tde-banana-odoo commented on addons/mail/tests/test_mail_message_translate.py
> +            {"message_id": self.message.id, "update_data": {"attachment_ids": [], "body": None}},
Reading this, I don't see what you gain, expect you blur everything using sub-dicts.

2025-02-13 09:32 UTC, maki-odoo commented
Done in odoo/odoo#192202

2025-02-13 09:32 UTC, closed without merging