[IMP] pos*: introduce sale warnings when selecting a customer
odoo/odoo pull request #189671
Opened 2024-12-05 04:53 UTC by parp-odoo

pos*: pos, pos_hr

In this commit:
=========
Add a sale warning feature while adding a customer to a current order (similar to sales).

The available sale warnings are:-
- **No Message (default):** No warning when adding a customer.
- **Warning:** A warning popup is shown, but the customer is still added.
- **Blocking Message:** A warning popup is shown, and the customer is not added.

Task - 4375272

2024-12-05 04:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189671.png)](https://mergebot.odoo.com/odoo/odoo/pull/189671)

2024-12-17 06:47 UTC, paso-odoo requested changes

2024-12-17 06:47 UTC, paso-odoo commented on addons/pos_sale/models/res_partner.py
> +# Part of Odoo. See LICENSE file for full copyright and licensing details.
```suggestion
```

2024-12-17 06:47 UTC, paso-odoo commented on addons/pos_sale/models/res_partner.py
> +    _inherit = ['res.partner', 'pos.load.mixin']
```suggestion
    _inherit = 'res.partner'
```

2024-12-17 06:47 UTC, paso-odoo commented on addons/pos_sale/models/res_partner.py
> +    _name = 'res.partner'
```suggestion
```

2024-12-17 06:47 UTC, paso-odoo commented on addons/pos_sale/models/res_partner.py
> +        return data_fields
```suggestion
        return super()._load_pos_data_fields(config_id) + ['sale_warn', 'sale_warn_msg']
```

2024-12-17 06:47 UTC, paso-odoo commented on addons/pos_sale/static/src/app/services/pos_store.js
> +        if (productTemplate.sale_line_warn !== "block") {
```suggestion
        }
        // product is not added to the cart if it is blocked 
        if (productTemplate.sale_line_warn !== "block") {
```

2025-01-09 10:54 UTC, adgu-odoo requested changes
Most of it is fine for me, good job. Could you just look at my comments and resolve them? TY

2025-01-09 11:06 UTC, parp-odoo commented on addons/pos_sale/static/src/app/services/pos_store.js
> +        super.setPartnerToCurrentOrder(partner);
The existing partner will be removed when attempting to set a blocked partner while **another partner is already assigned**. 
For that we call the super with `False` as a parameter.

2025-01-10 08:19 UTC, adgu-odoo approved these changes

2025-01-10 10:46 UTC, adgu-odoo commented
robodoo r+

2025-01-10 13:54 UTC, closed without merging