[FIX] sale_timesheet: fix visibility of 'time remaining on SO' in pro…
odoo/odoo pull request #189795
Opened 2024-12-05 16:25 UTC by chrisduvivier

…ject sharing

In project sharing, the field 'time remaining on SO' should not be available when the project has no billable and no timesheets enabled. This commit aims to fix the visibility of this field by adding condition to the field in the List view.

To reproduce the bug:
1. Create Project with No billable and No timesheets enabled
2. Create some task in the new Project
3. Go to Project > Settings > Project Sharing with portal user
4. Login as Portal User and open the List view on the Project
5. The field 'time remaining on SO' is available among the Field to add.

After the fix:
In Step 5, the field 'time remaining on SO' should not be available.

Note: the issue is observed in 16.0 until saas-17.2

Task: 4369886

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-05 16:25 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189795.png)](https://mergebot.odoo.com/odoo/odoo/pull/189795)

2024-12-11 12:25 UTC, RaoufGhrissi requested changes
Thanks for your work, I added few comments.

2024-12-17 11:36 UTC, chrisduvivier commented on addons/sale_timesheet/views/project_sharing_views.xml
> +                    attrs="{'column_invisible': ['|', '|', '|', ('allow_billable', '=', False), ('sale_order_id', '=', False), ('partner_id', '=', False), ('remaining_hours_available', '=', False)]}"
Thanks for the review Raouf, you are definitely right. I didn't realise the `allow_timesheets` field and took similar condition I found on the form view above on line 36, but your suggestion is correct.

As for applying the same font coherently to the field, I've asked Alex about her opinion.
Thanks a lot!

2024-12-24 09:47 UTC, RaoufGhrissi commented on addons/sale_timesheet/views/project_sharing_views.xml
> +                    attrs="{'column_invisible': ['|', '|', '|', ('allow_billable', '=', False), ('sale_order_id', '=', False), ('partner_id', '=', False), ('remaining_hours_available', '=', False)]}"
hey @chrisduvivier  thanks for your changes, my point about 'coherency' was about the domain not about the color
![image](https://github.com/user-attachments/assets/4b3ee931-3f22-4e26-a3c7-1021c93e60cf)
why both domains are different, if the spec wants to hide it if allow_billable = False or allow_timesheets = False in the list view, so it should be also the same domain in the form view. what do you think ?

2025-02-05 09:14 UTC, xavierbol commented
I just rebase your branch

2025-02-05 12:08 UTC, xavierbol reviewed
LGTM, thanks for your work! 🙂 

robodoo r+

2025-02-05 12:10 UTC, xavierbol commented
robodoo r-

2025-02-24 11:09 UTC, xavierbol reviewed
LGTM, thanks for your work! 🙂 

robodoo r+

2025-02-24 13:00 UTC, closed without merging