[FIX] website: duplicate dialog issue and closure on button click
odoo/odoo pull request #189788
Opened 2024-12-05 15:31 UTC by SergeBayet

Since [1], clicking the button while the SEO toaster was
visible could repeatedly open the SEO optimization dialog, resulting in
multiple instances of the dialog box being opened.

This commit addresses this issue by:

- Adding logic to ensure toasters close properly when a button is
  clicked. (i.e the SEO toaster when you publish a page with missing
  important SEO informations).

[1]: https://github.com/odoo/odoo/commit/45ea6e4a4a5c8e314b110a45198fbe3d57bb996e

task-4384773

2024-12-05 15:31 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189788.png)](https://mergebot.odoo.com/odoo/odoo/pull/189788)

2025-01-06 08:24 UTC, aab-odoo commented
I don't think this is the responsibility of the notification service. It's purpose is to display notifications. If some piece of code generates duplicated notifications, and we don't want them, this is the one that needs to be fixed.

2025-01-06 09:08 UTC, SergeBayet commented
> I don't think this is the responsibility of the notification service. It's purpose is to display notifications. If some piece of code generates duplicated notifications, and we don't want them, this is the one that needs to be fixed.

@aab-odoo You're probably right, but i had no access to the notifications already there with the notification service. I had to add the object in the export alongside the 'add' method. Do you think of a better way?

2025-01-06 09:15 UTC, aab-odoo commented
you can debounce (core/utils/timing) the calls to notify(), with the same delay as the notification delay. Either in the component directly if you have a single component instance triggering all the notifications, or in a dedicated service in-between the component and the notification service.

I wouldn't change the API of the notification service. I'm afraid exposing notifications would be tempting for people to do weird stuff, like altering the array, modifying the props...

2025-01-06 09:20 UTC, SergeBayet commented
> you can debounce (core/utils/timing) the calls to notify(), with the same delay as the notification delay. Either in the component directly if you have a single component instance triggering all the notifications, or in a dedicated service in-between the component and the notification service.
> 
> I wouldn't change the API of the notification service. I'm afraid exposing notifications would be tempting for people to do weird stuff, like altering the array, modifying the props...

I was afraid of that too. I'll try to use the debounce utility with the same delay (4s I think). Thanks for your input.

2025-01-13 09:41 UTC, qsm-odoo requested changes
Commit message:
- Mentioned apps are wrong (while you are at it: missing space after `,`)
- "Preventing duplicate toasters by checking existing notifications before adding a new one." -> I don't see the code which does that
- task-XXX after the commit references please :pray:

2025-01-13 09:41 UTC, qsm-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +            }.bind(this),
Can't this just be `this.notify`? At worst `(...args) => this.notify(...args)`?

2025-01-13 09:41 UTC, qsm-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +            true
If I am not wrong, "true" means "leading=false, trailing=true". With a big 3 seconds delay... it means that when we call debouncedNotify, we only show the notification 3 whole seconds later... am I right? Is that really ok?

(see next comment: I would like to test but not sure how to)

2025-01-13 09:41 UTC, qsm-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +                autocloseDelay: AUTOCLOSE_DELAY,
Can you add real steps to reproduce in the commit message? This spoke about SEO but this code here is about the link popover, not sure how to reach this code.

2025-01-13 09:47 UTC, aab-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +            true
> If I am not wrong, "true" means "leading=false, trailing=true"

@qsm-odoo I think it's the opposite
![image](https://github.com/user-attachments/assets/5bec79ca-af79-41d5-b8d4-1b0bdcc972ed)

Note: this API is awful...

2025-01-13 10:10 UTC, SergeBayet commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +            }.bind(this),
You're right indeed.

2025-01-13 10:25 UTC, SergeBayet commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +                autocloseDelay: AUTOCLOSE_DELAY,
It was easier to reproduce the bug before this commit https://github.com/odoo/odoo/commit/da4faf4982840ea186dd71cf708d38f4d17c479a
But another way to do it: (I'll add the steps to reproduce in the commit message)
- Switch to edit mode.
- Click on the phone number in the header.
- In the options tab, change the URL to a URI like: geo:37.786971,-122.399677.
- Click on the phone number in the header again – the notifications will appear.
- Quickly click the URL in the options tab, then click the phone number in the header again.
- You’ll notice the notifications start stacking.

2025-01-13 10:32 UTC, SergeBayet commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +                autocloseDelay: AUTOCLOSE_DELAY,
But I wonder if it's worth keeping this fix (debounce) since the bug is now quite difficult to reproduce...

2025-01-13 14:27 UTC, qsm-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
> +            true
> if true, equivalent to exclusive leading. If false, equivalent to exclusive trailing.

Ok, I guess it's my english that is bad because I read that as "leading is excluded" instead of "only leading". But yeah, I would never pass a boolean ^^

2025-01-14 16:39 UTC, qsm-odoo requested changes
>  But I wonder if it's worth keeping this fix (debounce) since the bug is now quite difficult to reproduce...

@SergeBayet Indeed, I would remove that part of the fix. IMO it's more code for no-better, maybe even worse, behavior. I don't actually think it's really a bug that if you click multiple times on something wrong, you have multiple notifications about it. Your initial idea (not showing again if the notification is still there) is what we should do... I think we should really consider it @aab-odoo, the debounce idea is not good:

A.
- Click on the button -> notification shows up, good
- Keep clicking -> no added notification, good
- Notification disappears (autoclose)
- Keep clicking -> no notification is added... why?
- Stop clicking for a while
- Click on the button -> notification is added now :shrug: 

B.
- Click on the button -> notification shows up, good
- Close the notification by hand
- Re-click on the button  -> Cool, I don't have the error anymore... wait... wut?
- Wait for a while
- Re-click on the button -> now the error shows up.

All in all, I don't think debouncing is a good usecase for a notification. It acts as a "never show me again but only for 3 seconds", that does not make sense to me. Either never show again or keep showing... or the best: don't re-show while it is still being shown, but this requires changing the API, I don't see how we would be supposed to code that. I guess we could do "close the previous notification if I open a new one"... did you try that @SergeBayet ? But there would be a weird effect and more code :shrug: For now, I'd say you can just remove that part of the fix @SergeBayet

2025-01-15 07:22 UTC, aab-odoo commented
@SergeBayet @qsm-odoo 

The related task doesn't seem to be about duplicated notifications (but instead duplicated dialogs), so this discussion is a bit "abstract". But what I'm sure is that the notification service should not implement such kind of deduplication logic. If someone wants to trigger twice the same notification, he should be able to do so. If your usecase is a button, which, when clicked, triggers a notification, I think there's nothing to do. It's good to spawn a notification each time the user clicks, as he gets a feedback of the action he did. Otherwise, like you said on the example, he could believe that his click worked, as it didn't trigger a new notif...

2025-01-15 10:02 UTC, SergeBayet commented
> All in all, I don't think debouncing is a good usecase for a notification. It acts as a "never show me again but only for 3 seconds", that does not make sense to me. Either never show again or keep showing... or the best: don't re-show while it is still being shown, but this requires changing the API, I don't see how we would be supposed to code that. I guess we could do "close the previous notification if I open a new one"... did you try that @SergeBayet ? But there would be a weird effect and more code 🤷 For now, I'd say you can just remove that part of the fix @SergeBayet

I did that but I had to change the notifications API to expose the notification.messages object. That's probably not what we want. I'll remove this *almost*-fix, since I also consider that's not a bug anymore like you said.

2025-01-15 15:04 UTC, qsm-odoo approved these changes
@SergeBayet

Nitpicking but I changed the commit message: "When applied, this commit will... duplicate dialog issue" was hopefully not the goal :wink: 

> I did that but I had to change the notifications API to expose the notification.messages object.

What I was saying is that you could use the same thing you do for the SEO button, without changing the API: get the close function and before adding a new notification, close the previous one. But that would not be much better.

@aab-odoo 

> It's good to spawn a notification each time the user clicks

I think it would be slightly better for the same notification to not re-pop if it's already there, after clicking on the same element. But that's totally fine if it shows multiple times too. 

> If someone wants to trigger twice the same notification, he should be able to do so.

Of course, it would have been easy to implement an option like a "notification ID" to not base the check of "is the notification still open" on the message but on an another ID, but yes, maybe the less code the better.

@robodoo r+

2025-01-16 05:03 UTC, closed without merging