PRHOOT 28
odoo/odoo pull request #189710
Opened 2024-12-05 10:39 UTC by jum-odoo

## Pull Request HOOT (PRHOOT) 28

This pull requests brings various improvements and fixes to Hoot and the Odoo unit test ecosystem. See the different commit messages for more details.

Note: these changes are made in stable to avoid having to support multiple versions of the HOOT API. As such, these changes are intended to be strictly limited to unit tests as to not put the rest of the code base at risk.

Enterprise: https://github.com/odoo/enterprise/pull/78636

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-05 10:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189710.png)](https://mergebot.odoo.com/odoo/odoo/pull/189710)

2025-02-03 12:57 UTC, seb-odoo requested changes
Hello, here some comments based on the diff.

Also I strongly disagree for the change about animations and smooth scrolling, this makes the tests further from reality, they will be faster and more likely green, but the change will just hide when actual flows are broken. I don't know where the reasoning comes from, but for most tests, this change will make no difference at all, and for the tests that actually rely on this, we want to keep it.

Each test in our scope should be reviewed individually in this regard and I'd like all existing tests to keep the behavior before this PR. In particular but not limited to all tests that have scroll in their name or in their content.

2025-02-03 12:57 UTC, seb-odoo commented on addons/im_livechat/static/tests/embed/livechat_button.test.js
> +    await contains(".o-mail-Message-content", { text: "How can I help?" });
Why this should be changed? Order between the 2 await should be irrelevant here.

2025-02-03 12:57 UTC, seb-odoo commented on addons/im_livechat/static/tests/sidebar_patch.test.js
> +    await contains(".o-mail-Message", { text: "Hello" });
Why this should be changed? Order between the 2 await should be irrelevant here.

2025-02-03 12:57 UTC, seb-odoo commented on addons/mail/static/tests/discuss/core/web/sidebar.test.js
> +    await contains(".o-mail-Message", { text: "Hello" });
Why this should be changed? Order between the 2 await should be irrelevant here.

2025-02-03 12:57 UTC, seb-odoo commented on addons/mail/static/tests/discuss/call/ptt_ad_banner.test.js
> +    await animationFrame();
What's the point of this? The following `click` is supposed to wait for the element to be in DOM anyway. Adding an extra delay shouldn't make a difference.

2025-02-04 10:35 UTC, seb-odoo approved these changes
Thank you for the update! That looks like a reasonable trade-off.

2025-02-05 09:25 UTC, dmo-odoo commented on addons/html_editor/static/tests/delete/backward.test.js
> +        await microTick();
Why do you need to wait for two micro ticks? And why specifically those two files, `backward` and `forward`, and not any other?

2025-02-05 10:24 UTC, jum-odoo commented on addons/html_editor/static/tests/delete/backward.test.js
> +        await microTick();
This is due to the fact that dispatching events now also registers a "test event" (i.e. a log in the test result report), and this apparently messed up with the timing in these specific tests due to them relying on precise timing with the `tripleClick` helper. I reverted the diff in these tests and made sure that the timing in that helper remained the same.

2025-02-24 12:34 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-02-24 12:36 UTC, robodoo commented
@jum-odoo @mcm-odoo 'ci/template' failed on this reviewed PR.

2025-02-24 12:43 UTC, robodoo commented
@jum-odoo @mcm-odoo 'ci/runbot' failed on this reviewed PR.

2025-02-24 14:00 UTC, robodoo commented
@jum-odoo @mcm-odoo linked pull request(s) odoo/enterprise#78636 not ready. Linked PRs are not staged until all of them are ready.

2025-02-24 16:59 UTC, closed without merging