[IMP] hw_drivers: add devtools to disable features
odoo/odoo pull request #189768
Opened 2024-12-05 14:40 UTC by loouis-t

While developing, we often disable features like the db checkout and the IoT handlers download to save some time.

Now, instead of going in the code and comment the lines we want to remove, we can just type:

- `devtools disable general`: to disable general features (checkout, handlers download),
- `devtools disable actions <optional action name>`: to disable a device action (printing for example).

**Note:** by default, if you don't specify `<action name>`, it will disable all actions.

Task: 4291487

2024-12-05 19:00 UTC, lse-odoo commented
@loouis-t 
Is there any reason to do it in such a way rather than a menu in the iot ?

2024-12-06 09:52 UTC, lse-odoo commented
> > @loouis-t
> > Is there any reason to do it in such a way rather than a menu in the iot ?
> 
> We can do it as well, it's just an additional key in the `odoo.conf`. I spent more time thinking about how to do it without adding too much code in the drivers.

In my opinion it is more valuable and would let the customer have the full control. Prevent handler update could also be useful on windows virtual IoT (and checkout when windows IoT will use git)

2025-01-02 16:49 UTC, Ysoroko requested changes
Some minor suggestions in the comments.
Devtools work as expected and allow to deactivate useful features

2025-01-02 16:49 UTC, Ysoroko commented on addons/iot_box_image/overwrite_before_init/etc/init_image.sh
> +}
I'd say that for this to be less error-prone we can also limit the accepted arguments to:
1) `enable/disable`
2) `general/actions`

Otherwise we can end up with things like 

```
[devtools]
blabla = *
```

2025-01-02 16:49 UTC, Ysoroko commented on addons/iot_box_image/overwrite_before_init/etc/init_image.sh
> +    devtools enable \$2
the `enable` within `disable` is confusing, we should explain that we overwrite the existing value here

2025-01-02 16:49 UTC, Ysoroko commented on addons/iot_box_image/overwrite_before_init/etc/init_image.sh
> +    echo 'Usage: devtools <enable/disable> <general/actions> [action name]'
add the description of how to (de)activate multiple actions at a time

2025-01-09 12:50 UTC, xmo-odoo reviewed
> Could I have your opinion on such a tool? The idea here is to add some developer tools which would allow to de/re activate some methods which have the introduced decorator
> 
> While this would be a great tool to help us debug and work with the IoT Box, this might raise some security concerns so I prefer to have your opinion

:shrug: seems to require shell access to use so w/e?

2025-01-09 14:35 UTC, loouis-t commented
retargeted to [saas-18.1](https://github.com/odoo/odoo/pull/193078) (taking (xmo)'s comment into account.

2025-01-09 14:35 UTC, closed without merging