[FIX] website: Fix hreflang website test
odoo/odoo pull request #189705
Opened 2024-12-05 10:29 UTC by amay-odoo

The Issue:
Prior to this commit, invoking _get_frontend resulted in the get_current_website function returning a different website than the one specified in the MockRequest.

The Fix:
To resolve this, we ensure the function selects the correct website by explicitly passing it in the context.

runbot-64729

2024-12-05 10:29 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189705.png)](https://mergebot.odoo.com/odoo/odoo/pull/189705)

2024-12-17 12:48 UTC, amay-odoo commented
Hello @odoo/rd-website , Could someone please take a look at this PR? Thanks :)

2024-12-17 13:09 UTC, qsm-odoo requested changes
> Prior to this commit, invoking _get_frontend resulted in the get_current_website
function returning a different website than the one specified in the MockRequest.
>
> To resolve this, we ensure the function selects the correct website by explicitly passing it in the context.

What's the point of passing a website to the `MockRequest` if the calls to `get_current_website` afterwards do not use the given website?

2024-12-17 13:17 UTC, amay-odoo commented
Hello @qsm-odoo , I'm not sure why the `get_current_website` does not get the correct website passed in the `MockRequest`, but the behavior is that `get_current_website` does not return the same website (returns another website with a different id than 1), so I tried to pass the website in the context as an alternative

2024-12-17 13:47 UTC, qsm-odoo commented
@amay-odoo You should rather fix `MockRequest` IMO. Apparently it creates an env with `env = env(context=dict(context, lang=lang_code))`, should not the website be given there and everything might be fixed? :thinking: (don't know, wild guess).

2024-12-17 14:58 UTC, amay-odoo commented
Hello @qsm-odoo , thank you for the suggestion, I tried this approach and unfortunately, it didn't work because the `get_current_website` gets the `website_id` either from
- the `force_website_id` key inside the `request.session`
- the `context` passed from the test and not the context inside the `request`

Therefore we cannot fix the `MockRequest`.
At the moment I'm thinking about 2 approaches, either:
- passing the `force_website_id` in the `request.session` like that:
```
with MockRequest(self.env, website=website) as mock_request:
            mock_request.session["force_website_id"] = website.id
```

- Pass the `website_id` in the context within `self.env['res.lang']` as I did in this commit

or if you have any other suggestion please
Thank you very much for your time :)

2024-12-17 17:34 UTC, qsm-odoo commented
@amay-odoo With either solution, I don't understand what is the point of using the `MockRequest` then: with your solution, would not it work exactly the same just not using `MockRequest`?

2025-01-09 10:40 UTC, amay-odoo commented
Hello @qsm-odoo , The `MockRequest` is necessary because many functions rely on the request object, such as the `_get_frontend` function, which checks for a request before proceeding. Without the MockRequest, the resulting dictionary will be incomplete, leading to a test failure.

2025-01-17 16:31 UTC, qsm-odoo approved these changes
@robodoo r+

2025-01-17 19:24 UTC, closed without merging