[IMP] web: allow using the properties in the dynamic placeholder
odoo/odoo pull request #189841
Opened 2024-12-06 09:39 UTC by std-odoo

Purpose
=======
Allow using the properties in the dynamic placeholder (so we can use them for mail template, mailing, etc). Hide the separator properties, as it makes no sense to show their value in a template.

Technical
=========
For standard fields, the value is retrieved with `record.field`, we can't do that for properties, because for performance reason, all the verification (if the property still exists in the definition, if the m2x value still exists in database, if we removed a tag, etc) are done on `read` (not on `getattr`).

Also, we want to be able to follow the relational properties (m2o, m2m), like we do for normal fields. For that purpose, we added a method that will do all of that (using `read`, convert the record integer id to recordset, etc) so the templates are cleaner.

Task-4363868

2024-12-06 09:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189841.png)](https://mergebot.odoo.com/odoo/odoo/pull/189841)

2024-12-18 13:54 UTC, thjo-odoo reviewed
Hello @std-odoo 
Quite the work there, here's the validation.
Cheers!

2024-12-18 13:54 UTC, thjo-odoo commented on addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
> +                name = `_read_property('${this.selectedName}')`;
Since they are the same object.
```suggestion
                name = `_read_property('${name}')`;
```

2024-12-23 11:49 UTC, std-odoo reviewed
@thjo-odoo Hi :)

Thanks for the validation, I did the change and answered :)

2024-12-23 11:49 UTC, std-odoo commented on addons/web/models/models.py
> +            return next((t[1] for t in (definition.get('selection') or []) if t[0] == value), '')
it was intended (it's a bit more robust in case we have `False` in the selection for some reason)

2024-12-23 14:41 UTC, thjo-odoo approved these changes

2025-03-20 12:33 UTC, ryv-odoo requested changes
AFAIK, We have already at least 3 spots where we use properties in backend (export/import/crm) and new ones are coming (this one and filtered_domain that doesn't work with it). Each we have a different implementation (sometimes batched sometimes not, this one by ) for it that simulate a kind of `convert_to_record`.

2025-03-20 12:42 UTC, ryv-odoo commented on addons/web/models/models.py
> +            return self.read([field_name])[0][field_name] if self else False
This method should be only called for properties field. Don't create a new way to get a scalar value in a very inefficient way.

2025-04-10 13:15 UTC, kmagusiak reviewed
The overall idea is good: let property be a class that implements the same logic as the underlying dict.
However, there is no need for distinctions between None and False values. I will try to make a smaller PR with just the property adapted; I'll keep you posted.

2025-04-10 13:32 UTC, rco-odoo requested changes

2025-04-10 13:32 UTC, rco-odoo commented on odoo/addons/test_new_api/tests/test_properties.py
> +        self.assertEqual(self.message_3['attributes']['moderator_partner_id'], None)
That's a very bad idea.  If a key doesn't exist in a `dict`, accessing it raises a `KeyError` exception.  That's what you should get.

2025-04-10 13:32 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +    """Allow to be used in `convert_to_record` to make the verification only if we try accessing the property value."""
That's gibberish to me.  Please describe what a `Property` object is.  If I am not mistaken, it is the value of a "properties" field in the "record" format, i.e., the result of evaluating `record.property_field`.

2025-04-10 13:35 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +        raise ValueError("You can not write on a single property.")
Because you should modify the `properties` field instead of its value.  The value itself is immutable.

2025-04-10 13:48 UTC, std-odoo reviewed
@rco-odoo @kmagusiak Hi :) 

Thanks for the review, I did the change, except for `NoneProperty`

In a mail template, you can add a property in the template, but execute the template on a record not having that property

If it's not a relational property, no issue, we can return False

If it's a relational property, then we can not return False, because you can do

```python
record.properties['m2o_property'].company_id.name
```

The solutions I see are
- the `NoneProperty` class I did
- having ugly mail template with safe code
- making a SQL query (`get_property_definition`) to have the model, and returning `env[model]`

I'm open if you have othe ideas

Cheers

2025-04-10 13:48 UTC, std-odoo commented on odoo/addons/test_new_api/tests/test_properties.py
> +        self.assertEqual(self.message_3['attributes']['____'], None)
We can't, for mail template you can do
```
partner_id.name
```
and it won't crash if partner is falsy

We need the same for property, but you can execute a template on a record for a different parent (that's why we have NoneProperty)

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        records = self.record | self.record.browse(islice(self.record._prefetch_ids, 1000))
it was an optimization based on the fact that I'll get a "cached" exist, because it has been cancelled, I can revert this (and other place where I support batching)

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +            return NoneProperty()
We need it, see above (you can try to read a property that's defined on a different definition record, and so you don't have the definition, and it will cost a SQL query to get it)

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        raise ValueError("You can not write on a single property.")
we don't need it for now

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +    """Allow to be used in `convert_to_record` to make the verification only if we try accessing the property value."""
Yes, it's the result of `record.property_field`, the thing is that you can write a mail template, inserting a property of the "CRM team A", but execute that template on a record of the "CRM team B", this shouldn't crash imo, like for standard field

Once the template is validated, it shouldn't crash

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +    """Allow not crashing when doing `record.properties['prop']['partner_id']['name']`.
How do you do this safely in a mail template ?
```
record.properties['aaa'].company_id.name
```

2025-04-10 13:48 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        return Property(copy.deepcopy(value or {}), self, record)
it was there before, I can remove it

2025-04-11 06:12 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +    """Allow not crashing when doing `record.properties['prop']['partner_id']['name']`.
> The rest is the regular behavior of the ORM, isn't it?

Not if we crash because the property doesn't exist on that definition record

With "regular" behavior, we return an empty recordset

> I don't know what the third case should return, but it clearly looks wrong to me.

That's the only problem we have, that's why I have `NoneProperty`, I can do an additinal query to get the definition and return an empty recordset

What do you think ?

2025-04-11 06:37 UTC, std-odoo commented
@rco-odoo @kmagusiak I pushed a fixup commit with the POC to use the extra query when we don't have the definition, to return an empty recordset if needed

Let me know what you think

2025-04-11 10:26 UTC, rco-odoo reviewed
I have the feeling that the base implementation of fields `Properties` and `PropertiesDefinition` are not adequate, and really make your life difficult when you try to build things on top of them.

2025-04-11 10:26 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            definition = self.record.get_property_definition(f"{self.field.name}.{property_name}")
The performance issue with this call is `get_property_definition()`'s implementation, which always seemed awkward to me.  The definition of properties on a record depend on that record, doesn't it?  That's what the `definition` parameter is for.  The method simply ignores the record `self`, and the method is even decorated with `@api.model`.  It _always_ perform an SQL query (performance anti-pattern), and retrieves a _random_ value (LIMIT 1 without ORDER BY) for the corresponding `PropertiesDefinition` field.  Why don't you simply access ``record[field.definition_record][field.definition_record_field]``?

2025-04-11 10:26 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            return self.record.env[prop.get('comodel')].browse(prop.get('value')).with_prefetch()
`prefetch_ids` doesn't make sense to me.  And by the way, it's not used.  And by the way, `with_prefetch()` is totally useless in this context.

2025-04-11 10:26 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            return self.record.env[prop.get('comodel')].browse(prop.get('value')).with_prefetch(prefetch_ids)
Please explain.  The value is a recordset with ids like (42, 43, 45) and with unrelated prefetch ids like (1, 2, 3).  A loop on the recordset will fetch each record separately.  That call to `with_prefetch()` is a _counter_-optimization.

I suggest to simply ignore prefetching at the moment, we can improve this later.

2025-04-11 10:26 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +    def __getitem__(self, property_name):
Note that `dict` is not an abstract implementation.  The method `dict.get` does not call `dict.__getitem__`; it will therefore leak its "inner" value.  The same holds for methods `dict.values()`, etc.  The class `Property` should subclass `collections.abc.Mapping`, and store the cached value inside a "private" attribute.  What you want is a proxy object to the dict, not the dict itself.

2025-04-11 12:18 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            definition = self.record.get_property_definition(f"{self.field.name}.{property_name}")
> As I said in my review reply, you can read a property on a record not having that property (because it's defined on a different definition record)

Of course you can.  Simply get the property definition on the definition record, and you know the type of stuff you expect.  You cannot read a property _that is not defined_ on the definition record, but that's a different thing.

2025-04-11 12:24 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +            definition = self.record.get_property_definition(f"{self.field.name}.{property_name}")
> You cannot read a property that is not defined on the definition record, but that's a different thing.

So I guess you expect it to crash ?

So we go for the solution "ugly expression" in template ?

2025-04-11 12:25 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +        values = self.field.convert_to_read(records.env.cache.get(records, self.field), self.record, use_display_name=False)
I have the feeling that the overhead of `convert_to_read` is stupidly high.  Instead of mapping the cached value to the "read" format directly, you should map it to the "record" format, and then to the "read" format.

Moreover, method `cache.get()` takes one record, and you pass it all the records, which is obviously wrong.  If you fix this, you will realize that `records` is useless (it was already, but it will no longer be used.)

2025-04-11 12:27 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            # We need to know if it's a relational property defined on a different definition record
Please explain why "on a different definition record".  That part doesn't make any sense to me.  What's the point of defining a definition record if you can pick anyone in practice?

2025-04-11 12:31 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        values = self.field.convert_to_read(records.env.cache.get(records, self.field), self.record, use_display_name=False)
> I have the feeling that the overhead of convert_to_read is stupidly high. Instead of mapping the cached value to the "read" format directly, you should map it to the "record" format, and then to the "read" format.

How do you batch the check in `_get_res_ids_per_model` ?

2025-04-11 12:32 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        values = self.field.convert_to_read(records.env.cache.get(records, self.field), self.record, use_display_name=False)
> I have the feeling that the overhead of convert_to_read is stupidly high. Instead of mapping the cached value to the "read" format directly, you should map it to the "record" format, and then to the "read" format.

How do you batch `_get_res_ids_per_model` ?

Ok to remove `recrods`

2025-04-11 12:35 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +        values = self.field.convert_to_read(records.env.cache.get(records, self.field), self.record, use_display_name=False)
Or we need `convert_to_record_multi`

2025-04-11 13:02 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +    def __getitem__(self, property_name):
the onchange behave weirdly with a `collections.abc.Mapping`, I'll check if I have enough time when we know what approach we take (and when I did it)

2025-04-11 13:03 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +            # We need to know if it's a relational property defined on a different definition record
will be dropped if you are ok with the solution "always raise if property doesn't exist, and safe expression in template"

2025-04-11 13:46 UTC, std-odoo commented on odoo/orm/fields_properties.py
> +            definition = self.record.get_property_definition(f"{self.field.name}.{property_name}")
@rco-odoo I pushed the poc I call "ugly expression", so you can compare if you prefer

2025-04-11 15:03 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            raise KeyError(self.record.env._("Property doesn't exist"))
```suggestion
            raise KeyError(property_name)
```

2025-04-11 15:12 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +        values = self.field.convert_to_read(records.env.cache.get(records, self.field), self.record, use_display_name=False)
No, introducing prefetching is much more subtle than that.  You will need something like https://github.com/odoo/odoo/blob/61d44b354c9dc511ffe79635b591f18b572e2fdc/odoo/fields.py#L5334.

2025-04-11 15:29 UTC, rco-odoo commented on odoo/orm/fields_properties.py
> +            definition = self.record.get_property_definition(f"{self.field.name}.{property_name}")
Let's consider your "fallback" approach and use an expression like
```
record.properties['aaa'].company_id.name
```
Consider that `record` has no definition for `'aaa'`.  First, it means that the template makes no sense for `record`.  But anyway, consider that in the table of the corresponding definition records, you have two definitions for `'aaa'`:
```
{'name': 'aaa',
 'string': 'Partner',
 'type': 'many2one',
 'comodel': 'res.partner'},
{'name': 'aaa',
 'string': 'Partner',
 'type': 'many2one',
 'comodel': 'res.company'}
```
You cannot randomly pick one of those definitions, like `get_property_definition()` does.  That would crash randomly.

Now consider your solution with `NoneProperty` and the expression
```
record.properties['aaa'].kompany_id.name
```
At least it does not crash.  Well, kind of.  If you test your template with a record that has no definition for `'aaa'`, things will go fine, because the `NoneProperty` will make it work.  Now run it on a record that defines `'aaa'`, but the corresponding record has no field `kompany_id`.  That one will crash :face_with_diagonal_mouth:

2025-04-14 10:45 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-04-14 13:38 UTC, closed without merging