[FIX] account: right calculation amount to check
odoo/odoo pull request #189832
Opened 2024-12-06 08:11 UTC by jaeschwa

Steps to reproduce:
------------------

- Create a new journal
- Change the currency for another one than the company one
- To check amount is in the company currency

Issue:
-----

The calculation of the amount to check differed from the logic of the other amounts. The to check amount was calculated based on the amount_total_signed which is by default in the company currency.

Fix:
---

Created a new dict that follows the logic of the right calculated amount (to pay, late, ...). Now the to_check_vals is a dict of the same kind as others. This allows to use the function _count_results_and_sum_amounts. Since there are no to_check_vals for each journal, used a get with a False default return.

opw-4349684

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-06 08:11 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/189832.png)](https://mergebot.odoo.com/odoo/odoo/pull/189832)

2025-01-09 14:02 UTC, yosa-odoo requested changes
Hello,

Thanks for the fix !

I tried the flow, and it seems to achieve what you want but it's not totally fixed:

Two journals for the bills, one in $ (company currency) the other one in €

I create one bill in $ with the first journal to check
I create with the second journal: two bills in € and one in $, all to check

In the dashboard, 0 bill is tagged `to check` in the first journal and in the second there 4 bills `to check`
(see illustrations below)

Could you correct the fix to make sure it is consistent, adapt/create the test and check the minor remarks I made ?

Thanks!

(I'll be on holiday next week, you can wait for my return or ask any other persons in the scope accounting if it's urgent) 

![image](https://github.com/user-attachments/assets/ff6c529a-0135-4bbe-a220-75ff546e0314)
![image](https://github.com/user-attachments/assets/32155b6d-b78f-471e-b3b9-3e373b6712a7)

2025-01-14 12:38 UTC, jaeschwa commented
Hello @yosa-odoo, I applied the changes you mentioned :)

2025-01-21 15:15 UTC, yosa-odoo approved these changes
Thanks for the changes! Just the final remarks to be done for the accounting reviewer. Whenever it is done, you can put the PR as ready :)

2025-01-22 09:29 UTC, jaeschwa commented on addons/account/tests/test_account_journal_dashboard.py
> +        self.assertEqual(dashboard_data['number_to_check'], 2)
Hello @yosa-odoo is it what you expected? Thanks a lot for your feedbacks

2025-01-28 16:23 UTC, h4818 requested changes
Thanks for the PR
After discussing with the @chklop both the Misc and Sales/Purchase Journals should display all amounts in company currency
Also, please check older versions
(bank journals are the only exception)

2025-01-29 08:46 UTC, jaeschwa commented
> Thanks for the PR After discussing with the @chklop both the Misc and Sales/Purchase Journals should display all amounts in company currency Also, please check older versions (bank journals are the only exception)

Thanks for your quick feedback, my choice of the amount to check was based on the decision of WAN, but surely can be changed, however what do you mean by check older versions?

2025-01-29 08:53 UTC, h4818 commented
> what do you mean by check older versions?

IIANM I saw the same behaviour on 17.0, please target the earliest branch where this issue occurs on both sales/purchase and misc journals

2025-01-30 08:38 UTC, jaeschwa commented
Hello @h4818 , thanks again for your help and review, I applied the changes you mentioned.

2025-02-06 10:33 UTC, yosa-odoo commented
Hello @h4818 

Julien has left the company. It appears that he implemented the changes you suggested. Could you confirm if the PR is now good to go?

2025-02-06 15:14 UTC, h4818 reviewed
@yosa-odoo it's a big diff, for nothing really, no?

2025-02-06 15:14 UTC, h4818 commented on addons/account/tests/test_account_journal_dashboard.py
> +            [            1,       100,              1,          55,            1,      55, company_currency],
the docstring for this test is no longer accurate

2025-02-06 15:14 UTC, h4818 commented on addons/account/models/account_journal_dashboard.py
> +            } for journal, currency, company, amount_total_company, amount_total, count in self.env['account.move']._read_group(
This diff is no longer necessary, right? amount_total_signed is adequate

2025-03-26 12:27 UTC, yosa-odoo commented
https://github.com/odoo/odoo/pull/203475

2025-03-26 12:27 UTC, closed without merging