[FIX] account: x2many button on payment view
odoo/odoo pull request #190039
Opened 2024-12-09 10:16 UTC by guva-odoo

In the payment view, he `x2many_buttons` widget on `duplicate_payment_ids`
calls the `action_open_business_doc`, but this method is not implemented
on `account.payment`. This was not not a problem before 01b87f1230beac0568f4e3b1b76e547909506892
since a payment was always linked to a move, therefore we were calling
the method from `account.move`.

With this commit, we implement the `action_open_business_doc` in
`account.payment`.

Step:

- Create a payment and confirm
- Duplicate it
- Click on the 'Same payment' hyperlink
-> Error: "The method 'action_open_business_doc' does not exist on the
   model 'account.payment'"

opw-4363907

2024-12-09 10:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190039.png)](https://mergebot.odoo.com/odoo/odoo/pull/190039)

2024-12-10 15:55 UTC, alialfie requested changes
Thanks for the fix! I left two comments and your commit description has one small typo: "he" instead of "the" :)

2024-12-10 15:55 UTC, alialfie commented on addons/account/models/account_payment.py
> +            'view_mode': 'form',
```suggestion
```
Not needed

2024-12-10 15:55 UTC, alialfie commented on addons/account/models/account_payment.py
> +            'target': 'current',
```suggestion
```
Default is current according to [this](https://www.odoo.com/documentation/16.0/developer/reference/backend/actions.html?highlight=view_mode#window-actions-ir-actions-act-window)

2024-12-11 10:13 UTC, alialfie requested changes
Code LGTM, don't forget the typo in the commit message too please :)

2024-12-11 11:29 UTC, alialfie approved these changes
Thanks! A final review will soon follow :)

2024-12-13 10:17 UTC, gawa-odoo reviewed
@robodoo r+

2024-12-13 12:37 UTC, closed without merging