[IMP] website_sale: attribute filters revamp
odoo/odoo pull request #190049
Opened 2024-12-09 11:39 UTC by shrm-odoo

Post this commit:
- Store selected attribute values in the session, allowing them to be restored 
  when navigating from the product form back to the /shop page.
- Filters will now only display attribute values that match the available
  products within the current category or shop page.
- Automatic collapse of filter sections when there are four or more attributes
  in the filter.
- Add a 'View More' functionality for checkbox and radio filters:
  display up to 12 filter values, with additional values accessible through
  a popup.
- Correctly manage the display of pills type attributes.

task-4244913

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-09 11:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190049.png)](https://mergebot.odoo.com/odoo/odoo/pull/190049)

2025-01-29 11:47 UTC, livaios requested changes
Hello @shrm-odoo :wave: 
I added a few comments on your code but since they will result in changing the in many places I will continue reviewing after you're done with the changes
Have a nice day :slightly_smiling_face:

2025-01-30 13:01 UTC, livaios requested changes
I left some comments, I will continue the review once those are done :)

2025-01-31 05:14 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                <div t-attf-id="o_products_attributes_{{a.id}}">
Previously, the class attribute was added via xpath; now, t-attf-class is used instead. Therefore, the empty class attribute was removed. I will revert the change.

2025-01-31 05:30 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                                <option
Apologies🙏

2025-01-31 11:01 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                                    />
We need to display a maximum of 8 visible values, prioritizing checked values. If the number of checked values is fewer than 8, the remaining slots are filled with unchecked values to ensure a total of up to 8 visible values.

2025-01-31 12:39 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                                    />
I have discussed this with BOJE, will implement this for more than 20 values also

2025-02-07 10:03 UTC, livaios requested changes
Good work overall I see you cleaned up the variables a bit and reduced the variables to just `sorted_values` nice intuition :+1: 
Just a few nitpicking comments and clarification on the spec

2025-02-07 10:15 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                                            (a.name, len(a.value_ids))"
@Jean-boje told to move it to the placeholder instead of positioning it next to the arrow.

2025-02-07 10:21 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                                            View More
Previously, when I discussed this with BOJE, he suggested displaying 'View More' and 'View Less'. I will discuss it again and make the necessary updates accordingly.

2025-02-07 13:36 UTC, livaios approved these changes
LGTM :+1: 
Good work @shrm-odoo !

2025-04-01 17:13 UTC, chevalierv requested changes
Hello @shrm-odoo 

I see that you have conflicts, can you rebase your PR? I'll check the PR ASAP after :)

Have a nice day!

2025-04-01 17:13 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                    />
I'm not quite sure that is working at the moment, I've tested it can I seems like the attributes are not collapsed when I open the page, can you quickly check this and tell me if I'm testing it wrongly ?

2025-04-01 17:23 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                    />
Indeed you're right I tested with values 🤦‍♂️ Thanks for the heads up!

2025-04-02 16:28 UTC, chevalierv requested changes
Hello @shrm-odoo 

Thanks for rebasing, Good job on this! 

And thanks @livaios for the review

Have a nice day!

2025-04-02 16:28 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                                            </t>
Please factorize `o_wsale_offcanvas` and `products_attributes`, IMO it doesn't make sense to duplicate this much code ^^

2025-04-02 16:28 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                                    <a t-att-href="keep(category=0, tags=0)">
Why did you change this? I can't find in the specification. This task already address this kind of issue: https://www.odoo.com/odoo/project/4106/tasks/4262785

2025-04-02 16:28 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                                        t-att-href="keep('/shop/category/%s' % slug(category), category=0, tags=0)"
same

2025-04-02 16:28 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                                        t-att-href="keep(category=0, tags=0)"
same

2025-04-02 16:28 UTC, chevalierv commented on addons/website_sale/static/src/js/website_sale.js
> +    _onToggleViewMore(ev) {
nitpicking: So it's easier to understand what to expect from the function :)
```suggestion
    _onToggleViewMoreLabel(ev) {
```

2025-04-03 09:42 UTC, shrm-odoo commented on addons/website_sale/views/templates.xml
> +                                    <a t-att-href="keep(category=0, tags=0)">
The specification "Store attribute selection in the session" is intended to ensure that attribute selections are retained in the session. This allows users to navigate using breadcrumbs while preserving their selected attributes.

2025-04-16 15:06 UTC, chevalierv requested changes
Hello @shrm-odoo 

Sorry for the delay! I'm now focusing completely on this task.

Good job on the factorisation but I feel like we could go a bit further. See my comments about that.

Have a nice day!

2025-04-16 15:06 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +    <template id="o_wsale_offcanvas_select_attribute" name="Select type attribute in Filter">
Try to find a more suitable name (This applies to other templates you added too)
```suggestion
    <template id="website_sale.filter_select_attributes" name="Select attributes in Filter">
```

2025-04-16 15:06 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                    />
This is not applied in offcanvas and I think the offcanvas could benefit from the `t-cache` also. Isn't it possible to factorise the form and its content (or at the very least only the content)?

2025-04-17 16:11 UTC, chevalierv requested changes
Hello @shrm-odoo 

LGTM globally expect for the small nitpicking comment. Please fix the issue on runabout :)

Have a nice day!

2025-04-18 14:15 UTC, chevalierv approved these changes
Hello 

LGTM 👍 

robodoo r+

Have a nice day!

2025-04-19 09:26 UTC, closed without merging

2025-06-03 14:07 UTC, ltinel commented
I've got a few questions regarding this PR:
- Is it backward-compatible? I.e. will URLs using the `attribute_value` query param (instead of `attribute_values` (plural)) still work? If not, we should probably do something about it, e.g. set up a redirect, so that bookmarks, shared links, etc. still work.
- Storing the attribute values in the session is a bit weird IMO, especially since they're only cleared by clearing the filters on the shop page. If you just navigate away instead of clearing the filters, then the attribute values will remain in the session. This can lead to strange results if you navigate to a product page without going through the shop page first, and then use the breadcrumbs.

@Jean-boje @chevalierv FYI