base: cron job soft limit
odoo/odoo pull request #190038
Opened 2024-12-09 10:04 UTC by kmagusiak

Description of the issue/feature this PR addresses:
Add a configuration for a soft time limit for cron execution.

Current behavior before PR:
When there is many jobs to be executed, we may reach a hard time limit and the process is killed.

Desired behavior after PR is merged:
Allow to specify a soft limit to give the registry a chance to stop gracefully before reaching the hard limit.
This allows to distinguish very long running jobs (bad practice) from a lot of short ones.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-09 10:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190038.png)](https://mergebot.odoo.com/odoo/odoo/pull/190038)

2024-12-09 11:24 UTC, HydrionBurst approved these changes
LGTM

2024-12-09 11:24 UTC, HydrionBurst commented on odoo/addons/base/models/ir_cron.py
> +                        return
since we can know already processed jobs, can we log their id or even maybe their processing time in case we want to know which one is the slow cron

2024-12-09 11:41 UTC, kmagusiak commented on odoo/addons/base/models/ir_cron.py
> +                        return
That could e done in debug, otherwise logging executions will create a log of logs (since jobs are supposed to be small). This can certainly be improved in the future. Actually, I was thinking about having a table with a row per task - I need to do a POC first.

2024-12-10 08:13 UTC, nim-odoo reviewed
Thank you for the suggestion.

I'm not sure we would use this feature on the SaaS. By defining a `limit_time_real_cron`, we want to allow a DB to make the most of it, which can be achieved by properly defining a cron progress mechanism for each cron. If we want to make the most of the time allowed, we must make sure that:
- all crons are using the progress mechanism
- a progress is recorded at most every X seconds.

Something like:
```
if records_processed > N or (time.now() - last_progress_time > X):
    record_progress()
    last_progress_time = time.now()
```

This way you would have an adaptative progress ensuring you would lose at most X seconds in case of timeout (except if a single record processing takes more than X seconds, obviously).
It makes the crons much more aware of their progress at the expense of some progress boilerplate, but IMHO it's the best way to use the allocated duration.

EDIT: I'm aware that reviewing all crons to adapt them to the ir_cron_progress mechanism is a tedious task, but it has to be done once.

2024-12-24 12:27 UTC, nim-odoo requested changes
I don't think there is a need for this extra parameter as long as all crons have not been converted to the usage of the cron progress.
Once they are all converted and can be tuned with a specific `batch_size`, we will have a better view if a global soft limit is useful.

2024-12-27 17:20 UTC, kmagusiak commented
Closing for now. It will be part of a bigger task-4433571 to improve fairness in the scheduler.
As of today, the spec is in progress.

2024-12-27 17:20 UTC, closed without merging

2024-12-30 10:29 UTC, Julien00859 commented on odoo/service/server.py
> +            target = functools.partial(self.cron_thread, i)
```py
Thread(target=self.cron_thread, args=(i,), ...)```