[FIX] website_customer: fix missing CSS class for tags
odoo/odoo pull request #190175
Opened 2024-12-10 09:46 UTC by SergeBayet

The website_customer module introduced tags for sorting/filtering customers on the website in [1]. However, the default tag class was incorrectly set to bg-default, which is not defined in Bootstrap CSS. This commit resolves the issue by correcting the class assignment.

[1]: https://github.com/odoo/odoo/commit/e5ac65de59f45f2d15ae6f6b840b02cac78afd03

opw-4342343

2024-12-11 07:50 UTC, SergeBayet commented
No forward port needed for this one. The issue is only in 16.0

2024-12-13 10:56 UTC, xO-Tx requested changes
@SergeBayet Hmmm... There is no need for this (`t-if="False"`) part of the diff, right ?

2024-12-13 11:10 UTC, SergeBayet commented
> @SergeBayet Hmmm... There is no need for this (`t-if="False"`) part of the diff, right ?

@xO-Tx It's a trick to avoid a 'false' xpath in stable. In master I'll remove it.

2024-12-16 10:04 UTC, xO-Tx commented
@qsm-odoo can i get a `delegate` for this one Thanks :+1:

2024-12-16 15:00 UTC, qsm-odoo commented
@robodoo delegate=xO-Tx 
@xO-Tx 

cc @SergeBayet Instead of duplicating the whole node with the `t-if="False"` trick (which should be used sparingly), would it not work to just *add* the `text-bg-...` class **alongside** the `bg-...` class? I think the `text-bg-...` would get priority. And then in master, you could remove the bg- version.

2024-12-16 15:09 UTC, SergeBayet commented
> cc @SergeBayet Instead of duplicating the whole node with the `t-if="False"` trick (which should be used sparingly), would it not work to just _add_ the `text-bg-...` class **alongside** the `bg-...` class? I think the `text-bg-...` would get priority. And then in master, you could remove the bg- version.

@qsm-odoo 
I can try it that way indeed. But FYI there is no FW-port for this one. The problem is solved in the next version.

2024-12-16 16:03 UTC, robodoo commented
Forward-port disabled (via limit).

2024-12-16 17:52 UTC, xO-Tx commented
@robodoo r+

2024-12-16 19:04 UTC, closed without merging