[FIX] l10n_vn: Refactor to use company_ids (Many2many) instead of company_id
odoo/odoo pull request #190187
Opened 2024-12-10 10:34 UTC by bda-odoo

- Accounts no longer belong to a single company: we replace `company_id` by `company_ids`, which indicates which companies the account belongs to.

[Reference](https://github.com/odoo/odoo/commit/854c3b27aa5476c208572f19e64f8f3364bfc381#diff-19ef5a530c506fdee93fe0d113e61946b87fae7dd2d360558da69c0014f766b2R102)

```python
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1306, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 475, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 231, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/18.0/addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py", line 27, in migrate
    _fix_accounts_type(env)
  File "/home/odoo/src/odoo/18.0/addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py", line 21, in _fix_accounts_type
    accounts = env['account.account'].search(expression.OR(domains_per_company))
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1717, in search
    return self.search_fetch(domain, [], offset=offset, limit=limit, order=order)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1741, in search_fetch
    query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5736, in _search
    query = self._where_calc(domain)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5487, in _where_calc
    return expression.expression(domain, self).query
  File "/home/odoo/src/odoo/18.0/odoo/osv/expression.py", line 781, in __init__
    self.expression = domain_combine_anies(domain, model)
  File "/home/odoo/src/odoo/18.0/odoo/osv/expression.py", line 599, in domain_combine_anies
    domain_any = _anyfy_leaves(domain, model)
  File "/home/odoo/src/odoo/18.0/odoo/osv/expression.py", line 374, in _anyfy_leaves
    raise ValueError(f"Invalid field {model._name}.{path[0]} in leaf {item}")
ValueError: Invalid field account.account.company_id in leaf ('company_id', '=', 1)
```
tbg-1602
upg-2387888

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-10 10:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190187.png)](https://mergebot.odoo.com/odoo/odoo/pull/190187)

2024-12-11 09:37 UTC, jjmaksoud commented on addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py
> +                [('company_ids', '=', company.id), ('account_type', '!=', correct_account_type)],
Using an array operator seems more logical with an m2m field
```suggestion
                [('company_ids', 'in', [company.id]), ('account_type', '!=', correct_account_type)],
```

2024-12-11 13:47 UTC, aj-fuentes commented
This patch looks incorrect. If the clients upgrade the module locally, still in 17.0, it will fail. The script could be adapted to use one field or the other depending on the `odoo.release` version.

2024-12-12 07:24 UTC, bda-odoo commented
> This patch looks incorrect. If the clients upgrade the module locally, still in 17.0, it will fail. The script could be adapted to use one field or the other depending on the `odoo.release` version.

@aj-fuentes Thanks for the review.I have implemented the suggested changes

2024-12-12 07:59 UTC, aj-fuentes commented on addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py
> +            if parse_version(version) > parse_version("saas~17.5"):
17.5 was a developer version, never released
```suggestion
            if parse_version(version) > parse_version("18.0"):
```

2024-12-12 08:01 UTC, aj-fuentes approved these changes

2024-12-12 08:02 UTC, aj-fuentes commented
Note: I cannot r+ in this repo.

2024-12-12 10:40 UTC, alialfie requested changes
Thanks @bda-odoo and upgrade team!
I left one small suggestion below. And could you also please change your commit message a bit? The traceback could be replaced with another statement that explains the issue. Also, the title could be a bit shorter maybe?

2024-12-12 10:40 UTC, alialfie commented on addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py
> +                company_domain = [('company_ids', 'in', [company.id]), ('account_type', '!=', correct_account_type)]
```suggestion
                company_domain = [('company_ids', 'in', company.ids), ('account_type', '!=', correct_account_type)]
```
This is usually the better way to handle this (even though it won't change much in your case). It's more future proof if later the recordset changes to contain more records.

2024-12-12 12:56 UTC, alialfie approved these changes
Great, thanks @bda-odoo!
A final review will soon follow :)

2024-12-16 15:55 UTC, FlorianGilbert approved these changes
@robodoo r+

2024-12-16 20:47 UTC, robodoo commented
@bda-odoo @FlorianGilbert staging failed: ci/runbot on 907433c9b2d4b8cb7510378fc0521a01c0ad1102 (view more at https://runbot.odoo.com/runbot/build/72053003)

2024-12-17 07:55 UTC, FlorianGilbert commented
@robodoo retry

2024-12-17 10:05 UTC, closed without merging