[IMP] l10n_in: add support for depreciation and capital accounts
odoo/odoo pull request #190209
Opened 2024-12-10 12:04 UTC by hatr-odoo

This **PR** introduces two new accounts:

1. Depreciation Account: Account type set to expense.
2. IN Company Capital: Account type set to equity.

Additionally, it corrects the account type for Bank Charges from asset_cash to expense.

**task**-4394945

2024-12-10 12:04 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190209.png)](https://mergebot.odoo.com/odoo/odoo/pull/190209)

2024-12-17 13:06 UTC, hamo-odoo requested changes
You can keep the changes in csv, you just need to change type to `equity` for Capital Account here https://github.com/odoo/odoo/pull/190209/files#diff-2ea17545217b55a338e9bcf3607ebaa03d365ea4b920990054d5996c6a12568cR23

2024-12-18 05:03 UTC, hamo-odoo approved these changes
LGTM, Ready for final review

2024-12-18 10:40 UTC, jco-odoo commented
@robodoo r+

2024-12-18 16:58 UTC, closed without merging