[FIX] pos_restaurant: prevent multiple order send
odoo/odoo pull request #190391
Opened 2024-12-11 16:06 UTC by viso-odoo

before this commit and since commit 42b207f, the pos_restaurant does not lock the state of the order button anymore. This has as an effect that if the order submitting takes a lot of time (which e.g. happens when a preparation printer is configured) the user could press the order button multiple times.

This situation can happen both intentionally or unintentionally.

The end result is a disturbed flow for users, where orders are sent multiple times in preparation and therefore need to be manually checked by the staff regularly risking wrong extra order preparation otherwise.

This commit reverts the changes adding back the state locking the order button while it's being processed.

opw-4242269

2024-12-11 16:06 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190391.png)](https://mergebot.odoo.com/odoo/odoo/pull/190391)

2025-02-20 14:07 UTC, adgu-odoo commented
This was expected to remove the loading so maybe you can keep the behavior that we had before but without the spin

2025-02-20 14:09 UTC, adgu-odoo requested changes

2025-02-20 14:09 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/overrides/components/product_screen/actionpad_widget/actionpad_widget.xml
> +                    <t t-if="!(displayCategoryCount.length > 2)">Order</t>
You can remove this diff

2025-02-20 14:09 UTC, adgu-odoo commented on addons/pos_restaurant/static/src/overrides/components/product_screen/product_screen.xml
> +                    </div>                    <!-- Replace the payment button by the order button -->
And also this diff I guess

2025-02-24 16:01 UTC, viso-odoo commented
hello @adgu-odoo thanks for the review, i applied the changes :)

2025-02-27 07:07 UTC, adgu-odoo approved these changes

2025-02-27 07:37 UTC, adgu-odoo commented
robodoo r+

2025-02-27 11:31 UTC, closed without merging