[IMP] hr_holidays: Enhancing Accessibility for Multiple Allocation Req
odoo/odoo pull request #190332
Opened 2024-12-11 10:16 UTC by amah-odoo

- remove the cogMenu button and replce it with control button

Task: 4394168

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-11 10:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190332.png)](https://mergebot.odoo.com/odoo/odoo/pull/190332)

2024-12-24 13:24 UTC, abdelrahmankhaledg reviewed
Hello Abdelrahman, thanks for your work. I've left two comments.

2025-01-16 12:16 UTC, Bertrand2 requested changes
A question + 2 nitpicking comments.
Additionally, I noticed that the buttons will also be present in the "My Time Off" and "My Allocations" menus, and though it's only accessible to time off it shouldn't be present in those views. You can remove the buttons by hiding them in the overrides `hr_leave_view_tree_my` and `hr_leave_allocation_view_tree_my`

2025-01-16 12:16 UTC, Bertrand2 commented on addons/hr_holidays/__manifest__.py
Are the changes in this file necessary?

2025-01-16 12:16 UTC, Bertrand2 commented on addons/hr_holidays/views/hr_leave_allocation_views.xml
> +                    <button type="action" name="%(hr_holidays.action_hr_leave_allocation_generate_multi_wizard)d" string="Multiple Requests" class="btn btn-secondary" groups="hr_holidays.group_hr_hol
Split in multiple lines + nitpicking on double space in front of *display*
```suggestion
                    <button type="action" name="%(hr_holidays.action_hr_leave_allocation_generate_multi_wizard)d"
                        string="Multiple Requests" class="btn btn-secondary"
                        groups="hr_holidays.group_hr_holidays_user" display="always"/>
```

2025-01-16 12:16 UTC, Bertrand2 commented on addons/hr_holidays/views/hr_leave_views.xml
> +                    <button type="action" name="%(hr_holidays.action_hr_leave_generate_multi_wizard)d" string="Multiple Requests" class="btn btn-secondary" groups="hr_holidays.group_hr_holidays_user"
same here
```suggestion
                    <button type="action" name="%(hr_holidays.action_hr_leave_generate_multi_wizard)d"
                        string="Multiple Requests" class="btn btn-secondary"
                        groups="hr_holidays.group_hr_holidays_user" display="always"/>
```

2025-01-16 12:21 UTC, amah-odoo commented on addons/hr_holidays/__manifest__.py
As the button in the view use an action from the wizard, the wizard must be presented before the view.
I moved all the wizards to keep it as one block other than that one wizard should be above one view.

2025-01-17 12:50 UTC, tivisse commented
@robodoo r+

2025-01-18 05:43 UTC, closed without merging