WIP Address
odoo/odoo pull request #190312
Opened 2024-12-11 07:03 UTC by kcv-odoo

To-Do

2024-12-11 07:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190312.png)](https://mergebot.odoo.com/odoo/odoo/pull/190312)

2025-01-03 13:08 UTC, Feyensv reviewed
Big question: can't we move most of the l10n modules addresses logic to the `l10n_latam_base` module (identification types, responsibility types and vat) ?

I believe it would allow us to simplify a lot of code (and maybe even prepare for ecommerce localizations of other countries).

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/controllers/portal.py
> +            address_sudo.is_default_delivery_address = True
We shouldn't have to update n records everytime (and it won't happen if you switch to the logic we spoke about).

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/controllers/portal.py
> +    def shop_country_info(self, country, address_type, **kw):
```suggestion
    @route(
        '/portal/address/country_info/<model("res.country"):country>',
        type='jsonrpc',
        auth="public",
        methods=['POST'],
        website=True,
        readonly=True,
    )
    def portal_address_country_info(self, country, address_type, **kw):
```

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/controllers/portal.py
> +    def address_set_as_default(self, address_id, address_type, **kw):
```suggestion
    @route('portal/address/set_default', type='jsonrpc', auth='user', website=True)
    def portal_address_set_as_default(self, address_id, address_type, **kw):
```

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/controllers/portal.py
> +    def address_archive(self, address_id, **kw):
```suggestion
    def address_archive(self, partner_id, **kw):
```

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/views/portal_templates.xml
> +            <li t-if="page_name == 'address_form'" class="breadcrumb-item">
```suggestion
            <li t-elif="page_name == 'address_form'" class="breadcrumb-item">
```

2025-01-03 13:08 UTC, Feyensv commented on addons/portal/views/portal_templates.xml
> +            <li t-if="page_name in ['my_details', 'address_form']" class="breadcrumb-item">Details</li>
```suggestion
            <li t-elif="page_name in ['my_details', 'address_form']" class="breadcrumb-item">Details</li>
```

2025-01-03 15:40 UTC, vbe-odoo commented
Hello @kcv-odoo 
Should we test the changes based on the feedback given by @fvz-odoo and @masi-odoo on this PR https://github.com/odoo-dev/odoo/pull/3817 ?

Thanks

2025-01-06 05:27 UTC, kcv-odoo commented on addons/portal/controllers/portal.py
> +        is_anonymous_customer = partner_sudo._is_anonymous_customer()
No you can't create or update addressed if not logged in
I added this hook to avoid doing some bad patches in website_sale like computing country again for form values, adding more xpath in website sale to handle anonymous customer scenario and adding more complexity in address parsing and creation :see_no_evil:

2025-01-06 05:27 UTC, kcv-odoo commented on addons/portal/views/portal_templates.xml
> +            <li t-if="page_name in ['my_details', 'address_form']" class="breadcrumb-item">Details</li>
I want to add `Details` breadcrum for address for also `Addresses/Details `so I have to keep it t-if so Addresses and Details both breadcrumb added for address_form

2025-01-06 05:40 UTC, kcv-odoo commented
Hello @vbe-odoo 

Yes you can test it in this branch but I am doing some changes given by @Feyensv and applying further refactoring in branch so it would be better if you would give it try after that. I'll ping you and other once it is completely ready for testing and review

Thank you!!

2025-01-06 09:20 UTC, kcv-odoo commented on addons/website_sale/const.py
> +]
We only need to hide b2b fields on shop/address and since we are removing website_sale related localisations I thought it would be better to define one which country E-commerce we need to always display b2b fields instead needed to keep bridge
Moving into portal even make little less sense as we probably don't want to hide b2b fields  portal/address :slightly_frowning_face:

2025-01-06 10:18 UTC, Feyensv commented on addons/website_sale/controllers/main.py
> +        if is_anonymous_customer:
Anonymous cart and anonymous customer are two different logics.
The user could be anonymous when the cart isn't.
This code only makes sense when the cart was assigned to the Public Partner, not when the current user is the public user but he already provided his address for the cart.

2025-01-06 23:23 UTC, fvz-odoo commented
Hello @kcv-odoo 

Quick question, we're currently working on the development of E-commerce for l10n_uy. It would be very helpful to have a description of the PR of what is being done here so we know if something standard is changing and to be aware in the development we're doing for other locs. In l10n_uy, the implementation for the E-commerce will be very easy, as we just need to add the type of identification field to the address form and make that field and the vat number field mandatory, other than that, nothing else has to be done. This PR does that? If not, should we think about doing it on this PR? Or should we keep working on a separate PR for UY?

Let me know so we know how to approach the E-Commerce implementation in UY.

Thanks a lot and cheers!

Fernando

@vbe-odoo @zaoral

2025-01-07 04:58 UTC, kcv-odoo commented
Hello @fvz-odoo 

As VFE suggested l10n_uy is also part of l10n_latam_base and kind of same what already done for AR, BR and other localizations so we will be doing some generic approch to add type of identification field in address form as it is same for latam countries so I guess you probably don't need add that separately

I'll add description of PR ASAP! 
What we are doing is allowing user to add multiple address from portal and manage them in portal [Task](https://www.odoo.com/odoo/my-tasks/3628329) for reference

Thank you!!

2025-01-07 19:00 UTC, fvz-odoo commented
Hello @kcv-odoo 

Perfect, thanks, in that case, is it possible to ask to make those fields mandatory (ID type and ID number) for UY? If we can do this, E-commerce for UY would work already.

Let me know if this is possible.
Thanks a lot!

Fernando

2025-01-13 06:29 UTC, chevalierv requested changes

2025-01-13 06:29 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +        </t>
Why do you need to inherit the portal template? IMO it would be better to have separate templates calling the same sub-template containing the form.

2025-01-27 16:41 UTC, Feyensv reviewed
Great work, pushed some review commits, including some little comments for you (even though I solved most of them already).  Feel free to take a look and integrate it with your commits (or tell me if I broke something, hopefully not).

I didn't know that the existing account/portal address logic was used in the point of sale, did you investigate and test that logic to make sure your changes do not break it? :eyes:

2025-01-27 16:41 UTC, Feyensv commented on addons/l10n_it_edi_website_sale/tests/test_l10n_it_edi_website_sale.py
> -        self.start_tour("/", 'shop_checkout_address')
Where are all the loca tests now? :thinking:

2025-01-27 16:41 UTC, Feyensv commented on addons/l10n_es/controllers/portal.py
> +from odoo.addons.portal.controllers.portal import CustomerPortal
You could maybe inherit from the account `PortalAccount` controller instead to have an inheritance tree following the modules dependencies ? :thinking:

2025-01-28 04:53 UTC, kcv-odoo commented on addons/l10n_it_edi_website_sale/tests/test_l10n_it_edi_website_sale.py
> -        self.start_tour("/", 'shop_checkout_address')
I moved those tests in enterprise as there are some in enterprise so we can have one module l10n_test_website_sale module to contain all the test

2025-01-28 10:25 UTC, kcv-odoo commented on addons/website_sale/views/templates.xml
> -                    <!-- FIXME KCV this is shown even when creating a new address when logged in -->
This one is coming from master probably in 18.0 also. Created ticket https://www.odoo.com/odoo/project/49/tasks/4522138

2025-01-28 11:02 UTC, Feyensv commented on addons/website_sale/models/sale_order.py
> +
Keep it in the `#TOOLING` section where it was before, to reduce the diff ;)

2025-01-28 13:19 UTC, Feyensv commented on addons/portal/views/address_templates.xml
>                                              /> Add same for <t t-out="other_address_type"/> address
`other_address_type` won't be translated here, you should duplicate the code with the two different labels

2025-01-31 05:28 UTC, kcv-odoo commented
> I didn't know that the existing account/portal address logic was used in the point of sale, did you investigate and test that logic to make sure your changes do not break it? :eyes:

There are lots of test cases related to POS screen to ensure flow to create address and invoice from Payment screen so it should be good, Also there are test cases in mx POS localisation to ensure extra fields are properly set on address and related documents generated properly.
(Only issue in test was state was not required according to old flow but in mx country state is required so had to update test case to set state)

2025-02-04 14:30 UTC, vchu-odoo requested changes
Great work, thank you!

First round, some small comments and suggestions :)

2025-02-05 06:10 UTC, kcv-odoo commented on addons/portal/models/res_partner.py
> +            if 'invoice' in adr_pref and partner.default_billing_address_id:
Yes we could do that
But I didn't do that because it would make things complex because `adr_pref`  can have different and multiple element in list and it should work same for all the others type contact to work as same as before and only overwrite invoice and delivery address if set on main contact

Like let say `self` have 3 partners one with default invoice set, second with default shipping and third does not have any set then we call that method with `adr_pref = ['invoice', 'delivery']` then we need to call super for all three partner to get missing addresses but that will also override our default ones if we call super after that :thinking:

2025-02-05 07:23 UTC, kcv-odoo commented on addons/portal/models/res_partner.py
> +        if self == self._get_current_partner(**kwargs):
:thinking: Main address is used to check if it is current user's address or there is not address add if not logged in
but here we are checking access of user that if customer can edit following address or not, So if we use `_is_main_address` here then it will bypass this check if user without any address try to change someone's address

2025-02-05 07:46 UTC, vchu-odoo commented on addons/portal/models/res_partner.py
> +            if 'invoice' in adr_pref and partner.default_billing_address_id:
Indeed, we can keep it simple.

2025-02-06 15:36 UTC, vchu-odoo reviewed
Thank you for your changes!

Some more suggestions/nitpickings.

2025-02-06 15:36 UTC, vchu-odoo commented on addons/portal/views/address_templates.xml
> +    <template id="portal.address_details" name="Address Details">
```suggestion
    <template id="portal.address_form_fields" name="Address Details">
```

2025-02-07 04:47 UTC, kcv-odoo commented on addons/portal/views/address_templates.xml
> +            <div class="o_customer_address_fill">
This selector is also used to save_address which is in address_footer

2025-02-07 04:53 UTC, kcv-odoo commented on addons/portal/views/address_templates.xml
> +                            t-if="not selected and contact.type != 'contact'"
Portal users does not have access to archive main contact of active user also it might cause other issue as in my/account we display main contact

2025-02-07 05:16 UTC, kcv-odoo commented on addons/portal/controllers/portal.py
> -    def _get_mandatory_fields(self):
Removed that code as MX already have zip required and not sure about vat but there is customisation in l10n_mx_edi_pos and l10n_mx_edi_website_sale to handle invoice generation and other flow differently

2025-02-07 07:18 UTC, vchu-odoo commented on addons/portal/views/address_templates.xml
> +                            t-if="not selected and contact.type != 'contact'"
yes, but  we can have multiple contact addresses created from backend,. Anyway, indeed it is better to remove them for backend.

2025-02-13 13:26 UTC, chevalierv approved these changes
Hello @kcv-odoo @Feyensv 

Great job on adding this feature to the portal!

Here is a few nitpicking comments about the changes in eCommerce, nothing blocking, can be done post merge 😄 

Have a nice day!

2025-02-13 13:26 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                        <div t-attf-class="oe_clear_stucture oe_cart col-12 col-lg-7">
What does this class do? I'd rather not adding a random class to the e-commerce checkout layout if not needed (this affects cart, address, checkout, payment, confirmation, etc.)
```suggestion
                        <div t-attf-class="oe_clear_structure oe_cart col-12 col-lg-7">
```

2025-02-13 13:26 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                        t-att-data-submit-url="'/shop/address/submit'"
Why not using `form.action` then?
```suggestion
```

2025-02-14 07:38 UTC, kcv-odoo commented on addons/website_sale/views/templates.xml
> +                        <div t-attf-class="oe_clear_stucture oe_cart col-12 col-lg-7">
It contains same style as `oe_cart` only needed to move in portal
(Also kept `oe_cart` also as it was used in selectors)

2025-02-14 10:05 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                        <div t-attf-class="oe_clear_stucture oe_cart col-12 col-lg-7">
Thanks for the clarification! 

Please either fully replace `oe_cart` by `oe_clear_structure` or just don't add `oe_clear_structure` then. Having two classes that does the same thing is useless. 

Also, if you choose to remove `oe_cart`, please replace selectors with a name or an id. It's best to use classes solely for styling.

2025-02-14 10:55 UTC, Feyensv commented
@robodoo r+

2025-02-14 19:10 UTC, robodoo commented
@kcv-odoo @Feyensv unable to stage: merge conflict

2025-02-17 10:53 UTC, Feyensv commented
Mhm, dunno why the security CI appears now out of nowhere, asked Antoine for an override.

@robodoo delegate+

2025-02-17 11:31 UTC, AntoineVDV commented
@robodoo override=ci/security
Same logic as before: `window.location` to a safe, server-provider URL.

2025-02-18 02:33 UTC, robodoo commented
@kcv-odoo @chevalierv staging failed: ci/upgrade_enterprise on 544c92c28aabb9e1353198e7d22314bff9e0a711 (view more at https://runbot.odoo.com/runbot/build/75217239)

2025-02-18 05:33 UTC, kcv-odoo commented
@robodoo r+

(Need to re-based the branch to update upgrade script from saas.18.2 to saas.18.3)

2025-02-18 07:54 UTC, closed without merging