[IMP] hr: fix department employees count
odoo/odoo pull request #190322
Opened 2024-12-11 09:16 UTC by amah-odoo

- edit the `_read_group` domain to include the current active companies

Task: 4353391

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-19 15:40 UTC, mepe-odoo approved these changes
LGTM :+1:

2025-01-14 11:32 UTC, Bertrand2 requested changes
Just one comment, otherwise LGTM :)
That would be nice to have a test as well! Thanks :D

2025-01-14 11:32 UTC, Bertrand2 commented on addons/hr/models/hr_department.py
> +        plans_data = self.env['mail.activity.plan']._read_group([('department_id', 'in', self.ids), ('company_id', 'in', self.env.companies.ids)], ['department_id'], ['__count'])
The plan can be set with an empty company field, those should be included as well
```suggestion
        plans_data = self.env['mail.activity.plan']._read_group([('department_id', 'in', self.ids), ('company_id', 'in', self.env.companies.ids + [False])], ['department_id'], ['__count'])
```

2025-01-15 13:49 UTC, Bertrand2 approved these changes
LGTM! Thanks for the changes :)
robodoo r+

2025-01-16 05:03 UTC, closed without merging