[IMP] base: improve contact form ui
odoo/odoo pull request #190466
Opened 2024-12-12 10:27 UTC by mrsr-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-12 10:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190466.png)](https://mergebot.odoo.com/odoo/odoo/pull/190466)

2025-01-08 13:10 UTC, spe-odoo reviewed
Hey @mrsr-odoo :boy: 

Here is the batch of changes. Have a look.

धन्यवाद

2025-01-20 10:42 UTC, reth-odoo reviewed
:wave: A few comments and you might need a rebase as the autocomplete for "street" seems to prevent updating it at all from the form at the moment :D (don't think it's related to your changes but it works fine on master runbot)

2025-01-21 11:03 UTC, mrsr-odoo reviewed
Hello @reth-odoo :slightly_smiling_face: ,  Thanks for review 

Updated the code 
Please have a look 

Thanks

2025-01-21 13:44 UTC, reth-odoo commented on odoo/addons/base/views/res_partner_views.xml
>                              <span class="o_form_label o_td_label o_address_type" name="address_name">
Would also keep the button if you can manage to fit it in somehow (or maybe below?), otherwise it'd be difficult to convert the "company name" into an actual company.

2025-01-22 12:54 UTC, mrsr-odoo reviewed
Hello @reth-odoo :wave: 
Changes are done
Please have a look
Thanks

2025-03-18 09:33 UTC, Feyensv commented on addons/product/views/res_partner_views.xml
> +                    <field name="property_product_pricelist" groups="product.group_product_pricelist"/>
I don't mind showing the field value on the child address, but it should be readonly as the value is still supposed to be configured through the commercial entity.

2025-03-18 11:22 UTC, Bertrand2 requested changes
Hello,
The change on the employee form seems unrelated to the task. Is the change intended?
Thanks!

2025-03-18 11:22 UTC, Bertrand2 commented on addons/hr/views/hr_employee_views.xml
seems unrelated, + the view seems broken now

2025-03-20 05:55 UTC, mrsr-odoo commented on addons/hr/views/hr_employee_views.xml
I think it is intended 
as PO had planned and designed it in excalidraw
ref https://app.excalidraw.com/l/65VNwvy7c4X/3m5mbgi1Ke1

2025-04-04 15:23 UTC, awa-odoo reviewed
Hello @mrsr-odoo 

Did a first read on this one as it's a target task.

Thanks for your work & cheers!

2025-04-04 15:23 UTC, awa-odoo commented on addons/web/static/src/views/fields/placeholder_image/placeholder_image_field.xml
> +        <xpath expr="//div[hasclass('position-relative')]/div" position="attributes">
We should add a hooking class in the base template instead, this is very reliant on dom structure and styling.

2025-04-04 15:23 UTC, awa-odoo commented on addons/web/static/src/views/fields/placeholder_image/placeholder_image_field.xml
> +                t-else=""
No need for so many lines, all these attributes fit on one line.

2025-04-04 15:23 UTC, awa-odoo commented on addons/web/static/src/views/fields/placeholder_image/placeholder_image_field.xml
> +    <t t-name="web.PlaceholderImageField" t-inherit="web.ImageField" t-inherit-mode="primary">
Not a fan of the "PlaceholderImageField".

If this is something we want mainly for partners / users, maybe "ContactImageField" ?

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/static/src/scss/res_partner.scss
> +.o_kanban_partner_footer_buttons a:first-child{
I always prefer when specific styling is at least included in a main class of the res_partner whole form.

Otherwise it's a bit lost.

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_company_views.xml
> +                        <field name="logo" widget='image' class="oe_avatar text-start float-none" nolabel="1" options='{"size": [100,100], "img_class": "rounded-4"}'/>
We always use double-quotes for attributes. Would invert for options.

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_company_views.xml
> +                    <field name="logo" invisible="not logo" widget="image" options="{'size': [24, 24]}" width="30" nolabel="1"/>
Does "invisible" work on list views ? I don't think so.

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                    <field name="avatar_128" invisible="not image_1920 and not is_company" widget="image" options="{'size': [24, 24]}" width="30" nolabel="1"/>
Same comment on invisible.

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                            <field name="image_1920" widget='placeholder_image' options='{"preview_image": "avatar_128", "size": [100,100], "img_class": "rounded-4"}'/>
Same comment about double-quote attributes, please re-check all.

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                                    <field id="individual" options="{'line_breaks': False}" widget="text" class="text-break d-block" name="name" default_focus="1" placeholder="e.g. Brandon Freeman" i
So those are the exact same, except for the placeholder?

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                                                <div t-if="record.email.raw_value" class="text-truncate"><i class="fa fa-fw me-1 fa-envelope text-primary" title="Email"/><field name="email"/></div>
Could use some multi-line here though (and for phone).

2025-04-04 15:23 UTC, awa-odoo commented on odoo/addons/base/views/res_partner_views.xml
> +                                <div t-if="record.phone.raw_value"><i class="fa fa-fw me-1 fa-phone text-primary" title="Phone"/><field name="phone"/></div>
Multi-line.

2025-04-07 09:16 UTC, mrsr-odoo reviewed
Hello @awa-odoo :slightly_smiling_face: ,
Thanks for the review
Update the code 
Could you please have a look ?
(not sure what is wrong with upgrade)

2025-04-16 15:03 UTC, tde-banana-odoo reviewed
Zboing, some new comments, mainly on the new fresh specs :) cheers !

2025-04-16 15:03 UTC, tde-banana-odoo commented on odoo/addons/base/models/res_partner.py
> +    def _get_stat_info(self):
Do you need that intermediate method ? Can't you just call super()._compute_application_statistics(), then append the new module stat in result.get(p.id) ?

2025-04-16 15:03 UTC, tde-banana-odoo commented on addons/web/static/src/views/fields/list_stat/contact_stat.js
> +    displayName: _t("Contact Stat"),
Maybe we could be more specific as it supports only list view, so "List Contact Statistics" ?

2025-04-16 15:03 UTC, tde-banana-odoo commented on addons/purchase/models/res_partner.py
> +            if partner.purchase_order_count:
Could use a filtered

2025-04-16 15:03 UTC, tde-banana-odoo commented on addons/point_of_sale/models/res_partner.py
> +        for partner in self:
Same here, when you have a single "'if", use a filtered instead, you gain a line and an indent level :) (to propagate to other modules)

2025-04-17 08:07 UTC, mrsr-odoo reviewed
Hello @tde-banana-odoo :wave: ,
Done with the changes
and some explanation to question
Correct me If I am overlooking 
Thanks

2025-04-17 08:30 UTC, awa-odoo commented on odoo/addons/base/models/res_partner.py
> +    def _get_stat_info(self):
Dropping by for a quick comment but feel free to ignore if not practical / no time.
Was thinking about this yesterday evening and wondering if we need a JSON field in the model at all.

Isn't it possible to have a `<widget>` tag inside the list view, that takes a column space with a label.
And then in the widget, you'd configure a JSON dict with: the field it uses, the image it uses, and the label.

Then each additional module would patch the widget to add its field(s).
Would look something like what you have in the python, but defined in the widget instead.

As long as the matching fields are defined inside the list view, you should be able to access their value just fine through the props record data and build your list of values purely from the JS widget.

Again, not sure it's a good idea, so don't jump into it immediately, but maybe something to consider.

Good luck & cheers!

2025-04-17 10:30 UTC, tde-banana-odoo reviewed
Zboig !

2025-04-17 10:30 UTC, tde-banana-odoo commented on odoo/addons/base/models/res_partner.py
> +    def _get_stat_info(self):
It would effectively be better if we want to move "display" things in xml, but seems easier to do it in python. Would say to keep current implementation @mrsr-odoo , especially freeze is now ^^ .

2025-04-17 10:30 UTC, tde-banana-odoo commented on odoo/addons/base/models/res_partner.py
> +    def _get_stat_info(self):
> tried to keep _compute_application_statistics() but got false value when appending data to it. we need extra if checks
> 
> ```python
> #base
>     def _compute_application_statistics(self):
>         for p in self:
>             p.application_statistics = []
> 
> #calendar
>     def _compute_application_statistics(self):
>         super()._compute_application_statistics()
>         for partner in self.filtered(lambda partner: partner.meeting_count):
>             stat_info = {'iconClass': 'fa-calendar', 'value': partner.meeting_count, 'label': _('Meetings')}
>             if partner.application_statistics:
>                 partner.application_statistics += [stat_info]
>             else:
>                 partner.application_statistics = [stat_info]
> ```
> 
> Can we go with this one?

Not sure to understand: if you call super, everything is initialized with a void list, isn't it ? So you can always use ``append`` ?

2025-04-17 10:30 UTC, tde-banana-odoo commented on addons/web/static/src/views/fields/list_stat/contact_stat.js
> +registry.category("fields").add("contact_stat", contactStatField);
``contact_statistics``

2025-04-17 10:30 UTC, tde-banana-odoo commented on addons/account/models/partner.py
> +            ('partner_id', 'in', self._origin.ids),
We generally fetch commercial-entity based data, like in sale order
```
# retrieve all children partners and prefetch 'parent_id' on them
all_partners = self.with_context(active_test=False).search_fetch(
    [('id', 'child_of', self.ids)],
    ['parent_id'],
)
sale_order_groups = self.env['sale.order']._read_group(
    domain=expression.AND([self._get_sale_order_domain_count(), [('partner_id', 'in', all_partners.ids)]]),
    groupby=['partner_id'], aggregates=['__count']
)
self_ids = set(self._ids)

for partner, count in sale_order_groups:
    while partner:
        if partner.id in self_ids:
            partner.sale_order_count += count
        partner = partner.parent_id
```

2025-04-17 10:30 UTC, tde-banana-odoo commented on addons/account/models/partner.py
> +    def _get_account_stat_count(self):
Maybe ``_compute_account_move_count``, like if it was a real compute like _compute_sale_order_count or other. Even if we have no field, well voila. We could even add the field itself :D .

2025-04-17 13:05 UTC, mrsr-odoo reviewed
Hello @tde-banana-odoo :slightly_smiling_face: ,
Kept the old changes for computation as we get false
Thanks

2025-04-17 16:03 UTC, tde-banana-odoo commented on odoo/addons/base/views/res_company_views.xml
> +                        <field name="logo" widget="contact_image" class="oe_avatar text-start float-none" nolabel="1" options="{'size': [100,100], 'img_class': 'rounded-4'}"/>
You are right actually ... well, end of freeze.

2025-04-17 17:21 UTC, tde-banana-odoo commented
@mrsr-odoo Rebased and added a test (to try to merge it today). Indeed not sure why but we get False if we don't use an intermediate function... really really strange. No time to investigate so I kept the intermediate method (just renamed it :) ) .

2025-04-17 17:21 UTC, tde-banana-odoo commented
@robodoo r+ rebase-merge

2025-04-17 17:21 UTC, robodoo commented
@tde-banana-odoo you may want to rebuild or fix this PR as it has failed CI.

2025-04-17 17:22 UTC, robodoo commented
Merge method set to rebase and merge, using the PR as merge commit message.

2025-04-18 05:03 UTC, closed without merging