[ADD] l10n_dk_nemhandel: implement invoicing through Nemhandel
odoo/odoo pull request #190474
Opened 2024-12-12 11:10 UTC by gawa-odoo

Following Peppol (18.0), to send to IAP

task-3524121

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-12 11:10 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190474.png)](https://mergebot.odoo.com/odoo/odoo/pull/190474)

2024-12-12 11:15 UTC, gawa-odoo commented
@aboo-odoo @Megaaaaaa This will need probably a security check from your side (and you can check the IAP side if you wnat) :)
It's based on the code of account_peppol in 18

2025-01-15 15:13 UTC, malb-odoo reviewed
Thanks for this big Pr ! Some comments, questions and nitpickings :smile: Now i'm gonna rest because my brain is fried ahah

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/private_key.pem
> +-----BEGIN PRIVATE KEY-----
mhhh not sure we want those informations ? Or are they only for testing purposes ? same for the others files of the tools  directory

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/demo_bill
> +Z0FBQUFBQmxKVDZxTkRmMFBib0VheVp6aEZfSDVqZFdXQVd2UWVrRkRHQUZ5eXhwVFpscUo4VGtXaGFpeE1PLWZnNFJ3c2FTTExjM2dDQ0xLTzNFb3pYbFFpYnpWSlk3RlpOR0NxeXdjb19tcXRnUGlhcXFxdTl1dG9WZ1F2dUhfOFdjWjVjQmxYZ0FlVFBiVy1VY19
end of file missing btw :eyes:

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +from odoo import _, fields, modules, tools
order

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +        if not user.env['account.move'].search_count([
do we want to limit at one ?

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +    pass
kept for the sake of futur overrides ?

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +        if len(args) > 1 and 'proxy_type' in args[1]:
">1" can be removed

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/enc_key
> +HjlTVuGbHXeCBWAhlIDfR3xZcCtykbMmvRoeGLARDWN+AhOdTffFb0hR+3GkMpwCvTshTkIx4nJwdFyIx/g3OuKpGPQJLi1d/4IhwYyhhSFAuHJRWE8rm2Z++aZ4Qd69h4bQjr5ymy/icqiYZ6Atyu1EXfunZBk5LsctoTp99htyFD4EzX6IH+9sBzvb32tkdU7p4LB
end of file

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/account_move_views.xml
> +                       invisible="not nemhandel_move_state or state == 'draft' or move_type in ('in_invoice', 'in_refund')"/>
set instead of tuple ?

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/account_move_views.xml
> +                     invisible="not nemhandel_move_state or state == 'draft' or move_type in ('in_invoice', 'in_refund')">
same

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_config_settings_views.xml
> +                                <div invisible="l10n_dk_nemhandel_proxy_state  not in ('not_registered', 'in_verification')">
set

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_config_settings_views.xml
> +                                    <field name="nemhandel_contact_email" required="l10n_dk_nemhandel_proxy_state in ('sender', 'receiver')"/>
same

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_config_settings_views.xml
> +                                               nolabel="1"/>
one line here

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_config_settings_views.xml
> +                                     invisible="l10n_dk_nemhandel_proxy_state not in ('sender', 'receiver', 'rejected')">
same

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_config_settings_views.xml
> +                                         invisible="l10n_dk_nemhandel_proxy_state not in ('not_registered', 'in_verification')">
same

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_partner_views.xml
> +                        <field name="nemhandel_identifier_type" style="width:30%;"/>
can we use boostrap here and avoid using style :grimacing:

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +                    )
Could we use compute instead of onchange for maintainability onchange is pain ahah

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +        return action_dict
we can maybe use _get_records_action function ?

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +        vat = company.vat[2:] if company.vat and company.vat[:2].isalpha() else company.vat
check if we can use compact ?

2025-01-15 15:13 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration_views.xml
> +</odoo>
end of file line

2025-01-16 09:51 UTC, aboo-odoo reviewed
2 smalls comments, markup is fine thanks to the escape :smile:

2025-01-20 12:22 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_proxy_user.py
> +            ])
To discuss, but I'm not sure we can do far better by doing a `_read_group` before.
We would need to split the uuid and ids in batches then browse then write on these which would work on the batches (and not on all the moves that are in processing).
I'm not sure we gain really much by doing it before. (Maybe, but I'm not sure).

2025-01-20 13:15 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send.py
> +                wizard.company_id.l10n_dk_nemhandel_proxy_state in ['sender', 'receiver']
Even removed the 'sender' state, as it was useless (it's something that is prevented in Nemhandel while it's allowed in Peppol)

2025-01-20 13:33 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
> +    return vat
I know of `split_vat` and `fix_eu_vat_number` but they don't provide exactly that. So, I don't think there is (except from https://github.com/odoo/odoo/blob/17.0/addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py#L35 but that's not the same model, and importing it would not really bring value, especially since I intend to remove 2.01 at some point in master)

2025-01-20 13:42 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
> +                    'name': 'VAT',
We never translate it. I followed the 2.01 from Bib, but now, by checking, I see that VAT => Name = Moms / Code = 63, so I changed that.

2025-01-20 14:31 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/res_company.py
> +            raise ValidationError(error_message)
Nope, the error is caught if you're on the company (so it's not blocking).
It's blocking when you're changing it in the wizard, but there, we don't want any RedirectWarning.

2025-01-20 14:49 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/res_company.py
> +                ], limit=1)
I'm not sure it would improve things tbf. This is only triggered when your nemhandel state changes, so when you register or unregister from Nemhandel.
The code would would not really improve (as I would need to do a browse, to be able to write on the field, and writing on each company would trigger a query anyway each time).

2025-01-20 15:16 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/static/src/components/verification_code_widget/verification_code_widget.js
> +        for (let i = 0; i < 6; i++) {
To have the beautiful places to fill the code 
![image](https://github.com/user-attachments/assets/2bca6e15-4c35-4a36-b060-eb33d392785e)

(tbh I find them ugly, I will ask if we really want them)

2025-01-20 15:25 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/tools/private_key.pem
> +-----BEGIN PRIVATE KEY-----
Removed most of them (as I don't feel like the demo bill was any value (and I needed to prepare a bill for it :smile: ).
And the .pem is pretty useless, I just left it, but it's only fake info

2025-01-20 15:26 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +        if not user.env['account.move'].search_count([
removed :D

2025-01-20 15:29 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +    pass
No, just to avoid doing a real query on the SML to check if the partner really exists on Nemhandel

2025-01-20 15:31 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/views/account_move_views.xml
> +                       invisible="not nemhandel_move_state or state == 'draft' or move_type in ('in_invoice', 'in_refund')"/>
I think I can't in xml

2025-01-20 15:39 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +                    )
I don't see how. A compute that would change its own value seems weird (and a compute would proc too fast).

2025-01-20 16:08 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration_views.xml
> +                            <div class="col-2"/>
I would say yes, else it's really close to the edge of the wizard

2025-01-20 16:45 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/res_partner.py
> +        hash_participant = md5(edi_identification.lower().encode()).hexdigest()
It is a requirement, but it's not used for security purposes.
It's just a hash that is used to define which user you're looking for on the SML, . The adresses are public.
For instance http://b-c455d3a7a3dca28fffab1d784f96e3e1.iso6523-actorid-upis.edel.sml-demo.dataudveksling.dk/iso6523-actorid-upis%3A%3A0088%3A5798009811639
On Nemhandel there is no tool yet, but on Peppol, of which it is based, there is this tool to find these. For instance, there, you can see the adresses used https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?action=perform&scheme=iso6523-actorid-upis&value=9915%3Ahelger&sml=digittest

2025-01-23 13:49 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/models/res_partner.py
> +            return None
Indeed, followed peppol blindly and :smile: https://github.com/odoo/odoo/commit/b4a295132bbb50a14d7f248106fcef3026167745

2025-01-29 14:12 UTC, malb-odoo reviewed
Second swipe on the pr :partying_face:

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/tools/private_key.pem
> +-----BEGIN PRIVATE KEY-----
if it's useless then why keep it ? Needed for testing purposes ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/account_journal_dashboard_views.xml
> +                    <t t-if="record.l10n_dk_nemhandel_proxy_state.raw_value === 'receiver'">
i suppose that if the proxy_state is set then it means that the company is from DK ? or every company can send though nemhandel ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/views/res_partner_views.xml
> +                    <div class="row"
wondering if all thoses row classes could not be just d-flex but maybe you tried it already

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send.py
> +                                        "%s", names)
indent seems weird there and i suppose 5 an arbitrary number, if there is more then 5 wouldn't it be weird ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send.py
> +            if invoice_data.get('send_nemhandel'):
nitpick but possible early continue here, the function seems veryyyy long maybe we could split into multiple

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send.py
> +            lambda u: u.proxy_type == 'nemhandel')
indent weird

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send_views.xml
> +                        </b>
use bootstrap for that fw-bold

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +                return
a return in a inverse ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +        else:
else not needed

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +            ) # TODO ask olma if we do
:eyes:

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +        return True
useless ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration_views.xml
> +                        <div colspan="2" class="row mb-3" invisible="not phone_number or l10n_dk_nemhandel_proxy_state == 'in_verification'">
same maybe d-flex could be better here ?

2025-01-29 14:12 UTC, malb-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration_views.xml
> +                            <div class="col-2"/>
then why not put a padding start or something ? an empty div seems weird to me

2025-02-04 10:58 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/static/src/components/verification_code_widget/verification_code_widget.js
> +        for (let i = 0; i < 6; i++) {
Removed

2025-02-04 11:09 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/views/account_journal_dashboard_views.xml
> +                    <t t-if="record.l10n_dk_nemhandel_proxy_state.raw_value === 'receiver'">
I will hide the res_config_setting if they're not danish. (and they needed a CVR anyway to be registered)

2025-02-04 11:56 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/views/res_partner_views.xml
> +                    <div class="row"
d-flex would need other classes/style to avoid them taking all the room. So I would need to introduce paddings, force the repartition of size in another way.
I'm a bit lazy to look. But if you think it could be better, I can

2025-02-04 12:39 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/wizard/account_move_send.py
> +                                        "%s", names)
Replaced this whole field to look like other warnings (with redirection action)

2025-02-04 14:26 UTC, gawa-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration_views.xml
> +                            <div class="col-2"/>
Indeed, it was due to other classes (padding and shit). Removed them

2025-07-18 06:42 UTC, clbr-odoo requested changes
Hello, just did a first pass :wave: 

Add tests please !

There are imo big problems in the registration UX; we should decide on which one we want to use, I suggest we use the latest one from master, with some changes to support the phone validation.
But at the moment it's buggy, using deprecated features. Need a functional check as discussed @Olivier-olma, ideally discussed with @pmax-x that followed changes done in Peppol.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/account_peppol/i18n/account_peppol.pot
It's not a l10n so you don't have to.
I'm fine if you leave it tho, just be prepared for useless conflicts :laughing:

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/data/cron.xml
> +    <record id="ir_cron_nemhandel_get_new_documents" model="ir.cron">
No participant status update ? :thinking: How do you retrieve status changes from IAP ?
 
You'll also want the webhook thing in 18.3+ since I think you implemented it on IAP side.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/data/oioubl_templates.xml
SettlementPeriod seems to be part of the [classic UBL 2.1 spec](https://www.datypic.com/sc/ubl21/e-cac_SettlementPeriod.html).
Why not add it to the general definition within `account_edi_ubl_cii` ?
This way it's available for any future format/localization that will need it in the future ?

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_proxy_user.py
> +                self.company_idl10n_dk_nemhandel_proxy_state = 'not_registered'
```suggestion
                self.company_id.l10n_dk_nemhandel_proxy_state = 'not_registered'
```

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_proxy_user.py
> +    def _make_request(self, url, params=False):
In following versions, I think I merged `_call_peppol_proxy` and `_make_request` overrides, into just `_call_peppol_proxy` to be less messy.
Add a check on the proxy_type early to avoid dev mistakes.
```python
        if self.proxy_type != 'peppol':
            raise UserError(_('EDI user should be of type Peppol'))
```

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_proxy_user.py
> +                    if edi_user._nemhandel_import_invoice(attachment, partner_endpoint, content["state"], uuid):
Not available in 17.0 but note for your FW-port we have some kind of generic buttons to fetch einvoices that you could use: https://github.com/odoo/odoo/commit/3c55d68b156633707819f82928f7c67029d4331a

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_proxy_user.py
> +            ])
It's very marginal gain since we have only very few edi_user that'll be there.
It's basically like looping on companies.
Although I agree could've been done better. But then you need to fix the one in Peppol too :see_no_evil: 

Speaking about fixes ... https://github.com/odoo/odoo/commit/dc06bae451586978f0abe9a1c2d0d29bb5a995c5
I made this fix that is not present for you to make the crons actually work in real batches, to avoid cron timeout.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_journal.py
> +class AccountJournal(models.Model):
Not sure it really make sense to have that on journal instead of `edi_proxy_users` like in Peppol ?

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/res_partner.py
> +    nemhandel_identifier_type = fields.Selection(
Can't we use peppol_eas and peppol_endpoint ?
That would allow us to move the XML into `account_edi_ubl_cii` directly ? :thinking: 
[Discussed together] let's see that in master, since this XML is not what will be sent over Peppol it's fine keeping it aside.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/static/src/components/res_config_settings_buttons/res_config_settings_buttons.js
Don't do that, those shared buttons were a terrible idea. Just make a regular wizard, and regular buttons on the settings, you can have a look at what exists in recent versions.

All this JS (even if it's simple) just to avoid copying few buttons is not ok.
Do one registration wizard, and buttons to deregister on the settings.

You'll have to adapt in FW so just copy what's in master in Peppol, it's way simpler, and no FW changes needed.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/tools/demo_utils.py
> +        return self.env['ir.config_parameter'].get_param('l10n_dk_nemhandel.edi.mode') == 'demo'
If I were you; I'd avoid using the edi_mode on the proxy user, and just rely on a single system parameter, always.
Either everything is in test/demo/prod, or nothing.
I don't know why they added granularity on that, but it seems overingineering to me.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/wizard/nemhandel_registration.py
> +        mode_constraint = self.env['ir.config_parameter'].sudo().get_param('l10n_dk_nemhandel.mode_constraint')
mode_constraint is also something I completely removed in 18.0, no need to reintroduce it, it's useless.

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
> +UBL_TO_OIOUBL_TAX_CATEGORY_ID_MAPPING = {
probably cleaner if we use `_get_tax_category_code`

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
> +class AccountEdiXmlOIOUBL201(models.AbstractModel):
```suggestion
class AccountEdiXmlOIOUBL21(models.AbstractModel):
```

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
> +    _description = "OIOUBL 2.01"
```suggestion
    _description = "OIOUBL 2.1"
```

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_edi_xml_oioubl_21.py
Summoning @antoine162 If you want to double check the UBL part only :slightly_smiling_face:

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_move.py
> +            ('skipped', 'Skipped'),
```suggestion
```
That skipped state never made sense imo, I removed it later on:
https://github.com/odoo/odoo/commit/66b8413c6cddac3296d57e872cc25ba8dc1091a0#diff-14a573c641d57595927abfb4e72a786f836b6213f21eb07583efa255209be9d3R138

2025-07-18 06:42 UTC, clbr-odoo commented on addons/l10n_dk_nemhandel/models/account_move.py
> +        res = super()._need_ubl_cii_xml()
```suggestion
        res = self._need_ubl_cii_xml()
```
I guess ? :thinking:

2025-09-09 09:35 UTC, clbr-odoo commented
Replaced by https://github.com/odoo/odoo/pull/219886

2025-09-09 09:35 UTC, closed without merging