[FIX] point_of_sale: check company on tip product
odoo/odoo pull request #190700
Opened 2024-12-16 11:47 UTC by vise-odoo

**Current behavior:**
When a user opens a POS that has a tip product assigned to a different company, no products are displayed in the POS interface.

**Expected behavior:**
The user should receive an error message indicating that the assigned tip product is reserved for another company. If the default tip product is associated with a different company, products should still be listed in the POS.

**Steps to reproduce:**
1. Create a POS for a company A.
2. Create a Tip product (or, use the default tip product) reserved for company B.
3. Set the Tip product for the POS of company A.
4. Open the POS for company A.
5. No products are listed in the POS.

**Cause of the issue:**
The `get_special_products()` method returns the default tip product without verifying the company assignment, leading to incorrect behavior.

**Fix:**
- Introduced an additional check in the `get_special_products()` method to verify that the default tip product is not reserved for a different company.
- Implemented a `_check_tip_product()` method during POS configuration editing to ensure that the currently selected tip product belongs to the correct company. If it does not, an appropriate error message is displayed.

opw-4396020

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-16 11:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190700.png)](https://mergebot.odoo.com/odoo/odoo/pull/190700)

2024-12-16 14:04 UTC, pedrambiria commented
Thank you for fixing this issue. It would be better to have a more general fix for all special products. For example, we could encounter this issue with the discount product in the pos_discount module. Instead of checking only for the tip product, you can check for all special products. Additionally, instead of not returning the product in the _get_special_products function, you can filter them before adding them to load in the get_limited_products_loading function.

2024-12-19 12:51 UTC, pedrambiria commented on addons/pos_self_order/models/pos_config.py
> +        response['pos.config']['data'][0]['_pos_special_products_ids'] = self._filter_special_products().ids
Based on the logic that excludes the product, it's not needed to filter it here.

2024-12-19 12:53 UTC, pedrambiria requested changes

2024-12-19 12:53 UTC, pedrambiria commented on addons/point_of_sale/models/pos_session.py
> +        return self.env['product.product'].sudo().search_count([('available_in_pos', '=', True), ('list_price', '>=', 0), ('id', 'not in', self.env['pos.config']._filter_special_products().ids), '|',
And alse here

2024-12-19 12:53 UTC, pedrambiria commented on addons/point_of_sale/models/pos_session.py
> +        data[0]['_pos_special_products_ids'] = self.env['pos.config']._filter_special_products().ids
and here

2024-12-19 12:53 UTC, pedrambiria commented on addons/point_of_sale/models/pos_config.py
> +    def _filter_special_products(self):
So it's not needed to create a function.

2024-12-19 13:09 UTC, vise-odoo commented
@pedrambiria Understood, I removed the filtering function, leaving only the `check_special_products` method.

2024-12-19 22:03 UTC, pedrambiria commented
Sorry if my previous comment was unclear. It's important to filter `check_special_products` in `get_limited_products_loading`. This is because if you have an open session and add a company to the Tips product, for example, you won't encounter any errors, but it also won't load any products.

2024-12-20 13:52 UTC, vise-odoo commented
Yes @pedrambiria , I agree with your example. I was indeed confused by your previous message :cry:

2024-12-23 09:50 UTC, pedrambiria approved these changes
@caburj Could you please review this pr?

2025-01-02 15:26 UTC, davidmonnom reviewed
I wonder if it wouldn't be better to prevent the user from modifying the company of a special product. 

Because in this case, the user is prevented from logging in, which is very blocking.

2025-01-06 13:56 UTC, vise-odoo commented
Hi @davidmonnom ,

Thank you for your comment.
I agree that it would be better to raise a warning message when the company of a special product is modified.
However, the "special products" are not defined within the `product.product` model; rather, they are specified only within the POS configuration. This makes it challenging to determine whether a product qualifies as *special* outside of the POS environment.

Therefore, I don't see a way to implement this feature without adding more lines to modify the `product.product` model.
An immediate alternative would be to revise the current blocking message to a warning notification. This would allow users to log in and continue their work while still being informed of the potential risks associated with modifying special products.

2025-01-16 13:15 UTC, davidmonnom requested changes

2025-01-16 13:15 UTC, davidmonnom commented on addons/point_of_sale/models/pos_config.py
> +
Can you remove this check and modify this method `_get_default_tip_product`

```py
    def _get_default_tip_product(self):
        product = self.env.ref("point_of_sale.product_product_tip", raise_if_not_found=False)
        if not product or (product.sudo().company_id and product.sudo().company_id != self.env.company):
            product = self.env['product.product'].search([('default_code', '=', 'TIPS')], limit=1)
        return product
```

2025-01-16 13:15 UTC, davidmonnom commented on addons/point_of_sale/models/pos_config.py
> +        self._check_special_products()
Also remove this

2025-01-16 13:15 UTC, davidmonnom commented on addons/point_of_sale/models/pos_config.py
> +                            or product.sudo().company_id.id == self.company_id.id
```suggestion
                            or product.sudo().company_id == self.company_id
```

2025-01-16 13:15 UTC, davidmonnom commented on addons/point_of_sale/models/pos_config.py
> +                            or product.sudo().company_id.id == self.company_id.id
is not needed

2025-01-17 09:02 UTC, vise-odoo commented
Failing tests seem unrelated to the fix (Project & Hungarian localization...)

2025-01-17 09:03 UTC, vise-odoo commented
robodoo retry

2025-01-17 09:03 UTC, robodoo commented
@vise-odoo retry makes no sense when the PR is not in error.

2025-01-17 14:49 UTC, vise-odoo commented
(The above commit is the result of a rebase/force-push)

2025-01-20 11:40 UTC, davidmonnom approved these changes
@robodoo r+

2025-01-20 21:48 UTC, closed without merging