[FIX] website_sale_collect: hide 'Send to Shipper' button for 'in_store' delivery type
odoo/odoo pull request #190772
Opened 2024-12-17 05:38 UTC by aamo-odoo

This issue occurs when a delivery order is created with the ``Carrier`` set to ``Pick up in Store``. After saving and validating the order, click the ``Send to Shipper`` button.

Steps to reproduce:
---
- Install ``website_sale_collect`` module
- Create a new ``Delivery Order`` and in ``Additional Info`` select ``Carrier`` as ``Pick up in Store`` > Save and Validate
- Click on the ``Send to Shipper`` button

Traceback:
--- 
``TypeError: 'NoneType' object is not subscriptable``

This commit resolves the issue by adding an XPath to the view to hide the ``Send to Shipper`` button for orders with the delivery type set to ``in_store``.

sentry-6040319897

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-17 05:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190772.png)](https://mergebot.odoo.com/odoo/odoo/pull/190772)

2024-12-18 14:58 UTC, vchu-odoo requested changes
Thank you for your fix!

Just some small suggestions.

2024-12-18 14:58 UTC, vchu-odoo commented on addons/website_sale_collect/__manifest__.py
> +        'views/delivery_pick_up_in_store_views.xml',
Could you please rename the file?
```suggestion
        'views/stock_picking_views.xml',
```

2024-12-18 14:58 UTC, vchu-odoo commented on addons/website_sale_collect/views/delivery_pick_up_in_store_views.xml
> +    <record id="view_picking_withcarrier_out_form_inherit_puis" model="ir.ui.view">
```suggestion
    <record id="stock_picking_form" model="ir.ui.view">
```

2024-12-18 14:58 UTC, vchu-odoo commented on addons/website_sale_collect/views/delivery_pick_up_in_store_views.xml
> +        <field name="name">stock.picking.form.inherit.puis</field>
```suggestion
        <field name="name">stock.picking.form</field>
```

2024-12-19 04:59 UTC, aamo-odoo commented
Hey @vchu-odoo 

Requested changes are made.
You can now review this. 

Thanks! :)

2024-12-19 07:28 UTC, vchu-odoo approved these changes
Thank you for the changes!

LGTM :+1:

2024-12-19 09:12 UTC, AntoineVDV approved these changes
@robodoo delegate=vchu-odoo

2024-12-19 09:12 UTC, AntoineVDV commented on addons/website_sale_collect/views/stock_picking_views.xml
> +            <xpath expr="//button[@name='send_to_shipper']" position="attributes">
```suggestion
            <button name="send_to_shipper" position="attributes">
```

2024-12-19 10:46 UTC, vchu-odoo commented
@robodoo r+

2024-12-19 10:46 UTC, robodoo commented
@vchu-odoo you may want to rebuild or fix this PR as it has failed CI.

2024-12-19 10:48 UTC, aamo-odoo commented
Hey @vchu-odoo 

We need an exception from runbot team

2024-12-19 11:30 UTC, d-fence commented
Upgrade exception [#463](https://runbot.odoo.com/odoo/runbot.upgrade.exception/463?menu_id=405) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

PRs adding fields/models should be merged at the beginning of the week and all the forward ports should be merged in the same week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
view:website_sale_collect.stock_picking_form
```
cc @KangOl @nseinlet @aj-fuentes

2024-12-19 13:54 UTC, closed without merging