[IMP] base,*: use x2many kanban for server actions
odoo/odoo pull request #190709
Opened 2024-12-16 12:28 UTC by brboi

*: {test_}base_automation, mail, sms, web

This commit will make the "Multi actions" server actions form view to
present their child actions similarly to the automation rules form,
which uses an inline x2many kanban view.

In order to achieve this it has been necessary to:
- change the child_ids server actions field type from m2m to one2many
- move the whole automatic naming logic of automation rules' actions to
  the server actions themselves

Task: opw-4370092

2024-12-16 12:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190709.png)](https://mergebot.odoo.com/odoo/odoo/pull/190709)

2025-01-15 07:58 UTC, kebeclibre commented on addons/base_automation/models/ir_actions_server.py
> +        return super()._get_linkable_childs_domain_parts() + [
you don't really control the call to super, so use expression.py to write `expression.AND( super, newdomain)`

2025-01-15 07:58 UTC, kebeclibre commented on odoo/addons/base/models/ir_actions.py
> +    _order = 'sequence,id'
sequence,name,id ?

2025-01-15 07:58 UTC, kebeclibre commented on odoo/addons/base/models/ir_actions.py
> +        return [
always a good idea to use expression.py to build reliable domains

2025-01-15 07:58 UTC, kebeclibre commented on odoo/addons/base/models/ir_cron.py
> +        return self.ir_actions_server_id.action_set_automated_name()
on ir.cron ? why ?

2025-01-27 15:52 UTC, kmagusiak requested changes

2025-01-27 15:52 UTC, kmagusiak commented on odoo/addons/base/models/ir_actions.py
> +        ('multi', 'Multi Actions')], string='Type',
```suggestion
        ('multi', 'Multiple Actions')], string='Type',
```

2025-01-27 15:52 UTC, kmagusiak commented on odoo/addons/base/models/ir_actions.py
> +    child_ids = fields.One2many('ir.actions.server', 'parent_id', copy=True, domain=lambda self: f"[{', '.join(self._get_linkable_childs_domain_parts())}]",
Make it return a `Domain` or `str`. A little bit like it is done in `_description_domain` of relational fields.
```suggestion
    child_ids = fields.One2many('ir.actions.server', 'parent_id', copy=True, domain=lambda self: self._get_children_domain(),
```

2025-01-27 15:52 UTC, kmagusiak commented on odoo/addons/base/models/ir_actions.py
> +                vals['groups_id'] = parent.groups_id.ids
Shouldn't you add also an `api.constrains` for this?

2025-01-27 15:52 UTC, kmagusiak commented on addons/base_automation/models/ir_actions_server.py
> +        return super()._get_linkable_childs_domain_parts() + [
see my comment in the base module

2025-01-30 13:07 UTC, kmagusiak approved these changes

2025-01-30 13:07 UTC, kmagusiak commented on addons/base_automation/models/ir_actions_server.py
> +        ])
FYI,. you can call it like this
```suggestion
        return super()._get_children_domain() & Domain("base_automation_id", "=", False)
```

2025-02-10 10:25 UTC, kebeclibre approved these changes

2025-02-10 10:25 UTC, kebeclibre commented on addons/web/static/src/views/kanban/kanban_controller.scss
> +    &.o_kanban_full_width > .o_kanban_ungrouped {
I checked a while ago with @aab-odoo and he did not like the generic implementation of the all-width kanban cards.
Maybe he changed his mind ?

2025-02-10 10:32 UTC, aab-odoo commented on addons/web/static/src/views/kanban/kanban_controller.scss
> +    &.o_kanban_full_width > .o_kanban_ungrouped {
indeed, that's against the principles we established with the new kanban (no more magic classnames)

2025-02-11 07:52 UTC, kebeclibre commented on odoo/addons/base/models/ir_actions.py
> +            ("model_id", "=", unquote("model_id")),
I'm not familiar with the new Domain classes, but this has little chance to work.
For dynamic stuff I think strings are still necessary

right @kmagusiak ?

Moreover, unquote is in the translate.py module and doesn't seem to apply here.

2025-02-11 08:07 UTC, kebeclibre approved these changes
robodoo delegate+
modulo the domain/security thing and the kanban full width class

2025-02-14 15:02 UTC, robodoo commented
@brboi 'ci/upgrade_enterprise' failed on this reviewed PR.

2025-02-14 15:09 UTC, robodoo commented
@brboi 'ci/upgrade_enterprise' failed on this reviewed PR.

2025-02-14 15:53 UTC, robodoo commented
@brboi 'ci/upgrade_enterprise' failed on this reviewed PR.

2025-02-14 23:39 UTC, closed without merging