[FIX] mail: update follower counter when a follower is removed
odoo/odoo pull request #190728
Opened 2024-12-16 14:48 UTC by phenix-factory

Before this commit, `followersCount` was briefly desynced with the server when deleting a follower leading to "load more" being displayed in the UI (this also triggers an unwanted `message_get_followers` RPC). This commit updates the `followersCount` when a follower is removed.

Task-4404011

2024-12-16 15:03 UTC, seb-odoo commented on addons/mail/static/src/core/common/follower_model.js
> +        this.thread.followersCount -= 1;
`message_unsubscribe` (or a controller version of it) should return relevant store data instead

2024-12-17 12:15 UTC, seb-odoo commented on addons/mail/controllers/thread.py
> +        return Store(thread, [], as_thread=True, request_list=["followers"]).get_result()
There are still many extra RPC done after removing a follower.
data, messages, web_read and data again...
At least the first data (with followers and suggestedRecipients) should be replaced by this line.
I don't think messages is necessary in the flow of removing a follower.
`web_read` I would say it depends if any field in the view depends on follower, which is a bit complicated to know.
And data again (with all request params this time) I'm not sure what's the point.

2024-12-17 12:18 UTC, seb-odoo commented on addons/mail/controllers/thread.py
> +        return Store(thread, [], as_thread=True, request_list=["followers"]).get_result()
It looks like what we lack is a specific version of `onFollowerChanged` but only for when removing one, which requires less processing.

Note that ideally `this.load(thread, ["followers", "suggestedRecipients"]);` should be removed in all flows, and returned by the RPC adding/updating the followers instead, similar to what is done here for removal.

2025-01-28 15:56 UTC, alexkuhn commented on addons/mail/controllers/thread.py
> +        ).get_result()
Removing the follower and ask `request_list["followers"]` again will fetch the right counter and initial list of followers. This solves the counter and "load more", but the drawback is that the list is fresh.
This can be a problem on a record where lots of people join or leave: we cannot reliably find a edit a follower that is more than 100th one in the list when people are (un)subscribing at the same time.

Thankfully a search feature in follower menu could solve this (minor) usability issue https://www.odoo.com/odoo/project/1519/tasks/4427411, which is planned and discussion was about having it when there's the "load more" so both improvements would complete each-other nicely.

That's not a big deal for most records with dozens of followers (hundreds at most). A few records however can have 5 or 6 digits followers and these records could be challenging to manage without the search feature.

2025-01-29 10:14 UTC, phenix-factory commented on addons/mail/controllers/thread.py
> +        ).get_result()
This is just a way to correctly update the store after sub/unbscribe. I guess 100+ followers are handled properly by the Store class.

2025-02-11 12:08 UTC, seb-odoo requested changes

2025-02-11 12:08 UTC, seb-odoo commented on addons/mail/controllers/thread.py
> +        ).get_result()
Now that I think about it, why do we add these routes and return it by rpc rather than sending the data on the bus for the current user? in the existing methods.

2025-02-11 12:08 UTC, seb-odoo commented on addons/mail/static/src/chatter/web/chatter_patch.js
> -        this.load(thread, ["followers", "suggestedRecipients"]);
Removing it from here will prevent proper reload in `onClickEdit` and `onClickApply` from dialog if we don't also update the list in these respective flows.
(It looks like we have a bad test coverage.)

2025-02-11 12:38 UTC, tde-banana-odoo commented on addons/mail/controllers/thread.py
> +        ).get_result()
> Now that I think about it, why do we add these routes and return it by rpc rather than sending the data on the bus for the current user? in the existing methods.

Don't add bus code in message_(un)subscribe, they are optimized to avoid useless noise. Keep higher level methods when bus is really required.

2025-02-12 08:23 UTC, phenix-factory commented on addons/mail/static/src/chatter/web/chatter_patch.js
> -        this.load(thread, ["followers", "suggestedRecipients"]);
It look like it call /mail/data asking for everything:
![image](https://github.com/user-attachments/assets/727f4306-ed95-49d6-968c-0845f041b091)

2025-02-17 18:02 UTC, seb-odoo commented
I got this traceback when toggling "follow"/"unfollow" several times after having added another follow.
```
UncaughtPromiseError > TypeError

Uncaught Promise > thread.selfFollower is undefined

Occured on 75155775-master-all.runbot126.odoo.com on 2025-02-17 17:59:13 GMT

TypeError: thread.selfFollower is undefined
    onClickUnfollow@https://75155775-master-all.runbot126.odoo.com/web/assets/cc5a843/web.assets_web.min.js:16233:378
    mainEventHandler@https://75155775-master-all.runbot126.odoo.com/web/assets/cc5a843/web.assets_web.min.js:1408:77
    listener@https://75155775-master-all.runbot126.odoo.com/web/assets/cc5a843/web.assets_web.min.js:559:15
    
```

Also there is a badly positioned dropdown (should be closed instead?) when removing the last follower from the list:

![image](https://github.com/user-attachments/assets/191595ff-0d97-4ad7-a504-b6b8bf9d32de)

2025-02-18 15:04 UTC, seb-odoo approved these changes
@robodoo r+

2025-02-19 04:41 UTC, closed without merging