[ADD] website: regression test for sitemap language
odoo/odoo pull request #190779
Opened 2024-12-17 07:12 UTC by shsa-odoo

Ensure sitemap remains in English even when accessing the French version of a website.

Steps tested:
- Set up a website in English and French.
- Navigate to the French version (/fr).
- Access the sitemap (/sitemap.xml).

The issue was fixed in commit 809854c, but no test was written at the time. This test prevents regression for the reported bug [1].

task-3935135

2024-12-17 07:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190779.png)](https://mergebot.odoo.com/odoo/odoo/pull/190779)

2024-12-31 13:19 UTC, msh-odoo commented on addons/website_blog/tests/test_sitemap.py
> +        self.lang_fr.write({'url_code': 'fr'})
seems useless

2024-12-31 13:19 UTC, msh-odoo commented on addons/website_blog/tests/test_sitemap.py
> +        self.website.write({
Do we need this?

2025-01-01 12:20 UTC, shsa-odoo commented on addons/website_blog/tests/test_sitemap.py
> +        self.website.write({
Not exactly, since i have already did in setup, Thanks for pointing it out. :smiley:

2025-04-07 08:34 UTC, SergeBayet commented
Could you make this PR ready for review? Thanks. I'll review it when it's ready

2025-04-09 06:26 UTC, shsa-odoo commented
@SergeBayet Its ready for review now.

2025-04-14 06:42 UTC, SergeBayet requested changes
Great work. Some remarks though. Tell me if you can find a nice solution

2025-04-14 06:42 UTC, SergeBayet commented on addons/website_blog/tests/test_sitemap.py
> +        self.assertIn("/blog/travel-1/how-to-choose-the-right-hotel-3", response.text)
Could we avoid hardcoding slugs or translated slugs? You could dynamically fetch slugs from database instead. The test would be more future-proof.

2025-04-14 06:42 UTC, SergeBayet commented on addons/website_blog/tests/test_sitemap.py
> +        self.assertIn("/blog/voyager-1/vols-en-helicoptere-a-maui-2", response.text)
Same here.

2025-04-14 12:30 UTC, SergeBayet commented
@shsa-odoo Almost forgot, in the commit title, `[ADD]` is for adding new modules. Use [IMP] instead (don't forget to modify the PR title as well).

2025-04-14 12:35 UTC, shsa-odoo commented
@SergeBayet Updated, waiting for the build to be ready.

2025-04-14 13:59 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2025-04-14 14:02 UTC, SergeBayet commented
@robodoo r+

2025-04-14 14:03 UTC, SergeBayet commented
@robodoo r-

2025-04-14 14:04 UTC, SergeBayet commented
@shsa-odoo There is a mistake in the name of the module. It should be [IMP] website_blog. the website module remains untouched.

2025-04-14 16:31 UTC, shsa-odoo commented
@SergeBayet Done.

2025-04-15 06:29 UTC, SergeBayet commented
@robodoo r+

2025-04-15 07:04 UTC, SergeBayet commented
@robodoo retry

2025-04-15 07:33 UTC, robodoo commented
@shsa-odoo @SergeBayet staging failed: ci/runbot on 0c959e36f94440e0ed34cdbeba8cf9790fd80666 (view more at https://runbot.odoo.com/runbot/build/78411601)

2025-04-16 06:13 UTC, SergeBayet commented
@robodoo retry

2025-04-16 06:13 UTC, robodoo commented
@SergeBayet retry makes no sense when the PR is not in error.

2025-04-16 06:13 UTC, SergeBayet commented
@robodoo r+

2025-04-16 07:11 UTC, closed without merging