Master wsale checkout cart line layout mobile mano
odoo/odoo pull request #190720
Opened 2024-12-16 13:44 UTC by mano-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-16 13:44 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190720.png)](https://mergebot.odoo.com/odoo/odoo/pull/190720)

2025-01-29 14:22 UTC, chgo-odoo requested changes
Thanks @mano-odoo, that's a huge one 💪 

Visually speaking, it's a very nice improvement ! I left some comments, mainly about classes, I'll do another review once this first one is fixed 🙂

2025-01-30 09:03 UTC, mano-odoo commented on addons/website_sale/static/src/scss/website_sale.scss
> +            }
We need to keep this structure because we target both the `o_cart_product_image` and the `.o_image_64_max`.

2025-01-30 09:19 UTC, mano-odoo commented on addons/website_sale_loyalty/views/website_sale_templates.xml
> +                class="o_image_64_max w-100 h-100 align-content-center border rounded text-center text-500 bg-100"
You still have the border if your background matches the result of bg-100. It's an element which serves as a placeholder image, I find it acceptable to use static colors.

2025-02-04 09:43 UTC, chgo-odoo requested changes
Thanks @mano-odoo, almost there 💪 

Some small CSS comments but for the rest it's good 🙂

2025-02-04 09:43 UTC, chgo-odoo commented on addons/website_sale/static/src/scss/website_sale.scss
> +        }
Looks like we have `min-w-0` for this

2025-02-04 09:43 UTC, chgo-odoo commented on addons/website_sale/views/templates.xml
> +                    t-attf-class="o_cart_product d-flex py-4 gap-3 #{not line_last and 'border-bottom'}"
Nitpicking 😬 

```suggestion
                    t-attf-class="o_cart_product d-flex gap-3 py-4  #{not line_last and 'border-bottom'}"
```

2025-02-04 09:43 UTC, chgo-odoo commented on addons/website_sale/views/templates.xml
> +                        <ul t-if="is_combo" class="list-group list-group">
duplicated class

```suggestion
                        <ul t-if="is_combo" class="list-group">
```

2025-02-04 09:43 UTC, chgo-odoo commented on addons/website_sale/views/templates.xml
> +                        aria-label="Warning"/>
Wrong indentation 😉

2025-02-04 09:43 UTC, chgo-odoo commented on addons/website_sale/views/templates.xml
> +                                <span class="d-md-none fa fa-shopping-cart"/>
This was already there prior to your PR but let's use a `<i/>` tag ? 🥺

2025-02-06 08:53 UTC, chgo-odoo approved these changes
LGTM, thanks @mano-odoo  👍 

Just spotted this extra line here 🙂

2025-02-19 18:13 UTC, chevalierv requested changes
Hello @mano-odoo 

Good job on improving the template on mobile! It's wayyy much better now.

I've let a few comments and question about your code, feel free to reach out if you need more information.

Have a nice day!

2025-02-19 18:13 UTC, chevalierv commented on addons/website_event_sale/views/website_sale_templates.xml
>              <attribute name="t-attf-href"/>
useless now as there is no `t-attf-href` anymore on this element.
```suggestion
```

2025-02-19 18:13 UTC, chevalierv commented on addons/website_event_sale/views/website_sale_templates.xml
> +            <attribute name="t-attf-href">#{line.event_id and ('/event/%s/register' % slug(line.event_id)) or line.product_id.website_url}</attribute>
Why encapsulate the expression in `#{}`? 
```suggestion
            <attribute name="t-attf-href">line.event_id and ('/event/%s/register' % slug(line.event_id)) or line.product_id.website_url</attribute>
```

2025-02-20 09:41 UTC, chevalierv commented on addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
> +                t-if="line._is_sellable() and line.product_id.type != 'combo'"
It just come to my attention that in master, you can add a combo product to the Wishlist. Why do you remove this possibility in your PR?
```suggestion
                t-if="line._is_sellable()"
```

2025-02-20 09:58 UTC, mano-odoo commented on addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
> +                t-if="line._is_sellable() and line.product_id.type != 'combo'"
Sorry it's a mistake, I don't see any reasons why I did that so I probably messed it up during a rebase or I forgot to adapt after making some tests 🤔 Thanks for catching it!

2025-02-20 13:54 UTC, mano-odoo commented on addons/website_sale/views/templates.xml
> +                            <span t-field="product.image_128" t-options="{'widget': 'image', 'qweb_img_responsive': False, 'class': 'o_image_64_max border rounded'}"/>
It was there before, I kept what we had there is not reason, semantically it should just be the `<img>` without any containers. I'll replace by a `<t t-field>`

2025-02-20 14:02 UTC, mano-odoo commented on addons/website_sale/views/templates.xml
> +                            <span t-field="product.image_128" t-options="{'widget': 'image', 'qweb_img_responsive': False, 'class': 'o_image_64_max border rounded'}"/>
Nevermind 
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/c13468ad-28ff-419b-a3b3-368b5c4c24b3" />

I do guess we have to keep a container which is different than a img tag. For consistency we should maybe use a div since it's what we've been using for all the others

2025-02-24 09:15 UTC, Demesmaeker requested changes
Hello, looking very nice!

Small comment regarding `website_sale_loyalty`: we don't see the quantity rewarded any more. But in some cases (when there are more than one), it makes sense. If you use the "Buy X get Y" for instance.

Before:
![image](https://github.com/user-attachments/assets/21151484-7fad-455b-8e3b-47d7cddac78a)

After:
![image](https://github.com/user-attachments/assets/41cf16eb-989a-440e-81d6-24bfac4b32ef)

Have a very nice day!

2025-02-24 10:40 UTC, chevalierv commented
> Hello, looking very nice!
> 
> Small comment regarding `website_sale_loyalty`: we don't see the quantity rewarded any more. But in some cases (when there are more than one), it makes sense. If you use the "Buy X get Y" for instance.
> 
> Before: ![image](https://private-user-images.githubusercontent.com/69820391/416123987-21151484-7fad-455b-8e3b-47d7cddac78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzOTM3NDQsIm5iZiI6MTc0MDM5MzQ0NCwicGF0aCI6Ii82OTgyMDM5MS80MTYxMjM5ODctMjExNTE0ODQtN2ZhZC00NTViLThlM2ItNDdkN2NkZGFjNzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDEwMzcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjY5ZjM3OGY3OTNlYzFmZmY2ZGY1NjJjNzE5NDhjMTIzMjVkYzUzYWUwNDc0MDE0NWIxNWY3ODgxOTZmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QNLysleMjARlbJKkIR78wPqtuHeSvFLaNWfSDLU2jlE)
> 
> After: ![image](https://private-user-images.githubusercontent.com/69820391/416124174-41cf16eb-989a-440e-81d6-24bfac4b32ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzOTM3NDQsIm5iZiI6MTc0MDM5MzQ0NCwicGF0aCI6Ii82OTgyMDM5MS80MTYxMjQxNzQtNDFjZjE2ZWItOTg5YS00NDBlLTgxZDYtMjRiZmFjNGIzMmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDEwMzcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OTE2NGVjOTkzNzk2NjU5NTVlODU5YTU4NjI5NmIyM2UxY2IzMWM4OGFhOTIwYzYyYzMyMGUwMzhkY2M1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m6edidf6vbl3KukSPvRS0sKWeIoqKUfOEBjbWXaGvlk)
> 
> Have a very nice day!

Hello @Demesmaeker 

I've made the change for @Jean-boje, I'll let the two of you decide on whether to keep it or not :)

2025-03-04 14:03 UTC, mano-odoo commented
@chevalierv ready for another round of review
I left as TODO:
- Broken tour in /enterprise (see TODO VCR) in code
- Importing the assets for discount.png and event_ticket.png

*Note we will need to remove this code for the new asset instead `website_sale_loyalty/website_sale_template.xml` I will dot it when we can call the asset*
```xml
        <xpath expr="//div[hasclass('o_cart_product_image')]//div[@t-else]" position="before">
            <div
                t-elif="line.is_reward_line"
                class="o_image_64_max align-content-center w-100 h-100 border rounded bg-100 text-center text-500"
            >
                <i class="fa fa-2x fa-tags"/>
            </div>
        </xpath>
```

Since last time: 
- Changed picture size 96px on desktop; 64px on mobile with ratio corresponding to /shop page grid img ratio
- Remove borders under products
- New image for discount/appointment/event/gift_card
- Inserted the price in another container on mobile (next to title) to leave more room for description
- Quantity input & actions moved under the list on combo items
- Reintroduced the `cart_lines_link` template to wrap the content in a link conditionally (this removed the previously created upgrade PR since we repurposed the template)

2025-03-26 16:46 UTC, chevalierv commented on addons/loyalty/static/img/gift_card.png
I don't see gift card 🤔

2025-03-26 17:06 UTC, mano-odoo commented on addons/loyalty/static/img/gift_card.png
I don't know how specifically how to get a view with `o_ctx_menu_type == 'gift_ewallet'` but it's likely to be used in a similar way since they come from the same function

```py
    def get_program_templates(self):
        '''
        Returns the templates to be used for promotional programs.
        '''
        ctx_menu_type = self.env.context.get('menu_type')
        if ctx_menu_type == 'gift_ewallet':
            return {
                'gift_card': {
                    'title': _("Gift Card"),
                    'description': _("Sell Gift Cards, that allows to purchase products"),
                    'icon': 'gift_card',
                },
                'ewallet': {
                    'title': _("eWallet"),
                    'description': _("Fill in your eWallet, to pay future orders"),
                    'icon': 'ewallet',
                },
            }
        return {
            'promotion': {
                'title': _("Promotional Program"),
                'description': _("Automatic promo: 10% off on orders higher than $50"),
                'icon': 'promotional_program',
            },
            'promo_code': {
                'title': _("Promo Code"),
                'description': _("Get 10% off on some products, with a code"),
                'icon': 'promo_code',
            },
...
        }
```

2025-03-27 10:27 UTC, chevalierv commented on addons/loyalty/static/img/gift_card.png
Indeed, thanks for helping me finding the usage!

2025-03-27 11:31 UTC, chevalierv approved these changes
robodoo r+

2025-03-27 19:53 UTC, closed without merging