[FIX] web: display correctly purchase report
odoo/odoo pull request #190843
Opened 2024-12-17 12:28 UTC by jaeschwa

Steps to reproduce:
------------------
 - Go to settings
 - Change the Document Layout to folder
 - Go to purchase
 - Print a RFQ or a PO

Issue:
------

Currently the display of the folder wants the layout_document_title to fit in the upper right corner, which is not always possible especially in the purchase. This leads to the title being malformed. However this fix will also changes other apps display for this layout.

Fix:
----

The fix replace the <h2 t-out="layout_document_title"/> where it is in every other layout. This fix the issue and does not break other apps display.

opw-4380886

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-19 12:05 UTC, hubvd requested changes
The idea of the layout if specifically to have the title in that corner.

Maybe you can add some CSS to this block https://github.com/odoo/odoo/blob/6474797ee21c9547f9adb9e58bd9593870cacf6b/addons/purchase_stock/report/purchase_report_templates.xml#L41 knowing that the selector `.o_folder_adaptative_shape #informations` will only be applied for this layout.

2024-12-19 12:55 UTC, jaeschwa commented
> The idea of the layout if specifically to have the title in that corner.
> 
> Maybe you can add some CSS to this block
> 
> https://github.com/odoo/odoo/blob/6474797ee21c9547f9adb9e58bd9593870cacf6b/addons/purchase_stock/report/purchase_report_templates.xml#L41
> 
> knowing that the selector `.o_folder_adaptative_shape #informations` will only be applied for this layout.

Hello, thank you for very much for your help.
Indeed we could modify the css, but the problem lies in the corner, in the purchase order (RFQ, incoterms) there are elements there. Is this a local issue? 
![image](https://github.com/user-attachments/assets/60769298-33c8-47c4-9189-e9ebcfe2146f)
![image](https://github.com/user-attachments/assets/234057ce-7c49-4202-bc5b-0d3cb0d57ee0)

2024-12-19 13:26 UTC, jaeschwa commented
> Mmh, on my side it looks like this ![image](https://private-user-images.githubusercontent.com/48759451/397386473-fef07622-1197-4196-94ce-b5d64c04c723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTQzMjgsIm5iZiI6MTczNDYxNDAyOCwicGF0aCI6Ii80ODc1OTQ1MS8zOTczODY0NzMtZmVmMDc2MjItMTE5Ny00MTk2LTk0Y2UtYjVkNjRjMDRjNzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzMTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzM3MmQ4MGQ2ZjcxNDIzODY4YWMyOTFiOWEzYmE4MDc5NTcyYmJiYzI3ZDY0ZTU3MWFhOGVkYWIxNDAwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BkV5HpYRTBiX5gXuhaxifdu5o_5AgVWE7UyjqOB-qec)

Ok I get it there is a editor bug (studio->reports->edit sources), I will try the css thanks

2025-01-20 07:53 UTC, jaeschwa commented
Fixed in https://github.com/odoo/odoo/pull/192503

2025-01-20 07:53 UTC, closed without merging