[FIX] sale: remove draft indicator for pos down payment
odoo/odoo pull request #190892
Opened 2024-12-17 16:43 UTC by barracudapps

**Issue:**
A `(Draft)` text appears on sale orders lines when a down payment is done from the `Point of Sale` app. This text keeps appearing during the entire process, even on the invoice.
![2024-12-05_09-30](https://github.com/user-attachments/assets/ed46dbd5-c829-46b1-ae4f-000dc3222a61)

**Expected:**
A down payment made from the PoS app should not be a draft as it has been paid. The trailing text should not appear.

**Steps to reproduce:**
- Activate Sales and Point Of Sale apps;
- Ensure, in the PoS settings, the shop you will use has a down payment product setup (`Down Payment (POS)`);

![Capture d’écran 2024-12-17 à 17 39 54](https://github.com/user-attachments/assets/a0b0bb46-5147-4329-860d-9cef7a342cbd)
- Create a new `Quotation` from the `Sales` app with a product available in the PoS;
- Got to the shop view (open a session) and click on the `Quotation/Order` button;
- Select the lately created order and `Apply a down payment` with any value;
- Proceed payment with any method and navigate to backend;
- Go back to the quotation and look at the notebook.

**Cause:**
`(Draft)` text is added at the end of the down payment product's line as the `dp_state` is equal to `'draft'`.

**Fix:**
The problem has been correctly managed from saas-17.4 but needs more database fields: https://github.com/odoo/odoo/blob/0c0754b0fa9ee1f9efa20d1ae78a34df3dac5110/addons/sale/models/sale_order_line.py#L135-L145
![Capture d’écran 2024-12-17 à 16 20 29](https://github.com/user-attachments/assets/39c5c901-f8b6-4e88-8f75-22bb9817e031)

Backporting the following from saas-17.2 where the `(Draft)` text does not appear: 
https://github.com/odoo/odoo/commit/ba954604e5291ef206d58f621a815a515917d988 
https://github.com/odoo/odoo/commit/5542bfd48fad3b89e3e54c9534da2e4963a90d54
![Capture d’écran 2024-12-17 à 17 40 37](https://github.com/user-attachments/assets/9dafe93c-acf7-4a32-ab5d-32cd02d1c053)

**Result:**
![Capture d’écran 2024-12-17 à 16 21 45](https://github.com/user-attachments/assets/08ef9b7a-a6c8-4c5b-b773-06b71973a983)

opw-4380985

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-17 16:45 UTC, barracudapps commented
As the test is not implemented in saas-17.2, need to include it in the forwarding chain.

@robodoo up to saas-17.2

2024-12-17 16:45 UTC, robodoo commented
Forward-porting to 'saas-17.2'.

2024-12-18 10:36 UTC, lvsz reviewed
Bit of a big change for a small bug, but guess it's fine with it being a backport. Still need to update the .pot file though for the new translatable terms though.

> As the test is not implemented in saas-17.2, need to include it in the forwarding chain.

Unless I'm missing something, it seems like the `test_downpayment_line_name` test already exists in 17.0+ via https://github.com/odoo/odoo/pull/158094

2024-12-18 12:29 UTC, barracudapps commented
Thank you Levi, indeed, the test exists in 17.0+. Based my conclusion on the https://github.com/odoo/odoo/commit/5542bfd48fad3b89e3e54c9534da2e4963a90d54 fix only.

In the end, the feature could only modify 16.0 but I think it would be interesting to forward it to 17.0 too as a refactoring to match saas-17.2+ versions.

What do you think ?

@robodo up to 17.0

2024-12-18 16:31 UTC, lvsz commented
> In the end, the feature could only modify 16.0 but I think it would be interesting to forward it to 17.0 too as a refactoring to match saas-17.2+ versions.

Yeah, perhaps. If anything else needs fixing/adjusting, it would be easier if all versions have the same function.

By the way, you still need to export the translatable terms, here's some info if you haven't done this thing before: https://www.odoo.com/odoo/knowledge/10406

2024-12-19 12:08 UTC, lvsz requested changes
You should only update the `sale.pot` template file. Transifex handles the actual translations in the `*.po` files.

2024-12-19 14:39 UTC, lvsz reviewed
Looks good, just two minor style changes needed.

2024-12-19 14:39 UTC, lvsz commented on addons/sale/tests/test_sale_to_invoice.py
> +        dp_line.name = 'whatever'
```suggestion
        dp_line.name = "whatever"
```
Strings displayed to the user should use double quotation marks.

2024-12-19 14:39 UTC, lvsz commented on addons/sale/tests/test_sale_to_invoice.py
> +            dp_line.name, 'whatever',
```suggestion
            dp_line.name, "whatever",
```
ditto

2024-12-19 15:38 UTC, barracudapps commented
@lvsz Thank you ! Always good to know !

2024-12-19 15:45 UTC, lvsz approved these changes

2024-12-19 19:21 UTC, vava-odoo commented
> @robodo up to 17.0

@barracudapps you better ask `robodoo` :smile:

2024-12-19 19:26 UTC, barracudapps commented
@robodoo up to 17.0

2024-12-19 19:26 UTC, robodoo commented
Forward-porting to '17.0'.

2024-12-20 17:04 UTC, Feyensv commented
I'm not sure to understand why you need to backport the 'refactoring' part in your diff (the second commit) :thinking:
The test works fine without it, and there is less impact on the translated strings (the existing ones won't have to be updated).

2024-12-23 10:26 UTC, barracudapps commented
@Feyensv 
The 'refactoring' is to keep consistency between versions
For the translations, this also fixes a misspelling in `canceled` missing an `l`. Therefore, I thought that backporting the entire feature revision could be interesting

2024-12-24 10:00 UTC, Feyensv commented
In stable, each change impacts thousands of databases.
For example, until the new strings are translated again, all databases will have the english label for Down Payments, regardless of their chosen language.
Changes should be limited as much as possible in stable.  You could eventually fix the 'cancelled' issue, but I'm not even sure it really matters for stable (and there is a reason why we do most changes in master only, especially for non critical issues).
Mandatory read on the subject: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Please keep the changes as limited as possible in stable :pray:

2024-12-30 07:33 UTC, barracudapps commented
@Feyensv 
You are totally right. I fixed it a simpler way, keeping the correct fix's structure.

2025-01-02 12:27 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +            name = _("Down Payment (Draft)")
I'm not sure you understood exactly what i meant :thinking:.

Here, the translated string was `"%(line_description)s (Draft)"`, so there are changes in the .pot if you export it (and existing users will lose the translation of the label until it's translated again in Transifex, and updated inside odoo codebase).

Unless there is a bug in the existing translated strings, keep them as they are in stable.
You can add new translated strings for specific use-cases, but you shouldn't downgrade the experience of existing users.

2025-01-02 12:44 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +            name = _("Down Payment (Draft)")
Sorry, you are right, I badly checked translations.

2025-01-02 12:51 UTC, lvsz commented on addons/sale/models/sale_order_line.py
> +            name = _("Down Payment (Draft)")
> Here, the translated string was `"%(line_description)s (Draft)"`, so there are changes in the .pot if you export it (and existing users will lose the translation of the label until it's translated again in Transifex, and updated inside odoo codebase).

Just an FYI: "new" strings ought to get auto-translated by Transifex if they already have an exact match in a different versions (17.2 in this case IIRC), which is why I didn't consider the string changes to be an issue when reviewing it.

2025-01-02 12:59 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +            name = _("Down Payment (Draft)")
Good to know, translators won't have to translate it again but wouldn't we still have to wait for the weekly update of the .po files before the strings would be correctly translated ?

2025-01-02 13:18 UTC, lvsz commented on addons/sale/models/sale_order_line.py
> +            name = _("Down Payment (Draft)")
I'd assume strings changes first get pushed to Transifex before C3POdoo retrieves translation updates for the weekly `[I18N]` commit, because why wouldn't it, but not 100% sure tbh :shrug:

2025-01-17 08:59 UTC, barracudapps commented
Hello @Feyensv ,
Can you please r+ this PR if you are ok with the latest changes ?
Thank you

2025-01-23 10:06 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
>                      name = _("%(line_description)s (Canceled)", line_description=name)
`name` given as `line_description` is now undefined.
I suppose it's not tested since the runbot is green, but it'll probably raise in existing flows.

2025-01-30 14:20 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +                line.name = name
Took some time to finally test it, but in fact all this code here becomes dead after your changes.

We never get the `Down Payment (Draft)` description anymore, because down payment lines have a product_id, entering the condition on line 316, and ending with a simple `Down Payment` description.

I was curious how you were differentiating lines coming from PoS from lines that weren't coming from PoS, but you aren't, you're simply always removing the `(Draft)` and `(Cancelled)` from the SOL description.

2025-02-03 15:29 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +                line.name = name
Hello Victor,
Thank you for the review. Indeed, as the backport could not be done this way, another solution has been applied.

2025-02-06 13:28 UTC, Feyensv commented on addons/sale/tests/test_sale_to_invoice.py
> +    def test_downpayment_line_name(self):
This test doesn't cover any of your changes anymore, it could be removed from your PR and commit.
Ideally, for your fix, the test should be in `pos_sale` and mimic the flow you're fixing as much as possible.

2025-02-06 13:28 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +        if self.invoice_status == 'invoiced' and not invoice_lines:
Why the `or None` ? an empty recordset is already a falsy value.
Also, why do you need to check the `invoice_status` ? I feel like checking whether there are invoice_lines should be enough :thinking:

2025-02-06 13:28 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +from odoo.tools import float_is_zero, float_compare, float_round, format_date
`format_date` isn't used anywhere anymore.

2025-02-06 16:35 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +from odoo.tools import float_is_zero, float_compare, float_round, format_date
Indeed, my linter even displayed it.

2025-02-06 16:54 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +        if self.invoice_status == 'invoiced' and not invoice_lines:
Indeed, the `or None` can be removed.

For the conditions, these are needed as we may need to distinguish different kind of down payments.
Here under, you have the same scenario with and without the condition.
![Capture d’écran 2025-02-06 à 17 48 41](https://github.com/user-attachments/assets/08bf686d-0373-4fb6-8416-a789569d04d7)
![Capture d’écran 2025-02-06 à 17 51 36](https://github.com/user-attachments/assets/1e7b5005-b44d-4b47-b1af-6c75c513041a)

2025-02-11 07:49 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +        if self.invoice_status == 'invoiced' and not invoice_lines:
Kinda. If we remove the condition, having a classical down payment cancelled, all POS down payment will also be marked as cancelled.

2025-02-14 16:52 UTC, Feyensv reviewed
Nothing critical, little things that can probably be cleaned/removed ;)

2025-02-14 16:52 UTC, Feyensv commented on addons/pos_sale/tests/test_pos_sale_flow.py
> +from odoo.tests.common import TransactionCase
```suggestion
```

2025-02-14 16:52 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +            return 'draft'
Is it needed to move this code ?

2025-02-14 16:52 UTC, Feyensv commented on addons/sale/models/sale_order_line.py
> +
I don't think this part of the diff is needed anymore, let's remove unneeded changes.

2025-02-14 16:52 UTC, Feyensv commented on addons/pos_sale/tests/test_pos_sale_flow.py
> +        })
```suggestion
        downpayment_product = self.env['product.product'].create({
            'name': 'Down Payment',
            'available_in_pos': True,
            'type': 'service',
            'taxes_id': [],
        })
```
Don't assign a variable to `self` if only needed in the current test.

2025-02-14 16:52 UTC, Feyensv commented on addons/pos_sale/tests/test_pos_sale_flow.py
> +        downpayment_line_pos = sale_order.order_line.filtered(lambda line: self.downpayment_product.name in line.name)
```suggestion
        downpayment_line_pos = sale_order.order_line.filtered('is_downpayment')
```
Name comparison is not the most reliable way most of the time, so avoid it when possible ;).
(you could also have compared the product to the down payment product).

2025-02-17 12:28 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +
This comes from Odoo 18:
https://github.com/odoo/odoo/blob/8400e32f3727d51cf63ef5dad78254da89c558d8/addons/sale/models/sale_order_line.py#L364-L365
Indeed it is not needed but is part of the 18 version refactoring.

2025-02-17 12:29 UTC, barracudapps commented on addons/sale/models/sale_order_line.py
> +            return 'draft'
No more need indeed

2025-02-17 12:29 UTC, barracudapps commented on addons/pos_sale/tests/test_pos_sale_flow.py
> +        })
Indeed, not needed elsewhere

2025-02-24 18:01 UTC, Feyensv approved these changes
@robodoo r+

2025-02-24 20:02 UTC, closed without merging