[FIX] hr: fixed the plan smart button
odoo/odoo pull request #190938
Opened 2024-12-18 06:46 UTC by yava-odoo

In this PR,
- Set the default department for the Plans smart button.
- If there is no plan, it will open the form view.

Task-4356557

2024-12-18 06:46 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190938.png)](https://mergebot.odoo.com/odoo/odoo/pull/190938)

2024-12-25 07:14 UTC, kais-odoo requested changes

2024-12-25 07:18 UTC, yava-odoo commented on addons/hr/models/hr_department.py
> +from odoo.osv import expression
Done :+1:

2024-12-27 15:39 UTC, abdelrahmankhaledg reviewed
Hello Yash, thanks for your work. I've left one comment.

2024-12-30 12:49 UTC, yava-odoo commented on addons/hr/models/hr_department.py
> +        action['domain'] = expression.AND([ast.literal_eval(action['domain']), domain]) if 'domain' in action else domain
Hello :wave: 
Right, We should also include the plans that don't have department linked with them

2024-12-30 13:24 UTC, yava-odoo commented on addons/hr/models/hr_department.py
> +        ]
Opps :see_no_evil: 

I've fixed it :innocent:

2024-12-31 10:45 UTC, yava-odoo commented on addons/hr/models/hr_department.py
> +        ]
Done :+1:

2025-02-03 19:53 UTC, tivisse commented
@robodoo r+

2025-02-03 22:28 UTC, robodoo commented
@yava-odoo @tivisse staging failed: ci/runbot on b47d0b74595d1142eb857950a6f63b42c91ad630 (view more at https://runbot.odoo.com/runbot/build/74443264)

2025-02-04 05:29 UTC, tivisse commented
@robodoo retry

2025-02-04 06:33 UTC, closed without merging