Correct `By Employee` report in `Time Off`
odoo/odoo pull request #190947
Opened 2024-12-18 09:16 UTC by abdelrahmankhaledg

When an employee takes a leave that spans more than one month, for example from 15/10 to 13/12, the report `By Employee` will show the start month (October) and the total number of days of the leave request instead of showing each month spanned by the request and the number of days of each month.

To fix the issue, a new report `hr_leave_employee_report` is created instead of using the data of `hr_leave` directly in the report. In such a way, it is possible to customize the data shown in the reports to show the expected result.

task-4237738

2024-12-18 09:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/190947.png)](https://mergebot.odoo.com/odoo/odoo/pull/190947)

2024-12-20 09:02 UTC, Bertrand2 reviewed
Nice POC! I'm guessing the data will be aggregated differently for the report to serve its purpose, but the split seems to be done correctly :rocket: 
I left some comments, and additionaly, I'm warning that it won't be entirely exact as it is: with specific country rules (saturdays/part-time leaves in France, sandwich leaves in India,...) we're bound to have some inexact results, though it will be an issue for edge cases :slightly_smiling_face:

2025-06-24 12:43 UTC, amah-odoo requested changes
Great Job 💪🏼 
only few comments to go

2025-06-24 12:43 UTC, amah-odoo commented on addons/hr_holidays/views/hr_leave_views.xml
> +    <!-- DEPRECATED -->
I do not think we need this as we are targeting master. just remove them and add an upgrade script

2025-06-24 12:43 UTC, amah-odoo commented on addons/hr_holidays/report/hr_leave_employee_report.py
> +            })
As we try to avoid queries inside loops, I think extracting browse like this would be better for performance
```suggestion
        leave_ids = [report_record['leave_id'] for report_record in report_records] 
        leaves = self.env['hr.leave'].browse(leave_ids)
        holiday_status_id_by_leave_id = {leave.id: leave.holiday_status_id.id for leave in leaves}
        for report_record in report_records:
            # Remove the day_aligned_date_from/to as they are intermediate values for computing other values
            virtual_leave = self.env['hr.leave'].new({
                'date_from': report_record.pop('day_aligned_date_from'),
                'date_to': report_record.pop('day_aligned_date_to'),
                'employee_id': report_record['employee_id'],
                'holiday_status_id': holiday_status_id_by_leave_id[report_record['leave_id']],
            })
```

2025-06-24 12:43 UTC, amah-odoo commented on addons/hr_holidays/report/hr_leave_employee_report.py
> +        self._cr.execute(f"""
I think this should be `SQL()` instead of the `f-string`

2025-06-24 12:43 UTC, amah-odoo commented on addons/hr_holidays/report/hr_leave_employee_report.py
> +                    WHERE hl.employee_company_id {f"IN {tuple(self.env.companies.ids)}" if len(self.env.companies.ids) > 1 else f"= {self.env.companies.id}"}
if the `self.env.companies.ids` return a list that has single value in this case we could always use the `IN` operator no need for the condition

2025-06-25 11:23 UTC, closed without merging