[IMP] base_vat: Issue with RUT validation (UY)
odoo/odoo pull request #191066
Opened 2024-12-18 16:54 UTC by zaoral

- Implemented proper validation logic for Uruguayan VAT numbers (RUT).
- Now supports VAT numbers starting with '22', addressing previous validation issues.
- Corrections in l10n_uy tests due to changes in logic.

Task: 1292
adhoc-task-side: 45613

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-18 16:54 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191066.png)](https://mergebot.odoo.com/odoo/odoo/pull/191066)

2024-12-19 09:21 UTC, Megaaaaaa commented
Hello :wave:

Thank you for your PR, I'll forward it to the appropriate accounting subteam :+1:

2024-12-19 11:44 UTC, zaoral commented
Thank you @Megaaaaaa 

@fvz-odoo I have updated the PR as we discuss yesterday
If ready for you to test and git FUN test r+

Best Regards

2024-12-19 15:00 UTC, fvz-odoo commented
Hello @zaoral 

Thanks for the PR, this is working functionally. The runbot is failing though, can you please check? Otherwise, LGTM.

Cheers and thanks!

Fernando

2024-12-20 16:27 UTC, fvz-odoo commented
Hello @Megaaaaaa 

This is ready 😉. Cheers!

Fernando

@zaoral

2024-12-20 18:08 UTC, zaoral commented
Hi @fvz-odoo !
Yes indeed, i made the change but this not ping you to wait the runbot ci result.
Thank you for be alert
Hope we can have this one merged soon

Best Regards

2024-12-23 10:54 UTC, clbr-odoo requested changes

2024-12-23 10:54 UTC, clbr-odoo commented on addons/base_vat/models/res_partner.py
> +    'uy': _("'219999830019' (should be 12 digits)"),
```suggestion
    'uy': _("219999830019 (12 digits)"),
```
And you'll need to re-export the pot please.

2024-12-23 10:54 UTC, clbr-odoo commented on addons/base_vat/models/res_partner.py
> +        """  Taken from python-stdnum's master branch, as the release doesn't handle RUT numbers starting with 22.
Can you please link the code ? Maybe let's add a FIXME :slightly_smiling_face:

2024-12-23 10:54 UTC, clbr-odoo commented on addons/base_vat/tests/test_validate_ruc.py
> +        test_partner.write({"vat": "215521750017"})
```suggestion
        test_partner.vat = "215521750017"
```
[nit] Doesn't make much sense to use the write notation for a single field, I prefer the syntactic sugar.

2024-12-23 13:46 UTC, clbr-odoo commented
Note that I'll be off for two weeks, I assigned Antoine to handle the case when your changes are done :slightly_smiling_face: :wave:

2024-12-23 21:14 UTC, zaoral commented
Thank you for the review @clbr-odoo 

Hi @fvz-odoo 
I have updated the pr with the Claire suggestions and also change the warning we show to the user (because of what we walk in today's meeting that was confusion the "12 digits"

The new warming is now this one:
![message-en](https://github.com/user-attachments/assets/dd2c20b0-da0e-46ef-893f-4887a99fd5b2)

Please let me know if you agree or if you have any suggestion
Best  Regards

2024-12-26 09:34 UTC, antoine162 approved these changes
LGTM, thanks so much!
@robodoo r+

2024-12-26 10:40 UTC, closed without merging