[FIX] calendar: fix minor styling issues
odoo/odoo pull request #191056
Opened 2024-12-18 16:23 UTC by mano-odoo

Since the update of FullCalendar some styling was not properly applied.

Which leads to the following issues:
- Missing borders
- Cropped text in month views
- Double borders

task-3833841

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-18 16:23 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191056.png)](https://mergebot.odoo.com/odoo/odoo/pull/191056)

2025-01-21 13:50 UTC, anso-odoo requested changes
Hey, nice work! 

Just one comment,

And a suggestion: If it's not too tricky, we could add a `.bg-view` to the full day events row to fix the shadow being visible at the back

| Without bg-view | With bg-view |
|--------|--------|
| ![Screenshot 2025-01-21 at 14 49 23](https://github.com/user-attachments/assets/3f5e0bae-7b25-4423-bb40-a5d232b4ab21) | ![Screenshot 2025-01-21 at 14 49 41](https://github.com/user-attachments/assets/c8c470e2-b256-4740-8a3b-a64356fa79fb) | 

Thanks !

2025-01-21 13:50 UTC, anso-odoo commented on addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.xml
> +            <div class="o_event_title text-truncate text-nowrap" t-out="title"/>
Not sure this one is necessary as `text-truncate` already adds a `white-space: nowrap;`

![Screenshot 2025-01-21 at 14 40 56](https://github.com/user-attachments/assets/c928c6a9-41f3-42b5-86bd-920434dc5076)

2025-01-24 10:00 UTC, mano-odoo commented
req changes: https://github.com/odoo/odoo/compare/3a095ea8fab0b9ff89e3f860d251c87bd023ef8b..ffbbe9fc05f8b6797d076d1888ca3c0b33fb0dd6

2025-01-27 10:16 UTC, anso-odoo approved these changes
Clean, LGTM 👍

2025-01-28 07:49 UTC, rfr-odoo approved these changes
@robodoo r+

2025-01-28 09:17 UTC, closed without merging