[FIX] *: fix failed tests by voip reporting improvements.
odoo/odoo pull request #191010
Opened 2024-12-18 13:43 UTC by MohammedBasioni

This commit fixes the tests that fail due to logging/reporting improvements done in voip module in the following pr: https://github.com/odoo/enterprise/pull/75445

Task-3695951

2024-12-18 13:43 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191010.png)](https://mergebot.odoo.com/odoo/odoo/pull/191010)

2025-02-18 13:53 UTC, MohammedBasioni commented on addons/mail/tests/test_res_users.py
> +        voip_officer_group = self.env.ref("voip.group_voip_officer")
This test tries to create a new `res.users.settings` but when `VoIP` is installed, this model contains a `provider_id` field that regular users shouldn't have access to.

I agree with you that a VoIP reference shouldn't be included in the mail module; I will modify it to use `sudo`.

2025-05-08 09:58 UTC, thjo-odoo commented on addons/mail/tests/test_res_users.py
> -
Useless diff

2025-05-09 15:58 UTC, seb-odoo requested changes

2025-05-09 15:58 UTC, seb-odoo commented on addons/mail/tests/test_res_users.py
> +        settings = self.env['res.users.settings'].sudo().create({
How is creating settings impacted by a PR in voip?
Doesn't it mean there is a missing sudo in voip module instead?
From quick look I'm guessing the missing sudo is in `_get_default_voip_provider`?

2025-05-09 15:59 UTC, seb-odoo commented on addons/mail/tests/test_res_users.py
> +        settings = self.env['res.users.settings'].sudo().create({
Are users actually supposed be able to write on `voip_provider_id` or not?
The provider of their choice? Who is determining that?

Otherwise, the field should be moved somewhere else.

2025-05-12 10:13 UTC, MohammedBasioni commented on addons/mail/tests/test_res_users.py
> +        settings = self.env['res.users.settings'].sudo().create({
Thank you. As you said in `_get_default_voip_provider,` the voip module needed `sudo` to be installed. 

For your questions, no, regular users shouldn't have access to `VoIP provider`. A `VoIP Admin` should assign the provider to them. Who determines that? It's just the specs. 

Anyways, thanks for the help :))

2025-05-12 10:14 UTC, MohammedBasioni commented
PR Closed as the fix for the test is not needed anymore and can be fixed directly from the voip module.

2025-05-12 10:14 UTC, closed without merging