[FIX] sale: prevent creation of tax line
odoo/odoo pull request #191163
Opened 2024-12-19 11:56 UTC by yosa-odoo

Steps to reproduce:
[l10n_dk]
- create and confirm a sale order
- create an expense for a new employee and use a product set with reinvoice at cost and a tax with multiple repartition lines
- confirm and process the expense
- post journal entries

Issue:
Missing required fields on accountable sale order line.

Cause:
We want to reinvoice the tax line that no product on it

opw-4378714

2024-12-19 11:56 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191163.png)](https://mergebot.odoo.com/odoo/odoo/pull/191163)

2024-12-19 15:06 UTC, JulienAlardot requested changes
A test would be nice :p

2024-12-19 15:08 UTC, yosa-odoo commented
of course forgot to push it

2024-12-30 16:00 UTC, yosa-odoo commented
@JulienAlardot 

#### test added:
- :red_circle: - breaks without fix
- :green_circle: - passes with fix

#### branch rebased

2025-01-06 10:59 UTC, JulienAlardot approved these changes
LGTM @oco-odoo

2025-01-08 16:21 UTC, oco-odoo approved these changes
@robodoo r+

2025-01-09 09:47 UTC, yosa-odoo commented
robodoo retry

2025-01-09 11:28 UTC, closed without merging