[IMP] livechat: hide welcome bot message
odoo/odoo pull request #191116
Opened 2024-12-19 09:00 UTC by jayp-odoo

Current behavior before PR:

work in progress.......

Desired behavior after PR is merged:

..

task-4410808

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-19 09:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191116.png)](https://mergebot.odoo.com/odoo/odoo/pull/191116)

2025-02-10 12:16 UTC, rapr-odoo requested changes
`mail` needs to be added into PR and Commit title.

2025-02-10 12:16 UTC, rapr-odoo commented on addons/im_livechat/models/discuss_channel.py
> +            super()._post_leave_notification(p_id,member)
needs a space between two parameters.

2025-02-11 12:47 UTC, seb-odoo requested changes

2025-02-11 12:47 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_channel.py
> +        self._post_leave_notification(partner.id, member)
Always prefer working with recordset rather than id.
And don't need to give both partner and member as member itself contains more information already.

2025-02-11 12:47 UTC, seb-odoo commented on addons/mail/models/discuss/discuss_channel.py
> -        member._bus_send_store(custom_store, notification_type="discuss.channel/leave")
PR needs rebase, this notif was changed (and it shouldn't be removed, only the message_post should be overridden).

2025-02-11 12:51 UTC, seb-odoo commented
Also I believe we would like this in 18.1 if possible (and it looks like it's easily possible).

2025-02-12 07:36 UTC, jayp-odoo commented
@seb-odoo Hiii PR has been updated please have look thanks :)

2025-02-21 05:35 UTC, jayp-odoo commented
closing this PR as alternative [PR](https://github.com/odoo/odoo/pull/197583) was merged

2025-02-21 05:35 UTC, closed without merging