[IMP] orm: skip null checks for required fields
odoo/odoo pull request #191236
Opened 2024-12-19 16:33 UTC by kmagusiak

When generating SQL, skip NULL checks for required fields. We reduce the generated SQL for these cases.

task-4415011

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-19 16:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191236.png)](https://mergebot.odoo.com/odoo/odoo/pull/191236)

2025-02-10 13:43 UTC, ryv-odoo reviewed
That's a good idea.

I don't fully understand the code in loading.py. I let @HydrionBurst check that.

2025-02-10 13:43 UTC, ryv-odoo commented on odoo/orm/fields.py
> +                return SQL("%s IS NOT NULL", sql_field) if nullable else SQL("TRUE")
Is it still happened ? Because your new optimization should cover that case right or I miss something ?

2025-02-10 13:43 UTC, ryv-odoo commented on odoo/orm/fields.py
> +                can_be_null = nullable and (
`can_be_null` and `nullable` is quite confusing IMO. Maybe you can rename `can_be_null` (accept_null_value or check_null).

2025-02-10 15:52 UTC, kmagusiak commented on odoo/orm/fields.py
> +                return SQL("%s IS NOT NULL", sql_field) if nullable else SQL("TRUE")
It should not happen. But the goal here is to be generic and handle all inputs without relying on that particular optimization. I find it easier to test. It may happen if we have a field type that wouldn't get optimized and wanted to generate that code.

2025-02-10 15:54 UTC, kmagusiak commented on odoo/orm/fields.py
> +                can_be_null = nullable and (
Ok for "accept_null_value".

2025-02-11 10:24 UTC, HydrionBurst commented on odoo/modules/loading.py
> +                    models_to_check.discard(model_name)
`models_to_check` now are models which are simply loaded again after updated + custom_models if and module is updated? Am I right? Maybe we should defined it somewhere since `models_to_check` is quite vague

since `custom_models` are models not updated during the updating modules.
sementically I expect 🤔 
`models_update |= set(non_custom_model_names`
or maybe we should rename `models_update`?

2025-02-11 11:13 UTC, kmagusiak commented on odoo/orm/registry.py
> +            self._constraints_validated = False
We may. Note that we already check FKs and indexes declared on fields.

2025-02-11 11:20 UTC, kmagusiak commented on odoo/modules/loading.py
> +                    models_to_check.discard(model_name)
Custom models are updated during updating of modules (that's the root cause of the issue here). If you define a model "base" like `web` does, it will update custom models. These are not defined in that module so they should be checked afterwards. Normal models have been checked, so they can be discarded.

`models_to_check` is used in quite a few places and serves as a container that is passed into multiple functions. The variable keeps the same meaning: all models that need to be loaded again to update their definition in the DB.
I wanted to isolate just this change and we can refactor afterwards when the need arises.

2025-02-11 13:31 UTC, HydrionBurst reviewed
For `required` fields, the optimization is only activated when registry is ready.
but do we really need to support database with missing required constraints?
Are there many required fields in production database missing NOT NULL constraints?

Since, the `required` can be removed by adding a field(manual/auto) overriding the `required=False`, which is always doable from code/imported module. For database with missing constraints: why not treat them as corrupted?

---

BTW, another idea to make the `required` more explict
`required='strict'/True`: NOT NULL
`required='soft`: required for the UI, but can be NULL in database
`required=False`: can be NULL
When writing SQL for reports, developers can know better about if they should handle NULL.

During module update, if we find a NOT NULL is missing and cannot add it back. We can support the database by creating a field with `required='soft` to override the field in the registry to make sure the database is consistent with registry

2025-02-11 13:52 UTC, kmagusiak commented
@HydrionBurst I've renamed the constraint attribute to only be used by not null.
I think it would be too complex to have soft/strict constraints. Actually, `Field.required` is defined as not null in database. You can have an empty string in the UI. For UI, we will probably create a separate attribute, to separate what can be used in the python code and what is an attribute for the UI.

2025-02-11 14:05 UTC, HydrionBurst commented
> we will probably create a separate attribute, to separate what can be used in the python code and what is an attribute for the UI.

If there is a seperate attribute, I would propose we directly override the field with `required=False, required_ui=True` dynamically after check, which will make database and registry consistent. And we can optimize the SQL field by field. 

Whatever your current approach is still good to me. But we have to be careful to use `field.required`. Now I will defiene it as: try to add `NOT NULL` constraint when install/upgrade, and be `required` in UI.

2025-02-11 14:05 UTC, HydrionBurst commented on odoo/orm/registry.py
> +    def null_constraints_validated(self) -> bool:
Since `self._null_constraints_validated` is inited as `False` and can only be set to `True` in `check_null_constraints` which is very close to the end of `load_modules`, can we directly use `self._null_constraints_validated` and make it public?

2025-02-13 15:25 UTC, ryv-odoo commented on odoo/orm/registry.py
> +    def check_null_constraints(self, cr: Cursor, model_names: Iterable[str], *, log_level: int = logging.WARNING) -> None:
Minimun of API: can you remove `model_names` and log_level?

2025-02-13 15:25 UTC, ryv-odoo commented on odoo/orm/registry.py
> +        ]
```suggestion
        expected = [
            (Model, field)
            for Model in self.models.values()
            if Model._auto and not Model._abstract
            for field in Model._fields.values()
            if field.column_type and field.store and field.required
        ]
```

2025-02-13 15:25 UTC, ryv-odoo commented on odoo/orm/registry.py
> +        for Model, field in expected:
Why not inline `expected` here.

2025-02-14 15:45 UTC, rco-odoo requested changes

2025-02-14 15:45 UTC, rco-odoo commented on odoo/orm/fields.py
> +        nullable_column = not (self.required and model.env.registry.ready)
`nullable_column` is not a column.  Also, for the sake of code readability, it would explicitly introduce its inverse
```suggestion
        can_be_null = not (self.required and model.env.registry.ready)
```

2025-02-14 15:45 UTC, rco-odoo commented on odoo/orm/registry.py
> +            _schema.warning("Missing not-null constraint on %s", field)
Maybe the warning should be more explicit: "Missing not-null constraint on X.  Some SQL optimizations done by the framework are actually not correct, and search may return incorrect results..."

2025-02-14 15:50 UTC, rco-odoo commented on odoo/orm/registry.py
> +            _schema.warning("Missing not-null constraint on %s", field)
Please avoid writing complex code when possible.
```suggestion
        for Model in self.models.values():
            if Model._auto and not Model._abstract:
                for field in Model._fields.values():
                    if (
                        field.column_type and field.store and field.required
                        and (Model._table, field.name) not in existing
                    ):
                        _schema.warning("Missing not-null constraint on %s", field)
```

2025-02-14 15:52 UTC, rco-odoo commented on odoo/orm/registry.py
> +        existing = set(cr.fetchall())
I wouldn't call that `existing`, but something like `not_null_columns`.

2025-02-14 15:54 UTC, kmagusiak commented on odoo/orm/registry.py
> +            _schema.warning("Missing not-null constraint on %s", field)
Since I will add back the boolean on the constraint check, it should be sufficient.

2025-02-17 09:00 UTC, HydrionBurst approved these changes
LGTM

2025-02-17 10:47 UTC, rco-odoo commented on odoo/orm/registry.py
> +        self.can_rely_on_null_constraints = True
I think that it should be done field by field, instead of a global boolean, because:
* `field.required` indicates whether the field's _value_ can be null on real records; it corresponds to `NOT NULL` constraints only if the mapping of the field's value and a column is straightforward.
* the generated SQL represents the field's value, and not necessarily the content of a row's column.

The optimization is all about this: if we can assume that a field's value is never null, then we know that the condition `field = NULL` is always false, and that may lead to condition simplifications in SQL.  So the question is: in such conditions, can we rely on `field.required`?  The answer is yes if either the database itself guarantees it (via some constraint), or the ORM's implementation guarantees it (for stuff stored in JSON, for instance).

So not only do I agree with @HydrionBurst, but I will go even further: it's all about `field.required` and the SQL representation of the field's value.  The `NOT NULL` constraint issue is mostly an implementation detail.

2025-02-17 10:51 UTC, rco-odoo commented on odoo/orm/registry.py
> +                        _schema.error("Missing not-null constraint on %s, some optimizations may not be applied.", field)
@kmagusiak please ask our professional services to know whether we actually support such a situation or not.  Pretending that invariants are true while they aren't in practice, does not look like a good idea to me, since developers _will_ rely on those invariant to make my code as simple and efficient as possible...

2025-02-17 13:13 UTC, HydrionBurst commented on odoo/orm/domains.py
> +        and (model._table, field.name) in model.env.registry.not_null_columns
Code is OK.
Just thought of something
new added/modified manual required fields won't update `model.env.registry.not_null_columns` since they only trigger `setup_models` and `init_models` but not `check_null_constraints`

2025-02-17 13:48 UTC, kmagusiak commented on odoo/orm/registry.py
> +                        _schema.error("Missing not-null constraint on %s, some optimizations may not be applied.", field)
Done, they suggested WARNING.

2025-02-19 10:32 UTC, HydrionBurst commented on odoo/modules/loading.py
>          if models_to_check:
Another thought of something:
Maybe I can make another PR after this one
1. this code will be skipped if there are both `to upgrade` and `to remove` modules
2. `init_models` should work together with `finalize_constraints`
maybe we should move this and `# STEP 3.6: apply remaining constraints in case of an upgrade` into `# STEP 4: Finish and cleanup installations` 🤔

2025-02-19 13:50 UTC, kmagusiak commented on odoo/modules/loading.py
>          if models_to_check:
You may, but as you're saying, in another PR. :)

2025-02-26 11:35 UTC, ryv-odoo commented on odoo/orm/registry.py
> +        self.not_null_columns: set[tuple[str, str]] = set()  # {(table_name, column_name)}
`self.not_null_fields` and having Field inside the set instead of tuple.

2025-03-10 09:23 UTC, rco-odoo approved these changes
@robodoo rebase-ff r+

2025-03-10 09:23 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-03-10 09:29 UTC, rco-odoo commented
@robodoo r-

2025-03-10 09:32 UTC, rco-odoo commented on odoo/orm/domains.py
> +def _optimize_in_required(condition, model):
Operator optimizations are part of the `BASE` optimization level.  But this one depends on the database's state, i.e., it is transaction-dependent.  IMHO this optimization should be part of the `FOR_SQL` optimization level.

2025-03-10 12:29 UTC, kmagusiak commented on odoo/orm/domains.py
> +def _optimize_in_required(condition, model):
Strictly speaking yes. However, this does not change within the lifetime of the Registry (it depends on the schema, but does not depend on the data/state) and if it is saved in some cache, it will be purged after the registry reload.

Should we keep it as-is or can  you confirm to move this in the FOR_SQL optimizations?

2025-03-12 11:56 UTC, rco-odoo approved these changes

2025-03-12 11:57 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-03-12 12:17 UTC, HydrionBurst commented on odoo/orm/registry.py
> +                            self.not_null_fields.add(field)
Here we use the field onbject in the `self.not_null_fields`
When manual fields are modifed in `ir.model.field`, `_setup_models__` and `init_models` will be called but not this `check_null_constraints`, so I guess the new field object maynot be the old one?

2025-03-12 12:20 UTC, kmagusiak commented on odoo/orm/registry.py
> +                            self.not_null_fields.add(field)
Don't we create a new registry in that case?

2025-03-12 12:54 UTC, HydrionBurst commented on odoo/orm/registry.py
> +                            self.not_null_fields.add(field)
No, the registry is [invalidated](https://github.com/odoo/odoo/blob/8263ddc408fb9bef646558b8ae91a9de3b3b6cc8/odoo/orm/registry.py#L371) in `_setup_models__`. And the sequence of the current worker is [increased](https://github.com/odoo/odoo/blob/8263ddc408fb9bef646558b8ae91a9de3b3b6cc8/odoo/orm/registry.py#L954) at the end of the transaction to avoid reloading the registry.

I think it is base on the logic that manual fields are always toplevel which won't be overridden. So we don't need to reload the whole registry to get correct inheritence.

2025-03-12 15:53 UTC, closed without merging