[IMP] point_of_sale, pos_*: allow some settings to be modified during an open session
odoo/odoo pull request #191396
Opened 2024-12-20 16:46 UTC by stva-odoo

* pos_restaurant
Previously, some settings (Table booking: appointment type, Tips, Login with employees, Restrict categories, Flexible procelists, Global discount) could not be modified while a session was open.
With this commit, these settings can now be modified, and the POS will resynchronize after reloading

task-4380609

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-20 16:46 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191396.png)](https://mergebot.odoo.com/odoo/odoo/pull/191396)

2024-12-25 21:02 UTC, davidmonnom requested changes
Hey, nice PR

Here are a few changes to make. 

The next time the page is reloaded, the change will not be taken into account. To get the new data directly, the user can use the “reload product” option available in the PoS.

2024-12-25 21:02 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/services/data_service.js
> +        if (navigator.onLine && (sessionState !== "opened" || this.sync_required)) {
Use the current data integrity system instead of adding one

2024-12-25 21:02 UTC, davidmonnom commented on addons/pos_restaurant/models/pos_config.py
> +        return keys
You can also add these fields on `_compute_local_data_integrity`decorator

2024-12-26 09:09 UTC, stva-odoo commented
@davidmonnom Thanks, I missed the `_compute_local_data_integrity` method.

2024-12-26 15:12 UTC, davidmonnom approved these changes

2024-12-31 12:13 UTC, davidmonnom commented
@robodoo r+

2025-01-01 03:00 UTC, robodoo commented
@stva-odoo @davidmonnom linked pull request(s) odoo/enterprise#76014 not ready. Linked PRs are not staged until all of them are ready.

2025-01-02 10:42 UTC, davidmonnom commented
@robodoo r+

2025-01-02 13:35 UTC, closed without merging