[IMP] hr, _*: improve UX for employee-related features in Employee(HR) App.
odoo/odoo pull request #191337
Opened 2024-12-20 12:33 UTC by rame-odoo

_* = hr_skills, hr_skills_survey, hr_org_chart, hr_gamification, gamification

Purpose: Enhance the user experience for managing skills, resumes, and employee- related features in HR.

-------------------------------------------------------------------------------- 
Specification & Implementation:
--------------------------------------------------------------------------------

Skill Timeline:
- When no skills are available for an employee, the timeline is now hidden.

Tag Placeholder:
- Added tag placeholders for clearer user input. Reference.

New Resume UX:
- Revamped the resume section, ensuring better clarity and accessibility.

Certification Field Visibility:
- If the 'Category' is not Internal Certification, the certification field is hidden to avoid unnecessary clutter.

Social Media Category:
- Special UX adjustments for social media-related resume entries.

Organization Chart Linkable Text:
- Removed the smart button and made the 'Organization Chart' text linkable.
- Added action functionality to the text link similar to the smart button.

Gamification Empty Screen:
- Improved the empty screen experience for gamification with more engaging UX.

Badge Kanban:
- Improved the kanban view format for gamification, making it visually cleaner and more engaging.

Employee Creation on User Creation:
- When creating a new user, the corresponding employee record is automatically created in the selected company.

Job Position and Job Title Sync:
- If the Job Title is empty, it now automatically copies the Job Position.
- If the Job Position is later updated and the Job Title was customized, the title remains unchanged.

- Task: 4391333

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-20 12:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191337.png)](https://mergebot.odoo.com/odoo/odoo/pull/191337)

2025-01-02 13:07 UTC, kais-odoo requested changes

2025-01-02 13:07 UTC, kais-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +        for record in self:
```suggestion
        for line in self:
```

2025-01-02 13:07 UTC, kais-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +                record.is_social_media = False
EOL missing

2025-01-03 05:08 UTC, rame-odoo commented on addons/hr/views/res_users.xml
> +                    <field name="create_employee" force_save="1" string="Create Employee" invisible="1" groups="hr.group_hr_user"/>
It is required to get true value of this field because store value is false.

2025-01-03 05:15 UTC, rame-odoo commented on addons/hr_org_chart/views/hr_views.xml
> +                    <a class="o_link o_separator"
Done!!

2025-01-03 05:26 UTC, rame-odoo commented on addons/hr_org_chart/views/hr_views.xml
> +                                <span class="text-uppercase" style="font-size: 13px; font-weight: bold; letter-spacing: 0.03em;">Organization Chart</span>
Done!!

2025-01-03 05:39 UTC, rame-odoo commented on addons/hr_org_chart/views/hr_views.xml
> +                                <i class="fa fa-users ms-1" style="margin-top: 1px;"></i>
Done!!

2025-01-03 05:41 UTC, rame-odoo commented on addons/hr_org_chart/views/hr_views.xml
> +                    <a class="o_link o_separator"
Done!!

2025-01-03 06:06 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +    survey_id_visible = fields.Boolean(string='Is Survey Visible', compute='_compute_survey_id_visible')
Done!!

2025-01-03 06:08 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +        for record in self:
Done!!

2025-01-03 06:08 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +        for record in self:
Done!!

2025-02-25 12:35 UTC, mepe-odoo requested changes
Thanks for your work :partying_face:

2025-02-25 12:35 UTC, mepe-odoo commented on addons/hr_skills/models/hr_resume_line.py
>  # -*- coding: utf-8 -*-
you can remove this line too ;)

2025-02-25 12:35 UTC, mepe-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +            if internal_certification_type and line.line_type_id == internal_certification_type and line.display_type == 'certification':
why here you check if internal_certification_type exist and in the next method you don't check if social_media_type exist ? :/

2025-02-25 12:35 UTC, mepe-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +                line.date_start = fields.Date.context_today(line)
you should create a compute method for date_start too (and this field should be a computed store readonly field)

2025-02-25 12:35 UTC, mepe-odoo commented on addons/hr_skills/views/hr_views.xml
> +                            <field name="date_start" string="Dates" placeholder="Start Date" widget="daterange" options="{'end_date_field': 'date_end', 'placeholder': 'Ongoing'}" invisible="is_social
line too long

2025-02-25 12:35 UTC, mepe-odoo commented on addons/web/static/src/views/fields/datetime/datetime_field.js
did you ask the js framework for this changes ?

2025-02-26 10:28 UTC, rame-odoo commented on addons/gamification/views/gamification_badge_user_views.xml
> +                                    Granted on <t t-esc="luxon.DateTime.fromISO(record.create_date.raw_value).toFormat('D')"/>
Yes, Done!!

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_gamification/views/hr_employee_views.xml
> +                            <p class="o_view_nocontent_sad_face"></p>
Using o_view_nocontent, empty screen text set to the center of whole view (form view) but we want it in the page section only so...!!

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_gamification/views/hr_employee_views.xml
> +                        <button string="Grant a Badge" type="action" name="%(action_reward_wizard)d"/> <!-- to reward this employee for a good action -->
Okay, Done!

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_gamification/views/hr_employee_views.xml
> +                        <button string="Grant a Badge" type="action" name="%(action_reward_wizard)d"/> <!-- to reward this employee for a good action -->
Done!

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
>  # -*- coding: utf-8 -*-
Done!

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +            if internal_certification_type and line.line_type_id == internal_certification_type and line.display_type == 'certification':
Oh yes!! You are right. This check ensures that the reference hr_skills_survey.resume_type_certification is valid before proceeding. I should apply a similar check in _compute_is_social_media to avoid errors if social_media_type does not exist. I'll update the code to do this.

2025-02-26 10:29 UTC, rame-odoo commented on addons/hr_skills/views/hr_views.xml
> +                            <field name="date_start" string="Dates" placeholder="Start Date" widget="daterange" options="{'end_date_field': 'date_end', 'placeholder': 'Ongoing'}" invisible="is_social
Yes! Done!

2025-02-26 10:29 UTC, rame-odoo commented on addons/web/static/src/views/fields/datetime/datetime_field.js
No!! I was thinking to tag them here after validation done.

2025-02-26 10:39 UTC, rame-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +                line.date_start = fields.Date.context_today(line)
You mean should I remove this line [ line.date_start = fields.Date.context_today(line) ] and set this in _compute_date_start method and make it store true and readonly false? Adding, We want start date only when there is social media type. For others I added two different placeholders for start & end date.

2025-02-26 10:42 UTC, mepe-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +                line.date_start = fields.Date.context_today(line)
yes it's that :)

2025-02-26 10:43 UTC, mepe-odoo commented on addons/web/static/src/views/fields/datetime/datetime_field.js
i prefer to have their opinion before validating it :)

2025-02-26 10:44 UTC, mepe-odoo commented on addons/hr_gamification/views/hr_employee_views.xml
> +                            <p class="o_view_nocontent_sad_face"></p>
i speak about the picture himself, so define a new one ? :/

2025-02-26 10:49 UTC, rame-odoo commented on addons/hr_gamification/views/hr_employee_views.xml
> +                            <p class="o_view_nocontent_sad_face"></p>
As per specs, I think Geoffrey sir wants to add new emoji. So, I added svg file of picture same as specs.

2025-02-26 11:50 UTC, rame-odoo commented on addons/web/static/src/views/fields/datetime/datetime_field.js
Hello Team! @odoo/rd-framework-js 
I made some modifications in datetime_field.js file to get two different placeholders in field where daterange widgets is used. Like, In my task I want separate placeholders in date_start and date_end.
So can you give your opinion about this please? Thank you!!

2025-02-26 12:36 UTC, mepe-odoo commented on addons/hr_skills/models/hr_resume_line.py
> +                    line.date_start = fields.Date.context_today(line)
too many indentations and you forget to add an empty line at the end of the file :)

2025-03-18 10:13 UTC, pparidans commented on addons/web/static/src/views/view.scss
> +// the nocontent helper in fields specially for hr employee view form
As stated in your comment... this is specific to "HR" module... So why putting it in `web` ? :thinking:

2025-03-18 10:15 UTC, brboi reviewed
I was reviewing the `web` part while the branch has been updated and now there is no more JS diff in this module.

I would have said something like even though the code was correct I wasn't sure of the specs for the datetime field.

Moving it as and extension in hr modules is OK IMO.

If we see that use case more ofter we'll see how to tackle it through the `web` module ;)

2025-03-21 12:56 UTC, mepe-odoo requested changes
Hello thanks for your work :D

2025-03-25 12:28 UTC, mepe-odoo approved these changes
LGTM
I just don't understand why do you need to modify o_view_nocontent_neutral_face in your scss file

2025-03-25 12:33 UTC, rame-odoo commented on addons/hr_gamification/static/src/scss/hr_gamification.scss
> +    }
I added this default no content icon in page section as per we discussed. So, as per it is in web module, I couldn't extend that class in this module. So, I mentioned that in new scss file for this module.

2025-03-25 13:15 UTC, mepe-odoo commented on addons/hr_gamification/static/src/scss/hr_gamification.scss
> +    }
but you can do that in the xml
```xml
<div class="o_view_nocontent">
            <div class="o_nocontent_help">
                <p class="o_view_nocontent_neutral_face">
```

2025-03-25 13:21 UTC, rame-odoo commented on addons/hr_gamification/static/src/scss/hr_gamification.scss
> +    }
Yes! But by using o_view_nocontent class I can't access that in only page section because it is consider whole view(form). So, I made new class o_field_nocontent which is fit in page section and only for that I need to add other stuff also!1

2025-03-25 13:53 UTC, mepe-odoo commented on addons/hr_gamification/static/src/scss/hr_gamification.scss
> +    }
ok you're right i said nothing :saluting_face:

2025-04-22 09:39 UTC, tivisse commented on addons/hr/models/res_users.py
> +    create_employee = fields.Boolean(store=False, default=True, copy=False, string="Technical field, whether to create an employee")
Do you really wan to create an employee for each portal user ? :upside_down_face:

2025-04-22 11:59 UTC, tivisse commented
@robodoo r+

2025-04-23 20:06 UTC, closed without merging