[IMP] hr_expense: split invoice button
odoo/odoo pull request #191333
Opened 2024-12-20 11:56 UTC by malb-odoo

This commit will add a button when splitting an expense to easily find them.

task: 4418348

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-20 11:56 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191333.png)](https://mergebot.odoo.com/odoo/odoo/pull/191333)

2024-12-20 13:21 UTC, JulienAlardot commented
Just a thought, Wouldn't it be better to have a "original_expense_splitted_id" or something akin to that and search matching ones for the action? The value could be the id of one of the deleted expense if we don't set it as a related field, just as a unique index. I feel like yet another M2M for that kind of things would be overkill.

2025-01-16 13:22 UTC, malb-odoo commented on addons/hr_expense/wizard/hr_expense_split_wizard.py
> +        all_related_expenses = copied_expenses | self.expense_id | self.expense_id.split_expense_ids
needed for the split loop

2025-01-20 07:27 UTC, malb-odoo commented
NB: The task should be merged after the report removal one https://www.odoo.com/odoo/967/tasks/4481615

2025-02-20 14:14 UTC, oco-odoo requested changes

2025-02-20 14:14 UTC, oco-odoo commented on addons/hr_expense/models/hr_expense.py
> +        help="All expenses related to this split, including the original and the splits.",
```suggestion
        help="All expenses related to this split, including the original and the other splits.",
```

2025-02-20 14:14 UTC, oco-odoo commented on addons/hr_expense/models/hr_expense.py
> +        help="All expenses related to this split, including the original and the splits.",
Isn't it a bit strange, though ? Plus, this will create a LOT of relational links, since every expense of the split will always need to be linked to all the others. Isn't it too much ? Wouldn't a m2o on the split linking it to the main expense be enough ? 

Even if we want to keep this flow as-is, I think it would be possible to implement it like that, and have a bit of python processing to gather the records we want before opening them.

2025-03-03 10:40 UTC, oco-odoo requested changes
Last nitpicking ;)

2025-03-03 10:40 UTC, oco-odoo commented on addons/hr_expense/models/hr_expense.py
> +    split_expense_id = fields.Many2one(
Maybe the field should rather be called split_expense_origin_id, now ? (for clarity)

2025-03-03 10:54 UTC, JulienAlardot reviewed
The compute from same_receipt_expense_ids should also be adapte imo, because now we know which expense it comes from and it shouldn't raise a warning banner

(And tests would be nice)

:)

2025-03-10 10:53 UTC, JulienAlardot requested changes

2025-03-10 16:01 UTC, malb-odoo commented on addons/hr_expense/wizard/hr_expense_split_wizard.py
> +            split_expense_ids = self.env['hr.expense'].search([('split_expense_id', '=', self.expense_id.split_expense_origin_id.id)])
Maybe i don't see what you are suggesting but I think that i anyway need a search to display the all_related_expenses so i would say it's ok like that ? maybe i could just improve by not overriding the split_expense_origin if it's the same as the expense_id one but that would mean traverse the all_related expense so don't know if it's better ahah

2025-03-11 08:46 UTC, JulienAlardot commented on addons/hr_expense/wizard/hr_expense_split_wizard.py
> +            split_expense_ids = self.env['hr.expense'].search([('split_expense_id', '=', self.expense_id.split_expense_origin_id.id)])
Indeed, you need a search I failed to see the return
My point was more about
```python
all_related_expenses.split_expense_origin_id = self.expense_id
```
becoming
```python
(self.expense_id | copied_expense_ids).split_expense_origin_id = self.expense_id.split_expense_origin_id or self.expense_id
```

2025-03-25 08:59 UTC, JulienAlardot approved these changes
@robodoo r+

2025-03-25 11:25 UTC, closed without merging