[IMP] orm: Domain add "not =like" operator as standard
odoo/odoo pull request #191471
Opened 2024-12-23 08:29 UTC by kmagusiak

Adding the complement of `=like` and `=ilike`. This is mainly for completeness sake, but it also allows to avoid some NOT nodes in the AST of domains.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-23 08:29 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191471.png)](https://mergebot.odoo.com/odoo/odoo/pull/191471)

2025-01-08 09:10 UTC, ryv-odoo approved these changes
You need to resolve the conflict.

2025-01-09 12:15 UTC, ryv-odoo approved these changes
LGTM. Can you plz add least add one test case with these new operators (with filtered_domain too) ? Sry I didn't think about it sooner.

2025-01-10 15:33 UTC, ryv-odoo requested changes
I think you forget to change `Properties.condition_to_sql` to have an insensitive/unaccent `=not ilike`.

2025-01-10 15:33 UTC, ryv-odoo commented on odoo/addons/base/tests/test_expression.py
> -        self.assertNotIn(helen, self._search(Model, [('name', 'not ilike', 'hélène')]))
Why removing test on `not ilike` specifically? Just add yours ?
Same below

2025-01-10 17:23 UTC, kmagusiak commented
> I think you forget to change `Properties.condition_to_sql` to have an insensitive/unaccent `=not ilike`.

There is nothing to change, there are no conditions on `=like` and the `SQL_OPERATORS` contains `not =ilike`.

2025-01-13 07:54 UTC, ryv-odoo commented on odoo/addons/base/tests/test_expression.py
> -        self.assertNotIn(helen, self._search(Model, [('name', 'not ilike', 'hélène')]))
That doesn't change the fact that `not ilike` is not test anymore :thinking:

2025-01-13 08:07 UTC, kmagusiak commented on odoo/addons/base/tests/test_expression.py
> -        self.assertNotIn(helen, self._search(Model, [('name', 'not ilike', 'hélène')]))
Tests added back in the previous section.

2025-01-15 16:30 UTC, ryv-odoo commented on odoo/addons/base/tests/test_expression.py
> -        self.assertNotIn(helen, self._search(Model, [('name', 'not ilike', 'élè')]))
Bring these lines

2025-01-16 12:29 UTC, closed without merging