[FIX] website: fix scroll to anchor when animations
odoo/odoo pull request #191481
Opened 2024-12-23 10:24 UTC by bvr-odoo

Steps to reproduce the bug:

- Go to the website edit mode.
- Drag and drop a "Text - Image" block onto the page.
- Drag and drop a "Media List" block at the bottom of the page.
- Drag and drop a "Text" block at the bottom of the page.
- Click on the "Text" block.
- In the "Text" block options, click the "Create a link to target this section" button.
- Click on the "Button" inside the "Text - Image" block.
- In the options, paste the "link" to the anchor copied to the clipboard into the URL input of the button.
- In the "Column" options, add an "On Scroll" animation to the column.
- Save the page.
- Click the "Text - Image" button.
- Bug: the page doesn't scroll to the "Text" block.

This bug was introduced by commit [1], where the "overflow: hidden" CSS rule, used to prevent a horizontal scrollbar during animations caused by overflowing content on the right side of the page, was moved from the HTML element to the body element.

The bug appeared because when the code triggering the scroll animation to the anchor runs after clicking the button, it checks which element is scrollable. At that moment, the body has "overflow-x: hidden," which causes its "overflow-y" to become "auto" instead of "visible" (browser behavior, see https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) The body element is then considered scrollable, even though it isn't. This is why the scroll animation doesn't work.

To fix this, we replace "overflow-x: hidden" with "overflow-x: clip." This is more appropriate in this context and prevents "overflow-y" from becoming "auto."

[1]: https://github.com/odoo/odoo/commit/fece9cb85761e6cb3fe3642f947661464402363b

opw-4393527

2024-12-23 10:24 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191481.png)](https://mergebot.odoo.com/odoo/odoo/pull/191481)

2024-12-23 10:53 UTC, bvr-odoo commented on addons/website/static/src/scss/website.scss
> +        @supports not (overflow-x: clip) {
@qsm-odoo not sure we want to support 3 year old browsers but I think it's better than nothing

2024-12-24 09:53 UTC, qsm-odoo requested changes
Interesting. But somehow it creates an horizontal scrollbar in edit mode if an animated element overflows to the right.

2024-12-24 10:01 UTC, bvr-odoo commented
> Interesting. But somehow it creates an horizontal scrollbar in edit mode if an animated element overflows to the right.

on Firefox but not on Chrome 🤔 I check

2024-12-24 12:43 UTC, bvr-odoo commented
@qsm-odoo Could you re-check after my change

2024-12-24 12:58 UTC, qsm-odoo approved these changes
@robodoo r+

2024-12-24 15:31 UTC, closed without merging