[REF] pos*: use monetary field
odoo/odoo pull request #191740
Opened 2024-12-25 06:15 UTC by djip-odoo

point_of_sale, pos_online_payment, pos_sale, pos_l10n_se, pos_pricer

before this commit:
==============
- using Float fields to display currency values.
- Some views did not display monetary data correctly,.

after this commit:
==============
- All currency-related fields have been replaced with Monetary fields instead of Float fields.
- Views have been updated to follow the new approach for displaying monetary data consistently.

Task-4424052

2024-12-25 06:15 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191740.png)](https://mergebot.odoo.com/odoo/odoo/pull/191740)

2024-12-30 07:15 UTC, paso-odoo requested changes

2024-12-30 07:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_order_view.xml
> +                    <field name="currency_id" invisible="True" />
```suggestion
                    <field name="currency_id" invisible="1" />
```

2024-12-30 07:15 UTC, paso-odoo commented on addons/point_of_sale/views/pos_payment_views.xml
> +                        <field name="currency_id" invisible="1" />
Is it required?

2024-12-30 07:15 UTC, paso-odoo commented on addons/pos_online_payment/models/pos_order.py
> +    next_online_payment_amount = fields.Monetary(string='Next online payment amount to pay', required=False) # unlimited precision
```suggestion
    next_online_payment_amount = fields.Monetary(string='Next online payment amount to pay') # unlimited precision
```

2025-02-03 13:04 UTC, davidmonnom approved these changes
Nice one, but somes tests are failing in l10n :(

2025-02-10 12:42 UTC, caburj commented
I tried to debug and I noticed that the supposed rounded value isn't saved in the db. This is because during the computation of the field value (e.g. `pos.order.amount_total`), the currency_field isn't available. I checked the `account` module and what they do is put "precompute" attribute to the currency field (see the model in account_move_line.py).

For me, currency should be taken in to account as intended by the field definition.

2025-02-12 05:18 UTC, djip-odoo commented
@caburj  changes has been done !

2025-02-17 14:26 UTC, caburj commented on addons/point_of_sale/report/pos_order_report.py
> +    currency_id = fields.Many2one('res.currency', related='order_id.currency_id', string="Currency")
how about here? No need for precompute?

Also, does precompute require a field to be "store=True"?

2025-02-17 14:27 UTC, caburj commented on addons/point_of_sale/wizard/pos_payment.py
> +    currency_id = fields.Many2one('res.currency', related='config_id.currency_id', string="Currency")
here also, no precompute.

2025-02-17 14:29 UTC, caburj commented on addons/pos_sale/models/crm_team.py
> +    pos_order_amount_total = fields.Monetary(string="Session Sale Amount", compute='_compute_pos_order_amount_total')
Does the `crm.team` model have `currency_id`?

2025-02-18 06:35 UTC, djip-odoo commented on addons/pos_sale/models/crm_team.py
> +    pos_order_amount_total = fields.Monetary(string="Session Sale Amount", compute='_compute_pos_order_amount_total')
yes, `crm.team` model has `currency_id` inherited from its parent class https://github.com/odoo/odoo/blob/b5c848e1c13c9f80806da8647cdbc468ec5bf403/addons/sales_team/models/crm_team.py#L96-L98

2025-02-18 06:48 UTC, djip-odoo commented on addons/point_of_sale/report/pos_order_report.py
> +    currency_id = fields.Many2one('res.currency', related='order_id.currency_id', string="Currency")
https://github.com/odoo/odoo/blob/3cbd933b98eb218b6c3bf9970efd846e8759a5cc/addons/point_of_sale/report/pos_order_report.py#L10

 the _auto = False attribute is used in models to indicate that the model does not directly correspond to a database table (i.e., it's a view model rather than a regular model). 

 **is there any need of precompute in it ?**

For precompute to work, the store parameter must be set; without it, precompute has no effect.

2025-02-25 13:12 UTC, alialfie reviewed
Hello! Same comment as in the Enterprise PR, please add an upgrade script to handle changing the fields' types

2025-10-09 07:25 UTC, djip-odoo commented
Hello @davidmonnom
Could you please look into this PR?
Thanks!

2025-12-24 13:06 UTC, djip-odoo commented
not needed for now

2025-12-24 13:06 UTC, closed without merging