[IMP] product*: update product form view layout
odoo/odoo pull request #191742
Opened 2024-12-25 09:45 UTC by rare-odoo

*: sale, stock

With this commit, The following changes are made to product form

- Removed the `Update Quantity`, `Replenish`, and `Print Labels` buttons 
  from the product form header for a cleaner layout.
- Moved "Replenish" and "Print Labels" options to the server action menu
  (cog menu) for better organization.
- Removed the tooltip for the product type set to 'Goods'.
- Added the `Quantity On Hand` field, which is editable only when there are
  no multiple variants or when storage locations are disabled. If there are multiple 
  variants or storage locations are enabled, the `Update` button is displayed.
- Removed the 'On Hand Stat' button
- Improved the 'Forecast Stat' button to display both On Hand Quantity 
  and Forecast Quantity in a single column for better readability.

Task: [4385237](https://www.odoo.com/odoo/my-tasks/4385237)

2024-12-25 09:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191742.png)](https://mergebot.odoo.com/odoo/odoo/pull/191742)

2025-01-24 12:22 UTC, amoyaux commented on addons/sale/models/product_template.py
> +        if self.invoice_policy == 'delivery' and self.type != 'consu':
It says remove description, so you could completely remove the field and code.

2025-01-24 12:24 UTC, amoyaux commented on addons/stock/models/product.py
> +        for product in self:
Use _update_available_quantity

2025-01-24 12:26 UTC, amoyaux commented on addons/stock/models/product.py
> +    def _compute_show_qty_update_button(self):
Do it in xml

2025-01-24 12:32 UTC, amoyaux commented on addons/stock/views/product_views.xml
> +                    <div class="d-flex gap-2 align-items-baseline" invisible="type != 'consu' or not is_storable" groups="stock.group_stock_user">
can't be is_storable if the product is not consu. Half of the condition is useless

2025-01-24 12:33 UTC, amoyaux commented on addons/stock/views/product_views.xml
> +                for record in records:
"Consumable Products" is now a technical term and not in the interface. Not a good explanation for user

2025-01-27 10:29 UTC, rare-odoo commented
Thank you for the review, @amoyaux 
I've added a few comments in response to your change requests.

2025-01-27 10:29 UTC, rare-odoo commented on addons/sale/models/product_template.py
> +        if self.invoice_policy == 'delivery' and self.type != 'consu':
It says remove the description for goods, but it's unclear if this 
applies to services and combos as well.

2025-02-12 14:30 UTC, Whenrow requested changes

2025-02-12 14:30 UTC, Whenrow commented on addons/stock/models/stock_quant.py
> +                raise UserError(_('You need to provide a Lot/Serial Number for the product %s.', quant.product_id.display_name))
We want to keep the ability to set a lot only at the delivery. Could you remove this constrain ?

2025-02-13 10:07 UTC, rare-odoo commented
Thanks for the review, @Whenrow.
I’ve left a comment.

2025-02-13 10:07 UTC, rare-odoo commented on addons/stock/models/stock_quant.py
> +                raise UserError(_('You need to provide a Lot/Serial Number for the product %s.', quant.product_id.display_name))
So, Is it intended that we allow to enter product quantity 
without lot/sn during Inventory Adjustment or Quantity Update?

2025-02-13 10:08 UTC, rare-odoo commented on addons/stock/models/product.py
> +    def _compute_show_qty_update_button(self):
There are many parameters to consider, which is the main reason for handling it here.

2025-02-13 12:36 UTC, Whenrow commented on addons/stock/models/stock_quant.py
> +                raise UserError(_('You need to provide a Lot/Serial Number for the product %s.', quant.product_id.display_name))
I would say it's not blocking. but we will definitely do something to be a bit more strict in the future

2025-02-13 18:50 UTC, Whenrow commented
robodoo r+ rebase-ff

2025-02-13 18:50 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-02-13 19:00 UTC, robodoo commented
@rare-odoo @Whenrow linked pull request(s) odoo/upgrade#6980 not ready. Linked PRs are not staged until all of them are ready.

2025-02-14 13:43 UTC, Whenrow commented
robodoo r+

2025-02-14 21:58 UTC, closed without merging