[FIX] mail: recipient list overflow when screen size is increased
odoo/odoo pull request #191880
Opened 2024-12-27 10:59 UTC by maad-odoo

Purpose of this commit:
When the recipient list exceeds 5, the text 'X more recipients' is displayed. However, when the screen is zoomed, the list overflows, making the 'Show all recipients' button inaccessible. This issue occurred because the recipient list and the 'X other recipients' text were treated as a single string, preventing overflow. This commit splits the string into two parts: the recipient list, which will overflow, and the recipient count, which remains visible when the list is large.

task-4417552

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-27 11:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191880.png)](https://mergebot.odoo.com/odoo/odoo/pull/191880)

2025-02-10 06:35 UTC, robodoo commented
@maad-odoo the target branch 'saas-17.2' has been disabled, you may want to close this PR.

2025-02-12 08:37 UTC, maad-odoo commented
@seb-odoo I have re-targeted the PR to 17.4 and re-based the branch as well. You can have a look

2025-02-14 07:39 UTC, thjo-odoo commented
@maad-odoo 
Hello, just here to tell you that this recipient list has been revamped in master https://github.com/odoo/odoo/pull/188642. Your fix will thus need to be adapted in master/18.2 to accommodate these changes.

2025-02-18 17:05 UTC, seb-odoo requested changes
Hello, here are technical comments based on current diff, but is this really how we want to solve it?

There are css instructions allowing to break words/phrases if what is what we need to prevent overflow.

2025-02-18 17:05 UTC, seb-odoo commented on addons/mail/static/src/chatter/web/chatter_patch.js
>                  return `<span class="text-muted" title="${escape(
`markup()` should be as close as possible to code production, so when doing the return here.

2025-02-18 17:05 UTC, seb-odoo commented on addons/mail/static/src/chatter/web/chatter_patch.js
> +    get recipientsCount() {
The name of this method makes it look like it returns a count/number, but it returns a text/string.

2025-02-18 17:05 UTC, seb-odoo commented on addons/mail/static/src/chatter/web/chatter_patch.js
> +                 _t("out of %(recipientCount)s", {
It's not acceptable to split translation phrases in several parts as order might need to be changed in different languages.

There should be different complete translation phrases for the different possible cases.

2025-05-08 08:00 UTC, alexkuhn approved these changes
@robodoo r+

2025-05-08 08:07 UTC, alexkuhn commented
@robodoo up to saas-18.1

Reason: 18.2 has recipient list changed to recipient input, which wraps correctly when it has many items.

2025-05-08 08:07 UTC, robodoo commented
Forward-porting to 'saas-18.1'.

2025-05-08 12:34 UTC, closed without merging