tmp
odoo/odoo pull request #191813
Opened 2024-12-26 14:04 UTC by tsm-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-26 14:05 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191813.png)](https://mergebot.odoo.com/odoo/odoo/pull/191813)

2024-12-31 09:00 UTC, tsm-odoo commented on addons/im_livechat/static/src/embed/external/boot.js
> +        await loadBundle("im_livechat.assets_livechat_support_tours");
note: cannot be done in the template directly as odoo bundle is loaded with a defer script.

2025-01-06 09:14 UTC, tde-banana-odoo commented on addons/crm_livechat/models/crm_lead.py
> +        action["context"] = json.loads(action.get("context", "{}"))
You may use literal_eval normally

2025-01-15 11:30 UTC, alexkuhn approved these changes
@robodoo r+ rebase-ff

2025-01-15 11:30 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2025-01-15 18:00 UTC, robodoo commented
@tsm-odoo @alexkuhn linked pull request(s) odoo/enterprise#76279 not ready. Linked PRs are not staged until all of them are ready.

2025-01-16 07:06 UTC, pivi-odoo requested changes
Hi 👋🏼 

Left a few comments that needs to be addressed for perf reasons :)

2025-01-16 07:06 UTC, pivi-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one("discuss.channel", "Live chat from which the lead was created")
Missing 'btree_not_null` index.
Ref to https://github.com/odoo/enterprise/pull/76279#discussion_r1917044534 for more info

2025-01-16 07:06 UTC, pivi-odoo commented on addons/crm_livechat/security/crm_livechat_security.xml
> +        <field name="domain_force">[("crm_lead_ids", "!=", False)]</field>
Same note as https://github.com/odoo/enterprise/pull/76279#discussion_r1917069226

2025-01-16 09:04 UTC, pivi-odoo approved these changes

2025-01-17 14:23 UTC, alexkuhn approved these changes
@robodoo r+

2025-01-17 14:25 UTC, seb-odoo requested changes
@robodoo r-

2025-01-17 14:25 UTC, seb-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one("discuss.channel", "Live chat from which the lead was created", index="btree_not_null")
This field must be restricted to admin only to avoid giving access to arbitrary channels.

2025-01-17 14:36 UTC, seb-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one("discuss.channel", "Live chat from which the lead was created", index="btree_not_null")
Or at least enforce it to be read-only (write override) and only set it during the creation flow?

2025-01-17 15:36 UTC, seb-odoo commented on addons/crm_livechat/models/crm_lead.py
> +        return super().write(vals)
create should also be verified: only accessible channels should be allowed.

2025-01-17 15:40 UTC, tde-banana-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one("discuss.channel", "Live chat from which the lead was created", index="btree_not_null")
But that's the serpent qui se mord la queue: a high level user can link a channel, which then gives access to the channel to people who can see the lead ?

2025-01-17 15:42 UTC, tde-banana-odoo commented on addons/crm_livechat/models/crm_lead.py
> +        if "channel_id" in vals:
Would instead check current has read access on channel before allowing to change it, that way we check there is no access escalation, if I understood the feature. No need to be that restrictive.

2025-01-17 15:43 UTC, seb-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one("discuss.channel", "Live chat from which the lead was created", index="btree_not_null")
Well admins can do anything so it's not really a problem. If they want to grant lead access to channel its their problem.
But with constraints at least we're limiting admins too.

We're currently considering adding lead_id on channel instead, the code would be cleaner and more robust, but it was functionally possible to be a "many" so we'll have to see how we then have to enforce it to be unique.

2025-01-17 15:43 UTC, tde-banana-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    channel_id = fields.Many2one(
Make it readonly so that people are not tempted to change it in UI. That's not solving any security concern (both should be implemented) but that's some basics (anyway this field is there for information purpose mainly).

2025-01-17 15:45 UTC, tde-banana-odoo commented on addons/crm_livechat/models/discuss_channel.py
> +    crm_lead_ids = fields.One2many("crm.lead", "channel_id")
This field should probably be restricted to sales people
```suggestion
    crm_lead_ids = fields.One2many("crm.lead", "channel_id", groups="sales_team.group_sale_salesman")
```
Same below.

2025-01-24 15:36 UTC, seb-odoo commented on addons/crm_livechat/models/crm_lead.py
> +        return action
Wouldn't it be functionally better to open the chat window, to keep the lead page visible at the same time?

2025-01-24 15:42 UTC, seb-odoo commented on addons/crm_livechat/models/discuss_channel.py
> +        )
Maybe we should just drop the ACL and create a specific route allowing to join the channel if it has a lead.

2025-01-24 15:54 UTC, seb-odoo commented on addons/crm_livechat/models/discuss_channel.py
> +        )
Or make `has_crm_lead` a stored field.

2025-01-28 08:47 UTC, tsm-odoo commented on addons/crm_livechat/models/crm_lead.py
> +        return action
done :+1:

2025-01-28 08:52 UTC, tsm-odoo commented on addons/crm_livechat/models/discuss_channel.py
> +        )
That's not just about joining the channel but also being able to access it. I'm not found of dedicated routes that makes the logic more complex than it should. I changed the field to a stored one.

2025-02-03 17:29 UTC, seb-odoo approved these changes
PR is lacking ACL tests, similar to enterprise part

@robodoo delegate+

2025-02-03 17:29 UTC, seb-odoo commented on addons/im_livechat/models/discuss_channel.py
> +            parts.append(Markup(f"{msg_template}<br/>") % html2plaintext(message.body))
For good practice, markup should be around strong and br, not whole msg_template

2025-02-03 17:29 UTC, seb-odoo commented on addons/crm_livechat/models/discuss_channel.py
> +            "channel_id": self.id,
It would be nice to adapt at least one existing to ensure this is properly written.

2025-02-04 08:57 UTC, tsm-odoo reviewed
@robodoo r+

2025-02-04 23:36 UTC, closed without merging

2025-02-05 08:38 UTC, tde-banana-odoo reviewed
Probably a field to remove, lead is a heavy model, no need of useless fields.

2025-02-05 08:38 UTC, tde-banana-odoo commented on addons/crm_livechat/models/crm_lead.py
> +    from_livechat = fields.Boolean(compute="_compute_from_livechat", compute_sudo=True)
Useless field. Please remove stored field that have no usage.

2025-02-05 08:38 UTC, tde-banana-odoo commented on addons/crm_livechat/views/crm_lead_views.xml
> +                <button name="action_open_livechat" type="object" class="oe_stat_button" icon="fa-comments" invisible="not from_livechat" groups="sales_team.group_sale_salesman">
Just make a visible based on channel_id

2025-02-05 08:49 UTC, tsm-odoo commented on addons/crm_livechat/views/crm_lead_views.xml
> +                <button name="action_open_livechat" type="object" class="oe_stat_button" icon="fa-comments" invisible="not from_livechat" groups="sales_team.group_sale_salesman">
channel_id is limited to `base.group_erp_manager` group to avoid users to assign arbitrary channels to leads thus granting access to channel through ACLs. Do you have a recommendation to solve this issue?

2025-02-05 09:00 UTC, tde-banana-odoo commented on addons/crm_livechat/views/crm_lead_views.xml
> +                <button name="action_open_livechat" type="object" class="oe_stat_button" icon="fa-comments" invisible="not from_livechat" groups="sales_team.group_sale_salesman">
Do it the inverse way. Fix channel ACLs and let m2o do their job. You should use the ORM, not try to constraint it to do the inverse it was meant to be used.

I will remove the field before the freeze, then please fix channel ACLs accordingly. We can't add fields like that on models like crm.lead, it is too big to hold useless content.