[FIX] hr_holidays: fix the allocation approval
odoo/odoo pull request #191808
Opened 2024-12-26 13:26 UTC by amah-odoo

- fix the `hr_leave_allocation_rule_employee_update` rule to include `('manager','both') in validation_type` instead of `hr` as those are the types where the emoployee's manager should be able to update
- fix `_check_approval_update` function to match the designed access rules where TOO only approve `hr` and validate `both` and manager approvre `manager, both`

Task: 4432503

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-26 13:26 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191808.png)](https://mergebot.odoo.com/odoo/odoo/pull/191808)

2025-01-13 11:06 UTC, Bertrand2 requested changes
Thanks for the PR! Here's a couple of comments.
Additionally, as you change translated text in stable, you'll have to update the pot file, don't hesitate to reach if you need any help with that. :)

2025-01-13 11:15 UTC, amah-odoo commented on addons/hr_holidays/tests/test_allocation_access_rights.py
> +        cls.lt_validation_hr = cls.env['hr.leave.type'].create({
The details of the test and where it was used tells that it is testing the `hr` approval not the no validation type.
we can add a new class to test the no_validation scenario

2025-01-15 15:35 UTC, Bertrand2 requested changes
Thanks for the quick changes! Here are some extra comments :innocent:

2025-01-15 15:35 UTC, Bertrand2 commented on addons/hr_holidays/tests/test_allocation_access_rights.py
> +        cls.lt_validation_hr = cls.env['hr.leave.type'].create({
Ah indeed my bad, your changes make sense!

2025-01-15 15:36 UTC, Bertrand2 commented on addons/hr_holidays/models/hr_leave_allocation.py
> +                raise UserError(_('Only %s\'s Time Off Approver, a time off Officer/Responsible or Administrator can approve or refuse time off Allocation requests.') % (allocation.employee_id.name))
(will require to re-export the pot file)

2025-01-21 10:00 UTC, Bertrand2 approved these changes
Thanks for the changes! LGTM
robodoo r+

2025-01-21 12:56 UTC, closed without merging