[IMP] hr_contract: add method to fetch employee contract periods
odoo/odoo pull request #191917
Opened 2024-12-27 13:47 UTC by kthe-odoo

In this commit a method is added to find contract working periods in a specific interval.

Added some mock models for HOOT tests.

task-3885152

2024-12-27 13:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/191917.png)](https://mergebot.odoo.com/odoo/odoo/pull/191917)

2025-03-20 08:31 UTC, xavierbol requested changes
Thanks for your work, I left some comments. 🙂

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +            "",
Is it really needed? 🤔 

I guess there are also default values as we have in python, no?

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +            ]).toList(),
You can just give the domain list, I don't understand why you need to create domain object to convert it in domain list. 🤔

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +export class HrEmployeeContract extends hrModels.HrEmployee {
```suggestion
export class HrEmployee extends hrModels.HrEmployee {
```

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +hrModels.HrEmployee = HrEmployeeContract;
```suggestion
hrModels.HrEmployee = HrEmployee;
```

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
Why is this method public? 🤔 

Also, why not moving that method in hr.employee model since we don't use `self` we mainly use `employee_ids`, so we could move the model in employee model to be able to use `self`, no? 🤔

2025-03-20 08:31 UTC, xavierbol commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
Currently, since the method is public there is potentially a security issue since everything is made in sudo, it means any users to access to the information of any employees returned by that method. 😕

2025-03-20 12:40 UTC, kthe-odoo commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +            "",
Yes we could do like python but the default value would be undefined which is causing errors.

2025-03-20 12:42 UTC, kthe-odoo commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
Function moved to hr.employee and I will keep it mind to make methods which pass data to JS to be made private

2025-03-20 13:05 UTC, xavierbol commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
@kthe-odoo actually, if we don't need to call it in JS code then let's make the method private to avoid having any security issue and avoid having too much entry points. 🙂

2025-03-20 13:11 UTC, kthe-odoo commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
We are calling this method in _gantt_unavailability so we could make it private using @api.private , not directly called in directly using orm in js.

2025-03-20 14:45 UTC, xavierbol commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
We don't have to use a tag, the method name just starts with `_` as you did.

I am not sure to understand why you mention `@api.private`

2025-03-21 12:34 UTC, kthe-odoo commented on addons/hr_contract/models/hr_contract.py
> +    def get_employee_working_periods(self, employee_ids, start, stop):
Noted :heavy_check_mark:

2025-03-28 14:56 UTC, xavierbol reviewed
Thanks for your work, I left some comments. 🙂

2025-03-28 14:56 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +            employee = contract.employee_id.id
```suggestion
            employee_id = contract.employee_id.id
```

or 

```suggestion
            employee = contract.employee_id
```

2025-03-28 14:56 UTC, xavierbol commented on addons/hr_contract/tests/test_get_employee_working_periods.py
> +        return self.env["hr.employee"]._get_employee_working_periods(employee_ids, start, stop)
why not writing that instead of creating a hook just for that? 🧐

2025-04-01 11:54 UTC, kthe-odoo commented on addons/hr_contract/tests/test_get_employee_working_periods.py
> +        return self.env["hr.employee"]._get_employee_working_periods(employee_ids, start, stop)
Done :checkered_flag:

2025-04-01 11:54 UTC, kthe-odoo commented on addons/hr_contract/models/hr_employee.py
> +            employee = contract.employee_id.id
:white_check_mark:

2025-05-02 14:50 UTC, xavierbol reviewed
Thanks for your work, I left some comments. 🙂

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/static/tests/hr_contract_mock_models.js
> +    date_end = fields.Date();
I think we could use `ServerModel`

```suggestion
export class HrContract extends models.ServerModel {
    _name = "hr.contract";
```

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +        employees_sudo = self.browse(employee_ids).sudo()
why not using `self` instead of giving an extra parameter for the employee ids?

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +                    ("employee_id", "in", set(employees_sudo.ids) - set(contracts.mapped("employee_id").ids)),
`mapped` is implicit for relational fields.
```suggestion
                    ("employee_id", "in", set(employees_sudo.ids) - set(contracts.employee_id.ids)),
```

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +                    ("employee_id", "in", set(employees_sudo.ids) - set(contracts.mapped("employee_id").ids)),
Also, we could do something like this:

```suggestion
                    ("employee_id", "in", (employees_sudo - contracts.employee_id).ids),
```

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +                aggregates=["__count"],
```suggestion
                aggregates=["__count"],
                having=[("__count", ">", 0)],
```

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +            if employees_with_contract_outside_current_scale.get(employee):
```suggestion
            if employee in employees_with_contract_outside_current_scale:
```

2025-05-02 14:50 UTC, xavierbol commented on addons/hr_contract/models/hr_employee.py
> +    def _get_employee_working_periods(self, employee_ids, start, stop):
TBH, I am not sure it is needed to add sudo inside that method. That method could be called somewhere else in which the user has access to the employees and their contracts.

I think it would be better to call that method in sudo if it is needed (In our case, it would probably be the case).

2025-05-16 05:58 UTC, kthe-odoo commented on addons/hr_contract/models/hr_employee.py
> +    def _get_employee_working_periods(self, employee_ids, start, stop):
Agree !!!

2026-02-05 13:20 UTC, xavierbol reviewed
don't forget to change the commit title since hr_contract no longer exists. 🙂 

The code looks good, I will check detail in RD Review.

2026-03-27 08:53 UTC, xavierbol reviewed
Thanks for your work, I left one comment. 🙂

2026-03-27 08:53 UTC, xavierbol commented on addons/hr/models/hr_employee.py
> +            contracts = self.sudo()._get_versions_with_contract_overlap_with_period(start.date(), stop.date())
Cannot we directly do that in the domain of `employees_with_contract`? 🤔

2026-03-30 14:34 UTC, kthe-odoo commented on addons/hr/models/hr_employee.py
> +            contracts = self.sudo()._get_versions_with_contract_overlap_with_period(start.date(), stop.date())
We had something like [this](https://github.com/odoo/enterprise/pull/59884/changes#diff-2d3ccc086e0304e15e1aa3da45a8c3a342a5d411a907e77fc3a58086c3e1e105R33-R64) earlier, in which we need a separate array `employees_with_contract_in_current_scale` to know if user has contract and others as normal reject cases.

It was changed further changed in [here](https://github.com/odoo/enterprise/pull/83136/changes#diff-df53abdd36815e469e2fde8c5ff52a5dc9cf02878c9ec5cb3db32916cbd218cfR2399-R2451) and finally [here](https://github.com/odoo/enterprise/pull/93618/changes#diff-e461df1e784f21b4b8af6e3b8d218a8c1704ae29ab4da52be08fc6957786bf17R2682-R2734), but we always separate users with contract in current scale (those who may not have contract outside the current scale) and those who don't have. So two results opposing results in one read_group ?

I don't think it is possible, earlier we tried in a PR and chose to do this anyways. Did you have any other idea that might fit this exact use-case ? 🤔

2026-05-05 07:48 UTC, xavierbol commented on addons/hr/models/hr_employee.py
> +            contracts = self.sudo()._get_versions_with_contract_overlap_with_period(start.date(), stop.date())
Actually, I did not understand the purpose of `employees_with_contract` that's why I ask "why not including the contracts in the domain of `employees_with_contract`.

Maybe just a search could be sufficient.

Or we could do:


```suggestion
            employees_with_contract = self.env["hr.version"].sudo().search_fetch(
                domain=[
                    ("employee_id", "in", self.ids),
                    ('contract_date_start', '!=', False),
                ],
                fields=["employee_id"],
            ).employee_id
            contracts = employees_with_contract.sudo()._get_versions_with_contract_overlap_with_period(start.date(), stop.date())
```

But if the employees with contract have many versions we could have a performance issue, that's why it would surely be better to do it in search instead of using `_get_versions_with_contract_overlap_with_period`.

And so, we will have:


```suggestion
            employees_with_contract = self.env["hr.version"].sudo().search_fetch(
                domain=[
                    ("employee_id", "in", self.ids),
                    ('contract_date_start', '!=', False),
                ],
                fields=["employee_id"],
            ).employee_id
            contracts = employees_with_contract.sudo().search([
                ('contract_date_start', '!=', False), ('contract_date_start', '<=', stop.date()),
                '|', ('contract_date_end', '>=', start.date()), ('contract_date_end', '=', False),
            ])
```

2026-05-05 07:48 UTC, xavierbol commented on addons/hr/models/hr_employee.py
> +                if employees_with_contract.get(employee):
```suggestion
                if employee in employees_with_contract:
```

2026-05-11 12:26 UTC, xavierbol commented on addons/hr/models/hr_employee.py
> +                    continue
Does it not equivalent to:


```suggestion
            for employee in self - employees_with_contract:
```
? 🤔

2026-05-26 07:41 UTC, xavierbol commented
robodoo r+

2026-05-27 01:42 UTC, closed without merging