[IMP] point_of_sale, pos_restaurant: UI changes
odoo/odoo pull request #191929
Opened 2024-12-27 14:27 UTC by manv-afk

task-4331054

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-31 11:17 UTC, davidmonnom requested changes

2024-12-31 11:17 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/components/inputs/input/input.xml
>                  <i t-if="state.isOpen" class="fa fa-arrow-right"/>
props

2024-12-31 11:17 UTC, davidmonnom commented on addons/point_of_sale/static/src/app/components/popups/product_info_popup/product_info_popup.xml
> +                        <label class="fw-bold">Margin:</label>
Can you check `_hasMarginsCostsAccessRights` seems to be forgotten at some places

2025-01-02 09:10 UTC, manv-afk commented
@davidmonnom concerning the `input` component, the `isOpen` state was already used in the component itself, I've just added a callback to get this state in the parent, tell me if you have other ideas. Other requested changes are done

2025-01-02 14:26 UTC, davidmonnom approved these changes
@robodoo r+

2025-01-02 16:56 UTC, closed without merging