[FIX] account: prevent an error when print and send an invoice
odoo/odoo pull request #192020
Opened 2024-12-30 13:31 UTC by mega-odoo

Currently, an error occurs when attempting to print and send an invoice that is in a draft state.

Step to produce:

- Install the `account` module.
- Go to Invoicing / Customers / Invoices, Create one invoice without a customer and invoice line, and come to the list view of Invoices.
- Select this invoice and click on 'Print & Send'.

AttributeError: 'bool' object has no attribute 'replace'

The issue occurs because the system attempts to replace the name at [1] to generate a PDF file name. But the invoice's name is not available.

Link [1]: https://github.com/odoo/odoo/blob/41de88b930e569daea7624ee3655cef218f9136f/addons/account/models/account_move.py#L5739

To resolve this, raise a user error if the user tries to send an invoice that is in a draft state.

Sentry-6185757435

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-30 13:31 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/192020.png)](https://mergebot.odoo.com/odoo/odoo/pull/192020)

2024-12-31 09:03 UTC, maan-odoo commented on addons/account/models/account_move.py
> +        if any(move.state == 'draft' for move in self):
```suggestion
        if any(move.state != 'posted' for move in self):
```

2024-12-31 09:04 UTC, maan-odoo commented on addons/account/models/account_move.py
> +            raise UserError(_("You can't Send & Print invoice(s) in draft state."))
```suggestion
            raise UserError(_("You can't Print & Send invoices that are not posted."))
```

2024-12-31 09:13 UTC, maan-odoo commented
There is a `_check_move_constrains` already avaliable in the `account.move.send`
Should we reuse that?

2025-01-01 06:37 UTC, mega-odoo commented
Hello @odoo/sentry_reviewers

Please review this PR.

Thanks!

2025-01-07 09:19 UTC, aboo-odoo reviewed
LGTM! Thanks a lot, I'm passing you down to @rugo-odoo

2025-01-09 14:01 UTC, rugo-odoo requested changes
The change is good but the commit's message not so much :grimacing:.

For example, this:

> To resolve this, raise a user error if the user tries to send  an invoice that
> is in a draft state.

Is not correct (anymore).

We should rework it a bit.

2025-01-18 18:18 UTC, mega-odoo commented
> The change is good but the commit's message not so much 😬.
> 
> For example, this:
> 
> > To resolve this, raise a user error if the user tries to send  an invoice that
> > is in a draft state.
> 
> Is not correct (anymore).
> 
> We should rework it a bit.

The commit's message has been changed :)

2025-01-27 12:57 UTC, rugo-odoo approved these changes
@robodoo r+

2025-01-27 16:20 UTC, closed without merging