[FIX] website: s_tab elements do not get shift tabbed
odoo/odoo pull request #192024
Opened 2024-12-30 14:00 UTC by dabo-odoo

Before the change in the s_tab snippet the tab elements would get indented when the tab key is pressed.

Steps to reproduce:
- Open the website app
- Open any page in edit mode
- Add an s_tab snippet
- Click on any of the buttons generated by the s_tab
- Press tab
- The button gets indented in a list

After the change the buttons in the s_tab snippet do not get indented when the tab key is pressed and instead a tabulation is added to the text of the selected button.

task-4426975

2024-12-30 14:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/192024.png)](https://mergebot.odoo.com/odoo/odoo/pull/192024)

2025-01-15 12:41 UTC, SergeBayet requested changes
LGTM :+1: with some comments, see below.

2025-01-15 12:41 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
> +            const closestDiv = closestElement(sel.anchorNode, 'div');
I know it's not the case in this file (and in the web_editor team), but we tend to call the HTMLelement variables with the `el` suffix. Here it should be `closestDivEl`
And don't forget to use double quotes for literal strings.

2025-01-15 12:41 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
> +            } else if ((closestDiv && closestDiv.classList.contains('s_tabs_nav')) || !ev.shiftKey && sel.isCollapsed && !closestTableOrLi) {
You can use optional chaining in this case, it's shorter and also more readable.
Don't forget the double quotes. :+1:

2025-01-15 13:24 UTC, SergeBayet commented on addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
> +            } else if ((closestDiv && closestDiv.classList.contains('s_tabs_nav')) || !ev.shiftKey && sel.isCollapsed && !closestTableOrLi) {
@dabo-odoo You can inspire you of /addons/website/static/src/snippets/s_popup/000.js to handle the `ev.key`

2025-01-17 08:00 UTC, SergeBayet commented on addons/website/static/src/snippets/s_tabs/000.js
> +                if (closestElement(this.el.ownerDocument.getSelection().anchorNode, "div").classList.contains("s_tabs_nav")) {
Be cautious with this statement `closestElement(this.el.ownerDocument.getSelection().anchorNode, "div")`
Are you sure that it always returns an element?

2025-01-24 07:43 UTC, dabo-odoo commented on addons/website/static/src/snippets/s_tabs/000.js
> +/** @odoo-module */
Had to keep this since when I tried to remove it the 16.0 runbot gave me errors regarding the module.
https://runbot.odoo.com/runbot/batch/1768845

2025-01-24 07:44 UTC, dabo-odoo commented on addons/website/static/src/snippets/s_tabs/000.js
> +                if (closestElement(this.el.ownerDocument.getSelection().anchorNode, "div").classList.contains("s_tabs_nav")) {
I fixed this but could not use the ?. syntax since in version 16.0 eslint does not recognize it.
https://runbot.odoo.com/runbot/build/73509528

2025-01-31 06:41 UTC, SergeBayet approved these changes

2025-02-13 09:26 UTC, closed without merging

2025-02-13 09:26 UTC, qsm-odoo commented
After discussion: the bug does not seem to be there in master anymore and not in the new editor lib either. So let's choose to ignore it in stable as the editor team apparently already did