[IMP] website_sale: hide empty eCommerce categories
odoo/odoo pull request #192026
Opened 2024-12-30 14:37 UTC by lipiraux

To avoid displaying empty or not yet published categories, we need to adapt the visibility of it.

This PR limits access of public/portal users to only see eCommerce that contain published products. eCommerce categories mega-menus where also updated to reflect that change.

This PR also adds a new "group by eCommerce categories" filter on the website_sale.product_view.

task-4325764

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-12-30 14:37 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/192026.png)](https://mergebot.odoo.com/odoo/odoo/pull/192026)

2025-01-09 16:34 UTC, livaios requested changes

2025-01-10 16:22 UTC, lipiraux commented on addons/website_sale/security/ir_rules.xml
> +        ]"/>
Good remark. I pushed a change but Im not sure about the solution. Whats your opinion?

2025-01-14 08:22 UTC, lipiraux commented on addons/website_sale/security/ir_rules.xml
> +        ]"/>
Hey @livaios, I pushed yet another solution, which is better IMO 😅 . 

In my head, access rights should be clear: only designers can see empty categories, anyone else can only see published ones. But, this kind of rules is hard to translate into `ir.rule` because global rules are, as the name implies, global, and can’t be overridden even if the user is part of a group that has full access.

The first solution works but is not pretty. The second one is less restrictive but works in most cases.

2025-01-14 10:46 UTC, lipiraux commented on addons/website_sale/security/ir_rules.xml
> +        ]"/>
But then, they will not have access to published ones 😅 . I could move the restricted editor to have full access as well?

2025-01-15 09:02 UTC, lipiraux commented
So, I rewrote the commit history to be conform to the spec. The second solution is IMO better as it does not use global rules with a weird domain restriction. But, I'll let the final reviewer be the judge on this. (And you of course 😄)

2025-01-15 10:23 UTC, livaios approved these changes
Good work on that, I really appreciate the cleanup of the category getter on megamenu templates

Other than the small comment it LGTM

2025-01-15 11:30 UTC, lipiraux commented on addons/website_sale/views/snippets/s_mega_menu/image_menu.xml
>                                  <t t-foreach="category.child_id" t-as="sub_category">
Your right, I didn't think about that. Looping in a template is not efficient at all, better to filter in python before looping. Thanks for this, I just learned something 😊

2025-04-07 09:14 UTC, Feyensv commented on addons/website_sale/models/product_public_category.py
> +    has_published_products = fields.Boolean(compute='_compute_has_published_products', recursive=True, store=True)
Do you really need to store this field ?
Did you try using a `search` method to handle searches on the field ?

`has_published_products = fields.Boolean(search='_search_has_published_products')`

2025-04-07 09:14 UTC, Feyensv commented on addons/website_sale/views/snippets/s_mega_menu/image_menu.xml
> +                                <t t-foreach="category.child_id.filter(lambda c: c.product_tmpl_ids.is_published)"
probably breaks, since it's `filtered` :eyes:

2025-04-10 07:55 UTC, lipiraux commented on addons/website_sale/views/snippets/s_mega_menu/image_menu.xml
> +                                <t t-foreach="category.child_id.filter(lambda c: c.product_tmpl_ids.is_published)"
🫣

2025-04-10 09:48 UTC, lipiraux commented on addons/website_sale/models/product_public_category.py
> +    has_published_products = fields.Boolean(compute='_compute_has_published_products', recursive=True, store=True)
yeah, I had tested but struggled with the recursive aspect. But I found a way with the 'parent_of' operator.

2025-04-23 16:00 UTC, chevalierv reviewed
Hello @lipiraux 

LGTM except for the two changes

Have a nice day!

2025-04-24 09:12 UTC, chevalierv commented on addons/website_sale/views/templates.xml
> +                        t-att-data-publish="c.has_published_products and 'on' or 'off'"
As discussed, this is used for styling, and it's best to keep it this way to maintain consistency in how hidden elements are styled for public users.

2025-04-24 12:05 UTC, chevalierv approved these changes
Hello @lipiraux 

Good job on this task! Kudos for adding unit tests 🎉 

robodoo r+

Have a nice day!

2025-04-24 12:05 UTC, robodoo commented
@chevalierv you may want to rebuild or fix this PR as it has failed CI.

2025-04-24 14:32 UTC, chevalierv commented
robodoo override=ci/style
reason: Comment indeed start with a `#`, as every other comment in the file.

2025-04-24 14:32 UTC, robodoo commented
@chevalierv you are not allowed to override 'ci/style'.

2025-04-24 14:57 UTC, chevalierv approved these changes
robodoo r+

2025-04-25 07:43 UTC, d-fence commented
robodoo r-
([seems to break stagings](https://runbot.odoo.com/runbot/build/79080081))

2025-04-25 09:08 UTC, lipiraux commented
Hello @d-fence sorry for that

2025-04-25 10:55 UTC, chevalierv commented
robodoo r+

2025-04-25 18:04 UTC, closed without merging