[FIX] l10n_in_hr_holidays: fix sandwich leave warning sign
odoo/odoo pull request #192071
Opened 2024-12-31 07:10 UTC by dhka-odoo

The warning sign for sandwich leave is positioned vertically.
 It should be displayed horizontally.

task-4435090

2024-12-31 07:10 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/192071.png)](https://mergebot.odoo.com/odoo/odoo/pull/192071)

2025-01-20 12:29 UTC, kais-odoo commented on addons/l10n_in_hr_holidays/views/hr_leave_views.xml
> +            <xpath expr="//group[@name='col_left']" position="after">
We avoid xpath change in older versions you can do it in the latest version.

2025-01-21 14:50 UTC, Flotchet requested changes
thanks for you work

you should change your commit message 
it should be
- step to reproduce
- behavior before the fix
- the cause/explanation
- behavior after the commit

2025-01-23 13:59 UTC, Flotchet approved these changes
LGTM

2025-01-24 13:23 UTC, tivisse commented
@robodoo r+

2025-01-24 15:33 UTC, closed without merging