[FIX] stock_account: also don't create accounting entries in fifo vac…
odoo/odoo pull request #23316
Opened 2018-02-26 09:10 UTC by jco-odoo

…uum that would round to zero

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2018-02-26 11:25 UTC, sle-odoo requested changes
i think you better float_round everything in this method

2018-02-26 11:56 UTC, jco-odoo commented
As discussed, I am afraid we won't be able to float_round in a consistent
way between price_unit / remaining_value / quantities, so this rounding "at
the end" is a good method.

On Mon, Feb 26, 2018 at 12:26 PM, Simon Lejeune <notifications@github.com>
wrote:

> *@sle-odoo* requested changes on this pull request.
>
> i think you better float_round everything in this method
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/pull/23316#pullrequestreview-99264471>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADp7e0MkyWwDZ9W2h9mbHX2dou1JRFIvks5tYpTdgaJpZM4SS4z_>
> .
>

2021-04-21 09:16 UTC, yelizariev commented
Fixed here https://github.com/odoo/odoo/pull/28751

2021-04-21 09:25 UTC, closed without merging

2021-04-21 09:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/23316).

2021-04-21 09:26 UTC, robodoo commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.