[FIX] website_sales: wrong multi-lang in website_sale.dashboard_sales
odoo/odoo pull request #26067
Opened 2018-07-31 07:21 UTC by davidtranhp

The problem comes from how a language handle things like "Last week,
last month, last year".

For example, in Vietnamese, the "last" comes after the "week"/"month"/"year"
instead of doing before like what is in English. We say "Tuần trước", where "Tuần" means "week", not "last".

Before this commit, there is no way for the right translation into Vietnamese for the clause that was combined by `Sales Since Last <t t-esc="widget.date_range"></t>`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-09 13:31 UTC, JKE-be commented
@mart-e good fix, but for which version ?

2020-10-12 08:15 UTC, mart-e requested changes
Thanks for the PR !

> good fix, but for which version ?

`11.0` is no longer supported and as this bug is more on the "bugprovement" side, I would target the `14.0` branch (still early, still accepts changes of translatable content).

- Don't forget to update the `.pot` file too to reflect the changes
- still keep the old term as `t-else` in case there is another `date_range` in the selection
- use spaces not tabs

2020-10-19 09:27 UTC, mart-e commented
Thanks for the update, it looks good now :+1: 
@robodoo r+

2020-10-19 09:58 UTC, davidtranhp commented
> Thanks for the update, it looks good now 
> @robodoo r+

@mart-e all checks have passed now, please help merge. Tks!

2020-10-19 10:14 UTC, mart-e commented
@davidtranhp if you push in the branch after my r+, that will invalidate it ;-)
@robodoo r+ again please

2020-10-19 10:15 UTC, mart-e approved these changes

2020-10-19 11:37 UTC, closed without merging

2020-10-26 13:52 UTC, JKE-be commented on addons/website_sale/static/src/xml/website_sale_dashboard.xml
> +                                <h2>Sales Since Last Week</h2>
or not :/ Why add a h2 here...

h2 into h2 break the layout :'(

Will be fixed by https://github.com/odoo/odoo/pull/60737