Master stock split moves kic
odoo/odoo pull request #30878
Opened 2019-02-06 11:46 UTC by kic-odoo

Description of the issue/feature this PR addresses:
Task ID - https://www.odoo.com/web#id=1912896&action=327&model=project.task&view_type=form&menu_id=4720
Pad - https://pad.odoo.com/p/r.83e35586ce65fb5c181f217f30cd21b6

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-02-06 21:21 UTC, fmdl requested changes

2019-02-06 21:21 UTC, fmdl commented on addons/stock/models/stock_move.py
> +        total_org = sum(qty for qty in self.move_dest_ids.mapped('move_orig_ids.product_uom_qty'))
it is multi unit proof (what happend if move_orig_ids are diffrent unit) ?

2019-02-06 21:21 UTC, fmdl commented on addons/stock/models/stock_move.py
> +        total_dest = sum(qty for qty in self.move_dest_ids.mapped('product_uom_qty'))
don't need for loop
total_dest = sum(self.move_dest_ids.mapped('product_uom_qty')

2019-02-06 21:21 UTC, fmdl commented on addons/stock/models/stock_move.py
> +                    if qty_split == dest_move.product_uom_qty:
maybe use `float_compare`

2019-02-06 21:21 UTC, fmdl commented on addons/stock/models/stock_move.py
> +                    elif qty_split > 0:
maybe use `float_compare`

2019-02-06 21:21 UTC, fmdl commented on addons/stock/models/stock_move.py
> +    def split_mts(self):
get a private methode (with underscore)  `def _split_mts(self):`
and add `self.ensure_one()`

2024-04-16 11:27 UTC, C3POdoo commented
Dear @kirti-c,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 11:27 UTC, closed without merging