[ADD] account_generator: generate dummy data
odoo/odoo pull request #34814
Opened 2019-07-12 08:33 UTC by william-andre

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-07-12 11:35 UTC, mreficent commented
Couldn't this be merged in `account_test`? 🤔

2019-07-13 07:22 UTC, gdgellatly commented on addons/account_generator/models/generator.py
> +            create_vals.append({
would be nice to see all the val acquisitions split out to _prepare_* methods if this is for any kind of demo usefuleness

2020-01-23 18:32 UTC, pedrobaeza commented
Coming to this through codetriage.com. Is this still relevant?

2020-01-24 08:51 UTC, william-andre commented
It is put on the side ATM but not abandoned

2020-02-03 12:41 UTC, oco-odoo requested changes

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/generator.py
> +        self.env.su = True
Why not just doing a sudo() ?

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/generator.py
> +    journal_excluded_ids = fields.Many2many('account.journal', relation="generator_excluded_journal")
What's the point of these excluded journals and accounts? I don't see any real added value in using that.

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/generator.py
> +        _logger.info('Start Create')
Maybe also log the model name

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/generator.py
> +        self.env.su = True
sudo() ?

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/generator.py
> +    def _get_records(self):
We only call it once; so do we need this function ?

2020-02-03 12:41 UTC, oco-odoo commented on addons/account_generator/models/cleaner.py
> +        self.env.cr.execute('delete from account_move where company_id in %s;', [company_ids])
Can't this cleaner stuff be a little too dangerous when ran on a production db? The simple fact people could install that themselves gets me worried... Or maybe with something prompting the user like "are you really really 100% super certain that you want to do that?". But even so, I find it dangerous.

2020-04-01 14:17 UTC, william-andre commented
Not needed anymore since the populate mechanics

2020-04-01 14:17 UTC, closed without merging