[FIX] account, purchase, sale, stock: clear warning msg when no-message selected
odoo/odoo pull request #36694
Opened 2019-09-11 11:58 UTC by Florimond

-Go in Contacts, tab "Internal notes" and click Edit.
-Select "Blocking Message" for "Warning on the Sales Order", write a message
and save.
-Edit again, and select "No Message" instead of "Blocking Message", then save.

Before this commit:

The message won't appear when creating a sales order, but it's still showing
in the Internal Notes tab. It's impossible to clear it.

After this commit:

The warning message is cleared when saving with "No Message" selected.

Same principle for "Warning on the Picking", "Warning on the Invoice",
and "Warning on the Purchase Order".

OPW: 2069977

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-09-11 12:04 UTC, Florimond commented
@kebeclibre

2019-09-12 06:51 UTC, nim-odoo requested changes
I'd rather clear the message when "no-message" is selected in the contact.

2019-09-12 11:30 UTC, nim-odoo approved these changes
ok, but I will merge when forward-bot works better

2022-01-04 13:22 UTC, C3POdoo commented
Dear @Florimond,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2022-01-04 13:22 UTC, closed without merging