[FIX] mail: mail header names escape
odoo/odoo pull request #41519
Opened 2019-12-09 08:30 UTC by len-odoo

Fine-tuning of commit 55754c6af174dfe9cc8a1a1d1cf968aa305b6b3b

By https://tools.ietf.org/html/rfc2822#section-3.4,
we have that the address headers are of the form
$address(, $address)* with address = $addr-spec | name <$addr-spec>
where name can be quoted and/or encoded if needed,
depending on the presence of special characters (", ") or unicode ones.
If it's not necessary, no encoding is performed, everything is ASCII.

So the task is to segment the header, decode the encoded parts, then
write it as a decoded string that can be segmented back to get the
(name?, address) couples.
Decode header returns a list of couples (dstr, encoding) for each dstr
encoded differently in the header.
It does not segment the tokens semantically.
If we have =?UTF-8?B?8J+QpyBwZW4gcGVuIPCfkKc=?= <pen@oobo.com>, then
we have two dstr, one for the name and one for the address.
If we have "a1@a.com, a2@a.com" there is only one dstr, which is already
ASCII.

In the first case we should look to see if the name needs to be quoted
because we decode the header, so we need to make sure it can be
segmented after our operation.
In the second case we decode nothing, so there is nothing to do;
it's the responsibility of the mail sender to make sure that it can
be segmented.

What happens if we quote such a string it that "a1@a.com, a2@a.com"
becomes a name, instead of a couple of addresses.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-12-09 08:50 UTC, Julien00859 requested changes

2019-12-09 08:50 UTC, Julien00859 commented on odoo/tools/mail.py
> +                for a, b in getaddresses([smtp_header])
f, g, h, n, p, a, b ????

2019-12-09 08:51 UTC, len-odoo commented on odoo/tools/mail.py
> +                for a, b in getaddresses([smtp_header])
There aren't any shorter variable names, unfortunately.

2019-12-10 08:29 UTC, Julien00859 approved these changes

2019-12-20 11:42 UTC, len-odoo commented
@Julien00859 
I'll leave you decide what should be done with it. 
We checked with ODO and indeed it's not necessary with Python's native decoding of the headers, it puts the quotes when needed so provided examples worked as expected without any other fix. 

Since the code is a bit long and departs much from the initial one, it makes sense to put it in another function. His second suggestion was that we could do something like your proposed fix, which was to check the encoding: in case it's None, then there's nothing to do; so by rewriting it a bit it could be done in two steps, one to check if there might be a need to do something, in which case we go through the fix, and otherwise we just go through the old simple squash.

Besides that we discussed the potential pitfalls and that such fixes should probably be partially deployed at first to check for unexpected issues. 

Note that from what have been said, the issue is present in all versions before 13.0. (the idea was to backport it once it was checked as working properly - it was reported in 11 if you follow all PR links)

Good luck (or good closing)!

2020-07-23 11:21 UTC, Julien00859 commented
Fixed in #51985

2020-07-23 11:21 UTC, closed without merging