[IMP] hr_fleet: license plate is display on the employee
odoo/odoo pull request #43491
Opened 2020-01-17 13:39 UTC by ppr-odoo

Pad:https://pad.odoo.com/p/r.d74ee89df60138e4cc2a572a0f063ad4
Task:https://www.odoo.com/web#id=2158962&action=327&model=project.task&view_type=form&menu_id=4720

2021-03-03 14:50 UTC, kba-odoo requested changes

2021-03-04 09:46 UTC, ppr-odoo commented on addons/hr_fleet/models/fleet_vehicle.py
> +            for vahicle in self:
@kba-odoo changes done
cc @mba-odoo

2021-05-10 14:03 UTC, ppr-odoo commented
task cancelled

2021-05-10 14:03 UTC, closed without merging

2021-05-11 12:14 UTC, Williambraecky commented
Restored then deleted branch to cherry pick commit