[FIX] survey: allow access to survey at deadline date
odoo/odoo pull request #48976
Opened 2020-04-03 13:03 UTC by alt-odoo

We should compare date and not datetime in order to allow the survey to be
visible on the deadline date.

Description of the issue/feature this PR addresses:
opw-2229582

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-04-03 13:22 UTC, alt-odoo commented
@fw-bot up to 12.0

2020-04-03 13:33 UTC, rim-odoo commented
Well, `datetime` is a date+time field that allows specifying a precise time during the day... https://github.com/odoo/odoo/blob/12.0/addons/survey/models/survey.py#L700

I think that we better fix it by changing ` dt_now` to `fields.Datetime.context_timestamp()` (== "now", in the same timezone than the user?)

By the way, why deactivating the fwport?

2020-04-03 13:34 UTC, rim-odoo requested changes
Well, `datetime` is a date+time field that allows specifying a precise time during the day... https://github.com/odoo/odoo/blob/12.0/addons/survey/models/survey.py#L700

I think that we better fix it by changing ` dt_now` to `fields.Datetime.context_timestamp()` (== "now", in the same timezone than the user?)

By the way, why deactivating the fwport?

2020-04-03 14:47 UTC, alt-odoo commented
The problem is coming from Appraisal where date_close field is a date passed to deadline field of survey.user_input. So if I just adapt using now in the timezone of the user it will not be enough.

I have adapted so if the user_input is linked to an appraisal it takes 23:59:59 instead.

And I disabled the forwardport because of major refactor of survey/appraisal in >=13.0 and the initial issue cannot be reproduced anymore

2020-04-07 06:37 UTC, closed without merging

2020-04-07 06:39 UTC, alt-odoo commented
Other solution here : 

https://github.com/odoo/enterprise/pull/9701

2020-04-07 09:04 UTC, rim-odoo commented
> Other solution here :
> 
> [odoo/enterprise#9701](https://github.com/odoo/enterprise/pull/9701)

You anticipated my remark ;) if the issue comes from the appraisal module, it should be fixed there ;)