[IMP] http_routing: remove pointless redirection
odoo/odoo pull request #51813
Opened 2020-05-25 13:09 UTC by rim-odoo

There appears to be no reason to redirect routes like
  `/website/translations/<hash>`
to
  `/la_NG/website/translations/<hash>`
as this route only takes care of the language(s) passed as a parameter

We save one HTTP call here and potential failures while
redirecting (eg: #44110 opw-2259778 ).

2020-05-25 13:13 UTC, rim-odoo commented
PS: Fix done in master, as it works in standard, I chose the low risk/value ration :)

2020-05-25 13:27 UTC, mart-e approved these changes

2020-05-25 14:08 UTC, JKE-be commented
wait before merge

not sure ! I asked to rde to check recently.
And from memory it is not useless !!

2020-05-25 14:23 UTC, JKE-be requested changes
I confirm

It is wrong,

since the hash use the lang from user_context and not from request.
Keep the redirect will force to not use wrong cached lang

2020-05-25 14:47 UTC, rim-odoo commented
> since the hash use the lang from user_context and not from request.

Ok, good to know. Subsequent question: why does the hash rely on the lang?

2020-05-25 14:48 UTC, JKE-be commented
About you opw, the problem is the wrong configuration of nginx and not this one.

I have probably 5 issues closed with the nginx problem in the last year!
Each time, issues is open with the same comment.
But this redirect will just show you that you have misconfigured your nginx, but remove it will not fix your nginx ;)

2020-05-25 14:50 UTC, JKE-be commented
you question should be: why the hash don't use the request.lang?
Good question, probably because it has been dev by framework js initially and that they use the context ;)

The hask need to be invalidated according the lang ! because purpose is to force a redownlaod of this file according to the current lang ;)
So the redirect for now force this re-download, once by lang.

2020-05-25 14:54 UTC, JKE-be commented
As explain by the guy that open the initial issue, his error as a missing header.

You need to launch Odoo in proxy mode and use header X-Forwarded-Host $host;  with Nginx.

2020-05-25 15:04 UTC, rim-odoo commented
> I have probably 5 issues closed with the nginx problem in the last year!

Well, it's a bit nasty, because you don't think to check your Nginx proxy settings when you have an issue in loading the translations :s 

> The hash need to be invalidated according the lang

Yep, but lang is a GET parameter ANYWAY. There is some room for a future optimisation here I think ^^

Thanks for the explanations Jeremy, I'm closing this PR.

2020-09-11 09:57 UTC, rim-odoo commented
This issue also appears to be occuring with some Cloudflare settings, can we re-consider merging it as it does not bring any other issue? cc @Sehnde

2020-09-11 10:00 UTC, JKE-be commented
cannot be merge without hard test ! because this change is not a small detail. It will change the cached version by lang.

And do we really take risk to introduce bug of translation for wrong deploy.

Imo, no. And you will have patched this one, you will have other error later while you don't fix your deployment.

2023-11-13 21:24 UTC, closed without merging