[IMP] base : display bank in bank account
odoo/odoo pull request #51930
Opened 2020-05-26 20:07 UTC by fmdl

Description of the issue/feature this PR addresses:
When you make a payment, if a supplier have multi bank account, the bank name is not show in the selection. With the bank name it is more simple to find the good bank account (if you know the bank).

Current behavior before PR:
![image](https://user-images.githubusercontent.com/16716992/82945428-2fde4880-9f9d-11ea-875e-165453dd377d.png)

Desired behavior after PR is merged:
![image](https://user-images.githubusercontent.com/16716992/82945224-da09a080-9f9c-11ea-84bd-2e7a676ebf06.png)

@qdp-odoo 
@alexis-via 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-06-29 11:17 UTC, fmdl commented
OPW 2287217

2020-09-18 12:42 UTC, fmdl commented
ping @qdp-odoo

2020-10-03 08:50 UTC, fmdl commented
ping @oco-odoo @simongoffin

2020-10-07 09:07 UTC, oco-odoo commented
@tsb-odoo What do you think of that feature? (it's for master anyway)

2020-10-07 09:34 UTC, tsb-odoo commented
@oco-odoo IMHO, nice-to-have.

2020-10-07 11:40 UTC, oco-odoo requested changes

2020-10-07 11:40 UTC, oco-odoo commented on odoo/addons/base/models/res_bank.py
> +        return [(acc.id, '{} - {}'.format(acc.acc_number, acc.bank_id.display_name) if acc.bank_id else acc.acc_number)
The display_name of res.bank also contains the bic, which is not really useful to show here and makes the text longer and less readable. Instead, use acc.bank_id.name.

2020-10-13 13:43 UTC, oco-odoo commented
@fmdl Branch is red, you most probably need to rebase :)

2020-10-30 18:56 UTC, fmdl commented
ping @oco-odoo all green :-)

2020-11-02 14:09 UTC, oco-odoo commented
@robodoo r+ 
Thanks ! :)

2020-11-06 12:01 UTC, rdeodoo commented
@oco-odoo @fmdl  This one seems stuck

2020-11-06 14:07 UTC, oco-odoo commented
@d-fence Any idea why? :o

2020-11-06 14:13 UTC, d-fence commented
legal/cla ci was missing.
But the build is too old.
ci/security
and
ci/style are missing

2020-11-06 14:14 UTC, d-fence commented
I forced a new build

2020-11-06 14:50 UTC, oco-odoo commented
@fmdl Looks like it needs another rebase :/

2020-11-06 16:36 UTC, fmdl commented
@oco-odoo done

2020-11-06 17:15 UTC, d-fence commented
robodoo r+

2020-11-06 18:04 UTC, closed without merging