[IMP] website, *: login page customisation
odoo/odoo pull request #52719
Opened 2020-06-09 14:17 UTC by karlosvalverde

Now it's possible to enable a responsive side image, change its size and its
background position or even customise it, at the 'web/login' page. 

In the Customize header menu, there is a switch that enables this feature
and the user can select different options by using the Editor and selecting
this side image.

By default, this side image background is random, using the ones 
provided by Unsplash at 'https://source.unsplash.com/random', but the
user can choose any other desired option.

There are three Image Sizes:

1. Custom: 
allows the user to customise its width.

2. Small: 
it covers a 25% width of the viewport, with a fixed size but a fluid width in
smaller (< 720px) viewports. 

3. Big: 
it covers a 50% width of the viewport, with a fixed size but a fluid width in
smaller (< 720px) viewports.

It has also been added the 'background' and 'BackgroundPosition' snippet
options, which allows the user to change the background image and set
its background position. 

task-2118648

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-06-18 13:28 UTC, bvr-odoo requested changes
Hello Carlos, I made a first review of your code (before QSM or SRI I guess).
Do not hesitate to ask me if something is not clear ;).
I think your commits could have been only a single commit because its only small changes 
or changes to previous commits. (except for the fix).
I have a suggestion, it's add option to have a full page background like this https://imgur.com/a/HUaWp6q

2020-06-18 13:33 UTC, bvr-odoo commented on addons/web/static/src/scss/login.scss
> +    background: url(https://source.unsplash.com/random);
@sbuhl ?

2020-06-18 14:16 UTC, karlosvalverde reviewed
Thank you very much for your review!

I take note and, as a consequence, I'll carry out the following measures:

- I'll squash all the commits with the exception of the FIX one, where I'll give more context and details about it, as well as its task reference number.
- I'll 'beautify' the code, in order of not to have ugly whitespace characters when not needed.
- The hardcoded height in '.login_layout_opt' will be fixed in order to be fluid and to be adapted to the size of its container.
- I'll drop the unnecessary background values added to '.login_layout_opt' in the same way as any duplicated code in 'background'.

Let's see what does @sbuhl think about any changes to be applied on the size options and about the random source of the bg images.

2020-06-19 08:59 UTC, sbuhl commented on addons/web/static/src/scss/login.scss
> +    background: url(https://source.unsplash.com/random);
Yes, you can remove this random function.
Let's choose one picture per theme makes more sense.

2020-06-19 09:05 UTC, sbuhl commented on addons/website/views/website_templates.xml
> +            </we-select>
Agree with BVR on this one. 
I'd remove the whole setting "Image Size".
1. User choose to display "Side Image" with the customize option.
2. Default image selected per theme.
3. One may change the image through the Background setting.
4. One may change the size with handles.

2023-05-26 11:35 UTC, closed without merging