l10n_ch*: added QR-IBAN on bank account for Switzerland accounting
odoo/odoo pull request #55571
Opened 2020-08-06 13:52 UTC by rgo-odoo

Task: <a href="https://www.odoo.com/web?#action=4043&cids=2&id=2307262&menu_id=4720&model=project.task&view_type=form">2307262</a>

2020-08-27 11:34 UTC, yvaucher requested changes
QR-IBAN from invoice.invoice_partner_bank_id.l10n_ch_qr_iban must also be displayed on the report here:

https://github.com/odoo/odoo/blob/13.0/addons/l10n_ch/report/swissqr_report.xml#L103

2020-08-27 13:26 UTC, fclementic2c commented
> QR-IBAN from invoice.invoice_partner_bank_id.l10n_ch_qr_iban must also be displayed on the report here:

Yes the report is not valid at the moment (just tested it with a customer)

2020-08-31 08:12 UTC, yvaucher commented
ping @jco-odoo

2020-08-31 08:15 UTC, jco-odoo commented
@yvaucher I am on it today.  (if you have any suggestions...)

2020-08-31 08:26 UTC, yvaucher commented
@jco-odoo great, it's just to notice you on it. Only the visible part of the report is not ok. The QR code contains already the good information. It's just  a matter of syncing the content of the QR-Code and the informations displayed on the report.

We need to support either a customer that reads the report and copy it by hand or a customer that scan the QR code.

2020-08-31 16:25 UTC, jco-odoo commented
@yvaucher @fclementic2c I still want to do some clean up/review, but this changes the report already.  Do QR-IBANs only work with IBAN bank accounts?  Because I would make the QR-IBAN field visible on the bank account when the subscription fields are visible as well.  

@tsb-odoo

2020-09-01 09:43 UTC, fclementic2c commented
Improvement suggestion @jco-odoo : Please add the QR IBAN field on the view : account.online.sync.res.partner.bank.setup.form from model : account.setup.bank.manual.config
Go to Accounting / Configuration / Add a bank account -> Create it

![screenshot-fclementic2c-swiss-accounting odoo com-2020 09 01-11_37_35](https://user-images.githubusercontent.com/5735158/91834188-fe35e700-ec47-11ea-8169-a3d632645865.png)

2020-09-01 09:47 UTC, yvaucher commented
@jco-odoo I understand that you ask if there are any other kind of bank account in Switzerland than IBAN that could use a QR-IBAN.

The answer is no.

All QR-IBAN have a bank account with an IBAN that lies behind, I see no exception.
When you are provided a QR-IBAN from a supplier you don't need to know the IBAN behind it.

When you generate QR-Bill, you know both your IBAN and the linked QR-IBAN.

2020-09-01 10:35 UTC, jco-odoo commented
@yvaucher I could add the condition again for only showing the field when it is IBAN, but I think the most important is to show it when it is about a company bank account like the subscription numbers.

2020-09-01 11:07 UTC, yvaucher commented
I agree with you, that field is intended for the company bank accounts. Hiding it based on `acc_type` could confuse the users.

When you go to setup your company bank and see the field afterward I would guess that a confused user would:

1. Create new bank account
2. Fill QR-IBAN in IBAN field
3. See the QR-IBAN that just appeared :confused: 
4. Set the QR-IBAN again but in the other fiield this time and curse the program or it's developpers.

2020-09-01 12:22 UTC, jco-odoo commented
@oco-odoo Can you have a quick look as well?

2020-09-01 14:13 UTC, oco-odoo requested changes
Also, I assume the idea is to merge this new module with l10n_ch when the forward-port reaches master?

2020-09-01 14:13 UTC, oco-odoo commented on addons/l10n_ch_qr/models/res_bank.py
> +        return res
```suggestion
        return super()._is_qr_iban() or self.l10n_ch_qr_iban
```

2020-09-01 14:24 UTC, jco-odoo commented on addons/l10n_ch_qr/__manifest__.py
> +    'category': 'Accounting/Localizations',
Indeed.  Apparently there was not much respect for it at the time.

2020-09-01 14:24 UTC, jco-odoo commented on addons/l10n_ch_qr/__manifest__.py
> +# -*- coding: utf-8 -*-
qr_iban tends to be a bridge module for qr and iban, so I suggest l10n_ch_qriban

2020-09-07 09:20 UTC, fclementic2c commented
@jco-odoo @oco-odoo Any chance to merge this ? it is a problem on our side. Thanks

2020-09-07 18:15 UTC, jco-odoo commented
@fclementic2c To me, this is ok to merge.  I just give a bit of time for the functional check.

2020-09-08 08:41 UTC, jco-odoo commented
@robodoo r+ rebase-ff

2020-09-08 08:41 UTC, robodoo commented
Merge method set to rebase and fast-forward

2020-09-08 10:15 UTC, closed without merging