[FIX] fix margin issue when an activity is marked done
odoo/odoo pull request #55576
Opened 2020-08-06 14:28 UTC by phenix-factory

task-2280172

----

#

2020-08-07 13:33 UTC, alexkuhn reviewed
A bit annoying that notes come from python template with `o_old_class_name_conventions`, but the biggest problem IMO is the use of CSS `+` operator. It's significantly fragile because style depends on position in layout, all this because we didn't want to name the `<div>`...

Unfortunately, we can't properly fix previous messages without these selectors...

I'm wondering if we should put a category `// legacy` in our SCSS, which defines ugly styles that we need to keep for old record fields in DB (no /s, I really mean it). The newer records should have fields with nice templates, so that selectors are nice too.

cc @seb-odoo

2020-08-07 13:33 UTC, alexkuhn commented on addons/mail/static/src/components/activity/activity.scss
> +}
This stylerule is really not nice... kinda a way to say "but don't apply bootstrap margin on <p> in these (broadly) cases".

2020-08-07 15:07 UTC, seb-odoo commented
This looks really bad on many levels, but after cleaning this up as much as possible, ok to put the crap must be kept in a legacy category.

2020-08-07 15:09 UTC, seb-odoo commented
In this particular case, if this is "just" to reduce a margin somewhere, and only for legacy stuff, I would seriously challenge the spec to avoid doing it, but instead ensure future occurrences will look good by default.

2020-08-14 12:59 UTC, phenix-factory commented
Ok, I'm confuse. What I should do here ?

2020-08-25 12:51 UTC, alexkuhn requested changes

2020-08-25 12:51 UTC, alexkuhn commented on addons/mail/static/src/components/activity/activity.scss
> +}
Fix is nice. Would just re-organize a bit styles like this:

```scss
// ------
// Layout
// -------

// [AKU] put this style in alphabetic order
.o_Activity_note p {
   margin-bottom: 0;
}

// [AKU] put these styles at the end of category
// From python template
.o_mail_note_title {
   margin-top: map-get($spacers, 2);
}

.o_mail_note_title + div p {
   margin-bottom: 0;
}
```

_(without the [AKU] comments)_

Best to have simple and flat selectors, and the ones that apply on stuffs from python template is best to isolate from the rest (hence why I suggest putting it at the end).

I feel it's off to have this separation of component template and python templates... But this fix is acceptable considering it doesn't break old activity notes.

2020-08-25 12:53 UTC, alexkuhn commented on addons/mail/static/src/components/activity/activity.scss
> +}
I'll make the change myself, just comment fyi ;)

2020-08-25 12:58 UTC, alexkuhn approved these changes
@robodoo r+

2020-08-25 14:20 UTC, robodoo commented
Staging failed: ci/runbot (view more at http://runbot.odoo.com/runbot/build/3973837)

2020-08-25 14:21 UTC, alexkuhn commented
@robodoo retry

2020-08-25 14:42 UTC, robodoo commented
Staging failed: ci/runbot on 2cc917bd6b4a8e9a4e67797739e07c6e2ee0863b (view more at http://runbot.odoo.com/runbot/build/3974158)

2020-08-25 14:45 UTC, alexkuhn commented
@robodoo retry

2020-08-25 15:57 UTC, closed without merging