Master fix filter on blockquote bvr
odoo/odoo pull request #56422
Opened 2020-08-24 13:46 UTC by bvr-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-09-23 09:59 UTC, qsm-odoo requested changes

2020-09-23 09:59 UTC, qsm-odoo commented on addons/web_editor/static/src/scss/web_editor.common.scss
> +section, .oe_img_bg, [data-oe-shape-data], .o_background_video, .parallax {
- background video is not a class of we_editor
- I made a localized fix for the Big Boxes snippet, I guess your fix is better though so you can remove my fix at the same time in this commit

2020-09-23 09:59 UTC, qsm-odoo commented on addons/web_editor/static/src/scss/web_editor.common.scss
> +    right: 0;
I merged a similar fix recently while fixing another bug so I guess you can just drop this part sorry

2020-09-23 09:59 UTC, qsm-odoo commented on addons/web/static/lib/bootstrap/scss/_carousel.scss
> +  position: absolute !important;
You are modifiying the lib... you cannot

2020-09-23 09:59 UTC, qsm-odoo commented on addons/web/static/lib/bootstrap/css/bootstrap.css
> +  position: absolute !important;
You are modifying the lib... you cannot

2020-09-23 09:59 UTC, qsm-odoo commented on addons/web/static/lib/bootstrap/scss/_carousel.scss
> +  position: absolute !important;
You are modifying the lib... you cannot

2020-09-23 13:09 UTC, bvr-odoo commented
@qsm-odoo I made the modifications

2020-09-29 11:59 UTC, qsm-odoo requested changes
- Multiple commits in the PR, you need to mention the PR link in each commit
- Review commit message: no uppercase, wrong mentioned apps, etc

2020-09-29 15:52 UTC, qsm-odoo commented
Does not receive CI/upgrade for some reason, let's try on another PR: https://github.com/odoo/odoo/pull/58850

2020-09-29 15:52 UTC, closed without merging