[FIX] mail: edit subtype subscriptions is not saved in some case
odoo/odoo pull request #56775
Opened 2020-08-31 07:01 UTC by sat-odoo

**Current behavior before PR:**

Currently the subtype checked selection is not saved when user  add and  remove
 subtypes.

**Desired behavior after PR is merged:**

The subtype checked selection will be saved when user add and  remove
subtypes.

**LINKS**

Task-2241688

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-16 14:44 UTC, tde-banana-odoo requested changes
Hello,

Could you provide a test case ? Failing without the patch and working with it. Please also give reproducible steps explaning how to trigger the bug and what is the actual issue.

Many thanks,

2020-11-16 14:44 UTC, tde-banana-odoo commented on addons/mail/models/mail_followers.py
> +                        if new_sids:
Already done here above. Maybe you want to prepare a list of commands, in which case this should not be done like that.

2020-11-16 14:44 UTC, tde-banana-odoo commented on addons/mail/models/mail_followers.py
> +                        if new_sids:
Same remark here.

2020-11-23 10:26 UTC, hbh-odoo commented
@tde-banana-odoo Done!

2021-01-27 12:23 UTC, tde-banana-odoo commented
@robodoo r+ rebase-ff

2021-01-27 12:24 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-01-27 12:59 UTC, closed without merging