[FIX] project: search on archived partners fix
odoo/odoo pull request #56937
Opened 2020-09-02 11:23 UTC by kat-odoo

Current behavior before PR:

While searching on archived partners in the project model,
this did not return any task.

Desired behavior after PR is merged:

While searching on archived partners in the project model,
this will return the tasks.

LINKS

PR 
task-2326885

2020-09-08 13:33 UTC, mart-e requested changes
> When the search task by archived partners,
> will not returning respective tasks.

Of course, that's on purpose. We don't want to see results from archived partners,
I wrote a comment on the task to discuss the purpose.

2020-09-08 13:34 UTC, rco-odoo commented
@kat-odoo can you please make the issue description explicit?
What is the domain to be searched for, and on which model?
Thanks!

2020-09-09 05:32 UTC, kat-odoo commented
> @kat-odoo can you please make the issue description explicit?
> What is the domain to be searched for, and on which model?
> Thanks!

@rco-odoo , I am a newbie. This is WIP task and not reviewed yet.  
The purpose of the task is when we search on partner_id with the operator "child_of" it should include the search for an archived partner.

Thanks

2024-04-16 09:00 UTC, C3POdoo commented
Dear @kat-odoo,

Thank you for your contribution but the version saas-13.5 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 09:00 UTC, closed without merging