[FIX] website: fix invisible parallax snippet issue
odoo/odoo pull request #57075
Opened 2020-09-04 09:27 UTC by xO-Tx

When Height option not forced (50% or 100% screen's height), the snippet
simply disappear if there is no content inside (default).

The 4e220bf commit makes parallax snippet empty by default and the
main goal of a8f0cee was to make "DRAG BUILDING BLOCK HERE" placeholders
appear only on drag, that's why we need to add a "min-height" for parallax
to keep it visible when the "Height" selected is auto.

IMPORTANT : this could be fixed by adding id="wrap" on ".oe_empty"
div in parallax snippet xml content, but this will add a "DRAG BUILDING BLOCK HERE"
placeholder too.

task-2327025

2020-10-12 13:48 UTC, qsm-odoo requested changes
In your commit message you say
> Important: this could be fixed by adding id="wrap" on ".oe_empty"
div in parallax snippet xml content, but this will add a "DRAG BUILDING BLOCK HERE"
placeholder too.

Remove that, this is not true. id="wrap" is meant to be unique on the page, and hold the page content.

A min-height of 25vh is too much of a change. People may use the parallax snippet for a 10px height line with some effect... @sbuhl ? Smaller value right ?

2020-10-12 13:49 UTC, qsm-odoo commented
Also, as explained before, all your PR targetting 13.5 has to be retargeted to 14.0 ;)

2020-10-12 13:58 UTC, sbuhl commented
@qsm-odoo Yes

2020-10-14 15:53 UTC, qsm-odoo approved these changes
@robodoo r+

2020-10-14 16:39 UTC, closed without merging