[FIX/IMP] web_editor: fix remove btn z-index in media dialog
odoo/odoo pull request #57324
Opened 2020-09-09 08:10 UTC by bvr-odoo

Add a z-index on remove btn in media dialog because before that the
button was hidden behind images. Also review a little bit the style of
the button.

task-2312878

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-09-23 10:13 UTC, qsm-odoo requested changes
Can you change the [FIX/IMP] en [FIX] ?

2020-09-23 13:11 UTC, bvr-odoo commented
> Can you change the [FIX/IMP] en [FIX] ?

Done :+1:

2020-09-25 08:59 UTC, qsm-odoo commented
@bvr-odoo The PR did not receive CI, could you rebase it? Thanks

2020-09-29 12:57 UTC, qsm-odoo commented
Don't know why this PR is not getting ci/template, let's try with a new PR: https://github.com/odoo/odoo/pull/58815

2020-09-29 12:57 UTC, closed without merging