[FIX] account: Invoice in Documents not linked to the original invoice
odoo/odoo pull request #57341
Opened 2020-09-09 10:07 UTC by backspac

Steps to reproduce the bug:
- Install Accounting and Documents
- Go to Documents configuration
- Enable Files Centralization > Accounting and save
- Still in Documents configuration, into "-> Journals", create a new Journal to Synchronize with:
  - Journal: Customer Invoices (USD)
- Go to Accounting > Customers > Invoices
- Create a new invoice with any customer and product and save
- "Post" then "Send & Print"
- On the dialog, "Send & Print" (confirm the report template if necessary)
- Go to Documents

Bug:
The document is missing the "related resource" link shortcut

opw:2332596

2020-09-09 12:31 UTC, backspac commented
robodoo r+

2020-09-09 12:31 UTC, robodoo commented
I'm sorry, @backspac. You can't review+.

2020-09-09 13:06 UTC, nim-odoo requested changes
OK for the fix, but in this case the commit message should be more explicit. Usually, a commit message has 3 parts:
1. How to reproduce the bug
2. What is the cause of the bug (optional)
3. How your modification fixes the issue (optional)

Part 1 is ok, but since the issue is quite subtle I think it makes sense to describe the part 2 in more details. In this case, you can write:

The context key `default_res_id` is propagated up to:

https://github.com/odoo/enterprise/blob/a6606f000e66e72b9f89d353552950652ab2045f/documents/models/document.py#L364

Consequently, the corresponding document is created with a `res_id`, but no `res_model`.

By adding the `default_res_model` context key, the document is created with the right `res_model`. Note that another solution would be to remove `default_res_id` from the context before creating the `document.document` and leave the `_compute_res_record` do the job. However, this could have a larger impact since it would affect all document creations.

2020-09-10 08:36 UTC, nim-odoo approved these changes
robodoo r+

2020-09-10 09:36 UTC, closed without merging