[FIX] l10n_es Created new IVA Exento No Sujeto tax
odoo/odoo pull request #57724
Opened 2020-09-15 11:17 UTC by HaraldPanten

According to the Spanish VAT reporting (mod 303), this commit has been created to fix some inconsistencies in section number 60.

Exempt taxes comming from training, for example, wouldn't be taken in consideration anymore.

closes https://github.com/OCA/l10n-spain/issues/1300

@pedrobaeza That's my first approach. Looking forward for your comments.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-09-15 11:41 UTC, pedrobaeza requested changes
Thanks for taking care of this

2020-09-15 11:41 UTC, pedrobaeza commented on addons/l10n_es/data/account_tax_data.xml
> +        <field name="name">IVA Exento Sujeto</field>
```suggestion
        <field name="name">IVA Exento Repercutido Sujeto</field>
```

2020-09-15 11:41 UTC, pedrobaeza commented on addons/l10n_es/data/account_tax_data.xml
> +        <field name="name">IVA Exento No Sujeto</field>
```suggestion
        <field name="name">IVA Exento Repercutido No Sujeto</field>
```

2020-09-15 14:13 UTC, pedrobaeza approved these changes

2020-09-15 14:15 UTC, pedrobaeza commented
@oco-odoo another change we have detected as missing for proper Spanish fiscal correctness. This new tax if for a special service nature that is not VAT subjected (although exempted), and thus it shouldn't go to model 303 (Spain is such weird, I know...).

2020-09-17 12:29 UTC, oco-odoo requested changes

2020-09-17 12:29 UTC, oco-odoo commented on addons/l10n_es/data/account_tax_data.xml
> +        <field name="tax_group_id" ref="tax_group_iva_0"/>
The module won't be installable. You're missing a `</record>` 
Always test your code ;)

2020-09-17 12:30 UTC, oco-odoo commented
> @oco-odoo another change we have detected as missing for proper Spanish fiscal correctness. This new tax if for a special service nature that is not VAT subjected (although exempted), and thus it shouldn't go to model 303 (Spain is such weird, I know...).

Haha, I'm Belgian, I know the feel XD No worries ;)

2020-09-17 13:17 UTC, oco-odoo commented
@HaraldPanten thanks :) 

@robodoo r+

2020-09-17 13:18 UTC, HaraldPanten commented
> @HaraldPanten thanks :)
> 
> @robodoo r+

Rushing is not good

2020-09-17 14:40 UTC, robodoo commented
Staging failed: ci/runbot on 5757c6db335409560b7e9459cc5c6de0d7d78c87 (view more at http://runbot.odoo.com/runbot/build/4236588)

2020-09-17 15:34 UTC, HaraldPanten commented
Did I miss anything? 🤔

2020-09-18 14:43 UTC, oco-odoo commented
@HaraldPanten Phantomjs tests sometimes gave false positives in older versions, it's not your fault ;)

@robodoo retry

2020-09-18 15:39 UTC, closed without merging