[IMP]hr_holidays: Possible leaks for models
odoo/odoo pull request #58168
Opened 2020-09-22 04:40 UTC by nit-odoo

Currently, no protection against following models.
- resource.calendar.leaves: created using leave.name -> accessible for example
  freely to project.user, mrp.user
- hr.leaves.report: no protection against reading name , accessible to all
  (no group)
- hr.leaves.report.calendar: no protection against reading name or grouping on
  name, accessible to all employees

So in this commit, for model  resource.calendar.leaves leave.name only visible
for All Approver and Administrator. And for model hr.leave.report we apply
a group.

Task-Id: #2314838

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-03-03 09:08 UTC, kba-odoo requested changes
Use `_()` to have the string translated

2021-03-03 09:08 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +            'name': "%s: Time Off" % (leave.employee_id.name),
```suggestion
            'name': _("%s: Time Off", leave.employee_id.name),
```

2021-03-03 09:08 UTC, kba-odoo commented on addons/hr_work_entry_holidays/models/hr_leave.py
> +                    'name': "%s: Time Off" % (leave.employee_id.name),
```suggestion
                    'name': _("%s: Time Off", leave.employee_id.name),
```

2021-03-03 10:29 UTC, mba-odoo commented on addons/hr_work_entry_holidays/models/hr_leave.py
> +                    'name': "%s: Time Off" % (leave.employee_id.name),
@kba-odoo , Done the changes. Thanks

2021-03-10 14:22 UTC, tivisse commented
@robodoo r+

2021-03-10 16:41 UTC, closed without merging