[FIX] payment: fix lang in context after online payment
odoo/odoo pull request #59096
Opened 2020-10-05 11:25 UTC by kitan191

- Go to Invoicing > Configuration > Payment Acquirers
- Install, activate and configure Stripe
- Go to Invoicing > Customers > Payments
- Toggle Studio and add Related Field (Partner > Country > Country Name) to list view
- Go to Sales and create a Quotation
- Send by email, open preview and copy preview link
- Open preview in a Web Browser configured in a language not supported by Odoo (i.e. Irish (Ireland) -> ga_IE)
- /!\ No user should be logged
- Pay the SO using Stripe
After the payment is processed, an Error is raised while trying to create translations
for unsupported lang "ga_IE".

When no user is logged, it can happen that the lang of web browser is retrieved
and stored in context.
It is then possible to have a lang that is not supported by Odoo in context.
That's what happens in this usecase and it crashes when Odoo tries to create
a translation for that lang after the execution of the payment.

Lang in context has to be checked and corrected to an installed lang before any operation
that could depend on it is executed.

opw-2302678

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-05 11:26 UTC, kitan191 commented
ping @nim-odoo

2020-10-06 06:42 UTC, nim-odoo requested changes

2020-10-06 06:42 UTC, nim-odoo commented on addons/payment/models/payment_acquirer.py
> +            self.env.context = dict(self.env.context, lang=lang)
You cannot do that.

```suggestion
            return self.with_context(lang=lang)
        return self
```

2020-10-06 06:42 UTC, nim-odoo commented on addons/payment/models/payment_acquirer.py
> +        self._check_context_lang()
```suggestion
        self = self._check_context_lang()
```

2020-10-06 07:26 UTC, nim-odoo approved these changes
robodoo r+

2020-10-06 08:17 UTC, closed without merging