[FIX] core: preferably flush() with an env with a real uid
odoo/odoo pull request #59225
Opened 2020-10-06 09:18 UTC by rco-odoo

This fixes a crash in some controllers with `auth='None'` where some
updates are flushed with an environment where `uid=None`.  When there is
an environment with a real uid, preferably use it.

2020-10-06 09:35 UTC, sts-odoo requested changes

2020-10-06 09:35 UTC, sts-odoo commented on odoo/sql_db.py
> +        if env._cr is cr:
```suggestion
        if env.cr is cr:
```

2020-10-06 09:35 UTC, sts-odoo commented on odoo/sql_db.py
> +            if env._uid is None:
```suggestion
            if env.uid is None:
```

2020-10-08 09:49 UTC, tbe-odoo approved these changes
Hello,
I agree with this change, but I think the variable naming can be improved to ease the code readability.

Thanks for the fix :+1:

2020-10-08 09:49 UTC, tbe-odoo commented on odoo/sql_db.py
> +    env1 = None
I suggest to use a more explicit variable name for the environment that need to be flushed

```suggestion
    env_to_flush = None
```

2020-10-08 10:46 UTC, rco-odoo commented
@robodoo r+

2020-10-08 11:45 UTC, robodoo commented
Staging failed: ci/runbot on 1ee007731cd33b144440c6cd7e632db5d07d3158 (view more at http://runbot.odoo.com/runbot/build/4479996)

2020-10-09 11:07 UTC, rco-odoo commented
@robodoo retry

2020-10-09 11:08 UTC, robodoo commented
I'm sorry, @rco-odoo. Retry makes no sense when the PR is not in error.

2020-10-09 11:57 UTC, rco-odoo commented
@robodoo r+

2020-10-09 12:46 UTC, closed without merging

2020-10-09 14:00 UTC, odony commented
A link to a ticket or some steps to reproduce would have been appreciated, or something more specific than "a crash in some controllers" ;-) It's a core piece of our transaction management, and the problem must be tricky to reproduce if it went unnoticed for so long, so this kind of info is really important.

Cfr the details on odoo/odoo#48685 where something similar was discussed

2020-10-09 14:26 UTC, rco-odoo commented
@odony the issue was reported to me by @sts-odoo, who knows how to reproduce it.

From what he said, the issue occurs randomly, and is triggered in a controller with `auth=None`.  Sometimes, `flush` is done on some environment where `uid=None`, which makes a computed field that depends on the current user crash when recomputed (the field needs a real current user).

I attributed the presence of an environment with `uid=None` to the controller with `auth=None`, which creates an environment with the superuser from `request.env`.  The random nature of the bug is due to the non-deterministic iteration order of `WeakSet`.

2020-10-09 14:44 UTC, sts-odoo commented
@odony On a controller with `auth=None`, if you do `request.env.with_user(1)` for example you generate 2 environments with the same cursor, one with no user and one with the user 1.
At the end of the transaction, when the `cr.commit` is called, it recomputes all the fields needed, but you have 1 chance out of 2 of being with the environment with a user which was being used. If you have the bad luck of going the `uid=None`, you might have some access rights issues

2020-10-10 20:29 UTC, odony commented
> At the end of the transaction, when the `cr.commit` is called, it recomputes all the fields needed, but you have 1 chance out of 2 of being with the environment with a user which was being used. If you have the bad luck of going the `uid=None`, you might have some access rights issues

@sts-odoo Thanks for the extra info, is there a standard route/controller where you know this can be reproduced? It's useful to document reproduction steps whenever we fix a bug, especially if we can't write easily a regression test. This way next time we revisit that piece of code, we have a chance to verify we don't re-introduce the bug :-)

2020-10-12 10:57 UTC, sts-odoo commented
@odony I don't have a standard route unfortunately, but I do a have an example on paas: https://github.com/odoo/paas/blob/master/paas_worker/controllers/worker.py#L66