[FIX] sale,sale_management: Price list singleton error while choosing optional product without selecting customer
odoo/odoo pull request #59576
Opened 2020-10-09 08:28 UTC by Vanneri

Description of the issue/feature this PR addresses:

Impacted versions:
 
 - 13.0,14.0

Steps to reproduce:
 
 1. create a new sale order/quotation
 2. do not select a customer
 3. add a new line in optional products.
 4.After choosing a product error will popup

Current behavior before PR:

Error will pop up showing **ValueError: Expected singleton: product.pricelist()**

Desired behavior after PR is merged:
Price unit will be 0

![screenshot--2020 10 09-13_55_52](https://user-images.githubusercontent.com/56474164/95560682-414d5c00-0a37-11eb-97b8-aa16917c8587.png)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-17 10:26 UTC, pedrobaeza commented
@Feyensv can you please check this?

2020-10-19 10:41 UTC, Feyensv requested changes
Indeed, it's a correct solution :+1:.
Could you just remove the comment (the condition explains itself) and change the module name to **sale_management** in your commit message ?

Thanks.

2020-10-23 09:46 UTC, Vanneri commented
> Indeed, it's a correct solution +1.
> Could you just remove the comment (the condition explains itself) and change the module name to **sale_management** in your commit message ?
> 
> Thanks.

Please check

2020-10-23 09:48 UTC, Feyensv commented
> > Indeed, it's a correct solution +1.
> > Could you just remove the comment (the condition explains itself) and change the module name to **sale_management** in your commit message ?
> > Thanks.
> 
> Please check

Could you also squash your commits ?

2020-10-23 09:55 UTC, Vanneri commented
> > > Indeed, it's a correct solution +1.
> > > Could you just remove the comment (the condition explains itself) and change the module name to **sale_management** in your commit message ?
> > > Thanks.
> > 
> > 
> > Please check
> 
> Could you also squash your commits ?

ok now?

2020-10-23 10:10 UTC, Feyensv approved these changes
@robodoo r+

2020-10-23 10:57 UTC, closed without merging