[IMP] web: Allow only one dropdown open at same time
odoo/odoo pull request #59753
Opened 2020-10-12 12:58 UTC by res-odoo

Before this commit, if you click outside an open the dropdown menu, the
current open dropdown menu is still open. This can be confusing for the
end user because it's not the same behavior used by the bootstrap
dropdown (like the action menu). To avoid this confusing behavior
now we auto-close the dropdown menu when the user click outside the
dropdown menu like the bootstrap dropdown.

opw-1879566

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-13 09:37 UTC, Arcasias requested changes

2020-10-13 09:37 UTC, Arcasias commented on addons/web/static/src/xml/base.xml
> +                <button type="button" class="btn btn-primary o_click_dont_close_dropdown" t-on-click="_onRemoveFavorite">
When it comes to such behaviours it generaly applies to all of the items of a same dropdown and giving a specific className to each individual item might be bothersome. I would rather have a flag in the form of a prop on the dropdown menu itself ("`closeOnSelect`" or something similar) defaulted to `false` and explicitely set to `true` for the action and print menus for example (or the other way around if we find more occurences of the latter scenario).

2020-10-13 09:37 UTC, Arcasias commented on addons/web/static/tests/components/dropdown_menu_tests.js
> +            const form = await testUtils.createView({
Isn't it a bit heavy to spawn an entire form view here? Perhaps you could get away with creating and appending a node on the fly, set its innerHTML and remove it at the end of the test?

2020-10-13 09:37 UTC, Arcasias commented on addons/web/static/tests/components/dropdown_menu_tests.js
> +            assert.hasClass(dropdown.el, 'show');
I think the `show` class is more of an implementation detail than anything, and using `isVisible` and `isNotVisible` would be more appropriate here.

2020-10-13 09:37 UTC, Arcasias commented on addons/web/static/tests/components/dropdown_menu_tests.js
> +            await testUtils.dom.click(dropdown.el.querySelector('button'));
```suggestion
            await testUtils.controlPanel.toggleMenu(dropdown);
```

2020-10-27 14:50 UTC, Arcasias commented on addons/web/static/tests/components/dropdown_menu_tests.js
> +            bsDropdown.parentNode.removeChild(bsDropdown);
```suggestion
            bsDropdown.remove()
```

2020-10-27 15:00 UTC, Arcasias approved these changes

2020-10-28 14:05 UTC, pparidans approved these changes
Allez zou!
@robodoo r+

2020-10-28 14:42 UTC, closed without merging