Debian/master
odoo/odoo pull request #59866
Opened 2020-10-13 13:51 UTC by sdelafond

Description of the issue/feature this PR addresses: Debian packaging for inclusion in sid

Desired behavior after PR is merged: make sure the next odoo release is based on what will be in Debian sid

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-13 15:32 UTC, d-fence requested changes
Thanks for this PR.
May I ask you to change your commit message according to [our guidelines](https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure).
In this particular case, the first line of the commit messages should be something like:
`[FIX] packaging: fix debian files for 14.0.0 release`
and 
`[FIX] packaging: update debian changelog`
and
`[CLA] signature for sdelafond`

Also, the qweb ast validation patch is not needed anymore.

2020-10-13 15:39 UTC, sdelafond commented on debian/patches/0001-fix-qweb-ast-validation.patch
> +                 # {'nsmap': {None: 'xmlns def'}}
Done.

2020-10-13 15:39 UTC, sdelafond commented
Should be OK now.

2020-10-14 07:01 UTC, d-fence commented
> Should be OK now.

Hmm, one more thing, can you squash cf8d6f6 with da98f49 to avoid useless commits ?
Thanks

2020-10-14 07:09 UTC, sdelafond commented
> > Should be OK now.
> 
> Hmm, one more thing, can you squash [cf8d6f6](https://github.com/odoo/odoo/commit/cf8d6f698b300b00acf71cfae206617c08f82ef1) with [da98f49](https://github.com/odoo/odoo/commit/da98f4989799c22e5fd4bb2bbd92be0163c6abb8) to avoid useless commits ?

If possible, I'd rather not, as da98f4 is what was uploaded to NEW, and as such shouldn't disappear from the history (it holds the debian/14.0.0 tag).

2020-10-14 08:45 UTC, d-fence commented
Will be merged with #59946

2020-10-14 08:45 UTC, closed without merging