[FIX] website: TypeError: unsupported operand type(s) for +: 'bool' and 'str'
odoo/odoo pull request #60049
Opened 2020-10-15 07:56 UTC by luistorresm

![Screen Shot 2020-10-13 at 12 54 41](https://user-images.githubusercontent.com/7606656/95903060-44a85680-0d5b-11eb-920a-1636ba20bc4f.png)

Avoid TypeError when the system parameter web.base.url is not found.

Note: That parameter is removed in some manual backups and not allow
login with the admin to create again automatically.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-15 07:59 UTC, JKE-be commented
Hello

Odoo will not work without this 'web.base.url'.
What is your usecase to remove it during your backup ?

2020-10-15 08:02 UTC, JKE-be requested changes
Wrong place for fix, should be proabably done in function directly

```diff
diff --git odoo/models.py odoo/models.py
index 0150fd6ee01..515dd8e84f6 100644
--- odoo/models.py
+++ odoo/models.py
@@ -3203,7 +3203,7 @@ Fields:
 
         """
         self.ensure_one()
-        return self.env['ir.config_parameter'].sudo().get_param('web.base.url')
+        return self.env['ir.config_parameter'].sudo().get_param('web.base.url', '')
 
     def _check_concurrency(self):

```

But still not sure that we just need to support this case of missing ICP.
It is like if you try a bike with a missing wheel at first view.

2020-10-16 04:27 UTC, luistorresm commented
Hello @JKE-be 

Thanks, I do not remove the parameter, only is cleaned to overwrite when is restored the DB.

Regards

2020-10-16 07:33 UTC, JKE-be commented
I am not convinced by your use case to make it empty, but since empty will return False instead of '', my previous diff can make sense and ok to merge it. What should fix your use case at the same time.
```python
    @api.model
    def get_param(self, key, default=False):
        return self._get_param(key) or default  # => '' or False ===> False
```
But it seems that your last push-force, remove the correct diff :/ https://github.com/odoo/odoo/compare/c3382f64886774720a1f09e6ae301ce4e747065e..0cf224a167cfc40b1f2c4d53fe8722bc7dc38eec

In all cases, can you submit your PR v13 where this function get_base_url has been introduced.
(Don't forget to push force your branch **before** to change the target branch ;)) 

Thank you for your contribution

2020-10-16 12:24 UTC, JKE-be commented
Still another doubt about the:
> I do not remove the parameter, only is cleaned to overwrite when is restored the DB.

Since the value is required, except if you delete it, it should not crash.
And if you deleted it, I consider that it is a misuse, and technical error.

2020-10-16 12:45 UTC, closed without merging