[FIX] web_editor: disable handles pointer events on wheel event
odoo/odoo pull request #60160
Opened 2020-10-16 10:38 UTC by bvr-odoo

This commit disable the pointer events on the handle during the mouse
wheel event. To prevent page scrolling from stopping when hovering
over a handle. Unfortunately onwheel Event is not supported by Safari.

task-2312878

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-16 11:50 UTC, bvr-odoo commented
@qsm-odoo no reviewers were added on the PR so I ping you if needed

2020-10-16 12:28 UTC, qsm-odoo requested changes

2020-10-16 12:28 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +        }, 50));
Mmh, a bit hacky but not a bad idea :+1: However, don't do that in the sizing snippet option by adding an event handler on all handles. It's not related to any option: do that at the source on the main overlay element, so in the `SnippetEditor` class.

2020-10-19 15:24 UTC, qsm-odoo requested changes

2020-10-19 15:24 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +        $handles.on('wheel.snippet_editor', _.throttle(() => {
As explained before I don't think you need to attach an event handler on all handles. Just on the main overlay element (`this.el` here) and you can then use the `events` property with a real event handler definition, etc.

2020-10-20 10:04 UTC, qsm-odoo approved these changes
@robodoo r+

2020-10-20 11:40 UTC, closed without merging