[FIX] base: Contacts still have deactivated language
odoo/odoo pull request #60188
Opened 2020-10-16 15:11 UTC by backspac

Steps to reproduce the bug:
- Install web_studio, contacts
- Activate language English (UK)
- Switch all users' language to UK
- Deactivate language English (US)
- Via Studio, add a related field to a contact: Self > Language

Bug:
Traceback: contacts still have en_US as language and it's deactivated.

opw:2350362

2020-10-16 15:12 UTC, backspac commented
Ping @nim-odoo

2020-10-19 07:27 UTC, nim-odoo requested changes
Do not forget to export the translations :)

2020-10-19 07:27 UTC, nim-odoo commented on odoo/addons/base/models/res_lang.py
> -            if self.env['res.users'].search([('lang', 'in', lang_codes)]):
We could use `search_count` for performance.

2020-10-19 07:27 UTC, nim-odoo commented on odoo/addons/base/models/res_lang.py
> +              or self.env['res.partner'].search([('lang', 'in', lang_codes)]):
I'd split the 2 tests, with a different error message for each.

2020-10-19 11:15 UTC, nim-odoo approved these changes
robodoo r+

2020-10-19 11:52 UTC, closed without merging