[FIX] web: not translate the close icon of notifications
odoo/odoo pull request #60186
Opened 2020-10-16 14:45 UTC by bso-odoo

Before this commit the close icon was included in translated resources.
For example, in Spanish the "&times;" had been turned into "&veces;"
thus not rendering an icon anymore

After this commit the close icon is not a translated text anymore and
remains an icon across all languages

task-2312878

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-19 05:59 UTC, bso-odoo commented
Tested on runbot:
![image](https://user-images.githubusercontent.com/71644421/96407084-e4913480-11e0-11eb-9287-870ec1fd9021.png)

2020-10-19 16:21 UTC, qsm-odoo requested changes
Good :+1: 

Just a small change for the commit message: after the tag [FIX] we are supposed to list the apps we modify (here l10n is not an app). As listing them all here would be too long for one line, I personally write `*` then `*: module_A, module_B, etc` on the first line of the commit description. Our guidelines says to write "various" though :wink: https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure I let you choose. Not really important but this eases grepping through our commits, someone may grep l10n to target apps and may not want to reach your commit.

Same comment for the enterprise PR, this is just nitpicking.

2020-10-19 17:30 UTC, JKE-be commented
comme discuter sur discord, ca serait pas mal de fixer tous d'un coup du tout.

./addons/website_forum/i18n/website_forum.pot:msgid "<span>&amp;times;</span>"
./addons/website_profile/i18n/website_profile.pot:msgid "&amp;times;"
./addons/website_event_meet/i18n/website_event_meet.pot:msgid "&amp;times;"
./addons/website_event/i18n/website_event.pot:msgid "<span>&amp;times;</span>"
./addons/website_crm_partner_assign/i18n/website_crm_partner_assign.pot:msgid "&amp;times;"
./addons/sale_quotation_builder/i18n/sale_quotation_builder.pot:msgid "&amp;times;"
./addons/website/i18n/website.pot:msgid "&amp;times;"
./addons/survey/i18n/survey.pot:msgid "&amp;times;"
./addons/payment/i18n/payment.pot:msgid "&amp;times;"
./addons/account_payment/i18n/account_payment.pot:msgid "&amp;times;"
./addons/website_slides/i18n/website_slides.pot:msgid "<span>&amp;times;</span>"
./addons/sale/i18n/sale.pot:msgid "&amp;times;"
./odoo/addons/base/i18n/base.pot:msgid "<span aria-label=\"Close\">&amp;times;</span>"

./helpdesk/i18n/helpdesk.pot:msgid "&amp;times;"
./planning/i18n/planning.pot:msgid "<span aria-label=\"Close\">&amp;times;</span>"
./sale_subscription/i18n/sale_subscription.pot:msgid "&amp;times;"
./industry_fsm_report/i18n/industry_fsm_report.pot:msgid "&amp;times;"

2020-10-19 17:33 UTC, JKE-be commented
si tu t'embetes, il y aussi les fa-:

./addons/pos_restaurant/i18n/pos_restaurant.pot:"<span class=\"fa fa-lg fa-cutlery\" title=\"For bars and restaurants\" "
./addons/website_forum/i18n/website_forum.pot:"                    <span class=\"fa fa-trophy badge-gold ml-2\" role=\"img\" aria-label=\"Gold badge\" title=\"Gold badge\"/>"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\" fa fa-comment text-muted mr-1\"/>Comment"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-bell fa-fw\"/> Followed Posts"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-bug\"/> Filter Tool"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-check fa-fw mr-1\"/>Accept"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-check text-success d-block display-2\"/>\n"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-check\"/> How to configure TPS and TVQ's canadian taxes?"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-check-square-o fa-fw\"/> To Validate"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-chevron-left mr-1\"/>Back"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-chevron-left mr-2\"/>Back to All Topics"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-chevron-left small\"/> Back"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-flag fa-fw\"/> Flagged"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-flag ml-4 mr4\"/>\n"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-flag\"/> Country"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-pencil\"/>\n"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-question-circle-o fa-fw\"/> My Posts"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-reply mr-1\"/>Answer"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-share-alt text-muted mr-1\"/>Share"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-share-alt text-muted\"/>\n"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-star fa-fw\"/> Favourites"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-tags fa-fw\"/> Followed Tags"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-thumbs-down text-danger ml-3\" role=\"img\" aria-"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-thumbs-up text-success\" role=\"img\" aria-label=\"Positive"
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-times fa-fw mr-1\"/>Reject"
./addons/website_forum/i18n/website_forum.pot:"<i class=\"fa fa-times\"/> Good morning to all! Please, can someone help "
./addons/website_forum/i18n/website_forum.pot:msgid "<i class=\"fa fa-user\"/> User"
./addons/website_forum/i18n/website_forum.pot:"<span class=\"fa fa-trophy badge-bronze ml-2\" role=\"img\" aria-"
./addons/website_forum/i18n/website_forum.pot:"<span class=\"fa fa-trophy badge-silver ml-2\" role=\"img\" aria-"
./addons/website_forum/i18n/website_forum.pot:"                        <i class=\"fa fa-question-circle\"/>"
./addons/hr_contract/i18n/hr_contract.pot:"<span attrs=\"{'invisible': ['|', ('calendar_mismatch', '=', False), ('state', '!=', 'open')]}\" class=\"fa fa-exclamation-triangle text-danger o_calendar_warning pl-3\">\n"
./addons/hr_contract/i18n/hr_contract.pot:"<span attrs=\"{'invisible': [('calendar_mismatch', '=', False)]}\" class=\"fa fa-exclamation-triangle text-danger o_calendar_warning pl-3\">\n"
./addons/hr_contract/i18n/hr_contract.pot:msgid "Font awesome icon e.g. fa-tasks"
./addons/auth_totp/i18n/auth_totp.pot:"<i class=\"fa fa-2x fa-mobile pull-left\"/>\n"
./addons/auth_totp/i18n/auth_totp.pot:"<i class=\"fa fa-check-circle\"/>\n"
./addons/auth_totp/i18n/auth_totp.pot:"<i class=\"fa fa-warning\"/>\n"
./addons/auth_totp/i18n/auth_totp.pot:"                            <i class=\"fa fa-warning\"/>\n"
./addons/auth_totp/i18n/auth_totp.pot:"                            <i class=\"fa fa-check-circle\"/>\n"
./addons/maintenance/i18n/maintenance.pot:msgid "<i class=\"fa fa-ellipsis-v\" role=\"img\" aria-label=\"Manage\" title=\"Manage\"/>"
./addons/maintenance/i18n/maintenance.pot:msgid "Font awesome icon e.g. fa-tasks"
./addons/stock/i18n/stock.pot:msgid "<i class=\"fa fa-clock-o\" role=\"img\" aria-label=\"Date\" title=\"Date\"/>"
./addons/stock/i18n/stock.pot:msgid "<i class=\"fa fa-ellipsis-v\" role=\"img\" aria-label=\"Manage\" title=\"Manage\"/>"
./addons/stock/i18n/stock.pot:"<i class=\"fa fa-exclamation-triangle\"/>\n"
./addons/stock/i18n/stock.pot:"<i class=\"fa fa-fw fa-caret-right\" role=\"img\" aria-label=\"Unfold\" "
./addons/stock/i18n/stock.pot:"<span class=\"fa fa-lg fa-building-o\" title=\"Values set here are company-"
./addons/stock/i18n/stock.pot:"Report\" aria-label=\"Traceability Report\"><i class=\"fa fa-fw fa-level-up "
./addons/stock/i18n/stock.pot:"fa-rotate-270\"/></span>"
./addons/stock/i18n/stock.pot:msgid "Font awesome icon e.g. fa-tasks"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-building text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-calendar text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-cube text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-envelope text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-globe text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-industry text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-money text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-phone text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-twitter text-primary\"/>\n"
./addons/iap_mail/i18n/iap_mail.pot:"<i class=\"fa fa-fw mr-2 fa-users text-primary\"/>\n"
./addons/auth_totp_portal/i18n/auth_totp_portal.pot:"<i class=\"fa fa-warning\"/>\n"
./addons/auth_totp_portal/i18n/auth_totp_portal.pot:"                        <i class=\"fa fa-check-circle\"/>\n"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-arrow-right\"/> Add payment acquirers"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-bolt\"/> Buy Now"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-check\"/> Ship to this address"
./addons/website_sale/i18n/website_sale.pot:"<i class=\"fa fa-chevron-left\"/>\n"
./addons/website_sale/i18n/website_sale.pot:"<i class=\"fa fa-chevron-left\"/>\n"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-edit\"/> Edit"
./addons/website_sale/i18n/website_sale.pot:"<i class=\"fa fa-plus-square\"/>\n"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-print\"/> Print"
./addons/website_sale/i18n/website_sale.pot:msgid "<i class=\"fa fa-shopping-cart\"/> Add to Cart"
./addons/website_sale/i18n/website_sale.pot:"                                        <span class=\"fa fa-chevron-right\"/>"
./addons/website_sale/i18n/website_sale.pot:"                                    <span class=\"fa fa-chevron-right\"/>"
./addons/website_sale/i18n/website_sale.pot:"<span class=\"fa fa-chevron-down fa-border float-right\" role=\"img\" aria-"
./addons/website_sale/i18n/website_sale.pot:"<span class=\"fa fa-chevron-left p-2\" role=\"img\" aria-label=\"Previous\" "
./addons/website_sale/i18n/website_sale.pot:"<span class=\"fa fa-chevron-left\"/>\n"
./addons/website_sale/i18n/website_sale.pot:"<span class=\"fa fa-chevron-left\"/>\n"
./addons/website_sale/i18n/website_sale.pot:msgid "<span class=\"fa fa-chevron-left\"/> Previous"
./addons/website_sale/i18n/website_sale.pot:"<span class=\"fa fa-chevron-right p-2\" role=\"img\" aria-label=\"Next\" "
./addons/website_sale/i18n/website_sale.pot:"                            <span class=\"fa f [...]

2020-10-22 05:30 UTC, mart-e commented on addons/account_payment/views/account_portal_templates.xml
> +                            <button type="button" class="close" data-dismiss="modal" t-translation="off">×</button>
1 character translaions should [be ignored](https://github.com/odoo/odoo/blob/0e2c55eec07600585121acf560ec8ffebde442e3/odoo/tools/translate.py#L168) from the translation parsing `t-translation` should not be needed here

2020-10-22 05:30 UTC, mart-e commented on addons/portal_rating/static/src/xml/portal_rating_composer.xml
> +                            <span t-translation="off">×</span>
in `static/xml` files, it seems it's even [8 characters minimum](https://github.com/odoo/odoo/blob/14.0/odoo/tools/translate.py#L848) which seems a very high limit :thinking:

2020-11-24 13:00 UTC, JKE-be commented
@robodoo r+

2020-11-24 14:22 UTC, closed without merging