[FIX] stock_account: run fifo vacuum on all company
odoo/odoo pull request #60508
Opened 2020-10-22 09:11 UTC by Whenrow

The function _run_fifo_vacuum() is called by the scheduler every day (by
default). Only the stock move in the current admin's company are
processed. That means if the admin do not change his company for a long
time. The fifo stock moves to be vacuumed increased without being
emptied. This can lead (on active databases) to a very long time needed
to open the Inventory Valuation report.

opw : 2298929

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-22 09:26 UTC, nim-odoo requested changes
Modifying the method signature is not great for an old stable. I wouldn't mind for 14.0 or maybe 13.0, but for 12.0 I'm a bit reluctant.

Btw the runbot is red.

2020-10-22 09:26 UTC, nim-odoo commented on addons/stock_account/wizard/stock_quantity_history.py
> +        self.env['stock.move']._run_fifo_vacuum(self.env.user.company_id)
```suggestion
        self.env['stock.move']._run_fifo_vacuum(company_id=self.env.user.company_id)
```

2020-10-22 09:26 UTC, nim-odoo commented on addons/stock_account/models/stock.py
> +            moves_to_vacuum._fifo_vacuum()
No need to loop on all searches:
```suggestion
            fifo_valued_products = self.env['product.product']
            fifo_valued_products |= self.env['product.template'].search([('property_cost_method', '=', 'fifo')]).mapped(
                'product_variant_ids')
            fifo_valued_categories = self.env['product.category'].search([('property_cost_method', '=', 'fifo')])
            fifo_valued_products |= self.env['product.product'].search([('categ_id', 'child_of', fifo_valued_categories.ids)])
        for company in companies:
            moves_to_vacuum = self.search(
                [('product_id', 'in', fifo_valued_products.ids), ('remaining_qty', '<', 1)] + self._get_all_base_domain(company))
            moves_to_vacuum._fifo_vacuum()
```

2020-10-22 14:38 UTC, nim-odoo commented on addons/stock_account/models/stock.py
> +            self.env['stock.move'].with_context('all_companies': True)._run_fifo_vacuum()
are you drunk?

2020-10-22 14:39 UTC, Whenrow commented on addons/stock_account/models/stock.py
> +            self.env['stock.move'].with_context('all_companies': True)._run_fifo_vacuum()
oui

2020-10-22 15:07 UTC, nim-odoo reviewed
Looks ok, although I didn't test.

2020-10-22 15:07 UTC, nim-odoo commented on addons/stock_account/models/stock.py
> +            companies = [self.env.user.company_id]
This works as well:
```suggestion
            companies = self.env.user.company_id
```

2020-10-26 14:48 UTC, Whenrow commented
robodoo r+

2020-10-26 15:16 UTC, closed without merging