[FIX] account, hr_expense: show correct sign for tax_base_amounts of misc operations' lines
odoo/odoo pull request #60555
Opened 2020-10-22 15:27 UTC by oco-odoo

Before this, misc operations always used the balance of the base line as the tax_base_amount of the tax line. This was inconsistent with the invoices, for which we invert its sign when making a sale invoice or a purchase refund (as for those operations, positive amounts are put in credit). This commit should make everything behave in the same way.

saas-12.3 backport of https://github.com/odoo/odoo/pull/60548

2020-10-22 15:27 UTC, oco-odoo commented
@fw-bot up to saas-12.3

2020-10-23 13:03 UTC, smetl requested changes

2020-10-23 13:03 UTC, smetl commented on addons/point_of_sale/models/pos_order.py
> +                    base_amount = self._get_base_amount_to_display(tax['base'], rep_ln)
`_get_base_amount_to_display` is not defined on `pos.order`

2020-10-23 13:03 UTC, smetl commented on addons/hr_expense/models/hr_expense.py
> +                    base_amount = self._get_base_amount_to_display(tax['base'], rep_ln)
`_get_base_amount_to_display` is not defined on `hr.expense`

2020-10-23 14:43 UTC, smetl approved these changes
@robodoo r+

2020-10-27 12:41 UTC, smetl commented
@robodoo r+

2020-10-27 13:12 UTC, closed without merging