[IMP] mail: dynamic placeholder for text input
odoo/odoo pull request #60582
Opened 2020-10-23 07:15 UTC by ibo-odoo

**PURPOSE**

The motive is to change dynamic placeholder by giving context to the user for
indicating whom he/she is writing.

**SPECIFICATION**

Changing placeholder "Write Something..." by "Message person/group..." for chat
and "Message #channel..." for channel.

**LINKS**

PR
Task-2361155

2020-10-27 17:22 UTC, seb-odoo requested changes

2020-10-27 17:22 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> -        "should have 'Write something...' as placeholder in composer text input if composer is for a 'mail.channel'"
Remove this part from the "basic rendering" test, and make new specific tests with just 1 assertion each to verify the placeholder depending on channel type.

2020-10-27 17:22 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +    assert.hasClass(
don't test all this again in placholder test

2020-10-27 17:22 UTC, seb-odoo commented on addons/mail/static/src/components/composer_text_input/composer_text_input.js
> +                return _.str.sprintf(this.env._t("Message %s..."), name);
nested conditions are hard to read.

Prefer a flat hierarchy with quick returns.

If there is no thread do a `return ""` (this is not a realistic case and we will soon remove this condition with required fields). That's already 1 less indent level.

Then I would do all the specific conditions for `mail.channel` also with returns.

And at the bottom the conditions for "not channel" (without nesting them in an `else` condition, that's not necessary if all the other conditions also do `return`).

2020-10-28 09:31 UTC, seb-odoo requested changes

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer_text_input/composer_text_input.js
> +                                   : this.env._t("Send a message to followers...");
This is better but I think this is even better:
```suggestion
        if (this.composer.isLog) {
            return this.env._t("Log an internal note...");
        }
        return this.env._t("Send a message to followers...");
```

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer_text_input/composer_text_input.js
> +            return _.str.sprintf(placeholder, name);
Here's what I had in mind:
```suggestion
        if (this.composer.thread.model === 'mail.channel') {
            if (this.composer.thread.correspondent) {
                return _.str.sprintf("Message %s...", this.composer.thread.correspondent.nameOrDisplayName)
            }
            return _.str.sprintf("Message #%s...", this.composer.thread.displayName);
        }
```
Also note the change about correspondent which also makes it work for livechat out of the box.

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +        "should have 'Message #General...' as placeholder for composer text input"
"... when thread does not have specific correspondent"

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +        "should have 'Message Marc Demo...' as placeholder for composer text input"
"... when thread has exactly one correspondent"

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +QUnit.test('composer text input placeholder: linked thread is a mail.channel with type "chat"', async function (assert) {
make the test title almost similar as the assertion comment

2020-10-28 09:31 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +QUnit.test('composer text input placeholder: linked thread is a mail.channel with type "channel"', async function (assert) {
make the test title almost similar as the assertion comment

2020-10-28 10:35 UTC, seb-odoo requested changes

2020-10-28 10:35 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +QUnit.test('composer text input placeholder: when thread does not have specific correspondent', async function (assert) {
```suggestion
QUnit.test('composer text input placeholder should contain channel name when thread does not have specific correspondent', async function (assert) {
```

2020-10-28 10:35 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +QUnit.test('composer text input placeholder: when thread has exactly one correspondent', async function (assert) {
```suggestion
QUnit.test('composer text input placeholder should contain correspondent name when thread has exactly one correspondent', async function (assert) {
```

2020-10-28 10:35 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +        model: 'mail.channel',
data must be updated in this test to properly set `members`: `currentPartnerId` + one other partner

2020-11-16 14:14 UTC, seb-odoo requested changes

2020-11-16 14:14 UTC, seb-odoo commented on addons/mail/static/src/components/composer_text_input/composer_text_input.js
> +                return _.str.sprintf("Message %s...", this.composer.thread.correspondent.nameOrDisplayName)
should add `correspondent` in `useStore` to ensure proper refresh in case of name update

2020-11-16 14:14 UTC, seb-odoo commented on addons/mail/static/src/components/composer_text_input/composer_text_input.js
> +            return _.str.sprintf("Message #%s...", this.composer.thread.displayName);
same for `thread`

2020-11-16 14:14 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +    );
Use `findFromIdentifyingData`

2020-11-16 14:14 UTC, seb-odoo commented on addons/mail/static/src/components/composer/composer_tests.js
> +    });
Use `this.data` instead, similarly to what you did on the other test.

2020-11-17 07:00 UTC, ibo-odoo commented
Hello.. @seb-odoo Changes are done.! Thanks.

2020-11-18 17:58 UTC, seb-odoo approved these changes
Thank you, looks good.

I'll let @alexkuhn do a final check.

2020-11-19 16:21 UTC, alexkuhn approved these changes
@robodoo r+

2020-11-19 17:36 UTC, closed without merging