Master calendar synchronization avd
odoo/odoo pull request #60825
Opened 2020-10-27 13:13 UTC by Aurelienvd

Description of the issue/feature this PR addresses: Give more flexibility to the users by allowing them to stop
the synchronization with Google/Outlook calendar.

Current behavior before PR: Only way to stop the active synchronization with Google/Outlook calendar is
to uninstall both modules.

Desired behavior after PR is merged: Add a "toggle" button that allow to turn on/off the synchronization with Google/
Outlook calendar independently (i.e. possible to turn off Google sync. while leaving Outlook sync. active).

(PS for the review: the source codes for Outlook and Google are almost identical).

Task ID: 2330246

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-05 10:11 UTC, kba-odoo requested changes
Initial review - some (minor) comments :-)

I only left them on google sync but they are applicable for microsoft as weel :-p

2020-11-05 10:11 UTC, kba-odoo commented on addons/google_calendar/models/res_users.py
> +
(sorry, I can't highlight the relevant line :shrug: )

Line #112: you should add `google_synchronization_stopped != False` in the domain. That way the cron will not attempt to start the synchronization for users who disabled it.

2020-11-05 10:11 UTC, kba-odoo commented on addons/google_calendar/models/res_users.py
> +        })
You can remove this method, there's no real value added

2020-11-05 10:11 UTC, kba-odoo commented on addons/google_calendar/models/res_users.py
> +        self._set_google_synchronization_stopped(True)
```suggestion
        self.sudo().google_synchronization_stopped = True
```

2020-11-05 10:11 UTC, kba-odoo commented on addons/google_calendar/models/res_users.py
> +        self._set_google_synchronization_stopped(False)
```suggestion
        self.sudo().google_synchronization_stopped = False
```

2020-12-09 15:39 UTC, KangOl commented on addons/google_calendar/controllers/main.py
> +            if not need_refresh and request.env.user.google_synchronization_stopped:
Shouldn't we do this verification *before* doing the synchronization?

2020-12-09 15:39 UTC, tivisse commented
@robodoo r+ merge

2020-12-09 15:40 UTC, robodoo commented
Merge method set to merge directly, using the PR as merge commit message

2020-12-09 15:50 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#1923 not ready. Linked PRs are not staged until all of them are ready.

2020-12-09 18:20 UTC, robodoo commented
Staging failed: ci/runbot on ca0d43cc4deaee8ac7e46178217b55b70c65e19c (view more at http://runbot.odoo.com/runbot/build/5332019)

2020-12-10 09:24 UTC, tivisse commented
@robodoo r+

2020-12-10 11:13 UTC, merged