[FIX] mail: mail delivery exception
odoo/odoo pull request #60938
Opened 2020-10-29 06:04 UTC by hbh-odoo

**Current behavior before PR:**

When trying to send the notification for the user form, it shows a traceback.
This is happening after https://github.com/odoo/odoo/commit/ab4000fb3cf8fa54ba714ceceec391b78d73755e

**Desired behavior after PR is merged:**

Send the notification without any traceback as handle
the MailDeliveryException inside CrashManager

Task-2333121

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-10-29 10:43 UTC, seb-odoo requested changes

2020-10-29 10:43 UTC, seb-odoo commented on addons/mail/static/src/bugfix/bugfix.js
> +            'odoo.addons.base.models.ir_mail_server.MailDeliveryException': _lt("MailDeliveryException")
New string in stable should be added to pot file.

2020-10-29 10:43 UTC, seb-odoo commented on addons/mail/models/mail_mail.py
> +                    raise MailDeliveryException(_('Unable to connect to SMTP Server'))
I don't think this change is needed here, I don't see any difference if the extra param is kept? Let me know why you did it, or keep minimal diff.

2020-10-29 10:43 UTC, seb-odoo commented on addons/mail/static/src/bugfix/bugfix.js
> +        });
That looks like a complex way to just write this
```suggestion
        Object.assign(this.odooExceptionTitleMap, {
            'odoo.addons.base.models.ir_mail_server.MailDeliveryException': _lt("MailDeliveryException")
        });
```

2020-11-16 14:29 UTC, seb-odoo approved these changes
@robodoo r+

2020-11-16 14:34 UTC, seb-odoo requested changes
@robodoo r-

Actually I just realized that `MailDeliveryException` is actually defined in `base` not `mail`, so the fix can directly be made on `web`, no need for an override here.

2020-11-17 06:59 UTC, hbh-odoo commented
@seb-odoo Done!

2020-11-17 09:20 UTC, seb-odoo approved these changes
@robodoo r+

2020-11-17 10:39 UTC, closed without merging