[IMP] auth_totp: allow support of mobile device for 2FA
odoo/odoo pull request #61046
Opened 2020-10-30 13:07 UTC by res-odoo

Task ID: 2369433
opw-2354969

2020-11-04 13:17 UTC, xmo-odoo requested changes
Imma need way more explanations there, and an actual commit message. I've no idea how the mobile client works, what its flow is, and why it needs a new endpoint.

2020-11-04 13:17 UTC, xmo-odoo commented on addons/auth_totp/tests/test_totp.py
> +            'id': str(uuid4()),
useless complexity, you can just pass in the number `0`.

2020-11-04 13:17 UTC, xmo-odoo commented on addons/auth_totp/tests/test_totp.py
> +    def _build_payload(self, params={}):
Why id there a default value? In which situation would that be useful? Also / alternatively, why not use kwargs?

2020-11-04 13:17 UTC, xmo-odoo commented on addons/auth_totp/tests/test_totp.py
> +        response = self.url_open('/web/session/authenticate', data=json.dumps(payload), headers=headers)
`json` kwarg does the conversion on its own and automatically sets the request's content-type.

2020-11-04 13:17 UTC, xmo-odoo commented on addons/auth_totp/tests/test_totp.py
> +        self.assertEqual(response.status_code, 200)
Not super useful as JSON-RPC endpoints never return anything other than 200 unless they're missing.

Also `raise_for_status()` is the usual way to *assert* success (sadly it's not chainable).

2020-11-04 13:17 UTC, xmo-odoo commented on addons/auth_totp/tests/test_totp.py
> +        self.assertEqual(data['result']['error'], _("Invalid authentication code format."))
per [jsonrpc spec](https://www.jsonrpc.org/specification#response_object), the error should logically be signaled by `data['error']` being set, and `data['result']` being unset: `data['result']` signals success.

2020-11-04 15:17 UTC, xmo-odoo commented
@res-odoo do we close this as you implement the client-only version?

2020-11-09 09:54 UTC, closed without merging

2020-11-09 09:56 UTC, adr-odoo commented
Client-only version: https://github.com/odoo/mobile/pull/190