[IMP] account: Allow skipping statement line on payments
odoo/odoo pull request #61059
Opened 2020-10-30 14:47 UTC by smetl

A classic payment uses the outstanding account to create the line that needs to be matched later with a statement line.
Otherwise, some ppl doesn't want that (e.g. to manage cash transactions) and prefers creating a payment impacting directly the bank account even this payment will never be matched to any statement line.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-02 14:03 UTC, oco-odoo requested changes
I'd make the comments just a little more explicit. Also, the first commit message is weirdly phrased; I guess it's worth making it a little more understandable ^^

And for when it's done:
@robodoo delegate+

2020-11-02 15:15 UTC, smetl commented
@robodoo r+

2020-11-02 15:38 UTC, smetl commented
@robodoo r+

2020-11-02 16:50 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#14502 not ready. Linked PRs are not staged until all of them are ready.

2020-11-02 16:50 UTC, robodoo commented
Because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2020-11-03 09:14 UTC, smetl commented
@robodoo r+ rebase-ff

2020-11-03 09:15 UTC, robodoo commented
I'm sorry, @smetl. You can't method=rebase-ff.

2020-11-03 09:21 UTC, oco-odoo commented
@robodoo rebase-ff

2020-11-03 09:21 UTC, robodoo commented
Merge method set to rebase and fast-forward

2020-11-04 13:14 UTC, smetl commented
@robodoo r+

2020-11-04 14:46 UTC, closed without merging