[FIX] payment: prevent changing checkout options
odoo/odoo pull request #61493
Opened 2020-11-06 16:51 UTC by yelizariev

STEPS:

* install website_sale
* setup few delivery options
* setup online payment (e.g. paypal)
* at website add products to cart and proceed to checkout page
* slow down internet speed
* click "Pay now"

BEFORE: while it's loading, you can change delivery option. So, you have SO
changed, while in payment page you see old total amount

AFTER: it's not possible to change delivery options

WHY: this is dirty hack to fix the issue. A better way should be done in master

---

opw-2324543

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-06 16:51 UTC, yelizariev commented
Preview: https://drive.google.com/file/d/16Eqa5Js_Cf5F9KYgBb4J806Gxu-mr1IM/view?usp=sharing

2020-11-11 22:45 UTC, rdeodoo commented
IMHO, the perfect compromise would be to set the opacity to 0, so there is no change in the UI (this box around the cart is quite ugly and a big UI change), so we keep just the mouse spinner + the prevent click on the whole zone, without affecting the UI.
What do you think?

2020-11-12 09:46 UTC, yelizariev commented
opacity  0 is what I prefer too. Current design is mostly for demonstration and final design can be adjusted

2020-11-12 09:58 UTC, yelizariev commented
@odoo/rd-website

2020-11-12 17:48 UTC, rdeodoo commented
Can you replace the end of your commit message
```
AFTER: it's not possible to change delivery options

WHY: this is dirty hack to fix the issue. A better way should be done in master

---

opw-2324543
```
by
```
AFTER: it's not possible to change delivery options through UI

Note that it is not possible to pay less that what you should.

opw-2324543
```

Other than that it LGTM and I'll check with someone that can r+ to move forward with this one

2020-11-12 17:50 UTC, qsm-odoo commented
@robodoo delegate=rdeodoo

2020-11-13 08:35 UTC, yelizariev commented
@rdeodoo the commit message is updated

2020-11-13 08:45 UTC, JKE-be commented
not sure about the note ;) but if @rdeodoo is happy ;) 

@robodoo r+

2020-11-13 08:46 UTC, JKE-be commented
@robodoo r-

2020-11-13 08:49 UTC, JKE-be commented
Since we are in payment module, does it make sense to do it only for `.oe_website_sale`.
Can't we do it on body directly ?  or at least on the current form (o_payment_form)

2020-11-13 08:54 UTC, qsm-odoo commented
I agree :+1: `this.$el` instead of `$('.oe_website_sale')` is probably better

2020-11-13 10:04 UTC, rdeodoo requested changes
o_payment_form or this.$el can't work as it only block the payment part.
But indeed body or #wrapwrap would be better as it wouldn't use website class in payment module.
Note that with body you need to add a zindex property or the blockui will be behind the oe_main_menu_navbar.

2020-11-13 10:04 UTC, rdeodoo commented on addons/payment/static/src/js/payment_form.js
> +        $('.oe_website_sale').block({overlayCSS: {backgroundColor: "#000", opacity: 0}, message: false});
```suggestion
        $("body").block({overlayCSS: {backgroundColor: "#000", opacity: 0, zIndex: 1050}, message: false});
```

2020-11-13 12:47 UTC, yelizariev commented
I changed it body and tested basic ecommerce workflow on runbot :+1:

2020-11-13 13:03 UTC, rdeodoo commented
Same, thank you.
@robodoo r+

2020-11-13 13:51 UTC, closed without merging