[FIX] website: show mega menu over /my sidebar
odoo/odoo pull request #61505
Opened 2020-11-06 18:11 UTC by rdeodoo

Before this commit, the mega menu had a z-index of 1000 (BS value for
`.dropdown-menu`) while the portal sidebar has a z-index of 1020 (BS value for
`.sticky-top`).

Note that in 14.0 this is not needed as there is new stacking context created
with 5879e40445f0.

2020-11-06 18:15 UTC, rdeodoo commented
Should it be fw-bot up to 14 or saas-13.3 if we don't want the FWD to hit 13.0?

2020-11-06 21:02 UTC, qsm-odoo commented
@rdeodoo Seeing your question I'd say... neither :smile: But to answer what you meant: up to is including. Otherwise, how would you say you want it forward-ported to master? :wink:

2020-11-08 14:05 UTC, rdeodoo commented
@qsm-odoo You have become a master in the art of making fun of my typos. It always take me a few minutes to understand :smile_cat: 
But otherwise, to say I want it up to master, I just don't use up to ? :man_shrugging:

2020-11-09 09:17 UTC, qsm-odoo commented
@fw-bot up to saas-13.3
@rdeodoo With this fix, you solve the problem for mega menus, but not dropdowns. Also the commit you mention fixes the problem in 14.0 is not the one. What solves the problem in 14.0 is that we added that zindex you add here on the header element itself -> thus creating a stacking context for this element so that all the elements inside are stacked between each other only and so that the header is above other elements in the page. We should probably just backport that in previous version. (https://github.com/odoo/odoo/commit/0f2cab4aebcc33ca9e278c9395fed2cc8934ed38 -> note: the zindex-modal - 20 seems bad, probably should have used your value here... to check :+1:)

For the forward-port up to master, you can use it to:
- Correct a previous call to the bot.
- If you want to merge something in 12.0, stop the forward-port at 13.0 and continue it tweaked up to master. You'll have to invoke fw-bot up to master on the 13.0 merged branch (I have done that quite some times ;)).

2020-11-12 10:43 UTC, rdeodoo commented
> With this fix, you solve the problem for mega menus, but not dropdowns. Also the commit you mention fixes the problem in 14.0 is not the one

Done & commit adapted

2020-11-12 10:51 UTC, qsm-odoo requested changes
Do not target "header" for this fix, it is used by other stuff that the website main header. Either header#top like in 14.0 if possible, or #wrapwrap > header

2020-11-12 12:32 UTC, rdeodoo commented
Indeed, change done

2020-11-16 10:32 UTC, qsm-odoo approved these changes
Let's propagate to master despite the fact it is fixed in 14.0, it seems better to use zindex-fixed like here and adapt the 14.0 commit :+1: 

@robodoo r+

2020-11-16 11:37 UTC, closed without merging

2020-11-16 17:57 UTC, qsm-odoo commented
> Let's propagate to master
Dammit, forgot I added that fw-bot command before x)

2020-12-24 15:14 UTC, yelizariev commented
This breaks website chat in mobile. Please review my fix: https://github.com/odoo/odoo/pull/63787