[FIX] crm: fix Lost filter on Opportunities view of Contact
odoo/odoo pull request #61796
Opened 2020-11-16 15:45 UTC by kitan191

- Install CRM
- Create an Opportunity for a partner (i.e. Deco Addict) and mark it as Lost
- Go to Contacts and select Deco Addict
- Click on Opportunities smart button
- Select "Lost" filter
Nothing is displayed, although there should be at least one lost opportunity.

When displaying Opportunities from smart button of Contact,
('id', 'in', self.opportunity_count_ids.ids) is added in domain, which will not
allow any other opportunity to be displayed.
But Lost Opportunities are non-active records that were not originally computed
in "opportunity_count_ids".

Opportunities smart button should filter records on partner_id instead.

opw-2382754

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-16 15:47 UTC, kitan191 commented
@nim-odoo Only for 13.0 and saas-13.3
The issue is not present in 14.0

2020-11-17 12:12 UTC, nim-odoo commented
fw-bot up to saas-13.3

2020-11-17 12:18 UTC, nim-odoo commented
fw-bot ignore

2020-11-17 12:25 UTC, nim-odoo requested changes

2020-11-17 12:25 UTC, nim-odoo commented on addons/crm/models/res_partner.py
> -    opportunity_count_ids = fields.Many2many('crm.lead', compute="_compute_opportunity_count", string='Opportunities Count', help='Technical field used for stat button')
we should not remove a computed field in stable, it could be used in a third-party module

2020-11-17 12:25 UTC, nim-odoo commented on addons/crm/models/res_partner.py
> -        action['domain'] = [('id', 'in', self.opportunity_count_ids.ids)]
I'd rather use the same condition / domain than the computed field:
```py
operator = 'child_of' if self.is_company else '='
action['domain'] = [('partner_id', operator, self.id), ('type', '=', 'opportunity')]
```

2020-11-17 12:25 UTC, nim-odoo commented on addons/crm/models/res_partner.py
> -            partner.opportunity_count_ids = self.env['crm.lead'].search([('partner_id', operator, partner.id), ('type', '=', 'opportunity')])
we should keep the computation

2020-11-17 15:37 UTC, nim-odoo approved these changes
robodoo delegate+

2020-11-17 15:48 UTC, kitan191 commented
robodoo r+

2020-11-17 16:38 UTC, closed without merging