[FIX] fleet: Module fleet_account doesn't exist
odoo/odoo pull request #61867
Opened 2020-11-17 14:43 UTC by simongoffin

The module fleet_account has been replaced by account_disallowed_expenses_fleet
in https://github.com/odoo/odoo/commit/db9da432b7aedcd1bc944e23e59459c9c92801b7

opw:2382169

2020-11-18 13:50 UTC, william-andre reviewed
Not sure if it should be `account_fleet` or `account_disallowed_expenses_fleet`, I've asked to PO without answer yet.

Either way, it doesn't work with analytic accounts anymore so the strings have to be changed.

2020-11-18 15:01 UTC, william-andre requested changes
The module `account_fleet` is in auto-install, so no need for a setting anymore. The disallowed expense feature should not be a setting in fleet, and its installation is managed by the localization packages.

Thus we can just remove this field.

2020-11-18 15:46 UTC, william-andre approved these changes

2020-11-19 14:47 UTC, simongoffin commented
robodoo r+

2020-11-19 16:04 UTC, closed without merging