[FIX] web_tour: display the full text of tour tip steps
odoo/odoo pull request #62142
Opened 2020-11-23 08:29 UTC by bso-odoo

Before this commit the height of the tour tip text was forced, sometimes
hiding a part of the text

After this commit the height of the tour tip text is left to be computed
by the browser

task-2391201

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-23 08:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62142).

2020-11-24 16:15 UTC, JKE-be requested changes
Please, try to be be more critical of your changes...

I'm sure that you cannot find it better...

https://drive.google.com/file/d/1uhh9Uj7Ju7CYSBULYwGdCv1ftURBtYc0/view

First part of video is without your fix, without flickering
Last part of video is with you commit, it is just not acceptable as changes, we need to find another fix.

2020-12-02 10:28 UTC, bso-odoo commented
> Please, try to be be more critical of your changes...
> 
> I'm sure that you cannot find it better...
> 
> https://drive.google.com/file/d/1uhh9Uj7Ju7CYSBULYwGdCv1ftURBtYc0/view
> 
> First part of video is without your fix, without flickering
> Last part of video is with you commit, it is just not acceptable as changes, we need to find another fix.

New approach does not rely on "auto" anymore, it instead adjusts the computed target dimensions.

2020-12-16 06:35 UTC, sdegueldre commented
@bso-odoo I'm confused by this change, if the problem is that the size of the tooltip was calculated without accounting for borders, can't we just set the box-sizing of the tip to content-box so that the browser account  for it instead?

2020-12-16 09:12 UTC, sdegueldre commented
After further discussion: using box-sizing: content-box will make the tip slightly larger. To discuss whether this is a problem or not. If it is a problem, it would still be better to measure the size of the tip as though it was really in an active state rather than create a new class specifically for measuring that may not always reflect the active state, although it involves slightly more class juggling in JS.

2021-01-18 16:09 UTC, qsm-odoo approved these changes
@robodoo r+

2021-01-18 17:26 UTC, closed without merging