[IMP] hr_holidays: add various cosmetic changes
odoo/odoo pull request #62162
Opened 2020-11-23 11:42 UTC by Aurelienvd

Remove 'refuse' leaves from the Calendar View.
Improve leave/leave.allocation popup form views.
Add Sequence handle to leave type list view.

Task ID: 2377043

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-23 11:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62162).

2021-02-03 14:46 UTC, kba-odoo requested changes

2021-02-03 14:46 UTC, kba-odoo commented on addons/hr_holidays/security/hr_holidays_security.xml
> +        <field name="domain_force">[('employee_id.user_id', '=', user.id), ('state', 'not in', ['vaidate', 'validate1'])]</field>
```suggestion
        <field name="domain_force">[('employee_id.user_id', '=', user.id), ('state', 'not in', ['validate', 'validate1'])]</field>
```

2021-02-03 14:46 UTC, kba-odoo commented on addons/hr_holidays/static/src/scss/time_off.scss
> +        height: calc(100% - 6.0rem);
Can be reverted, it doesn't change anything

2021-02-05 15:47 UTC, mart-e commented
@robodoo override=ci/security
Reason: false positifve, changing the description

2021-03-09 08:54 UTC, tivisse commented
@robodoo r+

2021-03-09 10:45 UTC, closed without merging