[FIX] mail: refresh activity list after editing and activity.
odoo/odoo pull request #62252
Opened 2020-11-24 14:26 UTC by phenix-factory

It's possible to create a new activity when editing a existing activity (done
and schedule next). In this case, we must refresh the activity list, otherwise
they wont be in the chatter.

task-2389961

2020-11-24 14:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62252).

2020-11-25 09:28 UTC, alexkuhn requested changes
Fix looks good. Would slightly clean code to avoid duplicating branching code:
```js
let shouldDelete = false;
if (data) {
    this.update(this.constructor.convertData(data));
} else {
    shouldDelete = true;
}
this.thread.refreshActivities();
this.thread.refresh();
if (shouldDelete) {
    this.delete();
}
```
Also would make a test for marking activity as done and reschedule than needs `refreshActivities()` to pass.

2020-11-25 10:43 UTC, alexkuhn commented on addons/mail/static/src/models/activity/activity.js
> +
no newline

2020-11-25 12:23 UTC, phenix-factory commented
Without the hability to fill a view form and post it, I don't know how I can test this fix correctly

2020-11-25 12:29 UTC, alexkuhn approved these changes
@robodoo r+

2020-11-25 14:11 UTC, closed without merging