[IMP] fleet: improve ux + fix contracts/services archive bug
odoo/odoo pull request #62556
Opened 2020-11-27 15:50 UTC by Aurelienvd

Revamp the kanban view of fleet.vehicle.log.services.

Add some ux improvements (new filters, better naming,..).

Fix bug where contracts/services of archived fleet.vehicle were
not counted in statinfo.

When a fleet.vehicle is archived, archive its related contracts/services too.

Task ID: 2389823

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-11-27 15:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62556).

2021-01-08 08:40 UTC, kba-odoo requested changes

2021-01-08 08:40 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle_cost.py
> +        ('new', 'New'),
Don't forget to update the records with the new value in the upgrade script :-)

2021-01-08 08:40 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle.py
> +        super(FleetVehicle, self).action_unarchive()
You can override the ORM method `toggle_active` instead and do what's needed for the contract / services :-)

2021-01-08 08:40 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle_cost.py
> +    def action_archive_with_vehicles(self, vehicle_ids, archive = True):
cf. the toggle_active thingy above

2021-01-08 08:40 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle_cost.py
> +    def action_archive_with_vehicles(self, vehicle_ids, archive = True):
cf. the toggle_active thingy above

2021-01-11 07:14 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle.py
> +        self.env['fleet.vehicle.log.services'].search([('vehicle_id', 'in', self.ids), '|', ('active', '=', 1), ('active', '=', 0)]).toggle_active()
You can use `.with_context(active_test=False)` instead of active=0,1

2021-02-23 09:44 UTC, tivisse commented on addons/fleet/models/fleet_vehicle_cost.py
> +        return [key for key, _ in type(self).state.selection]
```suggestion
        return [key for key, dummy in type(self).state.selection]
```

2021-02-25 08:45 UTC, tivisse commented
@robodoo r+

2021-02-25 08:50 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#2063 not ready. Linked PRs are not staged until all of them are ready.

2021-02-25 10:49 UTC, closed without merging