[FIX] tests: kill remaining chrome headless instances
odoo/odoo pull request #62635
Opened 2020-11-30 16:48 UTC by d-fence

When an HttpCase goes wrong for one reason or another, a Chrome headless
browser may stay running in the background after the test session is
finished.

While it's not a problem on the runbot system as the Docker containers
are recycled, it may be a problem on other systems.

Latest use case: the requests.get is patched in a test but not
unpatched ... This made the _json_command method completely fails
leaving a Chrome headless browser running.

This PR is an attempt to fix that by registering atexit methods to kill eventually remaining chrome processes when Odoo exits.

2020-11-30 16:49 UTC, d-fence commented
Not sure that it's the proper fix

2020-11-30 16:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62635).

2020-12-02 09:43 UTC, d-fence commented
Linked to odoo/enterprise#15071

2020-12-02 09:44 UTC, d-fence commented
I summon @odoo/rd-security for a review please

2020-12-02 10:13 UTC, Xavier-Do requested changes

2020-12-02 10:13 UTC, Xavier-Do commented on odoo/tests/common.py
> +        os.kill(chrome_pid, 0)
You can call os.kill(chrome_pid, signal.SIGTERM)
This will avoid a possible corner case where the process disapear between the two kill.

2020-12-03 09:15 UTC, xmo-odoo commented
@d-fence seems a bit risky to register an atexit callback per Chrome instance, I don't know the exact details of atexit but even if it works I don't think it's setup to handle potentially dozens of callbacks. Registering a single callback globally & adding the pids to a list might be a better idea.

An other issue is pid recycling: by the time Odoo shuts down, the original chrome pid might have been reused for something else, so we should probably "unregister" the pid when shutting down chrome normally succeeds.

A safer option might be to kill all children instead of storing PIDs? `psutil` could probably be used to do that easily. Also note that SIGTERM could be ignored by a stuck process, recipes usually TERM first, then wait a bit, then KILL if the process is still alive.

2020-12-03 09:46 UTC, d-fence commented
Thanks, for the review. I agree with all the remarks. I was already worried about the PID recycling and the risk of killing an unrelated process.

2020-12-03 10:10 UTC, odony commented
> An other issue is pid recycling: by the time Odoo shuts down, the original chrome pid might have been reused for something else, so we should probably "unregister" the pid when shutting down chrome normally succeeds.

Good point. Children PIDs wouldn't normally be reused until they exit and the parent `wait()`s for them, but the PR actually adds a `waitpid()` call, so that is now entirely possible (but see below).

~~

@d-fence the description states:
> With this commit, when the chrome browser is stopped, the chrome process is waited in order to avoid zombie process during the Odoo execution.

As discussed before in your other PR, zombie processes are *not* an issue. They use virtually no resources and will be gracefully discarded by `init` when the parent exits. So the extra `waitpid()` doesn't actually solve any problem. On the contrary, it creates a possibly unbounded delay inside `stop()`. You could use tricks with `WNOHANG` or alarms, or properly handle `SIGCHLD`, but the safest option is to do exactly nothing, IMO ;-)

That leaves only 1 problem: chrome-headless processes that would still be running when the process exits. And here, the first and best option is to ensure that tests properly use cleanups, as you're doing in odoo/enterprise#15071, so that `stop()` does its job. I assume chrome-headless does exit when it's told to, in general.

If we want an extra safeguard, sending SIGTERM to children upon exit sounds like a workable solution, but it's still a dangerous thing. The children PIDs need to be filtered with the chrome-headless PIDs we _know_ we've spawned and have not SIGTERM'd yet. If they've already been signalled, there's not point doing it again unless we're prepared to do the full SIGTERM/SIGKILL dance. And I think that last option is definitely overkill, and should be avoided (more delays and risks).

2020-12-03 10:21 UTC, d-fence commented
@odony Thanks for the review.
I agree that finally, the best choice is to fix proper cleanups ... but this beast was detected by chance by odoo.sh teams and they are worried about the chrome headless leftovers from code that we don't have under control.
ping @sts-odoo

2020-12-03 10:43 UTC, d-fence commented
This attempt to fix a problem caused by other tests brings more issues.
So closing it.

2020-12-03 10:43 UTC, closed without merging