[FIX] mail: split attachments list to improve style
odoo/odoo pull request #62719
Opened 2020-12-02 09:34 UTC by xdu-odoo

There is now two lists of attachments : first one with images and second
one with non-images. Attachment viewer allows to navigate through
previews of all viewable attachments in the order they're shown.

task-2272587
task-2401325

2020-12-02 09:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62719).

2020-12-03 15:04 UTC, alexkuhn requested changes
Fix looks good. Since it was reported as issue in v14, would apply it to v14 too.

Don't forget ASC order when refering to task-id in commit message.

2020-12-03 15:04 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_list/attachment_list.js
> +    }
missing docstring

2020-12-03 15:04 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_list/attachment_list.js
> +}
Missing `// Public` section

2020-12-03 15:04 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_list/attachment_list.js
> +}
empty newline after last method of class

2020-12-04 09:17 UTC, xdu-odoo commented
> Fix looks good. Since it was reported as issue in v14, would apply it to v14 too.

Do we keep this and cherry-pick it in another PR targetting v14 or do we cancel this, retarget v14 and let forward bot do the job ?

> Don't forget ASC order when refering to task-id in commit message.

I don't understand, the task ids are ASC ordered ... ?

2020-12-04 09:38 UTC, alexkuhn commented
> > Fix looks good. Since it was reported as issue in v14, would apply it to v14 too.
> 
> Do we keep this and cherry-pick it in another PR targetting v14 or do we cancel this, retarget v14 and let forward bot do the job ?

Yeah. I'd like being fast in master and slower in stable, and this implies focusing master first and stable 2nd with this approach (so we do back-port rather than forward-port).

Ok to keep this PR. Can make another that targets v14, and we will avoid fw bot on this latter PR.

> 
> > Don't forget ASC order when refering to task-id in commit message.
> 
> I don't understand, the task ids are ASC ordered ... ?

Yeah... For some reasons my brain saw 6 digits out of 7 being lower and assume it was not ordered correctly. It's correctly ordered indeed.

2020-12-04 13:03 UTC, alexkuhn approved these changes
@robodoo r+

2020-12-04 14:25 UTC, closed without merging