[FIX] web: fix external layout of report templates
odoo/odoo pull request #62737
Opened 2020-12-02 12:25 UTC by kitan191

- Install Studio
- Enable debug mode
- Go to Apps
- Activate Studio & go to Reports
- Create an External Reports
- Click on Company address
The following error is raised:
"Error: Invalid Prop 'value' in component 'CustomCheckbox'"

opw-2393926

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-12-02 12:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62737).

2020-12-02 12:31 UTC, kitan191 commented
@nim-odoo Templates are the same in 12.0 & 13.0, but the error only happens in 14.0.
Seems to be linked to `owl.js`.

2020-12-02 14:08 UTC, qho-odoo commented
`"no_marker": true` seems also in 
[helpdesk_portal_templates.xml](https://github.com/odoo/enterprise/blob/78bee692624f1ae62309ae78d04d39d0e1c7b155/helpdesk%2Fviews%2Fhelpdesk_portal_templates.xml#L116) and [din5008_report.xml](https://github.com/odoo/odoo/blob/eb6a177a50128f2d78607fcff36aaf65e8a3034e/addons%2Fl10n_de%2Freport%2Fdin5008_report.xml#L82)

Will these two files get influenced as well?

2020-12-02 14:19 UTC, kitan191 commented
> `"no_marker": true` seems also in
> [helpdesk_portal_templates.xml](https://github.com/odoo/enterprise/blob/78bee692624f1ae62309ae78d04d39d0e1c7b155/helpdesk%2Fviews%2Fhelpdesk_portal_templates.xml#L116) and [din5008_report.xml](https://github.com/odoo/odoo/blob/eb6a177a50128f2d78607fcff36aaf65e8a3034e/addons%2Fl10n_de%2Freport%2Fdin5008_report.xml#L82)

I will fix all the occurences

2020-12-02 15:51 UTC, nim-odoo approved these changes
robodoo delegate+

2020-12-02 17:02 UTC, JKE-be commented
You have a lot of other occurrences that you doesn't replace :/
'time_only', 'date_only':, country_image, ...  And in all customizations...

But you are probably not fixing the problem.
It is supposed to work in qweb, and so in qweb.js too... so it is probably something that you should check with owl (@aab-odoo)
if your comment is right 
> templates are the same in 12.0 & 13.0, but the error only happens in 14.0. Seems to be linked to owl.js.

And it is maybe the right moment to create a task to the team 'regex' (@Feyensv) to replace all occurrences in master and remove the support officially in v15... https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_qweb.py#L431

2020-12-02 17:26 UTC, nim-odoo commented
@JKE-be We are planning to check in OWL as well.

2020-12-03 15:36 UTC, aab-odoo requested changes
I quickly checked, and the bug is in Studio, for a while (probably when the report editor has been introduced). It is at least in v13. The difference with v14, is that owl's props validation produces a crash, telling us that we provide a value for a boolean props that isn't a boolean (it is a weird Python object generated by py.js), which is thus always considered as true before v14, even if the underlying value is false. There is no need to update the templates here imho.

2020-12-04 11:10 UTC, closed without merging