[FIX] website_sale: compare id with id instead of record
odoo/odoo pull request #62924
Opened 2020-12-05 14:20 UTC by Yenthe666

Description of the issue/feature this PR addresses:  compare ID with an ID, not a record.

Current behavior before PR: Before this commit Odoo tries to compare an 'account.fiscal.position' id with an 'account.fiscal.position' record.
This causes a 'Comparing apples and oranges' warning in the logs and is not the right way to do this.
This is a fix for d89fa970e8e5b07f1b9a396e6ee02db7fdd136e4 where this issue was introduced

Desired behavior after PR is merged: Comparison of ID with an ID, not a record.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-12-05 14:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/62924).

2020-12-05 14:21 UTC, Yenthe666 commented
@kitan191 pinging you as the git history points back to you from https://github.com/odoo/odoo/commit/d89fa970e8e5b07f1b9a396e6ee02db7fdd136e4.

2020-12-05 14:24 UTC, wtaferner requested changes
One little remark

2020-12-05 14:24 UTC, wtaferner commented on addons/website_sale/models/website.py
>              )
```suggestion
            ).id
```

2020-12-05 14:24 UTC, wtaferner commented on addons/website_sale/models/website.py
> +            if sale_order.fiscal_position_id.id != fpos_id.id:
```suggestion
            if sale_order.fiscal_position_id.id != fpos_id:
```

2020-12-05 14:28 UTC, wtaferner approved these changes

2020-12-05 14:37 UTC, Yenthe666 commented
Closing in favor of https://github.com/odoo/odoo/pull/62925 as it was in 13.0 too.

2020-12-05 14:42 UTC, Yenthe666 commented
Actually still applies for V14.0 as the return value of `get_fiscal_position` has changed between V13 and V14.

2020-12-08 12:43 UTC, kitan191 commented
@rdeodoo LGTM

`get_fiscal_position` used to return an `id` in 13.0, but it has been changed in `14.0`
Now it returns a record.
I've missed it in the forward-port. My bad!

Without this fix, previous cart is discarded at each connection.

2020-12-08 12:49 UTC, rdeodoo commented
@kitan191 thank you, can you handle the r+? I can't

2020-12-08 12:50 UTC, kitan191 commented
> @kitan191 thank you, can you handle the r+? I can't

Me neither.

ping @nim-odoo

2020-12-08 12:58 UTC, JKE-be commented
@robodoo r+

2020-12-08 14:03 UTC, closed without merging

2020-12-08 14:23 UTC, Yenthe666 commented
Thank you all :)