[FIX] hr_expense: expense reconciliation
odoo/odoo pull request #63302
Opened 2020-12-14 10:08 UTC by adwid

The reconciliatin between an expense and a bank statement does not
update the expense and its sheet.

To reproduce the error:
(Need account_accountant)
1. Go to Expenses
2. Create one (e.g. an expense of $20)
3. Save, Create Report, Approve, Post Journal Entries
4. Go to Accounting > Bank
5. Create a bank statement (e.g. $-20)
6. Save, Post, Reconcile
7. Select the expense, Validate
8. Go to Expense > The created expense

=> The expense's state is still 'Approved'. It should be 'Paid'.
Moreover, if you click on the associated report ("View Report"), the
same error appears: the sheet's state is 'Posted' instead of 'Paid'.

The problem was that the method 'action_invoice_paid' (deleted in this
commit) was never reached. Moreover, there was no way to get the
expense's residual amount.

OPW-2389414

2020-12-14 10:09 UTC, adwid commented
@smetl

2020-12-14 10:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/63302).

2020-12-14 13:56 UTC, adwid commented
robodoo retry

2020-12-14 13:57 UTC, robodoo commented
I'm sorry, @adwid. Retry makes no sense when the PR is not in error.

2020-12-15 08:53 UTC, smetl requested changes

2020-12-15 08:53 UTC, smetl commented on addons/hr_expense/models/account_move_line.py
> +        paid_expenses.write({'state': 'done'}) # idk how to set an expense as paid
remove the comment :p

2020-12-15 08:53 UTC, smetl commented on addons/hr_expense/models/hr_expense.py
> +                return
`continue`!

2020-12-17 07:25 UTC, adwid commented
Fix must first be applied in master.
See #63486

2020-12-17 13:56 UTC, adwid commented
@jpp-odoo

2020-12-17 14:01 UTC, jpp-odoo commented
@robodoo delegate+

2020-12-17 14:21 UTC, adwid commented
robodoo r+

2020-12-17 14:24 UTC, adwid commented
@fw-bot ignore

2020-12-17 14:57 UTC, robodoo commented
Staging failed: ci/template on 1d82bc61386e066f98227813c1a8c6ee2777224b (view more at http://runbot.odoo.com/runbot/build/5445867)

2020-12-17 14:58 UTC, adwid commented
robodoo retry

2020-12-17 16:32 UTC, closed without merging