[IMP] account_lock: Update the module description
odoo/odoo pull request #63394
Opened 2020-12-15 13:23 UTC by vin-odoo

In order to clarify the purpose of the account_lock module, slightly
update its description.

Task id #2382740

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2020-12-15 13:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/63394).

2021-01-14 09:37 UTC, smetl requested changes
Plz update the `.pot` file accordingly

2021-01-14 11:19 UTC, vin-odoo commented
While looking at the pot file I saw that the old lines were used as user errors too, so I took the liberty to also update them.

2021-01-14 13:55 UTC, smetl reviewed
@robodoo r+

2021-01-14 14:43 UTC, closed without merging