[FIX] website_slides: Complete courses with video
odoo/odoo pull request #63684
Opened 2020-12-22 11:44 UTC by abz-odoo

What are the steps to reproduce your issue ?

    1. Install ELearning
    2. Create a course
    3. Add a video from youtube
    4. Attempt to do the course from a user that is invited

What is currently happening ?

    You cannot complete a video (turn the checkmark green) if there is not a quiz. Therefore you cannot complete the course

What are you expecting to happen ?

    Turn the checkmark green to signify that video is completed after watching the video and then have the ability to complete the course

Why is this happening ?

    Because of this commit https://github.com/odoo/odoo/pull/61581/files
    that changes 'youtube.com' to 'youtube-nocookie.com'

How to fix the bug ?

    Change to 'youtube-nocookie.com' at the setup of the youtube video

opw-2418545

2020-12-22 11:44 UTC, abz-odoo commented
@tde-banana-odoo

2020-12-22 11:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/63684).

2020-12-24 09:55 UTC, abz-odoo commented
@agr-odoo @nle-odoo

2020-12-28 14:19 UTC, agr-odoo requested changes
I believe* you are not required to specify the `host` so you could just omit that to avoid future issue like this
```diff
diff --git a/addons/website_slides/static/src/js/slides_course_fullscreen_player.js b/addons/website_slides/static/src/js/slides_course_fullscreen_player.js
index 01d1aba3609..a9afc6c1892 100644
--- a/addons/website_slides/static/src/js/slides_course_fullscreen_player.js
+++ b/addons/website_slides/static/src/js/slides_course_fullscreen_player.js
@@ -74,7 +74,6 @@ odoo.define('website_slides.fullscreen', function (require) {
          */
         _setupYoutubePlayer: function (){
             this.player = new YT.Player('youtube-player' + this.slide.id, {
-                host: 'https://www.youtube.com',
                 playerVars: {
                     'autoplay': 1,
                     'origin': window.location.origin
```

\* According to [other snippets](https://github.com/odoo/odoo/blob/c2bd3713ca2ecfe0abcb579e121b18f30cb1ace7/addons/website/static/src/js/content/snippets.animation.js#L812) and the [reference documentation](https://developers.google.com/youtube/player_parameters)

2020-12-28 15:50 UTC, nle-odoo approved these changes
if agr change works, this seems better

since the code seems to be the same in saas-12.3, I rebased this PR on saas-12.3

2020-12-29 09:32 UTC, nle-odoo reviewed
robodoo r+

2020-12-29 10:09 UTC, closed without merging