[FIX] mail: fix click event handling when renaming DM
odoo/odoo pull request #63785
Opened 2020-12-24 15:03 UTC by xdu-odoo

task-2414811

2020-12-24 15:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/63785).

2020-12-24 15:04 UTC, xdu-odoo commented
What do yo guys think of this approach ? The problem is that EditableComponent triggers 'o-clicked' event but do not stop propagation of 'click' which is handled by onClick and then close the editable.

2020-12-24 15:14 UTC, alexkuhn requested changes
Looks decent. I would mark event in `_onClick` of `EditableText` as handled, and checks whether it was handled by it in `_onClick` of `DiscussSidebarItem`. The advantage of doing this is that it doesn't require ref and it has improved traceability.

2020-12-24 15:38 UTC, alexkuhn reviewed
Small remarks then good to merge

2020-12-24 15:38 UTC, alexkuhn commented on addons/mail/static/src/components/discuss_sidebar_item/discuss_sidebar_item.js
> +const { isEventHandled } = require('mail/static/src/utils/utils.js');
define just below `const useStore = ...` (and keep single empty line before `const Dialog = ...`)

2020-12-24 15:38 UTC, alexkuhn commented on addons/mail/static/src/components/editable_text/editable_text.js
> +const { markEventHandled } = require('mail/static/src/utils/utils.js');
define below `'use strict';` with single empty line (and keep single empty line before `const { Component } = ...`)

2021-01-11 09:43 UTC, xdu-odoo commented
Ping ?

2021-01-11 09:55 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_item/discuss_sidebar_item.js
> +            // handled in `_onClickedEditableText`
Not very important but comment is overkill, we know where it comes from with the event handled name.

2021-01-13 11:00 UTC, seb-odoo approved these changes
@robodoo r+

2021-01-13 12:23 UTC, closed without merging