[FIX] portal: Due in %d days is not translated
odoo/odoo pull request #64160
Opened 2021-01-06 14:37 UTC by backspac

Steps:
- Install Invoicing and load French
- Go to Invoicing
- Click an invoice due in the future
- Click Preview
- Switch the preview to French by modifying the URL like this: example.com/my/invoices/6 -> example.com/fr_FR/my/invoices/6

Bug:
"Due in %d days" is still displayed in English. The rest of the page is in French.

Explanation:
This is due to two things:
1. `mail` and `portal` are both installed and we cannot have more than one `code` translation of a source [1]. Since `mail` is loaded before, alphabetically, `portal` doesn't add the duplicated translations with its own module name. When loading a web page, only the modules returned by `_get_translation_frontend_modules_domain()` are sent to the frontend. `mail` is not one of them and the duplicated translations are not sent. Adding `mail` in the query for `portal` translations makes the backend send `mail` translations to the frontend.
2. Translations in `portal_sidebar.js` are queried before the translation DB [2] is made. This results in an empty array and `_t()` returns the source. `session.is_bound` will wait until the app is fully loaded before querying.

[1] https://github.com/odoo/odoo/blob/ad2d96db8ad3e1fd7af2edda218fc34c0c1d259a/odoo/addons/base/models/ir_translation.py#L290
[2] https://github.com/odoo/odoo/blob/0de069b8ca9fb005ba5b076984f5677de25889ee/addons/web/static/src/js/core/translation.js#L51

opw:2421501

2021-01-06 14:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64160).

2021-01-06 14:44 UTC, backspac commented
@yelizariev Can you review this?

2021-01-06 15:46 UTC, yelizariev commented
Indeed, we have the term in mail and portal

https://github.com/odoo/odoo/blob/e2084a4356f63249920d8c777e92f1710be8b5a6/addons/mail/static/src/js/activity.js#L99
https://github.com/odoo/odoo/blob/e2084a4356f63249920d8c777e92f1710be8b5a6/addons/portal/static/src/js/portal_sidebar.js#L41

0.

The fix of this PR will load to frontend extra 1500 terms from mail modules (@JKE-be, what do think about it?)

![image](https://user-images.githubusercontent.com/186131/103786200-72d8c200-503c-11eb-8a6f-9441411a61ba.png)

1.

Alternative solution is changing portal term, e.g.

``Due in %d days`` -> ``Due in %1d days``.

2.

Also, as a workaround user could find the term and change ``module`` value from mail to portal.

---

I'm in favor of solution n.1

@mart-e what do you think?

2021-01-07 08:07 UTC, mart-e commented
Hi there,
Loading the `mail` translations is not correct as it's not actually what we want and loading every web translation of a module for one term is a bit overkill.
This is yet another example for the need of a better granularity to distinguish web and frontend translations.

The 1) is definitly the easiest workaround (you could also change to `Due in %d day(s)` for instance). And indeed, if it's not working, we aren't making it worse ;-)
This is still a very fragile hack to intentionnaly try to make terms uniques. Will work today but for how long...

2021-01-07 12:54 UTC, yelizariev approved these changes

2021-01-07 12:56 UTC, backspac commented
@jpp-odoo I think this is good to be merged.

2021-01-08 08:41 UTC, jpp-odoo requested changes
As @mart-e said, this is a very fragile hack, so I would add a comment on the code to explain why we use %1d instead of the classic %d.

@robodoo delegate+

2021-01-08 09:19 UTC, backspac commented
robodoo r+

2021-01-08 10:18 UTC, closed without merging