[FIX] web_editor: fix icon color preview not getting reset correctly
odoo/odoo pull request #64336
Opened 2021-01-11 13:22 UTC by sdegueldre

Previously, hovering a color or background color while having an icon
selected would preview the color, but upon leaving that color, it would
be reset to the equivalent (text color or background color) from its
parent instead. This was caused by the fact that the font-color code
created a range from the current selection, and used its starting
container to read the currently selected color, but because icons
typically have no content, the range start container was set to the
icon's container instead of the icon itself, causing the initial color
to be considered that of the container, and would reset to that color
instead of the icon's own initial color

This commit fixes that by setting the target node as the first node of
the range when possible (which is also what the font-applying code does)

2021-01-11 13:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64336).

2021-01-19 14:52 UTC, sdegueldre commented
@qsm-odoo not sure if you've seen this one or if it's flown under your radar, it's the thing we talked about with sbu concerning text-color and background-color previews in the html editor. It doesn't quite fix the problem of resetting the color on a range that contains multiple colors, but it should fix the preview-reset being broken on fontawesome icons at least.

2021-01-19 15:48 UTC, qsm-odoo requested changes
@sdegueldre Triple-click a text, open the colorpicker -> crash. There are also issues (but seems not to be the fault of this PR) trying to change a color previously set after reselecting... If that is not possible to resolve, let's remove the previews...

2021-01-20 06:44 UTC, sdegueldre commented
> There are also issues (but seems not to be the fault of this PR) trying to change a color previously set after reselecting... If that is not possible to resolve, let's remove the previews...

@qsm-odoo not sure what you mean here, could you explain with some more details?

2021-01-20 09:14 UTC, qsm-odoo commented
Select the text, change its color, do something else, reselect the text, try to change the color, fail.

2021-01-21 08:35 UTC, sdegueldre commented
> Select the text, change its color, do something else, reselect the text, try to change the color, fail.

@qsm-odoo I'm not able to reproduce this.

2022-03-08 06:59 UTC, closed without merging