[FIX] website: page visibility 'connected' leads to a 403 when connected
odoo/odoo pull request #64596
Opened 2021-01-15 10:19 UTC by backspac

Steps:
- As admin, go to "Contact us" or any other page on the website (1)
- Go to Pages > Page Properties > Publish
- Change the visibility to Signed In
- Save
- As demo, go to (1)

Bug:
The user "demo" is signed in but is returned a 403 Forbidden

Explanation:
When landing on a page with visibility: 'connected', the only way to see
the page is to have a group matching the groups of the page as seen
here: https://github.com/odoo/odoo/blob/28b748a559e1ffb5fb7c3631bf77adba121b2ebf/odoo/addons/base/models/ir_ui_view.py#L625-L626
This fix lets any connected users see the page.

opw:2431700

2021-01-15 10:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64596).

2021-01-15 10:57 UTC, backspac commented
Ping @jpp-odoo

2021-01-18 08:31 UTC, jpp-odoo requested changes
I will just change the line 368 : `if self.visibility != 'password':`
into : `if self.visibility not in ('password', 'connected'):`

2021-01-18 09:34 UTC, JKE-be commented
et supprimer le commentaire 370 tant qu'on y est ;) thx

2021-01-18 15:53 UTC, jpp-odoo approved these changes
@robodoo delegate+

2021-01-18 15:57 UTC, backspac commented
@robodoo r+

2021-01-18 17:26 UTC, closed without merging