[FIX] account: Purchase journal
odoo/odoo pull request #64741
Opened 2021-01-19 10:49 UTC by simongoffin

A purchase journal cannot be created without an expense account

opw:2431278

2021-01-19 10:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64741).

2021-01-20 15:00 UTC, qdp-odoo commented
why do you change/fix only ¼ of the occurrences of the default_account_id with that specific condition on the `required` attrs ?

2021-01-20 16:51 UTC, simongoffin commented
@qdp-odoo Why a purchase journal can be created without an expense account but when you want to modify it, the same field is required?

2021-01-20 16:58 UTC, simongoffin commented
@qdp-odoo by presumption of innocence

2021-01-20 17:16 UTC, qdp-odoo requested changes
ok, actually it was partlyjustified: bank and cash journal creation will trigger the account.account creation that will be set as default. So for bank and cash it's legit to let the `id!=False` on required.

Sale and purchase journals should be treated equally, though.

2021-01-20 17:16 UTC, qdp-odoo commented on addons/account/views/account_journal_views.xml
> +                                               attrs="{'required': [('type', '=', 'bank')], 'invisible': [('type', '!=', 'bank')]}"
undo

2021-01-20 17:16 UTC, qdp-odoo commented on addons/account/views/account_journal_views.xml
> +                                               attrs="{'required': [('type', '=', 'cash')], 'invisible': [('type', '!=', 'cash')]}"
undo

2021-01-21 08:55 UTC, qdp-odoo commented
last thing: commit message should mention the sale journal as well, not only the purchase one

2021-01-21 10:03 UTC, simongoffin commented
robodoo r+

2021-01-21 11:22 UTC, closed without merging