[IMP] mail: added edit feature for message
odoo/odoo pull request #64905
Opened 2021-01-22 10:16 UTC by pka-odoo

- added edit icon in message core if the current user is author of the message
- added more button in message core, that contains edit button
- edit the message with emoji and attachment
- inline composer for desktop device and using existing composer for
  mobile devices

taskId: 2362167

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-01-22 10:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64905).

2021-01-22 12:43 UTC, seb-odoo requested changes
Hello, here is a quick check of the code as you requested it. I gave some very specific comments on some lines, but overall I think we are not ready technically to make this task.

The main issue is that once the message exits, its content is html, and the only proper way to allow editing html is to have the web editor. And we are not allowed to use the existing one, because we know we will replace it as soon as possible. (There is nothing to do but wait.)

The second issue (which can be fixed from us) is that there is currently a problem with the composer model and the message model. I see what you have been forced to do to for this PR and it is not easy to maintain.
First we should have one composer model per composer component, instead of one composer model per thread model.
Second composer should always be modeling a message, and it should be able to distinguish from a new message or an existing message more easily, and with a lot more common code between the two.

2021-01-22 12:43 UTC, seb-odoo commented on addons/mail/static/src/components/message/message.scss
> +    border: none !important;
important is a keyword we should never use, if this has to override something, it's better to "remove the something" instead or add it only conditionally

2021-01-22 12:43 UTC, seb-odoo commented on addons/mail/static/src/components/message/message.xml
> -                        </div>
why is all of this moved?

2021-01-22 12:43 UTC, seb-odoo commented on addons/mail/static/src/models/composer/composer.js
> +        }
I don't like that we need to handle this manually. I still think we should postpone this task until we have the new web editor ready to use.

2024-03-11 13:17 UTC, tde-banana-odoo commented
Done (with a nice commit message) at https://github.com/odoo/odoo/pull/76483

2024-03-11 13:17 UTC, closed without merging