[FIX] stock_account: allow user to validate transfer
odoo/odoo pull request #64943
Opened 2021-01-22 14:42 UTC by agr-odoo

- Create a [DEMO] user with user access to inventory
- Create an account tag for taxes
- Add that account tag to the purchase tax under Tax grid
- As 'Admin' user create and confirm a PO with that tax
- Let this transfer to be validated by [DEMO]

A permission error on account.tag will block [DEMO] from
validating the transfer

opw-2382794

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-01-22 14:43 UTC, agr-odoo commented
@fw-bot ignore

2021-01-22 14:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/64943).

2021-01-22 15:54 UTC, agr-odoo commented
@jpp-odoo 

When dealing with security issues we have several possibilities and I feel often doubtful on what to use when, so I would really use a suggestion

Relevant stack
*X* patch applied here
```
  File "/home/odoo/Projects/odoo-13.0/odoo/api.py", line 374, in _call_kw_multi                                    
    result = method(recs, *args, **kwargs)
  File "/home/odoo/Projects/odoo-13.0/addons/stock/wizard/stock_immediate_transfer.py", line 34, in process       
    pick_to_do.action_done()       
  File "/home/odoo/Projects/odoo-13.0/addons/stock/models/stock_picking.py", line 730, in action_done          
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/home/odoo/Projects/odoo-13.0/addons/stock_account/models/stock_move.py", line 265, in _action_done        
    stock_valuation_layers |= getattr(todo_valued_moves, '_create_%s_svl' % valued_type)()
  File "/home/odoo/Projects/odoo-13.0/addons/stock_account/models/stock_move.py", line 156, in _create_in_svl               
   unit_cost = abs(move._get_price_unit())  # May be negative (i.e. decrease an out move). 
  File "/home/odoo/Projects/odoo-13.0/addons/purchase_stock/models/stock.py", line 43, in _get_price_unit            
    price_unit = line.taxes_id.with_context(round=False).compute_all(price_unit, currency=line.order_id.currency_id, quantity=1.0)['total_void']
  File "/home/odoo/Projects/odoo-13.0/addons/account/models/account.py", line 1796, in compute_all
X   'tag_ids': (repartition_line.tag_ids + subsequent_tags).ids,
```

we could make the `sudo()` call at a higher level

```
  File "/home/odoo/Projects/odoo-13.0/odoo/api.py", line 374, in _call_kw_multi                                    
    result = method(recs, *args, **kwargs)
  File "/home/odoo/Projects/odoo-13.0/addons/stock/wizard/stock_immediate_transfer.py", line 34, in process       
    pick_to_do.action_done()       
  File "/home/odoo/Projects/odoo-13.0/addons/stock/models/stock_picking.py", line 730, in action_done          
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/home/odoo/Projects/odoo-13.0/addons/stock_account/models/stock_move.py", line 265, in _action_done        
    stock_valuation_layers |= getattr(todo_valued_moves, '_create_%s_svl' % valued_type)()
  File "/home/odoo/Projects/odoo-13.0/addons/stock_account/models/stock_move.py", line 156, in _create_in_svl               
X   unit_cost = abs(move._get_price_unit())  # May be negative (i.e. decrease an out move).
  File "/home/odoo/Projects/odoo-13.0/addons/purchase_stock/models/stock.py", line 43, in _get_price_unit            
    price_unit = line.taxes_id.with_context(round=False).compute_all(price_unit, currency=line.order_id.currency_id, quantity=1.0)['total_void']
  File "/home/odoo/Projects/odoo-13.0/addons/account/models/account.py", line 1796, in compute_all
    'tag_ids': (repartition_line.tag_ids + subsequent_tags).ids,
```
or use a security rule in `stock_account`

2021-01-25 09:55 UTC, jpp-odoo requested changes
I'm not sure that adding a sudo() into the Accounting module to solve an issue on the stock module is a good idea.
I will just modify the access rules into the bridge module (stock_accouting) like : 
access_account_tag_stock_manager,account.tag stock manager,account.model_account_account_tag,stock.group_stock_user,1,0,0,0 (addons/stock_account/security/ir.model.access.csv)

If you place the sudo into a higher place, you can propagate the sudo into functions that you don't want, so this is not a good idea.

@qdp-odoo What do you think about this ?

Also, in the commit message, it will be easy if you add the modules needed to reproduce the issue : Accounting, Purchased and Inventory. Also specify that the [DEMO] user don't have right acess to Accounting.

2021-01-25 10:16 UTC, agr-odoo commented
> I'm not sure that adding a sudo() into the Accounting module to solve an issue on the stock module is a good idea.
> I will just modify the access rules into the bridge module (stock_accouting) like :
> access_account_tag_stock_manager,account.tag stock manager,account.model_account_account_tag,stock.group_stock_user,1,0,0,0 (addons/stock_account/security/ir.model.access.csv)

I prefer this way too, but I was not sure to add a new rule just for a single line of code

> Also, in the commit message, it will be easy if you add the modules needed to reproduce the issue : Accounting, Purchased and Inventory. Also specify that the [DEMO] user don't have right acess to Accounting.

Done, thanks for the note

2021-01-27 11:43 UTC, jpp-odoo commented
@robodoo delegate+

2021-01-29 11:38 UTC, agr-odoo commented
robodoo r+

2021-01-29 12:24 UTC, closed without merging