[FIX] website: disable anchor option for popup
odoo/odoo pull request #65055
Opened 2021-01-26 11:57 UTC by bvr-odoo

task-2172312

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-01-26 11:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/65055).

2021-02-01 10:18 UTC, qsm-odoo requested changes

2021-02-01 10:18 UTC, qsm-odoo commented on addons/website/views/snippets/snippets.xml
> +        data-exclude=".modal *, .oe_structure .oe_structure *, [data-oe-type=html] .oe_structure *, .s_popup, .o_newsletter_popup">
`o_newsletter_popup` is not a class of the website application

2021-02-15 18:43 UTC, qsm-odoo approved these changes
@robodoo r+

2021-02-15 18:44 UTC, robodoo commented
@qsm-odoo, you may want to rebuild or fix this PR as it has failed CI.

2021-02-16 09:20 UTC, bvr-odoo commented
> @qsm-odoo, you may want to rebuild or fix this PR as it has failed CI.

@qsm-odoo I have rebuilt and now it works

2021-02-16 09:22 UTC, qsm-odoo approved these changes
@robodoo r+

2021-02-16 10:55 UTC, closed without merging