[FIX] Resequence wizard not working in latam
odoo/odoo pull request #65673
Opened 2021-02-06 18:12 UTC by pepetreshere

The resequence wizard fails with "expected singleton" error.
The resequence wizard located at Accounting / Accounting / Journal Entries, under the action "Resequence" should allow to change the number of manual jorunal entries, but it fails in localizations where whe need to inherit the method _is_manual_document_number() as it is called with self instad of rec.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-02-06 18:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/65673).

2021-02-08 08:28 UTC, william-andre requested changes
Before being able to merge one of your PRs, you must first sign the CLA https://github.com/odoo/odoo/blob/14.0/doc/cla/sign-cla.md

The method `_is_manual_document_number` is supposed to work like an `@api.model`, even if it is not explicitly declared. The cleanest way would be to call it like this:
```python
self.env['account.move']._is_manual_document_number(rec.journal_id)
```

This said, I don't see anywhere in the code where having `self` instead of `rec` could raise a traceback. Do you have one?

2021-02-12 02:49 UTC, pepetreshere commented
Hello @william-andre, thanks for reviewing the PR. I have signed the CLA in this same PR

It breaks when l10n_latam_document_type is installed and you try to excecute the "Resequence" wizard in the method [resequence()](https://github.com/odoo/odoo/blob/14.0/addons/account/wizard/account_resequence.py#L139), on the last line when it tries to write the result it breaks as the computed field can't be calculated for several invoices at the time as it uses self instead of rec.

I think that even if it would't break it should be rec instead of self as this is the common way to declare computed fields.

Thanks in advance for your review

2021-02-12 08:21 UTC, william-andre commented
I agree that the method should maybe have been declared as 
```python
    def _is_manual_document_number(self):
        self.ensure_one()
        return True if self.journal_id.type == 'purchase' else False
```
instead of
https://github.com/odoo/odoo/blob/157ac9a5bb034dec5edd630ea5d1c929e80ca7ea/addons/l10n_latam_invoice_document/models/account_move.py#L84-L85

Then your PR would make sense indeed. But it is not the case, so nothing should be breaking; especially not in the part of the code you linked.
https://github.com/odoo/odoo/blob/157ac9a5bb034dec5edd630ea5d1c929e80ca7ea/addons/account/wizard/account_resequence.py#L139
This is using recordsets of length equal to one already.

You can make a PR in master to change the declaration of `_is_manual_document_number` if you wish, but this is unnecessary diff in a stable version, which we try to avoid. (unless you can provide me a traceback to prove me wrong)

2021-02-12 08:21 UTC, closed without merging