[IMP] hr: Create activity a month before Work Permit Expiration Date
odoo/odoo pull request #65899
Opened 2021-02-10 16:02 UTC by sofiagvaladze

Add boolean field to upload work permit

Task - 2442648

2021-02-10 16:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/65899).

2021-04-30 12:57 UTC, kba-odoo requested changes

2021-04-30 12:57 UTC, kba-odoo commented on addons/hr/models/hr_employee.py
> +        nearly_expired_work_permits = self.search([('work_permit_activity_scheduled', "=", False), ('work_permit_expire', '<', outdated_days)])
```suggestion
        nearly_expired_work_permits = self.search([('work_permit_activity_scheduled', '=', False), ('work_permit_expire', '<', outdated_days)])
```

2021-04-30 12:57 UTC, kba-odoo commented on addons/hr/models/hr_employee.py
> +                nearly_expired_work_permits.write({'work_permit_activity_scheduled': True})
This line should be out of the loop

2021-05-20 14:24 UTC, tivisse reviewed
Small review. You may ping me once it's done :)

Thanks for your work.

2021-05-20 14:24 UTC, tivisse commented on addons/hr/models/hr_employee.py
> +    work_permit_expire = fields.Date('Work Permit Expiration Date', groups="hr.group_hr_user", tracking=True)
```suggestion
    work_permit_expiration_date = fields.Date('Work Permit Expiration Date', groups="hr.group_hr_user", tracking=True)
```

2021-05-20 14:24 UTC, tivisse commented on addons/hr/models/hr_employee.py
> +    work_permit = fields.Binary(string="Work Permit", groups="hr.group_hr_user", tracking=True)
```suggestion
    has_work_permit = fields.Binary(string="Work Permit", groups="hr.group_hr_user", tracking=True)
```

2021-05-20 14:24 UTC, tivisse commented on addons/hr/models/hr_employee.py
> +    work_permit_activity_scheduled = fields.Boolean(default=False, groups="hr.group_hr_user")
```suggestion
    work_permit_scheduled_activity = fields.Boolean(default=False, groups="hr.group_hr_user")
```

2021-05-20 14:24 UTC, tivisse commented on addons/hr/models/hr_employee.py
> +        employees_scheduled.work_permit_activity_scheduled = True
To make it work in batch:
```suggestion
        employees_scheduled.write({'work_permit_activity_scheduled': True})
```

2021-05-25 10:13 UTC, tivisse commented
@robodoo r+

2021-05-25 10:50 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#2173 not ready. Linked PRs are not staged until all of them are ready.

2021-05-26 11:56 UTC, closed without merging