[FIX] mail: prevent message separator for new conversations
odoo/odoo pull request #65952
Opened 2021-02-11 11:49 UTC by ibo-odoo

**Before this commit:**

When a new conversation is initiated, the 'new messages' separator is displayed.
This looks a bit weird as there is no history of conversation and thus no older
messages from which new messages should be separated.

**After this commit:**

The 'new messages' separator will not be displayed in new conversations.

**LINKS**

PR
Task-2453511

2021-02-11 11:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/65952).

2021-02-12 14:33 UTC, seb-odoo requested changes
Hello, fix looks good, just some test cleanup comment. Thanks!

2021-02-12 14:33 UTC, seb-odoo commented on addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
> +        is_pinned: false,
Those 2 should not be necessary to specific for the test.

2021-02-12 14:33 UTC, seb-odoo commented on addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
> +        },
This is not needed here, already asserted in other test.

2021-02-12 14:33 UTC, seb-odoo commented on addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
> +    );
not needed, already asserted in other test

2021-02-12 14:33 UTC, seb-odoo commented on addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
> +    );
Good, this is the important assertion. Just make sure the text is similar to text title (missing the "no history of conversation" part).

2021-02-12 14:33 UTC, seb-odoo commented on addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
> +    );
Also not needed

2021-02-15 05:58 UTC, ibo-odoo commented
Hello..! @seb-odoo Changes are done.. Thanks.

2021-02-17 14:38 UTC, seb-odoo approved these changes
@robodoo r+

2021-02-17 15:44 UTC, closed without merging