[FIX] web_editor: fix external warning image not being displayed
odoo/odoo pull request #66732
Opened 2021-02-24 07:14 UTC by sdegueldre

This was caused by the entire widget being invisible if quality options
where unavailable.

task-2466819

2021-02-24 07:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/66732).

2021-02-24 10:18 UTC, qsm-odoo requested changes

2021-02-24 10:18 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +        }
Mmh should it in fact be false for unsupported mimetype or should there be a warning too? (I don't know, do what you think is best).
As discussed, you can adapt the message in JS for the t-field image optimization

2021-03-02 14:14 UTC, sdegueldre commented
closes  #66435

2021-03-03 11:51 UTC, qsm-odoo requested changes

2021-03-03 11:51 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +                            title.setAttribute('title', _t("Due to technical limitations, you can only change optimization settings on this image by choosing it again in the media-dialog or reuploadi
https://github.com/odoo/odoo/wiki/Translations#adding-new-terms-when-suggesting-fixes-in-stable-versions :wink:

2021-03-03 11:51 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +                        title.textContent = _t(" Quality options unavailable");
If the starting space in that sentence is important, move it out of translation. Otherwise, simply remove it.

2021-03-05 14:16 UTC, qsm-odoo commented
@sdegueldre ?

2021-03-05 14:42 UTC, sdegueldre commented
@qsm-odoo sorry about that. Was absorbed in the many2many task.

2021-03-05 15:23 UTC, qsm-odoo approved these changes
@robodoo rebase-ff r+

2021-03-05 15:24 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-03-05 15:24 UTC, robodoo commented
@qsm-odoo, you may want to rebuild or fix this PR as it has failed CI.

2021-03-05 15:56 UTC, qsm-odoo approved these changes
@robodoo rebase-ff r+

2021-03-05 15:56 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-03-05 17:45 UTC, closed without merging

2021-03-09 11:12 UTC, qsm-odoo commented
@sdegueldre I have the message "Due to technical limitations, ..." instead of the mimetype message when choosing a unDraw image as a background image... could you fix that? :cold_sweat: