[FIX] account: sum balance doesn't make sens
odoo/odoo pull request #66932
Opened 2021-02-26 14:44 UTC by fmdl

Description of the issue/feature this PR addresses:
Go to runbot
- create some bank statement
- go to in the pivot view and group by date
--> Issue start/end balance are sum --> it doesn't make sens

@oco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-02-26 14:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/66932).

2021-03-04 15:37 UTC, oco-odoo requested changes
Also, please make your commit message a little more explicit (and it's an IMP more than a FIX imo). You can even put the PR description within the commit message; it's good to know what was the issue exactly directly from the commit.

I suggest:
[IMP] account: bank statements pivot vue: don't sum start and ending balance
+ your PR description

2021-03-04 15:37 UTC, oco-odoo commented on addons/account/models/account_bank_statement.py
> +    balance_start = fields.Monetary(string='Starting Balance', states={'confirm': [('readonly', True)]}, compute='_compute_starting_balance', readonly=False, store=True, group_operator='max')
Wouldn't it make more sense with 'min' instead of 'max' here ?

2021-05-17 09:04 UTC, oco-odoo commented
Wouldn't it make more sense to add a pivot and graph view on statement lines directly, then? With something like this https://github.com/odoo/odoo/compare/14.0...odoo-dev:14.0-graph-st-lines-oco ? (if you're okay with this, I can make it a PR)

2021-05-17 11:28 UTC, fmdl commented
It is not the same things, in your PR you just sum amount of each operations. You don't have the amount in the bank account.

You should create a specific SQL view to compute the balance of account, with initial amount and group by per days (with using `account.move.line`)

2021-05-21 11:54 UTC, tsb-odoo commented
> It is not the same things, in your PR you just sum amount of each operations. You don't have the amount in the bank account.
> 
> You should create a specific SQL view to compute the balance of account, with initial amount and group by per days (with using `account.move.line`)

May I suggest you, @fmdl, to send us a feedback about the functional need ? I can consider if we put it in our next tasks. 
cc : @oco-odoo

2021-06-24 20:26 UTC, closed without merging