[FIX] web_editor: show mimemtype warning for illustrations
odoo/odoo pull request #67584
Opened 2021-03-10 12:00 UTC by sdegueldre

Previously, when clicking on an illustration in the editor, the image
options would be unavailable with a message saying that it was due to
technical limitations, and that the user should reselect the image in
the media-dialog for quality options to become available. This was
caused by the fact that in order to support more than one customizable
color in illustrations, they are now saved inside the database with an
url containing which colors are customizable inside the url's query
parameters. Since the endpoint that finds which attachment corresponds
to which image src was looking for an exact URL match, but query params
are trimmed on the client side before talking to the endpoint, they were
no longer matching.

This commit fixes that by searching for attachments whose URL matches
the provided one with or without any extra query parameters.

2021-03-10 12:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/67584).

2021-03-10 12:48 UTC, qsm-odoo requested changes
What's a mimemtype?

2021-03-10 15:49 UTC, qsm-odoo approved these changes
@sdegueldre I fixed the typo in the title. Note: your branch was also 700 commits behind saas-14.1... strange for a branch you created today :thinking: Anyways, thanks for the fix :+1: 

@robodoo r+

2021-03-10 17:33 UTC, closed without merging

2021-03-11 07:19 UTC, sdegueldre commented
> @sdegueldre I fixed the typo in the title. Note: your branch was also 700 commits behind saas-14.1... strange for a branch you created today thinking Anyways, thanks for the fix +1
> 
> @robodoo r+

@qsm-odoo I think I tried to checkout `14.1` and pulled, but then I realized the `14.1` checkout failed because it doesn't exist, and probably forgot to pull on `saas-14.1` :sweat_smile: