[IMP] account,website_sale: improved ux of terms and conditions.
odoo/odoo pull request #68225
Opened 2021-03-23 09:48 UTC by ham-odoo

Currently in the settings of Invoicing(account) if the user wants his terms
and conditions, as web then pad was there that pad, was not responsive.

So after this commit, if the user has rights for the website builder then it
will open a website builder page where the user can edit terms and conditions on
a web page. If the user does not have rights to website builder then that same
will open in a pop-up window.

In that terms and conditions, the template of default terms and conditions is
also added, that template will appear with the current company's name and
country, however, the user can edit that.

**Task-id - :- 2414659**

2021-03-23 09:49 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68225).

2021-03-23 11:19 UTC, JKE-be requested changes
Please create your PR in draft while it is not ready, and reviewed a minimal.

Code for website part is wrong
You should never create  a website.route it is loaded from controller file and only for autocomplete in form view
You should never write on a website.route it is only there for autocomplete in form view
You should not redirect a page on itself
Your search are duplicated
You should never access ir.config.parameter icp to have the base domain that is dynamic on record according to website_id -> get_base_url
Term_url should probably be just 'relative' and remove all the new method and code that hack it
"Open in Web Designer" is probably wrong terms, designer is the people, editor our product
Please describe why you change post_init_hook to pre_init_hook

2021-04-01 10:19 UTC, mba-odoo commented
@JKE-be , Done the changes. Thanks

2021-09-01 13:26 UTC, Feyensv commented
@robodoo r+

2021-09-01 13:41 UTC, rdeodoo commented on addons/website_sale/models/res_config_settings.py
> +    @api.depends('website_id')
Probably 'company_id' too as it impact the `get_base_url()` return but that's not the only place it is written without it :shrug:  so no need to r-

2021-09-01 15:49 UTC, rdeodoo commented on addons/website_sale/models/res_config_settings.py
> +    @api.depends('website_id')
it is also probably missing `website_id.domain` which is more problematic IMO

2021-09-01 23:08 UTC, closed without merging