[FIX] l10n_latam_invoice_document: only trigger constraint when partn…
odoo/odoo pull request #68308
Opened 2021-03-24 14:36 UTC by jco-odoo

…er_id is set

Before, when importing twice the same invoice, or even with the more
theoretical possibility of having the same number for different partners,
the constraint would be triggered, giving unnecessary problems when
importing vendor bills with an uncertain partner_id.

If we check the logic followed in the regular accounting on the ref field,
it only triggers when a partner is set, so we can follow the same logic here.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-03-24 14:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68308).

2021-03-24 14:40 UTC, jco-odoo commented
@Danisan I think this can be an important fix already to avoid errors while importing.

2021-03-24 15:19 UTC, william-andre requested changes
The constraint in the base module should only be triggered when the partner is known. It is not related to any l10n.

2021-03-24 15:24 UTC, jco-odoo commented
@william-andre This is a different constraint.

2021-03-25 13:20 UTC, jjscarafia approved these changes
LGTM. Tested un runbot, now the constraint only works if partner is set

2021-03-25 13:22 UTC, jco-odoo commented
@william-andre Can you reconsider?

2021-03-25 16:02 UTC, william-andre approved these changes
I already put a :+1: on your comment, but let's make it official then

2021-03-25 19:07 UTC, Danisan commented
Just a comment for reference: this will just prevent the exception when the partner is not set.

2021-03-26 10:41 UTC, william-andre commented
@robodoo r+

2021-03-26 11:30 UTC, closed without merging