[FIX] website_forum wrong number answer #68321
odoo/odoo pull request #68440
Opened 2021-03-29 01:22 UTC by daonamutc1

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

Fix website_forum wrong number answer 
#68321

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-03-29 01:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68440).

2021-03-29 06:56 UTC, JKE-be commented
Hello

Thanks for your contributions.

Please [sign our CLA](https://github.com/odoo/odoo/wiki/Sign-CLA
) to validate this PR before we take a look on it.


KR

2021-03-29 08:12 UTC, royleviindoo approved these changes

2022-07-29 14:44 UTC, rdeodoo requested changes
Sorry for the delay.
This doesn't seem to be fully fixing the problematic use case.
Please see https://watch.screencastify.com/v/1eavBWEq9gJenT42i6k8

2023-03-30 09:46 UTC, C3POdoo commented
Dear @daonamutc1,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2023-03-30 09:46 UTC, closed without merging