[FIX] account: Cash Basis - recompute tax exigibility on move creation
odoo/odoo pull request #68703
Opened 2021-04-02 13:16 UTC by Julien-CHEVREAU

Beforehand, tax exigibility was not systematically recomputed upon
move creation.

Now, as soon as an account move line is created on a move, tax exigibility
is recomputed.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-02 13:17 UTC, Julien-CHEVREAU commented
@oco-odoo, here it is!

2021-04-02 13:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68703).

2021-04-02 13:39 UTC, oco-odoo requested changes

2021-04-02 13:39 UTC, oco-odoo commented on addons/account/models/account_move.py
> +                rslt.update_lines_tax_exigibility()
Not exactly ;) Here, you're calling the function on all the resulting records, for each dict in vals list, so basically you're doing n² stuff. 
Rather

```suggestion
                for i, vals in enumerate(vals_list):
                    if 'line_ids' in vals:
                        rslt[i].update_lines_tax_exigibility()
```

2021-04-06 10:54 UTC, oco-odoo approved these changes
@robodoo r+

2021-04-06 11:45 UTC, closed without merging