[IMP] calendar: remove extended properties
odoo/odoo pull request #68887
Opened 2021-04-07 12:44 UTC by HydrionBurst

remove extended porperties for events without influencing the ownership during sync

taskid: 2491195

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-07 12:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68887).

2021-10-04 12:26 UTC, remybar requested changes

2021-10-04 12:26 UTC, remybar commented on addons/microsoft_calendar/models/calendar.py
> +        if not microsoft_event.isOrganizer:
Looks good to me except when the event:
- has been created in Outlook,
- the event is synced by a Odoo user who is an attendee of this event,
- the event organizer exists in Odoo.
In this case, as it was done before, I think we should find the organizer using the email set in the Outlook event.

So, as discussed on Discord, we could do something like:
1) if we don't want to allow an attendee modifying the event from Odoo when the organizer is not a Odoo user:
```python
if not microsoft_event.isOrganizer:
    values["user_id"] = user_id.id if env['res.users'].search([('email', '=', self.organizer['emailAddress']['address'])], limit=1) else False
```
2) if we want to allow an attendee to modify the Outlook event:
```python
if not microsoft_event.isOrganizer:
    values["user_id"] = user_id.id if env['res.users'].search([('email', '=', self.organizer['emailAddress']['address'])], limit=1) else self.env.user.id
```

2024-04-16 08:55 UTC, C3POdoo commented
Dear @HydrionBurst,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 08:55 UTC, closed without merging