[FIX] web_editor: fix default shapes not redacting to palette changes
odoo/odoo pull request #68893
Opened 2021-04-07 13:07 UTC by sdegueldre

Previously, when toggling on background shapes, they always had the
default colours. In 1e30bce81eb8deb732747f8964ebd7fcd78c802c we made it
so that when you toggle on a shape on a section, it would automatically
reuse the colors of the surrounding shapes if any.

Unfortunately, when the "implicit" colors were also the default colors,
they were still marked on the shape, and it got an explicit background
image that would no longer react to changes in the palette.

This was caused by the fact that the call to _getDefaultColors returns
an empty object when the section doesn't already have a shape-container,
this was not a problem before since we were not passing in any colors
when creating the initial shape previously, the the aforementioned
change made it so that we did.

This commit fixes the issue by creating the shape-container before
calling the method that will set the colors on the shape, this way
getDefaultColors works as expected, and the colors are not marked on the
section when they are the default ones, restoring the ability of the
shape colors to adapt to the palette

task-2500607

Co-authored-by: Tom De Caluwé <tdc@odoo.com>

2021-04-07 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68893).

2021-04-07 15:05 UTC, bso-odoo approved these changes
Nicely spotted.
Changes in the code are sound and clear, no comment there.
There is a "the the" typo in the commit message.

2021-04-20 11:35 UTC, qsm-odoo requested changes

2021-04-20 11:35 UTC, qsm-odoo commented on addons/website/static/tests/tours/default_shape_gets_palette_colors.js
> +tour.register("default_shape_gets_palette_colors", {
You add a test but you don't use it :thinking:

2021-04-28 11:05 UTC, sdegueldre commented
@qsm-odoo sorry for the delay, added the python test to start the tour and rebased

2021-04-28 14:05 UTC, qsm-odoo approved these changes
You mentioned a dev commit in your commit message instead of the merged one :wink: 
![Screenshot from 2021-04-28 16-00-56](https://user-images.githubusercontent.com/10338094/116417393-80a89200-a83b-11eb-81d4-c770021f4fb1.png)

I fixed it ;)

@robodoo r+

2021-04-28 16:41 UTC, closed without merging