[IMP] website : improve theme_view_kaban : better themes descriptions
odoo/odoo pull request #68985
Opened 2021-04-08 14:46 UTC by tsm-odoo

Task : https://tinyurl.com/8jse3wn2
This PR is linked to : https://github.com/odoo/design-themes/pull/461

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-08 14:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/68985).

2021-04-13 10:03 UTC, qsm-odoo requested changes
Commit message guidelines:
- max 72 characters per line
- The title should complete the sentence "When applied this commit will...". So something like "review theme kanban descriptions" instead of "improve theme_view_kaban : better themes descriptions"

2021-04-13 10:03 UTC, qsm-odoo commented on addons/website/views/website_views.xml
> +                                    <b><t t-esc="record.display_name.value.replace(('Theme'), '').replace(('theme'), '')"/></b>
Why parenthesis around the strings?

2021-04-19 09:18 UTC, JKE-be commented
@robodoo r+

2021-04-19 10:19 UTC, closed without merging