[IMP] expense: Add smart button on expense connected to his entry.
odoo/odoo pull request #69020
Opened 2021-04-09 08:22 UTC by FlorianGilbert

**Task ID:** #2464735

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-09 08:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69020).

2021-04-28 13:34 UTC, qdp-odoo requested changes
small change

2021-04-28 13:34 UTC, qdp-odoo commented on addons/hr_expense/views/hr_expense_views.xml
> +                        <field name="account_move_id" groups="account.group_account_invoice,account.group_account_readonly" invisible="1"/>
groups + invisible is dumb ^^

2021-08-04 07:42 UTC, smetl approved these changes
@robodoo r+

2021-08-04 09:08 UTC, closed without merging