[IMP] website: use id instead of name to identify industry
odoo/odoo pull request #69047
Opened 2021-04-09 14:18 UTC by smottet

Using industry id instead of industry name make the corresponding record retrieval on the iap side quite faster.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-09 14:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69047).

2021-04-09 14:25 UTC, smottet commented
note for @JKE-be LabelToId is used by blurIndustrySelection. If the user select an industry and then remove a character, on blur we remove the entire text from the input since it is not a valid industry. I don't see how I could get rid of this LabelToId...
Also the select callback from the jquery autocomplete has a strange behavior (https://api.jqueryui.com/autocomplete/#event-select). "The default action is to replace the text field's value with the value of the selected item.". The labels are displayed when you enter text but when you select an item the value (and not the label) is put in the text field.

2021-04-13 07:07 UTC, qsm-odoo requested changes
Max 72 character per line in commit messages please

2021-04-13 12:49 UTC, JKE-be commented on addons/website/models/website.py
>          domain = [('name', '=like', 'theme%'), ('name', 'not in', ['theme_default', 'theme_common'])]
and author ilike Odoo ?
whats do you think about this heuristic

2021-04-14 09:21 UTC, closed without merging