[FIX] webiste_editor: fix impossible to duplicate form field
odoo/odoo pull request #69156
Opened 2021-04-13 09:55 UTC by Guillaume-gdi

Since Odoo 14.3, field duplication in forms does not work correctly anymore.
This bug makes that in the Website editor, when you duplicate a field of a form that had just been created, nothing happens.

**Task #2501647**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-13 09:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69156).

2021-04-14 07:36 UTC, sdegueldre requested changes
The commit message doesn't follow the convention:

```
[TAG] module: short description of the changes

Long description of the changes when needed and/or context for the change

task-<task-id>
```

In this case, the module you are changing is called `web_editor`. The description that you have in the pull request should probably be part of the commit message, and in this case you should probably also add some context as to what causes the bug and why this change fixes it.

As far as reviewing the code itself and whether it's the right fix, I don't know enough about the new odoo editor so maybe @Goaman can take a look since he's the one who helped you with the problem :)

2021-04-15 06:15 UTC, sdegueldre requested changes
@Guillaume-gdi keep line length in commit at 72 characters or fewer.

2021-04-15 07:05 UTC, Goaman commented
Fine by me :+1:

2021-04-16 12:10 UTC, qsm-odoo reviewed
@Goaman Could you explain to me what is this change exactly doing? :) I don't understand it. 

And the commit message really does not help @Guillaume-gdi I think you should review it so that we can understand the fix immediately :wink:  "This historyStep can make historyRollBack and delete the new field" seems to be a strange sentence :grimacing: There should be no need to mention function names in commit messages, you can read the code for that. You are to explain the what and the why, not really the how :wink:

2021-05-03 10:19 UTC, qsm-odoo commented
@Goaman @Guillaume-gdi 17 days :wink:

2021-05-05 13:11 UTC, Goaman commented
> @Goaman Could you explain to me what is this change exactly doing? :) I don't understand it.
> 
> And the commit message really does not help @Guillaume-gdi I think you should review it so that we can understand the fix immediately  "This historyStep can make historyRollBack and delete the new field" seems to be a strange sentence  There should be no need to mention function names in commit messages, you can read the code for that. You are to explain the what and the why, not really the how

For each step, being done in the editor we check the unbreakable rules. This prevent to break some elements upon user edition.
However, the code for website is not prone to the unbreakable rules. To "whitelist" the clone, we have to call the method `unbreakableStepUnactive` before making a step.
I haven't investigated why the `clone` is violating the unbreakable rules but it does not matter as we know that this method can break it anyway.

2021-05-06 12:22 UTC, qsm-odoo commented
@Goaman 

> I haven't investigated why the clone is violating the unbreakable rules but it does not matter as we know that this method can break it anyway.

I am not sure to understand, why does it not matter to understand why a line of code is needed? :thinking: "It does not work without it" is not good explanation for the line IMO... maybe the clone is "violating the unbreakable rules" for a buggy reason in the unbreakable rules code, we can't just ignore that without checking why :|

> However, the code for website is not prone to the unbreakable rules

If that is true (that sounds strange though), why is not the call to `unbreakableStepUnactive` generically made for all website operations? Also, same question for the `historyStep` call at the end of this function in this PR. I don't think there should be any need in specific options (like the form one here) to call something specific to the editor. And if so, it should be something rare which we can explain IMO.

2021-05-17 07:37 UTC, Goaman commented
@qsm-odoo 
> I am not sure to understand, why does it not matter to understand why a line of code is needed? thinking "It does not work without it" is not good explanation for the line IMO... maybe the clone is "violating the unbreakable rules" for a buggy reason in the unbreakable rules code, we can't just ignore that without checking why :|

The unbreakable rules exists for protecting user input edition (when deleting), not command edition like this one (duplication form field).
Knowing why the command is triggering the unbreakable is useless as it has no impediment in the business behaviors even if it trigger the unbreakable rule.

> If that is true (that sounds strange though), why is not the call to unbreakableStepUnactive generically made for all website operations? Also, same question for the historyStep call at the end of this function in this PR. I don't think there should be any need in specific options (like the form one here) to call something specific to the editor. And if so, it should be something rare which we can explain IMO.

`unbreakableStepUnactive` and `historyStep` are called generically when calling an option. But the `remove` and `clone` function are not called generically.

2021-05-25 09:51 UTC, qsm-odoo approved these changes
@robodoo r+

2021-05-25 10:08 UTC, robodoo commented
Unable to stage PR ({"message":"Merge conflict","documentation_url":"https://docs.github.com/rest/reference/repos#merge-a-branch"})

2021-05-26 12:36 UTC, qsm-odoo commented
Bug is not there anymore without this dubious change, so let's forget about this now :shrug:

2021-05-26 12:36 UTC, closed without merging