[IMP] Mail: Move suggestion list code inside a model
odoo/odoo pull request #69280
Opened 2021-04-15 07:46 UTC by phenix-factory

This will reduce composer model complexity and allow to reuse suggestion code
inside other component.

task-2447140

2021-04-15 07:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69280).

2021-04-22 13:27 UTC, seb-odoo requested changes
It's better like this, but there is still an important part of suggestion list that should be moved into it, it is the search itself.

Not the delimiter part, but once the delimiter process has determined a model and search term it should be the list job to take it from there.

2021-04-22 13:27 UTC, seb-odoo commented on addons/mail/static/src/models/suggestion_list/suggestion_list.js
> +            this.update({ hasSuggestions: false });
`hasSuggestions` should stay a compute on the lists having elements.

2021-04-22 13:27 UTC, seb-odoo commented on addons/mail/static/src/models/composer/composer.js
> +            this.suggestionList.closeSuggestions();
Removing the delimiter should clear the suggestion search term which should make the suggestion list empty.
It shouldn't be needed to call any manual "close" on it.

2021-04-22 13:27 UTC, seb-odoo commented on addons/mail/static/src/models/composer/composer.js
> +            this.suggestionList.update({
The whole code of `_updateSuggestionList` should be done inside the suggestion list itself.

The main interaction between composer and suggestion list should be that the composer is updating the search term.

2021-04-23 13:18 UTC, phenix-factory commented
The more I think of it the more I think this PR make no sense. It add complexity and solve 0 problem.
It will never reach the state where, to support suggestions, we just wrap an input in a suggestion_list component and it will work.

2021-04-23 13:52 UTC, seb-odoo commented
> The more I think of it the more I think this PR make no sense. It add complexity and solve 0 problem.
> It will never reach the state where, to support suggestions, we just wrap an input in a suggestion_list component and it will work.

It's probably correct to say this goal will never be reached, and it's fine. I don't think it is adding complexity, it should make the code easier to maintain by correctly splitting concerns. If you don't have this feeling yet, it means the PR is not good enough yet.

2021-10-19 09:23 UTC, closed without merging