[FIX] snailmail_account: send letter to valid partners
odoo/odoo pull request #69633
Opened 2021-04-21 19:09 UTC by sswapnesh

Before this commit, It was sending letters for all Invoices
which might be failed if invoice has no `partner_id` since
`partner_id` is required field on `snailmail.letter`

Now, we are sending letters to Valid Invoices only.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-21 19:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69633).

2021-05-12 16:19 UTC, sswapnesh commented
@william-andre What do you think on this one ?

2021-05-14 14:16 UTC, william-andre reviewed
Don't you want it to fail with a nice message rather than a silent ignore?

Branch is red, probably needs a rebase

2021-05-15 13:22 UTC, sswapnesh commented
> Don't you want it to fail with a nice message rather than a silent ignore?

Should be in master.

2021-05-15 14:54 UTC, william-andre commented
Runbot thinks your branch targets master. It should be detected from the target of the PR but the fact that you branch name doesn't start with the target doesn't help.

Maybe @d-fence can give his input on this?

2021-05-17 06:50 UTC, d-fence commented
@william-andre runbot is able to detect PR target but here the problem is different.
Runbot is confused with other old PR's like #33770.
So I forced the 13.0 as the base on the runbot side.

2021-05-17 08:58 UTC, william-andre commented
> > Don't you want it to fail with a nice message rather than a silent ignore?
> 
> Should be in master.

Why? It will be harder for the user to know why it didn't work if it fails silently.

2021-05-17 15:28 UTC, sswapnesh commented
@william-andre So for that we will need to modify pot files on stable versions.

If you agree, Let's do it in a better way.

2021-05-17 15:37 UTC, william-andre commented
@sswapnesh I don't understand why you would want to change something since it is already handled with the error management of the snailmail module.

What are you trying to achieve with this PR? Is there a traceback or an unwanted behavior?

2021-05-17 15:44 UTC, sswapnesh commented
>  Is there a traceback or an unwanted behavior?

I might be missing something but still, 

1: Select and Try to Send Invoice which do not have `partner_id`.

![Screenshot (41)](https://user-images.githubusercontent.com/16624719/118516967-6edc4f80-b754-11eb-8425-e76ec0bbb02b.png)


This is not helpful, and No user wants to send when there is not  `partner_id` so in this PR Now, we are sending letters to Valid Invoices only.

Am I missing something ?

2021-06-04 17:27 UTC, sswapnesh commented
Ping @william-andre

2021-06-07 09:36 UTC, william-andre requested changes
* You want to filter out partners that don't have a partner. Not the opposite.
* You don't want to fail silently
* In case the partner is set but it has no address (or it is not complete), it is already managed in a cleaner/better way.
![image](https://user-images.githubusercontent.com/44770049/120994027-68099100-c784-11eb-9363-a6486ee5616e.png)
![image](https://user-images.githubusercontent.com/44770049/120994085-735cbc80-c784-11eb-88af-b909a39d9fcd.png)

2021-06-30 16:59 UTC, sswapnesh commented
@william-andre Updated
Am I still missing something ?

2021-07-01 11:37 UTC, william-andre commented
You are still failing silently aren't you?

2023-03-30 09:45 UTC, C3POdoo commented
Dear @sswapnesh,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2023-03-30 09:45 UTC, closed without merging