[FIX] account: display credit notes on portal
odoo/odoo pull request #69693
Opened 2021-04-22 13:41 UTC by kitan191

- Create an invoice for a portal user
- Add a credit note for that invoice
- Connect with portal user
- On Invoices & Bills menu, the correct count is displayed (i.e. 2)
- Open Invoices & Bills page
The "All" filter only displays out_invoice and in_invoice, making impossible to view
the other types (out_refund, in_refund, out_receipt, in_receipt).

opw-2486471

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-22 13:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69693).

2021-04-23 07:26 UTC, william-andre requested changes

2021-04-23 07:26 UTC, william-andre commented on addons/account/controllers/portal.py
> +            'all': {'label': _('All'), 'domain': []},
`('move_type',  '!=',  'entry')`

2021-04-23 07:50 UTC, kitan191 commented on addons/account/controllers/portal.py
> +            'all': {'label': _('All'), 'domain': []},
Thanks for the review.

2021-04-23 11:04 UTC, william-andre requested changes
Sorry

2021-04-23 11:04 UTC, william-andre commented on addons/account/controllers/portal.py
>              'bills': {'label': _('Bills'), 'domain': [('move_type', '=', 'in_invoice')]},
```suggestion
            'all': {'label': _('All'), 'domain': []},
            'invoices': {'label': _('Invoices'), 'domain': [('move_type', 'in', ('out_invoice', 'out_refund')]},
            'bills': {'label': _('Bills'), 'domain': [('move_type', 'in', ('in_invoice', 'in_refund'))]},
```

Sorry for the back and forth

2021-04-23 12:02 UTC, kitan191 commented on addons/account/controllers/portal.py
>              'bills': {'label': _('Bills'), 'domain': [('move_type', '=', 'in_invoice')]},
Done :)

2021-04-23 14:58 UTC, william-andre approved these changes
@robodoo r+
Thanks!

2021-04-23 16:14 UTC, closed without merging