[FIX] web, website: display default company name on frontend layout
odoo/odoo pull request #69943
Opened 2021-04-27 14:36 UTC by younn-o

The "Company name" placeholder was hardcoded in the frontend layout
template, and the user had to change it with his company name from the
website wiew, which was not user-friendly if the website module was not
installed.

By default the frontend layout template displays the user's company
name, and if website module is installed, the frontend layout template
is editable.

task-2468472

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-04-27 14:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/69943).

2021-04-27 14:58 UTC, qsm-odoo requested changes
Commit message type: "website wiew"

2021-04-29 11:25 UTC, bvr-odoo approved these changes

2021-05-11 16:01 UTC, qsm-odoo commented
@younn-o Why did you retarget to master? Someone told you to?

2021-05-11 16:06 UTC, younn-o commented
> @younn-o Why did you retarget to master? Someone told you to?

I retargeted to master as the fix involves changing templates in the db, but it should still be targeting 14.0 for new installations of that version ?

2021-05-21 14:11 UTC, JKE-be commented
@robodoo r+

2021-05-21 15:14 UTC, closed without merging