[FIX] hr_expense: Wrong journal entries
odoo/odoo pull request #70330
Opened 2021-05-04 12:49 UTC by simongoffin

Steps to reproduce the bug:

- Let's consider an expense E paid by the company
- Validate E and post journal entries

Bug:

Two journal entries were created:

1. Outstanding payments (debit) / Account Payable (credit) as draft instead of posted
2. Expense (debit) / Outstanding payments (credit) as posted instead of draft

opw:2510663

2021-05-04 12:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/70330).

2021-05-04 15:45 UTC, william-andre commented
Seems like this broke a few tests.

Not sure about the functional part, I would need to dig deeper, but from ELM's comment
> What I would expect to happen if we want to keep two entries is:
> expense /payable posted
> payable / outstanding draft
> 
> While now the moves are posted like this:
> expense outstanding posted
> payable outstanding draft

So it seems like one of the accounts of the posted entry is wrong. The draft entry is fine. It might be a bad configuration...

2021-05-04 15:46 UTC, william-andre requested changes
Seems like this broke a few tests.

Not sure about the functional part, I would need to dig deeper, but from ELM's comment
> What I would expect to happen if we want to keep two entries is:
> expense /payable posted
> payable / outstanding draft
> 
> While now the moves are posted like this:
> expense outstanding posted
> payable outstanding draft

So it seems like one of the accounts of the posted entry is wrong. The draft entry is fine. It might be a bad configuration...

2021-05-06 08:07 UTC, simongoffin commented
@william-andre 

I discussed with @tsb-odoo and the two generated entries must be in draft.
Now the created entries are as followed:
expense (debit) / payable (credit) as draft
payable (debit) / outstanding (credit) as draft

2021-05-31 08:12 UTC, william-andre reviewed
Line 404 is not useless

If that's what is needed functionally, ok. But you still need to change the tests then.

2021-06-02 13:16 UTC, william-andre approved these changes
@robodoo r+

2021-06-02 14:40 UTC, closed without merging

2021-06-28 22:58 UTC, Espzai commented
@simongoffin @william-andre, 
In my humble opinion this commit is wrong and has left this module useless.
Considering only hr_expense module without any other dependent module, that might change it's behavior, it never created double entries as mentioned as a bug. My clients were using it flawlessly.

The created entries were quite right as:
- company_account
expense (debit)/ bank account from bank journal (credit)
The expense report is marked paid. Accounting and management wise correct.

- own_account
expense (debit)/ Employee Payable Account (credit)
Now to close the sheet you need to pay the employee and an entry is created
Employee Payable Account (debit)/ bank or cash (credit)
Again this is correct.

After this commit what happens, in any case either company_account or own_account the same entry is created:
expense (debit) / Employee Payable (credit)
In company_account case the sheet is marked as "PAID" with a wrong draft entry as it needs to be paid again with regular payment.

If you see the code you removed was finding the destination account for both (company and own account). Now it only gets one account.

The option paid by company in this module is now useless and will create issues as leaving draft entries behind to be paid and reconciled later with payments.

Please review this commit as now we have to create a customization to fix it's behavior.

Regards.

2021-06-29 20:00 UTC, Espzai commented
@simongoffin  @william-andre
Further more to my previous comment. I did run the following instance which is before your commit: 
https://8049329-14-0-all.runbot44.odoo.com
- Installed Apps as I mentioned we are only talking about hr_expense module and I am not aware of any other modules that might change it's behavior to create two entries.
![Screenshot from 2021-06-29 20-09-50](https://user-images.githubusercontent.com/34160546/123857743-01126e80-d923-11eb-8d4f-b2216afca14a.png)

- Approved expense paid by company
![Screenshot from 2021-06-29 19-31-22](https://user-images.githubusercontent.com/34160546/123857928-37e88480-d923-11eb-9a84-a980f5e18185.png)

- Here is the created journal entry, posted and quite correct. It requires no intervention from accountants:
![Screenshot from 2021-06-29 20-09-26](https://user-images.githubusercontent.com/34160546/123857990-4898fa80-d923-11eb-91b8-61be4ca1cf10.png)

- I can't see the second entry in all journal entries:
![Screenshot from 2021-06-29 20-11-05](https://user-images.githubusercontent.com/34160546/123858252-957cd100-d923-11eb-8a83-70212e54b201.png)

**Now what happens after your commit**
https://8053613-14-0-all.runbot52.odoo.com

- Expense is paid by a "Draft Entry"
![Screenshot from 2021-06-29 20-52-42](https://user-images.githubusercontent.com/34160546/123858360-b47b6300-d923-11eb-926e-6e0bff693632.png)

- a draft entry that requires Account intervention and that is even wrong as now the accountant has to create a payment or some other means to pay to the employee. If it is going this way then why you are keeping the option "Paid by Company"
![Screenshot from 2021-06-29 20-52-50](https://user-images.githubusercontent.com/34160546/123858647-0f14bf00-d924-11eb-8d14-85e2624d32ef.png)

Some times, I don't understand the logic behind your changes but this is going to create confusions.
Could any body please explain this logic to me? @mart-e

2021-06-30 15:59 UTC, dreispt commented
@simongoffin This is not a fix, but a change in behavior, and users are complaining.
Now when you hit the Expense Report "POST" button, the Journal Entries are *not* posted. 😢 

Can we get an explanation on the reason for this change?
Is it somehow related to the previous fix https://github.com/odoo/odoo/pull/69875, supervised by @tivisse ?

2021-06-30 17:21 UTC, dreispt commented
Note that the Accounts are wrong - when paid "By Company", it should move a Payments Account and not a an AP account.

2021-07-13 14:46 UTC, tsb-odoo commented
@simongoffin Can you please revert this fix and check the behaviour should be the following. 

Expected behaviour : In the case of an Expense paid by the company, 
- One single entry
- Pressing "Post Entries" from App Expense really posts entries (not in draft anymore)
- Expense (Debit) / Outstanding Payments (Credit)
- Journal selected is a Bank Journal. (already the case now)

cc : @william-andre

2021-07-14 08:50 UTC, simongoffin commented
https://github.com/odoo/odoo/pull/73677