[FIX] web: setting avoid miss visual alignment on mobile
odoo/odoo pull request #70336
Opened 2021-05-04 13:36 UTC by rfr-odoo

In the settings view, on mobile the save and the discard button are
wrapped in a dropdown.

As the save button is primary and the discard is secondary when there
are wrapped in the dropdown there are miss aligned as there padding are
not the same.

This commit, avoid to change the padding on mobile of these elements.

Steps to reproduce:
* Open Odoo (on Mobile)
* Go in Settings
* Open the dropdown => BUG

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-05-04 13:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/70336).

2021-05-17 08:06 UTC, adr-odoo requested changes
Feel free to remove this rule and for me "Save" and "Discard" buttons shouldn't be in "o_statusbar_buttons"...

2021-06-24 10:53 UTC, pparidans commented
> Feel free to remove this rule and for me "Save" and "Discard" buttons shouldn't be in "o_statusbar_buttons"...

I second that. Also note that since the merge of wowl/redesign this seems less like an issue on master. Maybe fix it only in stable versions?

2022-07-13 10:39 UTC, rfr-odoo commented
Not applicable anymore

2022-07-13 10:39 UTC, closed without merging