[IMP] web: grey out avatar of archived users/employees
odoo/odoo pull request #70332
Opened 2021-05-04 13:06 UTC by hap-odoo

The purpose of this commit is to let users know when
another user or employee has been archived.
This is done by differentiates the archived user or employee
by greying out the avatar of it.

TaskID-2514400

2021-05-04 13:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/70332).

2021-05-21 07:14 UTC, JKE-be commented on odoo/tools/image.py
> +    image = ImageProcess(base64_source, user_active, verify_resolution)
`ImageOps.grayscale(image)`  should probably be done here, it is not linked to the `base64_to_image` function.
And param name be something related to grayScale and not user... Here your are in tools...

`image_base64 = image_process(image_base64, size=(int(width), int(height)), crop=crop, quality=int(quality), grayscale=not user_active)` for example

2021-05-21 07:41 UTC, mart-e commented
Hi,
Can't we make this purely in CSS on the image widget? How about if I archive and unarchive a user?

2021-05-25 05:58 UTC, msh-odoo commented
> Hi,
> Can't we make this purely in CSS on the image widget? https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/grayscale()
> Isn't that redundant with the ribbon widget?

The reason for doing code in controller instead of css is to save rpc calls, if we do it in css we need to add class to make image grey based on Archived/Unarchived value, we need to check first whether model has active field if yes then whether it's value is true/false, also if we do this code in avatar widget then we need to think about listview as avatar widget can be in listview where we may have hundreds of records, so we needed to handle reading of active field value wihtout doing extra rpc so we thought why not make imag grey when image controller is called.

2021-05-25 10:16 UTC, mart-e commented
You don't necessarily need another rpc, it's just reading the field `active` if present, the same way we are already doing for web_ribbon widget. This should be generic, don't hardcode the models in `web` module, one use could want to display archived products in grey for instance.

2021-05-25 10:46 UTC, seb-odoo commented
Hello, I think this task should be delayed and done after https://www.odoo.com/web#active_id=2404630&cids=1&id=2404630&model=project.task
This other task will introduce a new field specific for user avatar, where it will be easier to return a greyed version of it without having to further hack the current image route.

2021-05-25 10:56 UTC, seb-odoo requested changes

2021-05-25 10:56 UTC, seb-odoo commented on odoo/tools/image.py
> +    def __init__(self, base64_source, grayscale=False, verify_resolution=True):
grayscale should be an operation that you call in the chain, not a param of the constructor

2021-05-25 10:56 UTC, seb-odoo commented on odoo/tools/image.py
> +def base64_to_image(base64_source, grayscale=False):
This should be in the processing, not in the converter.

2021-05-26 08:03 UTC, msh-odoo commented
> You don't necessarily need another rpc, it's just reading the field `active` if present, the same way we are already doing for web_ribbon widget. This should be generic, don't hardcode the models in `web` module, one use could want to display archived products in grey for instance.

@mart-e The proble here is we do not want to read active field of current model, we want to check comodel record's active field, we want to check if comodel's record is archived then we want to make image field gray, the task is to make Many2oneAvatar widget with gray image if many2one record is archived.

2024-04-16 11:32 UTC, C3POdoo commented
Dear @hap-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 11:32 UTC, closed without merging