[IMP] website: disable already installed modules in configurator
odoo/odoo pull request #70413
Opened 2021-05-05 13:33 UTC by smottet

The selection of cards corresponding to already
installed modules is disabled. A disabled style
has been applied to these cards and an info icon
added. On hover on this icon the user is informed
that the module is already installed on its DB.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-05-05 13:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/70413).

2021-05-07 09:38 UTC, JKE-be requested changes
no new field in stable version !!!

2021-05-26 13:33 UTC, qsm-odoo requested changes
Details to change then I'll test and merge :+1: 

![image](https://user-images.githubusercontent.com/10338094/119667946-04ec3600-be37-11eb-88d6-89d1d64df263.png)

- Too much characters in the title
- Too few characters in the description
- Missing mention to the task (task-XXX)

2021-06-01 13:36 UTC, qsm-odoo requested changes
Commit message convention: `task-XXX` not `Task Id: XXX` (same comment for all future PR review).

At the same time, change "[IMP]" into "[FIX]"

2021-06-01 13:36 UTC, qsm-odoo commented on addons/website/data/website_data.xml
> +        <field name="description">Publish job offers and let people apply</field>
When you change or add a new term in stable version, you have to update the .pot file for the translation (https://github.com/odoo/odoo/wiki/Translations#adding-new-terms-when-suggesting-fixes-in-stable-versions). Technically, we don't even even fix typo in stable version but ... 14.3 we should indeed.

Strange I did not see that in my first review... sorry :/

2021-06-01 13:36 UTC, qsm-odoo commented on addons/website/static/src/components/configurator/configurator.xml
> +                                            <i t-attf-class="o_configurator_feature_status fa fa-info-circle text-muted" title="Already installed"/>
Actually, it is probably the same with this new term, can you check?

2021-06-24 08:15 UTC, JKE-be commented
@robodoo r+

2021-06-24 10:01 UTC, closed without merging