[IMP] im_livechat: unpin livechat channel after one day
odoo/odoo pull request #70474
Opened 2021-05-06 11:50 UTC by pka-odoo

PURPOSE:

livechat channel doesn't unpinned after one day automatically,
even if operator have seen that channel or not. it can be
case where operator is out of office for long and didn't check
the messages

SPECIFICATION:

livechat channel should be unpinned after one day of operator seen
that channel.

task-2446972

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-05-06 11:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/70474).

2022-04-29 16:22 UTC, seb-odoo requested changes
Thank you for the PR. Quick check below

2022-04-29 16:22 UTC, seb-odoo commented on addons/im_livechat/models/mail_channel_partner.py
> +                    cp.last_seen_date < current_timestamp - interval '1 day'
Also please take into account that the spec has been updated to only unpin after a day but also only if there are no unread messages for this channel partner.

2022-04-29 16:23 UTC, seb-odoo commented on addons/im_livechat/models/mail_channel_partner.py
> +    last_seen_date = fields.Datetime("Last seen date")
Would probably call it `last_seen_dt` instead (it's a datetime, not just a date),  similar naming than `last_interest_dt`

2024-04-16 11:36 UTC, C3POdoo commented
Dear @pka-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 11:36 UTC, closed without merging