[IMP] fleet, l10_be_hr_payroll_fleet: improve UX of manufacturer mode…
odoo/odoo pull request #70605
Opened 2021-05-10 13:15 UTC by kro-odoo

…l and kanban list

Currently, when adding some new manufacturer models, we don't know the
tax deduction and the CO2 fees. Also the UX of the kanban list view and
manufacturer model needs to be improved.

By this commit, in Manufacturer > Model for vehicle type;
	-Car: Tax Deduction and Co2 fees are added
	-Bike: Tax Deduction and Electric Assistance are added
In the kanban list view of Manufacturer, the counts of bikes and cars of
each particular manufacturer is added in the kanban card.

TaskID: 2439798

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-05-17 06:54 UTC, kba-odoo requested changes
I've left 2 minor comments, LGTM :+1:

2021-05-17 06:54 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle_model.py
> +            brand.car_count = car_dict.get(brand.id, 0)
As you have defined a defaultdict, you don't need to call `get()`

2021-05-17 06:54 UTC, kba-odoo commented on addons/fleet/models/fleet_vehicle_model.py
> +        datas = self.env['fleet.vehicle.model'].read_group(
Could you rename `datas` into something else? It's not a proper English word :sweat_smile:

2024-04-16 11:32 UTC, C3POdoo commented
Dear @kro-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 11:32 UTC, closed without merging