[FIX] tools: with Python >= 3.8 passlib >= 1.7.2 is required
odoo/odoo pull request #71013
Opened 2021-05-19 07:56 UTC by remybar

From Python 3.8, the `time.clock()` function has been definitively removed, leading to the following `passlib` issue:
`ImportError: cannot import name 'clock' from 'time' (unknown location)`.

This point has been fixed in `passlib` `1.7.2`.

Due to https://github.com/odoo/odoo/pull/51784, this passlib version update, is only done from Odoo 13.0.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-05-19 07:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/71013).

2021-05-19 10:00 UTC, remybar commented
> @remybar can you give more information on how to reproduce the problem.
> A few weeks ago, 13.0 was built on runbot using python3.8 and it was green: seen the full log [here](http://runbot41.odoo.com/runbot/static/build/7372053-13-0/logs/all_at_install.txt)

In fact, I've not reproduced this issue, I've just seen this error from a customer using Python 3.9 (here: https://www.odoo.com/web#id=2503194&action=333&active_id=70&model=project.task&view_type=form&cids=1&menu_id=4720), and after some research I've found that `time.clock()` has been removed from Python 3.8 (for example, here: https://foss.heptapod.net/python-libs/passlib/-/issues/111)

But, I can try to reproduce it if needed.

2021-05-19 12:26 UTC, remybar commented
> @remybar can you give more information on how to reproduce the problem.

So, after some retries, I was not able to reproduce this issue ... because the issue is on Windows only ... (thanks @KangOl, see here: https://foss.heptapod.net/python-libs/passlib/-/blob/1.7.1/passlib/utils/__init__.py#L843-848)

But, on Linux, if you run Python 3.8 and execute `from time import clock as timer` you will get the error.

So, IMHO, it would be better to update the passlib version.

2021-05-19 13:49 UTC, d-fence requested changes

2021-05-19 15:37 UTC, remybar commented on requirements.txt
> +passlib==1.7.2
ok, thanks :+1:

2021-05-20 05:48 UTC, d-fence commented
Sorry to bother you but the commit message header should be change to something like `[FIX] requirements: ...` in order to avoid confusion with the [tools](https://github.com/odoo/odoo/tree/13.0/odoo/tools) module

2021-05-20 05:51 UTC, remybar commented
> Sorry to bother you but the commit message header should be change to something like `[FIX] requirements: ...` in order to avoid confusion with the [tools](https://github.com/odoo/odoo/tree/13.0/odoo/tools) module

no problem, I'm not used to do this kind of modifications so I'm not really aware of the kind of tags we put for these cases ;-)

2022-02-22 07:56 UTC, remybar commented
What do I do with this PR ? Do you plan to merge it or do I close it ? :thinking:

2022-03-28 09:10 UTC, closed without merging