[IMP] project: improve the UX of the app
odoo/odoo pull request #71232
Opened 2021-05-25 15:40 UTC by cedricpri

Generic UX improvements for the project app.
More details soon.

task-2501760

2021-05-25 15:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/71232).

2021-06-23 16:41 UTC, SimonGenin requested changes

2021-06-23 16:41 UTC, SimonGenin commented on addons/web/static/src/legacy/js/views/calendar/calendar_popover.js
> +
All the changes in this file are unnecessary diffs.

2021-06-23 16:41 UTC, SimonGenin commented on addons/web/static/src/legacy/xml/kanban.xml
> +                            <a role="menuitem" href="#" class="dropdown-item o_column_unarchive_records">Unarchive All Tasks</a>
Are you sure it's what you want to do ? You change the xml of the kanban view globally here, meaning that your change will impact all the kaban views in any modules.
If you want to only do it in your module, you'll need to overwrite this template instead :)

2021-07-09 10:22 UTC, xavierbol requested changes
Thanks for your work ! 🙂 
I have made some comments.

2021-07-12 06:33 UTC, cedricpri commented on addons/hr_timesheet/views/project_views.xml
> +    </record>
Sorry, I didn't see that but it seems that another commit actually introduced the same feature while I was working on them, and a rebase then duplicated the view. I removed this.

2021-07-14 09:53 UTC, xavierbol approved these changes
LGTM ! Thanks for the changes. 🙂

2021-07-22 13:32 UTC, IT-Ideas reviewed
Thanks for your work 🙂 
Just some little things

2021-07-23 12:35 UTC, IT-Ideas approved these changes
LGTM Thanks

2021-07-23 12:36 UTC, IT-Ideas commented
@robodoo r+

2021-07-23 15:06 UTC, closed without merging