[IMP] mail: activity keyboard navigation improvement
odoo/odoo pull request #71501
Opened 2021-05-31 13:37 UTC by ibo-odoo

**PURPOSE**

Improve some mail activity issues regarding keyboard navigation through forms.

**SPCIFICATION**

- When creating an activity using the form view, allowing user for the form and
  given access for TAB key to the four buttons at the footer.
- When done an activity using the record list view, allowing user ENTER key
  support on "Done" or "Done and Schedule Next" button to post feedback and
  mark the activity as done.

**Task**-2528109

2021-05-31 13:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/71501).

2021-06-02 17:14 UTC, seb-odoo requested changes
Thank you for the PR, it looks like it is working, but it is a bit too much a copy of the old obsolete code.
I know it's not easy because this is still in old code, but see below for some changes that could already be improved.

Also it would be important to add tests because this is likely to be broken soon, either by the web client refactoring or actually converting this widget itself to new code.

2021-06-02 17:14 UTC, seb-odoo commented on addons/mail/static/src/js/core/dialog.js
> +                }
This is a bit confusing to compare names, but I guess ok as part of the old widget.

2021-06-04 14:51 UTC, seb-odoo commented on addons/mail/static/tests/chatter_tests.js
> +QUnit.test('list activity widget: done the acitivty with "ENTER" keyboard shortcut', async function (assert) {
Please move these tests into another file (a new one if necessary), as this file was supposed to be for chatter not for all of activity.
In this case if the whole list view is necessary for the test, it should be a test file in `widgets/list_view/` subfolder.

(Ideally this file should be deleted and the rest also split in new files as we have another file for chatter now, but don't do that in this PR.)

2021-06-04 14:51 UTC, seb-odoo commented on addons/mail/static/tests/chatter_tests.js
> +    );
Only one activity should be enough for the test

2021-06-04 14:51 UTC, seb-odoo commented on addons/mail/static/tests/chatter_tests.js
> +            }
This is out of scope of testing the keyboard shortcut

2021-06-04 14:51 UTC, seb-odoo commented on addons/mail/static/tests/chatter_tests.js
> +    ]);
just make an assert step for the activity route and not the rest

2021-06-04 14:51 UTC, seb-odoo commented on addons/mail/static/tests/chatter_tests.js
> +});
All the same remarks as first test, try to keep it as short as possible and to the point (only asserting that the keyboard shortcut works and nothing else).

2021-06-07 13:10 UTC, ibo-odoo commented
@seb-odoo changes are done.! Thanks.

2021-06-07 15:16 UTC, seb-odoo commented on addons/mail/static/src/widgets/list_view/list_view_tests.js
> +        mockRPC: function (route, args) {
same

2021-06-07 15:16 UTC, seb-odoo commented on addons/mail/static/src/widgets/list_view/list_view_tests.js
> +    await testUtils.dom.click(list.$('.o_data_cell:first'));
I think this click is unnecessary?

2021-06-07 15:16 UTC, seb-odoo commented on addons/mail/static/src/widgets/list_view/list_view_tests.js
> +
no need for new line between action and related assertion

2021-06-07 15:16 UTC, seb-odoo commented on addons/mail/static/src/widgets/list_view/list_view_tests.js
> +
no new line

2021-06-07 15:16 UTC, seb-odoo commented on addons/mail/static/src/widgets/list_view/list_view_tests.js
> +    await testUtils.dom.click(list.$('.o_data_cell:first'));
unnecessary click?

2021-06-08 05:20 UTC, ibo-odoo commented on addons/mail/static/src/js/activity.js
> +                ev.preventDefault();
To prevent this kind of default behaviour (https://drive.google.com/file/d/15AETKHqBPTqx4I5-Uuc3lxrD6-sHlrUK/view?usp=sharing)

2021-06-08 09:19 UTC, ibo-odoo commented
Hello. @seb-odoo Changes are done.! Thanks.

2022-01-17 08:40 UTC, closed without merging