[IMP] base, mail, sms, calendar_sms: add accounting firm to company data and xml exports
odoo/odoo pull request #71559
Opened 2021-06-01 13:55 UTC by epictete

A company may grant a mandate to an accounting firm or an agent
to file its tax return or financial reports.

The goal is to add a tab in the company data
to store the agent's address and VAT number.

While exporting the XML Tax Report, a modal opens up
to ask who is submitting the tax report : the company or its agent.

Task 2526717

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-06-01 13:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/71559).

2021-06-21 10:02 UTC, oco-odoo requested changes
I'm okay with the diff, just a note about the commit messages:

- The first one needs more explanation on why you are doing this. Add a few sentences to explain. Also, the title should be more explicit. The commit itself is not about accounting firms; it is needed by them, it's not the same. So the title should be about accounting firms.

- the second one is rather an IMP than a FIX: you're making something better by changing a label, not making something work again after it got broken

2021-08-17 15:01 UTC, william-andre approved these changes
@robodoo r/

2021-08-17 15:01 UTC, william-andre commented
@robodoo r+

2021-08-17 15:02 UTC, william-andre commented
@robodoo rebase-ff

2021-08-17 15:03 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-08-17 15:10 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#18295, odoo/upgrade#2605 not ready. Linked PRs are not staged until all of them are ready.

2021-08-17 16:10 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#2605 not ready. Linked PRs are not staged until all of them are ready.

2021-08-17 17:38 UTC, closed without merging