[FIX] payment: Change the client_handling_limit_date
odoo/odoo pull request #72042
Opened 2021-06-11 11:07 UTC by chevalierv

Currently, the cron post processes all transactions except those processed in the last minute. Now, It should not post process those made within the last 10 minutes.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-06-11 11:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/72042).

2021-06-18 08:07 UTC, AntoineVDV requested changes
Hello, some changes need to be made to your commit title & message:

> [FIX] payment: Change the client_handling_limit_date 

Usually, we avoid referring to a technical name in the commit message, unless it's the name of the main subject of the commit. Here, you mention a mere variable that could really be named as we want; it doesn't tell what this commit is really about.

> Currently, the cron post processes all transactions except those processed in the last minute. Now, It should not post process those made within the last 10 minutes.

The way you write this, it sounds like you arbitrarily decided to change the threshold from 1 to 10 minutes without any justification. Also, you describe the *what* of the change whereas the commit's body should explain the *why*. The *what* is easily understood by reading the diff most of the time.

A good idea for this commit message would be to mention the hash (8 char) of the commit that had it wrong and state that you revert the related change to the behavior in place prior to that commit. Take also the chance to explain *why* you had to make it 10 min again, as it's really not that obvious.

2021-06-22 15:24 UTC, chevalierv commented
@AntoineVDV I tried to rework my commit message. Can you check it again? As you can see, I didn't include the commit that had it wrong because it was a large commit that was not focused on the change I made (See https://github.com/odoo/odoo/commit/573ed74c121c1572b3fab6f9553ed7f93f7b3f99)

2021-06-24 12:42 UTC, AntoineVDV commented
> @AntoineVDV I tried to rework my commit message. Can you check it again? As you can see, I didn't include the commit that had it wrong because it was a large commit that was not focused on the change I made (See [573ed74](https://github.com/odoo/odoo/commit/573ed74c121c1572b3fab6f9553ed7f93f7b3f99))

That commit is still responsible of that change. It could be useful for example to checkout its parent commit to compare the behavior before and after it was merged.

2021-06-24 12:55 UTC, AntoineVDV approved these changes
I believe that you can see what needed to be changed so I force-pushed your branch with a new commit message that complies with the comments above ;)

2021-06-24 12:56 UTC, AntoineVDV commented
@robodoo r+

2021-06-24 15:19 UTC, closed without merging