[FIX] web_tour: use .concat to avoid max call stack error
odoo/odoo pull request #72132
Opened 2021-06-14 12:50 UTC by yelizariev

Variable `mutations` may have thousands of records. Using `.push(...mutations)`
would lead to error

STEPS:
* install website_sale
* create many categories:

```
for x in range(0, 4000):
    env['product.public.category'].create({'name': str(x), 'parent_id': 9})
```
* open /shop
* click [Edit]

BEFORE:

```
Uncaught RangeError: Maximum call stack size exceeded
http://devel.14.localhost:14069/web_tour/static/src/js/tour_service.js:136
```

https://github.com/odoo/odoo/blob/87a75c41a5721115c562aadca1512d1bfaa47939/addons/web_tour/static/src/js/tour_service.js#L136

AFTER: no errors

---

opw-2515707

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-06-14 12:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/72132).

2021-06-14 13:52 UTC, rdeodoo commented
Linked to https://github.com/odoo/odoo/issues/71197#issuecomment-855788162

2021-06-15 07:41 UTC, qsm-odoo requested changes
Thanks for this fix.

Commit message:
- Can you remove the link to your localhost instance?
- I don't get the point of adding a link which redirects to the line of code being modified by the commit. Can you remove that too?
- "AFTER: no errors" seems like an useless info... if you said "AFTER: still errors", it would not be a good commit :smile: 

TBH just the first part of the message is useful to me:
```
Variable `mutations` may have thousands of records. Using `.push(...mutations)`
would lead to maximum call stack size error.
```
That would be enough to understand the error and its fix... but matter of taste I guess. Can you at least remove the useless links? Thanks :+1:

2021-06-15 08:16 UTC, yelizariev commented
@qsm-odoo I'd prefer to keep reproducing steps and error message in commit description. I agree with you on the rest comments. Fixed

2021-06-15 08:29 UTC, qsm-odoo approved these changes
@robodoo r+

2021-06-15 09:51 UTC, closed without merging