[FIX] base_vat: properly checks XI VAT numbers
odoo/odoo pull request #72910
Opened 2021-06-29 10:17 UTC by SwagSamaSempai

In 12.0+ when adding an XI (Northern Ireland) VAT number on a vendor and specifying the country as United Kingdom, an error shows the VAT number as not valid. This is because the method to check specifically XI VAT numbers doesn't recognize XI as a country, and thus uses the GB VAT number verification, which doesn't recognize XI VAT numbers as it isn't up to date yet.

A method to check specifically XI VAT number was already added, but is never called because XI is not recognized as a country.
With this commit, we act as if XI were a country so the temporary method check_vat_xi can be called properly.
This commit is also temporary and the change should be reverted as soon as stdnum is updated.

opw-2534541

2021-06-29 10:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/72910).

2021-06-29 12:24 UTC, nle-odoo approved these changes
ok, but we already have a fallback when we can't guess the country, it would be better to do validation there, copying what was done for the new `check_vat_xi`:

```diff
diff --git a/addons/base_vat/models/res_partner.py b/addons/base_vat/models/res_partner.py
index 6cab0a057ff..3b72e1885ae 100644
--- a/addons/base_vat/models/res_partner.py
+++ b/addons/base_vat/models/res_partner.py
@@ -371,6 +371,16 @@ class ResPartner(models.Model):
     def check_vat_co(self, vat):
         return stdnum.util.get_cc_module('co', 'vat').is_valid(vat) if stdnum else True
 
+    def check_vat_gb(self, vat):
+        """ Temporary Nothern Ireland VAT validation following Brexit
+        As of January 1st 2021, companies in Northern Ireland have a
+        new VAT number starting with XI
+        TODO: remove when stdnum is updated to 1.16 in supported distro"""
+        vat_country_code, vat_number = self._split_vat(partner.vat)
+        if country_code == 'xi':
+            vat = vat_number
+        return stdnum.util.get_cc_module('gb', 'vat').is_valid(vat) if stdnum else True
+
     def check_vat_nl(self, vat):
         """
         Temporary Netherlands VAT validation to support the new format introduced in January 2020,
```

2021-06-29 12:37 UTC, SwagSamaSempai commented
I thought about that but then the behavior when using GB VAT numbers would be modified, even though it is working properly without the fix.

2021-06-29 12:53 UTC, nle-odoo commented
when we do gb vat number, we do:

```py
return stdnum.l.get_cc_module('gb', 'vat').is_valid(vat)
```

so it should be the same thing

2021-06-29 13:15 UTC, SwagSamaSempai commented
Ok then, but there is no need to duplicate the method as it was never called before without the fix, just renaming it is enough.

2021-06-29 14:48 UTC, nle-odoo commented
```py
stdnum.util.get_cc_module('gb', 'vat').is_valid('XI123456782')
```

returns false, the needed part of the code is:

```diff
+        vat_country_code, vat_number = self._split_vat(partner.vat)
+        if country_code == 'xi':
+            vat = vat_number
```

so we do instead:

```py
stdnum.util.get_cc_module('gb', 'vat').is_valid('123456782')
```

> Ok then, but there is no need to duplicate the method as it was never called before without the fix, just renaming it is enough.

but all tickets seems to accept that it was fixed, so my understanding was that there was still a way that this method was called, do you have an idea about that @agr-odoo ?

2021-07-01 10:31 UTC, agr-odoo commented
`check_vat_xi` was to be called when having a vat starting with *XI* before https://github.com/odoo/odoo/commit/5d7f0c3d4e7231aa5cf54baa678354cbcf821153

Now the flow is different
https://github.com/odoo/odoo/blob/a2463b213e7f19b4a089707b226f9a52b4a52b7a/addons/base_vat/models/res_partner.py#L153
XI is not in `res.country` so it will use the partner country code (gb) instead of the one taken from the vat
https://github.com/odoo/odoo/blob/a2463b213e7f19b4a089707b226f9a52b4a52b7a/addons/base_vat/models/res_partner.py#L160

But still if the version of stdnum is updated to at least 1.16 it should work with the standard *check_vat_gb*
https://github.com/arthurdejong/python-stdnum/commit/b93d69581f35aa18e7fdd52b3f7fdf06770215e3

Possible fixes are:
1) Add a new `res.country` 'Northern Ireland' with its own country code, you could just tell the customer to add this record manually and everything would be working fine
2) We could re-add the check using the country guessed from the vat number itself

Something like 
```diff
diff --git a/addons/base_vat/models/res_partner.py b/addons/base_vat/models/res_partner.py
index caffff7861e..e790dbef201 100644
--- a/addons/base_vat/models/res_partner.py
+++ b/addons/base_vat/models/res_partner.py
@@ -159,6 +159,10 @@ class ResPartner(models.Model):
             if (not vat_guessed_country or failed_check) and partner_country_code:
                 failed_check = not check_func(partner_country_code.lower(), partner.vat)

+            #if fails, check with country code from country
+            if (not vat_guessed_country or failed_check) and vat_country_code:
+                failed_check = not check_func(vat_country_code.lower(), vat_number)
+
             # We allow any number if it doesn't start with a country code and the partner has no country.
             # This is necessary to support an ORM limitation: setting vat and country_id together on a company
             # triggers two distinct write on res.partner, one for each field, both triggering this constraint.

```

Maybe @oco-odoo could provide more insight on how to fix this situation 

*Last note: the vat provided in the ticket is invalid and will fail the checksum anyway*

2021-07-21 13:09 UTC, oco-odoo commented
@agr-odoo I think fix option 2 could do the job, but it'd mean we'd sometimes call VIES when we actually don't need it (when the two first characters are not a legit code). 

I suggest instead we change this https://github.com/odoo/odoo/commit/5d7f0c3d4e7231aa5cf54baa678354cbcf821153#diff-1ef5fe83935572c9b9b9e6eec69a44551023f3b92fe38bed4f765a24e16694b4R153 : in addition to the search (with an 'or' condition), we just check if vat_country_code is in a constant set containing the legit codes that are not country codes in Odoo, such as XI. Wouldn't it work ?

2021-07-23 09:00 UTC, SwagSamaSempai commented
@agr-odoo @nle-odoo 
I implemented the solution @oco-odoo suggested, mostly because it seemed the most generic to me, since we can replicate this if needed for any country by simply adding a country code to the dictionary. It seems cleaner to me than directly calling the method from the VAT number itself, in particular because it allows for a custom error message (in the case where the country isn't set). What do you think?

2021-07-26 09:42 UTC, nle-odoo approved these changes
ok for me, but if it works I would prefer to have:

```diff
+ _equivalent_country = {
+    'xi': 'gb',
+ }

...
            vat_country_code, vat_number = self._split_vat(partner.vat)
+           vat_country_code = _equivalent_country.get(vat_country_code, vat_country_code)
            vat_guessed_country = self.env['res.country'].search([('code', '=', vat_country_code.upper())])
```

and in master `def check_vat_xi` could be removed

2021-07-27 08:07 UTC, SwagSamaSempai commented
Your first option wouldn't work because the check for GB doesn't include XI yet, `stdnum` would have to be updated. That also means we need to keep `check_vat_xi`.
I implemented the second option which works fine.

2021-07-27 13:06 UTC, nle-odoo commented
ok, thanks, I tought it would since in this case if you have `XI123456782` you would do:

```py
failed_check = not check_func('gb', '123456782')
``

so I thought there was no xi anywhere.

2021-07-28 11:16 UTC, nle-odoo reviewed
@oco-odoo are you ok with current implementation?

2021-08-16 09:19 UTC, oco-odoo requested changes
Sorry for the delay, I was on holiday. 

Small things, then you can merge :)

2021-08-16 09:19 UTC, oco-odoo commented on addons/base_vat/models/res_partner.py
>              vat_guessed_country = self.env['res.country'].search([('code', '=', vat_country_code.upper())])
Keeping the same name for this variable makes its use confusing.
Rename it something like vat_has_legit_country_code

2021-08-16 09:19 UTC, oco-odoo commented on addons/base_vat/models/res_partner.py
> +]
Rather use a set, just in case we add other specific codes like that in the future.

2021-08-16 09:19 UTC, oco-odoo commented on addons/base_vat/models/res_partner.py
> +_known_country_codes = [
Name is unclear. _region_specific_vat_codes ?

2021-08-17 09:58 UTC, nle-odoo approved these changes
thanks for the change @SwagSamaSempai and the last review oco :)

robodoo r+

2021-08-17 11:06 UTC, closed without merging