[IMP] account: Reconciliation Models usability imp
odoo/odoo pull request #73043
Opened 2021-07-01 06:17 UTC by jbw-odoo

This task aims to both explain supported reconciliation cases and
improve the reconciliation model form view.
The form improvement is mainly about label wording and
make the options more self speaking.

Task : 2427089

Ent PR : https://github.com/odoo/enterprise/pull/19395

2021-07-01 06:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73043).

2021-08-04 07:40 UTC, smetl requested changes

2021-08-09 07:04 UTC, jbw-odoo commented on addons/account/models/account_reconcile_model.py
> +                balance = initial_residual_balance * (line.amount / 100.0)
No, residual_balance is decremented in the loop so != initial_residual_balance

2021-08-09 07:55 UTC, jbw-odoo commented on addons/account/models/account_reconcile_model.py
> +                    'currency_id': False,
I copied the existing writeoff_line dict. Witch is fine, (working in default company currency). Witch make this erroneous :
`currency = st_line.currency_id or st_line.journal_id.currency_id or self.company_id.currency_id`
should be
`currency = self.company_id.currency_id`
Correct ?

2021-08-30 12:53 UTC, oco-odoo requested changes

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +    def _create_rule(cls, **kwargs):
_create_reconcile_model would be more consistent with the model's name

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +            **kwargs,
:+1: :1st_place_medal:

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        # The payment amount is higher than the invoice one.
Maybe we should check the case where the payment amount is lower here as well, for completeness ?

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        # The payment amount is higher than the invoice one.
Same here

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +
Duplicating the tests between inbound and outbound is a pity ; why not writing a loop each time, wich then takes care of each type ?

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        # The payment amount is higher than the invoice one. Tolerance is not checked.
But it matches the tolerance anyway here, so it'd match even if it was considered. I think this part of the test is useless.

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        # The payment amount is higher than the invoice one. Tolerance is not checked.
Same: "But it matches the tolerance anyway here, so it'd match even if it was considered. I think this part of the test is useless."

2021-08-30 12:53 UTC, oco-odoo commented on addons/account/models/account_bank_statement.py
> +            if i == len(existing_lines):
I don't get this condition; feels weird. Also, i is probably not a very good name if your not incrementing the counter at the end of the loop. Maybe enumerate() would make this clearer ?

2021-08-31 06:26 UTC, smetl commented on addons/account/models/account_reconcile_model.py
> +    allow_payment_tolerance = fields.Boolean(related='model_id.allow_payment_tolerance')
There is already a tooltip on the related field

2021-08-31 06:38 UTC, smetl commented on addons/account/models/account_reconcile_model.py
> +                balance = currency.round(residual_balance * (line.amount / 100.0))
:scream:

2021-08-31 06:43 UTC, smetl commented on addons/account/models/account_reconcile_model.py
> +            return {'write_off', 'reconcile'}
Indeed. This is the same behavior as before. We can discuss about that if you want to

2021-09-01 11:31 UTC, oco-odoo requested changes

2021-09-01 14:04 UTC, oco-odoo approved these changes
@robodoo r+

2021-09-01 22:03 UTC, closed without merging