[FIX] website_form: prevents errors when creating task from form
odoo/odoo pull request #73269
Opened 2021-07-06 07:06 UTC by SwagSamaSempai

In 14.0, when adding a form to a website and selecting "Create a Task" without an active project, an error pops up because no projects are found.

In this commit, we prevent an error from popping up when adding the form without projects, by allowing the field to be empty (not required).

2021-07-06 07:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73269).

2021-07-19 16:45 UTC, qsm-odoo requested changes
Commit message:
- Mention the correct apps: this is not website_form that you modify here
- The title must complete the sentence "when applied, this commit will ...", so "prevent" and not "prevents"
- "creating a task from a form" or "creating tasks from forms", choose :)
- Max 72 characters per line (or 80 if you prefer but the git recommendation is 72). The tile should even be limited to 50 characters per line if possible but 72/80 is fine there too.
- Finish you commit message by a blank line follow by exactly: `task-XXX` with XXX being the ID of your Odoo task

2021-08-17 15:38 UTC, rdeodoo requested changes
All remarks of @qsm-odoo were applied.
The fix works as it should, tested & working.
Just one last stuff, when @qsm-odoo said 
> Max 72 characters per line (or 80 if you prefer but the git recommendation is 72). The tile should even be limited to 50 characters per line if possible but 72/80 is fine there too.

What he meant was: make the lines **as long as you can**, up to 50/72/80 for the title and 72/80 for the commit message.

Here, I am not sure what you did but you cut your line at 53 instead of 80 :shrug: 

You can find everything in the [doc](https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html?highlight=commit%20guidelines#git) (event the [old one](https://www.odoo.com/documentation/11.0/reference/guidelines.html#git) since it didn't change in years)

**Commit Title**:
- Github purist: 52 -> impossible with Odoo as we have a prefix for IMP/FIX and another for module
- Odoo -> the most important rule is **NEVER OVER 72 character** for your title otherwise it is folded & truncated in github UI
See:
![image](https://user-images.githubusercontent.com/30048408/129756120-2b1153cf-8634-4788-a3ad-24297728f92c.png)

That's pretty bad, and it is truncated everywhere, in PR name, in PR commits list..

**Commit Description**, don't go over 80 ever, pretty universal as a rule (not only git, same for docstring etc), it allow stuff to be read on terminal. (ideally we should also don't go over 80 when coding but it is very hard to do, so 100 is fine for coding, and if you go over it it's not the end of the world)

In this case, your title is fine (72 char) but your commit description is not fine (up to 53 instead of up to 72/80 (choose one, choose 80 :D ))

Of course, the goal is
to take as much space
as we can, because
otherwise it gets hard to
read ;-)

2021-08-17 15:44 UTC, qsm-odoo reviewed
@robodoo delegate=rdeodoo

2021-08-17 15:50 UTC, rdeodoo commented
@robodoo r+

2021-08-17 15:55 UTC, rdeodoo commented
@SwagSamaSempai I adapted the commit message myself so this can be merged, please check my previous message that should give you additional info about it

2021-08-17 17:35 UTC, closed without merging