[13.0][FIX] account: account move company in analytic entrie
odoo/odoo pull request #73381
Opened 2021-07-07 14:47 UTC by PabloPaezSheridan

Description of the issue/feature this PR addresses:

When an invoice has a  line with a analytic account which has no company, the analytic entrie is saved with the company of the user and not the company of the invoice

Current behavior before PR:

1-Create a new invoice with a journal from a company different of the user actual logged company
2- add a line with a analytic account without company

Check that the analytic entrie is saved with the company logged and not with the invoice company

Desired behavior after PR is merged:

The analytic entries should be saved with the company of the journal (which is the company of the invoice)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-07 14:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73381).

2021-07-07 15:43 UTC, nicomacr approved these changes
LGTM

2021-07-08 11:28 UTC, oco-odoo requested changes
Just a small detail, then it's ok for me :)
Also, you'll need to sign the CLA in order to make the build green. See hhttps://github.com/odoo/odoo/blob/13.0/doc/cla/sign-cla.md

2021-07-08 11:28 UTC, oco-odoo commented on addons/account/models/account_move.py
> +
You don't need this empty line ;)

2021-08-12 13:00 UTC, closed without merging

2021-08-12 13:28 UTC, PabloPaezSheridan commented
@oco-odoo sorry about the delay (i was on my holidays) and the closed PR, it was quiet hard to solving the cla problem. All is fixed in #75031