[FIX] web: resize only target column in list view
odoo/odoo pull request #73636
Opened 2021-07-13 13:36 UTC by nboulif

Steps to reproduce:

  ! Chrome version >= 91.0.4472.114 (no issue on <= 90.0.4430.51)
  - Install Accounting module
  - Go to Customer Invoices and create a new one
  - Add a customer with a very long name, add product then save
  - Go back to list view
  - Ensure that the column "Customer" does not display the full
    customer name
  - Try to resize "Customer" column

Issue:

  All columns are resized.

Cause:

  Since Chrome 91.0.4472.114, `max-width` on column cause
  an issue with table.
  The issue is triggered when a <th> width size exceeds the maxWidth size.
  When resizing, the maxWidth of current column stays the same.

Solution:

  On resizing, update also, maxWidth with new width value.

opw-2585307

2021-07-13 13:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73636).

2021-07-13 13:38 UTC, nboulif commented
Hello @aab-odoo :slightly_smiling_face: 
May I ask for a review please?
Not sure if the fix make sense since I did not understand why a max-width is set on a cell that is re-sizable...
Thanks in advance!
cc @Arcasias

2021-07-19 07:38 UTC, nboulif commented
ping @odoo/rd-framework-js

2021-07-27 12:01 UTC, Arcasias requested changes
LGTM, though I think you remove one semicolon to many 👀

2021-07-27 12:33 UTC, nboulif commented on addons/web/static/src/js/views/list/list_editable_renderer.js
> +                th.style.maxWidth = `${maxWidth}px`
My bad. Done :+1:

2021-08-02 09:41 UTC, nboulif commented
Hello @Arcasias , do you think the PR is ready to r+?

2021-08-02 11:24 UTC, Arcasias requested changes
Hi, sorry to come back this late : actually I think it would be better to write a test to ensure that this fix is preserved in the soon-to-be-refactored list view. I think you can already find some tests with similar situations in which you can just add a few assertions to ensure that all other columns keep their widths unchanged.

2021-08-02 15:02 UTC, nboulif commented
@Arcasias Hello, thanks for the review!
My bad, I forget to push the test. I update the fix, but since I'm not so good in tests, not sure if what I did is ok...

2021-08-02 15:43 UTC, Arcasias approved these changes

2021-08-02 15:43 UTC, Arcasias commented
@robodoo r+

2021-08-02 15:44 UTC, robodoo commented
I'm sorry, @Arcasias. I'm afraid I can't do that.

2021-08-02 16:37 UTC, aab-odoo commented
robodoo r+

2021-08-02 17:20 UTC, closed without merging