[FIX] web_editor: fix link regex
odoo/odoo pull request #73694
Opened 2021-07-14 11:18 UTC by Goaman

The regex that automatically detect link when pasting text or
when pressing space when editing was not good enough and
for instance did not capture fully an url like:
https://1234-abc.runbot007.odoo.com/web#id=3&menu_id=221

Task ID: 2602725

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-14 11:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73694).

2021-07-16 07:48 UTC, Zinston requested changes
Commit looks good to me. Thanks for having added tests ;-)
I made the mistake of letting the previous one slide but you should follow the guidelines regarding commit messages:

https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html?highlight=guidelines#commit-message-header
> It should be self explanatory and include the reason behind the change. Do not use single words like “bugfix” or “improvements”.

2021-07-16 07:48 UTC, Zinston commented on addons/web_editor/static/lib/odoo-editor/test/spec/urlRegex.test.js
> +describe('urlRegex', () => {
:+1:

2021-07-19 07:36 UTC, Goaman commented
> Commit looks good to me. Thanks for having added tests ;-)
> I made the mistake of letting the previous one slide but you should follow the guidelines regarding commit messages:
> 
> https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html?highlight=guidelines#commit-message-header
> 
> > It should be self explanatory and include the reason behind the change. Do not use single words like “bugfix” or “improvements”.

I think it is self explanatory, the reason is also implicit, the regex is broken so we fix it.
This commit header is not a single word.

If you have a better message, can you make a suggestion ?

2021-07-19 07:48 UTC, Zinston commented
@Goaman 
> If you have a better message, can you make a suggestion ?

`[FIX] web_editor: properly capture any form of url on paste` for example. This tells _what behavior is fixed_ rather than just the code you touched. That part is for the commit message if even needed. The header should give a good idea of the _purpose_ of the commit for someone stumbling on it, who has no context and no particular knowledge of the workings of the editor.
Think of it this way: someone stumbles on the regex and blames it to see why it looks the way it does. Then they see "fix the regex". No information was learned, now they have to waste time looking into the history. Whereas if they see "properly capture any form of url on paste" they learned that it had something to do with pasting and being less restrictive with the url forms that could be captured. They saved time, energy and frustration.

2021-07-19 11:07 UTC, Goaman commented
Done.

2021-07-19 12:30 UTC, Zinston commented
@robodoo rebase-ff r+

2021-07-19 12:30 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-07-19 14:06 UTC, closed without merging