[FIX] web_editor: double insert link on paste
odoo/odoo pull request #73709
Opened 2021-07-14 12:28 UTC by Goaman

When pasting text containing url, the url was pasted twice.
One being simple text and the other one being a link.

Task ID: 2602785

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-14 12:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73709).

2021-07-16 07:59 UTC, Zinston requested changes
Lgtm. Again about the commit header though, please use a verb. For instance: "prevent double insert link on paste".

https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html?highlight=guidelines#commit-message-header
> Commit message header should make a valid sentence once concatenated with if applied, this commit will `<header>`.

2021-07-19 07:39 UTC, Goaman commented
> Lgtm. Again about the commit header though, please use a verb. For instance: "prevent double insert link on paste".
> 
> https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html?highlight=guidelines#commit-message-header
> 
> > Commit message header should make a valid sentence once concatenated with if applied, this commit will `<header>`.

Done.

2021-07-19 07:49 UTC, Zinston commented
@robodoo r+

2021-07-19 09:46 UTC, closed without merging