[FIX] base: Define address format for Peru
odoo/odoo pull request #73717
Opened 2021-07-14 12:59 UTC by DjamelTouati

Steps to reproduce the bug:
- Install eCommerce and l10n_pe
- Go as website visitor
- Add anything to your cart
- Continue with checkout to go to the address page
- Select country Peru and fill in all the required fields
- Validate
- You will get an error message telling you that you forgot to fill in a required field.

Problem:
You cannot validate the address because zip code is not displayed, but required. This field is based on the country format address to be displayed before or after the `" City "` field and is not displayed if `" zip "` is not present in the country format address

https://github.com/odoo/odoo/blob/b1107cba38e296f17d03d9919be67e6789a407be/addons/website_sale/views/templates.xml#L1208

https://github.com/odoo/odoo/blob/15fe3d43b4b925a32b42eb46048a33987e10336b/openerp/addons/base/res/res_country.py#L77

Solution:
"zip" is required for the Peru country, so it must be added in the address format

opw-2600526

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-14 13:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73717).

2021-07-14 13:39 UTC, JKE-be requested changes
Zip is already in the default format adress.
Your diff will be erased by  https://github.com/odoo/odoo/blob/14.0/addons/l10n_pe/data/res_country_data.xml#L35

Did you test your code ?

2021-07-14 14:13 UTC, jco-odoo commented
@JKE-be I agree with you that it is better to have these in base anyways.  It is just that for the view_id the district is added, which we don't have in base.

2021-07-14 15:02 UTC, JKE-be commented
Ok, ty for feedback.

So imo fix is to move it to base and add zip if required in address_format; and remove override from l10n_pe.

2021-07-14 15:40 UTC, DjamelTouati commented
Thanks for the review, unfortunately we can't move it to base because `" enforce_cities "` and `" street_name "` are not defined in base. so i think it's better to leave the override and just add zip in the address format.

I made an update, @JKE-be  could you check, please?
Thanks!

2021-07-15 08:38 UTC, JKE-be commented
@robodoo r+

after discussion, not easy to move in base, since the 'base' doesn't depend of base_address_extend for street_name.
And if l10n_pe not installed, the default format with zip will be used, so ecommerce available too.

2021-07-15 09:36 UTC, closed without merging