[IMP] account: improve invoice/bills view
odoo/odoo pull request #73723
Opened 2021-07-14 13:37 UTC by jbw-odoo

- Group filters into less technical/more functional approach
- Small tree view change

Task: 2541366

2021-07-14 13:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73723).

2021-07-27 08:14 UTC, smetl requested changes

2021-07-27 08:14 UTC, smetl commented on addons/account/views/account_move_views.xml
> +                    <field name="payment_state" widget="badge" decoration-danger="payment_state == 'not_paid'" decoration-warning="payment_state in ('partial', 'in_payment')" decoration-success="paym
plz indent :p
```
<field name="payment_state"
       widget="badge"
       decoration-danger="payment_state == 'not_paid'"
       decoration-warning="payment_state in ('partial', 'in_payment')"
       decoration-success="payment_state in ('paid', 'reversed')"
       attrs="{'invisible': [('payment_state', 'in', ('invoicing_legacy'))]}"
       optional="show"/>
```

2021-07-27 08:14 UTC, smetl commented on addons/account/views/account_move_views.xml
> +                        ('payment_state', '=', 'partial')]"/>
`('payment_state', 'in', ('in_payment', 'not_paid', 'partial'))` ?

2021-07-27 08:14 UTC, smetl commented on addons/account/views/account_move_views.xml
> +                        ('payment_state', '=', 'paid'), ('payment_state', '=', 'reversed')]"/>
`('payment_state', 'in', ('paid', 'reversed'))`

2021-07-27 08:14 UTC, smetl commented on addons/account/views/account_move_views.xml
> +                    <filter name="late" string="Overdue" domain="['&amp;', ('invoice_date_due',
this is confusing: `&` followed by 3 elements

2021-07-27 08:51 UTC, jbw-odoo commented
Done

2021-07-27 12:45 UTC, smetl commented
@robodoo r+

2021-07-27 17:23 UTC, closed without merging