[FIX] mrp: prevent crash if no date_end
odoo/odoo pull request #73746
Opened 2021-07-15 06:25 UTC by walidash

Description of the issue/feature this PR addresses:

- If there is no `date_end`, sorting will crash.

Current behavior before PR:

- Can't open MRP -> Operations -> Work Orders

Desired behavior after PR is merged:

- Be able to open Work Orders

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-15 06:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73746).

2021-07-15 13:43 UTC, amoyaux commented
Okay just need to make runbot green

2021-07-15 13:43 UTC, amoyaux commented
@fw-bot up to 13.0

2021-07-15 13:44 UTC, amoyaux commented
https://github.com/odoo/odoo/pull/56603

2021-07-15 15:10 UTC, DjamelTouati requested changes
Thanks for the fix @walidash
I think in order to make the runbot tests green you need to close this pr, delete the branch and create a new one with correct name by following these guidlines: https://github.com/odoo/enterprise/wiki/Git#branches

As you wrote `"12.0_"` instead of `"12.0-"`, runbot cannot detect with which version you want to merge your branch, so it chooses Master. You can go to `"ci/runbot> details> version"`. You will notice that it is master instead of 12.0

2021-07-15 16:21 UTC, amoyaux commented
It should not since it's in odoo community and the whole community code is already in the branch, runbot doesn't need to know the version here. Maybe just a rebase or a rebuild

2021-07-16 11:42 UTC, DjamelTouati commented
@amoyaux 
I did a test, I created a new branch with a name that starts with " 12.0_ " instead of " 12.0- ", I rebased it before pushing and i had the same problem. So for me the problem probably comes from the name of the branch and not from the rebase or the rebuild.

2021-07-16 17:21 UTC, closed without merging