[FIX] website: flip the TrackPage dependency to resolve an issue for anonymous website users
odoo/odoo pull request #73805
Opened 2021-07-15 17:56 UTC by holdenrehg

https://github.com/odoo/odoo/issues/71842

Anonymous website users do not have access to the Customize menu
obviously, but the `website.set_view_track` widget still attempts to
extend the CustomizeMenu.

The dependency can just be flipped around with the CustomizeMenu
depending on the `website.set_view_track module` instead. It's the only
place that the module is currently being referenced so it's only a
single change.

**Current behavior before PR:**

The JavaScript from Odoo fails if you're not logged in:

**Desired behavior after PR is merged:**

There's no missing dependencies issues causing parts of the JS to crash.

**Technical changes:**

- Moved the `TrackPage` widget to load only in editor assets.
- Included the `_attachTrackPage` functionality directly in the customize menu. No specific reason to have that split into 2 places, keeps the `TrackPage` widget a little more pure, dependencies a little less messy.
- Renamed `set_track_page.js` to `track_page.js` and `website.set_track_page` to `website.trackPage` because it is now only a standalone widget named `TrackPage`. It makes more sense to developers when importing `let TrackPage = require("website.trackPage");` instead of `set_track_page`.

--

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-15 17:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73805).

2021-07-15 18:12 UTC, Yenthe666 commented
@JKE-be here's the V13 PR :)

2021-07-15 18:36 UTC, JKE-be requested changes
ofc you cannot rename file in stable...
you cannot warranty the -u and the pull at the same time.

Why not just move the file without change name and without change code... 
Should be enough...

2021-07-15 20:15 UTC, holdenrehg commented
I can do that @JKE-be if you'd like.

It should require a `-u` either way because of the change to the `<link/>` reference (from frontend to editor assets), so thought it'd be a good opportunity for a couple very minor improvements.

2021-07-19 06:41 UTC, Yenthe666 commented
@holdenrehg do a squash & push :)

2021-07-20 14:50 UTC, holdenrehg commented
@Yenthe666 squashed and pushed :+1: 

@JKE-be updates made.

2021-07-20 14:53 UTC, JKE-be commented
@robodoo r+

2021-07-21 15:30 UTC, Yenthe666 commented
@JKE-be robodoo is not doing anything :)

2021-07-21 20:28 UTC, closed without merging