[IMP] web_editor: Image shapes for themes & website configurator
odoo/odoo pull request #73938
Opened 2021-07-19 07:49 UTC by xO-Tx

The goal of this PR is to add a "Python version" of the
shape on image feature using a controller.

Since the whole logic to apply shapes on image is JS based, we need
to use this URL (just like background shapes) when we want to add
a shape by default on images in themes.

When the configurator replaces a snippet image (with default shape),
the shape option should still be applied on the new one.

task-2593454

2021-07-19 07:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73938).

2021-07-28 09:39 UTC, qsm-odoo requested changes
Seems to be a good work, try to finish it even faster, I'd like to merge this today :+1: You'll have to adapt some stuff according to my only comment. Also in the second commit you say:

> - Update 'data-mimetype' on image to SVG since loadImageInfo()
> will set the original attachment mimetype on it.

-> seems useless to mention in the commit message

> - Prevent saving image as base64 when it's saved without
any changes being made.

I don't see what part of the code is doing that? And should not it be in a separate fix commit then?

Squash both commits, they are very related IMO.

2021-07-28 09:39 UTC, qsm-odoo commented on addons/web_editor/controllers/main.py
> +        if img_key:
Kinda strange to have a required attribute as additional parameter, maybe change the URL form to:

`/web_editor/image_shape/<the image key here>/<module>/<path:filename>`

2021-07-28 12:40 UTC, xO-Tx commented
> > * Prevent saving image as base64 when it's saved without
> >   any changes being made.
> 
> I don't see what part of the code is doing that? And should not it be in a separate fix commit then?

This happens when image has a shape option + image src is not a data URL (e.g. image with a saved shape option / image with shape added by theme using the Python URL).

I fixed that by adding a condition to prevent `_applyOptions()` from reapplying shapes (which converts image to base64) when image URL returns **image + a shape applied on it**.

Moved now to a separate commit since it's a general issue.

2021-07-29 10:36 UTC, qsm-odoo requested changes

2021-07-29 10:36 UTC, qsm-odoo commented on addons/web_editor/controllers/main.py
> +        if img_key:
@xO-Tx The point of the URL change, was to be able to remove that condition, you now always have an `img_key`.

2021-07-29 10:36 UTC, qsm-odoo commented on addons/web_editor/controllers/main.py
> +                user_colors.append([tools.html_escape(css_color_value), colorMatch.group(1)])
Seems good :+1: but maybe a small problem: when you search for a color in the bundle and that you don't find it (`if color_search` is falsy), you should return a bad request too I think?

2021-07-29 10:36 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +                .map(color => this._getCSSColorValue(color)).join(';');
Not sure this is perfect: don't you have the risk of ending up saving an image where the URL is still something with `?c1=o-color-3` but where you replaced the data-shape-colors with the actual CSS color of o-color-3?

= Can't you just convert with `_getCSSColorValue` when you **use** that data-shape-colors value?

2021-07-30 17:14 UTC, qsm-odoo approved these changes
Thanks for the work, in the end I squashed the 3 commits and added the final xpath example in the commit message (the 3 commits made the review easier but they were really too related to be merged individually).

@robodoo r+

2021-07-30 17:15 UTC, robodoo commented
@qsm-odoo, you may want to rebuild or fix this PR as it has failed CI.

2021-07-30 17:45 UTC, qsm-odoo commented
@xO-Tx A bit better this way: https://github.com/odoo/odoo/compare/17f7e8a30a47acd1aff82c77361b714a1dd76df6..4cad1ef8380a3fac7883e30ac863514ccd879163 :+1:

2021-07-30 17:45 UTC, JKE-be commented
@robodoo override=ci/security

Code moved
Already quickly checked by odo  https://github.com/odoo/odoo/pull/56479
Always limited to static files, so should be not risky
And now limited to svg

2021-07-30 17:46 UTC, qsm-odoo commented
@robodoo r+

2021-07-30 21:33 UTC, closed without merging