[FIX] website_forum: display anchor tag instead of link
odoo/odoo pull request #73960
Opened 2021-07-19 11:47 UTC by dhp-odoo

**Purpose**
Anchro tag is display as a string in the notification instead of display link.

**Specification**
Due to not passing the escaping parameter option in displayNotification,
it will display any html tag as a string in the warning.
With this commit, we have passed 'messageIsHtml' as a parameter to properly
display the Link in the warning notification.

Task : 2601633

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-19 11:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/73960).

2021-07-26 08:41 UTC, qsm-odoo requested changes

2021-07-26 08:41 UTC, qsm-odoo commented on addons/website_forum/static/src/js/website_forum.js
> +            messageIsHtml: true, // dynamic parts of the message are escaped above
Why do you explain that dynamic parts of the message are escaped above while not escaping is done above? :thinking:

2021-07-26 11:08 UTC, dhp-odoo commented
reference https://github.com/odoo/odoo/pull/74220

2021-07-26 11:08 UTC, closed without merging