Update user_type_id
odoo/odoo pull request #74061
Opened 2021-07-20 17:28 UTC by KARIZMA-CONSEIL

Description of the issue/feature this PR addresses:
Update user_type_id for some account template

Current behavior before PR:
Wrong setting of account type

Desired behavior after PR is merged:
Correct account type current assets and revenu type

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-20 17:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/74061).

2021-07-22 06:29 UTC, william-andre requested changes
Can you please follow the guidelines for the commit message and give some documentation for your changes?
https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure

2021-07-22 11:23 UTC, KARIZMA-CONSEIL commented
@william-andre I updated the title and description as you suggested.
I note that this update must apply on the 14.0 and master branches

2021-07-22 12:43 UTC, william-andre commented
You changes the description of the pull request, not of the commit.

Also, please remove useless diff. (encoding?) Harder to read the diff + potential conflicts + obfuscation in blame

2023-09-08 14:42 UTC, closed without merging