[FIX] website: traceback on non html page set as a link
odoo/odoo pull request #74080
Opened 2021-07-22 05:09 UTC by dhp-odoo

**PURPOSE**
when you add a link in any of the buttons on the website with
non HTML/XML page, it will raise the traceback as we fetch the content to find
id to propose as a list of anchors.

Reproduction Steps:
1) Add a button on the website using the editor.
2) Add link in URL (i.e. /robots.txt)
3) Traceback

**SPECIFICATION**
We are handling the catch if it will raise the traceback.

Task : 2596392

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-07-22 05:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/74080).

2021-07-23 08:22 UTC, JKE-be commented
Hey Dhruv,

Could you add a console.error to keep a trace of the error into the catch()

Thank you

2021-07-23 08:58 UTC, dhp-odoo commented
> Hey Dhruv,
> 
> Could you add a console.error to keep a trace of the error into the catch()
> 
> Thank you

Changes Done.

2021-07-23 13:21 UTC, rdeodoo requested changes
Just linter error
Working as expected :+1: (good catch for external link)

2021-07-23 13:21 UTC, rdeodoo commented on addons/website/static/src/js/utils.js
> +        if (url == window.location.pathname || url[0] == '#') {
```suggestion
        if (url === window.location.pathname || url[0] === '#') {
```

2021-07-23 13:21 UTC, rdeodoo commented on addons/website/static/src/js/utils.js
> +        } else if (url.length && !url.startsWith("http")){
```suggestion
        } else if (url.length && !url.startsWith("http")) {
```

2021-07-23 13:21 UTC, rdeodoo commented on addons/website/static/src/js/utils.js
> +        console.debug(error);
not sure this is useful but why not :shrug:

2021-07-23 14:33 UTC, JKE-be commented
@robodoo r+

thank you rdelint for review

2021-07-23 15:51 UTC, closed without merging