[FIX] account
odoo/odoo pull request #74427
Opened 2021-07-29 12:00 UTC by abz-odoo

Draft

2021-07-29 12:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/74427).

2021-07-30 07:06 UTC, smetl requested changes

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                    'tag_ids': [(6, 0, tax_tag_pos.ids)],#-G1,+GST
remove comments

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +            'sequence': 10,
sequence is useless

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +            'invoice_repartition_line_ids': [
remove `price_include`, `amount_type`, `type_tax_use` and rename the tax to something like `test tax`

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                'tax_ids': [(6, 0, [tax.id])]
`tax.ids`

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                'date': time.strftime('%Y-07-15'),
put `2020-07-15` directly

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +import time
remove this import

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                'company_id': self.company.id,
default company is the current one so you can remove `company_id` here and above

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                'partner_name': 'test',
`partner_name`, `company_id` are useless

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        res = reconciliation_model._get_write_off_move_lines_dict(bank_stmt.line_ids[0], 5)
you only have one st_line so `bank_stmt.line_ids` is enough

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +                'reconcile_model_id': reconciliation_model.id,
you can remove `currency_id`, `debit`, `credit`, `analytic_account_id`, `analytic_tag_ids`, `tax_exigible`
Also, plz use the same order in both dictionaries ><

2021-07-30 07:06 UTC, smetl commented on addons/account/tests/test_reconciliation_matching_rules.py
> +        self.assertEqual(res, model, 'Tags are not reverted')
use `assertRecordValues` plz

2021-07-30 08:19 UTC, smetl approved these changes
@robodoo r+

2021-07-30 10:52 UTC, robodoo commented
Staging failed: ci/runbot on 3c60d0514abceb780d0656e04a24e141a0a26be7 (view more at http://runbot.odoo.com/runbot/build/9199748)

2021-07-30 11:00 UTC, abz-odoo commented
@robodoo r+

2021-07-30 11:01 UTC, robodoo commented
I'm sorry, @abz-odoo. You can't review+.

2021-07-30 11:04 UTC, abz-odoo commented
@robodoo retry

2021-07-30 11:29 UTC, robodoo commented
Staging failed: ci/runbot on 6ae8cb1cce5ac4b415452801c123c1e344e00507 (view more at http://runbot.odoo.com/runbot/build/9200446)

2021-07-30 11:38 UTC, abz-odoo commented
linked pr: https://github.com/odoo/enterprise/pull/19979

2021-08-02 09:07 UTC, closed without merging