[IMP] web: Add debounce option in initAutoMoreMenu
odoo/odoo pull request #74677
Opened 2021-08-04 01:05 UTC by imanie383

Description of the issue/feature this PR addresses:
Add debounce option in initAutoMoreMenu

In some cases we need to:
When the element in the menu change and we need to resize instantaneously 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-08-04 01:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/74677).

2021-08-05 16:50 UTC, luisg123v commented
@moylop260 What do you think?

2021-08-05 17:04 UTC, moylop260 commented
@qsm-odoo
What do you think?

2021-08-06 07:36 UTC, qsm-odoo requested changes
Your video shows a need to update after an event which is not a 'resize' event. I don't think parameterizing the debounce after a resize event makes sense (either our value should be lower or higher but not changed depending on the cases).

Maybe you could do something like this?
```javascript
$el.data('dom:autoMoreMenu:adapt', _adapt);
```
So that your external code can update the menu directly when needed (not a fan of functions attached to the DOM as jquery data but it is already done for the destroy and it is bootstrap-like, we can still improve later).

Also, about your commit message: no uppercase to start the title sentence please :+1:

2021-08-08 16:27 UTC, luisg123v commented
Hi @qsm-odoo,

Requested changes habe been applied. Could you review again, please?

Regards,

CC @hugho-ad

2021-08-09 08:43 UTC, qsm-odoo requested changes
The data should be removed in destroy

2021-08-09 14:58 UTC, imanie383 commented
> The data should be removed in destroy

2021-08-09 16:43 UTC, qsm-odoo approved these changes
@robodoo r+

2021-08-09 16:44 UTC, robodoo commented
@qsm-odoo, you may want to rebuild or fix this PR as it has failed CI.

2021-08-09 16:48 UTC, qsm-odoo commented
@imanie383 can you rebase your branch please? Thank you :+1:

2021-08-09 17:13 UTC, imanie383 commented
> @imanie383 can you rebase your branch please? Thank you

Done

2021-08-10 08:47 UTC, qsm-odoo approved these changes
@robodoo r+

2021-08-10 10:11 UTC, closed without merging