[IMP] account: cache _get_fpos_by_region
odoo/odoo pull request #75004
Opened 2021-08-12 10:56 UTC by yelizariev

It saves about 180 ms for default /shop page

BEFORE

```
     187 0.138 0.264
     187 0.129 0.254
     187 0.162 0.317
     ---------------
AVG: 187 0.143 0.278

AFTER

      67 0.067 0.182
      67 0.072 0.154
      67 0.069 0.156
      --------------
AVG:  67 0.069 0.164
```

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-08-12 10:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75004).

2021-08-12 10:59 UTC, yelizariev commented
![image](https://user-images.githubusercontent.com/186131/129185865-914ac10e-5b65-4967-acf6-c43e6a5c5490.png)

2021-08-12 12:52 UTC, Yenthe666 commented
Couldn't this be a backport actually? As it is a perf 🤔

2021-08-17 15:56 UTC, william-andre requested changes
Very similar changes have already been refused by AL because it makes too many cache invalidation
https://github.com/odoo/odoo/pull/68404

2021-08-19 07:12 UTC, yelizariev commented
@william-andre 
create/write operations on `res.country`, `account.fiscal.position` don't happen often. Am I wrong?

2023-02-13 14:15 UTC, closed without merging