[FIX] web.controllers: export fail when list passed to write function
odoo/odoo pull request #75168
Opened 2021-08-16 22:40 UTC by assellalou

when trying to export the field `Tax amount by group` in invoices it fails with a traceback as the `write` function only expects a string while the `write_cell` function passes a list of tuples.

To reproduce it: go to invoices list view -> group by some field -> select some invoices and export the field Tax amount by group

opw-2591239

2021-08-16 22:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75168).

2021-08-16 22:41 UTC, assellalou commented
@LucasLefevre

2021-08-17 07:33 UTC, LucasLefevre requested changes
Hello @assellalou ,
I better understand the problem now. The field `amount_by_group` is actually a Binary field which contains a really custom python data structure.
I don't think we want to support this in the generic excel export. We don't want specific/obscure code in the generic web controller to handle an unusual/esoteric field in a lost sale report. That's a bad idea.

Can you ask the product owner what are his thoughts?
The export shouldn't crash though.

I see several options:
1) Cast everything to string in the `write` method like you originally wanted, even if the result is not user-friendly
2) try/catch failed cell values and ignore them (leave the cell blank)
3) refactor the way fields are exported to excel in order to implement custom behaviors cleanly (but that won't happen)
4) remove `amount_by_group` and use more conventional ways to achieve the same thing

In any case, a test is missing to test this scenario with weird computed fields. We need to ensure the export is robust ;)

2021-08-17 07:44 UTC, mart-e commented
> I better understand the problem now. The field amount_by_group is actually a Binary field which contains a really custom python data structure.
> I don't think we want to support this in the generic excel export. We don't want specific/obscure code in the generic web controller to handle an unusual/esoteric field in a lost sale report. That's a bad idea.

I tend to agree with Lucas on this. A binary field to transmit a list is kind of a hack and we don't really need to support it for the export, just forbidding to export it is probably enough.

2021-08-17 08:21 UTC, odony commented
>     3. remove `amount_by_group` and use more conventional ways to achieve the same thing

Let's pick option 3 and fix the tax-group-custom-field widget as this is a horrible hack ;) At the very least this field should be JSON-encoded, which would make it a string that can be safely exported.

Note that exporting this value will still be mostly broken because there is no "export"-equivalent for widgets, but at least it will work.

2021-08-19 09:54 UTC, assellalou commented
@oco-odoo @LucasLefevre I don't understand how the issue happens only when grouping by some field

2021-08-19 13:15 UTC, LucasLefevre commented
Data come from two different methods if its grouped or not (`read_group` vs `export_data`). Data is probably presented slightly differently between the two ;)

2021-11-10 12:31 UTC, assellalou commented
@LucasLefevre kindly review

2021-11-10 12:37 UTC, LucasLefevre requested changes
What happened to the test?

2021-11-10 12:41 UTC, LucasLefevre commented
Also, could you explain in your commit message that a similar issue was previously fixed in the same way for the "ungrouped" export (+ link the commit). To keep a consistent behaviour, the fix is similar (even though it's a bit crappy)

2021-11-10 12:47 UTC, assellalou commented
@LucasLefevre I forgot and forced-pushed :( mb you can add em again if you don't mind.

Thanks

2022-01-25 10:12 UTC, assellalou commented
@LucasLefevre can we please do something about this, please.

2022-01-25 13:14 UTC, LucasLefevre commented
Hello @assellalou 
I pushed a commit with a test.
You can squash both commit messages. I added some details why we fix the issue this way

robodoo delegate=assellalou

2022-01-26 10:37 UTC, assellalou commented
@LucasLefevre done, please review.

2022-02-02 08:17 UTC, LucasLefevre approved these changes

2022-02-02 08:19 UTC, LucasLefevre commented
robodoo r+

2022-02-02 09:11 UTC, closed without merging