[ADD] l10n_ar: move part of the logic of l10n_ar_edi tests to this module
odoo/odoo pull request #75223
Opened 2021-08-17 19:08 UTC by Bruno-Zanotti

### Latam Task 295

- Add a generic common module for tests in l10n_ar and related modules (l10n_ar_reports, l10n_ar_edi and l10n_ar_website_sale)
- Move part of the initialization, helpers, and generic unit test from l10n_ar_edi to l10n_ar
- Create all data used in the test on the fly, replicating what we have already in demo data.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-08-17 19:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75223).

2021-09-17 14:17 UTC, Bruno-Zanotti commented
@jco-odoo 
We already update the PR, all the tests in l10n_ar and l10n_ar_edi are working except for some in test_monotributista.py that are commented. About the l10n_ar_report we comment the init file because we are still working on that. We make a rebase on v14 and I think it's ready to merge.
Enterprise PR: https://github.com/odoo/enterprise/pull/20298

2021-09-23 13:48 UTC, jco-odoo requested changes
This needs cleaning.  But I have also been wondering if it we could not use the test data to create the demo data as well e.g.  (or the opposite)

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/common.py
> +    # TODO: add this move lines to invoice 19
can not be removed?

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/common.py
> +    # # TODO: add supplier invoices for l10n_ar_report tests
Could not this be part of l10n_ar_reports then?

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/common.py
> +        """ Validate an invoice and review that the invoice has been properly posted. """
This method is weird.  It only checks if the invoice is posted, but how can you have an expected_result with respect to that?

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/test_manual.py
> +    def test_03_afip_concept(self):
no need to test individual fields like that

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/common.py
> +            self._validate_and_review(self.demo_invoices[inv], error_msg=test_case)
why not use individual methods for each test instead of the cases-dict?  This looks a bit like reinventing the test framework.

2021-09-23 13:48 UTC, jco-odoo commented on addons/l10n_ar/tests/common.py
> +            pos_number = data.pop('l10n_ar_afip_pos_number')
why pop and not get? (It might be  a bit too magical)

2021-09-28 19:47 UTC, Bruno-Zanotti commented
@jco-odoo thank you for the review, we already update the pr with the suggested changes and removing the unnecessary comments, please let us know what do you think about it, and if everything it's okay it could be merged

2021-10-14 17:51 UTC, closed without merging