[FIX] l10n_ch: Display all QR codes in QR bill
odoo/odoo pull request #75408
Opened 2021-08-20 16:33 UTC by nboulif

Issue:

  It's a known issue with wkhtmltopdf: https://github.com/odoo/odoo/commit/2949138a7d84cd6c925ea1745d62f25ef077bb8b

Solution:

  Replace link by base64 image value.

opw-2620082

2021-08-20 16:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75408).

2021-08-23 12:56 UTC, nboulif commented
ping @oco-odoo

2021-08-31 08:00 UTC, nboulif commented
ping @oco-odoo

2021-09-06 09:18 UTC, oco-odoo requested changes

2021-09-06 09:18 UTC, oco-odoo commented on addons/l10n_ch/models/res_bank.py
> +        return image_data_uri(base64.b64encode(barcode))
Arent't we going to face the same kind of problems with SEPA QR-codes then ? Shouldn't we do the same for them ?
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/res_bank.py#L131

(Note for forward-port: this had nothing to do in base, and got moved to a new account_qr_code_sepa module in v14)

2021-09-08 09:56 UTC, oco-odoo approved these changes
@robodoo r+

2021-09-08 10:36 UTC, closed without merging

2021-09-08 15:39 UTC, nboulif commented
@oco-odoo Thanks!
Little question: is it normal that the fw-port didn't create the PRs?