[FIX] mail: markallasread doesn't care of domain
odoo/odoo pull request #75439
Opened 2021-08-23 10:08 UTC by fmdl

Description of the issue/feature this PR addresses:
- Go to discuss
- add a search in searchbar
- click on Mark All Read
--> Issue all messages are mark all read. The domain is not care

In V12 it works, the issue come from : https://github.com/odoo/odoo/commit/3fea5b2136627c1d7e83b2a5e111952fe3eb10a1

@tde-banana-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-08-23 10:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75439).

2021-08-23 10:08 UTC, fmdl commented
OPW #2630267

2021-08-24 14:26 UTC, nle-odoo approved these changes
intention of fix looks good to me, maybe this could also be done with:

```js
this.env.models['mail.message'].markAllAsRead(JSON.parse(this.discuss.domain));
```

@seb-odoo what do you think?

2021-08-24 14:32 UTC, seb-odoo requested changes

2021-08-24 14:32 UTC, seb-odoo commented on addons/mail/static/src/widgets/discuss/discuss.js
> +        this.env.models['mail.message'].markAllAsRead(this.discuss.domain);
Isn't there no `domain` field on discuss model? This should be `stringifiedDomain` instead?

2021-08-24 14:32 UTC, seb-odoo commented on addons/mail/static/src/widgets/discuss/discuss.js
> +            domain: searchQuery.domain,
The field does not exist, it won't work like that.

2021-08-24 15:59 UTC, fmdl commented
@seb-odoo @nle-odoo fixed !

2021-08-24 16:29 UTC, seb-odoo approved these changes
Thank you for the update
@robodoo r+

2021-08-24 17:46 UTC, closed without merging