[FIX] account: Manual reconcile use the currency
odoo/odoo pull request #75511
Opened 2021-08-24 10:51 UTC by Gorash

When reconciling with the widget, for currencies different from that of
the company, the amount was considered to be in the company currency.
Now, the amount sent is associated with the currency.

opw-2527631

2021-08-24 10:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75511).

2021-09-10 11:35 UTC, qdp-odoo requested changes
Can you detail the failing use case?
Did you check the behavior in the next versions?

2021-09-13 10:07 UTC, Gorash commented on addons/account/tests/test_reconciliation_widget.py
> +        self.env.ref('base.user_admin').write({'groups_id': [(4, self.env.ref('account.group_account_user').id)]})
No, without it the test will not work.

2021-09-13 12:57 UTC, Gorash commented
@qdp-odoo (I will add this example in the commit message). The bug is also in 14.0.

Issue:
What are the steps to reproduce your issue?

Company Currency: USD
Enable Currencies: EUR and USD
Create an Invoice of EUR 80.00
Register a payment of EUR 50.00
Go to Payment, Open Payment Matching
Go to the Tab Manual Operations
The amount is already completed, choose a label, select an account in EUR and a journal in EUR
Apply "Reconcile"

Open the Journal items:
Check all the corresponding journal entries
The amounts are incorrect.

Debit: $ 30.00
Credit: $ 0.00
Amount in currency: 30.00 €

The Debit and Credit amount is in the company's currency but is not applying the exchange rate and currency.

2021-09-16 15:05 UTC, qdp-odoo requested changes
somehow, you manage to break a flow which, sadly, isn't tested,

* company currency is USD
* create an invoice of 100€ + 15% vat (~175$)
* receive 160$ on the bank journal (USD) don't link that to any invoice but simply hit the `validate` button right away to leave that money hanging on the customer account
* open the partner form view, click on the smart button `due amount` to open the followup report
* click on the `reconcile` button to open the reconciliation widget again, on the partner this time
* select the invoice and the payment, and click on the open balance line to add a writeoff of the remaining amount. 
* When that's done, validate the entry
* with your PR, you'll end up having this message (while this use case is _currently_ working in 13.0):

> 'The amount expressed in the secondary currency must be positive when account is debited and negative when account is credited. Moreover, the currency field has to be left empty when the amount is expressed in the company currency.' 


So I'm afraid, this can be accepted as it. Did you consider having the reconciliation widget calls the `_convert()` method and directly sends the debit/credit values to `_create_writeoff()` ? It looks like a less dangerous approach. Also, it would be nice to add the missing test, while you're there...

2021-10-04 07:30 UTC, Gorash commented on addons/account/models/account_move.py
> +                    raise UserError(_("The currency must be the same of the computed write-off currency"))
Adding errors and error messages does not normally occur. However, in the event that this happens (even in stable) it is much better to have a clear error message than a hidden error.

2021-10-04 08:23 UTC, Gorash commented
@qdp-odoo Before correcting the resolution of this bug, I will add your example in a test to avoid regression.

2021-11-24 12:54 UTC, qdp-odoo commented
conflicts... can you solve ?

2022-01-17 13:29 UTC, Gorash commented
@qdp-odoo The branch is rebased

2022-01-18 12:30 UTC, william-andre commented on addons/account/models/account_move.py
> +                    raise UserError(_("The currency must be the same of the computed write-off currency"))
The strings need to be added in the `pot` files in stable versions

2022-01-18 13:10 UTC, Gorash commented on addons/account/models/account_move.py
> +                    raise UserError(_("The currency must be the same of the computed write-off currency"))
I added in .pot file and rebase.

2022-01-24 13:12 UTC, Gorash commented
@qdp-odoo @william-andre  ok ?

2022-03-24 22:10 UTC, tsb-odoo commented
@qdp-odoo Why isn't this merged ?

2023-02-14 12:32 UTC, william-andre commented
There is already a PR in 14.0, and 13.0 is deprecated https://github.com/odoo/enterprise/pull/20902

2023-02-14 12:32 UTC, closed without merging