[ADD] Added VAT report for Italy and simplify tax templates
odoo/odoo pull request #75740
Opened 2021-08-30 12:28 UTC by vin-odoo

The Italian VAT report is needed to help Italian customers fill in
their VAT report.

Task id #2079462

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-08-30 12:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75740).

2021-09-10 07:57 UTC, FlorianGilbert requested changes
Small changes, seems good!

2021-09-14 15:12 UTC, oco-odoo approved these changes
@robodoo r+

2021-09-14 15:12 UTC, robodoo commented
I'm sorry, @oco-odoo. Draft PRs can not be approved.

2021-09-15 05:44 UTC, FlorianGilbert commented
@robodoo r+

2021-09-15 06:26 UTC, closed without merging