[IMP] hr_holidays: improve views
odoo/odoo pull request #75940
Opened 2021-09-03 13:12 UTC by kba-odoo

- Hide transition mode if there is 0 or 1 level on accrual plan;
  - Fix kanban card
  - Reduce bottom padding on calendar view
  - Log a message when an allocation linked to accrual runs for the first
  time

  TaskID: 2636417

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-03 13:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/75940).

2021-09-03 14:07 UTC, mcm-odoo requested changes

2021-09-03 14:07 UTC, mcm-odoo commented on addons/web/static/src/legacy/js/views/calendar/calendar_controller.js
> +            this.previousOpen.on('closed', this, () => {
This is not good, you're creating a dependency between renderer and controller.
In the renderer when you call `trigger_up("openCreate", something)` you should pass a callback to something that will do the unselect.

don't forget to add a test

2021-09-08 10:26 UTC, tivisse commented
@robodoo rebase-ff r+

2021-09-08 10:27 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-09-08 13:54 UTC, closed without merging