[REM] obsolete dependency: feedparser
odoo/odoo pull request #76135
Opened 2021-09-08 05:13 UTC by nilshamerlinck

- Up to odoo 10.0, `feedparser` dependency was optionally used in the cli of [vendored `html2text.py`](https://github.com/odoo/odoo/blob/10.0/addons/mail/models/html2text.py#L437)
- Since 11.0, vendored `html2text.py` has been [removed](https://github.com/odoo/odoo/commit/67c17cb37f6ed0fde5e4bffa0d363e2502100f5b) in favor of maintained package
- Turns out the `feedparser` part in html2text was [dead code for a long time](https://github.com/Alir3z4/html2text/issues/220) anyway
- So we can safely drop this dependency, at least in master

What brought me here, is that odoo didn't install with pip anymore:
- [`feedparser==5.2.1` relies on 2to3](https://github.com/kurtmckee/feedparser/blob/5.2.1/setup.py#L6)
- but [2to3 support has been removed from setuptools since 58.0.0](https://setuptools.readthedocs.io/en/latest/history.html#breaking-changes)

2021-09-08 05:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76135).

2021-09-08 06:09 UTC, Yajo approved these changes

2021-09-08 06:23 UTC, simahawk approved these changes

2021-09-08 06:34 UTC, d-fence requested changes
Nice catch.
Can you change your commit message ?

The first line should be something like:
`[REM] packaging: remove obsolete dependency feedparser `

Also, the commit message should contain the reason why you remove this dependency.
It's very well explained in the pull request message, so you can copy that in the commit message.

Finally, I think you can safely re-target 14.0 to avoid a backport later.

2021-09-08 06:52 UTC, pedrobaeza commented
If I read correctly, in fact it can be removed since 12.0, isn't it?

2021-09-08 07:02 UTC, d-fence commented
> If I read correctly, in fact it can be removed since 12.0, isn't it?

omg, you are right. I was distracted by the  67c17cb37f6ed0fde5e4bffa0d363e2502100f5b only showing in 14.0 on github interface.

So, I'm sorry but you can re-target to 12.0

2021-09-08 07:38 UTC, MiquelRForgeFlow approved these changes

2021-09-08 07:45 UTC, nilshamerlinck commented
Complete @d-fence :)

2021-09-08 17:09 UTC, matteoopenf approved these changes

2021-09-09 06:44 UTC, d-fence commented
robodoo r+

2021-09-09 07:24 UTC, closed without merging

2021-09-09 07:54 UTC, matteoopenf commented
Forward to 13 and 14?

2021-09-09 07:57 UTC, d-fence commented
> Forward to 13 and 14?

It's automatic.

2021-09-09 07:58 UTC, matteoopenf commented
Thanks 

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 9 set 2021, alle ore 09:58, Christophe Monniez ***@***.***> ha scritto:
> 
> ﻿
> Forward to 13 and 14?
> 
> It's automatic.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_