[FIX] website: make search by "Visited Pages" work again
odoo/odoo pull request #76160
Opened 2021-09-08 13:05 UTC by yelizariev

Field `website.visitor::page_ids` was storable initially [1], but then it was
refactored [2] and hence the search by "Visited Pages" [3] became broken.

Fix it by adding `search=` attribute

[1] https://github.com/odoo/odoo/commit/6bec0e4d29e6b33b74962b2893a7a405667ef58c
[2] https://github.com/odoo/odoo/commit/e33172e83210a5e0044a6fb92e315b84deefc440
[3] https://github.com/odoo/odoo/blob/c6c7605cdae803aca4f441ef4e622a1b79f17019/addons/website/views/website_visitor_views.xml#L248-L257
---

opw-2622141

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-08 13:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76160).

2022-03-18 09:46 UTC, yelizariev commented
Hello @odoo/rd-website !

2022-05-16 20:33 UTC, rdeodoo requested changes
Hi thanks for the fix.

Could you please also adapt the commit message? The markdown links are missing the `:` which makes them real markdown links (see https://github.com/odoo/odoo/pull/80055#pullrequestreview-861376590).

So instead of
```
[1] https://github.com/odoo...
[2] https://github.com/odoo...
[3] https://github.com/odoo...
```
=> 
```
[1]: https://github.com/odoo...
[2]: https://github.com/odoo...
[3]: https://github.com/odoo...
```

2022-05-16 20:33 UTC, rdeodoo commented on addons/website/models/website_visitor.py
> +        return [('id', 'in', results.visitor_id.ids)]
Why not just
```suggestion
        return [('website_track_ids.page_id.name', operator, value)]
```

2022-05-16 20:33 UTC, rdeodoo commented on addons/website/models/website_visitor.py
> +        if operator not in ('like', 'ilike', 'not like', 'not ilike', '=', '!='):
Probably those 2 at that point?
```suggestion
        if operator not in ('like', 'ilike', 'not like', 'not ilike', '=like', '=ilike', '=', '!='):
```

2022-05-16 20:33 UTC, rdeodoo commented on addons/website/models/website_visitor.py
> +            raise ValueError(_('This operator is not supported'))
Missing translation in the .pot file?

2022-05-18 09:42 UTC, rdeodoo approved these changes
@robodoo r+
Thank you

2022-05-18 10:54 UTC, closed without merging