[FIX] website: use better practices for classList manipulation
odoo/odoo pull request #76346
Opened 2021-09-10 13:41 UTC by kzhekov

**Description of the issue/feature this PR addresses:**
Assigning a value to an element's classList is bad practice
and unpredictable behaviour.
**Current behavior before PR:**
This bad practice is used throughout the multirange_custom.js.
**Desired behavior after PR is merged:**
The recommended way of manipulating the classList is uses, i.e. the add(),
toggle(), and remove() methods are used instead of direct assignment.

2021-09-10 13:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76346).

2021-09-10 13:42 UTC, kzhekov commented
@qsm-odoo Pinging you for a quick review of the fix on the classList assignment issue. Could you take a look and tell me if this is the expected fix? As far as I can tell, the behaviour is exactly the same as before.

2021-09-10 15:20 UTC, qsm-odoo requested changes
Perfect diff and commit message :+1: Target the version where this was introduced though (14.5). Just retarget the PR here after rebasing + push forcing it (which you can only do when the PR is in draft, so if it was not, you should put it back to draft first to avoid pinging everyone). You can also mention the commit which introduced that file in the commit message, always better to keep track. You can do it with something like this:

```
Assigning a value to an element's [...] This commit fixes [1] which did that multiple times.
[...]

[1]: <link to the commit >
```

2021-09-13 08:50 UTC, qsm-odoo commented
@kzhekov Mention the commit which introduced the wrong classList uses like I explained in my previous review, not really important here but it's never too soon practicing good habits :+1:

2021-09-13 08:52 UTC, kzhekov commented
> @kzhekov Mention the commit which introduced the wrong classList uses like I explained in my previous review, not really important here but it's never too soon practicing good habits
Hi! I think I did so with the [these changes] link, but maybe I didn't do it correctly. If you click on "these changes", does it not lead you to the commit that introduced them?

2021-09-14 14:30 UTC, qsm-odoo requested changes
@kzhekov The commit you mention is not the one that was actually merged :grimacing:

2021-09-14 14:52 UTC, kzhekov commented
> @kzhekov The commit you mention is not the one that was actually merged

Indeed, my bad - should be fixed now I think.

2021-09-15 08:36 UTC, qsm-odoo approved these changes
@robodoo r+

2021-09-15 11:09 UTC, closed without merging