[FIX] project: align the div to the right in the activity view
odoo/odoo pull request #76681
Opened 2021-09-16 12:36 UTC by hap-odoo

The purpose of this commit is to display the project name and task
to the right of the div in the activity view.

before this commit, the project name and task displays next to
the many2many_tags div in the activity view.

TaskID-2646204

2021-09-16 12:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76681).

2021-10-04 14:52 UTC, xavierbol requested changes
Thanks for your work, I have made some comments and suggestions. 🙂

2021-10-04 14:52 UTC, xavierbol commented on addons/project/views/project_views.xml
> +                            <div class="ml-auto w-50">
We could align the text to the right for this div.
```suggestion
                            <div class="text-right">
```

2021-10-05 05:56 UTC, mba-odoo commented on addons/project/views/project_views.xml
>                          <div t-name="activity-box">
@xavierbol  Done!

2021-10-05 16:23 UTC, xavierbol approved these changes
LGTM, thanks ! 🙂

2021-10-21 06:48 UTC, IT-Ideas approved these changes
LGTM Thanks! 🙂

2021-10-21 07:19 UTC, IT-Ideas approved these changes
LGTM Thanks 🙂 !

2021-10-21 07:38 UTC, IT-Ideas commented
@robodoo r+

2021-10-21 08:52 UTC, closed without merging