[FIX] mail: avoid exception when creating channel
odoo/odoo pull request #76830
Opened 2021-09-20 11:44 UTC by phenix-factory

When a user without an email partner try to create a channel, an exception is
raison because he has no email.
This exception should not happen when creating a new channel.

task-2641660

2021-09-20 11:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76830).

2021-09-20 14:18 UTC, seb-odoo reviewed
Wrong word in commit: "exception is raison"

Also it would be nice to add a small test to cover it.

2021-09-22 19:28 UTC, seb-odoo requested changes

2021-09-23 07:22 UTC, phenix-factory commented on addons/mail/models/mail_channel.py
> +    def _message_compute_author(self, author_id=None, email_from=None, raise_exception=False):
I don't really understand the logic here. Category is obvious, but close to message_post ?

2021-09-23 10:08 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +    def _message_compute_author(self, author_id=None, email_from=None, raise_exception=False):
`_message_compute_author` is directly linked to `message_post` so it should be near it in the code, not near channel creation method

2021-09-23 16:26 UTC, seb-odoo approved these changes
@robodoo r+

2021-09-23 22:54 UTC, robodoo commented
Staging failed: ci/runbot (view more at http://runbot.odoo.com/runbot/build/10140201)

2021-09-24 08:05 UTC, alexkuhn commented
@robodoo retry

2021-09-24 10:54 UTC, closed without merging