[FIX] mail: avoid unwanted scroll bar jump with mulitline message
odoo/odoo pull request #76944
Opened 2021-09-22 09:34 UTC by phenix-factory

Before this commit, when the what window composer was multi line, the message
list scroll bar jumped over the content.
This PR prevent this jump by listening to resize event and restore the chat
window scroll position if needed.

task-2377824

2021-09-22 09:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/76944).

2021-09-22 13:39 UTC, seb-odoo requested changes

2021-09-22 13:39 UTC, seb-odoo commented on addons/mail/static/src/models/thread_view/thread_viewer.js
> +        }),
make `asc` the default value and avoid repeating it on every test on which it doesn't actually matter

2021-09-22 13:39 UTC, seb-odoo commented on addons/mail/static/src/models/thread_view/thread_view.js
> +        clientHeight: attr(),
check alpahbetical for all fields

2021-09-22 13:41 UTC, seb-odoo commented on addons/mail/static/src/models/thread_view/thread_viewer.js
> +        }),
This will fix runbot too because the issue is missing field

2021-09-22 18:03 UTC, seb-odoo reviewed
The diff itself is ok now, and it definitely resolves the composer new line issue, but I still have concerns about changing this part of the code. We'll need to think a bit more about it to be sure.

If it also resolved the `scrollHeight` issue (see comment below) then it would surely be a good trade-off, but as it's not the case the decision to go with the diff is not easy.

2021-10-28 09:56 UTC, alexkuhn reviewed
Typo in commit/PR title (multi-line)

2022-09-20 08:30 UTC, closed without merging