[FIX] website_crm_partner_assign: display valid partners on forward t…
odoo/odoo pull request #77008
Opened 2021-09-22 19:11 UTC by sswapnesh

…o partner

Steps:
Lead --> Assigned Partner --->Send Email

Issue: 
It will open Wizard which is displaying all Partners while
it should display partner with valid `grade_id`.

Fix:
Now we are displaying partner having `grade_id`.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-22 19:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77008).

2022-07-29 18:47 UTC, rdeodoo requested changes
Just passing by, cleaning a bit the `rd-website` review resquests.
No task? Probably correct, didn't check but maybe involve a PO to validate it and merge it?
In master tho, not something we want to change/break in stable IMHO.

Just left a nitpicking remark.

2022-07-29 18:47 UTC, rdeodoo commented on addons/website_crm_partner_assign/wizard/crm_forward_to_partner_view.xml
> +                                   domain="[('grade_id','!=',False)]" />
```suggestion
                                   domain="[('grade_id', '!=', False)]" />
```

2022-08-03 13:47 UTC, sswapnesh commented
@rdeodoo 

> No task?

Nope, I am contributer not an odoo employee  😃

2022-08-04 07:43 UTC, rdeodoo commented
Whoops :D 
I was a bit quick the other day when I sorted all the PR where there was a `RD-Website` review request.
I'll see to make this one move forward

2022-08-04 07:46 UTC, rdeodoo commented
@tde-banana-odoo That's probably something for your interest :+1:

2024-04-16 08:58 UTC, C3POdoo commented
Dear @sswapnesh,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 08:58 UTC, closed without merging