[FIX] website: properly handle removing the active item of a carousel
odoo/odoo pull request #77033
Opened 2021-09-23 10:02 UTC by tdecaluwe

A bug currently makes the carousel snippet collapse/disappear when its active contents are removed. This happens because after the removal, the carousel no longer has an active item.

The solution simply consists of activating another item in the carousel or possibly removing the carousel entirely when the last item is being removed.

task-2506165

2021-09-23 10:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77033).

2021-09-23 10:43 UTC, tdecaluwe commented on addons/website/static/src/js/content/snippets.animation.js
> +            this.destroy();
@qsm-odoo Is calling `destroy` necessary before removing the snippet from the DOM? (If yes, it should probably be moved in the async call...)

2021-10-11 10:10 UTC, tdecaluwe commented
@bso-odoo Even if it is already finished in 12.0?

2021-10-11 13:34 UTC, qsm-odoo requested changes

2021-10-25 15:39 UTC, qsm-odoo requested changes

2021-11-03 17:10 UTC, qsm-odoo approved these changes
@tdecaluwe Please try finishing this work entirely before asking for other tasks:

- The commit message was not updated and explained something which was not true anymore
- The app mentioned were not the right ones
- I don't see the PR for master you had to do like we talked about so that the user can choose the number of columns he wants inside (is it somewhere and I missed it maybe? or am I remembering it wrong and someone else is taking care of it?)

I made the changes for the commit message so this one can be merged:

@robodoo r+

2021-11-03 18:22 UTC, closed without merging