[IMP] l10n_vn: Change external ID for avoid confusion
odoo/odoo pull request #77073
Opened 2021-09-23 14:25 UTC by tranngocson1996

Description of the issue/feature this PR addresses:
Because of this id `chart8111` for `account 811`, I was perplexed. I created access to this id `chart811` for find `account 811` out of habit, but I couldn't find it.

Desired behavior after PR is merged:
To make code easier, I believe it is not difficult to alter this external id.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-23 14:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77073).

2021-09-30 15:28 UTC, qdp-odoo commented
Thank you for the contribution! :+1: 

can you squash the 2 commits into a single one and set the following commit message: 

> [FIX] l10n_vn: Change xml ID to avoid confusion
> 
> * XML-ID 'chart8111' was set for account 811, which didn't really make sense. Changed to 'chart811'
> * Also adapted the translation files accordingly

2021-09-30 18:56 UTC, qdp-odoo requested changes
see above comment

2021-10-01 01:10 UTC, tranngocson1996 commented
> see above comment

@qdp-odoo Thank you for your interest in my PR. I've tweaked it to your preferences.

2021-10-18 15:06 UTC, closed without merging