[FIX] industry_fsm: fix locale for start hour displayed on the kanban
odoo/odoo pull request #77134
Opened 2021-09-24 09:14 UTC by phwa-odoo

Description of the issue/feature this PR addresses:
In the kanban view of industry_fsm, the start time is hardcoded in 12 hours format.
The start time should be based on the user's time format

Current behavior before PR:
The start time is displayed in 12 hours format

Desired behavior after PR is merged:
The start time is displayed in 12 or 24 hours format according to the user's preferences.
The date is displayed according to user's preferences

task-2634340

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-24 09:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77134).

2021-09-27 08:08 UTC, xavierbol requested changes
Thanks for your job, you can do the same in one line. ^^
I have made some comments.

I hope everything it is clear. 🙂

2021-09-27 16:11 UTC, phwa-odoo commented on addons/project/static/src/js/project_kanban.js
> +let ProjectTaskKanbanRenderer = KanbanRenderer.extend({
Done, thanks :)

2021-09-27 16:11 UTC, phwa-odoo commented on addons/project/static/src/js/project_kanban.js
> +}
Done, thanks :)

2021-10-01 10:29 UTC, closed without merging