[IMP] account: Align the label of fields Narration in both
odoo/odoo pull request #77336
Opened 2021-09-28 13:21 UTC by kir-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-28 13:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77336).

2021-09-29 09:09 UTC, FlorianGilbert requested changes
Hello,
Could you please improve your commit message ? 
Put the task ID in the commit message and correct the typo. 

Thank you

2021-09-29 09:52 UTC, kir-odoo commented
@FlorianGilbert I have changed commit message, please check it out. 

Thank you

2021-09-29 09:58 UTC, FlorianGilbert commented
> @FlorianGilbert I have changed commit message, please check it out.
> 
> Thank you

Why didn't do the suggested changes ?

2021-09-29 10:16 UTC, kir-odoo commented
@FlorianGilbert Now i have done also suggested changes can you please check it.

Thank you

2021-09-29 13:06 UTC, FlorianGilbert approved these changes
@robodoo r+

2021-09-29 18:05 UTC, closed without merging