[FIX] website_forum: fix forum back button visibility
odoo/odoo pull request #77458
Opened 2021-09-30 06:58 UTC by hap-odoo

purpose of this commit is to remove the back button of the forum
page when the user opens the question from helpdesk ticket

before this commit, the back button displays on the forum page
when the user opens the question from the helpdesk ticket.

Task-2602604
related #21219

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-30 06:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77458).

2021-10-18 07:42 UTC, xavierbol reviewed
We could create a public widget to use `window.history.back()` when the referrer is not empty, for instance.
What do you think ? 🙂

2021-10-18 12:03 UTC, xavierbol commented
> > We could create a public widget to use `window.history.back()` when the referrer is not empty, for instance. What do you think ? slightly_smiling_face
> 
> @xavierbol we already did it using `window.history.back()` directly but tle has suggested to avoid the javascript injection. see: [#75585 (comment)](https://github.com/odoo/odoo/pull/75585#discussion_r714596095)
> 
> Thanks

Yeah, I know but the idea is to replace the a tag by a widget and when we will click on this widget, we will use the `window.history.back()`.

In your initial solution, you don't have made a widget, in fact, you inject the JS in `href` attribute of the `a` tag to use the `window.history.back()`. Apparently, it is a shortcut to do this:
```xml
<!-- source: https://stackoverflow.com/questions/7755088/what-does-href-expression-a-href-javascript-a-do/7755143#7755143 -->
<a href="" onclick="window.history.back(); return false;"
```
But this solution is not really use in Odoo (I saw only one occurrence). I think your initial solution is right but not really elegant.

To avoid having this solution everywhere in the code. I think we could do a widget to use the `window.history.back()` when the user clicks on this button/widget. Moreover, with this widget, we will be able to use it in another portal view and it will be more readable than `href="javascript: window.history.back()"`. :slight_smile:

2021-10-19 14:27 UTC, xavierbol reviewed
Thanks for the changes, now the `back_button_url` is only used as a boolean value, we could set a boolean value in this variable instead of the `url` in the controller of this template. 😇

2021-11-03 07:42 UTC, IT-Ideas approved these changes
LGTM 🙂 
Waiting for @qsm-odoo review before launch 🙂

2021-11-03 11:22 UTC, qsm-odoo requested changes
Strange we did not do it like that before... makes me wonder if there could be a reason.  @rdeodoo This seems good to you?

Note: commit message: task-XXX instead of Task-XXX per our convention :+1:

2021-11-03 11:22 UTC, qsm-odoo commented on addons/website_forum/static/src/js/website_forum.js
> +    //--------------------------------------------------------------------------
Should fill 80 chars

2021-11-03 11:22 UTC, qsm-odoo commented on addons/website_forum/static/src/js/website_forum.js
> +    */
Misindented

2021-11-03 11:22 UTC, qsm-odoo commented on addons/website_forum/static/src/js/website_forum.js
> +        'click': '_onClickBackButton',
`_onBackButtonClick`, verb/event name at the end

2021-11-03 11:22 UTC, qsm-odoo commented on addons/website_forum/static/src/js/website_forum.js
> +publicWidget.registry.websiteForumBackButton = publicWidget.Widget.extend({
Uppercase letter to start the public widget name, that's a class name

2021-11-04 10:32 UTC, rdeodoo commented
> Strange we did not do it like that before... makes me wonder if there could be a reason. @rdeodoo This seems good to you?

AFAIK, the back button was [developed](https://github.com/odoo/odoo/pull/45470#issuecomment-590338524) for the frontend, which obviously does not fit this backend flow.

2021-11-04 10:33 UTC, rdeodoo approved these changes

2021-11-04 10:41 UTC, IT-Ideas commented
@robodoo r+

2021-11-04 11:55 UTC, closed without merging