[IMP] sign: adds green savings report
odoo/odoo pull request #77471
Opened 2021-09-30 08:42 UTC by leonardopavanrocha

When printing general reports without specified record IDs, an indexError occurs. This PR adds a check to prevent this indexError from occuring and allows the printing to continue.

task-2552160

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-30 08:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77471).

2021-09-30 09:08 UTC, xmo-odoo requested changes
I don't understand what the title of the commit / PR is supposed to mean. What is "green savings" and what relationship does it have to an IndexError?

Is it the report you were adding when you found out this possible issue? Either way it needs to be fixed, this has no actual link to the commit.

2021-09-30 09:08 UTC, xmo-odoo commented on addons/web/controllers/main.py
> +                    data = dict(url_decode(url.split('?')[1]).items()) if len(url.split('?')) > 1 else {}  # decoding the args represented in JSON
Use `url_parse` instead, this way you can just use `url_parse(url).decode_query()`.

And the result can just be used as-is: [`url_decode`](https://werkzeug.palletsprojects.com/en/1.0.x/urls/#werkzeug.urls.url_decode) returns [a `MultiDict`](https://werkzeug.palletsprojects.com/en/1.0.x/datastructures/#werkzeug.datastructures.MultiDict) which can be used as-is, or alternatively we can pass `cls=dict` to ensure we get a `dict` out (e.g. avoid possible oddities with respect to `context`).

2021-09-30 11:36 UTC, xmo-odoo approved these changes
:+1:

2021-10-01 06:55 UTC, arj-odoo commented
@robodoo r+

2021-10-01 07:00 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#2694 not ready. Linked PRs are not staged until all of them are ready.

2021-10-01 12:40 UTC, closed without merging