[FIX] Expense is refused when account move is cancelled
odoo/odoo pull request #77482
Opened 2021-09-30 09:53 UTC by fdamhaut

Description of the issue/feature this PR addresses:

When an expense was accepted and then the account move related to the expense was reset to draft/cancelled, the expense's state stayed as payed.

Current behavior before PR:\

The expense's state stayed as payed.

Desired behavior after PR is merged:

 Change the expense's state to refused with the reason 'Payment Cancelled'.

opw-2559225

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-09-30 09:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77482).

2021-09-30 11:23 UTC, kba-odoo approved these changes
LGTM

PS: the commit title doesn't start with the application name 🙊

2021-10-01 13:39 UTC, fdamhaut commented
Updated commit name

2021-10-01 16:00 UTC, agr-odoo requested changes

2021-10-04 08:17 UTC, fdamhaut commented on addons/hr_expense/models/account_move.py
> +from odoo import api, fields, models
:ok_hand:

2021-10-04 08:18 UTC, fdamhaut commented on addons/hr_expense/models/account_move.py
> +                l.expense_id.refuse_expense(reason="Payment Cancelled")
:ok_hand:

2021-10-04 09:39 UTC, agr-odoo commented
Looks good
robodoo r+

2021-10-04 10:34 UTC, closed without merging