[IMP] website: add ability to make mega menu transparent
odoo/odoo pull request #77871
Opened 2021-10-05 14:05 UTC by Guillaume-gdi

Allows the user to put transparency in the background of a mega menu
Moreover, by default, the mega menu is the same color as the nav bar
**Task 2623335**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-10-05 14:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/77871).

2021-10-08 08:32 UTC, qsm-odoo requested changes
In fact, we'll do this: merge the default color as a fix for 15.0 (as right now, if users have a menu not using the first color preset, then their default mega menu may appear with unreadable text) and merge the transparent change in master (for 15.1) but it will need a migration script so that old mega menus are correctly migrated.

So keep this PR for the transparent change and the related migration script and create a new PR for 15.0 for the fix, thank you :+1:

2021-10-15 10:35 UTC, bvr-odoo approved these changes

2021-11-09 12:30 UTC, bso-odoo commented
In understand it has to be possible to make the mega menu transparent if needed, but should it be the default value ?
It currently is a bit unreadable by default:
![image](https://user-images.githubusercontent.com/71644421/140924286-f8591c0a-9218-4847-985a-61179bb7d641.png)
Maybe the default mega menu should be something like `o_cc1`, @pierre-pde what do you think ?

2021-11-09 12:59 UTC, Guillaume-gdi commented
> In understand it has to be possible to make the mega menu transparent if needed, but should it be the default value ? It currently [in this PR] is a bit unreadable by default: ![image](https://user-images.githubusercontent.com/71644421/140924286-f8591c0a-9218-4847-985a-61179bb7d641.png) Maybe the default mega menu should be something like `o_cc1`, @pierre-pde what do you think ?

https://github.com/odoo/odoo/pull/79094

2021-11-09 13:03 UTC, bso-odoo commented
> > In understand it has to be possible to make the mega menu transparent if needed, but should it be the default value ? It currently [in this PR] is a bit unreadable by default: ![image](https://user-images.githubusercontent.com/71644421/140924286-f8591c0a-9218-4847-985a-61179bb7d641.png) Maybe the default mega menu should be something like `o_cc1`, @pierre-pde what do you think ?
> 
> #79094

Indeed, rebasing solved the problem by including the fix that was done on 15.0.

2021-11-10 10:24 UTC, qsm-odoo commented
@bso-odoo Note: the point of working side by side one day a week is avoiding pinging people on GitHub, then waiting, then re-pinging, etc ... for conversations that could take 3 seconds in person (here @Guillaume-gdi who was working with you had the answer, he worked on it) :wink: I received 3 mails about this conversation (I have 100 unread right now), it's not the worse but that's the kind of stuff I want to reduce :+1: 

Other note: @Guillaume-gdi mentioning the commit that was merged in 15.0 in this PR's commit would also be a good idea, that way the question would not have existed in the first place :+1: Also when you have a master PR which depends on stable fixes, try to rebase the master one when the stable changes are merged and forward-ported :+1:

2021-11-29 13:07 UTC, qsm-odoo approved these changes
I reviewed the commit message:
- Finish _sentences_ with a point (instead of each line mid-sentence :shrug:)
- Mention the 15.0 _merged commit_ instead of PR
- Not mention the upgrade PR as it done automatically with an unified format accross all PR

@robodoo r+

2021-11-29 14:00 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#2929 not ready. Linked PRs are not staged until all of them are ready.

2021-11-30 17:43 UTC, qsm-odoo commented
@robodoo r-

We'll wait for the 15.1 freeze and merge this in master for 15.2 as the migration script requires some more fine-tuning.

2021-12-03 15:17 UTC, qsm-odoo commented
@Guillaume-gdi ... you push-forced the branch over my push-force restoring your bad commit message with point in the middle of sentences. Can you restore the commit message I made before my last r+? Thank you.

2021-12-27 14:15 UTC, qsm-odoo approved these changes
@robodoo r+

2021-12-27 15:47 UTC, closed without merging