[IMP] l10n_ar: total amount in letters for MiPyMEs
odoo/odoo pull request #78314
Opened 2021-10-13 13:57 UTC by Bruno-Zanotti

> l10n_ar task: 647

**Description of the issue/feature this PR addresses:**

According to the Argentinean law N° 27440, it is required for MiPyMEs
document types to show in the report the total amount in letters.

Do not FW-port.
PR for 14+: https://github.com/odoo/odoo/pull/79228

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-01 19:08 UTC, vbe-odoo commented
@Bruno-Zanotti LGTM this is ready for technical review/merge @jco-odoo
Thanks.

2021-11-25 13:00 UTC, jco-odoo commented
@fw-bot ignore

2021-11-25 13:01 UTC, jco-odoo requested changes

2021-11-25 15:55 UTC, jco-odoo commented
@robodoo r+

2021-11-25 16:40 UTC, closed without merging