[IMP] packaging: windows display version and rpm packaging
odoo/odoo pull request #78386
Opened 2021-10-14 13:54 UTC by d-fence

2021-10-14 14:45 UTC, Julien00859 approved these changes

2021-10-14 14:55 UTC, Julien00859 commented
Also, you seemed interested by `textwrap.dedent`

2021-10-15 13:14 UTC, xmo-odoo requested changes

2021-10-15 21:03 UTC, d-fence commented
robodoo rebase-ff

2021-10-15 23:28 UTC, closed without merging