[FIX] mail, web: properly add items to the systray
odoo/odoo pull request #78572
Opened 2021-10-18 14:55 UTC by oomsveta

This commit intends to fix two strange bugs encountered while trying to push a new component into the systray menu:
- MessagingMenuWidget and RtcActivityNoticeWidget were removing their parent node via DOM manipulations when attached in the DOM. This caused a crash when adding other items to the systray menu since the deleted nodes were actually managed by OWL.
- The t-foreach directive in the navbar used indexes as the t-key, which led mapping items subsequently added to wrong templates.

Previous PR: https://github.com/odoo/odoo/pull/78022

2021-10-18 15:23 UTC, sdegueldre requested changes

2021-10-19 09:29 UTC, alexkuhn reviewed
Code looks good to me.

2021-10-20 10:10 UTC, seb-odoo requested changes

2021-10-20 12:21 UTC, seb-odoo approved these changes
@robodoo r+

2021-10-20 14:48 UTC, robodoo commented
Staging failed: ci/runbot on ba9c202d0b79fbab1eca821e0fefe0e304002179 (view more at http://runbot.odoo.com/runbot/build/10639081)

2021-10-21 10:54 UTC, seb-odoo commented
@robodoo r+

2021-10-21 10:54 UTC, robodoo commented
I'm sorry, @seb-odoo. Retry makes no sense when the PR is not in error.

2021-10-21 16:00 UTC, closed without merging