[FIX] account: refund when duplicating payment
odoo/odoo pull request #78593
Opened 2021-10-19 06:34 UTC by guva-odoo

Steps to reproduce:

- On bank journal set the outstanding payments accounts and the
  outstanding receipts accounts, respectively to 101403 and
  101402
- In Accounting > Configuration > Settings > Default Accounts,
  let the two outstanding accounts empty.
- Customer > payment > create a payment : payment type Receive,
  amount 5 for example. Save it.
- Duplicate the payment and set the new one to payment type Send.
- Click on Save.

Issue

Got an UserError "Cannot create unbalanced journal entry"

Before the fix, when calling account_payment_seek_for_lines(), we
didn't check for the default account of the journal.

opw-2620046

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-10-19 07:44 UTC, guva-odoo commented
@fw-bot up to master

2021-10-20 09:03 UTC, vin-odoo requested changes

2021-10-21 06:47 UTC, vin-odoo approved these changes

2021-10-21 09:36 UTC, smetl commented
@robodoo r+

2021-10-21 11:13 UTC, closed without merging