[IMP] project: private task visibility for users
odoo/odoo pull request #78601
Opened 2021-10-19 08:58 UTC by ibo-odoo

**PURPOSE**

In project, private tasks (with no project) are visible to other users even if
they have project admin rights.

**SPECIFICATION**

Private tasks will not be visible to other users even if they have project admin
rights.

**Task**-2656512

2021-10-19 08:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/78601).

2021-10-22 13:12 UTC, xavierbol requested changes
Thanks for your work, I have made a suggestion. 🙂

2021-10-25 15:18 UTC, xavierbol reviewed
Thanks for the changes! 🙂 
Can you change the name of the rule to fit with the domain ? 🙂 
After that, it will be good for me.

2021-10-29 13:12 UTC, IT-Ideas approved these changes
LGTM thanks :)

2021-10-29 14:08 UTC, closed without merging