[IMP]  account: track lock dates changes
odoo/odoo pull request #78730
Opened 2021-10-21 06:45 UTC by jbw-odoo

Allow log date changes tracking by adding chatter on company and tracking lock date fields.

Task: 2651834
https://github.com/odoo/enterprise/pull/22479

2021-10-21 06:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/78730).

2021-11-10 10:58 UTC, smetl requested changes

2021-11-10 10:58 UTC, smetl commented on addons/account/models/company.py
> +        " date. Use it for period locking inside an open fiscal year, for example.")
plz indent:
```
period_lock_date = fields.Date(
    string="Journals Entries Lock Date",
    tracking=True,
    help="Only users with the 'Adviser' role can edit accounts prior to and inclusive of this "
         "date. Use it for period locking inside an open fiscal year, for example.",
)
```

2021-11-10 10:58 UTC, smetl commented on addons/account/models/company.py
> +    _inherit = ["res.company", "mail.thread"]
I don't think this should be added by the `account` module. To be discussed

2021-11-15 14:24 UTC, smetl commented on addons/account/models/company.py
> +    _inherit = ["res.company", "mail.thread"]
OK let's keep that on the account module

2021-11-16 15:03 UTC, jbw-odoo commented on addons/account/models/company.py
> +        " date. Use it for period locking inside an open fiscal year, for example.")
done

2021-11-18 13:20 UTC, smetl approved these changes
@robodoo r+

2021-11-18 18:01 UTC, robodoo commented
Staging failed: ci/runbot on 35cb5712cbce666f50ecfcc8609951f9da59cdab (view more at http://runbot.odoo.com/runbot/build/11121154)

2021-11-18 18:54 UTC, smetl commented
@robodoo retry

2021-11-18 19:57 UTC, robodoo commented
Staging failed: ci/runbot on 9268b0aea24ae44ecd1b3bba29ee4f02e65513cf (view more at http://runbot.odoo.com/runbot/build/11121648)

2021-11-19 08:45 UTC, smetl commented
@jbw-odoo The error seems related to your PR after all... can you have a look plz?

2021-11-19 08:49 UTC, jbw-odoo commented
> @jbw-odoo The error seems related to your PR after all... can you have a look plz?

will do

2021-11-23 14:45 UTC, jbw-odoo commented
added enterprise PR https://github.com/odoo/enterprise/pull/22479

2021-11-24 07:56 UTC, smetl commented
@robodoo retry

2021-11-24 07:57 UTC, robodoo commented
I'm sorry, @smetl. Retry makes no sense when the PR is not in error.

2021-11-24 12:02 UTC, jbw-odoo commented
> @robodoo retry

Maybe need to r+ ?

2021-11-25 09:09 UTC, smetl commented
@robodoo r+

2021-11-25 10:00 UTC, closed without merging