Master services generic imp 2.0 kpt
odoo/odoo pull request #78973
Opened 2021-10-26 06:58 UTC by kpt-odoo

project:

- Add analytic tags field in project. Those tags are passed to invoice lines generated from the
project's ​SO lines.
- The field name should be 'analytic tags' in task.
- In list view of task add rating field, the field should optional and hidden by default.

rating:

- Add rating_last_text  field in the rating mixin.

closes #78973
TaskID: 2667754

2021-11-23 14:16 UTC, xavierbol requested changes
Thanks for your work, I have made some suggestions and comments. 🙂

2021-11-23 14:16 UTC, xavierbol commented on addons/sale_project/models/sale_order.py
> +                values['analytic_tag_ids'] += [Command.link(tag_id.id) for tag_id in tag_ids]
We could refactor this to have less lines by doing this:
```suggestion
        if self.task_id.analytic_tag_ids or self.task_id.project_id.analytic_tag_ids:
            values['analytic_tag_ids'] += [Command.link(tag_id.id) for tag_id in self.task_id.analytic_tag_ids | self.task_id.project_id.analytic_tag_ids]
        elif self.is_service and not self.is_expense:
            tag_ids = self.env['account.analytic.tag'].search([
                '|', ('task_ids.sale_line_id', '=', self.id), ('project_ids.sale_line_id', '=', self.id)
            ])
            values['analytic_tag_ids'] += [Command.link(tag_id.id) for tag_id in tag_ids]
```

What do you think ? 🤔

2021-11-23 14:29 UTC, tde-banana-odoo reviewed
Being pinged for rating stuff, saying coucou.

2021-11-23 14:29 UTC, tde-banana-odoo commented on addons/rating/models/rating_mixin.py
> +    rating_last_text = fields.Selection(related='rating_ids.rating_text', string='Rating', groups='base.group_user', store=True)
In my opinion, this adds queries, a column on a lot of models and a juge migration script for about nothing valuable. I don't think we want to store "top" on all records inheriting from rating.mixin. As @xavierbol says, you may use rating_last_value . And maybe define a computed field (not stored) based on it, if you want to display things (will not be groupable but that more a filter issue, you may define filters manually that do the job).

2021-11-23 14:29 UTC, tde-banana-odoo commented on addons/project/views/project_views.xml
> +                    <field name="rating_last_text" string="Rating" decoration-danger="rating_last_text == 'ko'"
Or use a not-stored computed field, it should work if you really want some text :) . That way we don't store anything and computation is simple anyway.

2021-11-25 08:02 UTC, xavierbol reviewed
Thanks for the changes, I have made a comment, after that it will look good to me. 🙂

2021-11-25 08:02 UTC, xavierbol commented on addons/rating/models/rating_mixin.py
> +    rating_text = fields.Selection(string="Rating Text", groups='base.group_user', related="rating_ids.rating_text")
I think we select the last rating to get the `rating_text` field, like the others related fields in this mixin. So we could rename it by `rating_last_text`.
```suggestion
    rating_last_text = fields.Selection(string="Rating Text", groups='base.group_user', related="rating_ids.rating_text")
```

2021-11-25 10:32 UTC, kpt-odoo commented
Hi @xavierbol changes are done.
Thanks

2021-11-25 10:34 UTC, xavierbol approved these changes
LGTM, thanks 🙂

2021-12-06 10:17 UTC, IT-Ideas approved these changes
LGTM Thanks 🙂 
Can you remove the last commit?
Thanks

2021-12-06 10:17 UTC, IT-Ideas commented on addons/project/models/project.py
> +
Why not using it in the default_get?

2021-12-06 15:15 UTC, IT-Ideas commented
Hello @tde-banana-odoo 🙂 
Are the changes in rating ok for you?

Thanks!

2021-12-13 11:48 UTC, IT-Ideas commented
@robodoo r+

2021-12-13 12:01 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#3031 not ready. Linked PRs are not staged until all of them are ready.

2021-12-13 12:01 UTC, robodoo commented
Because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2021-12-13 12:10 UTC, IT-Ideas commented
@robodoo rebase-ff

2021-12-13 12:11 UTC, robodoo commented
Merge method set to rebase and fast-forward

2021-12-16 09:00 UTC, closed without merging