[IMP] l10n_ch: skip adding reports to invoice email
odoo/odoo pull request #79318
Opened 2021-11-03 11:24 UTC by TDu

When sending an invoice by email the reports for ISR and QR are
automatically added if it is possible.

But for some systems, those reports are already joined to the base
report linked to the template and adding them is redudant.

This improvement adds the option to skip the addition of those reports
through a context variable.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-03 11:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/79318).

2021-11-04 16:56 UTC, oco-odoo commented
> But for some systems, those reports are already joined to the base report linked to the template and adding them is redudant.

What do you mean by that exactly ? When and how does it happen ?

2022-02-11 16:05 UTC, i-vyshnevska commented
> 
> What do you mean by that exactly ? When and how does it happen ?

I suppose we are talking about oca implementation when we attach all possible invoices to main invoice https://github.com/OCA/l10n-switzerland/tree/14.0/l10n_ch_invoice_reports

2022-03-03 10:17 UTC, oco-odoo requested changes
One small thing, then we can merge

2022-03-11 09:02 UTC, TDu commented on addons/l10n_ch/models/mail_template.py
> +                    if record.partner_bank_id._eligible_for_qr_code('ch_qr', record.partner_id, record.currency_id):
Thanks for your review, I changed the implementation

2022-03-18 09:21 UTC, oco-odoo commented
@TDu I assume your forced push from yesterday was an attempt to rebase the branch because of the ci/upgrade_enterprise error, but it still fails (which is weird, as it seems totally unrelated to your diff). Are you sure you did it properly ? If it wasn't a rebase, you should make one :)

2022-03-18 09:54 UTC, TDu commented
@oco-odoo Actually, I did a typo on the refactor that lead to an error :sob: 
And when fixing it, I just squashed the commit and push forced.
But I did not rebase.

2022-03-18 10:31 UTC, oco-odoo commented
> @oco-odoo Actually, I did a typo on the refactor that lead to an error sob And when fixing it, I just squashed the commit and push forced. But I did not rebase.

Ok, please rebase then :)

2023-02-20 07:56 UTC, simahawk commented
@oco-odoo ping

2023-02-23 10:35 UTC, oco-odoo commented
@TDu Sorry but there are still conflicts, you need to rebase again :/ Ping me when you do ; this way we're sure I won't muss the notification

2023-02-28 07:35 UTC, TDu commented
@oco-odoo  I fixed the conflict, could you please pass by again. Thank you.

2023-03-08 12:57 UTC, oco-odoo approved these changes
@robodoo r+

2023-03-08 14:41 UTC, closed without merging