[FIX] accouting: fix 'unpaid invoice' filter on main dashboard
odoo/odoo pull request #79462
Opened 2021-11-08 07:26 UTC by anhe-odoo

### Expected Behaviour
When clicking on the "XX Unpaid Invoices" link on the main dashboard of the accounting app, we should get to a list view with only unpaid (and partially paid) invoices

### Observed Behaviour
When cliking on the link, we get all the invoices, even the paid ones.

### Reproducibility
This bug can be reproduced following these steps :
1. Create some invoices
2. Make sure some of them are paid and some are not
3. Go to the main dashboard
4. Click on the "XX Unpaid Invoices" link in the "Customer Invoices" app

### Problem Root Cause
The problem comes from a change in the filter name from V14 to V15 ("unpaid" category has been replaced by "open").

### Related issues
- opw-2681099

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-08 07:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/79462).

2021-11-08 08:58 UTC, oco-odoo requested changes
I find a few other occurences of search_default_unpaid when searching for it in the whole code. Shouldn't they be fixed as well, while we're at it?

2021-11-08 09:08 UTC, anhe-odoo commented
> I find a few other occurences of search_default_unpaid when searching for it in the whole code. Shouldn't they be fixed as well, while we're at it?

Yes, probably (if you mean the one in account/models/partner.py, line 520. Else, I couldn't find any other occurence). But as it wasn't directly related to the bug I was assigned to, I haven't changed it. Anyway, you're right, I'll update my commit :)

2021-11-09 09:16 UTC, oco-odoo commented
>  and the enterprise part can't be updated here

Why? Just make a second pull request in enterprise with the same branch name as this one, assign me as reviewer, and we'll merge them together ;) Otherwise, we're letting in the code a bug we know about; I think we receive enough tickets without intentionally saving bugs for later, don't you? :p

2021-11-09 10:53 UTC, anhe-odoo commented
> > and the enterprise part can't be updated here
> 
> Why? Just make a second pull request in enterprise with the same branch name as this one, assign me as reviewer, and we'll merge them together ;) Otherwise, we're letting in the code a bug we know about; I think we receive enough tickets without intentionally saving bugs for later, don't you? :p

Here it is : https://github.com/odoo/enterprise/pull/22188
Sorry, I'm quite new @Odoo and I wasn't aware it was a common practice to make both a PR on entreprise and community versions. But you're totally right, it's clearly stupid to keep a bug when we know it :D

2021-11-10 13:36 UTC, oco-odoo commented
@anhe-odoo No problem, we all had to learn at some point :) Welcome aboard !

2021-11-10 13:37 UTC, oco-odoo approved these changes
@robodoo r+

2021-11-10 15:25 UTC, closed without merging