[FIX] project - Fixed the issue of view not loading upon click of "Task in Recurrance" button
odoo/odoo pull request #79559
Opened 2021-11-09 12:51 UTC by odooaktiv

**Description of the issue/feature this PR addresses:**
When a user clicked on "Task in Recurrance" button it gave him following Warning.
No default view of type 'gantt' could be found !

**Current behavior before PR:**
In the code when the action was returned, there were gantt and map views returned. This views are not present in the XML and hence they do not exist.

**Desired behavior after PR is merged:**
This commit removes the map and gantt view from the action return and hence the view now loads successfully when user clicks on the smart button.

Fixes #79555

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-09 12:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/79559).

2021-11-15 14:04 UTC, IT-Ideas requested changes
Hello @odooaktiv 👋🏼 
Thanks for your Fix 🙂 
I have found other places that will raise the same kind of issue.
Can you adapt your PR accordingly?

As for the enterprise PR, just let me know whether you have the access to the enterprise repo or not. If not I will create the necessary PR.

Thanks!

2021-11-15 15:50 UTC, closed without merging

2021-11-16 05:07 UTC, odooaktiv commented
@IT-Ideas Its ok, Thanks for the update. Any idea why #79555 didn't auto-close after the PR is marked as closed?

2021-11-16 07:24 UTC, IT-Ideas commented
Maybe because it is not yet in master as there were conflicts? The master PR has been r+ed this morning. We'll see what happens we merged.