[IMP] product: changed product category field to be translatable
odoo/odoo pull request #79824
Opened 2021-11-16 10:29 UTC by aaj-odoo

Product category name field is made translatable

2021-11-16 10:30 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/79824).

2021-12-01 14:30 UTC, xavierbol approved these changes
LGTM, thanks 🙂

2021-12-03 09:43 UTC, IT-Ideas requested changes

2021-12-03 09:43 UTC, IT-Ideas commented on addons/product/models/product.py
> +    name = fields.Char('Name', index=True, required=True, translate=True)
We can't do this. It has been revert here 322618a69c8870835e0e4ea785b7268a16d14f67. The reason being that a compute store depends on it. More info here #22060

2021-12-03 12:24 UTC, IT-Ideas commented
Closing the PR as we can't set the product.product name translatable.

2021-12-03 12:24 UTC, closed without merging