14.0 fix register wizard las
odoo/odoo pull request #80418
Opened 2021-11-25 16:07 UTC by smetl

[FIX] account: Fix wrong filter on partner banks

[FIX] account: Fix available_partner_bank_ids in register payment wizard

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-25 16:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80418).

2021-11-26 08:34 UTC, newtratip approved these changes

2021-11-26 09:06 UTC, oco-odoo requested changes
Just some comments to add, for clarity. Also, your commit fixing the view is referencing a commit in odoo-dev instead of odoo repo to link the original fix :p

2021-11-26 16:05 UTC, oco-odoo requested changes
Just make your last commit message more explicit, then it's ok for me :)  (once you have applied my previous review as well :p )

2021-12-02 10:11 UTC, oco-odoo requested changes
https://www.youtube.com/watch?v=iUV-onnOsNs

2021-12-02 10:11 UTC, oco-odoo commented on addons/account/models/account_payment.py
> +                    .filtered(lambda x: x.company_id.id in (False, pay.company_id.id))._origin
Bug:

- Create 2 bank accounts A and B for your company, linked to journals J1 and J2
- open the form to create a new account.payment
- make partner_bank_id field visible in the form view (just to see the problem)
- click payment type = 'receive money'
- change journal (from J1 to J2)
- recipient bank account is not recomputed. It's still A, should be B.

(and if you fix it manually and change the partner, B is replaced by A again)

---------------

=> This field should only accept the bank set on the bank journal when receiving money (so, the journal should also be part of the dependencies)

2021-12-02 10:11 UTC, oco-odoo commented on addons/account/wizard/account_payment_register.py
> +                    batch_bank_account = self.env['res.partner.bank'].browse(batch['key_values']['partner_bank_id'])
Bug:
- Create 2 bank accounts A and B for your company, linked to journals J1 and J2
- Create a vendor refund and change the default recipient account (A becomes B)
- Post, click on "register payment"
- The bank account in the wizard is A. It should be B
-----------------------------------------------------------------------------

=> Probably finds its origin around here (not sure)

2021-12-03 10:14 UTC, oco-odoo requested changes

2021-12-07 15:27 UTC, Xavier-Do reviewed
Not sure the fields_view_get is the best way, but here are some quick comments!

2021-12-08 15:59 UTC, oco-odoo approved these changes
@robodoo r+
et bisous

2021-12-08 17:25 UTC, closed without merging