[FIX] sale: Shipping Amount for Online Orders
odoo/odoo pull request #80420
Opened 2021-11-25 16:38 UTC by simongoffin

The price of the shipping method was always the sales price on the product of the delivery method

opw:2646684

2021-11-25 16:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80420).

2021-11-25 16:55 UTC, fmdl commented on addons/sale/data/mail_data.xml
>                      % if object.carrier_id.fixed_price == 0.0:
`if object.amount_delivery == 0.0:`

2021-12-08 09:09 UTC, simongoffin commented
Hello @Feyensv 
Is it ok for you?

2021-12-13 09:36 UTC, Feyensv requested changes
Nope, this is a regression...

`carrier_id` is added in `delivery`, but `amont_delivery` is only present when `website_sale_delivery` is installed...

2024-04-16 08:56 UTC, C3POdoo commented
Dear @simongoffin,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 08:56 UTC, closed without merging