[FIX] base_vat: allow disabling VAT check through context
odoo/odoo pull request #80503
Opened 2021-11-29 09:57 UTC by Yenthe666

Before this fix there is no real way to influence the VAT validation.
This can be problematic though as in some cases external platforms push data to you
on which you don't really have control. If an external software pushes an invalid VAT
and your database has the option 'Verify VAT Numbers' checked on there is no way
for you to bypass this though.
This means that before this commit you have to always run VAT number checks on all data,
no matter if they come through the frontend or backend.

After this commit you can supply a context key 'no_vat_validation' though.
This way you could skip doing VAT number validations on (some) records while still
enforcing this in the UI.
This allows you to have crons/external API's push any VAT number while enforcing full
validation through the UI.

This opens up the best of both worlds.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-11-29 09:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80503).

2021-11-29 10:00 UTC, Yenthe666 commented
To expand a bit I'd like to give a real life sample:
We have a lot of employees who make contacts/sales through the UI. In this case we want to always verify the VAT number entered by the users.
On the other hand, we have external platforms which push contacts data into Odoo. Since this data is entered through customers and automatically pushes through API calls we have no control over the data. In this case we don't want to enforce VAT number validation on all flows though. It would break our pushes (due to the raise) and would make things tricky as we have a LOT of customer data. In this case it is impossible to manage it all manually & we want to override/pass the VAT number checks. This is why this PR was made & I believe it opens the best of both worlds :)

2021-12-02 09:18 UTC, Yenthe666 commented
@oco-odoo any update? This is kinda blocking us a bit :)

2021-12-02 10:37 UTC, oco-odoo requested changes

2021-12-02 10:37 UTC, oco-odoo commented on addons/base_vat/models/res_partner.py
> +            if failed_check and not self.env.context.get('no_vat_validation'):
Rather put it at the beginning of the function, just doing a return if this context key is set. Here, you're still running the check (potentially connecting to a web service) for nothing.

2021-12-02 16:37 UTC, oco-odoo approved these changes
@robodoo r+

2021-12-02 17:44 UTC, closed without merging

2021-12-03 08:41 UTC, Yenthe666 commented
Thank you so much :)