[REF] various: remove usage of html2plaintext
odoo/odoo pull request #80575
Opened 2021-11-30 09:17 UTC by tde-banana-odoo

2021-11-30 09:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80575).

2021-11-30 15:19 UTC, d-fence requested changes
If html2text is not used anymore, it should also be removed from packaging too:
* [requirements.txt](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/requirements.txt#L12)
* [setup.cfg](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/setup.cfg#L18)
* [Debian package](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/debian/control#L31)
* [docker files](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/setup/package.dfdebian#L31) and [fedora one](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/setup/package.dffedora#L24)
* probably [in point_of_sale](https://github.com/odoo/odoo/blob/d8072e57ea6be994aadaf86c1cf4b870b0ae56c9/addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh#L55]) too

2021-12-01 08:33 UTC, tde-banana-odoo commented
@odony FYI

2021-12-07 06:16 UTC, em230418 commented
> [REF] various: remove usage of html2plaintext 

I would call "add usage of html2plaintext", since we are adding it defacto.

2022-02-01 13:14 UTC, closed without merging