[FIX] timesheet_grid: authorize project_manager to update task's project
odoo/odoo pull request #80665
Opened 2021-12-01 10:20 UTC by thcl-odoo

### Expected behavior
Project manager can change task's project of any task including timesheets

### Current behavior
When Project manager with `Timesheets : See own timesheets` permission is updating task's project, an Access Error exception is raised `Only a Timesheets Approver or Manager is allowed to modify a validated entry.`

### Steps to reproduce
*Use demo data to make steps easier*
- Install Project and Timesheets
- Go to Project and select one
- Select any Task
- Edit it and try to change the Project

### Reason
When a user is a project administrator, he can still have basic permissions in Timesheets (`Timesheets : See own timesheets`), which prevents him from modifying the task's project if the task has some validated timesheet

2021-12-01 10:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80665).

2021-12-02 13:45 UTC, IT-Ideas requested changes
Some changes in the tests.

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        project.tasks[0].with_user(second_project_manager).write({
```suggestion
        task_1.with_user(project_manager).write({
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        })
We don't need another project_manager in my opinion, we just want to test that a user having the group `project.group_project_manager` can write on a timesheet.
```suggestion
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +            'user_id': second_project_manager.id,
```suggestion
            'user_id': project_manager.id,
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        project_manager = self.env['res.users'].create({
```suggestion
        '''This test checks that no error is raised when moving a task that contains timesheet to another project.
           This move implying writing on the account.analytic.line.
        '''

        project_manager = self.env['res.users'].create({
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        })
One timesheet is enough for the test 🙂 
```suggestion
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        self.env['account.analytic.line'].create({
```suggestion
        timesheet = self.env['account.analytic.line'].create({
```

2021-12-02 13:45 UTC, IT-Ideas commented on addons/hr_timesheet/tests/test_timesheet.py
> +        self.assertEqual(len(second_project.tasks), 1, 'Second project should have a task')
```suggestion
        self.assertEqual(timesheet.project_id, second_project, 'The project_id of timesheet should be second_project')
        
```

2021-12-02 15:01 UTC, thcl-odoo commented
Hello @IT-Ideas ,

Thanks for the review :slightly_smiling_face: 

I've just pushed the modifications according to your review.

2021-12-02 17:15 UTC, IT-Ideas approved these changes
Hello @thcl-odoo,
LGTM Thanks 🙂 

Don't forget to mention in the opw that a manual action is need on existing databases.

2021-12-02 17:15 UTC, IT-Ideas commented
@robodoo r+

2021-12-02 17:50 UTC, robodoo commented
Unable to stage PR ({"message":"Merge conflict","documentation_url":"https://docs.github.com/rest/reference/repos#merge-a-branch"})

2021-12-06 15:46 UTC, nle-odoo commented
robodoo r+

2021-12-06 16:29 UTC, closed without merging