[FIX] hr_timesheet : Time on task doesn't round
odoo/odoo pull request #80676
Opened 2021-12-01 12:34 UTC by auon-odoo

Steps :
- Install Sales & Timesheets
- Timesheets > Settings > Time Encoding :
	- Min duration : 60 min
	- Rounding up : 15 min
- Create a Project P
- Create a Product S :
	- Product Type : Service
	- Service Invoicing Policy : Timesheets on tasks
	- Service Tracking : Create a task in an existing project
	- Project : P
- Create a Sales Order SO and add S
- SO > 1 Tasks (smart button) as T > Timesheets (tab) > Add a line :
	- Employee : Mitchell Admin
	- Duration : 0

- Timesheets > Start :
	- Time : 1:09
	- Project : P
	- Task : SO:S
- T > Timesheets (tab) : Note Time = 1:15 (Min duration + Roundup)

- T > Start and Stop
- Confirm Time Spent Wizard : Note Duration = 1:00 (Min Duration)
	- Duration : 1:09
- Save and T > Timesheets (tab) : Note Time = 1:09

Issue:
- Unconsistent behaviors :
	The time is rounded when using Timesheets' timer and from Task's timer to Confirm Time Spent Wizard
	but it is not rounded when confirming the Wizard.

Fix:
- Round it in when confirming the wizard too.

opw-2672249

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-01 12:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80676).

2021-12-01 12:38 UTC, auon-odoo commented
Related PR : https://github.com/odoo/enterprise/pull/22636

2021-12-01 16:46 UTC, IT-Ideas requested changes
Thanks for your work 🙂 
Courage!

2021-12-01 16:46 UTC, IT-Ideas commented on addons/hr_timesheet/wizard/project_task_create_timesheet.py
> +        minutes_spent = self.task_id._timer_rounding(self.time_spent * 60, minimum_duration, rounding)
I guess you did not test your dev 👼🏼 😘 
This cannot work in community without enterprise 🙂 
The reason why it does not break is that there is no test using this code I guess.
You should take the logic from the _timer_rounding  def (coming from the timer mixin) and use it in here directly.

Can you add a test that use this code?

And mercikes 🙂

2021-12-02 09:38 UTC, IT-Ideas commented on addons/hr_timesheet/wizard/project_task_create_timesheet.py
>          self.task_id.user_timer_id.unlink()
🙈 Can you comment this line?
And add a comment above saying that the wizard has to be moved to timesheet_grid in master?

2021-12-02 09:39 UTC, IT-Ideas commented on addons/hr_timesheet/wizard/project_task_create_timesheet.py
>          self.task_id.user_timer_id.unlink()
And add an inheritance in timesheet_grid that call super and call self....
Thanks!

2021-12-02 09:40 UTC, IT-Ideas commented on addons/hr_timesheet/wizard/project_task_create_timesheet.py
>          self.task_id.user_timer_id.unlink()
This wizard should have been moved to enterprise at the timer has been moved to enterprise.

2021-12-02 16:04 UTC, IT-Ideas commented
@auon-odoo I just rebased as the runabout was yellow 🙂

2021-12-02 16:18 UTC, IT-Ideas approved these changes
LGTM Thanks 🙂

2021-12-02 16:18 UTC, IT-Ideas commented
@robodoo r+

2021-12-02 17:50 UTC, closed without merging