[IMP] hr+resource: populate
odoo/odoo pull request #80688
Opened 2021-12-01 15:36 UTC by flch-odoo

Populate script to prepare populate of modules depending on hr and resource
such as appointment.

See Task-2631088

2021-12-01 15:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80688).

2022-01-18 08:34 UTC, kba-odoo requested changes

2022-01-18 08:34 UTC, kba-odoo commented on addons/hr/populate/hr.py
> +                       **values}
Wouldn't it be better to use the user's company instead? :thinking: 
You also avoid updating each user that way.

2022-01-18 08:34 UTC, kba-odoo commented on addons/hr/populate/hr.py
> +                })
That will not work :smile: 

Either you browse() the record based on its id, or even better:

```py
employee.user_id.write({
    # ...
})
```

2022-01-18 08:34 UTC, kba-odoo commented on addons/resource/populate/resource_calendar.py
> +        a_lot = self.search([("name", "like", "A lot")])
You should use `filtered()` (or `filtered_domain()`) instead.
`search()` searches for records in the database and not on the current recordset.

2022-01-18 08:34 UTC, kba-odoo commented on addons/resource/populate/resource_calendar.py
> +        a_little = self.search([("name", "like", "A little")])
You can also do:

```suggestion
        a_little = self - a_lot
```

2022-01-18 08:34 UTC, kba-odoo commented on addons/resource/populate/resource_calendar.py
> +            )
You could do something like this also, to remove the `to_pop`th attendance:
```suggestion
            att_id = record.attendance_ids[to_pop].id
            record.write({
                'attendance_ids': [(3, att_id, 0)],
            })
```

2022-01-18 08:47 UTC, flch-odoo commented
Thanks a lot, @kba-odoo ! I'll go over these ASAP.

2022-01-18 08:51 UTC, kba-odoo commented on addons/hr/__init__.py
> +from . import populate
Already imported below, you can remove it

2022-02-01 11:35 UTC, tde-banana-odoo commented
@robodoo r+

2022-02-01 11:35 UTC, tde-banana-odoo commented
@robodoo r-

2022-02-01 13:44 UTC, tde-banana-odoo commented
@robodoo r+

2022-02-01 15:31 UTC, closed without merging