[FIX] l10n_ch: Fix the invoice title's CSS
odoo/odoo pull request #80873
Opened 2021-12-03 17:58 UTC by lordkrandel

The title's (S)CSS selector was failing to pick up the invoice title,
because it was inside the .swiss_container_v2 while it should be out of that.
    
opw-2584899

2021-12-03 17:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80873).

2022-01-13 14:06 UTC, william-andre requested changes

2022-01-17 08:43 UTC, lordkrandel commented on addons/l10n_ch/static/src/scss/report_swissqr.scss
> +}
Re-scoped the variables and changed the name to the ratio.

2022-01-17 15:35 UTC, william-andre approved these changes
@robodoo r+

2022-01-17 16:56 UTC, closed without merging