[FIX] fields: company_dep summable fields are summed when merged
odoo/odoo pull request #80904
Opened 2021-12-06 12:19 UTC by admi2806

How to reproduce the bug:

- Install POS and data_cleaning
- Create 2 customers and set loyalty points
- Select both customers and merge them
- Once the merge is done, the loyalty points have not been summed

Bug:

When you merge 2 contacts that have both loyalty points, the resulting
contact won't have the sum of the 2 source contacts. Instead of that,
the resulting contact will only have the points of one of of the
contact.

opw: 2686208

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-06 12:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80904).

2021-12-06 12:21 UTC, admi2806 commented
@simongoffin 
Can you please have a look at this plz ?

2021-12-08 08:57 UTC, simongoffin reviewed
Hello J'ai vu que le champ loyalty_points est company_dependent. Que se passe-t-il en multi compagnie? Ex Considérons deux compagnies C1, C2 et deux partenaires P1, P2
P1 a 3 points dans C1 et 2 points dans C2
P2 a 4 points dans C1 et 1 point dans C2
Si on merge P1 et P2 en P3
P3 aura t il bien 7 points dans C1 et 3 points dans C2?

2021-12-09 08:47 UTC, admi2806 commented
> Hello J'ai vu que le champ loyalty_points est company_dependent. Que se passe-t-il en multi compagnie? Ex Considérons deux compagnies C1, C2 et deux partenaires P1, P2 P1 a 3 points dans C1 et 2 points dans C2 P2 a 4 points dans C1 et 1 point dans C2 Si on merge P1 et P2 en P3 P3 aura t il bien 7 points dans C1 et 3 points dans C2?

Bien vu, je vais régler ça :)

2021-12-13 10:11 UTC, admi2806 commented
> Hello J'ai vu que le champ loyalty_points est company_dependent. Que se passe-t-il en multi compagnie? Ex Considérons deux compagnies C1, C2 et deux partenaires P1, P2 P1 a 3 points dans C1 et 2 points dans C2 P2 a 4 points dans C1 et 1 point dans C2 Si on merge P1 et P2 en P3 P3 aura t il bien 7 points dans C1 et 3 points dans C2?

Hello, après une discussion avec le Support Expert le PO de POS, Il faut bien gérer ce cas-là. Je vais le modifier maintenant du coup :)

2021-12-15 08:12 UTC, simongoffin approved these changes

2021-12-16 11:09 UTC, nle-odoo reviewed
I'm not sure it's correct to just get  self.env.user.company_ids since it's restricting to current user companies, but there could be data in other companies

I guess if we need to have them, you would need to check on ir.property directly, something like:

```py
field_id = self.env['ir.model.fields']._get('res.partner', column).id 
company_ids = self.env['ir.property'].sudo().search([
    ('fields_id', '=', field_id),
    ('res_id', 'in', src_partners.ids + [dst_partner_id.id]),
    ('company_id', '!=', False)
]).mapped('company_id')
```

I'm not sure how right that would be, but if you are getting the properties maybe you could maybe just do something like this:

```py
for property in properties:
        company_values = values_company_dependent.setdefault(property.company_id, {})
        if company_values.get(column):
            company_values[column] += property.get_by_record()
        elif property.get_by_record():
            company_values[column] += property.get_by_record()
```

2021-12-24 07:24 UTC, admi2806 commented
> 

Hello,
When I wrote the patch, I was not sure that only getting the current user companies would be enough but I'm pretty sure that if you try to access these values while the company is not active, you will get a security access error.

2022-02-03 08:48 UTC, simongoffin commented
@admi2806 Can you add a test for it?

2022-02-07 11:37 UTC, admi2806 commented
> @admi2806 Can you add a test for it?

I have added a test in the pos_loyalty module which is part of enterprise.
Here is a link to the PR: https://github.com/odoo/enterprise/pull/24059

2022-02-11 10:38 UTC, rco-odoo requested changes
I second the remark above: you should consider _all_ companies, as the result of the operation should not depend on the current user.

2022-02-11 10:38 UTC, rco-odoo commented on odoo/addons/base/wizard/base_partner_merge.py
> +        res_id = ['res.partner,{}'.format(id) for id in src_partners.ids + [dst_partner.id]]
This is a list, please use some consistent naming like `res_ids`.

2022-02-11 10:38 UTC, rco-odoo commented on odoo/addons/base/wizard/base_partner_merge.py
> +        values_company_dependent = dict()
Use a variable name that can be read and understood, and a `defaultdict` will make code easier.
```suggestion
        values_by_company = defaultdict(lambda: defaultdict(int))   # {company_id: {fname: value}}
```

2022-02-11 10:38 UTC, rco-odoo commented on odoo/addons/base/wizard/base_partner_merge.py
> +                                values_company_dependent[company_id][column] = write_serializer(item.with_company(company_id)[column])
Using `ir.property`'s model details is a big mistake IMO.
I suggest iterating on _all_ companies, and use `sudo()` (it is reasonable in this case).
With the `defaultdict` above, it becomes
```suggestion
                for company in self['res.company'].sudo().search([]):
                    for partner in (src_partners + dst_partner).sudo().with_company(company):
                        values_by_company[company][column] += write_serializer(partner[column])
```

2022-02-11 10:38 UTC, rco-odoo commented on odoo/addons/base/wizard/base_partner_merge.py
> +            dst_partner.with_company(company_id).write(values_company_dependent[company_id])
If you do that on all companies, you should write with a sudo(), which looks fine to me in this context.

2022-02-11 13:55 UTC, admi2806 commented
Hello @rco-odoo ,
Thanks for the review. I have taken your comments into account and your solution is the best one.

2022-02-11 14:26 UTC, nle-odoo approved these changes
I was afraid of doing `self.env['res.company'].sudo().search([])`, but looks a lot clearer like that :+1: 

looks good to me after removing:

```py
res_id = ['res.partner,{}'.format(id) for id in src_partners.ids + [dst_partner.id]]
```
that is no longer used

and commit message should  have module `base` in title

2022-02-11 16:41 UTC, rco-odoo commented
@admi2806 I modified a bit the commit:
- changed the commit's title
- removed useless `res_id`
- using `sum()` instead of a loop makes the computation more readable

2022-02-11 16:43 UTC, rco-odoo approved these changes

2022-02-11 17:25 UTC, rco-odoo commented
@simongoffin @nle-odoo I let you review my last changes, and merge the pull request.

2022-02-16 09:46 UTC, simongoffin approved these changes
Ok it looks good

2022-02-16 09:46 UTC, simongoffin commented
robodoo r+

2022-02-16 10:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#24059 not ready. Linked PRs are not staged until all of them are ready.

2022-02-16 13:39 UTC, closed without merging