[FIX] pos_coupon, pos_restaurant : Promotion program
odoo/odoo pull request #80925
Opened 2021-12-06 15:54 UTC by robinengels

Current behavior :
When you add a promotion campagn to a PoS the promotion is applied
on every line of every order everytime you load the order. This cause situations
where you have multiple discount for a single product.

Steps to reproduce:
- create a standrard promotion program (automatically applied, 10%)
- set that promotion on the PoS (bar)
- open a session, chooses a table and make an order --> promotion correctly applied
- get out of the table and go back to the same table --> 2 additional lines are created because of the promotion

opw-2699544

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-06 15:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/80925).

2021-12-07 16:05 UTC, agr-odoo commented
After having a look at it, seems that you only need to set the field `is_program_reward`
so why not recovering it while doing `_get_order_lines` ?
https://github.com/odoo/odoo/blob/89285c648008ac508a97bf4948f156d35da499fc/addons/pos_restaurant/models/pos_order.py#L159
The field list is get via `_get_fields_for_order_line`
https://github.com/odoo/odoo/blob/89285c648008ac508a97bf4948f156d35da499fc/addons/pos_restaurant/models/pos_order.py#L75
You can have an override in pos_coupon module to recover also `is_program_reward`

Note that we don't know the module load order so you possibly need to define the base method in `point_of_sale` and override in `pos_coupon` and `pos_restaurant`

2021-12-08 11:26 UTC, agr-odoo requested changes
Just some minor style changes

2021-12-08 11:26 UTC, agr-odoo commented on addons/pos_coupon/models/pos_order.py
> +from itertools import groupby
not needed anymore

2021-12-08 11:26 UTC, agr-odoo commented on addons/pos_restaurant/models/pos_order.py
> +
newline not needed

2021-12-08 11:26 UTC, agr-odoo commented on addons/pos_coupon/models/pos_order.py
> +        fields = super(PosOrder,self)._get_fields_for_order_line()
leave a space after the comma
`super(PosOrder, self)`

2021-12-08 11:26 UTC, agr-odoo commented on addons/pos_restaurant/models/pos_order.py
> +        fields = super(PosOrder,self)._get_fields_for_order_line()
leave a space after the comma
`super(PosOrder, self)`

2021-12-08 11:26 UTC, agr-odoo commented on addons/point_of_sale/models/pos_order.py
> +    def _get_fields_for_order_line(self):
maybe add a comment to explain this is here to be overridden

2021-12-08 14:26 UTC, agr-odoo commented
LGTM
robodoo delegate+

2021-12-08 14:40 UTC, robinengels commented
@robodoo r+

2021-12-08 17:25 UTC, closed without merging