[FIX] hr_holidays: fix being able to select invalid time off type
odoo/odoo pull request #81111
Opened 2021-12-09 09:58 UTC by phwa-odoo

Prior to this commit, the _search_valid method returns all the time off types.

With this commit, only the time off types that have a valid allocation are returned

task-2711388

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-09 09:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81111).

2021-12-09 10:39 UTC, Williambraecky commented
FYI @jb-macq 😄

2021-12-20 15:10 UTC, kbapt requested changes

2021-12-20 15:10 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_type.py
> +        allocation_search_date_from = self._context.get('default_date_to') or fields.Date.today().strftime('%Y-12-31')
Change not needed

2021-12-20 15:10 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave_type.py
> +        self._cr.execute(query, (employee_id or None, allocation_search_date_to, allocation_search_date_from))
Same here

2021-12-20 18:36 UTC, phwa-odoo commented on addons/hr_holidays/models/hr_leave_type.py
> +        allocation_search_date_from = self._context.get('default_date_to') or fields.Date.today().strftime('%Y-12-31')
Done, thanks :)

2021-12-20 18:36 UTC, phwa-odoo commented on addons/hr_holidays/models/hr_leave_type.py
> +        self._cr.execute(query, (employee_id or None, allocation_search_date_to, allocation_search_date_from))
Done, thanks :)

2021-12-21 07:20 UTC, kba-odoo commented
@robodoo r+

2021-12-21 09:04 UTC, closed without merging