[IMP][13.0] hr_expense: Add hook method for inherit
odoo/odoo pull request #81267
Opened 2021-12-11 05:00 UTC by tranngocson1996

This PR
-------
After paying the expense report, the lines are reconciled right away but
with this old code I can't inherit the custom reconciliation lines. So I
provide a hook method to be able to inherit and customize the lines that
want to be reconciled.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-11 05:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81267).

2021-12-11 05:03 UTC, tranngocson1996 commented
@kba-odoo Are you in charge of expense modules? If not, please tag me who is interested in this issue. Thank you bro
cc: @mart-e @Yenthe666

2021-12-11 11:58 UTC, davidtranhp requested changes

2021-12-11 11:58 UTC, davidtranhp commented on addons/hr_expense/wizard/hr_expense_sheet_register_payment.py
> +        return account_move_lines_to_reconcile
This is easier to understand
```suggestion
        return lines.filtered(lambda l: l.account_id.internal_type == 'payable' and not l.reconciled)
```

2021-12-11 13:24 UTC, tranngocson1996 commented on addons/hr_expense/wizard/hr_expense_sheet_register_payment.py
> +        return account_move_lines_to_reconcile
> This is easier to understand
> ```suggestion
>         return lines.filtered(lambda l: l.account_id.internal_type == 'payable' and not l.reconciled)
> ```

Yes sir

2021-12-12 01:57 UTC, leotranviindoo approved these changes

2021-12-12 13:08 UTC, tranngocson1996 commented
@kba-odoo Can you review this?
@mart-e @Yenthe666 Don't forget me. Plz :(

2021-12-13 07:17 UTC, kba-odoo commented
@robodoo r+

2021-12-13 07:29 UTC, tranngocson1996 commented
@kba-odoo thank you bro !!!

2021-12-13 08:01 UTC, closed without merging

2021-12-13 08:10 UTC, tranngocson1996 commented
@kba-odoo I am also having this problem on version 14.0. Do you have any ideas for it?
I still can't think of a solution

2021-12-13 08:15 UTC, kba-odoo commented
@tranngocson1996 you can probably do something similar in the inherited payment wizard: https://github.com/odoo/odoo/blob/14.0/addons/account/wizard/account_payment_register.py#L604

2021-12-13 08:17 UTC, tranngocson1996 commented
> @tranngocson1996 you can probably do something similar in the inherited payment wizard: https://github.com/odoo/odoo/blob/14.0/addons/account/wizard/account_payment_register.py#L604

@kba-odoo Thanks for your idea. I will do PR soon and please help me review it.