[FIX] account: make recipient bank account readonly
odoo/odoo pull request #81319
Opened 2021-12-13 14:10 UTC by aliyatastemirova

Currently: the "register payment" wizard allows selecting different bank accounts or even creating one when registering a payment on customer invoice/vendor refund.

Should be: the field should be set to partner_bank_id and be set as readonly.

Task: https://www.odoo.com/web#id=2710936&cids=1&action=333&active_id=967&model=project.task&view_type=form

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-13 14:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81319).

2021-12-13 14:47 UTC, aliyatastemirova commented
@oco-odoo Could you please review? Thanks :)

2022-01-19 15:44 UTC, oco-odoo requested changes
You need to do the same on accoun.payment's form view as well ;)  The 'register payment' button isn't the only way this flow can pass through. 

On the payment form, we could also improve the labelling: the field is called "customer bank account", but in case of an inbound payment, it receives the account of our company. So "Recipient bank account" would make more sense, just as on account.payment.register.

2022-01-31 12:41 UTC, oco-odoo commented on addons/account/views/account_payment_view.xml
> +                                            'readonly': ['|', ('state', '!=', 'draft'), ('payment_type', '=', 'inbound')],
I discussed these changes with tsb, and we'll do it a little differently, still keeping the old label in the cases where they are legit.

As it's kind of a bug, I made it in stable here: https://github.com/odoo/odoo/pull/83674

2022-01-31 12:43 UTC, oco-odoo commented
Now pushing to remove the part that I did in my fix in 15.0, and replace the [FIX] in the commit message by an [IMP], so that we can merge it right away. @aliyatastemirova don't be surprised, and thanks for your work :)

2022-01-31 12:51 UTC, oco-odoo approved these changes
@robodoo r+

2022-02-01 09:03 UTC, oco-odoo commented
@robodoo r+

2022-02-01 10:54 UTC, closed without merging