[FIX] website_sale: Only internal users can be picked as salesperson
odoo/odoo pull request #81368
Opened 2021-12-14 10:18 UTC by thcl-odoo

### Current behavior
Any users (not only internal users, but portal users too) can be selected from the `Salesperson` field in the Settings. 

### Expected behavior
Only internal users can be selected.

### Steps to reproduce
- Install eCommerce
- Go to Settings > Website category 
- Find 'Orders Followup' category
- Try to pick a salesperson

OPW-2709759

2021-12-14 10:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81368).

2021-12-14 13:41 UTC, agr-odoo approved these changes
Ok, this is already the case in multiple places, i.e.
```python
addons/website_crm/models/res_config_settings.py
18-    crm_default_user_id = fields.Many2one(
19:        'res.users', string='Default Salesperson', related='website_id.crm_default_user_id', domain=[('share', '=', False)], readonly=False,
20-        help='Default salesperson for new leads created through the Contact Us form.')
```

You could just add spacing in the domain now, to avoid issues when forward porting

robodoo delegate+

2022-01-04 12:34 UTC, thcl-odoo commented
Hello @odoo/rd-website :slightly_smiling_face: ,
Can I have a review on this one please ?

2022-01-04 16:55 UTC, rdeodoo requested changes
Please target correct version.
Unless I miss something, either this is for 13.0 or for master.
- Blocking issue or traceback -> Stable fix -> Version where it appears (especially true when the code is the same, like this) -> 13.0
- Non blocking issue -> Not worth the risk (one line fix never comes without risk) -> Improvement for master.

Arguably, since 15.0 is kind of new, some people might consider 15.0 in between master and stable, but this is not the case here anyway.

2022-01-06 16:15 UTC, thcl-odoo commented
Hello @rdeodoo ,
You're completely right, sorry for this mistake :sweat:

I recreated a PR targeting the right version, here it is : https://github.com/odoo/odoo/pull/82356

I will close this PR afterwards.

2022-01-06 16:35 UTC, rdeodoo commented
I quickly did it myself as I needed the branch in local anyway to test something. (And I am not sure you have the right to set the PR as draft or change the target? If not, you can anyway ask someone when needed, including me ;-) )

Can you just check https://github.com/odoo/odoo/pull/82247#issuecomment-1005547893 and then this should be good to r+ ?

2022-01-06 17:03 UTC, thcl-odoo commented
I've just updated the commit message according to your last comment

And I've never needed to change the target but at least I can set the PR as draft so.... I'll try it next time :smile: 
Thanks for the explanation of 'retargeting', I wasn't sure if it works like that, it will be useful!

2022-01-06 17:35 UTC, rdeodoo reviewed
You are welcome, whenever you are ensure of something or would like some explanation, don't hesitate to ask :).

Note that generally, commit title should fit the sentence `if applied, this commit will.. <insert commit title>`.
In this case, it does not fit but it is ok, let's not spend time on this detail, but so you know for next time.
Something like `[FIX] website_sale: let only internal users be picked as salesperson` would have been better to respect the commit guidelines (this one is not really the most important one so..).

Anyway, thanks for the fix/imp.
@robodoo r+

2022-01-06 17:35 UTC, rdeodoo approved these changes

2022-01-06 19:30 UTC, closed without merging