[IMP] payment: add 'payment tokens' on refund transaction
odoo/odoo pull request #81376
Opened 2021-12-14 10:48 UTC by hote-odoo

When refund transaction are created now, if a saved token was
used previously for the payment, then the refund will inherit
the token.
Before was not the case and refunds had not token regardless
of the payment having one or not.
Now it should be more easy to manage and track refunds if the
token is also present.

Task - 2694760

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-14 10:48 UTC, hote-odoo commented
Still working on it.

2021-12-14 10:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81376).

2022-02-18 10:27 UTC, chevalierv commented on addons/payment/controllers/portal.py
> +            if not token_verified:
This should be done in the sale part. You can create a new token minus the `confirm_order` once you've verified it in the sale controller. Doing this, no need to change anything in payment

2022-02-18 11:45 UTC, chevalierv requested changes
Great works on this task :+1: 

Although, we try to keep the business logic that does not concern `payment` outside of it. I've made a lot of comments to guide you through a bit of refactoring to keep the sale logic in `sale`.

2022-02-18 11:45 UTC, chevalierv commented on addons/payment/wizards/payment_link_wizard.py
> +
To be moved in `sale` module

2022-02-18 11:45 UTC, chevalierv commented on addons/sale/views/sale_portal_templates.xml
> +            </t>
I think this is too much. Customers will see if this is a quotation or a sale order by the title

2022-02-18 11:45 UTC, chevalierv commented on addons/sale/views/sale_portal_templates.xml
> +                        <b t-out="amount_paid"/>
You should add the currency. Lookup for `format_amount()`

2022-02-18 16:31 UTC, hote-odoo commented on addons/sale/controllers/portal.py
> +                })
For sale, confirm_order is always present

2022-02-24 18:03 UTC, chevalierv requested changes

2022-02-25 08:01 UTC, hote-odoo commented on addons/sale/wizard/payment_link_wizard.py
> +                'amount_max': record.amount_total,
This field is linked to total amount of the SO and it's used to differentiate between was has already been paid. It's better to leave as is.

2022-02-25 08:04 UTC, hote-odoo commented on addons/sale/controllers/portal.py
> +        new_access_token = None
Yes, in the case a partner_id is not provided `new_access_token` needs nevertheless to be initialized.

2022-02-25 08:19 UTC, hote-odoo commented on addons/sale/views/payment_templates.xml
> +    </template>
done :)

2022-02-25 08:30 UTC, hote-odoo commented on addons/sale/models/sale_order.py
> +        #   confirmed, where there is still a positive amount to be paid
done :)

2022-02-25 08:58 UTC, hote-odoo commented on addons/sale/controllers/portal.py
> +                                   access_token=(new_access_token or access_token), **kwargs)
Two cases are possible, there is a `sale_order_id` and the `access_token` was generated with `confirm_order` inside, thus we regenerate the access token. Second there is no `sale_order_id` and then the `access_token` was generated without `confirm_order` and we do not need to regenerate a new access token. 
Finally the logic of the access token is ok :)

2022-03-02 15:09 UTC, chevalierv approved these changes

2024-04-16 11:41 UTC, C3POdoo commented
Dear @hote-odoo,

Thank you for your contribution but we are closing it due to inactivity.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2024-04-16 11:41 UTC, closed without merging