[FIX] website_sale,payment: Block UI only on click pay
odoo/odoo pull request #81661
Opened 2021-12-20 13:27 UTC by nboulif

Step to reproduce:

  - Install website_sale module
  - Go to the shop
  - Add a product to the cart and proceed to checkout
  - Click on Customize and activate `Accept Terms & Conditions`
  - Deactivate the `Accept Terms & Conditions` or click on a
    payment method.

Issue:

  UI freeze.

Solution:

  Freeze ui only when clicking on pay button.
  Unfreeze only if payment process fails.
  revert of odoo@41b91e1

See also:
- Enterprise PR: odoo/enterprise#23560

opw-2702798

2021-12-20 13:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81661).

2021-12-23 12:37 UTC, rdeodoo commented
The issue reported on the OPW is 
> When you click on a payment method or on confirming the general conditions, the screen will start to load and sort of freeze.

You fixed the second case, but not the first one.
Isn't there an event that is strictly called when clicking a the **enabled** "pay now" button ?w
That's where we should really block the UI imo, in a generic way. I don't know the new payment implementation, let me know if you can't find anything.

That's how it was implemented [at first](https://github.com/odoo/odoo/commit/eb3ed89f8440050fc32f9a7b29fb2b6ab8fd6b59), `enable_button` and `disable_button` were only called around the actual Payment call:
```
> [PAY EVENT METHOD]
> 1. disableButton
> 2. call to payment provider
> 3. enableButton after RPC fail/succeed
```

My [fix](https://github.com/odoo/odoo/commit/41b91e12eb80cee08e3a25bcc6546ef34937d8cf) was then not ok, since those methods are now called outside of the payment call.

I'll let you investigate in that regard.

2021-12-23 12:38 UTC, rdeodoo requested changes
The issue reported on the OPW is 
> When you click on a payment method or on confirming the general conditions, the screen will start to load and sort of freeze.

You fixed the second case, but not the first one.
Isn't there an event that is strictly called when clicking a the **enabled** "pay now" button ?w
That's where we should really block the UI imo, in a generic way. I don't know the new payment implementation, let me know if you can't find anything.

That's how it was implemented [at first](https://github.com/odoo/odoo/commit/eb3ed89f8440050fc32f9a7b29fb2b6ab8fd6b59), `enable_button` and `disable_button` were only called around the actual Payment call:
```
> [PAY EVENT METHOD]
> 1. disableButton
> 2. call to payment provider
> 3. enableButton after RPC fail/succeed
```

My [fix](https://github.com/odoo/odoo/commit/41b91e12eb80cee08e3a25bcc6546ef34937d8cf) was then not ok, since those methods are now called outside of the payment call.

I'll let you investigate in that regard.

2021-12-27 09:45 UTC, rdeodoo commented
@AntoineVDV @Feyensv See my last message for a bit of context.
There is 2 commits on this PR now, can you take care of commit 1?
- Commit 1: leftover of first @nboulif fix implementation, is that something you want to keep in 15.0 or master as it seems to clean a bit the code (now that it's coded.. :))?
- Commit 2: is the real fix which is now correctly restoring the behavior (the only really needed part).

2022-01-03 12:25 UTC, AntoineVDV requested changes
**About commit 1**

I'd rather clean the whole delivery method + TC checkbox + submit button mess in master, ideally when porting everything to OWL, because it's better not to redefine methods in stable, and I believe it could be simpler if we rely on the bus to pass the information on the submit button's 'readiness' status.

Also, I spotted a few problems in your diff (I didn't spend too much time on it, though):
- Calling an event handler method from the `start` method is a bit weird. I know that it was also done before but it could be improved now.
- Enabling and disabling the submit button should always be done through the`_enableButton` and `_disableButton` methods. That was the point of the changes made in JS in various modules during the payment refactoring: some modules were completely ignoring each other when it comes to whether the button could be enabled or not, with or without the spinning animation, etc.

2022-01-03 12:52 UTC, rdeodoo commented
@AntoineVDV Please see my summary [here](https://github.com/odoo/odoo/commit/41b91e12eb80cee08e3a25bcc6546ef34937d8cf), we can't use the enable and disable methods, which it was how I made the fix initially to restore that behavior loss in the refactoring of payment.
Since those methods are now not only called on "Pay now" click, it can't be there. Button can be disabled (eg you did not checked T&C, but still we don't want to block the UI).

@nboulif You can then remove commit 1 :)

2022-01-10 10:26 UTC, nboulif commented
@rdeodoo  Sorry for the delay, I was on time off.
> You can then remove commit 1 :)

Done, thanks :+1: 
cc @AntoineVDV

2022-01-13 15:10 UTC, AntoineVDV requested changes
@nboulif I agree with the proposed fix :+1:

Could you however extend it to `manage_form.js`'s calls to `_processPayment` and `_assignToken`? The behavior should be the same in this widget.

Also, it's obvious now but at the time I didn't realize it was cleaner to enable the button back in the `guardedCatch` of the processing method and placed the call to `_enableButton` at the end of `_displayError` instead. The heuristic was not wrong (because all `guardedCatch` call this method) but it should definitely be moved alongside `$("body").unblock()` in the `guardedCatch`. Could you take care of that in master?

@rdeodoo We totally agree that this behavior cannot be tied to the payment button; they need to work in parallel. My comment was referring to how this button was enabled/disabled by directly toggling its props in the (now gone) first commit ;)

2022-01-14 14:58 UTC, nboulif commented on addons/payment/static/src/js/checkout_form.js
> +            this._processPayment(provider, paymentOptionId, flow).guardedCatch(function () {
Done :+1:

2022-01-14 14:59 UTC, nboulif commented
@AntoineVDV @rdeodoo Updated :+1: I will make the changes in Master for `disableButton`. Thanks!

2022-01-14 15:38 UTC, AntoineVDV approved these changes

2022-01-17 08:04 UTC, kitan191 commented
@robodoo delegate+

2022-01-17 14:45 UTC, nboulif commented
Enterprise PR : https://github.com/odoo/enterprise/pull/23560

2022-01-18 12:40 UTC, AntoineVDV reviewed
I think you need to apply the same kind of fix for payment_adyen as for payment_sepa_direct_debit.

2022-01-19 15:45 UTC, AntoineVDV approved these changes
@robodoo delegate+

2022-01-20 15:01 UTC, nboulif commented
robodoo r+

2022-01-20 18:43 UTC, closed without merging