[IMP] core: don't add f_name in vals if there is child
odoo/odoo pull request #81847
Opened 2021-12-23 10:00 UTC by jva-odoo

if there is the child then write vals is created like {'field_o2m_name': None} so it removes lines and adds them again by sub_records

so in this commit, we do not add f_name in vals if there is a child of o2m

this give a big effect on account.tax.report to check just update any localization module where account.tax.report is there, after the update all tag is removed from taxes and journal items(account.move.line)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-23 10:01 UTC, jva-odoo commented
@odoo/rd-framework-py hello team plz look at this

2021-12-23 10:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81847).

2021-12-23 18:31 UTC, Julien00859 requested changes
Where is the unittest ?

2021-12-24 04:50 UTC, jva-odoo commented
@Julien00859 let me create it

2021-12-24 14:30 UTC, rco-odoo reviewed
@jva-odoo I just pushed two commits to make the code more readable.
With this little change, things look okay to me.

That being said, I think we should fix this in saas-15.1, where that feature has been introduced.
Can you remake a branch for saas-15.1?

2021-12-26 11:20 UTC, Julien00859 reviewed
Test ok

2021-12-27 05:38 UTC, jva-odoo commented
@rco-odoo for saas-15.1 PR is here https://github.com/odoo/odoo/pull/81913
and Thank you for the improvement

2021-12-27 05:38 UTC, closed without merging