[FIX] payment_ingenico: Allow to send UTF-8 data to Ingenico
odoo/odoo pull request #81945
Opened 2021-12-27 16:12 UTC by nboulif

Issue:

  Sending utf8 data to Ogone non-utf8 endpoint.

Solution:

  Use the UTF-8 url provided by Ogone instead.

opw-2700911

2021-12-27 16:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/81945).

2022-01-03 13:23 UTC, AntoineVDV requested changes
Looks good! However, the following methods should also only rely on `_get_ogone_urls` for the same reason as for `ogone_s2s_do_transaction`:
- `ogone_s2s_do_refund`
- `_ogone_s2s_get_tx_status`
- `ogone_create`

2022-01-10 12:41 UTC, nboulif commented
Hello @AntoineVDV , sorry for the delay, I was on time off.
Thanks for the review, I update the fix :+1:

2022-01-10 13:28 UTC, AntoineVDV approved these changes
You may want to check in 15.0 if the fix is still needed (I believe it's not) and disable the forward-port.

2022-01-10 15:53 UTC, nboulif commented
@kitan191 Thanks!
robodoo r+

2022-01-10 17:31 UTC, closed without merging