[IMP] l10n_hk: Update chart of account
odoo/odoo pull request #82012
Opened 2021-12-29 06:58 UTC by tong-odoo

Description of the issue/feature this PR addresses:

Update Chart of Account for Hong Kong localization

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2021-12-29 06:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82012).

2022-04-14 10:43 UTC, FlorianGilbert requested changes
Hello

Please add the task ID in the commit message according to [guidelines](https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html#commit-message-structure)

Thank you

2022-04-20 02:04 UTC, tong-odoo commented
> Hello
> 
> Please add the task ID in the commit message according to [guidelines](https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html#commit-message-structure)
> 
> Thank you

Updated thanks~

2022-04-20 12:24 UTC, FlorianGilbert approved these changes
@robodoo r+

Thank you!

2022-04-20 17:12 UTC, closed without merging