[FIX] website{_*}: not truncate URLs in search results
odoo/odoo pull request #82201
Opened 2022-01-04 10:27 UTC by bso-odoo

website{_*}: website, website_blog, website_event, website_forum,
website_sale, website_slides

Before this commit all text fields were truncated in search results.
This caused problems for long URLs which were truncated as well, and
therefore could become invalid.

After this commit URL fields specify `'truncate': False` in their search
detail metadata, which informs the rendering to skip the text truncation
step for that field.

task-2727788

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-04 10:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82201).

2022-01-04 17:31 UTC, rdeodoo requested changes
A few comments here:
1) I would **add the step to reproduce**, as it was given by Fabio and is written in the task. It it always valuable to have it, even in obvious cases like this one -> I had to check why I could not get the issue when testing on the runbot, it was because I was on the homepage which allows for a longer character count than in the forum search bar. I learned something but.. It would be a lot better with a step to reproduce (like every single fix).
2) I would **add a link to the commit/PR (commit ideally) that introduced the behavior that need to be fixed** (in this case, the generic search bar). First, it helps during the review since I have to look for it to know if this is getting fixed in the right version. Plus, it will be helpful later in case someone investigate this code, to easily and quickly navigate / figure stuff.
3) I would have **written a test** for this (I don't think we have tests right now for this behavior), it would have tested this fix but not only, it would also have tested the whole behavior as you would ensure you got the expected result, including the correct URL.
(You can use MockRequest to test such controller (autocomplete)), up to you tho..

2022-01-05 13:35 UTC, bso-odoo commented
>    (You can use MockRequest to test such controller (autocomplete)), up to you tho..

@rdeodoo I have added a few tests that were previously missing, verifying the results of the autocomplete controller call.
Given that website tests are run before other modules are installed, I based them on `website_page` only (which is the only searchable model without additional website_* modules).

2022-01-11 15:17 UTC, rdeodoo approved these changes
Thank you for the commit and tests @bso-odoo 
There were a few linter [error](https://github.com/odoo/odoo/compare/01f8babf6eca23d5c196e41eaf2ff80c4b85f8d3..1407ccf73b73fe1ae5e48897446b794a38b7e7c1), I fixed those. Took the opportunity to clean the 2-3 already existing ones so we have a clean file.
@robodoo r+

2022-01-11 17:26 UTC, closed without merging