[IMP] skills: improve readability for dropdown lists
odoo/odoo pull request #82202
Opened 2022-01-04 10:43 UTC by Bertrand2

Description of the issue/feature this PR addresses:
When you want to add/select new skills, it could be more clear.

Current behavior before PR:
When you want to change a skill level, you have to select a skill level to see its progression value

Desired behavior after PR is merged:
- The progression value is displayed beside the skill level in the dropdown list.
- In the appraisal module, the same thing applies to skills, which also feature the skill type in the dropdown list.

task: #2719642 [Skills] Overwrite name_get()

2022-01-04 10:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82202).

2022-01-25 12:58 UTC, kba-odoo requested changes
LGTM!

Could you just amend your commit message? :-)

Thanks

2022-01-25 12:58 UTC, kba-odoo commented on addons/hr_skills/models/hr_skills.py
> +
`from_skill_dropdown` is not defined anywhere, thus you can drop this method

2022-01-25 12:59 UTC, kba-odoo commented on addons/hr_skills/models/hr_skills.py
> +
My bad, it's used in enterprise :facepalm:

2022-02-09 10:33 UTC, kba-odoo commented
@robodoo r+

2022-02-09 11:49 UTC, closed without merging