[IMP] remove divs created by default shadow computation
odoo/odoo pull request #82223
Opened 2022-01-04 14:19 UTC by tdecaluwe

The shadow option needs to create a div on the fly to be able to retrieve the default shadow value. This commit makes sure these divs are also removed when no longer needed.

2022-01-04 14:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82223).

2022-01-26 10:51 UTC, qsm-odoo requested changes
That PR should be retargeted to the first stable version where the bug was introduced (as always). The commit message should say "FIX" instead of "IMP". The commit message contains a double-space that should be removed.

2022-01-26 10:51 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +        let shadow = 'none';
Don't define that variable in the middle of the div creation code... either before or after. I think the best place is like just before the switch?

2022-01-26 10:51 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.options.js
> +            case 'outset':
Don't remove the surrounding `{`. I personally always prefer them (code more readable to me but also mainly avoid errors with variable scopes) but here, it's just a matter of "you don't need to break the history and authorship of that line for no reason".

2022-02-02 14:40 UTC, qsm-odoo requested changes
Same review as before, task was marked as ready but the previous review was not considered (still targeting wrong version, wrong commit message, ...)...

2022-02-02 15:16 UTC, tdecaluwe commented
My bad, the code has been rebased now. I'm not sure whether it qualifies as a bug though?

2022-02-02 15:40 UTC, qsm-odoo requested changes
And now wrong commit message

2022-02-02 17:43 UTC, qsm-odoo approved these changes
@robodoo r+

We'll review that code in master. There is actually no reason to create the div if the type is "outset" or "inset" :shrug: But let's keep that diff minimal for stable then.

2022-02-02 17:43 UTC, qsm-odoo commented
@robodoo r-

2022-02-07 17:31 UTC, closed without merging