[FIX] payment_authorize: Allow public user to read payment terms
odoo/odoo pull request #82251
Opened 2022-01-05 09:46 UTC by jev-odoo

After 61b4b67
the public user doesn't have the rights to read the payment terms anymore.

OPW-2705525

2022-01-05 09:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82251).

2022-01-05 10:08 UTC, Feyensv reviewed
Why don't you use the `SUPERUSER_ID` constant ?
(I prefer that instead of a hardcoded 1 which is really unclear for newbies IMHO)

Also, the bug explanation is quite unclear, could you elaborate? :thinking:

2022-01-05 10:30 UTC, AntoineVDV requested changes
This could just be one commit with title "[FIX] payment_*: allow public user to read payment terms".

In addition to the title, I'd like to see a good explanation in the commit body of why this fix is needed at all? I checked 61b4b6777d64218f94c51ec839 but it seems to be an exact revert of 57665a02f7b4cd113f8f40ec47c58a518fe8669c (which is almost one year and a half old!), so I don't see why these commits are even mentioned if they cancel each other?

2022-02-07 22:50 UTC, jorenvo commented
Hi, we started running into this again internally. I worked on https://github.com/odoo/enterprise/pull/23952 which has details on how to reproduce the issue in standard Odoo and also a full traceback. It's less coarse than this PR and instead focuses on the exact issue we are running into. I would like to make progress on this because when users are faced with an error after they paid they often times try to pay again which leads to double-payments.

@AntoineVDV  I suppose this PR is a bit high-risk to merge, since it touches all the feedback flows?
@mart-e perhaps we just continue patching the root causes one by one (like  odoo/odoo@e680084 and odoo/odoo@962919e)? 8ae1a43663687 is in use for a little while now and it seems the amount of issues is not huge?

2022-02-08 08:46 UTC, AntoineVDV commented
> @AntoineVDV I suppose this PR is a bit high-risk to merge, since it touches all the feedback flows?

@jorenvo Not only that but it's way too high in the call stack for me. This kind of fix is far from ideal as:
- it won't fix all the related issues
- it will soon be almost impossible to figure out which issue it fixes -> can't remove it later on
- it's done in a module that is only part of the flow, not part of the problem

Instead, we should either fix the root cause or make case-by-case patches the closest to the spotted issues as possible.

2022-02-10 15:03 UTC, closed without merging