Fix 75674
odoo/odoo pull request #82332
Opened 2022-01-06 12:22 UTC by yaazkal

All information related to the issue is at https://github.com/odoo/odoo/issues/75674 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-06 12:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82332).

2022-08-01 08:11 UTC, Williambraecky requested changes
Hello thanks for the fix!
Unfortunately it isn't acceptable as is.

I am not that knowledgeable about pricelist but I have the feeling this should be fixed in the base `_get_combination_info` instead.

@Feyensv could you take a look on this one if you have some time?
Cheers

2022-08-01 08:11 UTC, Williambraecky commented on addons/website_sale/models/product.py
> +                if pricelist.item_ids.base == 'pricelist' and pricelist.item_ids.base_pricelist_id:
This will fail with multiple pricelist_items.

2022-08-01 08:11 UTC, Williambraecky commented on addons/website_sale/models/product.py
> +                    list_price = pricelist.item_ids.base_pricelist_id._compute_price_rule([(product, quantity_1, partner)])[product.id][0]  # TDE: 0 = price, 1 = rule
What about the taxes?

2022-08-02 10:22 UTC, Feyensv commented
@Williambraecky Well, it's a tricky problem to fix in stable (even more if we want to do it cleanly).
The discount computation (when considering recursive pricelists) is not coherent between the different scopes at all (cf #91010 for the same problem in POS).

I'm not even sure it's fully fixed in master (the SO prices will be correct, but the displayed discount might not be).
I'm thinking of redoing the whole `_get_combination_info` logic, but I wasn't convinced by my first try ^^.

Ideally, the logic of `_get_real_price_currency` should be extracted in a separate util method and used everywhere to consistently compute the pricelist discounts.

2023-03-30 09:40 UTC, C3POdoo commented
Dear @yaazkal,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2023-03-30 09:40 UTC, closed without merging