[FIX] account: 0% tax not in tax report due
odoo/odoo pull request #82370
Opened 2022-01-07 09:56 UTC by smetl

Have a 0% Tax
Make an invoice with it
Open tax report

The 0% tax is not present in the report because there is no 0 tax lines generated for them.
Since the tax details is making a mapping between tax lines and base lines and the tax report is using them to compute the report, the tax report is not able to compute the tax base amount for such taxes.

opw-2711432

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-07 09:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/82370).

2022-01-12 09:45 UTC, oco-odoo requested changes
We discussed it, and I understand why we have no choice but to do it this way; but you should explain that in your commit message, as this change might come as a surprise for a lot of people, who would then be very happy to find the explanation directly in the commit ;)

2022-01-14 16:49 UTC, smetl commented
@william-andre I don't plan to explain all taxes combination in odoo in this commit. Think about group of taxes, tax affecting the base of the following... combine that with the current tax details query and you will probably figure out this is not a simple `UNION ALL`.

2022-01-18 10:25 UTC, oco-odoo approved these changes
@robodoo r+

2022-01-18 11:36 UTC, closed without merging