[FIX] website_sale: remove unpublished product from cart
odoo/odoo pull request #83204
Opened 2022-01-21 15:55 UTC by fdamhaut

Step to reproduce:
- Add a product to your cart on the website app.
- Unpublish the product.
- Go back to your cart and process checkout with the now unpublished product.

Current Behaviour:
- Customers on the site are able to purchase unpublished products that were published at the time they added the product to their cart.

Behaviour After PR:
- Item is removed from cart when updating cart
This behaviour is preferable to removing on unpublished because it doesn't remove if the item is unadvertendly unpublished/published.

opw-2742258

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-21 15:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83204).

2022-01-24 09:44 UTC, rdeodoo requested changes
Hi, no bug in 14.0?

2022-01-24 09:44 UTC, rdeodoo commented on addons/website_sale/models/website.py
> +            lambda ol: ol.product_id.is_published
```suggestion
            lambda ol: ol.product_id.website_published
```
Basically, `is_published` should never be used (except in your tests to set the value on created product for instance).
I'll let you check the mixin, but is_published doesn't mean it is really published, website_published does.

2022-01-24 09:56 UTC, rdeodoo commented
Btw, I was just checking superficially, but also the commit message should follow the guidelines, especially:
- max 72 characters per line (80 is fine for commit description but don't do extra long lines like here)

2022-01-24 09:58 UTC, JKE-be requested changes
Hello, my 5 cents because I was looking for bugfix due to feedback pad...

`sale_get_order` should make the minimum of work, it is probably not his job. It is called a lot of time (because we know that it is fast and without heavy code), basically, it will just return something from your session and should make the minimal of computation (only done on create cart, onchange_partner, onchange_fiscalposition, ...)

Moreover, the fix will break others flows, since you can have unpublished product in your cart (gift card, coupon, ...).
It is why we need to use image_data_uri [in some case](https://github.com/odoo/odoo/blob/saas-15.1/addons/website_sale/views/templates.xml#L1056).

2022-01-25 10:25 UTC, pierre-pde commented
Hi @JKE-be , @rdeodoo  & @fdamhaut ,
IMO, it's not worth automating the removal of product from open carts when the product is unpublished.
However, I think what we could do is to display a warning message to the admin;
"Please note that the product was already selected in X customer open carts.
You have to manually update those carts if you wish to remove it".

We try to use the same approach when admin changes product public prices or pricelist prices.

The advantage is that there is no 'black magic', the inconvenient is that the admin needs to take manual actions.

2022-01-27 09:25 UTC, fdamhaut commented
@pierre-pde After some test and checks, There is a problem because the current way to unpublish items cannot trigger default Odoo warning. These warning can (from what I understood) only be trigger via an onchange which is is not triggered in this case.

I guess we can create a special warning for this case only, but i first would like to know if @JKE-be @rdeodoo have better ideas ?

2022-01-27 09:58 UTC, rdeodoo commented
> Hi, no bug in 14.0?

^ https://github.com/odoo/odoo/pull/83204#pullrequestreview-860698599

First, what happened to this question? Not sure you replied?
The bug is only in 15.0?
If it also impacts 13.0, we might just want to do that "fix" (more a imp imo) in master only, as anyway we are just introducing a warning, not a blocking step.

2022-01-27 10:10 UTC, JKE-be commented
State should be filtered on sale.order.line instead to bring thousand of useless lines that you filter in python later.
Filter by website_id or None; quid about other website if product without website_id ? -> need to be specified by PO.

About all this specs, it is a big details imo, the most important is on the checkout to check if all products are still "sellable" else you remove it from cart... ​

2022-01-27 10:21 UTC, fdamhaut commented
> > Hi, no bug in 14.0?
> 
> ^ [#83204 (review)](https://github.com/odoo/odoo/pull/83204#pullrequestreview-860698599)
> 
> First, what happened to this question? Not sure you replied? The bug is only in 15.0? If it also impacts 13.0, we might just want to do that "fix" (more a imp imo) in master only, as anyway we are just introducing a warning, not a blocking step.

Sorry tough i had responded, this issues seems to be in Odoo 13+ like the no-update price bug(did not check 12 and before)

2022-01-27 10:26 UTC, rdeodoo commented
Then this fix has nothing to do in 15.0.
Either you qualifie it as a bug and fix it in 13.0, or not and fix it in master.

I'll let you judge if this qualifies as a bug (usually, it means it is either blocking flows or raising TB without possible alternatives, as don't forget that even a one line fix that seems totally risk-less is never resk-less :-) ).

Maybe in master we can improve the /publish route to return something else than just boolean, to display a message on top of performing the publish action (warning).

And in cart, as JKE said, in 13.0 remove it from the cart during checkout only.

2022-01-27 10:34 UTC, fdamhaut commented
The goal was to try and solve it in 15 as I had already started then when we find a solution everybody is happy about, start a rebase + merge from 13 (bcs I was a bit lazy i agree)

@rdeodoo when removing from the cart at checkout, should I try to warn the user about the change or simply proceed as usual ?

2022-01-27 12:06 UTC, rdeodoo commented
I just checked with @pierre-pde (PO), he confirmed what we were heading towards here:
- This does not really qualifies as a bug
- I doubt we want to change such a behavior in > 2 year old stable DBs

We will just add a warning in master (need method signature changes) when unpublishing a product to tell the admin/manager than some open carts still have this product. (the same way we did for abandonned carts here https://github.com/odoo/odoo/commit/c8fdea914dd43d51caa313966ff45ad9d67234bc)

We will create a task internally to handle that :+1:

2022-01-27 13:00 UTC, fdamhaut commented
Ok Ty, I'll clos the PR / ticket then :D

2022-01-27 13:00 UTC, closed without merging