[FIX] website_sale: only show item from current category
odoo/odoo pull request #83440
Opened 2022-01-26 16:24 UTC by fdamhaut

What are the steps to reproduce your issue?
- Select a category.
- Search for a term in the product title.

What is the current behavior that you observe?
- All products with term appear not just the ones in the category

What would be your expected behavior in this case?
- Only products in the category should appear.

opw-2739602

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-26 16:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83440).

2022-01-31 15:16 UTC, rdeodoo requested changes
Hello, this seems wrong and looks like a fix for a bug that is actually not a bug but just another request from a customer.

First, this does not qualifies as a bug:
- There is no traceback
- There is no blocking flow

Second, when you think about it, this is not wrong or bad behavior, actually most eshop do that? You can check on https://www.coolblue.be/fr or https://www.mediamarkt.be/fr/
I get that some clients would prefer that the searchbar acts differently but.. That's how it is, you can suggest them to upgrade to 15.0 ;-)

Third, this is just a functional change (as there is no bug, this is not a fix) in a 3 years old stable version, which will impact hundred thousand of eshop that do not want their searchbar to act differently all of a sudden..
Just to please a customer. 

Finally, this was improved in 15.0, **alongside** with a visual refactoring that included the search bar inside the result zone of the screen (bellow the categories breadcrumb). With the visual change, it can makes sense (I don't like it personally but that's not the point).

Anyway, that was just my 2 cents, I see way too many PR recently changing behavior just on customer request, where:
- There is no real bug
- This is just behavior change in old stable (I usually call it: it becomes a "bug as a feature")
- It is already improved or changed in later version

I'll let the final verdict to @tivisse which is now handling the eshop and @pierre-pde which is the product owner of that part.

2022-01-31 15:30 UTC, rdeodoo commented
Imho, this shouldn't even go past functional support, which should just come to the same conclusion then the one I wrote. We can't change behavior like that for every client request.
That would have saved:
- Technical analysis from tech support
- Technical analysis again & dev from bugfix (you)
- Review from me (took some time to check all versions and what was different in 15.0, then which part of the code from the new snippet is adding the category part)
- Multiple pings to @pierre-pde and @tivisse 

There is also the possibility that I am wrong and this is the kind of stuff we are actually fixing on client request, but I don't think so ;-)

2022-02-01 09:08 UTC, pierre-pde commented
Agreed with @rdeodoo .
Sorry I didn't reply to your ping fast enough though @fdamhaut

2022-02-01 09:27 UTC, closed without merging