[FIX] mail: Access error closing chat
odoo/odoo pull request #83603
Opened 2022-01-28 16:12 UTC by robinengels

Current behavior:
After creating a group chat in the discuss app you were not able to close it.

Steps to reproduce:
-Create a group chat with more than one user in the discuss app
- Try to leave it
- You get an access error

opw-2736464

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-28 16:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83603).

2022-01-28 16:51 UTC, nle-odoo requested changes
it is odd that removing yourself from a record would end up in an access issue

checking from where the error is raised, it is when accessing channel_partner_ids in this constraint:

https://github.com/odoo/odoo/blob/e4674bb4f1c1cedcae30d1da79938164916d9ef3/addons/mail/models/mail_channel.py#L100-L104

So the user is deleted from the channel, then there is a access error when evaluating the constraint (since the user no longer has access to the channel).

So I think there should be `.sudo()` in the constraint instead (something like `self.sudo().filtered` so all the read to the channels are in sudo).

2022-01-31 15:47 UTC, nle-odoo approved these changes
looks good to me

robodoo r+ delegate+

2022-01-31 15:47 UTC, robodoo commented
I'm sorry, @nle-odoo. Draft PRs can not be approved.

2022-01-31 15:57 UTC, nle-odoo commented
robodoo r+

2022-01-31 16:04 UTC, seb-odoo commented
Yep, I still don't understand why we haven't changed the constraints to always run as `sudo` automatically.

2022-01-31 17:16 UTC, closed without merging