[IMP] account: allow drag and drop to upload bills in list view
odoo/odoo pull request #83639
Opened 2022-01-29 21:54 UTC by william-andre

Make users feel at home with a warm welcome when they try to upload
something with a drag and drop.

[task-2748604](https://www.odoo.com/web#id=2748604&model=project.task)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-29 21:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83639).

2022-05-30 09:34 UTC, csnauwaert requested changes
Community review, found a traceback and a strange behavior while testing :)

2022-05-30 09:54 UTC, william-andre commented on addons/account/static/src/js/bills_upload.js
> +                buttons_template: 'DocumentKanbanView.buttons',
Changed everything to `DocumentsKanbanView` for more consistency

2022-05-30 09:59 UTC, william-andre commented on addons/account/static/src/js/bills_upload.js
> +                events: _.extend({}, KanbanController.prototype.events, UploadDocumentMixin.events),
Changing to `Object.assign`, but FYI spread was the slowest in my case
![image](https://user-images.githubusercontent.com/44770049/170968414-4f155c15-5b68-4e59-8052-e1f569340908.png)

2022-05-30 11:04 UTC, william-andre commented on addons/account/static/src/js/bills_upload.js
> +         _setJournalContext: function(ev) {
> don't really like the way we go fetch the id of the journal

Note that this was already like this before, but I changed it to get the value from `kanbanRecord` instead

> Also another problem is that the upload button only works first time

Seems to be working now :shrug:

2022-05-30 13:06 UTC, csnauwaert commented on addons/account/static/src/js/bills_upload.js
> +                events: _.extend({}, KanbanController.prototype.events, UploadDocumentMixin.events),
Funny :smile: , might have something to do with the browser as we should have similar computers. Tried on two different laptops and results were consistent for me, using latest version of chrome though

2022-05-31 11:22 UTC, csnauwaert commented
@robodoo r+

2022-05-31 12:00 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#3460 not ready. Linked PRs are not staged until all of them are ready.

2022-05-31 12:00 UTC, robodoo commented
Because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2022-05-31 12:25 UTC, robodoo commented
Merge method set to rebase and fast-forward

2022-05-31 12:25 UTC, robodoo commented
I'm sorry, @csnauwaert. This PR is already reviewed, reviewing it again is useless.

2022-05-31 15:05 UTC, closed without merging