[FIX] l10n_cl: avoid writing vat always in the same way
odoo/odoo pull request #83686
Opened 2022-01-31 13:20 UTC by jco-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-31 13:21 UTC, jco-odoo commented
@william-andre Not tested yet, but I wonder if it is not better to just skip when you write to multiple records (not do the formatting).  @Danisan

2022-01-31 13:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83686).

2022-01-31 13:30 UTC, william-andre requested changes

2022-01-31 13:30 UTC, william-andre commented on addons/l10n_cl/models/res_partner.py
> +                super(ResPartner, vat_dict[vat]).write(vat_values)
Completely ignoring all the other values that can be in `values`

2023-03-30 09:30 UTC, C3POdoo commented
Dear @jco-odoo,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

2023-03-30 09:30 UTC, closed without merging