[IMP] mass_mailing: add extra data for styles on email layout wrapper
odoo/odoo pull request #83701
Opened 2022-01-31 15:16 UTC by edi-odoo

When creating email templates, it's currently impossible to customize the background color of a template's layout.

By adding a `data-layout-styles` attribute to the template, and appending that attribute's value to `themeParams` we can add custom styles to the layout's wrapper.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-31 15:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83701).

2022-01-31 15:34 UTC, Zinston requested changes
LGTM in terms of content but two little remarks on the style.
Also, the commit message (with task id if there is one) is missing and the commit title is too long :
![image](https://user-images.githubusercontent.com/24205914/151822306-ddc88177-a413-4832-ac6b-60e42a86eb02.png)

You also need to write an upgrade script for this (https://github.com/odoo/upgrade/wiki/How-To for more info if you haven't done that before).

2022-01-31 15:34 UTC, Zinston commented on addons/mass_mailing/static/src/js/mass_mailing_widget.js
> +            'style':themeParams.layoutStyles,
```js
style: themeParams.layoutStyles,
```

(space after `:` and no single quotes around the key)

2022-01-31 15:34 UTC, Zinston commented on addons/mass_mailing/static/src/js/mass_mailing_widget.js
> +                layoutStyles:$theme.data("layout-styles"),
```js
layoutStyles: $theme.data('layout-styles'),
```

2022-02-01 08:46 UTC, Zinston commented on addons/mass_mailing/static/src/js/mass_mailing_widget.js
> +                layoutStyles:$theme.data('layout-styles'),
how 'bout that space hu ? :-D

2022-02-02 11:08 UTC, edi-odoo commented on addons/mass_mailing/static/src/js/mass_mailing_widget.js
> +                layoutStyles:$theme.data('layout-styles'),
Oops!

2022-02-28 09:01 UTC, Zinston commented
@robodoo r+

2022-02-28 10:15 UTC, closed without merging