[ADD] payment_mercado_pago: Implement mercado pago
odoo/odoo pull request #83957
Opened 2022-02-04 13:36 UTC by hote-odoo

Mercado Pago it is a more intesting acquirer in Latinoamerica than
other possible acquirers as PayULatam. Thus it is a good decision to
implement it as a possible acquirer for odoo.

Task - 2704764

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-04 13:36 UTC, hote-odoo commented
This is an initial commit to have an skeleton for the implementation.

2022-02-04 13:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/83957).

2022-06-09 11:46 UTC, hote-odoo commented on addons/payment_mercado_pago/models/payment_transaction.py
> +        :param external_reference: the transaction reference to sync with MP server
Remove this, parameter was removed.

2022-06-09 11:47 UTC, hote-odoo commented on addons/payment_mercado_pago/models/payment_transaction.py
> +        # Url to which MP can send notifications.
Maybe `URL` instead of `Url`.

2022-06-09 11:48 UTC, hote-odoo commented on addons/payment_mercado_pago/models/payment_transaction.py
> +    def _mercado_pago_create_preference(self, items=None, **kwargs):
Do I really need `**kwargs` here ? Will I ever use it ?

2022-06-21 11:15 UTC, Feyensv requested changes
First tech pass, mostly linting :)

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +                     pprint.pformat(payload or {}))
```suggestion
        _logger.info(
            "sending request to %s:\n%s\n%s", 
            request_url, pprint.pformat(headers), pprint.pformat(payload or {})
        )
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +            *args, is_validation=is_validation, currency_id=currency_id, **kwargs
```suggestion
            *args, currency_id=currency_id, is_validation=is_validation, **kwargs
```
keep the args ordering, it's clearer ;)

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +
the empty space could be  removed

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +
same

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +
```suggestion
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +
`self.ensure_one()`

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +
Single quotes for technical strings ;)

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                     if back_url else {})
```suggestion
        back_urls = {}
        if self.operation == "online_redirect":
            back_url = urls.url_join(
                self.get_base_url(),
                MercadoPagoController._url_checkout_return
            )
            back_urls = {k: back_url for k in ('success', 'pending', 'failure')}
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +
```suggestion
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                      )
```suggestion
        payment_id = self.acquirer_reference or self._get_payment_info_from_mp().get('id')
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                                  )
```suggestion
            raise ValidationError(
                "Mercado Pago:" + _(
                    "could not retrieve a payment id for the transaction with reference %s",
                    self.reference
                )
            )
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/views/payment_views.xml
> +            <xpath expr="//group[@name='acquirer']" position="inside">
```suggestion
            <group name="acquirer" position="inside">
```

2022-06-21 11:15 UTC, Feyensv commented on addons/payment_mercado_pago/views/payment_views.xml
> +                    <field name="mercado_pago_access_token" attrs="{'required':[('provider', '=', 'mercado_pago'), ('state', '!=', 'disabled')]}" password="True"/>
```suggestion
                    <field name="mercado_pago_access_token" attrs="{'required': [('provider', '=', 'mercado_pago'), ('state', '!=', 'disabled')]}" password="True"/>
```

2022-06-21 13:43 UTC, hote-odoo commented on addons/payment_mercado_pago/controllers/main.py
> +    _url_webhook = '/payment/mercado_pago/webhook'
done :)

2022-06-21 13:44 UTC, hote-odoo commented on addons/payment_mercado_pago/controllers/main.py
> +                )
thank you :)

2022-06-21 13:44 UTC, hote-odoo commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                      )
thank you !

2022-06-22 14:56 UTC, hote-odoo commented on addons/payment_mercado_pago/controllers/main.py
> +                )
I fixed it, I use now the company id to restrain to the specific acquirer used to create the transaction.

2022-06-22 14:57 UTC, hote-odoo commented on addons/payment_mercado_pago/controllers/main.py
> +                        )
It is not, their documentation only point to the API being able to handle refunds. The user portal do not provide with a refund interface either.

For the raise in the webhook I changed it.

2022-06-23 13:31 UTC, Feyensv reviewed
icon.svg & icon.png to remove, the module icon will be done by the design team later, only keep the acquirer icon used and referenced in payment.

2022-06-23 13:31 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +
```suggestion
```

2022-06-23 13:31 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                _("received data without 'results': %s", pprint.pformat(mp_data_results))
```suggestion
                "Mercado Pago:" + _(
                    "received data without 'results': %s",
                    pprint.pformat(mp_data_results),
                )
```

2022-06-23 15:26 UTC, Feyensv reviewed
Didn't see anything strange/wrong left, gotta take one last deep look next week to be sure :).

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +            tx = self.search([('id', '=', tx_id)])
```suggestion
            tx = self.search([('id', '=', tx_id), ('provider', '=', mercado_pago)])
```
to be sure early in the flow that somebody is not trying stuff on transactions of other acquirers.

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/controllers/main.py
> +                or payment_external_reference != tx_sudo.reference
```suggestion
            payment_title != tx_sudo._mercado_pago_generate_payment_title()
            or float_compare(payment_amount, tx_sudo.amount, tx_sudo.currency_id.rounding) != 0
            or payment_external_reference != tx_sudo.reference
```

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/controllers/main.py
> +                payment_id
```suggestion
            payment_type == 'payment' and
            payment_action in ['payment.created', 'payment.updated'] and
            payment_id
```

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/controllers/main.py
> +from odoo.http import request
```suggestion
from odoo.http import request, route
```
so that you can remove the global http import :)

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/const.py
> +    'pass': ['rejected'],
Why are rejected notification discarded ?

2022-06-23 15:26 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +            pass
Probably worth a comment here, and eventually a log somewhere :thinking:

2022-06-27 10:15 UTC, Feyensv reviewed
And another wave of comments :ocean:

2022-06-27 10:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +        return acquirers
Method should be before `_mercado_pago_make_request`, it's used earlier in the payment flow (and quite critical when wanting to understand why the acquirer isn't shown :D)

2022-06-27 10:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +                'area_code': '',
Why don't you provide the code ?
Are you sure it doesn't complain when the phone is partly specified ?

2022-06-27 10:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_transaction.py
> +            )
This check seems strange, is it necessary ?

2022-06-27 10:15 UTC, Feyensv commented on addons/payment_mercado_pago/models/payment_acquirer.py
> +                method, request_url, data=json.dumps(payload), headers=headers, timeout=60
```suggestion
                method, request_url, json=payload, headers=headers, timeout=60
```
?

2022-08-29 06:27 UTC, chapital commented
Do you gonna implement also mercado libre like the other connector (eBay, amazon, etc), thanks

2022-08-29 07:04 UTC, AntoineVDV commented
Hi @chapital, the current PR only concerns Mercado Pago, the Payment Services Provider, but we are considering integrating Odoo with Mercado Libre for the V17 release.

2022-08-29 07:04 UTC, hote-odoo commented
@chapital Hello, for the moment we are implementing only Mercado Pago. It could be the case that for odoo 17 the market place Mercado Libre will be implemented.

2022-08-30 10:23 UTC, AntoineVDV approved these changes
Reviewed in pair-programming.

2022-08-30 11:01 UTC, AntoineVDV commented
@robodoo override=ci/security
Reason:

- requests: Used to make requests to a controlled URL with a short timeout.

Link to ci/security build (master): https://runbot.odoo.com/runbot/batch/843219/build/18851069

@robodoo r+ rebase-ff

2022-08-30 11:01 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-08-30 19:25 UTC, closed without merging

2023-10-09 06:24 UTC, chapital commented
Hello @hote-odoo do you have any news about implementation of Mercado libre?

2023-12-28 14:18 UTC, its-dev-fer commented
It would be great to have the implementation of Mercado libre, just a thought.