[FIX] account: intrastat code isn't set
odoo/odoo pull request #84103
Opened 2022-02-07 16:07 UTC by momegahed

If applied, this commit will fix the following bug by adding
intrastat country to generated invoices if the partner country is
an intrastat country.

Steps to reproduce:

1- install subscriptions - intrastat
2- Create a user u from an intrastat country
3- Create a new subscription for u with a payment plan
4- edit the payment plan to anything other than manual
5- click on "Generate Invoice" action button
6- the generated Invoice doesn't have intrastat country set

Bug:

the ```intrastat_country_id``` is not being set while creating
the invoice

Fix:

Add intrastat_country_id to invoice

OPW-2693107

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-07 16:07 UTC, momegahed commented
@simongoffin

2022-02-07 16:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84103).

2022-02-08 12:01 UTC, Levizar commented
Could you add a small test for it ?

2022-02-08 13:24 UTC, simongoffin approved these changes

2022-02-09 09:21 UTC, momegahed commented
> Could you add a small test for it ?

Hi @Levizar , in the light of this PR alone, I don't see what to test exactly.

It have to be considered along https://github.com/odoo/enterprise/pull/24095

Where the actual fix is implemented

2022-02-09 16:49 UTC, william-andre requested changes
Just declare the field as compute in `account_intrastat`

2022-02-09 16:49 UTC, william-andre commented on addons/account/models/res_country.py
> +    _inherit = 'res.country'
??????

2022-02-10 10:22 UTC, closed without merging