[FIX] sale: allow overriding portal domain
odoo/odoo pull request #84240
Opened 2022-02-09 11:17 UTC by Yenthe666

Description of the issue/feature this PR addresses: Before this commit the only way to modify the domain is to completely override portal_my_quotes /portal_my_orders .

Current behavior before PR: Since this function is so big this is not clean/easy to do now. Besides of this we use twice the same domain written in two functions.

Desired behavior after PR is merged:
By creating a separate function we can simply override it and we can reuse the function on two places.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-09 11:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84240).

2022-02-09 12:54 UTC, wtaferner approved these changes
Much better to inherit and maintain in general 👍🏼

2022-02-09 13:25 UTC, Yenthe666 commented
@tde-banana-odoo could I ask you to review/merge this please? :)

2022-02-09 15:31 UTC, tde-banana-odoo approved these changes
Hello @Yenthe666 ,

I agree on the PR, seems it does not cost much and ease custom inheritance. I would prefer letting @Feyensv or @tivisse validate it as they are retaking the whole sales scope.

Cheers !

2022-02-11 11:04 UTC, tivisse requested changes

2022-02-11 12:55 UTC, Yenthe666 commented
@tivisse thanks a lot for you feedback and I'm really sorry for that stupid mistake! I can't believe I missed that one. 😓 
I've resolved it & force pushed now so let me know if you need anything else :)

2022-02-11 21:33 UTC, celm1990 approved these changes

2022-02-14 10:41 UTC, tivisse commented
@robodoo r+ 

@Yenthe666 No problem, it happens to everyone :)

2022-02-14 11:31 UTC, closed without merging

2022-02-14 13:26 UTC, Yenthe666 commented
Thank you very much! :-)