[FIX] website: disable fuzzy search if search term contains numbers
odoo/odoo pull request #84599
Opened 2022-02-15 08:28 UTC by bso-odoo

Since [1] when fuzzy search was introduced, fuzzy search was also used
when the search term contained numbers.
This is a problem for companies where the shop search is used on
references: the fuzzy search does not match against the whole database
and therefore the exact match might not be found.

After this commit the exact search is used whenever a number appears in
the search term - because it is very likely to be a reference or an
identifier.

[1]: https://github.com/odoo/odoo/commit/7559626c54e34b41e1549e28276a650accec6986

opw-2715647

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-15 08:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84599).

2022-02-15 13:13 UTC, bso-odoo commented
@rdeodoo I am disabling the fuzzy search whenever the search term contains numbers, because it is very likely to be a part of an identifier.

2022-02-17 17:35 UTC, rdeodoo requested changes
> After this commit the exact search is used whenever a number appears in
the search term - because it is very likely to be a reference or an
identifier.

I would quite think the absolute exact opposite, it is most likely not the case and very niche.
I think it is far most common that such cases are regular search like `iphone6`, `32go`, `Audi RS6` etc.

I had a quick look and it will break those flows.

Eg
```python
self._create_page("iphone6", "iphone6", "/whatever")
self._autocomplete("iphone7")
``` 
It won't return a match with this PR, while right now it will return the iphone6 record.
I guess you can change the PR to perform that behavior **only** if the search is containing numbers **only**.

Edit: Also, can you make sure to add a test for the flow I described?

2022-02-18 12:42 UTC, rdeodoo commented
I really don't know what would be the optimal solution about this problem: finding a good balance to understand when is it a reference/identifier or a legit search.

What I am 99% sure is that the legit search including numbers are the far most common and the one we should privilege.
I can think of tons of example, I just had a look at my amazon history and even yesterday I did a search for `AV500` which is the model of the `TP-Link CPL` I want.

Your 80% rule would match that case tho. AFAIC, with a good comment and if no one has a better idea, that could be a start.

2022-02-18 15:28 UTC, rdeodoo approved these changes
@robodoo r+

From commit msg:
> the fuzzy search does not match against the whole database
and therefore the exact match might not be found.

This is because there is a limit=1000 in the code.

2022-02-18 17:17 UTC, closed without merging