[REF] web, *: remove useless code in main web controller
odoo/odoo pull request #84811
Opened 2022-02-17 13:36 UTC by sdegueldre

*: website_sale_coupon, test_apikeys

The do_search_read method was only used in a single place: the
search_read controller, whose entire function body was just a function
call. The content of the do_search_read method has been moved to the
search_read controller.

The search_read controller is still pretty useless: it's basically
equivalent to making an RPC on a model and calling the method
web_search_read. As such, this controller should be removed, but lots of
code depends on it and adapting all the code that uses it is out of
scope for this PR. It will hopefully be removed alongside the legacy
views in the webclient (which are its main users).

The call_common method is completely unused.

The /web/dataset/call controller is used in only two places and can
trivially be replaced with a call to /web/dataset/call_kw

2022-02-17 13:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84811).

2022-02-17 14:55 UTC, aab-odoo approved these changes

2022-02-17 15:13 UTC, xmo-odoo commented
> The /web/dataset/call controller is used in only two places and can trivially be replaced with a call to /web/dataset/call_kw

You do know that we're a product company and shit gets used by clients, right?

2022-02-17 15:25 UTC, aab-odoo commented
> > The /web/dataset/call controller is used in only two places and can trivially be replaced with a call to /web/dataset/call_kw
> 
> You do know that we're a product company and shit gets used by clients, right?

I don't see the point of keeping a method we don't use, because someone in the world might be using it. This is master, we remove code and break stuff. Also in this case, as he said, the workaround is trivial.

2022-02-17 16:33 UTC, sdegueldre commented
> You do know that we're a product company and shit gets used by clients, right?

@xmo-odoo We break APIs all the time in master, in the case of /web/dataset/call maybe there isn't a compelling reason to remove it and we can keep it as the cost of having it is basically zero, but "stuff may be used by clients" is true for any API change, this one just happens to be a very "low level"/basic API. If you strongly feel that we should keep it I'll put it back. I assume you don't have any qualms about the other removals?

2022-02-18 09:54 UTC, Julien00859 approved these changes
/web/dataset/call is hardly used indeed, may I ask you to add those changes on top of my #78857  branch? Just a rebase on your side and it would saves me a conflict :)

2022-02-21 10:04 UTC, xmo-odoo commented
> I don't see the point of keeping a method we don't use, because someone in the world might be using it. 

Because clients and partners building solutions atop our pile of stuff is intended, and creating unnecessary work for them has to be weighted against the benefit of the change.

And this here was an API which was in active use internally, even if its replacement is trivial, its removal has good odds of breaking things.

> If you strongly feel that we should keep it I'll put it back. I assume you don't have any qualms about the other removals?

`do_search_read` doesn't matter, it's an internal component (in controllers only `@route` are really considered public APIs. For `load` and `call` I'd suggest adding a deprecation warning for 16, and removing them for 17, something along those lines.

2022-02-21 11:40 UTC, Julien00859 commented
+1 for deprecation warnings in current master with a message "will be removed in version x, use y instead"

2022-02-21 15:11 UTC, Julien00859 requested changes
\+ `import warnings`

2022-02-22 12:03 UTC, sdegueldre commented
@Julien00859 done :+1:

2022-02-22 13:03 UTC, Julien00859 approved these changes

2022-02-25 07:10 UTC, aab-odoo approved these changes
robodoo r+

2022-02-25 08:26 UTC, closed without merging