[FIX] account_*: payment method journal filter
odoo/odoo pull request #84916
Opened 2022-02-18 15:21 UTC by vin-odoo

Fix two issues linked to payment methods and their journal link.

SEPA Credit Transfer was marked as only available on EUR journals, but
from what we have been told, and we have seen, it should also be made
available for other currencies (CHF/SEK).
So we are changing the rule used to determine if SEPA Credit Transfer
is available on a journal to allow to use it on journals using CHF or
SEK as a currency.

There is another issue, where the filtering is done differently at the
journal creation and when the user add the payment method manually in
the lists.
The filter rules were not respected at the journal creation, which
would lead to incorrect default inbound and outbound payment method list.
For example, a new journal would have the company currency (let's say,
USD) but still have SEPA Credit Transfer (EUR,CHF,SEK) added on it by
default while it should not be available there.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-18 15:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84916).

2022-02-18 16:25 UTC, qdp-odoo commented
don't you need to add currency_id field also in the dependcies of `_compute_available_payment_method_ids`, for the same reason?

2022-02-18 16:26 UTC, qdp-odoo commented
I don't understand the commit message use cases. Can you rephrase? or give an example?

2022-02-21 06:27 UTC, vin-odoo commented
I don't think we need the currency_id on `_compute_available_payment_method_ids` as changing the currency will recompute de payment method and thus recompute the available payment methods.

2022-03-08 12:02 UTC, qdp-odoo commented
@robodoo r+

2022-03-08 13:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#24539 not ready. Linked PRs are not staged until all of them are ready.

2022-04-12 15:50 UTC, william-andre requested changes

2022-04-12 15:50 UTC, william-andre commented on addons/account/models/account_journal.py
> +        pm_info = self.env['account.payment.method']._get_payment_method_information().get(payment_method_code)
Is this Java? :smile:

2022-04-12 15:50 UTC, william-andre commented on addons/account/models/account_journal.py
> +        journal_types = domain[0][2]
How do you know it's the first clause?
Still not perfect, but better:
```suggestion
        journal_types = next(right for left, operator, right in domain if left == 'type' and operator == 'in')
```

2022-04-12 15:50 UTC, william-andre commented on addons/account/models/account_journal.py
> +        is_available = is_available and self.type in journal_types
```suggestion
        if (
            not currency_ids 
            or (self.currency_id.id is False and self.company_id.currency_id.id in currency_ids)  # check this, it doesn't make any sense
            or self.currency_id.id in currency_ids
        ):
            return False
        if country_id and self.company_id.account_fiscal_country_id.id != country_id:
            return False
        if self.type not in journal_types:
            return False
        return True
```

2022-04-12 16:00 UTC, vin-odoo commented on addons/account/models/account_journal.py
> +        domain = pm_info.get('domain', [('type', 'in', ('bank', 'cash'))])
Aaaaaaah I was wondering if something like this existed but wasn't sure. I'll check but this should be perfect for this situation thank you

2022-04-13 07:45 UTC, FlorianGilbert approved these changes
@robodoo r+

2022-04-13 08:00 UTC, william-andre commented on addons/account/models/account_journal.py
> +        domain = pm_info.get('domain', [('type', 'in', ('bank', 'cash'))])
So nothing?

2022-04-13 08:02 UTC, vin-odoo commented on addons/account/models/account_journal.py
> +        domain = pm_info.get('domain', [('type', 'in', ('bank', 'cash'))])
I can't really do it here without changing the method definition. And even then, it does a self.ensure_one() and I can't be sure we have a payment method for this code at this point in the db.
I will change this in master to use the method that returns the domain, just like you said but in stable I don't think it's possible.

2022-04-13 11:21 UTC, closed without merging