Master fix expense line ids sgv
odoo/odoo pull request #84978
Opened 2022-02-21 11:24 UTC by sofiagvaladze

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-21 11:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84978).

2022-02-21 16:24 UTC, kba-odoo commented on addons/hr_expense/models/hr_expense.py
> +                    report.is_editable = (is_approver or report.env.user in current_managers) and report.employee_id.user_id != report.env.user
```suggestion
                    report.is_editable = (is_approver or self.env.user in current_managers) and report.employee_id.user_id != report.env.user
```

2022-02-22 12:45 UTC, kba-odoo requested changes

2022-02-22 12:45 UTC, kba-odoo commented on addons/hr_expense/security/ir_rule.xml
> +        <record id="ir_rule_hr_expense_sheet_employee_draft" model="ir.rule">
Keep the same ID, and it should be updated in a migration script:

```suggestion
        <record id="ir_rule_hr_expense_sheet_employee" model="ir.rule">
```

2022-02-22 12:45 UTC, kba-odoo commented on addons/hr_expense/security/ir_rule.xml
> +        <record id="ir_rule_hr_expense_sheet_employee_rest" model="ir.rule">
```suggestion
        <record id="ir_rule_hr_expense_sheet_employee_not_draft" model="ir.rule">
```

2022-02-24 07:55 UTC, kba-odoo commented
robodoo r+

2022-02-24 08:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#24579, odoo/upgrade#3274 not ready. Linked PRs are not staged until all of them are ready.

2022-02-24 09:00 UTC, robodoo commented
Linked pull request(s) odoo/upgrade#3274 not ready. Linked PRs are not staged until all of them are ready.

2022-02-24 10:48 UTC, kba-odoo commented
robodoo r+

2022-02-24 11:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#24579 not ready. Linked PRs are not staged until all of them are ready.

2022-02-24 12:32 UTC, closed without merging