[FIX] mobile: calculation of invoice lines and journal items on update
odoo/odoo pull request #84982
Opened 2022-02-21 11:29 UTC by rugo-odoo

[FIX] mobile: calculation of invoice lines and journal items on update

Problem :
- updating an invoice line on mobile would result in an incorrect untaxed amount, tax amount and total amount on the invoice and an incorrect entries in the journal items
- subtotal of invoice line was not showing in mobile view

Solution :
- the problem was that debit and credit fields were missing from the view so onchange were not trigger

Task: task-2766245

--

I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

2022-02-21 11:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/84982).

2022-02-22 08:42 UTC, FlorianGilbert reviewed
Can you please update your commit message to explain why it's not working and how you fix it ?
Please add the task ID in the commit message.

Thank you

2022-03-03 14:07 UTC, william-andre requested changes

2022-03-03 14:07 UTC, william-andre commented on addons/account/views/account_move_views.xml
> +                                                       groups="account.group_show_line_subtotals_tax_excluded"/>
Missing the `price_total` field

2022-03-04 11:48 UTC, william-andre commented on addons/account/views/account_move_views.xml
> +                                                <field name="price_total" string="Total"/>
Aren't you missing something else now? :wink: 

https://github.com/odoo/odoo/blob/5b95c97a85ee93f690097b183a39d8e84fa92f65/addons/account/views/account_move_views.xml#L715-L720

https://github.com/odoo/odoo/blob/5b95c97a85ee93f690097b183a39d8e84fa92f65/addons/account/views/account_move_views.xml#L749-L750

2022-03-04 16:34 UTC, william-andre approved these changes
@robodoo r+

2022-03-04 17:17 UTC, closed without merging