[ADD]: l10n_ro: Add Romania BS and Profit and PnL reports menus items
odoo/odoo pull request #85008
Opened 2022-02-21 13:38 UTC by JulienAlardot

### [ADD]: l10n_ro: Add Romania BS and Profit and PnL reports menus items

As there are currently the implementation of Romanian localisation
Balance sheet and Profit and Loss reports. There are no link to
their views either. This will implement that last part.

**Task:** task-2697901

Signed-off-by: Julien Alardot (jual) <jual@odoo.com>

**Description of the issue/feature this PR addresses:** Adding the Romanian reports links in the menu

**Current behavior before PR:** no access to the romanian reports

**Desired behavior after PR is merged:** Access to the romanian reports in accounting

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-21 13:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85008).

2022-04-28 10:27 UTC, william-andre commented on addons/l10n_ro/i18n/ro.po
> +msgstr ""
Maybe we can translate these? It is not on Transifex yet.
Otherwise this file is useless

2022-04-28 10:27 UTC, william-andre commented on addons/l10n_ro/data/account.account.tag.csv
> +account_tag_0,Intangible Assets,accounts
I'm not sure why the tags are needed

2022-05-19 10:13 UTC, william-andre requested changes

2022-05-19 10:13 UTC, william-andre commented on addons/l10n_ro/data/account_tax_report_data.xml
> +        <field name="name">TAX BASE TRADE WITHIN AND OUTSIDE THE EU</field>
This doesn't seem to be translated

2022-05-19 10:13 UTC, william-andre commented on addons/l10n_ro/data/account_tax_data.xml
> +        <field name="name">VAT collected 0% Goods</field>
This doesn't seem to be translated

2022-05-19 10:13 UTC, william-andre commented on addons/l10n_ro/data/account_reconcile_model_template_data.xml
> +        <field name="name">Operations being clarified</field>
This doesn't seem to be translated

2022-10-25 08:31 UTC, jco-odoo commented on addons/l10n_ro/__manifest__.py
> +        'l10n_multilang',
No way in stable @JulienAlardot

2023-05-22 06:52 UTC, closed without merging