[FIX] stock_picking_batch: Add multicompany rule for batch picking
odoo/odoo pull request #85343
Opened 2022-02-24 16:04 UTC by robinengels

Current behavior:
All batch transfers are shown in the tree view. But only the one for the allowed companies should be in the list

Steps to reproduce:
- Be in a multicompany environnement
- Activate batch picking
- Go in Inventory/Batch transfers

opw-2752617
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-24 16:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85343).

2022-02-25 09:42 UTC, adwid requested changes
Could you retarget the fix to 13.0 ?
Also, I think all the multi-company feature is missing here
You should also add some security rules
(Otherwise, thanks to the URL, the user can still access to the batch picking of another company)

2022-03-01 08:56 UTC, adwid requested changes
I saw many multi-company rules with the field `global` defined. However, considering its definition, it does not look like necessary (except to improve the clarity ?):
https://github.com/odoo/odoo/blob/8bf4b8e015fa61f3929dbb8f1d81e1127272cfbb/odoo/addons/base/models/ir_rule.py#L256-L258
Besides my comments, lgtm. 
I prefer to let Stock-team check and validate the review since it's a security fix

2022-03-01 08:56 UTC, adwid commented on addons/stock_picking_batch/security/stock_security.xml
> +        <field name="model_id" search="[('model','=','stock.picking.batch')]" model="ir.model"/>
```suggestion
        <field name="model_id" ref="model_stock_picking_batch"/>
```
I think it's cleaner like this

2022-03-01 08:56 UTC, adwid commented on addons/stock_picking_batch/views/stock_picking_batch_views.xml
> +        <field name="domain">[('company_id', 'in', allowed_company_ids)]</field>
It becomes useless because the IR rule will already provide that domain

2022-03-14 07:42 UTC, robinengels commented
@odoo/rd-logistics ping

2022-03-16 08:49 UTC, ticodoo reviewed
Can you rename the file name to `stock_picking_batch_security.xml`? That way it will be consistent with how the other security files are named.

Other than my global=true comment, LGTM.

2022-03-16 08:49 UTC, ticodoo commented on addons/stock_picking_batch/security/stock_security.xml
> +    </record>
Can you please add in `<field name="global" eval="True"/>`?

2022-03-16 08:56 UTC, ticodoo commented on addons/stock_picking_batch/security/stock_security.xml
> +    </record>
Actually nevermind, it looks like `<field name="global" eval="True"/>` isn't added anymore. So just the file rename please :sweat_smile:

2022-03-16 09:33 UTC, ticodoo commented
Thanks!

@robodoo r+

2022-03-16 11:31 UTC, closed without merging