[FIX] l10n_it_edi_sdicoop: adapt user registration on settings
odoo/odoo pull request #85429
Opened 2022-02-25 15:59 UTC by dbkosky

To properly register account_edi_proxy_client.user when saving the res
config settings page, the radio buttons needed to be modified, and the
'register' button was adapted to be a checkbox instead.

2022-02-25 16:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85429).

2022-02-25 16:15 UTC, dbkosky commented
@jco-odoo

2022-02-25 17:13 UTC, jco-odoo requested changes

2022-02-25 17:13 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
> +                                        By clicking this button, I accept that Odoo may process my invoices.
It is a check box now

2022-02-25 17:13 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +    edi_proxy_current_state = fields.Char(compute='_compute_edi_proxy_current_state')
l10n_it_...

2022-02-25 18:25 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/account_edi_format.py
> +        if not self._get_proxy_user(move.company_id) and not self.env['ir.config_parameter'].get_param('account_edi_proxy_client.demo') == 'demo':
we should remove this, but put "demo" user in data instead of demo

2022-02-25 18:32 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +            pass
makes no snse

2022-02-25 18:32 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +        for config in self:
In the inverse, we should filter on the ones set to True

2022-02-27 19:02 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +                ('company_id', '!=', config.company_id.id),
```suggestion
                ('company_id', '!=', config.company_id.id),
                ('id_client', '!=', 'demo')
``` @dbkosky

2022-02-27 19:11 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +                ('company_id', '!=', config.company_id.id),
However you would need to set that other demo company is unregistered.

2022-02-27 19:15 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
> +                                        Saving this change will direct all companies on this database to this use this configuration.
to use this configuration.

2022-02-28 07:06 UTC, jbw-odoo approved these changes

2022-03-03 15:17 UTC, jco-odoo commented on addons/l10n_it_edi_sdicoop/models/res_config_settings.py
> +                    return
@dbkosky Could we remove this last return and put a newline?  (it would avoid ci/style errors in master)  Otherwise, it works fine.

2022-03-03 17:09 UTC, jco-odoo commented
@robodoo r+

2022-03-03 19:00 UTC, closed without merging