[FIX] l10n_it_edi_sdicoop: fix access rights so demo user can send in…
odoo/odoo pull request #85427
Opened 2022-02-25 15:30 UTC by jco-odoo

…voices

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-02-25 15:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85427).

2022-02-25 22:02 UTC, william-andre requested changes
I suppose that there is sensitive data on that model that regular users shouldn't be able to read?

If not, update the access rights instead.

Also, the commit message is pretty bad; you don't want to fix it for the demo, but for any user that is not database administrator...

2022-02-25 22:02 UTC, william-andre commented on addons/l10n_it_edi_sdicoop/models/account_edi_format.py
> +        proxy_users = self.env['account_edi_proxy_client.user'].sudo().search([('edi_format_id', '=', self.env.ref('l10n_it_edi.edi_fatturaPA').id)])
Please try to reduce the scope of the sudo environment

2022-02-25 22:18 UTC, jco-odoo commented on addons/account_edi_proxy_client/models/account_edi_format.py
> +        return company.sudo().account_edi_proxy_client_ids.filtered(lambda u: u.edi_format_id == self)
Maybe, but the easiest way to solve it as the proxy client user is only accessible by base.group_system.

2022-02-25 22:22 UTC, jco-odoo commented on addons/account_edi_proxy_client/models/account_edi_format.py
> +        return company.sudo().account_edi_proxy_client_ids.filtered(lambda u: u.edi_format_id == self)
Anyways, if the user gets an access error, the cron can still take it.

2022-02-25 22:23 UTC, william-andre commented on addons/account_edi_proxy_client/models/account_edi_format.py
> +        return company.sudo().account_edi_proxy_client_ids.filtered(lambda u: u.edi_format_id == self)
> Maybe, but the easiest way to solve it as the proxy client user is only accessible by base.group_system.

Not sure I understand what you mean

2022-02-25 22:25 UTC, jco-odoo commented on addons/account_edi_proxy_client/models/account_edi_format.py
> +        return company.sudo().account_edi_proxy_client_ids.filtered(lambda u: u.edi_format_id == self)
That if we do not sudo the record, a regular user can not read it.

2022-02-25 22:28 UTC, william-andre commented on addons/account_edi_proxy_client/models/account_edi_format.py
> +        return company.sudo().account_edi_proxy_client_ids.filtered(lambda u: u.edi_format_id == self)
That I know... It doesn't mean that you should just sudo blindly any record causing an issue like that

2022-02-28 10:34 UTC, jco-odoo commented
@william-andre Still WIP, but I think this principle is better where we only need to ask explicitly when the invoicing user wants to read the private fields or write to them.

2022-02-28 11:18 UTC, william-andre commented
It looks a lot better indeed

2022-02-28 15:58 UTC, jco-odoo commented
@william-andre tested by @dbkosky and me and I checked again the cases where it needs to write or check refresh_token/private_key, so this should be good to merge.

2022-02-28 17:22 UTC, william-andre approved these changes
@robodoo r+

2022-02-28 18:08 UTC, closed without merging