[FIX] mail: allow user to delete other's attachments again
odoo/odoo pull request #85469
Opened 2022-02-28 08:38 UTC by phenix-factory

Before this PR, only author of the message and admin could delete attachments
inside the chatter.
This behavior is now restricted to the channels and allow users to delete
attachments inside the chatter.

task-2753295

2022-02-28 08:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85469).

2022-02-28 12:54 UTC, phenix-factory commented
@seb-odoo @alexkuhn Little bug fix

2022-02-28 14:33 UTC, alexkuhn requested changes

2022-02-28 14:33 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_image/tests/attachment_image_tests.js
> +import { insertAndReplace, link } from '@mail/model/model_field_command';
Apparently unused in this file.

2022-03-01 07:09 UTC, phenix-factory commented on addons/mail/static/src/components/message/tests/message_tests.js
> +            }),
done !

2022-03-01 10:48 UTC, seb-odoo commented on addons/mail/static/src/models/attachment/attachment.js
> +            if (this.messages.length && this.originThread && this.originThread.model == 'mail.channel') {
`===`

2022-03-01 10:48 UTC, seb-odoo commented on addons/mail/static/src/models/attachment/attachment.js
> +            if (this.messages.length && this.originThread && this.originThread.model == 'mail.channel') {
Also this is not correct here, we need an extra field `isDeletable` instead of re-using `isEditable` as we are now splitting the 2 behaviors.

2022-03-01 10:50 UTC, seb-odoo commented on addons/mail/static/src/models/attachment/attachment.js
> +            if (this.messages.length && this.originThread && this.originThread.model == 'mail.channel') {
Actually looks like `isEditable` does not really make sense by itself on attachment, it's just badly named in the first place?

2022-03-11 10:38 UTC, seb-odoo approved these changes
@robodoo r+

2022-03-11 11:15 UTC, alexkuhn approved these changes

2022-03-11 11:57 UTC, closed without merging