[FIX] sale_margin: Correct computation of margin in groupby
odoo/odoo pull request #85689
Opened 2022-03-02 15:14 UTC by abz-odoo

For now the sale margin is incorrectly computed in group by

opw-2767397

2022-03-02 15:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85689).

2022-03-03 10:47 UTC, Feyensv requested changes
Nope, it's the amount of margin, you don't want the average when you are grouping.
In 14+, it might make sense for the `margin_percent` field, but the margin should stay as a `sum` when grouped.

Example:
If I group by company, I want to see 200K total price, with 15K total margin, not 15K/number of SO

2022-03-03 11:02 UTC, abz-odoo commented
Hello @Feyensv thanks for your feedback
@bouvyd  what do you think about it ?

2022-03-03 13:25 UTC, bouvyd commented
@abz-odoo Victor is right, only the percent field (margin_percent) should be averaged; margin _amounts_ should be summed (which is the default behaviour)

si indeed 14.0+ only

2022-03-03 15:27 UTC, closed without merging