[REF] mail: AttachmentViewer, review and simplify scss
odoo/odoo pull request #85772
Opened 2022-03-03 15:18 UTC by Brieuc-brd

Part of the overall v16 SCSS optimization/restyle, task-2704984

task-2781992

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-03 15:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85772).

2022-03-07 12:56 UTC, Brieuc-brd commented
@stefanorigano 👋 
This PR is ready for review 👍

2022-03-07 15:30 UTC, stefanorigano requested changes

2022-03-07 15:53 UTC, stefanorigano requested changes
@Brieuc-brd , just a couple of minor remarks.
When done you can remove the draft state and ping [@]seb for tech. review.

👍

2022-03-07 15:53 UTC, stefanorigano commented on addons/mail/static/src/components/attachment_viewer/attachment_viewer.xml
> +                        <div class="o_AttachmentViewer_headerItem d-flex align-items-center ms-4 me-2 o_AttachmentViewer_icon">
Move utility-classes **after** odoo's custom classes

2022-03-07 15:53 UTC, stefanorigano commented on addons/mail/static/src/components/attachment_viewer/attachment_viewer.xml
> +                    <div class="o_AttachmentViewer_headerItem d-flex align-items-center mx-2 o_AttachmentViewer_name">
Again, move utility-classes **after** odoo's custom classes... could you check all the other lines?

2022-03-16 13:55 UTC, alexkuhn reviewed
LGTM Otherwise

2022-03-16 13:55 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_viewer/attachment_viewer.scss
> +.o_AttachmentViewer_buttonNavigationNext > .fa {
Don't deal with CSS specificity. Introduce classname `.o_AttachmentViewer_buttonNavigationNextIcon` on this element, and just target with this classname.

2022-03-16 13:55 UTC, alexkuhn commented on addons/mail/static/src/components/attachment_viewer/attachment_viewer.scss
> +.o_AttachmentViewer_buttonNavigationPrevious > .fa {
Same remark but with `.o_AttachmentViewer_buttonNavigationPreviousIcon`.

2022-03-16 14:13 UTC, alexkuhn commented
(and resolve conflicts)

2022-03-17 12:45 UTC, alexkuhn approved these changes
@robodoo r+

2022-03-17 15:08 UTC, alexkuhn commented
@robodoo rebase-ff

2022-03-17 15:08 UTC, robodoo commented
Merge method set to rebase and fast-forward

2022-03-17 18:29 UTC, closed without merging