[FIX] payment: mandate deleted when payment fail
odoo/odoo pull request #85827
Opened 2022-03-04 12:13 UTC by robinengels

Current behavior:
When using Sepa direct debit if you are not logged in the payment fails but the mandate is still saved when it should be deleted

Steps to reproduce:
- Activate Sepa Direct Debit payment method (Test mode)
- Create a sale order and generate a payment link
- Open the link in an incognito browser page
- Check that you are not connected
- Try to pay with Sepa Direct Debit (ex:FR76 3000 6000 0112 3456 7890 189)
- The Payment Mandate is Posted when it should be deleted

opw-2754505

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-04 12:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85827).

2022-03-09 13:47 UTC, agr-odoo commented
Not sure about this:
- `sdd_mandate_id` is not in `payment` module so this would fail in the `except` case whenever `payment_sepa_direct_debit` is not installed
- Then if we don't want to create/use a mandate for public users, why do we create one and then delete when the transaction fails? 

Imho it would be better to add a check when creating the mandate
https://github.com/odoo/enterprise/blob/0a85eb01992a7fc9d1a7586c58042b1ece4441cc/payment_sepa_direct_debit/controllers/main.py#L87
something like
```python
if (request.uid == request.env.ref('base.public_user').id):
    raise UserError(_("You need to be logged in to use this payment method."))
```
Maybe @arj-odoo could give us useful info too

2022-03-09 15:12 UTC, arj-odoo commented
Hello. I can confirm that you can't use sdd mandate feature in `payment` module. You must make your change in sepa_direct_debit associated modules. (e.g. payment_sepa_direct_debit).
You could either restrict the mandate creation to portal/internal users or create a partner on the fly and assign the mandate to him. I let @AntoineVDV answer as he is in charge of the payment module.

2022-03-09 18:25 UTC, AntoineVDV commented
Hello, could you clarify the problem description a bit? I had to dig into the ticket and the attached videos to figure the issue out. :sweat_smile: 

So, the problem seems to be: a customer tries to pay something with SEPA while being logged out, an AccessError is raised somewhere along the way, and the mandate (maybe also the token) is still saved. I guess that the error is raised as soon as we try to read on the token [here](https://github.com/odoo/odoo/blob/15.0/addons/payment/controllers/portal.py#L260) without sudo, after creating it in sudo.

IMO, we shouldn't try to delete the mandate if something fails, and certainly not from `payment`'s code as it violates the modularity. Instead, we should prevent SEPA from being made available to the public user altogether. This could typically be done through an override of `_get_compatible_acquirers` on the `payment.acquirer` model. But, even though the use-case is currently specific to SEPA, I believe we should work in the `payment` module to fix the issue and avoid running into it again with new payment modules exhibiting the same use-case. The easiest way to achieve this is to add a new filter making use of the `_is_tokenization_required` method in `_get_compatible_acquirers`:

```py
compatible_acquirers = self.env['payment.acquirer'].search(domain)

# Prevent the public user from saving a token for acquirers that require tokenization.
if request.env.user._is_public():
    compatible_acquirers = compatible_acquirers.filtered(
        lambda acq: not self._is_tokenization_required(provider=acq.provider)
    )

return compatible_acquirers
```

2022-03-10 10:41 UTC, AntoineVDV commented on addons/payment/models/payment_acquirer.py
> +                lambda acq: not self._is_tokenization_required(provider=acq.provider)
```suggestion
                lambda acq: not self._is_tokenization_required(provider=acq.provider, **kwargs)
```
Should not be necessary but better to be safe than sorry.

2022-03-10 14:34 UTC, AntoineVDV reviewed
Don't forget to:
1. Flag your PR as "ready for review" when the Bugfix team considers it ready.
2. Re-request a review with the :recycle: button to let reviewers know that you're ready for a new pass of review.

2022-03-10 14:34 UTC, AntoineVDV commented on addons/payment/models/payment_acquirer.py
> +        if self.env.user._is_public():
```suggestion
        # Prevent the public user from saving a token for acquirers that require tokenization.
        if self.env.user._is_public():
```

2022-03-10 14:48 UTC, AntoineVDV approved these changes
Don't forget to update both the commit title+message and the PR title+description to:
1. Make the issue clear: how to reproduce; what is the error; etc.
2. State what your commit is changing to the code. For example, `exclude acquirers requiring tokenization when logged out`.

2022-03-10 16:25 UTC, AntoineVDV requested changes
Please find in bold below the unresolved requests. In particular, the SEPA Direct Debit payment option is not a payment method, it's an acquirer. It's confusing to mix the two.

- Make the issue clear: how to reproduce; **what is the error**; etc.
- State what your commit is changing to the code. For example, "**[FIX] payment: exclude acquirers requiring tokenization when logged out**"

2022-03-11 10:32 UTC, robinengels commented
@AntoineVDV This should be good now, sorry if I didn't understand what you wanted me to do exactly

2022-03-11 12:22 UTC, AntoineVDV approved these changes
:+1:

2022-03-14 17:40 UTC, closed without merging