[FIX] web: aggregate cells are not formatted with the monetary digits precision
odoo/odoo pull request #85851
Opened 2022-03-04 16:13 UTC by hubvd

**Steps to follow**

  - Use a currency with more than 2 digits of precision
  - Create a journal entry
  - Add a few lines
  -> The sum is not formatted to the correct precision

**Cause of the issue**

  The currency is not taken into account when calling formatMonetary

opw-2753312

2022-03-04 16:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85851).

2022-03-07 08:42 UTC, sdegueldre requested changes
Missing a test

2022-03-11 11:36 UTC, hubvd commented on addons/web/static/src/js/views/list/list_renderer.js
> +                }
What if I format with the currency only if all records share the same currency ?

2022-05-05 12:47 UTC, hubvd commented
Hey @aab-odoo,
I updated this PR according to the task. What do you think ?

2022-05-06 06:27 UTC, aab-odoo reviewed
It's not obvious to me that this should be done in v14. I would rather say this is an improvement for master. In any cases, I think the change is good functionally speaking. What matters the most here is the tests, as we are currently rewriting the list view from scratch. So having this new behavior fully tested is the only way to ensure that we won't break it directly. From that perspective, there's still a bit of work to do.

2022-05-06 06:27 UTC, aab-odoo commented on addons/web/static/src/js/views/list/list_renderer.js
> +                    if (currencyField && self.state.data.length) {
self.state.date.length could be checked in the first if

2022-05-06 06:27 UTC, aab-odoo commented on addons/web/static/src/js/views/list/list_renderer.js
> +                            return $cell.text('N/A').tooltip({
should be translatable -> _t("N/A")

2022-05-06 06:27 UTC, aab-odoo commented on addons/web/static/tests/views/list_tests.js
> +         this.data.res_currency.records.forEach(currency => {
you can modify data in place, each  test receives a deep copy

2022-05-06 06:27 UTC, aab-odoo commented on addons/web/static/tests/views/list_tests.js
> +
there should be a test for the N/A case, and one for the case where there is a digits attrs on the column

2023-02-01 15:29 UTC, closed without merging