[FIX] web: add optional arg to disable escape of message
odoo/odoo pull request #85914
Opened 2022-03-07 10:46 UTC by admi2806

How to reproduce the bug ?

- install Purchase, Studio modules
- enable Purchase Agreements in Settings
- in Purchase, go to Orders > Purchase Agreements
- in the purchase agreement creation form, enable studio and modify the
"Confirm" button such that an agreement is requested.
- make sure to remove your user from the approval group OR switch to a
different user which is not part of the approval group.
- Go back to the purchase agreement creation form and try to confirm a
new agreement.

What is the bug ?

When you want to display a notification which contains html code, the
html tags will be partially escaped. A consequence of that is the fact
that the tags will not be considered correctly and will be displayed in
the message of the notification instead of being not visible and
formatting the message.

opw-2780867

Signed-off-by: Adrien Minet <admi@odoo.com>
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-07 10:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/85914).

2022-03-07 10:47 UTC, admi2806 commented
This PR is related to this one: https://github.com/odoo/enterprise/pull/25036

2022-03-07 10:56 UTC, abz-odoo requested changes

2022-03-07 10:56 UTC, abz-odoo commented on addons/web/static/src/legacy/utils.js
> +                    message = _.escape(message)
Small changes !
```suggestion
                if (escape) {
                    message = _.escape(message);
```

2022-03-09 07:25 UTC, abz-odoo requested changes

2022-03-09 07:25 UTC, abz-odoo commented on addons/web/static/src/legacy/utils.js
> +                if(escape) {
```suggestion
                if (escape) {
```

2022-05-06 13:57 UTC, abz-odoo commented
new pr: https://github.com/odoo/enterprise/pull/27058

2022-05-09 06:49 UTC, abz-odoo commented
fixed in: https://github.com/odoo/enterprise/pull/27058

2022-05-09 07:17 UTC, simongoffin commented
https://github.com/odoo/enterprise/pull/27058

2022-05-09 07:17 UTC, closed without merging