[FIX] hr_holidays : deduct correct # days on allocation
odoo/odoo pull request #86101
Opened 2022-03-09 10:54 UTC by auon-odoo

Steps :
Create, confirm and validate 2 overlapping leave allocations :
	> Type : T
	> Duration : 5 days
Create, confirm and approve a time off request in the overlapping period :
	> Type : T
	> Duration : 10 days
Go to the allocations.

Issue :
They have respectively 0 and 10 days taken.

Cause :
hr_leave.holiday_allocation_id is m2o, so 2 allocations cannot be
attributed to the same leave request.
_compute_from_holiday_status_id() sets the first valid (in terms of
validity dates) allocation to this field, without comparing the
number of leave days of the allocation and the request.

Fix :
Compare it. If no allocation has sufficient number of days, but their
sum is enough, ask the user to split them.

opw-2781530

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-09 10:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/86101).

2022-03-09 11:14 UTC, phwa-odoo commented on addons/hr_holidays/models/hr_leave.py
> +                        + "Please split your request to fit in their number of days.") % (len(number_of_days), number_of_days))
The string needs to be translated and added to the .pot file 
https://www.odoo.com/documentation/15.0/developer/misc/i18n/translations.html
```suggestion
                        raise UserError(_("You have %(count)s allocations for those type and period. They have respectively %(count)s days. " +\
                        "Please split your request to fit in their number of days.", count=number_of_days)
```

2022-03-09 12:45 UTC, auon-odoo commented
Coucou @kba-odoo,
Can you review this please? :)

2022-03-14 08:33 UTC, kba-odoo requested changes

2022-03-14 08:33 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +                    if sum(number_of_days) >= self.number_of_days:
```suggestion
                    if sum(number_of_days) >= leave.number_of_days:
```

2022-03-14 08:33 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +                        raise UserError(_("You have %(count)s allocations for those type and period. They have respectively %(list)s days.\nPlease split your request to fit in their number of days.",
Raising a UserError in a compute method is *meh*. It should be done in an `api.constrains` instead

2022-03-24 13:55 UTC, kba-odoo commented
robodoo r+

2022-03-24 14:02 UTC, auon-odoo commented
@kba-odoo danke schön!

2022-03-28 09:28 UTC, kba-odoo commented
robodoo r+

2022-03-28 20:04 UTC, closed without merging