[FIX] base: do not duplicate spaces for t-foreach
odoo/odoo pull request #86427
Opened 2022-03-15 09:35 UTC by Gorash

The duplication was used to have a cleaner html page source code by
aligning the <script t-foreach/> for example. However, this behavior
seems difficult to understand and use. Additionally the behavior can be
done with a <t> tag and placing the script inside.

2022-03-15 10:16 UTC, bso-odoo approved these changes
This fixes my problem from https://github.com/odoo/odoo/pull/86199.
Thanks for the test it really helped understanding the actual impact of the change.

2022-03-16 09:55 UTC, rco-odoo requested changes
Please reformulate the commit message, it looks quite obscure to me.
State exactly what changes.
Maybe show the change with an example.

2022-03-16 10:07 UTC, rco-odoo approved these changes
Besides the commit message, the patch simplifies the code and make the convention much simpler to understand and use.

2022-03-18 15:45 UTC, rco-odoo commented
@robodoo r+

2022-03-18 17:55 UTC, closed without merging