[FIX] sale_order, l10n_de: fix the pro forma invoice report
odoo/odoo pull request #86651
Opened 2022-03-18 11:03 UTC by amay-odoo

This fix should solve the issue with the pro forma invoice not having the right title in the document file

Current behavior before PR:
- In the pro-forma invoice, the document title is either quotation or sale order depending on the state of the record

Desired behavior after PR is merged:
- display the pro-forma invoice in the document title to indicate that it's a pro-forma invoice

opw-2790124

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-18 11:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/86651).

2022-03-24 16:37 UTC, william-andre requested changes
Please include this in the computation of `l10n_de_document_title` instead

2022-03-24 16:48 UTC, amay-odoo commented
Okay, I will do that, Thank you so much

2022-03-24 19:32 UTC, william-andre commented
You can keep this same PR and force push. It's better to keep track of the required changes; no need to close it in the meantime :wink:

2022-05-05 08:40 UTC, alt-odoo commented
@amay-odoo 

Can you finalize this ?

2022-05-30 10:08 UTC, closed without merging

2022-05-30 10:43 UTC, william-andre commented
@amay-odoo Any reason for closing this PR? Please always give the reason of closing when you do it