[FIX] website: Don't override form value if already set
odoo/odoo pull request #86753
Opened 2022-03-21 11:36 UTC by nboulif

Steps to Reproduce:

  - Install website_form_project
  - Edit homepage
  - Add a form
  - Switch action to `Create a Task`
  - Select any project then save
  - Edit homepage again
  - Click on form and directly save
  - Edit homepage again and click on form

Issue:

  Project is not set.

Cause:

  Conflict with new feature `fill-with` and the fix
  https://github.com/odoo/odoo/pull/68634 .

Solution:

  Revert https://github.com/odoo/odoo/pull/68634 .

opw-2746377

2022-03-21 11:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/86753).

2022-03-23 13:31 UTC, nboulif commented
ping @rdeodoo

2022-03-28 09:57 UTC, rdeodoo requested changes
I didn't review this one directly when you pinged me because I smelt something bad.

I don't really know what to say.
You are reverting a commit which has a very clear history, reasoning and step to reproduce written in it: 
- it was created in 13.0 with https://github.com/odoo/odoo/pull/50745 but not forward ported
- it was then explicitly cherry-picked and merged in 14.0 up to master at https://github.com/odoo/odoo/pull/68634 as the bug was not only in 13.0
- the explanation is clear: go to a job form, see that the view's arch in DB doesn't have a value for the `job_id` field, and see that the DOM has one (added in js). Then enter edit mode, save the field, the value is now saved in the DB and shared for every job forms, meaning all application will submit for the same job.

You just reverted that commit without even checking.. You re-introduced the bug.. :grimacing:

2022-03-28 10:07 UTC, qsm-odoo commented
@nboulif BTW we are already bugfixing code around what you explain with https://www.odoo.com/web#id=2715201&menu_id=4720&cids=1&action=4043&model=project.task&view_type=form (I just have to review and merge), maybe related? :shrug:

cc @rdeodoo

2022-03-28 12:06 UTC, nboulif commented
@qsm-odoo Thanks for the heads-up! I just tried the following flows with your fix and looks good;
- Alter an application form (/jobs -> select any job offer -> Apply Now) then save. Switch to another application form (not the one edited) then send. => The right job_id is sent.
- Add a form, set action to `Create a Task`, select a project then save. Edit again, then save. => Project still set.

2022-03-28 12:06 UTC, closed without merging