[FIX] website: properly stop widgets before removing snippet.
odoo/odoo pull request #86751
Opened 2022-03-21 11:19 UTC by detrouxdev

__About__
This fixes the slow dynamic snippet removal but an underlying issue still exists:
Should `_callForEachChildSnippet` enable editors for snippets inside
a [contenteditable=false] element

_Commit Message_
```
Prior to this commit, removing a snippet while its widget was still
active could lead to slow removal as editors would be created for its
inner content.

Stopping a widget before removing it is good practice as it will clear
the DOM from any content it may leave behind and will prevent snippet
editor to be created for its dynamic inner content.

task-2781418

```

2022-03-21 11:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/86751).

2022-04-11 16:49 UTC, qsm-odoo requested changes
- Code too different in 13.0 to fix potential bugs there?
- Commit message:
    - You say "website" when you touch "web_editor", not reviewed :/
    - No point at the end of the title
    - "before removing snippets" or "before removing a snippet"
    - Before the task-XXX add "Closes YYY" with YYY being the github issue this task is all about (we'll forget about not creating editor for non editable areas for now, this is a whole other generic issue, I'll leave that in my TODO list).
    - Nitpicking: Your commit message is good and explain the problem clearly but in one year, I may not know what this was exactly about: I would add another paragraph "For example, [...]" mentioning how the issue was detected.

2022-04-11 16:49 UTC, qsm-odoo commented on addons/web_editor/static/src/js/editor/snippets.editor.js
> +        });
Even if the editor team broke that rule at some places I think, the "widget start and stop" notions are not supposed to be something the editor knows about.

As an example, see how widgets are destroyed before saving: `ready_to_clean_for_save`

2022-04-28 07:33 UTC, detrouxdev commented
@qsm-odoo I don't know if this is what you had in mind? The other possibility is to override the `SnippetEditor` 's `removeSnippet` in the website module. Could also catch the `will_remove_snippet` event on something like `edit.js` to `trigger_up` a `widgets_stop_request`.

I'm unsure about adding a snippet related event on the website_public_root, since it's kind of disconnected from the editor framework but it probably make sense.

2022-04-28 12:22 UTC, qsm-odoo commented
> The other possibility is [...]

@detrouxdev Good thinking but anything is fine to me here :+1: 

@robodoo r+

2022-04-28 13:23 UTC, closed without merging