[FIX] account: wrong destination account id in internal transfer
odoo/odoo pull request #86846
Opened 2022-03-21 17:25 UTC by agr-odoo

Setup at least 2 bank accounts [ACC1] and [ACC2]
Setup a Journal [BNK1] with [ACC1]
Setup a second journal [BNK2] with [ACC2]
Create an Internal Transfer from [BNK1] to [BNK2]
Save and confirm

partner_bank_id will be choosen from the Journal, for inbound
payment, ([ACC1]) or it from one of the company bank accounts in
outbound payment, so either [ACC1] or [ACC2]
This is wrong as [ACC2] should be used because defined on [BNK2]

opw-2794081

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-21 17:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/86846).

2022-04-15 08:13 UTC, Levizar requested changes
At first sight, it seems completely legit to me.

2022-04-15 08:13 UTC, Levizar commented on addons/account/models/account_payment.py
> +                            .filtered(lambda x: x.company_id.id in (False, pay.company_id.id))._origin
```suggestion
            elif pay.is_internal_transfer:
                pay.available_partner_bank_ids = pay.destination_journal_id.bank_account_id
            else:
                pay.available_partner_bank_ids = pay.partner_id.bank_ids\
                        .filtered(lambda x: x.company_id.id in (False, pay.company_id.id))._origin
```

2022-04-15 08:13 UTC, Levizar commented on addons/account/models/account_payment.py
>              else:
```suggestion
```

2022-04-15 13:47 UTC, agr-odoo commented
@Levizar Done, thanks

2022-04-19 14:53 UTC, Levizar requested changes

2022-04-19 14:59 UTC, agr-odoo commented on addons/account/models/account_payment.py
> +            elif  pay.is_internal_transfer:
how I didn't notice this... :thinking: 
fixed, thanks for noticing :+1:

2022-04-25 09:19 UTC, Levizar approved these changes
LGTM

2022-04-25 09:30 UTC, william-andre approved these changes
@robodoo r+

2022-04-25 11:32 UTC, closed without merging