[FIX] product: Wrong variants filtering
odoo/odoo pull request #87096
Opened 2022-03-23 15:57 UTC by MiniLau

Supplier pricelists doesn't restrict the choice of the variant to the
variants of the current product template (in the view).

To reproduce the issue:
1. Create a product with different variant
2. Install 'purchase' and go to the 'purchase' page on a product form.
3. Create a new Supplier Pricelist (a new line).
4. In the 'product_variant' the user can select any product of the company.
We should only see the variants of the current product.

Solution: Since 14.0, the Supplier Pricelist can be edited directly from the
tree view (while in 13.0 a form was used). In this tree view, there are no filtering/domain
on the 'product_tmpl_id'. This filtering is however present in the form in 13.0
which is why the problem is present only as from 14.0. Similarly to the 13.0 form,
the 'product_variant' field doesn't allow the quick creation.

opw-2792060

2022-03-23 16:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/87096).

2022-03-25 09:21 UTC, MiniLau commented
@svs-odoo can you take a look at this as apparently you have worked on this ?

2022-04-06 13:45 UTC, adwid requested changes

2022-04-06 13:45 UTC, adwid commented on addons/product/models/product.py
> +        for record in self:
Can you rename `record` to something more specific ? (for instance `supplier`)

2022-04-12 11:59 UTC, adwid commented
Hi @ticodoo 
Could you have a look here ?

2022-04-12 15:58 UTC, ticodoo commented
LGTM! @robodoo r+

2022-04-12 16:15 UTC, ticodoo commented
Looks like the bots aren't working right now :thinking: will try again tomorrow.

2022-04-13 06:32 UTC, MiniLau commented
Shouldn't it be "up to 15.0" as it is inclusive and issue was fixed in saas-15.1 ?

2022-04-13 08:03 UTC, closed without merging