[CLA] Remove old Vauxoo's members
odoo/odoo pull request #87201
Opened 2022-03-24 15:35 UTC by luisg123v

A lot of members aren't with us  anymore, some of them for several
years.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-24 15:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/87201).

2022-03-26 17:01 UTC, luisg123v commented
FYI @mart-e

2022-03-28 07:23 UTC, mart-e requested changes
Please don't remove people that have already made commits (e.g. arturo). You can move them at the end of the file and add a "(up to 2022-03-28)" for instance

2022-04-09 17:14 UTC, luisg123v commented
Almost all members have made commits. I'm closing this.

2022-04-09 17:14 UTC, closed without merging