[FIX] website: prevent animated navbar flicker
odoo/odoo pull request #87757
Opened 2022-04-01 12:33 UTC by tdecaluwe

2022-04-01 12:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/87757).

2022-04-14 11:53 UTC, tdecaluwe commented
Note: the `this.headerHeight` update in `_toggleFixedHeader` could technically be removed altogether, since it is already set when `start` is called. However, it still makes sense and might prevent future bugs.

2022-04-15 16:59 UTC, qsm-odoo commented
Did not read much nor investigated here but I think we already moved that header height computation in that location specifically as a bug fix... not sure, but worth some code blaming :grimacing: Anyways not sure, @bvr-odoo would you mind having a look? As you already worked on that JS code, you may be the best to know what's what :+1:

2022-04-19 08:06 UTC, bvr-odoo commented
> Note: the `this.headerHeight` update in `_toggleFixedHeader` could technically be removed altogether, since it is already set when `start` is called. However, it still makes sense and might prevent future bugs.

Actually, even if the header is fixed, its height can change after the start() (e.g. scroll effect = fixed + logo height = 120px + logo height scrolled = 40px). In this case, the main padding top is not updated porperly with this commit.

2022-04-19 08:17 UTC, bvr-odoo commented
> Did not read much nor investigated here but I think we already moved that header height computation in that location specifically as a bug fix... not sure, but worth some code blaming grimacing Anyways not sure, @bvr-odoo would you mind having a look? As you already worked on that JS code, you may be the best to know what's what +1

Indeed `_updateMainPaddingTop` needs to know the correct header height at all times for a fixed header (when transitioning logo size depending on scroll position, etc.). This commit needs to be reworked and more tested

2022-04-19 09:09 UTC, tdecaluwe commented
> Actually, even if the header is fixed, its height can change after the start() (e.g. scroll effect = fixed + logo height = 120px + logo height scrolled = 40px). In this case, the main padding top is not updated properly with this commit.

@bvr-odoo Yes, this is exactly what causes (and solves) this bug. My reasoning was that, once the header is in its fixed state it should, arguably, no longer influence the scroll height of the page. The top padding merely reserves the space needed for the header, once it leaves its fixed state once again. A similar argument can be made for the `mainPosScrolled` condition. Is there perhaps a bug caused by the header height no longer updating in its fixed state?

The line could also be kept in its current place, changing it to:

```
this.headerHeight = this.fixedHeader ? this.headerHeight : this.$el.outerHeight();
```

For comparison: the previous attempt in commit 897e6f9e7b6ce294f75ccd896c5d99b4a3ec4366 also solves this bug, it takes another approach though. It explicitly corrects for the scroll height change.

2022-04-19 09:15 UTC, bvr-odoo commented
> this.headerHeight = this.fixedHeader ? this.headerHeight : this.$el.outerHeight();
Have you tested it ?

2022-04-19 12:28 UTC, tdecaluwe commented
@bvr-odoo Yes, this fixes the bug in the same manner as the current commit. Logically/semantically it probably makes most sense to put the line in `_adaptToHeaderChange`. This is also the only call site for `_updateMainPaddingTop`.

2022-04-21 08:04 UTC, bvr-odoo commented
> this.headerHeight = this.fixedHeader ? this.headerHeight : this.$el.outerHeight();

See what happens when i test your fix (video) https://www.awesomescreenshot.com/video/8513685?key=b02c18c2de3276151c6309fab02a85c5

`_adaptToHeaderChangeLoop` is used to update the main padding top during height transition of the header.
Thanks to `_adaptToHeaderChange` used in it, we are able to know the height of the header in live during the transition (even if the header is fixed, its height could change as you can see in my video).
With your commit, this is broken, we no longer get the height at time "t" of the transition but only the height that the header had at the time of the start().

2022-05-25 15:55 UTC, qsm-odoo commented
@tdecaluwe More than one month here, do you still plan on adapting this?

2022-07-22 16:23 UTC, rdeodoo commented
Hello @tdecaluwe ,

As we have now clean the website bugfix pipe, I am checking the assigned ones (from someone else than the website team).
I am a bit lazy reading the whole thread, but seeing the last message, was something done in the meantime?

> I'll discuss with @bvr-odoo, so that we can reach a decision and move this PR forward. 

Let us know the current state of the PR and the ETA, or if you want someone to take it over. Let's try to finish this one ASAP :)

2022-07-28 09:25 UTC, tdecaluwe commented
@rdeodoo This should actually be ready for review as is. As discussed with bvr, the fix was implemented using the original strategy.

A better/alternative fix might be possible in master: when the header is put in an invisible `position: sticky` container (with `visibility: visible` on the header itself that does not change size, the scroll height of the page will no longer change either. As a result, these kind of workarounds are no longer needed.

However, for stability, the workaround was chosen.

2022-07-28 15:17 UTC, qsm-odoo commented
@bvr-odoo Could you confirm everything is fine to r+ here? Thank you :+1:

2022-07-29 07:56 UTC, bvr-odoo commented
> @bvr-odoo Could you confirm everything is fine to r+ here? Thank you +1

I just tested and I see this bug. Video => https://www.awesomescreenshot.com/video/10228710
The size of the logo does not return to its unscrolled size with the `Dissapears` effect when the page has a certain height. This bug does not exist without this PR...

2022-07-29 10:18 UTC, qsm-odoo commented
@bvr-odoo Your video is probably not configured to be shared "invalid share key". Would you mind taking care of solving the issue? (use this PR), I'll assign you on the opw as well so this can move forward :+1:  Thanks :+1:

2022-07-29 10:21 UTC, bvr-odoo commented
> @bvr-odoo Your video is probably not configured to be shared "invalid share key". Would you mind taking care of solving the issue? (use this PR), I'll assign you on the opw as well so this can move forward +1 Thanks +1

ok ! (I updated the video link)

2022-08-01 14:18 UTC, bvr-odoo commented
> @bvr-odoo Your video is probably not configured to be shared "invalid share key". Would you mind taking care of solving the issue? (use this PR), I'll assign you on the opw as well so this can move forward +1 Thanks +1

@qsm-odoo It should be ok, I tested and everything works fine for me

2022-08-02 14:17 UTC, qsm-odoo requested changes

2022-08-02 14:17 UTC, qsm-odoo commented on addons/website/static/src/js/content/menu.js
> +        const scrollEl = this.el.closest('#wrapwrap');
Can't you use `getScrollingElement`?

2022-08-04 07:10 UTC, bvr-odoo commented on addons/website/static/src/js/content/menu.js
> +        const scrollEl = this.el.closest('#wrapwrap');
@qsm-odoo Indeed, I made the change

2022-08-04 08:14 UTC, qsm-odoo reviewed
@bvr-odoo Still confused about this commit:

Commit message:
> Before this commit, there was an issue with the standard scroll effect
when the page had not much scroll when the header reappears by scrolling
down.

This is talking about a standard effect problem but the OPW is about having the problem with other effect but not the standard one

Besides that, I cannot reproduce the issue with any header effect, can you explain to me how I can reproduce it? I must be missing something :grimacing:

2022-08-04 08:28 UTC, bvr-odoo commented
> @bvr-odoo Still confused about this commit:
> 
> Commit message:
> 
> > Before this commit, there was an issue with the standard scroll effect
> > when the page had not much scroll when the header reappears by scrolling
> > down.
> 
> This is talking about a standard effect problem but the OPW is about having the problem with other effect but not the standard one
> 
> Besides that, I cannot reproduce the issue with any header effect, can you explain to me how I can reproduce it? I must be missing something grimacing

Actually the sentence "to use the scroll effect 'standard' on the header" in the task, he meant the "scroll effect'

2022-08-04 08:42 UTC, bvr-odoo commented
> @bvr-odoo Still confused about this commit:
> 
> Commit message:
> 
> > Before this commit, there was an issue with the standard scroll effect
> > when the page had not much scroll when the header reappears by scrolling
> > down.
> 
> This is talking about a standard effect problem but the OPW is about having the problem with other effect but not the standard one
> 
> Besides that, I cannot reproduce the issue with any header effect, can you explain to me how I can reproduce it? I must be missing something grimacing

Indeed, there is also a problem with other header effects. I actually found a problem with the standard effect and thought it was the bug mentioned in the task but it's an other one.. So I have to complete this PR to fix the other bugs..
To test it, you must set a scrolled logo height and have a page height that causes the header to reappear at the very end of the scroll down

2022-08-05 11:26 UTC, bvr-odoo commented
@qsm-odoo It should be ok.. FYI,  BSO tested et reviewed it ...

2022-08-17 11:54 UTC, qsm-odoo commented
@bvr-odoo @bso-odoo The bug is solved but we now have this... https://watch.screencastify.com/v/ArZEt0g4XoxNobXuPsuQ I think you should test a bit more :grimacing:

2022-08-18 15:02 UTC, bvr-odoo commented
> @bvr-odoo @bso-odoo The bug is solved but we now have this... https://watch.screencastify.com/v/ArZEt0g4XoxNobXuPsuQ I think you should test a bit more grimacing

I found an other bug with the effects, I wil fix it in this PR.. I'll ping you when it's done

2022-08-19 11:04 UTC, bvr-odoo commented
> > @bvr-odoo @bso-odoo The bug is solved but we now have this... https://watch.screencastify.com/v/ArZEt0g4XoxNobXuPsuQ I think you should test a bit more grimacing
> 
> I found an other bug with the effects, I wil fix it in this PR.. I'll ping you when it's done

@qsm-odoo ok it's done

2022-08-24 14:37 UTC, qsm-odoo requested changes
@bvr-odoo Found a bug again... can you test each scroll effect carefully? :pray: I did not have to go far to find it not working (but still, it makes me lose half an hour reading the code, reading the message, building databases, ...):

1. First test: "standard" scroll effect, not enough scroll in the page to handle the image logo reduction -> this PR fixes it :partying_face: 
2. Second test: same with "fixed" scroll effect: not enough scroll in the page to handle the navbar becoming fixed (and the same logo reduction) -> still broken (you cannot scroll at all while before the PR, it was jumping up and down).

In the end, I wonder if the fix should not be done another way: you describe the problem in your commit message very well: the scroll height is changed by the navbar animation / logo animation... maybe the more logical bug fix should be that... this scroll height does not change. We could review the animations so that a placeholder element ensures the page to keep the scrollheight independently of the navbar/logo animations. That would actually lead to a better animation I think: right now, the page "jumps" once the navbar becomes fixed/the logo is shrinking (if you use the keyboard arrow to scroll for example, each key-press make the page go down by ~50px, then you reach the point where the navbar become fixed and it makes a jump of ~200px.

But we could do that in master if that proves difficult... but at least let's make it so each scroll effect allows to scroll whatever the scroll height is :pray: :grimacing:

2022-08-25 08:07 UTC, bvr-odoo commented
> 2. Second test: same with "fixed" scroll effect: not enough scroll in the page to handle the navbar becoming fixed (and the same logo reduction) -> still broken (you cannot scroll at all while before the PR, it was jumping up and down).
> 

@qsm I didn't see it because I didn't expect a different behavior on Firefox and I did my tests on Chrome where everything works fine. But it's a good lesson, I have to test this kind of thing on all browsers ... /:

2022-08-25 12:54 UTC, tdecaluwe commented
> In the end, I wonder if the fix should not be done another way: you describe the problem in your commit message very well: the scroll height is changed by the navbar animation / logo animation... maybe the more logical bug fix should be that... this scroll height does not change.

@qsm-odoo This was what I proposed earlier, and I actually got it in a nearly working state, before it was decided to use the current approach. Using the `position: sticky` attribute it is not that hard. I think this is the relevant commit https://github.com/odoo-dev/odoo/commit/3d0bcce1a155d7558ddfb71d8c249f5fb10a5361. I can't remember anymore the exact problems that I was still experiencing, but as I remember, I thought the approach was promising.

2022-08-30 11:48 UTC, bvr-odoo commented
@qsm-odoo ok I made the changes, it works as well in firefox now

2022-10-20 12:17 UTC, qsm-odoo approved these changes
Seems to work :pray: I added a comment to say we should improve in the future so that animations are smoother and would allow to remove this kind of code.

@robodoo r+

2022-10-20 14:17 UTC, closed without merging