[FIX] website_blog: Remove stars from blog description using heading
odoo/odoo pull request #88082
Opened 2022-04-06 08:47 UTC by robinengels

Current behavior:
When adding a "Heading" in the first 200 characters of a blog with /Heading,
the short description of the blog preview would have unwanted stars (*) around the heading

Steps to reproduce:
- Create a blog article
- In the first 200 characters of the blog use a heading (e.g. /Heading1)
- Go back to the blog list, the description of the new article contains unwanted stars (*)

opw-2798595
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-04-06 08:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/88082).

2022-04-06 09:33 UTC, robinengels commented
@rdeodoo

2022-04-06 09:40 UTC, rdeodoo requested changes
Thanks for the fix.

Could you make sure your commit message doesn't go over the 72 char threshold? (see link in my other comment on the review).

Nitpicking but so you know since we are at it: Can you remove the uppercase in commit title? Commit title is supposed to fit `if applied, this commit will..` :+1:

2022-04-06 09:40 UTC, rdeodoo commented on addons/website_blog/tests/test_website_blog_flow.py
> +        """ Make sure that the content of the post is correctly rendered in proper plain text. """
```suggestion
        """ Make sure that the content of the post is correctly rendered in
             proper plain text. """
```

Keep docstring under 80 char per line, see https://github.com/odoo/odoo/pull/83508#discussion_r796442104

Basically, any of:
```
def blabla1():
    """
    Fixes the id fields in import and exports, and splits field paths
    on '/'.
    """

def blabla2():
    """ Fixes the id fields in import and exports, and splits field
    paths on '/'.
    """

def blabla3():
    """ Fixes the id fields in import and exports, and splits field
        paths on '/'.
    """
```
https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation](https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation
AFAIK, do whatever you want with the first line, but for following lines (2 and +) indent it the same way.

2022-04-06 09:40 UTC, rdeodoo commented on addons/website_blog/tests/test_website_blog_flow.py
> +        self.assertEqual(self.test_blog_post.teaser, " Test Content ...")
Thank you for the test.
For tracability: we decided that it was not worth introducing code to not add the `...` when the description was < 200 char. While it doesn't makes sense to add those `...`, a blog post is not supposed to ever have less than 200 char, so it actually makes sense.

2022-04-06 09:40 UTC, rdeodoo commented on addons/website_blog/tests/test_website_blog_flow.py
> +        self.test_blog_post.write({'content': "<h2>Test Content</h2>"})
```suggestion
        self.test_blog_post.content = "<h2>Test Content</h2>"
```

2022-04-06 11:32 UTC, rdeodoo requested changes
Small one + still need to adapt the commit message (72 char, as you did for the comment (80 char))
I tried to explained the guidelines and the reasonning about that here, let me know if something sounds unclear :) https://github.com/odoo/odoo/pull/83508#discussion_r796442104

2022-04-06 11:32 UTC, rdeodoo commented on addons/website_blog/models/website_blog.py
> +from odoo.addons.website.tools import text_from_html
Alphabetical :)

2022-04-07 09:46 UTC, rdeodoo requested changes
https://github.com/odoo/odoo/pull/88082#pullrequestreview-933166239
https://github.com/odoo/odoo/pull/88082#pullrequestreview-933317243

Commit message still not updated, you need to line return at 72 char (80 like everywhere but since git tools are adding 4 space before and after, need to be 72 as explained [here](https://github.com/odoo/odoo/pull/83508#discussion_r796442104)).

2022-04-08 10:44 UTC, rdeodoo requested changes
You literally just broke the whole /blog layout with this change.
It happens but please battle-test your changes, especially in this case this is a one line fix on a single screen/page that you directly see if you test your fix.
Keep in mind that there is thousand of DBs using our software in production, and we have to be very cautious when introducing fixes (that's why it is always tricky and take some times to triple check everything).

In this case, it was easy to see tho by just opening the runbot.

![image](https://user-images.githubusercontent.com/30048408/162418675-a66bc665-eae8-4125-8db6-6429b19f4ca0.png)


Here is what you need to do IMO:
In this PR:
Do the same that [here](https://github.com/odoo-dev/odoo/blame/af650c84b36e8292158a30d51c9c951635177914/addons/website/models/mixins.py#L370) to strip the whitespace chars.

In master forward-port:
Remove the line you introduced here and the one I linked and move it to the method `text_from_html` directly, eventually with a new boolean param `collapse_whitespace`.

2022-04-08 14:12 UTC, rdeodoo approved these changes
@robodoo r+

Generally, it is either the earliest version where the bug appear (13.0 here) or master if the risk/reward is not worth it.

I guess we can make an exception here and include our latest stable version in the fix, since the risk is low and the value is low.

2022-04-08 16:36 UTC, closed without merging