[FIX] website: prevent limbo state of the navbar publish management
odoo/odoo pull request #88287
Opened 2022-04-08 11:16 UTC by dja-odoo

Currently, if a page is loading and someone quickly clicks exactly on
the on the input checkbox within publish management button of website
navbar, the checkbox (input) is toggled but the string does not change.
This happens because the checkbox is toggled before the click event on
`js_publish_btn` is bound. Ideally, the checkbox should be toggled only
based on the state of the object (whenever it's changed after a
successful RPC call) so that the information we see is correct.

This commit fixes the issue by disabling the input checkbox so that
it is toggled only after the state is changed by RPC call and not
when user simply clicks on the input.

task-2819345
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-04-08 11:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/88287).

2022-05-02 09:48 UTC, tde-banana-odoo commented
@rdeodoo

2022-05-02 19:40 UTC, rdeodoo requested changes
LGTM, thank you :+1: 
(I just pushed to fix a typo `on the on the` and changed commit title)

2022-05-02 19:40 UTC, rdeodoo commented
@robodoo r+

2022-05-02 21:11 UTC, closed without merging