[FIX] web_editor: align icon to the right
odoo/odoo pull request #89010
Opened 2022-04-19 10:26 UTC by bso-odoo

When replacing an image by a pictogram, the classes of the previous media
are copied to the new icon's `<span>`. This potentially includes the
`w-100` class which prevents the alignment from behaving correctly.

This commit removes the `w-100` class if it exists - in addition to
removing the inline `width` attribute which was done before.

Steps to reproduce:
- Drop a "Media List" block
- Replace first image by pictogram.
- Align icon to the right.
=> Icon was displayed aligned to the left.

task-2729177

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-04-19 10:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/89010).

2022-04-21 14:12 UTC, bso-odoo commented
Only the first commit must be forward-ported, not the second one.

2022-05-18 11:54 UTC, bso-odoo commented
@dmo-odoo Can someone from `web_editor` give a look ?
It might seem overkill to do it in two commits - but the summernote-specific one should not be forward-ported.

2022-05-18 12:43 UTC, dmo-odoo commented
@bso-odoo I'm not sure I understand what is going on with the two commits. Since they both modify the same line, wouldn't it be better to have two PR ? One for 14.0 with one commit for 14.0 which will not be forward ported, and one for 15.0 with one commit for 15.0 that will be properly forward ported.

2022-05-19 07:26 UTC, bso-odoo commented
The 15.0 fix will require https://github.com/odoo/odoo/pull/85600 to be merged first.

2022-07-04 09:11 UTC, qsm-odoo requested changes

2022-07-04 13:29 UTC, bso-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/media.js
> +            this.$media.removeClass('w-25 w-50 w-75 w-100');
Indeed, moved the changes from "going to pictogram" to "leaving from image".

2022-07-04 15:30 UTC, qsm-odoo approved these changes
@robodoo rebase-ff r+

2022-07-04 16:43 UTC, closed without merging