[ADD] hr_holidays : populate leaves
odoo/odoo pull request #89017
Opened 2022-04-19 10:35 UTC by Bertrand2

This commit add population to hr_leave

taskID 2823582

2022-04-19 10:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/89017).

2022-04-25 15:34 UTC, kba-odoo requested changes

2022-04-25 15:34 UTC, kba-odoo commented on addons/hr_holidays/populate/hr_leave.py
> +import logging
Not needed

2022-04-26 07:05 UTC, kba-odoo commented
robodoo r+

2022-04-26 09:02 UTC, closed without merging