[REF] mail: `MessageInReplyToView`, review and simplify scss
odoo/odoo pull request #89032
Opened 2022-04-19 12:33 UTC by Brieuc-brd

Part of the overall v16 SCSS optimization/restyle, task-2704984

task-2826587

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-04-19 14:40 UTC, Brieuc-brd commented
Hello @seb-odoo @alexkuhn 👋
This PR is ready for review 👍

cc. @stefanorigano

2022-04-19 15:16 UTC, alexkuhn requested changes

2022-04-19 15:16 UTC, alexkuhn commented on addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
> +                <span class="o_MessageInReplyToView_corner position-absolute bottom-0 d-block mb-1 pr-4 pb-2 opacity-50"/>
Style was `d-inline-block`, which is the case by default on `span`.
From my testing, `d-block` is actually useless: visual is the same with or without it.

2022-04-20 08:57 UTC, Brieuc-brd commented
@alexkuhn The branch is updated 👍

2022-04-20 10:04 UTC, alexkuhn approved these changes
@robodoo r+

2022-04-20 11:41 UTC, closed without merging