[FIX] product, point_of_sale: min, max margins not applied correctly
odoo/odoo pull request #89142
Opened 2022-04-20 13:35 UTC by momegahed

If applied, this commit will fix the following bug by using the cost of
 the product instead of the sale price

Steps to reproduce:

1- install sales
2- enable discounts, pricelists with a formula
3- create a new pricelist pl with the item i
4- set i to apply discount pr% with min margin x
5- select pl in a quotation with a product p
6- the minimum margin calculation is not respected

for example when:
p.price = 100
p.standard_price = 20
pr = 35
x = 60

the correct price on sales order should be:
max(p.price*(1-pr), p.standard_price + x)
max(65,80) = 80

the current behavior results in a price of 160

Bug:

the price is used instead of the standard_price

Fix:

use standard price

OPW-2811271

2022-04-20 13:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/89142).

2022-04-25 13:37 UTC, kitan191 commented
LGTM

2022-04-25 14:19 UTC, Feyensv requested changes
Nope, this code is 6/7 years old, we won't make such a critical change in the logic now.
This is really the kind of change to please one customer that will break all existing setups based on the current behavior.
If needed, you can modify the description of the margin fields to clarify it's the margin applied on the base price of the formula, but we certainly won't make that change now in 13.0

2022-04-25 14:55 UTC, Feyensv commented
You could make a feedback on the subject, but I'm not sure this really must be modified without more thoughts on it.  The current behavior allows some things that would be lost with your change.

Example: Currently, you could specify a discount of 10% on all products, with a minimum margin of -5 €
Product price: 100€
Pricelist Price = max(90, 100-5) = 95

Even if it's done in master, it might still break some setups, and in a particularly hidden way, since the resulting prices would be different after migration without any warning/notice/...
If we do it, it should follow the generic task process, go through PO validation, be clarified in the release notes ideally, ...

2022-04-27 09:45 UTC, closed without merging