[FIX] portal: PU can't change their company details
odoo/odoo pull request #89239
Opened 2022-04-21 09:35 UTC by MiniLau

A Portal User (PU) cannot edit his company details once they are logged in.

Step to reproduce the issue:
1. Create a new Contact (as an individual) and link him with a company
2. Create an associated PU using the "Action" button on the Contact
3. Retrieve the registration link from the User app and authenticate as the user
4. From the Portal main page, edit the company details.
You will get an error related to the edition of the company_name while no change was done.

Solution: In a previous commit(beb50e8047f4dbe148933edd52cceadb2d5cccde), a change was done
on the `company_name` input. This modification changed the JSON that was sent upon form submission.
Indeed, previously the `company_name` field was not sent (thanks to a <p>) but now this field is sent,
causing an error. To mimic the <p> behavior and keeping the idea of the first change, the attribute
"disabled" was used in the input, allowing to not send this field upon form submission.

[1]: beb50e8047f4dbe148933edd52cceadb2d5cccde

opw-2754584

2022-04-21 09:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/89239).

2022-04-25 20:54 UTC, rdeodoo requested changes
Hello @MiniLau

Thank you for your PR.

I appreciate the effort you put in the commit message:
- There is a step to reproduce :+1:
- There is a "clear" explanation of why it broke (you blamed commits and mentioned it) :+1:

It seems like you also tried to use a markdown link (:+1:), which is cool but you most likely didn't pay attention or lost a part of the message as there is no `[1]` anywhere in the commit message to points to that end-of-commit markdown link.

Given the fact you are recently new, all this is pretty cool :)
That's not your first PR where I see a detailed explanation and a history blame.
It really eases the review and the future when someone will have to blame this commit and figure why it was done.

Anyway, there is a few things to be mentioned, I thought it would be cool to share it with you:
1. About the markdown link, you wrote `[1]: beb50e8047f4dbe148933edd52cceadb2d5cccde` at the end of the message.
You should actually insert the full github link `[1]: https://github.com/odoo/odoo/commit/beb50e8047f4dbe148933edd52cceadb2d5cccde` so it clickable outside of github. That's the purpose of markdown links (and why we love to use it), see https://github.com/odoo/odoo/pull/80055#pullrequestreview-861376590 for more details
2. About that markdown link, as I said and probably a forgetting, but you have to reference that markdown link somewhere, here you wrote `Solution: In a previous commit(beb50e8047f4dbe148933edd52cceadb2d5cccde), a change was done`, instead write `Solution: In a previous commit [1], a change was done`.
3. There is a guideline for the commit title, no big deal but is makes everything looks the same so it is juste (a bit) easier to read and figure as we are used to it. And it is not a Odoo guidelines but a Git guidelines used elsewhere too.
You commit should ideally fsit the sentence `If applied, this commit will.. <Commit message>`.
In this case, you could maybe write `[FIX] portal: allow portal user to change their contact details`.
4. Since the commit message is actually terminating a sentence, don't write an uppercase, it looks weird :).
5. Your commit message should never go over 72 char / line, that's a common git (but not only) guideline.
This is not just historical, if your title go over 72 char it messes with github UI, everywhere your commit title is cropped and looks weird.
That's just the classic 80 char rule version of git, which actually becomes 72 since there is 4 whitespaces before and after the text.
You will find more info here https://github.com/odoo/odoo/pull/83508#discussion_r796442104
(You can ignore that for the HTML comment in this PR, as you are just modifying a small part of it, and then duplicating it, leave it like that, it will make the diff minimal)
6. About the step to reproduce, it feels a bit unclear, there is some UX/functionnal stuff to know to figure what you are talking about (which I do as I work on the website team). Maybe it could be a bit more "step by step".
The idea would be that a robot could follow it by just clicking where you tell him to click.
`from the User app` -> There is no user app
`Create an associated PU using the "Action"` -> Not super clear
`edit the company details` -> That's the contact details, not the company details, a bit confusing
`You will get an error related to the edition of the company_name while no change was done.` -> Not really, you have to modify something to have the error, like the phone, otherwise the save juste reload the page without any error.
That's really a nitpicking remark, just for you to know, that's already better than most commit messages which just don't include a step to reproduce, but since you are quite new, I am just sharing it with you, feel free to ignore it!

If you can fix at least 1. 2. and 5. that would be nice, thank you!

2022-04-26 08:10 UTC, MiniLau commented
@rdeodoo Thanks a lot about all these remarks, that's what I want to read so that I can improve at most as I can. Have adapted the commit message according to all your remarks.

2022-04-26 09:56 UTC, rdeodoo approved these changes
@robodoo r+

Thanks a lot, especially for the step to reproduce, way clearer imo :) (even if it is nitpicking, might as well spend 30 extra seconds to do it like you did :))

> that's what I want to read so that I can improve at most as I can

That's cool!

Note that the commit message was not "line returned" at 72 char max :) (as per point 5.)
What I meant is that it should not go past that vertical line, basically
![image](https://user-images.githubusercontent.com/30048408/165273086-9ae94418-e776-4b0f-a3d3-17c354e0aa16.png)

I push forced that myself so you can just have a look and we can ship this PR :)

2022-04-26 12:43 UTC, closed without merging