[IMP] mail: replace local_storage service by the native one
odoo/odoo pull request #89851
Opened 2022-04-27 12:30 UTC by tsm-odoo

This PR prepares the ground for the introduction of the wowlEnv in the discuss app.
Indeed, the local_storage service is not available as a service anymore but the native
one (localStorage) is used instead. In order to reduce the noise in the main PR, this
change is done separately.

task-2582313

2022-04-27 12:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/89851).

2022-04-27 15:47 UTC, alexkuhn requested changes

2022-04-27 15:47 UTC, alexkuhn commented on addons/mail/static/src/models/user_setting.js
> +            this.messaging.browser.localStorage.setItem('mail_user_setting_voice_threshold', voiceActivationThreshold);
Docstring says `voiceActivationThreshold` is `float`, and `legacy_local_storage` service applied `JSON.stringify(value)`.

The `window.localStorage.setItem(keyName, keyValue)` needs `keyValue` as string, so it's important to type-cast here.

2022-04-27 15:47 UTC, alexkuhn commented on addons/mail/static/src/models/user_setting.js
> +            const audioInputDeviceId = this.messaging.browser.localStorage.getItem(
`localStorageService.getItem` does `JSON.parse()`, which made a typecast (e.g. write `10.5` => `"10.5"`, read `"10.5"` => `10.5`).

`windowLocalStorage.getItem` simply returns string. So in example above it returns `"10.5"`.

2022-04-29 07:32 UTC, tsm-odoo commented
@seb-odoo The parseFloat was already done by the `loadLocalSettings` function. https://github.com/odoo/odoo/blob/e22a517fb756b3a3ab7a49f29f8109c42669edd3/addons/mail/static/src/models/user_setting.js#L183

2022-04-29 09:25 UTC, seb-odoo approved these changes
@robodoo r+

2022-04-29 11:12 UTC, closed without merging