[IMP] website_sale: show compare_list_price for product templates on /shop
odoo/odoo pull request #90195
Opened 2022-04-29 14:43 UTC by alpa-odoo

This PR adds the `compare_list_price` to `/shop`.

If there is a `compare_list_price` and a pricelist `fixed_price` for a product template, the `compare_list_price` will be striked through and the `fixed_price` will be displayed

task-2813257

2022-04-29 14:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/90195).

2022-04-29 14:44 UTC, alpa-odoo commented on addons/website_sale/models/product_template.py
> +from odoo.tools.translate import html_translate
optimize imports ?

2022-05-05 07:59 UTC, Williambraecky reviewed
Looking good :)

Some small comments but otherwise seems correct to me.

2022-05-05 07:59 UTC, Williambraecky commented on addons/website_sale/models/product_template.py
> +            if has_compare_list_price:
No need for a variable to store that;
```suggestion
            has_pricelist_price = pricelist_contains_templates[template.id]

            if template.compare_list_price:
```

2022-05-05 07:59 UTC, Williambraecky commented on addons/website_sale/models/product_template.py
> +            has_pricelist_price = pricelist_contains_templates[template.id]
Same here no need to store it in a variable when you can access it directly from the `dict`

2022-05-05 07:59 UTC, Williambraecky commented on addons/website_sale/models/product_template.py
>                      template_price_vals['base_price'] = base_price
We can avoid duplicating code here: 
```python
            if has_compare_list_price:
                # The base_price becomes the compare list price and the price_reduce becomes the price
                base_price = template.compare_list_price
                if not has_pricelist_price:
                    price_reduce = base_sales_prices[template.id]
                    template_price_vals.update(price_reduce=price_reduce)
            elif show_discount and has_pricelist_price:
                base_price = base_sales_prices[template.id]

            if base_price != price_reduce:
                base_price = self.env['account.tax']._fix_tax_included_price_company(
                    base_price, product_taxes, taxes, self.env.company)
                base_price = taxes.compute_all(base_price, pricelist.currency_id, 1, template, partner_sudo)[
                    tax_display]
                template_price_vals['base_price'] = base_price
```

2022-05-05 07:59 UTC, Williambraecky commented on addons/website_sale/tests/__init__.py
> +from . import test_website_sale_shop
Filename is a bit too generic, it would be better if the name was related to the content of the tests.
Especially since the test is so specific.

2022-05-23 13:52 UTC, Williambraecky requested changes
Nice work!

Thanks!

2022-05-23 13:52 UTC, Williambraecky commented on addons/website_sale/models/product_template.py
> +                                        in zip(sales_prices.items(), base_sales_prices.items())}
This feels unsafe to me, I agree there is no reason that the order from `sales_price` differs from the order from `base_sales_prices` but I would still take it into account.

```suggestion
        base_sales_prices = self.price_compute('list_price', currency=pricelist.currency_id)

        # This is a structure that contains whether a product template has a pricelist for it
        pricelist_contains_templates = {product: price != base_sales_price[product]
                                        for product, price
                                        in sales_prices}
```

2022-05-23 13:52 UTC, Williambraecky commented on addons/website_sale/models/product_template.py
> +                                        in zip(sales_prices.items(), base_sales_prices.items())}
Also side note I am not sure we actually need to create that dict, we could also just compare it when necessary (can be done once per template if you store it)

2022-05-23 13:52 UTC, Williambraecky commented on addons/website_sale/static/src/js/tours/tour_utils.js
> +    function assertProductPrice(attribute, value, productName) {
Linting: 
```suggestion
    }

    function assertProductPrice(attribute, value, productName) {
```

2022-05-23 13:52 UTC, Williambraecky commented on addons/website_sale/static/src/js/tours/tour_utils.js
> +    function assertProductPrice(attribute, value, productName) {
I like these utils function thanks.
It would be beneficial to add a note to this function that it only works for the product grid though 🙂 .

2022-06-23 12:34 UTC, Williambraecky commented
Thanks for your work and the test!
robodoo r+

2022-06-23 16:27 UTC, closed without merging

2022-08-03 08:50 UTC, Whenrow commented
Hello, In the tests of this PR, you create product of type `product`.
https://github.com/odoo/odoo/commit/112abd5b91249#diff-de036fe6cb8c7e0293ff014eb56425b962da37205e120e43e817b7b3cb2522feR14-R18
 This type is defined in the Stock module and website_sale don't depend on it. The tests pass correctly because of the post_install tag, but crash if website_sale is installed alone. (see : https://runbot.odoo.com/runbot/build/search?config_id=3&trigger_id=22&version_id=1&create_batch_id.bundle_id=1&description=Testing%20module%20website_sale). 
Do you need your products to be storable ? If yes, could you move the tests to the website_sale_stock module ? 
if not, I would create them as consumable.
Thank you :)

2022-08-03 10:59 UTC, Williambraecky commented
> Hello, In the tests of this PR, you create product of type `product`. [112abd5b91249#diff-de036fe6cb8c7e0293ff014eb56425b962da37205e120e43e817b7b3cb2522feR14-R18](https://github.com/odoo/odoo/commit/112abd5b91249#diff-de036fe6cb8c7e0293ff014eb56425b962da37205e120e43e817b7b3cb2522feR14-R18) This type is defined in the Stock module and website_sale don't depend on it. The tests pass correctly because of the post_install tag, but crash if website_sale is installed alone. (see : https://runbot.odoo.com/runbot/build/search?config_id=3&trigger_id=22&version_id=1&create_batch_id.bundle_id=1&description=Testing%20module%20website_sale). Do you need your products to be storable ? If yes, could you move the tests to the website_sale_stock module ? if not, I would create them as consumable. Thank you :)

Hello 👋 
Thanks for reporting, indeed we can change it to a consumable, sorry for the trouble.
I just created this PR https://github.com/odoo/odoo/pull/97380 to fix it :)