[REF] mail: `ThreadIcon`, review and simplify scss
odoo/odoo pull request #90524
Opened 2022-05-04 14:18 UTC by Brieuc-brd

Part of the overall v16 SCSS optimization/restyle, task-2704984

task-2843238

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-04 14:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/90524).

2022-05-05 07:16 UTC, Brieuc-brd commented
Hello @alexkuhn 👋 
This PR is ready for review.

cc. @stefanorigano

2022-05-05 08:52 UTC, Brieuc-brd commented on addons/mail/static/src/components/thread_icon/thread_icon.scss
>      width: 13px;
Good point, I updated the branch. 👍

2022-05-05 10:13 UTC, alexkuhn requested changes
There are overrides of `ThreadIcon` template, in `im_livechat` and `hr_holidays`. Some changes must also affect these modules.

2022-05-05 12:16 UTC, alexkuhn approved these changes
@robodoo r+

2022-05-05 14:22 UTC, closed without merging