[FIX] mrp_subcontracting: fix BoM structure subcontractor costs
odoo/odoo pull request #91463
Opened 2022-05-16 11:20 UTC by MerlinGuillaume

BoM Structure & Cost report has different errors:
- The product cost of a subcontractor included in a product doesn't
scale with the quantity of the product
- The BoM cost of a product composed of a subcontractor doesn't include
the subcontractor price

Steps to reproduce:
1. Install mrp_subcontracting_purchase
2. Create a product, in the Purchase tab specify Azure Interior as
vendor with price 5$
3. Create a bill of material for the product with BoM type
'subcontracting', subcontractor Azure Interior and one bolt as component
4. Go to the Bom Structure and Cost
5. The product BoM Cost doesn't include the subcontractor price (it
should be the sum of its components)
6. Increase the quantity of the product
7. The subcontractor's product cost doesn't change (it should increase
with the quantity)

Solution:
Scale the subcontractor product cost with the quantity and update the
BoM cost of a product with the subcontractor price

opw-2844482

2022-05-16 11:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91463).

2022-05-19 12:13 UTC, adwid requested changes
lgtm
could you add a test ?

2022-05-20 09:59 UTC, MerlinGuillaume commented
@adwid I ran into another issue while writing the test which I explained in the commit. Should be good now, what do you think ?

2022-05-20 09:59 UTC, MerlinGuillaume commented
@adwid I ran into another issue while writing the test which I explained in the commit. Should be good now, what do you think ?

2022-05-20 11:53 UTC, adwid commented
robodoo r+

2022-05-20 13:19 UTC, closed without merging