[FIX] http_routing: fix translation on additional modules
odoo/odoo pull request #91479
Opened 2022-05-16 13:19 UTC by MiniLau

Translations from non-standard modules on the website are not properly loaded,
thus no translation is done even though translated terms are valid (e.g.
signing a document shared).

Linked to [1]. In 14.0, the new route was already added but it contains the
same issue as in [1]. However, the issue from [1] (15.0) is not visible here
because the frontend still uses the old route. To avoid future issue, the
partial fix was backwarded from 15.0

[1]: https://github.com/odoo/odoo/pull/91478

opw-2842699

2022-05-16 13:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91479).

2022-05-25 08:42 UTC, rdeodoo requested changes
> in 14.0

In 13.0?

> the new route

What new route?

> the frontend still uses the old route

What old route? There was not change and `/website/translations/` is used in every version isn't it?

Maybe you can adapt the message to somehow include some of the explanation I detailed here https://github.com/odoo/odoo/pull/91478#pullrequestreview-981506366
Important part:
- There is no issue in the codebase before 15.0 as the `mods` is never used
- Mention the commit that (probably) broke it
- Ideally mention the (apparently) first commit that started using `mods` in 15.0

2022-05-30 16:10 UTC, MiniLau commented
@rdeodoo Is it ok for the commit message now ? I will be more careful in the future.

2022-05-30 16:36 UTC, rdeodoo approved these changes
Thanks :+1: 

@robodoo r+ see https://github.com/odoo/odoo/pull/91478#pullrequestreview-981506366

2022-05-30 16:43 UTC, rdeodoo requested changes
@robodoo r-
Let's be very cautious as this is 13.0.
Let's add a check to not break any potentiel custo calling this directly in python
```py
Routing().get_website_translations(unique, lang, mods=['whatever', 'example'])
```

2022-05-31 09:16 UTC, rdeodoo approved these changes
@robodoo r+

Thanks, better safe than sorry

2022-05-31 10:16 UTC, closed without merging