[IMP] mail: Allow to easily override message post data
odoo/odoo pull request #91526
Opened 2022-05-17 04:57 UTC by jat-odoo

Description of the issue/feature this PR addresses:

Current behavior before PR:
It is not possible to pass custom values in message post from composer.

Desired behavior after PR is merged:
It will allow to easily override and pass custom values in message post.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-17 04:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91526).

2022-05-17 05:03 UTC, jat-odoo commented
@alexkuhn Can you check it please?

2022-05-17 09:32 UTC, alexkuhn commented
Why do you need to override data in message post?

2022-05-17 09:47 UTC, jat-odoo commented
@alexkuhn I'm working on project and now i have case to pass custom values in message post.
So, Made it overridable that also help someone in future.

2022-05-17 09:55 UTC, alexkuhn requested changes
Such changes are usually better in master. Is it good for you doing it in master?

2022-05-17 09:55 UTC, alexkuhn commented on addons/mail/controllers/discuss.py
> +    def _get_alllowed_message_post_params(self):
`alllowed` => `allowed`

2022-05-17 09:55 UTC, alexkuhn commented on addons/mail/static/src/models/composer_view/composer_view.js
> +         _getPostData(composer) {
Don't need passing `composer`, you can just use `this.composer`

2022-05-17 09:55 UTC, alexkuhn commented on addons/mail/static/src/models/composer_view/composer_view.js
> +         _getPostData(composer) {
Missing `@private`

2022-05-17 09:55 UTC, alexkuhn commented on addons/mail/static/src/models/composer_view/composer_view.js
> +         _getPostData(composer) {
Should be placed alphabetically in the file, in the proper `private` category

2022-05-17 09:55 UTC, alexkuhn commented on addons/mail/static/src/models/composer_view/composer_view.js
> +         _getPostData(composer) {
`_getPostData` => `_getMessageData`

2022-05-17 12:15 UTC, alexkuhn commented
Could you please add a commit to sign CLA?
See https://github.com/odoo/odoo/blob/master/doc/cla/sign-cla.md
Thanks!

2022-05-17 13:08 UTC, jat-odoo commented
done!

2022-05-17 15:02 UTC, mart-e commented
@jat-odoo would you mind changing your github handle? The `-odoo` suffix leads to some confusions, as you have seen with Alexandre.
Good luck in your new projects :)

2022-05-18 05:32 UTC, jat-odoo commented
Hi @mart-e ,

I created this `jat-odoo` Github user 8 years ago. this is only my Github account. I have many repos/projects/tools/scripts running on this username. So, I don't want to break anything.

I hope, you understand.

Thanks.

2022-05-18 11:09 UTC, alexkuhn approved these changes
@robodoo r+ rebase-ff

2022-05-18 11:09 UTC, robodoo commented
Merge method set to rebase and fast-forward

2022-05-18 12:49 UTC, closed without merging