[FIX] web_editor: allow to manage all types of buttons
odoo/odoo pull request #91630
Opened 2022-05-18 08:43 UTC by Guillaume-gdi

Before this commit, some types of buttons were not managed by the
editor, only the primary, secondary and link buttons were supported.
However, if there is another type of btn in the DOM, the editor must be
able to handle it. This commit allows to manage all types of buttons in
the editor.

Steps to reproduce the fixed bug:
 - Drop a block with a <a> with the btn-success class
 - Click on the button to edit it
 - The link tool part in the editor does not work properly
or
 - Drop the newsletter block
 - Save and register to the newsletter
 - Edit the new "Thanks" button
 - The link tool part in the editor does not work properly

task-2802139
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-18 08:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91630).

2022-05-18 14:06 UTC, qsm-odoo requested changes
- Add a test, the link edition code is not the cleanest one. Especially here, if we ever refactor it right, I'd prefer a testing suite to ensure we are not breaking anything.

- For customer tickets, we write opw-XXX instead of task-XXX in commit messages.

2022-05-18 14:06 UTC, qsm-odoo commented on addons/web_editor/static/src/js/wysiwyg/widgets/link.js
> +                    || !this.data.iniClassName.split(' ').find(el => supportedTypes.includes(el));
Unless I am missing something, `supportedTypes` contains either `'link', 'primary', 'secondary', 'custom'` or `'', 'primary', 'secondary', 'custom'`, depending on if it's a button or a link we edit. You then loop through classes and try to find one that matches one of those "supported types" which are not class names :shrug: 

What I am not understanding right?

2022-05-19 10:11 UTC, Guillaume-gdi commented
@qsm-odoo This one is ready :+1:

2022-05-19 13:57 UTC, qsm-odoo requested changes
![image](https://user-images.githubusercontent.com/10338094/169311065-e80daf73-1316-4441-b081-a8cf6e5a3d0b.png)
Why the space?

2022-05-19 16:43 UTC, Guillaume-gdi commented
@qsm-odoo I implemented the changes you asked

2022-05-25 15:44 UTC, qsm-odoo approved these changes
@robodoo r+

2022-05-25 17:24 UTC, closed without merging