[FIX] web_editor: compare size CSS properties
odoo/odoo pull request #91799
Opened 2022-05-19 13:32 UTC by bso-odoo

When CSS properties are updated, a check is made to verify whether the
new value is different from the old one. This process sometimes involves
unit conversions.
Since [1] when a CSS property is updated, it is also set before checking
in order to verify whether it should be set as `!important`.
When the CSS property is a size, such as the `background-size` CSS
property, it is made of two dimensions, but the verification does not
handle that situation: it handles `15px auto` as being a single number
with the unit `px auto`, which is wrong.

This commit adapts the CSS property comparison mechanism into splitting
the size properties into their parts and comparing each part separately.

Steps to reproduce:
- Drop a "Banner" block.
- Set "Position" as "Repeat Pattern".
- Type "5" in the "Width".
=> Did raise an error.

[1]: https://github.com/odoo/odoo/commit/d3c3dab8950abc25b29937605091d8ce32305fa4

task-2853161

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-19 13:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91799).

2022-12-28 16:19 UTC, sobo-odoo requested changes
Here is my review :slightly_smiling_face: 
I also have more general comments:
- I tried to reproduce the bug in versions higher than 15.3 and it did not happen (so I think the fix should only target 15.3).
- For the second commit, the traceback only appears right after the first commit. Otherwise, the behaviour is that the input doesn't display the number after it becomes too big (even if the property is set to it as we can see when we inspect the element), maybe you should mention it in the commit message? Also, this behaviour starts from 14.0 so I wonder if this commit shouldn't go in another branch starting at version 14 :thinking:  (even though no one is supposed to write a number that big)
What do you think ?

2023-01-02 09:49 UTC, bso-odoo commented
> I tried to reproduce the bug in versions higher than 15.3 and it did not happen (so I think the fix should only target 15.3).

Thanks for raising this - I found out that it is because the whole mechanism about establishing whether the `!important` marker is needed is broken in 16.0 (in short, the bug makes it always important).
I just created a PR about that issue: https://github.com/odoo/odoo/pull/108893. Once applied, this PR's bug is back.

2023-01-02 10:39 UTC, bso-odoo commented
> For the second commit, the traceback only appears right after the first commit. Otherwise, the behaviour is that the input doesn't display the number after it becomes too big (even if the property is set to it as we can see when we inspect the element), maybe you should mention it in the commit message? Also, this behaviour starts from 14.0 so I wonder if this commit shouldn't go in another branch starting at version 14 thinking (even though no one is supposed to write a number that big)

Hmmm... given that typing such an input is not a reasonable scenario anyway, I guess that I might have to move it to master instead.
@rdeodoo What do you think ?

2023-01-02 15:12 UTC, rdeodoo commented
> given that typing such an input is not a reasonable scenario anyway, I guess that I might have to move it to master instead.

I'd say we don't need to spend much time on this scenario unless it's straightforward to fix and in this case master will be fine indeed

But actually:
- In 15.0, typing `100000` or `aaa` doesn't crash
- In 15.3, typing `aaa` doesn't crash but `100000` does

So maybe worth fixing as it's a regression and there is something already there to prevent crash with `aaa`

2023-01-03 10:14 UTC, bso-odoo commented on addons/web_editor/static/src/js/common/utils.js
> +    if (cssProp && cssProp.endsWith('-size')) {
To minimize impact, I'd rather only check for sizes. We will add further properties if we manage to produce specific issues.

2023-01-03 13:25 UTC, bso-odoo commented
@sobo-odoo Changes done and tested on runbot.

2023-01-04 12:55 UTC, sobo-odoo approved these changes

2023-01-04 13:05 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-01-04 13:58 UTC, closed without merging