[IMP] website_sale: add to cart button
odoo/odoo pull request #91882
Opened 2022-05-20 08:29 UTC by alpa-odoo

task-2824359

2022-05-20 08:29 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91882).

2022-06-20 10:49 UTC, Williambraecky commented
Converted to draft while still being wip :)

2022-07-25 09:16 UTC, Williambraecky requested changes
Thanks for your work! It's looking good!

2022-07-25 09:16 UTC, Williambraecky commented on addons/website_sale/static/src/snippets/s_add_to_cart/options.js
> +        this.rerender = true;
Can't this be done via a `data-dependencies`?

2022-07-25 09:16 UTC, Williambraecky commented on addons/website_sale/static/src/snippets/s_add_to_cart/options.js
> +
Empty line
```suggestion
```

2022-07-27 14:13 UTC, Williambraecky requested changes
Another review!

2022-07-27 14:13 UTC, Williambraecky commented on addons/website_sale/views/snippets/s_add_to_cart.xml
> +                                 data-default-message="Choose a Product..."
This does nothing.
```suggestion
```

2022-07-27 14:13 UTC, Williambraecky commented on addons/website_sale_stock_wishlist/static/src/js/website_sale.js
> +/** @odoo-module **/
This neither

2022-07-28 08:04 UTC, Williambraecky requested changes
Last review 😄

2022-07-28 08:04 UTC, Williambraecky commented on addons/website_sale/static/src/snippets/s_add_to_cart/000.scss
> +a:disabled {
I think this file is not necessary.

Moreover it will apply to all `a` disabled tags on the website if the file is loaded which is not wanted.

2022-07-28 09:03 UTC, rdeodoo requested changes
Nice :+1: 

Just passing by, didn't read the code but just commented the website files seeing the linter errors. (Same in all JS files.)

Don't forget to install a linter, see https://www.odoo.com/documentation/15.0/fr/developer/howtos/rdtraining/02_setup.html?highlight=eslint#code-editor and https://github.com/odoo/odoo/wiki/Javascript-coding-guidelines#use-a-linter for guidance.

2022-07-28 09:42 UTC, alpa-odoo commented
> Nice 👍
> 
> Just passing by, didn't read the code but just commented the website files seeing the linter errors. (Same in all JS files.)
> 
> Don't forget to install a linter, see https://www.odoo.com/documentation/15.0/fr/developer/howtos/rdtraining/02_setup.html?highlight=eslint#code-editor and https://github.com/odoo/odoo/wiki/Javascript-coding-guidelines#use-a-linter for guidance.

Thanks, I configured ESLint and it caught more linting issues 👍

2022-07-28 13:08 UTC, Williambraecky approved these changes
Thanks for your work!

robodoo r+

2022-07-29 07:08 UTC, Williambraecky commented
Fixed the conflicts.

robodoo r+

2022-07-29 10:41 UTC, closed without merging