[FIX] wip - fix options flicker
odoo/odoo pull request #91929
Opened 2022-05-20 12:45 UTC by bso-odoo

investigation in progress
also try to find out why the inner text toolbar is re-shown before this
is even called

task-2821398

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-20 12:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/91929).

2022-11-30 17:22 UTC, rdeodoo commented
@robodoo delegate=@Guillaume-gdi

2022-12-07 10:15 UTC, Guillaume-gdi commented
Hello @bso-odoo can you rebase this branch and check that everything is still working well. Thanks :slightly_smiling_face:

2022-12-08 10:24 UTC, bso-odoo commented
> Hello @bso-odoo can you rebase this branch and check that everything is still working well. Thanks slightly_smiling_face

@Guillaume-gdi Rebased, and is still works fine. :+1:

2022-12-15 14:06 UTC, Guillaume-gdi requested changes

2023-01-26 10:40 UTC, Guillaume-gdi commented
@robodoo r+

2023-01-26 11:40 UTC, closed without merging

2023-01-26 14:33 UTC, qsm-odoo commented
@Guillaume-gdi @bso-odoo I think it would have been worth a few inline comments here :wink: Because reading just the code raises a huge flag: "omg why are we updating the DOM on start"... which actually is not the case once you read the parameter doc further... but you still ask: "why do we need this as the UI will be updated later anyway?"... The commit message is good, but inline comments are more important IMO.

Add some comments in the forward-ported version, no need to change 15.0 as long as it is explained in further versions (at least master). Reminder: if you push-forced the first 15.X forward-port PR, fw-bot will automatically update the other forward-port PR :+1: TBH I am not sure this really qualified as a stable fix in the first place but that's ok :wink: