[FIX] stock: check serial lot name properly for double usage
odoo/odoo pull request #92334
Opened 2022-05-26 14:11 UTC by wtaferner

**Description of the issue/feature this PR addresses:**
The check was not working as assuming to have more than one when we do not count ourselves is wrong.
Besides as we do not get back the newId record from the method `_get_similar_move_lines` anymore we just remove the original record as it is currently changed anyway.

**Current behavior before PR:**
The check was not working at all

**Desired behavior after PR is merged:**
Finally the check is working again

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-26 14:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/92334).

2022-05-30 09:10 UTC, wtaferner commented
@amoyaux @Whenrow @nle-odoo 
Maybe interesting for one of you guys...I looked up the code from 13.0 up to master and it seems this warning was kinda ignored for quite some changes. At least in 13.0 it does not work as it is implemented, so I had to fix it. Thank you for your time in advance.

2022-06-10 09:52 UTC, Yenthe666 approved these changes
LGTM

2022-06-10 10:06 UTC, wtaferner commented
OPW-2880791

2022-07-06 12:26 UTC, adwid requested changes
The fix breaks a use case:
1. Create a tracked-by-serial product P
2. Update its quantity with three serial numbers SN01, SN02, SN03
3. Create and confirm a planned delivery order with 2 x P
4. Check the availability: 
    - SN01/SN02 should be reserved
6. Edit the move lines:
    - Switch SN01 with SN03
    - Switch SN02 with SN01
        - Error: This change will trigger the warning while it should not

2022-07-06 16:00 UTC, wtaferner commented
@adwid
Awesome, I can imagine the reason for that and it is complicated. Can you write a test for that and the standard use case?
Currently the expected behavior is not working as it will not trigger at all which is more important than breaking a complicated use case IMO.

And yes, your described use case should be working too, but I do not think removing the functionality of the standard use case is the way to go which was intentionally?! done then or was the framework changed? I think it was the latter and no test was available, so nobody noticed until now 😉

2023-02-19 11:45 UTC, closed without merging