[FIX] fields: prevent writing float fields if not changed
odoo/odoo pull request #92336
Opened 2022-05-26 16:04 UTC by poma-odoo

[FIX] fields: prevent writing float fields if not changed

 In some rare cases, this line causes float fields to write even when the value has not been changed because of precision. This causes bugs like #91626
Here is an example, when record value is 0.12:

origin[name]=0.12 and cache is calculated here:

```python
class Float(Field):
    #...
    def convert_to_cache(self, value, record, validate=True):
        # apply rounding here, otherwise value in cache may be wrong!
        value = float(value or 0.0)
        if not validate:
            return value
        digits = self.get_digits(record.env)
        return float_round(value, precision_digits=digits[1]) if digits else value
```
the value in cache is:
```
>>>float_round(0.12, precision_digits=4)
0.12000000000000001
```
then it is detected as a changed field because `0.12 != 0.12000000000000001`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-26 16:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/92336).

2022-05-27 09:22 UTC, poma-odoo commented
Here is another fix:
```python
class Float(Field):
    def convert_to_column(self, value, record, values=None, validate=True):
        result = float(value or 0.0)
        digits = self.get_digits(record.env)
        if digits:
            precision, scale = digits
            result = float_repr(float_round(result, precision_digits=scale), precision_digits=scale)
        return result

    def convert_to_cache(self, value, record, validate=True):
        # apply rounding here, otherwise value in cache may be wrong!
        value = float(value or 0.0)
        if not validate:
            return value
        # HERE
        # - digits = self.get_digits(record.env)
        # - return float_round(value, precision_digits=digits[1]) if digits else value
        return float(self.convert_to_column(value, record, validate))
```

2022-06-24 08:20 UTC, kbr-odoo commented
@poma-odoo Hello, Pouya!
Do you believe we'll be able to progress with this fix soo-ish?
Thank you!

2023-01-02 12:18 UTC, VincentSchippefilt requested changes
This change requires some tests showing the failing cases of the previous implementation.

2023-01-02 12:18 UTC, VincentSchippefilt commented on odoo/fields.py
> +                    return record[name] != origin[name]
As a matter of fact, this method should be defined in each field type:
- float and monetary for their special cases
- relational fields for the `_origin` case
- field for the fallback case

2023-09-08 14:41 UTC, closed without merging