[ADD] payment_razorpay: integrate with "Razorpay Payment" gateway
odoo/odoo pull request #92848
Opened 2022-06-03 06:10 UTC by mba-odoo

See README for technical details.

task-2800823
See also:
  https://github.com/odoo/documentation/pull/2149

2022-06-03 06:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/92848).

2022-07-29 15:16 UTC, AntoineVDV requested changes
Hello, I made a first *partial* review pass and highlighted the parts of the code that involved some changes or raised some questions. I will push a fixup commit containing nitpicking changes aimed at cleaning the code only.

I see that you integrated with the Razorpay Standard Checkout solution, but I find that the [Hosted Checkout](https://razorpay.com/docs/payments/payment-gateway/web-integration/hosted) solution would be better suited for our needs:
- The UX would be better than with an in-page modal that badly integrates with Odoo's interface.
- The code would be much simpler because it will allow dropping all the JS customization as well as some Python methods.
- Even if a redirection error occurs, we're covered with the webhook.

Could you please if that is feasible and if it indeed simplifies the code? I will resume the review after we decide on the final solution. :)

2022-08-02 05:11 UTC, mba-odoo commented on addons/payment/data/payment_icon_data.xml
> +        <field name="sequence">220</field>
@AntoineVDV , it captures a 60 percent share of India's card market so we prefer to keep it after Paypal at sequence 75. thanks

2022-08-02 05:12 UTC, mba-odoo commented on addons/payment/data/payment_acquirer_data.xml
> +        <field name="name">Razorpay</field>
@AntoineVDV , We will display it as `Credit & Debit Card, UPI (Powered by Razorpay)`. Thanks

2022-08-02 07:52 UTC, AntoineVDV commented on addons/payment/data/payment_icon_data.xml
> +        <field name="sequence">220</field>
Fine by me, but let's move it after PayPal so it's less confusing then ;)

2022-09-01 16:02 UTC, AntoineVDV approved these changes
@robodoo override=ci/security
Reason:
- `hmac`, `hashlib`: Used to compute a signature.
- `requests`: Used to make requests to a controlled URL with a short timeout.

Link to ci/security build (master): https://runbot.odoo.com/runbot/batch/846307/build/18940375

@robodoo r+ rebase-ff

2022-09-01 16:03 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-09-01 18:22 UTC, closed without merging

2022-09-02 05:13 UTC, mba-odoo commented
🥳