[FIX] website, test_website: fallback on exact search if max reached
odoo/odoo pull request #92864
Opened 2022-06-03 09:32 UTC by bso-odoo

For performance reasons, when fuzzy search was introduces it was
decided to limit the number of records used for finding fuzzy terms to
1000.  Because of this, when a database contains more than 1000
products matching words that start with the same letter, further
products are not examined. This can lead to searches not finding an
existing exact match.

This commit introduces a fallback mechanism so that, if we are in a
situation where the maximum number of examined records was fetched, we
also explicitly check for a possible exact match across all records.

Steps to reproduce:
- Do not install the pg_trgm extension.
- Have more than 1000 products containing searchable words (name,
description...) starting with the same letter.
- Add one more such product (so that it is not in the 1000 first ones).
- Search for that last product by correctly typing the word.
=> Exact match was not returned.

task-2870947

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-03 09:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/92864).

2022-06-03 11:44 UTC, bso-odoo commented
Before fix:
![image](https://user-images.githubusercontent.com/71644421/171847242-650dd5f3-59a2-4c2b-bf31-8d53d41f0ebb.png)
After fix:
![image](https://user-images.githubusercontent.com/71644421/171847300-b1962b21-ca23-450e-a4fe-c1a664bfe198.png)

2022-06-03 12:27 UTC, bso-odoo commented
@rdeodoo The fix itself is only 4 lines long, but I added all the tests I could think of.
The screenshots above are taken from runbots by importing 1500 products from an `.xslx`. (oops... the "before" screenshot is from master instead of 15.0)

2022-07-28 07:13 UTC, bso-odoo commented
@rdeodoo Ping... I guess we forgot about this one.

2022-08-05 10:07 UTC, rdeodoo requested changes
Indeed, sorry.
LGTM, just a nitpicking about comment/variable then good to be shipped :+1:

2022-08-05 10:07 UTC, rdeodoo commented on addons/website/models/website.py
> +            if len(records) == 1000:
Could we make those 2 lines `1000` "linked" by using a variable? Will be easier to figure.
And definitely add a comment for this new code block, write it as you prefer but something along those lines I guess
```suggestion
            perf_limit = 1000
            records = model.search_read(domain, fields, limit=perf_limt)
            # Exact match might have been missed due to the 1000 blabla.. (I let you write it the way you prefer)
            if len(records) == perf_limit:
```

2022-08-05 10:07 UTC, rdeodoo commented on addons/test_website/tests/test_fuzzy.py
> +    def _autocomplete(self, term, expected_count, expected_term):
The expected term is just the expected fuzzy term, right?
```suggestion
    def _autocomplete(self, term, expected_count, expected_fuzzy_term):
```

2022-08-05 12:42 UTC, bso-odoo commented
@rdeodoo Suggested changes done.

2022-08-05 14:21 UTC, rdeodoo approved these changes
@robodoo r+
Nice, thanks :+1: (especially for the tests)

2022-08-05 15:45 UTC, closed without merging