[FIX] Internal transfer second payment issue
odoo/odoo pull request #92927
Opened 2022-06-04 11:53 UTC by wm-cortex

Confirm Internal transfer (duplicate from exists once) doesn't create the second payment in the destination journal.

Description of the issue/feature this PR addresses:
Steps to reproduce:

1. Go to Invoicing app, From customer menu open payments.
2. Create a new internal transfer from Bank to Cash and confirm it.
3. From actions, select duplicate. a new internal transfer will be created.
4. confirm the new internal transfer.

Check the journal entries created, You will find only the first payment from source journal.

Current behavior before PR:
Once the internal transfer confirmed, only first payment created and the second payment is not created in the destination journal.

Desired behavior after PR is merged:
The second payment should be created and reconciled with the first payment.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-04 11:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/92927).

2022-06-04 11:54 UTC, wm-cortex commented
#92926

2022-06-05 06:58 UTC, sswapnesh commented on addons/account/models/account_payment.py
> +    paired_internal_transfer_payment_id = fields.Many2one('account.payment', copy=False
```suggestion
    paired_internal_transfer_payment_id = fields.Many2one('account.payment', copy=False,
```

2022-06-13 08:05 UTC, Levizar requested changes
Hello,

The change seems legit to me but the commit isn't ok for the moment:

1) squash the commits
2) Commit message first line should comply with: `[FIX] module_name: brief description of change`
3) Commit body, you explain what you are doing but we can see that in the diff. Instead we need you to explain **why** you made the commit. (To what end? What was the issue? ect)

2022-09-05 15:05 UTC, closed without merging