[IMP] im_livechat: introduce LivechatButtonView/history
odoo/odoo pull request #93563
Opened 2022-06-14 09:32 UTC by alexkuhn

Task-2883232

2022-06-14 09:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/93563).

2022-06-17 09:50 UTC, oomsveta requested changes

2022-06-17 09:50 UTC, oomsveta commented on addons/im_livechat/static/src/legacy/widgets/livechat_button.js
> +        if ( this.messaging.livechatButtonView.history) {
unwanted whitespace

2022-06-20 08:15 UTC, alexkuhn commented on addons/im_livechat/static/src/legacy/widgets/livechat_button.js
> +        if ( this.messaging.livechatButtonView.history) {
Changes done

2022-06-20 08:20 UTC, oomsveta approved these changes

2022-06-20 19:43 UTC, alexkuhn commented
Merged in grouped PR: https://github.com/odoo/odoo/pull/94090

2022-06-20 19:43 UTC, closed without merging