[IMP] website_livechat: introduce Message/publicLivechatServerUrlChatbot
odoo/odoo pull request #93603
Opened 2022-06-14 14:14 UTC by alexkuhn

Task-2883598

2022-06-14 14:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/93603).

2022-06-17 10:03 UTC, oomsveta requested changes
wrong commit message: `Message` ➡️ `Messaging`

2022-06-20 08:38 UTC, alexkuhn commented on addons/website_livechat/__manifest__.py
> +            'website_livechat/static/src/models/*.js'
Changes done

2022-06-20 09:06 UTC, oomsveta approved these changes

2022-06-20 19:44 UTC, alexkuhn commented
Merged in grouped PR: https://github.com/odoo/odoo/pull/94090

2022-06-20 19:44 UTC, closed without merging