Master disable tokens lasc
odoo/odoo pull request #93774
Opened 2022-06-16 06:22 UTC by lascha212

task-2649806

See also: 
- TODO!

2022-06-16 06:23 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/93774).

2022-07-01 16:15 UTC, Feyensv reviewed
:duck:

2022-07-01 16:15 UTC, Feyensv commented on addons/payment/models/payment_acquirer.py
> +                ('acquirer_id', '=', self.id.origin)
```suggestion
                ('acquirer_id', '=', self._origin.id)
```
Most usages rely on `_origin.id` instead.  Both paths work indeed, but I'd prefer if you use the most used one :).

2022-07-05 10:36 UTC, Feyensv reviewed
Missing/wrong points from my last review, nearly good to go :)

2022-07-05 10:36 UTC, Feyensv commented on addons/payment/models/payment_acquirer.py
> +        if self.state == 'disabled' and self.id:
```suggestion
        if self.state == 'disabled' and self._origin.id:
```
My bad, self.id is always falsy in an onchange as NewId objects are always falsy.

2022-07-05 10:36 UTC, Feyensv commented on addons/payment/models/payment_acquirer.py
> +                    )
I think we could go for a generic message `%s token(s)` to have one less translation to manage in database.

2022-07-05 10:36 UTC, Feyensv commented on addons/payment/models/payment_acquirer.py
> +        if 'state' in values and enabled_acquirers:
```suggestion
        if 'state' in values and values['state'] == 'disabled' and enabled_acquirers:
```

```acquirer.write({'state': 'enabled'})``` shouldn't disable the tokens if the acquirer is already enabled ;)

2022-07-05 10:46 UTC, Feyensv commented on addons/payment/models/payment_acquirer.py
> +                    )
Well, considering the guidelines (https://www.odoo.com/documentation/master/developer/howtos/translations.html?highlight=plural#plural), let's keep it like this then.

Ty @chevalierv :D

2022-07-05 12:18 UTC, Feyensv commented on addons/payment_adyen/models/payment_token.py
> +    # and documents are unlinked in payment_token.py
leftover comment to remove :eyes:
(you can remove the header for the `BUSINESS METHODS` as well)

2022-07-05 14:34 UTC, Feyensv approved these changes

2022-07-08 16:06 UTC, AntoineVDV requested changes

2022-07-11 09:51 UTC, lascha212 commented on addons/payment/models/payment_acquirer.py
> +
@AntoineVDV 
I couldn't think of anything better than checking first if the acquirers are in 'test' or 'enabled' and then checking the states they're changed to. I know I could squash the if statements into (probably) one, but I thought for readability, it's better this way.

2022-07-11 09:53 UTC, lascha212 commented on addons/payment/models/payment_transaction.py
> +            ))
@AntoineVDV 
Should raising the error include acquirers in the 'test' state?

2022-07-11 10:40 UTC, lascha212 commented on addons/payment/models/payment_acquirer.py
> +            enabled_acquirers._handle_acquirer_disabling()
I couldn't think of anything better than checking first if the acquirers are in 'test' or 'enabled' and then checking the states they're changed to. I know I could squash the if statements into (probably) one, but I thought for readability, it's better this way.

2022-07-11 10:42 UTC, lascha212 commented on addons/payment/models/payment_transaction.py
> +                "the acquirer used for this transaction has been disabled."
Should raising the error include acquirers in the 'test' state?

2022-07-11 10:43 UTC, lascha212 commented on addons/payment/models/payment_token.py
> +                self.filtered(lambda x: x.active is True).sudo()._handle_deactivation_request()
Indeed *mindblown* - how does that work?

2022-07-11 13:03 UTC, AntoineVDV approved these changes
@robodoo r+

2022-07-12 02:21 UTC, closed without merging