[FIX] account_payment_register: register different payment type
odoo/odoo pull request #93943
Opened 2022-06-17 14:50 UTC by guva-odoo

When register a payment for a bill an a credit note,
the two payments have the same type.

Steps:

- Create a Vendor Bill, and a Vendor Bill Credit Note
- Select both and register payment without grouping them
-> The two created payments have the same type

With this commit, if the field group_payment is True, we
set the payment type regarding the balance of the move line.

opw-2852186

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-17 14:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/93943).

2022-07-18 09:18 UTC, Levizar requested changes

2022-07-18 09:18 UTC, Levizar commented on addons/account/wizard/account_payment_register.py
> +                                'payment_type': 'inbound' if line.balance > 0 else 'outbound'
This line seems weird but I see it's the same than in the get_batch method so I guess it's normal

2022-08-11 09:26 UTC, smetl approved these changes
@robodoo r+

2022-08-11 11:10 UTC, closed without merging