[FIX] point_of_sale: add warning when entering not existing SN/lot_id
odoo/odoo pull request #94047
Opened 2022-06-20 12:09 UTC by robinengels

Current behavior:
If the operation type of the PoS is configured to not create SN/lot_id
and you use an unexisting lot/SN in the PoS you receive no warning.

Steps to reproduce:
- Make sure that the "Create New Lots/Serial Numbers" is not checked
  in the PoS orders operation type
- Create a product tracked by SN
- Start a PoS session and add this product to the order
- Enter a wrong SN
- You get no warning that the SN is wrong

opw-2884883
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-27 06:57 UTC, robinengels commented
@pimodoo @caburj , I should probably extract this block and make a function but I'm not sure where to put it (in custom_hooks ?)
https://github.com/odoo/odoo/pull/94047/files#diff-e46316aff1bfa06a735ee6e23e2573ade06d07d422881fc1c764a7a805c7389aR55-R73

2022-06-27 07:03 UTC, caburj commented on addons/point_of_sale/static/src/js/Screens/ProductScreen/OrderWidget.js
> +            }
You can extract this as a method and put it in `PosModel`. Then access thru `this.env.pos`. Also, you don't need to `.then` the rpc call:
```js
                const result = await this.rpc({
                    model: 'stock.production.lot',
                    method: 'check_lots_exist',
                    args: [lots],
                });
                // do something with the result
```

2022-06-27 08:08 UTC, caburj commented
I was stupid. I thought you didn't introduce `check_lots_exist`, and that it was there. But anyway, I'm not sure if I can approve the full PR because there is a change in other addons, apart from pos.

I'm okay with the idea. However, before I can approve, we need to make sure that adding a product in the order should not be blocked when offline. So, can you `try catch` the check and ignore the rpc error?

2022-06-27 13:57 UTC, caburj requested changes
I do have some requests to change, but overall, I'm okay with this PR.

2022-06-27 13:57 UTC, caburj commented on addons/stock/models/stock_production_lot.py
> +        return list(set(lots) - set(existing_sn.mapped('name')))
Perhaps you can just put this in the `stock_picking.py` file in `point_of_sale` addon. I don't see a reason to ask the inventory team to approve such method.

2022-06-27 13:57 UTC, caburj commented on addons/point_of_sale/static/src/js/custom_hooks.js
> +                console.log("There was an error while checking the serial numbers", e);
I prefer `console.warn`.

2022-06-27 13:57 UTC, caburj commented on addons/point_of_sale/static/src/js/custom_hooks.js
> +    function useCheckLotsIds() {
Can you change your use of "lots ids" with "lot names". E.g. rename this method to `useCheckLotNames`.

2022-06-28 08:01 UTC, caburj requested changes
I tested this branch and it allowed me to include lots/sn that belongs to other products. I think we need to take into account the product in the backend method you created.

2022-06-28 10:21 UTC, robinengels commented
Forgot to add the product in the backend function, working on it

2022-06-28 12:50 UTC, caburj approved these changes
I can approve this already. I do have some more suggestions if you want to consider. Thanks for this fix/improvement.

2022-06-28 12:50 UTC, caburj commented on addons/point_of_sale/models/stock_picking.py
> +        """returns the list of serial numbers that do not exist"""
```suggestion
        """returns the list of serial numbers that do not exist for the given product"""
```

2022-06-28 12:50 UTC, caburj commented on addons/point_of_sale/static/src/js/custom_hooks.js
> +                    }), product.id],
```suggestion
                    args: [lots.map(item => ({ 'name': item.text })), product.id],
```

2022-06-28 12:50 UTC, caburj commented on addons/point_of_sale/models/stock_picking.py
> +        return list(set(map(lambda x: x['name'], lots)) - set(existing_sn.mapped('name')))
```suggestion
        existing_sn = self.env['stock.production.lot'].search_read([('name', 'in', [lot['name'] for lot in lots]), ('product_id', '=', product_id)], ['name'])
        return list(set(lot['name'] for lot in lots)) - set(lot['name'] for lot in existing_sn))
```

2022-07-04 09:02 UTC, pimodoo commented
as explained on the task: 
Hello, this is not a bug, but a feedback. Nothing is broken if you sell a product with a serial that is not suppose to exist. We are not suppose to add feature that change the behavior in stable, as it will start to show warnings to users that didn't get ones and didn't have problems.

Moreover, in this change you are breaking the use case when the serials numbers are created during the sale.

And also it only check that a lot exists, which mean nothing as you can have empty stock or whatever else.

So Maybe we should do a task in master, we specs that are taken into account more use cases than just "The lot does not exist'

2022-07-04 09:02 UTC, closed without merging