[FIX] l10n_id_efaktur: fix price when tax is not included
odoo/odoo pull request #94114
Opened 2022-06-21 03:30 UTC by nni-odoo

Description of the issue/feature this PR addresses:
When tax is configured to be "Include in Price", the e-faktur document violates official regulation. Prices columns in e-faktur has to be declared without tax inclusion. Current code does not differentiate behaviour when "Include in Price" configuration in tax is True or False.

Current behavior before PR:
When tax is configured to be "Include in Price", the prices columns (unit price and the total) includes tax, which violated the e-faktur documentation rule. Consequently, the calculation for discount will be flawed since the current discount amount computation is (price_unit * quantity) - price_subtotal.

Desired behavior after PR is merged:
Price columns (unit price and total) should no longer include tax, and will result to correct discount amount calculation.

Task:
2889400

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-21 03:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94114).

2022-06-21 13:17 UTC, fja-odoo requested changes

2022-06-22 02:54 UTC, nni-odoo commented on addons/l10n_id_efaktur/models/account_move.py
> +                invoice_line_total_price = line.tax_ids.compute_all(line.price_unit * line.quantity)['total_excluded']
there is possibility of decimal place issue depending on how user configures their currency.
I tested in multiple db across multiple versions that is using indonesian localization, https://grahateknikraya.odoo.com/ <- this DB sets the IDR currency to be 1 decimal place, later on the value for `invoice_line_total_price` will be incorrect

2022-06-22 03:08 UTC, fja-odoo commented on addons/l10n_id_efaktur/models/account_move.py
> +                invoice_line_total_price = line.tax_ids.compute_all(line.price_unit * line.quantity)['total_excluded']
Make sure to add a test for the different edge cases you came across

2022-06-23 09:05 UTC, fja-odoo commented on addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
> +        line_6 = '"OF","","","100","1.0","100","0","100","10","0","0"\n'
This part should be put in the test directly so this method can be used to retrieve the csv head in potential future tests.

2022-06-23 09:05 UTC, fja-odoo commented on addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
> +    def test_efaktur_csv_output(self):
Give this test a number and a more specific name explaining what you are testing

2022-06-29 07:42 UTC, fja-odoo approved these changes

2022-06-29 08:11 UTC, qdp-odoo requested changes
only one small remark: it's better to document explicitly when intentionally doing weird things in code, rather than relying on git blame/commit message... because those are easily missable.


thanks

2022-06-29 08:11 UTC, qdp-odoo commented on addons/l10n_id_efaktur/models/account_move.py
> +                invoice_line_unit_price = line.tax_ids.compute_all(line.price_unit)['total_excluded']
please add comments on why you can't take directly `line.price_unit` and `invoice_line_unit_price * line.quantity`

2022-07-04 03:54 UTC, nni-odoo commented
noted with thanks!

2022-07-18 10:13 UTC, jco-odoo commented on addons/l10n_id_efaktur/models/account_move.py
> +                invoice_line_unit_price = line.tax_ids.compute_all(line.price_unit)['total_excluded']
You can take price_subtotal and the discount field and calculate the price_subtotal before discount from there and do price_subtotal_before_discount/quantity for the invoice_line_total_price (just be careful when quantity == 0)
That way we avoid the compute_all.  (price_subtotal is always price excluded)  @nni-odoo

2022-07-18 10:15 UTC, jco-odoo commented
check e.g. https://github.com/odoo/odoo/blob/24d57edd6e49b4ec4e3101e83748d01a755cd5d5/addons/account/models/account_move.py#L706  or 
https://github.com/odoo/odoo/blob/5a11bf321eb57457ca40d7775528393e0b9a7fd2/addons/account_edi/models/account_move.py#L657

2022-07-19 03:40 UTC, nni-odoo commented
@jco-odoo Well noted and thank you for the input! I've amended the code as appropriate

2022-07-22 08:48 UTC, william-andre approved these changes
The comment in the code doesn't really matter as it is a test that won't likely be modified a lot in the future, just giving you feedback ;)

The PR description is clearer than the commit message
Don't forget to explain what the number you give is (`opw-2889400` or `task-2889400`, or `something completely different 2889400`)

@robodoo r+ squash

2022-07-22 08:48 UTC, william-andre commented on addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
> +        efaktur_csv_expected = output_head + line_4 + line_5 + line_6
Don't limit yourself to numbered variables (`line_4`) and hardcoded patterns (`%s%s%s`)
```suggestion
        efaktur_csv_expected = ''.join([
            _csv_row(FK_HEAD_LIST, ','),
            _csv_row(LT_HEAD_LIST, ','),
            _csv_row(OF_HEAD_LIST, ','),
            _csv_row(["FK","01","0","0000000000001","5","2019","1/5/2019","12345","l10ntest","","100","10","0","","0","110","0","0","INV/2019/0001 12345","0"], ','),
            _csv_row(["FAPR","000000000000000","YourCompany","test","","","","","","","","","","12345"], ','),
            _csv_row(["OF","","","100","1.0","100","0","100","10","0","0"], ','),
        ])
```
or
```suggestion
        efaktur_csv_expected = (
            '"FK","KD_JENIS_TRANSAKSI","FG_PENGGANTI","NOMOR_FAKTUR","MASA_PAJAK","TAHUN_PAJAK","TANGGAL_FAKTUR","NPWP","NAMA","ALAMAT_LENGKAP","JUMLAH_DPP","JUMLAH_PPN","JUMLAH_PPNBM","ID_KETERANGAN_TAMBAHAN","FG_UANG_MUKA","UANG_MUKA_DPP","UANG_MUKA_PPN","UANG_MUKA_PPNBM","REFERENSI","KODE_DOKUMEN_PENDUKUNG"\n'
            '"LT","NPWP","NAMA","JALAN","BLOK","NOMOR","RT","RW","KECAMATAN","KELURAHAN","KABUPATEN","PROPINSI","KODE_POS","NOMOR_TELEPON"\n'
            '"OF","KODE_OBJEK","NAMA","HARGA_SATUAN","JUMLAH_BARANG","HARGA_TOTAL","DISKON","DPP","PPN","TARIF_PPNBM","PPNBM"\n'
            '"FK","01","0","0000000000001","5","2019","1/5/2019","12345","l10ntest","","100","10","0","","0","110","0","0","INV/2019/0001 12345","0"\n'
            '"FAPR","000000000000000","YourCompany","test","","","","","","","","","","12345"\n'
            '"OF","","","100","1.0","100","0","100","10","0","0"\n'
        )
```
(first one is a bit more readable but we are not testing `_csv_row` and `*_HEAD_LIST`)

2022-07-22 09:35 UTC, closed without merging