[FIX] website: split s_countdown templates into specific files
odoo/odoo pull request #94118
Opened 2022-06-21 07:40 UTC by detrouxdev

The s_countdown snippet had 2 templates defined into one file (000.xml):
- One for showing a redirect message which is rendered in the
  public widget flow.
- Another for showing an end message which is rendered and
  appended to the snippet in the option flow.

The templates were loaded by the public widget, which means that even
if no end message was shown, the template would be loaded into memory
for a visitor.

This commit fixes that by splitting the file into 2 templates, one for
the options and one for the public widget, insuring that the option will
load what it needs.

(This necessary for the task linked, which moves the edition to the
backend, preventing the option from relying on a public widget template.
Since it can slightly benefit stable as well, it is done here.)

task-2687506

2022-06-21 07:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94118).

2022-06-21 07:46 UTC, detrouxdev commented
@qsm-odoo I hope this is what you had in mind for https://github.com/odoo/odoo/pull/89223#discussion_r871308907
I somehow cannot reply to that comment.

2022-06-21 11:32 UTC, qsm-odoo requested changes
@detrouxdev The fix is right but you cannot do it in stable despite what your commit says:

> Since it can slightly benefit stable as well, it is done here.

=> It would benefit the stable version yes (very very small benefit) but... custo may rely on the fact the moved template is in the 000.xml file (small risk)

=> The benerit / risk ratio is way too small => This fix must be done in master :+1: Retarget this PR and adapt the commit message, thanks :+1:

2022-06-23 16:52 UTC, qsm-odoo approved these changes
@robodoo r+

2022-06-23 22:40 UTC, closed without merging