[FIX] analytic: fix analytic group issue
odoo/odoo pull request #94146
Opened 2022-06-21 11:05 UTC by kcv-odoo

This commit makes the analytic tag group implied from analytic
account group so when the analytic tag group is on then analytic
account group will be true.

task-2861376

2022-06-21 11:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94146).

2022-06-29 13:15 UTC, qdp-odoo requested changes

2022-07-18 14:23 UTC, xavierbol commented on addons/analytic/security/ir.model.access.csv
> +access_account_analytic_tag_user,access_account_analytic_tag_user,model_account_analytic_tag,base.group_user,1,0,0,0
You don't really `hide that record if user have no access to tag.` so your commit message is not really right. 🤔

2022-07-18 15:29 UTC, xavierbol reviewed
I suggest to keep your commit message and instead of your changes, we will add the `groups='analytic.group_analytic_accounting'` in all `many2many` field in which the comodel is the `account.analytic.tag` model. By doing that we will hide the field when the user has not the group.

For instance in `project.project`, you have to change [this line](https://github.com/odoo/odoo/blob/8577184187851f1e90fa6fd73a176662460c6124/addons/project/models/project.py#L299) like this:
```diff
-    analytic_tag_ids = fields.Many2many('account.analytic.tag', string='Analytic Tags')
+    analytic_tag_ids = fields.Many2many('account.analytic.tag', string='Analytic Tags', groups='analytic.group_analytic_accounting')
```

2022-07-19 05:05 UTC, kcv-odoo commented
> I suggest to keep your commit message and instead of your changes, we will add the `groups='analytic.group_analytic_accounting'` in all `many2many` field in which the comodel is the `account.analytic.tag` model. By doing that we will hide the field when the user has not the group.
> 
> For instance in `project.project`, you have to change [this line](https://github.com/odoo/odoo/blob/8577184187851f1e90fa6fd73a176662460c6124/addons/project/models/project.py#L299) like this:
> 
> ```diff
> -    analytic_tag_ids = fields.Many2many('account.analytic.tag', string='Analytic Tags')
> +    analytic_tag_ids = fields.Many2many('account.analytic.tag', string='Analytic Tags', groups='analytic.group_analytic_accounting')
> ```

https://nimb.ws/dNVtzi when analytic tags are set on project and try to create new task in that project when user has not analytic tags access then it'll try to access tags of project to set on new task in default_get same for timesheets.
Even if I add group in all 'account.analytic.tag'`s M2M fields still it'll not fix above issue. Should I have find another way to fix above issue rather then giving base user read access?

2022-07-25 09:46 UTC, xavierbol commented
Even if the user has the read access the issue that you described is still there, isn't it? 🤔

2023-01-08 06:17 UTC, kcv-odoo commented
Up to saas-15.3

2024-02-23 13:36 UTC, Levizar commented
I'm closing the pr because:
- It's old
- No one seems to complain about this
- No answer given to Xavierbol
- It's not linked to the related task anymore and a R&D Feedback has been created

2024-02-23 13:36 UTC, closed without merging