[FIX] point_of_sale: res.partner doesn't belong to a specific company
odoo/odoo pull request #94153
Opened 2022-06-21 11:43 UTC by momegahed

Steps to reproduce:

1- install POS in multicompany env
2- create a customer c from POS UI
3- c doesn't belong to the active company

Bug:
the company_id is not set when the customer is created

Fix:
set comapny_id to current active company

OPW-2881551

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-21 11:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94153).

2022-06-21 15:46 UTC, agr-odoo requested changes
Consider this use case:
create a shared contact via backend without company_id (on purpose)
open pos, select the customer, edit the info, save

With this change we would overwrite the company_id on the partner
Imho it would be better to put this in `create_from_ui` (`addons/point_of_sale/models/res_partner.py`), only when creating new contacts

2022-06-21 15:46 UTC, agr-odoo commented on addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
> +            processedChanges.company_id = this.env.pos.company.id
Forgot `;`

2022-07-11 08:36 UTC, momegahed commented
@agr-odoo changed the fix to be in python, I was a bit afraid of the changing nature of js right now so I prefer to do it in python if I can

2022-07-12 10:41 UTC, agr-odoo commented
> @agr-odoo changed the fix to be in python, I was a bit afraid of the changing nature of js right now so I prefer to do it in python if I can

Against my first comment imho it is better to send the correct data instead of having to edit it in backend.
We can see `this.env.pos.company` used in several places so it should be fine
It seems you also need to rebase on the latest revision

2022-07-14 13:24 UTC, momegahed commented
@agr-odoo

2022-07-14 14:05 UTC, agr-odoo requested changes

2022-07-14 14:15 UTC, agr-odoo approved these changes

2022-07-14 16:49 UTC, closed without merging

2022-07-25 20:21 UTC, pimodoo commented
@momegahed @agr-odoo Hello, I've just seen this fix. This is not a fix, it is a change of behavior and should be reverted. When you go to the backend, and create partners, no company ids are set on the partners because partners are always shared between company in odoo by default, you are changing this behavior that is probably used by customers in production.