[IMP] account: make account creation easier
odoo/odoo pull request #94171
Opened 2022-06-21 14:00 UTC by aliyatastemirova

Task 2888204

- Name is automatically split into code and name
- account_type is computed based on the closest parent of the code prefix (and can be changed)
- _onchange_name is needed to split the name into code and name when creating from a related model's form

Taking the relevant code from odoo/odoo#90474

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-21 14:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94171).

2022-07-14 07:40 UTC, qdp-odoo requested changes

2022-07-14 09:54 UTC, aliyatastemirova commented on addons/account/models/account_account.py
> +            closest = account.search([('code', '<', account.code), ('company_id', '=', account.company_id.id)], order="code desc", limit=1)
I agree. I decided to do it with an SQL query as I only need the codes and account types

2022-07-14 13:53 UTC, qdp-odoo commented
@robodoo r+
@aliyatastemirova thanks :+1:

2022-07-14 17:11 UTC, closed without merging