[IMP] hr_recruitment_survey: add interview template
odoo/odoo pull request #94178
Opened 2022-06-21 14:39 UTC by Bertrand2

This commit adds a new mail template to be sent by default for interviews.

taskID 2884526

2022-06-21 14:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94178).

2022-06-27 09:38 UTC, kba-odoo requested changes

2022-06-29 07:10 UTC, kba-odoo commented on addons/hr_recruitment_survey/models/survey_invite.py
> +        if 'applicant_id' in answer and answer.applicant_id:
The field exists as it's defined just above :-D
```suggestion
        if answer.applicant_id:
```

2023-03-01 09:34 UTC, kba-odoo requested changes

2023-03-01 09:34 UTC, kba-odoo commented on addons/survey/wizard/survey_invite.py
> +            existing_answers = self.survey_id.user_input_ids
```suggestion
            existing_answers = wizard.survey_id.user_input_ids
```

2023-03-01 09:34 UTC, kba-odoo commented on addons/survey/wizard/survey_invite.py
> +            self.existing_text = existing_text
```suggestion
            wizard.existing_text = existing_text
```

2023-03-03 13:00 UTC, robodoo commented
@Bertrand2 @kba-odoo linked pull request(s) odoo/upgrade#3731 not ready. Linked PRs are not staged until all of them are ready.

2023-03-09 16:02 UTC, closed without merging