[13.0][FIX] purchase_stock lines date propagation
odoo/odoo pull request #94272
Opened 2022-06-22 10:44 UTC by chienandalu

This fix landed in [saas-13.4](https://github.com/odoo/odoo/tree/saas-13.4) and it was later discarded as in [14.0](https://github.com/odoo/odoo/tree/14.0) all the propagate_date stuff was discarded. Anyway, the bug still exists in [13.0](https://github.com/odoo/odoo/tree/13.0).

From the rationale of the commit:

Before this commit, when we manually create a PO line, the propagate_date will always be `False`. So the change on scheduled date will never pass to corresponding move.

After this commit, when create a PO line, if no propagate_date for it, we find if the product has a route with a buy rule. If yes, use the setting on its first buy rule, if no, set the default to be true.

cc @Tecnativa TT37567

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-22 10:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94272).

2022-06-23 06:54 UTC, Whenrow commented
robodoo r+
see https://github.com/odoo/odoo/pull/55155 to get full context
@chienandalu Thank you

2022-06-23 06:54 UTC, Whenrow commented
robodoo rebase-ff

2022-06-23 06:55 UTC, robodoo commented
Merge method set to rebase and fast-forward

2022-06-23 07:17 UTC, robodoo commented
Staging failed: ci/runbot on b03b8a37adfff117a47ff39d1986f947c60a8527 (view more at https://runbot.odoo.com/runbot/build/16774223)

2022-06-29 06:58 UTC, chienandalu commented
@Whenrow It seems didn't make it into the main branch. Can you check why?

2022-07-04 23:04 UTC, cesar-tecnativa requested changes

2022-07-04 23:04 UTC, cesar-tecnativa commented on addons/purchase_stock/models/purchase.py
> +        for line, vals in zip(lines, vals_list):
`if 'propagate_date' not in vals`  before for loop to prevent going inside?

2022-07-06 15:40 UTC, Whenrow commented
robodoo retry

2022-07-06 16:49 UTC, closed without merging

2022-07-06 16:59 UTC, pedrobaeza commented
Thanks!