[IMP] hr_holidays: send time off cancellation notification to manager
odoo/odoo pull request #94533
Opened 2022-06-24 11:34 UTC by sofiagvaladze

Purpose: the manager that validated the time off, should be notified
if/when the time off is canceled by the user.

task - 2857233

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-24 11:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94533).

2022-07-15 09:09 UTC, kba-odoo requested changes

2022-11-25 12:33 UTC, kbapt requested changes

2022-11-25 12:33 UTC, kba-odoo commented on addons/hr_holidays/models/hr_leave.py
> +            if responsibles:
You could re-use the `_notify_manager` method with the subject / body as arguments

2022-11-28 13:01 UTC, kba-odoo commented
robodoo r+

2022-11-28 14:00 UTC, robodoo commented
@sofiagvaladze @kba-odoo linked pull request(s) odoo/upgrade#3809 not ready. Linked PRs are not staged until all of them are ready.

2022-11-28 14:00 UTC, robodoo commented
@sofiagvaladze @kba-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2022-11-28 14:08 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-01-10 14:25 UTC, kba-odoo commented
robodoo r+

2023-01-10 15:51 UTC, closed without merging