[IMP] im_livechat: remove useless code in WebsiteLivechat
odoo/odoo pull request #94570
Opened 2022-06-24 14:57 UTC by alexkuhn

Task-2894765

2022-06-24 14:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94570).

2022-06-29 13:45 UTC, oomsveta requested changes

2022-06-29 13:45 UTC, oomsveta commented on addons/im_livechat/static/src/legacy/models/public_livechat.js
> +        this.trigger.bind(this, 'message_posted');
remove the bind

2022-06-29 13:57 UTC, oomsveta approved these changes

2022-06-30 12:49 UTC, alexkuhn commented
Merged in grouped PR: https://github.com/odoo/odoo/pull/94914

2022-06-30 12:49 UTC, closed without merging