[FIX] web_editor, web_unsplash, website: fix unsplash on the frontend
odoo/odoo pull request #94572
Opened 2022-06-24 14:58 UTC by younn-o

Before this commit, when the admin had set his unsplash credentials in
the media dialog, he could search for unsplash images in the backend
(website builder, optimize SEO, html fields), but not on the frontend
(from the website_forum reply section for example). This was caused by a
wrong assets management for the media dialog views.

This commit reworks the assets_media_dialog introduced in [1], that were
not correctly defined. Until now, a web_editor.assets_media_dialog
bundle including js, scss and xml files was included in both the
web.assets_frontend and web.assets_backend bundles. It was built that
way, because the frontend only takes the views defined in the
web.assets_frontend bundle.
Two mistakes were made with that approach:
- The views defined in web.assets_backend are not added to the
webclient's templates list. Only the ones defined in web.assets_qweb
are. It was only working because web.assets_qweb was globally taking
every component view, defined as /component/*/*.xml.
- The qweb extensions templates for web_unsplash were defined in
web.assets_qweb (therefore, not included in web.assets_frontend and not
added to the frontend's template list).

To change that and include the web_editor and web_unsplash media dialog
views both for the frontend and the backend, a
web_editor.assets_media_dialog_templates is added, with the xml files
from the web_editor.assets_media_dialog bundle. But this time, this new
views-only bundle is included in web.assets_frontend and
web.assets_qweb.

Also, the extension template that adds the unsplash records is reworked:
the t-if is separated from the t-foreach, and set using an id instead of
the qweb instruction that it was using before, as it is more robust.

Finally, the isFetching getter was not set on the unsplash ImageSelector
patch, leading to a visual glitch ("No images found" was displayed while
querying unsplash). It is added in this commit.

task-2687506

[1]: https://github.com/odoo/odoo/pull/89223/commits/a154ee7ad6fd3ebdd38943e1439badae11c3151d

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-28 16:50 UTC, rdeodoo approved these changes
LGTM, tested & working.
Note that the admin still can't add the unsplash key from the frontend media dialog (despite seeing an "Unsplash" entry in the select), but that could be something for later as there is also a weird UX about unsplash credentials: In the backend settings the user can only enter his key, not his appid... which is required.. So it actually has to do it in the frontend anyway
I'll create a task for that

2022-06-28 16:50 UTC, rdeodoo commented on addons/web_unsplash/__manifest__.py
> +        'web_editor.assets_media_dialog_templates': [
Could you add a `TODO` comment for those 2 new media dialog assets keys?
Something about what was discussed at https://github.com/odoo/odoo/pull/89223#discussion_r895627061 eg `TODO: Move those dialog assets in assets_common and make the public root fetch templates from the common asset`

2022-06-28 16:50 UTC, rdeodoo commented on addons/web_editor/static/src/components/media_dialog/image_selector.xml
> +            <t t-if="['all', 'media-library'].includes(state.searchService)" id="o_we_media_library_images">
Nitpicking: Not ideal to have an `id` on a `</t>` element but in this case it is fine, more robust as you said. But just move the `id` as first attribute.

2022-06-29 08:51 UTC, qsm-odoo requested changes
The change seems good and the commit message does explain it well. I'll leave the testing and r+ to you @rdeodoo 

The commit title is wrong though, website is not modified.

2022-06-29 10:15 UTC, rdeodoo approved these changes
Thanks
@robodoo r+ https://github.com/odoo/odoo/pull/94572#pullrequestreview-1022089613

2022-06-29 11:31 UTC, closed without merging