[FIX] website: fix edit_megamenu inconsistent test
odoo/odoo pull request #94924
Opened 2022-06-30 08:00 UTC by younn-o

Before this commit, the edit_megamenu test was failing inconsistently.
When adding a mega menu, two dialogs are displayed:
- The main "Edit Menu" dialog, from which you can open
- The "Menu" dialog with the mega menu name input
The tour was successively closing the two dialogs one after the other
(validate the name of the menu, then validate the addition of the new
menu).

The issue was coming from that the two steps "click on the save button
of the dialog" were sometimes executed for the same dialog. Thus, the
last dialog was never closed and the test would fail.

To prevent that, an extra_trigger is added on the second "click on save"
step to check that there is only one dialog displayed.
It is also used for the "edit_menu" tour that was sometimes failing for
the same reason.

runbot-4000
runbot-4001
runbot-4004
runbot-4005

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-30 08:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/94924).

2022-06-30 15:00 UTC, rdeodoo requested changes
Thanks for the fix.
AFAIC, I don't think this is the correct fix.
We are fixing the consequence of incorrect testing steps IMHO.
Why aren't we checking after clicking on the save of the first dialog, that the change is reflected correctly in the modal behind it? Eg either the new menu entry is added in it, or the existing modified one received the notification?
That way, it will indirectly actually wait for the dialog to be correctly closed?
And it will be more correct functionally: when I do an action, the next step should ensure the action was correctly done. Here, saving the menu edition dialog expected action is not the close (well, secondary yes), but the real expected action is for the menu to be reflected on the second dialog.

What do you think? Is there any issue doing that instead?

2022-06-30 16:52 UTC, rdeodoo requested changes

2022-07-01 07:30 UTC, younn-o commented on addons/website/static/src/js/tours/tour_utils.js
> +};
I agree, I think a few lines of code are not worth readability. I changed for explicit steps with clearer content :)

2022-07-04 11:13 UTC, rdeodoo approved these changes
@robodoo r+
Thanks for the changes, I think this approach is more correct :)
Could be useful: https://github.com/odoo-dev/odoo/commit/f7703c5d9b3ccfaf16ec6a233eb71ca3d0c9cd70

2022-07-04 13:22 UTC, closed without merging