[IMP] im_livechat, *: introduce PublicLivechatGlobal/publicLivechat
odoo/odoo pull request #95113
Opened 2022-07-01 15:52 UTC by alexkuhn

*: website_livechat

Task-2900869

2022-07-01 15:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/95113).

2022-07-26 14:10 UTC, oomsveta requested changes

2022-07-26 14:10 UTC, oomsveta commented on addons/im_livechat/static/src/models/public_livechat_global.js
>          }),
alphabetical

2022-07-26 14:31 UTC, alexkuhn commented on addons/im_livechat/static/src/models/public_livechat_global.js
>          }),
Done

2022-07-26 14:35 UTC, oomsveta approved these changes

2022-07-28 11:54 UTC, alexkuhn commented
Merged in grouped PR: https://github.com/odoo/odoo/pull/96690

2022-07-28 11:54 UTC, closed without merging