[IMP] odoo: employee values to sync
odoo/odoo pull request #95159
Opened 2022-07-02 02:27 UTC by TheAlekLuna

By enabling the method 'employee_values_sync' the original behavior is kept. Furthermore, by overriding, the method now is possible to decide whether a field is synced or not into an employee.

Description of the issue/feature this PR addresses:
When you change a user's name (res.user), the employee's name related to the user is also changed. The option of deciding whether this behavior is wanted or not can be achieved by overriding the method. If no override exists, the method will behave exactly like the original 'write' method.

Current behavior before PR:
Changing the User name will cause the employee name related to being also changed.

Desired behavior after PR is merged:
ONLY if 'get_employee_values_sync' method is overridden, the name of the employee can remain the same even if the user name is changed. Otherwise, the 'write' method will remain the same.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-02 02:27 UTC, TheAlekLuna commented
@deivislaya here it is!

2022-07-02 02:28 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/95159).

2022-07-02 05:43 UTC, luisg123v requested changes
Commit title should include module name and summarice the change, e.g.:

`[IMP] hr: make inheritable user fields to sync with employee`

2022-07-02 05:43 UTC, luisg123v commented on addons/hr/models/res_users.py
> +    def get_employee_values_sync(self, vals):
Use private method, please

```suggestion
    def _get_employee_values_sync(self, vals):
```

2022-07-02 05:43 UTC, luisg123v commented on addons/hr/models/res_users.py
> +        """This method keep the original behavior inside 'write' method, but allow us to select either a
This is more of a commit description than a docstring. If read after your change is applied, it doesn't make much of a sense.

Maybe something like

```"""Get values to synk with related employee when the user is changed"""

2022-07-02 05:50 UTC, luisg123v commented
@TheAlekLuna this same change could be cherry-picked to v13, so target branch 13.0 instead (patch will still work).

2022-07-02 05:52 UTC, luisg123v commented
CC @hugho-ad

2022-07-04 17:50 UTC, hugho-ad approved these changes

2022-07-04 18:07 UTC, TheAlekLuna commented
Hello @luisg123v !
Commit title changed. 
Method name changed to private.
Docstring remade.
Target branche changed from 14.0 > 13.0 

Let's wait for checks!

2022-07-06 02:11 UTC, luisg123v approved these changes
LGTM :+1:

Hi @IT-Ideas, what do you think?

2022-07-11 11:32 UTC, IT-Ideas commented
Hello @TheAlekLuna 👋🏼 
The hr scope is held by @kba-odoo

2022-07-14 14:55 UTC, luisg123v commented
Hi @kba-odoo,

I like also tat idea, just take into account returning a dictionary instead of a list has the advantage of being able to sync fields that don't have the same name in both user and employee

Regards,

2022-07-14 16:42 UTC, luisg123v commented
@TheAlekLuna could you apply requested changes, please?

2022-07-15 22:53 UTC, TheAlekLuna commented
@luisg123v changes applied!
@kba-odoo this is ready! can you help me, pls?

Regards!

2022-07-18 06:26 UTC, kba-odoo commented
Thanks @TheAlekLuna !

robodoo r+

2022-07-18 07:11 UTC, closed without merging