[REF] *: Migrate Bootstrap to version 5.1.3
odoo/odoo pull request #95450
Opened 2022-07-06 14:36 UTC by rfr-odoo

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-06 14:51 UTC, adr-odoo commented
@beledouxdenis

2022-07-06 16:04 UTC, AntoineVDV requested changes

2022-07-06 17:50 UTC, pparidans commented on addons/payment/views/payment_templates.xml
> +                                  class="rounded-pill text-bg-warning"
Same as for the previous comment.

2022-07-06 17:50 UTC, pparidans commented on addons/payment/views/payment_templates.xml
> +                                <span class="rounded-pill text-bg-secondary ms-1">
Actually the "badge" class was already missing... (cf. https://getbootstrap.com/docs/4.3/components/badge/)

2022-07-07 08:00 UTC, AntoineVDV commented on addons/payment/views/payment_templates.xml
> +                                <span class="rounded-pill text-bg-secondary ms-1">
I'm fine with whichever adaption you need to do to the structure, classes, etc. to restore the original visual. If you correct inconsistencies while doing so, even better!

2022-07-07 09:30 UTC, xmo-odoo commented
@robodoo override=ci/security

Bootstrap updates

2022-07-07 11:15 UTC, adr-odoo approved these changes
@robodoo rebase-merge p=1 r+

2022-07-07 11:22 UTC, d-fence commented
robodoo p=0

2022-07-07 11:27 UTC, d-fence commented
robodoo r+ p=0

2022-07-07 11:28 UTC, robodoo commented
I'm sorry, @d-fence. This PR is already reviewed, reviewing it again is useless.

2022-07-07 12:14 UTC, adr-odoo commented
> And where is the upgrade script?

We are currently working on it with the website team.

2022-07-07 12:32 UTC, KangOl commented
But it should have been merged with this PR.

2022-07-07 12:43 UTC, closed without merging

2022-07-09 10:08 UTC, adr-odoo commented
Personal note: +32,205 -27,824

2022-07-11 06:06 UTC, xmo-odoo commented
> Personal note: +32,205 -27,824

Is that where you hid your treasure?