[IMP] purchase: SCSS revamp
odoo/odoo pull request #95732
Opened 2022-07-11 09:09 UTC by morm-odoo

Prior to this commit, the dashboard was a table and there was
unnecessary scss.
This commit changes the table into the new bs5 grids
and clean the scss files.

task-2906527

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-11 09:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/95732).

2022-07-12 09:20 UTC, stefanorigano reviewed
Hello @morm-odoo , some feedbacks for you.
I'm not sure about the final visual result, especially on mobile.

The previous implementation was kinda broken on small screens...
![image](https://user-images.githubusercontent.com/8558351/178455509-4e9275bf-a262-4481-9ab2-ef75f5844dfe.png)

...the one you propose is not an improvement unfortunately 😕
![image](https://user-images.githubusercontent.com/8558351/178455707-f4ed2bf6-8971-43d4-a106-df286f0db8f8.png)

For the rest seems good 👍 
TIp: create and push an enterprise branch with the same so runbot will performs enterprise tests too ;)

2022-07-12 09:20 UTC, stefanorigano commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +
Add a new line at the end of each file... there are editor's extensions that hi-lights these kind of issues ;)

2022-07-12 09:20 UTC, stefanorigano commented on addons/web/static/src/legacy/scss/bootstrap_overridden.scss
> +$enable-cssgrid:              true;
These lines should be added in the "Options" section of the file.

2022-07-12 11:57 UTC, morm-odoo commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +                                <div class="g-col-3 o_dashboard_action p-0" title="All Draft RFQs" context='{"search_default_draft_rfqs": true}'>
Is it ok now? :)

2022-07-12 13:12 UTC, stefanorigano requested changes
@morm-odoo , good.

Almost there, courage 👍

2022-07-12 13:12 UTC, stefanorigano commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +                    <div class="d-flex align-items-center g-col-5 g-col-md-3 py-2 ">
unnecessary space before closing `"`

2022-07-12 13:12 UTC, stefanorigano commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +                    <div class="o_dashboard_action g-col-2 g-col-md-3 p-0 " title="My Waiting RFQs" context='{"search_default_waiting_rfqs": true, "search_default_my_purchases": true}'>
again, unnecessary space before closing `"` (there are many other occurrences)

2022-07-12 13:12 UTC, stefanorigano commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +                        <div class="d-flex align-items-center g-col-5 g-col-md-3 py-2">Avg Order Value (<t t-out="values['company_currency_symbol']"/>)</div>
move `g-col-X` classes before utility classes

2022-07-12 13:13 UTC, stefanorigano commented on addons/purchase/static/src/xml/purchase_dashboard.xml
> +                                <div class="g-col-3 o_dashboard_action p-0" title="All Draft RFQs" context='{"search_default_draft_rfqs": true}'>
here yes, but I've spot other issues, check my new messages 👍

2022-07-12 16:03 UTC, stefanorigano requested changes

2022-07-12 16:03 UTC, stefanorigano commented on addons/web/static/src/legacy/scss/bootstrap_overridden.scss
> +$enable-cssgrid: true;
It's very unlikely that people want to disable it, but it's better to add `!default` ;)

2022-07-13 09:28 UTC, closed without merging

2022-07-13 09:51 UTC, morm-odoo commented
moved to
- https://github.com/odoo/odoo/pull/95902