[FIX] website: await async part when changing transparent header color
odoo/odoo pull request #95896
Opened 2022-07-13 09:06 UTC by detrouxdev

Commit [1] adapted the topMenuColor option to the 14.0 editor but
did not await the call to action_demand.

This didn't cause any issue but could lead to race conditions and is
not correct.

It also breaks after [2].

[1]: https://github.com/odoo/odoo/commit/98c8438f5225dbc34b15fc2ed5b9918d537bb71b
[2]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b

task-2687506

2022-07-13 09:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/95896).

2022-07-13 11:37 UTC, detrouxdev commented
related to : https://github.com/odoo/odoo/pull/94949

2022-07-13 12:14 UTC, qsm-odoo requested changes
@detrouxdev 

Commit message:

- task-XXX at the end, after the commit references please
- `await action_demand call` as title is not precise and too technical to me. I would go with `[FIX] website: await async part when changing transparent header color` -> at least it gives an idea of the functional stuff you are fixing (even if it is just about a potential race condition as you explain in your message).

2022-07-14 11:40 UTC, qsm-odoo approved these changes
@robodoo r+

2022-07-14 12:33 UTC, closed without merging