[FIX]sale_project: fix muted text
odoo/odoo pull request #95979
Opened 2022-07-14 08:46 UTC by pasa-odoo

In this PR, fixes the muted text in 'task_in_project' and
'project_only' fields.

task-2891983

2022-10-11 09:10 UTC, MissingNoShiny requested changes
Thanks for your work. :slightly_smiling_face: 
Since the changes are done in stable, we also need to update the .pot file

2022-10-11 09:44 UTC, mba-odoo commented
@MissingNoShiny , No new string is added in a diff. just changed position of the line so no update in pot file.  Thanks

2022-10-11 09:46 UTC, MissingNoShiny commented
You are right, my bad 🙂

2022-10-18 07:10 UTC, xavierbol approved these changes
LGTM, thanks for the fix. 🙂 

robodoo r+

2022-10-18 08:17 UTC, closed without merging