[ADD] l10n_es: add cooperatives account chart template
odoo/odoo pull request #96156
Opened 2022-07-18 07:49 UTC by acysos

Hello,

This PR add the PCGE for Spanish Cooperatives pymes and complete.
This PGCE make some change in groups because add new groups only for this type of companies. So it have a common account chart template with the groups that are common and two new templates for each cooperative.

It neccesary to change some accounts in the common account chart template because have different name. This is the list of account removed por account chart template common and added in each chart:

- 112
- 113
- 150
- 171
- 502
- 521
- 526
- 5585

More information about Spanish Cooperative Chart Account here: https://www.boe.es/buscar/doc.php?id=BOE-A-2010-20034

Greetings

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-18 07:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96156).

2022-07-18 08:01 UTC, acysos commented
Hello, 

I see that I remove the doble colon in the CSV when I edited. I go to send again.

Greetings

2022-07-18 08:15 UTC, acysos commented
Hello,

I have change the CSV with the double quotes. The PR can continue.

Greetings

2022-07-19 08:04 UTC, ValentinVinagre commented
@HaraldPanten

2022-07-19 09:25 UTC, HaraldPanten requested changes
Just some writing changes

2022-07-19 09:25 UTC, HaraldPanten commented on addons/l10n_es/data/account_chart_template_data.xml
> +        <field name="name">PGCE Cooperativas común</field>
If we want to continue with the same structure as the other COA, "Común" should be written with capital letter. Shouldn't it?

2022-07-19 09:25 UTC, HaraldPanten commented on addons/l10n_es/data/account_group.xml
> +    </record>
Desembolsos no exigidos

2022-07-19 09:25 UTC, HaraldPanten commented on addons/l10n_es/data/account_group.xml
> +    </record>
You are writing "Fondo de Educación, Formación y Promoción a largo plazo" for long term. I think you should use capital letters here, and solve typos.

2022-07-19 09:25 UTC, HaraldPanten commented on addons/l10n_es/data/account_group.xml
> +    </record>
Efectuadas

2022-07-27 17:22 UTC, acysos commented
@HaraldPanten hecho

2022-07-28 08:16 UTC, HaraldPanten commented
Hi @acysos 

I still see accent marks that you should add in Educacion, Formacion y Promocion --> Educación, Formación y Promoción

Could you check the commit message as well? I see 2 [ADD] messages that are meaning the same.

Sorry for being picky 😝.

THX!

2022-08-11 15:49 UTC, acysos commented
> Hi @acysos
> 
> I still see accent marks that you should add in Educacion, Formacion y Promocion --> Educación, Formación y Promoción
> 
> Could you check the commit message as well? I see 2 [ADD] messages that are meaning the same.
> 
> Sorry for being picky stuck_out_tongue_closed_eyes.
> 
> THX!

xD Done

2022-09-02 10:47 UTC, HaraldPanten approved these changes
We could add this one and make changes in a future if needed.

2022-09-27 07:12 UTC, cubells approved these changes
:+1: 

LGTM

Code review and test

2022-12-30 09:19 UTC, closed without merging