[IMP] hr_expense: add can_be_expensed field in product view
odoo/odoo pull request #96619
Opened 2022-07-25 10:19 UTC by kba-odoo

Purpose: Allow users to make product 'expense available'
(or the opposite, unset them as expense products) by making the
field 'can_be_Expensed' available in the base product view.

task - 2909067

2022-07-25 10:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96619).

2022-07-25 11:33 UTC, bouvyd requested changes

2022-07-25 11:33 UTC, bouvyd commented on addons/hr_expense/views/hr_expense_views.xml
> +                    <div>
should be a `<span class="d-inline-block">` for consistency with the other elements inside the `<div name="options">`.

2022-07-26 09:39 UTC, kba-odoo commented
robodoo r+

2022-07-27 04:05 UTC, closed without merging