[FIX] website: restore inline SVG on steps snippet start
odoo/odoo pull request #96734
Opened 2022-07-26 09:37 UTC by bso-odoo

Since [1] when a process steps snippet is sanitized, the content of the
inline SVGs involved in drawing the connectors is lost.

This commit restores those SVGs in case they are not present when the
snippet is started.

Steps to reproduce:
- Drop a steps snippet in the product-specific part of a product page.
- Configure its arrow type and its color.
- Save.
=> The connectors were not displayed anymore.

[1]: https://github.com/odoo/odoo/commit/aba31e9f2d8a44ce1586403f2a621a6caeed57b4

task-2829961

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-26 09:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96734).

2022-07-26 12:37 UTC, qsm-odoo requested changes
I would go the way it was discussed with RDE here: https://github.com/odoo/odoo/pull/91639#discussion_r875834453 (for the gmap snippet at the time): an utility method called by both the option and public widget. It has the advantage of not doing anything on page load for visitors + as it is a strange case to have a public widget build something in its `start` but not destroy it in its `destroy`, better to clearly see where the option builds what is related to edition (the SVG) (without relying on the public widget, which should be disabled in editable mode then).

2022-07-26 12:37 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_process_steps/000.js
> +        'connector_changed': '_onConnectorChanged',
I don't think this handler is ever called? This is the name of an Odoo event which you trigger_up, not a DOM event.

2022-07-26 14:54 UTC, bso-odoo commented
> I would go the way it was discussed with RDE here: [#91639 (comment)](https://github.com/odoo/odoo/pull/91639#discussion_r875834453) (for the gmap snippet at the time): an utility method called by both the option and public widget. It has the advantage of not doing anything on page load for visitors + as it is a strange case to have a public widget build something in its `start` but not destroy it in its `destroy`, better to clearly see where the option builds what is related to edition (the SVG) (without relying on the public widget, which should be disabled in editable mode then).

@qsm-odoo Moved the redrawing to an util, and kept the reset of the defs SVG specific to the public widget in case it had been lost. Tested on runbot too.

2022-07-26 15:33 UTC, qsm-odoo requested changes
Quick review: seems good (without testing) except for a small detail about indentation.

Although: this is technically not stable as your remove many methods from the option class :grimacing: Should we make an exception and not care @rdeodoo ? (as it's targeting a small snippet in saas-15.X only). Maybe just keeping them empty for the sake of it so that potential call/include do nothing instead of crashing?

Also we could argue that it may be more difficult for an external custo to add arrow types with the new code (as you use inline functions inside an utility function, maybe you could make the utils a class with internal methods instead @bso-odoo) ?

2022-07-26 15:33 UTC, qsm-odoo commented on addons/website/static/src/snippets/s_process_steps/000.xml
> +        <defs>
Don't indent the first level of XML files, just add blank lines between the templates (to separate from `<templates`)

2022-07-26 16:04 UTC, rdeodoo commented
Exception is fine here IMO yes, very niche/specific part of the code + 15.2.

2022-07-27 12:51 UTC, bso-odoo commented
> Also we could argue that it may be more difficult for an external custo to add arrow types with the new code (as you use inline functions inside an utility function, maybe you could make the utils a class with internal methods instead @bso-odoo) ?

@qsm-odoo Moved the function to a dedicated utility file within the Process Steps snippet folder and turned it into an actual JS class to allow for method patching.

2022-07-27 14:29 UTC, qsm-odoo commented
Seems good but will need a security override though :grimacing: Waiting for some internal discussion about sanitization before r+ though.

2022-07-27 15:01 UTC, bso-odoo commented
> Seems good but will need a security override though grimacing Waiting for some internal discussion about sanitization before r+ though.

Shouldn't there be a `qweb.renderAsElement(template, params)` to avoid these ?

2022-07-28 10:03 UTC, qsm-odoo commented
> Shouldn't there be a `qweb.renderAsElement(template, params)` to avoid these ?

@bso-odoo Yes, that's something I'd like too, but I guess the need will be less frequent the more we start using OWL so it may not be needed (but not to avoid security trigger, rendering a qweb template is not enough to say it is safe (in your case I think it is)).

2022-07-28 10:09 UTC, qsm-odoo commented
We'll handle this differently in the end, sorry for the lost time @bso-odoo

2022-07-28 10:09 UTC, closed without merging