[Fix] point_of_sale: Use taxed prices in discount comparison
odoo/odoo pull request #96749
Opened 2022-07-26 11:21 UTC by khah-odoo

Before this commit, If "Show public price & discount to the customer"
discount display policy is selected, taxed prices in the pricelist with
discounts are compared with untaxed prices in the public pricelist,
which leads to not showing the discounted values when the pricelist
value is less than untaxed list price, but the taxed value is more than
untaxed list price.

Steps to reproduce:

1. Create a product, add it to a pricelist with a lower price in a way
 that if the tax is added the price is more than its sale price, add a
 tax option to the product
2. Set the pricelist discount display policy as `Show public price &
discount to the customer`
3. Set the PoS to use tax-included prices, and to use the discounted
pricelist
4. start the PoS session, add the product, you will see that the
public price isn't shown (with a strike-through)

To fix, we can use a different function that computes the taxed public
price, so it could be compared with the pricelist price.

opw-2919734
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-26 11:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96749).

2022-07-27 06:43 UTC, khah-odoo commented
@caburj Could you please take a look?

2022-08-01 08:47 UTC, khah-odoo commented
> @khah-odoo I made some changes, can you try it? You can just pull this branch to have the commit locally, because I didn't force-push. The idea is to reuse `compute_fixed_price` which practically does the same as your new method.

It doesn't work for some reason.

2022-08-01 09:15 UTC, caburj commented
I see. I just notice that the method's main consideration is about "included" taxes.

2022-08-01 09:20 UTC, caburj requested changes
You can drop my commit. While you're at it, can you consider the following?

2022-08-01 09:20 UTC, caburj commented on addons/point_of_sale/static/src/js/models.js
> +            return price;
* Reduce indentation.
* Can you also consider "iface_tax_included" since the result of this method is compared to "get_unit_display_price"?

2022-08-01 12:03 UTC, caburj requested changes
Return taxed price when "tax_included == 'total'", otherwise, return the lst_price (doesn't matter if it include some "tax-included price". So that we have apple-to-apple comparison with get_unit_display_price.

2022-08-01 12:03 UTC, caburj commented on addons/point_of_sale/static/src/js/models.js
> +        return price;
```suggestion
        var lst_price = this.get_lst_price();
        if (this.pos.config.iface_tax_included === 'total') {
            var product =  this.get_product();
            var taxes_ids = product.taxes_id;
            var product_taxes = this.get_taxes_after_fp(taxes_ids);
            return this.compute_all(product_taxes, lst_price, 1, this.pos.currency.rounding).total_included;
        }
        return lst_price;
```

2022-08-02 06:46 UTC, caburj approved these changes

2022-08-02 06:46 UTC, caburj commented
@robodoo r+

2022-08-02 07:14 UTC, robodoo commented
Staging failed: ci/runbot on 8d2ff25b845d47473274ed1ffa4384e5ac2eeab0 (view more at https://runbot.odoo.com/runbot/build/18051889)

2022-08-02 09:27 UTC, caburj commented
@robodoo retry

2022-08-02 10:17 UTC, closed without merging