[IMP] web: add stacked line chart
odoo/odoo pull request #96833
Opened 2022-07-27 08:54 UTC by dafl-odoo

2022-07-27 08:55 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96833).

2022-07-28 11:10 UTC, SimonGenin commented on addons/project/static/src/burndown_chart/burndown_chart_view.js
> +  Renderer: GraphRenderer,
not necessary

2022-07-28 11:13 UTC, SimonGenin commented on addons/web/static/src/views/graph/graph_renderer.js
> +        }
add as a boolean expr above

2022-07-28 11:22 UTC, SimonGenin commented
@IT-Ideas for info, we're moving this feature to a generic one.

2022-07-28 11:46 UTC, IT-Ideas commented
@SimonGenin, Nice 🙂
Thanks for the notification!

2022-08-01 09:45 UTC, SimonGenin requested changes

2022-08-01 09:45 UTC, SimonGenin commented on addons/web/static/src/views/graph/graph_renderer.js
> +            elementOptions.line.fill = stacked;
`fill` is assigned to `false` then to `stacked`, you can make this a one liner.

2022-08-01 09:45 UTC, SimonGenin commented on addons/web/static/src/views/graph/graph_renderer.js
> +        }
While this is probably easier to read, it seems that you just loop over dataset a second time for "nothing".
Maybe check if you can put this in the for loop above, something like:
```js
if (stacked) {
    dataset.backgroundColor = hexToRGBA(dataset.borderColor, 0.4);
}
```
I ultimately agree that this code is somewhat gross.

2022-08-01 09:45 UTC, SimonGenin commented on addons/web/static/tests/views/graph_view_tests.js
> +        assert.expect(4);
not needed

2022-08-01 09:45 UTC, SimonGenin commented on addons/web/static/tests/views/graph_view_tests.js
> +        assert.expect(5);
not needed (i think ? maybe the for loop at the end can cause problems?)

2022-08-01 12:38 UTC, SimonGenin approved these changes

2022-08-01 14:01 UTC, closed without merging