[FIX] account: fix account type computation
odoo/odoo pull request #96832
Opened 2022-07-27 08:52 UTC by aliyatastemirova

There can be many accounts in self and the "search_read" is currently breaking because of self.company_id in the domain.
Account codes should however be still limited to the current company and we don't want to do a `search_read` for account codes within the for loop, so one way is to prefetch and create a nested dictionary.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-27 08:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/96832).

2022-07-29 09:53 UTC, Levizar requested changes
Only one small code change that might be insignificant otherwise the code LGTM but the commit message could me clearer and straightforward.

You are solving 2 different problems but it's not obvious from the commit message:
- multi-company environment
- Default value for account.type

Put a small sentence below each to explain the problem.

Bonus just to mess around with you: :grin:  
> we don't want to search_read for account codes within
the for loop, so one way is to prefetch and create a nested dictionary

This appear subjective. Instead of it, you can write something like "for performance reason we batch the searching part" which is more factual.

Otherwise, nice job!

2022-07-29 09:53 UTC, Levizar commented on addons/account/models/account_account.py
> +        all_accounts = self.search_read(domain=[('code', '!=', False), ('company_id', 'in', self.company_id.ids)], fields=['code', 'account_type', 'company_id'])
We only need those from companies of `accounts_to_process` which might be a subset
```suggestion
        all_accounts = self.search_read(domain=[('code', '!=', False), ('company_id', 'in', accounts_to_process.company_id.ids)], fields=['code', 'account_type', 'company_id'])
```

2022-07-29 10:20 UTC, Levizar approved these changes

2022-08-08 06:24 UTC, aliyatastemirova commented on addons/account/models/account_account.py
> +        all_accounts = self.search_read(domain=[('code', '!=', False), ('company_id', 'in', accounts_to_process.company_id.ids)], fields=['code', 'account_type', 'company_id'])
you're right, I fixed that :slightly_smiling_face:

2022-08-08 09:14 UTC, william-andre approved these changes
@robodoo r+

2022-08-08 13:33 UTC, closed without merging