[FIX] website: not record header animation in editor history
odoo/odoo pull request #97372
Opened 2022-08-03 09:20 UTC by bso-odoo

Before this commit when the header scroll effect was happening, the
related DOM updates were recorded in the editor's history.

This commit deactivates the history during the updates of the header.

Steps to reproduce:
- Drop a few snippets in the page. (e.g. 4 Banners)
- Save.
- Edit page.
- Drop another snippet in the page. (e.g. Text)
- Click undo => Text block disappears.
- Click redo => Text block reappears as expected.
- Click undo.
- Scroll down until header vanishes and reappears.
=> Redo step is lost, undo tries to undo the header animation.

task-2930568

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-03 09:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/97372).

2022-08-03 17:03 UTC, qsm-odoo requested changes
Hello @bso-odoo I tried to reproduce the issue following your steps and I could not, any more information?

Note: about the fix itself, I guess it make sense, I would just like to see an effect :grimacing: Actually I created this PR a year ago: https://github.com/odoo/odoo/pull/74923, the plan was to review the way to stop/restart that new editor team's observer, avoiding the ugly short-circuit syntax `this.options.wysiwyg &&`, uncoupling the use of the wysiwyg directly inside public widgets and handling every DOM edition that was done by public widgets and that the editor should not track (like your header one here)... as you can see there were lots of them (and probably more now)... I actually made the fix you are trying to do here in my PR: https://github.com/odoo/odoo/pull/74923/files#diff-875d6d62cea4b05ee632b9c35fbfa92f0f2db831472943a22ef508f0c9662167R83.

But in the end, I stopped midway that work when I saw that I was doing had no effect and I have been meaning to talk with the editor team about that PR and/or wait to receive actual bug reports related to this (like the one you are trying to solve here... but again, I cannot reproduce the problem (at least consistently, I see it sometimes when I am not trying to...) :grimacing:).

2022-08-04 07:58 UTC, bso-odoo commented
Fixed the scenario, but I think I better rebase your branch instead of having this merged.

2022-08-04 08:45 UTC, qsm-odoo approved these changes
:+1: 

As discussed I'll review https://github.com/odoo/odoo/pull/74923 by myself later to review all similar potential problems.

@robodoo r+

2022-08-04 10:33 UTC, closed without merging