[FIX] website_sale_delivery: no carrier change if there is a valid transaction
odoo/odoo pull request #97414
Opened 2022-08-03 14:01 UTC by mafo-odoo

Issue:
Customers can use Mollie and lower the price on a quotation through changing the
delivery method, if they have two pages "/shop/payment" and proceed with payment
on one they can still change the carrier on the second. Although the quotation is
not confirmed because of mismatching amount, a confirmation email is still sent
and a bank payment is still created. Please see the following test video.

Solution:
We add a check so that changing a carrier can only be done when a no active/done
transaction is linked to the sale order.

opw-2925673

2022-08-04 13:54 UTC, Williambraecky requested changes
Hello 👋 
Thanks for the fix, it makes sense.
It is badly missing a test though.
Cheers

2022-08-04 13:54 UTC, Williambraecky commented on addons/website_sale_delivery/controllers/main.py
> +            if any(order.transaction_ids.filtered(lambda tx: tx.state not in ["canceled", "error"])):
Written as such it is not very efficient, though it mostly likely wont matter, any accepts generators
```suggestion
            if any(tx.state not in ("canceled", "error") for tx in order.transaction_ids):
```

2022-08-09 07:53 UTC, mafo-odoo commented
@Williambraecky

2022-08-09 08:05 UTC, Williambraecky commented
Thanks for the fix and test!
robodoo r+

2022-08-09 09:09 UTC, closed without merging