[FIX] website: fix configurator/edit menu ui
odoo/odoo pull request #97570
Opened 2022-08-05 10:47 UTC by younn-o

[FIX] website: fix edit menu dialog ui

This commit adds the hint that [1] missed when adapting the "Edit menu"
dialog to owl, and adds a margin removed by the bootsrap update.

[1]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b

task-2687506

-----

[FIX] website: fix configurator style

When [1] moved the configurator frontend to a backend client action, it
did not correctly adapt the style: the backend's root element has a
font-size of 12px when the frontend has the default one (16px). As a
result, every css property using rem units was inaccurate.
This commit temporarily sets the root element font size to 16px when the
configurator client action is displayed to restore the style it had on
versions 15.X.
It also adapts the style to bootsrap 5.

[1]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b

task-2687506

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-05 10:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/97570).

2022-08-05 13:03 UTC, younn-o commented
@qsm-odoo Here is a lazy solution to restore the configurator's previous style, without changing all classes depending on rem units. What do you think about it ?

2022-08-08 14:57 UTC, qsm-odoo requested changes

2022-08-08 14:57 UTC, qsm-odoo commented on addons/website/static/src/client_actions/configurator/configurator.js
> +        }, () => []);
No, instead the CSS has to be adapted I guess. It's also fine that the design changed a little to match a bit more the backend spirit IMO. I think it's not a commit for you to make in the end, a designer should review the configurator design post all refactorings.

2022-08-08 14:57 UTC, qsm-odoo commented on addons/website/static/src/client_actions/configurator/configurator.scss
> +    }
I don't see why the bootstrap behavior would have to be reviewed for the configurator. At that point, using bootstrap make no sense if we don't even like what it does and override everything :grimacing: Again, I think a design should review the structure etc. I'll remove this commit and create a task for it.

2022-08-08 14:57 UTC, qsm-odoo commented on addons/website/static/src/components/dialog/dialog.scss
> +    }
The form-group class apparently does not exist anymore in BS5... and apparently the class was kept everywhere in the codebase anyway :( Migrating to BS5 does not mean restoring its old rules case by case... :grimacing: Here what you have to do is properly migrate to BS5, not restore BS4 rules to make it work :/

2022-08-08 14:57 UTC, qsm-odoo commented on addons/website/static/src/components/dialog/edit_menu.xml
> +                <small class="form-text text-muted">Hint: Type '/' to search an existing page and '#' to link to an anchor.</small>
I'll move this to another PR and keep this PR open in draft, we'll see what to do with it when you are back

2022-08-08 15:04 UTC, qsm-odoo commented on addons/website/static/src/components/dialog/edit_menu.xml
> +                <small class="form-text text-muted">Hint: Type '/' to search an existing page and '#' to link to an anchor.</small>
https://github.com/odoo/odoo/pull/97733 -> also removed the text-muted class which had no effect

2022-09-20 14:08 UTC, qsm-odoo commented
Design was adapted another way.

2022-09-20 14:08 UTC, closed without merging