[FIX] website_hr_recruitment: disable caching on thank you page
odoo/odoo pull request #97591
Opened 2022-08-05 13:11 UTC by kba-odoo

The Thank You page was cached and could potentially show the same
recruiter for different job applications.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-05 13:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/97591).

2022-08-05 14:51 UTC, rdeodoo requested changes
Isn't the enterprise's helpdesk thank you page suffering of the same issue?

Edit: Went a bit fast reading the PR, previous message was off topic.

2022-08-05 14:53 UTC, rdeodoo commented
@robodoo up to saas-15.3
In saas 15.4 this field doesn't exists anymore, replaced by the new qweb cache

2022-08-05 18:30 UTC, rdeodoo commented
@fw-bot  up to saas-15.3
In saas 15.4 this field doesn't exists anymore, replaced by the new qweb cache

2022-08-08 06:18 UTC, kba-odoo commented
> Isn't the enterprise's helpdesk thank you page suffering of the same issue?
> 
> Edit: Went a bit fast reading the PR, previous message was off topic.

Indeed :-) That's how we found out the issue PR odoo/enterprise#29778 :smile:

2022-08-08 06:18 UTC, kba-odoo commented
robodoo r+

2022-08-08 12:02 UTC, closed without merging