[ADD] point_of_sale: Send Context Closing POS Session
odoo/odoo pull request #97864
Opened 2022-08-09 23:58 UTC by CarmenMiranda

Sending a context when you are closing a `pos.session` will allow you to make some validations/actions only when the closing is being done from the UI.
For example, sending values for new fields or a message that includes something from the pos, like the Cashier ID, name, etc.

Also, it will help more when it is necessary to inherit the function in a simpler way, to avoid having to overwrite it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-09 23:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/97864).

2022-11-10 16:52 UTC, hugho-ad commented
@trj-odoo @caburj what do you think about this?

could you review it pls

2022-11-14 09:07 UTC, trj-odoo requested changes
Sending the `userContext` is fine but not the other one. 
I get what you are trying to do, we should maybe add `**kwargs` to the closing session python method but this'll be in master and not in stable.
I can suggest you an alternative which is to override the `bankPaymentMethodDiffPairs` with what you really want on your end

2022-11-14 09:07 UTC, trj-odoo commented on addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
> +                    }
This doesn't ring a bell, not sure if this even exists

2022-11-14 23:16 UTC, CarmenMiranda commented
Hi @trj-odoo 

> Sending the userContext is fine but not the other one.

We tried to use that context in order to send the value that we need but it doesn't work (as shown in the video)

> I can suggest you an alternative which is to override the bankPaymentMethodDiffPairs with what you really want on your end

I get your suggestion but that alternative includes the override of the whole `closeSession` function not only `bankPaymentMethodDiffPairs` since this is just a little part of that function, and I don't think is the right thing to do. I'm open to more suggestions

![Task - VG - closeSession Function](https://user-images.githubusercontent.com/26889951/201787300-bac708f5-3857-406c-bfd7-3ba1c962f054.png)

https://github.com/odoo/odoo/blob/d282b8c6f495092218833864162c7fc061bc4e08/addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js#L103-L157

Video with the `userContext` test (sorry in advance for my pronunciation 🙈): https://youtu.be/kz93ON8OzXg

2022-11-15 10:59 UTC, trj-odoo commented
> We tried to use that context in order to send the value that we need but it doesn't work (as shown in the video)

From what I can see, both `user_context` and `userContext` are computed field (js getter), hence why you cannot assign it.
What you can do in your customization is to patch said getter.
Basically you will need to do this
```js
override close_session:
  const unpatch = patch(this.env.session, {
     user_context: () => {
       const result = this._super();
       // do something on result
       return result;
     },
  });
  const result = call super on close_session;
  unpatch();
  return result;
```
Don't forget to import `patch.js`

2022-11-16 19:12 UTC, CarmenMiranda commented
Hi @trj-odoo Thanks for your suggestion, it worked 😄 
```js

async closeSession () {
    patch(
        this.env.session,
        name,
        {
            get user_context () {
                const context_result = this._super();
                // Something here
                return context_result;
            },
        }
    );
   const result = await super.closeSession();
   unpatch(this.env.session, name);
   return result
}
```

I already did the change to avoid sending just the `user_context`

2022-11-17 15:25 UTC, trj-odoo commented
Glad it worked :smile:
It seems there's a small problem with the pipelines, could you rebase your branch with the latest changes of 15.0 and push it ? 
Also can you change the tag? `[ADD]` refers more to an addition of a new module, it feels more like a [IMP]/[REF] imho ([guideline](https://www.odoo.com/documentation/master/contributing/development/coding_guidelines.html?highlight=github%20guideline#tag-and-module-name))
I'll merge it afterwards

2022-11-17 16:40 UTC, CarmenMiranda commented
Hi, @trj-odoo I did the rebase and the change in the name of the commit 😄

2022-11-18 08:47 UTC, trj-odoo commented
@robodoo r+

2022-11-18 10:24 UTC, closed without merging