[FIX] website: remove an option from the facebook block
odoo/odoo pull request #98177
Opened 2022-08-16 12:13 UTC by Guillaume-gdi

Facebook no longer supports the option to see the profile pictures of
friends who have liked the page. So this commit removes the option
(which was no longer useful). See [same issue at WordPress].

[same issue at WordPress]: https://wordpress.org/support/topic/facebook-likebox-disappearance-of-the-faces-of-friends-who-like-the-page/

task-2950329
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-16 12:14 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98177).

2022-08-18 12:29 UTC, rdeodoo requested changes
Why not just adding `d-none` directly on the template?
It is a static XML file, it will work for existing databases without the need of a -u

2022-08-18 15:03 UTC, Guillaume-gdi commented
> Why not just adding `d-none` directly on the template? It is a static XML file, it will work for existing databases without the need of a -u

Indeed, now it should be OK :+1:

2022-08-18 15:05 UTC, rdeodoo commented
add a TODO comment in the code or no one will figure why is there a d-none, + so we don't forget to remove it later

2022-08-18 15:14 UTC, Guillaume-gdi commented
> add a TODO comment in the code or no one will figure why is there a d-none, + so we don't forget to remove it later

Done :heavy_check_mark:

2022-08-18 15:21 UTC, rdeodoo approved these changes
@robodoo r+

Everything tends to same conclusion, this option is not working anymore.

2022-08-18 16:37 UTC, closed without merging