[IMP] account: add default filter to journal items when coming from an account
odoo/odoo pull request #98183
Opened 2022-08-16 12:47 UTC by ushyme

This PR adds the 'posted' filter by default on the journal items list view, when coming from an account's form view.

opw-2896728

2022-08-16 12:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98183).

2022-08-24 09:07 UTC, agr-odoo requested changes
Make sense, even if it more an improvement
However, instead of adding the context on the button calling the action, it may be better to modify the action definition, so it will behave consistently
https://github.com/odoo/odoo/blob/830730adb1f0a59beca838b55ae0b04fb051bef5/addons/account/views/account_move_views.xml#L1383-L1387

2022-08-24 13:59 UTC, agr-odoo approved these changes
robodoo r+

2022-08-24 14:29 UTC, robodoo commented
@ushyme @agr-odoo staging failed: ci/runbot on 6f39e1916499335a1fe21b878345a7c4735b8d8b (view more at https://runbot.odoo.com/runbot/build/18691638)

2022-08-25 11:17 UTC, ushyme commented
@robodoo retry

2022-08-25 12:08 UTC, closed without merging