[FIX] requirements.txt: Fix compatibility of cryptography with pyopenssl
odoo/odoo pull request #98232
Opened 2022-08-17 02:11 UTC by moylop260

The pinned pyopenssl==19.0.0 is not compatible with latest version of cryptography

pyopenssl==19.0.0 requires cryptography>=2.3

Currently, it is installing latest version cryptography-37.0.4 for a fresh environment

But using the l10n_mx_edi module it is raising the following error:

    INFO db odoo.modules.loading: Module l10n_mx_edi: loading demo
    INFO db odoo.modules.loading: loading l10n_mx_edi/demo/demo_cfdi.xml
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
        class X509StoreFlags(object):
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

The debian:bullseye is using cryptography==3.3.2 same for docker image odoo:14.0
Based on apt package python3-cryptography

Even if ubuntu:20.04 and odoo-sh are using cryptography==2.8 both versions are compatible with pyopenssl==19.0.0

`pip install -U cryptography==37.0.4`

`psql test -c "UPDATE ir_module_module SET demo=True WHERE name='l10n_mx_edi'" && ~/instance/odoo/odoo-bin -d test -i l10n_mx_edi --stop-after-init --log-level=warn; pip3 freeze |grep -i "pyopenssl\|cryptography"`

Now, repeat the last command but using:
`pip install -U cryptography==3.3.2`

Result:
 - <img width="1907" alt="Screen Shot 2022-08-16 at 21 09 48" src="https://user-images.githubusercontent.com/6644187/185019107-cd0a42b5-dd9e-4ffe-9287-bab7e06063eb.png">

2022-08-17 02:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98232).

2022-08-17 02:27 UTC, moylop260 commented
@d-fence @odony 

Hi my friends!

Could you check this requirements case, please?

2022-08-17 10:26 UTC, d-fence requested changes
I confirm that installing the requirements on a clean ubuntu focal will lead to the installation of the latest cryptography package.

It does not happen on the runbot docker images because some pre-installed Debian packages are installing the Ubuntu `python3-cryptography` package.

2022-08-17 10:26 UTC, d-fence commented on requirements.txt
> +cryptography==3.3.2
```suggestion
cryptography==2.8
```
When the [Debian](https://packages.debian.org/bullseye/python3-cryptography) and [Ubuntu](https://packages.ubuntu.com/focal/python3-cryptography) versions are different, I prefer to choose the smallest one.

2022-08-23 14:43 UTC, moylop260 commented
@d-fence 

Any update on this?

2022-09-28 01:46 UTC, moylop260 commented
Fixed from https://github.com/odoo/odoo/pull/99829

2022-09-28 01:46 UTC, closed without merging