Master hr home working nm roco
odoo/odoo pull request #98242
Opened 2022-08-17 08:33 UTC by tivisse

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-17 08:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98242).

2022-08-22 08:29 UTC, kba-odoo commented on addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
> +                        configurations (work entry type, homeworking location, ...) to be lost.</span>
I guess the "homeworking location" is no longer relevant here? :thinking:

2022-09-05 08:07 UTC, kba-odoo requested changes

2022-09-05 08:07 UTC, kba-odoo commented on addons/hr/views/hr_employee_views.xml
> +                <tree string="Employees" expand="context.get('expand', False)" multi_edit="1" sample="1" js_class="hr_employee_list">
I'd use a less generic name than `expand` as it can be confusing and not know where/why it's used.
Something like `expand_employee_list` maybe

2022-09-05 08:07 UTC, kba-odoo commented on addons/hr_holidays/views/hr_views.xml
> +                             style="background-color: white"
```suggestion
                        <div class="row o_kanban_primary_bottom bottom_block bg-white"
```

2022-09-06 06:51 UTC, tivisse commented
@robodoo r+ merge

2022-09-06 06:52 UTC, robodoo commented
Merge method set to merge directly, using the PR as merge commit message.

2022-09-06 07:00 UTC, robodoo commented
@tivisse linked pull request(s) odoo/enterprise#30489 not ready. Linked PRs are not staged until all of them are ready.

2022-09-06 10:00 UTC, merged