[FIX][15.0] base: fix helpstring
odoo/odoo pull request #98258
Opened 2022-08-17 10:07 UTC by minhthuy145

While testing Odoo application, I have the following problem:

- Currently: helpstring of 2 fields "Unit per USD" and "USD per unit" are the same, displayed as
"The currency of rate 1 to the rate of the currency."

> Desired: Modify the helpstring of the USD per unit field.
=> help="The rate of the currency to the currency of rate 1"

https://user-images.githubusercontent.com/91191721/185093011-cdf9d88e-7f28-43e3-a5e9-4bd85244d7aa.mp4

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-17 10:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98258).

2022-08-18 01:57 UTC, minhthuy145 commented
@tranngocson1996 Can you help me with this ticket?

2022-08-18 08:47 UTC, Julien00859 requested changes
The PO file should only contains the modified bit: i.e. the bit about the new help message, not the whole pot.

2022-08-18 09:40 UTC, minhthuy145 commented
base

2022-08-22 06:25 UTC, jbw-odoo approved these changes
Lgtm

2022-08-22 07:20 UTC, merged

2022-08-23 08:46 UTC, Julien00859 commented
You screwed up your branch, the commit is missing

![image](https://user-images.githubusercontent.com/8208953/186114429-85e21aa3-0fbe-451c-9619-73466c4f2b26.png)

2022-08-23 08:51 UTC, tranngocson1996 commented
@minhthuy145 ping ping

2022-08-23 09:12 UTC, Julien00859 commented
It looks like it moved too #98540