[FIX] web: disable timezone convert for Date field custom filters
odoo/odoo pull request #98413
Opened 2022-08-18 14:08 UTC by Jinjiu96

Reproduction:
1. Install Timesheet, and load demo data
2. Mimic a timezone in browser (Chrome): Right click->Inspect->Sensors,
in the Location-> choose Other…, type “America/Puerto_Rico” in Timezone
ID, refresh the page
3. Go to Timesheets->Timesheets->All timesheets, choose pivot view
4. Add custom filter, Date is between 1st/Aug/2022 and 5th/Aug/2022,
apply
5. The filter result is correct but the tag in the search bar is “Date
is between 31/07/2022 and 04/08/2022”

This also happens to other fields with type Date, but not Datetime. For
example, in Accounting->Reporting->Invoices Analysis->Pivot view, the
same issue happens with Due Date filter. For Datetime field, it doesn’t
have the issue, for example in CRM->Sales->My pipeline, change to pivot
view, the custom filter for Assignment Date doesn’t have the time zone
issue.

Note: reproduction usually works during the daytime in Brussels.

Reason: miswriting when rewrote custom_filter_item from V14 to V15. The
value pushed to descriptionArray should not be changed on time zone.

Fix: set timezone as false in the formatting of descriptionArray

Related PR: https://github.com/odoo-dev/odoo/commit/aeb8e49972f871b0c9b07c507987ee77cf5e8abd?diff=unified#diff-6d9230cfcd007b087b2851cbf0b4a33b26dc3c91087853da6fe7ce8c2b60e42f

Reference code in V14: https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/js/control_panel/custom_filter_item.js#L170-L173

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-18 14:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98413).

2022-08-25 08:31 UTC, Arcasias reviewed
Looks good, although I went a little further and moved your fix to the local `parseField` and `formatField` functions to keep consistency accross the whole file. If you're ok with it and once it's green I'll squash the changes and r+ :+1:

2022-08-25 09:20 UTC, Jinjiu96 commented
> Looks good, although I went a little further and moved your fix to the local `parseField` and `formatField` functions to keep consistency accross the whole file. If you're ok with it and once it's green I'll squash the changes and r+ +1

Hi @Arcasias Thanks a bunch for the input! I understand the changes and it works for sure. But I prefer the previous fix because:
1. from the perspective of a bug fixer, we usually try to keep the change minimum. Here in the new commit, the number of parameters for `parseField` and `formatField` is changed. Though it's only used in this file, I prefer to keep the function definition as before.
2. Also with the parameter `opts`, we also have better modularity and generalization in my opinion, so when we add a new formatting option for other data types in the future, we can do the formatting locally instead of changing the definition. 

Hello@brboi  What do you think?

2022-08-25 09:56 UTC, brboi commented
Hello @Jinjiu96 

As parseField and formatField are local to this file, this is better IMHO to make the fix in those, as @Arcasias suggested.

I understand your point of view regarding the lesser diff policy, but the Arcasias proposition is not too much diff I think.

2022-08-25 09:57 UTC, brboi commented
> @Jinjiu96 hey again, you're right about future possible formatter types and APIs, so I kept the `opts` parameter. However I insist on adding the `timezone` property in these local helpers for the sake of consistency (and in this case `timezone` should always be true if the field type is 'datetime', correct me if I'm wrong).

You're right.

2022-08-25 10:00 UTC, Jinjiu96 commented
> Hello @Jinjiu96
> 
> As parseField and formatField are local to this file, this is better IMHO to make the fix in those, as @Arcasias suggested.
> 
> I understand your point of view regarding the lesser diff policy, but the Arcasias proposition is not too much diff I think.



> @Jinjiu96 hey again, you're right about future possible formatter types and APIs, so I kept the `opts` parameter. However I insist on adding the `timezone` property in these local helpers for the sake of consistency (and in this case `timezone` should always be true if the field type is 'datetime', correct me if I'm wrong).

Thanks for the quick fix! I saw that @brboi agrees with you and he's the expert in DateTime. I'm happy as long as he is happy :smile: Looks great to me! :+1:

2022-08-25 10:01 UTC, brboi commented
FYI, @Jinjiu96 the default timezone option has been changed for datetimes in master: https://github.com/odoo/odoo/commit/9d1786c3613b44a59bfe2ffca54a62502e82142b#diff-752cdb896135dde7e44e79943e422bb68b058c7707e8404654c8e68df1b018fe

2022-08-25 10:03 UTC, brboi requested changes
Nice fix.

Please squash and adapt commit message ("descriptionArray" part)

2022-08-25 10:27 UTC, Jinjiu96 commented
> FYI, @Jinjiu96 the default timezone option has been changed for datetimes in master: [9d1786c#diff-752cdb896135dde7e44e79943e422bb68b058c7707e8404654c8e68df1b018fe](https://github.com/odoo/odoo/commit/9d1786c3613b44a59bfe2ffca54a62502e82142b#diff-752cdb896135dde7e44e79943e422bb68b058c7707e8404654c8e68df1b018fe)

I saw that `options.timezone=true` is set by default for `DateTime`. I believe we won't need this fix in master then :smile: Thanks for the hint!

2022-08-25 11:49 UTC, Jinjiu96 commented
@fw-bot up to saas-15.3

2022-08-25 14:45 UTC, Jinjiu96 commented
@brboi Squashed and commit message changed, could you r+ it or approve it? thanks! :smile:

2022-08-25 15:44 UTC, brboi commented
Please wait tomorrow, I have found a related le issue in custom filter item.

2022-08-26 10:17 UTC, brboi commented
Hello @Jinjiu96 

There is an issue with web/src/core/datepicker/datepicker.js

To reproduce, create a custom filter with 'between' operator on a date (or datetime) field, change the value in only one the two datepickers. Now check 'onApply' in custom_filter_item.js. The conditions array contains two DateTime objects, but one is in local timezone (the one you did not changed) and the other one is in UTC.

As parse/format helpers DOES have a different behavior regarding the input DateTime object timezone, there is an issue here...

In master, @Arcasias and I have worked together in order to remove the timezone option in both parse/format helpers, resulting in a consistent usage of luxon DateTime objects across odoo. But we cannot do this change in stable.

So I propose to fix this in the datepicker directly, by adding the following `date.setZone(...` line right after parsing:
```js
    onDateChange({ useStatic } = {}) {
        let date;
        try {
            date = this.parseValue(this.inputRef.el.value, this.getOptions(useStatic));
            // parseValue outputs the correct date but with the wrong timezone
            date.setZone("local", { keepLocalTime: true });
        } catch (_err) {
        // ...
```

What do you think, @Arcasias , @Jinjiu96  ?
If you're OK, @Jinjiu96 could you make this fix in another/same commit and add a test ? Thanks.

2022-08-26 10:54 UTC, Jinjiu96 commented
@brboi Thanks for the new fix suggestion! I will check in the afternoon :smile:

2022-08-29 13:52 UTC, Jinjiu96 commented
> Hello @Jinjiu96
> 
> There is an issue with web/src/core/datepicker/datepicker.js
> 
> To reproduce, create a custom filter with 'between' operator on a date (or datetime) field, change the value in only one the two datepickers. Now check 'onApply' in custom_filter_item.js. The conditions array contains two DateTime objects, but one is in local timezone (the one you did not changed) and the other one is in UTC.
> 
> As parse/format helpers DOES have a different behavior regarding the input DateTime object timezone, there is an issue here...
> 
> In master, @Arcasias and I have worked together in order to remove the timezone option in both parse/format helpers, resulting in a consistent usage of luxon DateTime objects across odoo. But we cannot do this change in stable.
> 
> So I propose to fix this in the datepicker directly, by adding the following `date.setZone(...` line right after parsing:
> 
> ```js
>     onDateChange({ useStatic } = {}) {
>         let date;
>         try {
>             date = this.parseValue(this.inputRef.el.value, this.getOptions(useStatic));
>             // parseValue outputs the correct date but with the wrong timezone
>             date = date.setZone("local", { keepLocalTime: true });
>         } catch (_err) {
>         // ...
> ```
> 
> What do you think, @Arcasias , @Jinjiu96 ? If you're OK, @Jinjiu96 could you make this fix in another/same commit and add a test ? Thanks.

Hi @brboi , I checked the condition values if we only change one date and leave the other untouched, the values indeed have different timezones. However, I'm not very sure it's the best place to fix it directly in the datepicker. I tried it locally but it breaks many tests of DatePicker (for date), the DateTimePicker tests are ok though. I'm still trying to understand why this happens, e.g. the date was converted to the day before of selected date. But I have a gut feeling that the date is transformed to UTC somewhere because the timezone is set as local. Could you give me some insights about it? Thanks! :pray: 

![2022-08-29_15-46_1](https://user-images.githubusercontent.com/23055668/187216832-44e581c9-2643-46fe-b3b1-43a9c2cd2f8a.png)

2022-08-30 14:07 UTC, brboi commented
Hello @Jinjiu96 

I tried another approach:
- ignore the fact the the datepicker could output inconsistently a datetime object in utc/local timezone
- but make sure that everywhere we format a date it is consistent

If you are interested in the diff I will discuss tomorrow with @Arcasias , here it is:
```diff
diff --git a/addons/web/static/src/core/l10n/dates.js b/addons/web/static/src/core/l10n/dates.js
index fe2ad77bbc9..39a659fa9ca 100644
--- a/addons/web/static/src/core/l10n/dates.js
+++ b/addons/web/static/src/core/l10n/dates.js
@@ -151,6 +151,7 @@ export const strftimeToLuxonFormat = memoize(function strftimeToLuxonFormat(valu
  * @returns {string}
  */
 export function formatDate(value, options = {}) {
+    value = value.setZone("utc", { keepLocalTime: true });
     return formatDateTime(value, {
         timezone: false, // Timezone should never alter a 'date' value.
         ...options,
```

If we are doing this, I will do it myself, write test and we will also discuss to merge your PR as it is.

2022-08-31 09:07 UTC, Jinjiu96 commented
> Hello @Jinjiu96
> 
> I tried another approach:
> 
> * ignore the fact the the datepicker could output inconsistently a datetime object in utc/local timezone
> * but make sure that everywhere we format a date it is consistent
> 
> If you are interested in the diff I will discuss tomorrow with @Arcasias , here it is:
> 
> ```diff
> diff --git a/addons/web/static/src/core/l10n/dates.js b/addons/web/static/src/core/l10n/dates.js
> index fe2ad77bbc9..39a659fa9ca 100644
> --- a/addons/web/static/src/core/l10n/dates.js
> +++ b/addons/web/static/src/core/l10n/dates.js
> @@ -151,6 +151,7 @@ export const strftimeToLuxonFormat = memoize(function strftimeToLuxonFormat(valu
>   * @returns {string}
>   */
>  export function formatDate(value, options = {}) {
> +    value = value.setZone("utc", { keepLocalTime: true });
>      return formatDateTime(value, {
>          timezone: false, // Timezone should never alter a 'date' value.
>          ...options,
> ```
> 
> If we are doing this, I will do it myself, write test and we will also discuss to merge your PR as it is.
> 
> Edit: runbot is green with this change (which is a bit freaking sweat_smile)

Hi @brboi , thanks for the new solution! I did a few tests locally and it indeed doesn't break anything. I also tested a case where I set a different time zone in the browser and check the filtered result. The filtered result is the same without the change. So technically it works well :rofl: 

It took me some time to understand what this is doing. Based on the documentation of luxon here: https://github.com/odoo/odoo/pull/98413#issuecomment-1231720308 I think we are setting the time zone of the date without changing the value. However, this, in my opinion, should mean we will have a different time (or date) from the original time (or date) we picked. Like the example in the attached pic, e.g. the value equal checking is `false`. 

Another side note: I found when we parse the `Date` type in `date.js`, we specify that `timezone: false` in `return formatDateTime(...)` (https://github.com/odoo/odoo/blob/15.0/addons/web/static/src/core/l10n/dates.js#L201-L212) Maybe that's why all the tests are still green after the change? Because it doesn't consider the timezone change anyways in the parsing step?

Please feel free to correct me if I'm wrong, not yet an expert in time zone shifting :smile: 
![2022-08-31_10-47](https://user-images.githubusercontent.com/23055668/187639863-5ad006aa-234f-43d1-bbdb-aae48b1e456d.png)

2022-08-31 13:18 UTC, brboi commented
Hello @Jinjiu96 you have well understand the keepLocalTime option.
I discussed with @Arcasias and we agree that this is the best fix we can do in a stable branch.
I'll handle that part. In the meantime, I will r+ this PR as it is independent.

Thanks for the discussion ;-)
I already picked and adapted your commit for the master branch in odoo/odoo#98980

2022-08-31 13:19 UTC, brboi commented
@robodoo r+
@fw-bot up to saas-15.3

2022-08-31 14:49 UTC, Jinjiu96 commented
> Hello @Jinjiu96 you have well understand the keepLocalTime option. I discussed with @Arcasias and we agree that this is the best fix we can do in a stable branch. I'll handle that part in #99327. In the meantime, I will r+ this PR as it is independent.
> 
> Thanks for the discussion ;-) I already picked and adapted your commit for the master branch in #98980

Thanks a bunch! :smile:

2022-08-31 15:37 UTC, closed without merging