[FIX] website_sale, product: function defined in child module
odoo/odoo pull request #98493
Opened 2022-08-19 14:29 UTC by Jinjiu96

Reason:
The function _create_first_product_variant is used in the product module
but only defined in its child module website_sale

Fix: change the definition place to module product

opw-2790543

Related PR: https://github.com/odoo/odoo/pull/88075

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-19 14:30 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98493).

2022-08-22 15:16 UTC, Williambraecky requested changes
Hello :)
Totally ok with the change, but this should be done in the version it was introduced, which seems to be 13.0? (12.0 is out of support)
Could you change the target version please? :)
Thanks

2022-08-22 15:22 UTC, Jinjiu96 commented
> Hello :) Totally ok with the change, but this should be done in the version it was introduced, which seems to be 13.0? (12.0 is out of support) Could you change the target version please? :) Thanks

Of course!

2022-08-22 15:24 UTC, Williambraecky commented
Oof you pinged a lot of people here 😅 
FYI for next time you should create another branch in 13.0 and do another PR

2022-08-22 15:31 UTC, Jinjiu96 commented
> 

Yes indeed. My bad, guys! I will make another PR :pray:

2022-08-22 15:31 UTC, closed without merging