[IMP] website_sale: edit feature name
odoo/odoo pull request #98528
Opened 2022-08-20 03:23 UTC by tuyenphung

While testing the application, I get the following error:

[Step]:

         + Select a product A
         + On tab `eComerce` choose Field `Accessory Products` : Select a product is accessory products for product A.
         + Click button `Go to Website`.
         + Click button `Add to Cart`.
         + Click `Alternative Products in my cart` on menu `Customize`.

[Expected]:

         + This function will add the `accessory product` of product A to the cart, so the name of this function should be Accessory Products in my cart

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-20 03:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98528).

2022-08-22 04:05 UTC, tranngocson1996 commented
@Williambraecky plz review this PR. Thank bro
cc: @xmo-odoo

2022-08-22 07:08 UTC, Williambraecky requested changes
Hello LGTM

The commit message is empty to I would suggest something along those lines.

```
[IMP] website_sale: rename badly named template

The template `suggested_products_list` is badly named as it does
not show alternative products in the cart but accessory/suggested
products, leading to possible confusion in the customize menu when
editing the website.
This commit changes it to `Accessory Products in my cart`.
```

2022-08-22 07:09 UTC, tranngocson1996 commented
> The commit message is empty to I would suggest something along those lines.

@Williambraecky thank bro. @tuyenphung fix it

2022-08-22 07:13 UTC, tuyenphung commented
> > The commit message is empty to I would suggest something along those lines.
> 
> @Williambraecky thank bro. @tuyenphung fix it

ok bro!!
cc: @Williambraecky

2022-08-22 07:20 UTC, Williambraecky commented
Thanks!
robodoo r+

2022-08-22 09:01 UTC, closed without merging