[FIX] website: prevent BS5 from failing when dropdown-menu is missing
odoo/odoo pull request #98688
Opened 2022-08-23 12:17 UTC by bso-odoo

Since [1] when the searchbar was created, the menu is removed when the
focus gets out of the suggestion box.
Since [2] when BS5 was introduced this poses a problem because BS5 tries
to access the `.dropdown-menu` element which has been removed.

This commit hides the old menu instead of removing it in case no new
menu is created, so that BS5 does not fail.

Steps to reproduce:
- Go to shop page.
- Type "desk" in the search input.
- The suggestion popup appears.
- Click outside the field. (e.g. to the left of it)
- Click on the search field.
=> An error popup was displayed.

[1]: https://github.com/odoo/odoo/commit/ce1da231b9c84d1b4e06b265ee7b1a6d89bf51ea
[2]: https://github.com/odoo/odoo/commit/971e5a91aab96d36129a823e03f1f9f1b1293968

task-2960518

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-23 12:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98688).

2023-01-25 07:51 UTC, bso-odoo commented
@xO-Tx Old concerns expressed in the task have been solved by https://github.com/odoo/odoo/pull/98756.
Kept the keyboard navigation fix on this PR, and rebased in on 16.0.

2023-02-09 07:48 UTC, bso-odoo commented
@xO-Tx I forgot to ping you after the last changes. This is ready for review.

2023-02-10 15:28 UTC, xO-Tx requested changes
> Since [1] when BS5 was introduced, the keyboard navigation of search
> autocomplete suggestions did not work anymore.

@bso-odoo code here LGTM :+1:, but from what I see, the keyboard navigation was lost on 15.0 too (not because of BS5 updates), I just did a quick check and it seems that the `:focus` style was overridden on `.dropdown-menu` ([following an OWL refactoring for 15.0](https://github.com/odoo/odoo/pull/76892/commits/7355f9453bd839106e554593c1b03a9f8d7b9bc7#diff-e801969af5282018e0952093876e7c7472c2fbd4846cebb238f21cfcf15d5957R4-R6)).

So it seems that keyboard navigation works correctly but the `:focus` was invisible (to test...). Wouldn't be better to target 15.0 with this code? in worst case, we can fix the CSS on 15.0 to restore the focus on `.o_searchbar_form` (see [A]) and set your code on 16.0...

[A]: Maybe something like:
```CSS
.o_searchbar_form {
    .dropdown-item:focus {
        background-color: $dropdown-link-hover-bg;
    }
}
```
What do you think ?

2023-02-13 16:08 UTC, bso-odoo commented
> > Since [1] when BS5 was introduced, the keyboard navigation of search
> > autocomplete suggestions did not work anymore.
> 
> @bso-odoo code here LGTM +1, but from what I see, the keyboard navigation was lost on 15.0 too (not because of BS5 updates), I just did a quick check and it seems that the `:focus` style was overridden on `.dropdown-menu` ([following an OWL refactoring for 15.0](https://github.com/odoo/odoo/pull/76892/commits/7355f9453bd839106e554593c1b03a9f8d7b9bc7#diff-e801969af5282018e0952093876e7c7472c2fbd4846cebb238f21cfcf15d5957R4-R6)).
> 
> So it seems that keyboard navigation works correctly but the `:focus` was invisible (to test...). Wouldn't be better to target 15.0 with this code? in worst case, we can fix the CSS on 15.0 to restore the focus on `.o_searchbar_form` (see [A]) and set your code on 16.0...
> 
> [A]: Maybe something like:
> 
> ```css
> .o_searchbar_form {
>     .dropdown-item:focus {
>         background-color: $dropdown-link-hover-bg;
>     }
> }
> ```
> 
> What do you think ?

@xO-Tx I think I will create another PR on 15 to fix the CSS. => https://github.com/odoo/odoo/pull/112569

2023-02-14 15:22 UTC, xO-Tx commented
@robodoo r+

2023-02-14 17:11 UTC, closed without merging

2023-02-14 17:45 UTC, qsm-odoo commented
Not sure about this merge, asking question on backport PR at https://github.com/odoo/odoo/pull/112569#pullrequestreview-1298097700