[FIX] website_hr_recruitment: show job only when company has website
odoo/odoo pull request #98833
Opened 2022-08-24 14:21 UTC by abla001

To Reporduce
=============
- Create two companies A and B
- Create website for A
- Create job position in B

try to access the job description.

Problem
=======
When redirected to website we have an access error.
This is caused by the fact that the website belongs to Company A and we try to display job from Company B in it.

Solution
=========
Remove the possibility to access job description if the job's company doesn't have a website.

opw-2957744

2022-08-24 14:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98833).

2022-08-26 18:11 UTC, nle-odoo reviewed
looks good to me besides details

- this leaves an empty span (alternative would be to have t-if on span) but it is invisible so doesn't matter too much

- hr.job().company_id is not required so the link should be shown if there is no company_id on the record

- the website field on company_id is a char field that contain the website url (eg. in the footer) you can have it without website installed. you would need to search a website (with limit=1) with that company instead.

even with these changes, we don't know if the link will really work since we will get possibly to a website of another company (eg. if a website of another company is configured for the current domain) when we click on the link, but it would be a little better if we don't want the error page.

2022-09-02 05:24 UTC, abla001 commented
@kba-odoo can you take a look at this fix, thank you :pray:

2022-09-05 07:15 UTC, abla001 commented
@kba-odoo can you review this please ?

2022-09-05 13:53 UTC, rdeodoo requested changes
@robodoo r-

Something is certainly off, `website` field of `company` has nothing at all to do with the website module and URL.

It should never be part of business code, at best it is part of some mail templates default link value in footer etc

Didn't have time to review this yet, sorry, but it looks off.

We will have a deeper look ASAP and sorry if the r- was not needed, but pretty sure this is wrong

2022-09-05 13:53 UTC, rdeodoo commented on addons/website_hr_recruitment/models/hr_recruitment.py
> +            job.website_url = job.company_id.website and "/jobs/detail/%s" % job.id
? website is a plain text field, it has nothing to do and it not and should not be involved in anything regarding the website module

2022-09-05 14:05 UTC, abla001 commented
> @robodoo r-
> 
> Something is certainly off, `website` field of `company` has nothing at all to do with the website module and URL.
> 
> It should never be part of business code, at best it is part of some mail templates default link value in footer etc
> 
> Didn't have time to review this yet, sorry, but it looks off.
> 
> We will have a deeper look ASAP and sorry if the r- was not needed, but pretty sure this is wrong

oh my bad I didn't pay attention to @nle-odoo (sorry :pray: ) commented above, I will make a search on website with company_id instead.

2022-09-05 14:24 UTC, rdeodoo commented
I am not even sure of what you are trying to fix here.

That's how multi company and multi website works in Odoo.
It won't let you see records on a website if this record is not allowed on the website / company you are landing on.

Is that a real problem here for job position as the whole kanban card is redirecting to the website? (Instead of just the "Go to Website" in the form view usually)

I doubt this even qualifies as a bug, and we probably don't want to change anything in 13.0.

Arguably this could be improved for 15.0, or simply master.

2022-09-05 14:28 UTC, abla001 commented
> I am not even sure of what you are trying to fix here.
> 
> That's how multi company and multi website works in Odoo. It won't let you see records on a website if this record is not allowed on the website / company you are landing on.
> 
> Is that a real problem here for job position as the whole kanban card is redirecting to the website? (Instead of just the "Go to Website" in the form view usually)
> 
> I doubt this even qualifies as a bug, and we probably don't want to change anything in 13.0.
> 
> Arguably this could be improved for 15.0, or simply master.

yeh I agree it's not really a bug, we just want to remove the ability to access to website from the job kanban if the company of the job doesn't have a website because it will lead to access error anyway, I can close this PR and create an improvement in 14 or 15

2022-09-07 17:00 UTC, rdeodoo requested changes
Honestly I wouldn't do it in 13.0. The risk/reward is quite poor to say the least, especially since this does not really qualifies a bug strictly speaking:
- No traceback
- There is workaround (don't click on the kanban card but on edit)

Plus it is only about multi-company environments.

You should target master, or 15.0 if you really think this is important despite not really being a bug, the risk/reward will be a bit better than in 13.0 (living for years now).

In later version than 13.0, you will be able to simply patch the kanban view `if` condition without altering the `website_url` and might just do something like `t-if="record.company_id and record.company_id.website_id"`

2022-09-08 07:43 UTC, abla001 commented
I agree with you the risk/reward is not that important

2022-09-08 07:43 UTC, closed without merging