[FIX] web_editor: differentiate images from text within iframe
odoo/odoo pull request #98889
Opened 2022-08-25 11:15 UTC by bso-odoo

Since [1] when the website UI was moved to the backend, the edited page
is inside an iframe. Conditions based on instanceof are not reliable
anymore: the element's type is specific to the document inside which it
was created. Because of this, `targetEl instanceof HTMLElement` is
`true` when the snippet was dragged from the options menu - because both
`targetEl` and `HTMLElement` are the ones from the main document where
the editor options panel is. But it is `false` if the page was loaded
because the `targetEl` is of a type from the iframe's document.

We cannot use `targetEl.ownerDocument.defaultView.HTMLElement` because
the `ownerDocument` is the current one to which the target belongs - not
the one where it was created. So, a full condition would have to look
like this:
```js
(targetEl instanceof this.odooEditor.document.defaultView.HTMLElement
                || targetEl instanceof HTMLElement)
```
That is pretty verbose, so I just check if it has the `querySelectorAll`
method instead.

Steps to reproduce:
- Drop a "Text - Image" snippet.
- Save.
- Edit.
- Select image.
- Press "CTRL+K".
=> An `<a class="oe_edited_link">` is created instead of triggering the
image link tools - as if it was a text selection (except the text link
tool is not available).

[1]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b

task-2962619

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-25 11:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98889).

2022-08-25 13:21 UTC, bso-odoo commented
@qsm-odoo This is a one-liner to fix a weird behavior when using `instanceof` across `iframe`s.

2022-08-26 07:42 UTC, qsm-odoo requested changes
@bso-odoo This seems to be a Chrome-only bug, maybe it's worth mentioning :+1: And on Chrome, while this fixes the issue, this creates a bigger one: following the mentioned steps: the image disappears after hitting CTRL+K :grimacing: (note that I rebased your branch in local before testing, may be related).

2022-08-26 09:47 UTC, bso-odoo commented
> @bso-odoo This seems to be a Chrome-only bug, maybe it's worth mentioning +1 And on Chrome, while this fixes the issue, this creates a bigger one: following the mentioned steps: the image disappears after hitting CTRL+K grimacing (note that I rebased your branch in local before testing, may be related).

@qsm-odoo I pushed a fix for the undisplayed image in Chrome. I have to reset the `src` to make it re-evaluate the width & height. This causes a flicker. I could try to avoid the flicker by doing the following - but I do not know if it is worth it:
- keep track of the correct width and height before wrapping the image
- forcing the image width and height attributes to those values (but we don't want to save those attributes)
- create a new image element similar to the initial one
- once the new image is loaded, replace the old one by the new one

2022-08-31 13:16 UTC, qsm-odoo approved these changes
@robodoo rebase-ff r+

2022-08-31 13:16 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-08-31 15:18 UTC, closed without merging