[FIX] payment,*: unable to access the documents of your companies
odoo/odoo pull request #98910
Opened 2022-08-25 12:53 UTC by Feyensv

Task ID - 2960827
opw-2954181

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-25 12:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/98910).

2022-08-25 15:03 UTC, AntoineVDV requested changes

2022-08-26 10:08 UTC, AntoineVDV approved these changes

2022-08-29 15:51 UTC, Feyensv commented
robodoo r+

2022-08-29 17:12 UTC, closed without merging