[FIX] website_forum: avoid singleton error
odoo/odoo pull request #99090
Opened 2022-08-29 09:48 UTC by tdecaluwe

The current domain on the forum post `child_ids` field is not guaranteed to work since it requires the recordset on which it is applied to be a singleton.

2022-09-16 09:15 UTC, JKE-be commented on addons/website_forum/models/forum.py
> +    child_ids = fields.One2many('forum.post', 'parent_id', string='Post Answers', domain=lambda self: [('forum_id', 'in', self.forum_id.ids)])
When it is a problem in real world ? 
A post is only for one forum...

Avoid useless pr, in old version, that you let in draft and nobody will check... 
It is just noise...

2022-09-16 11:27 UTC, tdecaluwe commented on addons/website_forum/models/forum.py
> +    child_ids = fields.One2many('forum.post', 'parent_id', string='Post Answers', domain=lambda self: [('forum_id', 'in', self.forum_id.ids)])
It is causing problems in most POC builds for improved uninstallations. This is an example:
https://runbot.odoo.com/runbot/build/18514454

2022-09-16 12:19 UTC, JKE-be commented on addons/website_forum/models/forum.py
> +    child_ids = fields.One2many('forum.post', 'parent_id', string='Post Answers', domain=lambda self: [('forum_id', 'in', self.forum_id.ids)])
ok, my bad in this case. :thinking: 

Meanwhile I found this commit in another pr with uninstall code... 
But without context, this one was really strange.

With the context, it is still strange as bug, but I consider that you double checked yourself and it is the best way ;)

2022-09-16 12:38 UTC, tdecaluwe commented on addons/website_forum/models/forum.py
> +    child_ids = fields.One2many('forum.post', 'parent_id', string='Post Answers', domain=lambda self: [('forum_id', 'in', self.forum_id.ids)])
Full story: for me the two reasons to create this PR were:

1. We're always reminded about keeping technical debt small. Waiting for a bug to happen didn't seem like a piece of technical debt we'd want to keep around. Personally, I thought this was enough of a reason for this PR, which is why I didn't include the part about the uninstallations. But, as you mentioned, this might not warrant targeting a stable version.
2. I saw this problem popping up regularly in POC versions for the improved uninstallation process.

More importantly, this bug **should** happen when uninstalling modules including more than one forum post in their (demo) data. At least, when we require using an uninstallation algorithm that guarantees correctness (full details available on request). This assertion holds in general for inverse fields of many2one fields having `ondelete == 'cascade'`.

Currently, it is not yet clear if improved uninstallation code will also be backported to stable versions, but as the diff of this PR is quite small and easily reviewed, targeting stable seemed acceptable to me.

2022-10-07 10:12 UTC, tdecaluwe commented
From @rco-odoo at https://github.com/odoo/odoo/pull/102410:
> That domain function is just plain wrong: it is expected to take any recordset from the field's model, not necessarily the recordset being read. It is also used in search() with an empty recordset, BTW.
> 
> The purpose of domain is to restrict the subset of lines to the ones that satisfy some extra condition, but the condition may not depend on the records with the one2many field. The domain above looks more like a domain for the form view, in fact.

2022-10-18 12:50 UTC, rco-odoo approved these changes
The existing domain did not make sense in the context of the ORM.  However, I can see it make sense in a view (client side).  That looks correct to me.

2022-10-19 15:08 UTC, rdeodoo requested changes
If I am not wrong, this change makes the domain actually useless, no? And so, you might as well remove it simply, it would be the same?

Actually, it is missing the most important part in the commit message: why do we have that domain?
Again, if I am not missing anything, this is "simply" to prevent visual inconsistencies if someone is messing around in the backend, like change the forum_id of a question but not its answer or the other way around.
It will do two things (that I can think of):
- Adapt the answer count to not count the ones from another forum (that are kinda lost forever)
- Don't show those "wrong forum" answer in the child_ids o2m in the form view

So could you mention this to the commit message?

I gave it a try and it seems like those 2 cases are not working anymore with this commit, right ?(don't forget to add/remove a child to update the query count as it is stored based on the child_ids, need to recompute it)

Then, from there, I guess what should really be done (on top or in place of this) is to patch the `write()` method to keep those post and answers `forum_id` synchronized, so if you change it on the post, it changes also the childs, and if you change the child forum, same (or forbidden?). If possible ofc.

Or adapt the view to add the domain + change the `api.depends` to consider the forum changes.

Or do nothing in 14.0 if no real issue (if it does no break the nightly until master eg) and adapt the `write` in 16.0/master

2022-10-20 12:20 UTC, rdeodoo commented
> This definitely makes sense, but to me it seems like this should be done in the 16.0 forwardport, right?

Ideally yes, in place of the domain. At least it's true now, the longer it will take to hit v16 the less true it will be. Arguably after next week I would even do that in master only to not alter the Odoo 16.

> Presumably, it would be better to use this revision https://github.com/odoo/odoo/commit/89176134f839487cbc5ca482e2b0d768a81e6294, as it works as expected for both usecases.

Didn't test but if that's true (keep the current behavior + fix the uninstall issue), well, that would be ideal indeed :+1:

2022-11-15 10:30 UTC, tde-banana-odoo commented
Hello,

As we will gradually take over forum, some thoughts here ... I don't really understand the usage of that domain. Either you add a constraint (and/or something in create / write), either nothing and we let the o2m live as it is. Using a domain for m2o / o2m is strange for me.

If some view allows to change the forum, we could add a domain, and/or rely on a constraint. Having inconsistent hierarchy is probably something we want to avoid, and a domain does not really prevent from having wrong data.

Cheers !

2022-12-02 06:41 UTC, tdecaluwe commented
@tde-banana-odoo I created the PR because the current domain definition is faulty, not supported and potentially causes problems when uninstalling. As you say, having inconsistent hierarchy data is something we want to avoid, so what do you suggest?

2023-01-10 18:36 UTC, closed without merging