[FIX] web: numpad decimal with number type
odoo/odoo pull request #99126
Opened 2022-08-29 13:09 UTC by yosa-odoo

Steps to reproduce:
- in Barcode > Inventory Adjustment
In the quantities add a decimal numpad

Issue:
Traceback

opw-2956481

2022-08-29 13:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99126).

2022-09-07 08:30 UTC, yosa-odoo commented
Hello @brboi,

I tried the solution you provided but it didn't work. And after many conversations (notably with @nle-odoo), it seems this solution is viable though not ideal.

Let me know of what you think :)

2022-09-15 11:43 UTC, brboi requested changes

2022-09-15 11:43 UTC, brboi commented on addons/web/static/tests/legacy/fields/basic_fields_tests.js
> +
assert here that the field is of type number (important!)

2022-09-15 11:43 UTC, brboi commented on addons/web/static/tests/legacy/fields/basic_fields_tests.js
> +        assert.verifySteps(["Using the numpad decimal did not crash"])
No need to explain something you don't assert.

It made me realize that the main point of this test is to check that the event is not default prevented!
Remove this and see comment of the patch section.

2022-09-15 11:43 UTC, brboi commented on addons/web/static/tests/legacy/fields/basic_fields_tests.js
> +            }})
I realized that the important assertion we can make here is that the browser will apply the default behavior of the keydown event (also a bit of nitpicking: code style)
```suggestion
        assert.expect(2); // (as we don't use verifySteps anymore)

        patchWithCleanup(basicFields.NumericField.constructor.prototype, {
           _onKeydown(ev) {
                const res = this._super(...arguments);

                // This _onKeydown handler must not prevent default
                // a keydown event for NumericField with type=number
                assert.ok(!ev.defaultPrevented);

                return res;
            },
        });
```

2022-09-15 14:19 UTC, brboi approved these changes

2022-09-19 07:10 UTC, kitan191 commented
@robodoo delegate+

2022-09-19 07:21 UTC, yosa-odoo commented
@robodoo r+

2022-09-19 09:41 UTC, closed without merging