[FIX] website: popup snippet scrolling
odoo/odoo pull request #99338
Opened 2022-08-31 13:43 UTC by adr-odoo

cookie bar + popup snippet

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-31 13:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99338).

2022-09-01 08:53 UTC, qsm-odoo requested changes

2022-09-01 08:53 UTC, qsm-odoo commented on addons/web/static/src/legacy/scss/base_frontend.scss
> +.modal-open #wrapwrap:not(.s_has_popup) {
@adr-odoo This rule will soon be gone so it is kinda annoying... why do we need this? If there is no popup, there no modal-open class normally... right? Why do we need a double class? :grimacing:

2022-09-07 11:15 UTC, rfr-odoo approved these changes

2022-09-14 12:47 UTC, rdeodoo approved these changes
@robodoo r+

Tested on chrome and smartphone. Tried a dozen of use cases are didn't find anything wrong.

Thank you for the fix and time you spent on it. I know testing those use cases is probably one the hardest test you could have to do, as the use cases are basically infinite.

There might be unseen issues but the main use cases are at least all working. Given the nature of the fix, the time it took and the fact that right now it simply crashed if you enable the cookies bar without this PR, I'll merge it.
If something were to be found, it will be fixed later. But given state of things right now, this is a very nice step.

Note that there is 2 changes following this PR:
- The scrollbar of a scrollable popup without backdrop will be inside the popup itself. It is not critical or blocking. It is a bit less nice but it comes with the benefits of not having 2 scrollable scroll bar on top of each other. Also, in mobile, that's a non issue as the scrollbar is barely visible.
- A scrollable popup will now have a different behavior regarding its top and bottom margin against the screen edge. Its not better or worst, just different than what we had and what bootstrap does. It could be restored later if really needed but it is ok like that.
Before: Popup had margin top and no margin bottom, and when you scroll down and hit the bottom, the margin bottom reveal and the popup is against the top screen edge.
Now: The top and bottom margin are always shown, the scroll only impact the popup itself.

[I created a task](https://www.odoo.com/web#menu_id=4720&cids=1&action=4043&model=project.task&view_type=form&id=2983901) to introduce a testing suite some day about it. In the meantime, it will serve as a checklist for when we have to retest everything. That will also maybe allow India testing to be involved.

Here is part of the task:
```
Create a testing suite that simulate the best it can a real user scroll.
There is dozen and dozen of cases which results of a mix of the following list, which is not exhaustive:
- Having a page with or without a scrollbar (eg home has no scrollbar while contactus has a scrollbar)
- All 3 layout modes of cookies bar
- With or without the backdrop enable
- With a cookies bar scrollable or not (eg only one block = no scroll, multiple block = scroll)
- Same but with popup snippet -> Scrollable or not and with or without backdrop
- Combination of Cookies bar + popup underneath, the first one should be scrollable (or not depending the use case), but when close the second one should be adapted, and when close too the page should be adapted.
- Both mobile and desktop !!!! Real smartphone differ from chrome debugger phone preview !!!
```

2022-09-14 13:00 UTC, robodoo commented
@adr-odoo @rdeodoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2022-09-14 13:05 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-09-14 20:19 UTC, closed without merging