[FIX] purchase: auto-complete apply the correct currency rate
odoo/odoo pull request #99640
Opened 2022-09-06 13:09 UTC by HANNICHE-Walid

Steps to reproduce:
- enable multi currency in settings
- set different rates for multiple days
- create a vendor bill in a different currency
- create a second vendor bill
- fill the second bill using auto complete from the first one

Bug:
the correct currency rate isn't applied unless date is changed when
the source is a vendor bill not a purchase order

Fix:
update currency after adding a line via auto-complete for vendor bills

opw-2890210

2022-09-07 14:06 UTC, agr-odoo requested changes
The same behavior occurs even without `purchase` app installed, this patch would not fix every case.
We need to call the onchange right after the currency is set in the `_onchange_invoice_vendor_bill` call (`account` module)

2022-09-08 14:33 UTC, HANNICHE-Walid commented
@agr-odoo  done thanks :)

2022-09-08 15:25 UTC, agr-odoo approved these changes

2022-09-09 12:47 UTC, agr-odoo commented
robodoo r+

2022-09-09 13:38 UTC, closed without merging