[IMP] hr_contract: include cancelled contracts in contract history
odoo/odoo pull request #99767
Opened 2022-09-07 15:18 UTC by robcoekaerts

In order to avoid empty contract histories when there are existing but cancelled contracts, cancelled contracts are now also included in the contract history.

task-2939158

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-07 15:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99767).

2022-09-14 11:46 UTC, kba-odoo requested changes

2022-09-14 11:46 UTC, kba-odoo commented on addons/hr_contract/report/hr_contract_history.py
> +                            WHEN contract.state = 'cancelled' THEN 3
```suggestion
                            WHEN contract.state = 'cancel' THEN 3
```

2022-09-14 11:53 UTC, kba-odoo commented
robodoo r+

2022-09-14 17:13 UTC, closed without merging