[FIX] website_hr_recruitment: fix job apply page colors
odoo/odoo pull request #99976
Opened 2022-09-10 07:38 UTC by Bertrand2

On the application page, too much elements are set in the primary color, creating confusion as of where is located the main page action.

2022-09-10 07:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99976).

2022-09-13 12:27 UTC, rdeodoo requested changes
Just passing by, got curious due to the code owner ping.

Thought I would drop some nitpicking remarks:
- It's an `IMP` not a `FIX`
- `task-2980889`, not `taskID 2980889`, as per guidelines. Otherwise the task id will redirect to a commit hash starting with the same number.

2022-09-14 10:55 UTC, phwa-odoo commented
Missing the task ID in the PR message as well as the change related to partner_mobile both in the commit and PR message

2022-09-16 09:37 UTC, kba-odoo commented
robodoo r+

2022-09-16 13:29 UTC, closed without merging