[REM] payment: remove useless refund parameter
odoo/odoo pull request #99998
Opened 2022-09-12 09:42 UTC by vava-odoo

The param `create_refund_transaction` from `_send_refund_request` became useless following this PR (https://github.com/odoo/odoo/pull/92279). It was only used for Authorize.net, which now works without calling this param.

task-2869910

2022-09-12 09:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99998).

2022-09-14 15:11 UTC, Demesmaeker reviewed
:duck:

2022-09-15 08:20 UTC, Demesmaeker approved these changes

2022-09-16 14:50 UTC, AntoineVDV requested changes
In your PRs, prefer mentioning commits rather than PRs because it will log a message on the mentioned PR each time your push your commits. That can be quite annoying on open PRs. Fortunately, the PR mentioned here has been closed for a while.

Also, you commit title should ideally mention (or give a hint of) the modules it impacts. Here, `[CLN] payment(_*): remove useless refund parameter` should do. Eventually, you can add the line `*: adyen, authorize,`... in your commit message's body.
Note that I swapped the tag for [CLN] (clean) because [REM] is usually used for feature removals.

2022-09-16 14:50 UTC, AntoineVDV commented on addons/payment/models/payment_transaction.py
>          :return: The refund transaction if any
```suggestion
        :return: The refund transaction created to process the refund request.
```

2022-09-16 14:50 UTC, AntoineVDV commented on addons/payment_adyen/models/payment_transaction.py
>          :return: The refund transaction if any
Same as above, and for other providers too.

2022-09-26 08:04 UTC, AntoineVDV approved these changes
@robodoo r+

2022-09-26 10:32 UTC, closed without merging