[FIX] web: `FormView`, inner_group title style
odoo/odoo pull request #99992
Opened 2022-09-12 08:57 UTC by Brieuc-brd

Prior to this commit, the `inner_group` title was not wrapped in a <tr/>
like every other <td/> and the correct padding to create space between
other `inner_group` didn't apply.

This commit fixes this issue.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-12 08:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/odoo/pull/99992).

2022-09-14 08:47 UTC, Brieuc-brd commented
@stefanorigano little reminder :)

2022-09-14 09:00 UTC, stefanorigano requested changes
Margin is still tiny compared to legacy.. also, I don't think we want margins on mobile

![image](https://user-images.githubusercontent.com/8558351/190110230-6a6b37bf-f9ed-4d1d-9739-96910cbb7a25.png)

Thanks!

2022-09-14 10:33 UTC, stefanorigano approved these changes
LGTM 👍 
Thanks @Brieuc-brd 

@odoo/rd-framework-js , ready for tech. review, thanks

2022-09-30 11:21 UTC, Brieuc-brd commented
Since the merge of https://github.com/odoo/odoo/pull/98911, this PR is no longer necessary.

2022-09-30 11:21 UTC, closed without merging